### PR TITLE
dtc package update xz to gz

### PR DESCRIPTION
**Pull request by bambam82**
-PKG_URL="https://git.kernel.org/cgit/utils/dtc/dtc.git/snapshot/$PKG_VERSION.tar.xz"
+PKG_URL="https://git.kernel.org/cgit/utils/dtc/dtc.git/snapshot/$PKG_VERSION.tar.gz"

gz is used instead of xz

### CODE REVIEW

**Comment by MilhouseVH** [comment]
It already is gz. Your repo is out of date, and you're pushing the wrong commits. Please sort your repo out.

**Comment by MilhouseVH** [comment]
Do you even mean to be pushing to LibreELEC/LibreELEC.tv?

It seems you should be pushing your changes to xhbl/LibreELEC_dualaudio.

**Comment by vpeter4** [comment]
@MilhouseVH: stuff is already at that repo. I think he would like to push it here.

Not sure what relationship is between dtc and dualaudio?

**Comment by MilhouseVH** [comment]
We don't need these changes, as they've already been applied here months ago - it's the downstream https://github.com/xhbl/LibreELEC_dualaudio fork that is out of date and needs updating.

**Pull request closed without merging**
