### PR TITLE
backup: fix up messages

### PR DESCRIPTION
**Pull request by MilhouseVH**
Mainly cosmetic improvements of the messages we show during backup and reset.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
The backup-restore script (and possibly hard reset) could benefit from the spinners we use in init and fs-resize, just not sure it's worthwhile? If anyone thinks it is I can look at it tomorrow.

**Comment by MilhouseVH** [comment]
Updated with spinners at @chewitt's request. Untested, will do that later today.

**Comment by lrusak** [comment]
Thanks for taking this on

**Comment by MilhouseVH** [comment]
Made a few tweaks to sync deletes and writes during spinner.

Tested on NUC - the new `run` mode came in _really_ handy!

Factory reset (soft & hard) and backup/restore working perfectly.

**Pull request merged**
