### PR TITLE
Net-snmp addon : Avoid loading config two time

### PR DESCRIPTION
**Pull request by Celedhrim**
this fix this https://sourceforge.net/p/net-snmp/mailman/message/21333882/

### CODE REVIEW

**Comment by Celedhrim** [comment]
Maybe just an include in the config file $ADDON_HOME/share/snmp/snmpd.conf is good ?

I personnaly think it's better to "see" config file in launch option.
https://serverfault.com/a/605690

and with this you don't includ bug with snmpd-old.conf during test ^^
Global loading is really not the best solution in my opinion

**Comment by Celedhrim** [comment]
@omonar did you config user using addon ?

I'm currently work on improve addon configuration and it seems that current user creation is not well done

addon exec that  
`system("net-snmp-config --create-snmpv3-user -a {0} {1}".format(snmppassword,snmpuser))`

but this should be the good way for me 
`system("net-snmp-config --create-snmpv3-user -a MD5 -A {0} {1}".format(snmppassword,snmpuser))`

this is help: 
```
  net-snmp-create-v3-user [-ro] [-A authpass] [-X privpass]
                          [-a MD5|SHA] [-x DES|AES] [username]
```

**Comment by omonar** [comment]
Sorry for my late reaction. I was not aware of the comment to my comment ;)

My point is that one really needs to read BOTH configuration files, that is, $ADDON_HOME/share/snmp/snmpd.conf and $ADDON_HOME/snmpd.conf. The first one includes "normal" configuration data that users may edit and change. The other one, that is, $ADDON_HOME/snmpd.conf, is used by snmpd agent to store persistent data that need to be kept between reboots. These are, for example, engineID and usmUser structure.

The command "net-snmp-config --create-snmpv3-user" saves createUser command to $ADDON_HOME/snmpd.conf which is OK. But since this file is not included into snmpd configuration (due to -C flag) it is never read, snmpv3 simply does not work (usmUser structure is not created and saved into config file).

As for the possible solution, one should test it. We could make include in the config file $ADDON_HOME/share/snmp/snmpd.conf. Or, we could add one more file to -c flag, that is,

ADDON_DIR/bin/snmpd -f -LS0-6d -C -c $ADDON_HOME/share/snmp/snmpd.conf,$ADDON_HOME/snmpd.conf -M $ADDON_DIR/share/snmp/mibs -p /var/run/snmpd.pid

To answer your second question, I have not used addon config. It is too simple for me ;) I put my own createUser line into $ADDON_HOME/snmpd.conf. I did it because I needed SHA and AES with separate phrases. Note that SHA, DES, and AES are available because snmpd is compiled with openssl. Addon config defaults to MD5. But you could be right, there is probably a bug in addon config.

**Comment by Celedhrim** [comment]
@omonar, this pr should fix it https://github.com/LibreELEC/LibreELEC.tv/pull/2280
now include $ADDON_HOME/snmpd.conf if v3 is set

**Pull request merged**
