### PR TITLE
Enable -fPIC for some packages

### PR DESCRIPTION
**Pull request by lrusak**
I needed this when building without lto support. I don't think it should harm anything but would be work including in a @MilhouseVH build

### CODE REVIEW

**Comment by lrusak** [comment]
at this point it might be worth adding `-fPIC` to the global `CFLAGS` and adding a `strip_fpic` options like we have for lto and gold

@stefansaraev is there any downside to building all packages with `-fPIC`?

**Comment by stefansaraev** [comment]
@lrusak none. on (at least) x86_64 architecture, code that is compiled into static library is required to be position-independent if it will be used in a shared library. 

so, all packages that are built with --enable-static --disable-shared (static only) should have --with-pic (or -fPIC in C/CXXFLAGS).

**Comment by lrusak** [comment]
Ok well maybe this is the way to go then instead of adding `-fPIC` to the global `CFLAGS`

**Comment by lrusak** [comment]
please merge

**Pull request merged**
