### PR TITLE
llvm: update to llvm-9.0.0 / updated PKG_URL

### PR DESCRIPTION
**Pull request by 5schatten**
https://releases.llvm.org/9.0.0/docs/ReleaseNotes.html

### CODE REVIEW

**Comment by MilhouseVH** [comment]
```
MISSING        Delta: -26,695,088  #0922: n/a           #0921b: 26,695,088   /usr/lib/libLLVM-8.so
NEW FILE       Delta: 31,495,632   #0922: 31,495,632    #0921b: n/a          /usr/lib/libLLVM-9.so
```

5MB increase... :(

**Comment by lrusak** [comment]
I’d check the cmake build options for new or changed options as that change size seems way too big

**Comment by MilhouseVH** [comment]
image comparison: http://ix.io/1WvD

`#0922`: last night's test build (`llvm-8.0.1`, `pulseaudio-12.2`)
`#0923b`: new test build (`llvm-9.0`, `pulseaudio-13.0`)

**Comment by 5schatten** [comment]
I compared both CMakeLists for 9.0 & 8.0 and found this option `LLVM_ENABLE_UNWIND_TABLES` which is new. 

```
LLVM_ENABLE_UNWIND_TABLES:BOOL
Enable unwind tables in the binary. Disabling unwind tables can reduce the size of the libraries. Defaults to ON.
```

Also there is a new RISChttps://raw.githubusercontent.com/llvm/llvm-project/release/8.x/llvm/CMakeLists.txtV target but we only build AMDGPU so this should not matter.

https://raw.githubusercontent.com/llvm/llvm-project/release/9.x/llvm/CMakeLists.txt
https://raw.githubusercontent.com/llvm/llvm-project/release/8.x/llvm/CMakeLists.txt

**Comment by MilhouseVH** [comment]
Adding `-DLLVM_ENABLE_UNWIND_TABLES=OFF` (http://ix.io/1Xbx) seems to get us more-or-less back to where we were with llvm-8.x.

With default `LLVM_ENABLE_UNWIND_TABLES` (ie. `ON`):
```
MISSING        Delta: -26,695,088  #0922: n/a           #0921b: 26,695,088   /usr/lib/libLLVM-8.so
NEW FILE       Delta: 31,495,632   #0922: 31,495,632    #0921b: n/a          /usr/lib/libLLVM-9.so
```
With `-DLLVM_ENABLE_UNWIND_TABLES=OFF`:
```
MISSING        Delta: -26,695,088  #0927: n/a           #0921b: 26,695,088   /usr/lib/libLLVM-8.so
NEW FILE       Delta: 28,091,856   #0927: 28,091,856    #0921b: n/a          /usr/lib/libLLVM-9.so
```
So a 1.3MB increase with llvm-9.0, which seems more reasonable.

**Pull request merged**
