### PR TITLE
C2/Hub/Play2: Simplify passthrough audio

### PR DESCRIPTION
**Pull request by Kwiboo**
This PR bumps linux-amlogic to remove sysfs requirement for passthrough audio and removes all amcodec workarounds in Kodi's alsa sink.
It also enables 32khz audio streams and replaces the surround71 alsa device with a hdmi device.

Kodi will now list two audio output devices (Default and HDMI), default will be used for LPCM regardless of the chosen output device and HDMI is the only device allowed for passthrough.

### CODE REVIEW

**Comment by lrusak** [comment]
Thanks! I'll have a test later and see how it goes

**Comment by chewitt** [comment]
@Kwiboo can you rebase the linux-amlogic githash as I merged something else there, sorry :)

**Comment by wrxtasy** [comment]
Q. @kwiboo or @codesnake 

Why have we got different Kernel configs -  CONFIG_SND_AML_SPLIT going on between two S905 projects now ?

Hub:
https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/WeTek_Hub/linux/linux.aarch64.conf#L2668

Play_2:
https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/WeTek_Play_2/linux/linux.aarch64.conf#L2653

Which is the correct one ?

**Comment by codesnake** [comment]
@wrxtasy I don't know how that happened, most likely by accident. Last time I tried it didn't make any difference whether CONFIG_SND_AML_SPLIT was enabled or not. BTW Amlogic has it enabled in their default config: https://github.com/LibreELEC/linux-amlogic/blob/amlogic-3.14.y/arch/arm64/configs/meson64_defconfig#L404

**Comment by Kwiboo** [comment]
@chewitt I will rebase later tonight and will possibly also make an update to the Kodi patch
Playing 8ch LPCM and having HDMI as output device did not fallback to default when doing a quick test this morning
Will update PR once I have completed more extensive speaker tests on both C2 and Hub

**Comment by stefansaraev** [comment]
hum. it seems that now, after this PR (or a recent change in LE aml kernel) packages/mediacenter/kodi/patches/aarch64/kodi-0001-aml-Fill-audio-packets-completely-when-resampling-to.patch is not needed anymore. 

cc @codesnake can you check ?

**Comment by codesnake** [comment]
@stefansaraev As far as I remember that patch is needed only for some audio tracks, so maybe you didn't notice any problems without it at first. The patch was created long ago and for kernel 3.10, so maybe things changed since then.

**Comment by stefansaraev** [comment]
@codesnake 
it was easy to reproduce at the time I received my wetek play 2. and it has always been an issue with wetek play / core. I am sure I always had noisy sound whtn playing anything from my music library, and (most) tv channels. do you have a sample?

**Comment by codesnake** [comment]
@stefansaraev I have it somewhere, need to find it first.

**Comment by codesnake** [comment]
@stefansaraev Hmmm, I cannot find any sample to reproduce the issue.

**Comment by Kwiboo** [comment]
PR has now been updated to point to latest kernel gitsha but will need a new update once a channel mapping update is merged.
Kodi patch was changed to force `default` device for LPCM to fix 8ch LPCM issue when HDMI device was selected as the output device.
`CONFIG_SND_AML_SPLIT` is now enabled for Play2 same as other S905 projects, using split mode enables use of a simple `memcpy` for writing audio data to hw.

A channel mapping fixup patch was added to fix a center/lfe mixup when using LPCM, this will be sent to linux-amlogic once confirmed working correctly with mpv.

@codesnake @stefansaraev should we remove the fill sample completely patch in this PR?

**Comment by LongChair** [comment]
Works fine with mpv :)

**Comment by LongChair** [comment]
we also probably want to bump kernel in this one once https://github.com/LibreELEC/linux-amlogic/pull/17 has been merged

**Comment by Kwiboo** [comment]
Updated once more to use the linux-amlogic gitsha that contains the channel mapping fix

**Comment by stefansaraev** [comment]
@Kwiboo best keep it for now. it does not harm. can be removed at any time later

**Pull request merged**
