### PR TITLE
buildsystem: use /usr/bin/python3 in scripts

### PR DESCRIPTION
**Pull request by MilhouseVH**
Distributions (eg. Ubuntu 19.10) no longer ship with Python2 as standard, and no longer include the `/usr/bin/python` sym link, therefore our python-based scripts fail (until such time as `python2` is installed, which then installs the `python` sym link). Since `python2` is effectively dead, require `python3` in our scripts.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
#### scripts/checkdeps:

On a system without `gcc`, running `scripts/checkdeps` results in the following message:
```
neil@ermine:~/projects/LibreELEC.tv$ scripts/checkdeps
***** Please install gcc *****
```

Yet `scripts/checkdeps` is intended to install `gcc` when it is required. But it can't.

The problem is that sourcing `config/options` includes [this check](https://github.com/LibreELEC/LibreELEC.tv/blob/27a56739afd8ca77928df5c3fcbc5a08584a36f0/config/options#L66):
```
# Need to point to your actual cc
# If you have ccache installed, take care that LOCAL_CC does not point to it
[ -z "${LOCAL_CC}" ] && export LOCAL_CC="$(command -v gcc)"

if [ -z "${LOCAL_CC}" ]; then
  die "***** Please install gcc *****" "127"
fi
```

Since it doesn't look like we need to source `config/options`, remove it. Problem solved.

While I'm at it, improve the error message informing the user to run `scripts/checkdeps`.

**Comment by MilhouseVH** [comment]
#### scripts/checkdeps 2:

I've added `make`, as Ubuntu 19.10 (server) does not include it by default.

I've no idea what package is required to install `make` on other non-Debian/Ubuntu distros.

**Comment by MilhouseVH** [comment]
Just for documentation purposes:

images for RPi, RPi2, Generic, Allwinner (A64, H3, H6) all build successfully without any version of Python2 installed, anywhere.

I have not tested Amlogic, Rockchip, NXP or Qualcomm builds.

Apart from `libretro-mame2015`, all RPi2 addons either built successfully, or failed for non-Python related reasons.

`libretro-mame2015` has a hard dependency on `python2` which needs to be addressed up stream (or via a temporary patch): http://ix.io/217K - `Python3:host` should also be added to `PKG_DEPENDS_TARGET`:
```
mkdir -p obj/osd/retro
/home/neil/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabi-g++ -DCRLF=2 -DDISABLE_MIDI=1 -DNDEBUG -DFLAC__NO_DLL -DLUA_COMPAT_APIINTCASTS -DOSD_RETRO -DNO_USE_MIDI -march=armv7ve -mtune=cortex-a7 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=neon-vfpv4 -fomit-frame-pointer -Wall -pipe  -O2 -DDISABLE_MIDI -fno-delete-null-pointer-checks -D__LIBRETRO__ -DGIT_VERSION=\"d43c94f\" -fPIC -fsigned-char -finline  -fno-common -fno-builtin -falign-functions=16 -mstructure-size-boundary=32 -DALIGN_INTS -DALIGN_SHORTS -fstrict-aliasing -DSDLMAME_NO64BITIO -DSDLMAME_ARM -DRETRO_SETJMP_HACK -DARM -fno-merge-constants -pipe -O3 -fno-strict-aliasing  -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -fweb -frename-registers -I./src/mame/layout -Isrc/mame -Isrc/mame/layout -Isrc/emu -Iobj/emu -Isrc/emu/layout -Isrc/lib/util -Isrc/lib -I3rdparty -Isrc/osd -Isrc/osd/retro -Isrc/osd/retro/libretro-common/include -I3rdparty/expat/lib -I3rdparty/zlib -Isrc/lib/util -I3rdparty/libflac/src/libFLAC/include -I3rdparty/libjpeg -Isrc/osd/retro/libretro-common/include -fpermissive -DWANT_MAME -x c++ -std=gnu++98 -Woverloaded-virtual -c src/mame/mame.c -o obj/mame/mame.o
/home/neil/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabi-g++ -DCRLF=2 -DDISABLE_MIDI=1 -DNDEBUG -DFLAC__NO_DLL -DLUA_COMPAT_APIINTCASTS -DOSD_RETRO -DNO_USE_MIDI -march=armv7ve -mtune=cortex-a7 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=neon-vfpv4 -fomit-frame-pointer -Wall -pipe  -O2 -DDISABLE_MIDI -fno-delete-null-pointer-checks -D__LIBRETRO__ -DGIT_VERSION=\"d43c94f\" -fPIC -fsigned-char -finline  -fno-common -fno-builtin -falign-functions=16 -mstructure-size-boundary=32 -DALIGN_INTS -DALIGN_SHORTS -fstrict-aliasing -DSDLMAME_NO64BITIO -DSDLMAME_ARM -DRETRO_SETJMP_HACK -DARM -fno-merge-constants -pipe -O3 -fno-strict-aliasing  -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -fweb -frename-registers -I./src/mame/layout -Isrc/mame -Isrc/mame/layout -Isrc/emu -Iobj/emu -Isrc/emu/layout -Isrc/lib/util -Isrc/lib -I3rdparty -Isrc/osd -Isrc/osd/retro -Isrc/osd/retro/libretro-common/include -I3rdparty/expat/lib -I3rdparty/zlib -Isrc/lib/util -I3rdparty/libflac/src/libFLAC/include -I3rdparty/libjpeg -Isrc/osd/retro/libretro-common/include -fpermissive -DWANT_MAME -x c++ -std=gnu++98 -Woverloaded-virtual -c src/mame/drivers/ertictac.c -o obj/mame/drivers/ertictac.o
Building driver list src/mame/mame.lst...
/home/neil/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabi-g++ -DCRLF=2 -DDISABLE_MIDI=1 -DNDEBUG -DFLAC__NO_DLL -DLUA_COMPAT_APIINTCASTS -DOSD_RETRO -DNO_USE_MIDI -march=armv7ve -mtune=cortex-a7 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=neon-vfpv4 -fomit-frame-pointer -Wall -pipe  -O2 -DDISABLE_MIDI -fno-delete-null-pointer-checks -D__LIBRETRO__ -DGIT_VERSION=\"d43c94f\" -fPIC -fsigned-char -finline  -fno-common -fno-builtin -falign-functions=16 -mstructure-size-boundary=32 -DALIGN_INTS -DALIGN_SHORTS -fstrict-aliasing -DSDLMAME_NO64BITIO -DSDLMAME_ARM -DRETRO_SETJMP_HACK -DARM -fno-merge-constants -pipe -O3 -fno-strict-aliasing  -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -fweb -frename-registers -I./src/mame/layout -Isrc/mame -Isrc/mame/layout -Isrc/emu -Iobj/emu -Isrc/emu/layout -Isrc/lib/util -Isrc/lib -I3rdparty -Isrc/osd -Isrc/osd/retro -Isrc/osd/retro/libretro-common/include -I3rdparty/expat/lib -I3rdparty/zlib -Isrc/lib/util -I3rdparty/libflac/src/libFLAC/include -I3rdparty/libjpeg -Isrc/osd/retro/libretro-common/include -fpermissive -DWANT_MAME -x c++ -std=gnu++98 -Woverloaded-virtual -c src/mame/drivers/ssfindo.c -o obj/mame/drivers/ssfindo.o
/bin/sh: 1: python2: not found
make: *** [Makefile:939: obj/mame/mame/drivlist.c] Error 127
make: *** Waiting for unfinished jobs....
```

**Comment by Kwiboo** [comment]
Rockchip mainline RK3288 and RK3399 seems to build using this PR inside a `eoan` docker container.
RK3328 fails on u-boot, I will try to find a workaround.

The following Dockerfile was used:
```
FROM ubuntu:eoan

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get install -y locales sudo \
 && rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8 \
 && update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

RUN adduser --disabled-password --gecos '' docker \
 && adduser docker sudo \
 && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN apt-get update && apt-get install -y \
    wget bash bc gcc sed patch patchutils tar bzip2 gzip perl gawk gperf zip unzip diffutils lzop make \
    g++ xfonts-utils xfonts-utils xfonts-utils xsltproc default-jre-headless python3 \
    libc6-dev libncurses5-dev \
    libjson-perl libxml-parser-perl \
    golang-go \
    xz-utils file \
    git openssh-client \
    --no-install-recommends \
 && rm -rf /var/lib/apt/lists/*

USER docker
```

`xz-utils` and `file` is probably missing from `scripts/checkdeps`, I had to add `xz-utils` for LE to build and I kept `file` since we have it in the `tools/docker` Dockerfiles.

**Comment by Kwiboo** [comment]
I found a workaround for RK3328, using `UBOOT_TARGET="u-boot-dtb.bin"` in the device `options`-file (I have not done any runtime test of these images).

**Comment by MilhouseVH** [comment]
Yeah, `xz-utils` should be added to `scripts/checkdeps` - it's pretty much in the same boat as `bzip2` and `gzip` as we need to have the decompresser installed prior to building the toolchain in order to uncompress the `xz` tarballs as it's highly likely that a dependency of `xz-utils` will be using `xz` compression, making it impossible to build `xz-utils` from scratch (chicken, egg, etc.).

I've added `xz-utils` and also `file` to `scripts/checkdeps`. As before, I've no idea if these packages are named differently in other non-Debian distros - if anyone knows please shout otherwise it can be fixed as and when...

The existing `bionic`/`stretch`/`xenial` Dockerfiles already include `xz-utils` and `file` (and also `make`). The inclusion of `u-boot-tools` and `python` is now redundant as we build `u-boot-tools`, and we no longer need/want to install `python2`.

I agree that `texinfo` is also not required, and I've dropped this from the existing docker files.

I've added a new `eoan` Dockerfile that hopefully works (clone of `xenial`).

**Pull request merged**
