### PR TITLE
screenshots for addons

### PR DESCRIPTION
**Pull request by CvH**
please feel free to comment about the screenshots (I will add few more before merge)

### CODE REVIEW

**Comment by zag2me** [comment]
Are png screenshots allowed?

**Comment by vpeter4** [comment]
You see in first commit that png's are used and jpg's in second.

**Comment by zag2me** [comment]
Thanks, I just remember some team discussion a while ago about only using jpeg. I couldn't remember what the result was though.

I've always stuck to jpg myself.

**Comment by CvH** [comment]
@zag2me our addons are working according to the new standard, just drop screenshot-01.jpg/png into the resources folder of the addon, done. To choose png/jpg is depending what images are shown (png compress differently to jpeg) - to optimize the png with pngquant/optipng/... is mandatory to save 20-40% filezize without quality loss.

**Comment by lrusak** [comment]
I think we should limit it to max 3 screenshots per add-on

**Comment by CvH** [comment]
@lrusak size wise this makes no sense (3png could be pretty small, 3jpg could get pretty big), maybe better limit it to X-kb per addon
min 3 screens - max 6 with an total size of max 600kb (or something)

**Pull request closed without merging**
