### PR TITLE
linux (Generic): update to linux-5.7

### PR DESCRIPTION
**Pull request by MilhouseVH**
~@chewitt I have added a temporary workaround for `wireguard-linux-compat` as this no longer builds with 5.7-rc1, and doesn't seem to be required.~

Current versions of `crazycat` and `dvb-latest` both fail to build, and have been disabled.

----

#### Test build posts
| Kernel | Generic | Announce |
| :--- | :---: | :----: |
| 5.7-rc1 | [`#0413x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2940445#pid2940445) | [Link](https://lkml.org/lkml/2020/4/12/203) |
| 5.7-rc2 | [`#0419x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2942397#pid2942397) | [Link](https://lkml.org/lkml/2020/4/19/410) |
| 5.7-rc3 | [`#0426x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2944635#pid2944635) | [Link](https://lkml.org/lkml/2020/4/26/518) |
| 5.7-rc4 | N/A | [Link](https://lkml.org/lkml/2020/5/3/306) |
| 5.7-rc5 | [`#0511x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2948811#pid2948811) | [Link](https://lkml.org/lkml/2020/5/10/389) |
| 5.7-rc6 | [`#0519x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2950868#pid2950868) | [Link](https://lkml.org/lkml/2020/5/17/314) |
| 5.7-rc7 | [`#0527x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2952990#pid2952990) | [Link](https://lkml.org/lkml/2020/5/24/407) |
| 5.7.0 | [`#0601x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2954351#pid2954351) | [Link](https://lkml.org/lkml/2020/5/31/326) |

### CODE REVIEW

**Comment by antonlacon** [comment]
5.7 should allow removing the fuse exfat driver and replacing with the in kernel one. Thoughts?

**Comment by MilhouseVH** [comment]
@antonlacon probably best in a separate PR once 5.7.0 is merged?

**Comment by chewitt** [comment]
best to handle it separately - wireguard needs similar cleanup

**Comment by MilhouseVH** [comment]
https://github.com/LibreELEC/iwlwifi-firmware/pull/27

**Comment by CvH** [comment]
tx, merged

**Pull request merged**
