### PR TITLE
docker: updated to 19.03.2 / bumped dependencies

### PR DESCRIPTION
**Pull request by 5schatten**
Release notes:
- https://github.com/docker/docker-ce/releases/tag/v19.03.2
- https://docs.docker.com/engine/release-notes/#19032

Package dependencies
- docker: updated to 19.03.2 / updated storage location patch
- containerd: updated to v1.2.8 / fixed displayed git commit
- go: updated to v1.12.9
- libnetwork: updated to git fc5a7d9
- runc: fixed displayed git commit

@TheChuckster 
Have a look at it

### CODE REVIEW

**Comment by TheChuckster** [comment]
Were you able to test? If not, I can help out again this weekend.

**Comment by 5schatten** [comment]
I tested `19.03.1` which worked fine beside the missing/wrong version information which needed some adjustments. When `19.03.2` was released I had cleaned my buildroot minutes before so I haven't tested it yet. But I guess it should work fine too since it's just a maintenance release.

**Comment by 5schatten** [comment]
Well... surprisingly a Docker release did _not_ build... :roll_eyes: and needed a fix.

@TheChuckster docker 19.03.2 addon - tested with my PCSX2 image
http://5schatten.libreelec.tv/addons/Docker/service.system.docker-9.80.1.128.zip

**Comment by 5schatten** [comment]
Updated package versioning/name scheme
http://5schatten.libreelec.tv/addons/Docker/service.system.docker-19.03.2.1.zip

**Comment by zsolooo** [comment]
@5schatten I experience an issue with this addon release with rpi2 nightly build (rolling back addon version to 9.80.1.127 works).
The issue: containerd dies with a segmentation fault when trying to start it. If I can get some quick pointer on how to build the addon (not yet familiar with the libreelec build scripts), then I could experiment with it maybe in the weekend, there's also a 19.03.3 release.

**Pull request merged**
