### PR TITLE
Kodi: Force build libsse4

### PR DESCRIPTION
**Pull request by ozolli**
When compiling kodi only the libsse4 library is only built when on sse4.1 compatible machine.
It makes sense when building on target computer so I feel a PR upstream is not wise.

As we cross compile LE it would be good to force build this lib when the build machine does not have a sse4.1 cpu or it won't be available on compatible targets, thus this kodi patch.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Kodi has a `CMAKE_CROSSCOMPILING` property (in master, not sure about Krypton), would the following work and make it suitable for upstream?
```
if(HAVE_SSE4_1 OR CMAKE_CROSSCOMPILING)
```

**Comment by ozolli** [comment]
@MilhouseVH
CMAKE_CROSSCOMPILING is not recognized : 
```
CMake Error at /home/olivier/ozLE/build.LibreELEC-Generic.x86_64-ozolli/kodi-5c40b5c/xbmc/linux/sse4/CMakeLists.txt:1 (if):
  if given arguments:

    "HAVE_SSE4_1" "or" "CMAKE_CROSSCOMPILING"

  Unknown arguments specified

```
Trying to find how to make this work.

**Comment by stefansaraev** [comment]
add -D_SSE41_TRUE=ON _SSE41_OK=ON to PKG_CMAKE_OPTS_TARGET

**Comment by ozolli** [comment]
@stefansaraev 
Doesn't seem to work:
```
-- Found SSE: 1
-- Found SSE2: 1
-- Could not find hardware support for SSE3 (missing:  _SSE3_TRUE)
-- Could not find hardware support for SSSE3 (missing:  _SSSE3_TRUE)
-- Could not find hardware support for SSE4.1 (missing:  _SSE41_TRUE)
-- Could not find hardware support for SSE4.2 (missing:  _SSE42_TRUE)
```
Isn't it because of https://github.com/xbmc/xbmc/blob/master/cmake/modules/FindSSE.cmake ?

**Comment by stefansaraev** [comment]
works for me http://sprunge.us/gNLY :)

**Comment by lrusak** [comment]
Sorry, but as this patch wouldn't be accepted into upstream kodi we won't accept it either.

We need to find a solution that can be sent upstream.

Thanks for the PR.

**Pull request closed without merging**
