### PR TITLE
kodi: update amltiming patch

### PR DESCRIPTION
**Pull request by Raybuntu**
Update to @peak3d's recent amltiming patch. Fixes various videos that did not start.

### CODE REVIEW

**Comment by lrusak** [comment]
is this going upstream at all?

**Comment by Raybuntu** [comment]
as far as I know @peak3d plans a PR and he wants to support this backport.

**Comment by lrusak** [comment]
The problem is that Team Kodi has an issue with us shipping with code that hasn't been sent upstream. It would be nice if we could reference an upstream PR even if it's WIP

**Comment by Raybuntu** [comment]
Afaik there is none yet. It's just an updated version of that patch. If it's really an issue I suggest removing the patch and ship a broken LE8 Krypton for Amlogic.

**Comment by Raybuntu** [comment]
I'm closing this. Obviously Team Kodi is against it.

**Comment by kszaq** [comment]
If we said A by merging the previous version of the timing patch we should also say B and merge these updates. Or delete the timing patch altogether and ship broken decoder.

**Comment by lrusak** [comment]
Show me an upstream PR and we can talk about it.

If amlogic is broken then we can just hold back the release and wait for 17.1 which hopefully has fixes in it.

**Comment by kszaq** [comment]
@peak3d Do you think you can PR your patches to Krypton?

**Comment by Raybuntu** [comment]
The Fix is not going to be in Krypton at all. Not in 17 or 17.1. Just remove the whole patch.

**Comment by lrusak** [comment]
The PR doesn't have to be for krypton, it can be for master.

@Raybuntu incase you didn't see, https://github.com/LibreELEC/LibreELEC.tv/pull/1317

**Comment by Raybuntu** [comment]
I don't care about master because the patch is removed in master because Kodi 18 will have that fix upstreamed so what for a patch?

This patch was PR'd for LE8 after @peak3d gave his ok and ensured to support it for Krypton. Now that we can't update the patch because of Kodi's Trademark threats I see no reason to keep it. Please remove it.

**Comment by lrusak** [comment]
@peak3d can we expect a PR to Kodi master anytime soon? and possibly a backport to Kodi Krypton

**Comment by peak3d** [comment]
PR is send to kodi master

**Comment by kszaq** [comment]
@Raybuntu Can you reopen this PR? It would be nice to have this in LE8 and now it can be considered as a backport.

**Pull request closed without merging**
