### PR TITLE
First look at toolchain depends

### PR DESCRIPTION
**Pull request by antonlacon**
This converts the compress/* packages and bcm2835-utils (and depend dtc) to depend primarily on gcc:host. Packages were chosen because they're generally straightforward packages without large depend graphs.

Edits what's using pigz:host, which at the moment is just the linux kernel on RPi devices using 64bit kernels and for all images in the script to create images. 

Built test for RPi5.

### CODE REVIEW

**Comment by heitbaum** [comment]
Completed a test build with Generic.

**Comment by antonlacon** [comment]
Rebased with security/* and their depends added. My first impression so far is that cpu utilization is going up, but total build time remains the same (on a machine with 16 threads) as the critical path hasn't been impacted yet.

**Comment by antonlacon** [comment]
Added systemd and samba, along with their depends, and changing autoconf:host -> autotools:host in existing commits. I'm seeing improvement in build time of around 20% on RPi5 images.

**Comment by antonlacon** [comment]
Added heitbaum's fixups.

**Review by CvH — APPROVED** [review]

**Comment by CvH** [comment]
lets have a look if something breaks :)

**Pull request merged**
