### PR TITLE
settings: bump LE settings add-on to 9.0.0

### PR DESCRIPTION
**Pull request by HiassofT**
Use updated methods of starting/stopping lircd after #1320 lirc changes

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Careful, as this will pull in the smbd/nmbd change (https://github.com/LibreELEC/service.libreelec.settings/pull/62) which has a dependency on #1469...

**Comment by HiassofT** [comment]
phew. Then how should we go with that? The LE settings changes from settings PR 63 are required for the lirc changes that are now in master.

**Comment by MilhouseVH** [comment]
Options:

1) Go full steam ahead on Samba4 with all it's niggling problems, and merge #1469.

2) Revert https://github.com/LibreELEC/service.libreelec.settings/pull/62 and rebase this PR, which buys us more time to ponder Samba4 (I can resubmit the smbd/nmbd PR if/when necessary).

I'm cool with either option. Ping @chewitt, @lrusak.

**Comment by HiassofT** [comment]
option 2 seems to be safest to me

**Comment by HiassofT** [comment]
@chewitt @lrusak could you please merge settings PR 64, then I'll update this PR with the new hash.
https://github.com/LibreELEC/service.libreelec.settings/pull/64

**Comment by MilhouseVH** [comment]
Oops sorry didn't see you'd asked chewitt/lrusak. My bad.

**Comment by HiassofT** [comment]
Updated PR with new git hash (LE settings without Samba changes)

**Pull request merged**
