### PR TITLE
projects/Amlogic: move common directories to project folder, clean up symlinks

### PR DESCRIPTION
**Pull request by kszaq**
There is no point to keep initramfs and kernel config in device folder when all devices share it.
If we introduce devices with different config, device folder can be added.

I think that even if we want to add S912 devices in the future, a common kernel config and initramfs can be used.

Ping @adamg88

### CODE REVIEW

**Comment by adamg88** [comment]
Thanks

**Comment by adamg88** [comment]
@kszaq I have been thinking on this and I'm not sure if it is appropriate, we have some specific config items for S912, one that comes to mind is this https://github.com/LibreELEC-AML/LibreELEC.tv/commit/cc18e18cefc9c7d1376ca4dc570469011eda6e06

**Comment by kszaq** [comment]
@adamg88 These options are safe to be enabled for S905 devices, I have already tried it when some time ago I wanted to create a unified S905/912 build.

**Comment by adamg88** [comment]
Ok that's great news then, I already had a PR ready for S912 but this
commit has thrown somewhat of a spanner at it, we will just have to hash
the details out later on.

**Pull request merged**
