### PR TITLE
Package updates: various minor bumps

### PR DESCRIPTION
**Pull request by MilhouseVH**
These are mostly minor package bumps (bug fixes, security etc.) that bring us up-to-date with current releases. I've avoided major updates.

The next Kodi bump (which I'd like to push soon, once things settle down on the Kodi side) breaks a lot of addons which will all need to be re-built, so merging this PR together with the future Kodi bump would be advantageous as all add-ons will need rebuilding.

I did try bumping `glibc` from 2.24 to 2.25 but the new version wouldn't link `libblkid`, so I've left that for another time/someone else. :smile:

With OpenSSH 7.5p1, `UsePrivilegeSeparation` is no longer supported, so that has required the reversion of #844.

`libmicrohttpd` 0.9.54 complains about missing flag `MHD_USE_INTERNAL_POLLING_THREAD` so that is patched into Kodi. Happy to upstream this if/when required.

@Kwiboo can you verify the `pkg-config` change - I've had to update your sysroot patch, hopefully I got it right.

With this PR I've successfully built all projects (RPi, RPi2, Generic, Odroid_C2, imx6, Wetek_*), although I've only booted RPi/RPi2/Generic.

I've built the following test addons:

Generic:
```
    vdr-addon
    tvheadend42
    moonlight
    screensaver.shadertoy
    visualization.projectm
    visualization.shadertoy
    visualization.spectrum
    visualization.waveform
```
RPi/RPi2/Odroid_C2/imx6/Wetek_*:
```
    vdr-addon
    tvheadend42 [1]
    screensaver.shadertoy
    visualization.shadertoy
    visualization.spectrum
    visualization.waveform
```

1. `tvheadend42` failed to build for Wetek_Hub and Odroid_C2: [build log](http://sprunge.us/UCcD), however `tvheadend42` also fails to build for these two projects without this PR so I don't think the failure is related.

### CODE REVIEW

**Comment by stefansaraev** [comment]
@MilhouseVH openssh 7.5p1 worked for me with --with-privsep-user=nobody. make sure /var/empty is created via tmpfiles.d or sshd.service

ref: https://github.com/stefansaraev/TB/commit/866f52791015e417598b156abc5eb96f1b70fc96

**Comment by MilhouseVH** [comment]
@stefansaraev thanks, will test that (I did check your repo to see how you'd handled it but couldn't find openssh at all - I shoulda checked the history!)

**Comment by stefansaraev** [comment]
I replaced openssh with dropbear, thats why :)

**Comment by MilhouseVH** [comment]
I know :)

**Comment by MilhouseVH** [comment]
Thanks @stefansaraev - that seems to be working just fine, new commit added (and revert dropped).

**Comment by MilhouseVH** [comment]
@Kwiboo since there has been some change in the area where the `pkg-config` patch applies, is the sysroot patch (originally from #1135) still needed? If it is, has the process started to get the change added upstream?

I'm not really sure what the sysroot patch is fixing (never had a problem without it) so I've done my build tests for this PR with the updated patch based on the assumption it is still required, however it would be really nice to drop it if possible (if not now, then in the long term).

**Comment by Kwiboo** [comment]
@MilhouseVH I will take a look, possible `Handle -isystem and -idirafter when PKG_CONFIG_SYSROOT_DIR is set. (#97337)` could have fixed the issue. Also no upstreaming process have been started.

The main reason for the patch was to make cmake set `<package>_INCLUDE_DIRS` for e.g. kodi binary addons. Possible this is not needed any more or have been fixed by cmake/gcc/addons default includes when cross-compiling.

**Comment by vpeter4** [comment]
> I did try bumping glibc from 2.24 to 2.25 but the new version wouldn't link libblkid, so I've left that for another time/someone else.

Seems the problem with glibc 2.25 bump is setting LD_LIBRARY_PATH at
https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/path#L201_L203
which has ':' separator at the end. Rewriting this code to something like
```
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$TOOLCHAIN/lib"
elif [ "$LD_LIBRARY_PATH" = "${LD_LIBRARY_PATH#$TOOLCHAIN/lib}" ]; then
  export LD_LIBRARY_PATH="$TOOLCHAIN/lib:$LD_LIBRARY_PATH"
fi
```
helps. Would be nice to get confirmation by someone else too.

**Comment by MilhouseVH** [comment]
Thanks, I'll test your rewritten version.

**Comment by vpeter4** [comment]
It didn't build whole Generic over night - now there is problem with mesa & llvm. Investigating...

**Comment by CvH** [comment]
@MilhouseVH the build failure for tvh (dvb-apps) is due the missing kernel bump for the C2/WH (this bump reverts some hacky AML patches)

**Comment by MilhouseVH** [comment]
@vpeter4 I've moved the glibc change to this branch: https://github.com/LibreELEC/LibreELEC.tv/compare/master...MilhouseVH:glibc_fix

Fixing the trailing colon allows glibc-2.25 to build, but I've hit the same mesa/llvm issue - no idea how to fix it right now.

You'll also need bumped gdb, and patches for fontconfig and libnfs, all of which are in the glibc branch.

**Comment by MilhouseVH** [comment]
@vpeter4 I've added an llvm fix (mentioned by @InuSasha from #1086) to my glibc branch, can you try it? llvm is now building a usable `llvm-config-host`, and mesa is currently building for me.

The remaining question is whether we need to mess about with LD_LIBRARY_PATH at all, or if we should just unset it every time - if/when I push the glibc changes we can have that conversation.

**Comment by vpeter4** [comment]
Building...

Isn't LD_LIBRARY_PATH needed when running some executable from our toolchain and library is not found automatically? But I see that [rpath ](https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/optimize#L33)is set.
Let's try building without this variable and we will see.

**Comment by MilhouseVH** [comment]
@vpeter4 let's continue the discussion on #1616. :)

**Comment by lrusak** [comment]
What's the status of this without the glibc bump #1616 ?

**Comment by MilhouseVH** [comment]
With or without #1616, this PR seems OK to me. I've had it (without #1616) in my test builds for the last few days, and no issues reported.

**Pull request merged**
