### PR TITLE
rng-tools: new package

### PR DESCRIPTION
**Pull request by adamg-xda**
Needed for #2254

### CODE REVIEW

**Comment by lrusak** [comment]
Please provide descriptions for you case. I appreciate your contributions but I have no idea why you need this.

**Comment by adamg-xda** [comment]
@lrusak apologies, please check PR #2254 specifically projects/S905/packages/oem/package.mk

**Comment by lrusak** [comment]
Ok but that doesn't describe _why_ you need it.

**Comment by adamg-xda** [comment]
This was a change added by @kszaq some time ago, I haven't been able to determine why he added considering the kernel has the PRNG, hopefully he can shed some light, otherwise I will drop it from the package.

**Pull request closed without merging**
