### PR TITLE
repository.kodinerds: initial package

### PR DESCRIPTION
**Pull request by CvH**
adds the repository from kodinerds.net (icon is wip)

### CODE REVIEW

**Comment by lrusak** [comment]
What do they provide?

**Comment by CvH** [comment]
```plugin.audio.prime_music
plugin.program.newscenter
plugin.program.tvhighlights
plugin.service.gto
plugin.video.amvnews
plugin.video.eurosportplayer
plugin.video.jim_panse_gamer
plugin.video.laola1tv
plugin.video.mvmix
plugin.video.rocketbeanstvlive
plugin.video.sport1de
plugin.video.spoxtv
plugin.video.stoersendertv
plugin.video.tvsendermediatheken
resource.images.addonicons.color
resource.uisounds.destiny
script.delete.files
script.loungeripper
service.fritzbox.callmonitor
service.idle.actions
service.kn.switchtimer
service.lgtv.remote
service.nfo.watchedstate.updater
service.rytecepgdownloader
service.sleepy.watchdog
service.tvh.manager
skin.destiny
skin.horizonzv.isengard
skin.moddedconfluence.4
```

only legal stuff ofc :)

**Comment by islipfd19** [comment]
Build Me

**Comment by islipfd19** [comment]
Build Me

**Comment by islipfd19** [comment]
Build Me

**Comment by islipfd19** [comment]
Build Me

**Comment by islipfd19** [comment]
build me

**Comment by islipfd19** [comment]
build me

**Comment by islipfd19** [comment]
build me

**Comment by islipfd19** [comment]
ok to test

**Comment by islipfd19** [comment]
test this please

**Comment by islipfd19** [comment]
test this please

**Comment by islipfd19** [comment]
test this please

**Comment by islipfd19** [comment]
test this please

**Comment by islipfd19** [comment]
build me please

**Comment by islipfd19** [comment]
build me please

**Comment by islipfd19** [comment]
generic build me please

**Comment by islipfd19** [comment]
imx6 build me please

**Comment by islipfd19** [comment]
Odroid_C2 build me please

**Comment by islipfd19** [comment]
RPi build me please

**Comment by islipfd19** [comment]
RPi2 build me please

**Comment by islipfd19** [comment]
WeTek_Core build me please

**Comment by islipfd19** [comment]
WeTek_Play build me please

**Comment by islipfd19** [comment]
Generic build me please

**Comment by islipfd19** [comment]
Generic build me please

**Comment by CvH** [comment]
fixed icon and squashed, rdy for merge

**Comment by MartijnKaijser** [comment]
Why can't they bother to actually submit their Addons to Kodi repo if this all OK to just add as repo?

**Comment by chewitt** [comment]
@MartijnKaijser these are Linux docker containers wrapped-up as Kodi add-ons specifically to make running them on LE easier. It's not something applicable to other OS/distros.

**Comment by CvH** [comment]
@MartijnKaijser iirc some of the authors had already their kodi repo "experience" and decided to not repeat it again. Ofc I do not speak for any of these addon creators, feel free to contact them [here](http://www.kodinerds.net/index.php/Thread/52771-Kodinerds-Repo-Diskussionsthread/) - english should be okay.
Ping to @tyl0re (hopefully the right L0RE)

**Comment by MartijnKaijser** [comment]
Fast updates are pointless as I already explained because kodi does only check once every, 24 hours

**Comment by MartijnKaijser** [comment]
Also please explain why you guys have problems with submitting Addons and others don't while there almost zero difference in what kind of media they provide?

**Comment by CvH** [comment]
@MartijnKaijser these pr is an half year old, the list was correct at these date

**Comment by tyl0re** [comment]
> @tyl0re that's why I added you to our slack channel so you could ask and discuss I real time and so far you didn't ask anything there.

I Have Asked phil65 directly in slack on 7.Nov and 17 November. I havnt asked in the Channel since i dont want to Bother Other People, when he is the one working on my PR

**Comment by tyl0re** [comment]
> Fast updates are pointless as I already explained because kodi does only check once every, 24 hours
Mayby An Example from today
On Kodinerds Repo: A Bug was sumbmitted 16 h Ago, A fied it in the Evening after 8h. Told the User he should Test. Most of the time an Search for New Updates Manually is enough for  the User. to test if his Bug is Fixed. ==> 8h

On Kodi.tv i make an PR, Normally it get reviewed within 24 h, Lets say 5h. The Reviewer finds an Typo in my Variable Name for example viedo_url="http://example.com". Reports Back to me. I work Tomorrow in the Day. So i Correct it in the Evening tomorrow, and make an new Pull Request with video_url="
Since i have Corrected it very Late, the PR Mod is already Offline an reviews in an 18h the next day
So it takes nearly 48 h to be Corrected.

If the correction was an big one (I Corrected my Magine Addon Code Change 90%) If it would be in kodi TV  (I think with Question and Answer Game in the PR ) it would take up to 1 Week to be corrected

**Comment by tyl0re** [comment]
"Also please explain why you guys have problems with submitting Addons and others don't while there almost zero difference in what kind of media they provide?"

I submit mine also to the Official one. But maybe its Better to say Whats other then the Official one

System works on Trust. An Addon Gets Added when it works for the User. The Developer Get Access to his Plugin, so he can maintain his Addon by himself. if A developer is Trustforthy he gets Added to direct Access to the Repo. so he also can Add his New Addons. All User know "Do not Supmit Harmfull Code or Illegal Contetn Plugins". If someone would do harm, it would get removed as fast as possible. Until now i have never happend

**Pull request merged**
