### PR TITLE
lirc: replace parallel build fix

### PR DESCRIPTION
**Pull request by InuSasha**
lirc failed with parallel build (missing library "cannot find -llirc").
disable it temporary

### CODE REVIEW

**Comment by CvH** [comment]
hmm [this should fix it](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/lirc/patches/lirc-0003-use-proper-linking-method-to-avoid-parallel-build-issue.patch)

**Comment by lrusak** [comment]
Reset your git, there is a patch included that already addresses this

**Comment by InuSasha** [comment]
it was not help on my system...

checked my build log
i builded the commit with this specific patch (c6c222dc4bba1a88060f3a1045cd58f1126290f1),
but it was failing, with the missing lirc. The unpack show me the patch was applied

**Comment by mcaptur** [comment]
inusasha same here

**Comment by stefansaraev** [comment]
most likely, liblirc is picked from sysroot instead of source tree next build, thats why it fails once after make clean

settings MAKEFLAGS += -j1 is perfectly acceptable for known broken packages, even if it's broken on just one configuration (today it's one - tomorrow - many)

**Comment by InuSasha** [comment]
found a better solution, that fixes parallel build.
Will update PR, soon.

**Comment by InuSasha** [comment]
it builds fine on my system in parallel mode, now.
@mcaptur can you test it, too?

**Comment by MilhouseVH** [comment]
> it builds fine on my system in parallel mode, now.
Change PR title? :)

**Comment by InuSasha** [comment]
@MilhouseVH done

**Pull request merged**
