### PR TITLE
[LE11] Switch from pre-built to self-build aarch64 gcc

### PR DESCRIPTION
**Pull request by jernejsk**
While binary packages can spare some time while building images from scratch, there are also issues with such approach. We can't be completely sure what's in the binary and also binary itself can be incompatible with some distros or CPUs. Since at least for aarch64 arch we only need baremetal compiler, it doesn't really make sense to keep it as binary. This PR switches it from binary to self-build aarch64 gcc toolchain. On Ryzen 3700X such approach increases build time for 4 minutes.

@HiassofT @SupervisedThinking and anyone else, please test! Although there is plenty of benefits to build this toolchain from scratch, it still takes some time. Maybe it would be possible to slim it down some more...

### CODE REVIEW

**Comment by jernejsk** [comment]
Another added benefit is that you can now build arm 64/32 split image on risc-v host, if you would like to do for some reason.

**Comment by HiassofT** [comment]
Thanks a lot!

I did a quick test on my i7-3740QM laptop, scripts/build_mt gcc-aarch64:host (for RPi4) took about 11 minutes, with sources preloaded and other build-deps from ccache.

other deps took about 3 minutes to build, binutils-aarch64 1min30 and gcc-aarch64 6min30.

So that's roughly 8 minutes more than with binary toolchain, which is in the ballpark of what I expected and not too bad IMO.

I'll do a full build and runtime test now.

**Review by HiassofT — APPROVED** [review]
RPi4 build looks good here
```
[    0.000000] Linux version 5.15.33 (hias@delle) (aarch64-none-elf-gcc-11.2.0 (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Thu Apr 14 21:50:32 CEST 2022
```

**Review by heitbaum — APPROVED** [review]
build tested all of

```
PROJECT=Allwinner ARCH=arm DEVICE=A64
PROJECT=Allwinner ARCH=arm DEVICE=H3
PROJECT=Allwinner ARCH=arm DEVICE=H5
PROJECT=Allwinner ARCH=arm DEVICE=H6
PROJECT=Allwinner ARCH=aarch64 DEVICE=H6
PROJECT=Rockchip ARCH=arm DEVICE=RK3288
PROJECT=Rockchip ARCH=arm DEVICE=RK3328
PROJECT=Rockchip ARCH=arm DEVICE=RK3399
PROJECT=NXP ARCH=arm DEVICE=iMX6
PROJECT=NXP ARCH=arm DEVICE=iMX8
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard
PROJECT=Samsung ARCH=arm DEVICE=Exynos
```
run tested on
```
[    0.000000] Linux version 5.17.3 (docker@7eb781e589ab) (aarch64-none-elf-gcc-11.2.0 (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP PREEMPT Fri Apr 15 05:34:11 UTC 2022
[    0.000000] Machine model: Tanix TX6
```

**Review by CvH — APPROVED** [review]

**Pull request merged**
