### PR TITLE
tools/docker: add sid, groovy, hirsute containers

### PR DESCRIPTION
**Pull request by heitbaum**
This PR adds a groovy, hirsute and sid container and adds the details of the containers in the readme.

### CODE REVIEW

**Comment by CvH** [comment]
@antonlacon pls have a look

**Comment by antonlacon** [comment]
I haven't used docker, but the additional dependencies on the base image look correct. The only difference between these is the FROM line? If yes, these should all be fine.

My understanding of https://wiki.ubuntu.com/Releases has Ubuntu 16.04 (Xenial) in paid support only, so that dockerfile can be removed.

**Comment by lrusak** [comment]
What's the point in this?

**Comment by heitbaum** [comment]
What versions are we using for the build hosts in 9.2? If so - keep 16.04 there?

I put all of these images in as we needed to test the "make image / create_addon" on sid. Also so as to test the glibc mismatches across target and host.

**Comment by antonlacon** [comment]
> What versions are we using for the build hosts in 9.2? If so - keep 16.04 there?

I don't know about the build hosts. I would keep the 16.04 dockerfile in the 9.2 branch.

**Comment by heitbaum** [comment]
> > What versions are we using for the build hosts in 9.2? If so - keep 16.04 there?
> 
> I don't know about the build hosts. I would keep the 16.04 dockerfile in the 9.2 branch.

So suggest we drop 16.04 in master - can do.

**Review by CvH — APPROVED** [review]

**Pull request merged**
