### PR TITLE
WireGuard: add initial package/tools and connman support

### PR DESCRIPTION
**Pull request by chewitt**
I'm sending this PR to 9.2 branch because a) this needs public testing and given the current state of master due to the Python 3 changes more people are likely to test it on LE 9.2, and b) I'm using it myself on LE 9.2 in various forms for some time and I'd like to stop building and revert to stock images on the family daily-driver. It would be a late feature addition, but also (IMHO) a fairly low-risk addition. If accepted I will forward-port the changes once master is usable again.

Why now? .. In the last 24h connman finally pushed initial support for WireGuard so we bump connman to current HEAD to pick-up the commits. We need to revert two recent changes with patches as wagi wrongly assumed everyone is using near-latest glibc. He's advised the reverts are harmless to carry until we bump to newer glibc or he reworks upstream code. Connman is due a version bump soon, and he's aware of the issue, so we probably don't carry them for long.

WireGuard support is made configurable in distro options because downstream distros like Lakka are unlikely to need it. The WireGuard package currently builds kernel driver + tools. Hopefully kernel code is merged upstream in the near future (but don't hold breath) and when that happens the package can be reworked to be tools only. For this reason it lives under packages/network not packages/linux-drivers.

Connman does not yet support direct import of a generated WireGuard conf file, so users must copy/paste details into `/storage/.config/wireguard/anyname.config` using the template config in the same dir (nb: `host` is the peer/server IP or FQDN and `domain` is mandatory but free-text) then run `connmanctl services` to discover the connman service name, and copy/paste this into `/storage/.config/system.d/wireguard.service` using the template .service file in the same dir. Once the service has been created `systemctl enable wireguard.service` enables it, and `systemctl start wireguard.service` will start it. As connman presents WireGuard as a service similar to Ethernet and WiFi networks the service name (from the .config) becomes visible in the LE settings add-on and can be connected/disconnected over dbus from there. LE settings needs minor cosmetics to add a WireGuard service icon, but that's simple (we have some prior art from older versions of the add-on). The systemd service is needed for auto-starting a connection on boot. How autostart is achieved may change in future iterations of connman.

At the current time connman supports a single WireGuard service configuration. If you add two or more .config files with WireGuard profiles to `/storage/.config/wireguard` connman-vpn service (which continuously watches /storage/.config/wireguard for .service files to use) will crash, but it's a harmless failure and once you rename files so there is only one .service file present the service can be restarted again. In the future connman plans to support multiple configurations.

I've also created helper scripts for `wg-keygen` which creates/stores keys in `/storage/.cache/wireguard` though most users will probably obtain keys from an externally generated WireGuard conf, and `wg-quick` which is my interpretation of the default interface up/down script that is documented in 99% of WireGuard HOWTO guides. In LE `wg-quick` is a simple wrapper around connmanctl stop/start/restart.

I've been using WireGuard in some variation for around six months, including earlier iterations of the connman patches. This is tested working for me on 4-5 different WireGuard connections and I've received positive (not public) feedback from a couple of testers who've been tracking my test branch. I'd like eyeballs and feedback on script robustness, typos, etc. please.

### CODE REVIEW

**Comment by chewitt** [comment]
I bumped connman so the revert patches are no longer needed (wagi pushed a fix). I also dropped the wg-quick script as it has some logic flaws and needs rethinking - best to keep things simple for now. So connect/disconnect it's either done via the settings add-on GUI, connmanctl on the SSH console, or you automate connect on boot using systemd and the template .service file.

**Comment by trayntab** [comment]
Hey guys are there new information about WireGuard in libreelec?

**Comment by chemical1979** [comment]
I tried to tinker with this a little bit (thank you for implementing), but it seems to always route 0.0.0.0/0 into the tunnel, although the .AllowedIPs is limited to a remote subnet. Is this a bug? 
Details [here](https://forum.libreelec.tv/thread/21906-wireguard-changes-the-default-route-although-not-configured/)

**Comment by QBN0** [comment]
Hello... I have a rasberry pi3, with the latest libreelec... I'm trying to install wireguard but I haven't been successful... please... help me

**Comment by lrusak** [comment]
> 
> 
> Hello... I have a rasberry pi3, with the latest libreelec... I'm trying to install wireguard but I haven't been successful... please... help me

@QBN0 use the forum for support. https://forum.libreelec.tv/

**Pull request closed without merging**
