### PR TITLE
Clean up kernel dependencies

### PR DESCRIPTION
**Pull request by jernejsk**
This PR also splits out commits from #6425 It's just a small cleanup of linux dependencies. linux:host is there really to install headers only. There is no need for toolchain or openssl being build for them. On ARM split builds (64-bit kernel and 32-bit userspace), changes made here also remove dependency on 32-bit toolchain. It's really not needed.

https://github.com/LibreELEC/LibreELEC.tv/pull/6425#issuecomment-1113956000 also suggest removing unpack dependencies for linux:host, but I don't think this is possible with current build system. Variable is evaluated and used before any *_target() function is called. Since this is just unpack dependency and downloaded files are cached, it should provide only minor inconvenience.

I also added a commit to remove openssl dependency on cmake here. It's not needed to build any package. If it is too out of place, I can make separate PR for it.

Changes made here will allow for better parallelism when building images or update files and less dependencies to build when building addons.

Build tested with:
PROJECT=Allwinner ARCH=arm DEVICE=H6 make release
PROJECT=Generic DEVICE=x11 ARCH=x86_64 make release

### CODE REVIEW

**Review by CvH — APPROVED** [review]

**Comment by jernejsk** [comment]
Yeah, building rust didn't work for me due to uname issue, so I missed it. Last time I tried cmake without openssl it worked fine, but granted, it was a while ago.

**Comment by heitbaum** [comment]
> Yeah, building rust didn't work for me due to uname issue, so I missed it. Last time I tried cmake without openssl it worked fine, but granted, it was a while ago.

Simple fix to add the dependencies to both cargo and mariadb done.

**Comment by vpeter4** [comment]
With this PR **cmake** fails to download files from https:// URLs: https://cmake.org/cmake/help/latest/command/file.html#download
`For https:// URLs CMake must be built with OpenSSL support.`
and this happen
```
[3/1599] Creating directories for 'dvdcss'
[4/1599] Performing download step (download, verify and extract) for 'dvdcss'
FAILED: build/libdvd/src/dvdcss-stamp/dvdcss-download /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src/dvdcss-stamp/dvdcss-download
cd /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src && /home/user/LibreELEC/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/toolchain/bin/cmake -P /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src/dvdcss-stamp/download-dvdcss.cmake && /home/user/LibreELEC/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/toolchain/bin/cmake -P /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src/dvdcss-stamp/verify-dvdcss.cmake && /home/user/LibreELEC/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/toolchain/bin/cmake -P /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src/dvdcss-stamp/extract-dvdcss.cmake && /home/user/LibreELEC/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/toolchain/bin/cmake -E touch /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src/dvdcss-stamp/dvdcss-download
-- Downloading...
   dst='/home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/download/libdvdcss-1.4.3-Next-Nexus-Alpha2.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/xbmc/libdvdcss/archive/1.4.3-Next-Nexus-Alpha2.tar.gz'
CMake Error at dvdcss-stamp/download-dvdcss.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/xbmc/libdvdcss/archive/1.4.3-Next-Nexus-Alpha2.tar.gz' failed
          status_code: 1
          status_string: "Unsupported protocol"
          log:
          --- LOG BEGIN ---
          Protocol "https" not supported or disabled in libcurl

  Closing connection -1

          --- LOG END ---
```
If I send PR to revert cmake changes will it be merged? I'm asking just to not waste time for nothing.

**Comment by HiassofT** [comment]
@vpeter4 which kodi and libdvdcss versions are you using?

This sounds a bit like kodi isn't happy with the provided tarball from the libdvdcss package - cmake shouldn't download stuff from the net during build but instead use the (cached) packages from SOURCES
https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/mediacenter/kodi/package.mk#L99

There were some changes to kodi's handling of libdvdcss/read/... deps, maybe something is buggy there or something needs to be changed in kodi package.mk (we still use Alpha1 in master)

**Comment by jernejsk** [comment]
Yeah, this is actually good. Before I made this change, I already fixed such issue in kodi's package.mk.

**Comment by vpeter4** [comment]
On CoreELEC we don't use provided tarball from all 3 libdvd* packages because the version in the package must match the version in Kodi. It is unneeded manual job that's why we automated this process and allow Kodi to download correct version if necessary. If the tarball is already present in the sources folder it is used without subsequent download.

https://github.com/CoreELEC/CoreELEC/commit/8c99ffd474a0516e7a3a364dd30a30ccdd5f1e2c

**Comment by HiassofT** [comment]
@vpeter4 in that case you need to revert the cmake/openssl change in CoreELEC.

We prefer to have kodi deps managed and cached via SOURCES as that avoids downloading the deps again and again on kodi (re-)builds - every now and then you may hit a network/github/... glitch which then lets kodi build fail if the download fails. Usually these glitches happen when you need them least...

**Comment by vpeter4** [comment]
> cached via SOURCES as that avoids downloading the deps again and again on kodi (re-)builds

As I said it still works this way.

But ok, I understand: your playground, your rules. Case closed.

**Pull request merged**
