### PR TITLE
imx6: update kernel, prepare for second kernel

### PR DESCRIPTION
**Pull request by vpeter4**
officially supported kernel is branch 3.14-1.0.x-mx6-sr from solidrun (3.14.60 at the time of writing)
unofficial kernel is branch imx6-4.4.y from xbian thanks to mk01 (4.4.6+rt3)

patches can be in subfolder: projects/imx6/patches/linux/3.14-mx6-sr/
kernel config can be in subfolder: projects/imx6/linux/3.14-mx6-sr/linux.arm.conf

### CODE REVIEW

**Comment by mhueske** [comment]
Just a question from my side: As I understood kernel 4.5 should support imx platform and vivante libraries (aka etnaviv). So might it be possible to use that one?

**Comment by vpeter4** [comment]
One day sure. But right now probably not.

**Comment by lrusak** [comment]
@vpeter4 are you happy with this?

**Comment by vpeter4** [comment]
Yes, if there is no objections please merge. In next PR I will add the second kernel. And later some other things. Depends in which way we want a progress. There has been lot of work done recently to make this project much better.

**Pull request merged**
