### PR TITLE
Add PKG_STAMP to trigger a package rebuild

### PR DESCRIPTION
**Pull request by Kwiboo**
This PR adds support for using `PKG_STAMP` to trigger a package rebuild (extracted from #2328)

`u-boot` package is changed to use `PKG_STAMP` instead of a special `UBOOT_SYSTEM` hack in `scripts/build` to trigger package rebuild when `UBOOT_SYSTEM` changes
`linux` package will be rebuild when changes is made to make targets parameters in `options`-file

Another example of usage is for the `mali-rockchip` package, see https://github.com/Kwiboo/LibreELEC.tv/commit/505b753cfddd17a6d5a1b5072824ad74fee4ff87 (triggers a package rebuild if `options` is changed to use another x11/wayland/gbm driver)

### CODE REVIEW

**Comment by adamg88** [comment]
Could this be expanded so if there is changes to initramfs to rebuild busybox/initramfs/linux?

**Comment by MilhouseVH** [comment]
> Could this be expanded so if there is changes to initramfs to rebuild busybox/initramfs/linux?

No because you'll likely be caught in a circular dependency - initramfs is built from within linux so it's not possible for initramfs to rebuild linux.

There also comes a point where you can only go so far with automated cleaning before you might as well clean build every time.

**Comment by chewitt** [comment]
@Kwiboo can you rebase against changes in `scripts/build` please

**Comment by vpeter4** [comment]
This is something useful - can be merged?

**Comment by Kwiboo** [comment]
Rebased on latest LE master

**Pull request merged**
