### PR TITLE
libressl: update to 2.4.5 for security reasons

### PR DESCRIPTION
**Pull request by sopparus**
libressl: update to 2.4.5 for security

### CODE REVIEW

**Comment by chewitt** [comment]
@sopparus please change the commit message (not the PR title) to `libressl: update to 2.4.5 for security patches` or similar, thanks

**Comment by sopparus** [comment]
k done

**Comment by chewitt** [comment]
You need to force-push the changes to github, e.g. `git push -f origin master` too. Also not a good idea to work directly in `master` .. always make changes in a topic branch.

**Comment by vpeter4** [comment]
Fixed the tile.
But not sure if this affects us: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.4.5-relnotes.txt

**Comment by chewitt** [comment]
commit message, not PR title, as previously instructed :)

**Pull request merged**
