### PR TITLE
systemtools addon update

### PR DESCRIPTION
**Pull request by CvH**
- replaced mxvt with rxvt, there is still some problem that it only shows a pink background ad all colors are wrong (no time yet in looking into it) @mglae fixed it last time
- strace update allows it to build again

### CODE REVIEW

**Comment by mglae** [comment]
I've tested st terminal emulator some time ago on 9.2, see https://github.com/mglae/LibreELEC.tv/commits/le92_terminal_st. No idea if it compiles on master. There is need for a color patch too.

Please consider to include some of the default.py changes.

I've put rxvt-unicode testing on my todo list.

**Comment by mglae** [comment]
rxvt-unicode color patch: http://ix.io/2y3P

But the result is still interesting because bold fonts are not shown:
rxvt-unicode_2020-09-18

**Comment by CvH** [comment]
wondering if we do something wrong or the package itself is just not working correctly
Mabye looking at the patchset of debian https://sources.debian.org/patches/rxvt-unicode/9.22-8/ helps to fix it ?
Btw I tried ST before and it didn't compiled for multiple reasons with fancy errors.

**Comment by mglae** [comment]
#### rxvt-unicode
LE is only using a subset of X libraries, debian all. There seems to be no real changes in the patchset.

In addition i.e. --enable-xft is ignored because not being found by pkg-config.

#### st
I've tested http://ix.io/2y93 on top of this PR. The package is [building fine](http://ix.io/2y9o). There is only a minor issue I've seen on 9.2 too: you have to install the Locale Addon to be able to non type ASCII chars like ÄÖÜ.

**Comment by CvH** [comment]
superseded

**Pull request closed without merging**
