### PR TITLE
[le10] prometheus-node-exporter: initial addon - backport

### PR DESCRIPTION
**Pull request by heitbaum**
Backport of
- #5549

https://forum.libreelec.tv/thread/25267-help-installing-the-prometheus-node-exporter-service/?postID=166568#post166568

### CODE REVIEW

**Review by chewitt — APPROVED** [review]
Reported working in the forums. Can be merged once the test zip is dropped from the PR.

**Comment by heitbaum** [comment]
@chewitt - test zip has been dropped.

**Comment by chewitt** [comment]
Thanks!

**Comment by CygnusHyoga** [comment]
Hi, I have installed LE 10.0.2, I'm trying to use the backported prometheus-node-exporter service, but the service don't start. Trying from systemctl and manually without luck. Any help? Thanks!

# cat /etc/os-release 
NAME="LibreELEC"
VERSION="10.0.2"
ID="libreelec"
VERSION_ID="10.0"
PRETTY_NAME="LibreELEC (official): 10.0.2"
HOME_URL="https://libreelec.tv"
BUG_REPORT_URL="https://github.com/LibreELEC/LibreELEC.tv"
BUILD_ID="8fd15cdad59fb70083aa25b5c9680d8826b94696"
LIBREELEC_ARCH="Generic.x86_64"
LIBREELEC_BUILD="official"
LIBREELEC_PROJECT="Generic"

# systemctl start service.prometheus-node-exporter

# systemctl status service.prometheus-node-exporter
service.prometheus-node-exporter.service - Prometheus Node Exporter service
     Loaded: loaded (/storage/.kodi/addons/service.prometheus-node-exporter/syst
     Active: failed (Result: exit-code) since Sat 2022-03-26 09:18:11 UTC; 23s a
    Process: 11985 ExecStart=/storage/.kodi/addons/service.prometheus-node-expor
   Main PID: 11985 (code=exited, status=2)

Mar 26 09:18:11 sharingan systemd[1]: service.prometheus-node-exporter.service: 
Mar 26 09:18:11 sharingan systemd[1]: Stopped Prometheus Node Exporter service.
Mar 26 09:18:11 sharingan systemd[1]: service.prometheus-node-exporter.service: 
Mar 26 09:18:11 sharingan systemd[1]: service.prometheus-node-exporter.service: 
Mar 26 09:18:11 sharingan systemd[1]: Failed to start Prometheus Node Exporter s

~
~
~
~
~
~
~
~
~
~
~

If I try to run mannually:

 # /storage/.kodi/addons/service.prometheus-node-exporter/bin/prometheus-node-exporter.start
/storage/.kodi/addons/service.prometheus-node-exporter/bin/prometheus-node-exporter: line 1: syntax error: unexpected word (expecting ")")

**Pull request merged**
