### PR TITLE
Enable CONFIG_BINFMT_MISC on RasPi 1/2/3/4

### PR DESCRIPTION
**Pull request by volfyd**
Hi. I hope libreelec-9.2 is the right branch. If there are future releases of LE 9 before 10, it would be nice to have CONFIG_BINFMT_MISC=y so it's possible to run x86 binaries on Raspberry Pi without running a fork.

I have tested this on a Raspberry Pi 3 with the following docker container, which will allow you to access a Debian stretch chroot.

```
FROM arm32v7/debian:buster

# Save this as /storage/qemu/Dockerfile and run
# docker build -t qemu /storage/qemu

# And then to start the container run
# docker run --privileged --rm --name qemu -v /storage:/storage -it qemu

RUN apt-get update
RUN apt-get -y install qemu binfmt-support qemu-user-static debootstrap dialog

CMD dpkg-reconfigure qemu-user-static > /dev/null; \
    if [ ! -e /storage/x86/stretch ]; then \
        mkdir -p /storage/x86/stretch; \
        debootstrap --arch amd64 stretch /storage/x86/stretch http://deb.debian.org/debian/; \
    fi; \
    for f in dev dev/pts sys proc run; do \
        mount --bind /$f /storage/x86/stretch/$f; \
    done; \
    chroot /storage/x86/stretch

```

### CODE REVIEW

**Comment by lrusak** [comment]
I don't see why not. Thanks for the PR!

What are you wanting to run that is available for x86 but not armv7?

**Comment by volfyd** [comment]
@lrusak I have some backup software that is only available in binary form. qemu might need some patches to give it more SCSI support. I tried my hand at creating patches but they need some more work.

https://lists.nongnu.org/archive/html/qemu-devel/2020-07/msg08637.html

**Comment by lrusak** [comment]
Is this still needed? Can you please change the branch to master?

**Comment by CvH** [comment]
closing it because we are likely never merge that
its a very niche feature

**Comment by arnaufugarolas** [comment]
Hi, I created a PR to make these changes https://github.com/LibreELEC/LibreELEC.tv/pull/10205 Could you check it? thanks!

**Pull request closed without merging**
