### PR TITLE
Re-enable lirc_serial driver

### PR DESCRIPTION
**Pull request by jbollacke**
The driver lirc_serial has been renamed to ir_serial in linux v4.10. See https://github.com/torvalds/linux/commit/fa5dc29c1fcc9151c3bcfd9e291a2899ae15f61
But this driver is needed for some IR receivers e.g. Atric IR Receiver to work.

First added in https://github.com/LibreELEC/LibreELEC.tv/commit/af3d9e7fa2d2904703dd7cdff12064b0e2331547.
Removed in https://github.com/LibreELEC/LibreELEC.tv/commit/491b7010f2f60a773caa3d41a52aac1bebc01851 (due to migration to linux v4.10).

This PR does:
- Enable ir_serial as module
- Add alias named lirc_serial so scripts referencing this module (e.g. autostart.sh) won't break

### CODE REVIEW

**Comment by HiassofT** [comment]
Please add  `CONFIG_IR_SERIAL_TRANSMITTER=y` - LE8 contained `CONFIG_LIRC_SERIAL_TRANSMITTER=y` as well.

And I'd strongly suggest dropping the modprobe.d file with the alias. People can just change the module name in .config/modules-load.d/*.conf. This is a lot cleaner than adding support for legacy configurations which will then probably linger around forever.

**Comment by HiassofT** [comment]
Just had a look at the serial IR driver, by default it uses the rc6-mce map. This means MCE remotes will work out of the box and use in-kernel decoding. Running userspace lircd in parallel to that will result in double keypresses.

So people will have to adjust their configs anyway and remove their lircd.conf if they use an MCE remote (or some other remote supported by LE out of the box).

**Comment by jbollacke** [comment]
As far as I know `CONFIG_IR_SERIAL_TRANSMITTER` is `y` by default. See https://github.com/torvalds/linux/commit/fa5dc29c1fcc9151c3bcfd9e291a2899ae15f61#diff-9b924813a0f386da12899ca6acdf420cR404 for reference. So adding it would just make it more verbose.

I agree with dropping the module alias.

**Comment by jbollacke** [comment]
Will squash later

**Comment by lrusak** [comment]
Thanks!

**Comment by MilhouseVH** [comment]
If you run `make oldconfig` on the Generic kernel now you are prompted to enable `CONFIG_IR_SERIAL_TRANSMITTER` or not - the default is "yes", but being verbose and specifying a value means there is no confusion or need to prompt. Will add `CONFIG_IR_SERIAL_TRANSMITTER=y` in the next kernel bump.

**Pull request merged**
