### PR TITLE
netbsd-curses: update to 4c156be

### PR DESCRIPTION
**Pull request by awiouy**
194ddef is the first version that builds after 0.2.1

### CODE REVIEW

**Comment by awiouy** [comment]
Iu

**Comment by CvH** [comment]
@awiouy ?

**Comment by awiouy** [comment]
You have a  dyfr

**Comment by awiouy** [comment]
My pocket is typing !
Sorry for the noise...

**Comment by MilhouseVH** [comment]
This is working fine for me building the main image and a handful of addons (PVRs, inputstream, tvheadend42) for RPi/RPi2/Generic (and a test OdroidC2/aarch64 build) - has anyone tested it with any other addons or shall we merge and see what falls out?

**Comment by MilhouseVH** [comment]
I guess we merge and see what falls out...

**Pull request merged**
