### PR TITLE
kernel-overlays-setup: fix ls error in journal if .config/firmware do…

### PR DESCRIPTION
**Pull request by HiassofT**
…esn't exist

Sorry, I missed that when testing the .config/firmware changes

### CODE REVIEW

**Comment by vpeter4** [comment]
Why exactly original line doesn't work?

**Comment by HiassofT** [comment]
Because test / "[" evaluates both expressions - compared to `foo && bar` where `bar` isn't run if `foo` failed.

So `ls directory` was executed even if the test before determined that `directory` doesn't exist / isn't a directory.

**Comment by vpeter4** [comment]
Something to remember. Thank you.

**Comment by MilhouseVH** [comment]
It's something that is mentioned in the [coding standards](https://github.com/LibreELEC/LibreELEC.tv/pull/3055) proposal. Diverting stderr to /dev/null is another solution, but not executing a command that is going to fail should be the preferred solution.

**Pull request merged**
