### PR TITLE
intel-gpu-tools: initial addon

### PR DESCRIPTION
**Pull request by awiouy**
Work in progress.
This builds, but runtime depends on a multitude of libraries.

### CODE REVIEW

**Comment by awiouy** [comment]
Could someone tell me which of the following are not included in the LE image.
If there is a systematic way to do it, please share.
 0x0000000000000001 (NEEDED)             Shared library: [libcairo.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libdrm_intel.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdrm.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libglib-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpciaccess.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libudev.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
Thank you in advance.

**Comment by MilhouseVH** [comment]
Not present in Generic builds:

 0x0000000000000001 (NEEDED) Shared library: [libcairo.so.2]

The rest should be present.

What's the background for this add-on, why is it needed or what's the benefit?

**Comment by lrusak** [comment]
I think you only need
libpixman-1.so.0
libcairo.so.2

**Comment by awiouy** [comment]
@MilhouseVH https://forum.libreelec.tv/thread-1556.html
@lrusak indeed: ldd yields libpixman-1.so.0, too

**Comment by stefansaraev** [comment]
o_O. I have compiled intel-gpu-tools for a friend one year ago or so. I dont remember seeing cairo as a runtime dependency ?!

hint: you should never compile such stuff in a build environment where you already compiled heavy addons like chromium... ?

**Comment by awiouy** [comment]
@stefansaraev 
https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/tree/README#n137
It builds clean, and should run, too ;)
https://drive.google.com/open?id=0B-GDMT6DbxCVSWN3eUMxaDdLakk

**Comment by stefansaraev** [comment]
software bloat at its best if you ask me, I can't autoreconf that source tarbal right now to check if cairo is an optional dependency. is it? if not - you should patch configure.ac and remove it!.

**Comment by awiouy** [comment]
@stefansaraev Thank you for your efforts and suggestions. This addon is not intended to be added to the repository (see #728), builds and runs. Let's move on to something more permanent ;)

**Pull request closed without merging**
