### PR TITLE
retroplayer addons

### PR DESCRIPTION
**Pull request by CvH**
Added several missing retroplayer addons and some fixes

**still missing retroplayer addons:**
`game.libretro.chailove` - usefulness around zero ?
`game.libretro.fbalpha2012` - we have already the latest
`game.libretro.lutro`  - usefulness around zero ?
`game.libretro.pcem` - heavily outdated upstream
`game.libretro.rustation` - PlayStation Emu not yet working ?
`game.libretro.vram-test` - usefulness around zero ?
^^^^ @garbear ???

**libretro-mame:**
- mame builds now for generic (takes as long as an complete RPi LE9 image for me -.-) and based at lakkas package TX! #next-chromium
- arm fails for unknown reason (contacted lakka)

**libretro-vice** 
- based partly at @5schatten package TX !

everything is buildtested at Generic/RPi but not runtime due missing emus etc

**libretro-fs-uae**
- is not building at RPi, any ideas ?
`PROJECT=RPi DEVICE=RPi2 ARCH=arm scripts/build libretro-fsuae`
Log: http://ix.io/1geO

### CODE REVIEW

**Comment by lrusak** [comment]
I would just disable libretro-fs-uae for arm and leave the arm version for arm

**Comment by 5schatten** [comment]
IMHO it makes sense to pick the "best" emulators for each platform and focus on them rather to have dozen of barely working ones.

Btw. can someone look into libretro-reicasts makefile? I use Mint 19 to build it but without the libgl1-mesa-dev package it complains about missing GL.h & missing libgl. But both should are provided by the mesa package and so some INCFLAGS or something should resolve this?

**Comment by lrusak** [comment]
Any OpenGL emulators should be disabled for now until we merge support for them into kodi

**Comment by CvH** [comment]
@5schatten I have sadly no real experience with emus besides some usage and zero background info. I have really no idea why we have 3x snes9x or why 5x mame is needed. But lakka (they should know) has 5x snes9x and 7x mame so I can guess there is some reason :) If we pick the best SNES, NES, PSX ... Emu and just provide it I can guarantee that we soon get hammered that emu abc is not there and "everyone" needs it. So I guess best way is to just provide whatever gh/kodi-game provides.

**Comment by chewitt** [comment]
Some games work best (or only) with a specific emulator and/or some hardware works better with a particular emulator. In some platforms there are myriad combinations to handle and in the long-term the thing that needs to happen (and might happen with a boost in popularity from Kodi use that brings more eyeballs to the problem) is some of the emulators evolving and being merged. That's said, with the emulator scene having lots of people working in isolation https://www.xkcd.com/927 is also likely :)

**Comment by garbear** [comment]
@5schatten your breadth of testing is impressive. of course the solution is crowd-sourcing all the data we need, but in the meantime I'd like to build a system for fully automating emulator selection and fill it with expert knowledge. that would handle the basic cases and be a drastic improvement over letting the user guess and hope.

What information can we use for emulator selection? your post mentions:

* Underlying platform/architecture
* Individual game compatibility and performance
* Speed
* Accuracy
* Stability
* Size

**Comment by garbear** [comment]
@CvH can you include VRAM-test for now? https://github.com/kodi-game/game.libretro.vram-test

Useful for debugging now. I suggest we drop it before release.

**Comment by CvH** [comment]
@garbear added, it builds for Generic and RPi2 (no runtimetest)

**Comment by garbear** [comment]
@chewitt does this mean that game.libretro is the correct version to work with v18 alpha 3 builds?

**Comment by garbear** [comment]
@CvH do game add-ons work in LE currently? I melted my last microSD card so can't test ATM.

**Comment by CvH** [comment]
These updates are the latest versions available at pr time so it should work :) 
We have overall not too much feedback about Retroplayer. The hidden feature + konami code isn't helpful either. I guess upstream should decide if this should be a feature or not and stop hiding it :)

**Comment by matejmosko** [comment]
My feedback about retroplayer: On LE it doesn't work since around 402 milhouse's build. Not even after latest updates (including this one). Libretro compatibility addon (1.0.36.106) is complaining about wrong version of kodi.binary.instance.game (1.0.36)

[This is my log](http://paste.kodi.tv/alojurasiy) (RPi3, milhouse's build 705) - the results are same with newer versions as well. (posted this to PR #2817  as well, I have discovered this thread later)

**Comment by Qstick** [comment]
Libreelec repo likely needs updating to bring compatibility addon up to current, version of kodi.binary.instance.game is 1.0.38 currently

**Comment by garbear** [comment]
@CvH the following are still missing:

game.libretro.chailove
game.libretro.fbalpha2012
game.libretro.lutro
game.libretro.pcem

**Comment by CvH** [comment]
@garbear 
`game.libretro.lutro` An experimental Lua game framework for libretro inspired by LÖVE
do we need this at all ? nothing to do with emulator

`game.libretro.chailove` 2D Game Framework with ChaiScript
do we need this at all ? nothing to do with emulator

`game.libretro.fbalpha2012` we have already the latest one do we need the old on too, if so for what reason (just for the record) ?

`game.libretro.pcem` `My own personal fork of PCem, based on OBattler's experimental branch. THIS IS OUT OF DATE, USE 86Box-mooch INSTEAD` https://github.com/MoochMcGee/PCem-mooch
sounds like the libretro port is outdated - is this useful at all ?

**Comment by garbear** [comment]
`game.libretro.lutro` Yes, I've downloaded and played some LUA games. We could even package LUA games as content add-ons

`game.libretro.chailove` @RobLoach should this go in LibreELEC?

`game.libretro.fbalpha2012` often times the older versions of emulators are faster on slow hardware. compatibility can change between versions, too, so this core may be required for some games

`game.libretro.pcem` https://github.com/libretro/libretro-pcem this looks up to date?

**Comment by CvH** [comment]
`game.libretro.lutro` 👍 

`game.libretro.fbalpha2012` - `so this core may be required for some games` so you can't name any I guess ? Its just we end up with an huge number of emulators nobody could really explain why they are there and the users get even more variations (current list is already really scary). There are already a lot questions at the forum what emulator to use etc ... - and the emulator feature is still hidden and did not hit the "normal" masses yet.

`game.libretro.pcem` - its basically a copy of https://github.com/MoochMcGee/PCem-mooch and there the author states it is outdated, thats why I ask if it is a good idea to add an outdated emulator

**Comment by garbear** [comment]
regarding emulator bloat - this is handled by an automatic emulator chooser. doesn't matter how long the dialog is if it's hidden from the user. however, until we can autoselect emulators, best to not include this.

regarding pcem, does IAGL support any IBM PC games, and if so can they be played with another core?

**Comment by RobLoach** [comment]
`game.libretro.chailove` is not needed. It's a game engine inspired by Love2D. Sample game is [Floppy Bird](https://github.com/RobLoach/ChaiLove-FloppyBird).

**Comment by CvH** [comment]
@garbear `this is handled by an automatic emulator chooser` if this works I have no objections to include whatever is available in every version that is needed, as long the user still need to manually choose from a list it creates a mess if we include every variation. I guess this will develop over some time as soon proper feedback could be gathered.

`and if so can they be played with another core?` - no idea but from some googling (never used it so google is my knowledge source) pcem and the "successor" 86Box are an solution to run Windows and then that you can run games there. Basically something like DosBox from my understanding.
Btw the original developement tree https://bitbucket.org/pcem_emulator/pcem is still under active development - I guess the libretro implementation is just out of date.
Was this tested at all at Kodi ?

**Comment by RobLoach** [comment]
The [pcem libretro core](https://github.com/libretro/libretro-pcem) is rather out of date.

Regarding "emulator bloat", there are pros and cons to each core. On one platform, you may have reason to choose one core over another. Performance vs accuracy can be a factor, another can licensing. Pick and choose which one suites your needs, and roll with it.

**Comment by CvH** [comment]
`there are pros and cons to each core` - thats correct but now imagine you have that information nowhere collected and the "normal" user of Kodi has to decide it by himself without any knwoladge. 
You basically have 10 Emulators that would work with a game - how do you decide what you wanne use ?

**Comment by matejmosko** [comment]
For me it's just trial and error. For me the first thing that is necessary is to determine the console, that the rom is intended for. As far as I know, nowadays, when I am going to play psx game, I am presented with a multitude of cores that are irrelevant (it's the problem of not-exclusive file extensions for psx games) and only two of them belongs to psx (pcsx and beetle-psx). Moreover only one of them is usable on arm system (pcsx).

In my view:
**First** the shown cores on select box must be relevant to the platform, 
**second** they have to be relevant to game, 
**third** - they may be recomended on per game or per system basis (I really don't see any other way than crowdsourcing the third step)

**Comment by CvH** [comment]
`I really don't see any other way than crowdsourcing the third step`
https://wiki.dolphin-emu.org/index.php?title=Wii#A
also from my perspective the only way to go
I am not even confident that the normal users are able to properly distinguish between 
```
bsnes-mercury-accuracy
bsnes-mercury-balanced
bsnes-mercury-performance
```

how the heck should you understand what you need and what trade off you make, especially this is likely per game basis ... happy fubar :)

**Comment by RobLoach** [comment]
> happy fubar

It's not FUBAR... Accuracy, balanced and performance have different use cases. If you're running on a super powerful gaming machine, then accuracy/balanced is a good choice. If you're running on a Raspberry-Pi, then you'll need the performance core. While I agree that a common user may not know those cases, forcing the choice on the user goes against the nature of open source and LibreELEC.

Also, this is just the package code, which packages are built are deterministic on the distribution building them. It all comes down to the use case. If you're building LibreELEC for a Raspberry Pi, compile which cores you find suitable, and build for those. Otherwise, just build all available, and leave it to the user to decide which to run.

If you're setting it up, just uninstall the cores you find don't fit your system specs. In the following screenshot, if you don't want to have a choice presented, just uninstall cores that you don't want...

**Comment by CvH** [comment]
Just look at the screenshot, if you rename the emulators to 1,2,3,4,5 it won't matter for the normal users (not even to me). Names that doesn't reflect any useful information - thats the actual problem (from my POV).
I really don't mind adding a ton of different version/years/forks whatever but currently there is no way to present them in any proper fashion.

>forcing the choice on the user goes against the nature of open source and LibreELEC

Not really - we try to get it as easy as possible without sacrificing too much.

>It all comes down to the use case.

for example RPi2 and I want to play SNES  Mario Kart ... whats next ? there are ZERO help - its basically purely random what happens next

**Comment by garbear** [comment]
@matejmosko

> First the shown cores on select box must be relevant to the platform

How do we figure out which platform the game belongs to?

> second they have to be relevant to the game

How do we figure out which game is being played?

**Comment by matejmosko** [comment]
@garbear 
`How do we figure out which platform the game belongs to?`
`How do we figure out which game is being played?`
I am sorry for my poor english, I meant something slightly different. 

1. First filter (preferably on repository level)  should select just usable cores for my system (platform was not right word). I don't need to see beetle-psx or BSNES Acuracy/Balanced (this one I have found out just thanks to this thread. I had no idea which bsnes should I use) on RPi because they are not intended for my system. They are just bloat in the repo for my system.

2. Second step is about the platform. File extension is not very good way to find out what platform the game belongs to (zip files, cue files, iso files etc.) I am not quite sure whether it is possible inside kodi, but would looking at file contents help to determine the platform? I not, there is probably no simple way to make this step work. Therefore the approach should be same as in third step.

3. In the third step we are determining which core of a platform should be used. While the first two steps were "musts", this third should work as a recommendation. The system should offer core that is most probable to work on a system->platform->game basis (just a badge with word "recomended" beside core is enough). This third step can be either crowdsourced on a game basis (but for this a game library has to be implemented in RP) or based on a system of rules (Is this RPi? Ok, choose cores that work best on RPi. Is this SNES? Ok, choose the cores that are best maintained or least updated or etc. The game part is still unusable while there is no game library)

**Pull request merged**
