### PR TITLE
libcec: update imx6 patch to work with p8-platform

### PR DESCRIPTION
**Pull request by vpeter4**

### CODE REVIEW

**Comment by lrusak** [comment]
@vpeter4 can you move the patch into the project specific folder?

**Comment by vpeter4** [comment]
@lrusak: Done.

**Comment by MilhouseVH** [comment]
Now that this imx6 patch is moved to the imx6 project, the following amlogic libcec package patch no longer applies cleanly (which is a problem for all projects, not just imx6):

https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/devel/libcec/patches/libcec-03-amlogic-support.patch

The amlogic patch needs fixing up to take account of the imx6 patch no longer being applied before it - the amlogic patch now fails as follows:
```
patching file README.md
patching file include/cectypes.h
Hunk #2 FAILED at 909.
1 out of 2 hunks FAILED -- saving rejects to file include/cectypes.h.rej
patching file src/libcec/CMakeLists.txt
patching file src/libcec/adapter/AdapterFactory.cpp
Hunk #2 FAILED at 156.
1 out of 3 hunks FAILED -- saving rejects to file src/libcec/adapter/AdapterFactory.cpp.rej
patching file src/libcec/adapter/Amlogic/AmlogicCEC.h
patching file src/libcec/adapter/Amlogic/AmlogicCECAdapterCommunication.cpp
patching file src/libcec/adapter/Amlogic/AmlogicCECAdapterCommunication.h
patching file src/libcec/adapter/Amlogic/AmlogicCECAdapterDetection.cpp
patching file src/libcec/adapter/Amlogic/AmlogicCECAdapterDetection.h
patching file src/libcec/cmake/CheckPlatformSupport.cmake
patching file src/libcec/cmake/DisplayPlatformSupport.cmake
patching file src/libcec/env.h.in
```

The first hunk fails when applying the following patch:
```
@@ -899,7 +899,8 @@
   ADAPTERTYPE_RPI              = 0x100,
   ADAPTERTYPE_TDA995x          = 0x200,
   ADAPTERTYPE_EXYNOS           = 0x300,
-  ADAPTERTYPE_IMX              = 0x400
+  ADAPTERTYPE_IMX              = 0x400,
+  ADAPTERTYPE_AMLOGIC          = 0x500
 } cec_adapter_type;
```
because `ADAPTERTYPE_IMX` is no longer present - it was being added by `libcec-00-imx6-support.patch`, but has somehow been lost in the move:
```
@@ -876,7 +887,8 @@ typedef enum cec_adapter_type
   ADAPTERTYPE_P8_DAUGHTERBOARD = 0x2,
   ADAPTERTYPE_RPI              = 0x100,
   ADAPTERTYPE_TDA995x          = 0x200,
-  ADAPTERTYPE_EXYNOS           = 0x300
+  ADAPTERTYPE_EXYNOS           = 0x300,
+  ADAPTERTYPE_IMX              = 0x400
 } cec_adapter_type;

 /** force exporting through swig */
```
I haven't looked at the second failing hunk, but it's probably similar.

**Comment by gdachs** [comment]
Look at PR 254.

Gerald

**Comment by MilhouseVH** [comment]
Ok thanks - I've merged #254 to resolve this issue.

**Comment by vpeter4** [comment]
I think lrusak merge my pr to early :)

**Pull request merged**
