### PR TITLE
tslib: update to newest version

### PR DESCRIPTION
**Pull request by hevilp**
Please update

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Waiting until 1.15 is released would be preferable to merging a release candidate.

Also, can you use the standard commit/PR naming format when updating a package, ie. "tslib: update to tslib-1.15" etc.

Thanks.

**Comment by vpeter4** [comment]
@hevilp: Did you even tried to build it? I assume no. Because you need to remove patches which are made for old version. And second you need to add ac_cv_func_malloc_0_nonnull to configure.

Also I hope you know that touch service will not work anymore (daemon will not start) - you will get only functional tslib binaries and you will need to start everything from autostart.sh or some new service file.

**Comment by vpeter4** [comment]
Does Kodi supports multi-touch gestures from touchscreen in Linux? My latest test with tslib's ts_uinput daemon shows device as mouse in Kodi:

```
16:00:13.102 T:3016482816   DEBUG: ProcessMouse: unknown mouse command 57605
16:00:13.102 T:3016482816   DEBUG: ProcessMouse: trying mouse action mousedrag
16:00:13.103 T:3016482816   DEBUG: ProcessMouse: unknown mouse command 57606
16:00:15.247 T:3016482816   DEBUG: ProcessMouse: unknown mouse command 57605
16:00:15.247 T:3016482816   DEBUG: ProcessMouse: trying mouse action mousedrag
16:00:15.248 T:3016482816   DEBUG: ProcessMouse: unknown mouse command 57606
16:00:15.383 T:3016482816   DEBUG: ProcessMouse: unknown mouse command 57605
16:00:15.383 T:3016482816   DEBUG: ProcessMouse: trying mouse action mousedrag
16:00:15.383 T:3016482816   DEBUG: ProcessMouse: unknown mouse command 57606
```

**Comment by chewitt** [comment]
@vpeter4 will you address tslib 1.15 in a future touch add-on update or does this PR need to be revised? It looks like 1.15 was released 21 days ago, see: https://github.com/kergoth/tslib/releases

**Comment by vpeter4** [comment]
No, I will not update it to tslib 1.15 because ts_uinput daemon there doesn't work as it should (and my ts_uinput_touch daemon works much better). Because I have limited access to touchscreens (only two special ones) I'm unable to help much.

**Comment by chewitt** [comment]
@vpeter4 thanks for confirming
@hevilp I'm closing the PR as it doesn't appear to be complete or offer benefits

**Pull request closed without merging**
