### PR TITLE
feat: enable webcam driver as kernel module to be consistent with all projects

### PR DESCRIPTION
**Pull request by nicolaspernoud**
Hi,

I am using this for months with a RPI3, without any issues.
It has been enabled for some projects, but not all of them.

Thanks,

### CODE REVIEW

**Comment by chewitt** [comment]
Hi, what's the use-case for a webcam under LE?

**Comment by nicolaspernoud** [comment]
Since docker is enabled, I have a webcam on top on the TV to monitor my home with a mjpg-streamer container. A motion/motion eye container can be used as well to auto detect intruders.

The TV spot is a great place to do so, since the media center is always on, and the TV is generally in the center of homes.

**Comment by nicolaspernoud** [comment]
Hello,
Any news on this PR ? This module is already activated in most projects.

**Comment by MilhouseVH** [comment]
You only need to post the question in one PR! :)

The normal procedure is to test/merge in master first, then backport to `libreelec-9.2` if there are no issues, so the focus of conversation should be in this thread and your other PR doesn't really need to be involved (certainly not at this stage).

Unfortunately this PR is incomplete, as enabling `CONFIG_USB_VIDEO_CLASS` requires additional options to be answered which are not included here. Can you run `make oldconfig` on the kernels with this PR and include the missing options? Or squash the following:

RPi4: http://ix.io/21Ql
Allwinner/aarch64: http://ix.io/21Qm
Allwinner/arm: http://ix.io/21Qn
iMX6: config is rotten but you should be able to work it out

You'll probably need the same changes on the backport.

**Comment by nicolaspernoud** [comment]
Thanks,

I added the missing options on both branches.

Actually we exchanged a few months ago about this : https://github.com/LibreELEC/LibreELEC.tv/pull/3402 . The CONFIG_USB_VIDEO_CLASS_INPUT_EVDEV bit is not useful (no need to get buttons events).

**Pull request merged**
