### PR TITLE
kodi: use sane artistseparators default

### PR DESCRIPTION
**Pull request by HiassofT**
Current kodi default leads to wrong import if artist name
include colons. See http://trac.kodi.tv/ticket/17401

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Shame it's not possible to exclude a separator with `<separator not=true>:</separator>` (or similar), while retaining all other default separators.

And isn't this change removing ; and | as separators in addition to : ? Whenever a custom separator is included in as.xml it clears all existing separators before leading the custom values. So this change is more than just colon.

Colon does seem an odd choice for a default separator, though.

**Comment by MilhouseVH** [comment]
https://github.com/xbmc/xbmc/blob/master/xbmc/settings/AdvancedSettings.cpp#L742-L753

**Comment by HiassofT** [comment]
There are artists with "|" in their name as well - quick search turned up Love|Less. Not sure if there are some with semicolon.

The " feat. ", " ft. " separator seemed useful to me so I kept it. Also itemseparator " / " (blank, slash, blank) is used in addition to that.

Itemseparator was choosen this way (with blanks before and after the slash) so that names like AC/DC wouldn't be split up. Enabling additional separators without blanks around them by default is very odd and unexpected.

IMO if people use some other tagging scheme (" / " has been supported in xbmc/kodi for a long time) they should specifically enable it in their local settings.

**Comment by MilhouseVH** [comment]
The only problem adding this as a default is that it makes LE less "compatible" with plain Kodi and will mean LE produces different database results to Kodi running on any other platform.

For instance, how would music scanning work if a user has MySQL and a mixture of LE and Windows (ie. non-LE) clients? Would some artists be split, and others not, depending on which client scans the artists into the database?

I think it might be best if users were to add this to their own as.xml rather than we add it as a default. And ideally : would be dropped as a default separator from upstream Kodi...

**Comment by HiassofT** [comment]
Good point, hadn't thought about shared/mixed setups before. This could be problematic.

I've posted another comment on trac, trying to explain why I think the additional separators are not a good default, let's see where that goes.

**Comment by HiassofT** [comment]
closing for now, waiting for upstream kodi response

**Pull request closed without merging**
