### PR TITLE
[LE11] Fix issue with incremental screen refreshes on ncurses apps

### PR DESCRIPTION
**Pull request by wagnerch**
Backport of #8244

Build tested.

### CODE REVIEW

**Review by heitbaum — COMMENTED** [review]
Whilst ncurses is not a shared library and these changes would not impact the LE11.0.3 code as it is already shipped. These changes would make it in to a LE11.0.4 image (if one is done.) so on the side of caution - would suggest this is skipped for LE11. I’ll leave the hashmap review to @mglae - as the patch and change where done whilst enabling Wide Characters.

**Comment by wagnerch** [comment]
As you noted it is statically linked, it would also require a bump of addons to get it pushed out.

**Comment by mglae** [comment]
Using hashmap should be safe because of being default on ncurses and is working find from a quick test.

I recommend to include it in nightly LE 11 and release updated addons to satisfy mc users.

**Comment by chewitt** [comment]
@heitbaum @mglae do we pull this into LE11?

**Comment by mglae** [comment]
@chewitt Yes.

With ncurses lib build static the updated e.g. System- and Network-Tools Addons will work on older LE11 systems too.

**Comment by CvH** [comment]
LE12 is out soon, no changes anymore for LE11

**Pull request closed without merging**
