### PR TITLE
lirc cleanup: switch to upstream fixes and configuration

### PR DESCRIPTION
**Pull request by HiassofT**
don't merge yet, this is WIP

Discussion with upstream revealed that several crosscompile issues (yaml, poll, uinput) are already fixed in lircd 0.9.4d and we can use upstream configure methods instead of working around these with downstream patches.

I've also added the proposed upstream fixes from https://sourceforge.net/p/lirc/tickets/264/ (lirc-make-devinput picking up host headers and enabling devinput on the target) so we can test them in LE builds.

@lrusak @Kwiboo @jerome-benoit the downstream lircd patches seem to be originating from you, can you please check if everything's still fine?

Also: what's the purpose of lirc-0002-disable-python3.patch? lirc compiled fine without that patch on Debian Jessie and lircd still worked fine on my RPi2 so not quite sure why we are carrying it.

### CODE REVIEW

**Comment by Kwiboo** [comment]
`lirc-0002-disable-python3.patch` was needed last time I tried to build when python was missing on build host (minimal ubuntu xenial docker container). I will test again if this is still needed.

**Comment by Kwiboo** [comment]
Without `lirc-0002-disable-python3.patch` building lirc without Python 3.1 on host errors out:
```
checking for a Python interpreter with version >= 3.1... none
configure: error: no suitable Python interpreter found
```
From https://www.gnu.org/software/automake/manual/html_node/Python.html
`If action-if-not-found is not specified, as in the following example, the default is to abort configure.`

**Comment by HiassofT** [comment]
I've finished the cleanup and moved compilation and configuration very close to upstream:

lircd and lircd-uinput are now standard systemd units, lircd socket is managed by systemd - like in upstream.

I've kept the .cache/services/lircd.conf ConditionPathExists so enabling lirc via LE settings works as before, but for proper starting/stopping the services (while LE is running) a LE settings update is needed: https://github.com/HiassofT/service.libreelec.settings/commit/03511b348c0ca8ef4024e7541ff4b2b21bed05d2

Common configuration (driver etc) is now handled via lirc_options.conf, the default in /etc can be overridden via //storage/.config.

I've also split the huge combined lircd.conf.* files into separate ones in lircd.conf.d and added a default lircd.conf file which includes all these separate files.

I also had to add a few fixes backported from lirc master branch which can be dropped on the next lirc bump. I've reorganized the patch numbering so that the upstream fixes (which can be dropped) start with 0001 whereas our downstream patches start with 0100.

**Comment by HiassofT** [comment]
this PR survived 2 weeks of testing in milhouse builds, so I'd say this is good to go now!

**Pull request merged**
