### PR TITLE
packages/emulation/*: compile packages for S905

### PR DESCRIPTION
**Pull request by adamg88**
Self explanatory PR

### CODE REVIEW

**Comment by Kwiboo** [comment]
I have something similar in Rockchip, but maybe we should rework this to make use of TARGET_FEATURES related functions and/or TARGET_CPU, something that will also work for rockchip, allwinner and nxp projects.
The imx6 check can probably also be removed.

**Comment by adamg88** [comment]
I agree it's a mess, support is also missing from libretro-ppsspp, libretro-desmume, libretro-reicast, I think @CGarces attempted to rework this some months ago

**Comment by CGarces** [comment]
@Kwiboo @adamg88  please review #2141

Should work for Rockchip, S905 and probably for allwinner. From my point of view this PR is duplicated.

**Comment by adamg88** [comment]
Closing as superseded by #2141

**Pull request closed without merging**
