### PR TITLE
buildsystem: drop/replace PKG_SECTION

### PR DESCRIPTION
**Pull request by InuSasha**
`PKG_SECTION` is unneeded in most packages.

it has two functions, and both has nothing to do with the location in package-tree.
And this both function can conflict with each other, when a addon package is a virtual package, too.

Both functions are replaced, by more understandable solution.
* maker as virtual package -> moved to `PKG_TOOLCHAIN` as `virtual`
* addon section (place in the addon repository) -> replaced by new `PKG_ADDON_SECTION`

@islipfd19 @MilhouseVH are there problems with jenkins?
When yes: how can i help, to solve this.

Build tested for Generic and RPi2

### CODE REVIEW

**Comment by islipfd19** [comment]
Removing PKG_SECTION from package.mk will break Jenkins. It's how Jenkins knows how to build the directory path for the add-on and filename. Please don't remove this.

**Comment by InuSasha** [comment]
it is only relevant for addons? Can jenkins use `PKG_ADDON_SECTION` instead?

**Comment by islipfd19** [comment]
No, because not all add-ons have that. PKG_SECTION is included in every add-on and provides the directory path structure of where the addins get zipped to.

**Comment by CvH** [comment]
superseded by https://github.com/LibreELEC/LibreELEC.tv/pull/3035

**Pull request closed without merging**
