### PR TITLE
libretro-pcsx-rearmed: fix PCSX ReARMed build

### PR DESCRIPTION
**Pull request by KOPRajs**
The _game.libretro.pcsx-rearmed_ addon is currently broken and is crashing Kodi in both _master_ and _libreelec-9.2_ branches. The build needs to be adapted to the changes in the upstream Makefile.libretro:
https://github.com/libretro/pcsx_rearmed/commit/3d96277d011b4d683d682740eed61b1113a613b1

Fixes https://github.com/LibreELEC/LibreELEC.tv/issues/4431

This PR needs to be applied also to the _libreelec-9.2_ branch but I'm not sure how to do it correctly.

I'm also not sure how to get rid of the _Merge pull request #1_ commit, sorry. You can cherry-pick only the _5a1fe82_.

### CODE REVIEW

**Comment by chewitt** [comment]
The main mistake is working in the `master` branch not a seperate "topic" branch. If you are using git from the commands line the following sequence should clean things up:

```
git checkout master
git fetch upstream/master
git reset --hard upstream/master
git checkout -b fix-pcsx-rearmed
git cherry-pick 5a1fe82388d798a0a8bf18ecb39b60ef87059ea0
git push origin fix-pcsx-rearmed
```

Now visit this page and "edit" the PR (top right) and select the `fix-pcsx-rearmed` branch (instead of master) and the PR should only see a single request. The way to remove "merge" commits it to rebase (git rebase master) but you cannot rebase your changes against the master branch because you're already working on (in) the master branch. If you are unable to change the branch, close this PR and open a new one - and the new one will have only the single commit.

To send the same PR to 9.2:

```
git checkout libreelec-9.2
git fetch upstream/libreelec-9.2
git reset --hard upstream/libreelec-9.2
git checkout -b fix-pcsx-rearmed-92
git cherry-pick 5a1fe82388d798a0a8bf18ecb39b60ef87059ea0
git push origin fix-pcsx-rearmed-92
```

If you're lucky the `cherry-pick` will also work on the 9.2 branch. If not you'll need to repeat the same changes and make a fresh commit. After pushing to origin you can visit either the LE pull-requests page or your fork of our repo, and follow the "make pull request" prompts. By default it will try to send the PR to master, but this will be flagged as un-mergeable. If you select the libreelec-9.2 branch it should flag as mergeable and you can give it a title/description/etc. and continue.

If you're working in some fancy git client designed to make things easier .. the process is the same but no idea what or how you do things. One of the main benefits of "doing it the hard way" is .. it's massively easier to get help :)

See how you get

**Comment by CvH** [comment]
I have tested it and the addon is not working at generic (but the binary don't crash).
Can someone point me to a combination/rom that should just work ? Not sure I use the emulator right, or not.
Bios files where placed according to the messy Kodi wiki `and its BIOS file must be placed in the system folder on your emulator software (libretro cores in this case)`  -> `/.kodi/userdata/addon_data/game.libretro.pcsx-rearmed/system/`.

**Comment by KOPRajs** [comment]
The correct path for the BIOS files should be:
_/storage/.kodi/userdata/addon_data/game.libretro.pcsx-rearmed/resources/system/_

MD5:
_CoreELEC:~/.kodi/userdata/addon_data/game.libretro.pcsx-rearmed/resources/system # md5sum *
8dd7d5296a650fac7319bce665a6a53c  scph5500.bin
490f666e1afb15b7362b406ed1cea246  scph5501.bin
32736f17079d0b2b7024407c39bd3050  scph5502.bin
1e68c231d0896b7eadcad1d7d8e76129  scph7001.bin_

If you want more help or links, please send me an email to zdenek.koprivik@post.cz.

Please note that it is a known problem that the current x86 build with the new Lightrec dynarec doesn't work at all without BIOS file. It is already fixed in upstream by disabling the use of the dynarec when no BIOS file is detected but we need to wait until Kodi-game addons gets updated for this to work, see here:
https://github.com/libretro/pcsx_rearmed/commit/44747c73cf572febe81ff687c81548ce5b5de493

I'll try to update the PR as suggested by @chewitt. I hope to have some time for it tomorrow.

**Comment by KOPRajs** [comment]
I have created the new branch as suggested:
https://github.com/KOPRajs/LibreELEC.tv/tree/fix-libretro-pcsx-rearmed

But I cannot change the source branch of this PR. I can only change the target branch, not the source branch. Am I doing something wrong? Should I close this PR and create a new one?

**Pull request closed without merging**
