### PR TITLE
[le10] kodi-binary-addons: update to latest versions

### PR DESCRIPTION
**Pull request by heitbaum**
- pvr.hdhomerun: update 19.0.0-Matrix to 19.0.1-Matrix
- pvr.waipu: update 19.0.2-Matrix to 19.1.0-Matrix

### CODE REVIEW

**Review by CvH — APPROVED** [review]

**Comment by flubshi** [comment]
Will binary add-ons automatically be pushed to the repo or will the add-ons only get updated on a new LE Release?

**Comment by CvH** [comment]
currently its still a semi manual thing, someone needs to press the button at jenkins and then press another button at the addon server

**Comment by CvH** [comment]
pushed all add-ons to current state at the addon server

**Comment by flubshi** [comment]
Thanks a lot!

**Pull request merged**
