### PR TITLE
xorg-server: update to 1.19

### PR DESCRIPTION
**Pull request by lrusak**
This is a rather large bump. Many other x11 libs needed to be updated for this bump.

I have also enabled threaded input support.

We need to wait to see if nvidia puts out a new driver with support for 1.19
The other drivers should be ok.

### CODE REVIEW

**Comment by escalade** [comment]
Works great on my NUC. Even got mouse pointer visible in VNC, which I'm pretty sure wasn't before.

**Comment by piotrasd** [comment]
please make sync of this 2 files 
mesa has updates pci-ids for Kaby lake and Apollo lake in xorge server still some are missing
https://cgit.freedesktop.org/mesa/mesa/tree/include/pci_ids/i965_pci_ids.h

https://cgit.freedesktop.org/xorg/xserver/tree/hw/xfree86/dri2/pci_ids/i965_pci_ids.h

**Comment by lrusak** [comment]
@piotrasd thanks! added

**Comment by lrusak** [comment]
Rebased for 1.19.0 release. Hopefully nvidia will release a driver soon.

**Comment by escalade** [comment]
libX11 needs autoreconf now, complains about missing automake-1.14.

**Comment by piotrasd** [comment]
@lrusak please try build nvidia driver with 
"-ignoreABI"

**Comment by lrusak** [comment]
@piotrasd we need both nvidia drivers to build/run so we have to wait :)

**Comment by lrusak** [comment]
updated ati and amdgpu drivers to their released versions.

**Comment by lrusak** [comment]
pushed xf86-video-nvidia update to 375.20

now we are just waiting for nvidia-legacy to be updated.

**Comment by lrusak** [comment]
@MilhouseVH rebased

**Comment by piotrasd** [comment]
there is also libdrm 2.4.74 ;)

**Comment by piotrasd** [comment]
intel driver we should bump
commit: sna: Handle xf86Randr12 gamma changes in xorg-xserver-1.19
https://cgit.freedesktop.org/xorg/driver/xf86-video-intel/commit/?id=9ac7a3370ab265d4cbdbbf3dc588af88c37048e1

**Comment by lrusak** [comment]
thanks @piotrasd I updated it in #1006

**Comment by MilhouseVH** [comment]
Should be safe to merge after #1059.

**Pull request merged**
