### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by lrusak**
thanks @vpeter4 and @cvh

### CODE REVIEW

**Comment by MilhouseVH** [comment]
https://gist.github.com/MilhouseVH/8dd78665a3c6ffef9b77 for the other two RTL* annoyances.

**Comment by lrusak** [comment]
added, thanks @MilhouseVH

**Comment by HiassofT** [comment]
Please revert the _sysconfigdata commit https://github.com/LibreELEC/LibreELEC.tv/pull/14/commits/70ee30ebf92754e333eee3fd72a79c239b7ec4fd kodi and hyperion won't start here (RPi3) otherwise
http://sprunge.us/ARTY

With that commit removed everything seems to be running fine!

**Comment by MilhouseVH** [comment]
> Please revert the _sysconfigdata commit 70ee30e 

Reverted by #20

**Pull request merged**
