### PR TITLE
go: add support for /usr/local host installations

### PR DESCRIPTION
**Pull request by arthur-liberman**
fix build when compiling on arm/aarch64

### CODE REVIEW

**Comment by arthur-liberman** [comment]
Building `go` on my Ubuntu Server 20.04 LTS fails because the go version is too old (1.13.8) and this package requires at least go 1.17.
Go installation instructions state to place it in ``. That's what I did, and following the changes in this PR the build succeeded.
In addition, add support for compiling on host platforms other than `x86_64`.

**Comment by heitbaum** [comment]
> Hi. I build directly on the OS without using docker.

Understood - Commands are the same for OS. Uninstall the old go-1.13 and then you will be able to use the Ubuntu 1.18 release.

```
apt-get install golang-1.18-go
ln -s /usr/lib/go-1.18 /usr/lib/go
```

should get you going.

**Review by heitbaum — CHANGES_REQUESTED** [review]
Now that I have got an aarch64 build host, and the build errors for the other packages are addressed and can build all images and all addons. Wanted to check into this closer. 

This `export GOARCH=amd64` line is incorrect on a non `x86_64` build host. Output shows that in addition to the host architecture - it creates the target amd64 architecture `go` binary (not as intended.)
```
Building packages and commands for host, linux/arm64.
Building packages and commands for target, linux/amd64.
```

```
docker@6a24df6aa4ae:/home/ubuntu/LibreELEC.tv$ find build.LibreELEC-AMLGX.arm-12.0-devel/toolchain/lib/golang/bin/
build.LibreELEC-AMLGX.arm-12.0-devel/toolchain/lib/golang/bin/
build.LibreELEC-AMLGX.arm-12.0-devel/toolchain/lib/golang/bin/gofmt
build.LibreELEC-AMLGX.arm-12.0-devel/toolchain/lib/golang/bin/linux_amd64
build.LibreELEC-AMLGX.arm-12.0-devel/toolchain/lib/golang/bin/linux_amd64/gofmt
build.LibreELEC-AMLGX.arm-12.0-devel/toolchain/lib/golang/bin/linux_amd64/go
build.LibreELEC-AMLGX.arm-12.0-devel/toolchain/lib/golang/bin/go

docker@6a24df6aa4ae:/home/ubuntu/LibreELEC.tv$ build.LibreELEC-AMLGX.arm-12.0-devel/toolchain/lib/golang/bin/linux_amd64/go
bash: build.LibreELEC-AMLGX.arm-12.0-devel/toolchain/lib/golang/bin/linux_amd64/go: cannot execute binary file: Exec format error

docker@6a24df6aa4ae:/home/ubuntu/LibreELEC.tv$ file build.LibreELEC-AMLGX.arm-12.0-devel/toolchain/lib/golang/bin/linux_amd64/go
build.LibreELEC-AMLGX.arm-12.0-devel/toolchain/lib/golang/bin/linux_amd64/go: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=kXtfudQ_ucmsBvDTQTFs/SoYrnoayOSJ37etLZJhj/OKjs2HlbXdLgPRwdVWtq/ZjFxMoCwdM58n8JYV4WY, with debug_info, not stripped
```

This GOARCH line should be replaced as per the case statement but using MACHINE_HARDWARE_NAME not ARCH. But based on the ref docs and a quick test - dropping GOOS and GOARCH from configure_host() might be the way to forward? As below. 
```
diff --git a/packages/addons/addon-depends/go/package.mk b/packages/addons/addon-depends/go/package.mk
index c54077fd89..397420a9e8 100644
--- a/packages/addons/addon-depends/go/package.mk
+++ b/packages/addons/addon-depends/go/package.mk
@@ -13,14 +13,12 @@ PKG_LONGDESC="An programming language that makes it easy to build simple, reliab
 PKG_TOOLCHAIN="manual"
 
 configure_host() {
-  export GOOS=linux
   export GOROOT_FINAL=${TOOLCHAIN}/lib/golang
   if [ -x /usr/lib/go/bin/go ]; then
     export GOROOT_BOOTSTRAP=/usr/lib/go
   else
     export GOROOT_BOOTSTRAP=/usr/lib/golang
   fi
-  export GOARCH=amd64
 
   if [ ! -d ${GOROOT_BOOTSTRAP} ]; then
     cat <<EOF
```
Output after dropping GOOS and GOARCH on aarch64 build host. I haven’t tested other build hosts nor run the Add-on builds.
```
BUILD      go (host)
    TOOLCHAIN      manual
Building Go cmd/dist using /usr/lib/go. (go1.18.1 linux/arm64)
Building Go toolchain1 using /usr/lib/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/arm64.
…
```
Ref doco: https://www.digitalocean.com/community/tutorials/building-go-applications-for-different-operating-systems-and-architectures

**Comment by heitbaum** [comment]
Hi @arthur-liberman - just following up if you can update the pr to remove the “export GOARCH” / “GOOS”. The /usr/local is GtG.

**Comment by arthur-liberman** [comment]
@heitbaum Sorry, not sure what you mean.
Do you mean that the switch\case for setting the GOARCH in my PR needs to be removed or the IF/ELSE for the go paths?

**Comment by heitbaum** [comment]
> @heitbaum Sorry, not sure what you mean. Do you mean that the switch\case for setting the GOARCH in my PR needs to be removed or the IF/ELSE for the go paths?

The case statement please. Your /usr/local is all good. 

Based on the testing and documentation https://github.com/heitbaum/LibreELEC.tv/commit/e864caec5aad907e3ee8a6deb1a843f9ae1d6b1c builds both the required host and target **go**

**Comment by arthur-liberman** [comment]
@heitbaum Ok, does it look ok now?

**Review by heitbaum — APPROVED** [review]

**Comment by heitbaum** [comment]
> @heitbaum Ok, does it look ok now?

Thanks. Merged.

**Pull request merged**
