### PR TITLE
u-boot: build second u-boot package for imx6 project

### PR DESCRIPTION
**Pull request by vpeter4**
everything is installed from main u-boot package (files from second package is copied there)
needed for different systems

For better organization of this two packages I'm open for suggestions. But this one is working for me for a long time.

### CODE REVIEW

**Comment by Kivutar** [comment]
I took a look at it, and it's the best solution for now.

Before thatin OE, we could have a single u-boot package with a mrproper call. But since we switched to the mainline u-boot, we need those two packages because udoo is not yet supported by u-boot mainline.

An alternative would be to remove build*/u-boot* each time we build if SYSTEM is set and unpack the appropriate u-boot.

We can also come back to the old u-boot used in OE that was compatible with both solidrun and udoo. I'm not sure why the switch to mainline u-boot was necessary. I guess it was to support a newer kernel for solidrun?

**Comment by vpeter4** [comment]
This different u-boot is actually used for udoo (which I add SPL support in mainline - one image to support both dual and quad boards).
Original u-boot is used by solidrun.
I have no intent to go back :)

**Comment by Kivutar** [comment]
So we should just merge this :)

**Comment by Kivutar** [comment]
We can also split the imx6 project in separate projects. Most of the time, merging projects leads to this kind of issues and makes the code ugly. It sure save disk space, but disk space is so cheap these days.

**Comment by vpeter4** [comment]
No, splitting would be wrong approach. Kernel already supports all the systems but obviously bootloader is not the same. If this proposed solution is not good then someone should propose something else how to have multiple u-boot packages (or other in general).

But if this is not acceptable then split if you want. But I personally will keep them in one project for my images.

**Comment by Kivutar** [comment]
I follow you, as long as it works.

**Comment by vpeter4** [comment]
I did some re-thinking and come to better/cleaner solution. Now second u-boot is dependency of main one. Both packages are build independently as all other packages are. Build files stays in it's own build folder and are copied to image directly from there (files are not copied to main u-boot folder).

**Comment by chewitt** [comment]
Neither @lrusak or I can come up with something better. It has been mentally tagged as "ugly" and should be revisited again in the future :)

**Comment by vpeter4** [comment]
I see it quite clean actually. The only "hack" is with copying files from both build folders and using wildcard with base package name.

**Pull request merged**
