### PR TITLE
netbase: initial package

### PR DESCRIPTION
**Pull request by CvH**
current iana version version is from 2008
`protocols` is 25kb
`services` 750kb

new version is from ubuntu 17.04 release (if it is good enough for ubuntu ...)
`protocols` is 3kb
`services` 19kb

changed package to `netbase`

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Not sure I'm qualified to approve this, to be honest. Ping @lrusak?

What about https://github.com/Mic92/iana-etc as a source, as used by [NixOS](https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/misc/iana-etc/default.nix#L8)?

**Comment by CvH** [comment]
@MilhouseVH pure guess for review ;) 
Mic92/iana-etc is 20x in size (even its "just" kb), same for amylum/iana-etc

The ubuntu one was the smallest i could find. It is good enough for ubuntu server so I guess it is safe to assume that it is good enough for us too.

**Comment by MilhouseVH** [comment]
OK I'll add this to tonight's test builds (along with the tz bump)

**Comment by vpeter4** [comment]
What about preparing it from direct source like arch is doing? [link](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/iana-etc)
And having mkpkg_iana_etc script.

**Comment by CvH** [comment]
@vpeter4 this is 20x the size of the ubuntu one, ofc I would prefer some direct source - but I haven't found it for Ubuntu or other OS that offers an "small" version of the file.

**Comment by vpeter4** [comment]
Then why not use directly file http://archive.ubuntu.com/ubuntu/pool/main/n/netbase/netbase_5.4.tar.xz and avoid repacking.

**Comment by CvH** [comment]
@vpeter4 tx fixed :)

**Comment by stefansaraev** [comment]
what about renaming the package from iana-etc to netbase /me runs

**Comment by CvH** [comment]
@stefansaraev I thought the same, but "netbase.zip" includes basically the iana db + some debian magic ... I am really lost what is there the best way to go here - if noone has a preference I keep the current.

**Comment by vpeter4** [comment]
I think @stefansaraev mentioned above because of [this](https://github.com/stefansaraev/TB/blob/master/packages/base/netbase/package.mk) :)

**Comment by lrusak** [comment]
I would just do it like seo has it.

**Comment by CvH** [comment]
updated to netbase

**Comment by MilhouseVH** [comment]
Looks good (contents of netbase is identical to iana-etc). Let's test build it for a couple more days to be sure.

**Comment by stefansaraev** [comment]
the rpcbind sed hack feels like hack ;)

if rpcbind is not [assigned](http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt) that means some ugly userspace is doing the wrong thing (or it did in the past, but not anymore, who knows). you should drop that hack /me runs ;)

**Comment by CvH** [comment]
@stefansaraev are you confident that it breaks nothing we should care about ?
After your comment I googled a bit and found some relation with transmission - maybe this was a fix tm long time ago.

The commit message for this "**fix**" is useless https://github.com/LibreELEC/LibreELEC.tv/commit/4640084f296214c780dbd135cd5ba5bc97b1fd4d so I didn't opened pandora's box :)

**Comment by HiassofT** [comment]
I also vote for dropping "fix" - use the file as it's in Debian and Ubuntu.

BTW: and I'd also suggest sourcing the package from Debian (like @stefansaraev does), as that seems to be the original source - Ubuntu's .dsc is referring to Debian's git :)
http://archive.ubuntu.com/ubuntu/pool/main/n/netbase/netbase_5.4.dsc

**Comment by stefansaraev** [comment]
I am pretty sure it breaks nothing. or the same thing would appear broken on all other linux distributions :)

if you can mount nfs shares via ssh using busybox mount - all good (isn't that the only purpose of rpcbind in LE), if not - there is something wrong somewhere else happening.

**Comment by CvH** [comment]
dropped "fix" and changed to debian
@stefansaraev tx for clarification
@HiassofT changed to debian (ubuntu has the hash identical archive)

**Pull request merged**
