### PR TITLE
lirc: update to 0.10.0

### PR DESCRIPTION
**Pull request by HiassofT**
Don't merge yet, wait until lirc 0.10.0 final is released.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
@HiassofT would you mind rebasing this after the sha256 change? The new sha needs to be:
```
PKG_SHA256="86206d7c68af855225e91f852fdd0d0b9a92591e06757534cc6c546818fab89b"
```

**Comment by HiassofT** [comment]
rebased and set sha256

**Comment by HiassofT** [comment]
Lirc 0.10.0 final just got released https://sourceforge.net/p/lirc/mailman/message/35993192/

Updated package.mk to final version and rebased on top of master branch. build and runtime tested on RPi3.

But let's give this a few more days of testing in milhouse builds before merging, just in case.

**Comment by MilhouseVH** [comment]
Good to go?

**Comment by HiassofT** [comment]
yes, press the button!

**Pull request merged**
