### PR TITLE
Enable VLAN support for RK3328.

### PR DESCRIPTION
**Pull request by rdorsch**
chewitt proposed in the #libreelec IRC channel at 18-11-2022 to do a test build with a VLAN_8021Q as kernel module and check if VLAN support is working if this module is available.

The module is smaller then 44kB (uncompressed), i.e. the change of the compressed image size is insignificant.

I submitted the patch on master, but it should also be applied on the libreelec-10.0 branch.

This is my first pull request I ever generated on github, please let me know, if I did something wrong.

Many thanks
Rainer

### CODE REVIEW

**Comment by chewitt** [comment]
@rdorsch: please apply the same config change to all linux confs (so all devices have the same capabilities), and change the git commit message to `linux: enable VLAN support` to keep with our normal `package: description of change` style.

**Comment by rdorsch** [comment]
@chewitt: The situation is currently quite heterogeneous:

There are architectures with VLAN_8021Q configured unconditionally in (e.g. Dragonboard), configured as module (e.g. Allwinner or Amlogic), or disabled (e.g. RK3328). Most of the devices have it configured as module today.
```

rd@master:~/git/LibreELEC.tv$ find -name linux.*.conf -exec grep --with-filename VLAN_8021Q \{\} \;|grep -v VRP
./projects/Allwinner/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=m
./projects/Allwinner/linux/linux.arm.conf:CONFIG_VLAN_8021Q=m
./projects/Amlogic/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=m
./projects/Generic/linux/linux.x86_64.conf:CONFIG_VLAN_8021Q=m
./projects/NXP/devices/iMX6/linux/linux.arm.conf:CONFIG_VLAN_8021Q=y
./projects/NXP/devices/iMX8/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=m
./projects/Qualcomm/devices/Dragonboard/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=y
./projects/RPi/devices/RPi/linux/linux.arm.conf:CONFIG_VLAN_8021Q=m
./projects/RPi/devices/RPi2/linux/linux.arm.conf:CONFIG_VLAN_8021Q=m
./projects/RPi/devices/RPi4/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=m
./projects/Rockchip/devices/RK3288/linux/default/linux.arm.conf:# CONFIG_VLAN_8021Q is not set
./projects/Rockchip/devices/RK3328/linux/default/linux.aarch64.conf:CONFIG_VLAN_8021Q=m
./projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf:# CONFIG_VLAN_8021Q is not set
./projects/Samsung/linux/linux.arm.conf:# CONFIG_VLAN_8021Q is not set
rd@master:~/git/LibreELEC.tv$ 
```

How do you want to proceed? Configuring it as module where it is not configured today, i.e. on these devices

```
rd@master:~/git/LibreELEC.tv$ find -name linux.*.conf -exec grep --with-filename VLAN_8021Q \{\} \;|grep -v VRP|grep "not set"
./projects/Rockchip/devices/RK3288/linux/default/linux.arm.conf:# CONFIG_VLAN_8021Q is not set
./projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf:# CONFIG_VLAN_8021Q is not set
./projects/Samsung/linux/linux.arm.conf:# CONFIG_VLAN_8021Q is not set
rd@master:~/git/LibreELEC.tv$ 
```

?

I am somewhat hesitant to configure it as module where it is enabled today:

rd@master:~/git/LibreELEC.tv$ find -name linux.*.conf -exec grep --with-filename VLAN_8021Q \{\} \;|grep -v VRP|grep "=y"
./projects/NXP/devices/iMX6/linux/linux.arm.conf:CONFIG_VLAN_8021Q=y
./projects/Qualcomm/devices/Dragonboard/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=y
rd@master:~/git/LibreELEC.tv$ 


Should I break it into two commits, one for the architectures in le10 and one for the remaning one? Then it would be easy to cherry-pick a commit to apply the change to le10.

Thanks
Rainer

**Comment by heitbaum** [comment]
> @chewitt: The situation is currently quite heterogeneous:
> 
> There are architectures with VLAN_8021Q configured unconditionally in (e.g. Dragonboard), configured as module (e.g. Allwinner or Amlogic), or disabled (e.g. RK3328). Most of the devices have it configured as module today.
> 
> ```
> 
> rd@master:~/git/LibreELEC.tv$ find -name linux.*.conf -exec grep --with-filename VLAN_8021Q \{\} \;|grep -v VRP
> ./projects/Allwinner/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=m
> ./projects/Allwinner/linux/linux.arm.conf:CONFIG_VLAN_8021Q=m
> ./projects/Amlogic/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=m
> ./projects/Generic/linux/linux.x86_64.conf:CONFIG_VLAN_8021Q=m
> ./projects/NXP/devices/iMX6/linux/linux.arm.conf:CONFIG_VLAN_8021Q=y
> ./projects/NXP/devices/iMX8/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=m
> ./projects/Qualcomm/devices/Dragonboard/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=y
> ./projects/RPi/devices/RPi/linux/linux.arm.conf:CONFIG_VLAN_8021Q=m
> ./projects/RPi/devices/RPi2/linux/linux.arm.conf:CONFIG_VLAN_8021Q=m
> ./projects/RPi/devices/RPi4/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=m
> ./projects/Rockchip/devices/RK3288/linux/default/linux.arm.conf:# CONFIG_VLAN_8021Q is not set
> ./projects/Rockchip/devices/RK3328/linux/default/linux.aarch64.conf:CONFIG_VLAN_8021Q=m
> ./projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf:# CONFIG_VLAN_8021Q is not set
> ./projects/Samsung/linux/linux.arm.conf:# CONFIG_VLAN_8021Q is not set
> rd@master:~/git/LibreELEC.tv$ 
> ```
> 
> How do you want to proceed? Configuring it as module where it is not configured today, i.e. on these devices
> 
> ```
> rd@master:~/git/LibreELEC.tv$ find -name linux.*.conf -exec grep --with-filename VLAN_8021Q \{\} \;|grep -v VRP|grep "not set"
> ./projects/Rockchip/devices/RK3288/linux/default/linux.arm.conf:# CONFIG_VLAN_8021Q is not set
> ./projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf:# CONFIG_VLAN_8021Q is not set
> ./projects/Samsung/linux/linux.arm.conf:# CONFIG_VLAN_8021Q is not set
> rd@master:~/git/LibreELEC.tv$ 
> ```
> 
> ?
> 
> I am somewhat hesitant to configure it as module where it is enabled today:
> 
> ```
> rd@master:~/git/LibreELEC.tv$ find -name linux.*.conf -exec grep --with-filename VLAN_8021Q \{\} \;|grep -v VRP|grep "=y"
> ./projects/NXP/devices/iMX6/linux/linux.arm.conf:CONFIG_VLAN_8021Q=y
> ./projects/Qualcomm/devices/Dragonboard/linux/linux.aarch64.conf:CONFIG_VLAN_8021Q=y
> rd@master:~/git/LibreELEC.tv$ 
> ```
> 
> Should I break it into two commits, one for the architectures in le10 and one for the remaning one? Then it would be easy to cherry-pick a commit to apply the change to le10.
> 
> Thanks Rainer

Go with module on all. Dragonboard is current not building and iMX6 will be fine with =m

**Comment by chewitt** [comment]
> Should I break it into two commits, one for the architectures in le10 and one for the remaning one?

One commit for changes in master would be preferred, and a second PR to LE10 branch if you want the changes there

**Comment by chewitt** [comment]
@rdorsch use something like `linux: enable and unify VLAN_8021Q support over all projects/devices` for the commit message; we require the `package: description of changes` format. Thanks.

**Comment by heitbaum** [comment]
Why MVRP and GVRP?

also please update the commit message - as per - https://github.com/LibreELEC/LibreELEC.tv/pull/7228#issuecomment-1345297651

**Comment by rdorsch** [comment]
> @rdorsch use something like `linux: enable and unify VLAN_8021Q support over all projects/devices` for the commit message; we require the `package: description of changes` format. Thanks.

Thanks, I did not realize that this convention is in place :-)

**Comment by rdorsch** [comment]
> Why MVRP and GVRP?

It was enabled in Allwinner and disabled in all other architectures. I concluded there must be a usecase for it.

I thought that configuring it as module probably works for all architectures.

https://www.kernelconfig.io/config_vlan_8021q_gvrp
https://www.kernelconfig.io/config_vlan_8021q_mvrp

On my setup, I do not see any drawbacks without GVRP and MVRP, I can also 
- disable it consistently or (but this might cause a regression on Allwinner)
- leave it as it is ( but this is inconsistent across platforms).

I did not expect that in some architectures there was not GVRP and MVRP in the config options at all (e.g. 3328).

Please wait with merging until I have done another build on RK3328 to check that MVRP and GVRP at least compile without any issues.

**Comment by heitbaum** [comment]
> > Why MVRP and GVRP?
> 
> It was enabled in Allwinner and disabled in all other architectures. I concluded there must be a usecase for it.
> 
> I thought that configuring it as module probably works for all architectures.
> 
> https://www.kernelconfig.io/config_vlan_8021q_gvrp https://www.kernelconfig.io/config_vlan_8021q_mvrp
> 
> On my setup, I do not see any drawbacks without GVRP and MVRP, I can also
> 
> * disable it consistently or (but this might cause a regression on Allwinner)
> * leave it as it is ( but this is inconsistent across platforms).
> 
> I did not expect that in some architectures there was not GVRP and MVRP in the config options at all (e.g. 3328).
> 
> Please wait with merging until I have done another build on RK3328 to check that MVRP and GVRP at least compile without any issues.

I think a previous miss. MVRP and GVRP are used on network switches to propagate dynamic clan configuration information. Shouldn’t be enabled on “edge devices” - unless there was a specific use case -  but don’t think so in the LE case.

**Comment by jernejsk** [comment]
> It was enabled in Allwinner and disabled in all other architectures. I concluded there must be a usecase for it.

Not really. Usually configuration is based on some defconfig from kernel and has options set that they are not needed by LE. There are too much options to check so not useful options can fall through.

As @heitbaum said, it doesn't make sense to have them enabled, so you can disable them in AW configuration too.

**Comment by rdorsch** [comment]
I updated the commit, but I have some side effects, with other commits which I do not understand. I try to resolve this, in the worst case I open another pull request.

**Comment by rdorsch** [comment]
I created a new branch rdorsch/unify_VLAN_8021Q_support from master which cherry-picked my commit from the rdorsch:rdorsch/VLAN_support_for_RK3328 w/o the side effects on other commits.

Has anybody some objections, if I open a new pull request and link them through mentioning the other pull request in the comments?

Alternatively, I need some advice how to clean up this one.

**Comment by jernejsk** [comment]
Don't worry about branch name. Please disable GVRP and MVRP. As @heitbaum stated, it doesn't make sense and it's not turned on for AW intentionally.

**Comment by rdorsch** [comment]
It seems the pull request did not survive the branch renaming although I used the github UI :-/

I opened a new one:

https://github.com/LibreELEC/LibreELEC.tv/pull/7231

**Pull request closed without merging**
