### PR TITLE
Package coding standard cleanup

### PR DESCRIPTION
**Pull request by antonlacon**
This PR is an automated pass over the package feed to make the following changes:

```
`command` -> $(command)
$VARIABLE -> ${VARIABLE}
$VARIABLE="$VARIABLE stuff" -> $VARIABLE+=" stuff"
if [ test ] ; -> if [ test ];
```
It touches nearly 800 packages, so I'm thinking it's best merged for LE11 (or whatever LE10+1 is named), but it does apply now. I am using it with my image. Scripting `tools/fixlecode.py` powered the automation.

### CODE REVIEW

**Comment by CvH** [comment]
We should merge this (if okay) before LE10 ships, otherwise backports are getting complicated.
Function wise there should be no difference so the outcome should be 1:1 the same.
But my bash foo is not good enough to properly review this (looks okay for me).

**Comment by HiassofT** [comment]
I'd also say now, before we ship the first alpha, would be a good time to get this treewide cleanup in.

From a quick glance the changes look fine

**Comment by heitbaum** [comment]
I’m happy for it to go in now. I can rebase any outstanding packages that haven’t been merged yet. I don’t have any packages in my local tree anyhow - so all ok.

**Comment by CvH** [comment]
@antonlacon rebase pls

**Comment by antonlacon** [comment]
Rebased.

**Review by HiassofT — APPROVED** [review]
RPi4 clean build and runtime tests looked good

**Pull request merged**
