### PR TITLE
Revert 32-bit Y2038 changes

### PR DESCRIPTION
**Pull request by HiassofT**
The sledge-hammer approach taken in #6727 , forcing `-D_FILE_OFFSET_BITS=64` and `-D_TIME_BITS=64"` onto all packages, was a very bad idea as it didn't fix any actual problem we have right now but created lots of new problems like the need for additional patches that were rejected upstream https://sourceforge.net/p/lirc/git/merge-requests/46/#0e6a and broken zip https://github.com/LibreELEC/LibreELEC.tv/issues/6858 and DVD playback https://forum.libreelec.tv/thread/26050-dvd-playback-issue/?postID=174272#post174272

Clearly this was the wrong approach, potential Y2038 or large file issues need to be fixed on a case-by-case basis, and we don't know what else might be broken. So it's best to revert all those changes.

I'm creating this as a draft as we need to check for other patches that we added as a result of the Y2038 change and should now be dropped, too, so we don't carry over unnecessary cruft.

We also need to bump the addon repo version and rev-bump all kodi addons so they get rolled out - I'll add those shortly before merging this PR to avoid merge conflicts. Very likely this will result in kodi crashes due to binary addon incompatibility again, like we had with #6727, but there's not much we can do about it.

So far I've reverted all changes of #6727 except for the eventlircd patch. This patch later got replaced with an eventlircd update that included the change. I'm not reverting it because it's OK for us as we won't be running the latest eventlircd on ancient kernels.

I've also dropped the ZIP fix change https://github.com/LibreELEC/LibreELEC.tv/pull/6863 as it's no longer needed and very likely won't work as is.

Please let me know if you identified other changes that we can or should drop. I'm looking through the change since #6727 got merged but a few additional pairs of eyes would help a lot as it's easy to miss something.

### CODE REVIEW

**Comment by HiassofT** [comment]
RPi4 image build and RPi4 scripts/create_addon build both succeeded, that latter with the same 2 failing addons as before (audiodecoder.fluidsynth and visualization.fishbmc - nothing new here).

After update to the new image kodi crashed in pvr.hts - as expected and also as before when we merged the y2038 changes

DVD playback now works fine, tested with my Monty Python's Flying Circus DVDs

**Comment by heitbaum** [comment]
Can you please drop these reverts - as they are correct and will be merged upstream sooner or later in that they follow the kernel 4.16 > (for both 32bit and 64bit builds)
- 649b909742e3802662e8bd65ec399344d4344652
- 621b0e657aff16553f9d9bf50eed3c313d39142f
- 755f404f1be73b5dad2f3f3e6b83f5086b3d6b7d

- reverting zlib I am happy with (these patches can be improved) 
  - still wip upstream 
  - but probably correct regardless. 
- need to test zip if -D_FILE_OFFSET_BITS=64 is not defined 
  - I believe the fix is probably correct though.

for reverts for: glibc, mariadb, libretro-fbneo - no issue either way. They can be reverted or not / as they are only “active” when config/arch.arm included `-D_TIME_BITS=64` and `-D_FILE_OFFSET_BITS=64`

Would like to see the test with only 0ed423a29f9c9221b6cb2fd55b61bbc87ea1f883 reverted.

going to have a look at the `libdvdcss` separately and find out why it might have been upset.

**Comment by HiassofT** [comment]
I'd rather keep the tslib, dvbapps and lirc patch reverts as we don't need them right now and it means we are deviating from upstream, potentially keeping patches that aren't merged in their current form.

We'll get the final fixes through upstream package bumps later, when they have been integrated upstream.

The goal of this PR is also to clean up any unnecessary downstream patches

**Comment by HiassofT** [comment]
I haven't found any more commits to revert and think it should be complete now.

I added repo version and PKG_REV bumps of all kodi binary addons

**Comment by HiassofT** [comment]
As posted on Slack:

- Proper fix for tslib is to update to version 1.22 which was released 2 years ago. We still ship the ancient 1.1 release from 2013 https://github.com/libts/tslib/releases/tag/1.22 - the update might even allow us to drop some or all of our downstream patches
- Proper fix for lirc is to get the fix via the next package update. There's no need to add a downstream patch
- Proper fix for dvb-apps is to not build it's test programs - we don't even ship them in the addon so there's no need to add a downstream patch for a file we shouldn't have built in the first place

**Comment by vpeter4** [comment]
> * Proper fix for tslib is to update to version 1.22 which was released 2 years ago. We still ship the ancient 1.1 release from 2013 https://github.com/libts/tslib/releases/tag/1.22 - the update might even allow us to drop some or all of our downstream patches

I hope someone will try the addon after this change. Because I'm sure it will not work anymore.
Or maybe just drop this addon - don't know if anyone is even using it lately.

**Comment by HiassofT** [comment]
I've added a commit to disable building dvb-apps tests and dropped the tslib revert commit as it's a (partial) backport.

I still kept the lirc patch revert, as it was recjected upstream and the new proposed patch hasn't been accepted yet and we don't need it.

TBH I tink we should not pursue the 32bit userland Y2038 issue further until glibc comes up with a better solution that doesn't break ABIs.

Moving to 64bit (rather realistic within the next 10 years) or to another libc (not so much realistic) are all better options than the mess glibc created - it purely worked for them but pretty much no one else and almost every distribution abandoned the glibc approach so I think we should do the same.

This should be good to go now, DVD playback is fine again and let's not worry about glibc's unsuccessful Y2038 approach any more.

**Review by CvH — APPROVED** [review]

**Pull request merged**
