### PR TITLE
WeTek_Hub: use meson-ir and lirc

### PR DESCRIPTION
**Pull request by Kwiboo**
This is a RFC to change from amremote to meson-ir on WeTek Hub
Using meson-ir makes it possible to use lirc or ir-keytable with the integrated IR-receiver same as on C2

**Good**
- Same way to configure IR remotes using lirc/ir-keytable as C2/RPi/Generic
- More IR remotes works with default configuration

**Bad**
- No air-mouse support
- Fast presses on a button is sometime missed in Kodi, e.g. repeatedly pressing `down` in a fast interval

**Needs more testing**
- if IR keeps working after resuming from suspend (u-boot reconfigures IR and CEC)
- ensure buttons on the Hub-remote is mapped the same way in Kodi as with amremote
- different remotes with the updated `lircd.conf.amremote` (`lircd.conf.rpi` appended at the end)

Please tag with Do Not Merge

### CODE REVIEW

**Comment by LongChair** [comment]
I like the idea. I suppose it will need a matching PR on the kernel side or ?

**Comment by LongChair** [comment]
Tested those both on C2 & Hub with Harmony having MCE profile. just worked like a charm.
It felt like the response time was a bit slower on hub than on C2 but was really usable.

Also tested with the stock wetek remote and works fine.
So you have my vote 👍 

@codesnake : any feelings on that one ? :)

**Comment by Kwiboo** [comment]
https://github.com/Kwiboo/LibreELEC.tv/blob/hub-meson-ir/projects/WeTek_Hub/patches/linux/meson_ir.patch is the required change on kernel side to replace aml_remote with meson-ir and should be sent to linux-amlogic if this PR is to be accepted.

**Comment by LongChair** [comment]
Also wanted to add a note for @wrxtasy. I checked both on C2 & Hub if CEC was still working as you mentionned a possible issue there. On my setup with TV + AVR + Hub/C2 , CEC works still ok.

**Comment by codesnake** [comment]
Works good for me. I can confirm the issue with fast button presses, but it is not critical. As for the mouse support - I think it is useless in Kodi, but it is my own opinion.

**Comment by LongChair** [comment]
@kwiboo : any chance we can turn this into two mergeable PRs or is there anything blocking still ? :)

**Comment by LongChair** [comment]
personally i would love this patch in. Although i would also like it to be splitted into a PR that changes the dts file in linux-amlogic and one for the LE side :) We have a linux repo now, so no need to have patch files one something we maintain 😛

**Comment by lrusak** [comment]
Would it be possible to remove amremote and use meson_ir for all amlogic projects?

**Comment by Kwiboo** [comment]
This PR has been updated:
- Linux patch has been removed in favor of a linux-amlogic bump
- OK button is now mapped to KEY_OK (no change in action)
- removed unused `lircd.conf.amremote` in lirc package

Note that there is a small change in the power and back actions compared to amremote as the `remote.xml` keymap is used now

The linux-amlogic bump commit should be updated once the linux-amlogic PR is merged

@lrusak: It should be possible to use meson-ir for the other amlogic projects if `lircd.conf` with correct mappings is added

**Comment by lrusak** [comment]
@Kwiboo do you consider this good to go? If so I can merge https://github.com/LibreELEC/linux-amlogic/pull/22 and get you to rebase this so we can merge.

Otherwise if you want to work on it more just say so.

**Comment by Kwiboo** [comment]
This should be good to go :)

**Comment by lrusak** [comment]
Merged, please update the linux-amlogic commit

**Comment by Kwiboo** [comment]
Updated, rebased and re-tested, good to go :)

**Comment by lrusak** [comment]
thanks!

**Pull request merged**
