### PR TITLE
lirc: simplify scripts

### PR DESCRIPTION
**Pull request by lrusak**
would someone with some sanity left please test this.

@MilhouseVH ?

It seems to work fine on my WeTek Hub

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I don't think I'm able to test LIRC

**Comment by lrusak** [comment]
So incase people are wondering this basically lets the lirc_helper script run lircd-uinput after lircd. This way we don't have any systemd dependency issues.

I have also added some log messages if lirc fails to run (because of a missing lircd.conf file)
```
Feb 07 23:26:16 LibreELEC lircd_helper[3885]: No device specific lircd.conf.amremote file found
Feb 07 23:26:16 LibreELEC lircd_helper[3885]: You need to provide your own lircd.conf.amremote file
Feb 07 23:26:16 LibreELEC lircd_helper[3885]: Place it in /storage/.config/lircd.conf.amremote
```
So now people can check the journal to see why lircd isn't running.

**Comment by InuSasha** [comment]
@lrusak  I made a simple test on RPi2 with lirc-rpi overlay.
Remote was correctly detected and is running, without problems.
here the journal-log: http://sprunge.us/AIZU

**Comment by HiassofT** [comment]
I ran some quick tests on my RPi2, lirc_rpi, gpio_ir with lircd.conf, lirc_rpi+gpio_ir with and without lircd.conf and so far everything seems to startup fine.

Thanks!

**Comment by lrusak** [comment]
looks good :+1:

**Comment by MilhouseVH** [comment]
Included in tonight's [#0208] RPi/RPi2/Generic test build.

**Pull request merged**
