### PR TITLE
buildsystem: two scripts to reunpack and rebuild package

### PR DESCRIPTION
**Pull request by vpeter4**
reunpack: clean and then unpack
rebuild: clean and then build

Maybe useful for someone else?

### CODE REVIEW

**Comment by CvH** [comment]
@vpeter4 yea already thought of this, but tbh shouldn't unpack always clean the package before (I don't see the usecase that it don't do it)? So reunpack would be obsolet if this was "fixed/changed" at unpack.

rebuild makes some sense especially while testing around

**Comment by vpeter4** [comment]
@CvH: Both scripts are for test use case.
About unpack cleaning package first: Not sure if this is good idea. If package is unpacked successfully why remove it on next script call.

Anyway, if no one see any point in use I can easily close pr. I'm using both scripts for a very long time and I though I should share it. That's all :)

**Comment by CvH** [comment]
@vpeter4 damn you are right, just thought about the manual `... scripts/unpack` cmd, for the normal build script it would be useless extra work

**Comment by MilhouseVH** [comment]
Build directories should be deleted automatically if the package is "dirty", ie. changed in some way since the last build (determined from the stamp). This should render `rebuild` and `reunpack` unnecessary, unless I'm missing something, or some particular workflow, as in both cases the build directory will be cleaned - and actually removed if the package is "dirty" - before the `build` and `unpack` (`build` will call `unpack`, which calls `clean`).

Calling `clean` on a package that is not dirty will not remove the build directory, so this all seems to be redundant behaviour as `build` and `unpack` already call `clean`. Or I'm missing something...

**Comment by vpeter4** [comment]
If some patch is changed or added then package is not rebuild automatically. But maybe this happen only for me (like with openssl issue).

Probably better to just close this pr. Doesn't bring any useful feature anyway.

**Comment by MilhouseVH** [comment]
> If some patch is changed or added then package is not rebuild automatically

Any time the package is modified (change the package.mk, add/remove/modify a patch or any other dependent file), it should be automatically rebuilt... if that's not happening then there's an issue with the build system.

**Comment by vpeter4** [comment]
Like I wrote maybe this happen (or better saying doesn't happen) only for me.

But please try touch-ing some patch and build it's package. Wondering what will happen.

**Comment by CvH** [comment]
Maybe I remember it wrong, but if I change something at the patches (media_build) it basically ignores it and just didn't clean the directory (the patches that are called from the (not LE) script inside of the actually build). I had these cases already several times, if I test around with some packages I basically want always "rebuild" and "reunpack" behaviour - currently this is not guaranteed.

current workaround is `... scripts/clean` && `... scripts/unpack` btw `... scripts/clean` && `... scripts/build`

**Comment by MilhouseVH** [comment]
@CvH that sounds like the stamp isn't being calculated on all files in the package. Changing any file in the package should result in the package being considered "dirty", and any subsequent attempt to build/unpack/install the package should result in it being removed first (and then unpacked, built, installed).

I'll run some tests.

**Comment by MilhouseVH** [comment]
The stamp for `media_build` is based on these files:
```
e416c55129a968832a29c605501e4313  packages/linux-drivers/media_build/sources/backports/linux-220-hauppauge_dualhd_second_tuner_support.patch
e018fea8be655ec8a296d5e57f16f931  packages/linux-drivers/media_build/sources/backports/linux-204-lirc_fix_for_4.12.patch
55803b42bdd42bb27e29c8c3088238bb  packages/linux-drivers/media_build/sources/backports/linux-203-stb0899_enable_low_symbol_rate.patch
7bacbd423dbbd80f8270d60444a78c66  packages/linux-drivers/media_build/sources/backports/linux-062-imon_pad_ignore_diagonal.patch
76492696e1f1bcc0b2cd2c2c0529d66e  packages/linux-drivers/media_build/sources/backports/linux-054-nuvoton_revert_d7b290a1056c5564eec8a1b169c6e84ff3.6.114c13.patch
c6a5d3a2b78bd5c07c038fcf9560d5d9  packages/linux-drivers/media_build/sources/backports/linux-057-Removed-MCE-customer-code-restriction-in-rc6-decode.patch
e863751fea1029ee7561cd91f3bfed3c  packages/linux-drivers/media_build/sources/backports/linux-202-lnbp22_patch_for_more_power_if_rotor.patch
e1f199563e397ab2b4eae0e2ff3fc83d  packages/linux-drivers/media_build/config/usb.config
c6d16384d7757daff171f4e5d3d4686f  packages/linux-drivers/media_build/config/generic.config
ba79170f653f333c554188ea5539d3b5  packages/linux-drivers/media_build/package.mk
e5a50c5e2af263eff2ef5525496548ae  packages/linux-drivers/media_build/patches/media_build-01-remove-rmmod.pl.patch
c924669b3468c55bde00617629f23592  packages/linux-drivers/media_build/patches/media_build-02-add-to-backports.patch
ae7fbe9d3f08d64bea923205149efbcc  projects/Generic/linux/linux.x86_64.conf
d8ba47caccc9da7f14620080689453ba  packages/linux/package.mk
a73bd6a2ea87b21ddc07a381328bc631  packages/linux-firmware/intel-ucode/package.mk
```

ie. if any of them change their contents, then the entire package will be automatically deleted when building, unpacking or installing.

To confirm, I've just built LibreELEC so currently `media_build` is "clean" in my repository:
```
neil@nm-linux:~/projects/LibreELEC.tv$ PROFILE=Generic ARCH=x86_64 scripts/build media_build
neil@nm-linux:~/projects/LibreELEC.tv$
```

Touching a patch file has no effect (nor should it - it's the content that matters not the timestamp):
```
neil@nm-linux:~/projects/LibreELEC.tv$ touch packages/linux-drivers/media_build/sources/backports/linux-062-imon_pad_ignore_diagonal.patch
neil@nm-linux:~/projects/LibreELEC.tv$ PROFILE=Generic ARCH=x86_64 scripts/build media_build
neil@nm-linux:~/projects/LibreELEC.tv$
```

I then edited `packages/linux-drivers/media_build/sources/backports/linux-062-imon_pad_ignore_diagonal.patch` and modified the timestamp - a harmless change:
```
diff --git a/packages/linux-drivers/media_build/sources/backports/linux-062-imon_pad_ignore_diagonal.patch b/packages/linux-drivers/media_build/sources/backports/linux-062-imon_pad_ignore_diagonal.patch
index 677de3e..d4acede 100644
--- a/packages/linux-drivers/media_build/sources/backports/linux-062-imon_pad_ignore_diagonal.patch
+++ b/packages/linux-drivers/media_build/sources/backports/linux-062-imon_pad_ignore_diagonal.patch
@@ -1,5 +1,5 @@
 diff -Naur linux-3.16.1/drivers/media/rc/imon.c linux-3.16.1.patch/drivers/media/rc/imon.c
---- linux-3.16.1/drivers/media/rc/imon.c       2014-08-14 04:36:35.000000000 +0200
+--- linux-3.16.1/drivers/media/rc/imon.c       2014-08-14 04:36:35.000000000 +0201
 +++ linux-3.16.1.patch/drivers/media/rc/imon.c 2014-08-15 13:57:16.587620642 +0200
 @@ -1344,6 +1344,17 @@
                        }
```
And now `media_build` is automatically cleaned:
```
neil@nm-linux:~/projects/LibreELEC.tv$ PROFILE=Generic ARCH=x86_64 scripts/build media_build
  CLEAN    media_build
      * Removing /home/neil/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.0-devel/media_build-2017-06-20-rpi ...
  UNPACK   media_build
      APPLY PATCH (common)   packages/linux-drivers/media_build/patches/media_build-01-remove-rmmod.pl.patch
patching file v4l/Makefile
      APPLY PATCH (common)   packages/linux-drivers/media_build/patches/media_build-02-add-to-backports.patch
patching file backports/backports.txt
  BUILD    media_build (target)
make -C linux/ untar
make[1]: Entering directory '/home/neil/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.0-devel/media_build-2017-06-20-rpi/linux'
tar xfj linux-media.tar.bz2
(etc.)
```

So for me, the build system is working as expected.

**Comment by CvH** [comment]
@MilhouseVH like said I am not too sure at which point this happened, as soon it hits me again I will report :)

**Comment by vpeter4** [comment]
Then seems I'm doing it wrong :)

**Pull request closed without merging**
