### PR TITLE
wireguard: add initial support for WireGuard VPNs [backport]

### PR DESCRIPTION
**Pull request by chewitt**
In 9.2 the Rockchip Miqi/Tinkerboard devices still exist. Apart from that difference the PR content is the same as #4139

### CODE REVIEW

**Comment by xtintinx** [comment]
Nobody test?

PROJECT=Rockchip DEVICE=RK3328 ARCH=aarch64 make  --> FAILURE: scripts/install connman has failed!

**Comment by jernejsk** [comment]
ARCH=aarch64 is usually not tested, LE builds are with ARCH=arm for many reasons

**Comment by chewitt** [comment]
I haven't built aarch64 images for ~2 years, so no, not tested (no reason to). Pastebin the connman build log and we can look. The buildsystem error message isn't useful.

**Comment by vpeter4** [comment]
**arm** doesn't build either for me :( Must be host difference?
```
../src/shared/mnlg.c: In function 'mnlg_socket_open':
../src/shared/mnlg.c:286:33: error: 'NETLINK_EXT_ACK' undeclared (first use in this function); did you mean 'NETLINK_CAP_ACK'?
  mnl_socket_setsockopt(nlg->nl, NETLINK_EXT_ACK, &one, sizeof(one));
                                 ^~~~~~~~~~~~~~~
                                 NETLINK_CAP_ACK
../src/shared/mnlg.c:286:33: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:4328: src/shared/vpn_connman_vpnd-mnlg.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f src/.deps/vpn_connman_vpnd-backtrace.Tpo src/.deps/vpn_connman_vpnd-backtrace.Po
mv -f src/.deps/src_connmand-dnsproxy.Tpo src/.deps/src_connmand-dnsproxy.Po
mv -f src/.deps/src_connmand-iptables.Tpo src/.deps/src_connmand-iptables.Po
make[1]: *** [Makefile:1704: all] Error 2
make[1]: Leaving directory 'LibreELEC.tv/build.LibreELEC-RK3328.arm-9.2-devel/connman-9c781b75657bb72a9d65ba7cc73aa5111ae13eb2/.armv8a-libreelec-linux-gnueabi'
FAILURE: scripts/install connman has failed!
[133/250] [FAIL] install connman

```

**Comment by HiassofT** [comment]
`NETLINK_EXT_ACK` was added in kernel 4.12, so this is expected...

From a quick glance over connman sources it should be enough to disable wireguard support for RK, it probably won't work anyways with the old kernel.

**Comment by vpeter4** [comment]
> `NETLINK_EXT_ACK` was added in kernel 4.12, so this is expected...

No one tests PR's anymore? Come on :)

**Comment by chewitt** [comment]
I tested on Allwinner, Amlogic, Rockchip, RPi(various) and Generic in master and most of them in 9.2 branch (but I missed RK, oopsie). WireGuard is supported on 3.10+ via the compat module so it should be fine once this is resolved.

**Comment by ammgws** [comment]
Sorry for intruding but does this backport mean current 9.2 installations will soon get an update with this backport included, or will it be in another (9.3?) release instead?

**Comment by chewitt** [comment]
It will go into LE 9.2.1, which will ship if/when Kodi v18.6 appears (no schedule)

**Comment by chewitt** [comment]
NB: I consider WireGuard support experimental, but as the number of active master branch test installs is lower than normal (likely due to GBM/V4L2 and Python3 plumbing changes ~ lots of things are still work-in-progress at this point) I've wanted to merge WireGuard into LE9.2 so that people experiment and the issues get found. I've been using it since last summer in various forms so "it works for me" but I'm sure there are some lurking issues to resolve.

**Pull request merged**
