### PR TITLE
stripping changes

### PR DESCRIPTION
**Pull request by lrusak**
see the discussion at https://github.com/OpenELEC/OpenELEC.tv/pull/4661

@MilhouseVH is this ok with you?

### CODE REVIEW

**Comment by MilhouseVH** [comment]
If it's the same as #4661 then my comments remain the same - my only concern is that it appears to bloat addons, not sure if this is intentional or can be improved upon? Otherwise I'm totally OK with this, thanks.

**Comment by lrusak** [comment]
Good to go :+1: we can figure out stripping add-ons as we go

**Comment by stefansaraev** [comment]
I would not call that bloat. it will make debugging in binary addons much, much easier including line numbers and so on. whatever you dont want to have debug syms shipped - just do
```
debug_strip $ADDON_BUILD/$PKG_ADDON_ID/ 
```
at the end of addon(). would work for any OE addon.

**Comment by MilhouseVH** [comment]
True, it's only adds a few MBs to the addons (although relatively speaking it can result in some add-ons increasing by 50% in size). However if it proves useful then it shouldn't be an issue, and nobody has complained so far (well, apart from me - maybe consider it more of an observation than complaint!)

**Pull request merged**
