### PR TITLE
ffmpeg: add v4l2 backports and pending patches

### PR DESCRIPTION
**Pull request by lrusak**
All of these patches are either merged upstream or are awaiting approval on the mailing list.

This moves from my original patches to the ones recently submitted by @tmm1

I have yet to runtime test this yet which I will do shortly. @chewitt if you have time you could also test this out (if possible).

### CODE REVIEW

**Comment by chewitt** [comment]
These changes currently break as much as they solve for Amlogic, but it's fine to merge them if we don't want to hold up other platforms. Once the next batch of Amlogic vdec/firmware changes from @elyotna land on kernel mailling lists @tmm1 will need to revalidate the ffmpeg side anyway as the updated vdec drivers include some V4L2 compliance changes. Amlogic reached a maturity point where some breakage and retooling is essential to keep aligned with the kernel stateful APIs.

**Comment by lrusak** [comment]
Unfortunately this patch set doesn't work properly at the moment and I'm still trying to find some time to debug it properly. Hopefully I'll get to it this weekend and we can have a nicer patch set that properly tracks upstream.

**Comment by 150balbes** [comment]
Are there recommendations with which kernel and patches to check these patches ?

**Comment by chewitt** [comment]
Closing as will be superseded by #4166

**Pull request closed without merging**
