### PR TITLE
system-tools: update addon

### PR DESCRIPTION
**Pull request by CvH**
- updated nearly every addon to latest stable version
- some programs are heavily outdated and I changed to "active" maintained forks

### CODE REVIEW

**Comment by CvH** [comment]
builds okay, no runtime test yet

**Comment by chewitt** [comment]
@CvH all tested now?

**Comment by CvH** [comment]
@chewitt looks working now, added finally htop (tx @awiouy) rather messy due netbsd-curses

If https://github.com/LibreELEC/LibreELEC.tv/pull/1749 is merged `htop-02_temp_remove_set_escdelay.patch` could be removed (but currently necessary for back ports).

**Comment by thoradia** [comment]
Would aria2 fit in this add-on?

**Comment by thoradia** [comment]
https://github.com/CvH/LibreELEC.tv/pull/7

**Pull request merged**
