### PR TITLE
buildsystem: replace wget with curl

### PR DESCRIPTION
**Pull request by antonlacon**
This replaces the use of wget by the buildsystem with curl. This should allow the use of ftp:// $PKG_URLs again without concern for the distribution on the running system.

The issue previously observed in #9280  was resolved by updating the WSL2/Ubuntu combo to Ubuntu 24.04.

### CODE REVIEW

**Comment by CvH** [comment]
@antonlacon pls rebase

**Comment by antonlacon** [comment]
Rebased.

**Review by heitbaum — APPROVED** [review]

**Comment by heitbaum** [comment]
Can you please have a look. It seems that the curl does not “honour” “check” for 404. I noticed when bumping qemu?


script to use to test.

```
curl --connect-timeout 30 --retry 3 --continue-at - --location --max-redirs 5 --output /var/media/DATA/home-rudi/LibreELEC.tv/sources/qemu/qemu-9.1.1.tar.xz https://download.qemu.org/qemu-9.1.1.tar.xz
```

**Comment by heitbaum** [comment]
Looks like `--fail` might be the way to go.

```
curl --fail --connect-timeout 30 --retry 3 --continue-at - --location --max-redirs 5 --output /var/media/DATA/home-rudi/LibreELEC.tv/sources/qemu/qemu-9.1.1.tar.xz https://download.qemu.org/qemu-9.1.1.tar.xz
** Resuming transfer from byte position 153
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   153    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
```

**Review by CvH — APPROVED** [review]

**Pull request merged**
