### PR TITLE
Rollback nvidia driver to 304.137

### PR DESCRIPTION
**Pull request by gurabli**
Rollback to nVidia legacy (ION support)

### CODE REVIEW

**Comment by chewitt** [comment]
Thanks, but I'm closing the PR because the change from 304.xx to 340.xx nVidia driver was deliberate so we have no interest in reverting or adding a third nvidia driver blob to the image. The LE 8.2 branch is also in an end-of-life state; no changes except for minor addon bumps.

Please see https://forum.libreelec.tv/thread/7291-libreelec-builds-with-nvidia-304-xx-driver if you need LE images with the older driver.

**Comment by MilhouseVH** [comment]
Also, the 304.xxx line is [no longer supported](https://nvidia.custhelp.com/app/answers/detail/a_id/3142/~/support-timeframes-for-unix-legacy-gpu-releases) by Nvidia, and 304.137 doesn't support X.org Server ABI 24 so would be impossible to use going forward (ie. in LE9). In other words, it's the end of the line for 304.xxx and ION hardware (or you limit yourself to the custom LE8 build linked above).

My advice would be to upgrade to a new device, but not another Nvidia device given the uncertainty regarding continued Nvidia (VDPAU) support in Kodi 19+. You could probably replace your (up to) 10-year old ION device with a Raspberry Pi3+ (or similar) running latest LE official releases for an equivalent or better viewing experience.

**Comment by chewitt** [comment]
No problem. It's best practice to work in a topic branch (not master) so you can keep your changes isolated and rebased against our upstream repo, e.g.

```
git checkout -b nvidia304
git checkout 
git fetch upstream/master
git reset --hard upstream/master
git checkout nvidia304
git rebase master
git push -f origin nvidia304
```

^ this should give you a topic branch called `nvidia304` with the current single change that you made rebased against our current master/HEAD, and if you push changes they go into your repo instead of ours (as a PR). Keep adding your changes to that branch, and rebase it regularly as we push changes as it's easier to deal with little changes often than infrequent larger change-sets. If you need more git tips, post in the forums :)

**Comment by gurabli** [comment]
You so helpful, this is a really excellent community! Those who are willing to learn always get the support from you professionals.
I already opened a forum thread for my case, perhaps you can check there and see if I'm doing things (more or less) right: [LE Forum](https://forum.libreelec.tv/thread/13106-compile-le-8-2-5-with-nvidia-legacy-driver-and-dual-audio-patch/)

**Pull request closed without merging**
