### PR TITLE
update avahi, nss-mdns and jsoncpp

### PR DESCRIPTION
**Pull request by CvH**
changed the url from OE mirros to actually maintained repos
- just changed to the same version with identical files at the archives
- avahi, jsoncpp and nss-mdns are partly horrible outdated, I didn't updated due very likely changed behaviour (no idea how to test it)
- nss-mdns 0.10 files at github are not identical to the released 0.10 so I used the "old" package url (they missing the buildscripts)

### CODE REVIEW

**Comment by fuzzard** [comment]
The 0.x.y branch of jsoncpp is feature compatible with the 0.5.0 used from my testing. I looked at updating a pvr addon (pvr.hdhomerun) to use newer updated versions, and the latest 0.10.6 release had no regressions.
The 1.x.y branch is completely incompatible as they have changed the reader/writers, and would require major rework for all code.

This is more just to let you know my experiences. I havent looked at anything LE ships that uses jsoncpp, so obviously it would require some thorough testing.

**Comment by MilhouseVH** [comment]
@fuzzard many thanks for the info.

Unfortunately all of the pvr addons that use `jsonccp` (the only `jsoncpp` consumers in LE, as far as I know) are using `0.5.0`, and for the sake of continued support it would be better to continue using the same version in LE - using a different version increases the risk of errors/bugs being pushed back on us because we're not using the same library version as the author/maintainer supports, etc.

What should happen is that the upstream projects switch to using a more modern `jsoncpp`, and then we can follow suit.

The PVR addons using `jsoncpp` are:
```
pvr.argustv
pvr.filmon
pvr.hdhomerun
pvr.octonet
pvr.pctv
pvr.stalker
```
`pvr.filmon` is basically dead, and `pvr.argustv` is on life support.

Ping @ksooo - time to update jsoncpp in the remaining addons? Maybe even to 1.x.y if possible?

**Comment by fuzzard** [comment]
Fully understand, just wanted to pass on info i had at hand.

I have a working branch of pvr.hdhomerun running on the 1.x.y branch, but the most annoying thing with that is the build on win machines has deprecated warning spam. Even if no deprecated methods are being used or referenced. There was a PR to jsoncpp to minimise the deprecation warnings to only when affected functions were used, but last i checked (couple weeks back) the behaviour hadn't changed.

I have a PR at pvr.hdhomerun to pull it up to 0.10.6 with the end goal to take it up to the 1.x.y branch, but maintaner has gone a little awol. I figure if we can get one of the pvr clients up to date as a reference, it might make it easier on the others to change. All this isnt really relevant to LE though. Again, just info at hand that might be useful at a later date.

**Comment by CvH** [comment]
added 3 commits to bump to latest versions
- it builds for generic
- I have no idea if this is right
- nss-mdns installs this files (even the old version) to image, likely we only need `libnss_mdns.so.2` - but no idea how to test it runtime
```
libnss_mdns.so.2
libnss_mdns4.so.2
libnss_mdns6.so.2
libnss_mdns_minimal.so.2
libnss_mdns4_minimal.so.2
libnss_mdns6_minimal.so.2
```

**Comment by awiouy** [comment]
According to docs and https://github.com/CvH/LibreELEC.tv/blob/76d000231af7df69ce4079992f82c44f38c16898/packages/network/nss-mdns/config/nsswitch.conf only libnss_mdns_minimal is needed.

I will also have a look at librespot later tonight.

IIRC to runtime test, resolve libreelec.local (or another device on your subnet, eg a routee) in libreelec.

**Comment by MilhouseVH** [comment]
A brief test on Generic is working OK (absolute basics - booting into Kodi, pinging www.google.co.uk, Samba is working, but no PVR tests)

However if @ksooo (or anyone else) has no plans to update `jsoncpp` in the upstream PVR addons then I'd prefer that we do not bump to a newer version of `jsoncpp` and potentially introduce unexpected behaviour.

I'll include this as-is in test builds as it will help confirm there are no immediate `jsoncpp` incompatibilities and improve the chances of an upstream bump, but unless it happens I don't think we should merge a `jsoncpp` bump ahead of upstream.

**Comment by MilhouseVH** [comment]
I chatted @ksooo on Slack and he has no plans to update `jsoncpp` on Kodi-PVR, but PRs are welcome.

Until upstream is updated (and really, all the PVR addons need to be updated to be on the same version otherwise it gets messy), we should drop the `jsoncpp` bump.

**Comment by fuzzard** [comment]
Ive had a quick glance at those other 5 pvr addons Millhouse (not including pvrhdhomerun).

Octonet is the only one that currently compiles against Leia Head. Ill do a PR to octonet for a version bump, would you be able to throw that into test builds to try and get some actual testing done against it? I dont have the backends for any of these pvr addons for testing.

https://github.com/DigitalDevices/pvr.octonet/pull/15

The other 4 all use instances of iChannelNumber and strStreamUrl which were removed as part of ksooo's work over the past couple months. As you have already been excluding them in your builds, im not sure whats best to do here. Ill have a look through and see if i can make the necessary changes to compile them in a minimalist fashion. But the maintainers (if there are any) will probably need to look at some of the other changes ksooo has done lately anyway.

**Comment by MilhouseVH** [comment]
Yes, currently only `pvr.hdhomerun` and `pvr.octonet` are building - if nobody fixes the other addons to bring them up to date with latest Kodi PVR API then they'll likely be removed at some point. It might still be worth submitting PRs (assuming it's not too much work) on the off chance someone does get around to fixing them up.

The upstream PRs are not strictly relevant to LibreELEC as we build with an "external" `jsoncpp`, so the last couple of Milhouse builds have included `pvr.hdhomerun` and `pvr.octonet` with `jsoncpp 0.10.6` (which is bumped in this PR) regardless of whatever version the upstream currently uses.

Hopefully the addons that do compile will merge your PRs in which case we can then align LibreELEC with the commit already in this PR. Many thanks for taking care of this!

**Comment by fuzzard** [comment]
Hi MillHouse,

Ive done an initial pass on pvr.filmon to bring upto PVR API 5.7.0 as a bit of a test to see what may be required for the others.

https://github.com/kodi-pvr/pvr.filmon/pull/76

Could you possibly build with this, and request any feedback. If it functions, ill look to pull the rest up to the bare minimum, but i cant test it at all, so its a blind fix. It compiles, and runs in Leia Head, but thats as far as i can get.

**Comment by MilhouseVH** [comment]
Thanks - I'll try building pvr.filmon later this and give you feedback on the PR.

**Comment by fuzzard** [comment]
Another PR this time for pvr.pctv. The only thing ive noticed in regards to jsoncpp (and this is the same for argustv) is they use a deprecated function (getFormatedErrorMessages). The only reason this method has been deprecated is because of the typo in the function name (new method getFormattedErrorMessages). 

https://github.com/kodi-pvr/pvr.pctv/pull/52

Im wondering if theres any point updating some of these addons, or if we/i should just let them die. Theres lots of non implemented ToDo's running back to the timer changes done for API 2.0.0/1.9.7
I've only been doing the bare minimum to get them compiling, and they *SHOULD* function, but again, i dont have any of these backends to test/verify.

**Comment by MilhouseVH** [comment]
Thanks, I'll include `pvr.pctv` and `pvr.stalker` in tonight's build so long as they build (won't know for another hour or so). `pvr.filmon` will also be included as we know that builds.

Killing addons is never an easy decision, but if they're not maintained it does become a little easier.

**Comment by MilhouseVH** [comment]
pvr.pctv and pvr.stalker have both built successfully - thanks!

**Comment by CvH** [comment]
@MilhouseVH I guess it works for your builds ? If so I should squash the commits I guess?

**Comment by MilhouseVH** [comment]
@Rechi has just submitted PRs for the PVR addons that bumps jsoncpp to 1.8.3:

https://github.com/kodi-pvr/pvr.argustv/pull/74
https://github.com/kodi-pvr/pvr.filmon/pull/79
https://github.com/kodi-pvr/pvr.hdhomerun/pull/70
https://github.com/kodi-pvr/pvr.pctv/pull/54
https://github.com/kodi-pvr/pvr.stalker/pull/102
https://github.com/DigitalDevices/pvr.octonet/pull/17

I'm not seeing any code changes though - I thought jsoncpp 1.x.y was incompatible with jsoncpp 0.x.y? @fuzzard are the PVR changes sufficinet for jsconcpp 1.8.3?

**Comment by fuzzard** [comment]
your going to see a shit ton of deprecation spam in your builds. The old functions are still in, but are all marked as deprecated. Should work for now, but dont expect good things in the future. i would suggest sticking with the 0.x.y branches at this stage personally

**Comment by MilhouseVH** [comment]
@fuzzard As upstream has now moved to 1.8.3 I think doing the same is the best option, regardless of the deprecation spam - if we remain on 0.x.y while upstream uses 1.x,y any differences in behaviour that we experience (both good and bad) could be the result of being on the older library.

Presumably the deprecation changes are in the pipeline?

@CvH could you add another commit that bumps jsconpp to 1.8.3 and I'll try some test builds.

**Comment by fuzzard** [comment]
yeah, feel free to bump if they are going to do that. ive put a comment on the pvr.hdhomerun PR to ask if he is aware of the changes, but if they want to push to it, thats up to them i guess.

**Comment by MilhouseVH** [comment]
Many thanks, @fuzzard!

**Comment by MilhouseVH** [comment]
Thanks that builds ok. These are the jsoncpp-related deprecation warnings for all PVR addons: http://sprunge.us/APZD

**Comment by fuzzard** [comment]
I've put up a patch to the pvr.hdhomerun addon to change to the new methods. The spam comes from the windows side of builds. GCC/Clang handles the deprecations differently, with only 1 message per instance, but windows seems to show it regardless with multiple.

Seems Rechi is wanting to go ahead with it regardless, and i understand why. Just would have been nice to update the addons to remove the deprecated methods rather than blindly do a version bump, but all good.

**Comment by fuzzard** [comment]
Another off topic, but @MilhouseVH ive just pushed a PR to pvr.argustv https://github.com/kodi-pvr/pvr.argustv/pull/75
Any chance you can build and see if we get any feedback from users. As with the other addons, completely blind fixes, with no runtime testing.

**Comment by MilhouseVH** [comment]
> Any chance you can build and see if we get any feedback from users. 

Will do. I can at least say they all build OK.

**Comment by CvH** [comment]
rebased

**Pull request merged**
