### PR TITLE
Request to add RTL8723BS Bluetooth driver support

### PR DESCRIPTION
**Pull request by sorhtyre**
I have included all of files required to support the Bluetooth function built into the RealTek RTL8723BS chip.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks for this, however a few issues/questions.

Please drop the two merge commits.

Where did this firmware come from, and why are there 2 files?

Is there any reason not to use the `rtl8723bs*` firmware from the `kernel-firmware` package ?
```
-rw-rw-r-- 1 neil neil 20886 Apr  4 22:30 rtlwifi/rtl8723bs_ap_wowlan.bin
-rw-rw-r-- 1 neil neil  9120 Apr  4 22:30 rtlwifi/rtl8723bs_bt.bin
-rw-rw-r-- 1 neil neil 32108 Apr  4 22:30 rtlwifi/rtl8723bs_nic.bin
-rw-rw-r-- 1 neil neil 26398 Apr  4 22:30 rtlwifi/rtl8723bs_wowlan.bin
```
(we don't currently install `rtlwifi/*` but could do)

Please drop the https://github.com/LibreELEC/LibreELEC.tv/pull/1591/commits/efae133ccd7cef330f2d8c3e4ac4f1f9a89996c6 commit as it is not valid - there are no such files to be dropped. Your repo might need cleaning up?

The systemd service is unconditional, which means it will fail on systems without an RTL8723BS chip. Please add a condition so that the service only runs when the relevant hardware is available, and/or use a udev rule (for example, see https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/linux-firmware/brcmfmac_sdio-firmware-rpi which uses both systemd and udev).

The current kernel is 4.10.13 (soon to be 4.11.y), can you confirm if your driver builds against both of these kernels?

**Comment by sorhtyre** [comment]
I can confirm that the driver builds correctly against 4.10.10 and will perform a compile tonight to ensure it builds against 4.10.13.

I will make the appropriate change to the systemd service as you have pointed out.

I have attempted to use the rtlwifi/rtl8723bs_bt.bin firmware, as I thought it was the logical choice, but was unsuccessful. I can perform tests and produce output logs if need required.

The current firmware provided originally came from Larry Finger's rtl8723bs_bt repository. I cleaned up/reorganized what was needed for LibreELEC.

I appologize for the state of my repository, I am brand new at git. As soon as I learn how to drop the efae133, 500f487, and b1a22e4 commits I will. As far as I know, no one depends on my repo... I can always wipe it out and start clean.

**Comment by MilhouseVH** [comment]
This branch has the 4.10.12+ changes: https://github.com/LibreELEC/LibreELEC.tv/compare/master...MilhouseVH:linux41012+ - as 4.10.14 has just been released I've included the change for 4.10.14 also. I'll PR it tomorrow once RPi commits are updated.

**Comment by sorhtyre** [comment]
Once I see the inclusion of 4.10.14 I will rebuild and request a new PR.

Is that acceptable?

**Comment by MilhouseVH** [comment]
Sure.

**Comment by sorhtyre** [comment]
I have clean my repository as requested.

I also fetched your branch: https://github.com/MilhouseVH/LibreELEC.tv/tree/linux41012+ and performed a test build against 4.10.13. No issues reported.

**Pull request closed without merging**
