### PR TITLE
kodi: bump kodi and binary add-ons to current

### PR DESCRIPTION
**Pull request by chewitt**
This PR bumps Kodi and associated platform/addon bits to current versions as it's been a while since we updated them and people are starting to create testing builds. 

NB: The update_binary-addons script still captures the game.retroplayer items so I've included those changes - i'm not sure if that is still intended as there's also a separate update-binary-addons-retroplayer script in tools/mkpkg?

### CODE REVIEW

**Comment by lrusak** [comment]
Please drop the game add-ons bump. The game add-ons and their libraries need to be bumped at the same time using the update_retroplayer-addons script. That script will also adjust the PKG_REV which needs to be bumped if there is and update available.

**Comment by chewitt** [comment]
PR updated to drop the game add-ons.

**Comment by MilhouseVH** [comment]
Maybe we should adjust the `update_binary-addons` script to ignore the game add-ons if they should only be handled by `update_retroplayer-addons`?

**Comment by chewitt** [comment]
@MilhouseVH yes, would be a good idea to exclude them

**Pull request merged**
