### PR TITLE
RPi/RPi2: Linux and Kodi Updates

### PR DESCRIPTION
**Pull request by MilhouseVH**
Not yet build tested, will do that later today.

### CODE REVIEW

**Comment by lrusak** [comment]
are the Confluence patches something we want for all platforms maybe?

**Comment by MilhouseVH** [comment]
I wouldn't say so - they're just patches that are in the jarvis rbp backports branch and presumably have been deleted in the past. The commits are of most benefit to low power devices, particularly RPi1, as the costly animated "busy" spinner (that drives the GUI at 60fps, 75% CPU load) is replaced for a a much cheaper 2 fps GIF (barely any CPU load at all).

**Comment by lrusak** [comment]
fair enough. good to go then?

**Comment by MilhouseVH** [comment]
I haven't build tested yet, and won't be able to for another few hours. If anyone else is able to test before me that would be great. I'd rather we got at least one good build before merging though!

**Comment by MikeBuzz** [comment]
both RPi and RPi2 just built with out issues

**Comment by MilhouseVH** [comment]
Thanks Mike. I've also completed my testing - both build and run fine. Merge any time.

**Pull request merged**
