### PR TITLE
addons: clean up

### PR DESCRIPTION
**Pull request by awiouy**
Cosmetic changes.
@cvh would you please be so kind to review?

### CODE REVIEW

**Comment by CvH** [comment]
@chewitt addons could be rebuild and uploaded - no `PKG_REV` bump because it is only some changes at the description - no need to molest ppl with updates for this (at least new users have directly the "better" version)
pls merge if you are okay with this

**Comment by chewitt** [comment]
Can we change `tinc` to `Tinc` so that add-on names are capitalised. Not sure if there are any other add-ons in the list that need the same (can't look at a box right now).

**Comment by CvH** [comment]
tinc is the only exception (iirc) that is a bit off - the official name is `tinc` and not `Tinc` (ofc nitpicking)
idk if we should care or not ¯\_(ツ)_/¯

**Comment by awiouy** [comment]
tinc is tinc, not Tinc see https://www.tinc-vpn.org/ ;)

**Pull request merged**
