### PR TITLE
kodi/imx6: move project specific patches to project folder

### PR DESCRIPTION
**Pull request by vpeter4**

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Would a single patch file, similar to RPi/RPi2, be more manageable?

**Comment by vpeter4** [comment]
No idea actually. I think would be easier to fix only some patches/files when needed in the future.
But if having one big file would be more appropriate I can change that.

**Comment by MilhouseVH** [comment]
Use whatever makes it easier for you to produce and maintain them, just pointing out that a single file for a patch set is what we've tended to use for RPi - if a patch is changed, the entire patch set is regenerated. As far as the build system is concerned it's not going to make a lot of difference whether it's one patch file or many.

**Comment by vpeter4** [comment]
Changed to a single patch. Ready to merge.

**Pull request merged**
