### PR TITLE
kodi: service addon wrapper call fix

### PR DESCRIPTION
**Pull request by vpeter4**
Currently when addon is installed it's service is enabled and started.
But immediately service is stopped, disabled, enabled and started again.
This second part should be executed only on addon's update.

Discussion in PR #1835 https://github.com/LibreELEC/LibreELEC.tv/pull/1835#commitcomment-31787284

### CODE REVIEW

**Comment by HiassofT** [comment]
Thanks, this looks good to me!

Could you also rename `LE_ADDON_POST_INSTALL` to `LE_ADDON_POST_UPDATE` and change the `post-install` option to `post-update` (both in kodi patch and in the service-addon-wrapper script)? The first comment in the post-install case in the script ("post-install is triggered on update as well,") should probably be dropped.

I had a quick look if we could also get a pre-update notification from kodi (then pre-update handling could be merged with disable and post-update with enable) but didn't have much luck. When AddonInstaller sends the PreInstall notiification addon->Path() still points to the ZIP file, not the addon directory. Maybe I'll have a look at it again sometimes later, but for now your changes are good enough.

**Comment by vpeter4** [comment]
Is something wrong with this PR? It fixes a bug but still ignored :(

**Comment by CvH** [comment]
The pr is at the @MilhouseVH builds for a while, this gets merged for B3 if no problems appear.

**Comment by aptalca** [comment]
@HiassofT @vpeter4 I noticed that my systemd service addons are no longer restarting the services when addon settings change. Could this PR be the reason? My addons use the following:
```
   def onSettingsChanged(self):
      subprocess.call(['systemctl', 'restart', self.id])
```

Here's the full code: https://github.com/linuxserver/libreelec-addon-repo/blob/letsencrypt2/docker.linuxserver.letsencrypt/default.py

Thanks

**Pull request merged**
