### PR TITLE
snapcast

### PR DESCRIPTION
**Pull request by awiouy**
This builds snapcast for LibreELEC. I added it to 8.2 for development/test purposes. I am not sure if it should be shipped with an existing addon (multimedia-tools, librespot), standalone or at all. I hope it will be picked up by creative users/developers.

### CODE REVIEW

**Comment by lrusak** [comment]
I'm not really sure we need this. You can do multi room audio with pulseaudio already.

Also, you need to use PKG_TOOLCHAIN now instead of having all the `make_target() { : }` stuff

**Comment by awiouy** [comment]
`PKG_SHA256` and `PKG_TOOLCHAIN` come with LibreELEC 9.0, and I will add them if I port this.

I played around with this, and setup a three room Spotify system in five minutes.
On system 1:
`./snapserver -s spotify:///librespot?name=snapcast&bitrate=320`
On systems 1 to 3
`./snapclient`
On mobile phone:
play!

Also, it is [very complete](https://github.com/badaix/snapcast/blob/master/doc/player_setup.md) and has [Python hooks](https://github.com/badaix/snapcast/tree/master/control).

I can not unsee...

**Comment by lrusak** [comment]
Everything needs to be PR'd to `master` first then can be backported

**Comment by awiouy** [comment]
Will do

**Pull request merged**
