### PR TITLE
Update moonlight

### PR DESCRIPTION
**Pull request by dead**
Update moonlight to 2.2.2

### CODE REVIEW

**Comment by lrusak** [comment]
looks pretty good, thanks for the help.

You can remove https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/addon-depends/moonlight-embedded/patches/moonlight-embedded-0002-revert-upstreamm-commit-6fcc63e.patch with the moonlight-embedded update to 2.2.2

If you wouldn't mind separating each package into it's own commit that would be great. To do so you just need to reset this commit
```
git reset HEAD^
```
then add each folder and prepend the commit message with the package.
```
git add packages/addons/addon-depends/moonlight-embedded
git commit -m "moonlight-embedded: update to 2.2.2 and remove unneeded patch"
```
Please do similar for the other packages also, thanks.

then force push
```
git push -f origin master_moon
```

**Comment by dead** [comment]
Thanks @lrusak !
Done 😄

**Comment by lrusak** [comment]
Thanks!!

Yes please do that same for the backport

**Comment by lrusak** [comment]
LGTM

**Pull request merged**
