### PR TITLE
linux: update to 6.4.y

### PR DESCRIPTION
**Pull request by heitbaum**
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.4
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.4.1

6.4 - Linux Kernel release
6.4.1 - 31 patches

errors / fixes / issues / regressions / todo
- incorporate Wireless Intel AX101
  - https://www.spinics.net/lists/linux-wireless/msg236143.html
- nvidia update to 470.182.03 and patch
- rtw88: drop upstreamed patches included in kernel 6.4
- TODO: Add working 6.3 rtw88 patch to Amlogic 
- TODO: Rockchip
  - review WIP patches
- update to Linux 6.4.1
- update iwlwifi firmware for 6.4 - core78

### log 
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.4.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.4.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/log/
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.4
- https://linux-regtracking.leemhuis.info/regzbot/mainline/
- https://linux-regtracking.leemhuis.info/regzbot/stable/

### 6.4.1 Build tested on all of:

```
PROJECT=Allwinner ARCH=arm DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H3 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H6 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX6 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX8 s/build linux
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard s/build linux - u-boot build failure
PROJECT=Generic ARCH=x86_64 DEVICE=Generic s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
```

### 6.3.y Run tested on all of:
- Allwinner all - tested - TBA - jernejsk
- Allwinner H6 (Tanix TX6) - 6.4.1 - heitbaum
- Generic Generic (Intel ADL - NUC12) - 6.4.1 - heitbaum
- NXP iMX6 (Cubox-i4Pro) - TBA - heitbaum
- Rockchip RK3399pro (Rock Pi N10) - TBA - heitbaum
- RK all - tested - TBA - knaerzche
- Samsung Exynos (Hardkernel ODROID XU4) - TBA - heitbaum

——

Fixed: ~~Issues on Tanix TX6 - 8822bs/cs - fixed with byte-wise-word-io patch~~
```
8822bs
[    8.817489] rtw_8822bs mmc1:0001:1: Firmware version 27.2.0, H2C version 13
[    8.817786] sunxi-mmc 4021000.mmc: unaligned scatterlist: os f80 length 2
[    8.817796] sunxi-mmc 4021000.mmc: map DMA failed
[    8.817804] rtw_8822bs mmc1:0001:1: sdio read16 failed (0x10230): -22
...
[    8.818259] rtw_8822bs mmc1:0001:1: failed to download rsvd page
[    8.818313] rtw_8822bs mmc1:0001:1: failed to download firmware
...
[    8.819096] rtw_8822bs mmc1:0001:1: failed to setup chip efuse info
[    8.819103] rtw_8822bs mmc1:0001:1: failed to setup chip information
[    8.819323] rtw_8822bs: probe of mmc1:0001:1 failed with error -16

8822cs
[    7.426639] rtw_8822cs mmc1:0001:1: WOW Firmware version 9.9.4, H2C version 15
[    7.428342] rtw_8822cs mmc1:0001:1: Firmware version 9.9.15, H2C version 15
[    7.437851] sunxi-mmc 4021000.mmc: unaligned scatterlist: os f80 length 2
[    7.437891] sunxi-mmc 4021000.mmc: map DMA failed
[    7.437901] rtw_8822cs mmc1:0001:1: sdio read16 failed (0x10230): -22
...
[    7.438363] rtw_8822cs mmc1:0001:1: sdio write16 failed (0x10204): -22
[    7.438393] rtw_8822cs mmc1:0001:1: failed to download rsvd page
[    7.438444] rtw_8822cs mmc1:0001:1: failed to download firmware
...
[    7.438928] rtw_8822cs mmc1:0001:1: failed to setup chip efuse info
[    7.438944] rtw_8822cs mmc1:0001:1: failed to setup chip information
[    7.439218] rtw_8822cs: probe of mmc1:0001:1 failed with error -16
```

### CODE REVIEW

**Comment by jernejsk** [comment]
See https://lore.kernel.org/linux-wireless/880bb4ed-f3a5-2d7f-db10-fec65087dd05@lwfinger.net/T/#mf53120e175d8015c12a8ef57d2643da2ac34a74f for wifi issue

**Comment by heitbaum** [comment]
> See https://lore.kernel.org/linux-wireless/880bb4ed-f3a5-2d7f-db10-fec65087dd05@lwfinger.net/T/#mf53120e175d8015c12a8ef57d2643da2ac34a74f for wifi issue

I can confirm that both TX6 (822bs and 8822cs have running WiFi and Bluetooth with 6.4-rc1 and the byte-wise-word-io patch. I havent done any performance tests / ... But connectivity was no issue.

With HCI_QUIRK_BROKEN_LOCAL_EXT_FEATURES_PAGE_2 now in 6.4-rc1 - I'll tidy up the BT 8822bs patch and submit.

**Comment by heitbaum** [comment]
iperf testing has no dmesg errors - tested with both ipv4/ipv6 and both arm/aarch64 user lands
```
tx6-8822cs:~ # iperf --client nuc12.local -t 60
...
[  5]  57.00-58.00  sec  4.85 MBytes  40.7 Mbits/sec    0   1.06 MBytes
[  5]  58.00-59.00  sec  5.40 MBytes  45.3 Mbits/sec    0   1.06 MBytes
[  5]  59.00-60.00  sec  5.10 MBytes  42.7 Mbits/sec    0   1.06 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec   351 MBytes  49.1 Mbits/sec    0             sender
[  5]   0.00-60.04  sec   347 MBytes  48.5 Mbits/sec                  receiver

tx6-8822bs:~ # iperf --client nuc12.local -t 60
...
[  5]  57.00-58.00  sec  4.11 MBytes  34.5 Mbits/sec    0    650 KBytes
[  5]  58.00-59.00  sec  4.85 MBytes  40.7 Mbits/sec    0    650 KBytes
[  5]  59.00-60.00  sec  4.85 MBytes  40.7 Mbits/sec    0    650 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec   291 MBytes  40.7 Mbits/sec    0             sender
[  5]   0.00-60.03  sec   289 MBytes  40.4 Mbits/sec                  receiver


nuc12:~ # iperf --client tx6-8822cs -t 60
...
[  5]  57.00-58.00  sec  7.61 MBytes  63.9 Mbits/sec    0   3.15 MBytes
[  5]  58.00-59.00  sec  7.92 MBytes  66.4 Mbits/sec    0   3.15 MBytes
[  5]  59.00-60.00  sec  8.60 MBytes  72.1 Mbits/sec    0   3.15 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec   493 MBytes  68.9 Mbits/sec    0             sender
[  5]   0.00-60.00  sec   492 MBytes  68.8 Mbits/sec                  receiver

nuc12:~ # iperf --client tx6-8822bs -t 60
...
[  5]  57.00-58.00  sec  4.79 MBytes  40.2 Mbits/sec    0   3.15 MBytes
[  5]  58.00-59.00  sec  4.30 MBytes  36.1 Mbits/sec    0   3.15 MBytes
[  5]  59.00-60.00  sec  4.11 MBytes  34.5 Mbits/sec    0   3.15 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec   260 MBytes  36.3 Mbits/sec    0             sender
[  5]   0.00-60.00  sec   259 MBytes  36.3 Mbits/sec                  receiver
```

**Comment by heitbaum** [comment]
@Kwiboo / @knaerzche - are these rebases ok? Otherwise let me know. If so I squash (change from wip) and finalise 6.4.
- 3ccfdf5653bee1b575fcd39ddafb5782379f4b35
- 3a8937ba828b809c56e95765fe4d7f2ed5e926aa

**Comment by Kwiboo** [comment]
> @Kwiboo / @knaerzche - are these rebases ok? Otherwise let me know. If so I squash (change from wip) and finalise 6.4.
> 
> * [3ccfdf5](https://github.com/LibreELEC/LibreELEC.tv/commit/3ccfdf5653bee1b575fcd39ddafb5782379f4b35)
> * [3a8937b](https://github.com/LibreELEC/LibreELEC.tv/commit/3a8937ba828b809c56e95765fe4d7f2ed5e926aa)

I can take a closer look, the dropped patches should probably be reworked and not just dropped.

Currently slowly working on upstreaming rockchip hdmi 2.0 patches and will rework as progress is made.

**Comment by heitbaum** [comment]
> > @Kwiboo / @knaerzche - are these rebases ok? Otherwise let me know. If so I squash (change from wip) and finalise 6.4.
> > 
> > * [3ccfdf5](https://github.com/LibreELEC/LibreELEC.tv/commit/3ccfdf5653bee1b575fcd39ddafb5782379f4b35)
> > * [3a8937b](https://github.com/LibreELEC/LibreELEC.tv/commit/3a8937ba828b809c56e95765fe4d7f2ed5e926aa)
> 
> I can take a closer look, the dropped patches should probably be reworked and not just dropped.
> 
> Currently slowly working on upstreaming rockchip hdmi 2.0 patches and will rework as progress is made.

I’ll revisit looking today (and look if I can rebase) as It is an unpleasant “stay inside” winter day here

**Comment by heitbaum** [comment]
> > @Kwiboo / @knaerzche - are these rebases ok? Otherwise let me know. If so I squash (change from wip) and finalise 6.4.
> > 
> > * [3ccfdf5](https://github.com/LibreELEC/LibreELEC.tv/commit/3ccfdf5653bee1b575fcd39ddafb5782379f4b35)
> > * [3a8937b](https://github.com/LibreELEC/LibreELEC.tv/commit/3a8937ba828b809c56e95765fe4d7f2ed5e926aa)
> 
> I can take a closer look, the dropped patches should probably be reworked and not just dropped.
> 
> Currently slowly working on upstreaming rockchip hdmi 2.0 patches and will rework as progress is made.

@Kwiboo I’ve gone through the code today, the 3 dropped patches were across the same function `dw_hdmi_rockchip_mode_valid`. Diffs are below, few differences in that MODE_CLOCK_HIGH, ycbcr_420_allowed and no specific handling for 340000. I can see where the code has diverged but come back together in the mpll_cfg, but not quite sure on rebasing it all back together.

the brute force revert 6.5 to 6.4-LE patch is here 40ff3634f71b8bf1769d05a565e7275b6ecbac51 which is easier to read

**upstream change 6.4 to 6.5**
```
@@ -241,23 +250,39 @@
 }
 
 static enum drm_mode_status
-dw_hdmi_rockchip_mode_valid(struct dw_hdmi *hdmi, void *data,
+dw_hdmi_rockchip_mode_valid(struct dw_hdmi *dw_hdmi, void *data,
                            const struct drm_display_info *info,
                            const struct drm_display_mode *mode)
 {
+       struct rockchip_hdmi *hdmi = data;
        const struct dw_hdmi_mpll_config *mpll_cfg = rockchip_mpll_cfg;
        int pclk = mode->clock * 1000;
-       bool valid = false;
+       bool exact_match = hdmi->plat_data->phy_force_vendor;
        int i;
 
+       if (hdmi->ref_clk) {
+               int rpclk = clk_round_rate(hdmi->ref_clk, pclk);
+
+               if (abs(rpclk - pclk) > pclk / 1000)
+                       return MODE_NOCLOCK;
+       }
+
        for (i = 0; mpll_cfg[i].mpixelclock != (~0UL); i++) {
-               if (pclk == mpll_cfg[i].mpixelclock) {
-                       valid = true;
-                       break;
-               }
+               /*
+                * For vendor specific phys force an exact match of the pixelclock
+                * to preserve the original behaviour of the driver.
+                */
+               if (exact_match && pclk == mpll_cfg[i].mpixelclock)
+                       return MODE_OK;
+               /*
+                * The Synopsys phy can work with pixelclocks up to the value given
+                * in the corresponding mpll_cfg entry.
+                */
+               if (!exact_match && pclk <= mpll_cfg[i].mpixelclock)
+                       return MODE_OK;
        }
 
-       return (valid) ? MODE_OK : MODE_BAD;
+       return MODE_BAD;
 }
 
 static void dw_hdmi_rockchip_encoder_disable(struct drm_encoder *encoder)
```
**Downstream LE patches 6.4 to 6.4-LE**
```
@@ -245,19 +245,31 @@
                            const struct drm_display_info *info,
                            const struct drm_display_mode *mode)
 {
-       const struct dw_hdmi_mpll_config *mpll_cfg = rockchip_mpll_cfg;
-       int pclk = mode->clock * 1000;
-       bool valid = false;
-       int i;
-
-       for (i = 0; mpll_cfg[i].mpixelclock != (~0UL); i++) {
-               if (pclk == mpll_cfg[i].mpixelclock) {
-                       valid = true;
-                       break;
-               }
+       struct dw_hdmi_plat_data *pdata = (struct dw_hdmi_plat_data *)data;
+       const struct dw_hdmi_mpll_config *mpll_cfg = pdata->mpll_cfg;
+       int clock = mode->clock;
+       unsigned int i = 0;
+
+       if (pdata->ycbcr_420_allowed && drm_mode_is_420(info, mode) &&
+           (info->color_formats & DRM_COLOR_FORMAT_YCBCR420)) {
+               clock /= 2;
+               mpll_cfg = pdata->mpll_cfg_420;
+       }
+
+       if ((!mpll_cfg && clock > 340000) ||
+           (info->max_tmds_clock && clock > info->max_tmds_clock))
+               return MODE_CLOCK_HIGH;
+
+       if (mpll_cfg) {
+               while ((clock * 1000) < mpll_cfg[i].mpixelclock &&
+                      mpll_cfg[i].mpixelclock != (~0UL))
+                      i++;
+
+               if (mpll_cfg[i].mpixelclock == (~0UL))
+                       return MODE_CLOCK_HIGH;
        }
 
-       return (valid) ? MODE_OK : MODE_BAD;
+       return MODE_OK;
 }
 
 static void dw_hdmi_rockchip_encoder_disable(struct drm_encoder *encoder)
```
**Resulting difference between 6.4-LE and 6.5**
```

@@ -241,35 +250,39 @@
 }
 
 static enum drm_mode_status
-dw_hdmi_rockchip_mode_valid(struct dw_hdmi *hdmi, void *data,
+dw_hdmi_rockchip_mode_valid(struct dw_hdmi *dw_hdmi, void *data,
                            const struct drm_display_info *info,
                            const struct drm_display_mode *mode)
 {
-       struct dw_hdmi_plat_data *pdata = (struct dw_hdmi_plat_data *)data;
-       const struct dw_hdmi_mpll_config *mpll_cfg = pdata->mpll_cfg;
-       int clock = mode->clock;
-       unsigned int i = 0;
-
-       if (pdata->ycbcr_420_allowed && drm_mode_is_420(info, mode) &&
-           (info->color_formats & DRM_COLOR_FORMAT_YCBCR420)) {
-               clock /= 2;
-               mpll_cfg = pdata->mpll_cfg_420;
-       }
-
-       if ((!mpll_cfg && clock > 340000) ||
-           (info->max_tmds_clock && clock > info->max_tmds_clock))
-               return MODE_CLOCK_HIGH;
-
-       if (mpll_cfg) {
-               while ((clock * 1000) < mpll_cfg[i].mpixelclock &&
-                      mpll_cfg[i].mpixelclock != (~0UL))
-                      i++;
-
-               if (mpll_cfg[i].mpixelclock == (~0UL))
-                       return MODE_CLOCK_HIGH;
+       struct rockchip_hdmi *hdmi = data;
+       const struct dw_hdmi_mpll_config *mpll_cfg = rockchip_mpll_cfg;
+       int pclk = mode->clock * 1000;
+       bool exact_match = hdmi->plat_data->phy_force_vendor;
+       int i;
+
+       if (hdmi->ref_clk) {
+               int rpclk = clk_round_rate(hdmi->ref_clk, pclk);
+
+               if (abs(rpclk - pclk) > pclk / 1000)
+                       return MODE_NOCLOCK;
+       }
+
+       for (i = 0; mpll_cfg[i].mpixelclock != (~0UL); i++) {
+               /*
+                * For vendor specific phys force an exact match of the pixelclock
+                * to preserve the original behaviour of the driver.
+                */
+               if (exact_match && pclk == mpll_cfg[i].mpixelclock)
+                       return MODE_OK;
+               /*
+                * The Synopsys phy can work with pixelclocks up to the value given
+                * in the corresponding mpll_cfg entry.
+                */
+               if (!exact_match && pclk <= mpll_cfg[i].mpixelclock)
+                       return MODE_OK;
        }
 
-       return MODE_OK;
+       return MODE_BAD;
 }
 
 static void dw_hdmi_rockchip_encoder_disable(struct drm_encoder *encoder)
```

**Review by CvH — APPROVED** [review]

**Pull request merged**
