### PR TITLE
Linux update to 4.6

### PR DESCRIPTION
**Pull request by lrusak**
Some patch issues:
* [x] linux-052-XBOX_remote_support.patch.todo
  - ~~applies fine but doesn't build~~ updated, thanks @MattDevo 
* [x] linux-058.05-hid_sony-add_autorepeat_for_PS3_remotes.patch.todo
  - updated, thanks @MattDevo 
* [x] linux-063-xpad-fix_xbox360_wireless.patch.todo
  - @MattDevo ~~can you take care of this?~~ update thanks
* [x] linux-221-ngene-octopus.todo
  - ~~did this ever get fixed?~~, dropped
* [x] linux-950-saa716x_PCIe_interface_chipset.patch.todo
  - ~~applies fine but doesn't build~~ @vpeter4 , dropped
* [x] linux-999-i915-use-legacy-turbo.patch.todo
  - ~~not sure if needed anymore?~~ @fritsch, updated 
* [x] linux-990.06-hda-Avoid-outputting-HDMI-audio-before-prepare-.patch
  - ~~doesn't apply, upstreamed?~~ @stefansaraev
    - patch updated 

Some patch drops:
 - linux-006_enable_utf8.patch
  - doesn't apply, not sure if needed
 - linux-001-Intel-EDID-fix.patch
  - doesn't apply, upstreamed? @fritsch 
 - linux-224_Hauppauge_WinTV-soloHD.patch
  - upstreamed
 - linux-228-support-tt-ct2-4650-v2.patch
  - upstreamed
 - linux-229-avermedia-volar-hd2.patch
  - upstreamed
 - linux-231-fix-cx23885-ci-devices.patch
  - upstreamed

----

There seems to be some kernel header issues, this is noted here:
 - https://bugzilla.redhat.com/show_bug.cgi?id=1300256
 - https://github.com/poettering/systemd/commit/da678a5fde283b2b64a53ce217acf7151eced83f

The connman patch fixes this. Not sure how many other packages are broken, will find out after a clean build.

----

~~I think we need to move to the in kernel RTL8192CU driver also. I'll test this and amend this PR soon.~~

----

~~also, the RPi's don't build~~ @popcornmix
fixed in the latest rpi patch set.

----

Update: ~~RTL8192CU, RTL8812AU, and~~ dvbhdhomerun all fail to build with similar errors
```
/home/lukas/libreelec/build.LibreELEC-Generic.x86_64-8.0-devel/dvbhdhomerun-20130704/kernel/dvb_hdhomerun_fe.c:408:18: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .get_frontend = dvb_hdhomerun_fe_get_frontend,
                  ^
```

### CODE REVIEW

**Comment by stefansaraev** [comment]
@lrusak pick http://sprunge.us/DHbB or drop it. quick and dirty, not tested. no idea if needed. I just adapted it once. @anssi and @fritsch know more

feel free to drop linux-221-ngene-octopus. I wont update this even if you pay me ;)

**Comment by MattDevo** [comment]
I'll take a look at these later tonight, I have a feeling some of them 
might have been already upstreamed in 4.5/4.6

**Comment by popcornmix** [comment]
Just a warning that 4.6 kernel on Pi has a problem for me.
An nfs boot with raspbian usually hangs for a long time (several minutes) on boot although appears functional once booted. No idea what it is currently, so no ETA on a fix.
Not sure if this issue will affect LibreELEC, but make sure you test before merging.

**Comment by lrusak** [comment]
updated: builds on Generic and RPi/RPi2 now. Just the remaining patch issues and issues with the external linux drivers left.

**Comment by lrusak** [comment]
@fritsch any word on the Intel patches?

@vpeter4 do you care about linux-950-saa716x_PCIe_interface_chipset.patch.todo ?

**Comment by fritsch** [comment]
@lrusak which one, did it not apply? If we are talking about the audio support then it's for @piotrasd as  he has hw to test.

**Comment by lrusak** [comment]
@fritsch linux-999-i915-use-legacy-turbo.patch.todo and linux-001-Intel-EDID-fix.patch

**Comment by fritsch** [comment]
The turbo patch should be dropped as the upstream intel folks try to fix it differently. The EDID stuff did not yet make it into the kernel?

**Comment by piotrasd** [comment]
Hi
yes, i have 2 difrent boxes based on Atom x5-8300, and i get new patch for audio jack support. 
On days maybe even will be HDaudio …. im keep contact with main developer of this patch …


"BTW I also have an Ara Tronsmart X5 and you can enable the jack as well. look for my patches
http://mailman.alsa-project.org/pipermail/alsa-devel/2016-March/105332.html <http://mailman.alsa-project.org/pipermail/alsa-devel/2016-March/105332.html>, already merged at git://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git <git://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git>”

**Comment by vpeter4** [comment]
@lrusak: No, just drop it. If anyone needs it there are builds from CvH.

**Comment by fritsch** [comment]
@lrusak https://github.com/fritsch/linux/commit/aefcd1a6b1ec22e4e0d26eb932b618c5d12f7e9c after some people on intel irc told that they still needed it

**Comment by lrusak** [comment]
rebased to rc5 and updated with the comments.

The only outstanding issue is with dvbhdhomerun

**Comment by fritsch** [comment]
Don't forget the above cherry-pick :-)

**Comment by lrusak** [comment]
Cherry picked 😺

**Comment by lrusak** [comment]
I would like to merge this sooner than later as it takes work to rebase it.

The only problem right now is dvbhdhomerun not building but I have included a commit to disable building this external kernel module until a solution is found.

**Pull request merged**
