### PR TITLE
Elementaryos

### PR DESCRIPTION
**Pull request by mtkaalund**
Added support for install missing (host) packages for elementary os.

### CODE REVIEW

**Comment by lrusak** [comment]
Thanks. Why do you need to use quotes?

**Comment by mtkaalund** [comment]
Because $DISTRO will return elementary with quotes, so I did the least amount of change to the script.

**Comment by mtkaalund** [comment]
I don't know how many that uses elementary os and compiles libreelec, but I do sometimes (I'm a nerd, I know). So I did this because, I'm lazy and I don't want to install packages manually

**Comment by lrusak** [comment]
what is the output of `cat /etc/os-release`

**Comment by Starbix** [comment]
``http://elementary.io/``

**Comment by mtkaalund** [comment]
Sorry for not answering in a while, been busy moving to a new appartment. But as Starbix has written it is:
`NAME="elementary OS"
VERSION="0.4 Loki"
ID="elementary"
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 0.4 Loki"
VERSION_ID="0.4"
HOME_URL="http://elementary.io/"
SUPPORT_URL="http://elementary.io/support/"
BUG_REPORT_URL="https://bugs.launchpad.net/elementary/+filebug"
`

**Pull request merged**
