### PR TITLE
Rockchip: switch to mainline u-boot

### PR DESCRIPTION
**Pull request by Kwiboo**
This PR switches Rockchip project to use mainline u-boot instead of vendor u-boot.
`bootloader/install` has been reworked and most parts dealing with what blob to use has been moved to the `rkbin` package.

The following blobs is used after this PR:
- RK3288: no blobs
- RK3328: `bl31.elf` and `ddr.bin`
  ddr init blob is used because open-source alternative is causing an unstable HDMI signal
- RK3399: `bl31.elf`

This needs more runtime testing on different rockchip devices, I have runtime tested on:
- RK3288 Tinker Board S
- RK3328 Rock64
- RK3399 RockPi 4

### CODE REVIEW

**Comment by jernejsk** [comment]
Allwinner project needs following changes: http://ix.io/2AqL (build tested only)

**Comment by chewitt** [comment]
I've done some testing with the two patches in this tree https://github.com/chewitt/u-boot/commits/2020.10-patches with newer Amlogic devices and so far no problems.

**Comment by Kwiboo** [comment]
@jernejsk  @chewitt thanks! I have updated the u-boot v2020.10 commit with your changes and did a quick `scripts/unpack` check.
I will create a new PR with the update to v2020.10 and let this PR only handle the rockchip switch to mainline u-boot.

**Comment by lkundrak** [comment]
Hi @Kwiboo 

we've tested this patch set, rebased on master with U-Boot 2021.01 on @petr-chlupaty's Rockpro64 board and can confirm that Rockpro64 (RK3399) works well too.

It's actually better, because the Rockchip's U-Boot seems to do something to the ethernet PHY that dramatically increases packet loss on 1Gbps media. (Sorry, I haven't traced the issue down, given the boot loader update just fixes things and I've seen forum posts that indicate it's a known issue on some revisions of the board.)

Thanks for your work on this.

Lubo

**Comment by mo123** [comment]
Anyone working on an updated patch?
Would be very useful to have mainline u-boot working for RK3328/RK3399 devices.

**Comment by CvH** [comment]
@knaerzche any news here ?

**Comment by mo123** [comment]
Anyone working on a newer u-boot for Rockchip devices?
I see LibreELEC still uses u-boot from 12 Sep 2018, stock Rockchip u-boot which is very ancient.

A year ago I tested u-boot 2021.04 and everything worked fine on RK3399 ROC-PC-PLUS, RK3328 ROC-PC.
With current 2018 u-boot, RK3328 ROC-PC which is already in mainline kernel and merged into LibreELEC kernel package, can't boot since it needs 'rock64-rk3328_defconfig' and 2018 u-boot only has evb-rk3328_defconfig which is unbootable on it.

Armbian already uses 2021.07 u-boot and all supported Rockchip devices seem to work fine with it.
Perhaps it's packages and patches can be used?

**Comment by fliegenderfish** [comment]
Could someone confirm that this project is dead? Thats what it seems to me!
Thanks

**Comment by CvH** [comment]
superseeded by https://github.com/LibreELEC/LibreELEC.tv/pull/6885

**Pull request closed without merging**
