### PR TITLE
tvheadend 4.0 addon

### PR DESCRIPTION
**Pull request by CvH**
this is only the tvh 4.0.9-1 addon - needed for upgrade
@MilhouseVH mind a look

### CODE REVIEW

**Comment by stefansaraev** [comment]
fyi, when I tried this a month ago, tvheadend was crashing on start because it did not like our dvr-config

**Comment by CvH** [comment]
@stefansaraev I know that the log complains since forever about the dvr-config but never seen a crash due this. (I avoid to change something for Tvh 4.0.x - it is just here for upgrade purpose)
But I look if this works at least - real cleanup only for 4.2.

**Comment by MilhouseVH** [comment]
tvheadend is not really something I use, but I've managed to build this. No objections if you want to merge this.

**Comment by lrusak** [comment]
@CvH  is this good to go?

**Pull request merged**
