### PR TITLE
kodi: update to 21.0a3-Omega

### PR DESCRIPTION
**Pull request by jernejsk**
Update Kodi to 21.0 Alpha 3.

### CODE REVIEW

**Comment by jernejsk** [comment]
Without removing `DEPENDS_PATH` Kodi doesn't build, but I'm not sure if it has any other side effect.

**Comment by HiassofT** [comment]
`DEPENDS_PATH` was added by @lrusak in commit 98a96ef1f72 - see also PR #768 

Best to wait for his comments on that, the (side-) effects are not 100% clear to me

**Comment by heitbaum** [comment]
Run testing now.
```
=== tested on ===
Generic.x86_64-devel-20230910101005-4065bc6
Linux nuc12 6.5.2 #1 SMP Sat Sep  9 16:58:25 UTC 2023 x86_64 GNU/Linux
Starting Kodi (21.0-ALPHA3 (20.90.301) Git:21.0a3-Omega). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2023-09-10 by GCC 13.2.0 for Linux x86 64-bit version 6.5.2 (394498)
Running on LibreELEC (heitbaum): devel-20230910101005-4065bc6 12.0, kernel: Linux x86 64-bit version 6.5.2
FFmpeg version/source: 6.0
Host CPU: 12th Gen Intel(R) Core(TM) i7-1260P, 16 cores available
[    0.000000] DMI: Intel(R) Client Systems NUC12WSKi7/NUC12WSBi7, BIOS WSADL357.0088.2023.0505.1623 05/05/2023
CApplication::CreateGUI - trying to init gbm windowing system
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_RENDERER = Mesa Intel(R) Graphics (ADL GT2)
GL_VERSION = OpenGL ES 3.2 Mesa 23.2.0-rc3
libva info: VA-API version 1.19.0
vainfo: VA-API version: 1.19 (libva 2.19.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.3.3 (60b582202e)
```

**Comment by lrusak** [comment]
> Without removing `DEPENDS_PATH` Kodi doesn't build, but I'm not sure if it has any other side effect.

it's just an old leftover, shouldn't be needed.

**Review by HiassofT — APPROVED** [review]

**Pull request merged**
