### PR TITLE
linux: Haswell black screen fix for Generic

### PR DESCRIPTION
**Pull request by mglae**
Haswell black screen patch, see description in patch.

### CODE REVIEW

**Comment by HiassofT** [comment]
Can you split off the IOMMU kernel config change? This commit can go in immediately.

Keep the haswell test hack commit as a "MERGE BLOCKED" PR so others can test it (it shouldn't go into LE)

**Comment by CvH** [comment]
the haswell hack looks working, dmesg is now happy again

**Comment by mglae** [comment]
@CvH Thanks for testing.

The patch was created using normal workflow: bisecting the failing commit and reverting it. The only hack is the reversion by disabling the initialization of the new functionality.

**Comment by CvH** [comment]
after some usage I can report that it is now properly working again :)

I would wait till kernel 5.9 is merged and the revisit this pr, maybe that got fixed upstream in the meantime.

**Comment by mglae** [comment]
According to an issue post there was no fix in rc5.

**Comment by HiassofT** [comment]
If you want to add this as a temporary workaround until the issue is fixed upstream please move the patch to projects/Generic/patches/linux (so it doesn't affect other projects) and rename it to something like "linux-XYZ-temporary-workaround-for-haswell-issues.patch" so it's clear what it is.

**Comment by mglae** [comment]
Moved.

**Pull request merged**
