### PR TITLE
vdr-addon: support locale / wirbelscan and vnsi fixes (115) 

### PR DESCRIPTION
**Pull request by mglae**
Add language support using locale to vdr-addon.

Install and configure Locale Addon to use this feature. Visible in Live Plugin WEB interface and VDR console interface via "PVR Settings" -> "Client specific" in Kodi.

### CODE REVIEW

**Comment by mglae** [comment]
(Hopefully) fixed wirbelscan patch line endings.

**Comment by smp79** [comment]
Did you guys check if VDR OSD in "Client Specific Settings" work? It doesn't work here, at least on GBM/GLES x86 build.

**Comment by CvH** [comment]
Not sure how it works but likely it just uses vdrs x11 capabilities, so as long vdr doesn't support gbm its likely not working. 
VDR is feature wise basically dead since years, so not sure if this happens at all.

**Comment by CvH** [comment]
does this local changes are working with the new vdr-live (https://github.com/MarkusEh/vdr-plugin-live) too ?

**Comment by mglae** [comment]
> Did you guys check if VDR OSD in "Client Specific Settings" work?

Yes with X11. The OSD bitmap is transferred to pvr.vdr.vnsi and rendered using GL or GLES. Is there anything in debug log?

>  It is broken for a while now.

Define "while". There was a major rework in June.

**Comment by mglae** [comment]
> does this local changes are working with the updated vdr-live (https://github.com/MarkusEh/vdr-plugin-live) too ?

Technically the .mo files are added to the addon, the locale path is configured  and $LANG is allowed to be modified. There is no code change to vdr or plugins.

HEAD of MarkusEh/vdr-plugin-live is building fine and WEB interface can be opened.

**Comment by smp79** [comment]
> Is there anything in debug log?

`2021-01-26 01:11:20.502 T:813      INFO <general>: Loading skin file: /usr/share/kodi/addons/pvr.vdr.vnsi/resources/skins/skin.estuary/xml/Admin.xml, load type: LOAD_ON_GUI_INIT
2021-01-26 01:11:20.512 T:813     DEBUG <general>: [Warning] CGUITextureManager::GetTexturePath: could not find texture '-'
2021-01-26 01:11:20.513 T:813     DEBUG <general>: ------ Window Init (/usr/share/kodi/addons/pvr.vdr.vnsi/resources/skins/skin.estuary/xml/Admin.xml) ------
2021-01-26 01:11:20.513 T:813     DEBUG <general>: CGUIMediaWindow::GetDirectory ()
2021-01-26 01:11:20.513 T:813     DEBUG <general>:   ParentPath = []
`


> Define "while". There was a major rework in June.

I started doing GBM builds in April 2019 and it worked back then. It was broken sometime in 2020.

**Comment by mglae** [comment]
My debug log output is exactly the same.

There is a suspicious line in pvr.vdr.vnsi:
```
--- a/src/GUIWindowAdmin.cpp
+++ b/src/GUIWindowAdmin.cpp
@@ -589,7 +589,7 @@ bool cVNSIAdmin::Open(const std::string& hostname,
     return false;
 
   m_bIsOsdControl = false;
-#if defined(HAS_GL) || defined(HAS_GLES2)
+#if defined(HAS_GL) || defined(HAS_GLES)
   m_osdRender = new cOSDRenderGL();
 #else
   m_osdRender = new cOSDRender();
```

Better open an issue on https://github.com/kodi-pvr/pvr.vdr.vnsi

**Comment by smp79** [comment]
> There is a suspicious line in pvr.vdr.vnsi:

It didn't work, now can't even enter the "Client specific settings" menu.

> Better open an issue on https://github.com/kodi-pvr/pvr.vdr.vnsi

Ok.

**Comment by CvH** [comment]
is this good to go ?

**Comment by mglae** [comment]
Yes, my 9.2 backport is working fine in daily use.

**Review by CvH — APPROVED** [review]

**Pull request merged**
