### PR TITLE
some upstream changes and fixes

### PR DESCRIPTION
**Pull request by lrusak**
This includes some changes added to the upstream repo.

I have removed the mkpkg scripts as theses aren't needed with our new download method.

### CODE REVIEW

**Comment by lrusak** [comment]
Keep open till we sort out the RPi stuff

**Comment by lrusak** [comment]
should be good to go now :+1:

**Comment by HiassofT** [comment]
Just a quick heads-up, you might also want to pick up this RPi kernel commit
https://github.com/raspberrypi/linux/commit/942df43ddba2e7593ba577e720a7d56df0b10738

Without it the device-tree overlay builds weren't exactly reproducible and I got very strange effects (hard kernel lockups without backtrace on serial console) using the lirc-rpi overlay with gpio_in_pin set on OE master.

ping @MilhouseVH (but I guess it's already too late for your nightly OE build)

**Comment by MilhouseVH** [comment]
Thanks HiassofT - bit behind with tonight's OE build but I'll include this. We'll get it committed here ASAP, many thanks.

**Pull request merged**
