### PR TITLE
[le11] update to latest kodi master with DRMPRIME DVD fix

### PR DESCRIPTION
**Pull request by HiassofT**
The filter/deinterlaced patches were rebased by @popcornmix 

Runtime test on RPi4 was fine, DVD menus and deinterlacing still works.

@knaerzche @jernejsk please test on AW/RK

### CODE REVIEW

**Comment by HiassofT** [comment]
I've now moved all RPi deinterlace/filter improvements/fixes except for the YUV420 patch to the common kodi patch dir.

Unpacked source for RPi is identical to previous versions.

I'll keep this PR as draft until we have confirmation if this also works on AW and RK

**Comment by jernejsk** [comment]
It works on AW, thanks for working on unification!

**Comment by knaerzche** [comment]
Works fine in RK also, thx.

**Comment by HiassofT** [comment]
Thanks a lot to both of you for testing!

I've removed draft, approve and merge if you're happy

**Pull request merged**
