### PR TITLE
Please include 'who'

### PR DESCRIPTION
**Pull request by dagwieers**
It helps to have a POSIX-compliant way to find the uptime of a system.
Using */proc/uptime* or `uptime` output are not standardized on Unix.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Don't you want this in the target conf?

**Comment by dagwieers** [comment]
@MilhouseVH That explained why nothing was actually enabled. Thanks for that :-)

**Comment by MilhouseVH** [comment]
Any chance you could squash the commits into one (or just drop the 3rd and 1st commits)?

**Comment by dagwieers** [comment]
@MilhouseVH I edited the files online for convenience. This PR can be squashed on commit (which is a common thing in most projects I contribute to).

**Comment by MilhouseVH** [comment]
> That explained why nothing was actually enabled. Thanks for that :-)

No, you also need this change: http://ix.io/1mEU (see [coreutils/who.c](https://github.com/mirror/busybox/blob/master/coreutils/who.c#L20)).
```
config FEATURE_UTMP
        bool "Support utmp file"
        default y
        help
        The file /var/run/utmp is used to track who is currently logged in.
        With this option on, certain applets (getty, login, telnetd etc)
        will create and delete entries there.
        "who" applet requires this option.
```

In future please build and run-time test your own changes before submitting a *working* PR... :wink:

Please update the PR with the additional config change and then squash.

With this feature enabled (RPi2 image):
```
NEW FILE       Delta: 7            #0914: 7             #0913b: n/a          /usr/bin/who -> busybox
SIZE CHANGE    Delta: 4,116        #0914: 523,156       #0913b: 519,040      /usr/bin/busybox
```
Test output (2 users logged in):
```
LibreELEC (community): devel-20180914001936-#0914-g56eae68 (RPi2.arm)
rpi22:~ # who
root            pts/0           00:00   Sep 14 00:30:26  192.168.0.9
root            pts/1           00:00   Sep 14 00:30:32  192.168.0.9
```

**Comment by MilhouseVH** [comment]
> This PR can be squashed on commit (which is a common thing in most projects I contribute to).

It can, but that's not what we normally do in this project. Thanks for your understanding.

**Comment by dagwieers** [comment]
Thanks for the feedback.

**Pull request closed without merging**
