### PR TITLE
NVIDIA updates for kernel 5.14

### PR DESCRIPTION
**Pull request by heitbaum**
- xf86-video-nvidia: update to 460.91.03 and patch for kernel 5.14
- xf86-video-nvidia-legacy: allow build with kernel 5.14
  - pdev references have been removed
  - Kernel 5.14 no longer supported pdev.
  - .load and .unload for DRM will report -ENODEV. 
  - Update to .load and .uload functions will need to be done.

### CODE REVIEW

**Comment by CvH** [comment]
`python3 packages/x11/driver/xf86-video-nvidia/scripts/make_nvidia_udev.py` is not working for me and creates a empty udev rule, can you check if it works for you and adds new rules https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/x11/driver/xf86-video-nvidia/package.mk#L6? 

nvidia legacy is not building for me

**Comment by heitbaum** [comment]
> `make_nvidia_udev.py` is not working for me and creates a empty udev rule, can you check if it works for you and adds new rules https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/x11/driver/xf86-video-nvidia/package.mk#L6?

yes it deleted everything too. Will have a further look today now I’ve had some sleep :-)
Maybe I’ll try going back to PKG_VERSION="460.67" with the patch too.

> nvidia legacy is not building for me

Same - draft patch still needs ->pdev removed (a change between 5.13 and 5.14. It’s in a few places.

**Comment by heitbaum** [comment]
@CvH updated the patches so both compile now. nvidia-legacy I'm sure needs work - It is technically code correct - but I believe the logic will leave it with -ENODEV on the drm module load.

Regarding the `make_nvidia_udev.py` - looks like the data on the website have been changed. But from the diff between `460.67` and `460.91.03` there are only additional chips - just working through the python code now.

- http://us.download.nvidia.com/XFree86/Linux-x86_64/460.91.03/README/supportedchips.html
- http://us.download.nvidia.com/XFree86/Linux-x86_64/460.67/README/supportedchips.html

**These being the newly supported devices in `460.91.03`**
```
CMP 50HX 1E09
GeForce GTX 1650 with Max-Q Design 1F9D 1043 185C
GeForce GTX 1650 with Max-Q Design 1F9D 1462 12F4
GeForce GTX 1650 with Max-Q Design 1F9D 1462 1302
GeForce RTX 3080 Ti 2208
GeForce RTX 3080 2216
GeForce RTX 3070 Ti 2482
GeForce RTX 3070 2488
GeForce RTX 3060 Ti 2489
GeForce RTX 3060 2504
GeForce RTX 3050 Ti Laptop GPU 2523
GeForce RTX 3050 Ti Laptop GPU 2563
GeForce RTX 3050 Ti Laptop GPU 25A0
GeForce RTX 3050 Laptop GPU 25A2
GeForce RTX 3050 Laptop GPU 25A5
GeForce RTX 3050 Ti Laptop GPU 25E0
GeForce RTX 3050 Laptop GPU 25E2
GeForce RTX 3050 Laptop GPU 25E5
T1000 1FB0 10DE 12DB
T600 1FB1 10DE 1488
T400 1FB2 10DE 1489
T600 Laptop GPU 1FBA
T1200 Laptop GPU 1FBC
PG506-232 20B6 10DE 1492
A30 20B7 10DE 1532
RTX A5000 2231 10DE 147E
A10 2236 10DE 1482
A10G 2237 10DE 152F
RTX A4000 24B0 10DE 14AD
RTX A5000 Laptop GPU 24B6
RTX A4000 Laptop GPU 24B7
RTX A3000 Laptop GPU 24B8
RTX A2000 Laptop GPU 25B8
```

**Comment by CvH** [comment]
@warpme has maybe an idea, he has also some script to gerate the needed data https://github.com/warpme/minimyth2/blob/master/script/nvidia/nvidia-470.63.01/files/generate-nvidia-udev-rule.sh

**Comment by heitbaum** [comment]
> @warpme has maybe an idea, he has also some script to gerate the needed data https://github.com/warpme/minimyth2/blob/master/script/nvidia/nvidia-470.63.01/files/generate-nvidia-udev-rule.sh

Will have a look - dinner time here. My shell is much better than my python :-)

**Comment by lrusak** [comment]
@heitbaum you can use this commit. It seems the page returns 403 without it. https://github.com/lrusak/LibreELEC.tv/commit/84a5e1b824cbe9da80d7b1555c2e1d6d1031a87e

```
$ python3 packages/x11/driver/xf86-video-nvidia/scripts/make_nvidia_udev.py 
b'<?xml version="1.0" encoding="iso-8859-1"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\n         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">\n\t<head>\n\t\t<title>403 - Forbidden</title>\n\t</head>\n\t<body>\n\t\t<h1>403 - Forbidden</h1>\n\t</body>\n</html>\n'

```

**Comment by heitbaum** [comment]
> @heitbaum you can use this commit. It seems the page returns 403 without it. [lrusak@84a5e1b](https://github.com/lrusak/LibreELEC.tv/commit/84a5e1b824cbe9da80d7b1555c2e1d6d1031a87e)

Thank you @lrusak - Added, and fixed the `96-nvidia.rules`

**Comment by SupervisedThinking** [comment]
@heitbaum what about https://www.nvidia.com/Download/driverResults.aspx/179599/en-us

**Comment by heitbaum** [comment]
> @heitbaum what about https://www.nvidia.com/Download/driverResults.aspx/179599/en-us

I did look at that and thought best run with 460 first and have a look at 470 after. Need someone to do the testing :-)

**Comment by CvH** [comment]
it builds

**Review by CvH — APPROVED** [review]

**Pull request merged**
