### PR TITLE
reduce $DEVICE complexity

### PR DESCRIPTION
**Pull request by Kwiboo**
This PR adds support to use $DEVICE in shell version output and also changes to use same formatting as in the settings addon (`<device/project>.<arch>`)

Before:
```
LibreELEC (community): devel-20170711073201-r25890-ge7ffdc769 (Rockchip arm)
```
After:
```
LibreELEC (community): devel-20170711073201-r25890-ge7ffdc769 (TinkerBoard.arm)
```

### CODE REVIEW

**Comment by MilhouseVH** [comment]
No objection to this change in principal, but it could be simplified to:
```
-echo "$DISTRONAME ($LIBREELEC_BUILD): $LIBREELEC_VERSION ($PROJECT $TARGET_ARCH)" >> $INSTALL/etc/issue 
+echo "$DISTRONAME ($LIBREELEC_BUILD): $LIBREELEC_VERSION (${DEVICE:-${PROJECT}}.$TARGET_ARCH)" >> $INSTALL/etc/issue 
```
The `${DEVICE:-${PROJECT}}` approach could probably be used in several other places and would avoid the more cumbersome - but admittedly more explicit - `if..then..else`.

Just a matter of style/preference, really.

**Comment by Kwiboo** [comment]
I like the `${DEVICE:-$PROJECT}` approach and have pushed a fixup commit to remove some of the `if..then..else`, will squash after proper testing

**Comment by Kwiboo** [comment]
I made a small adjustment and defined `LIBREELEC_ARCH="${DEVICE:-$PROJECT}.$TARGET_ARCH"` that is reused instead

**Comment by Kwiboo** [comment]
Squashed and updated to use the `${DEVICE:-$PROJECT}` approach in `config/path` and `scripts/create_addon`.
Also made `scripts/image` pass `$DEVICE` to `scripts/mkimage`

**Comment by MilhouseVH** [comment]
Looks good to me, @lrusak any concerns?

**Comment by MilhouseVH** [comment]
Might also be worth backporting this to libreelec-8.2?

**Pull request merged**
