### PR TITLE
scripts/create_addon: improve PKG_ADDON_PROJECTS check

### PR DESCRIPTION
**Pull request by Kwiboo**
This PR changes `PKG_ADDON_PROJECTS` to allow a similar pattern matching as `PKG_ARCH`.

Allows "any !DEVICE" to be interpreted as "any device, but not DEVICE".

Also updates docker addon packages to make use of this change and allows building with all projects and devices except for WeTek_Core and WeTek_Play that is using amlogic-3.10 kernel.

Old:
~~This PR changes to check for both `PROJECT` and `DEVICE` in `PKG_ADDON_PROJECTS` instead of only `DEVICE` if it was defined.~~
~~Allows for adding `Rockchip` to `PKG_ADDON_PROJECTS` and not all devices to docker addon.~~

~~This will have an impact on addons for `Slice` and `Slice3`, whey will now include `dispmanx_vnc` and `rpi-tools` that both have `PKG_ADDON_PROJECTS="RPi RPi2"`
If this is not desired maybe we should add a `PKG_ADDON_DEVICES` instead~~

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I don't think you can do it like this - the problem is that we now conflate DEVICE and PROJECT, which is a problem when a device has the same name as a project eg. the device RPi has the same name as the RPi project.

So, when a package is defined as "PKG_ADDON_PROJECTS=RPi", then with this change it will build for RPi (which is the PROJECT) as well as RPi2 and Slice and Slice3 (which are all devices within the RPi project) even though the intention is that the add-on is compatible only with RPi (the device) and not any of those other devices.

This isn't an issue for the Rockchip project where all the devices have different names to the project, but is a problem for RPi.

Essentially, DEVICE trumps PROJECT as far as PKG_ADDON_PROJECTS is concerned - if DEVICE is defined, then PROJECT is irrelevant (which is what the existing code implements).

I understand what you are trying to achieve, but I think we do one of the following:

1. add all the Rockchip devices to the PKG_ADDONS_PROJECTS of add-ons where they are compatible - tedious, but accurate
2. add some sort of notation to PKG_ADDONS_PROJECTS, such as `Rockchip:all` that can be used to express the fact that a particular addon is compatible with all devices within a given project
3. add PKG_ADDON_DEVICES which specifies individual devices (that you'd be adding in #1 anyway)

With PKG_ADDON_DEVICES I assume the logic would be something like:
```
if ! listcontains "${PKG_ADDON_PROJECTS}" "${DEVICE:-${PROJECT}}" && 
   ! listcontains "${PKG_ADDON_DEVICES}" "${DEVICE}"; then
  echo "*** ERROR: $PKG_ADDON_ID: '${DEVICE:-${PROJECT}}' not supported ***"
  exit 0
fi
```
I think I'd favour #1 because it is consistent and relatively straight forward, but does involve more work when initially adding a new project. #2 and #3 will probably involve almost as much work as #1.

The problem with #2 is that if, at some point in the future you add a new device that has different capabilities to existing devices meaning some addons are incompatible, you're stuffed and have to revise all the addon that are using `Rockchip:all`, whereas with #1 you're in better shape.

Sorry if this has been a bit of a ramble...

**Comment by Kwiboo** [comment]
@MilhouseVH thanks for your feedback, I will change to include `DEVICE` in `PKG_ADDON_PROJECTS` for now.

Another idea would be to change the `PKG_ADDON_PROJECTS` check and make it similar to the `PKG_ARCH` check in `scripts/build`, that should allow changing docker addon package to something like `PKG_ADDON_PROJECTS="any !WeTek_Core !WeTek_Play"`.

**Comment by MilhouseVH** [comment]
> something like PKG_ADDON_PROJECTS="any !WeTek_Core !WeTek_Play".

That could work, yes.

**Comment by Kwiboo** [comment]
Changed to make `PKG_ADDON_PROJECTS` allow a similar patter matching as `PKG_ARCH`

**Comment by MilhouseVH** [comment]
Thanks. I think this should work, although I guess we won't know for sure unless we merge it. :)

I propose leaving this for a day or two for further comments, then get it in for testing.

Do you have plans to update/adapt `PKG_ADDON_PROJECTS` in the packages that will make use of this change?

**Comment by Kwiboo** [comment]
It worked similar to `PKG_ARCH` when I did some tests locally, but will be good to wait a day or two. :)

I would like to change the `docker` and `repository.linuxserver.docker` addons to use `PKG_ADDON_PROJECTS="any !WeTek_Core !WeTek_Play"`, wasn't sure if I should include such change in this PR or not.

Such change should allow docker addon for all new feature branch projects without having to add all devices to the addon packages.

To my knowledge `amlogic-3.10` is the only kernel not supporting docker, not sure why `Slice` or `Slice3` currently isn't in `PKG_ADDON_PROJECTS`.

**Comment by MilhouseVH** [comment]
You can add the package changes to this PR as an additional commit, that way if it needs to be reverted then it's all self contained (I don't think it will, but just in case!)

> not sure why Slice or Slice3 currently isn't in PKG_ADDON_PROJECTS.

Probably an oversight, although not sure anyone would realistically run `docker` on a Slice (or RPi) but presumably the only criteria is whether it builds not whether it is actually usable. Ping @chewitt as the wrangler of all things Slice.

**Comment by Kwiboo** [comment]
Added a commit with the proposed changes to docker addon packages.

**Comment by chewitt** [comment]
Slice/Slice3 use RPi/RPi2 add-ons respectively (via webserver aliases) so there is no need to build another set of add-ons for them. For the same reason you won't see WH/WP2 anywhere as those are using Odroid_C2 add-ons (again, via webserver aliases).

**Comment by Kwiboo** [comment]
This seems to work as intended in my tests, makes it possible to build the two docker addons on new projects/devices without having to add the project/device to a whitelist.

**Pull request merged**
