### PR TITLE
openssh: pointing package location to CDN

### PR DESCRIPTION
**Pull request by fnv-fnv**
There are issues with connection to ftp.openbsd.org due a network problems.
cdn.openbsd.org should be more reliable as using CDN technology to delivery package.

### CODE REVIEW

**Comment by heitbaum** [comment]
Confirmed CDN is the first http download location.

https://www.openssh.com/portable.html#http 

2890D48C-56EB-4607-8B7E-FAEB966E4ACB

tested download

**Review by heitbaum — CHANGES_REQUESTED** [review]
Could you please shorten the commit message, so it doesn’t wrap.

**Comment by fnv-fnv** [comment]
Hope it's better now...

**Comment by CvH** [comment]
Can you squash your commits into a single one?

**Comment by fnv-fnv** [comment]
Sorry I still learn git and messed up the branch. I discard PR and send another one with proper format.

**Pull request closed without merging**
