### PR TITLE
mesa: update to 21.2.0

### PR DESCRIPTION
**Pull request by heitbaum**
backported patches are now included in upstream 21.1.0
- https://gitlab.freedesktop.org/mesa/mesa/-/issues/4605#note_890953
- https://cgit.freedesktop.org/mesa/mesa/log/?h=21.1&qt=author&q=Erico

Ann:
- https://lists.freedesktop.org/archives/mesa-dev/2021-May/225248.html
- https://lists.freedesktop.org/archives/mesa-dev/2021-August/225459.html
release notes:
- https://docs.mesa3d.org/relnotes/21.1.0.html
- https://docs.mesa3d.org/relnotes/21.2.0.html

**Mesa Drivers**
- The launch was announced from the first version of the branch 21.1.0  which has an experimental state and that after the final stabilization of the code, the stable version 21.1.1 will be released
- Mesa 21.1.0 features full OpenGL 4.6 compatibility for 965, iris (Intel), radeonsi (AMD), zink and llvmpipe drivers. Support for OpenGL 4.5 is available for AMD (r600) and NVIDIA (nvc0) GPUs, and OpenGL 4.3 for virgl (virtual Virgil3D GPU for QEMU / KVM). Vulkan 1.2 is compatible with Intel and AMD cards, and Vulkan 1.0 for VideoCore VI (Raspberry Pi 4).

**Mesa 21.2.0 Release Notes / 2021-08-04**

Mesa 21.2.0 is a new development release. People who are concerned with stability and reliability should stick with a previous release or wait for Mesa 21.2.1.

Mesa 21.2.0 implements the OpenGL 4.6 API, but the version reported by glGetString(GL_VERSION) or glGetIntegerv(GL_MAJOR_VERSION) / glGetIntegerv(GL_MINOR_VERSION) depends on the particular driver being used. Some drivers don’t support all the features required in OpenGL 4.6. OpenGL 4.6 is only available if requested at context creation. Compatibility contexts may report a lower version depending on each driver.

Mesa 21.2.0 implements the Vulkan 1.2 API, but the version reported by the apiVersion property of the VkPhysicalDeviceProperties struct depends on the particular driver being used.

**main novelties**

In this new version of the Mesa controllers we can find various improvements implemented in the controllers as well as in the support of the extensions and is that for example the controller RADV implements VRS support for use with any depth buffers, plus VRS improves productivity at the expense of quality.

The D3D12 Gallium Controller with an OpenGL layer over API DirectX 12 (D3D12) provides OpenGL 3.3 support when working with WARP (rasterizer software) and NVIDIA D3D12 drivers and is that the driver is used in the WSL2 layer to run Linux graphical applications on Windows.

Also noteworthy is the inclusion of a new venus driver which integrates the virtual GPU implementation (virtio-gpu) based on the Vulkan API.

On the other hand, it is noted that the Zink driver (an implementation of the OpenGL API on Vulkan) includes support for OpenGL 4.6 and OpenGL ES 3.1. Zink, which allows for hardware-accelerated OpenGL if your system has limited drivers to support only the Vulkan API. It is mentioned that Zink's performance is close to that of native OpenGL implementations.

Also in the lavapipe controller (a software rasterizer implementation for the Vulkan API analogous to llvmpipe, but for Vulkan) adds support for Vulkan 1.1 and implements the Vulkan extension VK_KHR_copy_commands2. The implementation of the software in lavapipe is based on duplicating the calls from the Vulkan API to the Gallium API.

On the part of the extensions new support for extensions is highlighted VK_KHR_workgroup_memory_explicit_layout and VK_KHR_zero_initialize_workgroup_memory for Vulkan RADV controllers (AMD) and ANV (Intel).

Of the other changes that stand out from this new version of Mesa 21.1.0:

- Added support for caching shaders in a single file.
- The Virgl (Virgil3D virtual GPU for QEMU / KVM) and Lima (ARM Mali GPU) drivers support disk shader caching.
- Added support for AMD GPU Aldebaran (gfx90a).
- New OpenGL extensions added:
- The RADV driver (for AMD GFX9 cards) added support for DRM format modifiers (VK_EXT_image_drm_format_modifier extension included).

### CODE REVIEW

**Comment by SupervisedThinking** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=Mesa-21.1.1-Released

**Comment by heitbaum** [comment]
> https://www.phoronix.com/scan.php?page=news_item&px=Mesa-21.1.1-Released

Updated

**Comment by heitbaum** [comment]
Updated

**Comment by zhangn1985** [comment]
@heitbaum would you like to include https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/11076 ?

**Comment by heitbaum** [comment]
> @heitbaum would you like to include https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/11076 ?

@zhangn1985 Any reason to bring it in to this draft PR? Will include it once it makes it into an official Mesa release. It is not planned to bring this mesa draft PR into LE10 at the moment - it is a placeholder to keep track of the current mesa and optionally allow community to pull updates.

**Comment by zhangn1985** [comment]
never mind, I will do it in my project.

**Comment by CvH** [comment]
@heitbaum can you update/remove draft ?

**Review by CvH — APPROVED** [review]

**Pull request merged**
