### PR TITLE
llvm: update to 3.9.0

### PR DESCRIPTION
**Pull request by lrusak**
This converts the package to use the new cmake build system.

Pretty trivial but should be tested by @MilhouseVH 

llvm isn't used by arm so I've ripped that stuff out.

### CODE REVIEW

**Comment by piotrasd** [comment]
new mesa will need also python mako, but for now there is no new stable release 
(im using master version, just prepeared eveything for Apollo Lake/Kaby Lake)

**Comment by lrusak** [comment]
updated to use static LLVM libs

**Comment by lrusak** [comment]
@MilhouseVH any issues here?

**Comment by vpeter4** [comment]
It doesn't build anymore on i386 host because llvm-config is used from target (64 bit binary). That's why llvm must be build for host too as was before. And then copied as llvm-config-host. Also LLVM_CONFIG must be changed in mesa package.
Not sure why this change was introduced but seems wrong to me.

**Pull request merged**
