### PR TITLE
kernel-firmware: add MediaTek mt7610 firmware

### PR DESCRIPTION
**Pull request by MilhouseVH**
https://forum.libreelec.tv/thread/21319-solved-osmc-wifi-dongle-on-rpi/?postID=134349#post134349

160KB addition
```
-rw-rw-r--  1 neil neil  80680 Feb  4 17:23 mt7610e.bin
-rw-rw-r--  1 neil neil  80288 Feb  4 17:23 mt7610u.bin
```

Edit: The mt7610e is for PCI adapters, currently only supported by Generic, and not worth the hassle of differentiating.

### CODE REVIEW

**Comment by chewitt** [comment]
Only the mt7610u firmware is required. I've never seen the PCIe version used and nobody is asking for it to be included.

**Comment by MilhouseVH** [comment]
If we don't include the MT760E firmware we should disable MT760E support in the Generic kernel as it's unlikely to be working if we don't include the firmware. I can include the MT760E firmware in the x86 build only (just couldn't be arsed) or drop it completely and disable it in the Generic kernel (really can't be arsed) - what's your preference?

**Comment by chewitt** [comment]
I'd disable the module in the kernel. It doesn't work and nobody is complaining. I've only seen this chip used in USB devices. Let's avoid the death of a thousand cuts.

**Comment by MilhouseVH** [comment]
Disabled in kernel (where enabled) and no longer including mt7610e.bin firmware.

**Pull request merged**
