### PR TITLE
media_build: update to 2017-04-17-rpi

### PR DESCRIPTION
**Pull request by MilhouseVH**
Update to latest media_build package.

This includes support for CXD2880 which is a Sony DVB-T2/T tuner to be used by RPi (many thanks @CvH).

### CODE REVIEW

**Comment by MilhouseVH** [comment]
We've found some RC button repeat breakage when using this new `media_build` package with 4.10.11 (button repeat is fine without this bump) so don't merge this just yet...

**Comment by CvH** [comment]
problem exist in kernel >= 4.11 
@HiassofT  ideas ?

**Comment by HiassofT** [comment]
> problem exist in kernel >= 4.11 
> @HiassofT  ideas ?

It seems the same issue that bit us in 4.6/4.7, was fixed in July
after I reported it on linux-media has been reintroduced with 4.11-rc1

milhouse is currently testing a proposed fix from me

**Comment by MilhouseVH** [comment]
Button repeat fix patch added. Works OK with 4.10.11 and 4.11-rc7 kernels. Patch needs to go upstream where I guess it will be picked up by a future media_tree.

**Pull request merged**
