### PR TITLE
hddtemp: update urls to new project site

### PR DESCRIPTION
**Pull request by redwil**
Don't know if this is the proper way to do it so you are welcome to comment in any way you see fit

### CODE REVIEW

**Comment by Raybuntu** [comment]
Looks good but the commit message should be changed to meet the standard.
I'll let upstream suggest one since I never bothered to learn it.
Something like:
hddtemp: change PKG_SITE to new url

**Comment by redwil** [comment]
Sorry guys, my first time doing a pull request.
I did not give to much thought.
@CvH thank you for changing title
@MilhouseVH savannah was the only 'official' place to get the .db file. I must admit I have not looked at the sig file and seem to be a gpg signature file as per savannah protocol for uploading files. OTOH hddtemp.db is a text file that can be added (after review) to the build tree. The drawback will be occasion requests to update the file although whoever wants to use hddtemp addon ought to know how to use the underlying program.
I am not quite sure what you guys want me to do exactly. I can:
 - change the commit message
 - make a new pull request adding the hddtemp.db file
 - whatever you may think of in such way that i do not step on peoples toes.

BTW: the hddtemp project seem abandoned and as far as I seen issues are not addressed (both on github and savannah)

thanks

**Comment by redwil** [comment]
so far i tried to change the commit comment and removed the .sig file for is useless without being used to verify the content of hddtemp.db
I apologize in advance if I made any newbie mistakes

**Comment by MilhouseVH** [comment]
The problem is you didn't create a feature branch for the PR so you're pushing changes from your `master` (which now includes merges and other changes unrelated to this PR). Are you using the github web interface or `git` command line? If it's the former then give up now and start again as any type of change usually goes to complete shit.

> BTW: the hddtemp project seem abandoned and as far as I seen issues are not addressed (both on github and savannah)

All the more reason to include the db file in the package directory rather than continue downloading it. We'll be hosting the tarball on the LibreELEC mirror so that's not an issue if the project disappears from the web, but if the database disappears then this add-on would be finished.

**Comment by redwil** [comment]
It is obvious I have no clue whatsoever about how to properly propose a PR and I deeply regret your waste of time. 
I will close this hoping is the right thing to do.
If you wish me to try again maybe it's a good time to point me into the right direction to read about the workflow you are using here and hopefully it will be better

**Comment by MilhouseVH** [comment]
Closing isn't the outcome I was looking for, but the unfortunate fact is that whenever anyone uses the github web interface to push a PR it usually becomes a nightmare for the committer to change/update/squash commits as the github web interface doesn't really support this kind of functionality.

To do this PR "right" you are better off using the command line `git` (instructions assume a Linux OS):

1. `git clone https://github.com/redwil/LibreELEC.tv`
2. `cd LibreELEC.tv`
3. `git remote add upstream https://github.com/LibreELEC/LibreELEC.tv`
4. `git pull upstream master`
5. `git checkout -b hddtemp-fix` (this creates a "feature" branch)
<make your changes, use `git add -A` then `git commit -am "hddtemp: add url"`>
6. `git push -f` to push your changes to github.com.

And now on github.com you should be able to create a new PR.

If you need to make changes then you can add new commits, squash with `git rebase HEAD~n` (where n is the number of commits to consider) and force push your changes (which automatically updates the PR on github.com).

If you'd rather not do this then let me know and I'll take a look at it later.

**Pull request closed without merging**
