### PR TITLE
kodi: batched updates

### PR DESCRIPTION
**Pull request by MilhouseVH**
To be updated during October.

### CODE REVIEW

**Comment by adamg-xda** [comment]
The following binary addons have also been updated

audiodecoder.stsound
audioencoder.vorbis
game.libretro.genplus
game.libretro.hatari
game.libretro
inputstream.adaptive
inputstream.rtmp
pvr.pctv
pvr.stalker

**Comment by MilhouseVH** [comment]
@adamg-xda the updating of binary addons is [almost entirely automated](https://github.com/LibreELEC/LibreELEC.tv/blob/master/tools/mkpkg/update_binary-addons) these days - I'll re-run the script shortly before submitting a final version of this PR, which will automatically include those in your list (and no doubt others). No need to maintain a manual list!

game addons are out of scope for this PR though (@lrusak: do you want me to add them?)

**Comment by adamg-xda** [comment]
@MilhouseVH I didn't know you had these automated, makes me feel a little stupid for spending over an hour looking through them now =(

**Comment by MilhouseVH** [comment]
Updated, but note that JSON-RPC now returns a version of `0.3.0` (rather than `8.3.0`), presumably something is wrong with:

https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/mediacenter/kodi/patches/kodi-100.70-fix-json.patch

Also see https://github.com/xbmc/xbmc/pull/12936 which introduces the same issue (though not in this version of Kodi) as it tries to fix the same problem our patch does.

**Comment by MilhouseVH** [comment]
WIP removed.

**Comment by MilhouseVH** [comment]
JSON-RPC version should be fixed now.

**Comment by MilhouseVH** [comment]
I've no more updates planned for this PR, it's bang up to date and ready to go in.

**Pull request merged**
