### PR TITLE
ffmpeg: Bump to release/3.1-xbmc (67171c3)

### PR DESCRIPTION
**Pull request by MilhouseVH**

### CODE REVIEW

**Comment by axbmcuser** [comment]
Generated/extracted chapter thumbnails are often totally pixelated after this commit. (ffmpeg 3.1.x)

I reverted d11b730 - and pixelation while generating chapter thumbnails is gone. (back on ffmpeg 3.0.x)

**Comment by MilhouseVH** [comment]
This would most likely be an upstream issue with Kodi (it's the Kodi ffmpeg we are using). Can you confirm you have pixellated thumbnails with Kodi master built on Ubuntu? A screenshot of the pixellation might provide a clue as to the cause.

**Comment by axbmcuser** [comment]
Debug snippet:
`00:04:21 T:140501422364416   DEBUG: FactoryCodec - Video:  - Opening
00:04:21 T:140501422364416  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
00:04:21 T:140501422364416   DEBUG: CDVDVideoCodecFFmpeg - Updated codec: ff-h264
00:04:21 T:140501422364416   DEBUG: FactoryCodec - Video: ff-h264 - Opened
00:04:21 T:140501422364416   DEBUG: ExtractThumb - seeking to pos 4995000ms (total: 5552843ms) in smb://WINSVR/SMB/TESTLIB/Test Movie (2015)/Test Movie (2015).mkv
00:04:21 T:140500342482688    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
00:04:21 T:140501422364416   DEBUG: SeekTime - seek ended up on time 4994698
00:04:21 T:140501422364416   DEBUG: cached image 'special://masterprofile/Thumbnails/3/3cbbf19b.jpg' size 720x404
00:04:21 T:140500342482688   DEBUG: Thread FileCache 140500342482688 terminating
00:04:21 T:140501422364416   DEBUG: CSMBFile::Close closing fd 10001
00:04:21 T:140501422364416   DEBUG: ExtractThumb - measured 563 ms to extract thumb from file <smb://WINSVR/SMB/TESTLIB/Test Movie (2015)/Test Movie (2015).mkv> in 54 packets.
00:04:21 T:140501422364416   DEBUG: DoWork - trying to extract thumb from video file smb://WINSVR/SMB/TESTLIB/Test Movie (2015)/Test Movie (2015).mkv
00:04:21 T:140501422364416   DEBUG: CFileCache::Open - opening <SMB_1/00 HARDDISKS/HDD J/VIDEO/DISCS___/The Witch (2015)/The Witch (2015).mkv> using cache
00:04:21 T:140501422364416   DEBUG: CSMBFile::Open - opened smb://WINSVR/SMB/TESTLIB/Test Movie (2015)/Test Movie (2015).mkv, fd=10001
00:04:21 T:140500342482688   DEBUG: Thread FileCache start, auto delete: false
00:04:21 T:140501422364416   DEBUG: Open - probing detected format [matroska,webm]
00:04:21 T:140501422364416   DEBUG: Seek - waiting for position 25235739066.
00:04:21 T:140501422364416   DEBUG: Open - avformat_find_stream_info starting
00:04:21 T:140501422364416   DEBUG: ffmpeg[7FC9095ED700]: [matroska,webm] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle): unspecified size
00:04:21 T:140501422364416   DEBUG: ffmpeg[7FC9095ED700]: [matroska,webm] Consider increasing the value for the 'analyzeduration' and 'probesize' options
00:04:21 T:140501422364416   DEBUG: ffmpeg[7FC9095ED700]: [matroska,webm] Could not find codec parameters for stream 4 (Subtitle: hdmv_pgs_subtitle): unspecified size
00:04:21 T:140501422364416   DEBUG: ffmpeg[7FC9095ED700]: [matroska,webm] Consider increasing the value for the 'analyzeduration' and 'probesize' options
00:04:21 T:140501422364416   DEBUG: ffmpeg[7FC9095ED700]: [matroska,webm] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle): unspecified size
00:04:21 T:140501422364416   DEBUG: ffmpeg[7FC9095ED700]: [matroska,webm] Consider increasing the value for the 'analyzeduration' and 'probesize' options
00:04:21 T:140501422364416   DEBUG: Open - av_find_stream_info finished
00:04:21 T:140501422364416   DEBUG: CDVDDemuxFFmpeg::AddStream ID: 0
00:04:21 T:140501422364416   DEBUG: CDVDDemuxFFmpeg::AddStream ID: 1
00:04:21 T:140501422364416   DEBUG: CDVDDemuxFFmpeg::AddStream ID: 2
00:04:21 T:140501422364416   DEBUG: CDVDDemuxFFmpeg::AddStream ID: 3
00:04:21 T:140501422364416   DEBUG: CDVDDemuxFFmpeg::AddStream ID: 4
00:04:21 T:140501422364416   DEBUG: CDVDDemuxFFmpeg::AddStream ID: 5
00:04:21 T:140501422364416   DEBUG: FactoryCodec - Video:  - Opening
00:04:21 T:140501422364416  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
00:04:21 T:140501422364416   DEBUG: CDVDVideoCodecFFmpeg - Updated codec: ff-h264
00:04:21 T:140501422364416   DEBUG: FactoryCodec - Video: ff-h264 - Opened
00:04:21 T:140501422364416   DEBUG: ExtractThumb - seeking to pos 5282000ms (total: 5552843ms) in smb://WINSVR/SMB/TESTLIB/Test Movie (2015)/Test Movie (2015).mkv
00:04:21 T:140500342482688    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
00:04:21 T:140501422364416   DEBUG: SeekTime - seek ended up on time 5281651
00:04:22 T:140501422364416   DEBUG: cached image 'special://masterprofile/Thumbnails/6/6c995e47.jpg' size 720x404
00:04:22 T:140500342482688   DEBUG: Thread FileCache 140500342482688 terminating
00:04:22 T:140501422364416   DEBUG: CSMBFile::Close closing fd 10001
00:04:22 T:140501422364416   DEBUG: ExtractThumb - measured 501 ms to extract thumb from file <smb://WINSVR/SMB/TESTLIB/Test Movie (2015)/Test Movie (2015).mkv> in 39 packets.
00:04:51 T:140501592303360   DEBUG: Thread JobWorker 140501592303360 terminating (autodelete)
00:04:51 T:140501567125248   DEBUG: Thread JobWorker 140501567125248 terminating (autodelete)
00:04:51 T:140500392736512   DEBUG: Thread JobWorker 140500392736512 terminating (autodelete)
00:04:52 T:140501422364416   DEBUG: Thread JobWorker 140501422364416 terminating (autodelete)`

0d40d17b

**Comment by MilhouseVH** [comment]
OK, it's the same on RPi2 (LibreELEC master) and todays Kodi master built on Ubuntu 16.04 so this is not strictly a LibreELEC issue - I've mentioned it to @fritsch but this really needs a trac issue opened on trac.kodi.tv

**Comment by axbmcuser** [comment]
Great. So it's tested and verified broken on LibreELEC, Windows and Ubuntu. Added debug snippet.

**Comment by axbmcuser** [comment]
http://trac.kodi.tv/ticket/16803

**Comment by fritsch** [comment]
Post a full debuglog with the Pi and ffmpeg component debug logging while
creating such a broken thumb, please.
Am 13.07.2016 12:46 vorm. schrieb "axbmcuser" <notifications@github.com>:

**Comment by axbmcuser** [comment]
I have no RPi available (only a LibreELEC Haswell NUC and Windows machine) and i'm out of reach until this evening.
@MilhouseVH - maybe you can supply the requested RPi log, since you verified the error there successfully yesterday? If not, i can supply a NUC log later. Thanks all.

**Comment by MilhouseVH** [comment]
Replied on trac.

**Comment by axbmcuser** [comment]
I read it - will check this weekend! 

As a pre-info: I can say, that it's absolutely common and "clean" 1080p mkv-content which is muxed with stable and not too old versions of mkvtoolnix. Since all the h264 content with this outlined specs seems to be affected, you won't find anything special in a sample file (which i'll try to provide).

**Comment by fritsch** [comment]
Sadly besides you no one can reproduce.

Am 15.07.2016 1:33 nachm. schrieb "axbmcuser" <notifications@github.com>:

**Comment by axbmcuser** [comment]
Sorry for the delay. 
Debug log with ffmpeg component debug: http://pastebin.com/raw/i6L3kRhG

Problem still happens with latest nightlies on both my Intel Haswell test systems (Windows + Linux/LibreELEC)

Content is still absolutely common "untouched" h264 1080p .mkv content. (~30GB+) 
Happens on almost all similar test files. No difference playing local or over LAN.

If still needed, i will check if i can provide a file snippet with with a few chapters.

**Comment by axbmcuser** [comment]
Still happens with LibreELEC @ ffmpeg 3.1.2, pixelation visually unchaged (therefore did not make new logs). Posted log as above on tract. Thanks!

**Comment by MilhouseVH** [comment]
Fixed by https://github.com/xbmc/xbmc/pull/10391 - thanks for reporting.

**Pull request merged**
