### PR TITLE
Allwinner: add Crust support for bananapi-m2-zero

### PR DESCRIPTION
**Pull request by mklein-de**
This enables poweroff on the Banana PI M2 Zero and reduces the current
consumption after poweroff from ~160mA to ~40mA

### CODE REVIEW

**Comment by jernejsk** [comment]
Since this is a media center distro, wouldn't it be better to add missing pieces for Crust support? That way you could wake up your device either via power button or via HDMI CEC and it would also disable regulators and clocks as much as possible, so you should get similar low power consumption.

Crust should be easy to enable:
1. copy projects/Allwinner/devices/H3/patches/u-boot/0001-DO-NOT-MERGE-sunxi-psci-Delegate-PSCI-to-SCPI.patch to H2-plus folder
2. add Crust config to scripts/uboot_helper. I guess orangepi_one_defconfig should work just well
3. add a patch for DT, which marks power button as wake up source and changes button function to power key. Check https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Allwinner/patches/linux/0035-h3-h5-power-key-wake-up-source.patch for examples.

**Comment by jernejsk** [comment]
Ah, I forgot one last item:
4. add `UBOOT_FIRMWARE="crust"` to projects/Allwinner/devices/H2-plus/options

**Comment by mklein-de** [comment]
> Ah, I forgot one last item: 4. add `UBOOT_FIRMWARE="crust"` to projects/Allwinner/devices/H2-plus/options

Yeah, I figured this out coincidentally. Deep sleep current is at ~110mA with Crust now according to a cheap USB power meter,

**Comment by jernejsk** [comment]
Please move Linux patch to common folder (projects/Allwinner/patches/linux), then it's good to go.

BTW, since there is no IR on board, I guess you can add if clause around https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/tools/crust/package.mk#L40-L41 It should help with current consumption. I guess you could check if ${UBOOT_SYSTEM} matches "bananapi-m2-zero" or not.

**Comment by mklein-de** [comment]
> Please move Linux patch to common folder (projects/Allwinner/patches/linux), then it's good to go.

Almost, the Crust-enabled image breaks WiFi:

```
[    8.497419] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[    8.497757] usbcore: registered new interface driver brcmfmac
[    8.498479] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430-sdio.sinovoip,bpi-m2-zero.bin failed with error -2
[    8.692942] Bluetooth: HCI UART driver ver 2.3
[    8.692981] Bluetooth: HCI UART protocol H4 registered
[    8.692989] Bluetooth: HCI UART protocol BCSP registered
[    8.693108] Bluetooth: HCI UART protocol LL registered
[    8.693120] Bluetooth: HCI UART protocol ATH3K registered
[    8.693189] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    8.693411] Bluetooth: HCI UART protocol Intel registered
[    8.698274] Bluetooth: HCI UART protocol Broadcom registered
[    8.698368] Bluetooth: HCI UART protocol QCA registered
[    8.698379] Bluetooth: HCI UART protocol AG6XX registered
[    8.698436] Bluetooth: HCI UART protocol Marvell registered
[    8.782802] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[    8.922480] ieee80211 phy0: brcmf_fw_crashed: Firmware has halted or crashed
[    8.922529] ------------[ cut here ]------------
[    8.922537] WARNING: CPU: 1 PID: 64 at kernel/workqueue.c:1501 __queue_work+0x3b8/0x50c
[    8.922580] Modules linked in: hci_uart btqca btrtl btbcm btintel brcmfmac brcmutil bluetooth sun8i_ce lima gpu_sched crypto_engine ecdh_generic ecc cfg80211 rng_core sun8i_di display_connector fuse
[    8.922676] CPU: 1 PID: 64 Comm: kworker/u9:0 Not tainted 5.15.0 #1
[    8.922689] Hardware name: Allwinner sun8i Family
[    8.922699] Workqueue: brcmf_wq/mmc1:0001:1 brcmf_sdio_dataworker [brcmfmac]
[    8.922928] [<c010c748>] (unwind_backtrace) from [<c01097a4>] (show_stack+0x10/0x14)
[    8.923018] [<c01097a4>] (show_stack) from [<c09f773c>] (dump_stack_lvl+0x40/0x4c)
[    8.923069] [<c09f773c>] (dump_stack_lvl) from [<c09f4d04>] (__warn+0xbc/0x118)
[    8.923114] [<c09f4d04>] (__warn) from [<c09f4dc8>] (warn_slowpath_fmt+0x68/0x7c)
[    8.923134] [<c09f4dc8>] (warn_slowpath_fmt) from [<c013e5c8>] (__queue_work+0x3b8/0x50c)
[    8.923178] [<c013e5c8>] (__queue_work) from [<c013e764>] (queue_work_on+0x48/0x54)
[    8.923212] [<c013e764>] (queue_work_on) from [<bf1473d0>] (brcmf_sdio_dataworker+0x620/0x2170 [brcmfmac])
[    8.923392] [<bf1473d0>] (brcmf_sdio_dataworker [brcmfmac]) from [<c013ee1c>] (process_one_work+0x1dc/0x448)
[    8.923491] [<c013ee1c>] (process_one_work) from [<c013f0ec>] (worker_thread+0x64/0x5a8)
[    8.923512] [<c013f0ec>] (worker_thread) from [<c0146048>] (kthread+0x148/0x164)
[    8.923538] [<c0146048>] (kthread) from [<c0100130>] (ret_from_fork+0x14/0x24)
[    8.923557] Exception stack(0xc1aadfb0 to 0xc1aadff8)
[    8.923571] dfa0:                                     00000000 00000000 00000000 00000000
[    8.923582] dfc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[    8.923591] dfe0: 00000000 00000000 00000000 00000000 00000013 00000000
[    8.923600] ---[ end trace 1d581f038f138710 ]---
[    9.238451] Bluetooth: hci0: BCM: chip id 94
[    9.239070] Bluetooth: hci0: BCM: features 0x2e
[    9.241485] Bluetooth: hci0: BCM43430A1
[    9.241571] Bluetooth: hci0: BCM43430A1 (001.002.009) build 0000
[    9.307069] Bluetooth: hci0: BCM43430A1 'brcm/BCM43430A1.hcd' Patch
[    9.910023] dwmac-sun8i 1c30000.ethernet eth0: PHY [0.1:01] driver [Generic PHY] (irq=POLL)
[    9.930227] dwmac-sun8i 1c30000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[    9.931649] dwmac-sun8i 1c30000.ethernet eth0: No Safety Features support found
[    9.931691] dwmac-sun8i 1c30000.ethernet eth0: No MAC Management Counters available
[    9.931706] dwmac-sun8i 1c30000.ethernet eth0: PTP not supported by HW
[    9.935724] dwmac-sun8i 1c30000.ethernet eth0: configuring for phy/mii link mode
[    9.937782] dwmac-sun8i 1c30000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[    9.937846] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    9.997343] 8021q: 802.1Q VLAN Support v1.8
[   10.397258] Bluetooth: hci0: BCM43438A1 26MHz AP6212A1_CL1 BT4.0 OTP-BD-0034
[   10.397322] Bluetooth: hci0: BCM43430A1 (001.002.009) build 0106
[   11.433892] brcmfmac: brcmf_sdio_bus_rxctl: resumed on timeout
[   11.433958] ieee80211 phy0: brcmf_c_process_clm_blob: clmload (4733 byte file) failed (-110)
[   12.214928] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   12.214999] Bluetooth: BNEP filters: protocol multicast
[   12.215038] Bluetooth: BNEP socket layer initialized
[   12.235681] sun8i-ce 1c15000.crypto: Fallback for ecb-aes-sun8i-ce is ecb(aes-arm)
[   13.993821] brcmfmac: brcmf_sdio_bus_rxctl: resumed on timeout
[   13.993879] ieee80211 phy0: brcmf_c_process_clm_blob: get clmload_status failed (-110)
[   13.993922] ieee80211 phy0: brcmf_c_preinit_dcmds: download CLM blob file failed, -5
[   13.993951] ieee80211 phy0: brcmf_bus_started: failed: -5
[   13.993991] ieee80211 phy0: brcmf_attach: dongle is not responding: err=-5
[   14.043996] brcmfmac: brcmf_sdio_firmware_callback: brcmf_attach failed
```
 
> BTW, since there is no IR on board, I guess you can add if clause around https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/tools/crust/package.mk#L40-L41 It should help with current consumption. I guess you could check if ${UBOOT_SYSTEM} matches "bananapi-m2-zero" or not.

That doesn't seem to make a measurable difference, so I'll leave it as-is.

**Comment by jernejsk** [comment]
Are you sure Crust is at fault? Is this report from cold boot? I've seen something similar before on OrangePi Win, but I dismissed it as driver issue. If this is not from cold boot, it's more likely something in driver doesn't resume correctly.

**Comment by mklein-de** [comment]
Yes, this is 100% reproducible. The Crust-enabled image has no Wifi, and reverting this change brings it back. Cold/warm boot makes no difference.

**Comment by jernejsk** [comment]
I asked Crust author for help, let's see if he has any idea.

**Comment by mklein-de** [comment]
Weird, the same commit is working now. The SYSTEM images contain apparently different firmware binaries:

```
$ diff -r --brief x/m y/m 2>/dev/null
Files x/m/etc/group and y/m/etc/group differ
Files x/m/etc/issue and y/m/etc/issue differ
Files x/m/etc/os-release and y/m/etc/os-release differ
Files x/m/etc/passwd and y/m/etc/passwd differ
Files x/m/etc/release and y/m/etc/release differ
Files x/m/usr/cache/shadow and y/m/usr/cache/shadow differ
Files x/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac4339-sdio.bin and y/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac4339-sdio.bin differ
Files x/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac43430a0-sdio.bin and y/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac43430a0-sdio.bin differ
Files x/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac43430-sdio.bin and y/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac43430-sdio.bin differ
Files x/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac43430-sdio.sinovoip,bpi-m2-ultra.txt and y/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac43430-sdio.sinovoip,bpi-m2-ultra.txt differ
Files x/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac43455-sdio.bin and y/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac43455-sdio.bin differ
Files x/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac4356-sdio.bin and y/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac4356-sdio.bin differ
Files x/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac4356-sdio.khadas,vim2.txt and y/m/usr/lib/kernel-overlays/base/lib/firmware/brcm/brcmfmac4356-sdio.khadas,vim2.txt differ
Files x/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.alias and y/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.alias differ
Files x/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.alias.bin and y/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.alias.bin differ
Files x/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.dep and y/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.dep differ
Files x/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.dep.bin and y/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.dep.bin differ
Files x/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.order and y/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.order differ
Files x/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.symbols.bin and y/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/modules.symbols.bin differ
Files x/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/RTL8192EU/8192eu.ko and y/m/usr/lib/kernel-overlays/base/lib/modules/5.15.0/RTL8192EU/8192eu.ko differ
Files x/m/usr/lib/python3.8/site-packages/kodi/defs.pyc and y/m/usr/lib/python3.8/site-packages/kodi/defs.pyc differ
Files x/m/usr/share/bootloader/u-boot-sunxi-with-spl.bin and y/m/usr/share/bootloader/u-boot-sunxi-with-spl.bin differ
```

**Comment by jernejsk** [comment]
ok, this can be merged and wifi issue can be resolved separately, if needed.

**Review by jernejsk — APPROVED** [review]

**Comment by jernejsk** [comment]
@mklein-de I plan to send 0035-h3-h5-power-key-wake-up-source.patch and 0063-bananapim2-zero-key_power.patch upstream as one patch. What kind of authorship would suffice to you? Is it enough to just add your signed-off-by to the patch?

**Comment by mklein-de** [comment]
Sure, signed-off-by is absolutely sufficient!

**Pull request merged**
