### PR TITLE
web package updates

### PR DESCRIPTION
**Pull request by heitbaum**
Minor bumps to current for the 2 web packages:

- curl: updated to 7.74.0
- nghttp2: updated to 1.42.0

### CODE REVIEW

**Comment by antonlacon** [comment]
curl introduced experimental hsts support in 7.74. Disable?

**Comment by chewitt** [comment]
@lrusak is there a dependency between Kodi and curl version? (ffmpeg depends on curl)

**Comment by lrusak** [comment]
> @lrusak is there a dependency between Kodi and curl version? (ffmpeg depends on curl)

not necessarily but it's one package that really requires a lot of testing when bumping a major version.

**Review by lrusak — APPROVED** [review]
probably fine. no reason to hold this back really.

**Pull request merged**
