### PR TITLE
libmediainfo: use github and update to 0.7.99

### PR DESCRIPTION
**Pull request by thoradia**
libmediainfo exists in github.
I took the liberty to bump to it to the latest release.

### CODE REVIEW

**Comment by chewitt** [comment]
@thoradia You need to bump the tools add-on as well else the depends package(s) of the add-on will not be rebuilt. Can you investigate what other packages for that bundle can be updated? then we can combine multiple items and do a bulk rebuild.

**Comment by CvH** [comment]
libzen, squeezelite, tsdecrypt and mpg123 have updates (at a quick look) - they all including mediainfo belong to the multimedia-tools addon. I can put the updates together if you like (I won't stop you if you like to do it).

**Comment by adamg-xda** [comment]
This change has broken repo-tool

**Comment by MilhouseVH** [comment]
@adamg-xda in what way? Can you provide a log, or more details on what the problem is?

**Comment by adamg-xda** [comment]
When attempting to build official addons with repo-tool, build process breaks when it comes to libmediainfo due to various undefined references, reverting this commit and everything proceeds as normal.

**Pull request merged**
