### PR TITLE
Python3, util-linux: fix uuid build and rebuild issues

### PR DESCRIPTION
**Pull request by MilhouseVH**
See discussion: https://github.com/LibreELEC/LibreELEC.tv/pull/2966#issuecomment-420314426

Disabling uuid might be the easiest option right now. If anyone finds a better solution I'm all ears...

### CODE REVIEW

**Comment by asavah** [comment]
> Disabling uuid might be the easiest option right now. If anyone finds a better solution I'm all ears...

Here is your problem https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/e2fsprogs/package.mk#L36

On rebuild it's linking with libuuid from e2fsprogs.
been there ... I have libuuid disabled in e2fsprogs and everything links with util-linux one.

**Comment by MilhouseVH** [comment]
@asavah:

With http://ix.io/1mwf, clean RPi/RPi2 `e2fsprogs (init)` builds are failing (but Generic is successful):
```
      BUILD    e2fsprogs (init)
          TOOLCHAIN    configure (auto-detect)
Executing (init): /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9.0-devel/e2fsprogs-1.43.9/configure --host=armv6zk-libreelec-linux-gnueabi --build=x86_64-linux-gnu --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --libdir=/usr/lib --libexecdir=/usr/lib --localstatedir=/var --disable-static --enable-shared BUILD_CC=/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9.0-devel/toolchain/bin/host-gcc --enable-verbose-makecmds --enable-symlink-install --enable-symlink-build --disable-elf-shlibs --disable-bsd-shlibs --disable-profile --disable-jbd-debug --disable-blkid-debug --disable-testio-debug --disable-libuuid --enable-libblkid --disable-debugfs --disable-imager --enable-resizer --enable-fsck --disable-e2initrd-helper --enable-tls --disable-uuidd --disable-nls --disable-rpath --disable-fuse2fs --with-gnu-ld
configure: WARNING: unrecognized options: --disable-static, --enable-shared
Generating configuration file for e2fsprogs version 1.43.9
Release date is February, 2018
checking build system type... x86_64-pc-linux-gnu
checking host system type... armv6zk-libreelec-linux-gnueabi
checking for armv6zk-libreelec-linux-gnueabi-gcc... /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9.0-devel/toolchain/bin/armv6zk-libreelec-linux-gnueabi-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9.0-devel/toolchain/bin/armv6zk-libreelec-linux-gnueabi-gcc accepts -g... yes
checking for /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9.0-devel/toolchain/bin/armv6zk-libreelec-linux-gnueabi-gcc option to accept ISO C89... none needed
checking for dlopen in -ldl... yes
checking for armv6zk-libreelec-linux-gnueabi-gcc... (cached) /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9.0-devel/toolchain/bin/armv6zk-libreelec-linux-gnueabi-gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9.0-devel/toolchain/bin/armv6zk-libreelec-linux-gnueabi-gcc accepts -g... (cached) yes
checking for /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9.0-devel/toolchain/bin/armv6zk-libreelec-linux-gnueabi-gcc option to accept ISO C89... (cached) none needed
checking how to run the C preprocessor... /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9.0-devel/toolchain/bin/armv6zk-libreelec-linux-gnueabi-cpp
checking for additional special compiler flags... (none)
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
Disabling maintainer mode by default
Enabling symlinks for install
Disabling relative symlinks for install by default
Enabling symlinks for build
Enabling verbose make commands
Disabling ELF shared libraries
Disabling BSD shared libraries
Disabling profiling libraries
Disabling journal debugging
Disabling blkid debugging
Disabling testio debugging
checking pkg-config is at least version 0.9.0... yes
checking for uuid_generate in -luuid... no
configure: error: external uuid library not found
Makefile:9: recipe for target 'release' failed
make: *** [release] Error 1
```

The Generic `e2fsprogs (init)` build is here: http://ix.io/1mwo.

This is building on Ubuntu 16.04 - minimal additional dev headers installed.

**Comment by MilhouseVH** [comment]
I'll try `+pic` on `e2fsprogs`, but since we build `util-linux` followed by `e2fsprogs` with both installing `libuuid.a` (with `e2fsprogs` overwriting `util-linux` in a clean build) shouldn't we stop `util-linux` from installing `libuuid.a`, because if we ever rebuild `util-linux` and `Python3` (but not `e2fsprogs`) then we're back to square one and potentially linking against the "wrong" `libuuid.a`.

**Comment by vpeter4** [comment]
So we have 2 same library? This is little strange :)
Back to drawing board then.

**Comment by MilhouseVH** [comment]
Maybe it's only `util-linux` that is installing `libuuid.a` in `$TOOLCHAIN/lib` (and not `e2fsprogs`):
```
neil@nm-linux:~/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.0-devel$ find . -name libuuid.a -ls
 18756003      0 lrwxrwxrwx   1 neil     neil           14 Sep 12 01:45 ./e2fsprogs-1.43.9/.x86_64-libreelec-linux-gnu-init/lib/libuuid.a -> uuid/libuuid.a
 20482744     24 -rw-rw-r--   1 neil     neil        23644 Sep 12 01:45 ./e2fsprogs-1.43.9/.x86_64-libreelec-linux-gnu-init/lib/uuid/libuuid.a
 18756985      0 lrwxrwxrwx   1 neil     neil           14 Sep 12 03:16 ./e2fsprogs-1.43.9/.x86_64-libreelec-linux-gnu/lib/libuuid.a -> uuid/libuuid.a
 18756984     24 -rw-rw-r--   1 neil     neil        23644 Sep 12 03:16 ./e2fsprogs-1.43.9/.x86_64-libreelec-linux-gnu/lib/uuid/libuuid.a
  8308823     48 -rw-rw-r--   1 neil     neil        45346 Sep 12 03:18 ./util-linux-2.31/.x86_64-linux-gnu/.libs/libuuid.a
  8144274     48 -rw-r--r--   1 neil     neil        45346 Sep 12 03:18 ./toolchain/lib/libuuid.a
```
in which case adding `+pic` to `e2fsprogs` isn't likely to have any effect.

**Comment by vpeter4** [comment]
Then I will try with `+pic ` in util-linux.

I think we should disable installing library (and headers) from two packages in first place. In this case from e2fsprogs.

**Comment by MilhouseVH** [comment]
I think Python3 may also be using `uuid.h` from the build host when `uuid-dev` is installed, as we don't build `util-linux:host` as a Python3 dependency, in which case we haven't installed the `libuuid.a` and associated headers from `util-linux` while building Python3 for the first time.

From Ubuntu 16.04 (without `uuid-dev` installed, clean build)
```
checking for dlopen in -ldl... yes
checking for shl_load in -ldld... no
checking uuid/uuid.h usability... no
checking uuid/uuid.h presence... no
checking for uuid/uuid.h... no
checking uuid.h usability... no
checking uuid.h presence... no
checking for uuid.h... no
checking for uuid_generate_time_safe... no
checking for uuid_create... no
checking for uuid_enc_be... no
checking for library containing sem_init... -lpthread
```
From Ubuntu 17.10 with `uuid-dev` installed (clean build):
```
checking for dlopen in -ldl... yes
checking for shl_load in -ldld... no
checking uuid/uuid.h usability... yes
checking uuid/uuid.h presence... yes
checking for uuid/uuid.h... yes
checking uuid.h usability... no
checking uuid.h presence... no
checking for uuid.h... no
checking for uuid_generate_time_safe... yes
checking for uuid_create... no
checking for uuid_enc_be... no
checking for library containing sem_init... -lpthread
```

On 16.04 (without `uuid-dev` headers) a clean Python3 build is successful (but without `uuid`), and a rebuild of Python3 finds `$TOOLCHAIN/include/uuid/uuid.h` and subsequently fails to build `uuid` due to linker errors.

On 17.10 (with  `uuid-dev`) the clean Python3 build is also successful (linking against build host files?) but the rebuild fails for the same reason as 16.04.

Adding `util-linux:host` as a dependency to Python3 might help avoid this issue - I'll try that on 16.04, while also removing `uuid-dev` from 17.10 to confirm that uuid/uuid.h is no longer detected.

**Comment by MilhouseVH** [comment]
Confirming that without `uuid-dev`, 17.10 now fails to find `uuid/uuid.h`, same as 16.04.

Adding `util-linux:host` to Python3 `PKG_DEPENDS_HOST` causes the build system to enter an infinite loop. Eugh.

**Comment by vpeter4** [comment]
I didn't check what you wrote but instead I continue my own path.

I was adding `PKG_BUILD_FLAGS="+pic"` to util-linux. It didn't help. Then I noticed that this didn't set `-fPIC`. So I'm wondering does `PKG_BUILD_FLAGS` works also for building host packages? I think not?
That's why I add old fashioned way `export CFLAGS="$CFLAGS -fPIC"` to util-linux and rebuild host part. I saw `-fPIC` was really used. Then I rebuild Python3:host and it succeed.

I do have uuid-dev installed.

**Comment by MilhouseVH** [comment]
The reason for the infinite loop (`Python3` -> `util-linux` -> `toolchain`) is that `Python3` is now technically part of `toolchain` through `meson:host`, so trying to build `util-linux` (with an incomplete `toolchain`) as a dependency of `Python3` results in a circular dependency. Marvelous...

**Comment by MilhouseVH** [comment]
Good to know that the CFLAGS fix is working, but that's still not solving the core issue which is that a clean build is not using the toolchain uuid headers or libuuid, but instead whatever is installed in the build host (assuming `uuid-dev` is installed). The rebuild will always include `uuid` (through `util-linux` + CFLAGS) but the clean build only has a 50/50 chance of building Python3 with `uuid`. While not fatal, this uncertainty isn't ideal either should we ever need `uuid` in Python3.

I'm hoping we can build `util-linux` before Python3 so that Python3 always has the `uuid` headers/library in $TOOLCHAIN.

**Comment by MilhouseVH** [comment]
> So I'm wondering does PKG_BUILD_FLAGS works also for building host packages? I think not?

`+pic:host` (https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/functions#L35-L39)

**Comment by MilhouseVH** [comment]
About to kick off clean RPi/RPi2/Generic builds with this patch: http://ix.io/1mxP on Ubuntu 16.04 (without `uuid-dev`) and 17.10 (with `uuid-dev`).

`util-linux:host` will now be built before Python3, ensuring `uuid.h` and `libuuid.a` is always available from $TOOLCHAIN, and I've removed the `toolchain` dependency from `util-linux:host` to avoid the circular dependency. Also, `util-linux` will be built with `-fPIC`.

One thing that does stand out is (on 16.04, without `uuid-dev` and `uuid.h` etc. from `util-linux`):
```
checking for dlopen in -ldl... yes
checking for shl_load in -ldld... no
checking uuid/uuid.h usability... yes
checking uuid/uuid.h presence... no
configure: WARNING: uuid/uuid.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: uuid/uuid.h: proceeding with the compiler's result
checking for uuid/uuid.h... yes
checking uuid.h usability... no
checking uuid.h presence... no
checking for uuid.h... no
checking for uuid_generate_time_safe... yes
checking for uuid_create... no
checking for uuid_enc_be... no
checking for library containing sem_init... -lpthread
```

This wasn't from a clean build, though, so not sure whether to be concerned...yet.

**Comment by vpeter4** [comment]
Ah, I missed :host. Well, next time than.

With `+pic:host` for util-linux Python3 can still build uuid. Not sure if needed. Probbaly not.

Anyway, I'm off with this issue then.

**Comment by MilhouseVH** [comment]
This is what Autoconf has to say about the "accepted by the compiler, rejected by the preprocessor!" warnings:
```
20.7 Header Present But Cannot Be Compiled
==========================================

The most important guideline to bear in mind when checking for features
is to mimic as much as possible the intended use.  Unfortunately, old
versions of `AC_CHECK_HEADER' and `AC_CHECK_HEADERS' failed to follow
this idea, and called the preprocessor, instead of the compiler, to
check for headers.  As a result, incompatibilities between headers went
unnoticed during configuration, and maintainers finally had to deal
with this issue elsewhere.

   The transition began with Autoconf 2.56.  As of Autoconf 2.64 both
checks are performed, and `configure' complains loudly if the compiler
and the preprocessor do not agree.  However, only the compiler result
is considered.
```
I wonder if this is another of those issues arising from *:host packages using the build host gcc not the $TOOLCHAIN gcc.

> With +pic:host for util-linux Python3 can still build uuid. Not sure if needed. Probbaly not.

I'll test with/without (currently building clean "with") - I don't want to include anything extra that isn't necessary...

> Anyway, I'm off with this issue then.

Thanks (?) for finding all these issues. :)

**Comment by vpeter4** [comment]
Where do you get this "accepted by the compiler, rejected by the preprocessor!" ?

**Comment by MilhouseVH** [comment]
When building `Python3` after `util-linux`

**Comment by MilhouseVH** [comment]
It only seems to be an issue on 16.04 without `uuid-dev`, as I didn't get the same warnings on 17.10 which is building with `uuid-dev`. Go figure...

**Comment by vpeter4** [comment]
I don't see this (anymore).

**Comment by vpeter4** [comment]
Yes, I can confirm this on 16.04 WITHOUT uuid-dev.

**Comment by MilhouseVH** [comment]
A clean build with `util-linux` but without `+pic:host` fails, so `+pic:host` is required.

I've updated this PR with the new changes, which seem to be working fine now: Python3 builds clean and can also be rebuilt, and Python3 will build `uuid` support regardless of whether `uuid-dev` is installed or not.

Fingers crossed this is the last of this issue... :wink:

**Pull request merged**
