### PR TITLE
kodi: updates for Kodi 17.0-RC2

### PR DESCRIPTION
**Pull request by chewitt**
To be combined with https://github.com/LibreELEC/LibreELEC.tv/pull/1105

keep open for a bit as there are probably some other changes to add

### CODE REVIEW

**Comment by phedoreanu** [comment]
@chewitt Do you have a script that updates the `package.mk` files with the latest commit or do you do it manually?

**Comment by chewitt** [comment]
kodi package.mk is manual the binary add-ons is a script in tools/mkpkg

**Comment by phedoreanu** [comment]
> kodi package.mk is manual the binary add-ons is a script in tools/mkpkg

And for the rest of the packages? I was thinking a script could check and update the `package.mk`'s with latest `PKG_VERSION` from `PKG_URL` and maybe a branch name?
What do you think?

**Comment by chewitt** [comment]
tools/distro-tool does this

**Comment by phedoreanu** [comment]
> tools/distro-tool does this

Cheers!

**Comment by chewitt** [comment]
Something is royally messed up in my branch .. I'm closing this and will resubmit the PR

**Pull request closed without merging**
