### PR TITLE
RPi/RPi2: add linux kernel patch creation instructions

### PR DESCRIPTION
**Pull request by lrusak**
@MilhouseVH go over this and let me know if it needs any expansion or clarification

see here for the markdown formatted version
https://github.com/lrusak/LibreELEC.tv/tree/rpi-linux-instructions/projects/RPi2/patches/linux

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks, excellent instructions. I've pushed #66 with updated Linux and Kodi patches.

Comments:
1) Do we really want `--cover-letter`? This seems to add a lot of unnecessary flannel to the patch, I've left it out of my patch

2) As an alternative to "rebase conflict", what about creating a local branch in which to do the rebase, then simply delete the local branch at the end? This seems a bit "cleaner" to me.

3) The Kodi patches are another pig, possibly worse than the Linux commits. The https://github.com/popcornmix/xbmc/commits/jarvis_rbp_backports branch includes patches for both Kodi and Confluence which need to be split (or at least, the Confluence patches removed). To do this I produced a patch for Confluence (`cd addons/skins.confluence; git format-patch <sha> . --stdout >confluence.patch`) then rebased the branch removing those commits present in `confluence.patch`, creating a kodi.patch based on what was left.

Now that I understand how you produce these patches I'll give some thought to how this can be scripted...

**Comment by lrusak** [comment]
1) doesn't really matter, I like it that's all

2) yes that's pretty much what happens anyways

3) I've dealt with this when doing the retroplayer patches, basically this is what I do

to exclude a specific directory
```
git diff origin/master -- . ':!addons/skin.confluence'
```
to get the diff of a specific directory
```
git diff origin/master -- addons/skin.confluence
```
This allows me to make two patches easily

**Comment by MilhouseVH** [comment]
Ok thanks, then as far as the Kodi/Confluence patches go, that becomes quite easy:

Based on a comparison of the jarvis_rbp_backports branch and xbmc:Jarvis, https://github.com/xbmc/xbmc/compare/Jarvis...popcornmix:jarvis_rbp_backports, the first revision is 0418867953596638f7c8bd9a73f993588ef9ca14, so in order to produce the two patches...

```
git format-patch 0418867953596638f7c8bd9a73f993588ef9ca14~1 --stdout -- addons/skin.confluence  >/tmp/confluence.patch

git format-patch 0418867953596638f7c8bd9a73f993588ef9ca14~1 --stdout -- . ':!addons/skin.confluence'  >/tmp/kodi.patch
```

**Comment by Kwiboo** [comment]
I use this sequence editor script to generate `linux-01-RPi_support.patch` from the tip of `rpi-4.4.y` and `linux-4.4.y` if it can be of any help

```
#!/bin/bash

# Setup:
# git clone -b rpi-4.4.y --depth=1000 --single-branch git@github.com:raspberrypi/linux.git raspberrypi-linux
# git remote add -t linux-4.4.y linux-stable git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
# Update:
# git fetch --all --depth=1000
# git reset --hard origin/rpi-4.4.y
# GIT_SEQUENCE_EDITOR=../rpi-linux-rebase.sh git rebase -i linux-stable/linux-4.4.y
# git format-patch --no-signature --stdout linux-stable/linux-4.4.y > ../linux-01-RPi_support.patch

TODO=$1

# Drop commits not used
DROP_COMMITS="Add non-mainline source for rtl8192cu wireless driver version
rtl8192c_rf6052\: PHY_RFShadowRefresh\(\)\: fix off-by-one
rtl8192cu\: Add PID for D-Link DWA 131
Added Device IDs for August DVB-T 205"

IFS=$'\n'
for COMMIT in $DROP_COMMITS; do
  sed -i -E "s/^pick ([0-9a-f]+) ($COMMIT)/drop \1/g" $TODO
done
```

**Comment by MilhouseVH** [comment]
@Kwiboo many thanks, that should help make things a little easier (and less prone to error/omission!)

One small suggestion for your rebase script:
```
  sed -i -E "s/^pick ([0-9a-f]+) ($COMMIT.*)/drop \1 \2/g" $TODO
```
would produce a more informative `drop` line in the $TODO file - your original seems to be losing the commit message.

**Comment by Kwiboo** [comment]
@MilhouseVH thanks will try it out.

When I switched from commit id (for rpi-4.1.y) to commit message match I originally had some problem using similar replace to keep the message, since I never look at the $TODO file I just skipped the message.

**Comment by MilhouseVH** [comment]
If you never look at the todo, don't you need to add something like 

```
sed -i -E "/^drop /d" $TODO
```
to the end of the rebase script? Otherwise it errors:
```
Unknown command: drop 9ee31007a5032a3afe2fcb20c36b34f0ad57df56 v4.0.2_9000 as this is widely used. Disabled older rtlwifi driver
Please fix this using 'git rebase --edit-todo'.
```
I assumed you were manually removing the drop lines. Also note how the commit description is incomplete - the todo file will appear as follows:
```
drop 9ee31007a5032a3afe2fcb20c36b34f0ad57df56 v4.0.2_9000 as this is widely used. Disabled older rtlwifi driver
drop 143ad4522384b15e68e4f8160d99d17aa70a6df8 143ad45
drop 95641b705b5eb334efbb10343e23e2b32f0ff670 95641b7
pick dbf03b37592b79d891cb796fda13d8495a6a5234 Speed up console framebuffer imageblit function
pick cf63ba6ba21e8a1d62b1eb4917af42d6bcfa4445 Allow mac address to be set in smsc95xx
pick 20f0537c77ac3ef4e446bd0013c37ddd3af3936b enabling the realtime clock 1-wire chip DS1307 and 1-wire on GPIO4 (as a module)
drop fbd8454a22771ed12e1905a52934a6a871bc492e fbd8454
pick 6f8e2aeb77e4437eab3a46d74a1a2b9533812c81 config: Enable CONFIG_MEMCG, but leave it disabled (due to memory cost). Enable with cgroup_enable=memory.
pick b507ac15b579d88a09bf915f2f3ca8de7f1e4bf7 ASoC: Add support for PCM5102A codec
```

when the first commit is `Add non-mainline source for rtl8192cu wireless driver version v4.0.2_9000 as this is widely used. Disabled older rtlwifi driver` and the other three dropped commits have lost their commit message completely.

In addition to the `sed` change, I've added the following two lines to the end of the rebase script:
```
grep -E "^drop " $TODO > /tmp/dropped
sed -i -E "/^drop /d" $TODO
```
and now it's completing without error, logging the commits that are dropped, and the commit descriptions are complete:
```
$ cat /tmp/dropped
drop 9ee3100 Add non-mainline source for rtl8192cu wireless driver version v4.0.2_9000 as this is widely used. Disabled older rtlwifi driver
drop 143ad45 rtl8192c_rf6052: PHY_RFShadowRefresh(): fix off-by-one
drop 95641b7 rtl8192cu: Add PID for D-Link DWA 131
drop fbd8454 Added Device IDs for August DVB-T 205
```

This will prove to be a great time saver!

**Comment by Kwiboo** [comment]
Running this four lines to generate the patch-file works fine on my Ubuntu 14.04 with git 2.7.4:
```
git fetch --all --depth=1000
git reset --hard origin/rpi-4.4.y
GIT_SEQUENCE_EDITOR=../rpi-linux-rebase.sh git rebase -i linux-stable/linux-4.4.y
git format-patch --no-signature --stdout linux-stable/linux-4.4.y > ../linux-01-RPi_support.patch
```

After having setup my local linux repo with:
```
git clone -b rpi-4.4.y --depth=1000 --single-branch git@github.com:raspberrypi/linux.git raspberrypi-linux
git remote add -t linux-4.4.y linux-stable git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
```

I always compare the resulting patch-file with the current patch-file to ensure nothing went wrong.

**Comment by Kwiboo** [comment]
Looks like `drop` was added to git 2.6: https://github.com/git/git/commit/c9266d589482544d588ccfd95f54d0bfdb277aee

**Comment by MilhouseVH** [comment]
Yes, I'm on Ubuntu 15.10 with git 2.5.0

**Comment by Kwiboo** [comment]
I have now changed to `sed -i -E "s/^pick ([0-9a-f]+) ($COMMIT.*)/noop \1 \2/g" $TODO` in my local script, should make it work for git<2.6, thanks.

**Comment by lrusak** [comment]
so what's the verdict here?

**Comment by MilhouseVH** [comment]
I'm happy. Might be worth adding a link to this PR as it contains very useful automation information.

**Comment by lrusak** [comment]
updated to link to this PR

**Pull request merged**
