### PR TITLE
fixed libcap build error

### PR DESCRIPTION
**Pull request by rinaldus**
I noticed, that it's impossible to build from current master branch due to libcap build error. I found [this thread](https://forum.libreelec.tv/thread-5168.html) with solution, but author of this solution didn't make pull request. I made pull request instead of him. Can you apply these patches to your upstream?

### CODE REVIEW

**Comment by lrusak** [comment]
Thanks for the PR but is this really required? What host OS are you building on that this fix is required? AFAIK everyone builds on a recent ubuntu or fedora version has no issues.

I'd rather not have to maintain a patch if I don't have to ;)

**Comment by rinaldus** [comment]
@lrusak , my OS is Gentoo Linux x86_64 and I had to use this patch to build LibreELEC properly.

**Comment by rinaldus** [comment]
@lrusak, so I close this PR, make changes as @escalade said and create 2 splitted PRs?
@escalade , do you allow me to do it? You are original author of these patches...

**Comment by escalade** [comment]
Feel free, I'm not the original author I found them on bugtrackers around the web. You don't need a new PR, just fix this one.

**Comment by escalade** [comment]
Looks like $ROOT is not used anymore in master, so you'll need to remove that from the post_unpack commands in libcap/package.mk.

`vim packages/devel/libcap/package.mk && git add packages/devel/libcap/package.mk && git commit --amend && git push -f`

**Comment by rinaldus** [comment]
@escalade , updated.

**Comment by escalade** [comment]
Then it looks good to go, provided it's an acceptable fix.

@lrusak 

Here's the relevant systemd PR (merged in master): https://github.com/systemd/systemd/pull/5055

As for libcap, it can safely be compiled without gperf so this PR disables it. More info here: https://bugs.gentoo.org/show_bug.cgi?id=604802

Another way (perhaps cleaner?) would be to compile gperf 3.0 for host.

**Comment by escalade** [comment]
@rinaldus 

I've added the proper fix for libcap from the ticket above, see here: 4affdd8a3e1988d2ae65d9b009a929380e789319

**Comment by rinaldus** [comment]
@escalade , is it fixed now and have I to close this PR? Please, don't forget to backport it to libreelec-8.0 branch.

**Comment by escalade** [comment]
No, you'll need to reset the last commit and add the one I posted above. You didn't change anything.

Also, it's up to the LE team if they accept this at all. As mentioned they might prefer adding gperf:host.

**Comment by rinaldus** [comment]
@escalade , updated. Did I understand you right? Should I not include patch for systemd?

**Comment by escalade** [comment]
No, the systemd patch should be included. The libcap commit looks correct now.

**Comment by rinaldus** [comment]
@escalade , updated.

**Comment by chewitt** [comment]
@lrusak can you please review this and merge or close. It's been hanging for a while :)

**Comment by chewitt** [comment]
@lrusak, please review and merge or close. Thanks.

**Comment by lrusak** [comment]
I've never seen this error.

**Comment by escalade** [comment]
@lrusak 

So if you have never seen the error it does not exist? Seeing PR's closed like this gives 0 motivation to contribute to LE. If you had bothered to read the discussion, it's a real problem if your host system has gperf 3.1.

**Pull request closed without merging**
