### PR TITLE
docker: update to 1.12.5, let LibreELEC handle the systemd service

### PR DESCRIPTION
**Pull request by lrusak**
We don't need the socket service anymore as of docker 1.12

Let's let use handle the systemd service file the normal way.

### CODE REVIEW

**Comment by Jonathan34** [comment]
I think this broke the add-on on 7.0.2. after a simple reboot I get error saying the daemon is not started

**Comment by lrusak** [comment]
Please get a log file
```
systemctl restart service.system.docker
```
```
systemctl status service.system.docker | pastebinit
```

**Comment by Jonathan34** [comment]
pi2:/usr/share/kodi # systemctl restart service.system.docker
Failed to restart service.system.docker.service: Unit service.system.docker.service not found.
pi2:/usr/share/kodi # systemctl status service.system.docker | pastebinit
http://sprunge.us/VSKM
pi2:/usr/share/kodi #

**Comment by Jonathan34** [comment]
I m in IRC right now if you want

**Comment by jdeluyck** [comment]
Problem is that there were paths adjusted: now the files reside in 
/storage/.kodi/addons/service.system.docker/system.d

where they used to reside in
/storage/.kodi/addons/service.system.docker/systemd

The docker systemd unit files still point to the old location, causing a complete failure of Docker on my end.
I ended adding a symlink from the old path to the new.

**Comment by lrusak** [comment]
@jdeluyck I know, there isn't much I can do though.

you can rm the old symlinks, then just re-enable docker
```
rm /storage/.config/system.d/service.system.docker.service
rm /storage/.config/system.d/docker.service
systemctl enable /storage/.kodi/addons/service.system.docker/system.d/service.system.docker.service
```

**Pull request merged**
