### PR TITLE
projects/Odroid_C2: move and refactor project to Amlogic

### PR DESCRIPTION
**Pull request by adamg88**
This is a WIP.

A few notes...

`bootloader/update.sh` was removed, we have a project-wide one written by @kszaq that I believe is already compatible with the C2

`filesystem/usr/share/alsa/cards/AML-M8AUDIO.conf` as above
`filesystem/usr/lib/systemd/system/serial-console.service` **
`filesystem/usr/lib/systemd/sleep.conf.d/sleep.conf` **

`filesystem/usr/share/bootloader/canupdate.sh` I'm unsure if this file needs to be adjusted with this PR.

### CODE REVIEW

**Comment by kszaq** [comment]
My 2 cents: for backwards compatibility we should keep `boot.ini` the same way it used to be and modify `options` so that when merged with `projects/Amlogic/options` they match `projects/Odroid_C2/options`:
```  # Kernel target for u-boot (default 'uImage' if BOOTLOADER=u-boot) (uImage / zImage)
     KERNEL_TARGET="Image"
 
   # Kernel extra targets to build
     KERNEL_UBOOT_EXTRA_TARGET=""
 
   # Additional kernel make parameters (for example to specify the u-boot loadaddress)
     KERNEL_MAKE_EXTRACMD="dtbs"
```
and so on.

**Comment by adamg88** [comment]
I changed it this way so it would be compatible with the update.sh script
and your device trees package.

Raybuntu has tested these changes already and confirmed they work with the
exception of CEC, however I don't have a C2 so I'm doing this blind, I
would rather close this PR and let somebody else take up this task.

On 6 Jan 2018 20:53, "kszaq" <notifications@github.com> wrote:

My 2 cents: for backwards compatibility we should keep boot.ini the same
way it used to be and modify options so that when merged with
projects/Amlogic/options they match projects/Odroid_C2/options:

     KERNEL_TARGET="Image"

   # Kernel extra targets to build
     KERNEL_UBOOT_EXTRA_TARGET=""

   # Additional kernel make parameters (for example to specify the
u-boot loadaddress)
     KERNEL_MAKE_EXTRACMD="dtbs"

and so on.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LibreELEC/LibreELEC.tv/pull/2391#issuecomment-355775770>,
or mute the thread

**Comment by adamg88** [comment]
PR updated as discussed, changes still need to be tested, no urgency or rush on this PR though.

**Comment by adamg88** [comment]
@kszaq reverting the changes as per your recommendations broke booting, it booted before but hdmi-cec didn't work, closing this PR as I was doing the PR blind, would be better for someone else to take it over

**Pull request closed without merging**
