### PR TITLE
curl: shift to gnutls

### PR DESCRIPTION
**Pull request by antonlacon**

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Shouldn't we drop `openssl`, and add `gnutls`, as target dependencies?

**Comment by antonlacon** [comment]
Only if we want it to be correct. :) Fixed.

**Comment by FernetMenta** [comment]
this introduced some issues. i.e. this cmd executed on a RPi results in certificate error
curl -vvv https://orf-live.ors-shoutcast.at/fm4-q2a

reverting back to openssl fixes the issue.

neither curl on my mac nor my ubuntu systems use gnutls as backend. there might be a reason for this.

**Comment by CvH** [comment]
```
LibreELEC:~ # curl -vvv https://orf-live.ors-shoutcast.at/fm4-q2a
*   Trying 109.70.96.179:443...
* Connected to orf-live.ors-shoutcast.at (109.70.96.179) port 443 (#0)
* found 138 certificates in /run/libreelec/cacert.pem
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL connection using TLS1.3 / ECDHE_RSA_AES_256_GCM_SHA384
* server certificate verification failed. CAfile: /run/libreelec/cacert.pem CRLfile: none
* Closing connection 0
curl: (60) server certificate verification failed. CAfile: /run/libreelec/cacert.pem CRLfile: none
More details here: https://curl.se/docs/sslcerts.html
```

**Comment by FernetMenta** [comment]
If you verify the cert with openssl it shows the the cert is valid. something goes wrong with gnutls

**Comment by CvH** [comment]
I did a PR, works for me with changed to openssl

**Pull request merged**
