### PR TITLE
[le11] pcre/pcre2: fix pkg site URL

### PR DESCRIPTION
**Pull request by ihipop**
1. `ftp.pcre.org` is closed https://github.com/LibreELEC/LibreELEC.tv/issues/5880

1. https://github.com/LibreELEC/LibreELEC.tv/pull/5859 updated the pcre pkg URL but it doesn't use[ `${SOURCEFORGE_SRC}`](https://github.com/LibreELEC/LibreELEC.tv/blob/f3b5ec549b7743d598df1f5bea2578dc6dcf158a/config/sources#L2) format  eg: https://github.com/LibreELEC/LibreELEC.tv/blob/f3b5ec549b7743d598df1f5bea2578dc6dcf158a/packages/graphics/giflib/package.mk#L9
This PR Unite them
2. same changes to pkg `pcre2`

### CODE REVIEW

**Comment by heitbaum** [comment]
@ihipop thanks for the PR. Can you please break this into 2 commits and use house style.

e.g. something like.
`pcre: update PKG_URL`

can you also do both these commits as backports for the libreelec-10.0 branch too.

**Comment by SupervisedThinking** [comment]
Well what about Github tags? https://github.com/PhilipHazel/pcre2/tags IIRC sourceforge is not exactly a reliable source

**Comment by ihipop** [comment]
> @ihipop thanks for the PR. Can you please break this into 2 commits and use house style.
> 
> e.g. something like. `pcre: update PKG_URL`
> 
> can you also do both these commits as backports for the libreelec-10.0 branch too.

yes of course, I will do it

**Comment by ihipop** [comment]
> Well what about Github tags? https://github.com/PhilipHazel/pcre2/tags IIRC sourceforge is not exactly a reliable source

1. We have `sha256` checksum to ensure that the source is not modified by   `sourceforge` or MIM
2. `pcre.org` sites gives out the  `sourceforge`  url to download the Tarball , If it's not reliable, we should suggest them to remove the URL too
3. `LE` use many `${SOURCEFORGE_SRC}` in source code , if `sourceforge` is not reliable ,we should remove it all from `LE` 
source, not just this one. IMO, a new issue should  be opened to discuss about that

**Comment by SupervisedThinking** [comment]
The sourceforge site was "down" often in the past. The `pcre` package is eol but there are Github mirrors too https://github.com/jwilk-mirrors/pcre/tags as for `pcre2` the latest release on sourceforge is 10.37 while the Github repo offers 10.39. And IMHO [`PCRE2 development is now based here.`](https://github.com/PhilipHazel/pcre2) speaks for itself.

**Review by heitbaum — APPROVED** [review]

**Review by CvH — APPROVED** [review]

**Pull request merged**
