### PR TITLE
Allwinner: linux: add hw dec driver

### PR DESCRIPTION
**Pull request by jernejsk**
This PR adds HW decoding driver which is WIP. Do not merge yet.

### CODE REVIEW

**Comment by jernejsk** [comment]
This will change considerably, so there is no point keeping this PR open.

**Comment by uglide** [comment]
@jernejsk I've compiled image with your linux patches from this PR, but still see only 20-25fps on orange pi plus 2e. What else is required to enable hw decoding of videos?

**Comment by jernejsk** [comment]
@uglide 
This PR is only kernel driver.
What is missing:
1. improved DE2 DRM driver to support planes and HW scaling (almost good enough code is on my github)
2. Atomic DRM PRIME renderer in Kodi (initial version is in @lrusak repository, I think)
3. Current v4l2 driver for Allwinner SoCs is implemented using Request API. This API is not even in mainline kernel yet (presumably Q1 or Q2 2018). The main difference between current v4l2 m2m codecs and future request API based v4l2 codecs is the form of the data supplied to them. Current codecs accept plain video bitstream which is parsed and decoded on coprocessor, whereas Request API codecs need already parsed video bitstream. Current agreement is that bitstream parsing is too complex and error prone to be done in kernel. This mean that v4l2_m2m in ffmpeg needs to be extended to support such v4l2 codecs.

Anyway, a lot of work needs to be done...

**Comment by uglide** [comment]
@jernejsk 
Thanks for detailed info.
1. Is it https://github.com/jernejsk/linux-1/tree/h3_de2_impr ?
2. Is  it https://github.com/xbmc/xbmc/pull/12672 ?
3. I see Request API patch to linux kernel included  https://github.com/jernejsk/LibreELEC.tv/blob/fc4eb95c0c1fdbbfd3dd89fd36e55a307f842a6f/projects/Allwinner/patches/linux/90-add-request-api.patch , Is it enough to test it?

To summarize, is it possible to test all things together if I just pull your changes to linux kenel (DE2) and @lrusak changes to XBMC?

**Comment by jernejsk** [comment]
@uglide 
1. yes, but it not finished yet (it should be soon good enough for LE/Kodi needs)
2. that is only windowing part. There is also rendering part.
3. that driver works per-se, but there is no userspace component suitable for LE/Kodi needs.

To summarize, no, it is not possible to make it work just yet. I guessed you missed the part that ffmpeg needs changes to use such driver. I guess it will be few months?

Free Electrons company scheduled work on mainline Allwinner VPU driver around March next year. Till then, Request API should stabilize and hopefully ffmpeg will gain some support for it too.

In the meantime, I will try to polish other kernel parts like DRM driver, HDMI audio and similar. Maybe even add support for HW rendering SW decoded video (which should definetly improve FPS and be default choice for unsupported codecs in HW). But since everything is done in spare time, I can't guarantee anything.

**Pull request closed without merging**
