### PR TITLE
include firmware file for bluetooth controller on Z97I-PLUS motherboard

### PR DESCRIPTION
**Pull request by Hydrosaure**
Embedded bluetooth controller of this motherboard needs a firmware file to be properly initialized.

Dmesg log when file is missing:
`LibreELEC:~ # dmesg | grep -i blue`
`[    2.801891] Bluetooth: Core ver 2.22`
`[    2.801896] Bluetooth: HCI device and connection manager initialized`
`[    2.801898] Bluetooth: HCI socket layer initialized`
`[    2.801899] Bluetooth: L2CAP socket layer initialized`
`[    2.801901] Bluetooth: SCO socket layer initialized`
`[    2.817332] Bluetooth: hci0: BCM: chip id 63`
`[    2.833175] Bluetooth: hci0: LibreELEC`
`[    2.834750] Bluetooth: hci0: BCM20702A1 (001.002.014) build 0000`
`[    2.834915] bluetooth hci0: Direct firmware load for brcm/BCM20702A1-0b05-17cf.hcd failed with error -2`
`[    2.834916] Bluetooth: hci0: BCM: Patch brcm/BCM20702A1-0b05-17cf.hcd not found`
`[    2.894888] Bluetooth: BNEP (Ethernet Emulation) ver 1.3`
`[    2.894889] Bluetooth: BNEP filters: protocol multicast`
`[    2.894891] Bluetooth: BNEP socket layer initialized`
`[    7.052233] Bluetooth: RFCOMM TTY layer initialized`
`[    7.052236] Bluetooth: RFCOMM socket layer initialized`
`[    7.052238] Bluetooth: RFCOMM ver 1.11`

File BCM20702A1-0b05-17cf.hcd has to be added in /usr/lib/firmware/brcm directory

The file itself can be obtained here:
[BCM20702A1-0b05-17cf.hcd](https://github.com/geyslan/configs/blob/master/lib/firmware/brcm/BCM20702A1-0b05-17cf.hcd)

### CODE REVIEW

**Comment by chewitt** [comment]
I'm guessing you meant to submit the PR against libreelec-8.0 not master?

**Comment by Hydrosaure** [comment]
You are right, my apologies.

**Comment by escalade** [comment]
You'll want to create the PR against the LibreELEC branch and not my fork as well.

**Comment by chewitt** [comment]
It's also best practice to make PR's from a topic branch not a main branch; then when corrections are needed you only have to wrestle a few commits. Sorry if this is turning into a github tutorial :)

**Comment by Hydrosaure** [comment]
Guess it's obvious I'm trying to figure this out

**Comment by chewitt** [comment]
git clone https://github.com/LibreELEC/LibreELEC.tv
cd LibreELEC.tv
git checkout libreelec-8.0
git checkout -b newbranch
<make changes>
git add <stuff>
git commit -m "package: description of change"
git push origin newbranch
<visit GH website and create PR against LibreELEC/libreelec-8.0>

If the current git clone is done from escalade's repo you'll need to define a new upstream remote for our repo and fetch it to rebase your commits against it, or you start from a new clone of our repo and repeat the change. Unless you really understand the first statement the second option is the quicker route to success :)

**Pull request closed without merging**
