### PR TITLE
gcc: update to 12.1.0

### PR DESCRIPTION
**Pull request by heitbaum**
changes:
- https://gcc.gnu.org/gcc-12/changes.html
- https://gcc.gnu.org

~requires #6469 as a precursor~ - DONE

### this PR is merge blocked / draft until the iMX8 atf code fix is completed.

it is presented as draft so others can test as required.

build of all of:- successful (with the above patches and gcc-12.1.0)
```
    PROJECT=Allwinner ARCH=arm DEVICE=A64 make image
    PROJECT=Allwinner ARCH=arm DEVICE=H3 make image
    PROJECT=Allwinner ARCH=arm DEVICE=H5 make image
    PROJECT=Allwinner ARCH=arm DEVICE=H6 make image
    PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 make image
    PROJECT=Rockchip ARCH=arm DEVICE=RK3288 make image
    PROJECT=Rockchip ARCH=arm DEVICE=RK3328 make image
    PROJECT=Rockchip ARCH=arm DEVICE=RK3399 make image
    PROJECT=NXP ARCH=arm DEVICE=iMX6 make image
    PROJECT=NXP ARCH=arm DEVICE=iMX8 make image 
       ^^^^^ FAILs - see atf workaround below.
    PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard make image
    PROJECT=Samsung ARCH=arm DEVICE=Exynos make image
    PROJECT=Generic ARCH=x86_64 DEVICE=Generic make image
    PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy make image
    PROJECT=RPi ARCH=arm DEVICE=RPi2 make image
    PROJECT=RPi ARCH=arm DEVICE=RPi4 make image
    PROJECT=Amlogic ARCH=arm DEVICE=AMLGX make image
```

error with gcc-12 iMX8 build is due to atf
- https://developer.trustedfirmware.org/T991
- https://developer.trustedfirmware.org/T984
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105523
- Draft workaround b0b588a3ff4ad9a1eda057daaf27005044537a26

### CODE REVIEW

**Comment by SupervisedThinking** [comment]
@heitbaum is this good to go for testing? I guess adding fixes the problem? `CFLAGS="--param=min-pagesize=0"`

**Comment by heitbaum** [comment]
> @heitbaum is this good to go for testing? I guess adding fixes the problem? `CFLAGS="--param=min-pagesize=0"`

I have been building with gcc12 for 2 months now. GtG by me. I updated the atf patch, to be more specific - as it only errors with iMX8.

**Comment by SupervisedThinking** [comment]
Since you're touching the patches anyway - could you rename them according to this scheme, so we are aware what's the origin of those patches? I guess all of them should start with `gcc-100.0x-` ?

```
100.* - LibreELEC specific patches that wont go upstream
995.* - LibreELEC specific patches that should be send upstream
999.* - patches backported from upstream
```
https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/mediacenter/kodi/patches/README.patches

**Comment by HiassofT** [comment]
@SupervisedThinking ignore that README, no one is following it and IMO it should be deleted as it recommends to number patches in the wrong order (backports would have to come first, local-only last)

**Comment by SupervisedThinking** [comment]
> @SupervisedThinking ignore that README, no one is following it and IMO it should be deleted as it recommends to number patches in the wrong order (backports would have to come first, local-only last)

Well then we should reverse the numbering but IMHO it's really handy so have an overview which patch is a "LE hack" which was sent upstream or should be upstreamed & which is a backport/PR.

Without those numbering logic the patches were randomly applied as they were named and I guess that's pretty much worse, isn't it?

**Comment by HiassofT** [comment]
The order isn't random, within a directory the order is implicitly defined as globs (like '*.patch') are sorted. And we have a defined order between package patches (come first), project specific package patches (second), device patches (last).

I don't see a pressing need to define a numbering, most project/package patches are doing it right already and eg contain "fromlist" or "backport" in the patch filenames.

Also some patch directories simply contain git format-patch output with 4-digit sequential numbers and changing that to enforce an aritificial LE rule/guide would only cause hassles with no benefit.

**Comment by SupervisedThinking** [comment]
If you have a look at https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/lang/gcc/patches which patch comes first? GCC is just an example X.org had the same random crap patch names & most older packages share this "problems". The only package with "fromlist" or "backport" named patches that came to my mind is linux & even then we might have still some downstream packages mixed in.

> Also some patch directories simply contain git format-patch output with 4-digit sequential numbers and changing that to enforce an aritificial LE rule/guide would only cause hassles with no benefit.

The benefit ist maintainability - not all patches contain the whole header generated by github or else and in 5 years nobody knows where they come from, what they do etc.

Currently Looking at a xxx-100. patch instantly tells me it's something LE specific while xxx-999. means it can be most likely dropped by a package bump.

**Comment by HiassofT** [comment]
No need to overcomplicate things. Everything with "backport" "PR" or something similar in the name should be obvious, everything else is downstream or unmerged patches.

**Comment by SupervisedThinking** [comment]
@heitbaum please add https://github.com/SupervisedThinking/LibreELEC-RR/commit/f4415262bcb9d31ed0412786e075999c9a19660a otherwise compilation of assimp will fail

**Comment by heitbaum** [comment]
I have pulled you commit in 

> @heitbaum please add [SupervisedThinking@f441526](https://github.com/SupervisedThinking/LibreELEC-RR/commit/f4415262bcb9d31ed0412786e075999c9a19660a) otherwise compilation of assimp will fail

I have pulled the commit in. 

Still leaving as merge blocked - but it can be approved / merged when we are ready.

**Comment by SupervisedThinking** [comment]
Overall it looks good, I'm currently building my custom build which pulls in a s%/!%!/d of additional packages & until now they build fine, also the by me used libretro cores look like they don't fail.

**Comment by HiassofT** [comment]
Runtime test on RPi3B+ and RPi4 was fine

**Review by HiassofT — APPROVED** [review]

**Pull request merged**
