### PR TITLE
add kernel options for wireguard

### PR DESCRIPTION
**Pull request by lrusak**
This is based on the documentation here https://www.wireguard.com/compilation/

pretty straightforward

### CODE REVIEW

**Comment by jernejsk** [comment]
Would disabling options via this mechanism work too? systemd requires that some options are disabled...

**Comment by lrusak** [comment]
> Would disabling options via this mechanism work too? systemd requires that some options are disabled...

@jernejsk see #5217

**Comment by jernejsk** [comment]
gah, sorry, commented on wrong PR

**Comment by lrusak** [comment]
Just as an FYI CONFIG_WIREGUARD selects a bunch of crypto options, so we don't need to explicitly list them
```
config WIREGUARD
	tristate "WireGuard secure network tunnel"
	depends on NET && INET
	depends on IPV6 || !IPV6
	select NET_UDP_TUNNEL
	select DST_CACHE
	select CRYPTO
	select CRYPTO_LIB_CURVE25519
	select CRYPTO_LIB_CHACHA20POLY1305
	select CRYPTO_LIB_BLAKE2S
	select CRYPTO_CHACHA20_X86_64 if X86 && 64BIT
	select CRYPTO_POLY1305_X86_64 if X86 && 64BIT
	select CRYPTO_BLAKE2S_X86 if X86 && 64BIT
	select CRYPTO_CURVE25519_X86 if X86 && 64BIT
	select ARM_CRYPTO if ARM
	select ARM64_CRYPTO if ARM64
	select CRYPTO_CHACHA20_NEON if ARM || (ARM64 && KERNEL_MODE_NEON)
	select CRYPTO_POLY1305_NEON if ARM64 && KERNEL_MODE_NEON
	select CRYPTO_POLY1305_ARM if ARM
	select CRYPTO_BLAKE2S_ARM if ARM
	select CRYPTO_CURVE25519_NEON if ARM && KERNEL_MODE_NEON
	select CRYPTO_CHACHA_MIPS if CPU_MIPS32_R2
	select CRYPTO_POLY1305_MIPS if CPU_MIPS32 || (CPU_MIPS64 && 64BIT)
```

ref: https://github.com/torvalds/linux/blob/master/drivers/net/Kconfig#L75-L97

**Review by chewitt — APPROVED** [review]
LGTM :)

**Pull request merged**
