### PR TITLE
Generic, Allwinner, Rockchip: Update to Linux 5.9

### PR DESCRIPTION
**Pull request by jernejsk**
Everything is only build tested. It would be great if someone tests Generic images.

### CODE REVIEW

**Comment by Kwiboo** [comment]
Please pick top two commits from https://github.com/Kwiboo/LibreELEC.tv/commits/rk-5.9 to update Rockchip patches and update ffmpeg request-api patches to use the new h264 ctrls (requires updates of your Allwinner patches).

**Comment by smp79** [comment]
Generic works fine om Gemini Lake.

**Comment by jernejsk** [comment]
@Kwiboo is this ok? or should I drop v4l2 changes from that RK commit?

**Comment by Kwiboo** [comment]
@jernejsk I guess it does not matter if you include the v4l2 changes in this PR or in a separate ffmpeg PR, the rockchip platform is still missing some work-in-progress kernel patches to build a fully usable image anyway :-)

**Review by CvH — APPROVED** [review]

**Pull request merged**
