### PR TITLE
libressl: add patch to add back a verisign cert

### PR DESCRIPTION
**Pull request by lrusak**
to fix the stupid pandora issue.

I tested and it works both with curl and python's urllib2

### CODE REVIEW

**Comment by lrusak** [comment]
@stefansaraev please vocalize why you oppose this 😎

**Comment by chewitt** [comment]
It would be unusual for a CA certificate from a provider like Verizon to be removed without there being a good reason. We should understand that reason first before just adding the cert back in.

**Comment by CvH** [comment]
https://security.googleblog.com/2015/12/proactive-measures-in-digital.html

**Comment by chewitt** [comment]
I put security principles ahead of "It's only an HTPC so lets just make it work" so I don't support adding this cert back. I'm rather surprised a "name" destination like Pandora hasn't switched all the certs on their sites for ones that are globally supported.

**Comment by stefansaraev** [comment]
my :-1: does not mean "do not merge it". but there is a reason for this CA removal, it's explained on symantec website (see links in referenced libressl commit), they offer free replacement for those having it in their certificate chain, and it's bveen 6 (six) months now. be sure it will be removed at some point in major browsers, starting with chrome.

those who still did not reissue their server certificates should be slapped, imo. rally.

**Comment by stefansaraev** [comment]
can't we just send them (pandora an email) like "hey, your service is soon to get broken, you are using ssl CA that is no more, you should update your certs, in case you missed, look right here: https://knowledge.symantec.com/support/ssl-certificates-support/index?page=content&id=ALERT1941"

**Comment by MilhouseVH** [comment]
So what are the options?

1. Revert this PR
2. Apply a hack that works around the problem
3. Do nothing, as it's problem with Pandora's configuration that they should fix

If the certificate has been revoked I'm inclined to go with #3 and wait for Pandora to fix their crap (why is it always Pandora that is a problem when we change certs?)

I'm a little uncomfortable applying a hack/patch to work around a Pandora security issue, in which case reverting this PR would be my next preferred option, and maybe try this PR again with LE8, by which time Pandora might have got their act together.

**Comment by stefansaraev** [comment]
maybe @Pandora-Radio @hachr can help ?

**Comment by MilhouseVH** [comment]
> @MilhouseVH the point is, it is not revoked, but it was clearly stated you should not trust it anymore.

Then I suggest we do nothing.

**Comment by Kwiboo** [comment]
It turns out my trusted first backport patch works with pandora after all, openssl s_client needed the CAfile param to work correctly, see https://github.com/Kwiboo/LibreELEC.tv/commit/be541b921d983c4ef45f361be61b6be0f665b017

```
# openssl s_client -connect tuner.pandora.com:443 -CAfile /etc/ssl/cert.pem -trusted_first
CONNECTED(00000003)
depth=2 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2006 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primary Certification Authority - G5
verify return:1
depth=1 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = Terms of use at https://www.verisign.com/rpa (c)10, CN = VeriSign Class 3 Secure Server CA - G3
verify return:1
depth=0 C = US, ST = California, L = Oakland, O = "Pandora Media, Inc.", OU = operations, CN = tuner.pandora.com
verify return:1
```

**Pull request closed without merging**
