### PR TITLE
scripts/image: make the images as well when running make noobs

### PR DESCRIPTION
**Pull request by lrusak**
Git makes this change looks a bit scary, but it's basically just adjusting the indent for the if statements.

@chewitt give this a test please

### CODE REVIEW

**Comment by lrusak** [comment]
@chewitt did you test?

**Comment by chewitt** [comment]
I keep meaning to test it but keep having to prioritise something else. Will try and look tonight.

**Comment by MilhouseVH** [comment]
Just a nit, but the style of indent in this script seems to change after line 83, which results in unnecessary (and potentially confusing) indentation later on when this same style is repeated. What's the preferred style? I personally don't like this extra-indent-after-comment style and would rather it removed (which would make the PR appear even bigger, but better/consistent IMHO).

**Comment by hudokkow** [comment]
@lrusak you can view the diff omitting lines with only cosmetic changes (indent, trailing spaces, etc.) if you add w?=1 to the URL.

Give it a go -> https://github.com/LibreELEC/LibreELEC.tv/pull/311/files?w=1

:wink:

**Comment by lrusak** [comment]
bueller

**Pull request merged**
