### PR TITLE
v4l-utils: extend xbox_one keymap to support PDP Talon remote buttons

### PR DESCRIPTION
**Pull request by Niklas04**
There are two versions of official media remotes for the xbox one: A small one and a large one
For matching buttons the large remote has the same scancodes as the small one.

### CODE REVIEW

**Comment by CvH** [comment]
Can you add a picture of the remote here at github? There are some variations of the xbox one remote.

**Comment by Niklas04** [comment]
This is the large remote I mentioned:

More pictures of this remote one can be found here: 
https://www.amazon.de/Talon-Media-Remote-f%C3%BCr-Xbox/dp/B07VFCJ4KK

The small remote I mentioned (and for which the keymap was probably first created) is this:
https://www.amazon.de/Microsoft-6DV-00006-Xbox-Media-Remote/dp/B00I41H7K8

**Comment by HiassofT** [comment]
The keycode changes look fine but please change the commit message to indicate that these are buttons of a 3rd-party remote, not the official Microsoft remote. eg:

```
v4l-utils: extend xbox_one keymap to support PDP Talon remote buttons

Add scancodes for numeric and record buttons of the PDP Talon Media Remote
https://www.pdp.com/en/pdp-gaming-talon-media-remote-xbox
```

**Comment by CvH** [comment]
@Niklas04 the commit message :) you need to squash it and change the title of the commit to
`
Adding keycodes for xbox one remote` -> `v4l-utils: extend xbox_one keymap to support PDP Talon remote buttons`

**Comment by Niklas04** [comment]
Done

@CvH Thank you :)

**Review by CvH — APPROVED** [review]

**Pull request merged**
