### PR TITLE
glibc: update to 2.36 and drop now upstream RELR patch 

### PR DESCRIPTION
**Pull request by heitbaum**
### glibc-2.36 release:

- announcement:
  - https://sourceware.org/pipermail/libc-alpha/2022-August/141193.html
- release notes:
  - https://sourceware.org/git/?p=glibc.git;a=tag;h=refs/tags/glibc-2.36 
- https://sourceware.org/git/?p=glibc.git;a=shortlog;h=refs/heads/release/2.36/master 
- planned for release on 2022-08-01
- https://sourceware.org/pipermail/libc-alpha/2022-July/140352.html 
- https://sourceware.org/glibc/wiki/Release/2.36
- Freeze note: https://sourceware.org/pipermail/libc-alpha/2022-July/140484.html

### Done:
- rebased `glibc-fix-dns-with-broken-routers` patch
- ~Temporary revert of fsconfig abi changes~
- Drop included upstream `[COMMITTED] linux: Fix missing __convert_scm_timestamps (BZ #28860)`
- Drop RELR patch (tested)

### Issues: [DONE]
- https://sourceware.org/pipermail/libc-alpha/2022-July/140466.html
  - gcc 12.1.0 does not compile without the linux/fs.h patch
    - https://github.com/ceseo/gcc/commit/2701442d0cf6292f6624443c15813d6d1a3562fe
  - systemd-251.2 does not compile without linux/fs.h patch
    - https://github.com/systemd/systemd/issues/23984
  - conflicting headers (mount.h) 
    - https://sourceware.org/glibc/wiki/Synchronizing_Headers
    - https://sourceware.org/pipermail/libc-alpha/2022-July/140480.html
  - syslinux patch
  - hdparm patch
  - efivar patch
  - stress-ng patch

### Help required: [DONE]
- confirm by testing that the RELR patch can indeed be dropped, now that RELR is now upstream. #5376
  - Support for DT_RELR relative relocation format has been added to glibc.  This is a new ELF dynamic tag that improves the size of relative relocations in shared object files and position independent executables (PIE).  DT_RELR generation requires linker support for -z pack-relative-relocs option, which is supported for some targets in recent binutils versions.  Lazy binding doesn't apply to DT_RELR.

### CODE REVIEW

**Comment by knaerzche** [comment]
> confirm by testing that the RELR patch can indeed be dropped, now that RELR is now upstream. https://github.com/LibreELEC/LibreELEC.tv/pull/5376

There is now a abi version check in glibc if the binary was compiled against a version which included this feature, which ChromeOS libwidevinecdm.so unsurprisingly is not (even not the latest). So we need a small workarround for that: Please pick from https://github.com/knaerzche/LibreELEC.tv/tree/libwidevinecdm-upstream-glibc-abi-check-hack. Besides it is/seems feature-compatible .. I checked with netflix and amazon for some hours and everything was fine. (I checked this PR along with https://github.com/LibreELEC/LibreELEC.tv/pull/6470)

**Comment by heitbaum** [comment]
> > confirm by testing that the RELR patch can indeed be dropped, now that RELR is now upstream. #5376
> 
> There is now a abi version check in glibc if the binary was compiled against a version which included this feature, which ChromeOS libwidevinecdm.so unsurprisingly is not (even not the latest). So we need a small workarround for that: Please pick from https://github.com/knaerzche/LibreELEC.tv/tree/libwidevinecdm-upstream-glibc-abi-check-hack. Besides it is/seems feature-compatible .. I checked with netflix and amazon for some hours and everything was fine. (I checked this PR along with #6470)

Thanks. I have cherry picked it. Some other fixes needed for the fsmount - so adding them slowly too.

**Comment by knaerzche** [comment]
> Thanks. I have cherry picked it. Some other fixes needed for the fsmount - so adding them slowly too.

Ah yeah, I forgot to mention I had to drop that include from hdparm also. 9.64 available now, btw - but this is still not fixed there.

**Comment by heitbaum** [comment]
> > Thanks. I have cherry picked it. Some other fixes needed for the fsmount - so adding them slowly too.
> 
> Ah yeah, I forgot to mention I had to drop that include from hdparm also. 9.64 available now, btw - but this is still not fixed there.

syslinux fix is now here too. So should be close to GtG when it is released. I’ll run a full clean build on all during the week.

**Comment by heitbaum** [comment]
glibc 2.36 tar file has been released. PR ready for final review. 

announcement:
- https://sourceware.org/pipermail/libc-alpha/2022-August/141193.html

release notes:
- https://sourceware.org/git/?p=glibc.git;a=tag;h=refs/tags/glibc-2.36

**Comment by SupervisedThinking** [comment]
lgtm - build & run tested on Generic x11 & Wayland custom builds

**Review by SupervisedThinking — APPROVED** [review]

**Pull request merged**
