### PR TITLE
linux: update to 6.11

### PR DESCRIPTION
**Pull request by heitbaum**
### packages updated
- linux: update to 6.11.x
- strace: update to 6.11

### 6.11.x mainline kernel update
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.11

### errors / fixes / issues / regressions / todo
- todo
  -
- known Issues
  - NXP iMX8 does not build
    - the patch 6912a78bb2d610a1c1341db1e9c2fc792013ce09 needs to be rewritten as per upstream change `WIP rebase patches for 6.11-rc1 - please review - DO NOT MERGE`
    - `projects/NXP/devices/iMX8/patches/linux/0001-drm-bridge-mhdp-Add-cdns-mhdp-driver-bridge-driver.patch`
    - the patch https://patchwork.kernel.org/project/linux-rockchip/cover/cover.1590982881.git.Sandor.yu@nxp.com/ needs to be replaced by https://patchwork.freedesktop.org/series/120825/
    - This is replaced with #9332 
  - wl (Generic) - still from 6.10
    - #8941
- fixes
  - na 
- done
  - iwlwifi-firmware
  - Allwinner
    - Confirm no issues with updating of_property_for_each_u32 in d92363305d575960b7132ffa3268a7814099581d `rebase patches for 6.11-rc1 - please review`
    - Validate ABFC patch changes 40d10e63e60612e029eee1f76dad4d16c23ec8bb `AFBC rebase patches for 6.11-rc1 - please review`
  - all compiles were successful (with only the 3 patches needing review/rewriting.)
  - `CONFIG_MEMCG_V1 is not set` on all .configs
  - The `CONFIG_COMPRESSED_INSTALL is not set` was left as-is
  - `CONFIG_SLAB_BUCKETS=y` for all .configs
 
### log 
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.11.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.11.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/log/
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.11
- https://linux-regtracking.leemhuis.info/regzbot/mainline/
- https://linux-regtracking.leemhuis.info/regzbot/stable/

### 6.11 Build tested on all of:
```
PROJECT=Allwinner ARCH=aarch64 DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H3 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=R40 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=aarch64 DEVICE=RK3328 s/build linux
PROJECT=Rockchip ARCH=aarch64 DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX6 s/build linux
PROJECT=NXP ARCH=aarch64 DEVICE=iMX8 s/build linux - does not build
PROJECT=Qualcomm ARCH=aarch64 DEVICE=Dragonboard s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
```

### 6.11.y Run tested on all of:
- Allwinner all - tested - TBA - jernejsk
- Allwinner H6 (Tanix TX6) - TBA - heitbaum
- Generic Generic (Intel ADL - NUC12) - 6.11 - heitbaum
- Generic Generic (AMD 7840HS - SER7) - 6.11 - heitbaum
- NXP iMX6 (Cubox-i4Pro) - TBA - heitbaum
- Rockchip RK3399pro (Rock Pi N10) - TBA - heitbaum
- RK all - tested - TBA - knaerzche
- Samsung Exynos (Hardkernel ODROID XU4) - TBA - heitbaum

### CODE REVIEW

**Comment by heitbaum** [comment]
@jernejsk 6.11-rc7 has refactored drm https://github.com/torvalds/linux/commit/9da7ec9b19d8c1ad4f44e459fa5f93ad7a117dcd  and we were having the compile errors. Should I add this Kconfig change to the projects/Allwinner/patches/linux/0049-drm-sun4i-dw-hdmi-Switch-to-bridge-functions.patch? Also could you check that I haven’t made any mistakes on the “2 x to review” Allwinner patches?

**Comment by jernejsk** [comment]
I'll test this and review probably next week once I get new PC.

**Comment by jernejsk** [comment]
Maybe you can try to use https://patchwork.freedesktop.org/series/120825/ for iMX8? It's the latest iteration, but then again, it would be great to test it.

I'm looking into AW code too. I'll provide updated patches once ready.

**Comment by jernejsk** [comment]
@heitbaum Please integrate changes from: https://github.com/jernejsk/LibreELEC.tv/commit/4c28621a6deac6646ee8b184230d99c9e6f98398

There are 2 caviats:
- I merged your patch  from "linux (Allwinner): new patch required for 6.11-rc7" to 0049-drm-sun4i-dw-hdmi-Switch-to-bridge-functions.patch, since changes most logically belongs there and I don't want to have patches that can't be applied with "git am" (no headers)
- VP9 HW decoding mostly don't work on H6 (some videos work, though). This is not blocker for this PR, but it certainly needs to be solved before any release

**Comment by jernejsk** [comment]
Please include following patch for Allwinner: https://github.com/jernejsk/linux-1/commit/4a6926ea19c64b49e2bdeb30ceef98fc812cc52d It's needed for v6.8+ kernels.

**Comment by heitbaum** [comment]
> Please include following patch for Allwinner: [jernejsk/linux-1@4a6926e](https://github.com/jernejsk/linux-1/commit/4a6926ea19c64b49e2bdeb30ceef98fc812cc52d) It's needed for v6.8+ kernels.

Added and the Allwinner commits all merged.

**Comment by jernejsk** [comment]
You can remove VP9 HW for H6 from todo :)

**Comment by heitbaum** [comment]
> You can remove VP9 HW for H6 from todo :)

👍

**Review by jernejsk — APPROVED** [review]

**Pull request merged**
