### PR TITLE
Revert "sqlite: enable ICU support"

### PR DESCRIPTION
**Pull request by HiassofT**
Including ICU in image increased image size by almost 10% (+12MB tar size in RPi4 build)

Also sqlite isn't built with ICU support on most major Linux distributions and kodi's embedded sqlite build for Windows doesn't enable that either.

As neither the size increase nor deviating significantly from kodi sqlite installations is a desirable thing let's revert the commit.

### CODE REVIEW

**Comment by CvH** [comment]
to build sqlite with icu is rather a workaround then a fix, that issue is something kodi has to solve for all platforms

**Review by CvH — APPROVED** [review]

**Comment by CvH** [comment]
reverts https://github.com/LibreELEC/LibreELEC.tv/pull/5977
@Kurganov

**Comment by chewitt** [comment]
Better language support is a good thing (no dispute) but the size impact from the change is too significant. An alternative approach or way to package the change needs to be identified.

**Comment by SupervisedThinking** [comment]
@Kurganov https://github.com/archlinux/svntogit-packages/blob/packages/sqlite/trunk/PKGBUILD at least doesn't depend on ICU? Do you know any sqlite+icu build which uses a someone cut down ICU lib which does not increase the size of the package by ~10%?

**Comment by CvH** [comment]
No OS ships a icu enabled sqlite build by default (afaik), no Kodi distribution includes any icu so it is nowhere working.
A manual character transformation at kodi would solve that problem. Maybe open a issue at kodi ?

btw there are a lot other characters that are not working like ö/Ö ....

**Comment by Kurganov** [comment]
@CvH @HiassofT @chewitt ?

**Comment by SupervisedThinking** [comment]
I'm pretty sure this size increase would be fine - got a link to your branch? What does filtered ICUData contain? Only characters of various languages?

**Comment by Kurganov** [comment]
https://github.com/Kurganov/LibreELEC.tv/tree/le11-sqlite-icu-woicudata/
ICUData (https://unicode-org.github.io/icu/userguide/icu_data/) contain tons of languge settings, like month or timezone local mapping. but filtered it has no effect on sorting non ASCII characters.

**Pull request merged**
