### PR TITLE
Fixed RTL8723BS detecting bluetooth devices

### PR DESCRIPTION
**Pull request by maideii**
Hi,
I had installed a clean LibreELEC 9.0.1 Generic version, and found out that the RTL8723BS bluetooth chip is not detecting any bluetooth devices. I know LE team had enabled this staging driver in linux kernel so I went on tinkering around.

I found out that enable these 2 option below will immediately fixed the problem:
CONFIG_SND_SST_IPC_PCI=m
CONFIG_SND_SST_ATOM_HIFI2_PLATFORM_PCI=m

My machine is mini PC Lattepanda.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
These options are intended for the Intel Merrifield/Edison platform, which is not used by the Lattepanda, and neither do they have anything to do with Bluetooth chip support (which is already enabled in the config `CONFIG_RTL8723BS=m`) as they are audio-related.

Can you post `dmesg` from the stock 9.0.1 kernel and again from your kernel that includes only these two extra options?

**Comment by maideii** [comment]
OK. I will upload the dmesg once I reach home.

Some additional info for your further investigation.

Lattepanda 2G board creator had request all users to change this in BIOS when dealing with Linux.
SCC SDIO Support -> PCI Mode

I don't know whether this is related or not.

**Comment by maideii** [comment]
Stock 9.0.1 dmesg - http://ix.io/1DVO
- Bluetooth headset in pairing mode
- LE setting found no bluetooth device
- After few second whole system locked inside LE setting, in semi freeze condition. Cannot turn off bluetooth option as bluetooth option page freeze. Only restart to recover.

Self compile dmesg - http://ix.io/1DVU
- no error 
- can detect bluetooth hardware & successful pairing
- no freeze in LE setting

**Comment by maideii** [comment]
I found another solution is enabled `CONFIG_RFKILL_GPIO=m` then patch the linux using the old patch as below will also help in detecting bluetooth headset.

> diff -ru a/net/rfkill/rfkill-gpio.c b/net/rfkill/rfkill-gpio.c
--- a/net/rfkill/rfkill-gpio.c	2017-02-26 05:11:18.000000000 -0500
+++ b/net/rfkill/rfkill-gpio.c	2017-04-24 12:14:28.860838267 -0400
@@ -161,6 +161,7 @@
 

>  #ifdef CONFIG_ACPI

>  static const struct acpi_device_id rfkill_acpi_match[] = {

> +	{ "OBDA8723", RFKILL_TYPE_BLUETOOTH },
 	{ "BCM4752", RFKILL_TYPE_GPS },
 	{ "LNV4752", RFKILL_TYPE_GPS },
 	{ },

**Comment by maideii** [comment]
Here is the dmesg for changes above.

http://ix.io/1EfF

**Comment by MilhouseVH** [comment]
I'm including this PR in nightly test builds - I meant to say that the other day but apparently I forgot to press the green "comment" button... :)

Your alternative solution is discussed [here](https://patchwork.kernel.org/patch/9671285/) where it was not accepted for mainline.

**Comment by maideii** [comment]
Ok. Thanks. I will get your testbuild for a test later. :)

**Comment by maideii** [comment]
So far, the bluetooth detection works flawlessly for Lattepanda using your latest Kodi testbuilds `#0327.`

**Pull request merged**
