### PR TITLE
RTL8812au update: update package to the stable version branch 4.3.20

### PR DESCRIPTION
**Pull request by jerome-benoit**
This fix the disparition of the upstream branch previously used.

### CODE REVIEW

**Comment by CGarces** [comment]
Maybe is a stupid question but...
Why use PKG_VERSION="4.3.20" instead of the commit id?
The link will point always to the last commit?

**Comment by jerome-benoit** [comment]
Le 07/11/2016 à 20:59, Carlos Garcés a écrit :
>
> Maybe is a stupid question but...
> Why use PKG_VERSION="4.3.20" instead of the commit id?
> The link will point always to the last commit?
>

Yes but it might be wise te be able to specify the commit id we want in
this branch.
I will be able to cook something this week if noboby beat me :)

-- 
Jérôme Benoit aka fraggle
Piment Noir - http://piment-noir.org
OpenPGP Key ID : 9FE9161D
Key fingerprint : 9CA4 0249 AF57 A35B 34B3 AC15 FAA0 CB50 9FE9 161D

**Comment by chewitt** [comment]
Can we get patches upstreamed to the original repo? we don't really want feature patches in the long term, only stuff specific to our build system.

**Comment by jerome-benoit** [comment]
On Mon, 07 Nov 2016 12:25:49 -0800 in
<LibreELEC/LibreELEC.tv/pull/923/c258952163@github.com>, Christian
Hewitt <notifications@github.com> wrote:

> Can we get patches upstreamed to the original repo? we don't really
> want feature patches in the long term, only stuff specific to our
> build system.

We can. It's not a bad thing to upstream patches that have been tested
for a while before in a FOSS OS. In case of a responsive upstream, it
ease the merge. 

-- 
Jérôme Benoit aka fraggle
Piment Noir - http://piment-noir.org
OpenPGP Key ID : 9FE9161D
Key fingerprint : 9CA4 0249 AF57 A35B 34B3 AC15 FAA0 CB50 9FE9 161D

**Pull request merged**
