### PR TITLE
kodi: update to 2f11e99

### PR DESCRIPTION
**Pull request by CvH**
- rebased patches and fixed the align errors
- I aligned `kodi-100.10-handle-SIGTERM.patch` without really knowing what I am doing so pls someone with actually coding skills pls have a look :)

so the SIGTERM patch is wrong

```
convert '((CApplication*)this)->CApplication::SetExitCode(((int)EXITCODE_POWERDOWN))' from 'void' to 'bool'
 1971 |     if (SetExitCode(EXITCODE_POWERDOWN))
      |         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
      |                    |
      |                    void
/home/cvh/LEbuild/build.LibreELEC-Generic.x86_64-11.0-devel/build/kodi-2f11e994f322f7376476b186293a3df34246b9a7/xbmc/Application.cpp:1997:38: error: expected primary-expression before ')' token
 1997 |     if (SetExitCode(EXITCODE_REBOOT);)
      |                                      ^
```

### CODE REVIEW

**Comment by CvH** [comment]
- removed sigterm patch, its an 8 year old patch forward ported again and again, so lets have a look if it is still a problem or not
- removed `dont set _NET_WM_STATE_FULLSCREEN` patch
```
I dont remember why I added this. I guess it was for
some 3rdparty stuff that needed to go fullscreen but
xbmc was acting weird..

this should probably be removed after OE 6
```

**Comment by CvH** [comment]
- moved out the wayland and x11 patches to ther device folders (not build tested) @SupervisedThinking

**Comment by CvH** [comment]
sigterm patch is needed or shutdown and reboot is not working from kodi :)

**Comment by CvH** [comment]
this update requires a addon update too
```
ERROR <general>: Repository add-on repository.kodi.game uses old schema definition for the repository extension point! 
This is no longer supported, please update your addon to use <dir> definitions.
```

**Comment by mglae** [comment]
Use http://ix.io/3RUy

**Comment by CvH** [comment]
@mglae tx pushed the fix, tested and looks working

**Comment by vpeter4** [comment]
Does **repository.linuxserver.docker** needs to be updated too?
https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/repository/repository.linuxserver.docker/sources/addon.xml#L9

Also I think the only supported attribute is **verify** in **checksum** node?
https://github.com/xbmc/xbmc/blob/master/xbmc/addons/Repository.cpp#L293

**Comment by CvH** [comment]
> Does repository.linuxserver.docker needs to be updated too?

It is updated at this pr :)

> Also I think the only supported attribute is verify in checksum node?

https://kodi.wiki/view/Add-on_repositories#checksum hmm looks like the it is not needed at all

**Review by heitbaum — APPROVED** [review]

**Pull request merged**
