### PR TITLE
graphics package updates

### PR DESCRIPTION
**Pull request by lrusak**
keep open till final releases are available

@MilhouseVH for testing

### CODE REVIEW

**Comment by piotrasd** [comment]
good will bump also xorg to rc 1.20 (xorg-server-1.19.99.901)
https://cgit.freedesktop.org/xorg/xserver/commit/?id=cf485c659d93c92b26c4390402575f061eb175f6
https://www.phoronix.com/scan.php?page=news_item&px=X.Org-Server-1.20-RC1

one package will need to replace
randrproto to -> xorgproto

https://cgit.freedesktop.org/xorg/proto/xorgproto

**Comment by lrusak** [comment]
updated to use libdrm 2.4.91 and llvm 6.0.0 final

@MilhouseVH can you include this in your builds please. Then when mesa final is out we can merge

**Comment by MilhouseVH** [comment]
Yep will do.

**Comment by lrusak** [comment]
updated to mesa 18.0.0-rc5

**Comment by lrusak** [comment]
Updated to mesa 18.0.0

@MilhouseVH merge when ready 👍

**Comment by lrusak** [comment]
@MilhouseVH all good?

**Pull request merged**
