### PR TITLE
imx6/linux: kernel fixes from vero (maybe fixes black screen when boo…

### PR DESCRIPTION
**Pull request by vpeter4**
…ting)

thanks to @samnazarko

### CODE REVIEW

**Comment by samnazarko** [comment]
Some background:

* When we moved to 4.4, some users just got a black screen on boot. This was caused by a bug when calculating cts values for audio. Fixed in [1] 
* Some users may have problems booting with the new kernel using some SD cards. This is caused by an SDHC tuning quirk that was omitted when SR was rebased on to 4.4 [2]. 
* We also had a nasty GPU hang. Symptom was that Kodi just froze, usually after a small period of inactivity. This is fixed by not attempting to idle the GPU in the gckEvent routine. [3]. There is also an optional commit [4], that will try and recover from GPU issues, it fixes [3] indirectly, but of course fixing it the right way is the better approach. [4] is good for potentially undiagnosed issues that may still exist.

[1] https://github.com/osmc/vero-linux/commit/aa30301610e7cc363390fa1614ae36bcd759f258
[2] https://github.com/osmc/vero-linux/commit/3a66d93507bb2130e1f95189a5d697602cbdf72b
[3] https://github.com/osmc/vero-linux/commit/ddf2e9f60ceb9dc8f287d8ee7c31ccd9419701fa
[4] https://github.com/osmc/vero-linux/commit/a1cb4557060bb94f0453922bf8e31aba9ab29826

**Comment by lrusak** [comment]
Thanks @samnazarko!!

**Comment by vpeter4** [comment]
According to first tests from forum [1] didn't help. So 'maybe' was correct :(

**Comment by samnazarko** [comment]
May be a separate issue, I would still suggest keeping [1].

If Kodi starts but you get a black screen, it may be CEC related. I remember some old fixes from mk01 re this.

**Pull request merged**
