### PR TITLE
openssl: nonparallel build...

### PR DESCRIPTION
**Pull request by InuSasha**
it is failing on my machine, when building parallel (8 threads) with filled ccache

### CODE REVIEW

**Comment by CvH** [comment]
Does host and target fail for you?
IIRC it fails just for target for me if ccache is filled.
It even fails for me with 2 threads. Updating ccache was also no solution at my system.

**Comment by InuSasha** [comment]
host on my side.
I think, it is pseudo random, depending on cpu, memory, harddisk and so on

**Comment by chewitt** [comment]
I see no issues building openssl on a 16-core box. For me that proves we don't have a parallel build issue that needs -j1 .. and whatever the problem is, this is only a workaround not a solution.

**Comment by CvH** [comment]
For me it is >50% that it wont build. I build at an VM with 8 cores,maybe something cpu related as it won't hit everyone. Already tested fresh VM etc, nothing helped.

**Comment by InuSasha** [comment]
@chewitt you are right, it is a workaround. but openssl parallel build is a very long and painful story.
The problem with race conditions in parallel build is that small change on the system can change the behavior. Watching a video in your browser, can be enough to trigger it (or not to trigger it) . So it is hard to say "it is fixed".

**Comment by MilhouseVH** [comment]
Odd, I've never had this issue myself - I did 9 clean builds the other day, and no issue with OpenSSL.

**Comment by lrusak** [comment]
I've never seen this issue either

**Comment by lrusak** [comment]
If CCACHE is the issue then just increase the size via the libreelec options file

**Comment by InuSasha** [comment]
ccache make the build to fast on my system :)
only solution is to disable ccache. 

@CvH can you send me your error message, when you hit it

**Comment by CvH** [comment]
@lrusak ccache isn't full, I can clean ccache, build openssl, clean and build openssl again -> error
It isn't that annoying as I don't build openssl every day.

@InuSasha yea will try tomorrow, it always errors out at the same point

**Comment by chewitt** [comment]
@InuSasha what distro are you using to build from? .. Arch?

**Comment by InuSasha** [comment]
debian stable

**Comment by InuSasha** [comment]
i actual test this solution: https://github.com/InuSasha/LibreELEC.tv/commit/5710a4d66e1e0971cf9d3167f3287554e838aa7a

**Comment by vpeter4** [comment]
I also have issue with parallel building of openssl from time to time. Investigation lead to similar solution as InuSasha have.

**Comment by Raybuntu** [comment]
I'm on debian oldstable (jessie) and my other build machine is Ubuntu Xenial and I never had issues with building openssl with -j8.

**Comment by vpeter4** [comment]
Maybe problem happen only on not-so-fast machines :)

**Comment by InuSasha** [comment]
The problem is, that the ccgost part is linked against libcrpyto, but do not depends on it.
The major target engines depends on both (first libcrypto, second ccgost (indirect)). 
When ccache is full on my machine, both are linked at the same time... *buummm*

**Comment by adamg-xda** [comment]
Easy way to reproduce this bug is to export CCACHE_DIR outside of the LibreELEC build dir, make, clean, make.

**Comment by the-dreamer** [comment]
i had the issue already in openelec times but after the switch to libreelec and libressl there was long time no error. After switching back to openssl i have also no issue the last time until now. I did a complete clean build and openssl failed. Tried to rebuild openssl 5 times without luck. After applying the fix from this PR it is now building. I don't know when it happens. But i encounter this issue first time after switch back to openssl. I am building on a slow 1900j intel celeron system.

**Comment by chewitt** [comment]
Is this PR still relevant? .. I have still never seen this on any of our build infrastructure.

**Comment by InuSasha** [comment]
I hit it, from time to time.
It will resolved with openssl 1.1.0+

**Comment by CvH** [comment]
easily reproduce able for me too, cleaning ccache before rebuilding openssl fixes it ofc, so no too big deal

**Comment by chewitt** [comment]
Is there a reason why we didn't already bump to openssl 1.1.x? .. ABI change?

**Comment by InuSasha** [comment]
big API change...
the last try was failed, same month ago... I start a new try

**Comment by HiassofT** [comment]
I've been hit by this about 4 times during the last week. Today this happened on a clean RPi2 build during openssl:host build
```
../../libcrypto.so: file not recognized: File truncated
```
I've ccache on a separate spinning platter HDD, limit set to 60GB, and cleaned it before I ran the build.

As @cvh mentioned that he seem to have got this error during target build as well I'd vote for building both host and target with -j1.

It's rather annoying to be greeted with an aborted build in the morning when I kicked off clean builds overnight.

**Comment by vpeter4** [comment]
How many users needs to hit this problem until it is recognized as a problem and fixed? :)

**Comment by InuSasha** [comment]
@vpeter4 should solved with #2521 :)

**Pull request closed without merging**
