### PR TITLE
linux: update to 4.14.37

### PR DESCRIPTION
**Pull request by MilhouseVH**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.31
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.32
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.33
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.34
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.35 (not released)
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.36 (not released)
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.37

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Updated kernel-firmware: [diff](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/log/?qt=range&q=7344ec9..a4e3fdf)

* linux-firmware: intel: Update Geminilake audio firmware
* linux-firmware: intel: Update Kabylake audio firmware
* linux-firmware: intel: Update Broxton audio firmware
* linux-firmware: intel: Update Skylake audio firmware

**Comment by MilhouseVH** [comment]
amdgpu: update vce firmware for Polaris
Update firmware files for Intel Bluetooth 9560, 9260, 8265 and 8260.

**Comment by lrusak** [comment]
what's the status here?

**Comment by MilhouseVH** [comment]
Not yet reached 4.14.35...

**Comment by HiassofT** [comment]
@MilhouseVH could you add this commit: https://github.com/HiassofT/LibreELEC.tv/commit/e9fd8be05875719bc86f8f85fc7ba90121d0de64

This enables dynamic debug in the kernel, i.e. debug texts are compiled into the kernel and can be enabled at runtime. See here for more info: https://www.kernel.org/doc/html/v4.14/admin-guide/dynamic-debug-howto.html

This option has been enabled in major Linux distros like Debian, Ubuntu etc for quite some time now (oldest Debian I have here is Jessie with kernel 3.16, and the x86 kernel has it enabled).

It'll increase kernel size a bit but it's not dramatic:
RPi2 build without DYNAMIC_DEBUG
```
-rw-r--r-- 1 hias hias   6984288 Apr 21 16:18 LibreELEC-RPi2.arm-9.0-devel-20180421161200-r28484-g1c10176468.kernel
-rw-r--r-- 1 hias hias 127942656 Apr 21 16:18 LibreELEC-RPi2.arm-9.0-devel-20180421161200-r28484-g1c10176468.system
-rw-r--r-- 1 hias hias 140001280 Apr 21 16:18 LibreELEC-RPi2.arm-9.0-devel-20180421161200-r28484-g1c10176468.tar
```
and with DYNAMIC_DEBUG enabled
```
-rw-r--r-- 1 hias hias   7078552 Apr 22 11:57 LibreELEC-RPi2.arm-9.0-devel-20180422112749-r28485-gd547f10333.kernel
-rw-r--r-- 1 hias hias 128536576 Apr 22 11:58 LibreELEC-RPi2.arm-9.0-devel-20180422112749-r28485-gd547f10333.system
-rw-r--r-- 1 hias hias 140687360 Apr 22 11:58 LibreELEC-RPi2.arm-9.0-devel-20180422112749-r28485-gd547f10333.tar
```

**Comment by MilhouseVH** [comment]
@HiassofT should we include DYNAMIC_DEBUG for WeTek_Core and WeTek_Play - that would complete the set.

**Comment by HiassofT** [comment]
Good catch, I totally missed the wetek projects.

Yes, please enable DYNAMIC_DEBUG there as well then all projects should be in line

**Comment by MilhouseVH** [comment]
DYNAMIC_DEBUG now enabled for all projects.

**Comment by HiassofT** [comment]
Another small RPi config change: could you pick this commit: https://github.com/HiassofT/LibreELEC.tv/commit/85095c941e2a96cabd76063888c1a05c08f2153a

This adds the missing gpio_keys and rotary_encoder modules that are enabled in the foundation kernel and should fix the gpio-shutdown overlay not working - see here: https://forum.libreelec.tv/thread/12322-rpi-enable-dtoverlay-gpio-shutdown-to-allow-a-switched-power-on-off/

**Pull request merged**
