### PR TITLE
enable silead driver modules in kernel config

### PR DESCRIPTION
**Pull request by stpf99**
enable silead driver modules in kernel config

### CODE REVIEW

**Comment by chewitt** [comment]
I pushed changes to your repo to rename the commit. Now you need to show testing/evidence of the changes working.

**Comment by stpf99** [comment]
in libreelec build overlay and produced img is missing file for systemd sensors for rotation https://github.com/systemd/systemd/blob/main/hwdb.d/60-sensor.hwdb , in this file is adaptation from various sensors in devices to proper screen rotation

**Comment by chewitt** [comment]
I pushed a commit with a minimal version of the file to our systemd package. Please make the same change to your own LE image build and validate that it works?

**Comment by stpf99** [comment]
sorry files exists and "Bush tablet" is listed in /usr/lib/udev/hwdb.d/60-sensor.hwdb :
 cat /etc/udev/hwdb.d/README 
Hardware Database Files

The hwdb files are read from the files located in the system hwdb directory
/usr/lib/udev/hwdb.d and the user runtime directory /storage/.config/hwdb.d
All hwdb files are collectively sorted and processed in lexical order, regardless of
the directories in which they live. However, files with identical filenames
replace each other. /usr/lib/udev/hwdb.d/* takes precedence over /storage/.config/hwdb.d/*

**Comment by chewitt** [comment]
> However, files with identical filenames replace each other. /usr/lib/udev/hwdb.d/* takes precedence over /storage/.config/hwdb.d/*

The reverse is true, the files in `/storage/.config/hwdb.d/*` override the embedded location. I'll drop the systemd change.

**Comment by stpf99** [comment]
LibreELEC:~ # dmesg |grep silead
[    6.977610] silead_ts i2c-MSSL1680:00: supply vddio not found, using dummy regulator
[    6.977806] silead_ts i2c-MSSL1680:00: supply avdd not found, using dummy regulator
[    6.978190] silead_ts i2c-MSSL1680:00: Silead chip ID: 0x80360000
[   12.585117] silead_ts i2c-MSSL1680:00: Initialization error, status: 0xFFFF0000

LibreELEC:~ # lsmod |grep silead
silead                 20480  0

**Comment by chewitt** [comment]
I've no idea about the hardware, sorry. I'm blocking the PR until you figure out what's needed (to prevent accidental merge).

**Comment by stpf99** [comment]
this was succesed by corrupted fw file ,i replaced fw file and touchscreen works , and pointing is accurate in estouchy and estuary, but rotation not work and it is probably because kodi is always in fullscreen, how to resolve this, maybe somewhere is conf for screen orientation..

input for touchscreen is initiated:
LibreELEC:~ # dmesg |grep silead
[    7.454750] silead_ts i2c-MSSL1680:00: supply vddio not found, using dummy regulator
[    7.454922] silead_ts i2c-MSSL1680:00: supply avdd not found, using dummy regulator
[    7.455328] silead_ts i2c-MSSL1680:00: Silead chip ID: 0x80360000
[    9.114531] input: silead_ts as /devices/pci0000:00/808622C1:04/i2c-4/i2c-MSSL1680:00/input/input11

**Comment by stpf99** [comment]
for gbm Generic build i have question how to set proper screen rotation, if gbm is trought fb (framebufer) where to setup rotation ?

**Comment by chewitt** [comment]
@stpf99 is there any update coming on this PR?

**Comment by stpf99** [comment]
Hi... if libreelec have wayland for kodi but with sceren rotation like Gnome silead may enable with firmware from gsl-firmware wide range tablet devices, some inf from maintainer screen rotation/silead driver some months ago i received "silead working otb only on Gnome mutter currenty" weston have also rotaton utils for this or something included, but i'm  not have current inf about this, kodi is better if in wide mode but some devices default mode is fliped to ebook reader mode in vertical

**Pull request closed without merging**
