### PR TITLE
Broadcom SDIO drivers for Amlogic changes

### PR DESCRIPTION
**Pull request by Stane1983**
This PR renames kernel driver package to bcmdhd-sdio-aml, points to my github repository and adds autoload nvram and other files automatically based on chip id. It also changes wlan-firmware-aml to copy all firmwares and nvram files from archive to target which are supported for auto load by DHD driver.

### CODE REVIEW

**Comment by lrusak** [comment]
@codesnake mind having a look here?

**Comment by codesnake** [comment]
I don't understand the whole point of this PR, except of that it copies firmware for other Ampack chips. Why to repoint package to @Stane1983  bdcmdhd-only repository? The package was initially created so because Amlogic distributes sources in such way. Please check here: https://github.com/openwetek/brcmpa6xx-aml, and here: http://openlinux.amlogic.com:8000/download/ARM/wifi/

**Comment by Stane1983** [comment]
@codesnake First, brcmap6xxx-aml builds only bcmdhd_1_201_59_x folder (SDIO driver) - https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/linux-drivers/brcmap6xxx-aml/package.mk so if you have USB device (AP6269 or AP6242) you would have to rewrite package.mk. Package name brcmap6xxx-aml in that case does not have any sense.
Second, I just checked driver. It loads config.txt and reads nvram.txt name from it. Which means if any other chip than AP6335 is used in any other Amlogic based project you would also have to modify package.mk or put config.txt in filesystem of project together with firmware files.

**Comment by codesnake** [comment]
Anyway I think it is better to keep the package in the same form as Amlogic distributes it.
If you want additional chips to be supported by the package, just add them to the config.txt here: https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/linux-drivers/brcmap6xxx-aml/config/config.txt#L6-L7, no need to modify driver source code.

**Comment by Stane1983** [comment]
Ok, config.txt is also not same for all modules.

AP6354 (p200_2G amlogic reference board):
`kso_enable=0
ccode=CN
regrev=38`

AP6356 (q200 amlogic reference board):
`kso_enable=0
ccode=CN
regrev=38
use_rxchain=1
tcpack_sup_mode=1
tx_in_rx=0
dhd_rxbound=64`
...

**Comment by codesnake** [comment]
If we'll ever need different config.txt, we can introduce some project-based variable and copy different config.txt versions in package.mk.

**Comment by wrxtasy** [comment]
Well that time has arrived as I've already had to change the config.txt for the AP6330 equipped WeTekl Play2:
https://github.com/wrxtasy/LibreELEC.tv.7.0/blob/Play2/packages/linux-drivers/brcmap6xxx-aml/config/config.txt

**Comment by codesnake** [comment]
@wrxtasy This works for me: https://github.com/codesnake/LibreELEC.tv/blob/wetek_play_2_le7/packages/linux-drivers/brcmap6xxx-aml/config/config.txt for both AP6330 and AP6335.

**Comment by chewitt** [comment]
If a repo is the best option for managing the driver it's better to create the repo under our GH account than host it @Stane1983's personal account as more people will contribute towards upkeep (when things are under a personal account everyone expects that person to do all the work) and the repo is also under our version control. I prefer drivers to follow upstream naming to avoid confusion.

**Comment by lrusak** [comment]
thanks but this isn't needed at the moment.

**Pull request closed without merging**
