### PR TITLE
$DEVICE naming changes

### PR DESCRIPTION
**Pull request by lrusak**
~~First we want to be able to build the base project by itself.~~ The $DEVICE should be an overlay of the base project, not it's own.

The naming should use $DEVICE.$ARCH not $PROJECT.$DEVICE.$ARCH. This makes it so we don't have to change any backend or updated things.

ping @codesnake @kszaq @Kivutar and whoever else may use the $DEVICE call that this may change the way their build works.

### CODE REVIEW

**Comment by Kivutar** [comment]
Your change looks OK to me.
We should also think about using $DEVICE over $SYSTEM, or the opposite, since they are similar mechanism. But that's another discussion.

**Comment by vpeter4** [comment]
Like I wrote: SYSTEM has nothing to do with DEVICE. The only reason I introduce SYSTEM was to distinguish which final image to build because of different bootloader has to be used. All other pieces are the same. That's why it is not needed to build multiple projects just because of one (or few) different package.
But if this has to change than just do it.

**Comment by Kivutar** [comment]
OK I understand the difference now. Thanks.

**Comment by chewitt** [comment]
@lrusak can you rebase this pls.

**Comment by lrusak** [comment]
rebased.

**Comment by lrusak** [comment]
bueller?

**Pull request merged**
