### PR TITLE
[le11] rework wayland displayserver & windowmanager handling

### PR DESCRIPTION
**Pull request by SupervisedThinking**
This PR decouples Wayland & Weston which allows to alter or replace the windowmanager / compositor if needed without editing other packages beside the project options.

- add backported patch for Weston to use `WAYLAND_DISPLAY=wayland-1` as other compositors do & updated Kodi conf
- use `DISPLAYSERVER="wl"` & `WINDOWMANAGER="weston"` for wayland builds
- set `WINDOWMANAGER="no"` instead `WINDOWMANAGER="none"` for all GBM builds
- added a virtual `wl` package which allows to add dependencies/tools at a central place if necessary
- the virtual package adds the windowmanager dependency instead of adding Weston, or else, as dep.

Build & run tested with generic

### CODE REVIEW

**Comment by lrusak** [comment]
Why is this needed? If you don't want to use Weston just use another compositor and use the same deps as Weston does.

If you really want to change it you can add the wayland virtual package but you need the dependencies from Weston.

The windowmanager variable really shouldn't be reused outside of x11.

There is also not really a good reason to change from `none` to `no` as far as I can see.

**Comment by SupervisedThinking** [comment]
> Why is this needed? If you don't want to use Weston just use another compositor and use the same deps as Weston does.

Well most useful compositors in question use wlroots and have other dependencies as Weston, as I said before: I have no clue who actually uses Weston beside "(tech)demo systems"
 
> If you really want to change it you can add the wayland virtual package but you need the dependencies from Weston.

IMHO the `DISPLAYSERVER` should specify the protocol which is used & the `WINDOWMANAGER` the actual compositor / window manager.

> The windowmanager variable really shouldn't be reused outside of x11.

It's currently only used for X11 builds and it does not change the behaviour of those builds.

```
supervisedthinking@x220l:/mnt/dev/LibreELEC-RR$ git grep WINDOWMANAGER
config/show_config:  config_message+="\n - Window Manager / Compositor:\t\t ${WINDOWMANAGER}"
packages/virtual/x11/package.mk:if [ -n "${WINDOWMANAGER}" -a "${WINDOWMANAGER}" != "none" ]; then
packages/virtual/x11/package.mk:  PKG_DEPENDS_TARGET+=" ${WINDOWMANAGER}"
projects/ARM/options:    WINDOWMANAGER="none"
projects/Allwinner/options:    WINDOWMANAGER="none"
projects/Amlogic/options:    WINDOWMANAGER="none"
projects/Generic/devices/Generic/options:  WINDOWMANAGER="none"
projects/Generic/devices/wayland/options:  WINDOWMANAGER="none"
projects/Generic/devices/x11/options:  WINDOWMANAGER="fluxbox"
projects/NXP/options:    WINDOWMANAGER="none"
projects/Qualcomm/devices/Dragonboard/options:    WINDOWMANAGER="none"
projects/RPi/options:    WINDOWMANAGER="none"
projects/Rockchip/options:    WINDOWMANAGER="none"
projects/Samsung/options:    WINDOWMANAGER="none"
```
> There is also not really a good reason to change from `none` to `no` as far as I can see.

At the moment basically alls vars use no e.g. `OPENGL` `INSTALLER_SUPPORT` `DRIVER_ADDONS_SUPPORT` `whatever` so why don't we bring `WINDOWMANAGER` which is only used one time as `WINDOWMANAGER="fluxbox"` in line with the others? Aren't standards a good reason?

**Comment by CvH** [comment]
gtg or anything left ?

**Comment by SupervisedThinking** [comment]
Should be fine

**Review by CvH — APPROVED** [review]

**Pull request merged**
