### PR TITLE
build xmlstarlet

### PR DESCRIPTION
**Pull request by lrusak**
I'm not sure about the last commit for including xmlstarlet into the target build.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I'm assuming the last commit is because xmlstarlet is an OE unofficial addon (or was, until recently). Building xmlstarlet for target could be useful in future if/when manipulating xml content at startup etc.

Presumably this is for Kodi 17?

**Comment by MilhouseVH** [comment]
Once we self-build `xmlstarlet` it can be dropped from `scripts/checkdeps`:

https://github.com/LibreELEC/LibreELEC.tv/blob/master/scripts/checkdeps#L31-L32

**Comment by lrusak** [comment]
added a commit, thanks @MilhouseVH

**Comment by lrusak** [comment]
all good?

**Pull request merged**
