### PR TITLE
moonlight: allow building for Generic, add neon support in opus

### PR DESCRIPTION
**Pull request by lrusak**
I need to runtime test this before merging.

### CODE REVIEW

**Comment by lrusak** [comment]
added neon optimizations in opus as pointed out in https://github.com/irtimmer/moonlight-embedded/pull/370#issuecomment-219878676

**Comment by lrusak** [comment]
runtime tested on Generic, seems fine.

**Comment by kevmegforest** [comment]
Would it be possible to backport this also to the libreelec7.0 branch?

**Comment by lrusak** [comment]
@kevmegforest see #379

**Pull request merged**
