### PR TITLE
connman: ignore kernel-configured netdev and improve resolv.conf handling

### PR DESCRIPTION
**Pull request by HiassofT**
When netbooting the device used for /flash and/or /storage NFS mounts
is already managed by the kernel and has to be ignored by connman.

Connman only autodetects that case for standard netboot with nfsroot=
on kernel command line but doesn't know about boot= or disk= netboot
in LibreELEC so we have to set up the ignore manually.

When using kernel network (auto-)configuration the kernel provides
/proc/net/pnp with nameserver and in case of dhcp autoconfiguration
also with domain info, in standard resolv.conf format.

Though connman parses /proc/net/pnp if present it only uses the
nameserver info in it when creating resolv.conf but not the domain
info. To fix that use /proc/net/pnp directly as resolv.conf in case
of netboot.

To handle corner cases not covered by connman or kernel resolv.conf
setup allow users to provide their own resolv.conf file in
/storage/.config/

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks for this, I'll include it in nightlies.

Just a minor, but would it be better to add `export CONNMAIN_MAIN` at the end of the script? It's kind of ugly exporting it, then appending another value, when the following might be cleaner:

```
  if [ -f /storage/.config/connman_main.conf ]; then
    CONNMAN_MAIN="--config=/storage/.config/connman_main.conf"
  else
    CONNMAN_MAIN="--config=/etc/connman/main.conf"
  fi
...
[ -n "$NFS_DEV" ] && CONNMAN_MAIN="$CONNMAN_MAIN -I $NFS_DEV"
...
export CONNMAN_MAIN
```

**Comment by HiassofT** [comment]
good idea, also thought about that before. I've added a commit to change this.

**Comment by kalaksi** [comment]
```
# in case of netboot tell connman to ignore the network device
# used for NFS mount as it's already managed by the kernel
```
Is that really accurate? In an environment where DHCP is used, wouldn't you need something else than kernel to take care of renewing the lease from time to time? In other words, the network device would be initially configured but not managed anymore by the kernel.

**Comment by HiassofT** [comment]
Interesting point.

A quick glance through net/ipv4/ipconfig.c didn't turn up anything that would try to renew the release.

I suspect kernel ip autoconfiguration will only work reliably in setups with static DHCP IP assignments where missing renewals are not an issue. Which makes kind of sense for NFS netboot, gracefully handling lease expire (client then has to deconfigure it's interface) or DHCP IP address changes could be really problematic with root (or flash/system like in LE) on NFS.

If someone has more info about this topic I'd be interested to hear about it.

**Comment by kalaksi** [comment]
It is my understaning that normally kernel indeed doesn't take care of that.

IMO the wording in the comments should indicate that the interface will be actually left unmanaged after initial configuration. I personally feel having an unmanaged interface is not an ideal situation since I'm used to the notion that some part of the OS will manage them in at least some way. It could maybe break in unexpected situations (network cable disconnected for a moment? Wifi needs reconnecting?).

Anyways, I checked the RFC for proper information about the DHCP client behaviour. It says that if the DHCP client doesn't get a renewal for the lease, it will eventually just stop using it. Makes sense that clients can't just decide to keep using a dynamically configured address without confirmation from DHCP. In theory this should be an issue with a statically defined DHCP lease too, but I'm not sure how this actually plays out if there isn't even a DHCP client running so in practice it could work.

Oh, for environments with switches that use DHCP snooping, I'm pretty sure it will break, since they will enforce proper DHCP behaviour.

(See the state transition graph with the BOUND, RENEWING and REBINDING states: https://tools.ietf.org/html/rfc2131#page-34)

**Comment by kalaksi** [comment]
Therefore, I think connman should not ignore the interface. The specific issue with network storage and connman should be resolved in a more accurate way. E.g. in cases where shutdown hangs, connman should be made to stop very late or to not drop interfaces at all in shutdown somehow.

**Comment by HiassofT** [comment]
If you prefer I can change the wording to use "configured" instead of "managed".

Other than that this PR is just mimicing connman's behaviour when it detects nfsroot https://git.kernel.org/pub/scm/network/connman/connman.git/commit/?id=ef0d26e6ef2b883193469f016117d8238c1c9658

I'm well aware about rfc2131 but in an nfsroot context you'll need DHCP to behave pretty much like BOOTP or RARP - i.e. hand out static leases. Everything else (also unplugging the network cable) will be fatal to the system.

If you think the kernel should issue DHCP renew requests or if you'd like to have some DHCP handover  between the kernel and connman then please discuss that with the kernel and connman developers. We'd be happy to switch to a better solution once it's available.

**Comment by HiassofT** [comment]
updated PR with changed wording (configured instead of managed) in comments and commit message

**Comment by kalaksi** [comment]
Okay, fair enough then :+1:. I'm happy with the explanation.

(Apparently DHCP snooping can apparently also be configured properly for environments using BOOTP.)

So yea,

**Comment by mglae** [comment]
With the ignored device connman does not ave a default service and stay in "idle" state never reaching "ready" or "online".

1) Therefore kodi-waitonnetwork.service and network-online.service unnecessarily may delay the boot process. Can be solved by adding
```
ConditionPathExists=!/dev/.flash_netboot
ConditionPathExists=!/dev/.storage_netboot
```
to the unit files `[Unit]` section.

2) Without default service connman does not start the built-in NTP client. A possible work around is to use the already included busybox `ntpd` when netbooting.

**Comment by HiassofT** [comment]
@mglae thanks a lot for your comment! Both your points make sense, I'll have a look at adding fixes for it (already noticed the wait-on-network issue but missed the NTP issue)

I'm wondering if there's any value to run connman at all in a NFS-boot environment (haven't checked yet if WIFI tethering would work) - but for now I'll keep it enabled

**Comment by HiassofT** [comment]
From a quick test wifi tethering doesn't seem to work when connman ignores the nfsboot device - wifi AP is started and client can connect but won't get any internet access - probably because connman is still in idle state and doesn't know about the preconfigured internet connection.

As connman doesn't seem to cope well with such a setup I'm very inclined to disable it completely in case of NFS boot. None of the functions (NTP client, WiFi tethering) that it's otherwised useful for seem to work.

Any comments or info why running connman may still be useful are highly welcome

**Comment by HiassofT** [comment]
I noticed there are a couple more scenarios to handle, eg iscsi boot.

Connman is pretty useless when we disable the netboot interface (it won't run NTP, wifi tethering won't work) so I think it's best to disable connman when the interface was configured by the kernel and just run ntpd from busybox.

I'll handle that in a separate PR, will close this one for now.

@MilhouseVH can you drop this PR from your builds? And thanks for testing so far!

**Comment by mglae** [comment]
Just a thought after looking at this again: even connman being useless in any netboot case, the LE network configuration is relying on the dbus interface. It may be easier to keep connman active in the background and just disable any activity.

From a quick test disabling the plugins with `-P ethernet,wifi` looks promising.

**Comment by HiassofT** [comment]
I thought about this as well and I think it might be best to disable LE network configuration in the settings addon in the netboot case if it causes any problems.

IP, DNS and NTP can and should all be setup via `ip=`... on the kernel command line so there's not much left for the LE settings addon.

Instead of busybox NTP I'm thinking about using systemd-timesyncd, config and enablement setup by a systemd generator - might be more modern and should also cope better with systemd time-sync.target (which would be a bit of a hassle with busybox ntp).

**Comment by HiassofT** [comment]
new follow-up PR is here: #3936

**Pull request closed without merging**
