### PR TITLE
webgrabplus: update to 2.1.5_beta

### PR DESCRIPTION
**Pull request by awiouy**

### CODE REVIEW

**Comment by chewitt** [comment]
@awiouy what's the status on this PR?

**Comment by awiouy** [comment]
I was waiting for a wg+ release.
Also, as the config changes quite a lot, I was thinking releasing the addon under a new name.
I will work on that next week.

**Comment by awiouy** [comment]
Rebased and uploaded to forum.
Waiting for user feedback

**Comment by awiouy** [comment]
Rebased

**Comment by awiouy** [comment]
Ready to merge

**Pull request merged**
