### PR TITLE
tvheadend42: update addon

### PR DESCRIPTION
**Pull request by CvH**
- added tv_grab_file support for compressed files (gz bz2 xz) picked from https://github.com/LibreELEC/LibreELEC.tv/pull/1456
- update to Tvheadend 4.2.1.7 (finally a stable branch)
- fix FRITZ!Box support, AVM Repeater and 6490 are now working (mess due full broken vendor implementation that is unlikely to get fixed)

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Looks OK to me, builds fine, no complaints so far...

**Comment by TheUlpio** [comment]
Only a question! Now that 4.2 is the stable branch, it might start considering deprecated the original one and in few addon updates rename this to tvheadend and the old one tvheadend40?

**Comment by CvH** [comment]
@TheUlpio updating from 4.0 -> 4.1/2 is "not possible" in a safe way, you have a good chance that it result in a broken profile

**Comment by Leatherface75** [comment]
4.2.2 is released now and fixes a lot of things.

**Pull request merged**
