### PR TITLE
[Allwinner,Generic,Rockchip] linux: Update to 5.10.30

### PR DESCRIPTION
**Pull request by heitbaum**
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.27
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.28
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.29
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.30

5.10.27,- 219 patches
5.10.28 - 126 patches
5.10.29 - 41 patches
5.10.30 - 188 patches

log - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-5.10.y

- Generic (TGL) - build and run tested 5.10.27,5.10.28,5.10.29, 5.10.30 - heitbaum

### CODE REVIEW

**Comment by SupervisedThinking** [comment]
Run tested on Generic SKL/APL systems, building Rockhip atm

**Comment by heitbaum** [comment]
5.10.29 Build tested on all of:
```
PROJECT=Allwinner ARCH=arm DEVICE=H6 UBOOT_SYSTEM=tanix-tx6 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX6 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX8 s/build linux
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
PROJECT=Generic ARCH=x86_64 s/build linux
```

**Comment by CvH** [comment]
is this ready ?

**Comment by heitbaum** [comment]
Squashed the kernel updates together. 
Run test validation on RK and Allwinner needed

**Comment by SupervisedThinking** [comment]
RK builds & runs fine on my RockPro64

**Review by CvH — APPROVED** [review]

**Pull request merged**
