### PR TITLE
build system: avoid "boldwhite" color

### PR DESCRIPTION
**Pull request by mglae**
White text is invisible on terminal with white background.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Maybe don't use a white background? Otherwise with this change we'll have users complaining who use a yellow background, or one of the other colours for a background that clashes with an existing foreground colour. Unless we make the colours configurable (which is maybe an idea, as is the option to disable colours entirely) this is always going to be a problem.

I'd have to say I'm against tweaking colours for individual preferences.

**Comment by MilhouseVH** [comment]
As an alternative, what about:

https://github.com/LibreELEC/LibreELEC.tv/compare/master...MilhouseVH:le90_custom_build_colours

Then in `$HOME/.libreelec/options`:

1. Add `DISABLE_COLOURS=yes` to disable all use of colour within the build log.

2. Add
```
CLR_TARGET=boldyellow
CLR_PATCH_DESC=boldyellow
```
to achieve what you propose with this PR.

**Comment by MilhouseVH** [comment]
Example:
```
CLR_INSTALL=boldblue
CLR_TARGET=boldyellow
```
s1

**Comment by MilhouseVH** [comment]
Specifying your own colours combinations would also be easy - again in `$HOME/.libreelec/options`:
```
yellowonred="\e[33;41m"
CLR_INSTALL=yellowonred
CLR_TARGET="\e[7;32m" #reverse green
```
s1

**Comment by chewitt** [comment]
Terminal colour scheme is a "tabs vs. spaces" discussion. I personally find it incomprehensible that anyone could use black-on-white when the bible clearly states god intended green-on-black to be the one true colour scheme! .. there's something in "revelations" among all the talk about the prophecy of Armageddon. IMHO @MilhouseVH has the right idea; either make it fully configurable or leave it at alone :)

**Comment by HiassofT** [comment]
Green? Are you kidding me? Everyone knows that amber is the only one true color for terminals :)

On a more serious note: a mono mode that disables use of colors could indeed be helpful, eg to avoid cluttering build logs with escape sequences.

```
--- a/config/path
+++ b/config/path
@@ -211,6 +211,7 @@ fi
 BUILD_INDENT_SIZE=4

 # define colors
+if [ -z "$NO_COLORS" ] ; then
   black="\e[0;30m"
   boldblack="\e[1;30m"
   red="\e[0;31m"
@@ -228,6 +229,7 @@ BUILD_INDENT_SIZE=4
   white="\e[0;37m"
   boldwhite="\e[1;37m"
   endcolor="\e[0m"
+fi
```

Now let's fight about the spelling of colo(u)r :)

**Comment by vpeter4** [comment]
For which text is this change? BUILD line? I have white background in my terminals and I see it: https://snag.gy/52ZPqN.jpg

**Comment by mglae** [comment]
What did I do! :-)

@MilhouseVH: Great implementation

**Pull request closed without merging**
