### PR TITLE
firmware: update blobs. add script

### PR DESCRIPTION
**Pull request by MilhouseVH**
Updated X86 blobs from http://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/

This adds a script, `tools/mkpkg/update_firmware`, that will download the blobs, copy them to `linux/firmware`, and update the Generic and Virtual config files.

This has updated pretty much all of the `amdgpu` blobs, while adding the following:
```
i915/bxt_dmc_ver1_07.bin
i915/kbl_dmc_ver1_01.bin
i915/kbl_dmc_ver1.bin
i915/skl_dmc_ver1_23.bin
radeon/bonaire_k_smc.bin
radeon/hainan_k_smc.bin
radeon/hawaii_k_smc.bin
radeon/oland_k_smc.bin
radeon/pitcairn_k_smc.bin
radeon/tahiti_k_smc.bin
radeon/verde_k_smc.bin
```
and also updating:
```
i915/bxt_dmc_ver1.bin
```

### CODE REVIEW

**Comment by vpeter4** [comment]
Why not move this binary files to separate package?

**Comment by MilhouseVH** [comment]
You mean a separate repository? And then include as a package?

**Comment by vpeter4** [comment]
Not sure if separate repository is needed. Script would just download/clone all those binary blobs and created fwblobs-version.tar.xz archive for a new package fwblobs. Linux package would have dependency for it and those files would be copied to linux folder.
It is just an idea - separating build environment from actual files which doesn't really belong to package folder. Ignore if this doesn't make sense :)

**Comment by MilhouseVH** [comment]
It can be done, it just means maintaining another repository. I suppose it could mean the main repository becomes a little smaller. If someone wants to do it, feel free. :)

**Comment by chewitt** [comment]
sort of like https://github.com/OpenELEC/dvb-firmware ?

**Comment by lrusak** [comment]
see #739

**Pull request closed without merging**
