### PR TITLE
busybox: bump package to v1.28.1

### PR DESCRIPTION
**Pull request by adamg88**
As the title says...

Patches updated to reflect the bump.

In regards to the config changes, I have left these as the default answers during build time.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Do we need `CONFIG_RUN_INIT=y` in `host` and `target`?
```
//config:config RUN_INIT
//config:       bool "run-init"
//config:       default y
//config:       select PLATFORM_LINUX
//config:       help
//config:       The run-init utility is used from initramfs to select a new
//config:       root device. Under initramfs, you have to use this instead of
//config:       pivot_root.
//config:
//config:       Booting with initramfs extracts a gzipped cpio archive into rootfs
//config:       (which is a variant of ramfs/tmpfs). Because rootfs can't be moved
//config:       or unmounted, pivot_root will not work from initramfs. Instead,
//config:       run-init deletes everything out of rootfs (including itself),
//config:       does a mount --move that overmounts rootfs with the new root, and
//config:       then execs the specified init program.
//config:
//config:       util-linux has a similar tool, switch-root.
//config:       run-init differs by also having a "-d CAPS_TO_DROP" option.
```
We use `switch_root` in `init`.

**Comment by MilhouseVH** [comment]
This PR adds `CONFIG_FEATURE_CROND_SPECIAL_TIMES=y` which should be added as a new `sed` [here](https://github.com/adamg88/LibreELEC.tv/blob/06a6cdb2673ba9ee82f19e9f55ca2249d3f22530/packages/sysutils/busybox/package.mk#L93-L97) whenever CRON is not configured (arguably not required, but for the sake of completeness...).

Also, I'm not sure we need the following for `host`:
```
CONFIG_HEXEDIT=y
CONFIG_NUKE=y
CONFIG_RESUME=y
CONFIG_SETFATTR=y
```

In order:
HEXEDIT: Ability to hexedit a file
NUKE: `nuke` utility, equivalent to `rm -fr`
RESUME: resume from "suspend-to-disk" image
SETFATTR: set/delete extended attributes on files

None of these seem particularly useful for the host config (so we just waste time building them).

**Comment by adamg88** [comment]
Updated

**Comment by MilhouseVH** [comment]
Thanks.

**Pull request merged**
