### PR TITLE
Docker:  Update default.py to fix Python BPO - syntax warning for "is" with a literal

### PR DESCRIPTION
**Pull request by heitbaum**
Docker: Update default.py to fix Python BPO - syntax warning for "is" with a literal  

Error in Kodi nightly 1002. This is the fix.
default.py:188: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if __addon__.getSetting('notifications') is '0': # default
default.py:203: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif __addon__.getSetting('notifications') is '1': # all
default.py:217: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif __addon__.getSetting('notifications') is '2': # none
default.py:220: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif __addon__.getSetting('notifications') is '3': # custom
default.py:237: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if message is not '':

Had raised as kodi bug: https://github.com/xbmc/xbmc/issues/18501

Python BPO that introduced the behaviour https://bugs.python.org/issue34850

### CODE REVIEW

**Comment by mglae** [comment]
Please add "Docker: " to commit message and PR title.

**Comment by mglae** [comment]
Thanks, but I did forget the administrative part.

Please increase PKG_REV in package.mk and update changelog.txt. For including #4557 please add a line like  `Fix "docker run --init"`.

**Comment by heitbaum** [comment]
Hi @mglae think I covered all required now. Thanks for the help.

**Comment by mglae** [comment]
You may consider to log your own change too.

**Review by heitbaum — COMMENTED** [review]
Completed update and review based on feedback. Code change and supporting files matched.

**Comment by heitbaum** [comment]
Fix "docker run --init".
Fixes #4541

**Comment by heitbaum** [comment]
> You may consider to log your own change too.

Hi @mglae - do I need to perform any other steps to complete the pull? I can’t see where to actually create the change record?

**Comment by chewitt** [comment]
Please squash changes to a single commit and update the commit messsage (not the PR title) to follow house style, e.g. 

```
docker: update default.py to fix Python BPO - syntax warning for "is" with a literal
```

**Comment by heitbaum** [comment]
All done ready for commit now :-) @chewitt - was definitely a learning exercise on squashing as a single commit. Was good to learn something new in the lockdown.

**Review by mglae — APPROVED** [review]

**Pull request merged**
