### PR TITLE
system-tools: fix 7z

### PR DESCRIPTION
**Pull request by CvH**
```
cd /storage
7z a /tmp/test.7z /storage/.kodi/temp/kodi.log
```
wasn't working due missing 7z.so

```
LibreELEC:~ # 7z a /tmp/test.7z .kodi/temp/kodi.log
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,2 CPUs x64)
Can't load './7z.dll' (./7z.so: cannot open shared object file: No such file or directory)
ERROR:
7-Zip cannot find the code that works with archives.
```

some makefile/libtool issue prevents proper paths at the binary, this is a workaround that make it work

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Yeah, weird issue, but your fix seems to work.

**Comment by vpeter4** [comment]
Instead of making a wrapper script path could be added to dlopen() function call.

**Comment by CvH** [comment]
Looks like the wrapper script is the semi official way to go, at least debian is doing the same way so likely p7zip is just a mess that would need fixing. But if a wrapper script is good enough for Debian/Ubuntu it should be good enough for us too.

**Comment by vpeter4** [comment]
Another solution would be removing ./ from ./7z.so and adding LD_LIBRARY_PATH.

**Comment by chewitt** [comment]
Closing as superceded by #4441

**Pull request closed without merging**
