### PR TITLE
[LE11] linux: reduce potential attack surface

### PR DESCRIPTION
**Pull request by BellaCoola**
This branch contains changes which should reduce potential attack surface of the Linux Kernel. I am sending the changes only for x86_64 architecture, since currently I can not test it on other architectures, however I believe the same (or similar changes) could prove beneficial also for other architectures.

### CODE REVIEW

**Comment by lrusak** [comment]
What exactly are you worried about? The default user is root so there are many other security implications already.

**Comment by BellaCoola** [comment]
> What exactly are you worried about? The default user is root so there are many other security implications already.

I know and at the same time I think that (from security perspective) it isn't very fortunate (since when LibreELEC e.g. plays some file, it is essentially processing untrustworthy input via software written in memory-unsafe language running without any sandbox :blush: )  however I guess that it keeps many things simple. Despite of that fact my idea was that when it comes to reducing potential attack surface, improving at least low hanging fruits (such as this commit) could be beneficial - to provide more layers of security which might make some potential attacks at least less likely / less viable. Since LibreELEC provides services such as SAMBA, I guess it is meant to be connected to users' local networks, i.e. it is not meant to be isolated, therefore I think it should be / we should aim to make it as safe as possible by default.

**Comment by jernejsk** [comment]
I believe BPF is used for IR decoding, @HiassofT right?

**Comment by HiassofT** [comment]
Yes, BPF is used by IR decoders and, even more importantly, by systemd to implement security features like network filtering.

You didin't seem to have run "make oldconfig" so this PR doesn't reflect the full change - this is the outcome here: http://ix.io/3NYT

You have disabled some essential options - eg we want STAGING for various wifi and dvb drivers (on RPi also the whole video decoders would be disabled by that), KALLSYMS, FTRACE, SYSRQ are essential for debugging and getting usable crash reports.

Some other options like syncookes might be worth to consider but - sorry to say - overall this PR looks like you flipped some random kernel options without explaining in detail the negative impact on LE.

**Pull request closed without merging**
