### PR TITLE
update samba url to https

### PR DESCRIPTION
**Pull request by sopparus**
doesnt fetch without https at the moment and build halts

### CODE REVIEW

**Comment by MilhouseVH** [comment]
No real objection to the https change, but can you post the actual download error you are experiencing - I'm testing the http url here and it redirects to https, so the download succeeds...

**Comment by sopparus** [comment]
yep the redirect works now, guess it was just broken a few hours ago then. Close or merge, you decide :)

**Comment by MilhouseVH** [comment]
I think we'll merge, I was just more intrigued by why it had suddenly become an issue. Also, if ever the tarball is not available from the package url it should always be available from the LE mirror, but unfortunately that server is offline right now. So a combination of two issues (no redirect and no backup mirror) would halt your build.

**Comment by MilhouseVH** [comment]
@sopparus would you mind adding the same change for ccache as a second commit on each of your PRs?

**Comment by sopparus** [comment]
done

**Comment by MilhouseVH** [comment]
Many thanks!

**Pull request merged**
