### PR TITLE
jellyfin: update to 10.8.0-beta1 and addon (101)

### PR DESCRIPTION
**Pull request by heitbaum**
Jellyfin 10.8.0 for LE11 support.

- #6064
- #6065
- #6066

### CODE REVIEW

**Review by CvH — APPROVED** [review]

**Comment by heitbaum** [comment]
Please see update: https://github.com/LibreELEC/LibreELEC.tv/issues/6065#issuecomment-1005430280_

**Comment by heitbaum** [comment]
Waiting on a nightly based on https://github.com/jellyfin/jellyfin/pull/7112 before this can be made ready.

**Comment by heitbaum** [comment]
The JellyFin patch that we have been waiting for ([7112](https://github.com/jellyfin/jellyfin/commit/e26446f9c06d23d483d7c3db40888d51d37fdcdc)) Has been merged. The nightly https://repo.jellyfin.org/releases/server/portable/versions/unstable/combined/20220226.9/jellyfin_20220226.9-unstable.tar.gz does not include it - will check later in the day and then test the fix. It would be expected that _alpha6_ will include this fix now that it is in **master** - will continue to track and test.

**Comment by heitbaum** [comment]
Tested and now working - so the next alpha will be GtG. 
- tested with https://repo.jellyfin.org/releases/server/portable/versions/unstable/combined/20220301.9/jellyfin_20220301.9-unstable.tar.gz all good - scanning progresses now. 👍🎉🍺 - thank you.

_Originally posted by @heitbaum in https://github.com/jellyfin/jellyfin/issues/7112#issuecomment-1055380848_

**Comment by heitbaum** [comment]
Beta1 of Jellyfin 10.8.0 working on LE11 supported by dotnet 6. Jellyfin has been tested using Jellyfin nightlies successfully. Was waiting to have a stable downloadable location (which is beta1.) I have tested beta1 with :master and on a NUC11

**Review by CvH — APPROVED** [review]

**Pull request merged**
