### PR TITLE
media_build: add upstream patches

### PR DESCRIPTION
**Pull request by CvH**
media_build: cleanup and add upstream fix
- cleanup and add a patch that dibusb actually works at load (@kszaq we/you had this patch in the past iirc)

media_build: add Hauppauge DualHD second tuner support
- added the second tuner for the DualHD (tested by @edit4ever)

media_build: add TBS5580 support
- untested but compiles fine, likely that this get tested soon (no alternative at the market for this device)

media_build: add several lirc fixes
- several lirc fixes from upstream ( choosen by @HiassofT )

media_build: add Cinergy S2 Dual support
- untested but compiles fine, harmless patch

every patch should be merged upstream at the time kernel 4.13 is released

### CODE REVIEW

**Comment by HiassofT** [comment]
Thanks, I could verify that the lirc fix works (tested on Generic with serial_ir)

**Comment by dcervi** [comment]
I don't know if it's caused by this PR, but my Terratec Cinergy S2 Rev.4 doesn't work anymore after updating to 8.1.0 beta on my Rpi2. It was working fine up to 8.0.2. After reverting back it's working again.

I can provide logs if needed.

**Comment by CvH** [comment]
@dcervi
This shouldn't have any impact as it was reverted later. Pls open an thread at the forum, if you can provide an `dmesg | paste` from the working and not working version would be nice.

**Comment by dcervi** [comment]
@CvH 
Sorry, I've been out on vacation. I've just opened a [thread](https://forum.libreelec.tv/thread/9756-terratec-cinergy-s2-rev-4-initialization-error-on-le-8-1-0-and-8-1-1/) on the forum with the dmesg from working and non working LE versions. I hope you can identify what's causing the error.

**Pull request merged**
