### PR TITLE
Virtual project

### PR DESCRIPTION
**Pull request by lrusak**
Maybe someone can look this over. It should be fine but I haven't built a Generic version with this PR yet.

### CODE REVIEW

**Comment by chewitt** [comment]
Good to merge?

**Comment by lrusak** [comment]
:+1:

**Comment by MilhouseVH** [comment]
@bam80 `extlinux` can be dropped from the script. The `cp` errors look like they may never have worked. However the ` create_virtualimage` script is no longer maintained - if you use it, can you push a PR with the updates? Thanks!

**Comment by chewitt** [comment]
Use http://releases.libreelec.tv/LibreELEC-Generic.x86_64-8.2.3.ova?mirrorlist .. there's no need to roll your own image. Current images are vmware only due to constant breakage with VB.

**Comment by chewitt** [comment]
The download page only lists officially supported releases.

**Comment by bam80** [comment]
Then, IMO other releases should be listed somewhere else. How one find them otherwise?  http://releases.libreelec.tv/ dosn't give the list.

**Comment by bam80** [comment]
Then, IMO other releases should be listed somewhere else. How one finds them otherwise? http://releases.libreelec.tv/ doesn't give the list.

**Pull request merged**
