### PR TITLE
Update mtools + optimize mkimage to catch errors / to allow SYSTEM_SIZE >= 1024 / for speed

### PR DESCRIPTION
**Pull request by ToKe79**
Updated mtools to latest version.

Modified `scripts/mkimage` so image with `SYSTEM_SIZE` above 1024 MB can be created and errors during mformat/mcopy/mmd will be caught.

### CODE REVIEW

**Comment by heitbaum** [comment]
Hi @ToKe79 

Tested without 633501a and mtools: 4.0.36 - which I had had the issue post 4.0.29 too.
```
image: checking filesystem on part1...
image: An error has occurred...

Failed to read sector 1116159.
fsck.fat 4.2 (2021-01-31)

image: cleanup...

*********** FAILED COMMAND ***********
env ROOT="${ROOT}" SCRIPTS="${SCRIPTS}" TOOLCHAIN="${TOOLCHAIN}" PROJECT_DIR="${PROJECT_DIR}" PROJECT="${PROJECT}" DEVICE="${DEVICE}" DISTRO="${DISTRO}" TARGET_IMG="${TARGET_IMG}" BUILD_NAME="${IMAGE_NAME}" IMAGE_NAME="${1:-${IMAGE_NAME}}" BOOTLOADER="${BOOTLOADER}" KERNEL_NAME="${KERNEL_NAME}" TARGET_KERNEL_ARCH="${TARGET_KERNEL_ARCH}" RELEASE_DIR="${RELEASE_DIR}" UUID_SYSTEM="${UUID_SYSTEM}" UUID_STORAGE="${UUID_STORAGE}" DISTRO_BOOTLABEL="${DISTRO_BOOTLABEL}" DISTRO_DISKLABEL="${DISTRO_DISKLABEL}" UBOOT_SYSTEM="${UBOOT_SYSTEM}" EXTRA_CMDLINE="${EXTRA_CMDLINE}" SYSTEM_SIZE="${SYSTEM_SIZE}" SYSTEM_PART_START="${SYSTEM_PART_START}" OVA_SIZE="${OVA_SIZE}" ${SCRIPTS}/mkimage
**************************************
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 1
```
but with the addition of your 633501a patch to `mkimage` all looking correct. I have built Generic and am doing test builds on the others now.

**Comment by vpeter4** [comment]
Just for the reference: the minimal change for mformat to support any system partition size. Instead of providing disk geometry parameters just set number of sectors directly.

```
diff --git a/scripts/mkimage b/scripts/mkimage
index 817fa3f4f9..1c9a974a0e 100755
--- a/scripts/mkimage
+++ b/scripts/mkimage
@@ -100,12 +100,10 @@ fi
 # create filesystem on part1
 echo "image: creating filesystem on part1..."
 OFFSET=$(( ${SYSTEM_PART_START} * 512 ))
-HEADS=4
-TRACKS=32
-SECTORS=$(( ${SYSTEM_SIZE} * 1024 * 1024 / 512 / ${HEADS} / ${TRACKS} ))
+SECTORS=$(( ${SYSTEM_SIZE} * 1024 * 1024 / 512 ))
 
 shopt -s expand_aliases  # enables alias expansion in script
-alias mformat="mformat -i ${DISK}@@${OFFSET} -h ${HEADS} -t ${TRACKS} -s ${SECTORS}"
+alias mformat="mformat -i ${DISK}@@${OFFSET} -T ${SECTORS}"
 alias mcopy="mcopy -i ${DISK}@@${OFFSET}"
 alias mmd="mmd -i ${DISK}@@${OFFSET}"
```

**Comment by heitbaum** [comment]
All the following builds (with the first 2 mtools ff787bc and 633501a patches) were ok. 
- so think the builds were good
- Haven't done a run test yet.
- Or a full build of the below with patch b388903 and ba592a9.
```
    PROJECT=Allwinner ARCH=arm DEVICE=A64 make image
    PROJECT=Allwinner ARCH=arm DEVICE=H3 make image
    PROJECT=Allwinner ARCH=arm DEVICE=H5 make image
    PROJECT=Allwinner ARCH=arm DEVICE=H6 make image
    PROJECT=Rockchip ARCH=arm DEVICE=RK3288 make image
    PROJECT=Rockchip ARCH=arm DEVICE=RK3328 make image
    PROJECT=Rockchip ARCH=arm DEVICE=RK3399 make image
    PROJECT=NXP ARCH=arm DEVICE=iMX6 make image
    PROJECT=NXP ARCH=arm DEVICE=iMX8 make image
    PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard make image
    PROJECT=Samsung ARCH=arm DEVICE=Exynos make image
    PROJECT=Generic ARCH=x86_64 DEVICE=Generic make image
    PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy make image
```
@knaerzche - I had the following build error on https://github.com/heitbaum/LibreELEC.tv/commits/kernel11 (not related to this mtools PR) - but as a FYI
```
Installing u-boot for board miqi...
...
  HOSTLD  tools/fdtgrep
tools/image-host.o: In function `fit_image_setup_sig':
image-host.c:(.text+0x4fd): undefined reference to `image_get_checksum_algo'
image-host.c:(.text+0x514): undefined reference to `image_get_crypto_algo'
tools/image-host.o: In function `fit_config_get_data':
image-host.c:(.text+0x1154): undefined reference to `fit_region_make_list'
collect2: error: ld returned 1 exit status
make[2]: *** [scripts/Makefile.host:108: tools/mkimage] Error 1
make[2]: *** Waiting for unfinished jobs....
tools/image-host.o: In function `fit_image_setup_sig':
image-host.c:(.text+0x4fd): undefined reference to `image_get_checksum_algo'
image-host.c:(.text+0x514): undefined reference to `image_get_crypto_algo'
tools/image-host.o: In function `fit_config_get_data':
image-host.c:(.text+0x1154): undefined reference to `fit_region_make_list'
collect2: error: ld returned 1 exit status
make[2]: *** [scripts/Makefile.host:108: tools/dumpimage] Error 1
make[1]: *** [Makefile:1297: tools] Error 2
make[1]: Leaving directory '/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RK3288.arm-11.0-devel/build/u-boot-8659d08d2b589693d121c1298484e861b7dafc4f'
FAILURE: scripts/build u-boot during make_target (package.mk)
*********** FAILED COMMAND ***********
DEBUG=${PKG_DEBUG} CROSS_COMPILE="${TARGET_KERNEL_PREFIX}" LDFLAGS="" ARCH=arm _python_sysroot="${TOOLCHAIN}" _python_prefix=/ _python_exec_prefix=/ make ${UBOOT_TARGET} HOSTCC="${HOST_CC}" HOSTCFLAGS="-I${TOOLCHAIN}/include" HOSTLDFLAGS="${HOST_LDFLAGS}" HOSTSTRIP="true" CONFIG_MKIMAGE_DTC_PATH="scripts/dtc/dtc"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************
*********** FAILED COMMAND ***********
UBOOT_SYSTEM="${UBOOT_SYSTEM}" ${SCRIPTS}/install u-boot 2>&1
**************************************
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 2
```

**Comment by heitbaum** [comment]
Build test (as above) with b388903 and ba592a9 was good too.

**Comment by heitbaum** [comment]
Just boot tested the LibreELEC-H6.arm-11.0-devel-20211123110500-b17148a-tanix-tx6.img.gz image (all good) 
```
[    1.477999] Checking disk(s):  UUID=2311-0529 UUID=4fc5dd82-ba64-4f54-a1f4-8d1dd49be10d
[    1.851194] fsck: Cannot initialize conversion from codepage 850 to ANSI_X3.4-1968: Invalid argument
[    1.851514] fsck: Cannot initialize conversion from ANSI_X3.4-1968 to codepage 850: Invalid argument
[    1.851669] fsck: Using internal CP850 conversion table
[    1.851793] fsck: fsck.fat 4.2 (2021-01-31)

/dev/mmcblk0p1          524008    136320    387688  26% /flash
/dev/mmcblk0p2        28707394      5947  28697351   0% /storage
```
with both this PR and the Kernel #5853

**Comment by ToKe79** [comment]
I updated the last commit, as I forgot to add the ENV in `scripts/image`. Also building the package `virtual` is not needed when skipping OVA.

**Comment by ToKe79** [comment]
I just realized that when skipping the virtual appliance image more optimizations can be done (remove `vmware` and `virtio` graphic drivers, remove some `CONFIG_*VIRTIO*`), so I am reverting this change and I will squash the changes to `mkimage`.

**Comment by heitbaum** [comment]
Build and run tested under `PROJECT=Amlogic ARCH=aarch64 DEVICE=AMLG12 UBOOT_SYSTEM=odroid-n2 make image` today with #5920

**Review by CvH — APPROVED** [review]

**Pull request merged**
