### PR TITLE
Update ddbridge drivers in kernel 4.7.2

### PR DESCRIPTION
**Pull request by mglae**
Support current Digital Devices tuner cards in kernel 4.7.2. Update drivers to 0.9.23.

The patch is created from the [dddvb-linux-kernel](https://github.com/herrnst/dddvb-linux-kernel/commits/mediatree/master-ddbridge-features) repository. All thanks go to @herrnst

### CODE REVIEW

**Comment by CvH** [comment]
@mglae http://forum.kodi.tv/showthread.php?tid=269815 >=0609 builds has this pr in - (we have no hw to test this)

**Comment by mglae** [comment]
@CvH I really should have noted that the patch worked for me on kernel 4.7.0 for one week and currently works since two days on 4.7.2

I will test #0906 from USB stick when there is a idle time slot on the HTPC.

**Comment by mglae** [comment]
@CvH Works.

**Comment by CvH** [comment]
@mglae
could you pr the changes needed for the Kconfig that `make oldconfig` would include the drivers ?

**Comment by mglae** [comment]
@CvH just the two diffs against linux.x86_64.conf that are part of this PR?

**Comment by MilhouseVH** [comment]
@mglae & @cvh: sorry I think there's been some confusion. @cvh and I were discussing some missing config options and @cvh mentioned that `CONFIG_DVB_STV6111` etc. were also missing, so I said if they're missing it's because they're not in the Kconfig. Turns out @cvh had been looking at a config from Virtual which might have been incomplete (or something). Anyway, I've re-done the options for 4.7.4 (see #748) and the options needed by this PR are present for both Generic and Virtual, so I think this is a false alarm.

**Comment by mglae** [comment]
@MilhouseVH @CvH: IMO the dvb frontends are auto selected by  CONFIG_MEDIA_SUBDRV_AUTOSELECT. No need to do it explicit.

**Comment by MilhouseVH** [comment]
They're all defaults (ie. auto-selected).

**Pull request merged**
