### PR TITLE
Update game addons... for Christmas!

### PR DESCRIPTION
**Pull request by garbear**
## Description

I had some time over the holiday break to do a round of game add-on updates. Besides rebasing everything on their master branches, not much has changed, except that the "Settings" button in the Advanced Settings is now using Kodi's localized "General" label: https://github.com/kodi-game/kodi-game-scripting/pull/132

## How has this been tested?

My build machine is in pieces on the floor, so I'm not able to compile-test this PR. But all add-ons have been run through Kodi's CI.

### CODE REVIEW

**Comment by heitbaum** [comment]
A quick build test of the addons (Generic)

```
UNPACK      libretro-stella
    APPLY PATCH (common)      packages/emulation/libretro-stella/patches/stella-01-do_not-use_static_libgcc_libstdc++.patch
patching file src/os/libretro/Makefile
Hunk #1 FAILED at 57.
1 out of 1 hunk FAILED -- saving rejects to file src/os/libretro/Makefile.rej
``` 

Need to revert b7fc8f5b3e for game.libretro.scummvm

Unable to build test game.libretro.tyrquake - my dev environment is gcc-15 at the moment (and game.libretro.tyrquake doesn’t build with gcc-15.)

**Comment by garbear** [comment]
I'll look into stella. I know that for Kodi's CI, it currently only builds on Windows, due to needing C++20.

Lets drop the scummvm patch, I'm still working on that: https://github.com/LibreELEC/LibreELEC.tv/pull/9083

I'll also look into tyrquake.

**Comment by heitbaum** [comment]
the addition of these 2 commits allow all to build
https://github.com/heitbaum/LibreELEC.tv/commit/fc94126682749fa6a4641bff297e239b0afefec8
https://github.com/heitbaum/LibreELEC.tv/commit/08c1c234cec31f90eefd237d3502392145b43ef6

**Comment by garbear** [comment]
I've confirmed that all add-ons build against LE master now after adding your patches, including Tyrquake (LE master using gcc version 14.2.0)

**Review by chewitt — APPROVED** [review]

**Pull request merged**
