### PR TITLE
busybox: disable password weakness check

### PR DESCRIPTION
**Pull request by CvH**
This disables the complex password check for busybox.
The complexity is rather meh in perspective of an mediabox that is overly used at a home network.
Ofc this opens the possibility to use highly insecure passwords as well, but at least we won't force users to set `as%&!hah91` passwords.

A better fix would be adjustable weakness checks at busybox, but this is not at the horizon yet.

### CODE REVIEW

**Comment by HiassofT** [comment]
Thanks, this is a very good idea - busybox's weak password check is ultimately annoying.

BTW: can you please also drop this patch so passwd works as in upstream busybox? https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/busybox/patches/busybox-06-prevent-root-weak-passwd.patch

**Comment by CvH** [comment]
@HiassofT done

**Comment by lrusak** [comment]
I don't really understand this. First we get a bunch of flack for having a non-changeable password. Now you want to be able to set a weak password?

So do you want security or not?

**Comment by HiassofT** [comment]
Changeable passwords are nice, but a too annoying password policy is not.

Neither Debian nor OpenWrt enforce such a policy so I don't see a point why LibreELEC should do that.

Security isn't a black-white yes/no thing, you have to find the right balance and I think following what Debian and OpenWrt do is a good choice

**Comment by HiassofT** [comment]
Ah, a good compromise may be to leave CONFIG_FEATURE_PASSWD_WEAK_CHECK=y intact and just drop our busybox patch.

Then we are at busybox's default config (which OpenWrt's uses as well) and you get a warning from passwd when you set a weak root password but are still able to set a weak password if you want to

**Pull request closed without merging**
