### PR TITLE
docker: updated to 19.03.3

### PR DESCRIPTION
**Pull request by 5schatten**
- https://github.com/docker/docker-ce/releases/tag/v19.03.3

### CODE REVIEW

**Comment by 5schatten** [comment]
@zsolooo
have a look

**Comment by zsolooo** [comment]
@5schatten Thank you for the quick introduction, it was easier than I expected. Though I had 2 minor issues during build (not in the docker addon), but quickly fixed them.
Unfortunately I had no time to try it on my device after the build, I will check it when I'm home.

**Comment by zsolt-keseru-epam** [comment]
@5schatten Something is not right, when I've upgraded from 127 to 129 it was working, my containers were fine, then updated to the 130 and I got containerd segmentation fault again.
Rolled back to 128 and I also got segmentation fault there.
It feels like some issue around the upgrade vs. the persisted data, so I will try to get it working again somehow then thinking on re-testing these upgrade paths in combinations of wiping data or not.

**Comment by zsolooo** [comment]
@5schatten Something is not right, when I've upgraded from 127 to 129 it was working, my containers were fine, then updated to the 130 and I got containerd segmentation fault again.
Rolled back to 128 and I also got segmentation fault there.
It feels like some issue around the upgrade vs. the persisted data, so I will try to get it working again somehow then thinking on re-testing these upgrade paths in combinations of wiping data or not.

**Comment by 5schatten** [comment]
@zsolooo 
well can you try to install the addons cleanly? Also _if_ `containerd` segfaults this is more likely a problem of this specific package :thinking: Have you tested your sd card too?

**Comment by 5schatten** [comment]
I'm not sure if this is not some RPi related b$ because have a look at this log https://pastebin.com/wDrPVw4H

I just tried to start `containerd` and got 2 times a segfault & it boots the third time...

Same for v1.2.10 https://pastebin.com/vSathPGx it started on 5x try.

@HiassofT any idea which problem could be RPi specific? I'm using Linux kernel 5.3.3 btw.

**Comment by 5schatten** [comment]
@zsolooo merge this PR https://github.com/LibreELEC/LibreELEC.tv/pull/3857 and try again. Looks like  it does not segfault anymore with Linux kernel 5.3.5

**Comment by heitbaum** [comment]
I have rebased the proposed docker update against Master with the latest 19.03.13 with containerd 1.3.7. I used @5schatten patches as a based line. This Docker has been tested on Generic.

go: update to go-1.14.11
containerd: updated to v1.3.7
libnetwork: updated to git 535ef36
docker: updated to 19.03.13

Please let me know the most appropriate way to have these commits integrated into master? 

https://github.com/LibreELEC/LibreELEC.tv/compare/master...heitbaum:master

**Comment by CvH** [comment]
@heitbaum the changes itself looking okay, sadly your git usage is the opposite :)
You should keep your master branch untouched and do all your changes in dedicated branches (random example https://github.com/CvH/LibreELEC.tv/branches/active).

So for docker you should create a branch from master named "docker_update" and put your changes there.
Depending what program you use it is more or less difficult. Then you create a pr against LE master from your "docker_update" branch. Currently you have a wild mix of changes at your master branch.

Btw you can still reuse your commits etc, no need to redo it. If you need help with git fu just ask :)

**Comment by heitbaum** [comment]
> @heitbaum the changes itself looking okay, sadly your git usage is the opposite :)

:-) I did expect that feedback LOL. I had thought it was getting unruly, hadn’t really been expecting to get fully back into source hacking, was on my list to fix up. Thanks for the direction, I’ll get the get fixed up and the PR later today. A nice day outside, so off to get a morning coffee.

**Comment by chewitt** [comment]
Closing as superseded by #4647

**Pull request closed without merging**
