### PR TITLE
kodi: cleanup patches

### PR DESCRIPTION
**Pull request by lrusak**
Waiting to hear back from https://github.com/xbmc/xbmc/pull/11261

### CODE REVIEW

**Comment by lrusak** [comment]
@vpeter4 do you mind testing the imx6 patch? I built it but it would be good to be double sure :)

**Comment by vpeter4** [comment]
@lrusak: all good.

**Comment by chewitt** [comment]
@lrusak is this good to go?

**Comment by lrusak** [comment]
not just yet

**Comment by lrusak** [comment]
Updated to the latest kodi commit that includes all my upstreamed patches.

This is good to go now. We can bump kodi again when the next RC is released

**Pull request merged**
