### PR TITLE
libbluray: update to 1.2.0

### PR DESCRIPTION
**Pull request by graysky2**
`packages/multimedia/libbluray/patches/*` patch into this version cleanly

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks, but probably best to wait until Kodi bumps to libbluray-1.2.0 as there may be [some changes required](https://github.com/xbmc/xbmc/issues/16331).

**Comment by CvH** [comment]
still not updated https://github.com/xbmc/xbmc/blob/master/tools/depends/target/libbluray/Makefile

**Comment by heitbaum** [comment]
@graysky2  - libbluray is now 1.2.1 - https://www.videolan.org/developers/libbluray.html
Still not merged in kodi (it is running 1.1.2)

https://code.videolan.org/videolan/libbluray/-/blob/master/ChangeLog

**changelog**
2020-10-25: Version 1.2.1
- Add initial support for .fmts files.
- Improve missing/broken playlist handling ("Star Trek Beyond 4K").
- Improve UHD metadata support.
- Improve BD-J compability.
- Improve error resilience and stability.
- Fix long delay in "Evangelion, You are (not) alone" menu.
- Fix JVM bootstrap issues with some Java 9 versions.
- Fix sign extended bytes when reading single bytes in BDJ.
- Fix creating organization and disc specific BD-J BUDA directories.
- Use external libudfread when available.
- Rename list_titles to bd_list_titles and add it to installed programs.

2020-03-22: Version 1.2.0
- Add functions to list and read BD-ROM files.
- Add support for separate key pressed / typed / released user input events.
- Add support for AWT mouse events (BD-J).
- Fix build with OpenJDK 12 / 13.

**Comment by CvH** [comment]
changelog 1.3.0, kodi has still not updated, if this should end somewhere someone needs to deal with it at Kodi
```
2021-04-05: Version 1.3.0
- Add bd_event_name().
- Add return value to bd_refcnt_inc().
- Add cache for parsed clpi file data.
- Add player setting for JRE location (JAVA_HOME).
- Improve FreeBSD BD-J support.
- Improve portability.
- Improve JVM and .jar file probing.
- Fix handling of non-ASCII .iso filenames in Windows (update libudfread to 1.1.2).
- Fix leak.
```

**Comment by CvH** [comment]
https://github.com/xbmc/xbmc/pull/20747

**Comment by HiassofT** [comment]
superseded by #6226

**Pull request closed without merging**
