### PR TITLE
Cpu temperature readings for devices with aml_thermal interface

### PR DESCRIPTION
**Pull request by drieschel**
Adds correct cpu temperature readings for Amlogic devices which have the aml_thermal (AML_PLATFORM_THERMAL) interface enabled.

@MilhouseVH This time everything in a single commit (hopefully)^^

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Many thanks, looks good to me.

Don't forget to submit this to Kodi! :)

**Comment by drieschel** [comment]
I already did. Here is the link to the PR: https://github.com/xbmc/xbmc/pull/10091

**Comment by drieschel** [comment]
Btw. Is the cputemp script still in use? It probably would make sense to split it in two scripts - cputemp and gputemp - and not only to create a gputemp symlink.

**Comment by chewitt** [comment]
I've added "don't merge" as this is clearly pending upstream agreement on changes

**Comment by drieschel** [comment]
The PR (https://github.com/xbmc/xbmc/pull/10091) to Kodi is closed and they won't include it yet. In the meantime I created a PR (https://github.com/codesnake/linux/pull/6) ) at @codesnake's Amlogic kernel (the amlogic kernel in LE) for integrating a patch, which let's the aml_thermal interface work. Codesnake commented also in the closed PR that he will check the aml_thermal functionality in this kernel. So let's see what he will find out.

**Comment by lrusak** [comment]
@drachul any updates here? Whats the state of this upstream?

**Comment by drieschel** [comment]
@lrusak This should work with Wetek Core and on all other Meson8* devices at least. I will check what have to be done in the kernel conf and update this pr soon. Was a bit busy the last time.

**Comment by Goga777** [comment]
@drieschel Can we see CPU temperature on wetek play devices in kodi interface ? Second question - is it possible to see cpu temperature through ssh in linux terminal ? I just to be sure that my wetek play is not overheated

**Comment by Stane1983** [comment]
Appending advancedsettings.xml with cputempcommand does it just fine. Kodi wiki on that section in advancedsettings.xml: http://kodi.wiki/view/advancedsettings.xml#cputempcommand

Sample: https://github.com/Extro-development/LibreELEC.tv/blob/master/projects/dsPure/kodi/advancedsettings.xml#L4

**Comment by Goga777** [comment]
it will work with wetek play ? In wiki wetek doesn't mention

**Comment by lrusak** [comment]
@Stane1983 can make you make a new PR for that for the existing amlogic projects?

**Comment by Stane1983** [comment]
@lrusak I can only check and commit patch for WeTek Play (version 1) as it's only device I have from WeTek. And that only if temp can be read from one of sysfs nodes. MX devices as far as I remember are using one of ADC channels for reading temperature. Have to test. Other 2 devices maybe to be PR by @codesnake or all 3?

**Comment by lrusak** [comment]
I can test on all three but wont be home for a couple days so unless someone gets to it sooner than I. The easiest thing to do is just make a PR for all three then I can kick of some builds with jenkins and have the builds ready to test when I get home.

**Comment by Stane1983** [comment]
Also for 3.14 kernel, Amlogic thermal driver must be enabled for this to work. My project is based on WeTek Hub where it is not enabled (Kconfig of aml thermal driver must select/depend on THERMAL, CPU_THERMAL, CPUCORE_THERMAL, GPU_THERMAL and GPUCORE_THERMAL to compile).

**Comment by mikko70** [comment]
I hope this can add soon, BTW  if i connect from PC internet browser and try look tv-shows (Wetek play 1 IP-address) processor running 100% and option not show tv-show information.

**Comment by lrusak** [comment]
@drieschel I'm not sure if this is needed anymore? seems the CPU temp is working ok on my Odroid C2 using the latest git

**Comment by drieschel** [comment]
@lrusak It's still needed for arm devices, ie meson8. Sorry for my delay. Working a lot and need to finish my project. But didn't forget this and will care about as soon as I have a bit more free time.

**Comment by lrusak** [comment]
Any updates here?

**Comment by drieschel** [comment]
@lrusak Not yet. I have problems updating my LE fork to the actual state. First I will do this and then I can create a new PR. So I will close it now.

**Pull request closed without merging**
