### PR TITLE
mesa: update to mesa-20.0.0

### PR DESCRIPTION
**Pull request by MilhouseVH**

### CODE REVIEW

**Comment by chewitt** [comment]
I've been using mesa 20 for a while with no issues, so LGTM.

**Comment by dhewg** [comment]
I've been using v20 (just a few days behind the tag) on Allwinner too, so that looks good too

**Comment by jernejsk** [comment]
Please don't merge it just yet, I want to test this with lima.

**Comment by jernejsk** [comment]
lima works fine

**Pull request merged**
