### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by lrusak**
Some last package updates before feature freeze

These have all built on my system, but should be included in a clean @MilhouseVH build before merging.

They are all micro version updates.

### CODE REVIEW

**Comment by lrusak** [comment]
updated to include mesa 12.0.2

**Comment by lrusak** [comment]
updated to include libva and libva-intel-driver bumps

**Comment by MilhouseVH** [comment]
Chromium broken by freetype bump:

```
NUC:~ # .kodi/addons/browser.chromium/bin/chromium
/storage/.kodi/addons/browser.chromium/bin/chromium.bin: symbol lookup error: /storage/.kodi/addons/browser.chromium/bin/chromium.bin: undefined symbol: png_set_longjmp_fn
```

This happened before, https://github.com/LibreELEC/LibreELEC.tv/pull/555#issuecomment-234759945

**Comment by MilhouseVH** [comment]
Chromium and freetype 2.6.5 also fails with the same error.

Chromium works with freetype 2.6.3.

**Comment by lrusak** [comment]
push a mysql update also, I had to revert this commit, https://github.com/mysql/mysql-server/commit/1919ed695a28905c40d4cc8dfd9d24db6c879f3d in order for it to build

**Comment by MilhouseVH** [comment]
Unfortunately png_set_longjump_fn is still a problem with Chromium 8.0.104.
```
neil@nm-linux:~/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/freetype-2.6.5$ readelf -s .install_pkg/usr/lib/libfreetype.so.6.12.5 | grep png_set_longjmp_fn
   210: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND png_set_longjmp_fn
```

but when running Chromium in the new build it fails as it did before:
```
NUC:~ # .kodi/addons/browser.chromium/bin/chromium
/storage/.kodi/addons/browser.chromium/bin/chromium.bin: symbol lookup error: /storage/.kodi/addons/browser.chromium/bin/chromium.bin: undefined symbol: png_set_longjmp_fn
```

**Comment by lrusak** [comment]
I've dropped the freetype update for now. I look into it at a later time or if we bump all add-ons

**Comment by lrusak** [comment]
most likely chromium needs to be rebuilt as quite a few libraries depend on freetype

```
browser.chromium/lib/libcairo.so.2
 0x0000000000000001 (NEEDED)             Shared library: [libfreetype.so.6]
browser.chromium/lib/libexif.so
browser.chromium/lib/libexif.so.12
browser.chromium/lib/libexif.so.12.3.3
browser.chromium/lib/libfreebl3.so
browser.chromium/lib/libgdk_pixbuf-2.0.so.0
browser.chromium/lib/libgdk-x11-2.0.so.0
 0x0000000000000001 (NEEDED)             Shared library: [libfreetype.so.6]
browser.chromium/lib/libgtk-x11-2.0.so.0
 0x0000000000000001 (NEEDED)             Shared library: [libfreetype.so.6]
browser.chromium/lib/libharfbuzz.so.0
 0x0000000000000001 (NEEDED)             Shared library: [libfreetype.so.6]
browser.chromium/lib/libnspr4.so
browser.chromium/lib/libnss3.so
browser.chromium/lib/libnssckbi.so
browser.chromium/lib/libnssdbm3.so
browser.chromium/lib/libnsssysinit.so
browser.chromium/lib/libnssutil3.so
browser.chromium/lib/libpango-1.0.so.0
browser.chromium/lib/libpangocairo-1.0.so.0
 0x0000000000000001 (NEEDED)             Shared library: [libfreetype.so.6]
browser.chromium/lib/libpangoft2-1.0.so.0
 0x0000000000000001 (NEEDED)             Shared library: [libfreetype.so.6]
browser.chromium/lib/libplc4.so
browser.chromium/lib/libplds4.so
browser.chromium/lib/libsmime3.so
browser.chromium/lib/libsoftokn3.so
browser.chromium/lib/libsqlite3.so
browser.chromium/lib/libssl3.so
browser.chromium/lib/nvidia_drv_video.so
browser.chromium/lib/vdpau_drv_video.so
```

**Pull request merged**
