### PR TITLE
pulseaudio: enable speex support 

### PR DESCRIPTION
**Pull request by lrusak**
This fixes the following warning:

```
You do not have speex support enabled. It is strongly recommended
that you enable speex support if your platform supports it as it is
the primary method used for audio resampling and is thus a critical
part of PulseAudio on that platform.
```

Note that this commit was done on top of the meson changes in #3928 thus the meson warning in the commit message. Ideally this can merge after the meson changes and I can update this to use meson instead.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
So when PulseAudio says `--enable-speex` it actually means "enable speexdsp"? What's the difference between [`speex`](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/audio/speex/package.mk) (which we already have, a dependency of `ffmpeg`) and `speexdsp`?

**Comment by lrusak** [comment]
> So when PulseAudio says `--with-speex` it actually means "enable speexdsp"? What's the difference between [`speex`](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/audio/speex/package.mk) (which we already have, a dependency of `ffmpeg`) and `speexdsp`?

I only found this reference: https://www.linuxquestions.org/questions/slackware-14/speex-vs-speexdsp-4175564119/#post5479361

**Comment by MilhouseVH** [comment]
OK - just wanted to check we're not adding an unnecessary/duplicate package, it sounds like you're correct, thanks.

**Comment by lrusak** [comment]
and just for further clarity pulseaudio looks for speexdsp for both autotools and meson

https://github.com/pulseaudio/pulseaudio/blob/v13.0/configure.ac#L1193
https://github.com/pulseaudio/pulseaudio/blob/v13.0/meson.build#L651

**Comment by lrusak** [comment]
rebased on latest meson changes

**Pull request merged**
