### PR TITLE
[le92] kodi binary addons: update to latest Leia versions

### PR DESCRIPTION
**Pull request by HiassofT**
build tested for RPi4 and Generic

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Nice, I really look forward for `inputstream.adaptive` 2.4.3!

**Comment by dagwieers** [comment]
This is related to https://github.com/peak3d/inputstream.adaptive/issues/387

**Comment by dagwieers** [comment]
@HiassofT So we want to make an announcement for an add-on that requires **inputstream.adaptive** 2.4.3. Do you expect that this becomes available rather soon (in the next coming days) or are we looking at weeks?

I need to know if we announce it now (and indicate LE will get an update in X weeks) or delay the announcement with a few days.

**Comment by HiassofT** [comment]
@dagwieers I hope this can get in soon and addons pushed to our repo within the next couple of days. Already pinged @CvH on slack who takes care of most addon/release stuff.

**Comment by dagwieers** [comment]
@HiassofT That is perfect and my preferred path going forward. I will hold off doing any announcement until the updates become available. The **inputstream.adaptive** update for Leia is well-tested by the community (see https://github.com/peak3d/inputstream.adaptive/wiki/Test-results) and we are working on improving the process in the future. Thanks for your help!

**Comment by HiassofT** [comment]
@dagwieers thanks a lot for the info about inputstream.adaptive testing!

From my (quite limited) testing I can confirm that inputstream.adaptive seems to be working fine.

I only tested with youtube and netflix (these are the only addons with i.a. support that I have installed on my RPi4) but as they are amongst the most popular addons I guess we should be fine :-)

**Comment by dagwieers** [comment]
@HiassofT Famous last words :wink:

**Comment by HiassofT** [comment]
Even if something should go south: no big deal, we can fix it with another update. We are used to addons breaking all the time for various reasons :)

I can't remember having major issues with i.a. updates in the past couple of years (and I did test it quite frequently, even dev snapshots) so I'm quite confident this update will work, too (though it's a large one this time)

**Comment by HiassofT** [comment]
@dagwieers addon updates are now available in our repo

**Pull request merged**
