### PR TITLE
DVB patches AML

### PR DESCRIPTION
**Pull request by CvH**
that adds the WP2 dvb patches to the Odroid and WH and streamline the projects
- fixes building of mumudvb (that need dvb5 headers)

@kszaq @codesnake @Raybuntu objections ? (instead of adding it as patch at the projects merge at kernel?)

### CODE REVIEW

**Comment by kszaq** [comment]
Maybe it'd be better to put it in patches directory for all devices? https://github.com/kszaq/LibreELEC.tv/commit/6e059991c6cef3427826216512f53a0c41efd644

**Comment by codesnake** [comment]
I think it is better to merge that patch into kernel. It just removes AML dvb-core modifications they did for unknown reason.

**Comment by CvH** [comment]
both would be possible and good - no idea what you guys prefer :)

**Comment by chewitt** [comment]
We control the kernel so IMHO it makes sense to harmonise this stuff for all build projects there than to add more project patches.

**Comment by chewitt** [comment]
closing as implemented in kernel via https://github.com/LibreELEC/linux-amlogic/commit/20791e8ac60e7fb1fc5e4d99daf594b904367581

**Pull request closed without merging**
