### PR TITLE
linux: Update to 4.7 (WIP)

### PR DESCRIPTION
**Pull request by MilhouseVH**
Starting with 4.7-rc4. I'll update this PR as new release candidates appear, until eventually 4.7.0 is released and updated in this PR.

The following patches are now merged upstream in 4.7:
```
packages/linux/patches/4.7-rc4/linux-056-add_Adaptec_eHome_Infrared_Receiver.patch
packages/linux/patches/4.7-rc4/linux-063-xpad-add-3rdparty-controllers.patch
packages/linux/patches/4.7-rc4/linux-223-Fix-video-artifacts-with-tt-3600-s2-usb.patch
packages/linux/patches/4.7-rc4/linux-230-elgato-eyetv-sat-v3.patch
```
The following patch is no longer compatible - it may have been included in a different way, or needs to be updated, but currently doesn't apply:
```
projects/Generic/patches/linux/linux-030-BYT-CHT-SOC-audio-support.patch
```

### CODE REVIEW

**Comment by popcornmix** [comment]
Pi config options look fine for me. Only difference with raspbian kernel is I chose ``CONFIG_NMI_LOG_BUF_SHIFT=12`` but I'm happy with either setting.

**Comment by MilhouseVH** [comment]
`CONFIG_TRIM_UNUSED_KSYMS=y` breaks Generic, resulting in numerous unset symbols in various drivers:
```
[    8.869908] snd_hda_intel: Unknown symbol snd_hdac_bus_enter_link_reset (err 0)
[    8.869924] snd_hda_intel: Unknown symbol azx_probe_codecs (err 0)
[    8.869944] snd_hda_intel: Unknown symbol azx_init_streams (err 0)
[    8.869980] snd_hda_intel: Unknown symbol azx_stop_all_streams (err 0)
[    8.869988] snd_hda_intel: Unknown symbol snd_hdac_bus_free_stream_pages (err 0)
[    8.869995] snd_hda_intel: Unknown symbol snd_hdac_bus_exit (err 0)
...
[    8.957673] rt2800pci: Unknown symbol rt2x00mmio_uninitialize (err 0)
[    8.957686] rt2800pci: Unknown symbol rt2x00mac_sw_scan_complete (err 0)
...
[    9.515297] nvidia: Unknown symbol cpufreq_get (err 0)
[    9.515312] nvidia: Unknown symbol set_memory_uc (err 0)
[    9.515322] nvidia: Unknown symbol drm_open (err 0)
```
etc., and a non-functional xorg.

Since this seems to be a flakey setting I've disabled it on RPi/RPi2 too, even though they seemed fine without it (but maybe would fail later when loading overlays etc.).

With this change RPi, RPi2 and Generic (Revo3700/ION2) are all booting and apparently running normally with 4.7-rc4.

**Comment by MilhouseVH** [comment]
4.7-rc4 test build #0623x: [RPi](http://milhouse.libreelec.tv/builds/testing/RPi/LibreELEC-RPi.arm-8.0-Milhouse-20160624043249-%230623x-g9b3d478.tar), [RPi2](http://milhouse.libreelec.tv/builds/testing/RPi2/LibreELEC-RPi2.arm-8.0-Milhouse-20160624043248-%230623x-g9b3d478.tar), [Generic](http://milhouse.libreelec.tv/builds/testing/Generic/LibreELEC-Generic.x86_64-8.0-Milhouse-20160624043249-%230623x-g9b3d478.tar)

**Comment by piotrasd** [comment]
projects/Generic/patches/linux/linux-030-BYT-CHT-SOC-audio-support.patch

New patch will be available after relase final kernel 4.7 :( so on RC stage no update for now .

**Comment by MilhouseVH** [comment]
Updated to 4.7-rc5.

**Comment by MilhouseVH** [comment]
Updated to 4.7-rc6.

**Comment by MilhouseVH** [comment]
Bump RTL8812AU driver to fix hard lock on RPi2.

**Comment by islipfd19** [comment]
imx6 build me please

**Comment by MilhouseVH** [comment]
Updated to 4.7-rc7.

**Comment by MilhouseVH** [comment]
Updated to 4.7.0 release.

Will add updated RPi kernel commits and firmware once @popcornmix has had a chance to rebase the rpi-4.7.y branch.

**Comment by MilhouseVH** [comment]
Updated with RPi/RPi2 patches and firmware.

Mirror (web03) needs updating with new 4.7 source tarball and bcm2835 mkpkg in order for anyone to build - I don't have access.

I'll include this PR in my test builds (as I have been for the last month), I'll remove "Don't Merge" label on Wednesday assuming there are no issues.

**Comment by MilhouseVH** [comment]
Mirror updated with4.7 tarball and latest firmware.

@piotrasd Are there any 4.7 audio patches for Cherrytrail?

**Comment by lrusak** [comment]
The audio patches haven't been rebased yet. We can add them later.

how close are we to merging this?

**Comment by MilhouseVH** [comment]
> how close are we to merging this?

Personally I think it's ready to go - I see no point continuing with 4.6.x.

There is this conversation https://github.com/raspberrypi/linux/commit/3a4a43e690dc28627513bf0bc58514e1f5ed2830#comments - assuming clivem doesn't respond with any changes then I think we can merge as-is, otherwise I can force push (or if you've already merged I'll push another PR). I'd suggest waiting until Thursday to merge.

**Comment by MilhouseVH** [comment]
Forgot we need to install the new libbrcmEGL/libbrcmGLESv2 libraries with latest firmware. See https://github.com/raspberrypi/firmware/issues/625.

We create symbolic links for the old libraries to for backward compatibility.

**Comment by MilhouseVH** [comment]
Updated with fix for IR autorepeat - thanks @HiassofT

**Comment by MilhouseVH** [comment]
Updated with an i915/ Valley View patch that I've been using since #0520 and which may fixe some display problems.

That's pretty much the last of the commits I've been carrying around in my builds... this should be good to go now.

**Comment by lrusak** [comment]
@MilhouseVH can you update the date of the commits?
```
git rebase --ignore-date upstream/master
```

**Comment by MilhouseVH** [comment]
Done!

**Comment by piotrasd** [comment]
> @piotrasd Are there any 4.7 audio patches for Cherrytrail?

Not yet :( i will let you know

**Comment by MilhouseVH** [comment]
Kodi `libEGL`/`libGLESv2` build failures are fixed by #592.

**Pull request merged**
