### PR TITLE
linux: update to 5.15.y

### PR DESCRIPTION
**Pull request by heitbaum**
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.9
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.10
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.11
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.12
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.13
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.14

5.15.9 - 1 patches
5.15.10 - 42 patches
5.15.11 - 177 patches
5.15.12 - 128 patches
5.15.13 - 72 patches
5.15.14 - 72 patches

### log 
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-5.15.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-5.15.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/log/
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/5.15

### 5.15.14 - Build tested on all of:

```
PROJECT=Allwinner ARCH=arm DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H3 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H6 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX6 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX8 s/build linux
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy s/build linux
```

### 5.15.y Run tested on all of:
- Allwinner all - tested - 5.15.0 - jernejsk
- Allwinner H6 (Tanix TX6) - 5.15.4 - heitbaum
- Generic Generic (Intel TGL - NUC11) - 5.15.14-rc1 - heitbaum
- NXP iMX6 (Cubox-i4Pro) - 5.15.14-rc1 - heitbaum
- Rockchip RK3399pro (Rock Pi N10) - 5.15.4-rc1 - heitbaum
- RK all - tested - 5.15.0 - knaerzche
- Samsung Exynos (Hardkernel ODROID XU4) - 5.15.0 - heitbaum (video issue)
- Also tested on out of tree:
  - Allwinner D1 (NeZha) - 5.15.0 - heitbaum (no GPU)
  - Allwinner A20 (BananaPi) - 5.15.0 - heitbaum

### CODE REVIEW

**Comment by zhangn1985** [comment]
Allwinner D1 (NeZha) - 5.15.0 - heitbaum RISC-V?

**Comment by heitbaum** [comment]
> Allwinner D1 (NeZha) - 5.15.0 - heitbaum RISC-V?

It builds with my :dev branch now. Mostly small toolchain fixes.
It builds a full LE11 - but will not run “Kodi” because of the lack of 3D GPU.
I have ordered my JH7100 StarFive VisionFive, but this is an academic exercise too. No GPU on this either. So this is really just getting the plumbing correct. Some minor fixes in kodi codebase too.

Waiting for a JH7110 SBC or similar.

**Comment by eldersixpack13** [comment]
ping @heitbaum 

are aware of this script ?
https://git.kernel.org/pub/scm/linux/kernel/git/mricon/korg-helpers.git/tree/get-verified-tarball

**Comment by heitbaum** [comment]
> ping @heitbaum
> 
> are aware of this script ? https://git.kernel.org/pub/scm/linux/kernel/git/mricon/korg-helpers.git/tree/get-verified-tarball

I follow (most days) and contribute to lkml, as well as following the stable queue - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/5.15 - and have a compile job that builds the -rcX for the LE:master - for LE itself. 

For the kernel update itself e.g. https://github.com/LibreELEC/LibreELEC.tv/pull/5987/commits/0c889130fe08c1ee9482954342c488aa4e25e6a4 - it is just a matter of updating the version and the sha when the kernel is released (and after the build/run testing - esp. when there are conflicting / changes / newly included patches (replacing our previous backported upstream patches) - e.g. https://github.com/LibreELEC/LibreELEC.tv/pull/5987/commits/e1991fca615bf2b76e3ef84f7934d8c7ad6521bf)

**Comment by eldersixpack13** [comment]
> > ping @heitbaum
> > are aware of this script ? https://git.kernel.org/pub/scm/linux/kernel/git/mricon/korg-helpers.git/tree/get-verified-tarball
> 
> I follow (most days) and contribute to lkml, as well as following the stable queue - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/5.15 - and have a compile job that builds the -rcX for the LE:master - for LE itself.
> 
...

I know, I see you at stable kernel testing what I do too (from time to time).
I just thought it would be a benefit to have the kernels gpg verified for LE and there would be no need to hack up a script cause there is already one.
that's all.

**Comment by heitbaum** [comment]
> > > ping @heitbaum
> > > are aware of this script ? https://git.kernel.org/pub/scm/linux/kernel/git/mricon/korg-helpers.git/tree/get-verified-tarball
> > 
> > 
> > I follow (most days) and contribute to lkml, as well as following the stable queue - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/5.15 - and have a compile job that builds the -rcX for the LE:master - for LE itself.
> 
> ...
> 
> I know, I see you at stable kernel testing what I do too (from time to time). I just thought it would be a benefit to have the LE kernels GPG verified too and if so, there would be no need to hack up a script cause there is already one. that's all.

Good to have this as a mechanism too.

**Comment by MastaG** [comment]
I gave 5.15.12 a run on my XU4 running Fedora 35.
However it seems that the MFC video decoder is still broken.
This using Kodi Matrix from git with ffmpeg using v4l2_m2m for decoding.

**Comment by heitbaum** [comment]
> I gave 5.15.12 a run on my XU4 running Fedora 35.
> However it seems that the MFC video decoder is still broken.
> This using Kodi Matrix from git with ffmpeg using v4l2_m2m for decoding.

Same here. You are correct the code removed between kernel 5.4–>5.5 has yet to be added back into 5.x

**Comment by chewitt** [comment]
@MastaG XU4 was added to the build-system so Lakka had an upstream target to work with. LE use either needs a revert to the Linux 5.4 kernel which would be hard to justify since it's moving in the wrong direction, or (better) someone needs to work on reverting the incomplete reworking of the MFC driver to restore it's original more-capable state, or (best) reworking the bit-rotting patches to finish the rework. The latter two need someone with coding skills though :)

**Comment by MastaG** [comment]
I totally agree my friends.
Actually the last kernel that has working MFC would be 5.8 (or 5.9.)
I'm using 5.8 on my Fedora 35 image and MFC decoding still works fine.
There was a dedicated thread on the odroid forums regarding 5.10: https://forum.odroid.com/viewtopic.php?f=184&t=41300 but nobody got it working.
All other things still work though, e.g. audio and mali-midgard with wayland/opengles etc.. I can still run gnome shell on 5.15.

**Comment by chewitt** [comment]
@MastaG Do you know if anyone reached out to the Samsung maintainers regarding MFC breakage? .. can you do some git bisect legwork to confirm the breaking commit and when it occurs? (5.8 or 5.9). I don't have an XU4 with me at the moment, but if we can pinpoint the issue I will formally take it up with the kernel maintainers.

**Comment by heitbaum** [comment]
Tracking of 5.15 done. Next kernel update will be 5.16

**Review by CvH — APPROVED** [review]

**Pull request merged**
