### PR TITLE
libbpf update to 1.0.1 and patch v4l-utils to support build with libbpf 1.0.1 

### PR DESCRIPTION
**Pull request by heitbaum**
- v4l-utils: support build with libbpf 1.0.1
  - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018915
- libbpf: update to 1.0.1

https://git.linuxtv.org/v4l-utils.git/log/

### CODE REVIEW

**Comment by HiassofT** [comment]
A proposed upstream fix has been posted on linux-media:
https://lore.kernel.org/linux-media/20221101202528.27306-1-sudipm.mukherjee@gmail.com/T/

Please update the patch with a backport of the upstream fix when it's been merged

**Comment by heitbaum** [comment]
> A proposed upstream fix has been posted on linux-media: https://lore.kernel.org/linux-media/20221101202528.27306-1-sudipm.mukherjee@gmail.com/T/
> 
> Please update the patch with a backport of the upstream fix when it's been merged

Perfect - was expecting it - good to see it is in the queue now.

**Comment by heitbaum** [comment]
> A proposed upstream fix has been posted on linux-media: https://lore.kernel.org/linux-media/20221101202528.27306-1-sudipm.mukherjee@gmail.com/T/
> 
> Please update the patch with a backport of the upstream fix when it's been merged

Upstreamed patch now included - https://git.linuxtv.org/v4l-utils.git/commit/?id=dce0e3e1e4ea91d3e46098362a880371ec5afe1b

**Review by HiassofT — APPROVED** [review]
Thanks, runtime test on RPi4 was fine!

**Pull request merged**
