### PR TITLE
Inputstream.adaptive: include decrypter lib

### PR DESCRIPTION
**Pull request by Raybuntu**
Decrypter lib was missing in the version before.

### CODE REVIEW

**Comment by stefansaraev** [comment]
first. 97e6547 is an orphaned commit at peak3d/inputstream.adaptive (did he force pushed? did he have a reason to remove it?). having references to orphaned commits in your packages should not be allowed
second. are you allowed to distribute wv?

**Comment by Raybuntu** [comment]
@stefansaraev: You are right. It was my mistake. I've been looking into liberty-developers repo. Got confused with all the nick names he has. You guys can revert that then. Not sure what the license status of wv is.

**Comment by lrusak** [comment]
We don't include libwidevine. Users have to source that themself.

**Comment by stefansaraev** [comment]
be very careful when you deal with drm or soon content providers may knock at your door.. librelec is not random russian/chinese project with no names behind it

**Comment by Raybuntu** [comment]
Sure @stefansaraev. libssd_dev.so was included with the inputstream.mpd and I just tried to make it behave the same way again.

**Pull request merged**
