### PR TITLE
Don't define -DMINIMAL=ON for tini

### LINKED ISSUE #4541: [BUG] tini is misconfigured for docker-init
### Describe the bug
tini is configured with `-DMINIMAL=ON` what makes it unusable for docker
https://github.com/LibreELEC/LibreELEC.tv/blob/a709f0e43efe581c60b3aea3ee909d8ff3e5cb9c/packages/addons/addon-depends/tini/package.mk#L14

As a result, all containers that created with `docker run --init` return `exec -- failed: No such file or directory` error. When I googled, I found similar error on CentOS bugtracker: https://bugs.centos.org/view.php?id=15320

### To Reproduce
1. Create a container with `docker run --init`

### Informations
 - 9.2.3
 - RPi4

### PR DESCRIPTION
**Pull request by ilya-fedin**
Fixes #4541

Could that be backported to 9.2?

### CODE REVIEW

**Comment by mglae** [comment]
> Could that be backported to 9.2?

PR the backport including docker addon revision number and changelog update like in #4573. Addon updates are still possible.

**Review by mglae — APPROVED** [review]

**Comment by ilya-fedin** [comment]
> PR the backport including docker addon revision number and changelog update like in #4573.

Should I open a PR with backport only after this PR will be merged or right now?

**Comment by chewitt** [comment]
Now is fine. We'll tag is as a backport and merge it after this is merged. Please change/update the commit message to follow house style, e.g. `tini: don't define -DMINIMAL=ON`

**Comment by ilya-fedin** [comment]
thx, I've opened #4588

**Pull request merged**
