### PR TITLE
linux (RPi): update to 5.15.70

### PR DESCRIPTION
**Pull request by HiassofT**
Runtime tested on RPi3B+ and RPi4

### CODE REVIEW

**Review by CvH — APPROVED** [review]

**Comment by pretoriano80** [comment]
@HiassofT  which are the plans for LE11 kernel ,will remain on 5.xx branch or at some point will switch to 6.x  ?
Thanks and sorry for asking this here ,but i couldn't find a better place to ask about it .

**Comment by HiassofT** [comment]
@pretoriano80 my plan is to switch to kernel 6.0 as soon as 6.0 final is released.

Testing with 6.0-rc already looks very good here, only RPi2/3 USB driver is somewhat broken - see https://github.com/raspberrypi/linux/issues/5189

It's easy to workaround the USB issue though (by disabling FIQ) which I may just do in LE builds until the bug is fixed so it doesn't hold up the switch to 6.0

**Comment by pretoriano80** [comment]
Nice!You already have a test branch which is publicly available ?

**Comment by HiassofT** [comment]
I just rebased and pushed my changes here: https://github.com/HiassofT/LibreELEC.tv/tree/le11-kernel-6.0

**Comment by pretoriano80** [comment]
Thank you!Will test om my RPi4.

**Pull request merged**
