### PR TITLE
amlogic: bump to Linux 5.15.y and other misc. changes

### PR DESCRIPTION
**Pull request by chewitt**
This bumps Amlogic (GX) to Linux 5.15.y with the following notable changes:

- Switch bootloader/install to use Makefiles in amlogic-boot-fip sources
- Move emmctool to a package so it can be tweaked/reused with iMX6 and Exynos
- Support for Bananapi-M5, Radxa Zero, WeTek Hub/Core2/Play2 added
- Odroid N2/N2+ or C4/HC4 auto-select the correct dtb on boot via FDTDIR
- Alsa userspace confs have been greatly simplified (thanks @HiassofT)
- GXBB (S905) devices now handle 48KHz audio correctly (thanks @xdarklight)

Known / Continuing Issues:

- GXBB/GXL/GXM devices have an audio bug (loud staccato noise) which may randomly trigger on transitions between 2.0 and multi-channel output. It triggers particularly easily in the Kodi audio settings page and if TV/AVR volumes are at normal levels it can be a nasty surprise. There is an ongoing but slow-burning attempt to figure this problem out, but no Eureka moment yet. When it occurs fiddling with audio settings, e.g. switching audio output from HDMI to Analogue or toggling 'send low-noise' resets the audio card and stops it.

- Both AIU and AXG audio drivers have an issue with speaker placement. If you set the 'Analogue' PCM output in Kodi the alsa confs we are using remap channels to workaround the problem and correct placement. The driver maintainer has been notified but he has little time to investigate a proper fix right now. HDMI can be used as a pass-through audio source.

- FFMpeg needs love. K20 wants to use FFMpeg v4.4 and we need to align with v4l2_m2m changes made for Raspberry Pi (as in theory we will all share the same stateful codebase in the future) but right now @jc-kynesim branch is has become too Pi flavoured. Beyond a specific commit we lose video output, and before the specific commit we have no hardware decode. This causes a regression for GXBB and GXL devices which have older/slower CPUs and need acceleration. It's less of an issue for GXM and newer devices which can handle 1080p software decoding. I may try to create an alternative patch-set but the patches are hard to work with so hopefully the issue can be worked around soon. There is no progress on VDEC support upstream so apart from FFMpeg state, there are no improvements.

- To use FFMpeg at a specific commit we need to avoid the default v4l2-drmprime patches by adding more if/then/else complexity. Instead of doing that I've chosen to add different source configs for Amlogic and RPi. This duplicates PKG_URL etc. since RPi also uses the default v4.4 source (but with a large patch) but I think it improves config readability. Once more RPi patches are upstream and we bin X11 support (and everything uses V4L2 of some form) some proper simplification of the package.mk can be done. IMHO it would be easiest to just point RPi at JC's branch via githash while K20 is in a pre-Alpha state and save the effort of patch creation/updating, but I appreciate there are political reasons for RPi patches.

This PR supersedes #5821 and most of #5494 (the bit for Meson8 devices will be handled separately).

### CODE REVIEW

**Comment by heitbaum** [comment]
Successful builds of my dev tree `PROJECT=Amlogic ARCH=aarch64 DEVICE=AMLG12 UBOOT_SYSTEM=odroid-n2 make image` and against master
`PROJECT=Amlogic ARCH=aarch64 DEVICE= AMLGX UBOOT_SYSTEM=odroid-n2 make image` needed to fix #5923 (as byproduct of tidying up my build environment)

```
=== run tested on (my dev tree) ===
AMLG12.aarch64-devel-20211127031619-b18fdf7
Linux odroid 5.15.5 #1 SMP PREEMPT Sat Nov 27 03:24:44 UTC 2021 aarch64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:08b7599d63e063545e34a24bb17fc3738cd4dde7). Platform: Linux ARM 64-bit
Using Release Kodi x64
Kodi compiled 2021-11-27 by GCC 10.3.0 for Linux ARM 64-bit version 5.15.5 (331525)
Running on Amlogic Meson G12B (S922X) Hardkernel ODROID-N2Plus with LibreELEC (heitbaum): devel-20211127031619-b18fdf7 11.0, kernel: Linux ARM 64-bit version 5.15.5
FFmpeg version/source: 10.0.0-1340-gb18fdf7eb6
6 CPU cores available
ARM Features: Neon enabled
EGL_VENDOR = Mesa Project
GL_VERSION = OpenGL ES 3.1 Mesa 21.3.0
```

did have a weird error on first boot (after the update) powered off then on, and it booted fine. As a final note http://ix.io/3Ge9 is an dmesg error log for the Odroid N2 which had been running since 2021-08-19.

887F8B1A-5F6B-4914-B8B1-AD6B8DDFD867

**Review by heitbaum — APPROVED** [review]
GtG from my perspective. Run tested.

**Comment by chewitt** [comment]
Those splats are an ongoing phenomena that isn't specific to the kernel version or this PR. I'd guess something low-level is the problem, but that code is all closed source. I did add https://github.com/chewitt/linux/commit/56740c96cd3b1cab018041425813e7942fd7ac65 as this seems to reduce the ocurrence.

**Comment by heitbaum** [comment]
> Those splats are an ongoing phenomena that isn't specific to the kernel version or this PR. I'd guess something low-level is the problem, but that code is all closed source. I did add [chewitt/linux@56740c9](https://github.com/chewitt/linux/commit/56740c96cd3b1cab018041425813e7942fd7ac65) as this seems to reduce the ocurrence.

I hadn’t seen it before on the N2+ - but good to know.

**Pull request merged**
