### PR TITLE
meson: update to 0.57.0

### PR DESCRIPTION
**Pull request by heitbaum**
update from 0.56.0 (30 Oct 2020) to 0.56.2 (15 Feb 2021)
changelogs:
- https://github.com/mesonbuild/meson/milestone/55?closed=1
- https://github.com/mesonbuild/meson/milestone/56?closed=1
- https://github.com/mesonbuild/meson/milestone/54?closed=1

release notes:
- https://mesonbuild.com/Release-notes-for-0-57-0.html

### CODE REVIEW

**Comment by CvH** [comment]
0.56.2 is released
@150balbes mentioned that it breaks ARM native build

```
ARCH=arm (nativ build)
glib 2.67.2 + meson 0.55.3 = working
glib 2.67.2 + meson 0.56.2 = not working
```

```
Compiler for C supports arguments -Wno-duplicated-branches: YES
Checking if "frexp works" with dependency -lm runs: DID NOT COMPILE
Checking if "frexpl works" with dependency -lm runs: DID NOT COMPILE
Checking if "frexpl prototype can be re-listed" compiles: YES
../glib/gnulib/meson.build:309:2: ERROR: Problem encountered: frexpl() is missing or broken beyond repair, and we have nothing to replace it with
```

**Comment by heitbaum** [comment]
In reading https://github.com/mesonbuild/meson/milestone/56?closed=1 (0.56.3) and https://github.com/mesonbuild/meson/milestone/54 (0.57.0) I don’t this the fix is there.

**Comment by heitbaum** [comment]
Reading the commit logs. Maybe one of the October 02 commits. https://github.com/mesonbuild/meson/compare/0.55.3...0.56.0

**Comment by heitbaum** [comment]
> 0.56.2 is released
I have rebased but should hold until we figure out to revert to 0.55.x, 0.56.x or 0.57.x

**Comment by 150balbes** [comment]
I checked the native build in ARCH=aarch64 mode with meson versions 0.56.0 \ 0.56.2 and glib 2.67.2. Clean build runs without errors. 
But the ARCH=arm build gives an error and only works if  roll back meson to version 0.53.1 and glib 2.67.2

**Comment by heitbaum** [comment]
Superseded by #5276 - fix identified in 0.57.1

**Pull request closed without merging**
