### PR TITLE
RTL8189FS: new driver package

### PR DESCRIPTION
**Pull request by adamg-xda**
Compiled/Tested against TX3 Pro (S905)

Needed for #2254

### CODE REVIEW

**Comment by CGarces** [comment]
Hi @adamg-xda 
If is used only for aml, consider use https://github.com/khadas/android_hardware_wifi_realtek_drivers_8189ftv
See https://github.com/kszaq/LibreELEC.tv/blob/libreelec-8.2/packages/linux-drivers/amlogic/RTL8189FS-aml/package.mk

In any case, if someone consider that driver is needed I don't have any problem to port it to 4.x kernels.

**Comment by adamg-xda** [comment]
It seems rather messy to use a gh repo that was meant for Android, I know the product.mk can be adjusted for it but I think it would be better to maintain our own repo for the driver. We can pull in the changes from that one at a later date, please keep an eye on the following PR, https://github.com/LibreELEC/LibreELEC.tv/pull/2254 thanks

**Comment by CvH** [comment]
@adamg-xda was the closing of this pr intended ?

**Comment by adamg-xda** [comment]
@CvH yes I have moved to #2254

**Comment by CGarces** [comment]
@adamg-xda I have changed the repository to use the newest version. Don't change the PKG_VERSION yet, I'll make some changes and send you the correct PKG_VERSION and SHA on 26 Nov.

**Comment by adamg-xda** [comment]
@CGarces have you just overwritten the whole master branch you had up?

**Comment by adamg-xda** [comment]
This is ready for merge.

**Comment by CGarces** [comment]
Hi.

As I said in previous comments, some patches are needed in order to compile with newer kernels. I'll do some work tomorrow, please don't merge.

The current version compile with 4.4.97 but I'll fail for 4.11 and probably also for 4.7 & 4.8

See the build matrix [there](https://travis-ci.org/CGarces/rtl8189FS/builds/307202257).

Also note that maybe you should remove c3f3cb6b68e497a2828313fc63bf693e9bd29163 from #2254

**Comment by CGarces** [comment]
Done.
The original code was not compiling for 4.6 for x86 and >=4.11 for all architectures.

Now is patched and [works](https://travis-ci.org/CGarces/rtl8189FS/builds/307440733?utm_source=github_status&utm_medium=notification) for all versions (tested on x86)

As a sort-term solution you can use my repository, but I'm planing to send all my stuff to https://github.com/jwrdegoede/rtl8189ES_linux/tree/rtl8189fs that is the [recomended repo](http://linux-sunxi.org/Wifi#RTL8189FTV) for the linux-sunxi comunity, instead of mantain my own fork.

Ping @jernejsk maybe will use this on his builds

**Comment by MilhouseVH** [comment]
The jwrdegoede repo might be better than most Realtek one-man band repositories that stop being updated after a few months once the owner loses interest - from [here](https://github.com/jwrdegoede/rtl8189ES_linux/pull/7#issuecomment-342165261):

> I've actually sort of handed over maintenance of this to others
(whom I've given commit rights), but pressing the merge button was
easy :)

Of course it could also turn into a free-for-all leading to reduced quality if too many people have commit access but a group effort is a refreshing change when almost all Realtek repos are solo efforts. If only more repo owners would do the same there'd be fewer pointless forks!

**Comment by CGarces** [comment]
Fully agree with you @MilhouseVH, I'm not planing to made another fork, I'll send a few patches to jwrdegoede that are missing and maybe send a separate PR to update to v4.3.24.6_20019.20161107.

BTW @adamg-xda don't need to wait until I finish the merge, just point the package to https://github.com/jwrdegoede/rtl8189ES_linux/commit/04b44d437b20f28ba83fcaecc0bdab7f7647fd11 and use that version. Is older than the one used by @kszaq (v4.3.24_15589.20151023) but better maintained for x86 and newer kernels

**Comment by Kwiboo** [comment]
@CGarces Rockchip have a newer v4.3.24.8_22657.20170607 at https://github.com/rockchip-linux/kernel/tree/release-4.4/drivers/net/wireless/rockchip_wlan/rtl8189fs if that is of interest

**Comment by adamg-xda** [comment]
@Kwiboo that whole tree is very interesting as it has the drivers for other chips that are in some S905 devices, I will test the sources later on tonight and see if they work, I think the best option would be for my to create a separate repo to maintain the driver as downloading the whole linux source tree wouldn't really be appropriate.

**Comment by CGarces** [comment]
@adamg-xda, of course we need a out-of-tree repository, but from now just point to https://github.com/jwrdegoede/rtl8189ES_linux/commit/04b44d437b20f28ba83fcaecc0bdab7f7647fd11 and give me some time (one week) to send the corresponding PR.

**Comment by adamg-xda** [comment]
@CGarces I think it would be best if we fork the repo, we can then add each other as collaborators so as to speed up updates, rather than waiting for someone to accept PR's.

**Comment by MilhouseVH** [comment]
Collaborating with (and pushing changes to) an "upstream" repo would be preferential to creating yet another Realtek fork.

**Comment by adamg-xda** [comment]
@CGarces there has been much discussion in great length on slack RE: realtek drivers, at present I think the consensus is to just keep this in its current state as it is only the S905/X that is using it. If there is any support added for other devices with the same chip in the future that utilizes a 4.x kernel then we could revisit it at a later date and move to a more unified driver but there is no need for it at present. This PR is holding up pushing through my other PR and hampering getting S905 into LE main branch.

**Pull request merged**
