### PR TITLE
Separate x11 and GBM Generic devices

### PR DESCRIPTION
**Pull request by smp79**
Build and runtime tested with no issues.

### CODE REVIEW

**Comment by CvH** [comment]
Any idea what kind of HW (generation) is needed ?
My not recent Intel Haswell GT1 GPU is showing Kodi quite nice (awesome loading times :) ) but I can't play anything regardless if I choose hw decoding or sw.

```17:29:55.335 T:698      INFO <general>: VideoPlayer::OpenFile: pvr://channels/tv/Alle%20Kan%c3%a4le/pvr.hts_1761998026.pvr
17:29:55.336 T:861      INFO <general>: Creating InputStream
17:29:55.424 T:861      INFO <general>: Creating Demuxer
17:29:56.666 T:861      INFO <general>: Opening stream: 1007 source: 256
17:29:56.666 T:861      INFO <general>: Whitelist search for: width: 720, height: 576, fps: 25.000, 3D: false
17:29:56.667 T:861      INFO <general>: Display resolution ADJUST : 1920x1080 @ 50.000000 Hz (31) (weight: -32402449147896069023919505408.000)
17:29:56.674 T:861   WARNING <general>: OpenStream - Unsupported stream 1007. Stream disabled.
17:29:56.674 T:861      INFO <general>: Opening stream: 1008 source: 256
17:29:56.674 T:861      INFO <general>: Finding audio codec for: 86016
17:29:56.676 T:861      INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder mp2
17:29:56.676 T:861      INFO <general>: Creating audio thread
17:29:56.676 T:863      INFO <general>: running thread: CVideoPlayerAudio::Process()
17:29:56.676 T:861      INFO <general>: Opening stream: 1001 source: 256
17:29:56.676 T:861      INFO <general>: waiting for teletext data thread to exit
17:29:56.676 T:861      INFO <general>: Creating teletext data thread
17:29:56.677 T:864      INFO <general>: running thread: CDVDTeletextData
17:29:56.680 T:861      INFO <general>: Opening stream: 1007 source: 256
17:29:56.680 T:861      INFO <general>: Whitelist search for: width: 720, height: 576, fps: 25.000, 3D: false
17:29:56.680 T:861      INFO <general>: Display resolution ADJUST : 1920x1080 @ 50.000000 Hz (31) (weight: -32402449147896069023919505408.000)
17:29:56.685 T:861      INFO <general>: Creating video codec with codec id: 2
17:29:56.685 T:861      INFO <general>: CDVDVideoCodecDRMPRIME::Open - using decoder MPEG-2 video
17:29:56.685 T:861      INFO <general>: Creating video thread
17:29:56.685 T:861      INFO <general>: Opening stream: 1008 source: 256
17:29:56.685 T:861      INFO <general>: Finding audio codec for: 86016
17:29:56.685 T:861      INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder mp2
17:29:56.685 T:861      INFO <general>: Opening stream: 1001 source: 256
17:29:56.685 T:866      INFO <general>: running thread: video_thread
17:29:56.685 T:866      INFO <general>: CVideoPlayerVideo - Stillframe left, switching to normal playback
17:29:56.686 T:866     ERROR <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: Operation not permitted (-1)
17:29:56.687 T:866     ERROR <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: Operation not permitted (-1)
.....
```

**Comment by smp79** [comment]
> Any idea what kind of HW (generation) is needed ?

I only tested GBM builds on Intel Gemini Lake and AMD Vega3 APU (Athlon 200GE), they work fine.

**Comment by CvH** [comment]
@smp79 did you tried to enable drm-prime at the kodi options ? causes not playing video/crash for me
fix for it http://ix.io/2tGe (kernel 5.8 based) mentioned by @jernejsk 

- overall drm-prime (needed for HDR and post processing) is currently SW only (with fix)
- if drm-prime is disabled HW acceleration works well
- deinterlacing SW filters BOB and Deinterlace (yadif) are not working, the other HW filters work well

updated build are here https://cvh.libreelec.tv/test/gbm/

**Comment by smp79** [comment]
@CvH 
It's the ffmpeg issue.
Those patches are needed for drmprime to work - https://github.com/Kwiboo/LibreELEC.tv/commit/7bfeca81561bc644897a332910a9984914af7a31
https://github.com/Kwiboo/LibreELEC.tv/commit/accd42abca4eaed61e012cf1c68f02bb91621980

A build with a working hw drmprime and a working HDR (on Gemini Lake):
https://www.dropbox.com/s/3etxmw8dla441yw/LibreELEC-Generic.x86_64-9.80-devel-20200722221052-38764c8.img.gz?dl=1

**Comment by Kwiboo** [comment]
> Those patches are needed for drmprime to work - [Kwiboo@7bfeca8](https://github.com/Kwiboo/LibreELEC.tv/commit/7bfeca81561bc644897a332910a9984914af7a31)
> [Kwiboo@accd42a](https://github.com/Kwiboo/LibreELEC.tv/commit/accd42abca4eaed61e012cf1c68f02bb91621980)

I have pushed a new kodi branch with what I hope is all the drmprime vaapi related patches hidden in those and related commits to https://github.com/Kwiboo/xbmc/commits/drmprime-vaapi-2020, but nothing I have compile or runtime tested so far.

And the updated ffmpeg branch is located at https://github.com/Kwiboo/FFmpeg/commits/drmprime-format-4.3, same here nothing I have runtime tested.

**Comment by CvH** [comment]
@smp79 
do you have an git branch with the required changes ?
If I add the patches etc I have no playback at drm-prime.

**Comment by smp79** [comment]
@CvH 
No, I cherry-picked some ffmpeg and kodi patches from Kwiboo's [work-in-progress](https://github.com/Kwiboo/LibreELEC.tv/commits/work-in-progress) branch to make drmprime/HDR work. 

@Kwiboo 
> but nothing I have compile or runtime tested so far

Thanks, I just built from those branches, everything seem to work fine (except deinterlacing).
I suppose deinterlacing for drmprime is not ready yet?

**Comment by CvH** [comment]
@smp79 I added some stuff https://github.com/CvH/LibreELEC.tv/commits/10.0/generic-gbm-v2
(Ignore the kernel 5.8 bump)

1.  drm-prime with vaapi patches (hacky stuff is missing for HDR)
2.  x11 renamed to Generic so the normal name of the generic build is kept (not build tested yet)
3.  update between gbm and "normal" generic version is possible
4.  kernel fix to support drm-prime
5.  addons use the Generic builds

- so drm-prime works now with vaapi hw acceleration (likely amd too)
- menu is still a bit slugish,compared to x11 @Kwiboo mentioned that they changed the govenor for the gpu to performance at RK to fix that (not really a option for Generic)
- deinterlacing is working even its shown as "none active", no idea what is actually used, maybe lowend BOB or something

build
https://cvh.libreelec.tv/test/gbm/

**Comment by smp79** [comment]
> * menu is still a bit slugish

It may help to run the GPU at max frequency. I have this in autostart.sh (750 Mhz is the max for Intel J4105):
**echo 750 > /sys/devices/pci0000:00/0000:00:02.0/drm/card0/gt_min_freq_mhz**

**Comment by smp79** [comment]
@CvH 
Do we really need CONFIG_DMABUF_HEAPS kernel options? It works fine without them.

**Comment by jernejsk** [comment]
@smp79 yes but I already enabled it in Linux 5.8 bump. It's needed for codecs which are not HW decoded.

**Comment by CvH** [comment]
@smp79 are you able to watch something for ~30-40min in a row ? I have crashes every 30-40min if I watch something.

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/lib/kodi/kodi.bin --standalone -fs'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f253cc18f68 in ?? () from /usr/lib/dri/i965_dri.so
```

**Comment by smp79** [comment]
@CvH no crashes here.

**Comment by smp79** [comment]
>x11 renamed to Generic so the normal name of the generic build is kept (not build tested yet)

I build tested it, no issues.

**Comment by lrusak** [comment]
I'd rather not have this extra project. You simply need to change 4 lines in the Generic options to allow building with kodi-gbm.

This also include a bunch of patches that are not merged upstream and will require maintenance.

The patches in this PR allow using vaapi with DRM prime which is not needed (and experimental at the moment). Vaapi works already with kodi-gbm without DRM prime.

If anyone wants to build LE with kodi-gbm I recommended doing it via the Generic build with a custom ~/.LibreELEC/options file.

Also note that kodi-gbm doesn't support the Nvidia binary driver so there is no point in including that either.

**Comment by smp79** [comment]
I removed the DRM prime patches. 
As far as I understand x11 is not going anywhere anytime soon, so I thought that there should be a bit better way to build Generic GBM images rather than having a custom options file.

**Comment by lrusak** [comment]
I'm going to close this as I don't think we should support another Generic project.

If people want to build with GBM support on Generic just add the following to `~/.libreelec/options`
```
OPENGL="no"
OPENGLES="mesa"
DISPLAYSERVER="no"
KODIPLAYER_DRIVER="mesa"
```

**Pull request closed without merging**
