### PR TITLE
dvb updates for 5.2

### PR DESCRIPTION
**Pull request by CvH**
- updated CC to 5.2 base, updated dvb-latest to ~5.3ish base
- hauppauge stuff is finally upstream
- added support for m88ds3103b (very very widely used device)

not yet tested against 5.2 kernel

### CODE REVIEW

**Comment by MilhouseVH** [comment]
@cvh can you revert https://github.com/LibreELEC/LibreELEC.tv/pull/3533/commits/6230c0852a1047ad7ba428f1ee456dfb8e90af46 in this PR, as I had to disable `DRIVER_ADDONS_SUPPORT` in 5.2.0 for RPi and Generic. Thanks.

**Comment by CvH** [comment]
Added some workarounds, sadly I found no maintainable solution to stop build pci/e drivers for USB Only devices. RPi2 should work now :)

**Comment by MilhouseVH** [comment]
Thanks @cvh. We'll have to ponder this a bit. :)

Can you add a commit that re-enables `DRIVER_ADDONS_SUPPORT` support for Generic and RPi (basically, revert https://github.com/LibreELEC/LibreELEC.tv/commit/6230c0852a1047ad7ba428f1ee456dfb8e90af46).

**Comment by CvH** [comment]
done

**Pull request merged**
