### PR TITLE
linux: update to 5.15

### PR DESCRIPTION
**Pull request by heitbaum**
### REVIEW
- review RTL drivers and the IPX removal - (still waiting on upstream PRs to be committed)
  - https://github.com/aircrack-ng/rtl8812au
  - https://github.com/lwfinger/rtl8192du
- systemd - update
  - systemd: update to 247.10
    - v247.10 (published - and dependent PR as #5824)
    - v249.5 (published - with Jinja2 - update as a future PR)

### KNOWN ERROR (race condition)
- **iMX8** + u-boot 2021.10
  - `stat: cannot stat 'arch/arm/dts/imx8mq-evk.dtb': No such file or directory `
  - `  MKIMAGE u-boot.itb `
  - `u-boot.itb.tmp: Warning (unit_address_vs_reg): /images/uboot@1: node has a unit name, but no reg property `
  - ` u-boot.itb.tmp: Warning (unit_address_vs_reg): /images/fdt@1: node has a unit name, but no reg property `
  - ` u-boot.itb.tmp: Warning (unit_address_vs_reg): /images/atf@1: node has a unit name, but no reg property `
  - ` u-boot.itb.tmp: Warning (unit_address_vs_reg): /configurations/config@1: node has a unit name, but no reg property `
  - `./tools/mkimage: verify_header failed for FIT Image support with exit code 1 `
  - ` make[1]: *** [Makefile:1442: u-boot.itb] Error 1 `
  - ` make[1]: *** Deleting file 'u-boot.itb'`

### Main changes between 5.14 and 5.15 in the LE11 :master
- **ntfs3: new NTFS driver for 5.15**
  - https://www.kernel.org/doc/html/latest//filesystems/ntfs3.html
  - https://lore.kernel.org/lkml/20200918162204.3706029-1-almaz.alexandrovich@paragon-software.com/
  - https://lore.kernel.org/lkml/aa4aa155-b9b2-9099-b7a2-349d8d9d8fbd@paragon-software.com/
  - Raised as a separate PR #5838 
- **IPX: net: Remove the ipx network layer header files**
  - https://lore.kernel.org/lkml/20210813120803.101-1-caihuoqing@baidu.com/
- **ARC4 set as module**

### DONE

- **Generic-legacy** Fix nvidia legacy
  - update from `drm/msm: drop drm_gem_object_put_locked()` to `drop drm_gem_object_put()`

**5.15 build tested on all of:**
```
PROJECT=Allwinner ARCH=arm DEVICE=H3 make image
PROJECT=Allwinner ARCH=arm DEVICE=H6 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 make image
PROJECT=NXP ARCH=arm DEVICE=iMX6 make image
u-boot ERRORING — PROJECT=NXP ARCH=arm DEVICE=iMX8 make image
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard make image
PROJECT=Samsung ARCH=arm DEVICE=Exynos make image
PROJECT=Generic ARCH=x86_64 DEVICE=Generic make image
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy make image
```

5.15 **run tested** against **:master** on all of:

- Allwinner all - tested - 5.15.0 - jernejsk
- Allwinner H6 (Tanix TX6) - 5.15.0 - heitbaum
- Generic Generic (Intel TGL - NUC11) - 5.15.0 - heitbaum
- NXP iMX6 (Cubox-i4Pro) - 5.15.0 - heitbaum
- Rockchip RK3399pro (Rock Pi N10) - 5.15.0 - heitbaum
- RK all - tested - 5.15.0 - knaerzche
- Samsung Exynos (Hardkernel ODROID XU4) - 5.15.0 - heitbaum
- Also tested on out of tree:
  - Allwinner D1 (NeZha) - 5.15.0 - heitbaum
  - Allwinner A20 (BananaPi) - 5.15.0 - heitbaum

log - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-5.15.y

### CODE REVIEW

**Comment by CGarces** [comment]
Please bump rtl8192eu and rtl8812au.
rtl8192eu is already patched for 5.15 and rtl8812au has one patch already on upstream.
I'll send the patches to upstream.

Note. Maybe is time to remove some of this drivers and start using rtl8xxxu

**Comment by knaerzche** [comment]
> Rebased to include #5749 rk patches
Thanks.

As you might have noticed not all patches from linux-0001-rockchip-from-5.15.patch made it in 5.15 - see: https://git.kernel.org/pub/scm/linux/kernel/git/mmind/linux-rockchip.git/tag/?h=v5.16-rockchip-dts64-1
Could you rename the file with the remaining patches to linux-0001-rockchip-from-5.16.patch?

**Comment by heitbaum** [comment]
Patch https://github.com/LibreELEC/LibreELEC.tv/pull/5738/commits/fbc7fb4509ef333feb236ff935461ed2c4a2e3a0 removed now that it is upstream and will be in 5.15 final https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3a4347d82efdfcc5465b3ed37616426989182915

**Comment by heitbaum** [comment]
Moved NTFS3 patch as separate PR #5824 - otherwise this PR is ready

Current known issues are:
- iMX8 + u-boot 2021.10
- https://github.com/aircrack-ng/rtl8812au - update to upstream release (once PR accepted)
- https://github.com/lwfinger/rtl8192du - update to upstream release (once PR accepted)

**Comment by jernejsk** [comment]
NXP iMX8 U-Boot issue is independent of this PR. It's a race condition and it already affects current master on my laptop. If you add -j1 to last make command in u-boot package, you'll be able to reproduce it without this PR.

**Comment by heitbaum** [comment]
> NXP iMX8 U-Boot issue is independent of this PR. It's a race condition and it already affects current master on my laptop. If you add -j1 to last make command in u-boot package, you'll be able to reproduce it without this PR.
> 
> EDIT: Ah, this is not the major problem, I'll look into that, but anyway, it's not Linux related.

Thanks @jernejsk for check this for me - I thought I was going mad.

**Comment by knaerzche** [comment]
> Patch 4447f30 removed now that it is upstream and will be in 5.15 final https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3a4347d82efdfcc5465b3ed37616426989182915

Thanks.
Just re-checked with 5.15.0: RK is (still) gtg

**Comment by jernejsk** [comment]
AW part looks good

**Review by knaerzche — APPROVED** [review]

**Comment by zhangn1985** [comment]
I find big performance drop after upgrade to 5.15.
I natively build on orangepi-pc, and the source code is on USB driver, the build time is almost doubled compare with 5.14.

do you also find same thing?

**Comment by jernejsk** [comment]
I don't use USB at all and Kodi works fine. I suggest you bisect kernel to figure out which commit is at fault.

**Pull request merged**
