### PR TITLE
cleanup game.libretro.mame20xx and ppsspp

### PR DESCRIPTION
**Pull request by CvH**
was deleted upstream

### CODE REVIEW

**Comment by CvH** [comment]
ppsspp was added, libretro.ppsspp was removed

**Comment by lrusak** [comment]
what?

https://github.com/libretro/ppsspp
https://github.com/libretro/mame2000-libretro
https://github.com/libretro/mame2003-libretro
https://github.com/libretro/mame2010-libretro
https://github.com/libretro/mame2014-libretro

**Comment by CvH** [comment]
@lrusak the kodi addons are missing, do we need to keep the libretro stuff if we can't use it?

**Comment by lrusak** [comment]
https://github.com/kodi-game/game.libretro.ppsspp

The upstream never existed for mame20**, I simply added the source code here.

**Comment by CvH** [comment]
Ah now get what is/was wrong, all `PKG_SITE` urls are wrong (404) - so I got the impression the it was dropped.

**Pull request closed without merging**
