### PR TITLE
new package exfat-utilities

### PR DESCRIPTION
**Pull request by adamg-xda**

### CODE REVIEW

**Comment by lrusak** [comment]
Can you explain why this is better?

**Comment by adamg-xda** [comment]
udevil can have issues with mounting usb drives formatted with exfat

this package also does not rely on fuse for mounting

**Comment by MilhouseVH** [comment]
> udevil can have issues with mounting usb drives formatted with exfat

Can you be more specific? What kind of issues?

**Comment by adamg-xda** [comment]
If a drive is uncleanly unmounted it will not mount within LE, this driver does not just cover exfat but all fat formats

**Comment by adamg-xda** [comment]
Generally the error received is as follows

**Comment by chewitt** [comment]
@MilhouseVH can you please pick for testing.

**Comment by MilhouseVH** [comment]
OK, will include from Thursday night.

**Comment by HiassofT** [comment]
Looking at the commit history of the driver repo https://github.com/dorimanx/exfat-nofuse/commits/master and the arch user repository info page (using the same driver) https://aur.archlinux.org/packages/exfat-dkms-git/ it looks like this out-of-tree driver will be breaking with every other kernel release.

Also there seem to be several competing forks of the driver so this very much looks like we would be going down the same rabbit hole as with the out-of-tree realtek wlan drivers.

In addition to that none of the major linux distributions use this driver, they all use the fuse exfat driver.

So I'd strongly advise against merging this PR, if there are issues with fuse-exfat they should be analyzed and fixed.

**Comment by chewitt** [comment]
@adamg-xda I'm going to close the PR as this doesn't appear to be quite as shiny and interesting as first thought. In addition to @HiassofT comments above, testing @MilhouseVH did earlier shows no clear performance advantage; see https://pastebin.com/raw/rrESHtGG. Thanks for making the effort to submit though.

**Comment by adamg-xda** [comment]
I have seen 100% cpu utilization on an RPI2 when attempting to read large
files but thanks for taking the time to review.

**Pull request closed without merging**
