### PR TITLE
media-driver: enable VAAPI deinterlacers at X11

### PR DESCRIPTION
**Pull request by mglae**
Tested on Gemini Lake

### CODE REVIEW

**Comment by lrusak** [comment]
does this fix a bug?

**Comment by mglae** [comment]
If not having VAAPI deinterlacers in Generic X11 is a bug - yes.

**Comment by lrusak** [comment]
> If not having VAAPI deinterlacers in Generic X11 is a bug - yes.

Might be worth noting that in the PR then

**Comment by CvH** [comment]
@mglae is it due the latest bump or something we don't have for a long time?

**Comment by heitbaum** [comment]
I have just tried a85a93d694 and the results are poor - jittery.

This is my system
```
 18:22:31 up  6:01,  load average: 1.46, 2.76, 2.30
Generic.x86_64-devel-20201219005711-9d802bb
Linux LibreELEC 5.10.1 #1 SMP Wed Dec 16 13:02:48 UTC 2020 x86_64 GNU/Linux
Starting Kodi (19.0-BETA2 (18.9.821) Git:19.0b2-Matrix). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2020-12-15 by GCC 10.2.0 for Linux x86 64-bit version 5.10.0 (330240)
Running on LibreELEC (community): devel-20201219005711-9d802bb 9.80, kernel: Linux x86 64-bit version 5.10.1
FFmpeg version/source: 4.3.1-Kodi
Host CPU: Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz, 4 cores available
[    0.000000] DMI:  /NUC6i5SYB, BIOS SYSKLi35.86A.0073.2020.0909.1625 09/09/2020
```


It does fix this in the logs though....
```
2020-12-19 18:36:55.638 T:5034    ERROR <general>: VAAPI output: Postproc preinit failed
2020-12-19 18:36:55.704 T:5034    ERROR <general>: VAAPI/vpp vaCreateConfig error: the requested VAProfile is not supported (12)
```

Jitter - http://ix.io/2IEK (with a85a93d694)
No jitter - http://ix.io/2IEL (without a85a93d694)

See #4732

**Comment by mglae** [comment]
@CvH Full featured build is recommended in readme. It's something we don't have for a long time, maybe because of the not obvios BYPASS_MEDIA_ULT parameter needed for cross compiling.

@heitbaum  Please enable debug logging when posting logs (hide overlay with advancedsettings.xml). Mpeg2 HW accelerated codec seems to be available now. Use the video context menu to check if different deinterlacers do change the jittery. "Deinterlace" should have been used before.

To test the older intel drivers create /storage/.config/kodi.conf:
```
MESA_LOADER_DRIVER_OVERRIDE=i965
LIBVA_DRIVER_NAME=i965
```
and restart kodi.

But my recommendation is to disable mpeg2 acceleration in linux on any AMD or Intel graphic because of the poor quality.

**Comment by heitbaum** [comment]
> But my recommendation is to disable mpeg2 acceleration in linux on any AMD or Intel graphic because of the poor quality.

@mglae firstly thanks for finding the 4732 log filling bug. Will do a full test over the next few days, with the mpeg2 media and the full set of combinations. I will also test on my NUC10i7FNH. Next couple of weeks are to get my new N2+, VIM3 going with LE10, and I’ll with the NUC10.

**Comment by lrusak** [comment]
I think the issue is related to non-free features and that's why I didn't enable it in the first place.

It would be wise to look into this and decide if we should enable non-free. Issues like redistribution and licensing should be looked at.

**Comment by CvH** [comment]
isn't nonfree that stuff that requires the intel-media-sdk ?

**Comment by mglae** [comment]
> isn't nonfree that stuff that requires the intel-media-sdk ?

Can be. At least there is no conditional licensing:

```
## License

The Intel(R) Media Driver for VAAPI is distributed under the MIT license with
portions covered under the BSD 3-clause "New" or "Revised" License.
You may obtain a copy of the License at [MIT](https://opensource.org/licenses/MIT) & [BSD-3-Clause](https://opensource.org/licenses/BSD-3-Clause)
```

**Comment by smp79** [comment]
High quality MADI/MCDI deinterlacing doesn't work with this. The deinterlacing options are now available and Kodi reports that "vaapi-mcdi" is used but only BOB is actually used even when "VAAPI - motion compensated" is selected. Tested on Gemini Lake, Generic GBM.

**Comment by lrusak** [comment]
Seems like this will still need some work upstream anyways https://github.com/intel/media-driver/issues/804

In the mean time BOB deinterlacing should still work.

**Comment by mglae** [comment]
In addition the YADIF "Deinterlace" deinterlacer can be selected.

In contrast to my statement I found the MPEG2 HW acceleration having a good quality, although I did not test the critical sources real DVD from drive and DVD ISO via SMB network.

**Comment by CvH** [comment]
increases filesize from ~8mb to 38mb of iHD_drv_video.so

**Comment by mglae** [comment]
SYSTEM enlargement: 4509696

**Comment by CvH** [comment]
any news ?

**Comment by mglae** [comment]
Not without public testing in some nightlies  ;-)

**Comment by CvH** [comment]
There is a comparison list of what we miss if we build not standard https://github.com/intel/media-driver#video-processing-features .
We are basically missing all processing features for kabylake and older.

By default the nonfree version is build at the media-driver, used by Arch and Alpine for example. 
We build the free version and basically misses all the good stuff and just implements the basic versions.

```
PKG_CMAKE_OPTS_TARGET="-DBUILD_CMRTLIB=OFF \
                       -DMEDIA_RUN_TEST_SUITE=OFF \
                       -Wno-dev"
```

From my perspective we should ship the full version instead of the stripped down one.

**Comment by smp79** [comment]
What are the benefits for of this media-driver for LE compared to i965-va-driver? i965-va-driver is small and works perfectly fine.

**Comment by CvH** [comment]
intel-vaapi-driver just supports the old generations (till broadwell?) and media-driver starts with broadwell

**Comment by smp79** [comment]
No, intel-vaapi-driver works fine on modern platforms.

**Comment by lrusak** [comment]
> No, intel-vaapi-driver works fine on modern platforms. I'm using it on Gemini Lake. Media-driver is huge and buggy, deinterlacing (still!) does not work properly.

Gemini lake is not modern anymore 😊

**Comment by smp79** [comment]
It will remain modern until Gen12 stuff actually hits the retail stores :)

> just supports the old generations (till broadwell?)

That was actually i965 vs Gallium3D mesa drivers, nothing to do with intel-vaapi-driver.

**Comment by lrusak** [comment]
You can always set the env variable to use the intel-vaapi-driver on your system

**Comment by smp79** [comment]
> Gemini lake is not modern anymore

Yeah, intel-vaapi-driver does not work on Tiger Lake. 

> LibreELEC:~ # vainfo
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva error: /usr/lib/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

media-driver is ok:

> LibreELEC:~ # vainfo
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.4.5 (d8b557f424)
vainfo: Supported profile and entrypoints
VAProfileNone : VAEntrypointVideoProc
VAProfileNone : VAEntrypointStats
VAProfileMPEG2Simple : VAEntrypointVLD
VAProfileMPEG2Main : VAEntrypointVLD
VAProfileH264Main : VAEntrypointVLD
VAProfileH264Main : VAEntrypointEncSliceLP
VAProfileH264High : VAEntrypointVLD
VAProfileH264High : VAEntrypointEncSliceLP
VAProfileJPEGBaseline : VAEntrypointVLD
VAProfileJPEGBaseline : VAEntrypointEncPicture
VAProfileH264ConstrainedBaseline: VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
VAProfileVP8Version0_3 : VAEntrypointVLD
VAProfileHEVCMain : VAEntrypointVLD
VAProfileHEVCMain : VAEntrypointEncSliceLP
VAProfileHEVCMain10 : VAEntrypointVLD
VAProfileHEVCMain10 : VAEntrypointEncSliceLP
VAProfileVP9Profile0 : VAEntrypointVLD
VAProfileVP9Profile1 : VAEntrypointVLD
VAProfileVP9Profile2 : VAEntrypointVLD
VAProfileVP9Profile3 : VAEntrypointVLD
VAProfileHEVCMain12 : VAEntrypointVLD
VAProfileHEVCMain422_10 : VAEntrypointVLD
VAProfileHEVCMain422_12 : VAEntrypointVLD
VAProfileHEVCMain444 : VAEntrypointVLD
VAProfileHEVCMain444 : VAEntrypointEncSliceLP
VAProfileHEVCMain444_10 : VAEntrypointVLD
VAProfileHEVCMain444_10 : VAEntrypointEncSliceLP
VAProfileHEVCMain444_12 : VAEntrypointVLD
VAProfileHEVCSccMain : VAEntrypointVLD
VAProfileHEVCSccMain : VAEntrypointEncSliceLP
VAProfileHEVCSccMain10 : VAEntrypointVLD
VAProfileHEVCSccMain10 : VAEntrypointEncSliceLP
VAProfileHEVCSccMain444 : VAEntrypointVLD
VAProfileHEVCSccMain444 : VAEntrypointEncSliceLP
VAProfileAV1Profile0 : VAEntrypointVLD
VAProfileHEVCSccMain444_10 : VAEntrypointVLD
VAProfileHEVCSccMain444_10 : VAEntrypointEncSliceLP

**Comment by smp79** [comment]
Can this now be merged?
MCDI is [finally fixed](https://github.com/intel/media-driver/pull/1162) and working!

**Comment by SupervisedThinking** [comment]
@smp79 isn't some package bump to the latest version https://github.com/intel/media-driver/releases/tag/intel-media-21.1.2 & an added [patch](https://patch-diff.githubusercontent.com/raw/intel/media-driver/pull/1162.patch) necessary to make it work?

**Comment by smp79** [comment]
I tested the patch with the current ver. 20.4.5, it applies and works fine.
IMO this PR can be merged as it is and the DI fix could be dealt with later (as a patch or as a package bump).

**Comment by SupervisedThinking** [comment]
You've got a test video or something?

**Comment by smp79** [comment]
You mean interlaced video? I got a satellite DVB tuner with tons of available interlaced h.264 channels.

**Comment by SupervisedThinking** [comment]
@smp79 I had vaapi-mcdi & tested different options, had not artifacts or something

**Comment by smp79** [comment]
You mean you tested with this PR but without a patch?
Without that patch vaapi-mcdi is actually vaapi-bob.

**Comment by SupervisedThinking** [comment]
I combined https://github.com/LibreELEC/LibreELEC.tv/pull/4771#issuecomment-802219137 & https://github.com/LibreELEC/LibreELEC.tv/pull/4771

**Comment by heitbaum** [comment]
I have built this PR - 88414751e4fa8427562535e546020895ed68556d
And here are my results - http://ix.io/2Tvo and http://ix.io/2Tvp

```
=== tested on ===
Generic.x86_64-devel-20210320091304-8cdbaf2
Linux nuc11 5.10.25-rc1 #1 SMP Sat Mar 20 09:13:28 UTC 2021 x86_64 GNU/Linux
Starting Kodi (19.0 (19.0.0) Git:19.0-Matrix). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2021-03-14 by GCC 10.2.0 for Linux x86 64-bit version 5.10.23 (330263)
Running on LibreELEC (heitbaum): devel-20210320091304-8cdbaf2 10.0, kernel: Linux x86 64-bit version 5.10.25-rc1
FFmpeg version/source: 4.3.1-Kodi
Host CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 8 cores available
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0037.2021.0106.1527 01/06/2021
CRenderSystemGL::InitRenderSystem - Version: 4.6 (Core Profile) Mesa 21.1.0-devel, Major: 4, Minor: 6
GL_RENDERER = Mesa Intel(R) Xe Graphics (TGL GT2)
GL_VERSION = 4.6 (Core Profile) Mesa 21.1.0-devel
```

**Comment by SupervisedThinking** [comment]
@mglae could you update your PR according to https://github.com/SupervisedThinking/LibreELEC-RR/commit/5bf2d2c14950167ae514226f8e89810caacb3811

Tested on SKL/APL & as @heitbaum stated MPEG2 HW acceleration works too

**Comment by SupervisedThinking** [comment]
@CvH LE11?

https://forum.libreelec.tv/thread/23735-issues-on-beta-1-with-x86/?postID=152986#post152986

**Review by CvH — APPROVED** [review]

**Pull request merged**
