### PR TITLE
linux (RPi): update to 4.18.10

### PR DESCRIPTION
**Pull request by MilhouseVH**
~Dependent on dvb update #2872.~

4.18.4 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.18.4
4.18.5 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.18.5
4.18.6 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.18.6
4.18.7 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.18.7
4.18.8 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.18.8
4.18.9 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.18.9

### CODE REVIEW

**Comment by 5schatten** [comment]
@MilhouseVH 
Could you rebase these patches against latest upstream code? I'm not sure which kernel conf options are really needed and which not :-)

**Comment by 5schatten** [comment]
Hmmm I tried to cherry pick your patches but once I try to apply the conf updates it fails for me.

git fetch https://github.com/MilhouseVH/LibreELEC.tv.git le90_linux4180_rpi && git cherry-pick [...]

**Comment by MilhouseVH** [comment]
You're most likely cherry-picking the commits in the wrong order.

Unfortunately github.com lists the commits in this PR in a random, totally incorrect and meaningless order, but git will - eventually - merge them in the correct order. So if you cherry-pick these commits in the order they are listed in this PR then eventually you'll get to a point where the commits no longer apply.

It's a known issue with github as I notified them about it back in March, and while they confirmed the issue they have no plans to fix it. At the time it was only the commits listed in the "timeline" (Conversation tab) that were listed incorrectly, while the commits in the "Commits" tab were listed correctly (ie. Date and Commit ID order, which is expected behaviour), but now it appears that the commits in both tabs are listed incorrectly in some random and broken order. Sigh.

This is the correct order of the commits obtained from my local git (oldest commit first):
```
1a0ba75 linux (RPi): update to linux-4.18
7a4072e linux (RPi): config options for 4.18
1f6ac02 linux (RPi): config - enable Realtek PCI/USB card readers
384ddbb linux (RPi): update Ouya patch
cdc8257 linux (RPi): drop spinelplus - needs fixing
025a7ad linux (RPi): update to linux-4.18.4
93197aa linux (RPi): enable CMA debugging
52c33f2 linux (RPi): update to linux-4.18.5
```

Since github.com is fundamentally broken, you're probably better off using:
```
wget -q https://github.com/LibreELEC/LibreELEC.tv/pull/2913.patch -O- | git am
```

**Comment by 5schatten** [comment]
Well thx I didn't knew this and normally it works fine when I cherry pick your or other stuff. :-)

**Comment by MilhouseVH** [comment]
> This patch for example is for kernel 4.14.62 and not .67?

There was no config change when the 4.14.y kernel bumped to 4.14..67, so the version number didn't change.

**Comment by MilhouseVH** [comment]
> and normally it works fine when I cherry pick your or other stuff.

That's probably been by pure luck, as you can no longer trust the commit order being shown to you by github.com. This problem also makes reviewing changes that bit more difficult, as a contributor might push commits in a logical order only for github.com to list the same commits in a totally random and illogical order.

**Comment by 5schatten** [comment]
Reordering & temp. disabling my commit https://github.com/5schatten/LibreELEC.tv/commit/721ef57e61c855be26a60a9a225a75b6ed1d5bfd#diff-81a3d8b40013a38a0ceee90507ad3524 was the solution. I need this module for midi sound in dosbox & unfortunately this broke the commit.

**Comment by HiassofT** [comment]
IMO it's best to avoid the github web interface completely, for testing Milhouse PRs (which I do quite often) I just added his repo to the remotes
`git remote add milhouse https://github.com/MilhouseVH/LibreELEC.tv.git`

Then it's easy to fetch his updates
`git fetch milhouse`

And merge them into my local working tree
`git merge milhouse/le90_linux4180_rpi`

or check logs to get commit ids for cherry picking -
`
git log --oneline milhouse/le90_linux4180_rpi`

**Comment by MilhouseVH** [comment]
In March I sent github.com a [test script](https://pastebin.com/raw/mYeiSdbm) which pushes commits in a logical and chronological order, only for github.com to then list the same commits in an apparently random order:

https://github.com/MilhouseVH/dgnd4000/pull/2

(please ignore the `config.sh: set target margin of 70` commit - that's just noise which I could fix but would require rebasing)

In the PR, the commits on the "Conversation" tab are listed in an incorrect (and frankly confusing and useless) order, while on the "Commits" tab they're listed in the correct order. If you were to attempt to cherry-pick commits based on the commit order from the "Conversation" tab then you'd run into problems with the first commit ("linux: update to linux-4.14.17"), as it's not actually the first commit at all.

I'm aware of [this Github FAQ](https://help.github.com/articles/why-are-my-commits-in-the-wrong-order how), however as can be seen from the test script the commits have not been rebased at all, and github.com is listing the commits incorrectly (and inconsistently) from the very first push.

Go figure. I'd have said this was a pretty fundamental issue, and in fact wasn't an issue prior to March.

**Comment by 5schatten** [comment]
Finally-> builds & runs fine on my RPi3

**Pull request merged**
