### PR TITLE
Atom Baytrail and CherryTrail HDMI audio support

### PR DESCRIPTION
**Pull request by chewitt**
add HDMI audio support for Atom Baytrail and CherryTrail using rebased kernel 4.6.x patch from Pierre-Louis Bossart  - thanks @piotrasd

### CODE REVIEW

**Comment by chewitt** [comment]
@MilhouseVH can you pick for testing please

**Comment by MilhouseVH** [comment]
This is currently in my builds - do we know if it works as expected?

**Comment by chewitt** [comment]
@piotrasd - Can you confirm all is good with a current Milhouse build?

**Comment by piotrasd** [comment]
ok please send me link

**Comment by lrusak** [comment]
@piotrasd http://milhouse.libreelec.tv/builds/master/Generic/LibreELEC-Generic.x86_64-8.0-Milhouse-20160605214320-%230605-ga682b4f.tar

see, http://forum.kodi.tv/showthread.php?tid=269815&pid=2352502#pid2352502

**Pull request merged**
