### PR TITLE
tinc: only build source

### PR DESCRIPTION
**Pull request by awiouy**

### CODE REVIEW

**Comment by vpeter4** [comment]
No need to use a patch just a
```
make_target() {
  make SUBDIRS=src
}

makeinstall_target() {
  $MAKEINSTALL SUBDIRS=src
  make install DESTDIR=$INSTALL SUBDIRS=src
}
```

**Comment by awiouy** [comment]
Hey! @vpeter4 long time no see. I hope you are fine.
Thanks for the hint, I will use it.

**Comment by CvH** [comment]
@awiouy if you pushed the changes I start an jenkins build (I can't recreate that buildissue here)

**Comment by awiouy** [comment]
@CvH pushed

**Comment by CvH** [comment]
@awiouy jenkins reported success

**Comment by vpeter4** [comment]
make_target() function should be removed too.

**Pull request merged**
