### PR TITLE
moonlight: update addon

### PR DESCRIPTION
**Pull request by CvH**
updates to latest version
- should fix some major problems reported (waiting for tester feedback)
- added changelog.txt :trollface:
- reworded description to fit our "standards"

### CODE REVIEW

**Comment by chewitt** [comment]
Since we're doing changes - 'dead' is the upstream author of moonlight not the original author or maintainer of our add-on, and we're exposing his email address in Kodi GUI. Can we replace that with whoever originally created this, or if we're bold assign to LE team.

**Comment by chewitt** [comment]
Also add $PKG_VERSION to the description so it's visible in Kodi GUI

**Comment by CvH** [comment]
no idea what is/was the intention of that - I drop that and the version is also fixed

**Comment by lrusak** [comment]
LGTM

**Pull request merged**
