### PR TITLE
linux: update to linux-4.12.4 [Backport]

### PR DESCRIPTION
**Pull request by MilhouseVH**
### *** Generic Only ***

This is basically a combination of #1629 and #1798 in order to bring the libreelec-8.2 branch on to 4.12.y, considering that 4.11.12 is now [EOL](https://lwn.net/Articles/728526/) and will receive no further updates.

This PR does NOT include the three media_build updates from #1629, nor does it include "bye bye lirc_xbox" #1812, although CONFIG_LIRC_STAGING is now disabled as this is using the exact same x86_64 config as master.

This includes the correction of `CONFIG_AIO=y` which was unintentionally disabled by the 4.11.8 bump (needed by Samba).

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I've added the latest `media_build` package from master (`2017-06-20-rpi`, as in #1629) along with #1812 which drops the XBOX controller support from Generic and also from `media_build`.

Since we still support LIRC_STAGING in older kernels I'm not entirely sure what effect this will have - we'll still be applying the XBOX controller patch to the 4.9.y kernel for RPi/RPi2.

Pinging @CvH and @HiassofT as the respective `media_build` and `LIRC` experts, for review.

This PR does build and boot on RPi, RPi2 and Generic (including ION2 based hardware), so no obvious issues. IR is working normally on my Skylake NUC (built-in RC6). WiFi and BT seems to be working (using the built-in WiFi/BT on NUC and RPi3).

**Comment by HiassofT** [comment]
Bumping media_build will break lirc_rpi, like before :)

lirc_rpi is built from the kernel source and is not ABI compatible to the lirc_dev module built by media_build (functions are removed there and struct lirc_driver is changed).

Easiest and safest thing to do is disable media_build for generic. The upstream drivers from 4.12 are about the same as the ones from the 2017-04-17 media_build, you'll only loose the additional "crazycat" drivers.

**Comment by HiassofT** [comment]
Another alternative would be to create a separate media_build package for generic, which then can be newer than the default one. As we'll probably have similar issues in about 3 months when 4.12 is EOLed that could be a good strategy.

**Comment by CvH** [comment]
We have several options, non is overall nice due the outdated out of tree driver that is commonly in use (we had reached an agreement to make an hard cut with 9.0 and remove that stuff).

current options from my pov:
1. don't build MB for RPix
2. create an separate MB package for the RPi (as all other platforms are still working with latest)
3. drop the outdated driver "today" (tbh doesn't sound that nice at an x.2 rls)
4. add [this patch](https://github.com/LibreELEC/LibreELEC.tv/pull/1780/commits/5718091a4219e255e4e47060beac2a31aab67d48) that reverts the removal of the ancient lirc code - looks like AML meson-ir has also an depending at this code and if I understood @Raybuntu right that patch worked for him

btw I really don't care about xbox_lirc driver - if it works it is just a bonus ;)

**Comment by HiassofT** [comment]
Options 1 and 2 would be fine with me.

I strongly advise against adding more patches which partially revert the mediabuild bumpages. This is turning into a holy mess and just brings us further into untested territory - lirc_dev is also used by the drivers from the rc subsystem /which are built from the crazycat media tree).

**Comment by HiassofT** [comment]
I have to add that I'm not happy at all with a general media build bump in the 8.2 tree.

We should now be stabilizing the 8.2 tree and IMO there need to be really strong arguments to warrant major version bumps at this stage.

I don't see these arguments for media build. Concerning that the bump has been included in regular milhouse builds for only one week and is known to break RPi the general risk for other, so far unnoticed, problems is just too high.

As only kernel 4.12/generic has problems with the current 8.2 media_build that should be fixed, not the other way round.

**Comment by CvH** [comment]
There is always the question if we want to keep an old unstable media_tree (where the dvb/rc drivers located) or do we want to update to a recent one that include fixes and new devices (and ofc possible new bugs). 4.9 has numerous problems with DVB drivers all over the place (also with plain kernel) so I would be rather happy to go ahead as far as possible. As per definition (or at least how they support it) media_tree is always unstable, there is sadly nothing like an stable media_tree (also not at lts kernels etc). If I could choose i would rather go with 4.8 media_tree instead of 4.9.

**Comment by HiassofT** [comment]
The big questions are: which issues will be fixed by the media build bump, and which new issues does it introduce? Or will plain kernel 4.12 without media_build work better or equally well (maybe plus the additional crazycat drivers that are not in official media_tree)?

**Comment by MilhouseVH** [comment]
I thought I added a comment a few hours ago but obviously not...

This PR no longer builds the `media_build` package for Generic, and has re-enabled LIRC and XBOX support.

This means there's nothing to block this PR, and the issue of building the `media_build` package for Generic can be addressed separately.

**Comment by CvH** [comment]
@MilhouseVH FYI `This PR no longer builds the media_build package for Generic This PR no longer builds the media_build package for Generic` 
that is the obvious problem due that commit https://github.com/LibreELEC/LibreELEC.tv/commit/9d5429d2bd0279c2e81b7557d2fd7e2d227446dd that reverted the mb back to an pre 4.12 version that is highly unlikely to work with 4.12 - this was expected and already told at slack :) 

In preparation for 4.12 the package was bumped before to allow testing and find bugs (only lacks
[this patch](https://github.com/LibreELEC/LibreELEC.tv/pull/1780/commits/5718091a4219e255e4e47060beac2a31aab67d48) that restore thee needed functions for the lirc_rpi) and should work platform independent.

**Comment by MilhouseVH** [comment]
I simply disabled `media_build` as per the discussion above to allow this PR to go in (as when I test built this kernel it failed with current `media_build` and needed the `media_build` bump which then affects other projects) and then any `media_build` tweaking can take place without my involvement (as frankly I find `media_build` very confusing!)

**Comment by chewitt** [comment]
Closing this PR as 4.11 will be the kernel for 8.2 releases, even if EOL now. Bumping to 4.12+ incurs too much additional change that needs to be properly worked through and figured out. Thx.

**Pull request closed without merging**
