### PR TITLE
mariadb: set DEFAULT_SSL_VERIFY_SERVER_CERT to off and update addon (3)

### PR DESCRIPTION
**Pull request by vpeter4**
similar to https://github.com/LibreELEC/LibreELEC.tv/pull/8970
fixes https://forum.libreelec.tv/thread/28662-le12-mariadb-can-t-connect/?postID=192997

### CODE REVIEW

**Comment by heitbaum** [comment]
I’ve had a couple looks at this. And it doesn’t seem to work (that is the upstream option)
The ssl verify is still set to true after the CMAKE setting is set. 

And the client seems to connect fine when using versions of client where `ssl-verify-server-cert` is set to `FALSE`. To get the mariadb client (11.4.2) binary to work in all scenarios to the LE mariadbd server (11.4.2) requires `—skip-ssl-verify-server-cert`

```
.kodi/addons/service.mariadb/bin/mariadb -h 192.168.0.6 
ERROR 2026 (HY000): TLS/SSL error: self-signed certificate

.kodi/addons/service.mariadb/bin/mariadb -h 192.168.0.6 --skip-ssl-verify-server-cert -u kodi -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7
Server version: 11.4.2-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```


```
This is on the LE 11.4.2 mariadb addon
./mariadb -? | grep ssl-verify-server-cert
  --ssl-verify-server-cert 
                      (Defaults to on; use --skip-ssl-verify-server-cert to disable.)
ssl-verify-server-cert            TRUE
```

connections from Ubuntu 24.04 (to the server with/without) the setting works regardless.

```
mariadb -u kodi -h 192.168.0.6 -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 11
Server version: 11.4.2-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>

$ mariadb -? | grep verify  --ssl-verify-server-cert 
ssl-verify-server-cert            FALSE

$ mariadb --version
mariadb  Ver 15.1 Distrib 10.11.8-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

**Comment by vpeter4** [comment]
> And it doesn’t seem to work (that is the upstream option)
It works on same LE version. But I didn't test cross use (LE11 + LE12).

**Comment by heitbaum** [comment]
So I don’t know what this make option actually changes in the build. Unfortunately I think the change made in upstream Mariadb is flawed as we have seen on the mariadb-connector-c when the trying to connect without SSL.

it does seem that the addon from the server does enable the SSL server. I haven’t compared the 10.x on demand ssl behaviour.

from 24.04
```
mariadb -u kodi -h 192.168.0.6 -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 12
Server version: 11.4.2-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> \s
--------------
mariadb  Ver 15.1 Distrib 10.11.8-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

Connection id:          12
Current database:       
Current user:           kodi@172.17.0.3
SSL:                    Cipher in use is TLS_AES_256_GCM_SHA384
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         11.4.2-MariaDB MariaDB Server
Protocol version:       10
Connection:             192.168.0.6 via TCP/IP
Server characterset:    utf8mb3
Db     characterset:    utf8mb3
Client characterset:    utf8mb3
Conn.  characterset:    utf8mb3
TCP port:               3306
Uptime:                 17 min 47 sec

Threads: 2  Questions: 15  Slow queries: 0  Opens: 17  Open tables: 10  Queries per second avg: 0.014
--------------

MariaDB [(none)]> 
```
from LE
```
.kodi/addons/service.mariadb/bin/mariadb -h 192.168.0.6 --skip-ssl-verify-server-cert -u kodi --s
sl -v -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 11
Server version: 11.4.2-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Reading history-file /storage/.mariadb_history
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>  \s
--------------
.kodi/addons/service.mariadb/bin/mariadb from 11.4.2-MariaDB, client 15.2 for Linux (x86_64) using readline 5.1

Connection id:          11
Current database:       
Current user:           kodi@nuc12
SSL:                    Cipher in use is TLS_AES_256_GCM_SHA384, cert is UNKNOWN
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         11.4.2-MariaDB MariaDB Server
Protocol version:       10
Connection:             192.168.0.6 via TCP/IP
Server characterset:    utf8mb3
Db     characterset:    utf8mb3
Client characterset:    utf8mb3
Conn.  characterset:    utf8mb3
TCP port:               3306
Uptime:                 17 min 3 sec

Threads: 1  Questions: 12  Slow queries: 0  Opens: 17  Open tables: 10  Queries per second avg: 0.011
--------------

MariaDB [(none)]> 
```

**Comment by vpeter4** [comment]
> So I don’t know what this make option actually changes in the build.

It does exactly the same as in _mariadb-connector-c_. Meaning it makes addon working again. But as I said I only tested LE 12 + addon from there. And it worked.

**Comment by heitbaum** [comment]
> > And it doesn’t seem to work (that is the upstream option)
> > It works on same LE version. But I didn't test cross use (LE11 + LE12).

127.0.0.1 seems to work all the time not encountering the TLS verify problem. 

```
.kodi/addons/service.mariadb/bin/mariadb -h 127.0.0.1 -u kodi -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 14
Server version: 11.4.2-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> \s
--------------
.kodi/addons/service.mariadb/bin/mariadb from 11.4.2-MariaDB, client 15.2 for Linux (x86_64) using readline 5.1

Connection id:          14
Current database:       
Current user:           kodi@localhost
SSL:                    Cipher in use is TLS_AES_256_GCM_SHA384, cert is OK
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         11.4.2-MariaDB MariaDB Server
Protocol version:       10
Connection:             127.0.0.1 via TCP/IP
Server characterset:    utf8mb3
Db     characterset:    utf8mb3
Client characterset:    utf8mb3
Conn.  characterset:    utf8mb3
TCP port:               3306
Uptime:                 27 min 58 sec

Threads: 2  Questions: 19  Slow queries: 0  Opens: 17  Open tables: 10  Queries per second avg: 0.011
--------------

MariaDB [(none)]>
```

**Comment by heitbaum** [comment]
> > So I don’t know what this make option actually changes in the build.
> 
> It does exactly the same as in _mariadb-connector-c_. Meaning it makes addon working again. But as I said I only tested LE 12 + addon from there. And it worked.

I have the addon working - as shown in the logs above (using the currently published - service.mariadb v12.80.0.2 - one) without this PR. So I’m confused?

**Comment by vpeter4** [comment]
I have to correct myself: Obviously I was testing only on master because there is this issue. And this PR is also for master.
But problem is also on LE12 because of addon bump: https://forum.libreelec.tv/thread/28662-le12-mariadb-can-t-connect/?postID=192974#post192974

**Comment by vpeter4** [comment]
I tried again LE master + Kodi Piers patch and seems to be working this time. Maybe there was some other change somewhere.
But I'm 100% sure is didn't work with a LE state at a time PR was send. I would not send PR if everything were working.

**Pull request closed without merging**
