### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by lrusak**
most of these are trivial maintenance updates.

busybox is the biggest update, but nothing new has been enabled in the configs.

Just building a clean image now with these changes

### CODE REVIEW

**Comment by lrusak** [comment]
Everything built ok

**Comment by MilhouseVH** [comment]
Thanks. I'll clean build overnight and include this in the #0721 build.

**Comment by lrusak** [comment]
@escalade I didn't have such a problem, I also selected N for all the new options.

**Comment by MilhouseVH** [comment]
I built RPi, RPi2 and Generic without any issues.

**Comment by lrusak** [comment]
Merge?

**Comment by MilhouseVH** [comment]
Any particular rush? It's just gone into a "nightly" (my test builds) so I'd rather see this tested for 1-2 days before merging (assuming there's no negative reports etc.)

**Comment by MilhouseVH** [comment]
Got a problem report: http://forum.kodi.tv/showthread.php?tid=269815&pid=2379814#pid2379814

Since build [#0721](http://forum.kodi.tv/showthread.php?tid=269815&pid=2378620#pid2378620) (which is when I first included this PR - a clean build) the Chromium add-on no longer works.

Running Chromium from the command line results in the following error:
```
NUC:~ # chromium
/storage/.kodi/addons/browser.chromium/bin/chromium.bin: symbol lookup error: /storage/.kodi/addons/browser.chromium/bin/chromium.bin: undefined symbol: png_set_longjmp_fn
```

In build [#0720](http://forum.kodi.tv/showthread.php?tid=269815&pid=2377976#pid2377976), Chromium works normally.


`libpng-1.6.23` appears to include the `png_set_longjmp_fn` function/symbol. `libpng` isn't being built shared, and Chromium is using a static version of `libpng` so in theory bumping `libpng` shouldn't have affected Chromium.

However, `libfreetype.so.6.12.3` (build #0720) includes a reference to `png_set_longjmp_fn`, but there is no such reference in `libfreetype.so.6.12.5` (build #0721), and Chromium is dynamically linked to `libfreetype.so.6`, so that might be the reason.

`libfreetype` doesn't appear to be a pacakge dependency for Chromium, when it probably should be.

Ideas? Rebuilding Chromium against the updated libfreetype might work... or the build might fail due to the missing symbol.

**Comment by MilhouseVH** [comment]
Copying `libfreetype.so.6.12.3` (from build #0720) to `/storage/.kodi/addons/browser.chromium/lib/libfreetype.so.6` allows Chromium to start successfully in build #0721, so it definitely looks like the updated `libfreetype.so.6.12.5` is the issue.

**Comment by MilhouseVH** [comment]
Looking at the `freetype` build directory without this PR:

```
neil@nm-linux:~/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/freetype-2.6.3$ readelf -s ./.x86_64-libreelec-linux-gnu/.libs/libfreetype.so.6.12.3 | grep png_set_longjmp_fn
   341: 000000000002c344   172 FUNC    GLOBAL DEFAULT   11 png_set_longjmp_fn
  1505: 000000000002c344   172 FUNC    GLOBAL DEFAULT   11 png_set_longjmp_fn
neil@nm-linux:~/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/freetype-2.6.3$ readelf -s ./.install_pkg/usr/lib/libfreetype.so.6.12.3 | grep png_set_longjmp_fn
   341: 000000000002c344   172 FUNC    GLOBAL DEFAULT   11 png_set_longjmp_fn
```

and now with this PR:

```
neil@nm-linux:~/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/freetype-2.6.5$ readelf -s ./.x86_64-libreelec-linux-gnu/.libs/libfreetype.so.6.12.5 | grep png_set_longjmp_fn
  1008: 000000000001f898   120 FUNC    LOCAL  HIDDEN    11 png_set_longjmp_fn.constp
neil@nm-linux:~/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/freetype-2.6.5$ readelf -s ./.install_pkg/usr/lib/libfreetype.so.6.12.5 | grep png_set_longjmp_fn
```

**Comment by lrusak** [comment]
I'll just drop the freetype update for now until I have to to build and test chromium

**Comment by lrusak** [comment]
done

**Comment by MilhouseVH** [comment]
Thanks Chromium works again.

**Pull request merged**
