### PR TITLE
Allwinner: H6: Temporar disable HS-DDR mode for eMMC

### PR DESCRIPTION
**Pull request by jernejsk**
Seems that HS-DDR mode breaks boot on some boards. Disable it until it is fixed.

/cc @clementperon

### CODE REVIEW

**Comment by clementperon** [comment]
The commit log is not correct but the patch is fine :+1:

**Review by clementperon — APPROVED** [review]

**Comment by clementperon** [comment]
@jernejsk we could drop the beelink gs1 specific patch no ?

**Comment by jernejsk** [comment]
yeah, we could

**Comment by jernejsk** [comment]
done

**Review by clementperon — APPROVED** [review]

**Review by chewitt — APPROVED** [review]

**Pull request merged**
