### PR TITLE
cleanup initramfs build, drop support for kernel modules in initramfs

### PR DESCRIPTION
**Pull request by HiassofT**
In order to support kernel modules in initramfs we had to jump through a lot of hoops - build kernel modules before kernel image, kick-off initramfs build inside linux target build etc.

As it turned out, the only user of that feature was uvesafb support - which is only needed to get the nice libreelec spash image during boot on x86 PCs booted in legacy BIOS/non-UEFI mode with Nvidia cards using the proprietary Nvidia driver. As that's a very niche issue the huge effort to support that is not warranted.

With kernel module support in initramfs removed we can drop a lot of the old cruft ~~and build initramfs as a normal linux target dependency which should help with parallel building~~

### CODE REVIEW

**Comment by kszaq** [comment]
Clean build works fine here for Amlogic mainline. :+1:

**Comment by HiassofT** [comment]
local tests (RPi2 and Generic) were fine, too, I've dropped the draft status

**Comment by HiassofT** [comment]
I had to drop the initramfs dependency in linux's PKG_DEPENDS_TARGET and revert back to the old way of building initramfs - now moved from make_target to pre_make_target, though as that broke clean building of addons.

The problem with addon build (actually any scripts/build kicked off manually) is that this doesn't install dependencies (as what's happening when running scripts/image) but only builds them. We won't get an initramfs.cpio though if initramfs is just built, so the `scripts/install initramfs` call is needed for now as we currently have no ppssibility in the buildsystem to express such a dependency.

**Comment by kszaq** [comment]
@HiassofT Would pointing to `initramfs` directory instead of cpio archive work?
https://github.com/torvalds/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/usr/Kconfig#L10-L16

**Pull request merged**
