### PR TITLE
attr: fix copying attr includes

### PR DESCRIPTION
**Pull request by rellla**
The includes are located in the attr subdir, so use it.

### CODE REVIEW

**Comment by heitbaum** [comment]
Definitely needs fixing but the Makefile does a sed of EXPORT to extern during header install. So PR should be reworked to incorporate. I did a quick test by commenting out the make install override and the below was the outcome.

```
$ find build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/.libreelec-package
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/etc
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/etc/xattr.conf
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/bin
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/bin/getfattr
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/bin/setfattr
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/bin/attr
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/lib
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/lib/libattr.la
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/lib/pkgconfig
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/lib/pkgconfig/libattr.pc
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/lib/libattr.a
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/include
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/include/attr
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/include/attr/libattr.h
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/include/attr/attributes.h
build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/attr-2.5.2/usr/include/attr/error_context.h
```

**Comment by rellla** [comment]
Changed the patch, so the sed is done on the header files before copying them to the toolchain directory. Is this ok for you?

**Comment by heitbaum** [comment]
A cleaner way that aligns to the prior art is to similar to 

https://github.com/LibreELEC/LibreELEC.tv/blob/7a0782cc23abf7794796f9e58fcc2186cf646eb7/packages/textproc/libidn2/package.mk#L21-L24

Then doesn’t introduce or depend on upstream making changes in their build

**Comment by rellla** [comment]
I see that only samba and stress-ng have the attr dependency. Do they only need lib and headers on build time, or do we also need the binaries in the image file?

So maybe, we should just drop the pkg makeinstall_target and add a `safe_remove ${INSTALL}` or at least a `safe_remove ${INSTALL}/include` in a post_makeinstall_target?

**Comment by heitbaum** [comment]
> I see that only samba and stress-ng have the attr dependency. Do they only need lib and headers on build time, or do we also need the binaries in the image file?
> 
> So maybe, we should just drop the pkg makeinstall_target and add a `safe_remove ${INSTALL}` or at least a `safe_remove ${INSTALL}/include` in a post_makeinstall_target?

Ideally best to “fix” the configure or makefile. In this case there is not much effort to have those changes done (but will need to be via upstream.) then a configure option like `—-without-tools`

we don’t need or want the `/etc` or `/usr/bin` files

the below (or similar) should work (similar to how the attr build currently works) - with the addition of the .pc file (may or may not be needed by samba/stress-ng.)

```
makeinstall_target() {
  make install-libLTLIBRARIES DESTDIR="${SYSROOT_PREFIX}"
  make install-pkgconfDATA DESTDIR="${SYSROOT_PREFIX}"
  make install-data-local DESTDIR="${SYSROOT_PREFIX}"
}
```

**Comment by rellla** [comment]
That would probably work, but is it necessary?
The attr-files you listed above are all copied into sysroot, when there is no packages' makeinstall_target. 
We wouldn't need bin and etc in sysroot, but that is wrong for most other packages, too!?

So imho we just need to know, if anything of attr should go to the image file? If not, a `safe_remove ${INSTALL}` or at least `safe_remove ${INSTALL}/usr/include/` would be a simple solution - independent on upstream changes.

**Comment by heitbaum** [comment]
For files in install_pkg you don’t need to worry about `./usr/include` as these are excluded from the image but `bin` files and `etc` files would be included. 

So if you were wanting to selectively clean install_pkg and get no artefacts in the image - then `safe_remove ${INSTALL}/usr/bin` and `safe_remove ${INSTALL}/etc`

see:
https://github.com/LibreELEC/LibreELEC.tv/blob/7e8052c9bfcfa88a06b3a5819e238faf640b2539/scripts/install#L155

**Comment by rellla** [comment]
Ok, so i think, best is to simply let LE do it's job and completely drop makeinstall_target like i did in last my force-push.
All files go to the toolchain sysroot but only /etc/, /usr/bin and /usr/lib go to the image. Cleaning up the sysroot directory would be another task...

**Comment by heitbaum** [comment]
> Ok, so i think, best is to simply let LE do it's job and completely drop makeinstall_target like i did in last my force-push. All files go to the toolchain sysroot but only /etc/, /usr/bin and /usr/lib go to the image. Cleaning up the sysroot directory would be another task...
> 
> If someone wants attr to be packaged, he probably expects the bin and etc to be in the image ... If attr is only intended as a build dependency, the two safe_remove should be done. What do you think? Personally I just need to get the headers copied to sysroot to get another package built.

The bin and etc shouldn’t be included. As the image will now look like this.

ls -l /etc/xattr.conf /usr/bin/*attr 
-rw-r--r--    1 root     root           681 Sep 20 21:59 /etc/xattr.conf
-rwxr-xr-x    1 root     root         14760 Sep 20 21:59 /usr/bin/attr
-rwxr-xr-x    1 root     root         19584 Sep 20 21:42 /usr/bin/chattr
-rwxr-xr-x    1 root     root         18936 Sep 20 21:59 /usr/bin/getfattr
-rwxr-xr-x    1 root     root         19584 Sep 20 21:42 /usr/bin/lsattr
-rwxr-xr-x    1 root     root         14784 Sep 20 21:59 /usr/bin/setfattr

**Comment by rellla** [comment]
Ok, so now only lib gets copied.

**Review by heitbaum — APPROVED** [review]

**Pull request merged**
