### PR TITLE
QA issues

### PR DESCRIPTION
**Pull request by vpeter4**
Fix issues find by QA Check https://github.com/LibreELEC/LibreELEC.tv/pull/6666

### CODE REVIEW

**Review by CvH — APPROVED** [review]
tx

**Comment by vpeter4** [comment]
Can someone check if there is QA message at the end of the build for arm targets?

**Comment by SupervisedThinking** [comment]
> Can someone check if there is QA message at the end of the build for arm targets?

Well didn't you check your changes before you PR them?

**Comment by heitbaum** [comment]
I checked the actions builds from last night ARM has the following: (e.g.)
```
[QA CHECK] [general] [qa_issues]:
QA issues present, please fix!
/build/build.LibreELEC-RPi4.arm-11.0-devel/qa_checks/libdrm-2.4.112/safe_remove
```
Generic has:
`ls: cannot access '/build/build.LibreELEC-Generic.x86_64-11.0-devel/qa_checks/': No such file or directory`

**Comment by vpeter4** [comment]
> Well didn't you check your changes before you PR them?

I did Generic only. And there is fine. No messages.

> so `safe_remove` has to remove `amdgpu_stress` conditionally

What is the point to complicate removing files which may or may not exist? Remove them if it does and if it doesn't exist do nothing. No need for this QA check and no need to print any warning when file doesn't exist.

So much pointless work for nothing ...

**Pull request merged**
