### PR TITLE
systemd: network-base: alter hosts.conf if contents still default

### PR DESCRIPTION
**Pull request by antonlacon**
This partially addresses #7674. Another part will be needed in the settings addon.

In short, the settings addon will just append localhost entries to user or image set /etc/hosts. This moves settings to the network-base.service, and makes adding entries contingent on the image's hosts.conf matching the same content as the one located in /storage. If there is any mismatch, no changes are made.

127.0.1.1 is added as the hostname's hosts entry as recommended by Debian's reference manual: https://qref.sourceforge.net/quick/ch-gateway.en.html see 10.4. It's for applications that believe the hostname should resolve to an address.

I don't believe it's enabled, but my understanding is ipv6 has only the one localhost address so there's no change to be made there.

The intended change in the settings addon is to change hostname.set_hostname() to just editing the hostname file in /storage and then restarting network-base.service (which just runs this script).

I'm not terribly thrilled about this approach because if the image's hosts.conf is updated, then existing installs will still have the hosts.conf from the original install. That would be detected as a user made change, which it isn't. This would be the kind of gotcha that gets forgotten about.

Also adds license header and shellcheck change.

### CODE REVIEW

**Comment by antonlacon** [comment]
Thinking further, maybe everyone should get the localhost entries added and then add hostname if grep doesn't show it on a line without a comment. Would eliminate having to care about the contents of hosts.conf.

**Comment by ajbathe** [comment]
Why so complicated? Why can't this information, which is always static and always the same, not go straight to /usr/config/hosts.conf ?

And what about the python script service.libreelec.settings/resources/lib/hostname.py[c] ? This is where host.conf is touched again. Or am I wrong?

And what will happen, when some hostname like "uranus" is double? Once created by a user and - like it is now at the moment - automatically added under localhost 127.0.0.1. ?

And I don't see the need of hostname added under ipv6 together with localhost. Which software needs that here under "Just enough OS for Kodi" where no GNOME software runs?

Just my 2 cents ...

**Comment by ajbathe** [comment]
"If your system has a permanent IP address then use that; otherwise use the address 127.0.1.1" means one case from the very past: A single computer isolated without internet. But who uses that for Kodi today? I'm sure nobody uses a media center system without a permanent IP. Adding hostnames to localhost is not only wrong but also unnecessary. I could guess, that it makes a proper system more confusing than that it helps. And an island system doesn't care if some hostname is missing, or does it?

My suggestion: Just create localhost entries like everybody on earth does it. Look in hosts of other distributions. No one puts real hostnames under localhost IPs as I know it.

**Comment by vpeter4** [comment]
If it helps somehow :)

```
me@ubuntu22:~$ cat /etc/hosts
127.0.0.1	localhost
127.0.1.1	ubuntu22

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

```

**Comment by ajbathe** [comment]
That Ubuntu as a Debian derivate does it wrong, too does not make me wondering.

Take Red Hat for example. They are much longer on the market than Ubuntu. And you could read that here:

https://access.redhat.com/solutions/57330
please see the references to Bug reports, too

=> Therefore in RHEL 6.1 Network Manager does not touch /etc/hosts file at all and only adds to hostname to /etc/sysconfig/network

Make it simple, make it right:

We prove now that your thinking is not correct here:

My hosts.conf on LE is given here:
--- schnipp ---
# /storage/.config/hosts.conf
#
# This configuration file allows you
# to manually map hostnames to IP addresses.
#
# Format:  <ipaddress> <hostname1> <hostname2>
# Example: 192.168.0.3 libreelec.mynetwork libreelec

# NOTE: do not edit /etc/hosts directly
# edit /storage/.config/hosts.conf then reboot

127.0.0.1       localhost
::1 localhost ip6-localhost ip6-loopback

192.168.178.31   raspi.fritz.box    raspi

# end of hosts.
--- schnap ---

What should hostname -s give? Right: raspi, correct.
What should hostname -d give? You don't now, the info comes from the router (DHCP) and in my case it is fritz.box
What should hostname -f give? Yeah: raspi.fritz.box

And now the same with your "wrong Debian-LE based system":

hostname -s -> raspi
hostname -f -> localhost
hostname -d is empty, should be fritz.box, right?

Any more questions?

And your :) makes me think, I should say "Naseweis" to you ;-)

**Comment by vpeter4** [comment]
> Any more questions?

No. But fix your code text above because it is hard to read.

> And your :) makes me think, I should say "Naseweis" to you ;-)

It was not meant to be read like this. I only provide the output just to compare. Without making any suggestions.

**Comment by ajbathe** [comment]
Sorry, this is githubs problem, causes by hashmarks, I just copy-pasted it here. I'm aware that Ubuntu is doing it wrong too - I use that on my laptop, but my /etc/hosts 
is
127.0.0.1	localhost
(hashmark)127.0.1.1	akoya

done by me.

**Comment by CvH** [comment]
just as reference alpine at proxmox

```
somesoftware:~# cat /etc/hosts
127.0.1.1       somesoftware
127.0.0.1       localhost localhost.localdomain
::1             localhost localhost.localdomain
# --- BEGIN PVE ---
192.168.0.123 somesoftware.lan somesoftware
# --- END PVE ---
```
```
somesoftware:~# hostname -s
somesoftware
somesoftware:~# hostname -f
somesoftware.lan
somesoftware:~# hostname -d
lan
```

**Comment by ajbathe** [comment]
somesoftware being member of 127.0.1.1 AND 192.168.0.123 is definetly wrong and confuses a machine which gets asked "give me the IP of somesoftware.

**Comment by CvH** [comment]
as reference why its there https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution

**Comment by ajbathe** [comment]
did you read exactly what follows?
---schnipp---
The IP address 127.0.1.1 in the second line of this example may not be found on some other Unix-like systems. The [Debian Installer](https://en.wikipedia.org/wiki/Debian-Installer) creates this entry for a system without a permanent IP address as a workaround for some software (e.g., GNOME) as documented in the [bug #719621](http://bugs.debian.org/719621).
---schnapp---

**Comment by ajbathe** [comment]
And I would like to get rid of one thing here: if you only ever do what other people do wrong, then you could call yourself a lemming.
I can remember SuSE inventing automated host entries and driving admins insane, RedHat had problems with that.
My simple hosts file with only one entry for localhost doesn't cause any problems.

**Comment by antonlacon** [comment]
I've pushed the grep approach to avoid having to care about the contents of image's host.conf file. Updated comments in image's hosts.conf while at it.

> Why so complicated? Why can't this information, which is always static and always the same, not go straight to /usr/config/hosts.conf ?

Changes to the image's host.conf will only get picked up on new installs. Existing users would need to reinstall their system. Scripting can resolve the problem well enough.

> And what about the python script service.libreelec.settings/resources/lib/hostname.py[c] ? This is where host.conf is touched again. Or am I wrong? And what will happen, when some hostname like "uranus" is double? Once created by a user and - like it is now at the moment - automatically added under localhost 127.0.0.1. ?

See first message's line and the part regarding hostname.set_hostname(). The addon's code doesn't live in this repo. Changes need to be made here first. Assuming "now at the moment" refers to the pre-PR, the intent here is to let users edit their /etc/hosts to their heart's content without requiring existing users to do anything. As mentioned, this is not the _complete_ solution.

> The other stuff.

.......

I appreciated the part where I was told that I'm a lemming who is doing it wrong for not wanting to break running systems. It let me know that spending my free time resolving this was time spent wisely. So uh... Thanks for that, I guess.

**Comment by ajbathe** [comment]
If you see some insult within my comment with the lemming, I am very sorry and it was not my intention to say that. This was reasoned by the facts I pointed out.

**Comment by antonlacon** [comment]
The entire existing install base has a /storage/.config/hosts.conf already. If the file isn't found, it's copied on system startup from /usr/config/hosts.conf. It's part of how /storage is populated after resizing on first boot. Changing any existing file in /usr/config/ will only get picked up when a user manually deletes a file expected to be there (and reboots), does a hard reset of their system, or writes a new image to their device.

If you're going to continue down the path of everything I'm doing is wrong, just open a new PR with tested code that works for the existing install base so I can close this. I'm out of goodwill.

**Comment by ajbathe** [comment]
All what you described in the first paragraph, I learnt it the hard way: Because I was wondering, why my hosts.conf file was badly changed. Right now,

127.0.0.1 localhost raspi
::1 localhost ip6-localhost ip6-loopback raspi

will be appended, although my user host.conf has only comments. This is done, as I found out, by the python script hostname.py of the addon service.libreelec.settings:
```
def set_hostname(hostname):
    with open(config.HOSTNAME, 'w') as output:
        output.write(hostname)
    with open('/proc/sys/kernel/hostname', 'w') as output:
        output.write(hostname)
    with open('/etc/hosts', 'w') as output:
        if os.path.isfile(config.HOSTS_CONF):
            with open(config.HOSTS_CONF) as input:
                output.write(input.read())
        output.write(f'127.0.0.1 localhost {hostname}\n')
        output.write(f'::1 localhost ip6-localhost ip6-loopback {hostname}\n')
```
And I guess that the idea here was the fact because /usr/config/hosts.conf had no entry for localhost.

I even did not know that some more scripting is done with packages/sysutils/systemd/scripts/network-base-setup.

Let's do a small test: You as an adminstrator want to have /etc/hosts empty because all that stuff is done by connman and co. So please do that with your system.

I had to correct hostname.py, and than with an user hosts file, you get

127.0.0.1       localhost
# end of hosts.
127.0.0.1 localhost raspi
::1 localhost ip6-localhost ip6-loopback raspi

This is my PR and I'm not out of goodwill. But I start to feel like Don Quijote fighting against wind mills. Theoretically, the hosts could be empty, because connman and co. are working here.

But I can live with people with an attitude of "We do it this way because we have always done it this way."

**Comment by antonlacon** [comment]
Good luck.

**Review by CvH — APPROVED** [review]

**Pull request merged**
