### PR TITLE
Odroid_C2/Linux patches

### PR DESCRIPTION
**Pull request by wrxtasy**
Some Important Patches for HardKernel v3.14.y linux commit #f0ddde5

- li04 - all HK HiFi Shield and usb_dac mods had to be reverted to enable at least partial HD Audio Passthrough to work, current Audio functionality is found here:
http://forum.kodi.tv/showthread.php?tid=258707&pid=2233982#pid2233982 
- li05 - the most important of the lot. Fix black screens on S905, that happen with amcodec and dynamic refresh rate switching enabled. Sent to me by  surkovalex (Alex).
This patch also allows the preferred AML Frame Rate Automation mode 1 to stay enabled for smooth video playback of fractional frame rates. 👍 
- li06 - attempt to fix VC-1 stuttering playback
- li07 - a patch for the 23.976fps pixel clock
- li08 - disable the Hybrid HDMI-CEC debug log
- li09 - Boblight Kernel patch originally from Codesnake
- li10 - increase amvideocap Buffer Size for Boblight and Hyperion on S905
- li12 - essential, see here: https://github.com/hardkernel/linux/commit/a00a8f810a8fe837d57119417a273c19dd61041e

gda and Raybuntu's Hybrid AML S905 HDMI -CEC work is already incorporated in the updated Kernel.
W.

### CODE REVIEW

**Comment by kszaq** [comment]
I think for the li05 patch you meant @surkovalex. ;)

**Comment by wrxtasy** [comment]
Looks like I'm getting my Alex's mixed up.  There are three of you now in the AML development sphere, its no wonder a bloke gets a bit confused ! ;)

**Comment by lrusak** [comment]
can we use the normal patch naming convention please?

`PKG_NAME-patch#-discription-with-dashes.patch`

**Comment by chewitt** [comment]
@wrxtasy can we get the patch naming sorted pretty please - else this is going to stagnate

**Comment by kszaq** [comment]
@wrxtasy For my experience *li05* patch doesn't work properly as it introduces stutter in 23.976fps playback. For a proper patches please look here: https://github.com/kszaq/LibreELEC.tv/tree/7.0.2.002/projects/S905/patches/linux

I have ported a patch from 3.10 kernel authored by @codesnake and added a patch to prevent frame rate switching on pause/seek. Based on user tests, 23.976fps video play smoothly and there is no black screen.

**Comment by chewitt** [comment]
I'm closing this PR down as its content will be superseded with the linux-amlogic repo. Thanks.

**Pull request closed without merging**
