### PR TITLE
webgrabplus: add user defined pre/post processing

### PR DESCRIPTION
**Pull request by awiouy**
The home folder of the addon is not acessible to other addons.
Therefore copying the generated epg files to /storage/downloads/webgrabplus
Users' requests

### CODE REVIEW

**Comment by chewitt** [comment]
IMHO a dedicated /storage/webgrabplus or /storage/.webgrabplus folder would be better so there's no overlap between EPG data and whatever random use of /storage/downloads takes place on the users' system.

**Comment by awiouy** [comment]
I am aware of what you write. However, /storage/webgrabplus is not a smb share. By placing the files in /storage/download/webgrabplus, they are available to addons and smb clients, without further configuration.

**Comment by awiouy** [comment]
After discussing with users in the forum, user defined pre/post processing is more appropriate.
I therefore updated the service to call before.sh/after.sh in $ADDON_HOME

**Comment by lrusak** [comment]
looks ok, not sure if you need to chmod +x the script before you run them.

**Comment by awiouy** [comment]
They are called with sh, and therefore need not be executable ;)

**Comment by awiouy** [comment]
I am done, ready to merge ;)

**Pull request merged**
