### PR TITLE
[le12] linux: update to 6.6.y

### PR DESCRIPTION
**Pull request by heitbaum**
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6

6.6 - Linux Kernel release

errors / fixes / issues / regressions / todo
- todo
  -
- done
  - xf86-video-nvidia
  - xf86-video-nvidia-legacy
  - iwlwifi-firmware
  - ~strace 6.5 does not compile against Linux-6.6~

### log 
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.6.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.6.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/log/
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.6
- https://linux-regtracking.leemhuis.info/regzbot/mainline/
- https://linux-regtracking.leemhuis.info/regzbot/stable/

### 6.6.0 Build tested on all of:

```
PROJECT=Allwinner ARCH=aarch64 DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H3 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX6 s/build linux
PROJECT=NXP ARCH=aarch64 DEVICE=iMX8 s/build linux
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard s/build linux - u-boot build failure
PROJECT=Generic ARCH=x86_64 DEVICE=Generic s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
```

### 6.6.y Run tested on all of:
- Allwinner all - tested - TBA - jernejsk
- Allwinner H6 (Tanix TX6) - 6.5.2 - heitbaum
- Generic Generic (Intel ADL - NUC12) - 6.6.0 - heitbaum
- NXP iMX6 (Cubox-i4Pro) - TBA - heitbaum
- Rockchip RK3399pro (Rock Pi N10) - TBA - heitbaum
- RK all - tested - TBA - knaerzche
- Samsung Exynos (Hardkernel ODROID XU4) - TBA - heitbaum

### CODE REVIEW

**Comment by obbardc** [comment]
for me on rk3399, this only outputs in 4k@36hz and not 60hz for some reason :-)

**Comment by heitbaum** [comment]
Kernel builds tested and ready - just waiting for strace 6.6 to be released to complete the PR.

**Comment by eldersixpack13** [comment]
https://github.com/strace/strace/releases/tag/v6.6

P.S.
_waiting a long time for the new features for my i5-1340P CPU in Kernel 6.6_

**Comment by eldersixpack13** [comment]
Thanks @heitbaum !

**Comment by heitbaum** [comment]
strace.io done and build tested. Merge Block removed.

**Review by chewitt — APPROVED** [review]

**Comment by zhangn1985** [comment]
@heitbaum tested this kernel 6.6 on H3,

I find 2 issues:

1, fail to reboot, this is also happen in mainline/stable linux (without patch). does it related not updated uboot?
 
2, no HDMI display, this not happen in mainline/stable linux, thus the patches break HDMI.

after read dmesg, I find sun8i_dw_hdmi module probe twice. first time it fails at `hdmi->hdmi = dw_hdmi_bind(pdev, encoder, plat_data);` 2nd time failed at `ret = sun8i_hdmi_phy_init(hdmi->phy);`  phy clock already initialed:

```
        /* check to see if a clock with this name is already registered */
        if (clk_core_lookup(core->name)) {
                pr_debug("%s: clk %s already initialized\n",
                                __func__, core->name);
                ret = -EEXIST;
                goto out;
        }
```

because the clock is registed at 1st probe. and 1st probe not unregister it.

**Comment by zhangn1985** [comment]
after carefully check config, I find it missing `CONFIG_DRM_DISPLAY_CONNECTOR`   everything works fine, include reboot,.

**Comment by heitbaum** [comment]
> after carefully check config, I find it missing `CONFIG_DRM_DISPLAY_CONNECTOR` everything works fine, include reboot,.

could you please raise a PR with your proposed fix, so that is can be reviewed.

**Pull request merged**
