### PR TITLE
Delete patch which breaks 5ghz

### PR DESCRIPTION
**Pull request by sopparus**
This patch breaks 5ghz on rtl8812au for me (zyxel) and another guy on irc with edison wifi stick.
Sam uses this patch on another repo and it's unclear if it does any good for libreelec.

### CODE REVIEW

**Comment by chewitt** [comment]
@sopparus Other Realtek drivers contain this message in rtw_mlme_ext.h .. so if the objective was to wait longer to prevent association timeouts the value of SURVEY_TO should be raised not set to zero. It might be worth keeping the patch (presumably it was authored to resolve user reports of issues, not just for fun) but change its value from 0 to 150ms.

```
/*      Increase the SURVEY_TO value from 100 to 150  ( 100ms to 150ms ) */
/*      The Realtek 8188CE SoftAP will spend around 100ms to send the probe response after receiving the probe request. */
/*      So, this driver tried to extend the dwell time for each scanning channel. */
/*      This will increase the chance to receive the probe response from SoftAP. */```

**Comment by sopparus** [comment]
Ok, i Will try with 150 tomorrow

**Comment by chewitt** [comment]
@sopparus any update?

**Comment by sopparus** [comment]
just tested and 5ghz worked fine with the value of 150.

**Comment by chewitt** [comment]
@sopparus thanks, do you want to rebase the PR with that change?

**Comment by stefansaraev** [comment]
cc @samnazarko in case he still uses this patch in osmc.

**Comment by samnazarko** [comment]
Thanks for the ping. This was brought to my attention in LE on Freenode. We didn't see negative reports from this in OSMC, but for good measure I've dropped it.

**Comment by sopparus** [comment]
Ehm, that didnt work too well, can you delade that i didnt manage

**Comment by chewitt** [comment]
Closing as superseded by #672

**Pull request closed without merging**
