### PR TITLE
dispmanx_vnc: move config to addon

### PR DESCRIPTION
**Pull request by awiouy**
Hello!
Here is an update to dispmanx_vnc: configuration is moved to the addon settings, and when the addon settings are updated the service is restarted.

### CODE REVIEW

**Comment by CvH** [comment]
@awiouy no need to bump the version - addon wasn't uploaded to the repo yet (insert snail.png)

btw multi-threaded and frame-rate at strings.po should be multithreaded and frame rate - at least if I can trust my dictionary (en_gb natives could help I think)

**Comment by awiouy** [comment]
@CvH
For simplicity, I reused the names from the documented config file. This can be easily be changed, and does not affect the behaviour of the addon.
Should I change the version?

**Comment by chewitt** [comment]
icon: http://chewitt.libreelec.tv/test/icon_dispmanxvnc.png

**Comment by awiouy** [comment]
@chewitt I used the proposed icon
@CvH I applied the changes you proposed, but for PKG_SECTION
I also corrected a typo, which prevented from setting a password.
This runs on my LE7 Pi2

**Comment by CvH** [comment]
@awiouy Raspberry PI -> Raspberry Pi
btw post at -> https://github.com/CvH/LibreELEC.tv/commit/4c78be582348fd8b5877018516aa91fdb7b3a4f8

**Comment by awiouy** [comment]
@CvH PI is now Pi

**Comment by chewitt** [comment]
If you change anything that has already been pushed to the repo you need to bump PKG_REV

**Pull request merged**
