### PR TITLE
uboot_helper: convert to use argparse

### PR DESCRIPTION
**Pull request by lrusak**
I originally wanted to use argparse when I wrote this script but didn't have the ability to do it then.

These change makes it much easier to read.

The functionality should be the exact same as before. The help has changed though.

```
$ ./scripts/uboot_helper --help                                                                                                                                                                                
usage: uboot_helper [-h] [project] [soc] [board] [dtb|config|crust_config]

Script to help with u-boot configuration

positional arguments:
  project
  soc
  board
  dtb|config|crust_config

optional arguments:
  -h, --help            show this help message and exit
```

@jernejsk @Kwiboo please test if you have a chance

### CODE REVIEW

**Comment by dhewg** [comment]
That looks nicer, but note that crust_config is optional, compare e.g.
`./scripts/uboot_helper Allwinner A64 pine64 crust_config`

**Comment by jernejsk** [comment]
with recent update, that example is not valid anymore. Currently failing example:
`./scripts/uboot_helper Allwinner H6 beelink-gs1 crust_config`

**Comment by lrusak** [comment]
I pushed a fixup so that it will just exit if the `crust_config` key doesn't exist.

It will also print available options when queried like:
```
$ ./scripts/uboot_helper Allwinner H6 orangepi-3
config crust_config dtb
```
This makes it more similar to how it works for the other options.

**Review by jernejsk — APPROVED** [review]
Seems good now

**Comment by lrusak** [comment]
Please try and look at the commit list before merging next time 😊

**Pull request merged**
