### PR TITLE
Tvheadend 4.3

### PR DESCRIPTION
**Pull request by CvH**
- the new Tvh can't replace Tvh 4.2, upgrade path is a bit borked
- 4.3 has broken stuff that works at 4.2 and reverse :) but overall 4.3 is better
- Generic has working vaapi acceleration for transcoding (RPi was disabled because it depends at omx/mmal)
- tested for the last ~3 years, a final 4.4 is sadly not in sight

### CODE REVIEW

**Comment by heitbaum** [comment]
Do we need to roll #4961 into this?

**Comment by SupervisedThinking** [comment]
@CvH maybe you consider cmake?
https://github.com/SupervisedThinking/LibreELEC-RR/blob/master-rr/packages/supervisedthinking/devel/pcre2-system/package.mk#L14-L17

**Comment by CvH** [comment]
@SupervisedThinking tx, i push a update

**Comment by CvH** [comment]
I pushed the cmake change, I`ll do a clean rebuild if it still works later (dirty was okay)

**Review by chewitt — APPROVED** [review]

**Pull request merged**
