### PR TITLE
input: change input repeat config

### PR DESCRIPTION
**Pull request by Kwiboo**
Same as #1323 but for master

### CODE REVIEW

**Comment by lrusak** [comment]
Seems to work as intended :+1:

**Comment by Kwiboo** [comment]
Updated to revert back to 1000ms delay as default delay, but keep 500ms delay for lircd-uinput.

Testing with Harmony Elite and a NUC5PPYH has shown that anything less then 700ms delay can produce double presses using input from the rc subsystem. When lirc and mceusb.lircd.conf is used (forced by custom udev rules) there was no double presses generated.

**Comment by Kwiboo** [comment]
After some more testing I am unsure if the repeat delay needs to be reverted to 1000ms. The default setting for Harmony's command repeats was set to 3, meaning it will send IR-commands 3-4 times for each button pressed, lowering this setting to 0 or 1 repeats also makes the double presses go away.

**Comment by Anuskuss** [comment]
@Kwiboo Sorry if unrelated but I sometimes experience some double presses while using the [Official Kodi Remote](https://itunes.apple.com/de/app/official-kodi-remote/id520480364?mt=8) (RPi2 w/ LibreELEC 7.95.3). Will this fix it?

**Comment by Kwiboo** [comment]
I have now restored the original 500ms delay (the previous revert to 1000ms only affected usb hid remotes and not rc remotes) and changed the remotedelay advanced setting in kodi to 1.
This makes kodi skip the first lirc repeat event and fixes the issue with double presses using a Harmony MCE profile with command repeats set to 3. For properly configured remotes it only adds one repeat period to the initial delay.

**Comment by MilhouseVH** [comment]
Had confirmation that the Harmony issue is fixed: http://forum.kodi.tv/showthread.php?tid=298462&pid=2529276#pid2529276

**Comment by Kwiboo** [comment]
Great! Rebased, squashed and ready to merge. Matches what is included in LE8.
I will look at making the repeat delay and period configurable in kodi/settings addon in another PR.

@Anuskuss this will not fix any double presses in the kodi remote app, as this only affects input devices such as keyboards and ir remotes.

**Pull request merged**
