### PR TITLE
Allwinner: Sort Linux patches

### PR DESCRIPTION
**Pull request by jernejsk**
This PR puts all mainlined patches together and adds few from upstream.

### CODE REVIEW

**Comment by clementperon** [comment]
nitpick comment I would rename the 002-backport-from-5.6.patch to 002-backport-from-next.patch because there is no 5.6 tag.

**Comment by jernejsk** [comment]
True, but whatever is in next will be in 5.6 and I don't intend to rename it in few weeks. Anyway, I plan to add PWM patches in this PR, so please don't merge it yet.

**Comment by jernejsk** [comment]
Added H6 PWM and two Cedrus patches.

**Comment by jernejsk** [comment]
tested on Tanix TX6 and OLinuXino Micro

**Pull request merged**
