### PR TITLE
feat: enable webcam driver as kernel module

### PR DESCRIPTION
**Pull request by nicolaspernoud**
Hi,

I am using this for months with a RPI3 on master branch, without any issues.

Thanks,

### CODE REVIEW

**Comment by nicolaspernoud** [comment]
Hello,
Any news on this PR ? This module is already activated in master branch.

**Comment by nicolaspernoud** [comment]
Hi,
At this point is there something more for me to do to see this PR merged in the 9.2 branch ?
Thanks,

**Comment by MilhouseVH** [comment]
@nicolaspernoud no, just allow us to run some tests... I'll merge it later today or tomorrow if no build issues.

**Comment by nicolaspernoud** [comment]
Nice. Thanks again for your insights and welcome.

**Pull request merged**
