### PR TITLE
alsa-lib 1.2.1.2 update

### PR DESCRIPTION
**Pull request by nouman8**

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Bump `alsa-utils` and `alsa-plugins` to 1.2.1 too?

**Comment by MilhouseVH** [comment]
Thanks! I'll include this in my nightlies and see if there's any issues before merging.

**Comment by HiassofT** [comment]
alsa-lib 1.2.1.1 has just been released - mainly UCM bugfixes http://www.alsa-project.org/main/index.php/Changes_v1.2.1_v1.2.1.1

**Comment by HiassofT** [comment]
In alsa-lib 1.2.1 the topology and ucm configuration files were split out into separate packages - see https://www.alsa-project.org/wiki/Changes_v1.1.9_v1.2.1

This means we'll have to add these 2 new packages, otherwise we'll be missing the configs.

I've added merge blocked for now as Intel Baytrail/Cherrytrail/... users probably won't be too happy if these files are gone

**Comment by MilhouseVH** [comment]
@nouman8 do you have time to look at the issue raised by @HiassofT ?

**Comment by nouman8** [comment]
looks like 2 new packages have to be added and i'm still learning the package.mk format, i'll pass this to you @MilhouseVH :)

**Comment by MilhouseVH** [comment]
I might have to pass the hat to @hiassoft... :smile:

**Comment by nouman8** [comment]
@MilhouseVH gave it a little try though it's a simple extract & repack job but im not sure i'll work.

**Pull request closed without merging**
