### PR TITLE
RPi/RPi2: use brcmGLES libraries

### PR DESCRIPTION
**Pull request by awiouy**

### CODE REVIEW

**Comment by chewitt** [comment]
They need to have their own section and an example of permitted values, and the values should be something simple (single word) not actual compiler flags. The simple thing can be expanded to the complex thing somewhere else in the buildsystem. It's also not clear to me if this will be a short-term fix; if yes we should be patching packages not adding (and then removing) things from the buildsystem.

@lrusak opinion please

**Comment by lrusak** [comment]
I'm not sure why this is needed?

**Comment by vpeter4** [comment]
Because packages like visualization.wavforhu are looking for GLESv2 and EGL library but they were renamed to brcmGLESv2 and brcmEGL. More discussion already made on slack.

**Comment by lrusak** [comment]
then let's adjust all the packages :)

**Comment by MilhouseVH** [comment]
The other option is to add sym links into the toolchain for `libEGL.so`/`libGLESv2.so` (in the bcm2835-driver package, linking to the `libbrmc*` equivalents), in which case all existing addons will build without any further change. However at some point this may need to be reviewed if/when the RPi firmware ships with the open source `libEGL`/`libGLESv2` libraries (I suppose we don't need to copy the new libs if we don't need them, and we simply carry on with the sym links for as long as they continue to work...)

Personally I'd prefer we linked against the correct `libbrcm*` libraries, which is what this PR achieves.

**Comment by MilhouseVH** [comment]
Added #606 after discussing with @lrusak on slack - both options are available now.

Close one, merge the other. :)

**Comment by chewitt** [comment]
closing as #606 is preferred, thanks

**Pull request closed without merging**
