### PR TITLE
jre.zulu: update addon to JDK11 (101)

### PR DESCRIPTION
**Pull request by heitbaum**
Move to the current LTS supported Java.

- jdk-aarch64-zulu: update to 11.45.27-11.0.10
- jdk-arm-zulu: update to 11.45.27-11.0.10
- jdk-x86_64-zulu: update to 11.45.27-11.0.10

all of the JREs have been updated (note: some work was required to use jlink to create the JREs)

update 8.38.0.162-1.8.0_212 to 11.45.27-11.0.10 (2021-01-19)

ref that openjdk 11 is supported by libbluray 1.1.0
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893227#101

changelog (libbluray support):
- https://code.videolan.org/videolan/libbluray/-/blob/master/ChangeLog
- 2019-02-12: Version 1.1.0
  - Add initial support for OpenJDK 11.

release notes:
- https://docs.azul.com/zulu/zulurelnotes/ZuluReleaseNotes/Title.htm

update the package to enable building jre (cross-target):
- https://www.oracle.com/java/technologies/javase/jdk-11-relnote.html
    Installing the JDK in previous releases optionally
    installed a JRE. In JDK 11, this is no longer an option. In this
    release, the JRE or Server JRE is no longer offered. Only the JDK is
    offered. Users can use jlink to create smaller custom runtimes.

### CODE REVIEW

**Comment by vpeter4** [comment]
Does BD and UHD BD menu still works with bumped versions?

**Comment by heitbaum** [comment]
> Does BD and UHD BD menu still works with bumped versions?

Will need to find some test media.

**Comment by vpeter4** [comment]
Seems this PR doesn't even build correctly. I would expect at least this but instead we have package bumps which probably doesn't solve anything. And the other changes even break working addon (comment 'libbluray needs arm/server' is there for a reason)!
Also don't rely if something is good for Generic x86_64 project because building for other arm based projects brings other issues.

```
./scripts/build jdk-x86_64-zulu
UNPACK      jdk-x86_64-zulu
sha256sum: packages/addons/addon-depends/jre-depends/jdk-x86_64-zulu/package.mk: No such file or directory
BUILD      jdk-x86_64-zulu (target)
    TOOLCHAIN      manual
```

```
PROJECT=NXP DEVICE=iMX6 ARCH=arm ./scripts/build jre.zulu
UNPACK      jdk-arm-zulu
/lib/ld-linux-armhf.so.3: No such file or directory
FAILURE: scripts/unpack jdk-arm-zulu during post_unpack (package.mk)
*********** FAILED COMMAND ***********
bin/jlink --module-path ${PKG_BUILD}/jmods --output ${PKG_BUILD}/jre11 --add-modules java.se
**************************************
```

Anyway, here are all the fixes. Tested as it should be.
https://pastebin.com/MX4bB5GJ

**Comment by heitbaum** [comment]
Thanks for the feedback. Has clarified my misunderstanding that ARCH isn’t BUILDHOST_ARCH will update PR.

**Comment by vpeter4** [comment]
I don't know why you are even bother with this bumps and not testing the result. Because after more testing I see
`2021-02-01 14:16:03.989 T:2330    DEBUG <general>: CBlurayCallback::Logger - bdj.c:862: Detected Java 9 or later JVM - support is experimental !`
And surprise surprise: not every sample I tried worked. So newer java is obviously not good.

Never is not always better!

**Comment by vpeter4** [comment]
Seems you just don't get it :(

I gave up.

**Comment by DaVukovic** [comment]
@vpeter4 stay cool ;) . This is marked as WIP anyway. So I guess it won't get merged soon. 

@heitbaum it would be nice if you could offer some testbuilds at LE slack. I happily test them as I still own a BD drive and are also able to do new rips. So testing would be easy. Feel free to ping me any time

**Comment by vpeter4** [comment]
> So I guess it won't get merged soon.

Yes, maybe it will be needed in a few years. But now it breaks working thing.

And not to mention (again) that packages doesn't build correctly. Maybe looking my paste would be good to do again and learn few bits of buildsystem.

**Comment by heitbaum** [comment]
@DaVukovic thanks for that. 

I had a look at my mistake on the understanding of what ARCH was last night, I have updated the WIP on HOSTTYPE (still WIP) - need to have it with the logic to build the blobs regarding of HOSTTYPE :-) once I have it to the next step and cross compiling on all ARCH

If there is free test media that can be shared - it would be great if I could test.

**Comment by vpeter4** [comment]
Free BD games:
```
8bitMemoirs-Issue1-English-v1.11.iso
UkkosJourney-BluPlay.iso
funkyFresh.iso
```
All three works with java8, none with java11.

I also tested real movies:
```
The Stanford Prison Experiment.iso
Shortwave.2016.COMPLETE.BLURAY-UNTOUCHED.iso
```
Both works with java8, only first one with java11.

Conclusion: using java11 gives 20% of media playback :)

**Comment by heitbaum** [comment]
Thanks for doing those tests @vpeter4 - I’ll grab those test media’s and put some testing time in 👍(see if we can’t figure out what the issue is with the later JREs)

**Comment by vpeter4** [comment]
Maybe something like this is needed to be included: http://git.1f0.de/gitweb?p=libbluray.git;a=commit;h=e670de413fc0ba59c036dfb442edaff85fd1cc1e;js=1

**Comment by CvH** [comment]
@vpeter4 https://github.com/LibreELEC/LibreELEC.tv/pull/4299
Needs kodi changes that nobody did yet, the Nevcairiel patch is for 3D at RPI afaik, so not needed for now.

**Comment by vpeter4** [comment]
Actually libbluray 1.2.1 is "almost there": https://github.com/xbmc/xbmc/pull/19424
and it works fine with Kodi 19.

From what I noticed this Nevcairiel patch is not just for 3D but for general BD-J menus too. So it is needed. For now I just manually changed few things inside for 1.2.1 support. Not pretty but it works.

**Comment by heitbaum** [comment]
Guess will have to follow this through now - good call on the LE11 label 😀

**Comment by vpeter4** [comment]
I think this is the process for creating nevcairiel patch.
It work on my samples. But also work without this patch :) So maybe really not needed as CvH wrote

```
rm -fr libbluray-patch
mkdir libbluray-patch
cd libbluray-patch
git clone git://git.1f0.de/libbluray.git libbluray-nevcairiel
git clone https://code.videolan.org/videolan/libbluray.git libbluray-master
cd libbluray-nevcairiel

git remote add libbluray-master ../libbluray-master
git fetch libbluray-master
git checkout -b for_patch

# for 1.2.0 and up revert commit in libbluray-nevcairiel: Disable JVM loading
git revert 5f2523bcc80bd1ba8603abefb774335d755ae497

# use commit from tag
git rebase for_patch $(git rev-list -n 1 1.2.1)

# make patch
git diff $(git rev-list -n 1 1.2.1) HEAD ':(exclude).gitignore' ':(exclude)config.h' \
  ':(exclude)*.vcxproj*' ':(exclude)libbluray.def' \
   ':(exclude)src/libbluray/bluray-version.h' ':(exclude)*_win32.c' ':(exclude)includes/inttypes.h' \
  >libbluray-01-bump_to_Nevcairiel_1_2_1.patch

```

**Comment by heitbaum** [comment]
Parking this PR

**Pull request closed without merging**
