### PR TITLE
libxslt: do not refer to xlocale.h

### PR DESCRIPTION
**Pull request by thoradia**

### CODE REVIEW

**Comment by chewitt** [comment]
@thoradia @stefansaraev can one of you please explain the problem this solves?

**Comment by vpeter4** [comment]
We don't have xlocale.h include file in toolchain.

Maybe we could just make symbolic link to locale.h and "fix" some other packages at the same time?

**Comment by escalade** [comment]
The issue is xlocale.h was renamed in glibc 2.26. I did this to avoid fixing individual packages: https://github.com/escalade/LibreELEC.tv/blob/le82/packages/devel/glibc/package.mk#L122-L123

**Comment by stefansaraev** [comment]
looks like a wrong autoconf check, perhaps it's also detecting xlocale.h from host. however, disabling the check should be safe :)

**Pull request merged**
