### PR TITLE
RTL8192EU: add support for 0bda:818b

### PR DESCRIPTION
**Pull request by chewitt**
from a user request on facebook - I'll forward port or make a change upstream if possible

### CODE REVIEW

**Comment by CGarces** [comment]
The device already exist on upstream
https://github.com/Mange/rtl8192eu-linux-driver/blob/master/os_dep/linux/usb_intf.c#L213

My knowledge is very limited, but I don't get why we need this PR.

**Comment by vpeter4** [comment]
I think already added device adds device with some vendor specific protocol. That's why different macro is used (USB_DEVICE_AND_INTERFACE_INFO) which adds some extra elements (class, subclass and protocol).

**Comment by CGarces** [comment]
So add it again (with USB_DEVICE) will work fine?

**Comment by chewitt** [comment]
I'm closing ~ we'll pick the driver updates currently in master for an 8.2 release so it won't be needed. No point in leaving it open.

**Pull request closed without merging**
