### PR TITLE
packages/sysutils/lirc: Cleanup patches - use configure options instead

### PR DESCRIPTION
**Pull request by codesnake**
Use configure options instead of patches for lirc.

### CODE REVIEW

**Comment by lrusak** [comment]
Did you test this? I don't want it to break anything because we do want uinput, we just don't want to run the check for it.

**Comment by codesnake** [comment]
I tested it on WeTek Hub and remote works OK.
BTW lirc package in current state doesn't build at all because some patches fail to apply. Try to delete downloaded source packages and rebuild.

**Comment by butanko** [comment]
please update lirc patches or submit this proposal

tested on WeTek Play, builded with this patch, remote is working OK

**Comment by Kwiboo** [comment]
This should probably be merged and also added to LE8, the lirc 0.9.4c package downloaded from SF have been changed from the taged [5625de4](https://sourceforge.net/p/lirc/git/ci/lirc-0_9_4c/tree/) to [26e152f](https://sourceforge.net/p/lirc/git/ci/26e152f768bd0cf99a67e19beeb95fff02a3a3b3/log/?path=) (only build system changes).

However `HAVE_UINPUT=no` is misleading and should be `HAVE_UINPUT=yes` as any value will enable uinput when cross-compiling.

**Comment by jester-xbmc** [comment]
These patches need a cleanup, currently its the reason the build is failing (at least for wetek play 2 compile from master) indeed lirc-0001-always-enable-uinput.patch is needed but needs to be updated to patch at lines 36 instead of 33, same for lirc-0008-force-have-poll-fine.patch

**Comment by chewitt** [comment]
@codesnake i'm closing this PR as it's superseded by @HiassofT work in #1320, thanks

**Pull request closed without merging**
