### PR TITLE
mali-midgard: provide a single package for Mali Midgard kernel module

### PR DESCRIPTION
**Pull request by kszaq**
This PR modifies `gpu-sunxi-midgard` package to make it compatible with Mali-T820 found in Amlogic S912. Eventually all patches should land in https://github.com/LibreELEC/mali-midgard/

Additionally, the kernel module is renamed from `mali_kbase` to `mali_midgard` to not clash with Bifrost kernel module. We cannot have a single kernel module for both generations as Bifrost userspace libraries use an updated API and we don't have blobs for Midgard using this API.

~~Rockchip is not included as 4.4 kernel includes an in-tree driver and the platform code can be added later when mainline project lands.~~

### CODE REVIEW

**Comment by Kwiboo** [comment]
@kszaq you can reduce number of patches and get some arm fixes by using https://github.com/Kwiboo/mali-rockchip/commits/midgard-r28p0 as a base, uses the midgard-r28p0 / bifrost-r16p0 base instead of the older r22p0 version. That one works great on Rockchip mainline.

**Comment by kszaq** [comment]
@Kwiboo I briefly tested your branch with yesterday and I needed to revert `REGULATOR` modifications otherwise the module causes kernel panic. I also had a lot soft-resets due to job timeouts but perhaps I was missing a compile flag: I noticed that for r22p0 we needed `EXTRA_DEFINES`, now they are all added by `Kbuild` based on `CONFIG` passed to `kernel_make`.

**Comment by kszaq** [comment]
Added a commit to use **r28p0** branch from @Kwiboo, patched to support Allwinner and Amlogic.

@jernejsk Would you be able to check this with a H6 device?
@Kwiboo I needed to partially revert one of your patches to prevent Amlogic crashes: https://github.com/kszaq/mali-midgard/commit/3fd6726a0c2a8f11a10a534565d4bd397475c4b0. At the same time adding pm callbacks to meson platform *seems* to keep CPU temp lower: https://github.com/kszaq/mali-midgard/commit/97cfac4a3c9a13fba873b3c15fd745b353f10292

For now `mali-midgard` uses my fork, if confirmed to work I will push the branch to LE repo and rework commits in this PR.

**Comment by jernejsk** [comment]
It fails to build for Allwinner H6: http://sprunge.us/GXLeDj However, I think I will remove devfreq support from DT because mainline DT won't have it anyway.

**Comment by kszaq** [comment]
@jernejsk Thank you for testing. It turns out that r28p0 still requires an extra CFLAG for devfreq. I pushed a fix to PR branch (rebased on master).

**Comment by jernejsk** [comment]
this doesn't work with H6, module doesn't get loaded

**Comment by kszaq** [comment]
@jernejsk I noticed mistakes in 2 places:
- missed to add `compatible` modification to H6 device tree patch
- missed to add a compile flag

Now both should be fixed. Can you please re-test this PR with Allwinner? If it works, I will still need to move repo and squash commits.

**Comment by jernejsk** [comment]
Still regulator issue: http://ix.io/1KK8

**Comment by kszaq** [comment]
@jernejsk it looks like the second missing item I mentioned was not pushed to my GH branch. Apologies for that and it would be great if you can test this one more time. 😇

**Comment by jernejsk** [comment]
test passed :)

**Comment by kszaq** [comment]
Thank you!

I will move the code to LE repo and squash commits accordingly. 

I would also like to ask @Kwiboo to check if https://github.com/kszaq/mali-midgard/commit/3fd6726a0c2a8f11a10a534565d4bd397475c4b0 does not negatively affect Rockchip or in other words test this PR with Rockchip mainline. 🙂

**Comment by kszaq** [comment]
Commits are now squashed, remaining parts:
- test Rockchip
- move to LE GitHub repo after successful test.

**Comment by Kwiboo** [comment]
Now tested on RK3288, and rockchip requires some smaller changes in order to enable/disable clock, please pick https://github.com/Kwiboo/mali-rockchip/compare/b5da11cacee89c82d35bde86860993272b9061c4...midgard-r28p0 (or should I PR to your repo?) and feel free to squash/fixup any commit.

**Comment by kszaq** [comment]
Thank you @kwiboo. I'll pick your changes, upload all to LE repo and update this PR for final testing.

**Comment by kszaq** [comment]
`mali-midgard` updated with patches from @Kwiboo (once again many thanks for doing this!) and pushed to LE repo. PR updated and runtime-tested on Amlogic. Ready to merge if Allwinner and Rockchip runtime tests pass.

**Pull request merged**
