### PR TITLE
Do not restart Kodi Service on Clean exit code

### PR DESCRIPTION
**Pull request by chlorophyll-zz**
I have the Kodi Addon Gamestarter, where the Kodi Service is exited when the Addon Emulationstation is started.
The Restart=Always drops in and Kodi Service is restarted, this seems like unwanted behaviour in this Context.

So i propose to only restart Kodi Service on unclean exit.
Readup: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=

Can someone confirm or review?
EDIT: Restart=on-failure does not let Emulationstation take over the Gui. Need help.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I'm not familiar with this particular add-on but how does the user return to the Kodi GUI once Kodi has exited? Calling `systemctl stop kodi` is the recommended way to exit Kodi, and `systemctl start kodi` to resume the Kodi GUI.

I'm not sure if we want to change the default Kodi service behaviour for one add-on that could instead implement support for systemctl - changing the service behaviour might have unwanted side-effects on other add-ons, and/or leave users without a GUI at all should Kodi fail but not with a suitable exit code.

**Comment by 5schatten** [comment]
I have no clue how Gamestarter actually deals with Kodi but I use a script to shut down Kodi and it stays down. 
So try to run this on your cli `systemctl stop kodi` and you should get a blank screen.

https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.x-rr/packages/oem/files/common/usr/bin/kodifreeze.sh#L15

**Comment by vpeter4** [comment]
From here https://github.com/bite-your-idols/Gamestarter/blob/master/repository.gamestarter/script.gamestarter/resources/bin/gamestarter.sh#L6 it uses approach with systemctl https://github.com/bite-your-idols/Gamestarter/blob/master/repository.gamestarter/script.gamestarter/resources/bin/gamestarter.start#L24. So it should work just fine.

**Comment by chlorophyll-zz** [comment]
@vpeter4 thank you for clarification.
@MilhouseVH I agree. This pull might have unwanted side effects.

So, step for step what i did was: I installed Gamstarter from https://github.com/bite-your-idols/Gamestarter/blob/master/repository.gamestarter/repository.gamestarter/repository.gamestarter-3.0.0.zip
Then i run the Emulationstation Addon. The Loading Screen from Emulationstation is displayed for two seconds, then Emulationstation obviously quits and Kodi is restarted from systemd. I spotted for the Restart option in the Service file, because i knew that Kodi is started as a systemd Service.
The expected behaviour would be that the Emulationstation Addon would quit Kodi and start Emulationstation. But instead Kodi is restarted because of Restart=Always in the Service Options.
So the Fix might be on the wrong place and i would have to create a Pull for the Gamestarter Script to "systemctl disable kodi" then "systemctl stop kodi" and to "systemctl enable kodi" and "systemctl start kodi" instead of only starting and stopping the kodi service. 
@bite-your-idols

**Comment by MilhouseVH** [comment]
`systemctl stop kodi`/`systemctl start kodi` should be sufficient, no need to `disable`/`enable` - once the service is stopped it will no longer restart automatically.

**Comment by bite-your-idols** [comment]
Gamestarter's emulationstation and retroarch addons use `systemctl stop kodi `and `systemctl start kodi` as you can see [here](https://github.com/bite-your-idols/Gamestarter/blob/master/repository.gamestarter/game.retroarch/addon.start#L76) and [here](https://github.com/bite-your-idols/Gamestarter/blob/master/repository.gamestarter/game.retroarch/addon.start#L195)

When in kodi if you ssh `systemctl stop kodi` you should exit kodi, if you do, gamestarter addons should do.

Also, I think is more a [Gamestarter issue](https://github.com/bite-your-idols/Gamestarter/issues) more than LIbreELEC one and I will appreciate it if you provide some info about your escenario: LE version, device, Emulationstation addon version, retroarch addon version, logs... because I think it could be another issue not the one you think.

**Comment by chlorophyll-zz** [comment]
@MilhouseVH @bite-your-idols 
for now, i have a Mx9-Pro Rk3328 Tv Box. Running LibreELEC-RK3328.arm-8.90.013-box-z28.img.gz with a replaced dtb (rk3328-a5x-mx10.dtb) file from Armbian Repo. Had not much Luck with the Lakka Build, so i opted for Libreelec with Gamestarter. Retroarch on Android is a mess on this Device. But i am getting OOT
Thank you. I will provide the Logs and first test with the LibreELEC-RK3328.arm-8.90.014-box-z28.img.gz and the systemctl stop in cli. And report back here.

**Comment by vpeter4** [comment]
I tried installing on x86_64 in VMware. And it works as it should here.
Maybe the problem is that Emulationstation quits for some reason after it is started. And because of that Kodi starts obviously.

**Comment by chlorophyll-zz** [comment]
@vpeter4 yes, that probably is the case. I first expected the Video Drivers (Mali-450 mp2) on that Device to be the Problem with Emulationstation.

**Comment by bite-your-idols** [comment]
That's is the problem: 

> i have a Mx9-Pro Rk3328 Tv Box

As you can see in first line of Gamestarter readme file:

> Retrogaming Kodi add-ons for LibreELEC (**RPi2/3 & Generic x86_64**)

Sorry you will not launch Gamestarter's Emulationstation in your device, you should look for another addon or build...

**Comment by chlorophyll-zz** [comment]
@bite-your-idols Sorry to you for ignoring the obvious Readme. I will try nevertheless to grab a Retroarch build from Lakka for OpenGles Devices and work my way to a Libreelec with Retroarch on that Box.

**Comment by 5schatten** [comment]
@chlorophyll-zz @bite-your-idols 
The main problem is SDL2 lacks a suitable mali driver like the one provided for RPi. So you have to patch SDL2 with something like this https://github.com/RetroPie/SDL-mirror/commit/b5e5778aabc8b69b6269255f5642881e62a6897b and add a mali video driver. Once this is done you should be able to start Emulationstation.

In the end it has nothing to do with LE or ES it's just a SDL2 issue.

**Comment by MilhouseVH** [comment]
@chlorophyll-zz close this now?

**Pull request closed without merging**
