### PR TITLE
chromium: update to 53.0.2785.92

### PR DESCRIPTION
**Pull request by lrusak**
changes are taken from https://aur.archlinux.org/cgit/aur.git/?h=chromium-vaapi

This should be tested first as I don't have time to compile it.

### CODE REVIEW

**Comment by lrusak** [comment]
I'm happy with this, I'm not 100% sure that hardware acceleration is working properly but it is in good enough shape for me for now.

**Comment by lrusak** [comment]
I'm fine with this, I'm not going to mess with it anymore

**Comment by chewitt** [comment]
Can you add Chromium version to the package description as discussed, then I will merge and build. Thanks.

**Comment by lrusak** [comment]
Done, and done for the backport as well

**Pull request merged**
