### PR TITLE
Ncurses: update to latest master

### PR DESCRIPTION
**Pull request by TheUlpio**
With the reintroduction of ncurses (version 20170812), i noticed artifacts especially using mc over ssh. Building version 20171007 i no longer notice these artifacts, so i think it's safe to update the package.mk (Caution, i tested only with mc 4.8.19 on two different openSUSE desktops connected via ssh to my htpc)

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Are you able to drop the merge commit?

**Comment by Raybuntu** [comment]
Can you also add a PKG_SHA256. Package seems to be missing it.

**Comment by TheUlpio** [comment]
@MilhouseVH Sorry, i don't know what is a merge commit, and i don't know how i made that :(
Maybe the best solution is to close this pr?

**Comment by MilhouseVH** [comment]
You should be able to `git rebase -i`, change `pick` to `drop` alongside the second "merge" commit and then save, followed by `git push -f` ("force push") which drops the merge commit from this PR.

However if you're doing this via the github GUI then yeah, a new PR is probably easiest...

Same with the PKG_SHA - make the change and create a new commit, then squash it into the first commit with `git rebase -i` changing the new PKG_SHA commit from `pick` to `squash` (or just `s`). Then save, and force push.

**Comment by TheUlpio** [comment]
Well, git for me is "only" the gui version, i use it only to clone LibreELEC and then play with my own changes. All the rest is done via gui...

**Comment by MilhouseVH** [comment]
OK, I'll do it in a separate PR. I've noticed there's a couple of other packages missing their PKG_SHA256 so I'll fix this and bump it at the same time.

**Comment by TheUlpio** [comment]
I owe you a beer :) Thanks!

**Pull request closed without merging**
