### PR TITLE
chromium: update to newer version

### PR DESCRIPTION
**Pull request by InuSasha**
simple runtime tests succeded

### CODE REVIEW

**Comment by lrusak** [comment]
Does hw acceleration work?

**Comment by InuSasha** [comment]
activate hw acceleration for intel and play a youtube video. working

**Comment by lrusak** [comment]
Please make sure it is actually working. We had the issue in the past where it said it was working but actually cpu usage was at 100%

**Comment by piotrasd** [comment]
Hi InuSasha, im starting build chromium but i found one mismatch
based on 
> PKG_URL="http://ftp.mozilla.org/pub/security/nss/releases/NSS_3_29_5_RTM/src/nss-3.29.5-with-nspr-4.13.1.tar.gz"

and in package.mk of nspr still is 4.13, i fix that with PR in your fork ;)

**Comment by InuSasha** [comment]
will squash chromium changes, after ok from testers

**Comment by InuSasha** [comment]
completely restarted the pr...
- update to 60.0.3112.113
- use system sqlite for nss (copied from @MilhouseVH / #1791)
- switch vaapi patch to version from Daniel Charles
- build gn as :host

**Comment by InuSasha** [comment]
new test addon uploaded: https://dl.inusasha.de/libreelec/dev/chromium/browser.chromium-9.0.107.002.zip. USE ONLY ON CLEAN INSTALLATION, the profile will dropped (only in this TEST-BUILD)!!!
I need test on amd and nvidia GPUs. please open url "chrome://gpu" and check, if hardware accelerator for decode is enabled, or not.

**Comment by msj33** [comment]
Any news on this? - Netflix in Chromium is broken in 8.1.2 version......Wife is driving me up the wall!

**Comment by LongChair** [comment]
IMHO that bump is lacking something. Since chromium 61 it supports GTK3 which allows to be using either X11 or Wayland as a backend.
I think GTK+ package should be bumped to v3 and also setup the proper gtk3 configure flags depending on the $DISPLAYSERVER ie `x11` or `wayland`.

**Comment by InuSasha** [comment]
@LongChair i had tried to update to gtk3, but i failed. 
But we had actual other more important problems with chromium (support of video hardware decoding). So it is not on top of the todo list.

**Comment by LongChair** [comment]
@InuSasha : just one comment, since chromium 61 it supports gtk3. I got it to build in my repo, would have been probably nice to bump gtk2 ...

**Comment by InuSasha** [comment]
@LongChair when you commit gtk3, i try to use it.
But not in the next 2 month... i need chromium holidays ;)

**Pull request merged**
