### PR TITLE
Update libsamplerate to 0.1.9

### PR DESCRIPTION
**Pull request by esfomeado**
Changelog: https://github.com/erikd/libsamplerate/blob/master/ChangeLog

### CODE REVIEW

**Comment by chewitt** [comment]
can you please explain what the updates bring/fix?

**Comment by esfomeado** [comment]
I added the changelog to the description.

**Comment by chewitt** [comment]
Changelog was last updated in 2013 :)

Is the PR submitted because you noticed the package could be updated, or does the bump fix and issue that you experienced? - not trying to be awkward, just wanting to understand. Thanks.

**Comment by polojoe** [comment]
a more recent changelog: https://github.com/erikd/libsamplerate/blob/master/NEWS

**Comment by lrusak** [comment]
Please rebase

**Comment by lrusak** [comment]
Thanks but I'm closing as we haven't heard back in a while

**Pull request closed without merging**
