### PR TITLE
Hyperion!

### PR DESCRIPTION
**Pull request by lrusak**
Thanks @stefansaraev 

I would like to squash and rename these commits, so let me know if you would like me to reset the author to myself.

Also, I don't think you would want to be listed as the package maintainer, in which case I can take this over.

### CODE REVIEW

**Comment by stefansaraev** [comment]
to be clear: this will only work on wetek hardware. needs some work for rpi/imx6/generic.

also, you need to adjust 4d6d5cc09fdc5d46770c247428077e25eb9189ed for wetek play. too

> Also, I don't think you would want to be listed as the package maintainer, in which case I can take this over

please do ;)

**Comment by stefansaraev** [comment]
and, I think this belongs to your unofficial repo ;)

**Comment by lrusak** [comment]
Updated commit's and squashed. @CvH please test :+1:

**Comment by stefansaraev** [comment]
some hints:

rpi users will want: -DDENABLE_DISPMANX=1  
-DENABLE_WS2812BPWM=1 and -DDENABLE_WS281XPWM dont hurt, some people may want to use ws28xx leds via spidev. (-DDENABLE_SPIDEV=1)

for hyperion-v4l support (analog grabbers) - you need protobuf. and x11 for generic users.

**Comment by lrusak** [comment]
Added a commit to allow for building on different platforms

**Comment by HiassofT** [comment]
Thanks a lot, having a hyperion addon is highly appreciated!

Did a RPi2 build and noticed some issues:
* `patches/01_std-isnan.patch` isn't picked up, it needs to be renamed to `patches/hyperion-01_std-isnan.patch`
* had to remove `-DENABLE_WS281XPWM=1`, the source tarball contains an empty external folder (external/rpi_ws281x/mailbox.c is missing and cmake fails)
* I had qmake-qt4 installed on the buildhost and that was picked up instead of the locally built qmake (FindQt4 searches for qmake-qt4 first, then qmake...). But that can easily be fixed by adding the `-DQT_QMAKE_EXECUTABLE=$SYSROOT_PREFIX/bin/qmake` cmake option

With these fixes the addon installed and worked fine on my RPi3, using the USB adalight driver.

Only a minor issue: it would be nice if `.kodi/userdata/addon_data/service.hyperion` could be created automatically and the hyperion.config.json.sample file copied over there.

**Comment by stefansaraev** [comment]
thanks for the feedback @HiassofT 

indeed, kodi/userdata/addon_data/service.hyperion is automaticaly created on first addon start, but it is not started because of a missing configfile. that was done by intention as I've got segfaults with shipped config. here a quick fix

http://sprunge.us/FJQC

**Comment by HiassofT** [comment]
Running hyperion with the sample config file might be risky - it uses /dev/spidev0.0 and if an RPi user has SPI enabled and connected something else then ouch.

I found the .sample and ConditionPathExists approach cleaner, so if there's no easy solution better keep this as is.

**Comment by stefansaraev** [comment]
one could sed out the spidev part (to /dev/null, /me runs). as we do for effects dir.

**Comment by lrusak** [comment]
Thanks, I updated with the suggested changes

**Comment by HiassofT** [comment]
@lrusak we currently also need `-DENABLE_WS281XPWM=0`. Looks like the external dependencies (protobuf and rpi_ws281x) are also missing in the V1.00.0 release tarball.

@stefansaraev  As for the config file/dir, how about something like this?
https://gist.github.com/HiassofT/b5ada3a42b4756effce1

After installation the addon_data directory is created and a .sample file put there, hyperiond won't start but log a message so users can find out why and what to do.

People will usually create hyperion.config.json from scratch using HyperCon, so we might as well drop the .sample file. Telling them to adjust the path to the effects directory would be enough IMHO.

**Comment by stefansaraev** [comment]
you need https://github.com/stefansaraev/TB/commit/57d4835286fe0fe5afbf34acb192bcee457b0244 for next version bump

**Comment by stefansaraev** [comment]
and. btw, for WS281XPWM. you have to package it yourself and do:
```
git submodule init
git submodule update
```

before creating source archive.

**Comment by lrusak** [comment]
updated

**Comment by CvH** [comment]
fyi @brindosch has updated HyperCon (V1.01.2) and add support for LE - needs to be tested if this work.

**Comment by lrusak** [comment]
I made a mkpkg script to recursively get the sources.

I now get an error when using `-DENABLE_WS2812BPWM=1`
Perhaps someone else can take a look at this?

**Comment by InuSasha** [comment]
Hyperion needs the OpenGL driver as dependency (on RPi for example bcm2835-driver)

**Comment by lrusak** [comment]
I've already added it. I'm just testing if it builds on all platforms before pushing

**Comment by lrusak** [comment]
This should be good to go now other than the `-DENABLE_WS2812BPWM=1` problem

**Comment by HiassofT** [comment]
I think it's fine to leave the ws2812b driver disabled and only compile the ws281x driver. According to the Hyperion wiki it seems ws2812b was only for RPi1 and the newer ws281x works on RPi1-3
https://github.com/tvdzwan/hyperion/wiki/WS2812b-PWM-led-devices

I have to add that I have no ws2812 device and haven't used any of these drivers myself though

**Comment by lrusak** [comment]
Then we should be good to merge :+1:

**Comment by brindosch** [comment]
There is a little issue that is not mentioned
WS2812B driver works just for RPi1 yes, but the WS281X driver works not for RPi1 if you use WS2812B leds. (WS2811 is also another type...) Not that easy ;)

**Comment by InuSasha** [comment]
Tested with OE6.0.3 on RPi2: works fine, too

**Comment by chewitt** [comment]
our RPi1 userbase is 10% the size of RPi2 so we'll take a gamble :)

**Comment by stefansaraev** [comment]
just push it and create/upload an addon so more people can test it ;)

**Comment by brindosch** [comment]
sorry for a little OT here: i saw a preview of the addon
http://addons.libreelec.tv/7.0/Generic/x86_64/service.hyperion/service.hyperion-7.0.0.zip
Is there a reason why you bundle no hyperion-v4l2 which is needed for screenshots if you use a usb grabber too?

**Comment by stefansaraev** [comment]
when I started initial packaging, it turned out that protobuf was a bitch to cross compile, and I didnt have any hardware to test it, anyway :)

I may re-try next few days if I find some time.

**Comment by stefansaraev** [comment]
nope. hyperion wont compile with external protobuf, too much trouble :)

**Comment by Kwiboo** [comment]
@stefansaraev I use external protobuf with hyperion together with a patch to use a simple find_package to find protobuf, works for me on RPi and Generic, hope it can be of any use.

protobuf: https://github.com/RasPlex/OpenPHT-Embedded/commit/9f35d28eede65d85ef34228ff5587ba32741f664
hyperion-patch: https://github.com/RasPlex/OpenPHT-Embedded/commit/62e065d47f2796714a96aa47b112d4dff96ebdb7#diff-97772625ba924905d80ee5787c2d186a

**Comment by stefansaraev** [comment]
great. thank you @Kwiboo. my initial protobuf OE package is at https://github.com/stefansaraev/TB/commit/f66dc804faaa7a4b1660bf7128c0888b2ba79160
(needs minor adjustments for OE buildsystem)

will test your hyperion patch later tonight.

**Comment by stefansaraev** [comment]
yep. at least compiles fine. I cant runtime test. updated my protobuf branch. /cc @lrusak

**Pull request merged**
