### PR TITLE
open-iscsi: allow installing utilities for target

### PR DESCRIPTION
**Pull request by lrusak**
This allows using the iscsiadm at all utilities from userspace.

I added a patch that was adapted from fedora sources (the patch doesn't apply). https://src.fedoraproject.org/rpms/iscsi-initiator-utils/blob/rawhide/f/0006-use-var-for-config.patch
The patch is needed to move configuration to r/w space.

`open-iscsi:target` depends on `open-iscsi:host` because of `iscsi-iname` which is used to create a unique initiator name for the target.

I tested this on my RPi4
```
# uname -a
Linux LibreELEC 5.15.32 #1 SMP Wed May 4 19:30:26 PDT 2022 aarch64 GNU/Linux

# iscsiadm -m discovery -t st -p 192.168.1.108
192.168.1.108:3260,1 iqn.2022-05.fedora-enterprise.xxxxxxxxx.com:lun1

# iscsiadm -m node -T iqn.2022-05.fedora-enterprise.xxxxxxxxx.com:lun1 -l
Logging in to [iface: default, target: iqn.2022-05.fedora-enterprise.xxxxxxxxx.com:lun1, portal: 192.168.1.108,3260] (multiple)
Login to [iface: default, target: iqn.2022-05.fedora-enterprise.xxxxxxxxx.com:lun1, portal: 192.168.1.108,3260] successful.
```

### CODE REVIEW

**Comment by CvH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/pull/6356

**Comment by lrusak** [comment]
Merge?

**Comment by chewitt** [comment]
@CvH Correct that #6356 removed distro boot-time iSCSI support but there's nothing to stop post-boot mount/use of iSCSI disks (aside from SMB or NFS being considerably easier).

**Comment by lrusak** [comment]
> @CvH Correct that #6356 removed distro boot-time iSCSI support but there's nothing to stop post-boot mount/use of iSCSI disks (aside from SMB or NFS being considerably easier).

iSCSI boot support is actually still there, it's just iSCSI support in general isn't included by default anymore.

There is no reason to rip it out really as it's quite harmless to support still. It's also quite easy to setup an iSCSI target to test with.

**Comment by CvH** [comment]
> It's also quite easy to setup an iSCSI target to test with.

speaking of experience, nobody did in the past and nobody does in the future

We have likely near to zero usage of it and mainstream NAS/NAS-distributions don't ship it by default anyway.
iSCSI is targeted for "professional" environments and even there it is basically old tech

No problem to keep it in tree but I am not too hot for enabling it again for the one guy, somewhere, that never heard of NFS before.

**Review by CvH — APPROVED** [review]

**Pull request merged**
