### PR TITLE
libdvbcsa: add NEON support on aarch64

### PR DESCRIPTION
**Pull request by piotrasd**
more here:
https://github.com/glenvt18/libdvbcsa/commit/1613dd4071c6d7291a88eed2a2938e2a94ee2849

just switched commit to brach with NEON for aarch64
but i can if you want make a patch ... (that only 1 commit more compare to master)

### CODE REVIEW

**Comment by CvH** [comment]
ping @glenvt18 is this working and okay to include ?

**Comment by glenvt18** [comment]
I've just updated arm64 branch. I've only tested it with QEMU and have no aarch64 device at the moment. Well, it should work. If you have an Odroid-C2 device it can be easily tested. Copy the executables from libdvbcsa-XXXX/test directory to your device's /tmp, cd /tmp and run
```sh
./testenc && ./testdec && ./testbsops && ./testbitslice && seq 10 | xargs -n1 ./benchbitslice
```
The build option is `--enable-neon`. You'll probably have to modify package.mk to make use of NEON because, as I see, TARGET_FPU variable is not set when building for AArch64. If the build option is picked correctly, you should see
```
 - Generating batch with 128 randomly sized packets
```
while running benchbitslice.

If you have an Ubuntu machine, you can quickly cross-compile it without LibreELEC:
```sh
sudo apt-get -y install gcc-aarch64-linux-gnu make autoconf automake libtool git
mkdir -p /tmp/build
cd /tmp/build
git clone https://github.com/glenvt18/libdvbcsa.git
cd libdvbcsa
git checkout arm64
./configure --enable-neon --with-sysroot=/usr/aarch64-linux-gnu --disable-shared --enable-static --host=aarch64-linux-gnu
make -j2
scp test/* YOURDEVICE:/TESTDIR
```
Or, download the executables built by me:
https://drive.google.com/open?id=0BxEZpdTX1bPvT2N6UmZTTlprbDQ

Pls, upload the benchmark results.
If it works OK, I'll merge that commit to the master.

**Comment by lrusak** [comment]
I can't even build it for aarch64 with `--enable-neon`

http://sprunge.us/NFUY
```
/home/lukas/libreelec/build.LibreELEC-Odroid_C2.aarch64-8.0-devel/libdvbcsa-1613dd4/test/testbsops.c:161:20: error: incompatible type for argument 1 of 'vcombine_u64'
   a = BS_VAL(0xabcdef1331fedcbaLL,
                    ^
In file included from /home/lukas/libreelec/build.LibreELEC-Odroid_C2.aarch64-8.0-devel/libdvbcsa-1613dd4/src/dvbcsa_bs_neon.h:29:0,
                 from /home/lukas/libreelec/build.LibreELEC-Odroid_C2.aarch64-8.0-devel/libdvbcsa-1613dd4/src/dvbcsa_bs.h:50,
                 from /home/lukas/libreelec/build.LibreELEC-Odroid_C2.aarch64-8.0-devel/libdvbcsa-1613dd4/test/testbsops.c:24:
/home/lukas/libreelec/build.LibreELEC-Odroid_C2.aarch64-8.0-devel/toolchain/lib/gcc/aarch64-libreelec-linux-gnueabi/6.2.0/include/arm_neon.h:5152:1: note: expected 'uint64x1_t' but argument is of type 'long unsigned int'
 vcombine_u64 (uint64x1_t __a, uint64x1_t __b)
 ^~~~~~~~~~~~
/home/lukas/libreelec/build.LibreELEC-Odroid_C2.aarch64-8.0-devel/libdvbcsa-1613dd4/test/testbsops.c:161:54: error: incompatible type for argument 2 of 'vcombine_u64'
   a = BS_VAL(0xabcdef1331fedcbaLL,
```

**Comment by glenvt18** [comment]
@lrusak It's fixed in glenvt18/libdvbcsa@97898b085d7e78c42e6fd03b1c1622a418ebd735. Pls update your hash.

**Comment by lrusak** [comment]
Thanks, I just used the hash in this PR

**Comment by lrusak** [comment]
seems to work ok

http://sprunge.us/SIBV

this is on my Odroid_C2

**Comment by glenvt18** [comment]
@lrusak Thanks. Those 190 Mbit/s are quite impressing! It's 85% of an old Atom performance. Can you build it without --enable-neon or with --enable-uint64 to see how faster it is. Just for curiosity's sake.

**Comment by lrusak** [comment]
Without `--enable-neon`
http://sprunge.us/MBIH

Not sure if this makes sense or not :/

**Comment by glenvt18** [comment]
Yes. Looks strange. It's 4-5x faster than on RPi2. Are you sure no other process was loading the CPU when the NEON test was running? Well, there might be some room for improvements as well. Could you run it with --enable-uint32 to be sure the figures are right?

**Comment by lrusak** [comment]
I re-ran the tests, I stopped all non essential processes.

without `--enable-neon`
http://sprunge.us/YIZF

with `--enable-neon`
http://sprunge.us/dRSC

with `--enable-uint64`
http://sprunge.us/egPW

with `--enable-uint32`
http://sprunge.us/Ohhi

**Comment by Raybuntu** [comment]
I was trying to build it for Odroid C2 with 32bit userspace but I'm getting a "Core dumped" in the tests:

`LibreELEC:~/test # ./testenc && ./testdec && ./testbsops && ./testbitslice && seq 10 | xargs -n1 ./benchbitslice
* CSA encryption *
 test 1
 test 2
* Done *
* CSA decryption *
 test 1
 test 2
* Done *
Ok
* DVBCSA test *
 - Generating batch with 128 randomly sized packets
 - Encrypting each packet using dvbcsa_encrypt()
 - Decrypting batch using _bitslice_ dvbcsa_bs_decrypt()
 - Checking results...
 - Decrypting each packet using dvbcsa_decrypt()
Bus error (core dumped)
`

**Comment by glenvt18** [comment]
@Raybuntu Could you try glenvt18/libdvbcsa@a2bde6fa52a5b6f54d67c9d80aa8e3fad02e4557

**Comment by Raybuntu** [comment]
I still have a bus error.

**Comment by glenvt18** [comment]
@Raybuntu Could you try this: glenvt18/libdvbcsa@7e760ea96e1c5da15cd8f86f03c24afc0d222dea

**Comment by Raybuntu** [comment]
@glenvt18 still the same effect

**Comment by glenvt18** [comment]
@Raybuntu Do you have a bus error only if built with --enable-neon?

**Comment by Raybuntu** [comment]
@glenvt18 No I have it anyway. Pretty sure it's due to 64bit kernel and 32bit userspace.
Maybe I did something wrong building it. I just copied the directory build.LibreELEC-Odroid_C2.arm-8.0-devel/libdvbcsa-f988715/.armv8a-libreelec-linux-gnueabi/test to my device and ran your command.

**Comment by glenvt18** [comment]
@Raybuntu I guess you just copied git content fo libdvbcsa-f988715 (because this is a wrong hash). If so, it's OK. You can manually check the file src/dvbcsa_pv.h to see
```C
#if defined(__aarch64__)
//#define DVBCSA_UNALIGNED_ACCESS_32 1
//#define DVBCSA_UNALIGNED_ACCESS_64 1
#endif

```
I see you use an aarch64 toolchain here and it should define `__aarch64__`.  You can put #error here
```C
#if defined(__aarch64__)
#error aarch64 defined
//#define DVBCSA_UNALIGNED_ACCESS_32 1
//#define DVBCSA_UNALIGNED_ACCESS_64 1
#endif
```
just to make sure.

BTW. How do you build 64 bit kernel and 32 bit userspace? Is there a LibreELEC option for that?
As for RPi3, it is built using the options for RPi2, hence armhf toolchain is used, and it builds armhf binaries, and they should work the same way as on RPi2. Or, am I wrong? Have you had bus errors previously?

**Comment by glenvt18** [comment]
@lrusak Thanks for testing. So we have neon bandwidth = 0.91 of uint64 bandwidth (which is 210 Mbits), and uint32 bandwidth = 0.8 of uint64. The latter is really odd. There are, probably, some bottlenecks. Could you run some specially built benchmarks from here?
https://drive.google.com/file/d/0BxEZpdTX1bPvdU91S0plaDBueHM
Extract it to /tmp and run `./run-bench.sh | tee benchmarks.txt`

**Comment by Raybuntu** [comment]
@glenvt18 : The commit looks odd because my last try was with the original commit that will change through this PR. And I'm seeing the same bus error even without this PR and your commits. So it's probably an issue with 32bit userspace with arm64 kernel.

Currently it's not possible to build LE with 64bit kernel and 32bit userspace in master. This is more like a personal project of mine. I'm using a prebuilt aarch64 toolchain to built Kernel and kernel drivers. The rest is built with 32bit toolchain. I did not use libdvbcsa before to be honest, I was asked to test this.

` toolchain/bin/armv8a-libreelec-linux-gnueabi-gcc -dM -E - </dev/null|grep -i arm
#define __ARM_SIZEOF_WCHAR_T 4
#define __ARM_FEATURE_SAT 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARMEL__ 1
#define __ARM_FEATURE_UNALIGNED 1
#define __ARM_FEATURE_IDIV 1
#define __ARM_FP 14
#define __ARM_ARCH_8A__ 1
#define __ARM_NEON_FP 6
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_PCS_VFP 1
#define __ARM_FEATURE_LDREX 15
#define __ARM_FEATURE_QBIT 1
#define __ARM_FEATURE_FMA 1
#define __ARM_NEON__ 1
#define __ARM_ARCH_PROFILE 65
#define __ARM_32BIT_STATE 1
#define __ARM_FEATURE_CLZ 1
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH 8
#define __arm__ 1
#define __ARM_FEATURE_SIMD32 1
#define __ARM_NEON 1
#define __ARM_ARCH_EXT_IDIV__ 1
#define __ARM_EABI__ 1
#define __ARM_FEATURE_DSP 1`

**Comment by Raybuntu** [comment]
@glenvt18 When I comment this out:
```
#if defined(__arm__) && defined(__ARM_FEATURE_UNALIGNED)
#error arm defined
/* only 32 bit unaligned access is allowed for armv6, armv7, armv8 */
//#define DVBCSA_UNALIGNED_ACCESS_32 1
#endif
```
I have no bus error.

**Comment by glenvt18** [comment]
@Raybuntu So if you don't define DVBCSA_UNALIGNED_ACCESS_32 it works, right?

libdvbcsa tries to use unaligned memory access on some platforms to speed-up things. GCC just defines `__ARM_FEATURE_UNALIGNED` on ARM platforms that support it - armv6, armv7, armv8. It looks like on your device unaligned memory access is disabled - turned off by the kernel (for what purpose?). This is not typical and GCC is unaware of it. Could you grep your kernel config for `ALIGNED`? As a workaround you can add `-mno-unaligned-access` to your CFLAGS. In this case GCC won't define `__ARM_FEATURE_UNALIGNED`. Could you try? It's better to add it to the global CFLAGS to affect all userspace software. But libdvbcsa's performance will suffer. Could you pls upload the result of
```
./testenc && ./testdec && ./testbsops && ./testbitslice && seq 10 | xargs -n1 ./benchbitslice
```

BTW. Your build has nothing to do with `arm64` branch - it's for 64 bit. You'll get bus errors starting with glenvt18/libdvbcsa@e01862274c919a5d5cf777bb662a3eda3ac2f0cf.

**Comment by Raybuntu** [comment]
@glenvt18 Thanks! Yes if I disable it it is working.

This is a Odroid C2 we are talking about and I'm using the same kernel config like for aarch64.
```
grep ALIGNED linux.aarch64.conf
# CONFIG_HAVE_64BIT_ALIGNED_ACCESS is not set
CONFIG_HAVE_EFFICIENT_UNALIGNED_ACCESS=y
```

Yes currently I'm thinking adding `-mno-unaligned-access` to global CFLAGS.

**Comment by glenvt18** [comment]
@Raybuntu Global `-mno-unaligned-access` will also affect code generation and hit performance of some applications.

BTW. Take a look at your `/proc/cpu/alignment`. On my RPi2 I have
```
User:           0
System:         6 (implement+0x9c/0x12c)
Skipped:        0
Half:           0
Word:           0
DWord:          6
Multi:          0
User faults:    2 (fixup)
```
Details:
https://www.kernel.org/doc/Documentation/arm/mem_alignment

**Comment by Raybuntu** [comment]
@glenvt18: I don't have a "/proc/cpu/alignment". C2 has 3.14 kernel.

**Comment by glenvt18** [comment]
@Raybuntu `CONFIG_DEBUG_KERNEL`? You're right. That's a bit off topic. Thanks for testing.

**Comment by glenvt18** [comment]
Summarizing. libdvbcsa works on AArch64 and works well. Achieved performance of 210 Mbit/s is pretty good for every day use. Although the best option is uint64 which is the default for AArch64, `arm64` branch is still needed because it enables 64 bit unaligned access which is important for performance. 

As for this PR, I would suggest adding a note like this:
glenvt18/LibreELEC.tv@e12ffb826894ed62fbd0c35b308f26d46ccb2eef
This would help to avoid further PRs and questions like "Why NEON is not enabled for AArch64?".
I can make a PR from that commit if everyone agrees.

I think further libdvbcsa discussions, testing etc. should move to
https://github.com/glenvt18/libdvbcsa/issues

@lrusak Benchmarking results from you can help a lot. They're the only source of information I can get now because I don't have an AArch64 device.

**Comment by Raybuntu** [comment]
Thanks @glenvt18 for your help. I will investigate it further and I'll take libdvbcsa as a reference. Once I have unaligned working I'll pubish those results. Without unaligned memory access I have 150mbit/s on my Odroid C2.

**Comment by CvH** [comment]
@glenvt18 yes pls pr :) tx for feedback !

**Comment by glenvt18** [comment]
@Raybuntu You can use this small program instead of libdvbcsa:
http://pastebin.com/0g9AwYbP
It simply reads 8, 16, 32 or 64 bit words from a 8-byte aligned buffer at a given offset:
```
./uatest 1 4    bus error
./uatest 0 8    ok
etc.
```
You can easily get bus errors with it.

**Comment by kszaq** [comment]
@glenvt18 I did some tests on my aarch64-kernel target and the results for `uatest` are:
* **ARM** binary with **Aarch64** kernel: bus error for `uatest 1 8`, `uatest 2 8`, `uatest 3 8` etc.
* **Aarch64** binary with **Aarch64** kernel: no bus errors

On the other hand I did some tests on my **ARM** target (S805) and when I configure alignment trap to `echo 5 > /proc/cpu/alignment` I can also generate bus error when running libdvbcsa tests.

https://www.kernel.org/doc/Documentation/arm/mem_alignment
Does this mean that something is wrong in libdvbcsa or should I expect this? 

With `echo 5 > /proc/cpu/alignment` Kodi is running OK.

**Comment by glenvt18** [comment]
@kszaq Yes. `uatest 1 8` should normally cause bus errors only on ARM (armv6+), not on AArch64 which is just like x86_64. `uatest 1 [2,4]` should work fine on ARM.

Unaligned access is controlled by bit A of the System Control Register (SCTLR):
```
[1]	A bit 	Banked	Enables strict alignment of data to detect alignment faults in data accesses:
    0 = strict alignment fault checking disabled. This is the reset value.
    1 = strict alignment fault checking enabled.
```
SCTLR can't be accessed from user mode. So S805's kernel (or, maybe, even u-boot) somehow (for some reason) sets this bit. I can't catch the idea behind it. It's a mystery:) And I just don't know how to read the A bit from userspace. That's why I suggested `uatest`.

"Good written" portable programs like Kodi shouldn't ever use unaligned access. It can only be used for the performance sake in compressors, networking, ciphers etc. ... and libdvbcsa.

I've just run libdvbcsa tests together with `uatest` on Allwinner and RPi2. Both are cortex-a7 and behave as expected (as your first test).

Note that libdvbcsa doesn't detect anything at runtime. Everything (alignment, endianess, simd) must be configured at build time. It relies on the toolchain for alignment and endianess. For example, if you build it with LE toolchain and run in a BE environment it will fail. Unaligned access is only enabled for known platforms. So, if you didn't supply `-mno-unaligned-access` while building and your target is ARMv6,7,8, 32 bit (but not 64 bit) unaligned access is enabled. 

BTW. `/proc/cpu/alignment` has a `User` counter which is updated for the whole system session. It can be useful to detect alignment violations by other programs. There is no need to write 4 or 5 to `/proc/cpu/alignment`. But bus errors are easier to catch by eye.

**Comment by kszaq** [comment]
@glenvt18 Thank you for taking your time to explain! I only wanted to note some things as I have zero previous knowledge on this. ;)

Just to be clear, libdvbcsa tests run just fine on S805 (which is Cortex-A5@1.5GHz), giving ~110Mbps with unaligned access turned on. With `-mno-unaligned-access` I'm getting ~60Mbps. With unaligned access enabled I am not getting bus errors until I do `echo 5 > /proc/cpu/alignment` - which is expected?

For S905 (Cortex-A53@1.5GHz, Aarch64 kernel) it looks like 32-bit applications behave as if I set `echo 5 > /proc/cpu/alignment`. I can only run libdvbcsa tests with `-mno-unaligned-access` and then I'm getting ~130Mbps.

**Comment by Raybuntu** [comment]
@glenvt18: I've been doing tests with uatest too. First uatest compiled with 32bit armhf toolchain, running under 64bit arm64 kernel with 32bit userland:
```
LibreELEC:~ # ./uatest.arm 0 4
got: 5a5a5a5a
LibreELEC:~ # ./uatest.arm 1 4
got: 5a5a5a5a
LibreELEC:~ # ./uatest.arm 2 4
got: 5a5a5a5a
LibreELEC:~ # ./uatest.arm 3 4
got: 5a5a5a5a
LibreELEC:~ # ./uatest.arm 4 4
got: 5a5a5a5a
LibreELEC:~ # ./uatest.arm 5 4
got: 5a5a5a5a
LibreELEC:~ # ./uatest.arm 2 4
got: 5a5a5a5a
LibreELEC:~ # ./uatest.arm 1 8
Bus error (core dumped)
```

Now uatest compiled with 64bit aarch64 toolchain running under 64bit arm64 kernel with 64bit userland:

```
LibreELEC:~ # ./uatest.aarch64 1 8
got: 5a5a5a5a5a5a5a5a
LibreELEC:~ # ./uatest.aarch64 1 4
got: 5a5a5a5a
LibreELEC:~ # ./uatest.aarch64 2 4
got: 5a5a5a5a
LibreELEC:~ # ./uatest.aarch64 0 8
got: 5a5a5a5a5a5a5a5a
LibreELEC:~ # ./uatest.aarch64 3 8
got: 5a5a5a5a5a5a5a5a
LibreELEC:~ # ./uatest.aarch64 8 8
got: 5a5a5a5a5a5a5a5a
LibreELEC:~ # ./uatest.aarch64 5 8
got: 5a5a5a5a5a5a5a5a
LibreELEC:~ # ./uatest.aarch64 5 4
got: 5a5a5a5a
LibreELEC:~ # ./uatest.aarch64 10 4
got: 5a5a5a5a
LibreELEC:~ # 
```

If I understand it correctly it's what we are expecting?

**Comment by glenvt18** [comment]
@kszaq On 32 bit ARM (S805 and S905 in 32 bit mode): if you write `echo 5 > /proc/cpu/alignment`, `./uatest 1 2`, `./uatest 1 4` and libdvbcsa test are expected to work. `./uatest 1 8` should always fail with bus error. `./uatest 1 4` and libdvbcsa should always work the same way. If they behave differently, there is probably a bug in libdvbcsa we should look into. Here I assume libdvbcsa is compiled without `-mno-analigned-access`.

@Raybuntu Yes, that's how it should be. But while `./uatest 1 4` works on 64/32, libdvbcsa test fails, right? If so, see below.

@kszaq @Raybuntu This PR is closed and our discussion is barely connected to LibreELEC. So, I suggest you to open an issue like "Unaligned access on Amlogic ARMs" under
https://github.com/glenvt18/libdvbcsa/issues
and refer to this PR from there.

**Comment by chewitt** [comment]
Closing as superseded by https://github.com/LibreELEC/LibreELEC.tv/pull/1058

**Pull request closed without merging**
