### PR TITLE
Drop X11

### PR DESCRIPTION
**Pull request by lrusak**
This is the bulk of the work required to get the Generic platform to not use X11 anymore :tada: 

This also removes tier 1 support for Nvidia. I have added nouveau support but because there is no reclocking support in nouveau, hw accelerated video decode won't work properly. I've added nouveau so if people do upgrade they won't be left with a blank screen. Sorry Nvidia lovers :heart: 

This also moves the Generic platform to use OpenGLES instead of OpenGL. This isn't super critical but some features in Kodi are lost (dithering, sw support for some 10bit formats, colour management (which LE didn't support anyways), etc). The reason for this change is that it is impossible currently to build OpenGL without x11 as it is tied to glx. @a1rwulf is working on this and has some patches but it depends on what upstream (mesa, libglvnd, kodi) want to support. So any add-ons that require OpenGL will need to be rebuilt to use OpenGLES which isn't really a big deal. If support for OpenGL without X11 is gained in the future we can always switch back. :1st_place_medal: 

The next thing is that this PR doesn't include the cleanup work to remove references to X11. This only includes the functional changes and dropping of X11 related packages. The cleanup can happen after this. :wastebasket: 

The next issue is that chrome/chromium will not work anymore. If people want this or care about it I suggest they look into running wayland/weston and/or the ozone backend in chromium.

So here it is, after almost 2 years of work we are finally here. :chart_with_upwards_trend:

### CODE REVIEW

**Comment by BellaCoola** [comment]
Dropping X11 would be great, but as far as I know, Intel GPUs need xrandr to switch to full-range output. Here is the current shell script: [intel-fullrange.sh](https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Generic/filesystem/usr/bin/intel-fullrange.sh)

**Comment by lrusak** [comment]
> Dropping X11 would be great, but as far as I know, Intel GPUs need xrandr to switch to full-range output. Here is the current shell script: [intel-fullrange.sh](https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Generic/filesystem/usr/bin/intel-fullrange.sh)

The same thing can be done with the `proptest` utility from libdrm

**Comment by BellaCoola** [comment]
> > Dropping X11 would be great, but as far as I know, Intel GPUs need xrandr to switch to full-range output. Here is the current shell script: [intel-fullrange.sh](https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Generic/filesystem/usr/bin/intel-fullrange.sh)
> 
> The same thing can be done with the `proptest` utility from libdrm

Well that's great to know! Everywhere I looked on the internet, the xrandr method was listed as the only option. Sorry for misinformation. :)

**Comment by lrusak** [comment]
> > > Dropping X11 would be great, but as far as I know, Intel GPUs need xrandr to switch to full-range output. Here is the current shell script: [intel-fullrange.sh](https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Generic/filesystem/usr/bin/intel-fullrange.sh)
> > 
> > 
> > The same thing can be done with the `proptest` utility from libdrm
> 
> Well that's great to know! Everywhere I looked on the internet, the xrandr method was listed as the only option. Sorry for misinformation. :)

It won't really matter though as we will most likely just expose the atomic property in kodi then we can just switch it ourselves using the normal Kodi setting

**Comment by smp79** [comment]
Would it be possible to set custom video modes without _xrandr --newmode_?

**Comment by lrusak** [comment]
> Would it be possible to set custom video modes without _xrandr --newmode_?

Not that I'm aware of

**Comment by CvH** [comment]
this needs a rebase

**Comment by smp79** [comment]
Why this was closed?

**Pull request closed without merging**
