### PR TITLE
linux: enable and unify VLAN_8021Q support over all projects/devices

### PR DESCRIPTION
**Pull request by rdorsch**
Recreated pull request, since it did not survive renaming a branch. Previous pull request was

https://github.com/LibreELEC/LibreELEC.tv/pull/7228

See also discussion and comments there.

### CODE REVIEW

**Comment by jernejsk** [comment]
see my last comment on previous PR

**Comment by rdorsch** [comment]
I must have forgotten to commit these changes. Thanks for pointing this out.

**Comment by rdorsch** [comment]
I created the pull request for le10 as well: https://github.com/LibreELEC/LibreELEC.tv/pull/7237

**Review by heitbaum — APPROVED** [review]

**Comment by lrusak** [comment]
It would probably be good to start a `net` section in the kernel_options and add this to it.

https://github.com/LibreELEC/LibreELEC.tv/blob/master/distributions/LibreELEC/kernel_options

**Pull request merged**
