### PR TITLE
projects/Amlogic: update kernel version and kernel config

### PR DESCRIPTION
**Pull request by kszaq**
This PR:
* bumps amlogic-3.14 kernel version to latest linux-amlogic revision
* updates kernel config for projects/Amlogic and removes an already applied patch

Reasons for kernel options are listed in commit message.

As a bonus, projects/Amlogic now compiles. Runtime tested on a S905X device.

### CODE REVIEW

**Comment by kszaq** [comment]
Added WIP label to discuss kernel options for media drivers.

My suggestion is to add IR drivers (especially ir-meson) and not include other modules, e.g. DVB as these are outdated in 3.14 and users should download one of media addons instead.

**Comment by Raybuntu** [comment]
Currently we have no dvb addons upstreamed for AML. Even though they are outdated they might be more stable than those experimental media build ones. I'd like to keep the config similar to C2, WH and WP2 so those can be moved under the Amlogic project someday.

**Comment by adamg88** [comment]
I agree with you @kszaq media drivers should not be included, they should be handled by crazycat, I also agree with @Raybuntu the config should be similar to C2/Wetek to support potentially merging them in the future.

On a side note, none of the dvb supporting code has been commited/PR'd yet

**Comment by adamg88** [comment]
I just noticed you disabled CONFIG_VM_EVENT_COUNTERS I think @MilhouseVH enabled this previously so he may want that retained

**Comment by kszaq** [comment]
Thank you @adamg88 for your review.

I will re-enable VM_EVENT_COUNTERS, you are correct that they were enabled in all projects.

I will check what is missing to support S912.

**Comment by kszaq** [comment]
@adamg88 Have you compiled a device tree for U9 specifically for this kernel? Unfortunately device trees changed again and you can't use these: https://kszaq.libreelec.tv/s912/8.2/device_trees/

**Comment by adamg88** [comment]
@kszaq no I used the one from the link above, I will test again later and let you know thanks

**Comment by kszaq** [comment]
Thank you @adamg88 for confirming that it works. I have updated kernel config re-enabling VM_EVENT_COUNTERS and rc drivers. Will test is and should be good to go.

**Comment by kszaq** [comment]
This PR is good to go if there are no objections.

@adamg88 I uploaded all device trees for the updated kernel: https://kszaq.libreelec.tv/s905/9.0/device_trees/

**Comment by Raybuntu** [comment]
Imho it would be good to have some basic media/dvb support like we have on C2, WH and WP2. Mediabuild will always be experimental. For instance I'm using Sundtek DVB devices and therefore don't need any mediabuild.
So either add those now or in a separate PR before we enable crazycat for S905 later. I can also do this in my crazycat PR if that's better?

**Comment by adamg88** [comment]
Ray I think it would be better to leave it till it's enabled in crazycat, community builds can fill the void until then seeing as it will be some time before there is an Official LE release for Aml.

**Comment by kszaq** [comment]
Sure, I can align media config to WeTek/C2.

**Comment by kszaq** [comment]
Media config copied from Odroid_C2 and redacted by running `make menuconfig`.

Builds and runs.

**Pull request merged**
