### PR TITLE
Fix net-snmp addon build

### PR DESCRIPTION
**Pull request by Celedhrim**
Hi,

This pull request give a fully functionnal net-snmp daemon.
See https://forum.libreelec.tv/thread/2997-snmpd/?postID=68955#post68955

Test on wetek play 2 and Rpi2 sucessfully on 8.2.0 release

I request pull to master , but making it available to libreleec 8 would be great !

### CODE REVIEW

**Comment by CvH** [comment]
@Celedhrim could you add information from where the patch ordinates and what it fixes ?! 

Also after looking into the mess upstream it might be better to use an recent developer version? 

There are "several" patches which are not included at the ancient 5.7.3 .
https://github.com/CvH/net-snmp/compare/v5.7.3...V5-7-patches that doesn't looks too trustworthy.

**Comment by Celedhrim** [comment]
@CvH , The real main issue was the enable mini-agent.

the patch for config.sub was made by me was with the official new config.sub from the one using URL given in actuel headers

```
# You can get the latest version of this script from:
# http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
```

For a most recent version , why not but 5.7.3 is the lastest release with LTS support

I'm not a developper and I just make it work primary for me , I have update config.sub to recognize new arch ( aarch64 for wetek play 2 ) to help the configure script to load good mib.

Actually , the snmp addon is just an empty shell ( daemon run but return nothing about system , this PR make it work , maybe improvement can be for another PR :)

My goal was just making it work , sorry if it was'nt the right way .

(And excuse me for my english , I'm french ^^)

**Comment by CvH** [comment]
> For a most recent version , why not but 5.7.3 is the lastest release with LTS support

I asked because there are 800+ commits/patches at the 5.7 LTS branch (since last patch release 3yrs ago) that fix compiling/usage at recent Perl, OpenSSL and other stuff that looks like it hit us sooner or later. I have no idea why there are no updates at the meantime (3yrs no update ...) as it looks rather scary to have a minor patch release with that amount of new stuff. I am not claiming to have a single idea about it, just the commit history (from the future 5.7.4) looks a bit scary compared to the current .3 release.

> I have update config.sub to recognize new arch ( aarch64 for wetek play 2 ) to help the configure script to load good mib.
- Are these changes PRed for upstream merging? I ask this because we had already several patches that wasn't merged/PRed upstream and then failed to work -> creates mess downstream.
- would this patch work too ? https://sourceforge.net/p/net-snmp/patches/1329/

> sorry if it was'nt the right way

I am just asking as likely nobody from us have a deeper knowledge about that addon and as long somebody is here that knows a bit about it I try to gather as much as possible information :)

**Comment by Celedhrim** [comment]
> would this patch work too ? https://sourceforge.net/p/net-snmp/patches/1329/

Yes ! :)

I first use this patch , but it's aarch64 specific , I used config.sub update from net-smnp to have a more "global update", I was thinking this patch could resolve 'my' issue , not every recent arch issue.

Concerning snmp having more than 800 patch since last release , I would say , it's snmp issue , not libreleec , but I really appreciate that would do things right and not just do thing.

But snmp is cleary too inactive :(

If you want I can try with new new patch on 5.7 net-snmp , but if this PR give a working snmp daemon for libreelec , it's already a great step , having a better snmp, it a second step ( that's only my point of view :))

to be clear , I make snmp addon just work , I don't try to improve it :)

**Comment by CvH** [comment]
> to be clear , I make snmp addon just work , I don't try to improve it :)

yea fair point, would be nice if you could give it a go at the lastest 5.7.x branch if it still works ;)

Btw you need to bump `PKG_REV="102"` -> `PKG_REV="103"` and also add an entry at the changelog.txt.
Tbh I have always my problems with large patches that are unlikely to get merged upstream. 

Btw is there a way to trim the patch down to just the stuff LE needs (sparc, ia16, bsd ... specific stuff)? 
I removed some stuff, should be enough for LE I think? https://pastebin.com/nAuYpvPK

**Comment by chewitt** [comment]
v102 was a bump to handle the LibreSSL/OpenSSL change, if you want to document it.

**Comment by Celedhrim** [comment]
It seems it was just a bump 

https://github.com/LibreELEC/LibreELEC.tv/commit/c7b9e90ce49af4d8e28a0c7b6b4d835e51b1a2bc

**Comment by chewitt** [comment]
@Celedhrim if you understand how to squash commits .. please do

**Comment by Celedhrim** [comment]
done !

**Comment by CvH** [comment]
@Celedhrim could you rename your commit `net-snmp: several bugfixes`or similar to keep the in house commit message style, besides that it looks good to go 👍

**Comment by Celedhrim** [comment]
You are right ! :)

**Pull request merged**
