### PR TITLE
imx6/linux: export symbol used by gpio-ir-recv

### PR DESCRIPTION
**Pull request by vpeter4**

### CODE REVIEW

**Comment by lrusak** [comment]
forward port?

**Comment by vpeter4** [comment]
> forward port?
Will be done in the future - master is currently not very much important to me.

**Comment by lrusak** [comment]
Please always PR to master first, then backport it.

**Comment by vpeter4** [comment]
Why exactly both branches must be same? I'm not testing/using master and this is extra work not needed at all.
Eventually I will send pr with all changes from 8.0 branch to master.

**Comment by MilhouseVH** [comment]
> Eventually I will send pr with all changes from 8.0 branch to master.
This is the risk, that "eventually" may never happen. Not suggesting it will happen in this case, but always merging to master first and then backporting ensures we don't "lose" changes that are never "forward ported" to master because the original submitter forgot, or was happy his problem was fixed in whatever branch he works on and never submitted the change to master. It's going to happen because we have different people focused on different branches and something will slip through the cracks eventually, unless we try to enforce this simple rule.

**Pull request merged**
