### PR TITLE
build fixes

### PR DESCRIPTION
**Pull request by lrusak**
Just running through after the big merges. Leave this open for a bit

### CODE REVIEW

**Comment by lrusak** [comment]
This is the only thing I found when building Odroid_C2, might as well merge :+1:

**Comment by MilhouseVH** [comment]
Maybe this is only needed by older kernels, as this PR fails to build on RPi/RPi2/Generic with kernel 4.8.8: http://sprunge.us/aUTF

Without this PR, the same projects build without a problem.

**Comment by lrusak** [comment]
thanks, I'll add it to aarch64 specific folder

**Comment by jerome-benoit** [comment]
I think you should replace extern by static, no just remove it.

**Comment by lrusak** [comment]
updated, thanks

**Pull request merged**
