### PR TITLE
alsa-lib: update to 1.2.2

### PR DESCRIPTION
**Pull request by nouman8**

### CODE REVIEW

**Comment by dhewg** [comment]
You could've updated #4000 for 1.2.2 with interactive rebasing and a forced push.
Now the topology and ucm changes you did there are missing here.

**Comment by HiassofT** [comment]
also please follow commit message style, they should be eg "alsa-lib: update to 1.2.2" instead of just "update package.mk"

**Comment by nouman8** [comment]
@dhewg ucm and topology changes in #4000 were untested and not included in the nightly builds...i hope somebody post a better PR soon as i have messed up this one as well.

**Comment by HiassofT** [comment]
superseded by #4223

**Pull request closed without merging**
