### PR TITLE
[LE13]Python: update to 3.12

### PR DESCRIPTION
**Pull request by jernejsk**
Python 3.12 dropped support for distutils install method. At the same time, python community decided on new build and install concept, described in PEP 517. In order to provide smooth and bisectable transition, this PR first adds new preferred python build method and then updates python to 3.12.

PR scope is just python update. Updating python packages with new build commands will be done in follow up PR.

### CODE REVIEW

**Comment by jernejsk** [comment]
Build system changes will be splitted in separate PR.

**Comment by heitbaum** [comment]
Build / and first run successful on Generic 
```
nuc12:~ # python --version
Python 3.12.5
```
starting testing on other targets (and aarch64 host)

**Comment by heitbaum** [comment]
`import imp` has been dropped in 3.12 in favour of importlib. does this just require the change of imp to importlib for both references:

- https://github.com/LibreELEC/service.libreelec.settings/blob/b36ea367e5cd62e360db56390813d669b5e02d6a/resources/lib/oe.py#L10 
- https://github.com/LibreELEC/service.libreelec.settings/blob/b36ea367e5cd62e360db56390813d669b5e02d6a/resources/lib/oe.py#L69

**Comment by heitbaum** [comment]
arm and aarch64 builds successful.
arm build on aarch64 host successful.

**Review by heitbaum — APPROVED** [review]

**Comment by heitbaum** [comment]
Build test
- Along #9226 and #9223 I have done the following builds:
 - aarch64 on aarch64
 - arm on aarch64
 - aarch64 on x64
 - arm on x64
 - generic on x64

all successful

Run tested:
- generic
- some `invalid escape sequence` SyntaxWarning in addons
  - raised with addon authors, some already fixed.

full addon build successful

**Comment by CvH** [comment]
gtg ?

**Comment by jernejsk** [comment]
afaik yes

**Comment by heitbaum** [comment]
Good here

**Pull request merged**
