### PR TITLE
RTL8812AU/RTL8192EU: Fix GRO_DROP deprecation kernel 5.12

### PR DESCRIPTION
**Pull request by heitbaum**
### RTL8812AU
Small patch to allow kernel 5.12 to compile with LibreELEC - does not impact < 5.12 code.
upstream merged patch:
- https://github.com/aircrack-ng/rtl8812au/pull/848
- patch by @CGarces

also:
- https://github.com/aircrack-ng/rtl8812au/pull/847
- Remove rtl8822bu device (and minor tidy ups) 

### RTL8192EU
Log:
- https://github.com/Mange/rtl8192eu-linux-driver/commits/realtek-4.4.x
- 5.12 fixes
- changes included are : Feb 6, 2021 —> Apr 4, 2021

### CODE REVIEW

**Comment by CGarces** [comment]
Please wait to merge this PR until someone confirms that works on real hardware.
See https://github.com/aircrack-ng/rtl8812au/pull/857
I'll update RTL8192EU and send a PR to rtl8192cu if someone confirm that the patch works (issue https://github.com/aircrack-ng/rtl8812au/issues/855)

**Comment by CGarces** [comment]
https://github.com/aircrack-ng/rtl8812au/pull/857 merged.

**Comment by heitbaum** [comment]
Updated with PR with rtl8812au/pull/857

**Comment by heitbaum** [comment]
Closing as updated in 5.15 PR #5738

**Pull request closed without merging**
