### PR TITLE
Amlogic: Disable POST_PROCESS_MANAGER_3D_PROCESS in kernel config

### PR DESCRIPTION
**Pull request by kszaq**
With the option enabled there is a NULL pointer reference kernel panic when playing some videos. 

Sample video at forum thread: https://forum.libreelec.tv/thread-3219.html

### CODE REVIEW

**Comment by codesnake** [comment]
@kszaq Do 3D movies still play correctly after disabling this?

**Comment by kszaq** [comment]
Unfortunately I don't have 3D content/TV to test this. This will probably break 3D.

**Comment by codesnake** [comment]
@kszaq I checked this PR on WP2 and 3D movies still play correctly with, so it is good to merge.

**Comment by kszaq** [comment]
Reopening the PR after @codesnake opinion.

**Comment by stefansaraev** [comment]
@codesnake @kszaq fyi https://github.com/xbmc/xbmc/pull/12316#issuecomment-309410656

**Pull request merged**
