### PR TITLE
busybox: update to 1.26.2

### PR DESCRIPTION
**Pull request by lrusak**
Allows us to drop a patch. Also the configs are reworked a bit.

Worth a build test or two ;)

### CODE REVIEW

**Comment by lrusak** [comment]
force pushed to enable `CONFIG_FEATURE_SH_MATH` otherwise the init would fail

**Comment by MilhouseVH** [comment]
http://sprunge.us/CSQj

We don't want a shell (`sh -> busybox`) in the host toolchain, as bad things will happen (eg. unpacking xf86-video-nvidia/xf86-video-nvidia-legacy will fail).

**Comment by lrusak** [comment]
added a fixup to disable building `sh` for host

**Comment by MilhouseVH** [comment]
With this PR we lose `bash` support on the target (noticed as this broke [Bluetooth on RPi](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/linux-firmware/brcmfmac_sdio-firmware-rpi/scripts/rpi-btuart) which depends on `bash`).

The following patch will restore `bash` (and thus Bluetooth):

http://sprunge.us/iQEL

**Comment by lrusak** [comment]
updated and squashed

**Pull request merged**
