### PR TITLE
Fix NAND auto installs on WeTek devices

### PR DESCRIPTION
**Pull request by drieschel**
Same PR like https://github.com/LibreELEC/LibreELEC.tv/pull/574 for master.

### CODE REVIEW

**Comment by stefansaraev** [comment]
why is this. this effectively reverted #137

userdata and cache are supposed to be clean up when using the recovery pinhole

**Comment by drieschel** [comment]
@stefansaraev Problem is change from Android to LE, the update is not working then with --wipe_cache and --wipe_data parameters.

**Comment by stefansaraev** [comment]
this is wrong. look again #137

who'll format /storage (data partition) now ?

**Comment by drieschel** [comment]
I saw that. But why is this necessary? There could be people who are using this method for updating LE instead of using the update folder method and they are losing all their data. If they still want to make a clean install, they can use the wipe data functionality in the "android recovery system" or add the parameters to their factory_update_param.mal file when they already switched to LE on NAND. Do I miss something?

**Comment by stefansaraev** [comment]
idk. OE has few great fuck ups regarding nand support, so I decided to not invest too much time and not even test changes. if your change works, okay, thats fine. sorry for the noise.

**Comment by drieschel** [comment]
It works! And yes, it's good to discuss, because verybody can overlook something. So thanks for your point of view.

**Comment by drieschel** [comment]
PS: It probably makes sense to explain the different update possibilities (including how to wipe data) for WeTek devices somewhere in the wiki.

**Pull request merged**
