### PR TITLE
[le10] fluidsynth: update to 2.2.3 and use with audiodecoder.fluidsynth 19.0.1-Matrix

### PR DESCRIPTION
**Pull request by heitbaum**
With recent kodi-binary-addons: update to latest versions `audiodecoder.fluidsynth: update 3.0.0-Matrix to 19.0.0-Matrix` #5575 the build fails due to new dependency on libgomp

refs: (Thanks @HiassofT)
- https://github.com/xbmc/audiodecoder.fluidsynth/commit/192203d4756772b57ebfecbcc23f5f8007e16f37
- https://github.com/xbmc/audiodecoder.fluidsynth/commit/2978ef181cfb925198c2237509425b95efd3b8a3

Build fails with:
```
/var/lib/jenkins/LE/build4/workspace/Addons/All_Addons-ARMv7/LibreELEC.tv/build.LibreELEC-ARMv7.arm-11.0-devel/toolchain/lib/gcc/armv7a-libreelec-linux-gnueabihf/10.3.0/../../../../armv7a-libreelec-linux-gnueabihf/bin/ld.gold: error: cannot find -lgomp
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FAILURE: scripts/build audiodecoder.fluidsynth:target during make_target (default)
```

### fluidsynth
update 1.1.6 (25 Jun 2017) to 2.2.3 (12 Sep 2021)
changelog: https://github.com/FluidSynth/fluidsynth/releases

release notes:
- https://github.com/FluidSynth/fluidsynth/releases/tag/v2.1.8
- https://github.com/FluidSynth/fluidsynth/releases/tag/v2.2.0
- https://github.com/FluidSynth/fluidsynth/releases/tag/v2.2.1
- https://github.com/FluidSynth/fluidsynth/releases/tag/v2.2.2
- https://github.com/FluidSynth/fluidsynth/releases/tag/v2.2.3

### CODE REVIEW

**Comment by heitbaum** [comment]
The update for the `audiodecoder.fluidsynth` builds successfully with this PR against `libreelec-10.0:Generic`

**Comment by HiassofT** [comment]
libgomp.so is being built now, but it's not installed to sysroot and image:
```
hias@delle:~/private/libreelec/libreelec-10.0/build.LibreELEC-RPi4.arm-10.0-devel$ find . -name libgomp.so
./toolchain/armv8a-libreelec-linux-gnueabihf/lib/libgomp.so
./toolchain/lib/gcc-arm-aarch64-none-linux-gnu/aarch64-none-linux-gnu/libc/usr/lib64/libgomp.so
./toolchain/lib/gcc-arm-aarch64-none-linux-gnu/aarch64-none-linux-gnu/lib64/libgomp.so
./build/gcc-10.2.0/.x86_64-linux-gnu/armv8a-libreelec-linux-gnueabihf/libgomp/.libs/libgomp.so
./build/gcc-arm-aarch64-none-linux-gnu-10.2-2020.11/aarch64-none-linux-gnu/libc/usr/lib64/libgomp.so
./build/gcc-arm-aarch64-none-linux-gnu-10.2-2020.11/aarch64-none-linux-gnu/lib64/libgomp.so
```

As gcc's package.mk is overriding make_install_xxx we probably have to manually install it (like libstdc++.so) and also check if some additional headers need to be installed to sysroot - or invoke `make -C libgomp install` or sth like that.

**Comment by HiassofT** [comment]
thanks, quick build test looks fine now.

can you PR for master, might be good to merge it there and give jenkins a round on build testing before merging into LE10

**Comment by heitbaum** [comment]
I checked `make -C libgomp install` relevant output below
```
/bin/mkdir -p './toolchain/lib/gcc/x86_64-libreelec-linux-gnu/10.2.0/include'
/usr/bin/install -c -m 644 omp.h libgomp/openacc.h libgomp/acc_prof.h toolchain/lib/gcc/x86_64-libreelec-linux-gnu/10.2.0/include'
```
Matches toolchain output. So no need to do further copies (I believe) of header files.
```
$ find build.LibreELEC-Generic.x86_64-10.0-devel/ -name openacc.h
build.LibreELEC-Generic.x86_64-10.0-devel/build/gcc-10.2.0/libgomp/openacc.h
build.LibreELEC-Generic.x86_64-10.0-devel/toolchain/lib/gcc/x86_64-libreelec-linux-gnu/10.2.0/include/openacc.h

$ find build.LibreELEC-Generic.x86_64-10.0-devel/ -name acc_prof.h
build.LibreELEC-Generic.x86_64-10.0-devel/build/gcc-10.2.0/libgomp/acc_prof.h
build.LibreELEC-Generic.x86_64-10.0-devel/toolchain/lib/gcc/x86_64-libreelec-linux-gnu/10.2.0/include/acc_prof.h

$ find build.LibreELEC-Generic.x86_64-10.0-devel/ -name omp.h
build.LibreELEC-Generic.x86_64-10.0-devel/build/gettext-0.21/.x86_64-linux-gnu/gettext-tools/gnulib-lib/omp.h
build.LibreELEC-Generic.x86_64-10.0-devel/build/gcc-10.2.0/.x86_64-linux-gnu/x86_64-libreelec-linux-gnu/libgomp/omp.h
build.LibreELEC-Generic.x86_64-10.0-devel/toolchain/lib/gcc/x86_64-libreelec-linux-gnu/10.2.0/include/omp.h
```

**Comment by heitbaum** [comment]
> thanks, quick build test looks fine now.
> 
> can you PR for master, might be good to merge it there and give jenkins a round on build testing before merging into LE10

all done in [le11] fluidsynth: update to 2.2.2 and use with audiodecoder.fluidsynth 19.0.0-Matrix #5587 👍

**Comment by HiassofT** [comment]
yes, thanks, I also checked header files and came to the same conclusion.

Thinking about it a bit more this new libopenmp dependency is a quite meh as it means that the updated addon (linking against the lib) won't run on current LE10 images.

openmp is an optional dependency in the new fluidsynth and I'm not quite sure why the kodi addon hard depends on it.

I'm a bit inclined to drop all the openmp stuff and just patch the kodi addon to not require openmp (nothing in the addon code pulls that in), ideally the kodi addon should be fixed and honor openmp as optional transitive dependency, too

**Comment by AlwinEsch** [comment]
Has brought in your fixes in and released new addon versions (19.0.1 and 20.0.1), thanks a lot for report and to bring fix about!

**Comment by mglae** [comment]
Building without OpenMP is now possible with 19.0.1 and 20.0.1

**Comment by HiassofT** [comment]
@heitbaum can you drop the openmp/gomp commits and add a audiodecoder.fluidsynth rev-bump? Then I think this should be good to go in

**Comment by heitbaum** [comment]
https://github.com/xbmc/audiodecoder.fluidsynth/pull/27
https://github.com/xbmc/audiodecoder.fluidsynth/pull/28

fix the dependancies on libgomp 

https://github.com/xbmc/audiodecoder.fluidsynth/releases/tag/19.0.1-Matrix
https://github.com/xbmc/audiodecoder.fluidsynth/releases/tag/20.0.1-Nexus

with the updates to 19.0.1/20.0.1 - drop proposed libgomp and just update:
- soxr: dont build with openmp **leave this fix in as improvement of not requiring openmp**
- fluidsynth: update to 2.2.3
- libsndfile: enable external-libs (FLAC, Ogg, Opus and Vorbis)

**Comment by heitbaum** [comment]
@HiassofT - test builds successful against both #5583 [le10] and #5587 [le11] - done with 19.0.1 and 20.0.1 against LibreELEC-10.0 and Master respectively.

**Comment by HiassofT** [comment]
thanks a lot, local builds went fine here, too!

**Review by HiassofT — APPROVED** [review]

**Pull request merged**
