### PR TITLE
add patch for fixing subtitles in 3D MVC videos for RPI2/3

### PR DESCRIPTION
**Pull request by TheMontezuma**
Workaround to fix https://github.com/xbmc/xbmc/issues/16362

### CODE REVIEW

**Comment by chewitt** [comment]
@popcornmix is there a reason this patch has not been merged upstream?

@TheMontezuma even if we accept/merge the patch there are currently no plans for an LE 9.2.7 release.

**Comment by TheMontezuma** [comment]
> @popcornmix is there a reason this patch has not been merged upstream?

Good question.  I'm also very interested to understand the background.
The fix was merged into newclock5 branch:
https://github.com/popcornmix/xbmc/commit/6af7c63f2883c87e87eb657e8b20b527258738b0

For me 3D MVC playback is an ultimate feature of the RPI3 + LibreELEC/KODI combo.
I was really disappointed to discover that the PGS subtitles are rendered not correctly (probably due to support for crappy SBS/TAB formats). Thanls to @HiassofT I was able to build LE locally and I tested the patch on the LE 9.2 branch.
I'm actually done, but I know that other users miss this feature, so I wanted to contribute.
Ideally, the fix should go into a KODI branch, which will be the base for the future LE verions.

> @TheMontezuma even if we accept/merge the patch there are currently no plans for an LE 9.2.7 release.

I see, but you never know :) There are any way other commits on top of LE 9.2.6

**Comment by TheMontezuma** [comment]
Below is the history of: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecFFmpeg.cpp
The lower red arrow points to the commit tagged with newclock5_18.9-Leia (the uppper arrow points to a commit with the fix).

history

**Comment by TheMontezuma** [comment]
I have tested now 2D videos and realized that the subtitles vertical position is wrong (they are displayed below the visible area)...

**Comment by TheMontezuma** [comment]
I ammended the commit to check one more condition.
After that I successfully tested 3D and 2D videos with subtitles.

**Comment by popcornmix** [comment]
There's been a couple of PRs to fix this, but they've not received much interest.
https://github.com/xbmc/xbmc/pull/17317
https://github.com/xbmc/xbmc/pull/8254

**Comment by TheMontezuma** [comment]
> There's been a couple of PRs to fix this, but they've not received much interest.

From developers or from users?

**Comment by TheMontezuma** [comment]
No interest, then let's close it.
LibreELEC is anyway not the right place to fix KODI issues :)

**Pull request closed without merging**
