### PR TITLE
linux: update to linux-4.13.0

### PR DESCRIPTION
**Pull request by MilhouseVH**
Looks like we can drop the button repeat fix.

4.13 announcement: https://lkml.org/lkml/2017/9/3/155

---
#### Test build posts
| Kernel | RPi/RPi2 | Generic | Build |
| :--- | :---: | :---: | :----: |
|4.13-rc1|[Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2620168#pid2620168)|[Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2620169#pid2620169)|`#0720x`|
|4.13-rc2|[Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2623640#pid2623640)|[Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2623641#pid2623641)|`#0727x`|
|4.13-rc3|[Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2626200#pid2626200)|[Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2626204#pid2626204)|`#0801x`|
|4.13-rc4|[Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2629366#pid2629366)|[Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2629369#pid2629369)|`#0808x`|
|4.13-rc5|[Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2632270#pid2632270)|[Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2632271#pid2632271)|`#0814x`|
|4.13-rc6|[Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2636989#pid2636989)|[Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2636990#pid2636990)|`#0824x`|
|4.13-rc7|[Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2641112#pid2641112)|[Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2641113#pid2641113)|`#0901x`|
|4.13.0|[Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2642665#pid2642665)|[Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2642666#pid2642666)|`#0904`|

### CODE REVIEW

**Comment by InuSasha** [comment]
note: @MilhouseVH when you go back to kernel.org with PKG_URL, can you stay at https. kernel.org has activated HSTS already, so http unwanted, now ;)

**Comment by MilhouseVH** [comment]
Noted, thanks.

**Comment by lrusak** [comment]
good to go?

**Comment by MilhouseVH** [comment]
Sure, why not. :)

**Pull request merged**
