### PR TITLE
Update make to 4.4.1

### PR DESCRIPTION
**Pull request by heitbaum**
~~Updated with upstream fix [SV 63347] for nss~~
upstream fix now included in make-4.4.1

Replaces 
- #7068 

~~make 4.4 is handling config.mk differently~~
~~- specifically `CPU_TAG`~~
~~- replace variable CPU_TAG with the _TARGET_ARCH.~~
~~This results in the same result as make 4.3~~

~~`sed -i -e "s/^CPU_TAG = _.*/CPU_TAG = _${TARGET_ARCH}/" coreconf/Linux.mk` is the workaround.~~

~~Raised bug with nss team. Occurs with both 3.84 and 3.85~~
Bug raised on make-4.4
- https://bugzilla.mozilla.org/show_bug.cgi?id=1801182
- https://bugzilla.mozilla.org/show_bug.cgi?id=1800237
- https://git.busybox.net/buildroot/commit/?id=5852fee868c318f0864bed3238b46348156422b6
- https://savannah.gnu.org/bugs/index.php?63347

tested create_addon builds for Generic, ARMv7 and ARMv8
tested x86_64, arm and aarch64 `make image`

nss source - https://hg.mozilla.org/projects/nss/

### CODE REVIEW

**Comment by heitbaum** [comment]
Bug on nss raised : https://bugzilla.mozilla.org/show_bug.cgi?id=1800237

**Comment by heitbaum** [comment]
This is the why: https://savannah.gnu.org/bugs/index.php?63347

**Comment by heitbaum** [comment]
Whilst this is GtG on arm platforms, now with the nss fix - Leaving as merge block / WIP - Until we get upstream direction on if/when a fix will be available.

**Comment by heitbaum** [comment]
The SV63347 fix has been merged upstream 
- https://git.savannah.gnu.org/cgit/make.git/commit/?id=dc2d963989b96161472b2cd38cef5d1f4851ea34
- https://savannah.gnu.org/bugs/index.php?63347

nss test builds now working on all.

Make Git Logs:
- https://git.savannah.gnu.org/cgit/make.git/log/

**Comment by CvH** [comment]
do we want to delay it for LE12 ?

**Comment by heitbaum** [comment]
> do we want to delay it for LE12 ?

no great rush - so ok by me. I have libtool (have had all year) that is  an LE12 candidate too.

**Review by CvH — APPROVED** [review]

**Pull request merged**
