### PR TITLE
libssh: explicitly disable Kerberos support

### PR DESCRIPTION
**Pull request by vpeter4**
In case krb5 package is build before libssh then libssh is build with Kerberos support. But later addons using libssh doesn't have required libraries and fail to start.

undefined symbol: GSS_C_NT_HOSTBASED_SERVICE

### CODE REVIEW

**Comment by CvH** [comment]
as krb5 is only needed by `dotnet-runtime` and just used via `$(get_build_dir krb5)/.install_pkg/usr/lib/libcom_err.so.? \`
it might be enough to not install krb5 to toolchain at all ?

adding
```
makeinstall_target() {
  :
}
```
to https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/addon-depends/dotnet-runtime-depends/krb5/package.mk#L23

would prevent that other packages could have the same problem

**Comment by vpeter4** [comment]
Yes, the problem is that krb5 is installed to toolchain and picked by libssh.
@awiouy: Is solution above from CvH acceptable? It would be more generic for other packages.

**Comment by Raybuntu** [comment]
Since I'm most likely the only person on the planet using only sftp for my media access, I can confirm this PR is working. Good job @vpeter4

**Comment by CvH** [comment]
@awiouy ??

**Comment by vpeter4** [comment]
I think you can merge this and later @awiouy can change also krb5.

**Comment by CvH** [comment]
ofc, won't harm to have both

**Comment by vpeter4** [comment]
Thank you.

**Comment by vpeter4** [comment]
Thank you. Now I'm again at 0.

**Pull request merged**
