### PR TITLE
kodi: remove beelink mouse patch

### PR DESCRIPTION
**Pull request by chewitt**
I'm still looking for a better solution for this device, but until then, this corrects fat thumbs.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Unfortunately this doesn't fix the Kodi whine - we're still getting the following in Kodi even with this PR:
```
2020-04-13 21:27:27.993 T:1213   DEBUG: LoadMappings - loaded node "Motorola Nyxboard Hybrid"
2020-04-13 21:27:27.993 T:1213   DEBUG: LoadMappings - loaded node "CEC Adapter"
2020-04-13 21:27:27.993 T:1213   DEBUG: LoadMappings - loaded node "Pulse-Eight CEC Adapter"
2020-04-13 21:27:27.993 T:1213   ERROR: LoadMappings - ignoring node "iMON HID device" with invalid vendor_product attribute
2020-04-13 21:27:27.993 T:1213   DEBUG: LoadMappings - loaded node "iMON HID device"
2020-04-13 21:27:27.993 T:1213   DEBUG: LoadMappings - loaded node "WETEK Play remote"
2020-04-13 21:27:27.993 T:1213   DEBUG: LoadMappings - loaded node ""
2020-04-13 21:27:27.993 T:1213   DEBUG: Add-on bus: Registering add-on peripheral.joystick
```
Full log: http://ix.io/2hVe

We probably need to look at the kodi code to understand why it is complaining.

This is `/usr/share/kodi/system/peripherals.xml` from the test system: http://ix.io/2hVc

**Comment by MilhouseVH** [comment]
The issue is pretty clear:
https://github.com/xbmc/xbmc/blob/master/xbmc/peripherals/Peripherals.cpp#L510-L515

Kodi only expects `vendor:product` ie. `15C2:32` and not `0003:2319:00B2:0003`

**Comment by HiassofT** [comment]
yes, exactly, this change doesn't make sense. see also my comment 2 weeks ago https://github.com/LibreELEC/LibreELEC.tv/pull/4220#issuecomment-606119123
> on closer inspection I can't see how the beelink remote change could have any (positive) effect. Kodi simply ignores vendor:product entries that don't have exactly one colon
> 
> see https://github.com/xbmc/xbmc/blob/master/xbmc/peripherals/Peripherals.cpp#L507-L520
> 
> my guess is the beelink remote commit can simply be dropped

**Comment by chewitt** [comment]
I'm not seeing crazy behaviour in current dev builds, so either something changed in recent Kodi or in Linux 5.7, but either way this doesn't appear to be needed, so the patch is dropped.

**Pull request merged**
