### PR TITLE
[le11] kodi: add shutdown hook to autostart

### PR DESCRIPTION
**Pull request by wagnerch**
This adds an "autostop.sh" script, which is based on the conversation and related threads [here](https://forum.libreelec.tv/thread/25150-solved-kodi-on-rpi4-on-libreelec-run-custom-script-upon-kodi-power-off/?postID=165518#post165518).

The kodi-autostart.service already has RemainAfterExit set, so the service already fires a "stop" at shutdown.  So just added the ExecStop with a shell test for "/storage/.config/autostop.sh" and TimeoutStopSec=5min to allow the stop script to run up to 5 minutes.

The script itself is implemented just like autostart.sh, and would run at stopping of kodi-autostart.service which normally would happen before poweroff.target is met (while networking is still available).  This gives you an opportunity to run some shutdown scripts before the network is shutdown.

Tested by adding script /storage/.config/autostop.sh:
```sh
#!/bin/sh

echo "stop $(date)" >> /storage/autostart.log
ping -c 1 192.168.0.1 >> /storage/autostart.log
```

And rebooting LE.  Permissions should be set executable, same as autostart.sh.

One fault I can see is autostop.sh would not run unless there is an autostart.sh, you could call that a feature or a fault.  :)  Let me know what you think on that, can remove the "ConditionPathExists" and add a shell test for autostart.sh.

### CODE REVIEW

**Comment by vpeter4** [comment]
autostart.sh doesn't need to be executable
make separate service _kodi-autostop.service_, no need to check for the file then

**Comment by wagnerch** [comment]
@vpeter4 Yeah, that's certainly an option which is what you posted originally.  But I think it's a good idea to keep it in a single service file and move the condition check to the ExecStart, the reason is this gives people who want it an opportunity to use the 2 scripts together essentially as a SysV initscript.

I think things like "systemctl restart kodi-autostart" would be easy if we moved the condition as part of the shell bootstrap code, otherwise your left with "systemctl stop kodi-autostart; systemctl restart kodi-autostop; systemctl start kodi-autostart" with the 2 service option.

**Comment by vpeter4** [comment]
But using _autostop_ only if _autostart_ is enabled is wrong.

**Comment by wagnerch** [comment]
Just bumped to what I was suggesting, this may be useful to someone who just wants stop/start or both.  Just trying to maintain backward compatibility with people who already have scripts, but ideally I think I would prefer an argument like an initscript.

Hopefully this is a decent compromise.

**Comment by CvH** [comment]
@wagnerch could you add some howto to the wiki ?

**Review by CvH — APPROVED** [review]

**Pull request merged**
