### PR TITLE
systemd: make standard systemctl commands work again

### PR DESCRIPTION
**Pull request by HiassofT**
systemctl mask/unmask/edit are helpful commands and work as expected. So let's drop the patch that disabled them

### CODE REVIEW

**Comment by lrusak** [comment]
as discussed these are dangerous commands and we are saving users from themselves.

There are manual ways to execute these commands for those that know what they are doing.

Also, masking systemd files that are triggered by udev is not a solution, you should mask the udev file.

I won't block this if others want it but for me it's a :-1:

**Comment by HiassofT** [comment]
With these commands disabled you make it hard for scripts, addons, developers and experienced users to use standard systemd commands. systemctl edit --full is really helpful when testing systemd rules. So are mask/unmask if one wants to make sure something is never started. Telling people to edit udev or systemd rules (and manually copying them into the right location before) is a lot more errorprone than telling them to mask/unmask a service - eg for testing.

If a user really wants to shoot himself in the foot there are better ways - disabling some systemctl commands doesn't add much protection, it just makes life of experienced users much more difficult.

As discussed before, I have no problem if you disabled stuff that can't work for a technical reason but I see no reason to do that for these perfectly working and helpful commands. If there are technical issues I don't know of please tell.

**Comment by lrusak** [comment]
again,

`systemctl mask`:
```
ln -s /dev/null /storage/.config/system.d/kodi.service
```

`systemctl edit --full`:
```
cp /usr/lib/systemd/system/kodi.service /storage/.config/system.d/
nano /storage/.config/system.d/kodi.service
```

I'm sure @stefansaraev has some words about this as he is the creator of this patch

**Comment by HiassofT** [comment]
sure, and now which of these commands are easier to type and remember? Why do it the hard way when there are easy methods to achieve this out-of-the box?

**Comment by stefansaraev** [comment]
I dont have strong opinion on this. if those commands work now (some did not work well at the time I added the patch to OE) - drop the patch and you'll have one less to maintain

I, personaly, never used systemctl edit or systemctl mask. OE was supposed to be a distribution for kodi and only kodi, LE seems to have different goals, so removing the patch probably makes sense.

**Comment by lrusak** [comment]
I'm fine with this if it makes people's life easier. Just don't abuse it.

**Pull request merged**
