### PR TITLE
wlroots 0.16.1 and 1.8 sway updates

### PR DESCRIPTION
**Pull request by heitbaum**
- hwdata: initial package
  - dependency for wlroots, they have moved the pci.ids out of the wlroots
  - https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/eec95e3d5e1a4f2e13b1f6b34cc287475ca57daf
- wlroots: update to 0.16.1
- swaybg: update to 1.2.0
- sway: update to 1.8

### CODE REVIEW

**Comment by SupervisedThinking** [comment]
Please split wayland & x11 stuff. Sway is tied to certain wlroots versions so they need to be bumped together once a new Sway version is ready https://github.com/swaywm/sway/blob/1.7/meson.build#L64

**Comment by heitbaum** [comment]
> Please split wayland & x11 stuff. Sway is tied to certain wlroots versions so they need to be bumped together once a new Sway version is ready https://github.com/swaywm/sway/blob/1.7/meson.build#L64

- Split into #7118

**Comment by SupervisedThinking** [comment]
unless we want to wait until a next sway release is ready you have to split off wlroots + the hwdata commit. Those are directly linked to Sway & if the version does not match the wayland build is broken. The proto & input stuff should be independent.

**Comment by heitbaum** [comment]
> unless we want to wait until a next sway release is ready you have to split off wlroots + the hwdata commit. Those are directly linked to Sway & if the version does not match the wayland build is broken. The proto & input stuff should be independent.

Cool. Done.

**Comment by SupervisedThinking** [comment]
Will check this out next week https://github.com/swaywm/sway/releases/tag/1.8-rc1 - needs some patching to run as root

**Comment by heitbaum** [comment]
> Will check this out next week https://github.com/swaywm/sway/releases/tag/1.8-rc1 - needs some patching to run as root

@SupervisedThinking - I have updated the patc( - it should work for you.

**Comment by SupervisedThinking** [comment]
- please merge this commit https://github.com/SupervisedThinking/LibreELEC-RR/commit/abc78ed5259bea6f94c8bd9625cd26018e8d6838 & sqash your stuff ^^
-  looks like we don't need all cflags anymore & the updated patch fixes sway version in log which otherwhise would use LE git version & branch, it also moves the `detect_suid` check to a place where logging is already initialized because otherwhise only error where listed in log & info not
```
00:00:00.000 [INFO] [sway/main.c:334] Sway version 1.8-rc1
00:00:00.000 [INFO] [sway/main.c:335] wlroots version 0.16.0
00:00:00.000 [INFO] [sway/main.c:120] Linux wayland 6.0.9 #1 SMP Tue Nov 29 18:45:26 CET 2022 x86_64 GNU/Linux
00:00:00.010 [INFO] [sway/main.c:136] Contents of /etc/os-release:
00:00:00.010 [INFO] [sway/main.c:120] NAME="LibreELEC"
00:00:00.010 [INFO] [sway/main.c:120] VERSION="RR-20221130-6d826fe"
00:00:00.010 [INFO] [sway/main.c:120] ID="libreelec"
00:00:00.010 [INFO] [sway/main.c:120] VERSION_ID="11.0"
00:00:00.010 [INFO] [sway/main.c:120] PRETTY_NAME="LibreELEC (ST): RR-20221130-6d826fe"
00:00:00.010 [INFO] [sway/main.c:120] HOME_URL="https://libreelec.tv"
00:00:00.010 [INFO] [sway/main.c:120] BUG_REPORT_URL="https://github.com/SupervisedThinking/LibreELEC-RR"
00:00:00.010 [INFO] [sway/main.c:120] BUILD_ID="6d826fe646dad506c5ef9ed1f2bb619b09c5b371"
00:00:00.010 [INFO] [sway/main.c:120] LIBREELEC_ARCH="wayland.x86_64"
00:00:00.010 [INFO] [sway/main.c:120] LIBREELEC_BUILD="ST"
00:00:00.010 [INFO] [sway/main.c:120] LIBREELEC_PROJECT="Generic"
00:00:00.010 [INFO] [sway/main.c:120] LIBREELEC_DEVICE="wayland"
00:00:00.010 [INFO] [sway/main.c:120] BUILDER_NAME="ST"
00:00:00.010 [INFO] [sway/main.c:108] LD_LIBRARY_PATH=
00:00:00.010 [INFO] [sway/main.c:108] LD_PRELOAD=
00:00:00.010 [INFO] [sway/main.c:108] PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
00:00:00.010 [INFO] [sway/main.c:108] SWAYSOCK=
00:00:00.010 [INFO] [sway/main.c:155] Running sway as root user
00:00:00.010 [ERROR] [sway/main.c:62] !!! Proprietary Nvidia drivers are in use !!!
00:00:00.010 [INFO] [sway/main.c:377] Starting sway version 1.8-rc1
00:00:00.014 [INFO] [wlr] [libseat] [libseat/libseat.c:73] Seat opened with backend 'seatd'
00:00:00.014 [INFO] [wlr] [libseat] [libseat/backend/seatd.c:212] Enabling seat
```

**Comment by heitbaum** [comment]
> * please merge this commit [SupervisedThinking@abc78ed](https://github.com/SupervisedThinking/LibreELEC-RR/commit/abc78ed5259bea6f94c8bd9625cd26018e8d6838) & sqash your stuff ^^
> * looks like we don't need all cflags anymore & the updated patch fixes sway version in log which otherwhise would use LE git version & branch, it also moves the `detect_suid` check to a place where logging is already initialized because otherwhise only error where listed in log & info not
> 
> ```
> 00:00:00.000 [INFO] [sway/main.c:334] Sway version 1.8-rc1
> 00:00:00.000 [INFO] [sway/main.c:335] wlroots version 0.16.0
> 00:00:00.000 [INFO] [sway/main.c:120] Linux wayland 6.0.9 #1 SMP Tue Nov 29 18:45:26 CET 2022 x86_64 GNU/Linux
> 00:00:00.010 [INFO] [sway/main.c:136] Contents of /etc/os-release:
> 00:00:00.010 [INFO] [sway/main.c:120] NAME="LibreELEC"
> 00:00:00.010 [INFO] [sway/main.c:120] VERSION="RR-20221130-6d826fe"
> 00:00:00.010 [INFO] [sway/main.c:120] ID="libreelec"
> 00:00:00.010 [INFO] [sway/main.c:120] VERSION_ID="11.0"
> 00:00:00.010 [INFO] [sway/main.c:120] PRETTY_NAME="LibreELEC (ST): RR-20221130-6d826fe"
> 00:00:00.010 [INFO] [sway/main.c:120] HOME_URL="https://libreelec.tv"
> 00:00:00.010 [INFO] [sway/main.c:120] BUG_REPORT_URL="https://github.com/SupervisedThinking/LibreELEC-RR"
> 00:00:00.010 [INFO] [sway/main.c:120] BUILD_ID="6d826fe646dad506c5ef9ed1f2bb619b09c5b371"
> 00:00:00.010 [INFO] [sway/main.c:120] LIBREELEC_ARCH="wayland.x86_64"
> 00:00:00.010 [INFO] [sway/main.c:120] LIBREELEC_BUILD="ST"
> 00:00:00.010 [INFO] [sway/main.c:120] LIBREELEC_PROJECT="Generic"
> 00:00:00.010 [INFO] [sway/main.c:120] LIBREELEC_DEVICE="wayland"
> 00:00:00.010 [INFO] [sway/main.c:120] BUILDER_NAME="ST"
> 00:00:00.010 [INFO] [sway/main.c:108] LD_LIBRARY_PATH=
> 00:00:00.010 [INFO] [sway/main.c:108] LD_PRELOAD=
> 00:00:00.010 [INFO] [sway/main.c:108] PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
> 00:00:00.010 [INFO] [sway/main.c:108] SWAYSOCK=
> 00:00:00.010 [INFO] [sway/main.c:155] Running sway as root user
> 00:00:00.010 [ERROR] [sway/main.c:62] !!! Proprietary Nvidia drivers are in use !!!
> 00:00:00.010 [INFO] [sway/main.c:377] Starting sway version 1.8-rc1
> 00:00:00.014 [INFO] [wlr] [libseat] [libseat/libseat.c:73] Seat opened with backend 'seatd'
> 00:00:00.014 [INFO] [wlr] [libseat] [libseat/backend/seatd.c:212] Enabling seat
> ```

updated and squashed.

**Comment by heitbaum** [comment]
added swaybg

**Review by SupervisedThinking — APPROVED** [review]

**Pull request merged**
