### PR TITLE
bluez: update QCA9337 patch

### PR DESCRIPTION
**Pull request by kszaq**
The PR updates `bluez` patch that adds QCA9377 support. Reasons for the patch not being upstream are outlined in https://github.com/LibreELEC/LibreELEC.tv/pull/2544

### CODE REVIEW

**Comment by rayelec** [comment]
Looks good to me...
https://github.com/CoreELEC/CoreELEC/commit/574887f33a814864734aa49728fef026472538c3

Bravo...
http://ix.io/1HH5

**Comment by kszaq** [comment]
Everything this commit covers is a `wget` from Github and rm 4 files. No code created, no code modified. Do you want to start pointing out every package bump for that reason - who bumped first? A slight difference in hashes suggests that whoever made that commit (it could have been me, I don't remember), *downloaded* the patch independently of Adam.

I would understand if you complained about a brand new patch, a piece of code, which this PR in not.

Shall I point you to every commit that submitted my *genuine* work under some else's name?

**Comment by rayelec** [comment]
Yes I will point from now on everything out. Because it is the 4th incident in total this happened and it was always chewitt doing it, when at the same time we are being called out publicly to do stuff that is not true. Got to live with the facts. I couldn't care less about authorship but that's what you all want to play: Game on!

**Comment by rayelec** [comment]
At least have the decency to give back some respect. That all we do too. We. Could claim to do all our package bumps we pull from LibreELEC to do ourselves. Anyone ever seen different?

**Comment by kszaq** [comment]
What you're saying is: if you want to bump the package, check if CoreELEC bumped it first.

**Comment by rayelec** [comment]
You do know exactly what I am saying. This is not the first incident and if you all want to play dumb fine. I will call BS out whenever I see it. Until now I have been quite but: No more.

**Comment by kszaq** [comment]
I'm really sorry I did not check. Let it be your way.

**Comment by adamg88** [comment]
> Shall I point you to every commit that submitted my genuine work under some else's name?

During my tenure at LE as well, I did ask you on multiple occasions if you wanted authorship to be retained when I did the initial 8.2->9.0 push and you did not have an issue with it back then and more recently on some old scripts you asked that I even removed your name/email from spdx headers.

We have always endeavoured to ensure that when we use a commit or code that someone else has created that we retain the authorship that goes along with it... even if it has to be reworked.

As a free o/s project we understand that this is the only recognition that individual contributions get for their contributions and try to respect this regardless of how things are between both camps.

**Comment by kszaq** [comment]
I always tried to retain authorship for all patches I provided. I don't have an issue if someone commits my work under their name as long as it's for the better of an(y) open source project. 

I simply don't understand the rage towards me for a simple wget-and-rm patch. I requested @chewitt to make it for the issue I had with a Beelink GT1. I did not check if you commited the bump before that idea came out.

**Comment by rayelec** [comment]
The rage was not towards you. The rage is a combination of recent events and very similar former copycat events. If you have commits looking 1:1 it annoys people and I remember you being annoyed by AlexELEC too for doing exactly the same thing.

**Comment by rayelec** [comment]
And again to make that clear everything you say in https://github.com/LibreELEC/LibreELEC.tv/pull/3475#issuecomment-488140014

This can be applied to 98% of LE commits. Yet I don't go ahead and and just rip of the author.

**Comment by kszaq** [comment]
Ripping off author requires more work as you need to find the commit, cherry-pick it, `--reset-author --date "$(date)"` and so on...

I think we could argue endlessly but I don't want to. Arguing is something I hate and hobby development has to be fun else it's becoming a torture. I would suggest everybody (not only you Ray and Adam, everybody) to let go whatever resentment you hold and only have fun with *ELEC hacking.

**Comment by rayelec** [comment]
Happy to do it @kszaq. I have offered several times a hand and offered peace but all we get back is hatred, disrespect and fake news being spread around not only on LE forum but also Kodi forum.

I will renew this here once and for all if the people calling the shots truly want this I'm willing to offer my hand and bury the hatchet so we can move on and work together. But this will not happen.

**Comment by kszaq** [comment]
@adamg88 I noticed that you pushed a commit that contradicts your statement, it's basically a squash of latest LE 9.0 commits. It's not a simple bump, changelog wording is the same:
https://github.com/CoreELEC/CoreELEC/commit/496729880d4a4577bde0b017fa51ea6ba07f0485

I am not telling the commit did something wrong as you retained copyright notices etc. The thing is that you cannot complain that I PRd a commit that was not inspired by CE (and I have a legitimate proof for this), then commit an AlexELEC-style squash...

**Comment by kszaq** [comment]
My point is that as long as we retain copyright notice where original author is mentioned it doesn't really matter who commited what.

**Comment by adamg88** [comment]
My statement was correct at the time of posting so I fail to see how there is a contradiction, copyright notice where the original author is mentioned has been retained in the commit linked. Also I was not the one who complained, like you I am happy if something I have helped create can be used to help others regardless of the implementation 😄 

*This* PR may or may not have been inspired by CE but others certainly have and this is something that we also have legitimate proof over and whilst I may not be bothered by this, others in our team are certainly bothered by it.

@kszaq lastly I noticed that 3 days has passed since Ray has offered peace (again) and nobody has thought it appropriate to reply?

**Comment by kszaq** [comment]
> We have always endeavoured to ensure that when we use a commit or code that someone else has created that we retain the authorship that goes along with it... even if it has to be reworked.

Here is the contradiction. This whole discussion started because commit author was different than in CE. 

> @kszaq lastly I noticed that 3 days has passed since Ray has offered peace (again) and nobody has thought it appropriate to reply?

If both sides want this, the best way to reply is focus on coding than on what "other side" does. You certainly noticed that I make PRs to CE whenever I find something worth adding.

I think everybody made their statement. I am sorry but I have to lock this conversation, I want to get feedback on patch itself, not who was first to download it from Boundary git.

**Comment by kszaq** [comment]
Closing for now as more bits require to be figured out for QCA9377.

**Pull request closed without merging**
