### PR TITLE
Tvheadend updates and change to ffmpeg 6.0.x

### PR DESCRIPTION
**Pull request by CvH**
- update ffmpegx to 6.0.
- update Tvheadend 4.3
- disable transcoding (ffmpegx depend) at Tvheadend 4.2 because it does not support ffmpeg >= 5.x
- fixed some crlf fu ups due git ignoring autocrlf setting

### CODE REVIEW

**Comment by CvH** [comment]
Tvh ffmpeg 6.0 support is basically done, I wait for merge

**Comment by smp79** [comment]
Maybe it's time to drop tvh 4.2? I see no reason to use it over 4.3, so why keep both.

**Comment by chewitt** [comment]
@smp79 4.2 is still technically the current stable Tvheadend release so it remains for now. Once 4.3 (dev) becomes 4.4 (stable) we'll reassess and probably drop 4.2. There's an active current effort to breathe more life into Tvheadend and once the dust settles on some short-term admin/organisational things, next-up is figuring out how to ship a release.

**Comment by chewitt** [comment]
@CvH Your ffmpeg 6.x bump is merged upstream now :)

**Review by HiassofT — APPROVED** [review]

**Pull request merged**
