### PR TITLE
build: implement PKG_PATCH_DIRS

### PR DESCRIPTION
**Pull request by MilhouseVH**
This would allow the following, eg. in `linux/package.mk`:
```
  *)
    PKG_VERSION="4.8.12"
    PKG_URL="http://www.kernel.org/pub/linux/kernel/v4.x/$PKG_NAME-$PKG_VERSION.tar.xz"
    PKG_PATCH_DIRS="$(echo "${PKG_VERSION}" | sed "s/\([0-9]*\.[0-9]*\)[\.-].*/\1/")")"
    ;;
```
where `PKG_PATCH_DIRS` would be set to `4.8`.

With this change we wouldn't have to `git mv` the patches folder every time we bump the kernel, which loses git history and causes additional maintenance overhead (eg. when having to repeatedly rebase while updating release candidates). Instead we would have just the `patches/4.8` folder.

I'll add PKG_PATCH_DIRS to `linux/package.mk` in the 4.9.0 change (#1017), assuming this is merged.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
For the `linux` package, I think I would like to add `PKG_PATCH_DIRS=default` for the default kernel (`*`), which will further reduce maintenance overhead and ensure we don't rename the patches directory when bumping from 4.y to 4.y+1

**Comment by lrusak** [comment]
looks ok, seems a bit complicated though

**Comment by MilhouseVH** [comment]
I'm not sure it is, the patch may just make it seem that way. Replacing `$(dirname $I)` is just a simplification/optimisation.

**Comment by lrusak** [comment]
This is good to go? @MilhouseVH do you want to make the linux commit here or in a seperate PR?

**Pull request merged**
