### PR TITLE
Various Mesa fixes

### PR DESCRIPTION
**Pull request by evelikov**
Removing no longer needed workaround(s), renaming local variables and documenting others.

This series is a preparation for Mesa VAAPI support. I'll submit that as this has landed, until then take a look at the branch https://github.com/evelikov/LibreELEC.tv/tree/mesa-vaapi

### CODE REVIEW

**Comment by fritsch** [comment]
Hi @evelikov thx for your contribution. Are you aware that kodi for now only works on intel gpus with vaapi cause of a missing possibility to properly share buffers between egl and vaapi that would work without those?

**Comment by chewitt** [comment]
@evelikov these might sit in the PR queue while we clear down our general backlog, but we will get to them soon. Thanks for the contribution :)

**Comment by lrusak** [comment]
Thanks! I've been meaning to look into adding glvnd support but I'm not sure if it is really needed for us. Nvidia has an EOL period in LibreELEC as far as I am concerned and may only be supported for the next (LE9.0) release. The sooner we can get amd on vaapi supported in kodi the sooner we can drop nvidia and x11 altogether. 

Are you sure the linking will work? We build many of the libraries as static and we needed to specify the extra libs to link against. I don't think I tested this in the 17.x mesa branch though so maybe some of this has been fix.

**Comment by MilhouseVH** [comment]
Hi @evelikov - just a small nit: if you are renaming or adding variables would you mind adding the `PKG_` prefix to those variables that are only used within the context of the package.mk (ie. `MESA_PLATFORMS` => `PKG_MESA_PLATFORMS`, `XA_CONFIG` => `PKG_XA_CONFIG` etc.) as we have a mechanism that will automatically unset `PKG_*` variables before the next package is sourced. This is also advice for any future changes (thanks!)

**Comment by evelikov** [comment]
@fritsch I believe Mark Thompson (and others) addressed that. Will double-check before submitting the mesa-vaapi series.

@chewitt sure thing - keep in mind that the glx-tls one is a must.

@lrusak - plan is to eventually use GLVND (by default) and removing the non GLVND paths. Wrt LIBS - pretty sure I fixed it with Mesa commit acf3d2afab0571b74c0c0d1aee0f631b33fdc7da - 17.2.0, backported to 17.1.x. Extra confirmation would be appreciated though ;-)

@MilhouseVH thanks, will do as follow-up. Might even make that a `PKG_MESA_XA` ;-)

**Comment by fritsch** [comment]
@evelikov yes - I am aware of that. Inside of kodi there is no support for that yet, which I wanted to point out.

**Comment by lrusak** [comment]
@evelikov sounds good to me. I'll look into implementing GLVND

**Comment by lrusak** [comment]
@MilhouseVH merge?

**Comment by MilhouseVH** [comment]
This needs a rebase after #2161, but once that is done I can test it (include it in test builds).

**Comment by MilhouseVH** [comment]
An adapted version of this PR (adapted due to context changes after #2161 which prevent the patch applying using most patching tools - gnu `patch`, `git am`, `git apply` all fail - but maybe github is smarter hence the lack of any warning) fails to build: http://sprunge.us/TTjW

It looks like at least one of the libraries removed by https://github.com/LibreELEC/LibreELEC.tv/pull/2163/commits/67bd798303975b7b44661ad2fa39f7cd3a0624bc should be restored.

**Comment by evelikov** [comment]
A comprehensive solution might be to introduce PKG_BUILD_TYPE=static (or perhaps just PKG_BUILD_STATIC), system wide, which:
 - adds -fPIC -DPIC and friends to *FLAGS
 - adds --enable-static --disable-shared to configure args
 - folds Libs.private into Libs for the produced .pc files
While doing ^^ on per-package basis, one could check/drop the explicit LIBS - other packages also are using the workaround.

Until something similar happens, please pull out the offending patch.
Add a reference to the issue (similar discussion on the topic) will be a good IMHO.

Let me know if you'd want me to respin the lot. Thanks!

**Comment by lrusak** [comment]
@evelikov would you mind dropping https://github.com/LibreELEC/LibreELEC.tv/pull/2163/commits/67bd798303975b7b44661ad2fa39f7cd3a0624bc for now and rebasing? Thanks :smile_cat:

**Comment by evelikov** [comment]
@lrusak done. I'd took the liberty of replacing the offending patch with one that explains the linking workaround.

**Comment by lrusak** [comment]
@evelikov thanks!

@MilhouseVH good to go?

**Comment by MilhouseVH** [comment]
All good now, many thanks.

**Pull request merged**
