### PR TITLE
chrome: improvements to launch script

### PR DESCRIPTION
**Pull request by antonlacon**
Improvements to chrome's launch script. Replaces #5983 (credit should be shared in commit...). Changes:

Increase debug output if it throws an exception on launch
Allows launching with custom audio devices
More pythonic on launching subprocesses

This is untested.

@pohutukawa if you're around to test, it would be appreciated. @mglae you reviewed the previous if you have time to look at this. I don't fully understand why getAudioDeviceType() returns ALSA for everything other than Pulse (not even a None if no dev...)

### CODE REVIEW

**Comment by mglae** [comment]
> I don't fully understand why getAudioDeviceType() returns ALSA for everything other than Pulse

Backward compatibility to existing installations, there was no prefix before.

Fixes:
```
--- a/packages/addons/browser/chrome/source/default.py
+++ b/packages/addons/browser/chrome/source/default.py
@@ -42,9 +42,9 @@ def _print_exception():
 def startchrome(args):
   try:
     chrome_env = {
-      'VAAPI_MODE': __addon__.getSetting('VAAPI_MODE')
-      'WINDOW_MODE': __addon__.getSetting('WINDOW_MODE')
-      'RASTER_MODE': __addon__.getSetting('RASTER_MODE')
+      'VAAPI_MODE': __addon__.getSetting('VAAPI_MODE'),
+      'WINDOW_MODE': __addon__.getSetting('WINDOW_MODE'),
+      'RASTER_MODE': __addon__.getSetting('RASTER_MODE'),
       'DARK_MODE': __addon__.getSetting('DARK_MODE')
     }
 
@@ -116,7 +116,7 @@ if (not __addon__.getSetting("firstrun")):
   __addon__.openSettings()
 
 try:
-  args = sys.argsv[1:]
+  args = sys.argv[1:]
 except Exception:
   args = ''
 
```

**Comment by antonlacon** [comment]
Thanks, fixed!

**Comment by mglae** [comment]
@heitbaum  Please add this to #7101. Chrome is working for me, we can merge it.

**Comment by heitbaum** [comment]
> @heitbaum Please add this to #7101. Chrome is working for me, we can merge it.

I have added the commit to 7101

**Comment by CvH** [comment]
superseded by https://github.com/LibreELEC/LibreELEC.tv/pull/7101

**Pull request closed without merging**
