### PR TITLE
HACK: fix audio for WP1

### PR DESCRIPTION
**Pull request by CvH**
We have a lot reports that WP1 audio is broken, this HACK makes it work again. 
This is no proper fix but there is currently nothing else available to have working audio at WP1.
It is an adapted version of https://github.com/LibreELEC/xbmc/commit/dd2255d77e5c3a819a92543de9f3ce276a522947
from https://www.kodinerds.net/index.php/Thread/62885-LE-9-auf-Wetek-Play-Ton-seltsam/?postID=483736#post483736

I have no WP1 so I can't test it at all (I ship an testimage to the forum).

### CODE REVIEW

**Comment by chewitt** [comment]
We should patch our own 3.10 kernel source in https://github.com/LibreELEC/linux-amlogic and then update the Linux package. Assuming it tests positively.

**Comment by CvH** [comment]
That is an kodi patch not an Linux patch.
Ofc there is likely a way to fix it at the kernel/driver but we have nothing for that yet.

**Comment by chewitt** [comment]
I'll get my coat..

**Comment by ashimokawa** [comment]
I *think* the transfer align for this device is 8 samples and when resampling this is no longer the case. By forcing the buffer to be filled completely the alignment stays intact. A "softer" workaround *might* be to just honour this constraint and only submit multiples of 8 samples.

**Comment by CvH** [comment]
ping @fritsch , any opinions ?
We like to avoid those hacks but currently we are sadly out of options besides dropping the whole device (very likely Wetek Core too).

**Comment by fritsch** [comment]
Same hack as four years ago ... please fix the root cause, e.g. return correct size from audio driver.

**Comment by fritsch** [comment]
It won't appear magically. It's something the vendor needs to provide / mainline kernel needs to provide. You know this issue will happen on all other Linux applications as well.

**Comment by fritsch** [comment]
Can you describe the "issue" that you hear?

From the code I think you get issues if less than "period" frames are added to the sink, right?

The patch as is, is a hack - cause there is no guarantee at all that AE "fills" you with amount of period frames at one go.

**Comment by CvH** [comment]
@fritsch I have no WP1/WC so no idea actually
From what I read here https://www.kodinerds.net/index.php/Thread/62885-LE-9-auf-Wetek-Play-Ton-seltsam/ the sound is `schrabbelig` (no idea how to translate) - other posts at the LE forum pointing to the exact same problem.

**Comment by fritsch** [comment]
Okay, the real fix here is, that the driver padds if frames don't fit its alignment. Normally the ALSA driver causes an interrupt after "#period" of frames. It seems to me that this driver here does it "directly" by assuming someone would only add "#period" frames at once.

Can you prepare a log for me, that output how AddPackets is called? E.g. number of frames and so on?

**Comment by fritsch** [comment]
And where is the kernel source? - so I can take a look.

**Comment by CvH** [comment]
as I have no hw maybe @codesnake can help ?

**Pull request merged**
