### PR TITLE
openssh: update to 9.2p1

### PR DESCRIPTION
**Pull request by heitbaum**
release notes:
- https://www.openssh.com/releasenotes.html#9.2p1

log:
- https://github.com/openssh/openssh-portable/compare/V_9_1_P1...V_9_2_P1

### CODE REVIEW

**Comment by CvH** [comment]
LE12 ?

**Comment by heitbaum** [comment]
> LE12 ?

Either are fine by me. It is pretty much all bugfixing (so suggested LE11)

**Comment by heitbaum** [comment]
> > LE12 ?
> 
> Either are fine by me. It is pretty much all bugfixing (so suggested LE11) no changes of ciphers, so compatibility there should be good.

**Comment by HiassofT** [comment]
release notes mention potential security issues so I'd say it's definitely LE11 material

**Review by HiassofT — APPROVED** [review]

**Pull request merged**
