### PR TITLE
plymouth-lite bootsplash was not displaying since kernel 6.6

### PR DESCRIPTION
**Pull request by heitbaum**
Tested on Generic
- plymouth-lite requires CONFIG_FB_DEVICE=y

~~Needs a further review as Plymouth is suppose to work with drm. But maybe -lite doesn’t.
All .config will need to be fixed.~~

Confirmed that /dev/fb0 is required.
https://github.com/neochapay/plymouth-lite/blob/32c3abd6108ed37dc7589b3ef9efa47af64a9090/ply-frame-buffer.c#L47

### CODE REVIEW

**Comment by lrusak** [comment]
Please add to distributions/LibreELEC/kernel_options

**Comment by heitbaum** [comment]
> Please add to distributions/LibreELEC/kernel_options

I left it out as it is not applicable to 6.1. Something to add once we move RPi to 6.[67]lts?

**Comment by chewitt** [comment]
@heitbaum please create a Draft PR for the kernel_options change with a comment to merge once Pi kernels bump beyond Linux 6.1.y so we don't forget it, then this can go in.

**Comment by heitbaum** [comment]
> @heitbaum please create a Draft PR for the kernel_options change with a comment to merge once Pi kernels bump beyond Linux 6.1.y so we don't forget it, then this can go in.

Added draft #8286

**Review by chewitt — APPROVED** [review]

**Pull request merged**
