### PR TITLE
Add PKG_SOURCE_NAME for non-standard package tarballs

### PR DESCRIPTION
**Pull request by lrusak**
@MilhouseVH are you happy with this currently?

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Yes, I'm happy - thanks.

**Comment by lrusak** [comment]
Don't merge yet because I'll have to adjust all the packages that use the old github releases method first

**Comment by MilhouseVH** [comment]
One anomaly when pulling direct from github is that a `PKG_URL` such as the following (which is just an example) can create a different filename to that which is requested:

```
PKG_NAME="libcec"
PKG_VERSION="6d68d21"
PKG_URL="https://github.com/Pulse-Eight/libcec/archive/$PKG_VERSION.tar.gz"
```
ie. https://github.com/Pulse-Eight/libcec/archive/6d68d21.tar.gz

This will download a tar with the name `libcec-6d68d21243aa92862592435e8396b4280ea46c3f.tar.gz`, which in turn - when unpacked - will create a build directory named `libcec-6d68d21243aa92862592435e8396b4280ea46c3f`.

This can be fixed with the addition of the following in the `package.mk`:
```
PKG_SOURCE_DIR="${PKG_NAME}-${PKG_VERSION}*"
```

However it's possible this could be performed automatically whenever PKG_SOURCE_DIR is not defined, here: https://github.com/lrusak/OpenELEC.tv/blob/download-changes/scripts/unpack#L88-L90, ie.:
```
if [ -n "$PKG_SOURCE_DIR" ]; then
  mv $BUILD/$PKG_SOURCE_DIR $BUILD/$PKG_NAME-$PKG_VERSION
elif [ ! -d $BUILD/$PKG_NAME-$PKG_VERSION ]; then
  mv $BUILD/$PKG_NAME-${PKG_VERSION}* $BUILD/$PKG_NAME-$PKG_VERSION
fi
```
I can update if you think this a good idea.

**Comment by lrusak** [comment]
Updated with @MilhouseVH changes
should be good to go :+1:

**Pull request merged**
