### PR TITLE
enable dynamic configuration of netconsole at runtime

### PR DESCRIPTION
**Pull request by avinson**
see this thread for more information: https://forum.libreelec.tv/thread/7315-8-0-x-netconsole-feature-unusable-and-the-way-to-fix-it/

netconsole is currently unusable because it is initialized prior to network devices and so cannot be configured properly via boot params. this PR enables dynamic runtime configuration for netconsole.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
So that all projects have feature parity (which simplifies support), can you cherry-pick the 7 commits from this branch and add them to this PR:

https://github.com/LibreELEC/LibreELEC.tv/compare/master...MilhouseVH:le90_dynamic_netconsole

**Comment by MilhouseVH** [comment]
And thanks for your contribution, btw!

**Comment by avinson** [comment]
@MilhouseVH done

**Comment by MilhouseVH** [comment]
@avinson any progress? This PR is going to rot pretty quickly with all the kernel changes that are lined up, but I don't want to merge this without confirmation that it is working. If we don't merge it soon you'll need to handle the rebasing that will be required.

**Comment by avinson** [comment]
@MilhouseVH I tested this tonight.. it looks like it needs `CONFIG_NET_POLL_CONTROLLER=y` which from my brief research looks like is not supported on rpi network controller :(

```
[  544.106930] netpoll: netconsole: local port 6665
[  544.106944] netpoll: netconsole: local IPv4 address 172.25.27.141
[  544.106949] netpoll: netconsole: interface 'eth0'
[  544.106955] netpoll: netconsole: remote port 6666
[  544.106960] netpoll: netconsole: remote IPv4 address 172.25.25.65
[  544.106969] netpoll: netconsole: remote ethernet address 00:1e:06:33:a7:59
[  544.106982] netpoll: netconsole: eth0 doesn't support polling, aborting
```

**Comment by MilhouseVH** [comment]
Yes, it doesn't look like netpolling is possible on the RPi: https://github.com/raspberrypi/linux/issues/1877

Does the `modprobe` solution work (once `CONFIG_NETCONSOLE=m` is configured)?

`CONFIG_NETCONSOLE` is not currently configured for Rockchip MiQi, RK3328, RKL3399 and TinkerBoard devices, so it would need to be added (as `m`), as well as changing all other projects. It's best to run `make oldconfig` for each project to determine the required options - if you need a hand with this I can provide you the extra commits as I did last time).

You can either update this PR to with the module solution, or close and open a new PR.

**Comment by avinson** [comment]
@MilhouseVH Compiling as a module won't make a difference. The issue is with the driver for the network controller. From https://wiki.ubuntu.com/Kernel/Netconsole:

```
The driver for the network card must support polling (netpoll api)
```

**Comment by MilhouseVH** [comment]
OK, then close? Or do you want to drop the RPi/RPi2 options and keep the rest (assuming they work, which is probably anyone's guess apart from Generic).

**Comment by avinson** [comment]
@MilhouseVH imho, I think we should merge as-is without dropping the RPi/RPi2 diff for a few reasons:

1) It's nice for support reasons to have the other kernel options such as `CONFIG_CONFIGFS_FS=y` synced across the projects and you already did the leg work on that for this PR.
2) Technically netconsole still "works" on RPi/RPi2 with this PR, just not with the current driver for the onboard network controllers. Adding an external network controller with netpoll support should work (although I'll admit that probably nobody will actually do this).
3) A future kernel update may potentially resolve the netpoll issue with the controller drivers and then netconsole will work out of the box in LibreELEC. It looks like the odroid team/community is actively working on this issue and their changes are being merged: https://github.com/hardkernel/linux/pull/299 so perhaps there is hope that RPi/RPi2 will get similar functionality eventually.

**Pull request merged**
