### PR TITLE
chrome: add missing lib to addon

### PR DESCRIPTION
**Pull request by CvH**
not build/runtime tested yet !

### CODE REVIEW

**Comment by chewitt** [comment]
@CvH can you please test/confirm this so we can either merge here or in #4376, thanks.

**Comment by CvH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/pull/4376 darkmod added

not sure but my system looks borked since some chrome versions, but it starts at least now

**Comment by Che-debarras** [comment]
Hi I wonder if chromz can be installed on Libreelec for android ?

**Comment by CvH** [comment]
@Che-debarras currently not possible for android boxes

**Pull request merged**
