### PR TITLE
linux: update to 6.10

### PR DESCRIPTION
**Pull request by heitbaum**
### packages updated
- linux: update to 6.10.x

# 6.10.x mainline kernel update
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.10

### errors / fixes / issues / regressions / todo

todo
  - NA

known Issues
  - wl (Generic)
    - [broadcom-wl-dkms](https://gitlab.archlinux.org/archlinux/packaging/packages/broadcom-wl-dkms/-/commits/main)
    - Causing thunk warning
    - #8941
    - https://github.com/torvalds/linux/commit/4461438a8405e800f90e0e40409e5f3d07eed381
    - https://bbs.archlinux.org/viewtopic.php?id=296729
    - https://discussion.fedoraproject.org/t/kernel-hangs-since-some-recent-fedora-kernels/120846/6?replies_to_post_number=5
    - https://bugzilla.rpmfusion.org/show_bug.cgi?id=6991
    - https://discussion.fedoraproject.org/t/kernel-hangs-since-some-recent-fedora-kernels/120846/17

fixes
  - na 

done
  - rtl 6.11
  - iwlwifi-firmware: update to githash d949433
  - strace - now compiling
  - nvidia
    - https://github.com/NVIDIA/open-gpu-kernel-modules/issues/642
    - fixed by #8974
  - Sony patch has been updated for 6.10 (but it is not supported in < 6.10)
    - packages/linux/patches/default/linux-058.05-hid_sony-add_autorepeat_for_PS3_remotes.patch
    - Patch is included an will require Amlogic to be bumped to 6.10 for Amlogic to compile

### log 
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.10.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.10.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/log/
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.10
- https://linux-regtracking.leemhuis.info/regzbot/mainline/
- https://linux-regtracking.leemhuis.info/regzbot/stable/

### 6.10 Build tested on all of:

```
PROJECT=Allwinner ARCH=aarch64 DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H3 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=R40 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=aarch64 DEVICE=RK3328 s/build linux
PROJECT=Rockchip ARCH=aarch64 DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX6 s/build linux
PROJECT=NXP ARCH=aarch64 DEVICE=iMX8 s/build linux
PROJECT=Qualcomm ARCH=aarch64 DEVICE=Dragonboard s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
```

### 6.10.y Run tested on all of:
- Allwinner all - tested - TBA - jernejsk
- Allwinner H6 (Tanix TX6) - TBA - heitbaum
- Generic Generic (Intel ADL - NUC12) - 6.10 - heitbaum
- NXP iMX6 (Cubox-i4Pro) - TBA - heitbaum
- Rockchip RK3399pro (Rock Pi N10) - TBA - heitbaum
- RK all - tested - TBA - knaerzche
- Samsung Exynos (Hardkernel ODROID XU4) - TBA - heitbaum

### CODE REVIEW

**Comment by chewitt** [comment]
@heitbaum there are two patchsets needed for RTL8192DU support. These are commits in my `amlogic-6.9.y` branch:

```
da2287b41888e02866f1416caa36c148c5723f8b FROMGIT(6.11): wifi: rtlwifi: Enable the new rtl8192du driver
11fc9ecc1d73fd506a3bd359bf3f8b9a94ca59df FROMGIT(6.11): wifi: rtlwifi: Add rtl8192du/sw.c
c791ad6e48ba58f4473b899ba7bf2de1d1536d17 FROMGIT(6.11): wifi: rtlwifi: Constify rtl_hal_cfg.{ops,usb_interface_cfg} and rtl_priv.cfg
e4592b803eb8ff3eda15c030906cc33226cc794e FROMGIT(6.11): wifi: rtlwifi: Add rtl8192du/dm.{c,h}
07d8e12d4523008675013f91d46a8a8d133a41c2 FROMGIT(6.11): wifi: rtlwifi: Add rtl8192du/fw.{c,h} and rtl8192du/led.{c,h}
f42c4cb0031563e684a66ea2e21072387d9fcc7f FROMGIT(6.11): wifi: rtlwifi: Add rtl8192du/rf.{c,h}
8125d619567b9a3620244251b8eab25074cafcfa FROMGIT(6.11): wifi: rtlwifi: Add rtl8192du/trx.{c,h}
40249d26740fceb059f121dde0922de1f9ec209a FROMGIT(6.11): wifi: rtlwifi: Add rtl8192du/phy.{c,h}
37626e4f236435875f40fd3e8a463aac1cd47c8b FROMGIT(6.11): wifi: rtlwifi: Add rtl8192du/hw.{c,h}
34ddbe7398b1e23d78192999dcc88a7f57bcaae5 FROMGIT(6.11): wifi: rtlwifi: Add new members to struct rtl_priv for RTL8192DU
76b9d3316e2d5db38de05e1ad8fe3c6acaabf21a FROMGIT(6.11): wifi: rtlwifi: Add rtl8192du/table.{c,h}
dec5fc45e4b69ac5c4c628fa9e482199d6e5ad71 FROMGIT(6.11): wifi: rtlwifi: rtl8192d: Use "rtl92d" prefix
...
d34a7e456b723f5b5b11834abd39f46352d2b776 FROMGIT(6.10): wifi: rtlwifi: Ignore IEEE80211_CONF_CHANGE_RETRY_LIMITS
7335e62025a7cfe186aab54609b23c4f24d838e0 FROMGIT(6.10): wifi: rtlwifi: Adjust rtl8192d-common for USB
01596bb6b5fa383bd37590981b6cf660ad5d51f4 FROMGIT(6.10): wifi: rtlwifi: Clean up rtl8192d-common a bit
eb9c40199ae9ae29f43705a11b7a0dba79dcfb8b FROMGIT(6.10): wifi: rtlwifi: Move code from rtl8192de to rtl8192d-common
91b01523927c0e78c0c53c0c8347ee9d194d34f0 FROMGIT(6.10): wifi: rtlwifi: rtl8192de: Fix endianness issue in RX path
93f781bf3955bd65a73ad8878c6f76439cdd4aaf FROMGIT(6.10): wifi: rtlwifi: rtl8192de: Fix low speed with WPA3-SAE
b51a3b582d9626e5b896141c9b9edbf0d49d147d FROMGIT(6.10): wifi: rtlwifi: rtl8192de: Fix 5 GHz TX power
```

To fully drop the vendor driver RPi needs the 6.10 + 6.11 patches and everything else needs only the 6.11 patches. Then all need a defconfig change to select the module. I haven't tried backporting onto the RPi 6.6 kernel but `iwlwifi` is low-traffic so I expect they will apply. Some of the 6.10 patches may have been picked to stable as well so might end up in the Pi kernel that we pull. If we create patchsets that apply to all I'll drop them from `amlogic-6.10.y` and push that to align.

**Comment by heitbaum** [comment]
> To fully drop the vendor driver RPi needs the 6.10 + 6.11 patches and everything else needs only the 6.11 patches. Then all need a defconfig change to select the module. I haven't tried backporting onto the RPi 6.6 kernel but `iwlwifi` is low-traffic so I expect they will apply. Some of the 6.10 patches may have been picked to stable as well so might end up in the Pi kernel that we pull. If we create patchsets that apply to all I'll drop them from `amlogic-6.10.y` and push that to align.

I’ll give it a try - “long weekend here this weekend”

**Comment by heitbaum** [comment]
Looks like it works for 6.9 and 6.6 (and 6.10) 

I have moved the 6.10 patches and 6.11 patches it to separate directories, added what I believe are the missing 6.7-6.9 patches, and updated all the .configs. All unpacks are successful. Now for a full build / run.

if this all does work - do we want to split the change RTL8192DU into its own PR?

**Comment by heitbaum** [comment]
@chewitt full compile of all “build linux” has worked. So RTL8192DU can be dropped across the board. I will separate this into its own PR against the current 6.9 and 6.6 kernels. So this can be now be tested with RPi (and others - although with already Amlogic 6.9 tested - should be ok on the others)

**Comment by eldersixpack13** [comment]
@heitbaum  are you aware of this bug/patch, too ?

https://bugzilla.kernel.org/show_bug.cgi?id=201761

**Comment by heitbaum** [comment]
> @heitbaum are you aware of this bug/patch, too ?
> 
> https://bugzilla.kernel.org/show_bug.cgi?id=201761

It’s a kernel fix, so would expect it to be backported to stable when it is merged upstream.

**Comment by eldersixpack13** [comment]
> > @heitbaum are you aware of this bug/patch, too ?
> > https://bugzilla.kernel.org/show_bug.cgi?id=201761
> 
> It’s a kernel fix, so would expect it to be backported to stable when it is merged upstream.

quiet clear to me.
my intension was just to prevent (maybe) user reports in the the forum or so, in case the unpatched Kernel 6.10 hits LE13
that's all

**Review by CvH — APPROVED** [review]

**Pull request merged**
