### PR TITLE
kodi: update to 19.0b2-Matrix

### PR DESCRIPTION
**Pull request by HiassofT**

### CODE REVIEW

**Comment by HiassofT** [comment]
runtime tested on RPi4

**Comment by HiassofT** [comment]
RPi2 looks good, too

**Comment by HiassofT** [comment]
added binary addon bumps, all addons with version bumps (inputstream.ffmpegdirect pvr.hdhomerun pvr.hts pvr.iptvsimple pvr.vuplus pvr.waipu vfs.sacd) built fine for RPi4.

Also bumped PKG_REV of all addons without PKG_VERSION change so rebuilt versions get rolled out

**Comment by HiassofT** [comment]
updated with reverted vfs.sacd PKG_VERSION change, vfs.sacd is now deprecated and removed from kodi repo, so the script fell back to unofficial addon bumping, resolving latest hash instead of tag.

We probably should remove vfs.sacd at some point, too

**Comment by heitbaum** [comment]
Looks good on Generic

```
2020-12-08 02:47:35.296 T:1200     INFO <general>: Starting Kodi (19.0-BETA2 (18.9.821) Git:19.0b2-Matrix). Platform: Linux x86 64-bit
2020-12-08 02:47:35.296 T:1200     INFO <general>: Using Release Kodi x64
2020-12-08 02:47:35.296 T:1200     INFO <general>: Kodi compiled 2020-12-07 by GCC 10.2.0 for Linux x86 64-bit version 5.9.12 (329996)
2020-12-08 02:47:35.296 T:1200     INFO <general>: Running on LibreELEC (community): devel-20201207142003-b781374 9.80, kernel: Linux x86 64-bit version 5.9.12
2020-12-08 02:47:35.296 T:1200     INFO <general>: FFmpeg version/source: 4.3.1-Kodi
2020-12-08 02:47:35.296 T:1200     INFO <general>: Host CPU: Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz, 4 cores available
```

**Review by CvH — APPROVED** [review]

**Pull request merged**
