### PR TITLE
tvheadend42: fix build with empty ARCH variable

### PR DESCRIPTION
**Pull request by InuSasha**

### CODE REVIEW

**Comment by vpeter4** [comment]
Isn't ARCH variable specified on command line?
`PROJECT=Generic ARCH=x86_64 ...`

**Comment by InuSasha** [comment]
@vpeter4: not needed by Generic.
$> export ARCH= DEVICE= PROJECT=

**Comment by vpeter4** [comment]
Wondering why other projects needs to set ARCH variable ;)

**Comment by stefansaraev** [comment]
https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/options#L23

here. add ARCH=x86_64. done :)

**Comment by InuSasha** [comment]
@stefansaraev had make new PR following your suggestion.
A tested the replacement of ARCH with TARGET_ARCH in the addon, but other build error occurred.

**Comment by CvH** [comment]
replaced by https://github.com/LibreELEC/LibreELEC.tv/pull/1672

**Pull request closed without merging**
