### PR TITLE
ffmpeg: sync with kodi

### PR DESCRIPTION
**Pull request by HiassofT**
Seems we forgot to bump it to 4.4.1-Nexus-Alpha1 when we updated kodi to Alpha1.
av1 patch is now included in kodi patches so we can drop the local patch.

Runtime test on RPi4 was fine, but the v4l2-request patch currently doesn't apply on Generic, AW etc - @jernejsk could you rebase your branch?

### CODE REVIEW

**Comment by heitbaum** [comment]
This is the patch I just tested with:

```
diff --git a/packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-request.patch b/packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-re
quest.patch
index 5062d475f2..6ff0f2853d 100644
--- a/packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-request.patch
+++ b/packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-request.patch
@@ -1312,9 +1312,9 @@ index c3a7338a70..c28b58cd5d 100644
          sl->idr_pic_id = get_ue_golomb_long(&sl->gb);

 +    pos = sl->gb.index;
+     sl->poc_lsb = 0;
+     sl->delta_poc_bottom = 0;
      if (sps->poc_type == 0) {
-         sl->poc_lsb = get_bits(&sl->gb, sps->log2_max_poc_lsb);
-
 @@ -1845,6 +1846,7 @@ static int h264_slice_header_parse(const H264Context *h, H264SliceContext *sl,
          if (pps->pic_order_present == 1 && picture_structure == PICT_FRAME)
              sl->delta_poc[1] = get_se_golomb(&sl->gb);
```

**Comment by jernejsk** [comment]
Created two new branches v4l2-request-hwaccel-4.4.1-Nexus-Alpha1 and v4l2-drmprime-v6-4.4.1-Nexus-Alpha1, thanks to @knaerzche

**Comment by HiassofT** [comment]
Thanks, I've now updated v4l2 request and drmprime patches to 4.4.1 branches.

I also noticed AML sources the RPi fork instead of the kodi ffmpeg fork, so it still needs the dav1d patch - I've now moved it to a separate patch dir which is only used by AML.

Runtime test on RPi4 worked fine, unpacking for AW and AML tested, too.

This should now be good for testing and merging

**Comment by heitbaum** [comment]
> Thanks, I've now updated v4l2 request and drmprime patches to 4.4.1 branches.
> 
> I also noticed AML sources the RPi fork instead of the kodi ffmpeg fork, so it still needs the dav1d patch - I've now moved it to a separate patch dir which is only used by AML.
> 
> Runtime test on RPi4 worked fine, unpacking for AW and AML tested, too.
> 
> This should now be good for testing and merging

Build and run tested on Generic TGL

**Review by heitbaum — APPROVED** [review]

**Pull request merged**
