### PR TITLE
Use Linaro GCC 5.3

### PR DESCRIPTION
**Pull request by fboudra**

### CODE REVIEW

**Comment by lrusak** [comment]
why?

**Comment by fboudra** [comment]
It's the latest release supported by us. There's no reason to stick to 4.9, and aarch64-none-elf isn't even needed. In addition, we'll be able to use it to cross-build librelec completely with this toolchain optimized for ARM platforms.

**Comment by lrusak** [comment]
This whole precompiled toolchain thing is kind of a hack to begin with. Did you try and compile u-boot with this? Does it work? Last time I tried using 5.3 (our cross build gcc) u-boot would build but fail to actually boot the kernel.

> In addition, we'll be able to use it to cross-build libreelec completely with this toolchain optimized for ARM platforms

Why would you want to? We cross build gcc specifically for our platform, what makes yours better?

I appreciate the support, I just don't understand why this is really needed 😄

**Comment by fboudra** [comment]
On 10 May 2016 at 20:58, Lukas Rusak <notifications@github.com> wrote:

> This whole precompiled toolchain thing is kind of a hack to begin with.
> Did you try and compile u-boot with this? Does it work? Last time I tried
> using 5.3 (our cross build gcc) u-boot would build but fail to actually
> boot the kernel.
>
I think the recipe took this version because it's the version documented on
hardkernel wiki. I tried, compiled and it works with Linaro GCC 5.3.


> In addition, we'll be able to use it to cross-build libreelec completely
> with this toolchain optimized for ARM platforms
>
> Why would you want to? We cross build gcc specifically for our platform,
> what makes yours better?
>
Linaro is well known for producing good quality and optimized toolchain for
ARM platforms.
As you may notice, many vendors are using our toolchain (including ARM,
hardkernel, freescale, TI, etc..)
Our Toolchain Working group is composed by several toolchain experts and
contributors to GCC upstream.
We have intensive testing of the toolchain and benchmarks done for each
release.
It's used in various distributions, like Debian, Ubuntu and OpenEmbedded
(through meta-linaro layer).

> I appreciate the support, I just don't understand why this is really
> needed 😄
>

It's definitely better than what is currently available in libreelec and it
opens the door to build the full system with this toolchain.

**Comment by lrusak** [comment]
I can give this a try and see if if boots properly.

I am just one person on this team but I think the rest of the team will agree with me when I say that we don't want to use a precompiled toolchain to build LibreELEC. Half the magic of our buildsystem is that everything is compiled from scratch (almost). 

If you would like to contribute patches or help us get our toolchain in a better working state so that we can build and boot u-boot that would be much appreciated.

**Comment by fboudra** [comment]
On 10 May 2016 at 21:29, Lukas Rusak <notifications@github.com> wrote:

> I can give this a try and see if if boots properly.
>
> I am just one person on this team but I think the rest of the team will
> agree with me when I say that we don't want to use a precompiled toolchain
> to build LibreELEC. Half the magic of our buildsystem is that everything is
> compiled from scratch (almost).
>

We can certainly build Linaro GCC from scratch ;)
http://releases.linaro.org/components/toolchain/gcc-linaro/5.3-2016.02/gcc-linaro-5.3-2016.02.tar.xz


> If you would like to contribute patches or help us get our toolchain in a
> better working state so that we can build and boot u-boot that would be
> much appreciated.
>
To clarify, I'm not pushing for replacing libreelec toolchain. Long term,
I'd like to have the option to be able to use an external toolchain.
Work is already done into improving Linaro toolchain (it's tracking FSF GCC
and include several backports).
I think time is better spent into using directly the toolchain (either from
source or binary) instead of redoing the work on top of libreelec toolchain.

Again, the main intent of this patchset is targeted at odroid c2 support,
using latest released binary toolchain.
I think it's a step in the right direction.

Extending the usage to the whole distro is another story, and up to
libreelec team.
If there's no interest in this goal, I can definitely continue to do a
custom build for my own usage.

**Comment by wrxtasy** [comment]
I will give this a try as well for the C2.
It is only aarch64 specific at the moment for the C2, but I can see lrusak point as well.
So sitting on the fence and just testing at the moment.

**Comment by fboudra** [comment]
FWIW, my patch u-boot-001-gcc5-support.patch has been merged upstream (in hardkernel U-Boot):
https://github.com/hardkernel/u-boot/pull/24

Any chance to get this pull request revisited?

**Comment by chewitt** [comment]
I'm closing this PR. We are not against changing things in the build-system, but items like this need to be properly investigated. Right now we have something that is proven and working and higher priorities for build-system evolution. Thanks.

**Comment by fboudra** [comment]
@chewitt actually by closing the PR, you are against changing things in the build system. It has been investigated by me and nobody showed up to prove it doesn't work as intended. So when the developers  doing the toolchain that you are using today tells you that it's recommended to use the new one which is supported by us, you push back.

**Comment by MilhouseVH** [comment]
@fboudra: Did see the comment on the following commit?

https://github.com/LibreELEC/LibreELEC.tv/commit/44cbace0b7b6ec4c69f86163cb95c47d55a126df

**Comment by fboudra** [comment]
@MilhouseVH no, I missed it. Thanks for the pointer!

**Pull request closed without merging**
