### PR TITLE
TUF dependencies

### PR DESCRIPTION
**Pull request by thoradia**
@Raybuntu 
Here is an alternative for TUF dependencies. Python dependencies are found in "$(get_build_dir le_tuf)/.install_pkg/lib/python)". You know where to find libsodium.

It will be possible to add securesystemslib through setup.py of le_tuf and thus remove the securesystemslib package when https://github.com/secure-systems-lab/securesystemslib/commit/d60b1c1ea5bb8678f6b2badf95298d9ad69ea3c9#diff-2eeaed663bd0d25b7e608891384b7298 is released.

It is not possible to simplify cffi, but hey, this is how it works.

Full version control of Python packages is possible through setup.py of le_tuf (I updated cryptography to 2.1.1).

This considerably reduces the number of packages to maintain.

I hope you will find the time to confirm this works. Thank you in advance.

### CODE REVIEW

**Comment by Raybuntu** [comment]
@thoradia Thanks for this! Is it the same as https://github.com/LibreELEC/LibreELEC.tv/pull/2059?
I do like your ideas especially to simplify/centralize python building. I'd like to get some feedback from others about those automatic egg installs.
I'm happy to drop my PR in favor of this.

**Comment by thoradia** [comment]
This PR reuses/reworks the parts of #2059 relevant to TUF.
I keep #2059 open until I determine how to propose cython/lxml/etc

**Comment by thoradia** [comment]
Rebased to cross-compile securesystemslib

**Comment by thoradia** [comment]
@Raybuntu 

I have further simplified building Python packages:
- cross compiling is done by easy_install
- le_tuf package is a single file
- libsodium is built static and therefore included in the Python packages

For target, the proposed Python package build system creates eggs (unzipped, without .py files, in $INSTALL/lib) which may be added individually to PYTHONPATH

**Comment by thoradia** [comment]
@Raybuntu 

I have updated this to use securesystemslib (f7f51ac) from github.

Package are pinned to their respective current version. These versions will systematically be rebuilt.

The built eggs may be used in several ways:
- install the eggs in site-packages
- add each egg individually in PYTHONPATH
- copy the content of the eggs somewhere in PYTHONPATH

This method can be used to build separate sets of Python packages, eg one set for LibreELEC and respective sets for add-ons, which may include different versions of a same package if required.

**Comment by thoradia** [comment]
I merged this downstream, closing

**Pull request closed without merging**
