### PR TITLE
RBP: Bump Kodi Jarvis backport

### PR DESCRIPTION
**Pull request by MilhouseVH**
This includes [a fix](https://github.com/popcornmix/xbmc/commit/7367c175628cac663dd5cbea18bef17e9c74f992) for http://forum.libreelec.tv/thread-118.html

### CODE REVIEW

**Comment by lrusak** [comment]
should probably go into the libreelec-7.0 branch

**Comment by MilhouseVH** [comment]
You're right, I'll submit another PR for le7

**Comment by MilhouseVH** [comment]
Do you want to merge this one or close it?

**Comment by lrusak** [comment]
It's probably not needed

**Pull request closed without merging**
