### PR TITLE
various: add missing dependencies

### PR DESCRIPTION
**Pull request by InuSasha**
adds some missing dependencies.

found with this script: https://github.com/InuSasha/LibreELEC.tools/blob/master/dependency_check.sh
Tested Devices: Generic, RPi2, RPi4, AMLG12, H6, RK3399

found some additional problems, but do not know the solution
Devices: 
* AMLG12/arm
* H6/arm
* RK3399/arm

Packages: 
* screensaver.asteroids
* visualization.shadertoy
* visualization.spectrum
* visualization.waveform

Problem: all they do not find the GLES libs

### CODE REVIEW

**Comment by jernejsk** [comment]
Issue is in libmali package and headers it provides. That package provides only partial GLES3 headers. cmake opengles script searches for GLES3/gl3.h header, which libmali provides and enables GLES3. However, when GLES3 is enabled, kodi/gui/gl/GL.h (included by screensaver.asteroid) expects also GLES3/gl3ext.h, which is not provided by libmali.

Another problem is that libmali provides also GLES2 only GPU drivers, which means GLES3 headers are completely unnecessary and may lead to misdetections like this here. For such GPUs libmali shouldn't even install GLES3 headers.

BTW, screensaver.asteroid carries it's own old copy of kodi/gui/gl/GL.h, which shouldn't be necessary.

**Comment by jernejsk** [comment]
Dropping (empty) gl3ext.h (like https://gitlab.freedesktop.org/mesa/mesa/blob/master/include/GLES3/gl3ext.h) in toolchain fixes the problem. I'll make PR to libmali...

**Comment by InuSasha** [comment]
reported build problems, are solved with https://github.com/LibreELEC/libmali/pull/9

we can merge this PR and make a new PR for the libmali change (@jernejsk)

**Comment by MilhouseVH** [comment]
@InuSasha worth adding the script to this PR (or in a separate PR)?

**Comment by jernejsk** [comment]
Finally found time to do a PR: https://github.com/LibreELEC/LibreELEC.tv/pull/3994

**Comment by InuSasha** [comment]
rebased on master and readd kodi to game.libretro as dependency (was "indirect" removed in #3986)

**Comment by MilhouseVH** [comment]
Yeah, sorry I missed the indirect `kodi` dependency.

Some Kodi 19 binary addons are starting to drop their dependency on `kodi-platform` which is what we use to add the `kodi` dependency (and also `p8-platform`).

It might be best to continue to use `kodi-platform` for consistency with all other binary addons, and then mass change all binary add-ons to something more appropriate in future (to `kodi`, or to something else?)

As an aside, I know we want to avoid the `kodi` dependency when possible so that we don't have to build `kodi` before building an add-on just because the add-on needs the `kodi` headers. But so far we don't have a solution for this.

**Comment by dhewg** [comment]
My bad, sorry about the `kodi` dependency.
Maybe the build system can take care of that automatically?

**Comment by InuSasha** [comment]
no problem, this can happen.
i do not think, the buildsystem can take care automaticly. how should the buildsystem find out, which package has which dependencies?
hardcode some dependencies is very confusing. After some days, all of us has forgotten this XD

**Pull request merged**
