### PR TITLE
kodi.sh: upgrade crash log information

### PR DESCRIPTION
**Pull request by mglae**
Write more information into kodi crash log.

Use full back trace. Add CPU register dump and disassembly of current function.

### CODE REVIEW

**Comment by lrusak** [comment]
Can you provide sample output before and after?

**Comment by mglae** [comment]
Milhouse Generic 0210 configured for recent WOL crash:

Before: http://ix.io/1B5A

After: http://ix.io/1B5B

**Comment by MilhouseVH** [comment]
Personally I think this adds an awful lot more information that for the most part is noise which makes the backtrace generally more difficult to work with and interpret, however after discussing this on Slack I would concede there are times when this additional information might be useful to a developer.

So to that end, how about making this optional, the default being the current "plain" backtrace, but generate the more detailed backtrace if `/storage/.config/debug.enhanced` exists? That way, users (ie. developers like yourself) that want the enhanced backtrace can enable it easily and permanently, and if a developer feels the enhanced backtrace would be useful then they can instruct end users how to enable it.

**Comment by mglae** [comment]
I expected someone saying "ugly", but only found very seldom useful information in the plain backtrace.

`debug.enhanced` is a good compromise.

**Pull request merged**
