### PR TITLE
Revert "Allwinner: Set ondemand as default cpufreq governor"

### PR DESCRIPTION
**Pull request by christian-0s**
This reverts commit 4f456fe66851136b68ea7f203f1c842f190f3c5c.
This caused a problem with CEC

### CODE REVIEW

**Comment by MilhouseVH** [comment]
What kind of problem? Can you provide a few more details before we can even consider reverting this?

**Comment by jernejsk** [comment]
LE forum: https://forum.libreelec.tv/thread/17565-nightly-images-for-a20-a64-h3-h5-and-h6-boards/?postID=137275#post137275

Reason why it might be so: HDMI CEC on almost all AW SoCs supported by LE is solved by bitbanging, e.g. software implementation. My theory is that frequency changes affect timing in some way. But since I don't have oscilloscope at hand, I can't confirm it.

**Comment by christian-0s** [comment]
> What kind of problem? Can you provide a few more details before we can even consider reverting this?

Hi @MilhouseVH , details are in LE forum, Allwinner thread. CEC kept disconnecting after a few keystroke, using git bisect as suggested by @jernejsk I found this commit as the root cause. Reverting it on latest master the problem disappeared.

**Comment by MilhouseVH** [comment]
Thanks, it's useful to connect this PR to the thread for those that aren't following the thread.

**Comment by jernejsk** [comment]
Thank you for your work, I imagine that bisecting took quiet some time.

**Pull request merged**
