### PR TITLE
Enable ATH10K Atheros 802.11ac drivers in Generic x86_64 kernel

### PR DESCRIPTION
**Pull request by devec0**
LibreELEC on x86_64 does not currently enable drivers for Atheros 802.11ac cards.
This PR enables the necessary drivers so that the ATH10K driver is included by default,
enabling the use of 802.11ac cards in addition to already enabled 802.11n Atheros cards.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Can you add these missing kernel options to the PR: http://ix.io/FAK

Do you know which (if any) [ath10k firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/ath10k) is required? Unfortunately including them all will add another 7.5MB in addition to the 0.5MB of ath10k kernel modules, so I'd rather be selective if possible.

Please install this [LE9/Kodi 18 test build](http://milhouse.libreelec.tv/builds/testing/Generic/LibreELEC-Generic.x86_64-9.0-Milhouse-20180210010018-%230209w-g7f93f94.tar) (which includes this PR, and the additional options) to confirm if there are any firmware requirements.

**Comment by devec0** [comment]
Thanks for the review.

I have added the missing options, and am currently building an image based on the PR, but will also test the provided image as well. When I have tested previously, I have not had to include additional firmware, but that was on OpenELEC. The card I have for testing is an Atheros QCA986x/988x chip.

The firmware I currently have installed on a working install with this card (and likely others) supportable are as follows -

```
/lib/firmware/ath10k/
/lib/firmware/ath10k/QCA6174
/lib/firmware/ath10k/QCA6174/hw2.1
/lib/firmware/ath10k/QCA6174/hw2.1/board-2.bin
/lib/firmware/ath10k/QCA6174/hw2.1/board.bin
/lib/firmware/ath10k/QCA6174/hw2.1/firmware-5.bin
/lib/firmware/ath10k/QCA6174/hw2.1/notice_ath10k_firmware-5.txt
/lib/firmware/ath10k/QCA6174/hw3.0
/lib/firmware/ath10k/QCA6174/hw3.0/board-2.bin
/lib/firmware/ath10k/QCA6174/hw3.0/board.bin
/lib/firmware/ath10k/QCA6174/hw3.0/firmware-4.bin
/lib/firmware/ath10k/QCA6174/hw3.0/notice_ath10k_firmware-4.txt
/lib/firmware/ath10k/QCA9377
/lib/firmware/ath10k/QCA9377/hw1.0
/lib/firmware/ath10k/QCA9377/hw1.0/board-2.bin
/lib/firmware/ath10k/QCA9377/hw1.0/board.bin
/lib/firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
/lib/firmware/ath10k/QCA9377/hw1.0/notice_ath10k_firmware-5.txt
/lib/firmware/ath10k/QCA988X
/lib/firmware/ath10k/QCA988X/hw2.0
/lib/firmware/ath10k/QCA988X/hw2.0/board.bin
/lib/firmware/ath10k/QCA988X/hw2.0/firmware-4.bin
/lib/firmware/ath10k/QCA988X/hw2.0/firmware-5.bin
/lib/firmware/ath10k/QCA988X/hw2.0/notice_ath10k_firmware-4.txt
/lib/firmware/ath10k/QCA988X/hw2.0/notice_ath10k_firmware-5.txt
/lib/firmware/ath10k/QCA99X0
/lib/firmware/ath10k/QCA99X0/hw2.0
/lib/firmware/ath10k/QCA99X0/hw2.0/board.bin
/lib/firmware/ath10k/QCA99X0/hw2.0/firmware-5.bin
/lib/firmware/ath10k/QCA99X0/hw2.0/notice_ath10k_firmware-5.txt
```

**Comment by MilhouseVH** [comment]
I fear we'll have to include the whole lot to be on the safe side, as the modules include references to pretty much every `ath10k` firmware file, which I suppose is to be expected:
```
$ strings ath10k_core.ko | grep QCA | sort
ath10k/QCA4019/hw1.0
ath10k/QCA6174/hw2.1
ath10k/QCA6174/hw3.0
ath10k/QCA9377/hw1.0
ath10k/QCA9887/hw1.0
ath10k/QCA9888/hw2.0
ath10k/QCA988X/hw2.0
ath10k/QCA9984/hw1.0
ath10k/QCA99X0/hw2.0

$ strings ath10k_pci.ko | grep QCA | sort
firmware=ath10k/QCA6174/hw2.1/board-2.bin
firmware=ath10k/QCA6174/hw2.1/board.bin
firmware=ath10k/QCA6174/hw2.1/firmware-4.bin
firmware=ath10k/QCA6174/hw2.1/firmware-5.bin
firmware=ath10k/QCA6174/hw3.0/board-2.bin
firmware=ath10k/QCA6174/hw3.0/board.bin
firmware=ath10k/QCA6174/hw3.0/firmware-4.bin
firmware=ath10k/QCA6174/hw3.0/firmware-5.bin
firmware=ath10k/QCA6174/hw3.0/firmware-6.bin
firmware=ath10k/QCA9377/hw1.0/board.bin
firmware=ath10k/QCA9377/hw1.0/firmware-5.bin
firmware=ath10k/QCA9887/hw1.0/board-2.bin
firmware=ath10k/QCA9887/hw1.0/board.bin
firmware=ath10k/QCA9887/hw1.0/firmware-5.bin
firmware=ath10k/QCA988X/hw2.0/board-2.bin
firmware=ath10k/QCA988X/hw2.0/board.bin
firmware=ath10k/QCA988X/hw2.0/firmware-2.bin
firmware=ath10k/QCA988X/hw2.0/firmware-3.bin
firmware=ath10k/QCA988X/hw2.0/firmware-4.bin
firmware=ath10k/QCA988X/hw2.0/firmware-5.bin
```
Some of the `core` firmware files might be for USB or SDIO (eg. QCA4019, QCA99X0), but it's hard to know for sure (unless anyone wants to pour over the Atheros source code).

**Comment by MilhouseVH** [comment]
> The only one which could be safely dropped without impacting PCI card support would be QCA4019.

Yeah, which amounts to just 672KB.

As much as I'd like to be selective, it's simply easier at this point to include the whole lot (as a bonus if we want to support USB or SDIO in future, there's less impact/risk). I don't know how popular Atheros SDIO/USB devices are these days - is it worth enabling these too? Or maybe just USB?

Can you also include this commit for the firmware: http://ix.io/FB4

**Comment by devec0** [comment]
Well, yeah, I think the extra 672KB is probably worth it, then :)

SDIO would mostly be found on SoC boards (routers and the like). The USB ath10k devices are fairly rare, there are only two devices I know of in production. It would be no huge deal to include the USB driver, but I have no way to test these devices.

I've updated the commit to include the ath10k firmware directory as well.

**Comment by MilhouseVH** [comment]
OK let's leave this at just PCI for now. And thanks.

This change does introduce a lot of bloat, for potentially niche hardware, so we'll need to consider this a little more closely before deciding on whether to merge.

**Comment by MilhouseVH** [comment]
After some discussion, adding USB seems like a bit of a no-brainer - the `ath10k_usb.ko` module adds only 18KB.

Would you mind adding http://ix.io/FBc and then I think this will get the green light.

**Comment by MilhouseVH** [comment]
Useful page for future reference (but may be incomplete): https://wikidevi.com/wiki/Ath10k

**Comment by devec0** [comment]
Sorry - I should have linked to that, it's the reference I was using for the above review.

I've amended the patches with `CONFIG_ATH10K_PCI=m` to enable USB support as well.

**Comment by devec0** [comment]
I've tested a build based on f8faab1 build now on x86 against the QCA986x/988x card I have in my HTPC, and I am able to connect and stream media without an issue over CIFS.

**Pull request merged**
