### PR TITLE
projects/Amlogic: SBC updates

### PR DESCRIPTION
**Pull request by kszaq**
* update LePotato bootloader patch to support `dd`ing image to eMMC and booting from it
* add support for Khadas VIM SBC
* merge *release* and *mkimage* scripts

### CODE REVIEW

**Comment by adamg88** [comment]
Does your uboot patch allow booting from sd and emmc similar to the one by kwiboo?

**Comment by kszaq** [comment]
@adamg88 Yes, the patch allows you to write LibreELEC.img.gz to eMMC and boot from it like from SD card. With the patch eMMC does not use "Amlogic-style" partition layout embedded in dtb but uses MBR instead. I tested it on both LePotato and Khadas VIM.

**Comment by adamg88** [comment]
@kszaq that's great news.

**Comment by kszaq** [comment]
I added an additional cleanup of merging all `mkimage` and `relase` scripts in Amlogic project. 

Build-tested for all devices and looks fine to me but I may have missed something, I would appreciate a review.

**Comment by adamg88** [comment]
I really like the unification you have done with the scripts, this will certainly reduce maintenance and make things easier.

Run time tested S905, no noticeable issues.

**Comment by kszaq** [comment]
Added support for Khadas VIM2 SBC.

**Pull request merged**
