### PR TITLE
kodi: update to update to 17.0-beta3-7041777

### PR DESCRIPTION
**Pull request by MilhouseVH**
@popcornmix let me know if the RPi Kodi patches need revising above/below the UNSTABLE placeholder, and I'll refresh this PR.

### CODE REVIEW

**Comment by lrusak** [comment]
good to go?

**Comment by MilhouseVH** [comment]
I'd rather wait another day or two before merging, unless you're made keen. :)

There's almost certain to be something missing, or an upstream PR for a show stopper bug that is required...

**Comment by lrusak** [comment]
ok that's fine, I can just pull the patch PR and use that for the time being.

**Comment by chewitt** [comment]
I have confirmation from @popcornmix that the placeholder is good

**Pull request merged**
