### PR TITLE
[le12] vdr-addon: update addon to (1)

### PR DESCRIPTION
**Pull request by heitbaum**
- vdr: update to 2.6.4
- vdr-plugin-epgsearch: update to 2.4.2
- pcre2: fix pcre2-config (used by vdr-plugin-epgsearch)
- vdr-plugin-live: dependancy of pcre2:host is unnecessary
- vdr-plugin-epgfixer: migrate to pcre2

### CODE REVIEW

**Comment by mglae** [comment]
While testing with epgsearch 2.4.2 I had to fix pcre2-config to link the correct target lib on x86_64: 

```
From 1b8b52715bb6bef20a7c161b68cf8a783f9551cc Mon Sep 17 00:00:00 2001
From: mglae <mglmail@arcor.de>
Date: Mon, 20 Feb 2023 15:43:44 +0100
Subject: [PATCH] pcre2: fix pcre2-config (used by vdr-plugin-epgsearch)

---
 packages/devel/pcre2/package.mk | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/packages/devel/pcre2/package.mk b/packages/devel/pcre2/package.mk
index 1b71c0eb55..0bdcf2c4ce 100644
--- a/packages/devel/pcre2/package.mk
+++ b/packages/devel/pcre2/package.mk
@@ -8,7 +8,7 @@ PKG_LICENSE="BSD"
 PKG_SITE="http://www.pcre.org/"
 PKG_URL="https://github.com/PCRE2Project/pcre2/releases/download/pcre2-${PKG_VERSION}/pcre2-${PKG_VERSION}.tar.bz2"
 PKG_DEPENDS_HOST="toolchain:host"
-PKG_DEPENDS_TARGET="toolchain"
+PKG_DEPENDS_TARGET="toolchain pcre2:host"
 PKG_LONGDESC="A set of functions that implement regular expression pattern matching using the same syntax."
 PKG_BUILD_FLAGS="+pic"
 
@@ -36,4 +36,8 @@ post_unpack() {
 
 post_makeinstall_target() {
   safe_remove ${INSTALL}/usr/bin
+
+  cp ${PKG_NAME}-config ${TOOLCHAIN}/bin
+  sed -e "s:\(['= ]\)/usr:\\1${PKG_ORIG_SYSROOT_PREFIX}/usr:g" -i ${TOOLCHAIN}/bin/${PKG_NAME}-config
+  chmod +x ${TOOLCHAIN}/bin/${PKG_NAME}-config
 }
-- 
2.35.3
```

**Comment by heitbaum** [comment]
Yes - that is definitely an issue `make: pcre2-config: No such file or directory`

Shouldn’t it pickup pcre2-config from the sysroot as it is a target build? (note: the pcre2-config in sysroot has the prefix set to /usr, whereas the other -config have the prefix set to …/sysroot/usr - so will need to be fixed regardless.

```
$ find build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin | grep -- -config
build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin/libpng-config
build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin/xml2-config
build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin/freetype-config
build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin/libpng16-config
build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin/pcre2-config
```

**Comment by mglae** [comment]
> Shouldn’t it pickup pcre2-config from the sysroot as it is a target build?

Sysroot binaries are for target architecture and must not be executed from host (even for shell scripts). When being confronted with this the last time I decided to use manual configuration for the few *-config scripts required (most packages are using pkg-config):

```
# git grep PKG_ORIG_SYSROOT_PREFIX packages/
packages/addons/addon-depends/cxxtools/package.mk:32:  sed -e "s:\(['= ]\)/usr:\\1${PKG_ORIG_SYSROOT_PREFIX}/usr:g" -i ${TOOLCHAIN}/bin/${PKG_NAME}-config
packages/devel/ncurses/package.mk:73:  sed -e "s:\(['=\" ]\)/usr:\\1${PKG_ORIG_SYSROOT_PREFIX}/usr:g" -i ${TOOLCHAIN}/bin/ncurses-config
packages/devel/pcre/package.mk:33:  sed -e "s:\(['= ]\)/usr:\\1${PKG_ORIG_SYSROOT_PREFIX}/usr:g" -i ${TOOLCHAIN}/bin/${PKG_NAME}-config
packages/devel/pcre2/package.mk:41:  sed -e "s:\(['= ]\)/usr:\\1${PKG_ORIG_SYSROOT_PREFIX}/usr:g" -i ${TOOLCHAIN}/bin/${PKG_NAME}-config
packages/web/curl/package.mk:82:  sed -e "s:\(['= ]\)/usr:\\1${PKG_ORIG_SYSROOT_PREFIX}/usr:g" -i ${TOOLCHAIN}/bin/${PKG_NAME}-config
```

**Comment by heitbaum** [comment]
Ready for re-review. This migrates both of the epg plugins to PCRE2. It includes the pcre2 build fixes from @mglae. Closing #8301 as this is included in this PR now.

**Comment by CvH** [comment]
@heitbaum `vdr-plugin-epgfixer` git is updated with the patch, so we could drop it

**Comment by heitbaum** [comment]
> @heitbaum `vdr-plugin-epgfixer` git is updated with the patch, so we could drop it

👍 Done

**Review by CvH — APPROVED** [review]

**Pull request merged**
