### PR TITLE
glibc: update to glibc-2.25

### PR DESCRIPTION
**Pull request by MilhouseVH**
Continuing discussion from https://github.com/LibreELEC/LibreELEC.tv/pull/1612#issuecomment-299976237

glibc-2.25 changelog: https://sourceware.org/ml/libc-alpha/2017-02/msg00079.html

The trailing colon added to LD_LIBRARY_PATH is breaking the glibc build. Also llvm will create unusable `llvm-config-host` causing mesa to fail. These issues were first raised in #1086 (thanks @InuSasha).

Question is: should we simply `unset LD_LIBRARY_PATH`, is prefixing with $TOOLCHAIN/lib required at all? More testing needed...

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I'll test this PR with this additional commit: http://sprunge.us/dPVR

If that works OK, then I'll include it in this PR.

**Comment by vpeter4** [comment]
I see you also unset LD_LIBRARY_PATH (I'm still building with). For this to be sure it is ok we need to build all projects from scratch. Maybe something would pop up :)

**Comment by MilhouseVH** [comment]
Yes, I've successfully built RPi/RPi2/Generic with https://github.com/LibreELEC/LibreELEC.tv/pull/1616/commits/358aac5f44f0edf0199195ae9f6c43b16c9beba6, so that's working. Now I'm going to clean build all projects with https://github.com/LibreELEC/LibreELEC.tv/pull/1616/commits/5b817827505e1cf6eaf2604955f1f92f5a654a42 to see if we need LD_LIBRARY_PATH at all. Should know in about 9 hours...

**Comment by InuSasha** [comment]
the Addons should built, too.
Actual, i make experiments with gcc7 & glibc2.15. It looks like, same addon dependencies need updates, too.
But i can not remeber in detail, if it depend on gcc or glibc update (i am on work).
https://github.com/InuSasha/LibreELEC.tv/tree/feature/gcc7
Status: Generic - LE build; some addon fixed, but not all.

**Comment by MilhouseVH** [comment]
All the projects (RPi, RPi2, Generic, imx6, Odroid_C2, WeTek_*) have built for me with LE master + #1612 + #1616, so dropping/unsetting "LD_LIBRARY_PATH" doesn't seem to be a problem.

I've run-time tested RPi/RPi2/Generic, and no obvious issues.

I also rebuilt the same addons I tested in #1612, and no new issues:

Generic::
```
vdr-addon, tvheadend42, moonlight, screensaver.shadertoy, visualization.projectm, visualization.shadertoy, visualization.spectrum, visualization.waveform
```

RPi/RPi2:
```
vdr-addon, tvheadend42, screensaver.shadertoy, visualization.shadertoy, visualization.spectrum, visualization.waveform
```

I've updated the libnfs patch using the upstream fix https://github.com/sahlberg/libnfs/commit/5b28ab5d535e0252c05640eef6e280581278dc36

@InuSasha: Hopefully with these updates (PR1612+PR1616) the jump to gcc-7.1 should be less painful, though maybe wait for gcc-7.2?

There's a gcc-6.3 bump available which might be another option.

If anyone wants to update gcc in a separate PR, feel free!

**Comment by lrusak** [comment]
PS. all add-ons and binary add-ons should be bumped using the `PKG_REV` when merging this.

**Comment by vpeter4** [comment]
Build was fine here too. Run-time test will follow.
Seems changes are fine.

**Comment by MilhouseVH** [comment]
> PS. all add-ons and binary add-ons should be bumped using the PKG_REV when merging this.

Sounds like a script to do that would come in handy... Is it just a matter of iterating over addons and `PKG_REV=$PKG_REV+1`?

**Comment by lrusak** [comment]
@MilhouseVH `tools/repo-tool` will do this already for the regular add-ons, it should be adapted to include the binary add-ons also

`./tools/repo-tool -ru`

**Comment by MilhouseVH** [comment]
Ok will take a look at add a commit to this PR

**Comment by MilhouseVH** [comment]
`repo-tool` updated to support `official`, `binary`, `retroplayer` and `all` option when bumping `PKG_REV`.

`PKG_REV` bumped for `all` addons (inc. retroplayer).

**Comment by MilhouseVH** [comment]
I've removed `Don't Merge` and `Wip` labels, as this seems to be working fine now. I'll include this PR in the next testbuild.

**Comment by MilhouseVH** [comment]
In relation to gcc-7.1, message from @stefansaraev (seo) on #irc:
```
[10-May-2017 19:51:55] <seo> ping Milhouse lrusak if you plan bumping to gcc 7.1. amlogic kernel is broken for me. ./drivers/amlogic/mmc/aml_sd_emmc.c booms. didn't have time to investigate further
[10-May-2017 19:52:24] <seo> cc @codesnake @peak3d ;)
[10-May-2017 19:54:03] <seo> Unhandled fault: alignment fault
```

**Pull request merged**
