### PR TITLE
distro: remove espeak

### PR DESCRIPTION
**Pull request by CvH**
There is no know working use-case of espeak at kodi. Also Kodi git doesn't show any sign of espeak at all.
Just disabling it for now, we can remove later if nobody complains.

### CODE REVIEW

**Comment by HiassofT** [comment]
I think you now could drop `ESPEAK_SUPPORT="no"` from the ARM options as well https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/ARM/options#L36-L37

**Comment by HiassofT** [comment]
As commented on slack it should be fine to remove espeak completely, I couldn't find any packages using it either.

**Comment by CvH** [comment]
added commits to purge it

**Review by HiassofT — APPROVED** [review]

**Comment by vbprofi** [comment]
Hi there,
I wanted to ask if the Kodi Screenreader TTS is running with Libreelec 10 on a Raspberry Pi 3+ now?

Link to workaround to run Kodi Screenreader TTS in Kodi 19.x:
`https://forum.kodi.tv/showthread.php?tid=196757&pid=3077471#`

would actually have to run if espeak was implemented again, right?
Last time I tested with the RPI2 image from 19 February. That didn't work with the February 19 image. Can anyone help?

**Comment by heitbaum** [comment]
> Hi there, I wanted to ask if the Kodi Screenreader TTS is running with Libreelec 10 on a Raspberry Pi 3+ now?
> 
> Link to workaround to run Kodi Screenreader TTS in Kodi 19.x: `https://forum.kodi.tv/showthread.php?tid=196757&pid=3077471#`
> 
> would actually have to run if espeak was implemented again, right? Last time I tested with the RPI2 image from 19 February. That didn't work with the February 19 image. Can anyone help?

Have a look at #6150 and #6151 - further work is required.

**Pull request merged**
