### PR TITLE
projects/Amlogic: don't build wetek dvb driver

### PR DESCRIPTION
**Pull request by afl1**
There is no device with wetek dvb tuner in Amlogic  project.

### CODE REVIEW

**Comment by Raybuntu** [comment]
@afl1 WP2 will be moved to Amlogic. As I understand S905 wants to use Wetekdvb driver as well so I'd say let's keep it.

**Comment by afl1** [comment]
You can select wetekdvd as I did in our community build:
[https://github.com/LibreELEC-AML/LibreELEC.tv/blob/1708d2708f4a4718e0b9e21f442893f9d88c556f/packages/linux/package.mk#L142]

**Comment by Raybuntu** [comment]
@afl1 I'd like to avoid that. That module is only 104K in size. It's not worth the effort imho.

**Comment by afl1** [comment]
With this approarch we can build all linux drivers for all Amlogic devices and left ADDITIONAL_DRIVERS in global Amlogic option file.

**Pull request closed without merging**
