### PR TITLE
nano: cleanup

### PR DESCRIPTION
**Pull request by InuSasha**

### CODE REVIEW

**Comment by stefansaraev** [comment]
zlib is only needed when built with --enable-magic

it should be safe to remove   ```export LIBS="$LIBS -lz"``` instead

**Comment by stefansaraev** [comment]
unrelated to this PR, but not stripping -Wl,--as-needed from LDFLAGS should also be safe. pre_configure_target() can go.

**Comment by InuSasha** [comment]
Ok, this is a solution too.
Make a clean build without the LIBS export of nano.

**Comment by stefansaraev** [comment]
no need for clean build. just remove LIBS=, rebuild nano and check library dependencies:

```build.*/toolchain/bin/*-readelf -d build.*/nano-*/.build_*/src/nano```

sorta, if libz.so is not listed as NEEDED. you are good.

**Comment by InuSasha** [comment]
switched to @stefansaraev solution.
build was fine, without zlib

**Comment by stefansaraev** [comment]
as you wish, you can add it, but it would need build testing for all supported project/archs

**Comment by InuSasha** [comment]
will add it, after build test

**Comment by InuSasha** [comment]
nano builds fine, in all project without "-Wl,-as-needed"

**Pull request merged**
