### PR TITLE
sundtek-mediatv: support new driver version ...

### PR DESCRIPTION
**Pull request by vpeter4**
(different output from mediaclient)

### CODE REVIEW

**Comment by vpeter4** [comment]
Thanks @Raybuntu.
The main issue was wrong DVB standard shown in settings (DVB-C tuner shows up as DVB-S/S2). Not sure if tuner actually worked or not.

**Comment by CvH** [comment]
Can't test it either, no HW available.

**Comment by Raybuntu** [comment]
I will test it with my stick later and just to double check.

**Comment by Raybuntu** [comment]
Thanks @vpeter4. I've tested and it's working good.

**Comment by vpeter4** [comment]
Good.

**Pull request merged**
