### PR TITLE
Odroid c2 updates

### PR DESCRIPTION
**Pull request by lrusak**
This updates the kernel, u-boot, and opengl-meson versions

I've also updated the kodi patch so that it compiles, however there are playback issues.

I also have to adjust users boot.ini file (which I don't like doing) because it requires some new parameters in order to work properly.

@LongChair please give this a go.

### CODE REVIEW

**Comment by LongChair** [comment]
@lrusak : if you're having playback perf issues, you might wanna kick the kernel up a bit again.

this commit https://github.com/hardkernel/linux/commit/01d61cd6e63570f4e5356a7c7a9c0ad454583194

solved some fps output limitation which was broken on C2.
Not sure if that is the source reason, but it's worther a try to grab the latest master.

**Comment by LongChair** [comment]
@lrusak : using those commits and updating with tarball didn't see to update my boot.ini.

Without the boot.ini patch it will crawl. gonna try with a full reflash

**Comment by LongChair** [comment]
Full flash didn't get me the patched boot.ini either ...

**Comment by lrusak** [comment]
can you pastebin your boot.ini please @LongChair

**Comment by LongChair** [comment]
sure, there you go : http://pastebin.com/25tmPBw5

**Comment by lrusak** [comment]
updated, @LongChair please test

**Comment by LongChair** [comment]
Boot now seems Ok :)

**Pull request merged**
