### PR TITLE
LE12 addon bump

### PR DESCRIPTION
**Pull request by CvH**
bump to final

### CODE REVIEW

**Comment by HiassofT** [comment]
I've added a temporary merge blocked tag, the changes look fine but we should merge this when we build the final LE12 release

**Comment by CvH** [comment]
rebased

**Review by HiassofT — APPROVED** [review]

**Comment by vpeter4** [comment]
Why are some addons bumped but others reset?

**Comment by HiassofT** [comment]
Kodi binary addons use the original kodi addon version with PKG_REV appended as the full version number, therefore it's necessary to bump PKG_REV to get new addons rolled out to users.

Our addons however use ADDON_VERSION with PKG_REV appended and as ADDON_VERSION was bumped PKG_REV can be reset.

If some addon failed to follow above rules and the full version number didn't increase (either via PKG_REV or ADDON_VERSION) it would be a bug - please report if you spotted such a case

**Pull request merged**
