### PR TITLE
[LE10] apache-ant: bump package to 1.10.11

### PR DESCRIPTION
**Pull request by Portisch**

### CODE REVIEW

**Comment by heitbaum** [comment]
Hi @Portisch - do we need Apache-ant bumped in LE10?

**Comment by Portisch** [comment]
The bump is needed as the old source download isn't available anymore.

**Comment by chewitt** [comment]
@Portisch I assume this is tested? .. asking because I have fuzzy memory of JRE-Zule being fussy about dependencies?

**Comment by heitbaum** [comment]
> @Portisch I assume this is tested? .. asking because I have fuzzy memory of JRE-Zule being fussy about dependencies?

I had tested Apache-ant 1.10.10 and 1.10.11 it as part of #5069 - but parked it to come back to.

**Comment by Portisch** [comment]
> @Portisch I assume this is tested? .. asking because I have fuzzy memory of JRE-Zule being fussy about dependencies?

As the addon jre.zulu remain untouched it compiles fine and it should work without issues.
We will check it again later/tomorrow but there is no surprise expected.

There is no other opportunity as the old source https://downloads.apache.org/ant/binaries/apache-ant-1.10.9-bin.tar.gz is not available anymore and the build of the addon fails because of the missing dependency.

**Comment by chewitt** [comment]
In theory we should have all packages for a release cached on the sources server for GPL purposes, but we probably need to ensure that script is running (or being run). It's no drama to bump though, as long as the package doesn't cause a problem.

**Comment by vpeter4** [comment]
This apache-ant bump is fine.
But the stock jre.zulu addon doesn't work because (I think) it needs one libbluray patch which I added only to my own branch it seems. At least this is true for arm (coreelec). Will try to check this sometime in the future.

**Review by CvH — APPROVED** [review]

**Pull request merged**
