### PR TITLE
fixed custom audio device configuration compatibility with previous settings (and launchability of the Chrome browser)

### PR DESCRIPTION
**Pull request by pohutukawa**
* improved exception reporting to the logger
* improved subprocess handling to be more pythonic
* fixed compatibility with configuration for custom audio devices (ALSA) to be compatible with previous custom settings
* fixed launchability of Chrome in presence of custom audio device config (that were working previously)
* slight simplifications for more pythonic code in some functions

### CODE REVIEW

**Comment by chewitt** [comment]
@pohutukawa I can't comment directly on the Python (not my skillset) but for the PR in general, two changes are needed:

a) Please follow house style for commit messages, e.g. `chrome: improvements to the python launch script` so we can read the git log later and know which pacage was touched and what was changed.

b) You also need to bump PKG_REV in `package.mk` else when we rebuild and push the updated package, nobody will see the revised versoin as an update.

c) If/once accempted, a backport to `libreelec-10.0` branch would be appreciated.

Thanks.

**Comment by pohutukawa** [comment]
@chewitt Thanks for responding to this, especially in this constructive fashion.

Apologies for not following the proper protocol here, but I've never contributed to LibreELEC or Kodi before (even though it's been for a while on my list to try myself on an add-on).

Unfortunately some of the things are a bit "out of my wheel house" as I've never done them before. I can certainly change the commit message (I was actually wondering how that stuff was done as it's all within a giant "god repo" ... :-) ). As for the `PKG_REV` ... I'm not sure how versioning is done here, but I suppose it'll be bumped to `112` in this case?. Would be lovely if you could confirm.

Now for the difficult bit: How would you like the backport to the `libreelec-10.0` branch be done? Another PR?

Cheers!

**Comment by chewitt** [comment]
Just increment `PKG_REV="112"` and (one more thing) add some description to the `changelog.txt` file as this text is visible in the Kodi GUI. Once the changes are accepted here, checkout a new branch from `libreelec-10.0`, make the same changes, push them to you fork, and then send a PR against the `libreelec-10.0` branch (same process, different branch).

**Comment by pohutukawa** [comment]
Seems like in making the changes on the PR (I wanted to avoid commit log inflation madness) the PR got a new number:
#5983

Done the bits as requested.

**Comment by chewitt** [comment]
```
nano packages/addons/browser/chrome/package.mk
git add packages/addons/browser/chrome/package.mk
git commit --amend
git push -f origin master
```

^ Make changes to the `package.mk` then ammend the previous commit by adding the changes - also an opprtunity to reword the commit message. Then force push the changes to your origin branch which is the source of the PR, so the PR will be updated automatically (no need to create a new PR to pick-up the changes). 

The other obvious "not necessarily a mistake, but good habit to learn" is working in a topic branch not master branch. We have some git pointers for LE here: https://wiki.libreelec.tv/development-1/git-tutorial

NB: Not criticism, everyone is always learning git :)

**Comment by pohutukawa** [comment]
Thanks for the pointers. Will certainly have a look at them. The time while I was developing a lot of software myself has been using SVN (and CVS before), so my Git skills are more rudimentary (I use it now, but not in a very sophisticated way). And I fully agree with topic branches, however for this "odd time" on my side (possibly the only time?) to contribute I didn't bother. And too true with the final note: Almost nobody "knows it all" on Git.

Anyway, the old PR is dead (can't seem to revive it, either), so the new PR is in #5983. Sorry for the inconvenience ... :-(

**Comment by mglae** [comment]
Superseded by #5983

**Pull request closed without merging**
