### PR TITLE
projects/imx6: enable cursor in serial console service

### PR DESCRIPTION
**Pull request by vpeter4**
hidden with PR #44

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Whoops.

**Comment by vpeter4** [comment]
Maybe same should be done for RPi too.

**Comment by MilhouseVH** [comment]
Is this the textmode console? Never actually tested that... two ticks...

**Comment by MilhouseVH** [comment]
Hmm yeah... bugger.

**Comment by vpeter4** [comment]
It is serial console. No idea if anyone is actually using this on RPi.
But imx6 devices like cuboxi and udoo has special micro usb connector with build-in serial to usb adapter.

**Pull request merged**
