### PR TITLE
libdvbcsa: AArch64 support

### PR DESCRIPTION
**Pull request by glenvt18**
This follows #1053.

### CODE REVIEW

**Comment by glenvt18** [comment]
Update, version change. Fixes glenvt18/libdvbcsa#1. Can anyone build and test it on RPi2/3 with the latest LibreELEC toolchain? Testing instructions: https://github.com/LibreELEC/LibreELEC.tv/pull/1053#issuecomment-266524248

**Comment by MilhouseVH** [comment]
This builds fine on RPi, RPi2 and Generic.

However performance is slightly worse on RPi3 - down from ~135MB/s to ~131MB/s:
new: http://pastebin.com/raw/qREwHNCB
old: http://pastebin.com/raw/gEMa3skW

**Comment by glenvt18** [comment]
@MilhouseVH I see
```
libdvbcsa 1613dd4 (post-#1058) on RPi3 (kodi not running):
```
in your paste, but the right hash is glenvt18/libdvbcsa@7360578 (like in this commit).

**Comment by MilhouseVH** [comment]
Sorry fat fingers - I was simultaneously looking at this PR and also #1053, and I copied the rev from #1053. The "post-#1058" rev should have been 7360578 (and in fact is, when I look at the package.mk in my repo).

**Comment by glenvt18** [comment]
If so, it's OK. Small performance drop (about 3%) is expected on ARM. I sacrificed some performance in favor of safety and maintenance, but I have some ideas how to get it back:) I didn't notice any performance drop on x86 and AArch64 though.

Also tests on 32 bit Amlogic showed that the current LibreELEC compiler (6.2) produces code that is about 10% slower on ARM than the one generated by Linaro 5.4. I've also tried Linaro 6.2.1. It's only a little bit better and it doesn't generate ldm instructions which lead to bus errors. But, in practice, 132 Mbit/s you got is not bad at all.

**Comment by Raybuntu** [comment]
I've tested this with Odroid C2 with aarch64 and arm. Works for me.

**Comment by lrusak** [comment]
@glenvt18 are you happy with this? do you want to update the git hash?

**Comment by glenvt18** [comment]
@lrusak Here you go. Just to point to my master branch. Though the changes are purely cosmetic.

**Pull request merged**
