### PR TITLE
config: ADD CONFIG_FB_UDL module (USB displaylink)

### PR DESCRIPTION
**Pull request by nahun**
config: ADD CONFIG_FB_UDL module (USB displaylink) ([61afb7c7](https://github.com/raspberrypi/linux/commit/61afb7c7c8242b1eb0dbfbdf51229c587cf5adea))

### CODE REVIEW

**Comment by lrusak** [comment]
Any kernel changes should be done for all projects if possible

**Comment by nahun** [comment]
Added change to add to all projects.

I'll understand if this change isn't wanted, but looks like it has been [tested before with LibreELEC](http://forum.kodi.tv/showthread.php?tid=250817&pid=2189808&highlight=CONFIG_FB_UDL#pid2189808). Thanks!

**Comment by MilhouseVH** [comment]
> but looks like it has been tested before with LibreELEC

That simply means it was added to the [default RPi config](https://github.com/raspberrypi/linux/blob/rpi-4.9.y/arch/arm/configs/bcm2709_defconfig#L829) which isn't used by OpenELEC/LibreELEC, so never actually tested (but should be safe).

**Comment by lrusak** [comment]
I'm fine with this

**Comment by piotrasd** [comment]
for generic please enable albo DRM_UDL=m ;)

**Comment by piotrasd** [comment]
that change wthout DRM for UDL dont will works on Generic, im tested once DisplayLink - USB3.0 to HDMI cable/adapter and worked with  DRM_UDL=m/y

**Pull request merged**
