### PR TITLE
kodi-binary-addons: update to latest versions

### PR DESCRIPTION
**Pull request by heitbaum**
- visualization.projectm: update 20.2.0-Nexus to 21.0.1-Omega
- pvr.plutotv: update 21.1.1-Omega to 21.2.0-Omega

### CODE REVIEW

**Review by chewitt — APPROVED** [review]

**Comment by vpeter4** [comment]
Why was PKG_REV set back to 1 and not 0 for pvr.plutotv ?

**Comment by CvH** [comment]
yea thats wrong (likewise commit taken from LE12), buts not really a problem functional wise

**Comment by heitbaum** [comment]
These are the code lines that do these changes:

https://github.com/LibreELEC/LibreELEC.tv/blob/cdf59619956a1df5f95474b5690572c8c4169200/tools/mkpkg/update_binary-addons#L156

https://github.com/LibreELEC/LibreELEC.tv/blob/cdf59619956a1df5f95474b5690572c8c4169200/tools/mkpkg/update_common_functions#L168

**Comment by HiassofT** [comment]
> https://github.com/LibreELEC/LibreELEC.tv/blob/cdf59619956a1df5f95474b5690572c8c4169200/tools/mkpkg/update_common_functions#L168

Feel free to change the rev to 0 here if you prefer - the minimum starting number is not really relevant, we could use 42, too :-)

**Pull request merged**
