### PR TITLE
linux: update to linux-4.11.0

### PR DESCRIPTION
**Pull request by MilhouseVH**
Currently based on top of #1440.

The following patches have been (temporarily?) dropped as they no longer apply cleanly (edit: both already merged):
- ~~`projects/Generic/patches/linux/linux-030-LPE-audio-hdmi-BYT-CHT.patch` - not sure if this is required any more, @piotrasd?~~
- ~~`packages/linux/patches/default/linux-063-fix-rc-raw-decoder-loading.patch` - ping @HiassofT~~

Most of the WiFi drivers need a 4.11 fix, however the second commit on 52e3f72 I'm not really sure about - anyone got any advice (or just confirmation it's the correct fix)? The net device structure no longer includes `last_rx` in 4.11-rc2, so I've simply removed it.

`media_build` is updated, but not currently fully compatible with 4.11-rc2.

`xf86-video-nvidia` (375.39) does not currently build with 4.11-rc2.

`xf86-video-nvidia-legacy` (340.102) does not currently build with 4.11-rc2.

### CODE REVIEW

**Comment by piotrasd** [comment]
is new patch and some parts already merged
"projects/Generic/patches/linux/linux-030-LPE-audio-hdmi-BYT-CHT.patch"

**Comment by HiassofT** [comment]
linux-063-fix-rc-raw-decoder-loading.patch is no longer needed, it has been added in 4.11-rc2 https://github.com/torvalds/linux/commit/413808685dd7c9b54bbc5af79da2eaddd0fc3cb2

@CvH please check if it's in the media_build tree as well

**Comment by CvH** [comment]
@HiassofT not yet atm https://github.com/crazycat69/linux_media/commit/6275d078d972591b9e449c7bad0fa24ea7519380 , because even the official media_tree is currently behind the official linux tree O_o

**Comment by CGarces** [comment]
Changes for RTL8192EU send and accepted, please update to https://github.com/Mange/rtl8192eu-linux-driver/commit/dcd71fa873ecc8277924c205edb1a1717687813f

**Comment by MilhouseVH** [comment]
@CGarces thanks, dropped RTL8192EU patch and bumped version.

I've also submitted a PR for RTL8812AU so hopefully we can drop that patch before this is merged.

**Comment by MilhouseVH** [comment]
@piotrasd does anything need to be added for Baytrail/Cherrytrail support? The current audio patch has been dropped entirely, so if there's a new one needed can you provide a link? Thanks.

**Comment by piotrasd** [comment]
only this PR https://github.com/LibreELEC/LibreELEC.tv/pull/1442

**Comment by MilhouseVH** [comment]
Added `xf86-video-nvidia` patch to build without `nvidia-drm` kernel module which avoids the license issue.

From: http://rglinuxtech.com/?p=1970

I've left in the udev.d sym link commit, as that is valid while we support building `xf86-video-nvidia-legacy` without `xf86-video-nvidia`, although there's undoubtedly a better/cleaner solution (however this works for now).

**Comment by lrusak** [comment]
@MilhouseVH do you want to squash all the linux bumps?

**Comment by MilhouseVH** [comment]
I think it useful to keep the full history of the PR considering it's a fairly long running change that is tested at different stages while it evolves (ie. we have weekly releases on Kodi forum of each rc) and this might make identifying regressions that bit easier should it be necessary. I've redated and force pushed.

**Pull request merged**
