### PR TITLE
kodi: rework aml video scaling patch

### PR DESCRIPTION
**Pull request by Kwiboo**
This PR should fix a video scaling issue when a 2160p video is played and a lower screen resolution is used.

Video resolution is now used when calculating video scaling and scaling is recalculated when render manager changes video resolution.

### CODE REVIEW

**Comment by stefansaraev** [comment]
ping @wrxtasy @codesnake

**Comment by codesnake** [comment]
I think this change is not needed at all (inherited from previous patch): https://github.com/Kwiboo/LibreELEC.tv/blob/aml-video-axis/packages/mediacenter/kodi/patches/aarch64/kodi-0006-aml-Scale-video-axis-correctly-when-1080p-to-2160p-switching.patch#L59-L67

**Comment by chewitt** [comment]
please figure out whats in/out today so we can pull things together for 7.90.008, thanks :)

**Comment by Kwiboo** [comment]
@codesnake you are correct, the DCI 4K (4096x2160) sample I tested played without artifacts when my TV switched to a 4096x2160 mode instead of a 3840x2160 mode, will update PR to remove that part

**Comment by Kwiboo** [comment]
Updated to also remove the _Limit 4096x2160p (smpte24hz) resolution_ parts as it is no longer needed

**Pull request merged**
