### PR TITLE
linux: Update to 4.8.1

### PR DESCRIPTION
**Pull request by MilhouseVH**
Currently based on rc7, but there's going to be an rc8.

I've released rc6 and rc7 builds based on these patches with good feedback - 4.8-rc6/7 fixes at least one resume bug present in 4.7.x.

@piotrasd: I've had to drop the `linux-030-BYT-CHT-SOC-audio-support.patch`, is there a version for 4.8-rcX? Can add once 4.8.0 is released.

@mglae: Unfortunately the ddbridge patch isn't compiling against 4.8-rcX. Not entirely sure why, could you take a look? It fails with [these errors](http://sprunge.us/BWYE). Same errors with gcc-5.4 and gcc-6.2.

`linux-231-Terratec-Cinergy-S2-Rev.3.patch` is now included in mainline.

A few lirc hacks are necessary:

1) I've had to use the development version of lirc due to lirc-related 4.8 kernel changes ([changelog](https://sourceforge.net/p/lirc/git/ci/31fcc8aa39f62c5cbf0e4af19d253764c905e4d4/)). Since the lirc project is hosted on SourceForge there's no easy way to pull the master version (I can pull it as a zip, but not a tar) so I've just packaged it and stuck it on the mirror for now.

2) There's a race condition while building this version of lirc - it tries to use the generated `paths.h` file before it's generated. Since the content of this file is (for us) static, creating it before the build avoids the build failure. Other solutions welcome...

3) There's a problem when referencing `remotes.list` and `irdb-get` - I'm assuming it's an bug, have patched it for now.

I can report 2 & 3 upstream if anyone else is able to confirm them as lirc errors (and not the result of something weird we do in LibreELEC).

### CODE REVIEW

**Comment by piotrasd** [comment]
> @piotrasd: I've had to drop the linux-030-BYT-CHT-SOC-audio-support.patch, is there a version for 4.8-rcX? Can add once 4.8.0 is released.

Not yet, usual Pierre making new patch after official release kernel

**Comment by mglae** [comment]
> @mglae: Unfortunately the ddbridge patch isn't compiling against 4.8-rcX. Not entirely sure why, could you take a look? It fails with these errors. Same errors with gcc-5.4 and gcc-6.2.

I always expecting this on new kernel versions. Fortunately an update is available:
```
wget -q -O - 'https://github.com/herrnst/dddvb-linux-kernel/raw/master-ddbridge-features/Makefile'|head -n 4
VERSION = 4
PATCHLEVEL = 8
SUBLEVEL = 0
EXTRAVERSION = -rc7
```
I did not build it yet but if you like to give it a try:
```
wget -O linux-221-ddbridge-features.patch 'https://github.com/herrnst/dddvb-linux-kernel/compare/master...master-ddbridge-features.diff'
```

**Comment by MilhouseVH** [comment]
@mglae: Many thanks, have pushed the update.

**Comment by MilhouseVH** [comment]
Rebased and updated to 4.8-rc8.

**Comment by MilhouseVH** [comment]
Updated to use lirc 0.9.4 patched with [4.8 backport](https://sourceforge.net/p/lirc/git/ci/31fcc8aa39f62c5cbf0e4af19d253764c905e4d4/), plus build hack.

**Comment by escalade** [comment]
Missing config symbol NET_CLS_MATCHALL.

**Comment by MilhouseVH** [comment]
Missing in what sense, are you being prompted for this? These are all defaults from `make oldconfig` and for whatever reason this option isn't being included... Will double check later this evening but if you could provide a little more information (which project, what you are building - just this PR or others etc.)

**Comment by escalade** [comment]
Disregard that, it's probably because I added the fq_codel PR. I'm on generic btw, and there seems to be an issue with the RTL8192EU patch:

`APPLY PATCH (common)   /root/LibreELEC.tv/packages/linux-drivers/RTL8192EU/patches/RTL8192EU-kernel-4.8.patch
patching file os_dep/linux/ioctl_cfg80211.c
Hunk #1 FAILED at 1891 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file os_dep/linux/ioctl_cfg80211.c.rej`

**Comment by MilhouseVH** [comment]
Thanks, I'll double check the patch later this evening - pretty sure it applied cleanly though (I built this PR yesterday, with no issues) - do you have any other RTL8192EU patches in your build?

**Comment by escalade** [comment]
No, I do not.

**Comment by MilhouseVH** [comment]
@escalade regarding the RTL8192EU patch, have you stripped the carriage returns off the patch when downloading it? The RTL8192EU kernel 4.8 patch needs (and in this PR, has) carriage returns - without the carriage returns you will get the `different line endings` error you posted when applying the patch.

I've added the latest 4.8.y RPi patches to this PR now.

**Comment by escalade** [comment]
Yeah, that was indeed the issue. I applied the PR using git am and it strips the CR's by default.

**Comment by MilhouseVH** [comment]
Rebased on 4.8.0.

RPi issues still to resolve.

**Comment by MilhouseVH** [comment]
Updated with a couple of i915 patches I've been using.

**Comment by MilhouseVH** [comment]
Dropped 4K patch, causes no sound on some amps.

**Comment by MilhouseVH** [comment]
RPi patches updated with CPUFreq fix - when `force_turbo=1` the 4.8 kernel drops the cpufreq interface as it's no longer required (min/max frequencies being the same). @popcornmix has added a commit that restores the original behaviour.

Added an i915 fix for random GPU hangs from @piotrasd, https://bugs.freedesktop.org/show_bug.cgi?id=97814

**Comment by MilhouseVH** [comment]
Updated to 4.8.1.

**Comment by MilhouseVH** [comment]
Updated with `linux-030-BYT-CHT-SOC-audio-support.patch`.

Suggest leaving this open for a couple of days to get some testing in.

**Comment by MilhouseVH** [comment]
Updated with latest RPi kernel patches, and associated firmware update (RPi kernel is dependent on this firmware).

**Comment by MilhouseVH** [comment]
@piotrasd has confirmed the Cherry Trail/Bay Trail audio support is working.

Merge away...

**Pull request merged**
