### PR TITLE
mono: update to 4.2.1.102

### PR DESCRIPTION
**Pull request by awiouy**
Work in progress:
Latest stable mono release builds static for arm and x86_64.
Not worth pushing without aarch64.
If someone knows where I could find the patches required to build mono 4 for aarch64, please let me know ;)

### CODE REVIEW

**Comment by escalade** [comment]
Breaks sonarr for me:

{{{
Aug 17 16:34:37 NUC mono[1910]: sgen is not supported when using --with-tls=pthread.
Aug 17 16:34:37 NUC mono[1910]: Stacktrace:
Aug 17 16:34:37 NUC mono[1910]: Native stacktrace:
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono() [0x592811]
Aug 17 16:34:37 NUC mono[1910]:         /lib/libpthread.so.0(+0x11030) [0x7f190b66a030]
Aug 17 16:34:37 NUC mono[1910]:         /lib/libc.so.6(gsignal+0x104) [0x7f190b0de024]
Aug 17 16:34:37 NUC mono[1910]:         /lib/libc.so.6(abort+0x16a) [0x7f190b0df45a]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono() [0x614019]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono() [0x6155ef]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono() [0x615e47]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono() [0x4861c0]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono() [0x42a6ff]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono() [0x45d786]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono() [0x571f2f]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono() [0x6372cc]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono() [0x638439]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono(mono_runtime_invoke+0x5a) [0x4fc67a]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono(mono_runtime_exec_main+0xa3) [0x5029c3]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono(mono_jit_exec+0x7f) [0x60a4cf]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono(mono_main+0x12a5) [0x60be55]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono() [0x42d7c0]
Aug 17 16:34:37 NUC mono[1910]:         /lib/libc.so.6(__libc_start_main+0xf0) [0x7f190b0cb240]
Aug 17 16:34:37 NUC mono[1910]:         /usr/bin/mono(_start+0x2a) [0x42db6a]
}}}

Tried recompiling without --with-tls=pthread, but then I get errors about undefined references.

**Comment by awiouy** [comment]
Thank you for the feedback.
I have no x86_64 to test with.
Could you try with --with-tls=__thread for x86_64?
(for the record, --with-tls=pthread builds and runs for arm)

**Comment by escalade** [comment]
That's the default, it wouldn't compile.
```

  CCLD     mono-sgen
sgen-alloc.c:551: error: undefined reference to 'tlab_temp_end'
mini-runtime.c:773: error: undefined reference to 'mono_lmf'
mini-runtime.c:763: error: undefined reference to 'mono_jit_tls'
mini-runtime.c:763: error: undefined reference to 'mono_jit_tls'
mini-runtime.c:784: error: undefined reference to 'mono_lmf_addr'
threads.c:258: error: undefined reference to 'tls_current_object'
domain.c:159: error: undefined reference to 'tls_appdomain'
mini-runtime.c:773: error: undefined reference to 'mono_lmf'
collect2: error: ld returned 1 exit status
Makefile:1398: recipe for target 'mono-sgen' failed

```

**Comment by escalade** [comment]
Just to be clear, it compiles and runs with pthread. It seems to be only sgen that doesn't work, and apparently it's needed by Sonarr and I would assume other things as well.

**Comment by awiouy** [comment]
sgen is the garbage collector :D
it therefore appears mandatory, especially since boehm gc build is disabled.
according to mono bug tickets, mono cross compilation is fubar since 4.0.5.1. Hopefully it will be fixed with 4.6

**Comment by escalade** [comment]
Seems LTO is the problem, added strip_lto before running configure and it compiles and runs fine with __thread (any reason why you chose pthread over the default?)

**Comment by awiouy** [comment]
Thank you for this precious information!
Building mono:target for failed with __thread.
I will try to use strip_lto for arm, too, to see if it builds and runs.
Did you simply add strip_lto before ./configure in configure_target()?

**Comment by escalade** [comment]
Yes, it has to be run somewhere before running configure as it strips away -flto from the compiler and linker flags. I put it inside configure_target(), but it would probably be cleaner and in line with other packages to add a pre_configure_target() step, as that's where it's normally put.

**Comment by awiouy** [comment]
Amazing: latest stable mono builds and run static with __thread on RPi2, too!
I would never have thought of strip_lto: thank you @escalade

**Comment by awiouy** [comment]
Great news!
Mono builds static for all architectures, thanks to patches from Debian.
I have built it for Generic, Odroid_C2 and RPi2.
I am using this to run Emby, WebGrab+Plus and other Mono applications on RPi2

Please do not merge, yet.
I first want to fix Emby to refer to libsqlite3.so.0, so we do not need to ship libsqlite3.so with this addon

**Comment by awiouy** [comment]
I am done ;)

**Comment by awiouy** [comment]
emby also builds for aarch64
ready to merge

**Pull request merged**
