### PR TITLE
[le11] fix wayland builds

### PR DESCRIPTION
**Pull request by SupervisedThinking**
- updated the dependencies
- fixed issues introduced by parallel package build
- fixed Kodi build

screenshot00000

### CODE REVIEW

**Comment by lrusak** [comment]
Can you try this patch instead? https://github.com/lrusak/xbmc/commit/b91a76aea33b60be19d3b66f9a49438887576ce6

**Comment by SupervisedThinking** [comment]
I'll give it a try tomorrow, but I guess should find if it doesn't report an error now 👍🏻

**Comment by SupervisedThinking** [comment]
Build & run tested - also tested if the gbm build is still fine.

screenshot00002

@heitbaum fyi you need to export the `TARGET_CFLAGS` otherwhise the package will build but probably won't run on systems without the same cpu feature set as your build host

https://github.com/LibreELEC/LibreELEC.tv/pull/5864/commits/c4ef45d3adf2c0362f8577c709c34ff8177278e6#diff-96ce4d9853ce2720de5ecc119059b67850a32a69754f2977dcf42dbce6ff21a3R36

**Comment by CvH** [comment]
@lrusak so https://github.com/lrusak/xbmc/commit/b91a76aea33b60be19d3b66f9a49438887576ce6 works, I guess it gets pred ?

**Comment by SupervisedThinking** [comment]
@CvH I've switched the wayland toolchain to meson since autotools will be dropped by [v1.20](https://lists.freedesktop.org/archives/wayland-devel/2021-November/042026.html) - let me do a clean build then it should be ready for merge

**Comment by SupervisedThinking** [comment]
Clean build finished without quirks, should be good to go.

**Review by CvH — APPROVED** [review]

**Pull request merged**
