### PR TITLE
lcdd: update to HEAD 2020-07-21 fixes PiFaceCAD

### PR DESCRIPTION
**Pull request by heitbaum**
Fixes https://github.com/LibreELEC/LibreELEC.tv/issues/4780
Please let me know if we need/want a back port.

### CODE REVIEW

**Comment by CvH** [comment]
do we need libhid ?
looks like libhid is shifted long time ag to https://github.com/libusb/hidapi

**Comment by heitbaum** [comment]
@kisik21 tested with the 9.2 HEAD with libhid 0.2.16

I just built lcdd on LE10 HEAD without libhid

```
diff --git a/packages/addons/service/lcdd/package.mk b/packages/addons/service/lcdd/package.mk
index eacf3c39c8..a5090976f6 100644
--- a/packages/addons/service/lcdd/package.mk
+++ b/packages/addons/service/lcdd/package.mk
@@ -10,7 +10,7 @@ PKG_ARCH="any"
 PKG_LICENSE="GPL"
 PKG_SITE="http://lcdproc.org/"
 PKG_URL="https://github.com/lcdproc/lcdproc/archive/$PKG_VERSION.tar.gz"
-PKG_DEPENDS_TARGET="toolchain freetype libftdi1 libhid libugpio libusb ncurses serdisplib"
+PKG_DEPENDS_TARGET="toolchain freetype libftdi1 libugpio libusb ncurses serdisplib"
 PKG_SECTION="service"
 PKG_SHORTDESC="LCDproc: Software to display system information from your Linux/*BSD box on a LCD"
```

**There are references to libhid in the code**
https://github.com/lcdproc/lcdproc/search?q=libhid

I have updated libhid to current https://github.com/LibreELEC/LibreELEC.tv/commit/0de3e472817b5b88355c16a90e02b997c226f45c and compiled results below

```
Executing (target): /home/rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/build/lcdd-9ec9ba4e5dda653288bc55d2898723aa2c2ad9c1/configure --host=x86_64-libreelec-linux-gnu --build=x86_64-linux-gnu --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --libdir=/usr/lib --libexecdir=/usr/lib --localstatedir=/var --disable-static --enable-shared --with-ft-prefix=/home/rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr --enable-libusb --enable-libftdi --disable-libX11 --enable-libhid --disable-libpng --enable-drivers=all
checking if libhid support has been enabled... yes
checking for libhid >= 0.2.16... yes
/home/rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc -I/home/rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include -I/home/rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/libusb-1.0 -I/home/rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include -fPIC -Wall -march=x86-64 -m64 -mmmx -msse -msse2 -mfpmath=sse -Wall -pipe  -O2 -fomit-frame-pointer -O3 -Wno-unused-function -ftrampolines -shared -march=x86-64 -m64 -Wl,--as-needed -fuse-ld=gold -o mdm166a.so mdm166a-mdm166a.o -L/home/rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib -L/home/rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib -lusb -lhid libLCD.a -ldl 
```

**Comment by heitbaum** [comment]
> do we need libhid ?
> looks like libhid is shifted long time ago to https://github.com/libusb/hidapi

Is hidapi the same as libhid? I couldn’t find the linkage between these 2 projects

**Comment by heitbaum** [comment]
Furthermore it does look like libhid is only required for the mdm166a VFD
- https://www.kodinerds.net/index.php/Thread/53959-mdm166a-Futaba-Display-Treiber-Unterschiede-Linux-zu-Windows/

CD1FAC41-F3AF-4F74-AFC4-8E5120B3513F

**Review by lrusak — APPROVED** [review]
LGTM

**Pull request merged**
