### PR TITLE
rpi-tools: initial add-on

### PR DESCRIPTION
**Pull request by lrusak**
This is an initial "virtual" add-on that has some tools included. Initially I am including:
1. [RPi.GPIO](https://sourceforge.net/projects/raspberry-gpio-python/)
2. [picamera](https://github.com/waveform80/picamera)

This can easily be updated to include more raspberry pi related tools in the future.

### CODE REVIEW

**Comment by InuSasha** [comment]
@lrusak: If it an idea to replace rpi.gpio with gpiozero, or to add gpiozero?
https://www.raspberrypi.org/blog/gpio-zero-a-friendly-python-api-for-physical-computing/
https://github.com/RPi-Distro/python-gpiozero

**Comment by lrusak** [comment]
@InuSasha done :)

anything else?

**Comment by InuSasha** [comment]
i know nothing else. maybe other?

**Comment by lrusak** [comment]
something can always be added later

**Pull request merged**
