### PR TITLE
vdr-addon: update to 2.4.0

### PR DESCRIPTION
**Pull request by CvH**
- update to VDR 2.4.0 (finally stable)
- several plugins updated

supersedes https://github.com/LibreELEC/LibreELEC.tv/pull/2590

@mglae maybe give it a test run ?

### CODE REVIEW

**Comment by CvH** [comment]
@belaid38 have a look here http://cvh.libreelec.tv/addons/9.0/vdr/

**Comment by belaid38** [comment]
thanx @CvH

**Comment by CvH** [comment]
@mglae added patch + change
tx for the patch didn't saw that, looks like nobody cares about upstream fixes :/

**Comment by belaid38** [comment]
@CvH   i tested vdr 2.4.0 in coreelec 

vdr 2.4.0 is work fine It looks excellent and fast ans stable but I can not judge it completely and libreelec 9 is alpha (kodi18 alpha not stable now )

**Comment by smp79** [comment]
Does it make sense to add [this small patch](https://github.com/FernetMenta/VDR/commit/e474ce83ef0d60e3d074a4f0c18b13c080b7374a)?
[More info.](https://forum.kodi.tv/showthread.php?tid=316451&pid=2687713#pid2687713)

**Comment by CvH** [comment]
> Does it make sense to add this small patch?

It `disable debug for locking sequence` - at default we have no vdr logging so this would change nothing. If you activate debug log you may want these info. The real question is why the heck is that not config able due some commandline/setting.

**Comment by belaid38** [comment]
hi @CvH   plz build vdr 2.4.0  for LE8.2 

LE9 is alpha not stable now

**Pull request merged**
