### PR TITLE
kodi update to latest

### PR DESCRIPTION
**Pull request by CvH**
- Kodi updated to latest
- emulator updates to latest incl. Leia -> Matrix switches
- fixes for bsnes, patches didn't align so blind fix for current version

build for generic (mame and mr boom are still broken)

### CODE REVIEW

**Comment by CvH** [comment]
added kodi bump that support he needed changes for https://github.com/xbmc/xbmc/pull/18534

currently blind changes including the suggestions from @HiassofT

**Comment by HiassofT** [comment]
we also need to include the appliance-gbm.xml - haven't created one yet :)

**Comment by jernejsk** [comment]
Very quick test on AW H6 didn't show any major issue. appliance.xml will probably need some adjustments.

**Comment by jernejsk** [comment]
Speaking too fast - power options menu shows only titlebar.

**Comment by lrusak** [comment]
> Speaking too fast - power options menu shows only titlebar.

this issue is fixed here -> https://github.com/xbmc/xbmc/pull/18669

**Comment by CvH** [comment]
- updated kodi (includes power option fix)
- removed @HiassofT suggestions - needs separate commit/pr

**Comment by jernejsk** [comment]
hm... fresh images have DRMPRIME decoder disabled and PRIME render method is set to EGL by default. I guess most projects would need appliance.xml adjusted. Currently I'm not sure what needs to be done to enable/change these two options.

**Comment by CvH** [comment]
After upgrading to latest kodi incl https://github.com/xbmc/xbmc/pull/18534 the my resolution settings are empty till I switch the inputs at the settings menu. Screen resolution didn't looked right so it likely self adjusted to some random value.


Ofc all binary addons are broken and need updates :)

**Comment by HiassofT** [comment]
@jernejsk @CvH could you test with the additional 3 commits from here https://github.com/HiassofT/LibreELEC.tv/commits/le10-kodi-windowing - esp "kodi: add appliance.xml for gbm windowing"

kodi/RPi4 unpacks and (semi-manually) merged appliance.xml looks reasonable but I can't test more ATM

**Comment by jernejsk** [comment]
@HiassofT I can confirm that commit 7eaf62856efe9bd9f65140d65bb64c4e952aecf9 solves settings issue.

**Comment by CvH** [comment]
- added @HiassofT fixes
- added latest kodi
- bumped addon version (api breakage, again)
- updated all binary addons

works for Generic

**Comment by CvH** [comment]
- update to K19a3
- updated addons again
- works now at Generic after merge of https://github.com/xbmc/xbmc/pull/18691

**Comment by jernejsk** [comment]
Seems to work now on Allwinner H6 (quick test only)

**Review by jernejsk — APPROVED** [review]

**Comment by heitbaum** [comment]
K19a3 built and running on NUC6 Generic. All looks good.

(Expected errors below on the add ons - no rush for me.) but as FYI
 
ERROR <general>: CCurlFile::Open failed with code 404 for https://addons.libreelec.tv/9.80.7/Generic/x86_64/addons.xml.gz.sha256:
ERROR <general>: Open - failed to open source <https://addons.libreelec.tv/9.80.7/Generic/x86_64/addons.xml.gz.sha256>
ERROR <general>: CRepository: failed read 'https://addons.libreelec.tv/9.80.7/Generic/x86_64/addons.xml.gz.sha256'
INFO <general>: ADDON: waiting for add-ons to update...
INFO <general>: ADDON: inputstream.adaptive version 2.6.0.2 is incompatible
INFO <general>: ADDON: inputstream.ffmpegdirect version 1.16.0.1 is incompatible
INFO <general>: ADDON: inputstream.rtmp version 3.2.0.1 is incompatible
INFO <general>: ADDON: pvr.hts version 7.2.1.1 is incompatible

**Comment by CvH** [comment]
@heitbaum the pr includes a bump of the addon repo version -> all addons need a rebuild.
And the addons are build after the pr got merged. So 1-2 days after those kind of pr the addons are in limbo.
Now the addons are merged and could be updated.

**Pull request merged**
