### PR TITLE
systemd: remove other notused systemd units

### PR DESCRIPTION
**Pull request by heitbaum**
Changes
- linux (Allwinner aarch64): change .config HUGETLBFS is not set
- linux (Qualcomm): change .config HUGETLBFS is not set
- linux (Rockchip RK3328): change .config HUGETLBFS is not set
- linux (Rockchip RK3399): change .config HUGETLBFS is not set
- systemd: remove other notused systemd units

CONFIG_HUGETLBFS and CONFIG_HUGETLB_PAGE need to be set for
/sys/kernel/mm/hugepages to be available. Reading at
https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt

remove unused units:
- systemd[1]: systemd-journald-audit.socket was skipped because of an unmet condition check (ConditionSecurity=audit).
- systemd[1]: dev-hugepages.mount was skipped because of an unmet condition check (ConditionPathExists=/sys/kernel/mm/hugepages).

### CODE REVIEW

**Comment by CvH** [comment]
@HiassofT opinions ?

**Comment by CvH** [comment]
@HiassofT ping

**Comment by HiassofT** [comment]
Very likely we won't ever use hugetlb but I have no idea why hugetlbfs is enabled in AW/RK/Qualcomm kernels

**Comment by jernejsk** [comment]
No special reason, I guess remnant of arm64 defconfig, at least for AW.

**Comment by lrusak** [comment]
Might be worth adding `CONFIG_HUGETLBFS=n` to the `kernel_options`

**Comment by heitbaum** [comment]
> Might be worth adding `CONFIG_HUGETLBFS=n` to the `kernel_options`

added

**Review by CvH — APPROVED** [review]

**Pull request merged**
