### PR TITLE
openssl: update to 3.0.1

### PR DESCRIPTION
**Pull request by heitbaum**
Update of openssl 1.1.1 to openssl 3.0.1.

announcement:
- https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final/
- https://www.openssl.org/docs/man3.0/man7/migration_guide.html
- https://github.com/openssl/openssl/blob/openssl-3.0.1/CHANGES.md
  - Version 3.0.1 released on 14th Dec 2021

This will allow the consolidation for crypto libraries under openssl only (and drop gnutls)
-  From OpenSSL 3.0 this is replaced by the Apache License v2.

### no longer a DRAFT PR 

I have been running this in the :dev branch - but would like to wait till 3.0.1 before incorporating into :master. The versioning has changed to semantic version numbers.

### CODE REVIEW

**Comment by heitbaum** [comment]
Will ”clean build test” this across all build targets, then remove from draft.

**Comment by heitbaum** [comment]
inplace upgrade issues:- note to self:
Missing libcrypto.so.1.1 causes `.kodi.FAILED`
these 2 addons in my case…
```
2021-12-15 22:01:42.836 T:1380    DEBUG <general>: ADDON: Dll Initializing - Archive support
2021-12-15 22:01:42.837 T:1380    DEBUG <general>: SECTION:LoadDLL(/storage/.kodi/addons/vfs.libarchive/vfs.libarchive.so.19.0.0)
2021-12-15 22:01:42.837 T:1380    DEBUG <general>: Loading: /storage/.kodi/addons/vfs.libarchive/vfs.libarchive.so.19.0.0
2021-12-15 22:01:42.839 T:1380    ERROR <general>: Unable to load /storage/.kodi/addons/vfs.libarchive/vfs.libarchive.so.19.0.0, reason: libcrypto.so.1.1: cannot open shared object file: No such file or directory
2021-12-15 22:05:36.072 T:1376    DEBUG <general>: ADDON: Dll Initializing - SFTP support
2021-12-15 22:05:36.072 T:1376    DEBUG <general>: SECTION:LoadDLL(/storage/.kodi/addons/vfs.sftp/vfs.sftp.so.19.0.0)
2021-12-15 22:05:36.072 T:1376    DEBUG <general>: Loading: /storage/.kodi/addons/vfs.sftp/vfs.sftp.so.19.0.0
2021-12-15 22:05:36.072 T:1376    ERROR <general>: Unable to load /storage/.kodi/addons/vfs.sftp/vfs.sftp.so.19.0.0, reason: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by CvH** [comment]
@heitbaum all addons need rebuild too

**Comment by heitbaum** [comment]
Need to check into the crust build failure issue further…
- https://github.com/m01/rock64-arch-linux-build/issues/3
- The patch does fix the compile (H6) tested `PROJECT=Allwinner ARCH=arm DEVICE=H6 make image`
- Now to do a full build run though of all images

**Comment by heitbaum** [comment]
Note: OpenSSL libatomic requirement - https://github.com/openssl/openssl/issues/17049

**Comment by heitbaum** [comment]
Build tested 3.0.1 on current :master on all of: reminder needs REBUILD
```
PROJECT=Allwinner ARCH=arm DEVICE=A64 make image
PROJECT=Allwinner ARCH=arm DEVICE=H3 make image
PROJECT=Allwinner ARCH=arm DEVICE=H5 make image
PROJECT=Allwinner ARCH=arm DEVICE=H6 make image
PROJECT=Amlogic ARCH=arm DEVICE=AMLGX make image
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy make image
PROJECT=Generic ARCH=x86_64 DEVICE=Generic make image
PROJECT=NXP ARCH=arm DEVICE=iMX6 make image
PROJECT=NXP ARCH=arm DEVICE=iMX8 make image
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 make image
PROJECT=RPi ARCH=arm DEVICE=RPi2 make image
PROJECT=RPi ARCH=arm DEVICE=RPi4 make image
PROJECT=Samsung ARCH=arm DEVICE=Exynos make image
```

**Comment by CvH** [comment]
pls add a repo update like https://github.com/LibreELEC/LibreELEC.tv/commit/f821c4bd433faf8dfbe70b51ff1b822270023041

additional todo (after merge)
- migrate curl etc back to openssl, licence conflict is solved with 3.0
- check if removing gnutls again

**Comment by heitbaum** [comment]
> pls add a repo update like [f821c4b](https://github.com/LibreELEC/LibreELEC.tv/commit/f821c4bd433faf8dfbe70b51ff1b822270023041)

Added ea503188cf

**Review by CvH — APPROVED** [review]

**Pull request merged**
