### PR TITLE
samba: update to samba-4.x

### PR DESCRIPTION
**Pull request by MilhouseVH**
Build pre-requisite: if
```
perl -MJSON -e 'exit(0);'
```
fails then you need to install ~`sudo cpan JSON`~ `sudo apt-get install libjson-perl` prior to building or the `samba` package will fail.

Thanks @sraue and @koying for laying the ground work on this.

This PR has a dependency on https://github.com/LibreELEC/service.libreelec.settings/pull/62 which needs to be merged and LE settings bumped when this goes in.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Updated with the addition of `libjson-perl` to `checkdeps` - this works for Debian but probably needs testing on non-Debian hosts.

**Comment by escalade** [comment]
I have a suggestion for this PR, the removal of the samba-autoshare script. A better approach is simply sharing /var/media as "Media" when SAMBA_AUTOSHARE=true. I can't see the point of creating a separate share on plugging a disk and restarting smbd each time, it's unnecessary complex.

Here's the changes I did in my build: https://github.com/escalade/LibreELEC.tv/commit/788161be5973382d030b03f6aeb3a607822b81da

There seems to be an issue with reported file size when Kodi uses libsmbclient from the updated version as well: https://forum.libreelec.tv/thread-302-post-42037.html#pid42037

Probably a good idea to test this PR properly :)

**Comment by MilhouseVH** [comment]
> I have a suggestion for this PR, the removal of the samba-autoshare script. 

I'd probably be more inclined to handle that as a separate PR, as I'm not convinced this change has legs right now.

> There seems to be an issue with reported file size when Kodi uses libsmbclient from the updated version as well: https://forum.libreelec.tv/thread-302-post-42037.html#pid42037

Yes, already fixed in this PR - the https://github.com/escalade/LibreELEC.tv/commit/788161be5973382d030b03f6aeb3a607822b81da commit on your branch is out of date, you should re-pull this PR.

> Probably a good idea to test this PR properly :)

Unless we can resolve the anonymous access issue, and also the occasional thread locking issue (some kind of race condition?) I'm inclined to park this regardless of whatever it might fix. So far I've seen no evidence it actually fixes anything, and just causes more problems.

**Comment by MilhouseVH** [comment]
Update to samba-4.6.1 due to security vulnerability: https://www.samba.org/samba/history/samba-4.6.1.html

**Comment by MilhouseVH** [comment]
Updated to 4.6.2 which fixes a regression introduced by the 4.6.1 bug fix...

https://www.samba.org/samba/history/samba-4.6.2.html

**Comment by MilhouseVH** [comment]
Added a systemd commit.

`smbd`, `nmbd`, `rpcbind` and `kodi` (via libsmbclient) all maintain locks in `/var`.

When shutting down the system without the requirement on `var.mount`, systemd will attempt to stop the `var.mount` unit (ie. unmount `/var`) _before_ the `smbd`, `nmbd`, `rpcbind` and `kodi` processes are terminated. As these processes all have open files on `/var`, the `var.mount` unit will fail.

Adding the `var.mount` requirement fixes this problem, and `var.mount` is stopped _after_ the other processes.

**Comment by stefansaraev** [comment]
you can mount /var in initramfs: http://sprunge.us/DTLa and save yourself some pain.

**Comment by MilhouseVH** [comment]
Thanks @seo - have dropped the systemd commit and added #1554

**Comment by MilhouseVH** [comment]
Re-added systemd commit as #1554 didn't work as expected due to systemd annoyances.

**Comment by mglae** [comment]
When removing `Conflicts=umount.target` from var.mount /var never gets unmounted because of `DefaultDependencies=no`

**Comment by MilhouseVH** [comment]
@mglae great thanks - that seems to work nicely! systemd patch removed, var.mount patch added.

**Pull request merged**
