### PR TITLE
linux: bump RPi/RPi2 to linux-4.9.36, Generic to 4.11.8

### PR DESCRIPTION
**Pull request by MilhouseVH**
Bump RPi and RPi2 to the latest stable 4.9.36 kernel with latest RPi firmware from stable branch.

Bump Generic to 4.11.8 in order to support new Intel and AMD CPUs and features (4K HEVC etc.).

Bumping RPi/RPi2 to 4.11.y is risky (relatively untested kernel, large user base) with no obvious benefit, whereas the benefits are relatively clear with Generic (plus, it's a much smaller user base).

Build and run-time tested for RPi, RPi2 and Generic.

### CODE REVIEW

**Comment by chewitt** [comment]
@MilhouseVH RTL8192* patches in https://github.com/LibreELEC/LibreELEC.tv/tree/libreelec-8.2/projects/Odroid_C2/patches can be dropped as they're included in the driver bumps.

**Comment by CGarces** [comment]
drivers on 8.2 not has been updated, so patches can't be dropped. Should I backport the package updates?

**Comment by chewitt** [comment]
@CGarces they're inhttps://github.com/LibreELEC/LibreELEC.tv/pull/1786/commits/f0d7f465a3e8d4e5fc13f5ab0d3e9fb9d636a134 which is part of this PR

**Comment by MilhouseVH** [comment]
Odroid RTL8192CU and RTL8192EU patches dropped (squashed into linux-drivers commit).

imx6 has an RTL8812AU-010-compile-3.14.patch patch, I'm guessing this can go too?

**Comment by chewitt** [comment]
@MilhouseVH no errors from imx6 when I build-tested the changes so that patch can stay.

**Comment by HiassofT** [comment]
Working fine on RPi3.

Tested I2S audio (Cirrus Logic audio card), lirc-rpi (with userspace lircd) and gpio-ir (with both userspace lircd and in-kernel decoding).

Thanks a lot!

**Pull request merged**
