### PR TITLE
systemd: add backport patch to fix device enumeration

### PR DESCRIPTION
**Pull request by HiassofT**
Revert the problematic systemd commit (plus a dependent one) that
causes partitions to be missing in kodi's "Files" list.

See https://github.com/systemd/systemd/issues/17259

### CODE REVIEW

**Comment by HiassofT** [comment]
systemd maintainers were quick and proposed a fix (it's still under discussion though). I've switched the PR to the proposed fix instead of the revert.

**Comment by HiassofT** [comment]
updated with v2 of the PR

**Comment by HiassofT** [comment]
updated with v3 of the PR, quick test looks good

**Review by CvH — APPROVED** [review]

**Comment by HiassofT** [comment]
v3 of the PR got merged upstream, so we can simply drop the backport patch in the next systemd bump

**Pull request merged**
