### PR TITLE
Update wayland and x11 packages

### PR DESCRIPTION
**Pull request by heitbaum**
- [xcb-proto: update to 1.15.2](https://github.com/LibreELEC/LibreELEC.tv/commit/f8317fb37b9df30f20cf6c06f04df7d3b6cedee1)
- [weston: update to 10.0.1 and pkg_url](https://github.com/LibreELEC/LibreELEC.tv/commit/1ea27ff2d9f54adb407331c4c3e591d8ac3564bd)
- bemenu: update to 0.6.10
- [wayland: update to 1.21.0 and PKG_URL](https://github.com/LibreELEC/LibreELEC.tv/commit/01eea564661f84054458778a1e81ce5bb8b96546)
- [wayland-protocols: update to 1.26](https://github.com/LibreELEC/LibreELEC.tv/pull/6670/commits/9b0c92e742b59380221645057d2351e5d632a00f)
- xf86-input-synaptics: update to 1.9.2 and https
- xorg-server: update to 21.1.4
- encodings: update to 1.0.6 and https
- font-util: update to 1.3.3 and https

### CODE REVIEW

**Review by CvH — APPROVED** [review]

**Comment by SupervisedThinking** [comment]
https://github.com/Cloudef/bemenu/releases/tag/0.6.10

**Comment by heitbaum** [comment]
> https://github.com/Cloudef/bemenu/releases/tag/0.6.10

Updated 👍

**Comment by heitbaum** [comment]
added wayland-protocols: update to 1.26

**Comment by heitbaum** [comment]
Added xf86-input-synaptics: update to 1.9.2 and https

**Comment by heitbaum** [comment]
Added xorg-server security release

xorg-server: update to 21.1.4
ann:
- https://lists.x.org/archives/xorg/2022-July/061035.html
- https://lists.x.org/archives/xorg/2022-July/061036.html

**Pull request merged**
