### PR TITLE
Add $DEVICE support to the build-system

### PR DESCRIPTION
**Pull request by kszaq**
Such projects should be compiled differently for each device.
A device for multi-device projects must be specified in the
command line.

Originally created by @codesnake: https://github.com/codesnake/OpenELEC.tv/commit/767125372cd5895aef6a05e86d47d2cd12c3d223

Adapted for LE, I hope I got it all. Comments are very welcome.

Submitted per request from @chewitt

### CODE REVIEW

**Comment by codesnake** [comment]
Thanks @kszaq. It is not the best solution, but I think is better than having a lot of similar projects with the same patches (especially for the Amlogic-based zoo). Makes maintenance easier for similar projects.

**Comment by kszaq** [comment]
I reworded commit message so that you don't get an email every time someone cherry-picks it in the future.

**Comment by Kwiboo** [comment]
Will there ever be a project with mixed arch devices? If so I would suggest squashing https://github.com/Kwiboo/LibreELEC.tv/commit/d644fbff71d9cd04a6a5977de410ddd79dd91fb5 into this PR.

**Comment by Kwiboo** [comment]
I have added some more commits to my [pr842](https://github.com/Kwiboo/LibreELEC.tv/commits/pr842) branch that should enhance the device support, feel free to pick and squash anything that makes sense to include.

I skipped the following packages/files as it did not make much sense to have device specific versions:
[xorg.conf](https://github.com/Kwiboo/LibreELEC.tv/blob/pr842/packages/x11/xserver/xorg-server/package.mk#L165-L166)
[busybox-target.conf/busybox-init.conf](https://github.com/Kwiboo/LibreELEC.tv/blob/pr842/packages/sysutils/busybox/package.mk#L58-L68)
[smb.conf](https://github.com/Kwiboo/LibreELEC.tv/blob/pr842/packages/network/samba/package.mk#L173-L175)
[splash.conf/splash-*.png](https://github.com/Kwiboo/LibreELEC.tv/blob/pr842/packages/tools/plymouth-lite/package.mk#L49-L53)

**Comment by lrusak** [comment]
I **do not** like having packages exist outside of $ROOT/packages/ I would like to clean up the fact that we currently allow $PROJECT/packages

Please if there is a way to avoid this please do it. There is no sense maintaining multiples of the same packages when you can just add a different PKG_VERSION to the package.mk

**Comment by vpeter4** [comment]
Please **leave** package existence in project folder at least how it is done now. No need to remove this part of the code!

**Comment by kszaq** [comment]
@Kwiboo Thank you, your commits are for sure a necessary addition here. I will pick them to this PR. 

@lrusak I can remove device-specific packages from this PR while not changing project-specific packages. What do you think?

**Comment by lrusak** [comment]
@kszaq Yes that would be preferred, thanks.

**Comment by kszaq** [comment]
PR Updated: 
- removed device-specific packages, while keeping device-specific patches
- improved $DEVICE support patches from @Kwiboo for features that I missed

**Comment by Kwiboo** [comment]
@kszaq the [scripts/image: bootloader device support](https://github.com/LibreELEC/LibreELEC.tv/pull/842/commits/95342a9ff1c2eafd368d0279a75ba85977fa3641) commit needs to be updated to remove the `BOOTLOADER_DIR` modifications now that device-specific packages is removed, other then that it looks great

**Comment by kszaq** [comment]
@Kwiboo thank you once again! Updated.

**Comment by lrusak** [comment]
I'm happy with this :+1: thanks @kszaq and @Kwiboo

**Comment by MilhouseVH** [comment]
One downside of this is that the `PRETTY_NAME` shown in Kodi Sys Info, and LE Settings > About may become illegible due to increased length, particularly for custom builds.

**Pull request merged**
