### PR TITLE
Remove language add-ons

### PR DESCRIPTION
**Pull request by lrusak**
This removes the language add-ons from being built in. This was very annoying when the language add-ons would update almost every day.

Instead, I have included a patch to disable the CEC peripheral option `use_tv_menu_language` by default. This should fix the bug where some users reporting not seeing any text because kodi would try to switch to a language that didn't exist on the system.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I just disable the languages in my builds with `KODI_LANGUAGE_ADDONS="no"` in `$HOME/.libreelec/options`. Maybe it would be easier to use (or change) that setting than revert the language support?

**Comment by lrusak** [comment]
Honestly I never liked this in the first place and I only did it because it was a "Release Blocker" for the old project.

**Comment by InuSasha** [comment]
Question: how will libreelec support different languages, in future?

**Comment by stefansaraev** [comment]
@InuSasha you can install a language addon from kodi repo. in fact, it will be automagicaly downloaded and installed when you switch change your language preference.

**Comment by MilhouseVH** [comment]
I thought the problem was that non-English users were having difficulty completing the first run wizard because as at that point, the only language installed is English. Hence installing all languages by default.

**Comment by stefansaraev** [comment]
that was the problem. but wizard is next next next finish. neither are language addons pre-installed on any other linux distro / android / ios/osx or windows

**Comment by MilhouseVH** [comment]
Coincidentally... http://forum.kodi.tv/showthread.php?tid=250817&pid=2310006#pid2310006

**Comment by lrusak** [comment]
We never even merged the language setting back into the first run wizard. This this wasn't doing anything anyways.

**Pull request merged**
