### PR TITLE
Allwinner: Improve suspend/resume

### PR DESCRIPTION
**Pull request by jernejsk**
This PR does following:
- refreshes Linux PM related patches with latest versions
- remove obsolete network hacks for H6
- add ATF patch which fixes shutdown sequence
- enable CIR on all boards, even if it's not present - some boards like pine64 have slot for IR receiver
- updates crust to latest master (fixes two IR issues)

Final outcome of this PR is actually working suspend/resume and power on on A64, ethernet is properly shutdown at suspend and reinitialized after resume and fixed IR on boards with external 32768 Hz oscillator.

What remains to be fixed after this PR:
- ~more reliable RC6 decoding~ (fixed in Crust update)
- H3 support
- configs for some boards

### CODE REVIEW

**Comment by smaeul** [comment]
@jernejsk FYI, in case this is a blocker: with the new `dwmac_sun8i` patches, on Orange Pi 3 only, Ethernet is not working for me after suspend/resume due to the unusual PHY setup. I can recover it by setting the interface down/up. I am not sure what the issue is.

**Comment by jernejsk** [comment]
@smaeul Network on OPi3 works just fine after resume, I tested it several times. In fact, I could get rid two OPi3 related eth hacks (suspend/resume handler hack and OPi3 specific shutdown handler). I think I know why I doesn't work for you. Take a look here: https://github.com/smaeul/linux/commits/pine64-5.11/drivers/net/ethernet/stmicro/stmmac/dwmac-sun8i.c
First you have commit 8784bc149235495e3d52acf3a80e79349010eae8 and then b98f624c85ebc4bff30c9ea910ca1927a277c82c. Clearly, second one should conflict first one because both add shutdown handler, but it doesn't, for some reason.

**Review by dhewg — APPROVED** [review]
Tested on OPi3, all fine and dandy!

**Comment by jernejsk** [comment]
@smaeul this is patch set used here: https://github.com/jernejsk/linux-1/commits/le-h6

It could also be that network manager (connman) automatically resets all interfaces at resume.

**Comment by jernejsk** [comment]
IR should work well again. This is gtg from my side.

**Pull request merged**
