### PR TITLE
Regain SPDIF passthrough on imx hardware with "old" kernel

### PR DESCRIPTION
**Pull request by mhueske**
Due to device name changes an alias has to be defined in the alsa config. After this Kodi is able to use SPDIF as passthrough device again.
This solves the following bug: https://forum.libreelec.tv/thread-904.html

### CODE REVIEW

**Comment by vpeter4** [comment]
I'm going to build one image for myself and see the result.

**Comment by mhueske** [comment]
I think the bug only exists with the old kernel. But this fix shouldn't break anything with the new one, so thanks for testing :-)

**Comment by vpeter4** [comment]
I build image with new kernel and hdmi audio still works. But can't actually test spdif because I don't have any cable which would go to cuboxi i4p (connector is to big).

**Comment by vpeter4** [comment]
If this change is problematic in general then patch can be moved to projects folder (projects/imx6/patches/alsa-lib).

**Comment by mhueske** [comment]
Good idea, thanks for the tip.
I have just updated this.

**Comment by vpeter4** [comment]
malte gave me few suggestions regarding the cable "fix": http://forum.solid-run.com/viewtopic.php?f=16&t=1069&p=7895#p7895

I decided to remove some plastic on a connector and now it gets attached to cuboxi. I tested image with new kernel and it is working. So I assume it works for old kernel too as was designed for it.

Ready to merge.

**Pull request merged**
