### PR TITLE
Rockchip more fixes

### PR DESCRIPTION
**Pull request by knaerzche**
After re-testing  also on different screens more fixes:

* fixed PLL settings for RK3288 for 2160p@60Hz (never had issues on my 4k screen, but appeared on 4k Samsung TV)
* enabled FE phy for Beelink A1 image, so that people using that image having only FE on their box will have ethernet too
* add cec pinctrl for RK3288 miqi 
* fixed devicetree to be used for updates from LE9 for tinker board (same as we use for images)

### CODE REVIEW

**Review by lrusak — APPROVED** [review]
LGTM

**Comment by knaerzche** [comment]
- added a patch to work arround an CSC issue (which obviously only exists for RK) in dw-hdmi
- aligned linux option accross RK SoCs (mostly by squashing what other projects have):
- FS options, supported block devices, partition types supported
- options recommended by systemd (might night a further changes depending on https://github.com/LibreELEC/LibreELEC.tv/pull/5217)
- aligned support for some HID and (other) input devices (might need further changes depending on https://github.com/LibreELEC/LibreELEC.tv/pull/5219)
- added support for more BT devices
- also some cleanup in RK3288 config which included support for foreign DRM systems

I'm still unclear if we really need VIRTIO support as most ARM projects don't enable it but it might be required by some docker stuff - so I've left it in

I also re-added a hack-fix for dw-hdmi CEC: It is no longer required for any of my CEC-capable screens, but it might help to solve https://github.com/LibreELEC/LibreELEC.tv/issues/5215)

**Comment by lrusak** [comment]
I don't know how much value there is in changing some options for PR's that haven't been merged yet. You may just have to change things again. It's not my platform so I don't really care but it may be more valuable to review those PR's before making changes that depend on them 😃 Without those PR's getting reviewed consensus will never be reached. 👍

**Comment by knaerzche** [comment]
Actually this PR just aligns with changes/options other projects already did/have to ensure we have more or less the same features across all platforms - I didn't even look yet in details what https://github.com/LibreELEC/LibreELEC.tv/pull/5217 or https://github.com/LibreELEC/LibreELEC.tv/pull/5219 proposing.
I just mentioned those explicitly to ensure this is _not_ understood as an anticipation of them and I'm fine to re-adapt if necessary :smile:

**Review by CvH — APPROVED** [review]

**Pull request merged**
