### PR TITLE
open-iscsi: update to 2.1.3

### PR DESCRIPTION
**Pull request by heitbaum**
this is the update to the open-iscsi package. iscsistart Is used in the initramfs.

open-iscsi: update to 2.1.3
- update bf39941 (2013-07-30) to 2.1.3 (2020-12-19)
- add dependency on open-isns package
- changelog: https://github.com/open-iscsi/open-iscsi/blob/master/Changelog
- releaselog: https://github.com/open-iscsi/open-iscsi/releases

open-isns: initial commit
- needed by open-iscsi 2.1.3
- open-isns is provided as a seperate package
- reference: https://github.com/open-iscsi/open-isns

successfully builds (on both Generic and AMLGX) 

runs - but needs operational testing within initramfs (volunteers?)
```
cd LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/initramfs/usr/lib
LD_LIBRARY_PATH=. LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/initramfs/usr/sbin/iscsistart 
iscsistart: InitiatorName not set. Exiting iscsistart
```

### CODE REVIEW

**Comment by CvH** [comment]
is iscsi used at all these days from anyone ?
there are basically no forum results that indicates that someone successfully using it

wondering if we should just drop it ?

**Comment by heitbaum** [comment]
Since open media vault dropped it. I believe that only (freenas) https://www.truenas.com/truenas-core/ is the open source offering. We use plenty at work. Most of our arrays are all iSCSI 40GB but wouldn’t use it in a home situation. Prefer NFS for VMDK if I need, otherwise SMB is just fine. 

As it is configured in LibreELEC it seems to have been for the purpose of boot partition, otherwise why would it have been in the initramfs? I did a lot of boot from SAN in the day, but now mostly a Virtualisation world. Still do some RDM / iSCSI pass through devices (but haven’t done any HPUX, AIX or Solaris for a few years) On Intel have configured some SQL servers with ISCSI boot - but again not very often.

Either way, probably needs work in doco / cleanup.

a reasonable article on https://wiki.archlinux.org/index.php/ISCSI/Boot

**Comment by mglae** [comment]
Fixes to make this booting: https://github.com/mglae/LibreELEC.tv/commits/le10_large_iscsi

But because of now including libcrypt the size of iscsistart increase from 305408 to 2628000.

My recommendation is to keep the old version. We can add the fixes and close this PR and merge another one documenting the size regression in package.mk

**Comment by CvH** [comment]
I would rather nuke it completely, its very niche and NFS serves the same functions or am I wrong ?

**Comment by heitbaum** [comment]
My 2c is that we ignore it / drop it? - for LE10. Revisit it as LE10.1 if we have users... 
iSCSI as a block device can make sense, but I would think very niche in the home media space. We don’t boot our work VMware clusters from iSCSI (they boot from flash and mount iSCSI luns.) The only time (of recent times) I have booted from iSCSI is HPUX service guard clusters and Microsoft SQL clusters.

**Comment by heitbaum** [comment]
I have updated the open-isns package to 0.101 (which negates the need for the patch) for the purposes of completeness.

**Comment by CvH** [comment]
current plan is to keep iscsi at LE10 and afterwards drop it, there is not really a use case that can't replaced by nfs

**Comment by heitbaum** [comment]
Ref: forum: https://forum.libreelec.tv/thread/23447-libreelec-not-boot-from-remote-iscsi-error-in-mount-flash-iscsistart-unable-to-c/

**Comment by heitbaum** [comment]
Parking this PR

**Pull request closed without merging**
