### PR TITLE
kodi: update to current master with ffmpeg 7.1

### PR DESCRIPTION
**Pull request by HiassofT**
Initial testing on RPi4 and RPi5 looks fine.

Depends on #9569

### CODE REVIEW

**Comment by knaerzche** [comment]
@HiassofT `AVFrame.interlaced_frame` has been deprecated (in ffmpeg 7.0, I think) and moved to `AVFrame.flags` - so the deinterlace filter kodi patches  should be updated accordingly, i.e. 

`if (!m_processInfo.GetVideoInterlaced() && m_pFrame->interlaced_frame)` 

should be converted to 

`if (!m_processInfo.GetVideoInterlaced() && !!(m_pFrame->flags & AV_FRAME_FLAG_INTERLACED))` 

I didin't do this myself, because I noticed RPi project has more patches which are touching this code which won't apply after I changed the common ones.
We be good if you could do - should be pretty trivial changes

**Comment by HiassofT** [comment]
@knaerzche thanks a lot for the hint, I've updated the drmprime-filter patchset and rebased the RPi patchset.

SW deinterlace still works fine on RPi4, HW deinterlace on RPi is a separate issue which we'll likely handle in a separate PR.

**Comment by HiassofT** [comment]
@jernejsk can you please test again with the current version of this PR if HW deinterlace still is fine on AW?

@popcornmix found out why HW deinterlace didn't work on RPi and this looks like a genuine bug in the filter patches:
https://github.com/popcornmix/xbmc/commit/77a2e061a1c3ace847ec96a38a47c366633e8396

I've added that commit to the drmprime-filter patchset, if it causes issues on AW I can move it to the RPi patchset

**Comment by jernejsk** [comment]
Will do.

**Comment by HiassofT** [comment]
I've moved the additional fix from drmprime-filters to RPi as it broke HW deinterlace on AW.

So non-RPi patches are back to before

**Comment by jernejsk** [comment]
Do you mind update Kodi again? https://github.com/xbmc/xbmc/pull/25467 was merged, which is important for new AW/RK v4l2_request implementation.

**Comment by HiassofT** [comment]
@jernejsk done - and I dropped the local PR25467 patch from the ffmpeg PR

**Review by knaerzche — APPROVED** [review]

**Pull request merged**
