### PR TITLE
Add kernel options for Kubernetes K3s

### LINKED ISSUE #6098: [Feature request] kernel options to allow Kubernetes K3s
As Docker is already available on LibreELEC (through the add-on), I investigated if it was possible to run [k3s](https://k3s.io/) (lightweight Kubernetes distribution).
My intention is to make my LibreELEC machine part of a self-hosted k3s cluster. It would take advantage of the power and capabilities of the machine to run some self-hosted services.

I managed to make it run (currently with some dirty hacks). See https://github.com/k3s-io/k3s/issues/4859

But I had to recompile LibreELEC, after adding several kernel options, on branch libreelec-10.0.

Here are the needed kernel options :

-  CONFIG_CGROUP_PIDS
-  CONFIG_USER_NS
-  CONFIG_NETFILTER_XT_MARK
-  CONFIG_NETFILTER_XT_CONNMARK
-  CONFIG_NETFILTER_XT_TARGET_CONNMARK
-  CONFIG_NETFILTER_XT_TARGET_MARK
-  CONFIG_NETFILTER_XT_TARGET_NFLOG
-  CONFIG_NETFILTER_XT_MATCH_COMMENT
-  CONFIG_NETFILTER_XT_MATCH_LIMIT
-  CONFIG_NETFILTER_XT_MATCH_MARK
-  CONFIG_NETFILTER_XT_MATCH_MULTIPORT
-  CONFIG_NETFILTER_XT_MATCH_PHYSDEV
-  CONFIG_NETFILTER_XT_MATCH_STATISTIC
-  CONFIG_IP_SET
-  CONFIG_IP_VS
-  CONFIG_IP_VS_RR
-  CONFIG_IP_VS_WRR
-  CONFIG_IP_VS_SH
-  CONFIG_BRIDGE_VLAN_FILTERING
-  CONFIG_VXLAN

I also had to workaround the fact that the root filesystem is a read-only squashfs, but I understand it's certainly by design to allow easier upgrades of LE.

NB : I did that on an amd64 machine, but it would probably work on most other architectures too : k3s also supports armhf and arm64

### PR DESCRIPTION
**Pull request by mossroy**
They are necessary to let k3s work on LibreElec.

Fixes #6098

### CODE REVIEW

**Comment by mossroy** [comment]
I've tested these kernel options on amd64, on libreelec-10.0 branch (kernel 5.10.54). I can create a separate PR for that branch.

I could not test on master branch (kernel 5.15.5), on which this PR is based on, because Kodi currently crashes on start on master, at least with https://test.libreelec.tv/LibreELEC-Generic.x86_64-11.0-nightly-20220108-00c51c7.ova. It's probably #6079

If this is approved, the same options should probably be applied for all other platforms (I can update the PR for that)

**Comment by heitbaum** [comment]
Hi @mossroy, 

If (big IF) a pull request like this was to be considered for LE master - you would need/want the PR to include the K3s bits and pieces including addon / ... Even for your own use (if you are using your media player in this way) - I would suggest you add the K3s addon to your fork - allowing you to maintain this as a package.

I haven't reviewed this pull request in itself; but sharing the previous conversations around this. 

References:
- https://forum.libreelec.tv/thread/23377-vxlan-support-in-kernel/
- #5061
- #5062

**Comment by chewitt** [comment]
@mossroy Our long-standing approach for this kind of "not core LE/Kodi" request is to have people spin up their own fork containing the changes, with BUILDER_NAME set so we can track usage in project stats, and make the custom image(s) and any related bits available and supported via the forums. In time, if we see the images/capabilities are popular with users we will be happy to receive a PR and absorb the changes. If we see low use we've avoided "the death of a thousand cuts" that comes with adding features that few people will use, and the forums still provide a route for interested users to get images and support.

So thanks for the PR, but I'm going to close it for now. We look forward to seeing an active support thread and perhaps a tools-addon for K8 users appearing in the forums. Thanks.

**Comment by mossroy** [comment]
Thanks for your feedback.

Even if it's disappointing, I understand and respect this point of view.

**Pull request closed without merging**
