### PR TITLE
mariadb: switch from mysql to mariadb

### PR DESCRIPTION
**Pull request by InuSasha**
to switch build with mariadb client, change the KODI_MYSQL_SUPPORT to "mariadb" in distribute/LibreELEC/option.
per default mysql is used.

actual, it is only build tested. (Generic & RPi2)
but i want to backport it to LE8.2.2, for real life testing at home (for same weeks).

when testing is successful, i pr the kodi changes, upstream.

(nice side-affect: no boost for base image needed)

Test ToDos:
- [x] Real-life test on 8.2.2 for min. 2 weeks (with mariadb server)
- [x] Dev-test against MySQL (5.7.20)
  - [x] incl. TLS
- [x] Dev-Test against  MariaDB (10.1.26)
  - [x] incl. TLS

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Can the Kodi MariaDB patch be sent upstream?

**Comment by InuSasha** [comment]
@MilhouseVH possible, yes. (https://github.com/InuSasha/xbmc/tree/feature/mariadbclient)
But i want same runtime test, before pr. 

please add wip falg and so

**Comment by lrusak** [comment]
This would be great to remove boost. Do you you have a mariadb package as well? If this works I'd rather do a hard switch to mariadb rather than make it a config option. We have to make sure that tls connections still work with mariadb as that was the whole reason we updated mysql to the version with boost

**Comment by InuSasha** [comment]
@lrusak 
the mariadb-client library package is included.
i see no reason for the full client/server package, if we only use the client library.

ok, i add an tls-test to the todo list

i prefer the config option, till KODI is official supporting mariadb. (maybe after my pr, or not) 

PS: i do not see the typo... blind or non-native ;)

**Comment by InuSasha** [comment]
kodi patch send upstream https://github.com/xbmc/xbmc/pull/13318

**Comment by MilhouseVH** [comment]
Thanks!

**Comment by sopparus** [comment]
Connector/C 3.0.3 is out with a ssl reconnect fix that might help in kodi

**Comment by InuSasha** [comment]
synced with upstream PR.
mariadb client is working since 23 days on 8.2.x :)

**Comment by chewitt** [comment]
upstream support was merged :)

**Comment by InuSasha** [comment]
i update the pr and switch to maria as default :)

**Comment by InuSasha** [comment]
* switched to mariadb as default (mysql can removed later)
* updated to merged version of kodi PR
* all commits squashed.
* the mariadb patch, is also merged upstream.

good to go.

**Comment by MilhouseVH** [comment]
Ideas? https://forum.kodi.tv/showthread.php?tid=298462&pid=2704252#pid2704252

**Comment by InuSasha** [comment]
Solution is to set `SET SESSION query_cache_type = OFF;` per connection for build against MariaDB client and used MySQL-DB

**Comment by MilhouseVH** [comment]
My only concern is that the query cache isn't a problem with older versions of MySQL Server and MariaDB connector.

My installation has MySQL Server 5.5.21 with the query cache enabled, and this works fine with the MariaDB connector in which case this might be a problem with only a small sub-set of MySQL Server versions (possibly even just the version used by the forum user, 5.7.19, ie. it's a bug in this particular release and the correct solution is to upgrade to 5.7.20, or manually disable query caching in the server config).

Clobber the query cache for all connections regardless of backend server type or version may have performance implications on systems with a working query cache, so if possible I'd like to understand more about this problem such as why it affects some servers but not others.

The defaults for my MySQL 5.5.21 server are:
```
> SHOW VARIABLES LIKE 'version';
'version', '5.5.21'
> SHOW VARIABLES LIKE 'have_query_cache';
'have_query_cache', 'YES'
> SHOW VARIABLES LIKE 'query_cache_size';
'query_cache_size', '0'
> SHOW VARIABLES LIKE 'query_cache_type';
'query_cache_type', 'ON'
```
A `query_cache_size` of `0` means that query caching is [disabled by default](https://dev.mysql.com/doc/refman/5.7/en/query-cache-configuration.html).

However I've manually configured:
```
query_cache_size = 64M
query_cache_limit = 16M
```
and this is working fine with the MariaDB Connector.

If this problem affects only MySQL 5.7.19 then the solution is easy: do nothing. :)

**Pull request merged**
