### PR TITLE
init: pre-create /dev/console

### PR DESCRIPTION
**Pull request by lrusak**
I think I got this right, thanks @stefansaraev

### CODE REVIEW

**Comment by stefansaraev** [comment]
yep. that's it in general. guess you did not runtime tested it yet, because you have a gzipped initramfs now, and your linux defconfigs dont have CONFIG_INITRAMFS_COMPRESSION_GZIP :)

or just remove "| gzip"..

**Comment by lrusak** [comment]
fixed thanks :)

**Comment by stefansaraev** [comment]
try again ;)

**Comment by lrusak** [comment]
I don't know what you're talking about ;)

**Comment by stefansaraev** [comment]
ok. github just refreshed and now | gzip is gone.

for a runtime test:  add "progress" as a boot parameter. if you see text printed while booting - it works.

**Comment by stefansaraev** [comment]
oh. you should also remove project specific linux devconsole patches.

http://sprunge.us/HcQf

**Comment by lrusak** [comment]
done, thanks

**Comment by MilhouseVH** [comment]
Seems OK on Generic/RPi/RPi2 - thanks.

**Comment by lrusak** [comment]
merge?

**Pull request merged**
