### PR TITLE
linux (NXP iMX6): enable docker options

### PR DESCRIPTION
**Pull request by heitbaum**
I have run tested this.

### CODE REVIEW

**Comment by CvH** [comment]
add to kernel_options ?

**Comment by heitbaum** [comment]
> add to kernel_options ?

Probably. Will need to review all the net stuff ( _CLS too ) - and make consistent. Identified a 6.2 kernel change error https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/?id=40cab44b9089 yesterday with retpoline - but noted the configs are different across all too. Not one for today though.

**Review by sm4rty-github — CHANGES_REQUESTED** [review]
ec 29 18:31:16 LibreWBQ dockerd[1310]: time="2022-12-29T18:31:16.983170353Z" level=info msg="[core] [Channel #1] Channel Connectivity change to READY" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:16.999721931Z" level=info msg="[core] [Channel #4] Channel created" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:16.999951236Z" level=info msg="[core] [Channel #4] original dial target is: \"unix:///var/run/docker/containerd/containerd.sock
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.000526496Z" level=info msg="[core] [Channel #4] parsed dial target is: {Scheme:unix Authority: Endpoint:var/run/docker/conta
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.000730804Z" level=info msg="[core] [Channel #4] Channel authority set to \"localhost\"" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.001423050Z" level=info msg="[core] [Channel #4] Resolver state updated: {\n  \"Addresses\": [\n    {\n      \"Addr\": \"/var
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.001865661Z" level=info msg="[core] [Channel #4] Channel switches to new LB policy \"pick_first\"" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.002632231Z" level=info msg="[core] [Channel #4 SubChannel #5] Subchannel created" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.003203492Z" level=info msg="[core] [Channel #4 SubChannel #5] Subchannel Connectivity change to CONNECTING" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.003751423Z" level=info msg="[core] [Channel #4 SubChannel #5] Subchannel picks a new address \"/var/run/docker/containerd/co
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.003752423Z" level=info msg="[core] [Channel #4] Channel Connectivity change to CONNECTING" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.006347762Z" level=info msg="[core] [Channel #4 SubChannel #5] Subchannel Connectivity change to READY" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.006752378Z" level=info msg="[core] [Channel #4] Channel Connectivity change to READY" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.016977421Z" level=info msg="[core] [Channel #7] Channel created" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.017668001Z" level=info msg="[core] [Channel #7] original dial target is: \"unix:///var/run/docker/containerd/containerd.sock
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.018350581Z" level=info msg="[core] [Channel #7] parsed dial target is: {Scheme:unix Authority: Endpoint:var/run/docker/conta
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.019234137Z" level=info msg="[core] [Channel #7] Channel authority set to \"localhost\"" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.020251009Z" level=info msg="[core] [Channel #7] Resolver state updated: {\n  \"Addresses\": [\n    {\n      \"Addr\": \"/var
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.020829603Z" level=info msg="[core] [Channel #7] Channel switches to new LB policy \"pick_first\"" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.021847142Z" level=info msg="[core] [Channel #7 SubChannel #8] Subchannel created" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.022120774Z" level=info msg="[core] [Channel #7 SubChannel #8] Subchannel Connectivity change to CONNECTING" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.022385408Z" level=info msg="[core] [Channel #7 SubChannel #8] Subchannel picks a new address \"/var/run/docker/containerd/co
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.022440067Z" level=info msg="[core] [Channel #7] Channel Connectivity change to CONNECTING" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.027568756Z" level=info msg="[core] [Channel #7 SubChannel #8] Subchannel Connectivity change to READY" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.027967039Z" level=info msg="[core] [Channel #7] Channel Connectivity change to READY" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.031870216Z" level=info msg="[graphdriver] trying configured driver: overlay2"
Dec 29 18:31:17 systemd[1]: storage-.kodi-userdata-addon_data-service.system.docker-docker-overlay2-check\x2doverlayfs\x2dsupport3049048151-merged.mount: Deactivated successfully.
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.210190476Z" level=info msg="Loading containers: start."
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.246160956Z" level=warning msg="Running iptables --wait -t nat -L -n failed with message: `modprobe: FATAL: Module ip_tables
Dec 29 18:31:17 systemd[1]: storage-.kodi-userdata-addon_data-service.system.docker-docker-overlay2-metacopy\x2dcheck3321942693-merged.mount: Deactivated successfully.
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.901720582Z" level=info msg="[core] [Channel #4] Channel Connectivity change to SHUTDOWN" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.902004213Z" level=info msg="[core] [Channel #4 SubChannel #5] Subchannel Connectivity change to SHUTDOWN" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.902181857Z" level=info msg="[core] [Channel #4 SubChannel #5] Subchannel deleted" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.902311174Z" level=info msg="[core] [Channel #4] Channel deleted" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.902881436Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.906538643Z" level=info msg="stopping healthcheck following graceful shutdown" module=libcontainerd
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.906830939Z" level=info msg="[core] [Channel #1] Channel Connectivity change to SHUTDOWN" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.907153899Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel Connectivity change to SHUTDOWN" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.907353540Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel deleted" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.907494856Z" level=info msg="[core] [Channel #1] Channel deleted" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.906641297Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.909194976Z" level=info msg="[core] [Channel #7 SubChannel #8] Subchannel Connectivity change to IDLE" module=grpc
Dec 29 18:31:17 dockerd[1310]: time="2022-12-29T18:31:17.910015206Z" level=info msg="[core] [Channel #7] Channel Connectivity change to IDLE" module=grpc
Dec 29 18:31:18 dockerd[1310]: failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed
Dec 29 18:31:18 dockerd[1310]: iptables v1.8.8 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Dec 29 18:31:18 dockerd[1310]: Perhaps iptables or your kernel needs to be upgraded.
Dec 29 18:31:18 dockerd[1310]:  (exit status 3)
Dec 29 18:31:18 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 18:31:18 systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 29 18:31:18 systemd[1]: docker.service: Consumed 2.376s CPU time.

**Comment by lrusak** [comment]
Please check with: https://github.com/moby/moby/blob/master/contrib/check-config.sh

Might want to check all configs really.

**Comment by sm4rty-github** [comment]
`info: reading kernel config from /proc/config.gz ...[m

Generally Necessary:
- cgroup hierarchy [nonexistent??[m
    [33m(see https://github.com/tianon/cgroupfs-mount)[m
- CONFIG_NAMESPACES [missing]
- CONFIG_NET_NS [missing]
- CONFIG_PID_NS [missing]
- CONFIG_IPC_NS [missing]
- CONFIG_UTS_NS [missing]
- CONFIG_CGROUPS [enabled]
- CONFIG_CGROUP_CPUACCT [missing]
- CONFIG_CGROUP_DEVICE [missing]
- CONFIG_CGROUP_FREEZER [missing]
- CONFIG_CGROUP_SCHED [missing]
- CONFIG_CPUSETS [missing]
- CONFIG_MEMCG [missing]
- CONFIG_KEYS [enabled]
- CONFIG_VETH [missing]
- CONFIG_BRIDGE [enabled]
- CONFIG_BRIDGE_NETFILTER [enabled (as module)[m
- CONFIG_IP_NF_FILTER [missing]
- CONFIG_IP_NF_TARGET_MASQUERADE [missing]
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE [missing]
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK [missing]
- CONFIG_NETFILTER_XT_MATCH_IPVS [missing]
- CONFIG_NETFILTER_XT_MARK [missing]
- CONFIG_IP_NF_NAT [missing]
- CONFIG_NF_NAT [missing]
- CONFIG_POSIX_MQUEUE [missing]
- CONFIG_CGROUP_BPF [enabled]

Optional Features:
- CONFIG_USER_NS [missing]
- CONFIG_SECCOMP [enabled]
- CONFIG_SECCOMP_FILTER [enabled]
- CONFIG_CGROUP_PIDS [missing]
- CONFIG_MEMCG_SWAP [missing]
    [1;30m(cgroup swap accounting is currently enabled)[m
- CONFIG_BLK_CGROUP [missing]
- CONFIG_BLK_DEV_THROTTLING [missing]
- CONFIG_CGROUP_PERF [missing]
- CONFIG_CGROUP_HUGETLB [missing]
- CONFIG_NET_CLS_CGROUP [missing]
- CONFIG_CGROUP_NET_PRIO [missing]
- CONFIG_CFS_BANDWIDTH [missing]
- CONFIG_FAIR_GROUP_SCHED [missing]
- CONFIG_RT_GROUP_SCHED [missing]
- CONFIG_IP_NF_TARGET_REDIRECT [missing]
- CONFIG_IP_VS [missing]
- CONFIG_IP_VS_NFCT [missing]
- CONFIG_IP_VS_PROTO_TCP [missing]
- CONFIG_IP_VS_PROTO_UDP [missing]
- CONFIG_IP_VS_RR [missing]
- CONFIG_SECURITY_SELINUX [missing]
- CONFIG_SECURITY_APPARMOR [missing]
- CONFIG_EXT4_FS [enabled]
- CONFIG_EXT4_FS_POSIX_ACL [enabled]
- CONFIG_EXT4_FS_SECURITY [enabled]
- Network Drivers:
  - "[overlay]":
    - CONFIG_VXLAN [missing]
    - CONFIG_BRIDGE_VLAN_FILTERING [missing]
      Optional (for encrypted networks):
      - CONFIG_CRYPTO [enabled]
      - CONFIG_CRYPTO_AEAD [enabled]
      - CONFIG_CRYPTO_GCM [enabled]
      - CONFIG_CRYPTO_SEQIV [enabled]
      - CONFIG_CRYPTO_GHASH [enabled]
      - CONFIG_XFRM [missing]
      - CONFIG_XFRM_USER [missing]
      - CONFIG_XFRM_ALGO [missing]
      - CONFIG_INET_ESP [missing]
  - "[ipvlan]":
    - CONFIG_IPVLAN [missing]
  - "[macvlan]":
    - CONFIG_MACVLAN [missing]
    - CONFIG_DUMMY [missing]
  - "[ftp,tftp client in container]":
    - CONFIG_NF_NAT_FTP [missing]
    - CONFIG_NF_CONNTRACK_FTP [missing]
    - CONFIG_NF_NAT_TFTP [missing]
    - CONFIG_NF_CONNTRACK_TFTP [missing]
- Storage Drivers:
  - "[aufs]":
    - CONFIG_AUFS_FS [missing]
  - "[btrfs]":
    - CONFIG_BTRFS_FS [enabled (as module)[m
    - CONFIG_BTRFS_FS_POSIX_ACL [enabled]
  - "[devicemapper]":
    - CONFIG_BLK_DEV_DM [missing]
    - CONFIG_DM_THIN_PROVISIONING [missing]
  - "[overlay]":
    - CONFIG_OVERLAY_FS [enabled (as module)[m
  - "[zfs]":
    - /dev/zfs [missing]
    - zfs command [missing]
    - zpool command [missing]

Limits:
- /proc/sys/kernel/keys/root_maxkeys [1000000]

`

**Comment by heitbaum** [comment]
Updated based on docker check-config.sh
**missing** have purposely been left disabled.


```
cubox:~ # ./check-config.sh 
info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: nonexistent??
    (see https://github.com/tianon/cgroupfs-mount)
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_NETFILTER_XT_MARK: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_POSIX_MQUEUE: enabled
- CONFIG_CGROUP_BPF: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_SECCOMP_FILTER: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_MEMCG_SWAP: missing
    (cgroup swap accounting is currently enabled)
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_SECURITY_SELINUX: missing
- CONFIG_SECURITY_APPARMOR: missing
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
    - CONFIG_BRIDGE_VLAN_FILTERING: enabled
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: enabled
      - CONFIG_CRYPTO_SEQIV: enabled
      - CONFIG_CRYPTO_GHASH: enabled
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled
      - CONFIG_XFRM_ALGO: enabled
      - CONFIG_INET_ESP: enabled
  - "ipvlan":
    - CONFIG_IPVLAN: enabled (as module)
  - "macvlan":
    - CONFIG_MACVLAN: enabled (as module)
    - CONFIG_DUMMY: enabled (as module)
  - "ftp,tftp client in container":
    - CONFIG_NF_NAT_FTP: enabled (as module)
    - CONFIG_NF_CONNTRACK_FTP: enabled (as module)
    - CONFIG_NF_NAT_TFTP: enabled (as module)
    - CONFIG_NF_CONNTRACK_TFTP: enabled (as module)
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
    - CONFIG_BTRFS_FS_POSIX_ACL: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000
```

**Comment by heitbaum** [comment]
``` 
LibreELEC (heitbaum): devel-20230102061651-98169f9 (iMX6.arm)
cubox:~ # docker run hello-world 
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
9b157615502d: Pull complete 
Digest: sha256:c77be1d3a47d0caf71a82dd893ee61ce01f32fc758031a6ec4cf1389248bb833
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm32v7)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

**Comment by heitbaum** [comment]
```
cubox:~ # docker run ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
c38006c9acc4: Pull complete 
Digest: sha256:27cb6e6ccef575a4698b66f5de06c7ecd61589132d5a91d098f7f3f9285415a9
Status: Downloaded newer image for ubuntu:latest
cubox:~ # docker run -it ubuntu bash
root@60662ad60542:/# date
Mon Jan  2 06:55:28 UTC 2023
root@60662ad60542:/# apt update
Get:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease [270 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease [114 kB]                                                        
Get:3 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease [99.8 kB]                                                     
Get:4 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease [110 kB]                                                       
Get:5 http://ports.ubuntu.com/ubuntu-ports jammy/restricted armhf Packages [13.3 kB]                                               
Get:6 http://ports.ubuntu.com/ubuntu-ports jammy/main armhf Packages [1701 kB]
…
```

**Review by chewitt — APPROVED** [review]

**Pull request merged**
