### PR TITLE
remove and rework kodi patches

### PR DESCRIPTION
**Pull request by lrusak**
@MilhouseVH please test this, it would be nice to remove some of these patches

apparently the minimum sample rate issue may be fixed in 4.9+ kernel

thanks @fritsch for all the help here.

`/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq` seems to be working just fine with p-state now.

### CODE REVIEW

**Comment by lrusak** [comment]
@MilhouseVH did you get to test this at all?

**Comment by MilhouseVH** [comment]
I've had this in my build since #0114 and no complaints. I've done a quick test on Intel NUC with clean .kodi and it correctly defaults to VAAPI. Can't test Revo right now, unfortunately.

**Comment by lrusak** [comment]
@MilhouseVH this was missed as a backport, should we get this for 8.0?

**Comment by MilhouseVH** [comment]
I've not had any issues reported so yes, if there's time. Otherwise maybe leave for 8.1.

**Pull request merged**
