### PR TITLE
webgrabplus: initial addon

### PR DESCRIPTION
**Pull request by awiouy**
@CvH 

As promised. This is the best I could think of...

This Frankenstein is a combination of version 1.1.1 (edited mdb, rex, WebGrab+Plus.config.xml), beta 2 (WebGrab+Plus.exe xmltv.dll), siteini.pack, and runtime output (guide.xml).

It would be appropriate to contact the author, to kindly ask him for versioned and operational zip files of wg++ and siteini (ie autonomous code, working configurations, etc.), but this is out of the scope I had given to my endeavour.

I will add a loop (in the webgrabplus.start or in default.py) if you agree with the current construction.
@

### CODE REVIEW

**Comment by chewitt** [comment]
@awiouy - This needs a different packaging approach. I'd suggest you merge things in new git repo and grab/unpack an archive of that repo at build time. Then the add-on only needs the usual skeleton content, not 919 files.

**Comment by awiouy** [comment]
Thank you for the feedback, I applied your recommendations, which make sense, indeed

**Comment by piotrasd** [comment]
not better move that to docker ?

**Comment by awiouy** [comment]
Better is in the eye of the beholder ;)
In so far as I could understand, some users requested a native implementation.
Maybe a docker implementation would be easier to maintain, at least for me :D

**Comment by piotrasd** [comment]
yes exactly... i dont understand either, maybe only 1 point, there is no gui manager for docker now and many afraid command line :) 

I have even tvheadend in docker because is possible use hardwared device in container
so my repo getting source from master everyday and autobuild latest tvheadend version
i can easy also switch from stable to dev. (and i dont care of depending libs in system etc)

Here more on forum (including GUI manager, some screenshot inside - like i have on my NAS)
https://forum.libreelec.tv/thread-982.html

**Comment by CvH** [comment]
@piotrasd docker is not supported at every platform + there is no gui yet to handle docker, if all this is "fixed" there would be not problem to move this stuff to docker especially for software which is basically a mess like this.

**Comment by piotrasd** [comment]
@CvH ok i didnt checked before that addon is for all platform inluding ARM, no problem

**Comment by stefansaraev** [comment]
nice.

may I ask. why is this one a service ?

**Comment by awiouy** [comment]
Thank you for your feedback, stefansaraev.
As for the service, it is work in progress.
I have no clue about WebGrab+Plus, but I gather it should run periodically. I am therefore trying to find a way to do that (loop in webgrabplus.sh, system.d timer, cron, etc).
I welcome any suggestions

**Comment by awiouy** [comment]
I am done:
I have added xmltv_time_correct, and webgrabplus.start is run at system startup and subsequently every 6 hours.
@chewitt would you please be so kind to create an icon for this, tia.

**Comment by awiouy** [comment]
Don't merge... A user detected a problem I want to fix

**Comment by awiouy** [comment]
User feedback is positive.
Ready to merge.

**Pull request merged**
