### PR TITLE
alsautils: depend on ncurses

### PR DESCRIPTION
**Pull request by awiouy**

### CODE REVIEW

**Comment by awiouy** [comment]
This builds for RPi2/arm

**Comment by chewitt** [comment]
@awiouy this was already published so the tools package needs to be bumped too

**Comment by escalade** [comment]
This removes netbsd-curses completely, I don't think that's what you wanted to do :)

**Comment by lrusak** [comment]
@escalade it really is what we want to do :) why do we need netbsd-curses when we have ncurses in LibreELEC-7.0 ?

**Comment by escalade** [comment]
Doh! My bad, forgot 7.0 still has ncurses.

**Comment by awiouy** [comment]
multimedia-tools is bumped

**Pull request merged**
