### PR TITLE
linux: update to linux-4.13.6

### PR DESCRIPTION
**Pull request by MilhouseVH**
Merge target: ~4.13.4~ 4.13.6

4.13.1 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.1
4.13.2 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.2
4.13.3 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.3
4.13.4 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.4
4.13.5 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.5
4.13.6 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.6

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Due to the ongoing problems with the Kodi forum I'd rather wait until we're sure we've had no reported issues before merging this - pushing the target out to 4.13.6, hopefully the Kodi server will have been found by then.

**Comment by polojoe** [comment]
Could you please publish a changelog of your testbuilds in the meantime?
Maybe on milhouse.libreelec.tv ?

**Comment by MilhouseVH** [comment]
OK, I've added temporary release threads on the LibreELEC forum:

[RPi/RPi2](https://forum.libreelec.tv/thread/10151-temporary-changelog-thread-for-milhouse-rpi-rpi2-builds-kodi-18) thread
[Generic:](https://forum.libreelec.tv/thread/10152-temporary-changelog-thread-for-milhouse-generic-builds-kodi-18) thread

**Comment by MilhouseVH** [comment]
This is good to go.

**Comment by lrusak** [comment]
Thanks @MilhouseVH!

**Comment by the-dreamer** [comment]
i have updated my build (from master) and new kernel 4.13 is included. My last build was from mid/end August was with 4.12 kernel. 
Now i have following crash in kernel regarding color range: 
[   15.028452] [drm:pipe_config_err] *ERROR* mismatch in limited_color_range (expected 1, found 0)
[   15.028462] pipe state doesn't match!

full dmesg from boot: http://sprunge.us/NKWi

Color behaviour in kodi is also wrong. dark screen when limited color enabled and brighter screen when disabled.

**Comment by MilhouseVH** [comment]
```
[    0.000000] Kernel command line: root=/dev/ram0 rdinit=/init usbcore.autosuspend=-1 BOOT_IMAGE=/KERNEL boot=LABEL=System disk=LABEL=Storage quiet initrd=/edid.cpio drm.edid_firmware=HDMI-A-3:edid/edid.bin video=HDMI-A-3:1280x720@50D
```

Can you try without your custom edid settings and see if the problem goes away?

Do you have the same issue with the latest build from this [thread](https://forum.kodi.tv/showthread.php?tid=298462)?

**Comment by the-dreamer** [comment]
reverting the rework of fritch patch removes the crash. So Kernel update is not the reason.
With your build i have the same crash: http://sprunge.us/AECh
Please ignore the boot cmd line for EDID due missing patch in your image: https://patchwork.freedesktop.org/patch/176284/ which should land to linux with 4.15. My Custom edid line has no affect in your build.

**Comment by MilhouseVH** [comment]
I'm really not sure why this is causing a problem for you but none of the other 100 or so people testing these builds, that's very odd.

**Comment by the-dreamer** [comment]
First i thougth the patch is the reason for the dark kodi UI but have read in forum that this is an issue in latest kodi (limited color in video is fixed since 09.10). So maybe it is working for all people but they have also the crash in dmesg. What is the intention of the patch rework? in kernel 4.13.0 it is working without rework. for the latest kernel i need to see it at home.

**Comment by MilhouseVH** [comment]
> What is the intention of the patch rework? in kernel 4.13.0 it is working without rework. for the latest kernel i need to see it at home.

I'll be honest - I can't remember exactly why the passthrough patch needed to be updated. The updated version is added with 4.13.2, and my hazy recollection is that the previous version no longer builds with 4.13.2+ (but it had been fine with 4.13.0 and 4.13.1).

The version of the patch we have now came about after some collaboration with @fritsch on Team Kodi Slack, and he has now posted the patch to the intel-gfx mailing list: https://lists.freedesktop.org/archives/intel-gfx/2017-September/138971.html

Pinging @fritsch for an opinion if this patch is now causing a problem.

**Comment by the-dreamer** [comment]
with reverted patch rework it seems to run on 4.13.9. I could also build the kernel without patch rework: http://sprunge.us/KMEN

commit c41021650de7d33f3938f808f3ed7e7a62171c93 (HEAD -> master)
Author: root <root@localhost>
Date:   Tue Oct 24 13:53:54 2017 +0200

    Revert "linux: update full range patch from fritsch"
    
    This reverts commit 3d76b5dca1e52b0836ff60a4a732e76f8297e233.

but as you said, fritch can tell more i think.

**Comment by fritsch** [comment]
Might be possible. Revert the updated patch for now and fall back to the older version. Will perhaps find time around christmas looking into it.

**Comment by MilhouseVH** [comment]
Many thanks, I've reverted the updated patch in #2118.

@the-dreamer please confirm if tonight's release #1024 is better for you (once it becomes available) - thanks.

**Pull request merged**
