### PR TITLE
scripts/build: use MinSizeRel cmake build type

### PR DESCRIPTION
**Pull request by lrusak**
This builds with -Os instead of -O3/-O2

### CODE REVIEW

**Comment by MilhouseVH** [comment]
What about the hard-coded `-DCMAKE_BUILD_TYPE=Release` in:

mysql: https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/databases/mysql/package.mk#L80
llvm: https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/lang/llvm/package.mk#L62
taglib: https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/audio/taglib/package.mk#L34

Anything to be concerned about?

**Comment by stefansaraev** [comment]
from cmake docs - release is default if not specified otherwise. MinSizeRel (whenever used at all) doesnt give you much saving imo.

**Comment by hudokkow** [comment]
Also make sure binaries are being stripped. https://github.com/xbmc/xbmc/pull/10595
I assumed `-DCMAKE_BUILD_TYPE=Release` stripped by default and it doesn't.

**Comment by stefansaraev** [comment]
ouch. I assumed something like https://github.com/stefansaraev/TB/blob/master/scripts/build#L169-L171 is already in LE. but it is not...

**Comment by lrusak** [comment]
@stefansaraev either you can PR it or I can for you ;)

**Comment by lrusak** [comment]
pushed some commits so that CMAKE_BUILD_TYPE isn't defined in the package.mk

**Comment by lrusak** [comment]
any objections? @MilhouseVH what's your verdict?

**Comment by MilhouseVH** [comment]
I'll need to re-try `DEBUG=yes` builds as it was failing on MySQL. Will give it a go overnight.

**Comment by MilhouseVH** [comment]
Unfortunately this still fails to build MySQL with `DEBUG=yes` - tail end of build log: http://sprunge.us/KQBc. It's the same failure on RPi and RPi2. With `DEBUG=no` MySQL builds OK.

**Comment by lrusak** [comment]
@MilhouseVH can I see the CMakeCache.txt for mysql?

**Comment by MilhouseVH** [comment]
cat ./.x86_64-linux-gnu/CMakeCache.txt | pastebinit
http://sprunge.us/VGCS

cat ./.x86_64-libreelec-linux-gnu/CMakeCache.txt | pastebinit
http://sprunge.us/EhUX

**Comment by lrusak** [comment]
thanks can you try adding `-Wno-maybe-uninitialized` to the `CFLAGS` and `CXXFLAGS`

**Comment by MilhouseVH** [comment]
I tried: http://sprunge.us/dRYG which created http://sprunge.us/KJCg but still have the same build error.

Perhaps I messed up the change, did you have something else in mind? If so can you provide a patch? Thanks.

**Comment by MilhouseVH** [comment]
@lrusak: any further ideas? I've hit a crash that would benefit from a debug build, so not being able to create them is a bit of an issue now. Alternative is to stop testing this PR...

**Comment by lrusak** [comment]
dropped the mysql commit for now. This should be able to be merged now.

I'll look into the issue soon.

**Pull request merged**
