### PR TITLE
zlib: add neon optimizations

### PR DESCRIPTION
**Pull request by antonlacon**
This introduces neon optimizations to zlib. The patches were pulled from zlib's pull requests, or are what are applied to Fedora Core's zlib build for arm. Versions of these patches are included in chromium/chrome/android for, I believe, almost a year. I believe I pulled all of the relevant patches (there are a couple more that involve armv8a and/or its crc extension).

Patches apply and build for me on an RPi3. The resulting image also works for me. What I'm not sure about is whether I've edited the package.mk correctly. Other testing welcome, too.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks. One of the patches seems to be intended for zlib-ng. Given that the upstream zlib doesn't seem to be very active, would it make more sense to switch to zlib-ng?

**Comment by antonlacon** [comment]
These patches should be in zlib-ng already, yes. I believe chromium passed along their x86 related optimizations as well.

Zlib upstream isn't completely dead. They were asking the chromimum dev for benchmarks last week (zlib's issue `#346`).

**Comment by CvH** [comment]
the benchmarks, that are sadly all done with old (2015-2016ish) zlib-ng and zlib versions, are not clearly in favor of any implementation :/ guess we need to benchmark our self

**Comment by CvH** [comment]
@antonlacon any idea how to run an benchmark for this? It would be nice to know if there are improvements or not and if there is a difference between zlib-ng/zlib+patches

**Comment by HiassofT** [comment]
We already include arm/neon optimized versions of memcpy et al on RPi via arm-mem that benefit all software
https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/devel/arm-mem/package.mk
https://github.com/bavison/arm-mem/commits/master

So it would be good to get some real-world benchmark results on LE with and without this PR. It could well be that there's not much improvement

**Comment by antonlacon** [comment]
The author gave a talk last week on his efforts. These are the slides: https://events.linuxfoundation.org/wp-content/uploads/2017/11/Optimizing-Zlib-on-ARM-The-Power-of-NEON-Adenilson-Cavalcanti-ARM.pdf It has benchmarks between chromium's zlib and mainstream zlib. I believe it uses zlib-bench for benching (a perl script invoking minizip(?)). Numbers behind their graphs are here: https://docs.google.com/spreadsheets/d/1_rOPJ1AXCs1EGOiy_qtiSpeAgmJ6C9v1b_oMh4xODRo/edit#gid=1368959096

The patches here (discussed in said talk) are for chunk copy, neon-adler 32, and slide-hash (all require neon). They do not include the crc patches (requires armv8a). I believe zlib-ng has all of the patches, as its the same author behind the patches for chromium's, mainstream's, and zlib-ng's neon & crc efforts as near as I can tell. zlib-ng & chromium also have improvements for x86.

**Comment by CvH** [comment]
@antonlacon as the pdf states `Zlib users should consider moving to Chromium’s zlib` why should we use zlib-ng and not directly https://cs.chromium.org/chromium/src/third_party/zlib/ ? Maybe I miss here some info :)

**Comment by antonlacon** [comment]
I haven't advocated for zlib-ng. I've answered questions where I've been asked. Chromium's zlib would probably be a nice change, but I have no idea how to build/package it. What I've done is try to get some of their improvements they were trying to upstream attached as a patch here.

**Comment by CvH** [comment]
@antonlacon `but I have no idea how to build/package it` we have looked into it and have the same problem - doesn't looks like we can package it properly

btw chrome zlib has an bench tool https://chromium.googlesource.com/chromium/src/+/875ad5e3c08831f1efa91adade7fc350b1ef45bc
maybe we could reuse that to get some results?

**Comment by antonlacon** [comment]
I wrote a script for benchmarking on LE with what it has available. If you want to use it, minizip doesn't get built by default, (for me anyway), so I tacked it on as a dependency of kodi and built it. I ended up having to copy the resulting binaries over to the sd card as it wasn't in the image. Script is here: https://gist.github.com/antonlacon/9c36c0eb40c8e6ba6ba408e97d0a79cc

My results for Project Gutenberg's complete works of Mark Twain (about 16MB of html text), was a 3.6% speed up (-0.25s real) in compressing, and a 8% slowdown (+0.03s real) in decompressing, after averaging over 50 runs. It's one sample and type of file, so others may have different results. My shot in the dark guess is that invoking neon has a penalty larger than is realized with such a small number/size file to work with.

Test machine was a rpi3 running le-9 git from Aug 30th built for aarch32.

**Comment by MilhouseVH** [comment]
This is additional testing, using a build with miniunzip, with and without this PR.

1. `get-zips.sh` - download a bunch of test zips:
```
#!/bin/bash

OUTPUT=/storage/zip-samples
HOST="http://mirrors.kodi.tv/addons/leia"

mkdir -p "${OUTPUT}"

wget -q ${HOST}/addons.xml.gz -O- | gunzip -dc | xmlstarlet sel -t -v "addons/addon/extension/path" | \
while read -r path; do
  filename="$(basename "${path}")"
  echo "${filename}..."
  [ -f "${OUTPUT}/${filename}" ] || wget "${HOST}/${path}" -O "${OUTPUT}/${filename}"
done
```

2. `unzip.sh` - unzip each zip 100 times and record the time taken:
```
#!/bin/bash

ZIPS=/storage/zip-samples
INPUT=/tmp/input.zip
TMPDIR=/tmp/unzip

LOOPS=100

for zip in $(ls -1 ${ZIPS}); do
  rm -fr ${TMPDIR}
  mkdir -p ${TMPDIR}

  cp ${ZIPS}/${zip} ${INPUT}

  s=$(date +%s%N)
  for i in $(seq ${LOOPS}); do
    mkdir -p ${TMPDIR}/${i}
    miniunz ${INPUT} -d ${TMPDIR}/${i} >/dev/null
  done
  t=$(($(date +%s%N) - s))
  echo "$((t / 1000000)) ${zip}"
  rm -fr ${TMPDIR}
done
```

3. `compz.sh` - compare the timings with/without NEON:
```
#!/bin/bash

NEON=/storage/neon.dat
NONEON=/storage/noneon.dat

T1=0
T2=0
i=0
while read -r t1 f1; do
i=$((i+1))
[ $i -gt 5000 ] && break
  t2=$(grep " ${f1}$" ${NEON} | sed 's/^[[:space:]]*//g' | cut -d' ' -f1)
  f2=$(grep " ${f1}$" ${NEON} | sed 's/^[[:space:]]*//g' | cut -d' ' -f2)

  if [ -n "$1" ]; then
    show=n
    [ "$1" = "fast" -a ${t2} -lt ${t1} ] && show=y
    [ "$1" = "slow" -a ${t2} -gt ${t1} ] && show=y
  else
    show=y
  fi

  if  [ ${show} = y ]; then
    T1=$((T1 + t1))
    T2=$((T2 + t2))

    printf "%8d %8d %8d %s\n" ${t1} ${t2} $((t2 - t1)) "${f1}"
  fi
done < ${NONEON}

grep -qm1 "\.png$" "${NEON}" && ISPNG=1000 || ISPNG=1

dT1=$((T1 / 1000 / ISPNG))
dT2=$((T2 / 1000 / ISPNG))
dTx=$(((T2 - T1) / 1000 / ISPNG))

printf "%-13s: %8d %4d\n" "NEON DISABLED" $((T1 / ISPNG)) ${dT1}
printf "%-13s: %8d %4d\n" "NEON ENABLED" $((T2 / ISPNG)) ${dT2}
printf "%-13s: %8d %4d (%d%%)\n" "DIFFERENCE" $(((T2 - T1) / ISPNG)) ${dTx} $((((dT2 * 100) / dT1) - 100))

echo
echo "Positive time: NEON is slower"
echo "Negative time: NEON is faster"
```

Step 1: Run `get-zips.sh` to download the Leia add-on zip files (1,159 files, 1.9GB)
Step 2: Run `unzip.sh` and pipe the output to `/storage/noneon.dat` (when testing a build without this PR) and `/storage/neon.dat` (when testing with this PR)
Step 3: Run `compz.sh` to compare the results.


When testing on a RPi3+:
```
NEON DISABLED:  2442318 2442
NEON ENABLED :  2510719 2510
DIFFERENCE   :    68401   68 (2%)

Positive time: NEON is slower
Negative time: NEON is faster
```

which shows that enabling NEON results in slower decompression (2%, or 68 seconds over a ~41 minute run), confirming the previous results.

@hiassoft also created a testing addon [timepng](https://github.com/HiassofT/LibreELEC.tv/commit/03083efa80f3f4108c475750efca20c18d2b1ce5) which outputs the time taken to load a PNG (binary [here](http://www.horus.com/~hias/tmp/libreelec/tools.timepng-9.0.100.zip), symbolically linked to zlib).

With the following command
```
find /storage/.kodi/userdata/Thumbnails -name \*.png | xargs timepng | sort -n
```
I decoded 2632 PNG images, then compared the output with `compz.sh`:
```
NEON DISABLED:    38663   38
NEON ENABLED :    34291   34
DIFFERENCE   :    -4372   -4 (-11%)

Positive time: NEON is slower
Negative time: NEON is faster
```

which shows there is in fact an overall PNG decode benefit of 11% (4.3 second reduction) from the NEON optimisation.

So it's not entirely clear cut - the benefit lies somewhere between non-existant and small, while the additional code complexity/maintenance is quite significant.

There seems to be a general (but small, 2%) performance reduction when decoding ZIP addons (and skins etc.), and a small - but not insignificant - improvement (11%) when decoding PNGs.

On balance, adding a 3000 sloc patch when the benefit is not always clear (or at best, barely noticeable) may not be worth the risk and ongoing maintenance overhead (IMHO). It's clear there is some benefit, and ideally the NEON patches will be accepted upstream so that we don't have to maintain them,

**Comment by antonlacon** [comment]
Mothball this for LE 10? Hopefully positive developments would happen in zlib/zlib-ng/chromium's zlib.

**Comment by MilhouseVH** [comment]
Yes, I think that's probably the best option for now - hopefully things move forward upstream in zlib, but if not (and zlib is no longer maintained, or at a glacial pace) then maybe we can consider an alternative fork. The Chromium zlib is a pain to build, but maybe zlib-ng is a better alternative... Certainly worth keeping an eye on, and coming back to for LE10.

Thanks for taking the interest and starting the discussion!

**Comment by antonlacon** [comment]
Closing as it's been a year.

zlib has no movement.
zlib-ng has no tagged releases.
chromium-zlib buildsystem is still a mystery.

**Pull request closed without merging**
