### PR TITLE
inputstream.adaptive: update 20.3.6-Nexus to 20.3.7-Nexus

### PR DESCRIPTION
**Pull request by heitbaum**

### CODE REVIEW

**Comment by HiassofT** [comment]
This needs also a bento4 update - see https://github.com/xbmc/inputstream.adaptive/pull/1216

**Comment by heitbaum** [comment]
> This also needs a bento4 update - see [xbmc/inputstream.adaptive#1216](https://github.com/xbmc/inputstream.adaptive/pull/1216)

Which one do I pull in? Not the Omega-7?

- I have included bento4 in #7766

**Comment by heitbaum** [comment]
> This also needs a bento4 update - see [xbmc/inputstream.adaptive#1216](https://github.com/xbmc/inputstream.adaptive/pull/1216)

I just did a clean LE11 addon build with just inputstream.adaptive / no bento4 and built fine. Whereas building the LE12 fails without the bento4

**Comment by HiassofT** [comment]
the Nexus i.a version now also uses the 7-Omega Bento4 version, likely this is needed for the single session fix so we should also use that instead of the 6-Nexus one
https://github.com/xbmc/inputstream.adaptive/blob/Nexus/depends/common/bento4/bento4.txt

**Comment by heitbaum** [comment]
> the Nexus i.a version now also uses the 7-Omega Bento4 version, likely this is needed for the single session fix so we should also use that instead of the 6-Nexus one
> https://github.com/xbmc/inputstream.adaptive/blob/Nexus/depends/common/bento4/bento4.txt

👍 I’ve added it

**Comment by HiassofT** [comment]
thanks! :+1:

**Review by HiassofT — APPROVED** [review]

**Pull request merged**
