### PR TITLE
merge xml files during installation of kodi

### PR DESCRIPTION
**Pull request by lrusak**
I've wanted to do this for a while and this is the best I can come up with. Python is the easiest as I couldn't figure out an easy way to do it with xmlstarlet.

This script combines our global kodi xml files with the project/device specific ones. If there isn't one available it just uses the global xml file.

A couple things I've noticed:
1. The cputemp, gputemp lines weren't included in all devices when they should be
2. The cputemp, gputemp scripts need adjusting
3. Many of the files were redundant

### CODE REVIEW

**Comment by lrusak** [comment]
@MilhouseVH did you get a chance to take a look?

**Comment by MilhouseVH** [comment]
Not entirely sure that cputemp/gputemp is required in advancedsettings.xml for all projects, as RPi/RPi2 works fine without either.

Is the 3rd cputemp/gputemp commit required, as that's now covered by #1348 isn't it? I'd drop the 3rd commit, and then this can probably go in.

Otherwise it looks good,

**Comment by lrusak** [comment]
rebased and dropped the uneeded commit and drop cputemp/gputemp from RPi/RPi2

@vpeter4 is the cputemp/gputemp script needed for imx6? Please let me know if I need to adjust it.

**Comment by vpeter4** [comment]
Yes, cputemp is needed and it reads from _/sys/class/hwmon/hwmon0/temp1_input_.

**Comment by MilhouseVH** [comment]
@lrusak: Any more updates before this merges?

**Comment by MilhouseVH** [comment]
Wouldn't it be better to drop the check for `-n $DEVICES` and just use:
```
+      $PKG_DIR/scripts/xml_merge.py $PKG_DIR/config/guisettings.xml \
+                                    $PROJECT_DIR/$PROJECT/kodi/guisettings.xml \
+                                    $PROJECT_DIR/$PROJECT/devices/$DEVICE/kodi/guisettings.xml \
+                                    > $INSTALL/usr/share/kodi/config/guisettings.xml
```
This way we use any global (package-level) settings file, then - if it exists - combine a project level file (which would presumably be common for all devices), and then finally - if it exists - combine any device specific xml.

**Comment by lrusak** [comment]
updated with @MilhouseVH 's suggestions and fixes. Thanks.

**Comment by lrusak** [comment]
added cputemp/gputemp to imx6

**Pull request merged**
