### PR TITLE
WeTek_Hub: Move project to Amlogic

### PR DESCRIPTION
**Pull request by Raybuntu**
Moving WH to Amlogic project. 
meson-ir was moved from C2 device to project as we are going to switch from amremote to meson-ir for Project Amlogic soon.
Clean build and runtime tested.
I've never build amlpkg zips so no idea this is affected. @codesnake please have a look.

### CODE REVIEW

**Comment by adamg88** [comment]
This device can use S905 image with WH dtb, is it necessary to have a separate project for it any longer?

**Comment by chewitt** [comment]
@adamg88 consolidating releases requires internal discussion so for now we just move the existing release line-up under the Amlogic project. It is noted that this change becomes possible.

**Comment by adamg88** [comment]
@chewitt I was just thinking purely from a logistical point of view that it would save on finite resources and it is 1 less project to maintain then, I understand there is a desire to try and merge C2 and LePotato with S905 (which I think is a great idea, if possible) so it would make sense to do the same with Wetek devices at some point in the future. I understand it needs more discussion though given that it is a radical/fundamental step to take.

**Comment by codesnake** [comment]
@adamg88 IMO in project/devices concept putting everything into single device is wrong.
DTB is not the only thing that is different for S905-based devices. WeTek supports LE out-of-the-box and doesn't need those bootloader environment manipulations during installation. Plus WeTek projects also contain bootloader and recovery that allow to build internal installations (Android OTA updates).

**Comment by vpeter4** [comment]
> can you imagine 20 devices? ~200mb per device per release

At least @lrusak doesn't see this as an issue :)

**Comment by chewitt** [comment]
@Raybuntu linux-0004-bt_device_on_after_probe.patch can be dropped as this was merged into the kernel the other day. Otherwise looks good to go.

**Comment by Raybuntu** [comment]
@chewitt Thanks! Should be fixed now.

**Pull request merged**
