### PR TITLE
linux: add patch for Xbox One tv tuner support

### PR DESCRIPTION
**Pull request by romanlum**
The added kernel patch adds support for the TDA18250 Tuner and Xbox One Digital TV Tuner support

### CODE REVIEW

**Comment by chewitt** [comment]
@romanlum Can you please explain the source for the patch as there is no attribution. I'd also like to understand what plans exist for the driver to be upstreamed into the mainline kernel. We have no problem adding patches when there is commitment to mainline that means we will be able to drop the patch in a future kernel update. If that commitment doesn't exist we need to consider the long-term impact on our technical debt.

**Comment by chewitt** [comment]
NB: the PR needs rebasing to drop the merge commit and reword the commit message to something like "linux: add patch for Xbox One tv tuner support" to follow house-rules on naming.

**Comment by romanlum** [comment]
First of all thanks for the feedback.

I changed the name of the PR and will rebase it on top of master.

The code was pushed to linux media, so i do not know if it will be merged to mainline kernel.
* https://patchwork.linuxtv.org/patch/42853/
* https://patchwork.linuxtv.org/patch/42854/ 

The patch taken from @CvH 8.2 RPI Branch and ported it to current Generic Kernel.
see https://github.com/CvH/LibreELEC.tv/commit/961949a8f54fa8e216233dbee67325f05f811181

**Comment by romanlum** [comment]
Please wait for review as i am currently cleaning up the patch

**Comment by chewitt** [comment]
@trsqr can we have a chat in Slack about timelines for upstream merges, thanks.

**Comment by romanlum** [comment]
Patch cleaned up and ready

**Comment by chewitt** [comment]
@romanlum the kernels in master are quite fluid right now and we don't want to be stuck waiting for an updated driver patch in order to bump, or be dropping and re-adding patches all the time; in our current pre-Alpha state it's easier/cleaner to just wait for the upstream merge. The 4.9 and 4.11 kernels in our 8.2 branch are a more static target for including a patch; but then two patches are required and no guarantee it will be a clean backport. TL/DR; we will postpone any decisions on this PR until we've had a chat with Olli. Thanks.

**Comment by trsqr** [comment]
I hope the patch will be in media_tree soon (when new patches for 4.14-rc1 are merged). Haven't gotten any feedback, but that's not unusual.

**Comment by CvH** [comment]
@trsqr are further bugfixes planed as users reporting about very poor reception at certain frequencies or is that an HW problem ?

**Comment by trsqr** [comment]
@CvH There is nothing I can currently do for those. The non-open source driver exhibits the same issues I'm being told. Furthermore, I don't see any issues with the broadcasting sources that I have available to me.

The tuner is programmed by setting 8-bit values into 93 different registers. Some parameter probably needs tweaking in order to get rid of the problems. However, without any reference, it's next to impossible to figure out the correct parameters.

One guy informed me that he could do some I2C traces using a HW I2C capture device and a real Xbox. If that happens, it might give us something more. At that point, I can make changes and upstream the changes as well - however, at the moment there's nothing more planned.

**Comment by CvH** [comment]
I close this as it was added with https://github.com/LibreELEC/LibreELEC.tv/pull/2270.

**Pull request closed without merging**
