### PR TITLE
ncurses: build ncursesw for UTF-8 support

### PR DESCRIPTION
**Pull request by mglae**
Build ncursesw library with widechars to support UTF-8 and drop plain ncurses.

The change is e.g. required by `mc` to show UTF-8 file names, see https://forum.libreelec.tv/thread/24885-midnight-commander-not-supporting-russian-or-japanese-letters and https://forum.libreelec.tv/thread/24008-national-symbols-in-the-console-and-kodi. It is still required to install the Locale Addon.

In addition ncurses is updated to 6.3. 

The ncurses changes are:
- update to 6.3
- Update patches 001 (terminfo xterm) and 002 (alloc fallback)
- add patch 003: fix USE_SCROLL_HINTS/USE_HASHMAP logic
- add patch 004: fix configure option --with-pkg-config-libdir is broken for cross compilation
- Add symbolic links of ncursesw to common ncurses lib and header files to allow all packages to be build.

For mc the configuration and patch to disable widechar are removed.

~Bump multimedia, network and system tools to rebuild with ncursesw.~

Tested on Generic by building image and multimedia, network and system tools. Most tests done with screen and mc (both having issues in the past) and starting other tools like alsamixer or htop.

### CODE REVIEW

**Comment by SupervisedThinking** [comment]
I guess this [comment](https://github.com/LibreELEC/LibreELEC.tv/blob/d0c088b2c164ac8e8d8278e7acccbf116bc9d392/packages/devel/ncurses/package.mk#L14) can be dropped since LTO flags aren't the default anymore

**Comment by CvH** [comment]
please drop the addon bump commits, we need to rebuild everything (not just due that pr) so I increase the addon version after bump

**Comment by mglae** [comment]
> I guess this [comment](https://github.com/LibreELEC/LibreELEC.tv/blob/d0c088b2c164ac8e8d8278e7acccbf116bc9d392/packages/devel/ncurses/package.mk#L14) can be dropped since LTO flags aren't the default anymore

Yes, done.

**Comment by mglae** [comment]
@CvH Addon bumps are removed.

I did no size comparisons because the effects are from both 6.1 to 6.3 update and widechar use. A quick view shows Generic mc-bin size increase from 1381336 to 1472376.

**Review by CvH — APPROVED** [review]

**Pull request merged**
