### PR TITLE
linux: update to linux-4.14.15 (-ish)

### PR DESCRIPTION
**Pull request by MilhouseVH**
WIP: Target milestone 4.14.15-ish.

KPTI is enabled only for Intel as 4.14.12 does not enable KPTI for AMD.

Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.11
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.12
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.13
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.14
Changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.15

### CODE REVIEW

**Comment by fritsch** [comment]
While doing a kernel update anyways (and kpti unrelated fixes are already included), please add those two:
https://bugzilla.kernel.org/attachment.cgi?id=260583&action=edit
https://bugzilla.kernel.org/attachment.cgi?id=260585&action=edit

**Comment by MilhouseVH** [comment]
Thanks @fritsch. I've added the Bay Trail patches and [posted a 4.14.12 test build](https://forum.kodi.tv/showthread.php?tid=326703&pid=2688287#pid2688287) for the affected user.

**Comment by MilhouseVH** [comment]
Added latest `intel-ucode` with Meltdown fixes.

```
Intel Processor Microcode Package for Linux
20180108 Release

-- Updates upon 20171117 release --
IVT C0          (06-3e-04:ed) 428->42a
SKL-U/Y D0      (06-4e-03:c0) ba->c2
BDW-U/Y E/F     (06-3d-04:c0) 25->28
HSW-ULT Cx/Dx   (06-45-01:72) 20->21
Crystalwell Cx  (06-46-01:32) 17->18
BDW-H E/G       (06-47-01:22) 17->1b
HSX-EX E0       (06-3f-04:80) 0f->10
SKL-H/S R0      (06-5e-03:36) ba->c2
HSW Cx/Dx       (06-3c-03:32) 22->23
HSX C0          (06-3f-02:6f) 3a->3b
BDX-DE V0/V1    (06-56-02:10) 0f->14
BDX-DE V2       (06-56-03:10) 700000d->7000011
KBL-U/Y H0      (06-8e-09:c0) 62->80
KBL Y0 / CFL D0 (06-8e-0a:c0) 70->80
KBL-H/S B0      (06-9e-09:2a) 5e->80
CFL U0          (06-9e-0a:22) 70->80
CFL B0          (06-9e-0b:02) 72->80
SKX H0          (06-55-04:b7) 2000035->200003c
GLK B0          (06-7a-01:01) 1e->22
```

**Comment by MilhouseVH** [comment]
This can go in now I think.

**Pull request merged**
