### PR TITLE
remove chromium and dependent packages

### PR DESCRIPTION
**Pull request by lrusak**
chromium is unmaintained (it is a real pain to maintain). let's get rid of it.

### CODE REVIEW

**Comment by chewitt** [comment]
I'm marking this as 'merge blocked' for a week to see if the threat of removal stimulates anyone to step forwards and take-over as addon maintainer. If nobody does, on June 8th we push the button and I'll purge the existing files from the 9.0 addon repo.

**Comment by the-dreamer** [comment]
i recall, that libwidevine is depend on chromium because of some missing libs which are coming with the chromium addon.

**Comment by InuSasha** [comment]
@the-dreamer is it on LE 8.2?
For LE9, nss is moved into the image.

**Comment by the-dreamer** [comment]
@InuSasha , as it was one year before, i assume indeed it was for LE 8.x. I can try to remove the addon next days and see if there is a problem. For me chromium was used for amazon prime, but with inputstream.adaptive i have not used it anymore because of lack a suitable keyboard for the htpc

**Comment by the-dreamer** [comment]
short feedback: 
LibreELEC:~ # ldd /storage/.kodi/cdm/libwidevinecdm.so
        linux-vdso.so.1 (0x00007ffe465e7000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f6994f95000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f6994c05000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f699487e000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f699467a000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f6994472000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f6995954000)
        libnss3.so => /usr/lib/libnss3.so (0x00007f699414f000)
        libnssutil3.so => /usr/lib/libnssutil3.so (0x00007f6993f1f000)
        libnspr4.so => /usr/lib/libnspr4.so (0x00007f6995917000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f6993d08000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f6993959000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f699584c000)
        libplc4.so => /usr/lib/libplc4.so (0x00007f699590f000)
        libplds4.so => /usr/lib/libplds4.so (0x00007f699590a000)
LibreELEC:~ #
after chromium deletation and reboot Netflix is still working.

**Comment by chewitt** [comment]
Closing as superseded by #2790

**Pull request closed without merging**
