### PR TITLE
Update lirc

### PR DESCRIPTION
**Pull request by Kwiboo**
This PR updates lirc to 0.9.4c and fixes a build issue when python is not installed on the build host.

This needs more runtime testing before merge.

Dropped patches have been replaced by upstream.

```
0.9.4a 29/6/16

    Fix syntax errors in systemd unit files (rhbz: 1350750).
    irrecord: Enhance "Don't use devinput" message (#180).
    plugins/uirt2_raw: Reset device to UIR mode on deinit.
    plugins/girs.c: Enable reception after sending.
    lirc.org: Updates and bugfixes
    lircd, liblirc_client: Fix freeaddrinfo handling (#195).
    Don't build commandir unless we have usb.h (#191).
    lirc_options.conf: debug => loglevel (#199).
    lib: use proper linking method to avoid parallel build issue
    tools: make_rel_symlink.py can also use python2
    plugins/devinput: Make the list-devices support available.
    configure.ac: Bugfix (BSD setting reported wrong).

0.9.4b 9/8/2016

    lircd-uinput: A multitude of fixes (#213, #211, #177). Adds new options.
    lirc_client: Fix "Can't redirect irsend output" (#207).
    lirc_client: Fix un-terminated buffer causing irsend crash (#216).
    irrecord: Fix under-sized buffer causing crash (#208).
    systemd: Add hardening options comments to services (#204).
    lircmd: Options, udev examples and manpage update.
    lib: Add missing Makefile.am dep, fixes parallel build failure (#210).
    Remove a single python2 dependency [4e3c97c].
    build: Don't define docdir - autoconf defines docdir (#215).
    build: support runstatedir configure option (#212).
    doc: Manpages and configuration guide fixes.

0.9.4c 22/10/2016

    New curl_poll files adds a new MIT license. Lirc now carries GPL, BSD and MIT licenses.
    Several patches to make lirc work again on macos (#226, #227).
    New tool irtext2udp generates udp plugin data (#197).
    Fix FTBS errors on linux kernel >= 4.8.0 (#232).
    plugins: girs: Add udp/receive support (#201).
    mode2: Fix broken --raw option (#223).
    lirc-make-devinput: Fix that two remotes has the same name (#222).
    lircd: Warn for duplicate remote definitions (#222).
    lircd: Retry temporary unavailable write sockets (#221).
    contrib: Fix usb devices' acl permissions (rhbz #1364744).
    lirc-setup: Fix crasher bugfix (Fedora abort trace).
    contrib: disable udev /dev/uinput rule requiring lirc user.
    plugins: audio_alsa: Fix byte truncating in 16-bit data (#218):
    plugins: irtoy: improve error handling (#220).
    Minor documentation fixes.
```

### CODE REVIEW

**Comment by HiassofT** [comment]
I think you can drop lirc-0005-uinput.patch, this should be fixed upstream https://sourceforge.net/p/lirc/tickets/213/

lircd-uinput should now also work fine (https://sourceforge.net/p/lirc/tickets/211/) so I think we're now good to switch to that and drop the deprecated --uinput option of lircd.

**Comment by lrusak** [comment]
We might want this back then, https://github.com/lrusak/LibreELEC.tv/commit/cd18f933ba8569b1be56ce786064d7523a51377d

**Comment by lrusak** [comment]
I'm not sure about the `--release=_UP` argument. It's probably worth it to do some testing and get it into a @MilhouseVH build

**Comment by Kwiboo** [comment]
Updated again: `98-eventlircd.rules` modified to enable eventlircd for lircd-uinput devices

**Comment by Kwiboo** [comment]
It is probably best to leave `--release=_UP` on `eventlircd`, it does not generate an extra `_UP` events.

From lircd socket:
```
# irw /run/lirc/lircd-lirc0
000000004db253ac 00 KEY_UP odroid_amremote
000000004db253ac 00 KEY_UP_UP odroid_amremote
000000004db2837c 00 KEY_RIGHT odroid_amremote
000000004db2837c 00 KEY_RIGHT_UP odroid_amremote
000000004db24bb4 00 KEY_DOWN odroid_amremote
000000004db24bb4 00 KEY_DOWN_UP odroid_amremote
000000004db29966 00 KEY_LEFT odroid_amremote
000000004db29966 00 KEY_LEFT_UP odroid_amremote
```

From eventlircd socket:
```
# irw /run/lirc/lircd
67 0 KEY_UP devinput
67 0 KEY_UP_UP devinput
6a 0 KEY_RIGHT devinput
6a 0 KEY_RIGHT_UP devinput
6c 0 KEY_DOWN devinput
6c 0 KEY_DOWN_UP devinput
69 0 KEY_LEFT devinput
69 0 KEY_LEFT_UP devinput
```

**Comment by MilhouseVH** [comment]
Seems to be working on NUC (Skylake). Will include in build tonight. Please keep an eye out for issues.

**Comment by Kwiboo** [comment]
@MilhouseVH thanks for including this in your build!

I have no more changes planed as everything seems to be back to "normal" after the `98-eventlircd.rules` change.

**Comment by HiassofT** [comment]
I've tested Milhouse build 1231 on a RPi3 with GPIO receiver and so far everything seems to be fine!

**Comment by lrusak** [comment]
@MilhouseVH all good?

**Pull request merged**
