### PR TITLE
Fix booting for khadas edge boards

### PR DESCRIPTION
**Pull request by xbezdick**

### CODE REVIEW

**Comment by zhangn1985** [comment]
I'm able to boot edge-v with current mainline uboot.

**Comment by knaerzche** [comment]
@xbezdick could you please outline what/why you're not able to boot? as mentioned by @zhangn1985 edge board should/does boot fine with edge boards.

**Comment by xbezdick** [comment]
I just bought clean khadas-edge board and built master for it. It will not boot the sdcard unless I enable this option. We either document hot to get new u-boot on the boards or enable legacy to work "out of the box".

**Comment by chewitt** [comment]
Please confirm which specific version of the board you have, it should be silk-screen printed on the board. Also whether it's the Edge, Edge-V, Edge-IO, captain board used, etc?

**Comment by xbezdick** [comment]
https://github.com/LibreELEC/LibreELEC.tv/pull/7501 is better solution!

**Pull request closed without merging**
