### PR TITLE
gcc: update to 10.1.0

### PR DESCRIPTION
**Pull request by jernejsk**
Mostly due to -fno-common being enabled by default, several packages need fixes. Most fixes are taken from upstream and should be removed when package is updated.

Not sure if make parallel build issue is caused by gcc 10 or not, but I needed that fix to finish build.

### CODE REVIEW

**Comment by jernejsk** [comment]
Most addons are fixed now

**Comment by CvH** [comment]
Jenkins is happy, local building also works now for all packages.
Currently it just don't build at Ubuntu 20.04, samba fails there. Can anyone with Ubuntu 20.04 verify that ?

**Comment by CvH** [comment]
Problem is due ICU that was build before samba. This is also happen without that PR at all Projects. So we can ignore that for now :)
`PROJECT=Generic ARCH=x86_64 scripts/build icu`
`PROJECT=Generic ARCH=x86_64 scripts/build samba`

**Comment by CvH** [comment]
@jernejsk tx

**Pull request merged**
