### PR TITLE
generic: switch from yasm to nasm; update libass to 0.14.0 to support

### PR DESCRIPTION
**Pull request by antonlacon**
Yasm hasn't seen a release since 2014. Nasm is still maintained, so make the switch.

Individual packages changed here have been test compiled for generic. I have not built a full generic image, and do not have a generic machine to install the resulting image. Further testing welcome.

### CODE REVIEW

**Comment by 5schatten** [comment]
I was wondering if nasm/yasm is part of the (virtual) toolchain dependency is it necessary to add it as deidcated dep?

**Comment by HiassofT** [comment]
I'm wondering if adding yasm/nasm:host to the toolchain is really needed for non-x86 builds.

A quick grep over the package files showed only ffmpeg not listing a yasm/nasm dependency, and it'd probably be cleaner to just add a yasm/nasm dependency there and remove yasm/nasm from the toolchain

**Comment by 5schatten** [comment]
Is nasm/yasm only needed for generic/x86_64 systems? Does ARM use gcc assembler instead?

**Comment by MilhouseVH** [comment]
On the face of it I agree with replacing `yasm` with `nasm`, assuming the latter is a direct drop-in replacement for the former and doesn't introduce any new issues (testing will confirm!)

I do agree with the above discussion, it looks like `yasm`/`nasm` should only be added as a target dependency when building `"${TARGET_ARCH}" = "x86_64"`, which would mean we don't build `nasm:host` at all for non-`x86_64` projects. `nasm:host` should also be dropped from `virtual/package.mk` entirely, as it's not strictly a toolchain dependency (unless there are missing dependencies elsewhere?)

I wonder if we should we add `PKG_ARCH=x86_64` to `nasm/package.mk`, as it's only ever used by `x86_64` and building it for non-x86_64 projects is at best unnecessary, at worst an error.

One thing I don't understand is why `ffmpeg` uses `yasm/nasm`, but `ffmpegx` does not - shouldn't `ffmpegx` also be using `yasm/nasm`? Ping @CvH...

**Comment by CvH** [comment]
iirc yasm didn't worked at all for ffmpegx so it was never added, building today shows
```
BUILD      ffmpegx (target)
    TOOLCHAIN      configure (auto-detect)
...
x86 assembler             nasm
...
```
so nasm should be added to the dep too i guess

**Comment by MilhouseVH** [comment]
@antonlacon thanks for the fixups, I'll try some clean builds overnight...

**Comment by lrusak** [comment]
This may sound silly but do we need nasm/yasm at all? Can we not just use the GCC assembler?

**Comment by CvH** [comment]
it looks like it worked before for ffmpegx and his depends (tvheadend, emby) so the main question is if we get a benefit speed wise or not (just encode something at ffmpegx should gave some numbers)

**Comment by antonlacon** [comment]
IIRC, it's a syntax issue. One writes assembly for nasm/yasm or gas. FFmpeg, at least, requires nasm/yasm as it lets them build with MSVC too.

**Comment by antonlacon** [comment]
nasm should be faster at building ffmpeg than yasm, but the performance of the end binary should be similar if not the same..

**Comment by antonlacon** [comment]
CvH's ffmpeg and related commits are pulled.

**Pull request merged**
