### PR TITLE
Allwinner: Add installation script

### PR DESCRIPTION
**Pull request by jernejsk**
This PR adds installation script for Allwinner images. Script recreates clean image on eMMC using files from current installation. Storage partition is already extended to full size, so additional resize step after booting from eMMC is not necessary.

If user wants to transfer Kodi configuration, backup/restore functionality must be used.

### CODE REVIEW

**Comment by chewitt** [comment]
To avoid confusion and false +ve results in Google searches (resulting in whiny Amlogic users asking for this) please call the script something other than installtointernal.

**Comment by jernejsk** [comment]
Some people already think installtointernal is available elsewhere, for example https://forum.libreelec.tv/thread/17565-nightly-images-for-a64-h3-h5-h6-and-r40-boards/?postID=149431#post149431 Anyway, I guess it can be called "install2emmc".

**Comment by 150balbes** [comment]
You have cleared the eMMC

https://github.com/LibreELEC/LibreELEC.tv/pull/5016/files#diff-eb4f615f1c94f0cfec28bd1151fbebbf50f258d8ef2e833b3b70735a68e9c80aR63

These commands are unnecessary and significantly slow down the work.

https://github.com/LibreELEC/LibreELEC.tv/pull/5016/files#diff-eb4f615f1c94f0cfec28bd1151fbebbf50f258d8ef2e833b3b70735a68e9c80aR73

https://github.com/LibreELEC/LibreELEC.tv/pull/5016/files#diff-eb4f615f1c94f0cfec28bd1151fbebbf50f258d8ef2e833b3b70735a68e9c80aR75

**Comment by jernejsk** [comment]
They are needed. If you take a closer look, all those commands clear only 1 MiB. First one destroys partition table and other two destroy existing file systems (precaution). If you remove second and third dd, you will get broken installation if you run this script two times. mkfs.ext4 doesn't want to write fresh filesystem if one already exists. Besides, all 3 commands write only 3 MiB of data, which is nothing in comparison to copy command below.

**Review by CvH — APPROVED** [review]

**Pull request merged**
