### PR TITLE
binary-addons: update some addons to latest

### PR DESCRIPTION
**Pull request by MilhouseVH**
Update some add-ons - the Leia version of `game.libretro` no longer builds against Kodi 19/Matrix.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Not build tested, btw.

**Comment by dhewg** [comment]
Feel free to squash this in: https://github.com/dhewg/LibreELEC.tv/commit/1a804214a404fd32478775aa4518316cf4535626

**Comment by MilhouseVH** [comment]
Thanks, I've had this change (or a variant of it) in my Kodi next development branch: https://github.com/LibreELEC/LibreELEC.tv/compare/master...MilhouseVH:le10_kodi19-next02

I'll squash the changes here, but normally we bump all the add-ons together when bumping kodi

**Comment by dhewg** [comment]
> normally we bump all the add-ons together when bumping kodi

Ok, but I'm not sure I follow. What's the difference between iptvsimple and the plugins you bumped in the first commit?

**Comment by MilhouseVH** [comment]
Memory is a bit hazy, but I don't think they build with the current Kodi, so they're being bumped because they're currently broken. The current version of pvr.iptvsimple isn't broken.

**Pull request merged**
