### PR TITLE
rework cmake build system and adjust build variables

### PR DESCRIPTION
**Pull request by lrusak**
Much of this goes together otherwise I would break it up into smaller bits. It's mostly just moving variables around, so it looks scary but should be relatively safe.

@MilhouseVH can you build with this please? I built it successfully for Generic so far, will test other platforms overnight. It will require a clean build.

credit goes to the original creator except where I have converted packages myself.

If we think this is too much at this point we can wait for LE9.

### CODE REVIEW

**Comment by hudokkow** [comment]
Ouch!
cc/ me

**Comment by MilhouseVH** [comment]
Had the following build failure on RPi2, seems to be NEON related: http://sprunge.us/QYJR

This was a clean build.

**Comment by lrusak** [comment]
@MilhouseVH thanks, just ran into this also, working on it. Seems cmake with libpng doesn't build neon support. may have to remove using cmake for libpng

**Comment by lrusak** [comment]
@MilhouseVH I just pushed a patch, please test :)

**Comment by MilhouseVH** [comment]
All OK on RPi/RPi2/Generic.

**Comment by stefansaraev** [comment]
@lrusak adding extra patches to libpng, to fix a (semi)broken cmake build for the sake of moving to cmake is not worth imo. there is nothing wrong with autoconf, you can keep libpng as is

**Comment by lrusak** [comment]
@stefansaraev you're right, simple is better, no need for extra patches.

and yes the freetype soname changes when building with cmake :(
why does that happen?

**Comment by stefansaraev** [comment]
idk. I noticed that soname change month ago when I tried to build freetype with cmake in my fork. did not care to check why it happened ;)

**Comment by lrusak** [comment]
Seems dumb.

Any other issues you foresee?

**Comment by stefansaraev** [comment]
none. still, you know my fork is very minimal. I've done this cmake rework in my fork in different way. I keep it even simpler. for packages that ship both cmakelists.txt and configure - cmake has higher prio. if I dont want to use cmake - I just delete cmakelists.txt in post_unpack()

from what I see in your PR, all should be fine after you squash/rebase reverts. 

f something needs extra work to use cmake, I dont touch it (kodi is an exception, as in v18 there will be no autoconf anymore, so I started earlier..). so in my fork, expat still uses autoconf, but yours should be ok.

**Comment by lrusak** [comment]
@LongChair not sure if any of these changes mess you guys up. There might just be some variable name differences. Just giving you a heads up :)

**Comment by LongChair** [comment]
That will probably require some adjustments in our packages ... But i suppose i should be ok :)

**Comment by lrusak** [comment]
rebased, should be good to go if @MilhouseVH gives the thumbs up

**Comment by lrusak** [comment]
pushed a commit to revert the yasm cmake change as yasm won't build for target when using cmake (not without patches at least).

**Comment by vpeter4** [comment]
It doesn't build for imx6 project (master + this pr) - don't understand what the issue could be.
```
CPP     xbmc/interfaces/python/PyContext.o
Unable to open file /home/pvic/tmp/a/le.xmlmake/build.LibreELEC-imx6.arm-8.0-devel/kodi-17.0-beta2-6e9d6fb/xbmc/interfaces/python/generated/AddonModuleXbmc.xml: No such file or directory
../../../codegenerator.mk:45: recipe for target '/home/pvic/tmp/a/le.cmake/build.LibreELEC-imx6.arm-8.0-devel/kodi-17.0-beta2-6e9d6fb/xbmc/interfaces/python/generated/AddonModuleXbmc.xml' failed
make[1]: *** [/home/pvic/tmp/a/le.cmake/build.LibreELEC-imx6.arm-8.0-devel/kodi-17.0-beta2-6e9d6fb/xbmc/interfaces/python/generated/AddonModuleXbmc.xml] Error 1
Makefile:428: recipe for target 'xbmc/interfaces/python/python_binding.a' failed
make: *** [xbmc/interfaces/python/python_binding.a] Error 2
```

**Comment by lrusak** [comment]
added some more fixup commits.

**Comment by lrusak** [comment]
any objections here? would be nice to get this in or should we wait till LE9?

**Comment by MilhouseVH** [comment]
None from me. I'd rather this was merged sooner than later.

**Comment by LongChair** [comment]
Yeah the sooner it's merged, the better it is, will need to fix our packages accordingly :p

**Comment by vpeter4** [comment]
I finally figure out where the problem is - I can't build in **le.cmake** folder. Wonder why... Seems there is some folder name changed to **le.xmlmake**.

**Comment by lrusak** [comment]
@MilhouseVH pushed a fixup to allow for debug builds

**Comment by lrusak** [comment]
rebased

**Pull request merged**
