### PR TITLE
Upstream changes

### PR DESCRIPTION
**Pull request by lrusak**
Looks like someone is looking to support Wayland!!! WOOOO

good thing I already have wayland support in my branch.... 

anyways. Pretty minor stuff here, some small fixes and some packages bumps.

keep this open till a little later incase there is more stuff to be picked :+1:

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I'm really not sure that adding hardware RAID support is a great idea (aside from the fact hardware RAID stopped being a good idea at least 10 years ago).

Where does this end? Do we add LSI, 3Ware, Adaptec and IBM support too, now that we've added MegaRAID support?

I think we need to be very careful about adding support for such a niche requirement. LibreELEC is after all a lightweight mediacenter client...

**Comment by chewitt** [comment]
You'll find there are existing pockets of hardware RAID support in the existing kernel .. added on request by people in the past. Agreed it's niche, but OE always had the stance that H/W RAID was okay as it's just a simple tweak to the KERNEL to support vs. S/W which is undesirable as it would require us to bloat up SYSTEM with RAID config and management tools for the change to be useful. If we want to put the kernel on a diet there are easier targets for size savings.

**Comment by MilhouseVH** [comment]
OK, just wanted to say my piece. :)

**Comment by lrusak** [comment]
I would be more than happy to drop it, however I don't want to be behind (feature wise) right out of the gate. I'm perfectly ok with kernel config changes as long as they don't require other software packages.

**Comment by lrusak** [comment]
should be good to go unless anyone objects

**Pull request merged**
