### PR TITLE
DVB driver addons update to latest

### PR DESCRIPTION
**Pull request by CvH**
- update everything to latest
- media_tree based at 4.19

### CODE REVIEW

**Comment by CvH** [comment]
Updated pr:
cleanup all packages and using now a new method to configure them, this disables everything besides the dvb drivers automatically and should work without maintenance for every new version too - this also benefits the compatibility and reduces buildtime (less stuff that can break).

See `driver.dvb.$NAME-02-disable-modules.patch`, this basically replaces the manual config and is done now at build time.

**added crazycat_aml**
I used the same package as crazycat but added (for copyright/for the record reasons I add this here)

- the meson drivers from https://github.com/CoreELEC/media_tree_aml/commit/619ba251386da72897262a39878c17804905a71d
- the dvb drivers from https://github.com/CoreELEC/media_tree/commit/a4be5a886fd1147ab6a59776886ee9d982fb4b97
- meson ir patch from https://github.com/CoreELEC/CoreELEC/blob/33b84c28062953f92c686d9430a6e5b136d253d7/packages/linux-driver-addons/dvb/depends/media_tree_cc/patches/media_tree_cc-01-meson-ir.patch
- the config_mycompat_h.patch from https://github.com/CoreELEC/CoreELEC/blob/33b84c28062953f92c686d9430a6e5b136d253d7/packages/linux-driver-addons/dvb/crazycat/patches/amlogic/driver.dvb.crazycat-01-config_mycompat_h.patch

Due the amount of AML 3.14 specific changes and that this is the last time someone touches the package I choose that way instead of proper patching the heck out of the current crazycat package.

This (aml) is not yet fully tested.

**Comment by afl1** [comment]
I only welcome this crazycat_aml addition. I have one note, in driver/media/platform/meson/Makefile are missing lines for building aml drivers.  Correct Makefile have to be:

> obj-$(CONFIG_VIDEO_MESON_AO_CEC)	+= ao-cec.o
obj-y += video_dev/
obj-y += dvb-avl/
obj-y += wetek/

In CoreELEC those commands are added in package.mk for compatibility with media_build_cc.

**Comment by CvH** [comment]
@afl1 Tx for reply

> Correct Makefile have to be:

I didn't hardwired it to have more flexibility.
Thats why I used the method at the package.mk

```
  # compile modules
  echo "obj-y += video_dev/" >> "$PKG_BUILD/linux/drivers/media/platform/meson/Makefile"
```

easier to add/remove the modules if needed

**Comment by MilhouseVH** [comment]
CrazyCat currently disabled for RPi and Generic while it doesn't build with 4.19.y.

**Pull request merged**
