### PR TITLE
update dvb addons

### PR DESCRIPTION
**Pull request by CvH**
- this updates all dvb addons (kernel 4.17 base)
- dropped patches that are upstream and regenerated the config
- dropped 37 hauppauge patches as they are upstream now
- dropped dvb-avl driver because it doesn't build anymore and there is no fix yet

### CODE REVIEW

**Comment by 5schatten** [comment]
Well I tried to update my [build ](https://forum.libreelec.tv/thread/12662-libreelec-9-0-reborn-remix-emulationstation-retroarch-dolphinqt-wip/) with PR#2776 (kernel 4.17.x) and your updated DVB add-ons but still the lirc device fails to build. I patched an older version of your DVB add-on for LE 8.2 Remix and this worked fine with kernel 4.17 (https://github.com/SupervisedThinking/cc-dvb)

So any clue why this still won't work?

**Comment by CvH** [comment]
@5schatten this needs update for 4.17, 4.14 build well - I update it asap we merge 4.17

**Comment by 5schatten** [comment]
@CvH okay thx for your explanation -> I thought this PR is already updated for K417 :-)

**Comment by chewitt** [comment]
@CvH what's the latest on this?

**Comment by CvH** [comment]
old version, superseded by https://github.com/LibreELEC/LibreELEC.tv/pull/2872

**Pull request closed without merging**
