### PR TITLE
linux: update to 5.18.y

### PR DESCRIPTION
**Pull request by heitbaum**
### Announcements
- 5.18-rc4 - https://lore.kernel.org/lkml/CAHk-=whmtHMzjaVUF9bS+7vE_rrRctcCTvsAeB8fuLYcyYLN-g@mail.gmail.com/
- 5.18-rc5 - https://lore.kernel.org/lkml/CAHk-=wjUhfhaes6_hMYDQFTbGjkmA-j2ZSeXZ32H66ufRfYrmQ@mail.gmail.com/
- 5.18-rc6 - https://lore.kernel.org/lkml/CAHk-=wi0vqZQUAS67tBsJQW+dtt89m+dqA-Z4bOs8CH-mm8u2w@mail.gmail.com/
- 5.18-rc7 - https://lore.kernel.org/lkml/CAHk-=wg2eVUN0a1E5UnBF1ziGaU1yrMJtnFPg4R78O=FcRDqnA@mail.gmail.com/
- 5.18 - https://lore.kernel.org/lkml/CAHk-=wjiqyoH6qntYvYTjR1F2L-pHtgX9esZMRS13iktCOJ1zA@mail.gmail.com/
- https://github.com/torvalds/linux/commits/master

### errors / fixes / issues / regressions

- RTL8812AU compile errors - FIXED
  - upstreamed PR patch backported until `aircrack-ng` PR committed
    - https://github.com/aircrack-ng/rtl8812au/pull/959
- ~needs iwlwifi-firmware: update to XXX~
  - ~https://git.kernel.org/pub/scm/linux/kernel/git/iwlwifi/linux-firmware.git/log/~
- ~refactor of the kernel has moved the MEDIA drivers - done~
  - ~VIDEO_ROCKCHIP_IEP Rockchip Kconfig moved **but not in the .config**~
  - ~VIDEO_SUN50I_DEINTERLACE Allwinner Kconfig moved **but not in the .config**~
- ~ffmpeg patch required for HVEC~
- ~error with firmware build - revert until solution found~
  - ~fix included as #6452~
  - ~https://superuser.com/questions/1677576/add-all-firmware-to-config-extra-firmware~
  - ~https://stackoverflow.com/questions/33051108/how-to-get-around-the-linux-too-many-arguments-limit~
  - ~https://github.com/ninja-build/ninja/issues/1261~
  - ~https://savannah.gnu.org/bugs/?45763~
- ~RTL8192DU does not compile~
  - ~temp fix in place~
  - ~https://github.com/lwfinger/rtl8192du/issues/91~
- ~xf86-video-nvidia-legacy does not compile~
  - ~ERROR: modpost: GPL-incompatible module nvidia.ko uses GPL-only symbol 'acpi_fetch_acpi_dev', so continuing the use of acpi_bus_get_device~
  - ~https://forums.developer.nvidia.com/t/linux-kernel-5-18-rcx/210965~

### log
- Rockchip DRM patch changed from `YCRCB` to `YCBCR` 
- add new files for `drivers/media/platform` to correct directories - e.g. `sunxi/sun50i-di`
- update diff `drivers/media/platform` files to correct directories - e.g. `sunxi/sun50i-di`
- drop upstreamed patches
- update the .config files
- minor refactor of `0032-ASoC-sun4i-i2s-Add-parenthesis-around-macro-argument.patch`
- patched bcm_sta to support kernel 5.18
- nvidia xf86-video-nvidia-470.103.01 patch
- Updated RTL8192DU
- Allwinner patch refactored
  - projects/Allwinner/patches/linux/0033-WIP-I2S-multi-channel.patch
- kernel-firmware: update to 20220411
- update kernel-firmware to use https://cdn.kernel.org/pub/linux/kernel/firmware/linux-firmware-${PKG_VERSION}.tar.xz
- iMX8 patches updated
- updated HEVC patch for Rockchip
- xf86-video-nvidia-legacy patch updated
  - reverted https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d017a3167bcb76caedf2b444645bf4db75f775a5
- fix patches for Kconfig
- [iwlwifi-firmware: update to d34bb99](https://github.com/LibreELEC/LibreELEC.tv/pull/6423/commits/9e61bbdd6c824de442a3b50f8e23dac1d22c792a)

### kernel 5.18 Build tested on all of:

```
PROJECT=Allwinner ARCH=arm DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H3 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H6 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX6 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX8 s/build linux
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy s/build linux
```

### 5.18.y Run tested on all of:
- Allwinner all - tested - 5.18-rc5 - jernejsk
- Allwinner H6 (Tanix TX6) - 5.18.0 - heitbaum
- Generic Generic (Intel TGL - NUC11) - 5.18.0 - heitbaum
- NXP iMX6 (Cubox-i4Pro) - 5.18.0 - heitbaum
- Rockchip RK3399pro (Rock Pi N10) - TBA - heitbaum
- Rockchip RK3399 - tested - 5.18-rc5 - knaerzche
- Rockchip RK3399 - tested - 5.18.0 - SupervisedThinking
- Samsung Exynos (Hardkernel ODROID XU4) - TBA - heitbaum (video issue)

### CODE REVIEW

**Comment by heitbaum** [comment]
Kernel 5.18 has dropped support for `V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR`:

- https://github.com/torvalds/linux/commit/7a3b3dc3bb2eeac4adf8b01b1b6b519bcbc48cfc
- https://lkml.kernel.org/lkml/20210831094900.203283-1-benjamin.gaignard@collabora.com/T/
- https://lkml.org/lkml/2022/1/7/494

@jernejsk / @HiassofT - what updates are required in the ffmpeg. 
@knaerzche - I have updated the `linux-2000-v4l2-wip-rkvdec-hevc.patch` as per https://github.com/torvalds/linux/commit/7a3b3dc3bb2eeac4adf8b01b1b6b519bcbc48cfc

```
$ git grep V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR
packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch:+#define V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR            0x03
packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch:+#define V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR            0x03
packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch:+            return V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR;
packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-request.patch:+            return V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR;
packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-request.patch:+#define V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR          0x03
projects/Rockchip/patches/linux/default/linux-2000-v4l2-wip-rkvdec-hevc.patch:+                 WRITE_RPS(!!(dpb[sl_params->ref_idx_l0[i]].rps == V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR),
projects/Rockchip/patches/linux/default/linux-2000-v4l2-wip-rkvdec-hevc.patch:+                 WRITE_RPS(!!(dpb[sl_params->ref_idx_l1[i]].rps == V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR),
projects/Rockchip/patches/linux/default/linux-2000-v4l2-wip-rkvdec-hevc.patch:                  WRITE_RPS(!!(dpb[sl_params->ref_idx_l0[i]].rps == V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR),
projects/Rockchip/patches/linux/default/linux-2000-v4l2-wip-rkvdec-hevc.patch:                  WRITE_RPS(!!(dpb[sl_params->ref_idx_l1[i]].rps == V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR),
```

All 3 defines in `packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-request.patch` are now deprecated
```
+#define V4L2_HEVC_DPB_ENTRY_RPS_ST_CURR_BEFORE 0x01
+#define V4L2_HEVC_DPB_ENTRY_RPS_ST_CURR_AFTER  0x02
+#define V4L2_HEVC_DPB_ENTRY_RPS_LT_CURR                0x03
```

**Comment by HiassofT** [comment]
jc has already a fix in his ffmpeg branch https://github.com/jc-kynesim/rpi-ffmpeg/commit/1185da965a12693f5e3d8615a08ea5ed06e7eed0 - I'll add it with the next ffmpeg rpi patch update

**Comment by jernejsk** [comment]
I updated v4l2-request patches, so you can update them with `tools/ffmpeg/gen-patches.sh v4l2-request` Only build tested for now.

Is there anything else I have to take a look at? Deinterlacing works?

**Comment by heitbaum** [comment]
> I updated v4l2-request patches, so you can update them with `tools/ffmpeg/gen-patches.sh v4l2-request` Only build tested for now.
> 
> Is there anything else I have to take a look at? Deinterlacing works?

I have included that now 👍

this still needs to be investigated:
- refactor of the kernel has moved the MEDIA drivers - NEED HELP
  - VIDEO_ROCKCHIP_IEP Rockchip Kconfig moved but not in the .config ??
  - VIDEO_SUN50I_DEINTERLACE Allwinner Kconfig moved but not in the .config ??

I have been running 5.18-rc5 this week on the TGL. 

Plan on doing the testing on some of the arms on the weekend. 

So pretty much ready to go apart from the nice to haves (upstream rtl8812au instead of the patch and iwlwifi fw) - and the 2 Kconfig issues.

**Comment by jernejsk** [comment]
Patch http://ix.io/3X3k should fix `VIDEO_SUN50I_DEINTERLACE Allwinner Kconfig moved but not in the .config ??` Same fix should be applied to linux-2001-v4l2-wip-iep-driver.patch too.

Please also check (Allwinner aarch64 config):
```
LINUX: kernel options not correct: 
        CONFIG_NLS_DEFAULT="utf8"

Please run ./tools/check_kernel_config
```

**Comment by heitbaum** [comment]
> Patch http://ix.io/3X3k should fix `VIDEO_SUN50I_DEINTERLACE Allwinner Kconfig moved but not in the .config ??` Same fix should be applied to linux-2001-v4l2-wip-iep-driver.patch too.
> 
> Please also check (Allwinner aarch64 config):
> 
> ```
> LINUX: kernel options not correct: 
>         CONFIG_NLS_DEFAULT="utf8"
> 
> Please run ./tools/check_kernel_config
> ```

Perfect - I’ll check it out.

For 2 - it is fixed by #6457

**Comment by heitbaum** [comment]
The 2 Kconfig patches fixed.

**Comment by knaerzche** [comment]
Adaptions for RK look good, thx @heitbaum

**Comment by knaerzche** [comment]
Runtime tested on RK3399:
- deinterlacing good
- HEVC: https://rentry.co/hanfi - WPP_D_ericsson_MAIN_2 is failing now and was OK before, shouldn't hold us back: I'll check later when tidying up HEVC patches

**Comment by heitbaum** [comment]
> Runtime tested on RK3399:
> 
> * deinterlacing good
> * HEVC: ~https://rentry.co/hanfi - WPP_D_ericsson_MAIN_2 is failing now and was OK before, shouldn't hold us back: I'll check later when tidying up HEVC patches~ nevermind there are still issues with threading in python: - when running fluster with -j1 everything is fine: https://rentry.co/qpvrp

Thanks for testing. 
Only rtl8812 and the release of 5.18.0 left….
Im still having an issue with the kernel firmware build, so that may be dropped from the PR. But otherwise running well here.

**Comment by smp79** [comment]
> Im still having an issue with the kernel firmware build

Same here. #6452 didn't fix it.

**Comment by heitbaum** [comment]
> > Im still having an issue with the kernel firmware build
> 
> Same here. #6452 didn't fix it.

I have checked the referenced forum and bug reports that I tagged in https://github.com/LibreELEC/LibreELEC.tv/pull/6423#issue-1213587187 - there have been no updates. I’m sure when I tested this - it worked - but obviously not!

**Comment by heitbaum** [comment]
@smp79 

I just tested - the patch is either not correctly applying / working differently from designed. Can you check yours the same way.

```
docker@ebec6854cac1:/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/make-4.3/tests$ PATH=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin:$PATH sh run_make_tests
Cannot locate ../tests/config-flags.pm
------------------------------------------------------------------------------
      Running tests for GNU make on Linux ebec6854cac1 5.18.0-rc6 x86_64
                                 GNU Make 4.3
------------------------------------------------------------------------------

Clearing work...
Finding tests...
…

…
features/long_command_line .............................. Error running make (expected 0; got 512): 'make' '-f' 'work/features/long_command_line.mk'
FAILED (0/1 passed).
```

**Comment by heitbaum** [comment]
Well after another look
- I know why now: fixed with a small patch #6487

`features/long_command_line .............................. ok     (1 passed) `

as we can’t patch `configure.ac` without a dependency loop. 
- and with the #6461 thus not defining `HAVE_LINUX_BINFMTS_H` and `HAVE_SYS_USER_H` 

The below patch always includes the required `#include` files.
```
diff --git a/packages/devel/make/patches/make-02-fix-large-command-line-on-POSIX-systems.patch b/packages/devel/make/patches/make-02-fix-l
arge-command-line-on-POSIX-systems.patch
index 0e4cc274306..12ac8b767a2 100644
--- a/packages/devel/make/patches/make-02-fix-large-command-line-on-POSIX-systems.patch
+++ b/packages/devel/make/patches/make-02-fix-large-command-line-on-POSIX-systems.patch
@@ -44,14 +44,12 @@ diff --git a/src/job.c b/src/job.c
 index 3bcec38..734c591 100644
 --- a/src/job.c
 +++ b/src/job.c
-@@ -26,6 +26,14 @@ this program.  If not, see <http://www.gnu.org/licenses/>.  */
+@@ -26,6 +26,12 @@ this program.  If not, see <http://www.gnu.org/licenses/>.  */
  #include "variable.h"
  #include "os.h"
  
-+#if defined (HAVE_LINUX_BINFMTS_H) && defined (HAVE_SYS_USER_H)
 +#include <sys/user.h>
 +#include <linux/binfmts.h>
-+#endif
 +#ifndef PAGE_SIZE
 +# define PAGE_SIZE (sysconf(_SC_PAGESIZE))
 +#endif 
```

**Comment by heitbaum** [comment]
Kernel 5.18 PR RTG. .config commits have been squashed.

**Comment by SupervisedThinking** [comment]
build & run tested with RK3399

**Review by SupervisedThinking — DISMISSED** [review]

**Comment by SupervisedThinking** [comment]
@heitbaum please move https://github.com/LibreELEC/LibreELEC.tv/pull/6423/commits/58566ad0d48ae8c6fde66b41dd2f659ff1de36d7#diff-ac0fb975346929807b263f9db7b96009f22017921545159a9f9b92958d583c5d to the `x11` subfolder out of generic-legacy

**Comment by heitbaum** [comment]
@SupervisedThinking - done. But now `Generic-legacy` will fail on the nvidia-legacy.

```
<<< linux:host seq 60 <<<
CLEAN      linux
    *      Removing /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/build/linux-5.18 ...
    *      Removing /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/install_pkg/linux-5.18 ...
UNPACK      linux
    APPLY PATCH (common - default)      packages/linux/patches/default/fs-ntfs3-since-5-15.patch
patching file fs/ntfs3/fslog.c
patching file fs/ntfs3/file.c
Hunk #1 succeeded at 495 (offset 1 line).
patching file fs/ntfs3/xattr.c
patching file fs/ntfs3/xattr.c
patching file fs/ntfs3/xattr.c
patching file fs/ntfs3/xattr.c
patching file fs/ntfs3/file.c
Hunk #1 succeeded at 762 (offset 1 line).
patching file fs/ntfs3/frecord.c
patching file fs/ntfs3/file.c
Hunk #1 succeeded at 662 (offset 1 line).
patching file fs/ntfs3/inode.c
    APPLY PATCH (common - default)      packages/linux/patches/default/linux-020-eld-constraints-for-compressed-formats.patch
patching file sound/core/pcm_drm_eld.c
    APPLY PATCH (common - default)      packages/linux/patches/default/linux-051-ouya_controller_support.patch
patching file drivers/hid/Kconfig
Hunk #1 succeeded at 814 (offset 155 lines).
patching file drivers/hid/Makefile
Hunk #1 succeeded at 84 (offset 13 lines).
patching file drivers/hid/hid-ids.h
Hunk #1 succeeded at 981 with fuzz 2 (offset 122 lines).
patching file drivers/hid/hid-ouya.c
patching file drivers/hid/hid-quirks.c
Hunk #1 succeeded at 559 (offset 21 lines).
    APPLY PATCH (common - default)      packages/linux/patches/default/linux-058.05-hid_sony-add_autorepeat_for_PS3_remotes.patch
patching file drivers/hid/hid-sony.c
Hunk #1 succeeded at 936 with fuzz 1 (offset -184 lines).
Hunk #2 succeeded at 2944 with fuzz 1 (offset 553 lines).
    APPLY PATCH (common - default)      packages/linux/patches/default/linux-062-imon_pad_ignore_diagonal.patch
patching file drivers/media/rc/imon.c
Hunk #1 succeeded at 1424 (offset 80 lines).
    APPLY PATCH (common - default)      packages/linux/patches/default/linux-999-no-lzma-in-x86-perf-build.patch
patching file tools/perf/Makefile.config
Hunk #1 succeeded at 56 with fuzz 2 (offset 21 lines).
    APPLY PATCH (common - default)      packages/linux/patches/default/linux-999.02-0001-pm-disable-async-suspend-resume-by-default.patch
patching file kernel/power/main.c
Hunk #1 succeeded at 95 (offset 49 lines).
BUILD      linux (host)
    TOOLCHAIN      make (auto-detect)
```

**Comment by SupervisedThinking** [comment]
@heitbaum add a symlink to the patch directory in `x11` - Generic & Generic-legacy should be only "virtual" packages which point to the actual stuff we build so either gbm/wayland/x11

**Comment by SupervisedThinking** [comment]
build & run tested with X11

**Review by SupervisedThinking — APPROVED** [review]

**Pull request merged**
