### PR TITLE
linux: add IOMMU support for Generic

### PR DESCRIPTION
**Pull request by mglae**
For the Haswell bug mentioned in the [linux 5.8.7 update](https://github.com/LibreELEC/LibreELEC.tv/pull/4545#pullrequestreview-483140499) there are reports in an [Arch forum](https://bbs.archlinux.org/viewtopic.php?id=256520&p=3) that using IOMMU allows booting the machines.

Enable IOMMU support in Generic kernel to allow affected users to test.

Tested on Gemini Lake (not affected by the bug).

### CODE REVIEW

**Review by HiassofT — APPROVED** [review]
thanks, looks reasonable to me, but can't test myself if it helps

**Comment by CvH** [comment]
looks similar so far
```
[    7.522229] snd_hda_intel 0000:00:1b.0: IRQ timing workaround is activated for card #1. Suggest a bigger bdl_pos_adj.
[   11.411569] i915 0000:00:02.0: [drm] GPU HANG: ecode 7:1:8edcfc79, in Xorg [708]
[   11.411570] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
[   11.411570] Please file a _new_ bug report at https://gitlab.freedesktop.org/drm/intel/issues/new.
[   11.411571] Please see https://gitlab.freedesktop.org/drm/intel/-/wikis/How-to-file-i915-bugs for details.
[   11.411571] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
[   11.411571] The GPU crash dump is required to analyze GPU hangs, so please always attach it.
[   11.411572] GPU crash dump saved to /sys/class/drm/card0/error
[   11.412256] i915 0000:00:02.0: [drm] Resetting chip for stopped heartbeat on rcs0
[   11.514629] i915 0000:00:02.0: [drm] Xorg[708] context reset due to GPU hang
```

**Comment by mglae** [comment]
I was afraid of that. Then there is only the [the hack from issue 2024](http://ix.io/2zKp) remaining.

**Comment by CvH** [comment]
for me nothing changed so should we revert that pr ?

**Comment by mglae** [comment]
@HiassofT Had the same idea, although there is nothing in LibreELEC needing VM functionality.

**Comment by HiassofT** [comment]
@mglae I agree, it's not really needed in LE ATM.

Although IOMMU_SUPPORT defaults to 'y' in Kconfig and it's also enabled for most other projects/devices in LE (except RPis, which don't have an IOMMU), so I'd just enable general IOMMU stuff for x86 as well - it won't hurt.

**Comment by CvH** [comment]
looks like this is breaking AMD 2400g support :)
https://forum.libreelec.tv/thread/22823-libreelec-nightly-regression-on-amd-2400g/?postID=145753#post145753

**Comment by mglae** [comment]
Yes :-(

Current confirmed work around is using `iommu=off` kernel parameter. This give us time looking for a solution.

**Comment by HiassofT** [comment]
AMD seems to have actually been caused by non-standard `pci=nomsi` option (in combination with iommu support).

User dropped that so everything seems to be fine
https://forum.libreelec.tv/thread/22823-libreelec-nightly-regression-on-amd-2400g/?postID=145816#post145816

**Pull request merged**
