### PR TITLE
kodi: update amltiming patch

### PR DESCRIPTION
**Pull request by Raybuntu**
Please add "Don't merge" and "WIP"

vc-1 a/v sync issue resolved
mpeg4 a/v sync issue resolved

See https://github.com/LibreELEC/linux-amlogic/pull/37
and https://github.com/LibreELEC/linux-amlogic/pull/38

### CODE REVIEW

**Comment by Raybuntu** [comment]
@kszaq: Looks good to me with linux-amlogic 3.14. What do you think about linux 3.10?
Got a lot of testing. I think its save to merge.

**Comment by kszaq** [comment]
Looks good to me for 3.10 devices after kernel bump.

**Comment by wrxtasy** [comment]
Three thumbs up here as well 👍 👍 👍

**Comment by Raybuntu** [comment]
Thanks kszaq. I included a commit to bump the kernel. It's ready to be merged. Please remove WIP, Don't merge labels.

**Comment by Raybuntu** [comment]
Thanks for the review and merge.

**Pull request merged**
