### PR TITLE
linux: update to linux-4.8.6

### PR DESCRIPTION
**Pull request by MilhouseVH**
ARCH_MULTIPLATFORM: https://github.com/raspberrypi/linux/pull/1699
Power Management: https://github.com/raspberrypi/linux/pull/1700

### CODE REVIEW

**Comment by MilhouseVH** [comment]
> Was this patch dropped because it doesn't apply?

It no longer applies on 4.8.6 as there seem to have been a number of changes to `drivers/gpu/drm/i915/intel_hdmi.c` between 4.8.4 and 4.8.6.
>  Do we still need it?

To be honest I don't know if this issue has been fixed in another way - so far, there have been no complaints in the two days of test builds since I dropped this patch.

@fritsch suggested I include it some time back, and it seemed to be of benefit to one (maybe two) people, but unless there's a replacement I'm not going to lose sleep over it. Including this type of patch is always a lottery when it comes to a new kernel.

**Comment by fritsch** [comment]
Which patch?

**Comment by MilhouseVH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/pull/900/commits/7f659b671d086b5342a2cad92166b18c8cb93a2b

**Comment by fritsch** [comment]
We will find out :-)

Am 03.11.2016 3:47 nachm. schrieb "MilhouseVH" <notifications@github.com>:

**Comment by lrusak** [comment]
good to go?

**Comment by MilhouseVH** [comment]
No issues reported so far.

**Pull request merged**
