### PR TITLE
[le92] linux (RPi): update to 4.19.67+

### PR DESCRIPTION
**Pull request by HiassofT**
not build-tested yet

### CODE REVIEW

**Comment by Noltari** [comment]
Rebased on current libreelec-9.2, built and tested successfully on RPi 4B.

**Comment by HiassofT** [comment]
@Noltari thanks for testing!

Keep in mind that there's a known issue with firmware versions since Aug 22 which results in dropped HDMI signal, errors in dmesg and long time to reboot when selecting 4kp50 (and maybe other 50Hz) modes.

RPi folks are working on a fix for that.

If you are affected by that issue you can add `core_freq_min=530` to config.txt as a workaround.

**Comment by Noltari** [comment]
TBH I’ve never been able to do 4k@60hz, I only get 4k@30hz on my Samsung Q9FN55.

**Comment by HiassofT** [comment]
@Noltari check the settings on your TV, you may need to enable "deep colour" or some similar setting on the HDMI port - needed to do that on my LG 55C8 to enable 4:4:4 mode. You'll also need "hdmi_enable_4kp60=1" in config.txt to get 4k modes above 30Hz.

**Comment by Noltari** [comment]
@HiassofT thanks, I could finally get 4k@60hz. The needed TV setting was pretty hidden and different to other Samsung models.
BTW, where is this issue reported? I couldn't find anything about it.

**Comment by HiassofT** [comment]
I reported it directly to popcornmix via our (private) LibreELEC slack channel - didn't open a public issue for that

**Pull request merged**
