### PR TITLE
mesa: updated to 21.0.1

### PR DESCRIPTION
**Pull request by SupervisedThinking**
Release notes:
- https://docs.mesa3d.org/relnotes/21.0.0.html
- https://docs.mesa3d.org/relnotes/21.0.1.html
- https://www.phoronix.com/scan.php?page=news_item&px=Mesa-21.0-Released
- https://www.phoronix.com/scan.php?page=news_item&px=Mesa-21.0.1-Released

### CODE REVIEW

**Comment by CvH** [comment]
@knaerzche @jernejsk do we want this for LE10b2 ?

**Comment by SupervisedThinking** [comment]
@CvH should be useful for RK3399, RPi4 etc.

**Comment by chewitt** [comment]
I've been tracking mesa master for a while with Amlogic and haven't seen any issues with lima/panfrost. I've no idea about RPi4/Generic usage tho.

**Comment by heitbaum** [comment]
Generic has been fine, but I have been using the 21.1 master. As per https://docs.mesa3d.org/relnotes/21.0.0.html `Mesa 21.0.0 is a new development release. People who are concerned with stability and reliability should stick with a previous release or wait for Mesa 21.0.1.` I am in favour of going to 21.0.0 but it does mean tracking the 21.0.y releases in LE10.

**Comment by SupervisedThinking** [comment]
Mesa 21.0.1 expected date is the 2021-03-24 
https://docs.mesa3d.org/release-calendar.html

I'm also using mesa head for all ARM builds, but 21.0.0 on SKL/APL Generic builds and had no problem at all. Beside that 21.0 matured for really a long time already since some blockers remained and so a lot of fixes had been backported form 21.1-dev anyway.

**Comment by heitbaum** [comment]
Just looking at queu of 35 @ 21.0.1 - https://gitlab.freedesktop.org/mesa/mesa/-/compare/21.0...staging%2F21.0 has some intel fixes - nothing else that jumped out.

**Comment by jernejsk** [comment]
I found out that current lima driver has OOM bug and fix https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/9172 is present only in 20.3.5 or 21.0.x. So yes, I would like this to go in.

Possibly related: https://forum.libreelec.tv/thread/17565-nightly-images-for-a64-h3-h5-h6-and-r40-boards/?postID=152335#post152335

**Comment by HiassofT** [comment]
very quick test on RPi4 with this PR looks good, so no objections from my side if it helps on other systems

**Review by CvH — APPROVED** [review]

**Comment by HiassofT** [comment]
The mesa update seems to have caused a regression, VDPAU is used on an AMD system instead of VAAPI: https://forum.libreelec.tv/thread/23736-problem-with-vdpau-decoder/

**Comment by SupervisedThinking** [comment]
Maybe it's related to this? https://gitlab.freedesktop.org/mesa/mesa/-/issues/3649

Beside that there are plenty of VDPAU + AMD issues listed in the  issue tracker:

https://gitlab.freedesktop.org/mesa/mesa/-/issues?scope=all&utf8=%E2%9C%93&state=opened&search=vdpau

**Comment by SupervisedThinking** [comment]
Looks like the issue is identified https://gitlab.freedesktop.org/mesa/mesa/-/issues/4605#note_873083 and can be solved by reverting https://github.com/mesa3d/mesa/commit/f7a4051b836294ab8f55c71d239e99c5cbf63170

**Comment by heitbaum** [comment]
Do we add the revert as a patch? Or wait for 21.0.3

**Pull request merged**
