### PR TITLE
Reintroduce trigger for debug shell again

### PR DESCRIPTION
**Pull request by mglae**
Alternative or addition (without the second commit) to #4494, based on the discussion there.

Kernel parameter `systemd.debug_shell` is only working if system is booting into default.target or the deviant target is forced with `systemd.unit=...`

Reintroduce `tty` option launching the default debug shell in any case. In addition the debug shell is active when using `debugging` or on existing file "/storage/.cache/debug.libreelec".

The advanced user still can use `systemd.debug_shell` if wanted.

Successful tested with "installer", "run" and installed system after incremental Generic build with my LE 9.2 tree.

### CODE REVIEW

**Comment by HiassofT** [comment]
I'm not too keen on adding yet another option to activate a debug shell.

If you want a debug shell in the installer then installer.target should pull that in - that doesn't need any kernel command line options.

TBH I'm also not to keen on abusing the debug shell (it may be OK for the installer). For normal and textmode boot we should be using getty with login - for obvious security reasons we don't want to have a root shell without login.

**Comment by mglae** [comment]
One with physical access to the machine can do everything - if there is a debug shell or not. But there is no need to have it by default.

The shell in installer is useful for the rare support cases when installation fails on Generic. 

This PR restores the debug shell for the testing/debugging options that are part of the LibreELEC project for a long time.

**Comment by HiassofT** [comment]
As mentioned in #4494 LE's init handling and systemd units are in desperate need of a revisit, the debug shell is also not working in the other LE targets (like backup restore, FS resize etc).

Instead of adding yet another workaround for underlying problems I'd rather like to start tackling the core issues.

Use of INIT_UNIT in the init script is one of these, a solution would probably be to move that to a systemd generator that changes the default target - like eg systemd's system-update-generator does.

**Comment by HiassofT** [comment]
@mglae please have a look at #4540, alt-f3 console works nicely in installer mode and other target with that PR

**Comment by mglae** [comment]
Closed because of #4540

**Pull request closed without merging**
