### PR TITLE
linux: enable MGLRU in config options

### PR DESCRIPTION
**Pull request by smp79**
https://raw.githubusercontent.com/torvalds/linux/master/Documentation/admin-guide/mm/multigen_lru.rst

Runtime tested on Generic, doesn't seem to break anything.

### CODE REVIEW

**Comment by chewitt** [comment]
Looks interesting, but the project has a long history of people showing up with the latest fashionable kernel tweak only to discover that in a minimalist (non-server, non-desktop) OS where everything already runs in RAM; there's no meaningful improvement. I'd like to see a higher standard of performance testing than "doesn't seem to break anything" please :)

**Comment by smp79** [comment]
That was a [forum user request](https://forum.libreelec.tv/thread/27686-please-enable-mglru-by-default-in-libreelec-with-linux-6-1/). The change looks harmless enough, so I don't see why not.

**Comment by chewitt** [comment]
If we implemented every user request from the forums LE would be a 1.2GB image download and we'd still be supporting i386 hardware. If you read more on this topic, i.e. https://lore.kernel.org/linux-mm/be281873-7c28-12b4-7eb5-50d08042549f@intel.com/ it's quite clear that the change targets and benefits systems under heavy memory pressure. Due to the low footprint of LE (450MB used on a 1GB system) and 1GB being the minimum hardware spec that we support now; most LE systems are not under memory pressure. Thus it would be good to run some performance testing with this change to see whether it has any real world benefit, or understand what conditions that it benefits. If there is proveable benefit we should add the change. If there isn't, we generally choose not to alter the dynamics of a stable kernel config.

**Comment by rsalvaterra** [comment]
@chewitt, that goes both ways, I guess. Case in point: why does the LibreELEC kernel need to reserve 256 MiB of CMA by default on the x86-64 architecture? Or why does it need to have any cgroup controllers enabled (aside from `CONFIG_CGROUPS=y`, which is required by systemd)?

**Comment by chewitt** [comment]
I'm 100% sure there questionnable defconfig options set among our codebase. it would be great to rationalise them, but anyone doing that will be equally requested to show evidence their removal or change does no harm and brings a benefit to the disro. Otherwise we desire minimum change to stable/proven configuration and have a "trust, but verify" approach for suggested changes.

**Comment by popcornmix** [comment]
We do have this enabled on RPiOS kernel.

There was an issue where OOM became common with CONFIG_VMSPLIT_3G (only used on 32-bit Pi4 kernel), where we had to disable MGLRU, but that shouldn't affect you.

We've had this enabled for 6 months or so, so I'm pretty happy it doesn't break anything.
Some anecdotes of it being better, but not a lot of hard evidence (outside of Phoronix benchmarks).

**Comment by HiassofT** [comment]
FYI: Debian x86_64 kernel is built with `CONFIG_LRU_GEN=y` but doesn't enable it by default so it's opt-in (via sysfs). That seems like a reasonable choice but likely adds some overhead compared to `LRU_GEN=n`

```
hias@lenny:~$ grep LRU_GEN /boot/config-6.1.0-13-amd64 
CONFIG_LRU_GEN=y
# CONFIG_LRU_GEN_ENABLED is not set
# CONFIG_LRU_GEN_STATS is not set
```

**Comment by rsalvaterra** [comment]
> There was an issue where OOM became common with CONFIG_VMSPLIT_3G (only used on 32-bit Pi4 kernel), where we had to disable MGLRU, but that shouldn't affect you.

Why would anyone run a 32-bit kernel on a 64-bit CPU? A 32-bit userspace I understand, but the kernel…? That's just insanity.

**Comment by popcornmix** [comment]
> Why would anyone run a 32-bit kernel on a 64-bit CPU? A 32-bit userspace I understand, but the kernel…? That's just insanity

32-bit userspace is needed by some if sdcard is used on older Pi's.
We have since switched the default kernel to 32-bit, but it has introduced a number of issues.
Mostly build files using `arch` (which is kernel's bit-ness) to choose gcc flags (which depends on userspace bit-ness).

**Comment by lrusak** [comment]
> @chewitt, that goes both ways, I guess. Case in point: why does the LibreELEC kernel need to reserve 256 MiB of CMA by default on the x86-64 architecture?

Because x86 can still use drm prime in Kodi which allocates from the cma pool (although it's for sw rendering only where inputstream is used).

Or why does it need to have any cgroup controllers enabled (aside from `CONFIG_CGROUPS=y`, which is required by systemd)? 

Not 100% sure on this one but it could be for docker.

**Comment by smp79** [comment]
I'm changing this to `# CONFIG_LRU_GEN_ENABLED is not set` as suggested by @HiassofT. Anyone who wants MGLRU can just add `echo y >/sys/kernel/mm/lru_gen/enabled` to autostart.sh.

**Comment by rsalvaterra** [comment]
> I'm changing this to `# CONFIG_LRU_GEN_ENABLED is not set` as suggested by @HiassofT. Anyone who wants MGLRU can just add `echo y >/sys/kernel/mm/lru_gen/enabled` to autostart.sh.

That'd be an acceptable compromise, in my humble opinion.

**Review by chewitt — APPROVED** [review]

**Comment by lrusak** [comment]
Should this be added to `distributions/LibreELEC/kernel_options`?

**Pull request merged**
