### PR TITLE
remove all kodi project and arch specific patches

### PR DESCRIPTION
**Pull request by lrusak**
This is just cleanup. We need to start from scratch with a minimal amount of patches.

It is becoming wildly difficult to track all the patches for specific platforms.

We are going to start using our upstream fork https://github.com/libreelec/xbmc

There we can track commit's easier and we can send stuff upstream easier.

We are in pre alpha right now for 9.0 so it is the time to send as much upstream as we can. Especially for amlogic and imx6 hardware.

**This comes from me having to commit all our current patches to our xbmc fork in order to apply for Kodi trademark exemptions. The amount of patches we carry is unacceptable. If people want to test patches they can still PR them to our repo, however before accepting them we need to see that they were sent upstream and if they we accepted/rejected/pending.**

For those that think this is unfair I have been assured that this process will apply to all distributions that are using Kodi. We need to maintain as vanilla experience as possible.

Please ask if you have any questions, thanks

To see the patches we have see:
https://github.com/xbmc/xbmc/compare/Krypton...LibreELEC:libreelec-8.0
https://github.com/LibreELEC/xbmc/compare/libreelec-8.0...LibreELEC:libreelec-8.0-rpi
https://github.com/LibreELEC/xbmc/compare/libreelec-8.0...LibreELEC:libreelec-8.0-wetek_play
https://github.com/LibreELEC/xbmc/compare/libreelec-8.0...LibreELEC:libreelec-8.0-wetek_core
https://github.com/LibreELEC/xbmc/compare/libreelec-8.0...LibreELEC:libreelec-8.0-aarch64
https://github.com/LibreELEC/xbmc/compare/libreelec-8.0...LibreELEC:libreelec-8.0-imx6

### CODE REVIEW

**Comment by CvH** [comment]
What happens if the upstream process isn't working or there is no real maintainer for one of the projects at team kodi (like we already seen) - do we have to ship it broken even if there are working fixes?

**Comment by lrusak** [comment]
@CvH the problem is that the code needs to be documented. We cannot just use out of tree patches without having them sent upstream first. If they are rejected upstream then this is a reason for us to include patches.

If we just continue to pull patches then no work gets sent back upstream and nothing really gets fixed.

**Comment by CvH** [comment]
@lrusak TX for clarification

**Comment by lrusak** [comment]
Objections? Would be nice to get this in for the trademark proposal.

**Comment by MilhouseVH** [comment]
How will each LE project pull in Kodi patches in future - will it build from the entire LE/xbmc tree, presumably a project specific branch or rev? If so, will common patches have to be applied (and maintained) on every project branch?

**Comment by lrusak** [comment]
merge?

**Comment by MilhouseVH** [comment]
I asked for clarification on how different projects are meant to build once this merges, but haven't seen a reply. I assume there's more to come as I don't see how we can build master after merging this PR, so it's either incomplete or needs to be merged with additional PRs.

**Comment by vpeter4** [comment]
As written in slack I will continue to build my own imx6 images regarding what is in libreelec repository.

**Comment by lrusak** [comment]
As written in slack,

The builds will be very close to vanilla Kodi after this PR other than our LibreELEC specific patches. What does this mean to users? Well the RPi optimizations will be gone from master, @MilhouseVH can continue to use them. If users want to self build with these patches that is ok too, we still include all the tools needed to make the patches.

During this alpha period we need to clean up as much as possible and make a push for things to go upstream. If by the time we reach beta (probably not for 10 months) we can reevaluate where we are and what is needed. Until that time I want to work together with Kodi and do as much as I can to not need these project specific patches anymore. If others want to help that is awesome, if I'm by myself on this then so be it.

**Comment by chewitt** [comment]
I'm confident that LE 9.0 is going to ship with a few patches same as 8.0 and 7.0 have done. The only difference is they'll be applied to a git repo not a filesystem, and with a little effort here and there the overall deviation from default Kodi will be reduced by thousands of lines of code (which went upstream). We need to adjust to a new workflow, and some of us old dogs will learn the new trick slower (expect some really dumb Q's from me). This is just a overdue reduction in technical debt. The sky isn't going to fall on anyone's head. In six month's we'll look back and wonder why we didn't do it sooner. And if somehow things don't work out, there's a revert button.

**Pull request merged**
