### PR TITLE
tbs-linux-drivers: remove drivers

### PR DESCRIPTION
**Pull request by CvH**
- these drivers are useless

### CODE REVIEW

**Comment by ozkaradag** [comment]
Greetings,

Dear friend, what is this TBS model for?
For which system?

Best regards...

**Comment by CvH** [comment]
@ozkaradag that are DVB drivers for TBS cards, these drivers weren't included in LE at all and are now superseded because we have them included via media_build

**Comment by ozkaradag** [comment]
Greetings,

I am very grateful for the information.

Well, dear master, I did not see the TBS 5990 in Media_Build. Is he not supported?

Best regards...

**Comment by CvH** [comment]
@ozkaradag https://github.com/tbsdtv/linux_media/wiki
look there for supported devices

**Comment by ozkaradag** [comment]
Greetings,

Thanks.

Great, these are devices like the ARM processor (like the S905 SoC) that run on the LibreELEC system?

Best regards...

**Comment by CvH** [comment]
We have currently no support for this at the AMLogic devices, but wrxtasy and kszaq have builds with this media_build in our forums that support this (S8xx/S905). The "normal" DVB drivers from the AMLogic devices support near to nothing DVB wise. It is likely that this gets merged into normal images too, but no time frame for this.

**Comment by ozkaradag** [comment]
Thank you very much for infos.

Best regards...

**Pull request merged**
