### PR TITLE
[Allwinner,Generic,Rockchip] linux: Update to 5.10.11

### PR DESCRIPTION
**Pull request by jernejsk**
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.5
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.6
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.7
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.8
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.9
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.10
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.11

Note: it was only build tested on AW.

/cc @knaerzche

### CODE REVIEW

**Comment by heitbaum** [comment]
You also need to delete projects/Generic/patches/linux/linux-100-temporary_i915_haswell_black_screen_fix.patch (for Generic) included in 5.10.9

ref: https://gitlab.freedesktop.org/drm/intel/-/issues/2024

**Comment by jernejsk** [comment]
I was hoping someone would actually build and test this PR on Generic and provide fixes...

**Comment by heitbaum** [comment]
I have been building 5.10.10. I have just cp’ed your PR. Will left you know once I do a full clean build though. I’m happy to add the Generic commit :-)

**Comment by SupervisedThinking** [comment]
@jernejsk looks like `linux-0020-drm-from-5.11.patch` for RK was included in 5.10.10 too

https://github.com/SupervisedThinking/LibreELEC-RR/commit/aa86fe5ef59a933e1c7fa8a593e341516333ff62#diff-ae40bca272825c429f33ecde254d7fa3779be3843fe25bd54954258bc2c4f16d

**Comment by jernejsk** [comment]
@knaerzche volunteered to add RK update

**Comment by heitbaum** [comment]
@jernejsk - my build didn’t go as planned (will look into it more after work) The PR for the patch delete the patch is with you. 

```
  AS      arch/x86/entry/thunk_64.o
arch/x86/entry/thunk_64.o: warning: objtool: missing symbol table
make[3]: *** [scripts/Makefile.build:360: arch/x86/entry/thunk_64.o] Error 1
make[3]: *** Deleting file 'arch/x86/entry/thunk_64.o'
make[2]: *** [scripts/Makefile.build:496: arch/x86/entry] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by heitbaum** [comment]
@jernejsk - building correctly now

    ...
    INSTALL sound/usb/usx2y/snd-usb-us122l.ko
    INSTALL sound/usb/usx2y/snd-usb-usx2y.ko
    INSTALL sound/x86/snd-hdmi-lpe-audio.ko
    DEPMOD  5.10.11

    50ded84eeb (HEAD -> testb) linux: Update to 5.10.11 [heitbaum]
    56b8bf34a2 Generic: linux: Remove patches included in 5.10.9 [heitbaum]
    2dfbccbad0 (upstream/master, master) Merge pull request #5053 from jernejsk/r40-dt-fix [GitHub]

with regard to https://lkml.org/lkml/2021/1/14/387 - issue only occurring in my https://github.com/heitbaum/LibreELEC.tv/tree/dev tree, in my build tree it is ok.

GTG from my perspective if you pull https://github.com/heitbaum/LibreELEC.tv/tree/kernel_update into the PR.

Will run test once full clean build finishes.

**Comment by jernejsk** [comment]
This PR is now ready for review and merging.

**Comment by mglae** [comment]
@jernejsk Please add cosmetic generic config update: https://github.com/mglae/LibreELEC.tv/commit/542d47957deb86756eca308b9525b103edd190fc

@CvH Can you test at your Haswell device after PR merge?

**Comment by jernejsk** [comment]
Done

**Review by mglae — APPROVED** [review]
For Generic it is ready to be merged.

**Comment by CvH** [comment]
@heitbaum @mglae not sure if you are using different downstrems ??

while building
```
    APPLY PATCH (project)      projects/Generic/patches/linux/linux-100-temporary_i915_haswell_black_screen_fix.patch
patching file drivers/gpu/drm/i915/gt/intel_ring_submission.c
Hunk #1 FAILED at 2083.
1 out of 1 hunk FAILED -- saving rejects to file drivers/gpu/drm/i915/gt/intel_ring_submission.c.rej
```

**Comment by heitbaum** [comment]
Looks like this got missed.
https://github.com/jernejsk/LibreELEC.tv/pull/5

**Comment by jernejsk** [comment]
hm... this patch is supposed to be removed in this PR

**Comment by heitbaum** [comment]
https://github.com/jernejsk/LibreELEC.tv/pull/5/commits/907b72dccdb3b480efd8ccb7219acd374d8c5a96

**Comment by jernejsk** [comment]
Could be rebase issue.

**Pull request merged**
