### PR TITLE
Image script : allow to execute a distro image script prior to image script

### PR DESCRIPTION
**Pull request by LongChair**
This allosw to run some operation, specifically to compute the CUSTOM_IMAGE_NAME

### CODE REVIEW

**Comment by lrusak** [comment]
seems sane to me 👍

**Comment by MilhouseVH** [comment]
Couldn't `CUSTOM_IMAGE_NAME` be formulated in a distro-specific `options` file?

https://github.com/plexinc/LibreELEC.tv/blob/upstream-pr/config/options#L41-L49

**Comment by LongChair** [comment]
Well that name is computed with git operations, and it looks like the option file is sourced in many places.

Probably a bit to much to execute that in there.

**Comment by MilhouseVH** [comment]
If you exported `CUSTOM_IMAGE_NAME` wouldn't you only need to compute it when it is blank, ie. once?

I'm just not sure this change is necessary when there are potentially alternative solutions that don't require the addition of optional scripts.

**Comment by LongChair** [comment]
I understand you point, although semantically it's probably not very nice to "execute" code in a file that is supposed to define options or ? 
But I agree that technically that could be part of the distro option file.

**Comment by MilhouseVH** [comment]
As long as it's not a full-on program, executing a few commands to generate the value for the variable shouldn't be an issue, it's the kind of thing that's already done in `config/options`: https://github.com/plexinc/LibreELEC.tv/blob/upstream-pr/config/options#L74

**Comment by LongChair** [comment]
The script we have behind is not a one-liner, but anyways :)

So that is a No-go right ? :)

**Comment by MilhouseVH** [comment]
If you can solve it via options, I'd prefer that - I don't currently see any other use/need for this extra script other than what you are trying to do, which you can do in options, so yes, no-go from me.

**Comment by LongChair** [comment]
ok :)

**Pull request closed without merging**
