### PR TITLE
Retroplayer Support Scripts

### PR DESCRIPTION
**Pull request by lrusak**
I use these to update all the emulators and the binary add-ons.

### CODE REVIEW

**Comment by lrusak** [comment]
rebased

note that it looks at my repo (https://github.com/lrusak/repo-binary-addons/tree/retroplayer) because the game add-ons haven't been merged into the upstream repo (I'm not sure if or when that will happen) maybe a question for @garbear or @MartijnKaijser

**Comment by garbear** [comment]
I think the major issue is the download size of a Kodi with 60 libretro cores. Binary add-ons in a repo would solve this... how does LE deal with different architectures? Is this something we could do for Kodi?

**Comment by lrusak** [comment]
@garbear I totally understand. They need a binary add-on repo.

We host binary add-ons for each architecture within a certain platform.

so:

Generic (Virtual uses Generic add-ons) (x86_64)
RPi2 (armhf)
RPi (armv6)
WeTek_Core (WeTek_Play uses WeTek_Core add-ons) (armhf)
Odroid_C2 (WeTek_Hub, WeTek_Play_2 uses Odroid_C2 add-ons) (aarch64)

we can reuse some add-ons because the platforms share SOC so they all use the same libgl and other support libraries.

**Comment by garbear** [comment]
Well, a binary add-on repo is what's stopping Kodi from announcing RetroPlayer, so if there's anything I can do to help (given my limited build system skill) I'd like to know. For Ubuntu, we need to package .debs, and Debian doesn't allow external CMake projects during build, so we need to use source tarballs or somehow transclude the RetroArch cores.

**Comment by lrusak** [comment]
@garbear it's exactly the same way it works for the regular add-ons, however, each platform has a specific repo that they look at. The rest is handled normally.

no need to deb's or tar as kodi uses zip files for all it's add-ons.

I'd like to see kodi updated to use tar.gz or tar.xz to minimize the add-on size. I think @vpeter4 has something for that already.

see, https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/mediacenter/kodi/config/repository.libreelec.tv/addon.xml#L8
and, https://github.com/LibreELEC/LibreELEC.tv/blob/master/distributions/LibreELEC/options#L188-L193

**Comment by garbear** [comment]
@fetzerch, @hudokkow, @wsnipex, can you chime in to say what we need for a game add-on repo to happen?

**Pull request merged**
