### PR TITLE
use libressl's shipped ca bundle

### PR DESCRIPTION
**Pull request by lrusak**
thanks @stefansaraev 

This is a nice cleanup and one less thing to worry about updating.

@MilhouseVH can you make sure that what we fixed before with the cacerts doesn't break with this PR?

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Seems to be OK, YouTube addon is working, I'm not seeing any Python issues (https://github.com/OpenELEC/OpenELEC.tv/issues/3749) and curl download from https is also working (https://github.com/OpenELEC/OpenELEC.tv/issues/4137).

**Comment by MilhouseVH** [comment]
Possible issue reported here: http://forum.kodi.tv/showthread.php?tid=269814&pid=2315618#pid2315618

```
14:42:14  36.327782 T:1463940000   ERROR: ERROR:root:Network error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
14:42:14  36.330311 T:1463940000  NOTICE: plugin.audio.pandoki Auth BAD
14:42:22  43.938244 T:1463940000   ERROR: ERROR:root:Network error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
14:42:22  43.941467 T:1463940000  NOTICE: plugin.audio.pandoki Auth BAD
14:42:23  44.825291 T:1961758720   ERROR: GetDirectory - Error getting plugin://plugin.audio.pandoki/
14:42:23  44.825710 T:1961758720   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.pandoki/) failed
```

I've no idea what Pandoki is, presumably something to do with Pandora?

**Comment by lrusak** [comment]
seems there is a bug in libressl, https://marc.info/?l=openbsd-tech&m=146106898531324&w=2

using
```
openssl s_client -showcerts -connect tuner.pandora.com:443
```
I get 
>Verify return code: 20 (unable to get local issuer certificate)

**Comment by MilhouseVH** [comment]
Since this Pandoki error isn't in the last OE test build (#0415), this error must be due to this change?

**Comment by Kwiboo** [comment]
The script used by libressl to reorder the bundled cacert file do not handle certificates with same name correctly, it overwrites certificates with same name. It is also missing some certificates compared to the curl/mozilla cacert file.

**Comment by lrusak** [comment]
@Kwiboo so is there any quick fix other than a revert?

**Comment by Kwiboo** [comment]
libressl must also have the last certificate in the chain provided by the server in its cacert file to validate the certificate, I backported the trusted-first option from openssl 1.0.2 to libressl go get around this but unsure if it is a 100% secure and working backport, see https://github.com/RasPlex/OpenPHT-Embedded/blob/openpht-1.5/packages/security/libressl/patches/libressl-trusted-first.patch
I also switched to a cacert file with the 1024 bit certificates mozilla have dropped at the same time.

**Comment by lrusak** [comment]
@stefansaraev what do you think? I think we can use that patch

**Comment by Kwiboo** [comment]
The patch does not seem to help with pandora, since none of the certificates in their chain is included in libressl's cert.pem file.

The root certificate used by pandora has been removed from libressl's cert.pem file, see https://github.com/libressl-portable/openbsd/commit/26b200b1a0b2b07c7762c5f1d118647c631ce7b2

**Comment by lrusak** [comment]
Ah thanks, we could patch that back in

**Comment by stefansaraev** [comment]
> Ah thanks, we could patch that back in

you better dont do that.

**Comment by Kwiboo** [comment]
tuner.pandora.com have a certificate with a fingerprint in the intermediate chain that is trusted by libressl, but it is not the same version of the certificate that is sent from the server as in cert.pem.
Possible https://github.com/openssl/openssl/commit/9a1f59cd3128ddac73d3e0721ecd55935f53ba8b will need backporting to trust a certificate in the intermediate chain in addition of instead of the trusted first patch to make tuner.pandora.com trusted

**Pull request merged**
