### PR TITLE
mesa: update to mesa-20.1.0

### PR DESCRIPTION
**Pull request by nouman8**

### CODE REVIEW

**Comment by chewitt** [comment]
@nouman8 please squash the two commits into one, thanks

**Comment by chewitt** [comment]
Now I'm seeing 3x commits :)

Run `git rebase -i HEAD~3` and it will open a list in a text editor. Leave the first commit (reading top-down) with `pick` and change the next two to `fixup` then save/close, and it will rebase and squash the 2nd/3rd commit into the first, leaving only one commit. Then `git push -f origin mesa-update` and it will push the changes to GitHub and update the PR.

**Comment by nouman8** [comment]
git push -f origin mesa-update this command says "Everything up-to-date".

**Comment by nouman8** [comment]
Done :) ...
Thanks for Helping out.!!

**Comment by CvH** [comment]
superseded by https://github.com/LibreELEC/LibreELEC.tv/pull/4415

tx

**Pull request closed without merging**
