### PR TITLE
packages: various updates (Q1 2020)

### PR DESCRIPTION
**Pull request by MilhouseVH**
Bumping various packages.

Test built `image` for `A64`, `RPi`, `RPi2` and `Generic` without issue. Currently building `all` addons.

### CODE REVIEW

**Comment by vpeter4** [comment]
What about librespot, rust and rustup.rs ? Maybe they would get librespot addon working again. According to forum addon has issues.

**Comment by awiouy** [comment]
I am not aware of librespot issues.
Anyways, I am working on librespot gapless playback, which I intend to push as soon as it is merged to librespot. I am also pondering switching from pulseaudio to pipe/ffmpeg in order to reduce latency.

**Comment by MilhouseVH** [comment]
@vpeter4 this PR relates to the "core" packages (those needed to build `image`), as I worked through `packages/audio`, `packages/compress` etc. - and I haven't looked at `packages/addons` as bumping `addon-depends` is best handled in a separate PR (ideally from the add-on maintainers). In addition, bumping the add-ons themselves is typically handled when we bump kodi (where possible).

Additional PRs are, of course, welcome. :smile:

Disclaimer: Not every "core" package that could be bumped has been bumped in this PR. For example the latest `qemu-4.2.0` isn't building right now (fails to find `-lpixman-1`).

**Comment by MilhouseVH** [comment]
Revert `glm-0.9.7` as `cmake install` has been removed in `0.9.6`, making the package basically unusable without manual workarounds and hacks. Crazy.

Issues:
https://github.com/g-truc/glm/issues/947
https://github.com/g-truc/glm/issues/961
https://github.com/g-truc/glm/issues/962

PR with potential future fix, of sorts:
https://github.com/g-truc/glm/pull/968

**Comment by MilhouseVH** [comment]
Possible (hopefully temporary) install fix pushed for `glm-0.9.9.7`.

**Pull request merged**
