### PR TITLE
[le10] Update kodi deinterlace patches for Allwinner and Rockchip

### PR DESCRIPTION
**Pull request by HiassofT**
Completely untested except unpacking kodi sources+patches so it should at least fix the CI build error.

I replaced the deinterlace patches with the versions we use on RPi and I added back the LOGERROR->LOGDEBUG change for RK.

@jernejsk @knaerzche please give this a try and report back if it works fine.

### CODE REVIEW

**Comment by jernejsk** [comment]
It seems to work fine on H6. What are improvements of updated patches?

**Comment by HiassofT** [comment]
No improvements, just rebased (by @popcornmix) so they apply on kodi in LE10 branch with DRM PRIME PR (i.e. fix CI builds and get up to date)

**Comment by HiassofT** [comment]
@knaerzche gentle ping, could you test this on RK? Would be nice to get the fix in

**Comment by knaerzche** [comment]
> @knaerzche gentle ping, could you test this on RK? Would be nice to get the fix in

Srry, didn't notice this one. GTG for RK also.

**Review by knaerzche — APPROVED** [review]

**Comment by heitbaum** [comment]
Builds all completed successfully with the addition of this PR for both Allwinner and Rockchip.

**Pull request merged**
