### PR TITLE
libbluray: bump to 1.0.2

### PR DESCRIPTION
**Pull request by adamg88**
This PR bumps libbluray to 1.0.2

### CODE REVIEW

**Comment by MilhouseVH** [comment]
What is the source of the Nevcairie_v1.0.2.patch, as it doesn't look as though Nevcariel (Hendrik Leppkes) has released 1.0.2 yet (http://git.1f0.de/gitweb?p=libbluray.git;a=summary;js=1).

**Comment by lrusak** [comment]
@MilhouseVH what is this patch for in the first place? It doesn't look like Kodi includes it in their depends build

**Comment by MilhouseVH** [comment]
From @popcornmix: "The tree contains code for parsing MPLS and CLPI from the bluray which is required for 3D playback." So this helps improve 3D playback on RPi which is where we originally got this from (newclock5 branch).

**Comment by adamg88** [comment]
Closing PR as I deleted original repository that I made the PR from

@MilhouseVH nevcairiel 1.0.2 patch is available @ https://github.com/LibreELEC-AML/LibreELEC.tv/commit/6cff4d9b1ae45410ef052a55edc11222f0688634 I don't know why it's not in that git repository though

**Pull request closed without merging**
