### PR TITLE
[le90] kodi: update to 18.1

### PR DESCRIPTION
**Pull request by HiassofT**
backport of #3300

### CODE REVIEW

**Comment by HiassofT** [comment]
build and runtime test for RPi2 and RockPro64 was fine.

No x86_84 test hardware here, I leave that to someone else :-)

**Comment by 5schatten** [comment]
tested with current master on x86-64 / RPi / KVIM and works fine.

**Comment by HiassofT** [comment]
RPi/Generic kodi updated to 18.1, Rockchip update missing ATM

build-tested for RPi2

**Comment by HiassofT** [comment]
added rockchip bump

**Pull request merged**
