### PR TITLE
kodi: update to 20.0a1-Nexus

### PR DESCRIPTION
**Pull request by HiassofT**
Only build-tested for RPi4 yet

### CODE REVIEW

**Comment by HiassofT** [comment]
Runtime test on RPi4 was fine

**Comment by SupervisedThinking** [comment]
build & run tested on Vim3

**Comment by heitbaum** [comment]
Initial feedback - build regression in my dev tree. checking through logs now.

[281.txt](https://github.com/LibreELEC/LibreELEC.tv/files/8745869/281.txt)

**Comment by heitbaum** [comment]
```
=== tested on ===
Generic.x86_64-devel-20220521004337-34efe25
Linux nuc11 5.18.0-rc7 #1 SMP Sat May 21 01:25:33 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.701) Git:20.0a1-Nexus). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2022-05-21 by GCC 12.1.0 for Linux x86 64-bit version 5.18.0 (332288)
Running on LibreELEC (heitbaum): devel-20220521004337-34efe25 11.0, kernel: Linux x86 64-bit version 5.18.0-rc7
FFmpeg version/source: 4.4-Kodi
Host CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 8 cores available
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0042.2021.1213.1702 12/13/2021
CApplication::CreateGUI - trying to init gbm windowing system
RetroPlayer[PROCESS]: Registering process control for GBM
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_RENDERER = Mesa Intel(R) Xe Graphics (TGL GT2)
GL_VERSION = OpenGL ES 3.2 Mesa 22.1.0
libva info: VA-API version 1.14.0
vainfo: VA-API version: 1.14 (libva 2.14.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.4.1 (34efe256579)
```

**Review by CvH — APPROVED** [review]

**Pull request merged**
