### PR TITLE
Odroid_C2: initial project

### PR DESCRIPTION
**Pull request by lrusak**
I think this is about ready. I'd like to have some other eyes look over the changes.

@vpeter4 can you look at the u-boot changes? Maybe we can work on cleaning up u-boot, it's an ugly mess.

maybe some of the amlogic guys can jump in and have a look also @kszaq @codesnake

### CODE REVIEW

**Comment by LongChair** [comment]
Did u changed the linux config flags that was missing over the weekend ? `GENERIC_CPUFREQ_CPU0` iirc

**Comment by vpeter4** [comment]
Seems fine to me.
But as I already wrote few times I'm using two u-boot packages in imx6 package folder anyway.

**Comment by kszaq** [comment]
I have only recently started looking at S905 so I don't know whether this question is relevant.. but are libhybris/mfc patches needed for Kodi?

**Comment by lrusak** [comment]
No objection so should be good to go 👍

**Pull request merged**
