### PR TITLE
buildsystem: cmake: allow specifying our optimization level

### PR DESCRIPTION
**Pull request by mglae**
This PR was triggered by #5486, first commit is a fix for this.

---

Looking at build.ninja I've noticed the optimizations are not set as expected. For e.g. building kodi's  CMakeFiles/kodi.dir/xbmc/platform/posix/main.cpp.o the flags are:
```
FLAGS = -march=x86-64 -m64 -mmmx -msse -msse2 -mfpmath=sse -Wall -pipe -O3 -fomit-frame-pointer -Os -DNDEBUG -flto=12 -fno-fat-lto-objects -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_UDMABUF=1 -DHAVE_LINUX_DMA_HEAP=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_MKOSTEMP=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_STATX=1 -DHAVE_SSE=1 -DHAVE_SSE2=1 -DHAVE_SSE3=1 -DHAVE_SSSE3=1 -DHAVE_SSE4_1=1 -D__STDC_CONSTANT_MACROS -D_FILE_OFFSET_BITS=64 -DHAS_POSIX_NETWORK -DHAS_LINUX_NETWORK -DHAS_BUILTIN_SYNC_ADD_AND_FETCH=1 -DHAS_BUILTIN_SYNC_SUB_AND_FETCH=1 -DHAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP=1 -DHAVE_INOTIFY=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAS_ALSA=1 -DHAS_AVAHI=1 -DHAS_ZEROCONF=1 -DHAVE_LIBBLURAY=1 -DHAVE_LIBBLURAY_BDJ=1 -DHAVE_LIBCEC=1 -DHAS_DBUS=1 -DHAS_ISO9660PP=1 -DHAS_LIRC=1 -DHAS_WEB_SERVER=1 -DHAS_WEB_INTERFACE=1 -DHAS_FILESYSTEM_NFS=1 -DHAS_NFS_SET_TIMEOUT -DHAS_AIRPLAY=1 -DHAS_PULSEAUDIO=1 -DHAS_PYTHON=1 -DHAS_FILESYSTEM_SMB=1 -DHAVE_LIBUDEV=1 -DHAS_UDFREAD=1 -DHAVE_LIBXSLT=1 -DHAVE_LIBVA=1 -DHAS_GLX=1 -DHAVE_LIBVDPAU=1 -DFFMPEG_VER_SHA=\"4.3\" -I/home/docker/LibreELEC.tv/build.LibreELEC-Generic.x86_64-10.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/fribidi -DSPDLOG_FMT_EXTERNAL -DSPDLOG_DEBUG_ON -DSPDLOG_NO_ATOMIC_LEVELS -DSPDLOG_ENABLE_PATTERN_PADDING -DHAS_EGL=1 -DHAVE_X11=1 -DHAVE_LIBXRANDR=1 -DHAVE_HDR_OUTPUT_METADATA=1 -DHAS_GL=1 -DHAS_MARIADB=1 -DHAS_UPNP=1 -DHAS_DVD_DRIVE -DHAS_CDDA_RIPPER -DHAS_AIRTUNES=1 -DBIN_INSTALL_PATH=\"/usr/lib/kodi\" -DINSTALL_PATH=\"/usr/share/kodi\" -std=c++14
```
The -O3 optimization set with `+speed` since #3524 is overwritten with -Os.

Using `-DCMAKE_BUILD_TYPE=MinSizeRel` for targets result in finally building with -Os.

Changing to default `-DCMAKE_BUILD_TYPE=""` is not allowed by to many packages including
Kodi, they are forcing a default option (in worst case "Debug", e.g. llvm)

Redefine the cmake parameters to not include any options and do the same for host choosing
"Release" as build type.

---

An additional improvement is to specify -NDEBUG for all release builds. From my tests only libstatgrab is failing to build with this define. The patch is already accepted upstream.

---

Allowing the speed optimizations does increase the size of SYSTEM. My Generic test build is using ~~293474304~~ 262602752 bytes  while current nightly is at 254210048. That is no fault of this PR. If a smaller size is wanted we can now remove +speed and/or use +size on package level.

Edit: Did further testing and fixed wrong SYSTEM size.

From a clean Generic build (of libreelec-10.0 branch) the following target packages are affected:
```
zlib (target)
expat (target)
lzo (target)
libjpeg-turbo (target)
taglib (target)
rapidjson (target)
libfmt (target)
libftdi1 (target)
flatbuffers (target)
spdlog (target)
soxr (target)
p8-platform (target)
libcec (target)
mariadb-connector-c (target)
gmmlib (target)
media-driver (target)
llvm (target)
kodi (target)
kodi-platform (target)
peripheral.joystick (target)
```
Largest package is likely kodi, changing the build flag options for it result in:

build flag | optimization | SYSTEM size
--- | --- | ---
+speed | -O3 | 262602752
w/o | -O2 | 261644288
+size | -Os | 259506176

### CODE REVIEW

**Comment by vpeter4** [comment]
Why removing `CMAKE_C_FLAGS/CMAKE_CXX_FLAGS` and not fixing problem itself?

**Comment by mglae** [comment]
cmake is initializing its CMAKE_*_FLAGS from *FLAGS environment variables. No need to try it explicit.

I have no idea what the intention of the not working parameter passing was.

**Comment by vpeter4** [comment]
If *FLAGS are actually used then it's ok.

Regarding parameter passing: You can't set any -D*** parameter with spaces in PKG_CMAKE_OPTS_TARGET.

**Comment by mglae** [comment]
Forgot the [link](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS.html).

> Regarding parameter passing: You can't set any -D*** parameter with spaces in PKG_CMAKE_OPTS_TARGET.

This apply to all PKG\_*\_OPTS\_\* variables when parameter with spaces are needed. It is the reason for using `make CFLAGS="$CFLAGS" ...` in several packages.

**Comment by vpeter4** [comment]
> This apply to all PKG_*_OPTS_* variables when parameter with spaces are needed. It is the reason for using `make CFLAGS="$CFLAGS" ...` in several packages.

Which one has make CFLAGS because of spaces?

**Comment by mglae** [comment]
Rebased. Commit "llvm: fix passing compile options building target " is included in #5561

**Comment by mglae** [comment]
The libstatgrab patch is included in update of #5631, removed.

**Review by CvH — APPROVED** [review]

**Pull request merged**
