### PR TITLE
Package updates: update kodi, ffmpeg, libcec

### PR DESCRIPTION
**Pull request by MilhouseVH**
Bring Kodi 18a1 up to date.

Updated ffmpeg with latest HEVC optimisations.

libcec to 4.0.2, may require some WeTek fixes - need to build again.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Dropped `linux-052-XBOX_remote_support.patch` from `media_build` as `lirc_xbox` is already present in 4.10.4 kernel.

**Comment by MilhouseVH** [comment]
All projects build with this PR.

**Comment by lrusak** [comment]
g2g?

**Comment by MilhouseVH** [comment]
Updated to latest kodi18a1 (and matching binary addons).

Added `rapidjson` package as Kodi has switched from `yajl` (but keeping `yajl` package, as it's needed by `mpd` addon).

Build tested, all fine - we should get this in before something else changes. :)

**Pull request merged**
