### PR TITLE
[le11] Add support for irtoy

### PR DESCRIPTION
**Pull request by BellaCoola**
This branch adds support for irtoy kernel module on x86-64 architecture to support compatible IR receivers / transmitters.

### CODE REVIEW

**Comment by heitbaum** [comment]
- Please update the commit message to house style: `git ls | grep linux` to see some examples.
- Should this be updated only for Generic?

**Comment by HiassofT** [comment]
Yes, this should be enabled for Allwinner, Amlogic and NXP as well (RPi and Rockchip already build the module)
```
hias@lenny:~/private/libreelec/libreelec-git$ git grep CONFIG_IR_TOY projects/
projects/Allwinner/linux/linux.aarch64.conf:# CONFIG_IR_TOY is not set
projects/Allwinner/linux/linux.arm.conf:# CONFIG_IR_TOY is not set
projects/Amlogic/linux/linux.aarch64.conf:# CONFIG_IR_TOY is not set
projects/Generic/linux/linux.x86_64.conf:# CONFIG_IR_TOY is not set
projects/NXP/devices/iMX6/linux/linux.arm.conf:# CONFIG_IR_TOY is not set
projects/NXP/devices/iMX8/linux/linux.aarch64.conf:# CONFIG_IR_TOY is not set
projects/RPi/devices/RPi/linux/linux.arm.conf:CONFIG_IR_TOY=m
projects/RPi/devices/RPi2/linux/linux.arm.conf:CONFIG_IR_TOY=m
projects/RPi/devices/RPi4/linux/linux.aarch64.conf:CONFIG_IR_TOY=m
projects/Rockchip/devices/RK3288/linux/default/linux.arm.conf:CONFIG_IR_TOY=m
projects/Rockchip/devices/RK3328/linux/default/linux.aarch64.conf:CONFIG_IR_TOY=m
projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf:CONFIG_IR_TOY=m
```

**Comment by BellaCoola** [comment]
@heitbaum Thank you very much for your feedback. I updated the commit messages to follow the style of other commit messages.

@HiassofT In my further commit I enabled this kernel module for all architectures.

**Review by HiassofT — APPROVED** [review]

**Comment by HiassofT** [comment]
thanks!

**Pull request merged**
