### PR TITLE
Make docker not slowing down boot proccess

### PR DESCRIPTION
**Pull request by queeup**
If you have multiple docker containers, boot process is slowing down drastically. Lets docker starting lastly.

### CODE REVIEW

**Comment by chewitt** [comment]
@aptalca I'd appreciate your input on whether this is a good idea?

**Comment by queeup** [comment]
Let me share some numbers about this change. This times is belonging to 4 container created with compose on the system.

Type=idle | Type=notify
------------ | -------------
Startup finished in 6.344s (kernel) + 13.178s (userspace) = 19.523s | Startup finished in 7.111s (kernel) + 52.797s (userspace) = 59.908s
kodi.target reached after 13.178s in userspace | kodi.target reached after 52.794s in userspace 
type_is_idle | type_is_notify

**Comment by lrusak** [comment]
How are you starting your containers? You clearly aren't using systemd services for each container (which I would recommend).

**Comment by queeup** [comment]
Yes you are right. I am not using systemd for containers. Just `docker create` and `start` commands without `--rm` option.

**Comment by aptalca** [comment]
At first glance, it looks like with `notify`, kodi is not started until the docker service is fully up and reports back whereas with `idle`, kodi does not wait for the report back from the docker daemon and only waits for the start of the service.

I'm thinking that as long as kodi is not reliant on docker service to be up for any critical operations, it probably would be fine (perhaps desired?). I'll do some tests locally as well.

**Comment by chewitt** [comment]
@aptalca any further thoughts?

**Comment by aptalca** [comment]
Still doing some tests, but having a hard time reproducing the slow down. Kodi still comes up in under 20 sec on an rpi4 with several containers, some created via addon, some cli.

I had a theory based on the following forum post, but it didn't quite go anywhere: https://forum.libreelec.tv/thread/22128-docker-created-on-restart/

I have a few more tests planned. I should have an answer in a few days

**Comment by lrusak** [comment]
Do we rely on docker containers being up before kodi for any reason? Say for a MySQL server?

**Comment by aptalca** [comment]
No, not really. For the mariadb addon, we make sure it starts before kodi via its service file

**Comment by aptalca** [comment]
Finally had some more time to test. With over a dozen containers, half addons (systemd managed) and half docker cli created (restarted by the docker service on boot), I was able to reproduce some slow down, where boot was taking about 36 sec as opposed to 20 sec. The suggested change in the PR reduced boot time to about 30 sec so there was improvement, and no negative side effects were observed.

The start of cli created containers on boot is handled directly by the docker service (when set to auto restart) and with `notify` docker service waits until all of those containers are up and reporting healthy before it reports back as started. During which time, other services depending on the docker service will wait. With some slow starting containers, the whole boot process can slow down. With `idle` on the other hand, docker service does not wait for the containers to go up and reports as started immediately. That way, other services dependent on docker service do not wait for docker service managed containers to go up first.

Since those containers are not required to be up prior to kodi start, I see no issues with this PR and there is benefit in some extreme cases (many and/or slow containers managed by docker service)

**Pull request merged**
