### PR TITLE
mesonbuild: udate to 0.52

### PR DESCRIPTION
**Pull request by InuSasha**
build tested (incl. addons) for: Generic, RPi2

### CODE REVIEW

**Comment by 5schatten** [comment]
I guess you should apply `PKG_BUILD_FLAGS="+pic +pic:host"` to https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/compress/xz/package.mk#L14

**Comment by MilhouseVH** [comment]
With the xz patch from @5schatten, this now builds fine on RPi/RPi2/Generic (Ubuntu 16.04).

**Comment by InuSasha** [comment]
add patch from @5schatten

**Comment by 5schatten** [comment]
Builds & runs here fine on Generic/RPi2/RK3399

**Pull request merged**
