### PR TITLE
Upstream changes

### PR DESCRIPTION
**Pull request by lrusak**
Mostly cleanup and some package updates and some new patches.

### CODE REVIEW

**Comment by MikeBuzz** [comment]
Re: 	ffmpeg: add upstream patches from popcornmix       44326c4

These have already been included as patches for only the RPi2 project it would seem

**Comment by lrusak** [comment]
thanks @MikeBuzz maybe @MilhouseVH can comment on this.

**Comment by MilhouseVH** [comment]
ffmpeg: Yes, they were included only for RPi2 as they're mostly HEVC optimisations which the RPi1 cannot do, so no point including for that project. Including these ffmpeg patches in only the RPi2 project folder was simply a way to minimise risk of breakage to any other projects for the Kodi 16 release, and then we'd move them to the ffmpeg package at the start of Kodi 17 testing.

I have no real objection if you want to add the patches to the ffmpeg package, although they've only really been tested in my RPi/RPi2/Generic builds and I've no idea what (if any) effect they will have on Wetek, imx6 etc. Probably no effect, but you never know...

**Comment by lrusak** [comment]
That's fine, I'll just drop the commit

**Comment by lrusak** [comment]
updated and dropped the offending commit

**Comment by MilhouseVH** [comment]
Building static libtinyxml2 breaks pvr.dvblink which expects it shared:
```
rpi22:~ # ldd /usr/lib/kodi/addons/pvr.dvblink/pvr.dvblink.so.3.1.1
ldd: $warning: you do not have execution permission for `/usr/lib/kodi/addons/pvr.dvblink/pvr.dvblink.so.3.1.1'
        linux-vdso.so.1 (0x7ee12000)
        /lib/libarmmem.so (0x76f55000)
        libtinyxml2.so.1 => not found
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x76e15000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x76de9000)
        libc.so.6 => /lib/libc.so.6 (0x76cb5000)
        libm.so.6 => /lib/libm.so.6 (0x76c37000)
        /lib/ld-linux-armhf.so.3 (0x54b0e000)
```

Any ideas on how to fix pvr.dvblink?

**Pull request merged**
