### PR TITLE
mono: create addon

### PR DESCRIPTION
**Pull request by awiouy**
Hello,
I saw on the fora requests/efforts to bring mono/emby/sonarr to xELEC.
I also saw that emby provides a docker image, however only for x86.
I therefore thought it might be useful to bring mono to LE, as an addon.
This package builds for and runs on RPi2.

It however remains work in progress, in particular:
- it needs to be tested on other architectures/projects;
- ~~it still requires libsqlite3.so (easy, since it has already be done elsewhere)~~;
- ~~it still requires libgdiplus (harder, does anyone know which LE package contains XShm.h)~~;
- reducing the size of the addon seems appropriate.

Do you think this fits in the LE project and is worth the effort?

### CODE REVIEW

**Comment by stefansaraev** [comment]
XShm.h should be part of x11. libXext

**Comment by zalaare** [comment]
Not sure if your aware, or if it falls outside the goals of this PR, but there is already a PR for Sonarr/mono via the docker container approach:
https://github.com/LibreELEC/Dockerfiles/pull/15

This may be redundant

**Comment by awiouy** [comment]
libgdiplus and libsqlite are not indispensable:
- I will defer ligdiplus to when someone really needs it;
- I will provide libsqlite with other mono addons, eg emby.

**Comment by awiouy** [comment]
Here is the status:
- all packages build;
- I merely guessed the depencies of libgdiplus;
- emby runs, and is accessible via the network;;
- emby uses libsqqlite;
- emby fails to load libgdiplus and ImageMagick;
- all of this needs to be tidied up.
Help welcome, eg for dependencies of libdgiplus.

**Comment by sparklyballs** [comment]
@awiouy 
here is the APKBUILD for libgdiplus building in alpine.
maybe help you with tracking the depedencies.

http://git.alpinelinux.org/cgit/aports/tree/testing/libgdiplus/APKBUILD

**Comment by awiouy** [comment]
Good news!

Emby runs on my RPi2, and uses both ImageMagick and sqlite!

Next steps:
- make Emby depend on mono;
- add a system.d service to Emby;
- trim mono a bit;
- understand why mono mono make install fails unless the image is installed.

Thank you all for your help

**Comment by awiouy** [comment]
I think I am done.
The addons build from a clean build system for RPi2 and Generic.
The addons run on my RPi2.
Please review.

**Comment by awiouy** [comment]
I have tested this to build for and run on Generic and RPi2.

I have delegated transcoding to the ffmpeg downloaded by Emby at runtime. As expected, transcoding works for Generic, but not for RPi2. Improving ffmpeg for arm is beyond the scope I had given to this project, and I therefore leave this task to the Emby project or to a dedicated LibreELEC project.

This PR builds a shared version of Mono. I have tried very hard to build a static version, as recommended by the Mono project, but cross compiling Mono is broken, and the proposed build option is the only one I found to be working.

I trust to have included all the recommended changes.

Please commit.

**Comment by chewitt** [comment]
@awiouy is this complete now?

**Comment by awiouy** [comment]
@chewiit yes

**Pull request merged**
