### PR TITLE
[le11] espeak-ng: fix build problems

### PR DESCRIPTION
**Pull request by nuive**

### CODE REVIEW

**Comment by SupervisedThinking** [comment]
Well did you run-test this stuff? I already fixed the build by different solutions:
https://github.com/SupervisedThinking/LibreELEC-RR/tree/up_espeak_dict
https://github.com/SupervisedThinking/LibreELEC-RR/tree/up_espeak

But none of them runs flawless, both were locked and only deliver output if they were run with strace ahead. ping @HiassofT

**Comment by HiassofT** [comment]
Just tested this on RPi4 and it doesn't work - espeak-ng just hangs

```
LibreELEC:~ # espeak-ng --version
^C
LibreELEC:~ # espeak-ng -w hello.wav hello
^C
LibreELEC:~ # 
```

**Comment by nuive** [comment]
@SupervisedThinking your fixes look well, however the fix I've made is the recommended by the developers of eSpeak for a propper build.

Now that you say it, it hangs on a LibreELEC 11.0 generic x86_64 too. Could it be an issue related to another LibreELEC 11 component? Because on the 10.0 branch it works flawlessly...

**Comment by nuive** [comment]
I'm making different test and something strange happens.
I build LibreELEC 11.0 Generic x86_64 with eSpeak-NG support. When running, for example 'espeak-ng --version' from LibreELEC's SSH it freezes. Same build and test process on LE10 works flawlessly.
The thing is, if I copy the built executables and data from LE11 to a LE10 distribution without eSpeak-NG or to an Ubuntu 18.04 distribution, this executable which freezes on LE11 works perfectly. Same thing, if I copy the files built on the LE10 distribution the a LE11 distribution without eSpeak-NG, even if the executable runs flawlessly on LE10, on LE11 it crashes. Could it be a problem related to LE11 and not to eSpeak_NG?

**Pull request closed without merging**
