### PR TITLE
linux (RPi) update to 4.19.58+

### PR DESCRIPTION
**Pull request by HiassofT**
as usual, I'll keep this open for a while to collect RPi kernel bumps and fixes

### CODE REVIEW

**Comment by HiassofT** [comment]
Better don't test with the current version, vc4 is OOPSing with 4.19.64 on RPi4

**Comment by HiassofT** [comment]
testing should be safe again, I've reverted back to the 4.19.64 version without the problematic vc4 commits

**Comment by HiassofT** [comment]
Everything's back to normal, latest rpi-4.19.y contains a fix for the oops. Runtime test on RPi4 worked fine

**Comment by HiassofT** [comment]
after about 1 month in draft state I think it's time to review/merge it

**Comment by MilhouseVH** [comment]
LGTM!

**Pull request merged**
