### PR TITLE
Update retroplayer add-ons to latest versions

### PR DESCRIPTION
**Pull request by garbear**
## Description

This PR updates all retroplayer add-ons to the latest version.

Over the last week I've updated all game add-ons in the kodi-game repo. This PR syncs everything with the latest versions.

I've removed patches for the following cores which have been upstreamed (thanks @heitbaum!):

* mame2000 (https://github.com/LibreELEC/LibreELEC.tv/pull/7793)
* bsnes (https://github.com/LibreELEC/LibreELEC.tv/pull/7794)
* bsnes-hd (https://github.com/LibreELEC/LibreELEC.tv/pull/7794)

## How has this been tested?

I compiled all game add-ons for the following platforms:

* Generic x86_64
* RPi2
* RPi4
* RK3399

### CODE REVIEW

**Comment by heitbaum** [comment]
Pretty sure you have fixed #7805 too.

**Comment by garbear** [comment]
Not quite. I'll need to add beetle-psx-hw as a new core. Alternatively, because we don't have GL support now, we can just force beetle-psx to always be SW, and beetle-psx-hw will pick up HW support when it's ready

**Comment by heitbaum** [comment]
> Not quite. I'll need to add beetle-psx-hw as a new core. Alternatively, because we don't have GL support now, we can just force beetle-psx to always be SW, and beetle-psx-hw will pick up HW support when it's ready

That works / or I’ll leave the issue open - as it only impacts Generic-legacy

**Comment by garbear** [comment]
I updated beetle-psx to only build the SW core. This should work on Generic-legacy (I'll verify when I get a chance).

When GL support lands, we can add beetle-psx-hw as a new core.

**Comment by garbear** [comment]
Rebased on https://github.com/LibreELEC/LibreELEC.tv/pull/7968, and bumped game.libretro to the Omega branch. This PR should be ready to go now.

**Review by lrusak — APPROVED** [review]

**Comment by heitbaum** [comment]
All built and published to the addon server. No build errors in GHA addons 😀

**Pull request merged**
