### PR TITLE
build system: add sha256 checksum to all packages

### PR DESCRIPTION
**Pull request by vpeter4**
putting #1597 in use

I think I got them all correctly. If not we will notice that very soon.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
While testing this I realised we might want a small cosmetic change: http://sprunge.us/aVKR

Instead of:
```
          GET      gettext
INFO Calculated checksum is: ff942af0e438ced4a8b0ea4b0b6e0d6d657157c5e2364de57baa279c1c125c43
          UNPACK   gettext
```
the following would be better:
```
          GET      gettext
              INFO Calculated checksum is: ff942af0e438ced4a8b0ea4b0b6e0d6d657157c5e2364de57baa279c1c125c43
          UNPACK   gettext
```

If you agree, can you add the patch as an extra commit?

**Comment by MilhouseVH** [comment]
Updated the cosmetic patch to use a slightly more terse message when reporting the calculated checksum.

**Comment by vpeter4** [comment]
Done.

I'm wondering if get script should create missing sha256 checksums on already downloaded files. Because after this PR all the source packages will be downloaded again. Which is not strictly required. If checksum doesn't match later from package.mk only then the source would be downloaded again.

**Comment by MilhouseVH** [comment]
I'd leave `get` as it is - yes we will re-download anything that doesn't currently have a sha256 (which would be anything not downloaded in the last 2 months, since #1597), but once everything has a sha256 there'd be no need to worry about files without a sha256, and that would then be "dead" code. Best just to take the one-off re-download hit once this goes in - anyone that has populated their sources folder within the last 2 months won't even take that hit.

**Comment by vpeter4** [comment]
I agree. It was just a though.

I build imx6 and RPi2 images without a problem and Generic is on the way. Seems thing is fine.

**Comment by MilhouseVH** [comment]
Thanks @vpeter4 - let the fun commence... :)

**Pull request merged**
