### PR TITLE
gcc: update to 8.1

### PR DESCRIPTION
**Pull request by InuSasha**
Work In Progress

Working builds (incl. addons):
* Generic
* RPi (device RPi2 used)
* Rockchip (device RK3399 used)
* WeTek_Core WeTek_Play
* Amlogic (device LePotato with #2745)

Open:
- [x] Runtime tests
- [x] size compare against master (@MilhouseVH which do you use for this)

### CODE REVIEW

**Comment by InuSasha** [comment]
**root-clause of WeTek_Play/Core is found, but not a solution**
the define `__put_user_x` in `arch/arm/include/asm/uaccess.h` is wrong optimized.
whole disable of optimization `-O0` leads to other problems...

**Comment by piotrasd** [comment]
could you test gcc with latest kernel 4.17rc6 ? I getting strange error which I never saw on gcc 7.x and I don't know how this fix :( 

```
TOOLCHAIN    make (auto-detect)
Executing (host): make ARCH=x86 headers_check
make[1]: Entering directory '/home/piotr/LibreELEC.tv_Coffe/build.LibreELEC-Generic.x86_64-9.0-devel/linux-c0a490c'
arch/x86/Makefile:184: *** Compiler lacks asm-goto support..  Stop.
make[1]: Leaving directory '/home/piotr/LibreELEC.tv_Coffe/build.LibreELEC-Generic.x86_64-9.0-devel/linux-c0a490c'
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 2

```

**Comment by InuSasha** [comment]
WeTek_Core/Play uses now a linaro toolchain for kernel compiling (and it is working, now).

**Comment by InuSasha** [comment]
file comparison:
```
gcc7                                          | gcc8
image/system/usr/lib/libstdc++.so.6.0.24      | image/system/usr/lib/libstdc++.so.6.0.25
```
size comparison:
```
gcc7: 676140 kb
gcc8: 678632 kb
-----------------
    +   2492 kb
```
looks good to me :)

**Comment by InuSasha** [comment]
tested on
* WeTek_Core (booting, thanks @codesnake)
* LePotato (+#2745  plays video, tmdb scraping)
* RPi2 (plays video, tmdb scarping)

good to go, from me

**Pull request merged**
