### PR TITLE
network/bluez enable btmgmt cmd from tools

### PR DESCRIPTION
**Pull request by stpf99**
this  is for some adapters where Bluetooth MAC is need to be changed 
https://github.com/LibreELEC/misc-firmware/pull/5

### CODE REVIEW

**Comment by jernejsk** [comment]
Which board needs this? If it is ARM board, bootloader is better place to implement fix for that. It can inject MAC address to bluetooth DT node.

**Comment by stpf99** [comment]
adapter as far i know is used for Intel Mini PC Z83-v1 (AZW-BT3), Intel Edison SBC and one of "Banana" or "Orange" SBC but don't remember which one now, static implementation in kernel level was made for Intel Edison where some problems have this series with manufacturing and assembly...

**Comment by jernejsk** [comment]
Ok, so x86 boot is not something we can update. OrangePi 3 has this issue, but fix was implemented in U-Boot. If you know some other OrangePi or BananaPi board, let me know.

**Comment by stpf99** [comment]
this patch introduce this behavior
https://lore.kernel.org/lkml/20190530030548.417582869@linuxfoundation.org/

**Comment by stpf99** [comment]
[OrangePi Lite2 & 3] (https://forum.armbian.com/topic/10219-orangepi-lite2-3-bluetooth/)

**Comment by stpf99** [comment]
Hi . i am trying to write config files and scripts to one random static bt mac address change 
/storage/.config/
1.autostart.sh
`chmod +x  /storage/.config/*e*_mac
/storage/.config/set_mac`
2.gen_mac
``echo `printf '43:34:1b:%02x:%02x:%02x\n' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256]`` > /storage/.config/bt_mac.txt`
3.set_mac
`/storage/.config/gen_mac
mv /storage/.config/gen_mac /storage/.config/gen_mac.back
/usr/bin/btmgmt -i hci0 public-addr `echo `cat /storage/.config/bt_mac.txt```

**Comment by stpf99** [comment]
hi. I try to write scripts for auto Bluetooth MAC change (infinite for user) and on local system this works but executed in LibreELEC something in "gen_mac" script not works , function $[RANDOM%256] not work
https://gist.github.com/stpf99/aff7f70a02d996fe3a4310b5352648e3

**Comment by antonlacon** [comment]
The shell on the device is busybox's ash, not bash. `$[RANDOM%256]` won't meant anything to ash. Write it out in long form: `$(( $RANDOM % 256 ))`, if I understand what you're doing.

**Comment by stpf99** [comment]
@antonlacon now working as expected, thank you!

**Comment by stpf99** [comment]
i have updated script to the max in enable_bt.sh on this gist 
https://gist.github.com/stpf99/a9960bb1c1f21558bab78d71c1e25bda
multiple affected firmware files could be defined in array 
then if any firmware defined  is recognized on dmesg script generate new random mac 
and this mac will be after new static but random one and autostart.sh after reboot sets this mac again

**Comment by chewitt** [comment]
This is a niche bit of hardware so I wouldn't over-think the setup process. I would simplify things to one script that does nothing more than generate a valid MAC and store it in /storage/.cache/btmac, and a sample systemd service file that can be embedded and copied to /storage on first run similar to how the smb/nfs mount files are populated. If users need to force a BT MAC, they can simply enable the script. This removes the need to parse boot logs to detect the chip, and using systemd allows proper before/after sequencing (autostart.sh is always a hack). NB: There is probably a way to do everything from a single systemd service file (no setup script) but I didn't think though all the logic yet :)

**Comment by stpf99** [comment]
thats the way, if systemd allow to split code to main or helper config file *service*.d/*helper.unit etc we have answer

**Comment by stpf99** [comment]
"There is probably a way to do everything from a single systemd service file (no setup script) but I didn't think though all the logic yet :)"
As you suggested i checked systemd option to do that (embending code to generate mac in systemd) but systemd without external "sh script" don't recognize proper some "code exceptions" needed to do that , some words reserved for realize instances...

**Pull request closed without merging**
