### PR TITLE
backport of #271

### PR DESCRIPTION
**Pull request by CvH**
@lrusak

### CODE REVIEW

**Comment by awiouy** [comment]
@CvH, @lrusak,
Can this wait a couple of days: I am in the process of moving the settings to Kodi, and I expect to submit the corresponding pull request before tomorrow evening.

**Comment by CvH** [comment]
@awiouy pls have a look at my fixup commit 
- our goal is to get an standard template for addon packages (we know it is a bit messy that there is no template where you can look at because everybody does it slightly different) - I **propose** an cleanup for the other addons later
- we are also try to reduce the sub subcategories (I think we want it @lrusak ?) if it is possible without major update breakage

**Comment by awiouy** [comment]
@CvH Thank you for the fixup. You and the team are very reactive and supportive, indeed. I will integrate the changes you propose in #285 this afternoon.

**Comment by awiouy** [comment]
@CvH 
Thank you for the extensive reply. I tried to comply: I updated from system/service, built and installed. On my system there are now two dispmanx_vnc addons, i.e., the legacy system/service addon and the service addon, which compete for the same default port. This is in my humble opinion a problem we need to address, but I would not know how. What do you suggest?

**Comment by CvH** [comment]
@awiouy yea this is of course an impasse - lets retain the current name (no better idea atm).

**Comment by awiouy** [comment]
Hi @CvH
You can close this, as it is superseed by #295. I will try to document how to manage (create, update and backports). Where is, according to you, the best place to do this?

**Comment by chewitt** [comment]
CONTRIBUTING.md would be a good location, but that needs an overhaul anyway. Write the text in GH markdown first and share the content, then we'll figure out where to use it :)

**Pull request closed without merging**
