### PR TITLE
media_build: add support for S905/S912

### PR DESCRIPTION
**Pull request by adamg-xda**
Self explanatory PR, part of the changes required to bring S905/S912 to LE/master

@kszaq @afl1 @Raybuntu

### CODE REVIEW

**Comment by Raybuntu** [comment]
@adamg-xda Have you seen this: https://github.com/LibreELEC/LibreELEC.tv/pull/2270?

**Comment by adamg-xda** [comment]
I have, there is no specific config in use here, until the PR is merged I obviously can't rebase against it.

**Comment by afl1** [comment]
Compiling AMLVIDEO driver as loadable kernel driver conflict with other Amlogic based devices.

**Comment by adamg-xda** [comment]
@afl1 there is an IF statement around the amlvideo code so it is only compiled as a module for S905 and S912

**Comment by Raybuntu** [comment]
This should not be specific to S905 only. It should support all Amlogic 3.14 devices. Not sure what the plans for mediabuild is. Last I checked with @CvH it is going to be moved to addons.

**Comment by CvH** [comment]
Buildwise there are no changes, the only change is after the initial build at `install()`.
Instead of hardwiring the kernel to load the module folder kernel/updates/... you can now choose what folder should be loaded (due the addons). The modules itself are build like usual.

**Pull request closed without merging**
