### PR TITLE
retroplayer: update add-ons

### PR DESCRIPTION
**Pull request by CvH**
update to latest (buildtested)
@garbear

### CODE REVIEW

**Comment by garbear** [comment]
Looks good. 4DO was fast-forwarded almost a month, do the other 60+ emulators need updating too?

**Comment by CvH** [comment]
> 4DO was fast-forwarded almost a month

Our commit was latest Jun 26 - Jul 10, 2018, I pushed a pr 20days ago so this is okay.
the last 4DO commit `38b0570` is from Jul 17, 2018 so a month ago isn't that true :)

**Comment by garbear** [comment]
Haha cool

**Comment by matejmosko** [comment]
The broken psx addon that need update is libretro.pcsx, as far as I know. ;) But maybe beetle-psx needs it as well.

**Comment by garbear** [comment]
I meant PCSX-rearmed instead of Beetle-PSX. PCSX works much better on ARM. It needs this patch: https://github.com/libretro/pcsx_rearmed/pull/178

**Comment by CvH** [comment]
added the bumps for the emulators too (just where we bump also the game.libretro addons)

**Comment by matejmosko** [comment]
Just for future reference. Pcsx-rearmed wasn't included in this PR. Pcsx-rearmed is still broken on libreelec because of missing https://github.com/libretro/pcsx_rearmed/pull/178

**Comment by chewitt** [comment]
PR's for missing pieces are welcomed :)

**Pull request merged**
