### PR TITLE
Amlogic updates

### PR DESCRIPTION
**Pull request by adamg88**
This PR contains the latest updates by @kszaq in his 8.2 branch ported over to master

I have tested all changes compile ok

### CODE REVIEW

**Comment by kszaq** [comment]
These changes have not been tested by users, please wait with merging.

**Comment by adamg88** [comment]
S905 is nowhere near ready yet on Master until we sort the kernel out

**Comment by kszaq** [comment]
I agree but I think it's better to confirm that all bumped drivers work well before we merge them.

Anyway, thank you for adapting driver bumps for LE master. 👍

**Comment by kszaq** [comment]
@adamg88 Please drop "linux-drivers/amlogic: ap6xxx-aml: update to "Oreo" branch" patch as it was reported to break Broadcom WiFi. Otherwise the PR is good to go.

**Comment by adamg88** [comment]
Done

**Pull request merged**
