### PR TITLE
Updated libretro-ppsspp package

### PR DESCRIPTION
**Pull request by peak-load**
1. wireguard-tools was updated recently, so recent version will be used.
2. libretro-ppsspp package was set to use non existing package file, so it was not downloaded with download-tool, changed to use latest version.

### CODE REVIEW

**Comment by heitbaum** [comment]
Morning @peak-load  - wireguard is duplicate of #5189. Best to have these packages separated, as they would be committed separately.

**Comment by antonlacon** [comment]
Commits need to be squashed to per package. Commit messages need to follow project-style "package affected: what is commit doing".

**Review by heitbaum — CHANGES_REQUESTED** [review]
Please remove the wireguard patch and squash the others.

**Comment by HiassofT** [comment]
libretro-ppsspp has been removed from master branch, this is no longer relevant

**Pull request closed without merging**
