### PR TITLE
Odroid_C2: CEC/IR wake-up and boot-logo.bmp.gz support

### PR DESCRIPTION
**Pull request by Kwiboo**
This PR updates the hardkernel u-boot to latest version and adds patches to enable CEC and IR wake-up from power-off state.
It also adds support for copying `boot-logo.bmp.gz` from `distributions/$DISTRO/splash` or `projects/$PROJECT/splash` to `/flash` for use in u-boot before plymouth-lite is started.

The CEC wake-up code needs wider testing before this PR is ready to be merged.
A test image can be found at https://www.dropbox.com/s/dqrhnyubezm11oi/LibreELEC-Odroid_C2.aarch64-8.0-devel-20160820171358-r23655-g81a4c0b.img.gz?dl=0

### CODE REVIEW

**Comment by wrxtasy** [comment]
Hi Kwiboo,

This is working nearly perfectly 👍 

Some feedback as I've been testing this for my LE 7.1 on the C2:
Q. Why are we using "hdmitx=cec1f" ?

I've actually had to use "hdmitx=cec0" in boot.ini to prevent my TV from turning itself back ON once the C2 has gone into its semi-powerdown state.

Also you might consider updating the boot-logo.bmp.gz in the u-boot updater script for .tar updates.

W.

**Comment by Kwiboo** [comment]
IR wake-up has been working flawlessly for me but it seems CEC wake-up is not fully functional with some TV vendors (I can only test with a Sony TV).

`hdmitx=cecXY` sets the cec config bitmask and as far as I know the bits configures:
1: cec wake-up code enabled/disabled in u-boot, unused by aocec
2-3: unused by u-boot/aocec
4: wake-up on cec power key command in u-boot, turn on TV in aocec
5: wake-up on cec set stream path command enabled/disabled in u-boot, unused by aocec
using `hdmitx=cec1f` enables all possible cec features

I have the same TV turning itself back ON once the C2 has gone into its semi-powerdown state issue using current hardkernel kernel/aocec-driver. This issue was not present last time I tested with a 20160701 amlogic kernel/aocec-driver.

**Comment by Kwiboo** [comment]
I have now added fixup commits to address: (will squash and rebase PR once I have fully tested the changes)
- Added a boot-logo.bmp.gz (splash-720.png converted to 24bit bmp, u-boot showlogo cmd expects a 720p logo)
- boot-logo.bmp.gz is copied/replaced in update.sh
- mkimage shouldn't be needed for Odroid C2
- added CEC wake-up on Routing Change message, enabled with bit 6
- CEC power-key wake-up is now enabled with bit 3

Updated cec config bits:
1: cec wake-up code enabled/disabled in u-boot
2: unused
3: wake-up on cec power key message
4: turn on TV in aocec
5: wake-up on cec set stream path message
6: wake-up on cec routing change message
using hdmitx=cec3f enables all possible cec features, use hdmitx=cec37 to only disable turning on TV

**Comment by Kwiboo** [comment]
Updated to address:
- remove use of unmounted debugfs in platform_init
- same bitmask is now used for set stream path and routing change message
- default boot.ini cec config now disables turning TV on by kernel/aocec, libcec will turn on configured devices once Kodi is started (fixes TV turning itself back ON once the C2 has gone into its semi-powerdown state and keeps CEC wake-up working)

**Pull request merged**
