### PR TITLE
exfat-fuse: remove package to make way for mainline driver

### PR DESCRIPTION
**Pull request by antonlacon**
This should be complete, but haven't been able to test it yet due to an unrelated issue. My only open question is with the udevil.conf, and it's whether exfat will be builtin to the kernel or as a module. As a module, exfat won't be listed in /proc/filesystems, so needs to be added with $KNOWN_FILESYSTEMS like here.

nonempty is a mount.fuse option, so no longer applies.

I don't intend on making the kernel config changes, so please let me know if you have a change to cherry-picked here, make separate PR or add to the kernel updates.

### CODE REVIEW

**Comment by jernejsk** [comment]
@antonlacon Please pick https://github.com/jernejsk/LibreELEC.tv/commit/0002c3b3a7e1f05df0f381a9f15ccf6cb24b152f for Allwinner project

**Comment by antonlacon** [comment]
Exfat flashdrive mounted as expected w/ exfat as kernel module.

**Comment by mglae** [comment]
> ... and it's whether exfat will be builtin to the kernel or as a module.

Currently in kernel for Allwinner and module on RPI is commited.

Traditionally LE is  including as much as possible into the kernel.

**Comment by HiassofT** [comment]
Built-in is only required for things needed from initrd.

Kernel config isn't too consistent across the various projects, but most rarely used filesystems (fuse, reiser, overlay, jfs, xfs, ...) are in general configured as modules.

As we don't need exfat in initrd it's better to just configure it as a module.

**Comment by antonlacon** [comment]
Edited every kernel config that is >=5.7. That's when the staging driver was removed and Samsung's was inserted as mainline. There's one project at 5.2 that I didn't touch.

Compile tested Generic only. Rest are untested.

**Comment by HiassofT** [comment]
can you remove utf8 from default_options_exfat and allowed_options_exfat?

utf8 is a dummy and just logs a deprecation warning - see https://github.com/torvalds/linux/commit/907fa893258ba6076f5fff32900a461decb9e8c5
```
[   14.418756] exfat: Deprecated parameter 'utf8'
```

A local test without that option worked fine. file with umlauts created from win7 showed up fine in LE/kodi

**Comment by antonlacon** [comment]
Updated.

**Review by HiassofT — APPROVED** [review]
thanks!

**Pull request merged**
