### PR TITLE
irserver: remove package

### PR DESCRIPTION
**Pull request by lrusak**
The irserver package never made the transition to systemd and yet no one has complained that it isn't working properly. So lets just get rid of it. If someone wants it then they can make it into an add-on.

### CODE REVIEW

**Comment by awiouy** [comment]
I will make it an addon next week-end

**Comment by lrusak** [comment]
updated as I had an extraneous file in there.

**Comment by lrusak** [comment]
rebased.

**Comment by ghemberg** [comment]
Did irserver ever make it into an add-on?

**Pull request merged**
