### PR TITLE
ncurses: improvements / system-tools 110: update mc and efibootmgr

### PR DESCRIPTION
**Pull request by mglae**
The default ncurses "xterm" terminfo definition use features of original xterm that are not supported by other terminal emulations claimed to be compatible. I.e. [Midnight Commander](https://forum.libreelec.tv/thread/13923-midnight-commander/) has corrupted display and mouse is not working in Putty.

Removing most recent mouse mode and ANSI repeats solve the issue.

This makes [screen](https://forum.libreelec.tv/thread/13384-8-90-005-rpi2-screen-from-system-tools-broken/) working again.

system-tools need to be rebuild and are updated to 110 with some improvements.

### CODE REVIEW

**Comment by vpeter4** [comment]
I think wrapper script for mc is unnecessary and _HISTFILE_ environment variable could be set from profile.d folder.
Anyway, will build mc and screen and test it.

**Comment by vpeter4** [comment]
To get screen working I copied termcap from Ubuntu 16.04 to /storage/.config/termcap. Is this file missing or what?

**Comment by CvH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/devel/ncurses/package.mk#L35
maybe MC depends at an binary for some reason ?

**Comment by mglae** [comment]
> As I wrote wrapper script should be removed and set environment variable from profile.d. Tested and it works.

The wrapper script is a work around for an `ash` limitation. Lines with leading white space are stored into the history.

The history file defaults to $HOME/.ash_history if not defined explicit. When navigating in mc the history is flooded with `cd ...` and other lines. Temporary moving the history file protects the relevant entries.

**Comment by mglae** [comment]
> I understand the reason. But wrapper scripts are not needed - use profile.d instead 

I don't understand. Using profile.d changes HISTFILE for all shells, not only mc sub shells.

**Comment by vpeter4** [comment]
> I don't understand. Using profile.d changes HISTFILE for all shells, not only mc sub shells.

I see. Then ignore this part. Just screen needs to be fixed.

**Comment by vpeter4** [comment]
All good now.

**Pull request merged**
