### PR TITLE
[le11] Generic: updated / added devices

### PR DESCRIPTION
**Pull request by SupervisedThinking**
When I fixed the Wayland based builds in https://github.com/LibreELEC/LibreELEC.tv/pull/5864 I realized that it's rather inconvenient to fiddle with the existing device opts, also `Generic-legacy` seems a bit odd to me. So I've added "devices" for every possible "windowing system / display server" Kodi supports. Generic is linked to gbm options & images can be build by e.g.:
- `PROJECT=Generic DEVICE=gbm ARCH=x86_64 make image`
- `PROJECT=Generic DEVICE=Generic ARCH=x86_64 make image` 
- `PROJECT=Generic DEVICE=wayland ARCH=x86_64 make image` (depends on https://github.com/LibreELEC/LibreELEC.tv/pull/5864)
- `PROJECT=Generic DEVICE=x11 ARCH=x86_64 make image` 

Summary:
- cleaned up options
- added gbm, wayland & x11 devices
- Generic-legacy replaced by x11
- kept Generic (=gbm) for easier transition
- updated canupdate.sh to allow updates, this should be backported to LE10 too 🤔

### CODE REVIEW

**Comment by zhangn1985** [comment]
why not use:`PROJECT=Generic WINSYS=x11 ARCH=x86_64 make image`

**Comment by SupervisedThinking** [comment]
@zhangn1985 well why should I? Using the Device identifier creates builds with meaningful names like `LibreELEC (community): devel-20211109220649-50dc6b1 (wayland.x86_64)` and it picks up the options file stored in each device dir. I have no intentions to virtually turn the build system inside out just to introduce a new var with basically no additional value.

**Comment by chewitt** [comment]
LE intends to drop Xorg from the build system sooner than later (Generic_Legacy is a temporary thing) so I don't see much point in a short-term rename or adding a duplicate for GBM (there is no plan to stop using the Generic name; explaining what GBM means will only confuse the majority of users). Once Xorg is gone the build-system will be cleaner and the short-term fiddly stuff should go away or significantly reduce. If maintaining Xorg is adding work I'd prefer we focus on dropping it sooner over adding complexity.

**Comment by SupervisedThinking** [comment]
If LE will drop X11 at some point you only have to delete one device which isn't exactly much work to do. I've symlinked the "Generic" device to gbm because at the moment Generic means X11 & Generic itself gives you basically down to 0 information what you actually get. I don't see any confusion because you still offer users a `Generic.x86_64` build while it's more precise to to use an option file of what it actually is -> GBM.

IMHO once you offer Generic(GBM) and X11 builds you have to tell user what's the difference anyway because it will screw over a lot of addons. Everything related to GLX & OpenGL will be broken unless EGL & OpenGLES renderer are in place. Stuff like browser addons are basically dead too & it's not solved by telling the addon maintainer to fix some code here & there like we did when python 2 was replaced by python 3.

I probably tend to repeat myself but cutting down the features for all users of x86_64 systems to 35$ SBC boards isn't probably the best LE should do.

**Comment by zhangn1985** [comment]
I understand you use `DEVICE= ` easy for X86_64 configure to X11/gbm/wayland.
I don't know whether has plan to enable ARM devices to support wayland? if has the plan, use `WINSYS= ` will be better.

**Comment by SupervisedThinking** [comment]
I've created specific devices because it's not done by setting a single variable like you suggested.
The difference between GBM, Wayland & X11 are the OpenGL API which is used, the display server & protocol, X11 also needs a window manager. So IMHO these devices should have been added long ago to make sure correct options are defined when someone builds other stuff like X11.

Beside that, these are project files & not the Kodi package configs, Kodi picks up the matching "window system" according to the options provided by the device files.

These changes/additions are needed because the transition from X11 to "whatever" & don't touch ARM projects at all. However you can basically already build Wayland based ARM images by adding weston as DISPLAYSERVER variable. IIRC this has been done in the past to work around missing GBM Mali blobs but there have been none official X11 builds for ARM.

**Comment by heitbaum** [comment]
My 2c worth is leave `Generic` as `Generic` and gbm as an alias (if required.)

**Comment by SupervisedThinking** [comment]
@heitbaum done - this works for me.

Otherwhise this PR should be good to & ease up things if you want to test/fix stuff for GBM, Wayland & X11 e.g. GTK for Chrome or Vulkan.

**Review by heitbaum — CHANGES_REQUESTED** [review]
Please do as rename `projects/Generic/devices/x11/options` Missing End-of-line.

**Comment by SupervisedThinking** [comment]
@heitbaum done

**Review by CvH — APPROVED** [review]
behaviour is still the same but makes the different build variants now cleanly buildable next to each other

our default is still Generic (gbm) and likely Generic-legacy (x11) for LE11

**Pull request merged**
