### PR TITLE
linux 4.9 patch for newer ddbridge DVB cards

### PR DESCRIPTION
**Pull request by mglae**
The patch is generated from [https://github.com/herrnst/dddvb-linux-kernel/tree/v4.9.0-ddbridge-features](https://github.com/herrnst/dddvb-linux-kernel/tree/v4.9.0-ddbridge-features) and works well on my DD Cine CT V6 DVB card.

It can be now applied again after the conflicting TBS patch was removed.

It is a 4.9 patch and will likely fail on any other major kernel version. When updating the kernel a matching version must be generated:

1. Check latest master:
`wget -q -O - 'https://github.com/herrnst/dddvb-linux-kernel/raw/master-ddbridge-features/Makefile'|head -n 4`
2. Let GitHub create the patch:
`wget -O linux-221-ddbridge-features.patch 'https://github.com/herrnst/dddvb-linux-kernel/compare/master...master-ddbridge-features.diff'`

### CODE REVIEW

**Comment by MilhouseVH** [comment]
The kernel config options are incomplete - additional options after running `make oldconfig` with this ddbridge patch:

[Generic](http://sprunge.us/hDGO)
[Virtual](http://sprunge.us/fahZ)

**Comment by mglae** [comment]
Thanks for the diffs.

**Comment by chewitt** [comment]
@CvH what's the status of this with media_build merged?

**Comment by CvH** [comment]
sadly not compatible to the media_build approach, besides that (if m_b disabled) it is working for v6 cards

**Pull request closed without merging**
