### PR TITLE
switch back to standard ncurses

### PR DESCRIPTION
**Pull request by CvH**
This changes the build system to use standard ncurses instead of netbsd-curses.
Motivation for this step back is the lack of support for netbsd-curses in real world and the resulting problems due this. 
Afaik beside LE/OE and Sabotage Linux nobody is using this Mod of the curses implementation for netbsd. 
So better stick with the Linux default to avoid useless time wasting due this.

Currently I have not squashed any commits (will do before rm WIP).

It looks like there is currently still a problem that curses get stuff from outside the build system (same problem for netbsd-curses). I have no idea how to fix this or even debug it (help welcome). 
Beside that it build for me, but as seen in the past this may differ from system to system.

### CODE REVIEW

**Comment by vpeter4** [comment]
What exactly is the problem with _curses get stuff from outside the build system_?

**Comment by CvH** [comment]
@vpeter4 I couldn't track it down (due no idea how to debug)
We had already that it builds at my clean VM, at my usual (rather dirty due other stuff) VM not (always 100% clean build dir) - same Ubuntu. 
Also at Ubuntu there are problems that do not appear at Arch Linux. 

So there are still depends to the outside of the builddir (btw I have no better explanation). 

For example we tried to compile https://github.com/escalade/LibreELEC.tv/tree/le82/ MC/htop (without current patch) at Ubuntu that never worked, it worked well at Arch (this is what @escalade build from). 
At Arch it found curses without any problem, at Ubuntu only due rather big hacks - this shouldn't happen (I guess). Maybe @escalade has some better explanation/ideas :) (this is really **not** my expertise, so pls feel free to disagree with everything I might say)

Also the rather frequently need of `-I$SYSROOT_PREFIX/usr/include/ncurses` looks rather strange.

**Comment by vpeter4** [comment]
I think I understand the problem :)

**Comment by vpeter4** [comment]
Did some tests but at the en I broke something - need to rebuild.

But from what I see is that ncurses needs to be configured with **--with-termlib**. This builds two libs: libncurses.a and libtinfo.a. The second one is looked by some configure scripts. If there is no libtinfo then libncurses includes it's functionality (could also be symbolic link from libncurses to libtinfo).
Htop patch can be removed, without -I...ncurses and with **PKG_CONFIGURE_OPTS_TARGET="--disable-unicode"**.

**Comment by CvH** [comment]
@vpeter4 
> Htop patch can be removed, without -I...ncurses and with PKG_CONFIGURE_OPTS_TARGET="--disable-unicode" in package.mk.

```
PKG_CONFIGURE_OPTS_TARGET="--disable-unicode"

pre_configure_target() {
  export CFLAGS="$CFLAGS -fno-strict-aliasing -lncurses"
}
```
doesn't build for me (tried different things too) 
`configure: error: missing libraries:  libncurses` without patch

**Comment by vpeter4** [comment]
You need to rebuild ncurses to get libtinfo library.

But seems with this ncurses change some packages needs _export LIBS="$LIBS -ltinfo"_ (connman, bluez and maybe others). Not sure if this is correct approach.

Regarding ncurses and libtinfo here is some discussion (very old one but seems still appropriate): https://bugs.launchpad.net/ubuntu/+source/ncurses/+bug/259139

**Comment by CvH** [comment]
@vpeter4 adding `--with-termlib` and added `LIBS="$LIBS -ltinfo"` won't help either (maybe you done something else ?)

**Comment by escalade** [comment]
@vpeter4 

Why would you need libtinfo? The bugreport you are linking to is with regards to an third party library being linked to libtinfo. That's not needed in a distribution like LibreELEC where everything is compiled. I don't use --with-termlib in my build and Arch does not use this option either. It's not the default and probably for a reason.

Options like that should not be used without purpose. As you can see other packages will actually need modification to compile against ncurses if you are using this option (-ltinfo).

**Comment by vpeter4** [comment]
I don't need libtinfo. But configure script for example htop fails without (I think). Also this lib is present on Ubuntu 16.04.3 LTS.
Yes, other packages who explicitly needs -lncurses would also need -ltinfo in this case.

But I'm just exploring options. Seems no changes is needed anyway.

**Comment by vpeter4** [comment]
But I think ncurses could be build without **--disable-overwrite**. Then headers will be installed in usr/include and not in ncurses subfolder. Which means no need to set **-I.../ncurses**.

**Comment by escalade** [comment]
That's because it's package specifies -lterminfo in CFLAGS. I can compile htop just fine both with netbsd-curses and ncurses (needs --disable-unicode) without any patches.

The option --disable-overwrite is already included. Where do you see -I../ncurses?

**Comment by CvH** [comment]
@escalade `The option --disable-overwrite is already included.` no, I changed it regarding of the "old" package we had (as thought that it had worked there - looks like not)

**Comment by escalade** [comment]
Yes sorry, it should be excluded, my original commit had this. Makes absolutely no sense to use a separate include dir when packages expect the opposite.

**Comment by CvH** [comment]
@escalade I had the expectation that the "old" ncurses had worked properly (as there were not those workarounds), I try without

**Comment by escalade** [comment]
They used this option in the old package and as a consequence had to modify other packages to find the correct include path. It wouldn't be a bad idea to go through every option used in this package to see if it's actually needed. I believe lots of them are the default already, so IMO no need to specify them.

**Comment by CvH** [comment]
@vpeter4 I squashed some of the commits and added the rm of the `--disable-overwrite`. 
Due this all those `-I$SYSROOT_PREFIX/usr/include/ncurses"` could be removed (`packages remove workarounds`). All is build tested and works for me.

The only concern is about htop, it still needs the patch and still much more then what @escalade has needed.

**Comment by vpeter4** [comment]
For htop: remove the patch and this function `pre_configure_target() {
   PKG_CONFIGURE_OPTS_TARGET="--disable-unicode HTOP_NCURSES_CONFIG_SCRIPT=ncurses-config"
}`

**Comment by vpeter4** [comment]
I think _mc_ package doesn't need _pre_configure_target_ function anymore.

**Comment by CvH** [comment]
@vpeter4 the cflags are 
`CFLAGS="-march=armv7ve -mtune=cortex-a7 -Wl,--as-needed -fuse-ld=gold -fuse-linker-plugin -flto"` 
with that sed the cflags are (-lncurses looks now useless)
`CFLAGS="-march=armv7ve -mtune=cortex-a7 -fuse-ld=gold -fuse-linker-plugin -flto -lncurses"`

both builds so I guess we go with removing the `pre_configure_target` at mc
I added 2 commits for htop/mc, the other 2 commits are just minor cosmetic.

**Comment by vpeter4** [comment]
Seems it builds fine here for Generic. Other projects will follow.

**Comment by MilhouseVH** [comment]
No problems building RPi/RPi2/Generic along with various PVR addons.

**Comment by CvH** [comment]
squashed commits, updated dates and removed WIP
from my pov good to go

**Comment by CvH** [comment]
Iirc it didn't build without, maybe you could build it without patch (I need to redo whole build)?

**Comment by vpeter4** [comment]
It builds fine here. But I only changes readline package - everything else was old.

Will do clean build over night without this patch and see.

**Comment by CvH** [comment]
@vpeter4 I guess this problem was fixed with the removal of `--disable-overwrite` , hadn't tested afterwards if it works without the patch. It build (dirty) for me too. A clean build would not hurt. I push the removal of the patch so it could be merged (I am away till monday).

**Comment by MilhouseVH** [comment]
Thanks @CvH

**Pull request merged**
