### PR TITLE
network-tools update

### PR DESCRIPTION
**Pull request by CvH**
- depends on https://github.com/LibreELEC/LibreELEC.tv/pull/3234
- tested

@vpeter4 rar2fs is added here, libunrar is a bit meh but it looks like the only solution possible without adding strange hacks to the unrar package

### CODE REVIEW

**Comment by CvH** [comment]
@vpeter4 I tried basically the same besides the `make clean` between - this might do the trick, I try.

**Comment by vpeter4** [comment]
Btw: Can you try this? Seems to be working too.```  make CXX="$CXX" \
     CXXFLAGS="$TARGET_CXXFLAGS" \
     RANLIB="$RANLIB" \
     AR="$AR" \
     STRIP="$STRIP" \
     -f makefile unrar clean lib```

**Comment by CvH** [comment]
@vpeter4 it build, but rarfs can't find it, 
```
configure: error: 
                Cannot find unrar library - add alternative library search path using
                --with-unrar-lib and rerun configure. If the intention was to build
                towards a static version of the library please make sure such has been
                built (only supported from v5.4.6 and later) in the source tree pointed
                to as /LE/build.LibreELEC-Generic.x86_64-9.0-devel/unrar-5.6.3.
```
it looks like it expect to have unrar **OR** lib and not both

```
make_target() {
  make CXX="$CXX" \
     CXXFLAGS="$TARGET_CXXFLAGS" \
     RANLIB="$RANLIB" \
     AR="$AR" \
     -f makefile lib

  mkdir lib
    cp $PKG_BUILD/* $PKG_BUILD/lib 

  make clean

  make CXX="$CXX" \
     CXXFLAGS="$TARGET_CXXFLAGS" \
     RANLIB="$RANLIB" \
     AR="$AR" \
     STRIP="$STRIP" \
     -f makefile unrar
}
```
works for me - now what is the better approach :D this or libunrar

**Comment by vpeter4** [comment]
I'm not sure what happen in your case but those 2 packages above on pastebin works perfectly fine for me on Generic.
Using libunrar is bad. I would avoid it because there is no reason for it.

I will rebuild everything over night and repeat process tomorrow.

**Comment by CvH** [comment]
With the packages above rar2fs never found rar with the error above. Not sure if I messed my toolchain too much or it is just nor working :)
```
make_target() {
  make CXX="$CXX" \
     CXXFLAGS="$TARGET_CXXFLAGS" \
     RANLIB="$RANLIB" \
     AR="$AR" \
     -f makefile lib

  mkdir lib
    cp $PKG_BUILD/* $PKG_BUILD/lib 

  make clean

  make CXX="$CXX" \
     CXXFLAGS="$TARGET_CXXFLAGS" \
     RANLIB="$RANLIB" \
     AR="$AR" \
     STRIP="$STRIP" \
     -f makefile unrar
}
```

```
PKG_CONFIGURE_OPTS_TARGET="--with-unrar=$(get_build_dir unrar)/lib \
                          --with-unrar-lib=$(get_build_dir unrar)/lib \
                          --disable-static-unrar"
```
worked for me

**Comment by vpeter4** [comment]
On fresh build my two packages still works.

**Comment by CvH** [comment]
@vpeter4 it worked for me too after a bigger clean up 🥇 
I removed the line because I need to copy it to the addon. Changes are pushed.
```
post_make_target() {
  rm -f libunrar.so
}
```

**Comment by vpeter4** [comment]
You can remove shared library and rar2fs will be build with static one. One less file. But it's up to you :)

**Comment by CvH** [comment]
If I try to build static rar2fs errors out at 
`checking for /LE/build.LibreELEC-Generic.x86_64-9.0-devel/unrar-5.6.8/libunrar.a... configure: error: cannot check for file existence when cross compiling`

Google didn't really help and I found no obvious fix so I went the easiest route for it :) (not stopping you from finding one)
In the end it doesn't even matter - so I choose less headaches.

**Comment by vpeter4** [comment]
How do you build rar2fs static? I didn't change anything in package and it is build successfully.
```
PKG_CONFIGURE_OPTS_TARGET="--with-unrar=$(get_build_dir unrar) \
                           --with-unrar-lib=$(get_build_dir unrar) \
                           --disable-static-unrar"
```

**Comment by CvH** [comment]
>How do you build rar2fs static? I didn't change anything in package and it is build successfully.

maybe I miss the obvious here :)

```
checking rar.hpp presence... yes
checking for rar.hpp... yes
checking for static linking of UnRAR library... yes
checking for /LE/build.LibreELEC-Generic.x86_64-9.0-devel/unrar-5.6.8/libunrar.a... 
             configure: error: cannot check for file existence when cross compiling
cvh@buildbot:~/LE$ ls /LE/build.LibreELEC-Generic.x86_64-9.0-devel/unrar-5.6.8/ | grep libunrar
libunrar.a
libunrar.so
```
I keep everything like currently pred and just change `--enable-static-unrar`. I also tried in removing it, or just build the libs and it always errors here.

**Comment by vpeter4** [comment]
Remove libunrar.so file and use --disable-static-unrar. Builds for generic and Amlogic.

**Comment by vpeter4** [comment]
Good then.
If you want replace TARGET_CXXFLAGS with CXXFLAGS. Now it seems that there is something special.

**Comment by CvH** [comment]
does it make any difference, because unrar works with that configuration since ages !?
I guess you mean that, right ?
```
  make CXX="$CXX" \
     CXXFLAGS="$CXXFLAGS" \
     RANLIB="$RANLIB" \
     AR="$AR" \
     -f makefile lib
```

**Comment by vpeter4** [comment]
Yes, that part. It is same value just different variable name.

**Comment by CvH** [comment]
oki, next time ;)

**Pull request merged**
