### PR TITLE
Update misc-firmware

### PR DESCRIPTION
**Pull request by ishioni**
Following up from https://github.com/LibreELEC/misc-firmware/pull/4

### CODE REVIEW

**Comment by chewitt** [comment]
It's clearly been a while since we bumped this package. Can you please use the full githash not the short one. Also update the commit message (not the PR title) to something like `misc-firmware: update to include asus bt-400 fw` to follow our message house-style. Thanks.

**Comment by lrusak** [comment]
@ishioni Please respond to the comment from @chewitt else this will be closed 😃 thanks!

**Comment by ishioni** [comment]
@lrusak Oh sorry, i missed this. Thanks for the reminder

**Review by chewitt — APPROVED** [review]
Thanks!

**Pull request merged**
