### PR TITLE
librespot: switch from ffmpegx to pulseaudio to stream to Kodi

### PR DESCRIPTION
**Pull request by awiouy**
WIP

### CODE REVIEW

**Comment by awiouy** [comment]
It works, but the log is flooded with:
pulseaudio[269]: E: [null-sink] rtp.c: sendmsg() failed: Connection refused

**Comment by awiouy** [comment]
Rebased

**Comment by awiouy** [comment]
Ready to merge

**Comment by chewitt** [comment]
@awiouy don't forget the equivalent PR's for 8.2/9.0

**Pull request merged**
