### PR TITLE
kodi: aarch64-patches fix 1080p to 2160p GUI and video scaling

### PR DESCRIPTION
**Pull request by wrxtasy**
Revert current AML S905 Freescale patch due to top left 1/4 screen
video display when Kodi resolution switches from 1080p GUI to 2160p
Also calculate the correct 2160p video_axis co-ordinates when doing so.

The current EGLNativeTypeAmlogic patch by @kszaq was actually untested on a 2160p display and 
results in top left 1/4 screen video playback if autoswitching 1080p>>2160p.
It is fine if the GUI is already @2160p and works well to scale a 1080p GUI correctly without the flickering problems we currently know about when drawing a 2160p GUI with the Mali GPU.

However, going forward, especially with Interlaced TV on the WeTek Play2. Users will be spending most of their time watching 480/576/720/1080i Interlaced content with a 1080 GUI.  There is no Interlaced video mode for 2160p displays, its all progressive. Using a 2160p GUI is then useless and results in Interlaced video playback problems.

I've tested this extensively playing all the 2160p Resolution video clips I have. The Kodi OSD scales and video plays correctly after re-calculating the correct video_axis coordinates when doing a 1080p>>2160p switch.

W.

### CODE REVIEW

**Comment by stefansaraev** [comment]
good one. thank you.

there is same broken refreshrate switching behaviour on wetek core too, and this PR fixes it. perhaps its worth moving the patches out of the aarch64/ dir

**Comment by lrusak** [comment]
The patches only touch amlogic code, so it is safe to take them out of the aarch64 directory.

**Comment by kszaq** [comment]
This patch breaks resolution switching when 720p is default resolution. 

Way to reproduce:
* switch to 720p in Android
* boot to LE
* turn on Automatic Refresh Rate Switching
* play 1080p or 4K video

Result: screen content garbled.

**Comment by stefansaraev** [comment]
@kszaq confirmed. and it seems to be kernel fault?
http://sprunge.us/VLSd

**Comment by kszaq** [comment]
My guess is that this is related to setting framebuffer size. 

Preferred (boot) screen resolution is 720p -> GetPreferredResolution returns 720p -> nativeWindow is 1280x720 and when you switch to 1080p there is not enough space for all the pixels. 

When we used to render GUI at native resolution (up to 4K) we set nativeWindow size according to maximum supported resolution: https://github.com/LibreELEC/LibreELEC.tv/blob/b458efe642c53b3dc3be7a17577710a8ecb89391/projects/WeTek_Hub/patches/kodi/0003-aml-Add-support-for-4k-resolutions.patch#L93

**Comment by kszaq** [comment]
IMHO we only need to patch `AMLCodec.cpp` over current patch. That's only an opinion, I have no TV to test on.

**Comment by stefansaraev** [comment]
k. I keep kodi-0006-calc-corect-video-axis-when-2160p.scaling.patch but replace kodi-0003-1080p-to-2160p-video-scaling-fixup-v3.14-modes.patch with http://sprunge.us/DUdD and my my 2160p samples play fine with refreshrate switch enabled and both 1920x1080p and 1280x720p set as default resolution. is that what you meant ?

still good after re-adding kodi-0003-EGLNativeTypeAmlogic-Enable-GUI-free_scale-when-framebuffer-size-is-less-than-output.patch and kodi-0006-fix-resolution-fallback.patch.

**Comment by kszaq** [comment]
Yes, the second one: keep kodi-0003-EGLNativeTypeAmlogic-Enable-GUI-free_scale-when-framebuffer-size-is-less-than-output.patch, kodi-0006-fix-resolution-fallback.patch and add http://sprunge.us/DUdD

But I don't know if then the reason for this patch still works: use 4K TV, set 1080p for GUI, play 4K video.

**Comment by stefansaraev** [comment]
@ksooo yep. I already found I still need your patches that were removed by this pr, without them samples play fine but gui is not rendered correctly. thanks.

**Comment by lrusak** [comment]
@wrxtasy can you rebase with the suggestions in this PR?

**Comment by lrusak** [comment]
@wrxtasy just another kind nudge to rebase with the requested changes.

**Comment by wrxtasy** [comment]
I've just been testing them, just got to work out how to rebase. 
I image pull a from new LE master and add changes and commit again ?

**Comment by stefansaraev** [comment]
```
git checkout 2160p_scaling
git remote add upstream https://github.com/LibreELEC/LibreELEC.tv.git
git fetch upstream
git rebase upstream/master

# do your changes (keep kszaq patches, move projects/WeTek_Play_2/patches/kodi/0001-aml-Scale-video-axis-correctly-when-1080p-to-2160p-s.patch to mediacenter/kodi/patches/aarch64, pick https://github.com/stefansaraev/xbmc/commit/cf4d1b4f9b291197ebbea3bab36179575a470a7f and that should be it)

git push -f origin 2160p_scaling
```

**Comment by stefansaraev** [comment]
I dont know if kodi-0006-fix-resolution-fallback.patch is still needed. you can squash everything into one commit.

**Comment by wrxtasy** [comment]
A...
git pull upstream master
merge the commit
redo the patches, squish some..
commit Em
Push
Review the work
Swear a bit for deleting the wrong Kodi 003 patch !
Re-add it
Beer !!! ;)

**Comment by stefansaraev** [comment]
nope. you should use pull --rebase. merge commits should not appear in PRs

**Comment by wrxtasy** [comment]
Thx for your help.

I've rebased as per instructions and did a -f push and I now see the correct patches reflected above.

**Comment by stefansaraev** [comment]
it seems you added -fix-resolution-fallback.patch contents to -aml-Scale-video-axis-correctly-when-1080p-to-2160p-switching.patch but forgot to remove it. is that what you want?

**Comment by wrxtasy** [comment]
Fixed thx.

**Pull request merged**
