### PR TITLE
ffmpeg: Update to ffmpeg 3.0.1 and Kodi upstream

### PR DESCRIPTION
**Pull request by MilhouseVH**
## !!\*\*KODI 17**!!

Major ffmpeg version change.

Switch to Kodi as upstream, allowing us to drop Kodi-specific patches.

Drops dcadec, which is now included in ffmpeg 3.0.

Adds popcornmix HEVC optimisations and bug fixes (previously RPi2 specific in Kodi 16).

### CODE REVIEW

**Comment by the-dreamer** [comment]
this PR is not compatible with PR98:

building kodi fails:
checking for vorbis/vorbisfile.h... yes
checking for LIBDCADEC... no
configure: error: libdcadec not found

not sure if PR98 contains a to old Kodi rev. (from 29 march.)

**Comment by MilhouseVH** [comment]
> not sure if PR98 contains a to old Kodi rev. (from 29 march.)

That probably it, I've been building with top of tree Kodi master without any issues (PR98 + PR77, bump to latest kodi master => builds).

No time to look into this today, but if it's not fixed overnight I'll try and confirm it tomorrow.

**Comment by mhueske** [comment]
On imx this works like Milhouse said. PR98 + PR77 + latest kodi master builds (after removing jarvis/imx specific patches). Not yet runtime tesed...

**Comment by lrusak** [comment]
Anything else needed here? This is ready to merge after #98 ?

**Comment by MilhouseVH** [comment]
>  This is ready to merge after #98 ?

I think so, yes.

**Comment by the-dreamer** [comment]
no error regarding this PR after updated PR #98

**Pull request merged**
