### PR TITLE
ffmpeg: update to 6.0

### PR DESCRIPTION
**Pull request by HiassofT**
This PR depends on the kodi ffmpeg 6.0 bump https://github.com/xbmc/xbmc/pull/22967 which isn't merged yet so I'm creating it as draft.

I've updated all ffmpeg patches and switched the AML ffmpeg version to current RPi version, so everything should build fine.

Runtime testing on RPi looks good so far

### CODE REVIEW

**Comment by jernejsk** [comment]
Testing on AW (Tanix TX6) also looks good so far

**Comment by Zapeth** [comment]
This is kind of offtopic, but have there been any attempts to upstream the v4l2-request ffmpeg changes? It would be useful to have the backend available upstream for supported devices without having to use a custom ffmpeg build, and lessen the effort required to rebase the patches here.

The last time I talked to ffmpeg devs they seemed to be open to accepting such changes (though admittedly that was some months ago already). Or is there some other reason they haven't been upstreamed so far?

**Comment by chewitt** [comment]
The patchset works well but would not be accepted upstream in its current form as it ignores rules on where (within the ffmpeg codebase) certain things belong. There is an active but slow-burning effort to coerce the current sprawl into a more structured set of changes with everything organised in the right places; suitable for the fun of upstreaming.

**Comment by Zapeth** [comment]
@chewitt thanks for the info, I don't really know much about ffmpeg rules for upstreaming but its good to know that there is something planned

**Review by CvH — APPROVED** [review]

**Pull request merged**
