### PR TITLE
 u-boot: allow using latest version

### PR DESCRIPTION
**Pull request by lrusak**
I use mainline u-boot for my cubox. so I wanted to PR with the option to build it.

@vpeter4 please test with this. It works great with my cubox i4 I'm not sure if it has support for your other imx6 devices like the tbs matrix and others.

### CODE REVIEW

**Comment by lrusak** [comment]
the libfdt crap is only needed for for sunxi so far, it's not relevant for imx6

**Comment by vpeter4** [comment]
Does mainline u-boot supports other devices too? And all SOM revisions?

**Comment by lrusak** [comment]
Looks like some other boards are supported:
tbs matrix http://git.denx.de/?p=u-boot.git;a=blob;f=configs/tbs2910_defconfig
wandboard http://git.denx.de/?p=u-boot.git;a=blob;f=configs/wandboard_defconfig
cubox http://git.denx.de/?p=u-boot.git;a=blob;f=configs/mx6cuboxi_defconfig

I think that is sufficient yeah?

**Comment by linux4kix** [comment]
Mainline is still missing support for our latest boards and soms.  I have a series of patches to add support, but also requires switching over to using device-tree overlays.  I am just waiting on another customer patchset that needs to also be mainlined and I will be working to get everything upstream.  I can push a testing repository out later this week for those interested.

**Comment by vpeter4** [comment]
@lrusak: I'm already using mainline u-boot for other boards. That's the reason for package https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/tools/u-boot-v2

**Pull request closed without merging**
