### PR TITLE
screensaver.shadertoy: Add package

### PR DESCRIPTION
**Pull request by MilhouseVH**
Build and run-time tested on both RPi and Generic.

### CODE REVIEW

**Comment by lrusak** [comment]
good to go?

**Comment by chewitt** [comment]
This is pi/Generic only at the moment. It needs consideration for WP/WC and imx6 builds.

**Comment by MilhouseVH** [comment]
It's only RPi-specific in the sense that RPi requires additional VideoCore headers - it's entirely possible imx6/WC/WP won't require further changes to this package.mk in order to build Shadertoy.

Can someone build imx6/WC/WP with this PR? If it works then `visualization.shadertoy` can be updated too, since it will only build for x86 right now. I can submit a PR for that, or @chewitt can update #62.

**Comment by lrusak** [comment]
Builds fine on the wetek play. :+1:

**Pull request merged**
