### PR TITLE
linux: add missing 4.7.x options

### PR DESCRIPTION
**Pull request by MilhouseVH**
These are required by the latest kernel bump, although I've been building fine without them (clean x2) some people need them. All defaults.

@lrusak: Virtual is a copy of Generic, not sure if you need anything different in Virtual.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
@piotrasd: updated.

**Comment by stefansaraev** [comment]
in the past, CONFIG_EFI_MIXED was known to cause boot failures on some 64bit uefi configurations. no idea if this is still an issue (things may have changed in the meantime), and I dont remember the exact boards.

**Comment by piotrasd** [comment]
i checked few devices ... and was fine. We will see if someone raport after test @MilhouseVH

**Comment by MilhouseVH** [comment]
I've tested a Skylake NUC (UEFI) and Revo3700 (legacy BIOS), both booted OK.

@stefansaraev I'll get you an img.gz ASAP - will take a bout 30-40 minutes.

**Comment by MilhouseVH** [comment]
img.gz: http://milhouse.libreelec.tv/builds/testing/Generic/LibreELEC-Generic.x86_64-8.0-Milhouse-20160919182808-%230919b-geaa6d81.img.gz

Thanks again.

**Comment by stefansaraev** [comment]
all good. boots fine on that stone old zotac box.

**Comment by MilhouseVH** [comment]
Thanks - probably best to let this bake for a couple of days and if no problems then merge.

**Comment by lrusak** [comment]
would be nice to get this merged ASAP, so if there are options you aren't sure about I would split them out into another PR. Otherwise jenkins and things will fail without default options set.

**Comment by MilhouseVH** [comment]
OK hang on.

**Comment by MilhouseVH** [comment]
Back to 100% defaults. I'll create another PR for the two new options.

**Comment by lrusak** [comment]
Yep works, thanks.

**Pull request merged**
