### PR TITLE
Inadyn: Update to 2.4

### PR DESCRIPTION
**Pull request by miikka75**
- Update to 2.4
- Add custom option for defining DDNS services which
  are not natively supported by inadyn

Signed-off-by: Miikka Tuppurainen <miikka75@gmail.com>

### CODE REVIEW

**Comment by miikka75** [comment]
I added command line option "-C" to inadyn because my DDNS provider returns error 200, if IP address hasn't changed: https://www.dy.fi/page/specification

**Comment by awiouy** [comment]
Thank you for your pull request.

The version update is very welcome, but the other changes you propose are less.

The custom option already exists. To use it, select `inadyn.conf` as Provider in the settings of the addon, and create `/storage/.kodi/userdata/addon_data/service.system.inadyn/inadyn.conf` with the appropriate configuration. You can create this file via either smb or ssh. Inadyn will pick up the file the next time it is started (at reboot, after addon disable/enable, or via the `systemctl restart service.system.inadyn` command.

The `continue-on-error` flag is discouraged both [by inadyn](https://github.com/troglobit/inadyn/blob/master/man/inadyn.8#L183-L190) and by [your provider (see the nochg section)](https://www.dy.fi/page/specification). If you use the `inadyn.conf` configuration file, you can reduce the number of nochg replies by increasing the value of `period`.

As for checkip, user the `inadyn.conf` configuration file if you need it.

Let me know if you need some help with creating or using the `inadyn.conf` configuration file.

**Comment by miikka75** [comment]
Thanks for your review and comments.

I am not familiar how service addons are behaving in the system. I am/was assuming that when inadyn fails with any error (for example nochg - as it happens to me because my IP doesn't change very often - not weekly or even monthly) and exits, whole service stops. Is inadyn executed again periodically if it is not running anymore in the system?

Reason I implemented UI configuration way of defining DDNS service is that there would be no need to use smb or ssh to create such file. As an average user (as I am), I would expect to find a way configure everything from UI. Because I was not familiar with Kodi addons, it took some reading of the shell scripts to figure out where to place the `inadyn.conf` file. So, that's why I would like to have the UI way of creating `inadyn.conf` file.

**Comment by awiouy** [comment]
@miikka75 

Addons could provide all bells and whistles from the Kodi user interface, but then they become difficult to develop and maintain. In the case of inadyn, my idea was that an average user should be able to configure a pre-defined provider from Kodi, while all other cases would be covered by the `inadyn.conf` configuration file. Your use case corresponds to the latter.

My suggestion in your case:
1. install the addon and configure it to use the `inadyn.conf` provider
2. ssh to your LibreELEC device
3. `nano /storage/.kodi/userdata/addon_data/service.system.inadyn/inadyn.conf` to edit it
4. `systemctl restart service.system.inadyn` to restart the service
5. `journalctl -u service.system.inadyn` to view the log
6. repeat 5 after some time, eg an hour

You could also ask the the inadyn developer to add your provider.

I am not familiar with the checkip function. If it is frequently used, we could add it to the user interface.

**Comment by mtuppura** [comment]
Removed UI changes and left only version update.

**Comment by awiouy** [comment]
Thank you @mtuppura

**Pull request merged**
