### PR TITLE
 buildsystem: add support for building extra packages specified in project or device options

### PR DESCRIPTION
**Pull request by adamg88**
As the title says, we have a couple of packages in projects/Amlogic (only 1 listed at present) that are required to be built.

As can be seen this has been added to the end of packages/virtual/debug/package.mk as this is the very last point in the build system that packages are compiled before an image is created.

I'm open to suggestions if anybody thinks this could or should be placed elsewhere.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I would suggest a new virtual package `packages/virtual/misc-packages` (add an entry in `scripts/image`, probably between `remote` and `virtual`) and then deal with `$ADDITIONAL_PACKAGES` in the `misc-packages` package rather than `debug`.

`misc-packages` could become a more general "other stuff" virtual package and be expanded upon in future.

**Comment by adamg88** [comment]
I had a feeling you would suggest that @MilhouseVH that was my initial thoughts as well for this PR however I was unsure which method to go with, I will make the changes later, thanks.

**Comment by adamg88** [comment]
PR has been updated as per recommendations

**Comment by MilhouseVH** [comment]
Thanks. I would have preferred a more neutral/general package name such as `misc-packages` (as per initial comment) as I would envisage this new virtual package becoming more of a dumping ground for packages that don't fit elsewhere, and `$ADDITIONAL_PACKAGES` would just be the start. Calling it `additional` (and the short/long descriptions used) makes it rather more specific than I think is necessary  (ie. it's for the `$ADDITIONAL_PACAGES`).

**Comment by adamg88** [comment]
I thought about your suggestion and thought 'additional' was more fitting for the purposes of continuity after looking at the other package names in packages/virtual, I felt 'misc-packages' would have looked out of place, if there is a consensus for misc as opposed to additional then I have no qualms in adjusting it to fit. Just my 2p worth.

**Comment by MilhouseVH** [comment]
`misc-packages` would be the package equivalent of `misc-firmware`. The point is to create a general virtual package "for stuff" and not to name it after the first package that is using it, which then becomes increasingly incorrect as more packages are added (which might be conditional on various variables, eg. $ARCH, or $TARGET_FEATURES etc, so not added through the extension of `$ADDITIONAL_PACKAGES`).

**Comment by adamg88** [comment]
It would be the equivalent if `misc-firmware` was a virtual package but it's not, I don't really another argument with you over your personal views and preferences, I've already made the previous changes you recommended.

**Comment by MilhouseVH** [comment]
> I've already made the previous changes you recommended.

Well no, actually you haven't - you've made the changes _you_ wanted to make, which is not what I suggested.

> I don't really want another argument with you over your personal views and preferences,

It's not an argument, and I'm really not sure why you have to turn it into this kind of discussion yet again. It's not about you, it's about doing getting the code right so that it doesn't have to be done again in future which it almost certainly will be if you leave it like this (not that I'll be merging this, and I hope nobody else will either).

I simply wanted you to implement a more general solution to what is becoming an increasingly common problem but you seem intent on implementing your specific solution for your one problem, rather than something more generic and extensible. Sheesh.

**Comment by Kwiboo** [comment]
I also agree with @MilhouseVH, the name `misc-packages` is much more suited for future usage, i.e. to possible remove the `oem` package, merge other virtual packages or remove hard coded install commands in `scripts/image`.

**Comment by adamg88** [comment]
I removed the code from debug as you requested.

The naming of the virtual package is a personal preference as opposed to technical, its neither here nor there, I have said if anybody feels the same I would be more than happy to change it but I feel that the naming proposed is appropriate for the purposes.

Your second point in relation to conditional arguments is not valid and is based on a scenario that has not happened nor may never happen and this is what we have the PR system for to prevent.

I feel like your baiting an argument here, your right this is not about me but it is not about you either, your personal preferences for the naming of a virtual package has been noted and I already said if anybody else had the same view then I would be happy to change it, I'm not being unreasonable.

**Comment by adamg88** [comment]
@Kwiboo that is what the general idea is to prevent future hard coding of packages needed, there is already provisions in the build system to include packages i.e they could be added to ADDITIONAL_DRIVERS or DRIVER_ADDONS and they will still be build and included but it doesn't look good, the whole thing could probably do with being reworked at some point.

Agreed OEM is also redundant now and should be removed.

**Comment by Kwiboo** [comment]
@adamg88 the 'problem' with `ADDITIONAL_DRIVERS` is that it is built very early in the image building process, I have had issues in the past with missing or circular depends when adding packages there since the drivers is built too early.

This new virtual package will make it a lot easier for downstream projects to add packages to an image and not having to clutter the `distributions/*/options`-file. From a downstream distribution point of view the `misc-packages` name will be much more fitting as the packages I plan to add inside this package is not additional, they are required for my distribution.

**Comment by adamg88** [comment]
@Kwiboo the packages are also needed for Amlogic and as yourself I didn't want to clutter scripts/image or the rest of the buildsystem with specific packages, anyway that makes much more sense 'additional>required', I will adjust the PR shortly, do you have any thoughts on the variable naming in options? Thanks.

**Comment by Kwiboo** [comment]
@adamg88 please keep using the `ADDITIONAL_PACKAGES` variable as this matches `ADDITIONAL_DRIVERS` that is used for similar purpose. All I am asking is that you reconsider the `misc-packages` name that @MilhouseVH suggested, and was something I was going to suggest myself but @MilhouseVH beat me to it.

> Your second point in relation to conditional arguments is not valid and is based on a scenario that has not happened nor may never happen and this is what we have the PR system for to prevent.

This is very much valid as I have this need in my downstream project that is based on LibreELEC. At the moment I have added conditional packages inside my `MEDIACENTER` package and is something I have been wanting to cleanup, moving these packages into a generic `misc-packages` seems like a perfect fit.

**Comment by adamg88** [comment]
I will make the changes shortly. I'm glad Amlogic will not be the only project making use of this.

I merely meant by that point it was a scenario that hadn't happened or may not happen, I didn't know you was using such methods in Rockchip branch then again I don't follow it.

**Comment by Kwiboo** [comment]
Thanks!, I am mainly referring to the RasPlex/OpenPHT-Embedded downstream project, I have also used a similar approach as this in my rockchip development tree when I wanted to include `mpv` in my local test builds, in my latest tree I have extended the `testing` package but at one time I had exactly `ADDITIONAL_PACKAGES` that I could pass on command line to include my test packages.

**Comment by adamg88** [comment]
@MilhouseVH @Kwiboo 

PR has been updated as requested.

**Comment by MilhouseVH** [comment]
Thanks - the general solution now looks fine to me, although I can't speak for the Amlogic part, but I'll assume it's OK unless anyone shouts tomorrow. I guess we also need to remember to use 2018 in license headers. :smile:

**Comment by adamg88** [comment]
@MilhouseVH I have updated the header 

I did test the changes in my fork prior to the changes requested and they worked as desired however the S905 device is not really ready in master yet.

**Comment by MilhouseVH** [comment]
Many thanks. I think I'll merge this, if there's a problem it will be just with S905 so the impact will be limited. Thanks again.

**Comment by adamg88** [comment]
Thanks :+1:

**Pull request merged**
