### PR TITLE
firmwares: use upstream repo [RFC]

### PR DESCRIPTION
**Pull request by MilhouseVH**
This updates `misc-firmware` package to use github url and hash based versioning. This PR needs updating if/when https://github.com/LibreELEC/misc-firmware/pull/1 is merged.

`x86-firmware` is renamed to `kernel-firmware`. From this package we now install those firmwares that were formerly in `misc-firmware`, via the [kernel repo](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/).

Since the kernel repo contains a lot of firmware files we don't need, there are control files that determine which files are installed. These control files can exist for all projects and devices (`any.dat`), and also the target arch (currently only `x86_64.dat`) so that we don't install, for example, `e100` and `intel` firmware on ARM devices.

I've continued to install the `ar3k` (Atheros), `bnx2` (Broadcom NetXtremeII) and `tigon` (obscure GigE controller) firmwares on all platforms as I've no idea if these are still needed or not. If anyone has suggestions (eg. "remove them" or "move them to x86_64") then please shout.

I've assumed the `rtl_bt` firmwares are needed by all projects, and that only x86_64 requires `rtl_nic` firmware. However if this is incorrect, I'll change - just shout.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Complete list of firmware files that are/were being installed from `misc-firmware` (the list does not include the `brcm` files that remain in `misc-firmware`):
```
ar3k/1020200/ar3kbdaddr.pst
ar3k/1020200/PS_ASIC.pst
ar3k/1020200/RamPatch.txt
ar3k/1020201coex/ramps_0x01020201_26_HighPriority.dfu
ar3k/1020201/PS_ASIC.pst
ar3k/1020201/RamPatch.txt
ar3k/30000/ar3kbdaddr.pst
ar3k/30000/PS_ASIC.pst
ar3k/30000/RamPatch.txt
ar3k/30101/ar3kbdaddr.pst
ar3k/30101coex/ar3kbdaddr.pst
ar3k/30101coex/PS_ASIC_aclHighPri.pst
ar3k/30101coex/PS_ASIC_aclLowPri.pst
ar3k/30101coex/PS_ASIC.pst
ar3k/30101coex/RamPatch.txt
ar3k/30101/PS_ASIC.pst
ar3k/30101/RamPatch.txt
ar3k/30101/Readme.txt
ar3k/AthrBT_0x01020001.dfu
ar3k/AthrBT_0x01020200.dfu
ar3k/AthrBT_0x01020201.dfu
ar3k/AthrBT_0x11020000.dfu
ar3k/AthrBT_0x11020100.dfu
ar3k/AthrBT_0x31010000.dfu
ar3k/AthrBT_0x41020000.dfu
ar3k/ramps_0x01020001_26.dfu
ar3k/ramps_0x01020200_26.dfu
ar3k/ramps_0x01020200_40.dfu
ar3k/ramps_0x01020201_26.dfu
ar3k/ramps_0x01020201_40.dfu
ar3k/ramps_0x11020000_40.dfu
ar3k/ramps_0x11020100_40.dfu
ar3k/ramps_0x31010000_40.dfu
ar3k/ramps_0x41020000_40.dfu
ath3k-1.fw
bnx2/bnx2-mips-06-6.2.1.fw
bnx2/bnx2-mips-09-6.2.1a.fw
bnx2/bnx2-rv2p-06-6.0.15.fw
bnx2/bnx2-rv2p-09-6.0.17.fw
bnx2/bnx2-rv2p-09ax-6.0.17.fw
e100/d101m_ucode.bin
e100/d101s_ucode.bin
e100/d102e_ucode.bin
intel/dsp_fw_bxtn_v1118.bin
intel/dsp_fw_bxtn_v2010.bin
intel/dsp_fw_bxtn_v430.bin
intel/dsp_fw_bxtn_v702.bin
intel/dsp_fw_kbl_v1037.bin
intel/dsp_fw_kbl_v701.bin
intel/dsp_fw_release_v827.bin
intel/dsp_fw_release_v869.bin
intel/dsp_fw_release_v896.bin
intel/dsp_fw_release_v927.bin
intel/dsp_fw_release_v948.bin
intel/dsp_fw_release_v951.bin
intel/dsp_fw_release_v958.bin
intel/dsp_fw_release_v969.bin
intel/fw_sst_0f28.bin
intel/fw_sst_0f28.bin-48kHz_i2s_master
intel/fw_sst_0f28_ssp0.bin
intel/fw_sst_22a8.bin
intel/ibt-11-5.ddc
intel/ibt-11-5.sfi
intel/ibt-12-16.ddc
intel/ibt-12-16.sfi
intel/ibt-hw-37.7.10-fw-1.0.1.2d.d.bseq
intel/ibt-hw-37.7.10-fw-1.0.2.3.d.bseq
intel/ibt-hw-37.7.10-fw-1.80.1.2d.d.bseq
intel/ibt-hw-37.7.10-fw-1.80.2.3.d.bseq
intel/ibt-hw-37.7.bseq
intel/ibt-hw-37.8.10-fw-1.10.2.27.d.bseq
intel/ibt-hw-37.8.10-fw-1.10.3.11.e.bseq
intel/ibt-hw-37.8.10-fw-22.50.19.14.f.bseq
intel/ibt-hw-37.8.bseq
intel/IntcSST2.bin
LICENCE.ibt_firmware
LICENCE.IntcSST2
rtl_bt/rtl8192ee_fw.bin
rtl_bt/rtl8192eu_fw.bin
rtl_bt/rtl8723a_fw.bin
rtl_bt/rtl8723b_fw.bin
rtl_bt/rtl8761a_fw.bin
rtl_bt/rtl8812ae_fw.bin
rtl_bt/rtl8821a_fw.bin
rtl_nic/rtl8105e-1.fw
rtl_nic/rtl8106e-1.fw
rtl_nic/rtl8106e-2.fw
rtl_nic/rtl8107e-1.fw
rtl_nic/rtl8107e-2.fw
rtl_nic/rtl8168d-1.fw
rtl_nic/rtl8168d-2.fw
rtl_nic/rtl8168e-1.fw
rtl_nic/rtl8168e-2.fw
rtl_nic/rtl8168e-3.fw
rtl_nic/rtl8168f-1.fw
rtl_nic/rtl8168f-2.fw
rtl_nic/rtl8168g-1.fw
rtl_nic/rtl8168g-2.fw
rtl_nic/rtl8168g-3.fw
rtl_nic/rtl8168h-1.fw
rtl_nic/rtl8168h-2.fw
rtl_nic/rtl8402-1.fw
rtl_nic/rtl8411-1.fw
rtl_nic/rtl8411-2.fw
tigon/tg3.bin
tigon/tg3_tso5.bin
tigon/tg3_tso.bin
```

**Comment by MilhouseVH** [comment]
`bnx2` and `tigon` now only installed for `x86_64`

**Comment by piotrasd** [comment]
+ please add backport (before 8.0.2) - some BT fw are needed in LE8 ...

**Comment by chewitt** [comment]
@piotrasd if there are BT firmwares missing/needed for 8.0 branch please get the files PR'd to misc-firmware so they can be included in the next maintenance release. There are currently no plans to backport the larger repo changes in this PR to 8.0 branch.

**Pull request merged**
