### PR TITLE
Use mesa for Allwinner H6 devices

### PR DESCRIPTION
**Pull request by dhewg**
Mesa/panfrost/T720 is now in a [promising looking state](https://forum.libreelec.tv/thread/17565-nightly-images-for-a64-h3-and-h6-boards/?postID=130204#post130204).

This switches from libmali to mesa for just the H6 devices - H3 and A64 stay at libmali.

Note: I tested this only on 5.4.0-rc7, so on top of #3879 and #3967. Those should land first before considering this, since there have been many panfrost fixes:
```
git shortlog v5.3..v5.4-rc7 drivers/gpu/drm/panfrost/

Christian König (1):
      dma-buf: rename reservation_object to dma_resv

Daniel Vetter (2):
      drm/prime: Actually remove DRIVER_PRIME everywhere
      drm/panfrost: don't set gem_obj->resv for prime import anymore

Linus Torvalds (2):
      Merge tag 'drm-next-2019-09-18' of git://anongit.freedesktop.org/drm/drm
      Merge tag 'drm-next-2019-09-27' of git://anongit.freedesktop.org/drm/drm

Mark Brown (1):
      drm/panfrost: Fix regulator_get_optional() misuse

Maxime Ripard (1):
      Merge v5.3-rc1 into drm-misc-next

Rob Herring (23):
      Revert "drm/panfrost: Use drm_gem_map_offset()"
      Revert "drm/panfrost: Use drm_gem_map_offset()"
      drm/panfrost: Remove completed features still in TODO
      drm/panfrost: Add madvise and shrinker support
      drm/panfrost: Restructure the GEM object creation
      drm/panfrost: Split panfrost_mmu_map SG list mapping to its own function
      drm/panfrost: Add a no execute flag for BO allocations
      drm/panfrost: Consolidate reset handling
      drm/panfrost: Convert MMU IRQ handler to threaded handler
      drm/panfrost: Add support for GPU heap allocations
      drm/panfrost: Bump driver version to 1.1
      drm/panfrost: Implement per FD address spaces
      drm/panfrost: Fix sleeping while atomic in panfrost_gem_open
      drm/panfrost: Fix possible suspend in panfrost_remove
      drm/panfrost: Use mutex_trylock in panfrost_gem_purge
      drm/panfrost: Rework runtime PM initialization
      drm/panfrost: Hold runtime PM reference until jobs complete
      drm/panfrost: Remove unnecessary mmu->lock mutex
      drm/panfrost: Rework page table flushing and runtime PM interaction
      drm/panfrost: Split mmu_hw_do_operation into locked and unlocked version
      drm/panfrost: Add cache/TLB flush before switching address space
      drm/panfrost: Flush and disable address space when freeing page tables
      drm/panfrost: Remove unnecessary hwaccess_lock spin_lock

Robin Murphy (1):
      drm/panfrost: Don't dereference bogus MMU pointers

Sean Paul (1):
      Revert "Revert "drm/panfrost: Use drm_gem_map_offset()""

Steven Price (9):
      drm/panfrost: Use drm_gem_map_offset()
      drm/panfrost: Export all GPU feature registers
      drm/panfrost: Enable devfreq to work without regulator
      drm/panfrost: Remove opp table when unloading
      drm/panfrost: Add missing check for pfdev->regulator
      drm/panfrost: Remove NULL checks for regulator
      drm/panfrost: Prevent race when handling page fault
      drm/panfrost: Add missing GPU feature registers
      drm/panfrost: Handle resetting on timeout better

Tomeu Vizoso (1):
      panfrost: Properly undo pm_runtime_enable when deferring a probe

Wei Yongjun (1):
      drm/panfrost: Fix missing unlock on error in panfrost_mmu_map_fault_addr()

Will Deacon (5):
      iommu/io-pgtable: Rename iommu_gather_ops to iommu_flush_ops
      iommu/io-pgtable: Hook up ->tlb_flush_walk() and ->tlb_flush_leaf() in drivers
      iommu/io-pgtable: Replace ->tlb_add_flush() with ->tlb_add_page()
      iommu/io-pgtable: Remove unused ->tlb_sync() callback
      iommu/io-pgtable: Pass struct iommu_iotlb_gather to ->unmap()

Yi Wang (1):
      drm/panfrost: fix -Wmissing-prototypes warnings

Yue Hu (1):
      drm: Switch to use DEVFREQ_GOV_SIMPLE_ONDEMAND constant
```

### CODE REVIEW

**Comment by dhewg** [comment]
cc @jernejsk

**Comment by jernejsk** [comment]
Thanks! I'll try that after Linux 5.4 is released.

**Comment by clementperon** [comment]
Could you add also the patch for Tanix TX6  ? 

https://git.kernel.org/pub/scm/linux/kernel/git/sunxi/linux.git/commit/?h=sunxi/for-next&id=3f04e059245ee92cd6b4b5b0013d58ae89edc4bd

**Comment by dhewg** [comment]
@clementperon Sorry, didn't see that commit, but done ;)

**Comment by jernejsk** [comment]
@dhewg I like to have patches from upstream in one of the two patch collections named 0001-backport-from-xxx.patch and 0001-backport-from-yyy.patch. Once 5.4 PR is merged, please add them to appropriate collection. I believe all except the one mentioned by @clementperon should go to 5.5 and the other one in 5.6 collection.

**Comment by jernejsk** [comment]
Otherwise these changes looks good, thanks!

**Comment by clementperon** [comment]
@jernejsk all are planned for 5.5, I think you confuse with the USB3 patch for Tanix TX6

**Comment by jernejsk** [comment]
ah, yes, sorry.

**Comment by dhewg** [comment]
Sure, I can add them to the 5.5.patch. I didn't do that because conflicts are handled on a per file basis (It will conflict once the misplaced "media: pixfmt-compressed.rst: improve H264/HEVC/MPEG1+2 /VP8+9" is removed there).

**Comment by dhewg** [comment]
@jernejsk How about you fixup #3967 with the patch I linked there, and then I'll rebase on that and move the patches?

**Comment by jernejsk** [comment]
yeah, I'll do it, as sson as I finish some tests

**Comment by dhewg** [comment]
Done, thanks!

**Comment by dhewg** [comment]
cc @chewitt for the mesa/panfrost bump

**Comment by chewitt** [comment]
I don't have time to test the mesa bump at the moment, but if it works for Allwinner I would epect it to work for Amlogic too. Kodi makes fairly simple demands on the GPU so any fundamental issues are likely to break both platforms.

**Comment by dhewg** [comment]
rebased and bumped mesa
tested on final v5.4, still looking promising :)

**Comment by 150balbes** [comment]
@dhewg 
On AML and RK33xx with kernel 5.3 with mesa-20, no errors detected.

**Comment by dhewg** [comment]
Nice, thanks for testing it on those platforms!

**Comment by chewitt** [comment]
Amlogic also tested on 5.4 with lima/panfrost .. no drama that I can see

**Comment by dhewg** [comment]
Updated with a mesa bump for the latest T720 patches, including its whitelisting

**Pull request merged**
