### PR TITLE
linux: include HBR and ELD fixes for Intel [backport]

### PR DESCRIPTION
**Pull request by MilhouseVH**
Backport of #2002 

This needs testing - I've done this blind. The patches apply, no idea if they build, or even work.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Added WIP until patches confirmed as working.

**Comment by MilhouseVH** [comment]
Adding "merge blocked" label, as this doesn't seem to play so well with 4.11.y. If necessary we skip this for 8.2.0.

**Comment by MilhouseVH** [comment]
@fritsch has confirmed this PR is working as expected with 4.11.12.

```
14:44 DTS-X: works DTS-HDMA: works DD+: works AC3: works DTS: works
14:44 TrueHD + Atmos: works
14:44 I tested it without Adjust Refreshrate as I (personally) have a problem with that and my J4250
```

PR updated with v2 patches. I'll upload another test build. Will leave blocker label until we determine this is safe for all users.

**Comment by chewitt** [comment]
No need for MERGE BLOCKED if in WORK IN PROGRESS state.

**Comment by chewitt** [comment]
I'm closing this PR. The fixes work fine on current generations of NUC hardware but cause problems on earlier generations and this makes them unsuitable for 8.2 releases. Issues are resolved once we reach 4.14 kernels (LE9.0).

**Pull request closed without merging**
