### PR TITLE
RK3399: add roc-pc-plus

### PR DESCRIPTION
**Pull request by cljidkx**
Added support for rk3399-roc-pc-plus, mainly modified and added the device tree and added peripheral drivers.

### CODE REVIEW

**Comment by chewitt** [comment]
Thanks for the PR .. however:

git grep for es8388 shows `sound/soc/codecs/es8328-i2c.c:  { .compatible = "everest,es8388", },` so you should implement support to use the existing in-kernel driver instead of adding a vendor driver? .. or provide changes to the upstream driver if any are needed (we will be happy to add a backport patch for the accepted changes).

In case it wasn't clear from previous answers, we have no interest in adding more out-of-tree Realtek WiFi drivers. They break with every kernel bump and are a long-term problem to maintain.

We are happy to add patches for device-tree changes; if those changes are accepted in the upstream kernel, e.g. a backport to our kernel version is fine. We are not interested in adding changes that are not merged (or at least submitted by a trusted contributor we know will complete the upstream process).

**Comment by cljidkx** [comment]
> Thanks for the PR .. however:
> 
> git grep for es8388 shows `sound/soc/codecs/es8328-i2c.c: { .compatible = "everest,es8388", },` so you should implement support to use the existing in-kernel driver instead of adding a vendor driver? .. or provide changes to the upstream driver if any are needed (we will be happy to add a backport patch for the accepted changes).
> 
> In case it wasn't clear from previous answers, we have no interest in adding more out-of-tree Realtek WiFi drivers. They break with every kernel bump and are a long-term problem to maintain.
> 
> We are happy to add patches for device-tree changes; if those changes are accepted in the upstream kernel, e.g. a backport to our kernel version is fine. We are not interested in adding changes that are not merged (or at least submitted by a trusted contributor we know will complete the upstream process).
> 
> and for future reference, we like each major change in its own commit for tracking purposes, not bundled all-in-one.

Ok, I will modify it on es8328. But if I don’t have TRL8723DU driver, I will not be able to use WIFI and Bluetooth

**Comment by mo123** [comment]
Hi

Must also change LibreELEC.tv/distributions/LibreELEC/options
otherwise RTK8723DU wifi driver isn't build
  ADDITIONAL_DRIVERS="RTL8192CU RTL8192DU RTL8192EU RTL8188EU RTL8812AU RTL8723DU"

There is a syntax error, extra ';' needed in rk3399.dtsi file change
<3 RK_PD7 1 &pcfg_pull_none>; instead of <3 RK_PD7 1 &pcfg_pull_none>,

-----------------------------------------------------------------------------------------------------
Perhaps the RTL8723DU wifi driver can only be build for ROC-RK3399-PC-PLUS and for all other devices disabled in LE so it doesn't cause problems.

Or extra build steps to add the wifi driver manually can be added to LE RK3399 readme and the wifi driver excluded so users have instructions to add it themselves which isn't difficult, only 2 files need to be changed.
I see the wifi driver is updated regularly and also supports the 5.12 kernel already so it should work on future LE too without problems just like the RTL8192CU RTL8192DU RTL8192EU RTL8188EU RTL8812AU ones.

**Comment by cljidkx** [comment]
> Hi
> 
> Must also change LibreELEC.tv/distributions/LibreELEC/options
> otherwise RTK8723DU wifi driver isn't build
> ADDITIONAL_DRIVERS="RTL8192CU RTL8192DU RTL8192EU RTL8188EU RTL8812AU RTL8723DU"
> 
> There is a syntax error, extra ';' needed in rk3399.dtsi file change
> <3 RK_PD7 1 &pcfg_pull_none>; instead of <3 RK_PD7 1 &pcfg_pull_none>,
> 
> Perhaps the RTL8723DU wifi driver can only be build for ROC-RK3399-PC-PLUS and for all other devices disabled in LE so it doesn't cause problems.
> 
> Or extra build steps to add the wifi driver manually can be added to LE RK3399 readme and the wifi driver excluded so users have instructions to add it themselves which isn't difficult, only 2 files need to be changed.
> I see the wifi driver is updated regularly and also supports the 5.12 kernel already so it should work on future LE too without problems just like the RTL8192CU RTL8192DU RTL8192EU RTL8188EU RTL8812AU ones.

Hello, thank you for your advice. Now I have adjusted the es8388 chip on the es8328 driver, but there is still a bug, that is, the HDMI is not connected when the board is powered on, and the es8388 can be used. After reconnecting to the HDMI, two  The user can switch and use at will, but the HDMI interface has no system; when the board is powered on, the HDMI interface and audio can be used, but the es8388 cannot be used. I checked that the DAC channel of the chip has data input. And the register configuration  It is also correct, but there is no sound coming out of the headset. This makes me very puzzled, this bug also existed when I used to adapt the es8323 driver.

**Pull request closed without merging**
