### PR TITLE
Fix flickering with graphic overlays for Rockchip/Allwinner

### LINKED ISSUE #9065: [BUG] UI items, subtitles causes playing video to glitch weirdly
### Describe the bug
When playing videos with `ff-h264-drm_prime (HW)` or `ff-vp9-drm_prime (HW)` Decorder, it causes the video to glitch weirdly (UI items like changing volume, mute/unmute, Video Info, etc). Even the Subtitle causes this issue as well.

Videos played locally, over the network, or YouTube Addon, all are affected. 

The issue does not occur with `ff-hevc-drm_prime (HW)` Decorder.

It is happening on a fresh test install too. Here is a video example https://youtu.be/IRxyoZ4qt_w

### How to reproduce
1. Play any video with h264/VP9 Codecs
2. Mute/unmute, disable/enable subtitles, open video info
3. Observe the glitch

### Information
 - LibreELEC Version: 12.0.0
 - Hardware Platform: NanoPC-T4 (RK3399)

### Debug Log
Bug happens randomly, hard to get debug log

### PR DESCRIPTION
**Pull request by NetDwarf**
Fix suggested by [@knaerzche](https://github.com/LibreELEC/LibreELEC.tv/issues/9065#issuecomment-2321517730)

### CODE REVIEW

**Comment by NetDwarf** [comment]
Fix was tested on Rock64 as described here: https://github.com/LibreELEC/LibreELEC.tv/issues/9065#issuecomment-2328519687

**Comment by knaerzche** [comment]
@jernejsk did you test with AW? 
The issue isn't really [visable](https://youtu.be/IRxyoZ4qt_w) when navigating in the gui, but it's *very* visable with subtiles, or just using the info overlay during video playback. I'd say until a fix is found, it's better to revert  https://github.com/xbmc/xbmc/pull/23921 (like RPi does)

**Comment by NetDwarf** [comment]
Okay, compiled and tested the code from [this branch](https://github.com/NetDwarf/LibreELEC.tv/tree/FixFlickerOnRockchipAllwinner) on the QPlus (Allwinner H6/Tanix-like) and it works. There is no flicker on overlay as was present on 12.0.0 when opening menus/infos etc.

**Review by knaerzche — APPROVED** [review]

**Comment by jernejsk** [comment]
> @jernejsk did you test with AW? 
Sorry, not yet. I'm good with reverting it until better solution is found.

**Pull request merged**
