### PR TITLE
Feature/addons service snapserver enhancements

### LINKED ISSUE #6247: [FEATURE] addons snapserver - Allow configuration of the librespot devicename and zeroconf-port
It would be nice to have an option to allow changing the default devicename and
the zeroconf-port of the librespot instance controlled by snapserver.

### PR DESCRIPTION
**Pull request by cr3bs**
Fixes  #6247

### CODE REVIEW

**Comment by heitbaum** [comment]
@cr3bs looking at this one (further) please squash the commits, and house style (use multi line comment in your commit message). I think you can close #6246 - as this is both some “fixes and the improvement”

something like:::

snapserver: fix blah and blah and enable librespot … addon (109)
<blank line>
- fix …..
- fix ….
- update addon to 109
- …..

similar to your changelog.

**Review by heitbaum — APPROVED** [review]
Fine here.

**Comment by cr3bs** [comment]
@CvH I would be really happy if this could be merged :)

**Comment by heitbaum** [comment]
> @CvH I would be really happy if this could be merged :)

Hi @cr3bs - addons are available for download

**Comment by cr3bs** [comment]
@heitbaum @CvH Thanks for merging!

**Pull request merged**
