### PR TITLE
hyperion: update to 355a324, enable qt5

### PR DESCRIPTION
**Pull request by lrusak**
Thanks @stefansaraev for the qt5 package

The patch hyperion-0002-add-extra-linking-libraries.patch is pretty ugly, but it allows it to build and run. Maybe there is a better solution. I just couldn't get the linking order right in cmake, so I just lumped it all together.

Moving to qt5 allows building of the webserver for hyperion. This will also be needed for hyperion.ng

I also did some cleanup to the package to make it simpler.

PS. I don't think this can be backported because of the pcre change.

### CODE REVIEW

**Comment by lrusak** [comment]
pushed a commit to make sure hyperion config gets copied to $ADDON_HOME so hyperion can always run. This allows users to use hypercon or the webconfig to adjust with the config file.

**Comment by stefansaraev** [comment]
you should try qt lts (5.6.x)

**Comment by lrusak** [comment]
added a fixup to use qt 5.6.2

anything else?

**Comment by lrusak** [comment]
Damn, got some fixup's in there :(

**Pull request merged**
