### PR TITLE
glibc: allow users to define locales on local storage

### PR DESCRIPTION
**Pull request by kad**
Signed-off-by: Alexander D. Kanevskiy <kad@kad.name>

### CODE REVIEW

**Comment by chewitt** [comment]
Is there a size impact on built images from this change?

**Comment by kad** [comment]
before patch, current master:
```
-rw-r--r-- kad/users 123326464 2016-06-15 21:12 LibreELEC-RPi.arm-8.0-devel-20160615210833-r23273-g820ca7d/target/SYSTEM
```
After patch:
```
-rw-r--r-- kad/users 126173184 2016-06-15 21:27 LibreELEC-RPi.arm-8.0-devel-20160615212007-r23274-g9f8b2a6/target/SYSTEM
```

**Comment by lrusak** [comment]
This doesn't effect the kodi experience so I don't think we need it. No from me.

**Comment by kad** [comment]
This would allow 3rd party daemons in user repositories or CLI utilities to work correctly for non-English speaking people. 7 bit ascii is not enough in modern world.

**Pull request closed without merging**
