### PR TITLE
config/arch.aarch64: drop TARGET_ABI=eabi

### LINKED ISSUE #7559: system-tools addon fails to build (cross-compile x86 to aarch64)
```
Dockerfile:

FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get install -y locales sudo \
 && rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8 \
 && update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

RUN adduser --disabled-password --gecos '' docker \
 && adduser docker sudo \
 && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN apt-get update && apt-get install -y \
    wget bash bc gcc-10 sed patch patchutils tar bzip2 gzip xz-utils zstd perl gawk gperf zip \
      unzip diffutils lzop make file g++-10 xfonts-utils xsltproc default-jre-headless python3 \
      libc6-dev libncurses5-dev libjson-perl libxml-parser-perl libparse-yapp-perl \
      golang-1.18-go git openssh-client \
    --no-install-recommends \
 && ln -s /usr/lib/go-1.18 /usr/lib/go \
 && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
    --slave /usr/bin/cpp cpp /usr/bin/cpp-10 \
    --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
    --slave /usr/bin/gcov gcov /usr/bin/gcov-10
RUN update-alternatives --config gcc

RUN ln -s /usr/bin/gcc-10 /usr/bin/cc
USER docker

Build container:

# apply patches to make the image like in CI
sed -i -e "/^USER docker/i RUN ln -s /usr/bin/gcc-10 /usr/bin/cc" tools/docker/focal/Dockerfile

# per tools/docker/README.md
docker build --pull -t libreelec tools/docker/focal

git branch
* (HEAD detached at 11.0.0)
  master

Result:

docker run --rm --log-driver none -v `pwd`:/build -w /build -it -e PROJECT=RPi -e DEVICE=RPi4 -e ARCH=aarch64 libreelec scripts/create_addon system-tools

[112/116] [DONE] build   mtpfs:target
<<< rust:host seq 53 <<<
BUILD      rust (host)
    TOOLCHAIN      manual
install: uninstalling component 'rustc'
install: creating uninstall script at /build/build.LibreELEC-RPi4.aarch64-11.0-devel/build/rust-1.67.1/rust-snapshot/lib/rustlib/uninstall.sh
install: installing component 'rustc'

    rustc installed.

install: uninstalling component 'rust-std-x86_64-unknown-linux-gnu'
install: creating uninstall script at /build/build.LibreELEC-RPi4.aarch64-11.0-devel/build/rust-1.67.1/rust-snapshot/lib/rustlib/uninstall.sh
install: installing component 'rust-std-x86_64-unknown-linux-gnu'

    rust std installed.

install: uninstalling component 'cargo'
install: creating uninstall script at /build/build.LibreELEC-RPi4.aarch64-11.0-devel/build/rust-1.67.1/rust-snapshot/lib/rustlib/uninstall.sh
install: installing component 'cargo'

    cargo installed.

cp: cannot stat '/build/packages/rust/rust/targets/aarch64-libreelec-linux-gnueabi.json': No such file or directory
FAILURE: scripts/build rust:host during configure_host (package.mk)
*********** FAILED COMMAND ***********
cp -a ${PKG_DIR}/targets/${TARGET_NAME}.json ${PKG_BUILD}/targets/${TARGET_NAME}.json
**************************************
FAILURE: scripts/build rust:host has failed!
```

### PR DESCRIPTION
**Pull request by heitbaum**
- Fixes #7559

@lrusak - could you please review. Or are there cases where `gnueabi` will be `gnu`?

### CODE REVIEW

**Comment by HiassofT** [comment]
This looks more like an issue in config/arch.aarch64 - we should build aarch64 for gnu, not gnueabi (which doesn't make sense on aarch64 as eabi implies soft float).

https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/arch.aarch64#L23

I suggest we clean up ARM abi selection, drop soft float support (which we never used, even original RPi1 was hard float), this will simplify our ARM arch config files - gnueabihf for 32bit arm, gnu for aarch64

**Comment by heitbaum** [comment]
> This looks more like an issue in config/arch.aarch64 - we should build aarch64 for gnu, not gnueabi (which doesn't make sense on aarch64 as eabi implies soft float).
> 
> https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/arch.aarch64#L23
> 
> I suggest we clean up ARM abi selection, drop soft float support (which we never used, even original RPi1 was hard float), this will simplify our ARM arch config files - gnueabihf for 32bit arm, gnu for aarch64

Giving that a test run on `PROJECT=Allwinner DEVICE=H6 ARCH=aarch64 s/create_addon system-tools` now

**Comment by heitbaum** [comment]
Build of both rust and make image ok. Need to do some run testing tomorrow.

**Comment by HiassofT** [comment]
runtime test of RPi4 aarch64 build (with kodi Omega and inputstream.adaptive) looks fine here

**Comment by MrDuck2742** [comment]
Clean re-build of:

fde721347f (HEAD, tag: 11.0.0)

with manual change as per above commit(s) - OK - image + addons:

service.net-snmp
service.system.docker
virtual.network-tools
virtual.system-tools

Runtime testing - no issues

**Comment by heitbaum** [comment]
Run tested on `Machine model: Tanix TX6`

**Review by HiassofT — APPROVED** [review]

**Pull request merged**
