### PR TITLE
Move WeTek_Play_2 to Amlogic

### PR DESCRIPTION
**Pull request by Raybuntu**
I need to runtime test this first

### CODE REVIEW

**Comment by adamg88** [comment]
You should be able to use the unified AML-M8AUDIO.conf, the same with WH as well

**Comment by Raybuntu** [comment]
@adamg88 that AML-M8AUDIO.conf is not working properly. Look here too https://github.com/LibreELEC/LibreELEC.tv/pull/2461.
I constantly get no Audio output on my Odroid C2. Reverting fixes it.

As for this PR. I've disabled crazycat and hauppauge driver addons as it requires a prebuilt wetekdvb.ko. @codesnake Can probably provide one for us.
Other than that I've runtime tested on my WP2 and everything seems to work.

**Comment by adamg88** [comment]
I can't speak for the C2 but that audio config has been in use on community builds for quite some time now without issue or if there was I haven't seen it reported 🤐

**Comment by Raybuntu** [comment]
Yeah but we have a different Kernel. No idea how many fixes are in Kszaq's Kernel.

**Pull request merged**
