### PR TITLE
Added support for RTL8812BU

### PR DESCRIPTION
**Pull request by ciaby**
As the title says :) Tested and working on a Raspberry Pi 4.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks, and sorry but no.

Please see the other Realtek PRs for reasons why we don't want to add any more Realtek drivers to the distribution: https://github.com/LibreELEC/LibreELEC.tv/pull/3989#issuecomment-555108656, https://github.com/LibreELEC/LibreELEC.tv/pull/3423#issuecomment-483228677, https://github.com/LibreELEC/LibreELEC.tv/pull/3279#issuecomment-458524243

**Comment by ciaby** [comment]
This driver is working, currently maintained. Does it mean that I have to keep my own fork just for a wifi driver? :-/

**Comment by CvH** [comment]
You could also build it as addon see https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/linux-driver-addons/

The Driver addon at Kodi is also aware of those drivers if implemented. So you could just install it as addon and it should work. I say "should" because nobody tested it yet :)

So you won't need to "fork" and you could easily rebuild if needed.

**Comment by jernejsk** [comment]
> This driver is working, currently maintained.

Yes, but for how long? From what I can see, it won't compile for 5.6, which is already in preparation (#4199). So what now? Wait to be fixed? Alert repo owner? Fix it? Multiply that by the amount of different Realtek chipsets out there which require it's own driver and you get the reason why we are rejecting new out-of-tree Realtek drivers.

**Comment by chewitt** [comment]
The challenge is .. we accept your driver and then we get submissions of another 5-6 and we can't say no because we said yes to the first one. Over time the handful we have support for have proven to be a pain in the rear, but they were popular with older Pi hardware due to lack of on-board wifi at the time and we allowed them. If you think it's unfair that we have some out-of-tree realtek drivers and not others, it's unfair, but I can assure you we're equally keen to dump the older ones we have too. Now isn't the right time, but their days are numbered.

**Comment by MilhouseVH** [comment]
> currently maintained.

Actually, I'd put money on it being dead already, as it's not had any updates in the 6 months since it was created. I very much doubt it will receive the kernel 5.6 support it now requires.

We hate having this conversation with well meaning contributors such as yourself but once you become more familiar with the entire Realtek ecosystem you'll quickly realise it is a total sh*t show, and supporting these out of tree third-party Realtek drivers is letting Realtek off the hook as they should be supporting their hardware with in-tree drivers, not delegating their role to unknown open source community members that often lose interest after publishing a single version on github.

**Comment by ciaby** [comment]
ok, fine. I'll try to keep it up-to-date in my fork, as long as it's working. :)

**Comment by CGarces** [comment]
> I say "should" because nobody tested it yet :)

I can confirm that works fine on several out of tree Realtek drivers. I have used it during testing builds to use wifi without build an entire image.

>ok, fine. I'll try to keep it up-to-date in my fork, as long as it's working. :)

@ciaby you don't need a entire fork, just setup a addon repository with linux-driver-addons.

Fell free to ping me (from a issue opened in your repo) if you have problems with the process.

**Comment by ciaby** [comment]
> > I say "should" because nobody tested it yet :)
> 
> I can confirm that works fine on several out of tree Realtek drivers. I have used it during testing builds to use wifi without build an entire image.
> 
> > ok, fine. I'll try to keep it up-to-date in my fork, as long as it's working. :)
> 
> @ciaby you don't need a entire fork, just setup a addon repository with linux-driver-addons.
> 
> Fell free to ping me (from a issue opened in your repo) if you have problems with the process.
Cool, I'll ping you as soon as I have some time to get the whole thing working.

**Pull request closed without merging**
