### PR TITLE
[WIP] add gobject-introspection

### PR DESCRIPTION
**Pull request by lrusak**
This is something I have been working on for a bit and I thought I would share it incase anyone else has interest.

gobject-introspection is explained here, https://wiki.gnome.org/action/show/Projects/GObjectIntrospection

The problem is that the typelib files have to be compiled for the specific architecture that it is going to be run on but there is no `cross compiler` available (yet) to do this. So we have to build the tool and run it via qemu user emulation to run the binary as it would on the architecture that it will be running on. I have built this for the RPi2 and x86_64 but it still needs work I think. I've cleaned it up as much as I can but there is still some hacky stuff happening.

I wanted to do this originally because dbus-glib is depreciated and shouldn't be use for new projects anymore (see, https://www.freedesktop.org/wiki/Software/DBusBindings/) This means that dbus-python that uses the dbus-glib bindings shouldn't be used anymore. I would like to convert the LibreELEC settings add-on to use this new pydbus implementation however it isn't quite complete yet and doesn't expose all the needed functionality that dbus-python does. Hopefully this changes in the near future.

This work was inspired by patches posted for buildroot and yocto to get gobject-introspection to properly cross compile.

So until there is any actual need for this we don't have to merge it.

### CODE REVIEW

**Comment by edit4ever** [comment]
It may be time to bring this back around - as Python 3.8 breaks python-gobject for LE Settings.

**Comment by lrusak** [comment]
> It may be time to bring this back around - as Python 3.8 breaks python-gobject for LE Settings.

Last I tried I believe there was crashes on arm (RPi), maybe they have been fixed since then. I also believe this way doesn't have all the methods available that we need (It's hard to remember 3 years ago).

**Comment by lrusak** [comment]
might have to look at something like this https://pypi.org/project/dasbus/ as pydbus development looks stalled

**Comment by lrusak** [comment]
There also seems to be a patch for dbus-python here https://src.fedoraproject.org/fork/churchyard/rpms/dbus-python/c/01a4993071babf69f6cb5e222b15caca069768af

**Comment by HiassofT** [comment]
As mentioned here https://github.com/LibreELEC/service.libreelec.settings/pull/173#issuecomment-695198345 there's also dbussy https://github.com/ldo/dbussy

This looks like the most promising approach to me: modern, pure Python 3 implementation without dependencies on glib. It's included in Debian testing and also found it's way into stable-backports.

The other alternatives either have hefty dependencies, are half-unmaintained, or both.

**Comment by chewitt** [comment]
> There also seems to be a patch for dbus-python here https://src.fedoraproject.org/fork/churchyard/rpms/dbus-python/c/01a4993071babf69f6cb5e222b15caca069768af

This patch is already applied in the dbus-python sources we're using.

**Pull request closed without merging**
