### PR TITLE
Revert zstd for SquashFS on RK3328

### PR DESCRIPTION
**Pull request by lorenz**
SquashFS with zstd on Rockchip's RK3328 produces a null pointer deference in the uncompress code.

This can be triggered by either watching multiple high-bandwidth videos (no specific bandwidth, but happens more with > 50Mbps) or much more reliably by shutting down Kodi (systemctl stop kodi) and then starting `memtester 850M` repeatedly and issuing a bit of I/O (for example `ls -lh`) in between. Usually happens after the first 1-5 tries.

I still haven't figured out the exact cause, but here is the kernel log excerpt:
```
[  290.315241] Internal error: Oops: 96000046 [#1] SMP
[  290.315818] Modules linked in: ir_lirc_codec ir_xmp_decoder ir_mce_kbd_decoder lirc_dev ir_rc5_decoder ir_sharp_decoder ir_sanyo_decoder ir_sony_decoder ir_jvc_decoder ir_rc6_decoder ir_nec_decoder snd_usb_audio rc_pine64 gpio_ir_recv snd_hwdep snd_usbmidi_lib snd_rawmidi rc_core mali
[  290.318647] CPU: 3 PID: 279 Comm: kworker/3:3 Not tainted 4.4.154 #1
[  290.319322] Hardware name: Pine64 Rock64 (DT)
[  290.319801] Workqueue: events read_wq_handler
[  290.320277] task: ffffffc037623600 task.stack: ffffffc03679c000
[  290.320911] PC is at __memcpy+0x110/0x180
[  290.321345] LR is at ZSTD_decompressStream+0x190/0xb50
[  290.321890] pc : [<ffffff80083d0f50>] lr : [<ffffff80083f6310>] pstate: 20000145
[  290.322676] sp : ffffffc03679fb30
[  290.323029] x29: ffffffc03679fb30 x28: 0000000000020000 
[  290.323609] x27: ffffffc03679fc70 x26: 0000000000000000 
[  290.324186] x25: ffffff800bf1b010 x24: 0000000000000002 
[  290.324768] x23: ffffffc03679fc88 x22: ffffff8008990960 
[  290.325343] x21: 0000000000001000 x20: ffffffc002f07800 
[  290.325919] x19: ffffffc002f076ee x18: ffffff8008990960 
[  290.326498] x17: 0000000000000001 x16: ffffff800bf1c4a8 
[  290.327080] x15: ffffff800bf1b108 x14: 001d001e00400006 
[  290.327660] x13: 0038004000000000 x12: 0000000000155ac0 
[  290.328239] x11: 0000000000000040 x10: 0000000000001000 
[  290.328821] x9 : 0000000100b70003 x8 : 0000000000000000 
[  290.329398] x7 : 00010102464c457f x6 : 0000000000000000 
[  290.329975] x5 : ffffff800bf819f9 x4 : 0000000000000000 
[  290.330556] x3 : 0000000000001000 x2 : 0000000000000f80 
[  290.331137] x1 : ffffff800bf61260 x0 : 0000000000000000 
[  290.331721] 
[  290.331721] PC: 0xffffff80083d0ed0:
[  290.332247] 0ed0  b8404423 b80044c3 36080062 78402423 780024c3 36000562 38401423 380014c3
[  290.333185] 0ef0  14000028 f1020042 5400024a a8c12027 a88120c7 a8c12829 a8c1302b a88128c9
[  290.334125] 0f10  a88130cb a8c1382d a88138cd f240145f 54fffba1 1400001b d503201f d503201f
[  290.335070] 0f30  d503201f d503201f d503201f d503201f a8c12027 a8c12829 a8c1302b a8c1382d
[  290.336009] 0f50  a88120c7 a8c12027 a88128c9 a8c12829 a88130cb a8c1302b a88138cd a8c1382d
[  290.336954] 0f70  f1010042 54fffeea a88120c7 a88128c9 a88130cb a88138cd f240145f 54fff841
[  290.337894] 0f90  d65f03c0 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  290.338867] 0fb0  00000000 00000000 00000000 00000000 eb01001f 54fff3e3 8b020023 eb03001f
[  290.339806] 
[  290.339806] LR: 0xffffff80083f6290:
[  290.340336] 6290  f9400320 f970301c b500297c a9468b21 b940cb20 eb01005f 54004121 34000840
[  290.341278] 62b0  a9408361 eb01001f 54004623 52800040 d280003c b9003320 1400003b 71000c1f
[  290.342214] 62d0  54000920 7100101f 540006c1 f9403721 f9403b3c cb01039c f94033e0 f9402f24
[  290.343158] 62f0  cb1a0003 eb1c007f aa1a03e0 9a9c9075 8b010081 aa1503e2 f90037e3 97ff6acd
[  290.344098] 6310  8b15035a f9403720 f94037e3 8b0002b5 f9003735 eb1c007f 54fffa03 f9403f21
[  290.345089] 6330  b9003338 f9403320 8b0102b5 eb0002bf 54fff8c9 f9400320 a906ff3f f9703015
[  290.346034] 6350  b4fff8b5 d503201f cb130281 eb15003f 54001583 91401003 f9402f21 f9403722
[  290.346979] 6370  b9608463 8b020021 71001c7f 54002080 f9403323 aa1503e4 cb020062 aa1303e3
[  290.347920] 
[  290.347920] SP: 0xffffffc03679fab0:
[  290.348447] fab0  08990960 ffffff80 3679fc88 ffffffc0 00000002 00000000 0bf1b010 ffffff80
[  290.349388] fad0  00000000 00000000 3679fc70 ffffffc0 00020000 00000000 3679fb30 ffffffc0
[  290.350339] faf0  083f6310 ffffff80 3679fb30 ffffffc0 083d0f50 ffffff80 20000145 00000000
[  290.351324] fb10  3679fc88 ffffffc0 08521ee4 ffffff80 ffffffff ffffffff 00010f78 00000000
[  290.352262] fb30  3679fc00 ffffffc0 082832b0 ffffff80 3e4d4000 ffffffc0 0000015e 00000000
[  290.353200] fb50  39992c00 ffffffc0 00000044 00000000 36515f00 ffffffc0 00000000 00000000
[  290.354143] fb70  0004600a 00000000 00000000 00000000 0bf1b010 ffffff80 00001000 00000000
[  290.355083] fb90  00001000 00000000 00001000 00000000 02f07400 ffffffc0 00000000 00000000
[  290.356023] 
[  290.356023] X1: 0xffffff800bf611e0:
[  290.356553] 11e0  cbdac03a afe7ed76 e2980ada 1984c005 23aec0cc 3fe6dd98 f9af7e90 ca17c430
[  290.357493] 1200  75cc172d e06a3fab bc9fa88e ce3a84c0 505f87d0 fa6c41b8 6a7afd44 ae32d2f7
[  290.358432] 1220  464c457f 00010102 00000000 00000000 00b70003 00000001 00001000 00000000
[  290.359368] 1240  00000040 00000000 00155ac0 00000000 00000000 00380040 00400006 001d001e
[  290.360306] 1260  00000001 00000005 00000000 00000000 00000000 00000000 00000000 00000000
[  290.361244] 1280  0001e4fc 00000000 0001e4fc 00000000 00010000 00000000 00000001 00000006
[  290.362184] 12a0  0001e5b8 00000000 0002e5b8 00000000 0002e5b8 00000000 00001a48 00000000
[  290.363120] 12c0  00001bb0 00000000 00010000 00000000 00000002 00000006 0001edd0 00000000
[  290.364095] 
[  290.364095] X5: 0xffffff800bf81979:
[  290.364622] 1978  00000712 00000000 0041a748 00000000 00000000 00000000 00000713 00000000
[  290.365560] 1998  0041a760 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  290.366500] 19b8  00000000 00000000 00000100 00000000 0041a260 00000000 00000000 00000000
[  290.367441] 19d8  00000101 00000000 0041a278 00000000 00000000 00000000 00000200 00000000
[  290.368384] 19f8  0041a288 00000000 00000000 00000000 00000201 00000000 0041a2a0 00000000
[  290.369330] 1a18  00000000 00000000 00000202 00000000 0041a2b0 00000000 00000000 00000000
[  290.370302] 1a38  00000300 00000000 0041a2c8 00000000 00000000 00000000 00000301 00000000
[  290.371238] 1a58  0041a2e0 00000000 00000000 00000000 00000302 00000000 0041a2b0 00000000
[  290.372176] 1a78  00000000 00000000 00000400 00000000 0041a2f0 00000000 00000000 00000000
[  290.373117] 
[  290.373117] X15: 0xffffff800bf1b088:
[  290.373654] b088  00020000 00000000 fd2fb528 100000a0 00000000 00000000 00000000 00000000
[  290.374591] b0a8  00000009 00000000 083f9350 ffffff80 083f9370 ffffff80 0bf1b000 ffffff80
[  290.375526] b0c8  00000000 00000000 00000000 00000000 00000000 00000000 0bf1b100 ffffff80
[  290.376465] b0e8  0bf1bd08 ffffff80 0bf1b904 ffffff80 0bf1c50c ffffff80 00010009 020000e8
[  290.377413] b108  020100d4 020100d8 020000ec 06030180 020100dc 020000f0 07060100 020100e0
[  290.378354] b128  020100e4 020000f4 040200e0 020100e8 020000f8 050500e0 020100ec 020000fc
[  290.379292] b148  02000100 040200f0 020100f0 02000104 05040140 020100f4 02000108 0200010c
[  290.380230] b168  020100f8 020100fc 02000110 060301c0 02010100 02000114 07080000 02010104
[  290.381170] 
[  290.381170] X16: 0xffffff800bf1c428:
[  290.381705] c428  0101002a 0100014a 0100014c 0101002c 0100014e 01000150 04030180 0101002e
[  290.382645] c448  01000152 070a0180 01010030 01000154 01000156 04030190 01010032 01000158
[  290.383626] c468  07060180 01010034 0100015a 0100015c 04020090 01010036 0100015e 04050030
[  290.384567] c488  01010038 01000160 01000162 0101003a 092f0000 092e0000 092b0000 092a0000
[  290.385509] c4a8  09290000 09280000 09270000 09260000 09250000 09240000 09230000 09220000
[  290.386451] c4c8  09210000 09200000 091f0000 091e0000 091d0000 091c0000 091b0000 091a0000
[  290.387394] c4e8  09190000 09180000 09170000 09160000 09150000 09130000 09120000 090f0000
[  290.388338] c508  090e0000 0c0b000c 0b8d0b5d 0baf0b8f 0bbe0bbd 0bcf0bcd 0bed0bdd 0a2b0a2b
[  290.389325] 
[  290.389325] X18: 0xffffff80089908e0:
[  290.389862] 08e0  00000fa6 00000054 00000499 00000080 0000094b 00000057 000012b1 00000058
[  290.390798] 0900  000004da 00000080 0000096f 0000005d 00001423 00000054 00000545 00000080
[  290.391737] 0920  00000a54 0000006a 0000148c 0000006a 000005af 00000080 00000976 0000007c
[  290.392669] 0940  0000104e 0000007c 000002d2 00000080 00000763 00000091 00000790 00000092
[  290.393607] 0960  00000001 00000002 00000003 00000004 00000005 00000005 00000001 00000004
[  290.394545] 0980  00000008 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  290.395483] 09a0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  290.396420] 09c0  00000000 00000000 00000001 00000001 00000001 00000001 00000002 00000002
[  290.397358] 
[  290.397358] X19: 0xffffffc002f0766e:
[  290.397893] 766c  08fcbdd5 0f11f444 1905be60 6c1476ad 97f799f5 5bfa7fa8 1753b598 a2c5e0ec
[  290.398831] 768c  15b4b0ee 5b506d44 5ec74e42 7e11cf54 f5cfda87 91a10ae4 1ec5ce74 41fae8e7
[  290.399766] 76ac  5f945268 e6352b5f 97cd559f 725a9c6d 9d2fe547 21b6563a f6f10b15 1504a0a2
[  290.400709] 76cc  ba9a3dd1 85d87713 3c54ed77 7c3af730 e967c0ed dd58a8eb 93a844b8 5ac15d81
[  290.401653] 76ec  4c9c21f7 8827be07 10481e66 382cce40 14dabb26 91cccad5 ff1455e6 2a365660
[  290.402616] 770c  e2e2d855 8ed8cb37 944b8da6 6b0b5200 0b2a4a21 3422f113 06874d7d 5cb6488d
[  290.403555] 772c  d35d044c 49b0b72d 93b489ad 29927fc8 3e7ff4a5 841ee91e 34c14d1e 0e4814bd
[  290.404497] 774c  64e259ff 15c8b176 6c0c9149 fe0f2ed7 688d3d08 8f3e359a 6113c276 489e2190
[  290.405437] 776c  e7848c34 85085481 24c2640b 59145a5e a8b6432b 5b880532 8d8a4218 a82ac9ac
[  290.406376] 
[  290.406376] X20: 0xffffffc002f07780:
[  290.406912] 7780  5b880532 8d8a4218 a82ac9ac 4085b19e b923d102 6aa06819 a3d92dfb 98eb9cf8
[  290.407852] 77a0  33eacf38 8abe4522 6b2f486c 6a28dfe6 642f6a49 e36b76ae 39f04e52 eb36a966
[  290.408805] 77c0  e53a3153 61850ef9 5ee7a806 d13d18c4 7cf421b8 5a940287 c9316e04 4ed38350
[  290.409740] 77e0  8354c44e 0616ca2c 30d4a6ab 5081799c 8d97c1a2 4b38138a 0b8d93d5 9b7e36f1
[  290.422426] 7800  276540e8 b632c359 a5226b34 36020a26 0c89f78f b7a17b13 b4f4f393 dd802529
[  290.435048] 7820  50870271 f1475693 14c76262 23598a6f 9dc82531 6dbec1dd 20801e74 05f4d746
[  290.447630] 7840  921e94cc 380f3d2c 255e8379 084883b5 f38f9924 4bc72268 31943408 22fb7420
[  290.460216] 7860  2f9419e6 8e479ce8 108b1ab1 4f52490d 89a2c376 706dcb6a ef4d9939 32175b84
[  290.472879] 
[  290.472879] X22: 0xffffff80089908e0:
[  290.496953] 08e0  00000fa6 00000054 00000499 00000080 0000094b 00000057 000012b1 00000058
[  290.509708] 0900  000004da 00000080 0000096f 0000005d 00001423 00000054 00000545 00000080
[  290.522467] 0920  00000a54 0000006a 0000148c 0000006a 000005af 00000080 00000976 0000007c
[  290.535188] 0940  0000104e 0000007c 000002d2 00000080 00000763 00000091 00000790 00000092
[  290.547911] 0960  00000001 00000002 00000003 00000004 00000005 00000005 00000001 00000004
[  290.560601] 0980  00000008 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  290.573291] 09a0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  290.585649] 09c0  00000000 00000000 00000001 00000001 00000001 00000001 00000002 00000002
[  290.597517] 
[  290.597517] X23: 0xffffffc03679fc08:
[  290.619957] fc08  08282524 ffffff80 39992c00 ffffffc0 3e4d4000 ffffffc0 0000015e 00000000
[  290.631887] fc28  0000036a 00000000 000570a0 00000000 36515f00 ffffffc0 39992c00 ffffffc0
[  290.643817] fc48  37108618 ffffffc0 fffffffb 00000000 00000000 00000000 3679fc80 ffffffc0
[  290.655784] fc68  00000000 00000000 02f07400 ffffffc0 00000400 00000000 00000000 00000000
[  290.667713] fc88  00000000 00000000 00001000 00000000 00000000 00000000 3679fce0 ffffffc0
[  290.679707] fca8  0827dd7c ffffff80 1d95f000 ffffffc0 00000000 00000000 0000015e 00000000
[  290.691613] fcc8  0000015e 00000000 3e4d4000 ffffffc0 36515f00 ffffffc0 3679fd40 ffffffc0
[  290.703596] fce8  0827ddf0 ffffff80 1d95f060 ffffffc0 1d95f060 ffffffc0 3ff88800 ffffffc0
[  290.715614] 
[  290.715614] X25: 0xffffff800bf1af90:
[  290.738457] af90  ******** ******** ******** ******** ******** ******** ******** ********
[  290.750641] afb0  ******** ******** ******** ******** ******** ******** ******** ********
[  290.762778] afd0  ******** ******** ******** ******** ******** ******** ******** ********
[  290.774847] aff0  ******** ******** ******** ******** 0c081230 ffffff80 0c081230 ffffff80
[  290.787033] b010  0bf1b0e0 ffffff80 00000000 00000000 00000000 00000000 00100000 00000000
[  290.799217] b030  00100000 00000000 00000000 00000000 00000004 00000000 0bf41220 ffffff80
[  290.811408] b050  00020000 00000000 00000000 00000000 00100000 00000000 0bf61220 ffffff80
[  290.823609] b070  00120010 00000000 00000000 00000000 00020000 00000000 00020000 00000000
[  290.835818] 
[  290.835818] X27: 0xffffffc03679fbf0:
[  290.858941] fbf0  083f9370 ffffff80 0bf1b000 ffffff80 3679fca0 ffffffc0 08282524 ffffff80
[  290.871272] fc10  39992c00 ffffffc0 3e4d4000 ffffffc0 0000015e 00000000 0000036a 00000000
[  290.883743] fc30  000570a0 00000000 36515f00 ffffffc0 39992c00 ffffffc0 37108618 ffffffc0
[  290.896100] fc50  fffffffb 00000000 00000000 00000000 3679fc80 ffffffc0 00000000 00000000
[  290.908369] fc70  02f07400 ffffffc0 00000400 00000000 00000000 00000000 00000000 00000000
[  290.920661] fc90  00001000 00000000 00000000 00000000 3679fce0 ffffffc0 0827dd7c ffffff80
[  290.932891] fcb0  1d95f000 ffffffc0 00000000 00000000 0000015e 00000000 0000015e 00000000
[  290.945143] fcd0  3e4d4000 ffffffc0 36515f00 ffffffc0 3679fd40 ffffffc0 0827ddf0 ffffff80
[  290.957504] 
[  290.957504] X29: 0xffffffc03679fab0:
[  290.980665] fab0  08990960 ffffff80 3679fc88 ffffffc0 00000002 00000000 0bf1b010 ffffff80
[  290.992915] fad0  00000000 00000000 3679fc70 ffffffc0 00020000 00000000 3679fb30 ffffffc0
[  291.005178] faf0  083f6310 ffffff80 3679fb30 ffffffc0 083d0f50 ffffff80 20000145 00000000
[  291.017403] fb10  3679fc88 ffffffc0 08521ee4 ffffff80 ffffffff ffffffff 00010f78 00000000
[  291.029602] fb30  3679fc00 ffffffc0 082832b0 ffffff80 3e4d4000 ffffffc0 0000015e 00000000
[  291.041715] fb50  39992c00 ffffffc0 00000044 00000000 36515f00 ffffffc0 00000000 00000000
[  291.053875] fb70  0004600a 00000000 00000000 00000000 0bf1b010 ffffff80 00001000 00000000
[  291.065973] fb90  00001000 00000000 00001000 00000000 02f07400 ffffffc0 00000000 00000000
[  291.077977] 
[  291.089246] Process kworker/3:3 (pid: 279, stack limit = 0xffffffc03679c000)
[  291.101088] Stack: (0xffffffc03679fb30 to 0xffffffc0367a0000)
[  291.112783] fb20:                                   ffffffc03679fc00 ffffff80082832b0
[  291.124794] fb40: ffffffc03e4d4000 000000000000015e ffffffc039992c00 0000000000000044
[  291.136755] fb60: ffffffc036515f00 0000000000000000 000000000004600a 0000000000000000
[  291.148716] fb80: ffffff800bf1b010 0000000000001000 0000000000001000 0000000000001000
[  291.160634] fba0: ffffffc002f07400 0000000000000000 0000000000000000 0000000000000400
[  291.172519] fbc0: ffffff80083f9370 ffffff800bf1b000 ffffff80083f9350 ffffff80083f9370
[  291.184422] fbe0: ffffff800bf1b000 ffffff80083f9350 ffffff80083f9370 ffffff800bf1b000
[  291.196319] fc00: ffffffc03679fca0 ffffff8008282524 ffffffc039992c00 ffffffc03e4d4000
[  291.208245] fc20: 000000000000015e 000000000000036a 00000000000570a0 ffffffc036515f00
[  291.220215] fc40: ffffffc039992c00 ffffffc037108618 00000000fffffffb 0000000000000000
[  291.232167] fc60: ffffffc03679fc80 0000000000000000 ffffffc002f07400 0000000000000400
[  291.244154] fc80: 0000000000000000 0000000000000000 0000000000001000 0000000000000000
[  291.256103] fca0: ffffffc03679fce0 ffffff800827dd7c ffffffc01d95f000 0000000000000000
[  291.267991] fcc0: 000000000000015e 000000000000015e ffffffc03e4d4000 ffffffc036515f00
[  291.279853] fce0: ffffffc03679fd40 ffffff800827ddf0 ffffffc01d95f060 ffffffc01d95f060
[  291.291751] fd00: ffffffc03ff88800 0000000000000000 ffffffc03ff8d000 ffffff80092654c8
[  291.303652] fd20: ffffffc03ff88828 0000000000000000 0000000000000000 ffffff8009136000
[  291.315556] fd40: ffffffc03679fd60 ffffff80080b2544 ffffffc0364d4cc0 ffffffc01d95f060
[  291.327511] fd60: ffffffc03679fdb0 ffffff80080b2f94 ffffffc0364d4cc0 ffffffc03ff88800
[  291.339454] fd80: ffffffc03ff88800 ffffff8009264000 ffffff8009175690 ffffffc0364d4cf0
[  291.351341] fda0: ffffffc03ff88828 0000000000000000 ffffffc03679fe00 ffffff80080b7ec0
[  291.363231] fdc0: ffffffc0364d1900 ffffffc037623600 ffffff8008b640eb ffffffc0364d4cc0
[  291.375091] fde0: ffffff80080b2d10 0000000000000000 0000000000000000 0000000000000000
[  291.387000] fe00: 0000000000000000 ffffff8008082ef0 ffffff80080b7de0 ffffffc0364d1900
[  291.398950] fe20: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  291.410942] fe40: ffffffc03679fe60 0000000000000000 ffffffc03ff89000 ffffffc0364d4cc0
[  291.423001] fe60: ffffffc000000000 dead4ead00000000 ffffffc0ffffffff ffffffffffffffff
[  291.435073] fe80: ffffffc03679fe80 ffffffc03679fe80 0000000000000000 dead4ead00000000
[  291.447176] fea0: 00000000ffffffff ffffffffffffffff ffffffc03679feb0 ffffffc03679feb0
[  291.459317] fec0: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  291.471566] fee0: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  291.483697] ff00: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  291.495792] ff20: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  291.507802] ff40: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  291.519748] ff60: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  291.531637] ff80: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  291.543434] ffa0: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  291.555178] ffc0: 0000000000000000 0000000000000005 0000000000000000 0000000000000000
[  291.566847] ffe0: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  291.578476] Call trace:
[  291.589608] Exception stack(0xffffffc03679f960 to 0xffffffc03679fa90)
[  291.601119] f960: ffffffc002f076ee 0000008000000000 ffffffc03679fb30 ffffff80083d0f50
[  291.612868] f980: ffffff800bf1b010 0000000000000000 ffffffc03679fc70 00000000000002ee
[  291.624554] f9a0: ffffff800bf26ef1 ffffff800bf61220 ffffff800bf1b100 ffffff800bf48526
[  291.636223] f9c0: ffffff800bf1b904 ffffff8008990988 ffffff800bf1bd0c ffffff800c081228
[  291.647855] f9e0: 0000002022ee873d ffffff800bf61220 ffffff800bf1f0e0 ffffff800bf4127b
[  291.659448] fa00: 0000000000000000 ffffff800bf61260 0000000000000f80 0000000000001000
[  291.671100] fa20: 0000000000000000 ffffff800bf819f9 0000000000000000 00010102464c457f
[  291.682748] fa40: 0000000000000000 0000000100b70003 0000000000001000 0000000000000040
[  291.694408] fa60: 0000000000155ac0 0038004000000000 001d001e00400006 ffffff800bf1b108
[  291.706076] fa80: ffffff800bf1c4a8 0000000000000001
[  291.717414] [<ffffff80083d0f50>] __memcpy+0x110/0x180
[  291.728800] [<ffffff80082832b0>] zstd_uncompress+0x1a0/0x304
[  291.740212] [<ffffff8008282524>] squashfs_decompress+0x64/0x98
[  291.751624] [<ffffff800827dd7c>] squashfs_process_blocks+0x2bc/0x310
[  291.763110] [<ffffff800827ddf0>] read_wq_handler+0x20/0x2c
[  291.774544] [<ffffff80080b2544>] process_one_work+0x228/0x364
[  291.785986] [<ffffff80080b2f94>] worker_thread+0x284/0x390
[  291.797424] [<ffffff80080b7ec0>] kthread+0xe0/0xf0
[  291.808795] [<ffffff8008082ef0>] ret_from_fork+0x10/0x20
[  291.820297] Code: a8c12027 a8c12829 a8c1302b a8c1382d (a88120c7) 
[  291.832077] ---[ end trace aa152395da0fb1ce ]---
```

There are a bunch of errors after this, but they are most likely caused by this issue and ultimately hang all cores in a kernel spinlock.

I've figured out that the destination base pointer (stored in x0) for `memcpy` in `decompress.c:2320` or `decompress.c:2326` (both get compiled to the same branch instruction) is a null pointer, which is super weird since `zds->headerBuffer` is not dynamically allocated in the first place and should just be an offset to the base pointer of `zds`, which is available and stored in x25.

Since I have no idea what the actual bug is (and currently don't have the time to attach my SWD debugger and debug the whole thing in hardware), just revert to gzip which works reliably.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Did this happen with previous versions of `zstd`, 1.4.0 and 1.38? Strange that this hasn't been seen on RPi or Generic thus far. I'll try running your `memtester 850` test on RPi3+.

**Comment by lorenz** [comment]
I think so. I tried back in May and the build crashed, but I didn't have time to investigate and just reverted to a late-2018 build. The memtester command is dependant on the amount of memory you have, just take most (but not all, that will fail) available memory.

**Comment by HiassofT** [comment]
It's quite likely that the zstd backport in the 4.4 Rockchip kernel has some bug. As I'm not sure anyone's too keen at looking into that I'd also say going back to the known-good previous (gzip) setting.

**Comment by 5schatten** [comment]
Fixed by https://github.com/LibreELEC/LibreELEC.tv/pull/3800/commits/27dff6bd1db06249d97fecd04971070095ea2fcb

**Pull request closed without merging**
