### PR TITLE
 RK3288-MiQi: Remedy wrong config in regulators and actual frequencies

### PR DESCRIPTION
**Pull request by Ntemis**
it can support.

Signed-off-by: Demetris Ierokipides <ierokipides.dem@gmail.com>

### CODE REVIEW

**Comment by SupervisedThinking** [comment]
@Ntemis could you please be a bit more specific what it could support? 1.7/1.8/2.0GHz?

**Comment by Ntemis** [comment]
Correct, the miqi is considered an inferior product from its sibling (see Tinkerboard) Where the sibling has the max frequency of 1.8ghz the miqi is set at 1.6ghz max due to miss-configuration of its gpu and cpu regulators that both are used in later products like the RK3399 family

**Comment by Ntemis** [comment]
https://datasheet.lcsc.com/lcsc/1806121835_Silergy-Corp-SYR828PKC_C111838.pdf
"**The output voltage can be programmed from 0.7125V to 1.5V through I2C interface.**"

**Comment by Ntemis** [comment]
Do Not Merge yet!
regulator-enable-ramp-delay might be needed on miqi.
I will push a fix soon
I get choppy sound / audio cuts out only on libretro cores 
Standalone cores work fine and kernel is very stable but still something is off

**Comment by Ntemis** [comment]
Looks like The gpu freqs dont need such a high voltage anyway
	gpu_opp_table: opp-table-1 {
		compatible = "operating-points-v2";

		opp-100000000 {
			opp-hz = /bits/ 64 <100000000>;
			opp-microvolt = <950000>;
		};
		opp-200000000 {
			opp-hz = /bits/ 64 <200000000>;
			opp-microvolt = <950000>;
		};
		opp-300000000 {
			opp-hz = /bits/ 64 <300000000>;
			opp-microvolt = <1000000>;
		};
		opp-400000000 {
			opp-hz = /bits/ 64 <400000000>;
			opp-microvolt = <1100000>;
		};
		opp-600000000 {
			opp-hz = /bits/ 64 <600000000>;
			opp-microvolt = <1250000>;
		};
	};

**Comment by Ntemis** [comment]
I would need a Rockchip expert opinion here like @heitbaum :)

**Comment by knaerzche** [comment]
@Ntemis HW wise it might be OK for your miqi version, but iirc there were 2 versions of miqi board and only the newer had an RK3288W which allows that. Could you please try to convice Heiko first who rejected this some time ago https://patchwork.kernel.org/project/linux-rockchip/patch/20210108151036.36434-3-ierokipides.dem@gmail.com/#23883027. Real solution would likely be to create a second device tree for the newer board version and only allow that higher frequency opps there.

**Comment by Ntemis** [comment]
@knaerzche Thank you for your guidance on the matter but since am modifying the existing regulators is safe to assume that both RK3288 & W MiQi variants have the same ones. Also my actual temps of the soc actually decreased by 1c-2c on my passive heatsink(no fan)

**Comment by Ntemis** [comment]
I have found the issue for the sound cutting out
https://dpaste.org/EMXMw
Looks like the cpuclk rate for this soc cant be changed this high on mainline.
Unfortunately I have to settle to platform defaults on a new pr :(

**Pull request closed without merging**
