### PR TITLE
opengl-meson and u-boot changes

### PR DESCRIPTION
**Pull request by lrusak**
This creates a unified opengl-meson package instead of having opengl-meson6, opengl-meson8, and possibly opengl-mesongxbb in the future.

The u-boot patches get moved to the version specific folder as they are only applicable for that version of u-boot. Is this ok with you @vpeter4 ?

These a precursor commits to the Odroid_C2 support that I have. The rest is Odroid_C2 specific

### CODE REVIEW

**Comment by kszaq** [comment]
How about adding an something like OPENGL_VARIANT instead of relying on PROJECT to choose package version? This would make things easier for forkers - me included.

**Comment by vpeter4** [comment]
@lrusak: imx6 project is using version u-boot-imx6-408544d. Which means you need to copy those 2 patches to this folder too.
If I see correctly u-boot 2011.03-rc1 is used by RPi*?

**Comment by MilhouseVH** [comment]
> If I see correctly u-boot 2011.03-rc1 is used by RPi*?

The current u-boot package isn't built by RPi* so these changes shouldn't have any effect on RPi*.

**Comment by vpeter4** [comment]
So all references for u-boot 2011.03-rc1 should be just removed. Seems some old leftover.

**Comment by zalaare** [comment]
In the future I see linux and u-boot with a 20 case long statement.  I think PROJECT_DIR/PROJECT/packages is the perfect place for packages that could fit this potential problem.  Eventually (assuming all is right in the world), support will be mainlined (or patched in) and these can fall off with none-the-wiser.

**Comment by lrusak** [comment]
Updated with suggested comments. not sure if "OPENGLES_VARIANT" makes sense, maybe "MESON_VARIANT" is better?

I don't agree with project specific packages, this creates more stuff to maintain and duplicates work, however, this can be discussed at another time on slack.

**Comment by codesnake** [comment]
I think most appropriate variable name is MESON_FAMILY.

**Comment by lrusak** [comment]
thanks @codesnake I've updated it

**Comment by lrusak** [comment]
@kszaq is this ok with you?

**Comment by vpeter4** [comment]
@lrusak: don't forget to move u-boot patches to correct version specific folder (imx6-408544d).

**Comment by kszaq** [comment]
@lrusak Yes, thanks a lot for considering my request.

**Comment by lrusak** [comment]
updates, should be good to go

**Pull request merged**
