### PR TITLE
project/generic: use mtune=generic

### PR DESCRIPTION
**Pull request by antonlacon**
@MilhouseVH @5schatten 

This should be a "free" performance improvement for Generic. march=x86_64 compiles for what every x86-64 processor should have. mtune=generic adds instructions to suit 'most common' x86-64 processors at the time of the GCC major release.

I compiled enough of a Generic project to confirm the flags were in place, but don't have available hardware for benchmarking.

### CODE REVIEW

**Comment by CvH** [comment]
any idea how to benchmark it ? (hw available here)

**Comment by antonlacon** [comment]
I would look at using ffmpeg as I believe kodi uses its libraries extensively. You would want before/after numbers from something like:

`ffmpeg -benchmark -i input.flac -v:n -c:a aac -b:a 160k output.m4a`

Which will use ffmpeg to convert input.flac to output.m4a at 160kbps. When completed, it will give some benchmark numbers like utime for time spent encoding, and maxrss for max memory used to do it.

Openssl has a benchmark functionality as well. If you want to try that, let me know and I'll dig up my notes on doing so.

The only other location I think a user might notice would be in emulation, and I don't know how to benchmark those beyond user experience.

**Comment by 5schatten** [comment]
Afaik Dolphin can be used as a benchmarking "tool" too:

https://forums.dolphin-emu.org/Thread-unofficial-new-dolphin-5-0-cpu-benchmark-results-automatically-updated--45007

**Comment by mglae** [comment]
mtune=generic seems to be default.

`build.LibreELEC-Generic.x86_64-9.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc -fverbose-asm -S -o - t.c` results in:

```
	.file	"t.c"
# GNU C17 (GCC) version 8.2.0 (x86_64-libreelec-linux-gnu)
#	compiled by GNU C version 5.4.1 20160904, GMP version 6.1.2, MPFR version 3.1.5, MPC version 1.0.3, isl version none
# GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
# options passed:  t.c -mtune=generic -march=x86-64 -auxbase-strip t.s
# -fverbose-asm
# options enabled:  -faggressive-loop-optimizations
# -fasynchronous-unwind-tables -fauto-inc-dec -fchkp-check-incomplete-type
# -fchkp-check-read -fchkp-check-write -fchkp-instrument-calls
# -fchkp-narrow-bounds -fchkp-optimize -fchkp-store-bounds
# -fchkp-use-static-bounds -fchkp-use-static-const-bounds
# -fchkp-use-wrappers -fcommon -fdelete-null-pointer-checks
# -fdwarf2-cfi-asm -fearly-inlining -feliminate-unused-debug-types
# -ffp-int-builtin-inexact -ffunction-cse -fgcse-lm -fgnu-runtime
# -fgnu-unique -fident -finline-atomics -fira-hoist-pressure
# -fira-share-save-slots -fira-share-spill-slots -fivopts
# -fkeep-static-consts -fleading-underscore -flifetime-dse
# -flto-odr-type-merging -fmath-errno -fmerge-debug-strings -fpeephole
# -fplt -fprefetch-loop-arrays -freg-struct-return
# -fsched-critical-path-heuristic -fsched-dep-count-heuristic
# -fsched-group-heuristic -fsched-interblock -fsched-last-insn-heuristic
# -fsched-rank-heuristic -fsched-spec -fsched-spec-insn-heuristic
# -fsched-stalled-insns-dep -fschedule-fusion -fsemantic-interposition
# -fshow-column -fshrink-wrap-separate -fsigned-zeros
# -fsplit-ivs-in-unroller -fssa-backprop -fstdarg-opt
# -fstrict-volatile-bitfields -fsync-libcalls -ftrapping-math -ftree-cselim
# -ftree-forwprop -ftree-loop-if-convert -ftree-loop-im -ftree-loop-ivcanon
# -ftree-loop-optimize -ftree-parallelize-loops= -ftree-phiprop
# -ftree-reassoc -ftree-scev-cprop -funit-at-a-time -funwind-tables
# -fverbose-asm -fzero-initialized-in-bss -m128bit-long-double -m64 -m80387
# -malign-stringops -mavx256-split-unaligned-load
# -mavx256-split-unaligned-store -mfancy-math-387 -mfp-ret-in-387 -mfxsr
# -mglibc -mieee-fp -mlong-double-80 -mmmx -mno-sse4 -mpush-args -mred-zone
# -msse -msse2 -mstv -mtls-direct-seg-refs -mvzeroupper

	.text
	.globl	main
	.type	main, @function
main:
.LFB0:
	.cfi_startproc
	pushq	%rbp	#
	.cfi_def_cfa_offset 16
	.cfi_offset 6, -16
	movq	%rsp, %rbp	#,
	.cfi_def_cfa_register 6
# t.c:4:   return 1;
	movl	$1, %eax	#, _1
# t.c:5: }
	popq	%rbp	#
	.cfi_def_cfa 7, 8
	ret	
	.cfi_endproc
.LFE0:
	.size	main, .-main
	.ident	"GCC: (GNU) 8.2.0"
	.section	.note.GNU-stack,"",@progbits
```

**Comment by antonlacon** [comment]
Thanks for testing. This looks like a bust. I'll roll the cflag move into a buildsystem cleanup PR.

**Comment by CvH** [comment]
I used to benchmark

ffmpeg decoder benchmark
`ffmpeg -benchmark -i some.mkv -f null out.null`

openssl benchmark
`openssl speed md5 sha1 sha256 sha512 aes-256-cbc`

results are pretty clear that this pr had made it even slightly (~2%) slower for some reason

**Pull request closed without merging**
