### PR TITLE
linux: update to 6.6.16

### PR DESCRIPTION
**Pull request by heitbaum**
# 6.6.x mainline kernel update

- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.15
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.16

6.6.15 - 331 patches
6.6.16 - 326 patches

### errors / fixes / issues / regressions / todo
- todo
  - tba
- done
  - tba

### log 
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.6.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.6.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/log/
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.6
- https://linux-regtracking.leemhuis.info/regzbot/mainline/
- https://linux-regtracking.leemhuis.info/regzbot/stable/

### 6.6.16 Build tested on all of:

```
PROJECT=Allwinner ARCH=aarch64 DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H3 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=R40 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=aarch64 DEVICE=RK3328 s/build linux
PROJECT=Rockchip ARCH=aarch64 DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX6 s/build linux
PROJECT=NXP ARCH=aarch64 DEVICE=iMX8 s/build linux
PROJECT=Qualcomm ARCH=aarch64 DEVICE=Dragonboard s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
```

### 6.6.y Run tested on all of:
- Allwinner all - tested - TBA - jernejsk
- Allwinner H6 (Tanix TX6) - 6.6.2-rc1 - heitbaum
- Generic Generic (Intel ADL - NUC12) - 6.6.16 - heitbaum
- NXP iMX6 (Cubox-i4Pro) - TBA - heitbaum
- Rockchip RK3399pro (Rock Pi N10) - TBA - heitbaum
- RK all - tested - TBA - knaerzche
- Samsung Exynos (Hardkernel ODROID XU4) - TBA - heitbaum

### CODE REVIEW

**Comment by HiassofT** [comment]
Quick heads up: you'll likely run into this issue on Generic legacy:
https://forums.developer.nvidia.com/t/linux-6-7-3-545-29-06-550-40-07-error-modpost-gpl-incompatible-module-nvidia-ko-uses-gpl-only-symbol-rcu-read-lock/280908/25

Until updated nvidia drivers are available using the gentoo patch linked in the thread might do the job

**Comment by heitbaum** [comment]
> Quick heads up: you'll likely run into this issue on Generic legacy: https://forums.developer.nvidia.com/t/linux-6-7-3-545-29-06-550-40-07-error-modpost-gpl-incompatible-module-nvidia-ko-uses-gpl-only-symbol-rcu-read-lock/280908/25
> 
> Until updated nvidia drivers are available using the gentoo patch linked in the thread might do the job

6.6.16 had compiled cleanly for me with Generic-legacy. But I have now included the patch.

**Comment by HiassofT** [comment]
ah, it could be that https://github.com/torvalds/linux/commit/6335c0cdb2ea0ea02c999e04d34fd84f69fb27ff fixed the 6.6.15 nvidia issue. If nvidia built fine with 6.6.16 then drop the patch

**Comment by heitbaum** [comment]
> ah, it could be that [torvalds/linux@6335c0c](https://github.com/torvalds/linux/commit/6335c0cdb2ea0ea02c999e04d34fd84f69fb27ff) fixed the 6.6.15 nvidia issue. If nvidia built fine with 6.6.16 then drop the patch

👍 dropped.

**Review by CvH — APPROVED** [review]

**Pull request merged**
