### PR TITLE
update to ccache 4 and support building early package with local ccache

### PR DESCRIPTION
**Pull request by HiassofT**
This is #7194 with the original ccache 4 PR #6887 on top - with a few fixes and modifications (I tried to keep original attribution to @heitbaum's  work as much as possible), trying to tame the cmake monster by making use of local ccache on the build host.

I benchmarked RPi4 builds (`PROJECT=RPi DEVICE=RPi4 ARCH=arm make`) on my HP Z240 workstation (4C/8T 3.5GHz Xeon E3-1245 v5, 32GB RAM, 1TB Samsung 980 Pro SSD).

I built with current master branch (commit 732acb28808958122aeae3802b9b4d748fe6caa4)  -  `ccache 3` in the table , with this PR using local ccache 4.2 on the build host (`export LOCAL_CCACHE="/usr/bin/ccache"` in `.libreelec/options`) - `ccache 4` in the table  and with this PR, local ccache and additionally ccache compression disabled (`export LOCAL_CCACHE="/usr/bin/ccache"` and `export CCACHE_NOCOMPRESS=yes` in `.libreelec/options`) - `ccache 4 nocompress` in the table, 

I did 3 runs each: first with wiped ccaches and build dir (`cold`), then with wiped build dir but intact ccaches (`hot1`) and then another one with wiped build dir and intact ccaches (`hot2`).

I've timed each build with `time` so it also includes squashfs and tar image generation, the values in the table are the "real" time values. I've also collected the ccache statistics and added the cache sizes after the second hot run in the table.

Here are the results:

|     | ccache 3 | ccache 4 | ccache 4 nocompress |
|---| --: | --: | --: |
| cold |  76m57.050s | 79m31.660s | 79m45.522s |
| hot1 | 16m37.305s | 16m57.351s | 17m3.866s |
| hot2 | 16m17.609s | 16m55.515s | 16m56.922s |
| cache size | 4.0 GB |  1.62 GB | 4.68 GB |
| local cache size | n/a | 64.6 MB | 151.3 MB |

One interesting result is that ccache 4 compression (which is enabled by default) had almost no impact on build time - but resulted in (almost) 1/3rd cache size - so the default of using compression in ccache 4 makes sense as it saves space.

Compared to ccache 3  ccache 4 only needs about 40% of the space - which is rather nice.

Compared to ccache 3 both the cold and hot2 rebuild times increased by about 4 percent - a lot better than we had without local ccache (see comments in #6887 )

Actually not sure why the ccache 3 hot2 time was so much faster than the hot1 time - hot1 time increase was about 2 percent.

Overall I have to say I'm quite happy now. The re-build performance hit of about 30% which we saw in #6887 went down to 2-4% while we can reduce cache size to 40% which is a quite nice tradeoff.

### CODE REVIEW

**Comment by heitbaum** [comment]
I have run a full set of tests and all looks right. Tested with “no local ccache”, “3.7 local ccache - focal”, “4.7 local ccache - downloaded from ccache.dev”. Looks to be an up to 3 minute saving with “local ccache” and using ccache4. Times coming close to that of the ccache3.

Similar results here:
- `time make image`
- `sync; echo 3 > /proc/sys/vm/drop_caches` between each runs
- `i7-1260P with 32GB and Nvme KINGSTON SKC3000D2048G`

|     | ccache 3 | ccache 4 | ccache 4 w/3.7 local ccache | ccache 4 w/4.7 local ccache | 
|---| --: | --: | --: | --: |
| cold |  87m56.817s | 94m12.579s | | |
| hot1 | 12m45.594s | 15m54.691s | 13m58.041s | 13m9.113s |
| hot2 | 12m26.244s | 16m8.890s | 13m14.727s | |
| cache size | 5.58 GB |  2.30 GB | 2.30 GB | 2.30 GB |
| local cache size | n/a | n/a | 113.9 MB | 67.2 MB |

I’ll close my PR as this PR now includes mine. probably good to squash the 4.6.3, 4.7, assembly, 4.7.1, 4.7.2, 4.7.3, and 4.7.4 commits.

**Review by heitbaum — CHANGES_REQUESTED** [review]
Just the squash of the ccache version commits, and rebase against master. The I’m happy with the PR.

**Comment by HiassofT** [comment]
rebased and squashed ccache 4 update commits

**Review by heitbaum — APPROVED** [review]

**Comment by heitbaum** [comment]
> rebased and squashed ccache 4 update commits

Looks good.

**Pull request merged**
