### PR TITLE
eventlircd: Fix missing buttons with WP2 remote

### PR DESCRIPTION
**Pull request by Raybuntu**
I noticed that on WP2 some keys weren't working. For instance Chan-Up and Chan-Down.
aml_keypad was not handled with eventlircd.

Please test this.

### CODE REVIEW

**Comment by Raybuntu** [comment]
Is that better?

**Comment by Raybuntu** [comment]
Hmmmh. I've noticed problems with my keyboard attached. DELL Keyboard is being handled by eventlircd now. I'm suggesting not to merge.

**Comment by Raybuntu** [comment]
Fixed. Damned trailing spaces

**Comment by Raybuntu** [comment]
@codesnake: I've also remapped capslock to KEY_F11. KEY_CAPSLOCK has a special treatment in eventlircd. I can't remap it and it's not working for sms style input in kodi anyway. KEY_F11 can be at least changed by the use. Now every key is working.

**Comment by lrusak** [comment]
Thanks!!

**Pull request merged**
