### PR TITLE
retroplayer updates

### PR DESCRIPTION
**Pull request by CvH**
update and minor cleanups

not build tested yet

### CODE REVIEW

**Comment by InuSasha** [comment]
i think `PKG_SECTION`should not droped, because jenkins need it.
ping @islipfd19

**Comment by CvH** [comment]
`PKG_SECTION=""` not sure what you can gather from "empty" but asking don't hurt :)

**Comment by CvH** [comment]
successfully build
`PROJECT=Generic ARCH=x86_64 scripts/create_addon retroplayer` and
`PROJECT=RPi DEVICE=RPi2 ARCH=arm scripts/create_addon retroplayer`

`FAILED ADDONS: game.libretro.mame2000 game.libretro.mame2003 game.libretro.mame2010 game.libretro.mame2014`
so nothing new :)

**Comment by chewitt** [comment]
@CvH please revert the PKG_SECTION removals until that's been agreed in Slack, then this PR can be merged and things can get built. Thanks.

**Comment by 5schatten** [comment]
@CvH 
Are you able to compile the mame cores like this?

PROJECT=Generic ARCH=x86_64 scripts/build libretro-mame2003

I have mame2003 & 2014 included in my remix build and both work fine as far as I can tell.

https://github.com/5schatten/LibreELEC.tv/tree/libreelec-9.0-rr/packages/emulation/libretro-mame2003
https://github.com/5schatten/LibreELEC.tv/tree/libreelec-9.0-rr/packages/emulation/libretro-mame2010

**Comment by CvH** [comment]
just `game.libretro.mame2014` is failing, not sure why and didn't investigate yet

**Comment by 5schatten** [comment]
Maybe this patch helps?

https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.0-rr/packages/emulation/libretro-mame2014/patches/libretro-mame2014-0001_fix-cross-compile.patch

**Comment by CvH** [comment]
> Maybe this patch helps?

no, `libretro-mame2014` is building but not `game.libretro.mame2014` (with or without that patch)

> this source for ppsspp

tx will change

**Comment by CvH** [comment]
@5schatten updated and used parts from https://github.com/5schatten/LibreELEC.tv/blob/b0b525bcdf2f9ea499be96c8b375d78a0a1e660d/packages/5schatten/emulation-cores/ppsspp/package.mk TX !
changed it to x86_64 only for now as we can't use it anyway and arm is not compiling ootb (could be fixed later to not delay this pr)
Needed to add `+pic` to SDL2 and changed the `mkpkg_libretro-ppsspp` script to the "new" url additionally also included some cleanup that massively reduces the size of the package (W10 binaries ...).

**Comment by matejmosko** [comment]
After merging this in Milhouse's build 705, retroplayer still doesn't work. Libretro compatiblity addon complains about wrong version of kodi.binary.instance.game (1.0.36). The Libretro compatility is 1.0.36.106.

[This is my log](http://paste.kodi.tv/alojurasiy) (RPi3, Milhouse's build 705)

**Comment by CvH** [comment]
Pls be aware that the add-ons are not yet updated. I pushed the genericaddons to http://cvh.libreelec.tv/addons/9.0/retroplayer/ temporarily.

**Pull request merged**
