### PR TITLE
kodi: bump to 17.1-RC1

### PR DESCRIPTION
**Pull request by chewitt**
To facilitate testing as we move towards an 8.0.1 release

### CODE REVIEW

**Comment by chewitt** [comment]
PR updated to current Krypton HEAD to include https://github.com/xbmc/xbmc/pull/11767 and remove upstream-merged patches

**Comment by magicsepp** [comment]
bump to 17.1 rc2 is available

**Comment by chewitt** [comment]
@magicsepp Unless you also see a git tag this is just the version information being prepared for next version. RC2 is not available yet.

**Comment by wrxtasy** [comment]
@chewitt 

With this PR - request a bump to amlogic-3.14 linux package source to: eb7e852

This picks up HEVC, VP9 and GPU driver bug fixes.

**Comment by chewitt** [comment]
@wrxtasy that should be done separately .. please submit PR's to 8.0/master

**Pull request merged**
