### PR TITLE
Generic: switch to GBM and drop X11

### PR DESCRIPTION
**Pull request by smp79**
Build tested. Runtime tested on Intel Gemini Lake and AMD Athlon 200GE (Vega 3).

### CODE REVIEW

**Comment by zhangn1985** [comment]
a tip: when build SDL2 without X11, need enable VIDEO_OPENGLES, VIDEO_KMSDRM and cflags: EGL_NO_X11

**Comment by CvH** [comment]
@all do we want to remove x11 completely or do we introduce a Generic-legacy (x11)?

GBM removes support for chrome? (not too sure), Nvidia and Hyperion.

From my pov I would rather change it to a device based model where "new" and legacy can coexist with minimal changes.
Especially for Nvidia users there is basically no other solution, the free nvidia drivers are useless.

**Comment by smp79** [comment]
I propose to remove X11 for good and be done with it. Let's focus on GBM/DRM PRIME instead.

**Comment by SupervisedThinking** [comment]
- Well what's the point/benefit of removing X11 now? 
- Does K20 include a full featured browser? 
- Will Wayland/Westen still be fully functional after this PR?

IMHO this removal basically reduces every generic system to the feature set of any 35$ SBC `¯\_(ツ)_/¯`

**Comment by smp79** [comment]
> this removal basically reduces every generic system to the feature set of a 35$ SBC & kicks out Nvidia users

LE is not a full featured desktop OS. If for whatever reason a user wants Chrome on their HTPC - that user can use Ubuntu or even Windows. Same goes for Nvidia users. Nvidia's discrete cards are not exactly HTPC/ Linux-friendly devices. Good riddance, as far as I'm concerned.

**Comment by SupervisedThinking** [comment]
> LE is not a full featured desktop OS. 

Neither this is an argument nor does LE ship a full featured desktop

> If for whatever reason a user wants Chrome on their HTPC - that user can use Ubuntu or even Windows. 

Because of...?

> Same goes for Nvidia users. Nvidia's discrete cards are not exactly HTPC/ Linux-friendly devices. Good riddance, as far as I'm concerned.

Why?

> X11 should have been removed back in 2018 #3152
> Not sure what happened then.

Probably nothing because removing X11 support without any advantages does not make that much sense?

> I regularly post Generic GBM builds with working HDR on LE forum. No one ever complained about missing X11.

Yes because the users with need of HDR support use your builds, while others e.g. need for Nvidia or Chrome support don't.

In the end this will cut off all Nvidia users,  personally I don't see any point to buy a full featured generic system which has basically the same feature set as a RPi4 35$ board. Why would anyone do this 🤔  I mean IF I need to play some HDR stuff I use my 30$ TV stick anyway 😄 

But I got your point. Ditch several features & options on generic systems for HDR.

**Comment by SupervisedThinking** [comment]
> Chrome should now be fully on the new ozone backend which means it should work on wayland and gbm. I have not tested this though.
> 
> https://www.phoronix.com/scan.php?page=news_item&px=Chrome-Ozone-X11-Future

No clue about the GBM capabilities but in this article they only mention the replacement of the legacy X11 code by Ozone? Anyway having a proper Wayland platform would be great too.

**Comment by SupervisedThinking** [comment]
> @ALL do we want to remove x11 completely or do we introduce a Generic-legacy (x11)?
> 
> GBM removes support for chrome? (not too sure), Nvidia and Hyperion.
> 
> From my pov I would rather change it to a device based model where "new" and legacy can coexist with minimal changes.
> Especially for Nvidia users there is basically no other solution, the free nvidia drivers, that support gbm, are useless.

I would totally support that too - basically make sure that still both images with displayserver & without build fine and EVERYONE is still happy.

**Comment by smp79** [comment]
> I would totally support that too - basically make sure that still both images with displayserver & without build fine and EVERYONE is still happy.

That idea was rejected last year. See https://github.com/LibreELEC/LibreELEC.tv/pull/4518
However, I think @lrusak was right to reject it.  No much point keeping both X11 ang GBM. Extra maintenance burden just to keep a few nvidia users happy.

IMO GBM is the only way forward and X11 should go. Now is a good time to get rid of it.

**Comment by heitbaum** [comment]
My 2c - change the default - aka - https://github.com/LibreELEC/LibreELEC.tv/pull/4518#issuecomment-752206076 ASAP and raise the draft PR to drop all remnants of X11, no different from the kernel approach of deprecated. This will give a full cycle of ironing out things. 

Note: doesn’t match my usual philosophy when working on IT jobs where I have used the catch phrase “gut the place - when talking about old infrastructure” more than once.

**Comment by dvidebaek** [comment]
Would love to see HDR working on My Generic Intel NUC. Hope this gets merged!

**Comment by vpeter4** [comment]
Before removing packages it should be checked which one is used by other addons. For example libXinerama is used for Java for Blu-ray menus. Or this will be removed too?

**Comment by SupervisedThinking** [comment]
I guess all add-ons which rely on X11/OpenGL(GLX) will be affected in one way or another.

@lrusak @chewitt any stats about the current Nvidia user base? IIRC it wasn't too big but still around?

**Comment by vpeter4** [comment]
> I guess all add-ons which rely on X11/OpenGL(GLX) will be affected in one way or another.

Sure. But mentioned addon doesn't even need X11 to be used.

**Comment by chewitt** [comment]
I'd like to see both Generic (GBM) and Generic_Legacy (Xorg) coexisting for a while. Forum feedback on @smp79 images seems to be positive but from ~10 years experience with community builds in the project I'm also confident the active user numbers are small and these days most staff are running ARM SoC devices not x86 kit so we have less personal testing experience. In short, I'd like to see larger scale testing with GBM on a wider array of user hardware before we throw Xorg under the bus, but I'd hope we reach that confidence point sooner-than-later and long before LE11 beta releases. NB: It would be good if @smp79 would add `BUILDER_NAME="smp79"` to .libreelec/options in his build folder so active installs of his images become identifiable in stats.

Stats show ~2,500 active Generic installs with nVidia GPUs, which is a decline of ~1,000 in the last 12 months, and ~75% of them are using the legacy driver (so older GPUs/cards) and age/time will continue to shrink the number. Stats for AMD cards are not much larger while Intel numbers are orders of magnitude greater. I don't see killing nVidia off as a concern because the user numbers are now a fraction of whatt they were 3-5 years ago and we've been up-front and vocal about the death of support for some time now, i.e. it shouldn't be a surprise for anyone.

**Comment by smp79** [comment]
Ok, looks like X11 just won't die, so I'm closing this.

**Comment by SupervisedThinking** [comment]
@smp79 could you rebase your device approach? I guess it's highly appreciated.

**Comment by dvidebaek** [comment]
Sad how this pull request was closed. Development of great features is hold back by People’s >=10 year Old hardware or hardware manufactors that refuse to make good drivers for Linux (NVIDIA). Why support NVIDIA when they Don’t support os??? The same happend with kodi. They kept Windows 7 and 8 support because People started whining and refused to upgrade to Win10. That delayed HDR support also, because of legacy code They have to maintain. Sorry for the rant, had to get it of my chest.. it doesnt Sound like it but you are all hero! Love Libreelec on my NUC and RPI4

**Comment by CvH** [comment]
its not about IF we are using gbm or x11, its just about the handling
LE11 is getting gbm

**Pull request closed without merging**
