### PR TITLE
Fix for RPi Compilation Problem

### PR DESCRIPTION
**Pull request by jmooremcc**
Updates packages/sysutils/e2fsprogs/package.mk and packages/x11/font/liberation-fonts-ttf/package.mk which prevented successful RPi compilation.

### CODE REVIEW

**Comment by chewitt** [comment]
@jmooremcc can you explain what the compilation error is please? - it's not something I/we have seen an problem with when building releases. We also prefer to use upstream URLs instead of our mirror. The upstream location appears to be here now:

https://releases.pagure.org/liberation-fonts/liberation-fonts-ttf-2.00.1.tar.gz.

The same changes also need submitting in a PR to master branch to keep things in-sync. 

Thanks :)

**Comment by vpeter4** [comment]
@chewitt: The problem with e2fsprogs is because of [this](https://forum.libreelec.tv/thread-2586-post-27679.html#pid27679). But I didn't bump package in 8.0 branch to not introduce some extra problems before final release.

**Comment by vpeter4** [comment]
@chewitt: The problem with e2fsprogs is because of [this](https://forum.libreelec.tv/thread-2586-post-27679.html#pid27679). But I didn't bump package in 8.0 branch to not introduce some extra problems before final release.
It would also be better if we would build one package (forgot which one) also for host and not rely on binary installed on host when creating image.

**Comment by ozolli** [comment]
I'm using the bumped package since January on the 8.0 branch and every project compiles fine with it. I have not seen any problems on Generic, RPi or Odroid.

**Comment by chewitt** [comment]
@jmooremcc please rebase with the change to the upstream font repo (our mirror is the fallback, it should not be primary when one is available) then this can be merged. Thanks.

**Comment by chewitt** [comment]
I guess your branch is out of date for fonts as https://github.com/LibreELEC/LibreELEC.tv/commit/4986f3606b4be481aac40ae365306df6c42e6277 already merged the liberation-font change ~2 months ago.

**Comment by chewitt** [comment]
superseded by #1548

**Pull request closed without merging**
