### PR TITLE
VDR with 4k/HEVC support

### PR DESCRIPTION
**Pull request by piotrasd**
added patch for VDR and updated VNSI
tested with DVB-S2 S19.2E and S13.0E 4k channels

### CODE REVIEW

**Comment by piotrasd** [comment]
Hi
im also successful compiled XVDR for VDR and Kodi addon maybe good will add to LE7.x
(i know support is droped but still working and for me even better than VNSI also on OdroidC2 and other ARM)

**Comment by CvH** [comment]
@piotrasd tx (I test this later) - could you describe "better"?

**Comment by piotrasd** [comment]
hi @CvH sorry om not using to often git so me discription skill are not good :( and i dont know now how to change that, i will try next time better describe

**Comment by CvH** [comment]
Sorry looks like you got me wrong ;) 
You said xvdr works better. I also see some request for xvdr but nobody could explain what is better or what vnsi didn't do that well.

**Comment by chewitt** [comment]
@piotrasd some changes please:

a) Add "- add sat-ip devices option" to changelog.txt; this was missed in a merged PR a few mins ago but we can add it to your PR to keep things tidy.

b) Squash to a single commit and rename to "vdr: updates and 4k/hevc support" (rename the commit message not the PR title).

**Comment by piotrasd** [comment]
ok about XVDR, less bufforing or shorter when you switching channels, faster zap (im suppose because each channels info about stream are save in cache, so when try next open this same channels you faster get picture on screen and like be less CPU consuption VDR on K1 Plus (AML S905) VDR taking 5% of CPU or less. Best if you just test example 30min XVDR and VNSI you will get your own feeling/comparsion.

**Comment by piotrasd** [comment]
@chewitt sorry i had some issue with "bonaire_ce.bin" and becuase this file i cannot do changes :( i will try over weekend little improve my git support

**Comment by chewitt** [comment]
Do `git rebase -i HEAD~5` and then change the first commit from `pick` to `reword` and the next four from `pick` to `squash` then save and it will ask you what the new commit message should be. Enter the new message, save again, and it will squash the five commits to be a single commit. Don't be shy about asking Q's - everyone learns git the hard way :)

**Comment by CvH** [comment]
@piotrasd rdy ? I would merge this asap, @chewitt pls don't build this yet I do a pr on top of this

**Comment by piotrasd** [comment]
that depends, i can try add XVDR plugin also ..

**Comment by CvH** [comment]
@piotrasd is xvdr from @nkvoronov ? if so it will (most likely) not work without rewriting the patches

**Comment by piotrasd** [comment]
i get from vitmod - but is needed 1 patch more for aarch64
https://github.com/vitmod/OpenELEC.tv/tree/master/packages/addons/depends/multimedia/vdr-plugin-xvdr

for all platform working (excluding aarch64)
we need fix that file
https://github.com/pipelka/xbmc-addon-xvdr/blob/master/addons/library.xbmc.addon/libXBMC_addon.h

becuase is not defined ADDON_HELPER_ARCH for aarch64
so when you compile without changes addon will call lib
Unable to load /usr/lib/kodi/addons/library.xbmc.addon/libXBMC_addon-i486-linux.so: cannot open shared object file: No such file or directory

and you will error like:
14:21:29 T:546937237728   ERROR: ADDON: Dll VDR XVDR Client - Client returned bad status (4) from Create and is not usable
14:21:29 T:546937237728 WARNING: UpdateAndInitialiseClients - failed to create add-on VDR XVDR Client, status = 4

**Comment by CvH** [comment]
@piotrasd  till we know how to fix that i merged the other changes (you should never use you master branch to pr something - better create an new branch and remove it after your pr gets merged)

**Comment by piotrasd** [comment]
@CvH @chewitt Thanks guys for helps all tips :) next PR will better :) is avaiable patch for Intel HDMI audio BYT/CHT https://github.com/piotrasd/LibreELEC.tv/commit/30c074d7c307716ef5d0844185808cfe35df273b

**Comment by piotrasd** [comment]
https://patch-diff.githubusercontent.com/raw/pipelka/xbmc-addon-xvdr/pull/169.patch fix for XVDR aarch64

**Pull request merged**
