### PR TITLE
fix crossbuilding heimdal by adding dependency to host-ncurses

### PR DESCRIPTION
**Pull request by lucianm**
Hello,

although heimdal-7.5.0 is configured `--without-libedit`, the configuration phase still runs the configuration for libedit and is unable to find libcurses or libncurses, unless adding a dependency to host-ncurses as in this pull request. This happened while building an image for Wetek Play with the command `PROJECT=WeTek_Play ARCH=arm make image` and was otherwise the only error encountered.

Greetings,
Lucian

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Just out of interest what is your build host (as I've not had this issue with Ubuntu 16.04/17.10).

Also, has this been reported upstream (to Heimdal) as they're pretty active right now dealing with a bunch of Samba changes... this sounds like an error/bug in the Heimdal configure and fixing that might be a better long-term fix.

**Comment by lucianm** [comment]
Well, I kind of expected such a question, since it's indeed a reportedly "unsupported" build host. I built on Sabayon (which is as its foundation it is built on, Gentoo, a rolling release distro) with current up to date packages which I had already installed in Virtualbox.

I didn't report upstream yet, I might have a look at their bug tracker if there something related exists already. If I'll report I'll link to this pull request. Anyway, I'm a bit surprised this happened again, as it was observed also some 3 years ago [here where I found the hint](http://lists.busybox.net/pipermail/buildroot/2015-July/132015.html) to this fix.

**Comment by CvH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/pull/2965 is also an Gentoo fix, we had other Gentoo fixes in the past too so keep going :)

**Comment by MilhouseVH** [comment]
Do we want to add Sabayon support to `scripts/checkdeps` ([here](https://github.com/LibreELEC/LibreELEC.tv/blob/master/scripts/checkdeps#L83) and [here](https://github.com/LibreELEC/LibreELEC.tv/blob/master/scripts/checkdeps#L143), `gentoo` -> `gentoo|sabayon`)?

I'm wondering if that would have avoided (masked) this issue as `ncurses` would then be found on the build host (which is presumably why this doesn't fail for other distros, such as Ubuntu).

**Comment by lucianm** [comment]
@MilhouseVH yeah, I think that could work. In line 83, just adding "|sabayon" to the case label should do. In line 143, a new case of its own dedicated to the sabayon package manager would be necesary, the command should be "equo install --ask" instead of gentoo's invocation of emerge.

**Comment by MilhouseVH** [comment]
Would you mind PR'ing those Sabayon changes? No way to test here, so I'd only be doing it blind.

**Comment by MilhouseVH** [comment]
I'll merge this, but maybe it can be reverted once upstream fixes https://github.com/heimdal/heimdal/issues/416. Thanks @lucianm.

**Comment by MilhouseVH** [comment]
BTW the reason I merged this is because it means fewer issues with any distros not supported by `scripts/checkdeps` (although the correct solution would be to fix `checkdeps`), but mainly because I'd rather we build `heimdal` with the $TOOLCHAIN `ncurses` headers rather than rely on whatever random version is installed on the build host. Plus, any rebuild of `heimdal` would have automatically used the $TOOLCHAIN `ncurses` headers, so this change should ensure a more consistent result when clean building and then rebuilding the `heimdal` package.

**Pull request merged**
