### PR TITLE
eventlircd: switch to LibreELEC repo

### PR DESCRIPTION
**Pull request by MilhouseVH**
Should be straightforward.

Updates with two new commits:

~https://github.com/LibreELEC/eventlircd/commit/fb514898cd2e6e324c2deb8a4cdd95daa8c6c9eb (add 'irw' command from lirc-0.9.0)~
~https://github.com/LibreELEC/eventlircd/commit/690ae62a53818ff7089bad276dad05c21ed087fb (cleanup)~

### CODE REVIEW

**Comment by HiassofT** [comment]
We don't want the irw commit, this was added because OE no longer ships with lirc. we ship with lirc, so have irw from the lirc package.

**Comment by MilhouseVH** [comment]
@chewitt can you drop the irw commit from the eventlircd repo, and then I'll update this PR.

**Comment by MilhouseVH** [comment]
Updated - irw commit now dropped.

**Comment by MilhouseVH** [comment]
Updated again, dropping the cleanup commit - this now just switches repository url.

**Pull request merged**
