### PR TITLE
kernel-firmware: use project specific firmwares and cleanup

### PR DESCRIPTION
**Pull request by MilhouseVH**
As per discussion on Slack, this change drops unnecessary firmwares from non-RPi projects.

As this PR stands, RPi, RPi2 and Generic will continue to install the same firmware as before, but all other projects will not now install any kernel firmware.

Any projects requiring kernel firmware will need to specify their own `packages/kernel-firmware/firmwares/any.dat`.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
After discussion on Slack this is updated.

If a project/device specific `kernel-firmware.dat` file if available it will be used as the sole source of firmwares to be installed, otherwise the global `any.dat` and `<arch>.dat` files will be used.

Amlogic, Wetek_Core and Wetek_Play projects are now configured with an empty `kernel-firmware.dat` and will not install any firmware files. That means no USB firmware files. No WiFi firmwares. Nothing.

All other projects (RPi, Rockchip, Generic etc.) will continue to install USB and WiFi firmwares based on `any.dat` and `<arch>.dat`.

**Comment by kszaq** [comment]
> Amlogic, Wetek_Core and Wetek_Play projects are now configured with an empty kernel-firmware.dat and will not install any firmware files. That means no USB firmware files. No WiFi firmwares. Nothing.

This is a bad idea - why remove a possibility to use a USB WiFi dongle with Odroid-C2 or any other AML device?

**Comment by MilhouseVH** [comment]
> This is a bad idea 

Yeah, I don't disagree, however the prevailing logic is that *some* projects don't need all the firmwares so with this change it will now be up to individual projects to specify what firmwares they do require (as I'm not able to divine that for them - I've no idea what firmware Amlogic requires).

Other projects that are happy to ship with the smorgasbord of firmwares that we ship with today don't need to specify anything and can continue using the default global config (`any.dat`/`<arch>.dat`).

So as things stand it's up to Amlogic/WeTek maintainers to chip in with the list of firmwares they do want to ship with, or if they want to continue with all of the firmwares there's probably no need for this change at all.

**Comment by MilhouseVH** [comment]
I would say this probably isn't _entirely_ a bad idea, as allowing projects or devices to specify their own firmwares may be useful in future, so that's a good thing. :)

However I am being intentionally provocative in configuring empty `kernel-firmware.dat` for Amlogic and WeTek as I don't know what firmwares these projects need but I've been told they don't need any, so if that isn't actually the case then I'll need guidance on what firmwares are needed. And if all firmwares are required then I can just drop the project-specific config file(s).

I must admit I'd have thought all platforms would need everything where USB is concerned, as any device with a USB port is likely to want to include the firmwares for typical USB devices.

**Comment by codesnake** [comment]
Yes, it would be good idea to include firmware for typical USB devices for AML/WeTek. I think many users of those boxes/boards use devices like WiFi or TV/DVB dongles.

**Comment by MilhouseVH** [comment]
@codesnake Thanks, I have dropped the `kernel-firmware.dat` project config files for WeTek_Core and WeTek_Play - these projects are now back to the complete set of firmware files, as before this PR.

This still leaves Amlogic without firmwares, so if the same change is required please decide amongst yourselves and let me know.

**Comment by chewitt** [comment]
The point of the change is simply to allow devices that already have decent onboard wireless and bt to cherry-pick the explicit firmwares they require without bloating up with additional stuff they don't need. It has never been my intention to strip Amlogic of firmware; so don't add an empty `kernel-firmware.dat` to do that.

**Comment by kszaq** [comment]
@MilhouseVH I think the best way to go would be to have Amlogic builds include the same set of firmware RPi builds do, except for the RPi-specific SDIO firmware. I think users expect to have the same set of firmware for all SBCs, no matter if it's RPi, C2 or KVIM.

**Comment by MilhouseVH** [comment]
Dropped Amlogic config, restored removal of RPi sdio firmwares.

All firmwares that are currently installed will continue to be installed. This PR now just adds some flexibility allowing projects or devices to install alternative firmwares, or remove any firmwares that are not required.

**Comment by MilhouseVH** [comment]
Merge me?

**Pull request merged**
