### PR TITLE
LibreELEC-settings: update to e755969

### PR DESCRIPTION
**Pull request by CvH**
wlan/bt should work now

### CODE REVIEW

**Comment by CvH** [comment]
doesn't start anymore :)
```
ERROR <general>: ExecuteAsync - Not executing non-existing script /usr/share/kodi/addons/service.libreelec.settings/service.py
ERROR <general>: CServiceAddonManager: service.libreelec.settings failed to start
```

**Comment by chewitt** [comment]
from Slack: default.py is now compiled, so Kodi should call default.pyc or default.py should not be compiled

**Comment by mglae** [comment]
default.py and service.py should not be compiled.

**Comment by antonlacon** [comment]
Can cherry-pick https://github.com/antonlacon/LibreELEC.tv/commit/6ab0d8d7d3cc4279b0b70bdbce8643ca1188d698.patch

**Comment by chewitt** [comment]
I'm not sure we need it to be that complex. Just skip the root folder:

```
diff --git a/packages/mediacenter/LibreELEC-settings/package.mk b/packages/mediacenter/LibreELEC-settings/package.mk
index 31e73236f2..e03e33607b 100644
--- a/packages/mediacenter/LibreELEC-settings/package.mk
+++ b/packages/mediacenter/LibreELEC-settings/package.mk
@@ -28,7 +28,7 @@ post_makeinstall_target() {
       -i $INSTALL/usr/lib/libreelec/backup-restore
 
   ADDON_INSTALL_DIR=${INSTALL}/usr/share/kodi/addons/service.libreelec.settings
-  python_compile ${ADDON_INSTALL_DIR}
+  python_compile ${ADDON_INSTALL_DIR}/resources/
 }
 
 post_install() {
```

**Review by chewitt — APPROVED** [review]

**Pull request merged**
