### PR TITLE
Update Steam controller support in mainline kernels

### PR DESCRIPTION
**Pull request by lrusak**
Removes the old python based steam controller add-on (and unused dependencies).

add the steamcontroller driver [1] to Allwinner and RPi (the other projects have it already).

 - [1] https://lwn.net/Articles/747174/

### CODE REVIEW

**Comment by jernejsk** [comment]
I'm fine with AW changes. Actually, a lot more HID devices need to be enabled, but I'll take care of that at 5.2 kernel bump.

**Comment by MilhouseVH** [comment]
LGTM.

Only question I have is that Generic has `CONFIG_HID_STEAM=m` while all others have `CONFIG_HID_STEAM=y`. Is there any advantage building a controller into the kernel rather than loading as a module? I feel we should be consistent across all projects, either all `y` or all `m`.

**Comment by HiassofT** [comment]
I'd vote for `CONFIG_HID_STEAM=m` - non-essential stuff like game controllers doesn't need to be built into the kernel (and it's also easier to blacklist the module or replace it with a different/out-of-tree version if needed/wanted)

**Comment by lrusak** [comment]
updated

**Comment by MilhouseVH** [comment]
Thanks both!

**Comment by HiassofT** [comment]
thanks!

**Pull request merged**
