### PR TITLE
initramfs: enable DNS if network is up

### PR DESCRIPTION
**Pull request by chrisnovakovic**
I ran into a problem while trying to network-boot LibreELEC: by specifying a hostname for the NFS server in the `boot` or `disk` kernel parameters, the init script fails with a nondescript error message. This is because, while my DHCP server is pushing a DNS server address (and the kernel is reporting it in `/proc/net/pnp`), the address is not being written to `/etc/resolv.conf` and the copy of glibc in the initramfs has no DNS resolver anyway.

This PR adds just enough of NSS to allow glibc to perform DNS resolutions in the initramfs, and writes any DNS servers known to the kernel to `/etc/resolv.conf` so they can be used by the glibc resolver.

### CODE REVIEW

**Comment by chrisnovakovic** [comment]
As mentioned in the previous PR, this has been tested on an RPi3 using the `RPi2` build.

**Comment by MilhouseVH** [comment]
Tested also on NUC, and works fine. Thanks!

**Comment by MilhouseVH** [comment]
@chewitt, worth a backport?

**Comment by chewitt** [comment]
I've cherry-picked into my latest 'stuff' PR for 8.2

**Pull request merged**
