### PR TITLE
script.moonlight: initial add-on

### PR DESCRIPTION
**Pull request by lrusak**
Thanks for showing me this @dead

This requires the changes I have outlined in https://github.com/dead/moonlight-openelec-rpi2/pull/21

This will be able to compile for any of the arm projects.

### CODE REVIEW

**Comment by lrusak** [comment]
updated for building on WeTek_* and imx6

at @vpeter4 what graphics packages do we build for? `imx-gpu-viv` ?

**Comment by vpeter4** [comment]
@lrusak: depend on kernel version (imx-gpu-viv or gpu-viv-bin-mx6q)
https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/imx6/options#L104

**Comment by chewitt** [comment]
@lrusak this still needs the addon icon I sent you.. then we can merge and build

**Comment by lrusak** [comment]
@chewitt updated

my only issue with this add-on is that it builds like the binary-addons and uses the shipped addon.xml instead of one we make/provide. This isn't really a problem other than it uses the stock add-on version for this which is [1.0.11](https://github.com/dead/moonlight-openelec-rpi2/blob/master/script.moonlight/addon.xml#L2)

maybe I should make this use our versioning scheme as it would be easier to keep track of?

**Comment by chewitt** [comment]
I'm easy, but if it's easier to track under our versioning .. do that.

**Comment by lrusak** [comment]
I'm happy with this now. It uses our versioning instead (easier to keep track of)

it builds for all arm and aarch64 platforms. 

Have a quick look over and if it's all good then merge and I will backport.

**Comment by da-anda** [comment]
I was just wondering if Opus couldn't be used via ffmpeg instead of a separate lib.

**Pull request merged**
