### PR TITLE
u-boot and u-boot-tools: update to 2022.07

### PR DESCRIPTION
**Pull request by heitbaum**
[ANN] U-Boot v2022.07 released
- https://www.mail-archive.com/u-boot@lists.denx.de/msg444768.html

Update u-boot (for all _**except**_ Rockchip)

- u-boot-tools: update to 2022.07
- u-boot: update to 2022.07
  - remove upstreamed Allwinner patches
  - rebase Allwinner patch
  - rebase NXP iMX8 patch
  - relocated some of the H3 patches

### Issues
- error with h5 and patch [0007-sunxi-psci-Add-support-for-H3-CPU-0-hotplug.patch](https://github.com/heitbaum/LibreELEC.tv/blob/u-boot/projects/Allwinner/patches/u-boot/0007-sunxi-psci-Add-support-for-H3-CPU-0-hotplug.patch)
  - moved these patches to the H3 folder

### Build tested - 5.18.10 + u-boot 2022.07
```
PROJECT=Allwinner ARCH=arm DEVICE=A64 make image
PROJECT=Allwinner ARCH=arm DEVICE=H3 make image
PROJECT=Allwinner ARCH=arm DEVICE=H5 make image
PROJECT=Allwinner ARCH=arm DEVICE=H6 make image
PROJECT=Amlogic ARCH=arm DEVICE=AMLGX make image
PROJECT=NXP ARCH=arm DEVICE=iMX6 make image
PROJECT=NXP ARCH=arm DEVICE=iMX8 make image
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard make image
PROJECT=Samsung ARCH=arm DEVICE=Exynos make image
```

### Run testing - 5.18.y + u-boot 2022.07
- Allwinner all - tested - TBA - jernejsk
- Allwinner H6 (Tanix TX6) - 5.18.11-rc1 + u-boot 2022.07 + atf 2.7 + kodi nexus 20a2 - heitbaum
- Amlogic all - tested - TBA - chewitt
- NXP iMX6 (Cubox-i4Pro) - TBA  - heitbaum
- Samsung Exynos (Hardkernel ODROID XU4) - TBA - heitbaum (video issue)

### Images built @ Jul 11-12
```
$ ls -1 target/*.img.gz
target/LibreELEC-A64.arm-11.0-devel-20220712050737-893a44f-orangepi-win.img.gz
target/LibreELEC-A64.arm-11.0-devel-20220712050737-893a44f-pine64.img.gz
target/LibreELEC-A64.arm-11.0-devel-20220712050737-893a44f-pine64-lts.img.gz
target/LibreELEC-A64.arm-11.0-devel-20220712050737-893a44f-pine64-plus.img.gz
target/LibreELEC-Dragonboard.arm-11.0-devel-20220712004812-893a44f-410c.img.gz
target/LibreELEC-Exynos.arm-11.0-devel-20220712011240-893a44f-odroid-xu4.img.gz
target/LibreELEC-Generic-legacy.x86_64-11.0-devel-20220712021421-893a44f.img.gz
target/LibreELEC-Generic.x86_64-11.0-devel-20220712011659-893a44f.img.gz
target/LibreELEC-H3.arm-11.0-devel-20220712052522-893a44f-bananapi-m2p.img.gz
target/LibreELEC-H3.arm-11.0-devel-20220712052522-893a44f-beelink-x2.img.gz
target/LibreELEC-H3.arm-11.0-devel-20220712052522-893a44f-libretech-h3.img.gz
target/LibreELEC-H3.arm-11.0-devel-20220712052522-893a44f-nanopi-m1.img.gz
target/LibreELEC-H3.arm-11.0-devel-20220712052522-893a44f-orangepi-2.img.gz
target/LibreELEC-H3.arm-11.0-devel-20220712052522-893a44f-orangepi-pc.img.gz
target/LibreELEC-H3.arm-11.0-devel-20220712052522-893a44f-orangepi-pc-plus.img.gz
target/LibreELEC-H3.arm-11.0-devel-20220712052522-893a44f-orangepi-plus2e.img.gz
target/LibreELEC-H3.arm-11.0-devel-20220712052522-893a44f-orangepi-plus.img.gz
target/LibreELEC-H6.aarch64-11.0-devel-20220711224209-893a44f-beelink-gs1.img.gz
target/LibreELEC-H6.aarch64-11.0-devel-20220711224209-893a44f-orangepi-3.img.gz
target/LibreELEC-H6.aarch64-11.0-devel-20220711224209-893a44f-orangepi-lite2.img.gz
target/LibreELEC-H6.aarch64-11.0-devel-20220711224209-893a44f-orangepi-one-plus.img.gz
target/LibreELEC-H6.aarch64-11.0-devel-20220711224209-893a44f-pine-h64.img.gz
target/LibreELEC-H6.aarch64-11.0-devel-20220711224209-893a44f-pine-h64-model-b.img.gz
target/LibreELEC-H6.aarch64-11.0-devel-20220711224209-893a44f-tanix-tx6.img.gz
target/LibreELEC-H6.arm-11.0-devel-20220711222822-893a44f-beelink-gs1.img.gz
target/LibreELEC-H6.arm-11.0-devel-20220711222822-893a44f-orangepi-3.img.gz
target/LibreELEC-H6.arm-11.0-devel-20220711222822-893a44f-orangepi-lite2.img.gz
target/LibreELEC-H6.arm-11.0-devel-20220711222822-893a44f-orangepi-one-plus.img.gz
target/LibreELEC-H6.arm-11.0-devel-20220711222822-893a44f-pine-h64.img.gz
target/LibreELEC-H6.arm-11.0-devel-20220711222822-893a44f-pine-h64-model-b.img.gz
target/LibreELEC-H6.arm-11.0-devel-20220711222822-893a44f-tanix-tx6.img.gz
target/LibreELEC-iMX6.arm-11.0-devel-20220712000857-893a44f-cubox.img.gz
target/LibreELEC-iMX6.arm-11.0-devel-20220712000857-893a44f-udoo.img.gz
target/LibreELEC-iMX6.arm-11.0-devel-20220712000857-893a44f-wandboard.img.gz
target/LibreELEC-iMX8.arm-11.0-devel-20220712002934-893a44f-mq-evk.img.gz
target/LibreELEC-iMX8.arm-11.0-devel-20220712002934-893a44f-pico-mq.img.gz
target/LibreELEC-RK3288.arm-11.0-devel-20220711230114-893a44f-miqi.img.gz
target/LibreELEC-RK3288.arm-11.0-devel-20220711230114-893a44f-tinker.img.gz
target/LibreELEC-RK3328.arm-11.0-devel-20220711231832-893a44f-a1.img.gz
target/LibreELEC-RK3328.arm-11.0-devel-20220711231832-893a44f-roc-cc.img.gz
target/LibreELEC-RK3328.arm-11.0-devel-20220711231832-893a44f-rock64.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-hugsun-x99.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-khadas-edge.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-nanopc-t4.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-nanopi-m4.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-orangepi.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-rock960.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-rock-pi-4.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-rock-pi-4-plus.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-rock-pi-n10.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-rockpro64.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-roc-pc.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-roc-pc-plus.img.gz
target/LibreELEC-RK3399.arm-11.0-devel-20220711234230-893a44f-sapphire.img.gz

target/LibreELEC-H5.arm-11.0-devel-20220712063834-893a44f-orangepi-pc2.img.gz
target/LibreELEC-H5.arm-11.0-devel-20220712063834-893a44f-tritium-h5.img.gz
target/LibreELEC-H5.arm-11.0-devel-20220712064915-ad6efd1-orangepi-pc2.img.gz
target/LibreELEC-H5.arm-11.0-devel-20220712064915-ad6efd1-tritium-h5.img.gz
```

```
=== tested on ===
H6.arm-devel-20220712065331-ad6efd1
Linux tx6 5.18.11-rc1 #1 SMP PREEMPT Mon Jul 11 14:09:07 UTC 2022 aarch64 GNU/Linux
Starting Kodi (20.0-ALPHA2 (19.90.705) Git:20.0a2-Nexus). Platform: Linux ARM 32-bit
Using Release Kodi x32
Kodi compiled 2022-07-11 by GCC 11.3.0 for Linux ARM 32-bit version 5.18.11 (332299)
Running on LibreELEC (heitbaum): devel-20220712065331-ad6efd1 11.0, kernel: Linux ARM 64-bit version 5.18.11-rc1
FFmpeg version/source: 4.4-Kodi
4 CPU cores available
ARM Features: Neon enabled
RetroPlayer[PROCESS]: Registering process control for GBM
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_VERSION = OpenGL ES 2.0 Mesa 22.1.3
```

### CODE REVIEW

**Comment by heitbaum** [comment]
@jernejsk - with the changes in 2022.07 (https://github.com/u-boot/u-boot/commit/0da35fa8d67415c7d595f6a74952905decc2a911) and rebase of the hot plug patch (so that it applies) https://github.com/LibreELEC/LibreELEC.tv/pull/6630/commits/e6ada4e774845bf45c0e03ef02d01bc5690e8e20 I am unsure what is required to fix this patch?

```
In file included from include/config.h:4,
                 from include/common.h:16,
                 from board/sunxi/board.c:13:
board/sunxi/board.c: In function 'board_late_init':
include/configs/sun8i.h:18:42: error: 'CONFIG_ARMV7_SECURE_BASE' undeclared (first use in this function)
   18 | #define SUNXI_RESUME_BASE               (CONFIG_ARMV7_SECURE_BASE + \
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~
include/configs/sun8i.h:22:42: note: in expansion of macro 'SUNXI_RESUME_BASE'
   22 | #define SUNXI_SCP_BASE                  (SUNXI_RESUME_BASE + SUNXI_RESUME_SIZE)
      |                                          ^~~~~~~~~~~~~~~~~
board/sunxi/board.c:865:28: note: in expansion of macro 'SUNXI_SCP_BASE'
  865 |         if (!rproc_load(0, SUNXI_SCP_BASE, SUNXI_SCP_MAX_SIZE)) {
      |                            ^~~~~~~~~~~~~~
include/configs/sun8i.h:18:42: note: each undeclared identifier is reported only once for each function it appears in
   18 | #define SUNXI_RESUME_BASE               (CONFIG_ARMV7_SECURE_BASE + \
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~
include/configs/sun8i.h:22:42: note: in expansion of macro 'SUNXI_RESUME_BASE'
   22 | #define SUNXI_SCP_BASE                  (SUNXI_RESUME_BASE + SUNXI_RESUME_SIZE)
      |                                          ^~~~~~~~~~~~~~~~~
board/sunxi/board.c:865:28: note: in expansion of macro 'SUNXI_SCP_BASE'
  865 |         if (!rproc_load(0, SUNXI_SCP_BASE, SUNXI_SCP_MAX_SIZE)) {
      |                            ^~~~~~~~~~~~~~
include/configs/sun8i.h:19:42: error: 'CONFIG_ARMV7_SECURE_MAX_SIZE' undeclared (first use in this function)
   19 |                                          CONFIG_ARMV7_SECURE_MAX_SIZE)
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/configs/sun8i.h:22:42: note: in expansion of macro 'SUNXI_RESUME_BASE'
   22 | #define SUNXI_SCP_BASE                  (SUNXI_RESUME_BASE + SUNXI_RESUME_SIZE)
      |                                          ^~~~~~~~~~~~~~~~~
board/sunxi/board.c:865:28: note: in expansion of macro 'SUNXI_SCP_BASE'
  865 |         if (!rproc_load(0, SUNXI_SCP_BASE, SUNXI_SCP_MAX_SIZE)) {
      |                            ^~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:258: board/sunxi/board.o] Error 1
make[1]: *** [Makefile:1923: board/sunxi] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by heitbaum** [comment]
> This will need a detailed look. Maybe Samuel already fixed it in one of his branches.

I checked the branch. It matches my proposed. But will have the same compile error. https://github.com/smaeul/u-boot/commit/67d5c4c59d012916dd9d556d98cdcdc9554826c7 
https://github.com/smaeul/u-boot/commits/allwinner

**Comment by heitbaum** [comment]
[ANN] U-Boot release v2022.07 DELAYED 1 week

https://lists.denx.de/pipermail/u-boot/2022-July/487922.html

**Comment by heitbaum** [comment]
U-boot 2022.07 released.
https://www.mail-archive.com/u-boot@lists.denx.de/msg444768.html 
Issue with h5 build - will leave merge-blocked until resolved.

**Comment by jernejsk** [comment]
I guess quick fix would be to move this patch to H3 specific folder. Anyway, this needs testing.

**Comment by heitbaum** [comment]
Hi @jernejsk  - I have moved the 2 patches to the H3 folder and now all of A64,H3,H5,H6 build.

**Comment by chewitt** [comment]
Is this GTG now?

**Comment by heitbaum** [comment]
> Is this GTG now?

I’m using it with the TX6 and using it in the kernel build tree.

**Review by CvH — APPROVED** [review]

**Pull request merged**
