### PR TITLE
ffmpeg: update rpi patch

### PR DESCRIPTION
**Pull request by HiassofT**
Runtime tested on RPi4

@CvH it's fine if you merge this after beta 1, no need to respin builds

### CODE REVIEW

**Comment by popcornmix** [comment]
I've got a slight feeling this bump may require:
https://github.com/popcornmix/xbmc/commit/8434ea0864adf3cf972a86f7cfba613bd7e5259b

for deinterlace to work. It was added to Matrix, but is that present in nexus/master?

**Comment by HiassofT** [comment]
@popcornmix we user the previous version of that patch (from end of september): https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/RPi/patches/kodi/0004-DVDVideoCodecDRMPRIME-use-AV_PIX_FMT_DRM_PRIME-for-f.patch

It seems you added `m_pCodecContext->thread_safe_callbacks = 1` (I assume to get rid of the ffmpeg threading warning) - is this working as expected and is the get_buffer callback actually thread safe?

I also noticed you seem to have brought back the deprecated sws_param option - this wasn't present in your series back then

**Comment by HiassofT** [comment]
Sorry, my fault, jernej dropped sws_param a while ago in LE 66894bcff8985d781b3ffd6603af9a676434ac7d so that didn't come from your branches.

And as we unified drmprime filter patches a while ago it then bubbled down the RPi specific patches, too

I'll give the thread_safe change a try, it indeed looks safe (thanks for checking and explaining, btw!)

**Comment by HiassofT** [comment]
I've included the kodi deinterlace patch update as well, testing on RPi4 looks good, and it's fine to merge now

**Review by chewitt — APPROVED** [review]

**Pull request merged**
