### PR TITLE
add "repository.libreelec.tv" to official repos

### PR DESCRIPTION
**Pull request by howie-f**

### CODE REVIEW

**Review by CvH — APPROVED** [review]

**Review by CvH — APPROVED** [review]

**Comment by HiassofT** [comment]
patch doesn't apply and breaks build, please fix
```
    APPLY PATCH (common)      packages/mediacenter/kodi/patches/kodi-100.32.add-le-repository-to-officials.patch
patching file version.txt
Hunk #1 FAILED at 7.
1 out of 1 hunk FAILED -- saving rejects to file version.txt.rej
*********** FAILED COMMAND ***********
patch -d $(echo "${PKG_BUILD}" | cut -f1 -d\ ) -p1 1>&${VERBOSE_OUT}
**************************************
```

**Comment by HiassofT** [comment]
@howie-f LE master is using kodi master but the patch seems to be for Matrix

**Comment by howie-f** [comment]
arf, i‘m sorry. just cherry-picked it. please revert, i‘ll provide the correct later 😳

**Comment by HiassofT** [comment]
just create a fixup PR when you're at it, no huge problem

**Pull request merged**
