### PR TITLE
Virtual Project Staging

### PR DESCRIPTION
**Pull request by zalaare**
This is a placeholder PR until this is cleaned up and finalized.

We are trying to make VMware and Virtualbox images during the regular `make image` process.  They should be generic enough to "just work" for use and be sane enough to handle both older versions of VB, or VMware.

Current status:

*VMware*
 - Import .ova file works as expected.
 - vmdk needs to be physically expanded by the user prior to booting for the first time or the storage partition will continue to stay the 32MB (which may be fine for the user).
   - If [PR#205](https://github.com/LibreELEC/LibreELEC.tv/pull/205) is used in conjunction, then user can resize disk at any point, then use the Reset LE to defaults option.
 - sound is working now

*Virtualbox*
 - Import .ova file works as expected.
 - image uses vmdk, so if the user wants to expand the disk, they will have to:
`vboxmanage clonehd $image.vmdk $image.vdi ; vboxmanage modifyhd $image.vdi --resize $size_in_mb`  : user can then attach the newly expanded vdi to their vm.
   - If [PR#205](https://github.com/LibreELEC/LibreELEC.tv/pull/205) is used in conjunction, then user can resize disk at any point, then use the Reset LE to defaults option.

### CODE REVIEW

**Comment by lrusak** [comment]
You have packages in the `project/` dirs, please move them.

You're commit messages don't match our styling.

Overall I don't agree with this. The create_virtualimage script we ship should be more than enough for users to create their own disk image. When providing pre built images you will be locked to using one size. It's just not worth it in my opinion.

**Comment by zalaare** [comment]
I can move projects/$PROJECT/packages to $ROOT/packages of course.

> You're commit messages don't match our styling.

Please explain. 

I don't agree with create_virtualimage.  I found it did almost exactly what mkimage was already doing, except it had to be run as root and required more dependencies to be installed on the host system.  The end-user can always re-size their disk image on their own so they are not locked to using one size afaik.  In vmware this is expanding and vboxmanage can resize vdi's.

**Comment by lrusak** [comment]
commit styling examples
```
qemu: add initial package
```
```
linux.x86_64.conf: add ensoniq es1371 sound card support
```

Sure, if you want to do it then go for it I won't block it. Just be aware that the virtual project is *not* aimed at users, it is aimed at developers for testing. If users need to use virtualization then they should use the Generic project in KVM.

**Comment by zalaare** [comment]
I've cleaned up the cosmetics of the commits including messages, some squashing, and some splitting.

**Comment by zalaare** [comment]
I've dropped the ovftool requirements from this PR thereby removing any need to deal with VMware licensing and packaging issues.  I'm still working on getting the ova manifest to work properly and I've left my commit regarding that off the last push.

Dropping ovftool made the virtual package rather redundant, but I don't know which is preferred:
`[ "$PROJECT" = Virtual ] && $SCRIPTS/install qemu:host`
`[ "$PROJECT" = Virtual ] && $SCRIPTS/install virtual`
I left it with the latter though virtual only installs qemu:host at this time.

**Comment by CvH** [comment]
@zalaare good to merge ? If no complains from @lrusak pls merge :)

**Comment by zalaare** [comment]
Yes, this should be good to merge.

**Comment by zalaare** [comment]
Recently the "es1371" audio driver stopped working correctly (vmware).  Switching to "hdaudio" solved this problem.

It was suggested to move the default Ethernet setup type from NAT to bridged.  I've done this as well.

A recent OVA with these changes can be found [Here](http://freeweb.mine.nu/zalaare/LibreELEC/LibreELEC-Virtual.x86_64-8.0-devel-20160727190941-r23499-g815e632.img.ova), however this OVA does **not** have any Virtualbox support in it because I cut it out when building for my testing purposes.

**Comment by anoma** [comment]
For historical reference we ideally want guestOS = "other3xlinux-64" rather than "Ubuntu 64-Bit" but the reference code currently eludes us.
	
I personally have no problems with not having Virtualbox OVA support since currently Virtualbox  does not work well anyway (and ongoing theme for Virtualbox). The inclusion of working sound and the trivial VMWare install are big steps for developers.

RQuning here no issues. Recommend pulling ASAP so it can be tested as part of the current Alpha cycle.

**Comment by zalaare** [comment]
Latest changes are squashed up.  Got this down the minimal commits.  Good to merge.

**Pull request merged**
