### PR TITLE
hybrid CEC driver for Odroid C2

### PR DESCRIPTION
**Pull request by gdachs**
Works with and without libcec. Based on the amlogic driver with extensions made by raybuntu and an libcec adapter made by me.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Why does Odroid need it's own libcec package? Can't Odroid share the existing libcec package?

**Comment by gdachs** [comment]
Because this ifdefs in the existing package gets more and more ugly. It was anyway not the best idea to decide which adapter to build depending on the KODIPLAYER_DRIVER. The CEC adapter has nothing to do with the display driver. And now this concept is broken, we have now 3 devices with the same display driver but 2 different adapters that are not interchangeable. Instead of finding another stupid criteria to differentiate them, I decided to use a project specific package without all this ifdefs.

**Comment by MilhouseVH** [comment]
Yes, the adapter dependency probably isn't the best solution but better than nothing.

I understand about the `#ifdefs`, but wouldn't you just need to make your current project/package patch into a project patch on top of the shared libcec package? I'm not averse to Odroid having it's own project specific package, just as long as someone remembers to bump it.

However if at all possible I'd rather it wasn't there, since the changes required to use the shared version seem so minor, but I'll leave it up to the rest of the team to decide.

**Comment by gdachs** [comment]
The patches for Wetek Core/Play and imx6 was already moved to their project specific patch directories some days before, because they was all the time in conflict in their common directory without any sense, because the adapter for imx6 was build for the weteks too, but never used. Why to have dead code on the devices?

**Comment by MilhouseVH** [comment]
Make `libcec-00-aocec-support.patch` project specific, building on top of the shared `libcec` package (once it's adapted to support the Odroid project), why wouldn't that work? You also wouldn't need PR208 as a project patch.

**Comment by gdachs** [comment]
because this doesn't work for the odroid: 
if [ "$KODIPLAYER_DRIVER" = "libamcodec" ]; then
  EXTRA_CMAKE_OPTS="$EXTRA_CMAKE_OPTS -DHAVE_AMLOGIC_API=1"
else
  EXTRA_CMAKE_OPTS="$EXTRA_CMAKE_OPTS -DHAVE_AMLOGIC_API=0"
fi

**Comment by MilhouseVH** [comment]
So find a solution that does... add an Odroid option if necessary.

**Comment by gdachs** [comment]
No, this is not my job, this PR is only an offer. For me it would be enough to PR this adapter to the upstream libcec, where it will stuck for months. I was so nice to make it more easy to you to get access to it. If you don't like it like it is, change it to you needs, or reject it. I will not beg for inclusion to LibreELEC.

**Comment by MilhouseVH** [comment]
So you want us to accept a bad solution that results in unnecessary maintenance overhead because you've been so kind to give it to us? Not sure it works that way...

:-1:

**Pull request closed without merging**
