### PR TITLE
linux: add udev rule to switch mode on Realtek RTL8821CU devices

### PR DESCRIPTION
**Pull request by vpeter4**
0bda:1a2b  RTL8821CU

### CODE REVIEW

**Comment by chewitt** [comment]
@vpeter4 does the approach in 40-modeswitch.rules not work for this device? (eject /dev/sr0)

**Comment by vpeter4** [comment]
No, this rule only ejects CD rom drive.
But usb_modeswitch changes the mode of 'multi-mode' USB devices.

**Comment by chewitt** [comment]
I was about to ask if RTL8821CU is supported in the upstream kernel? or only in a downstream vendor driver that CE has (which sounds like yes). Either way I think I'd want to promote usb_modeswitch from the system-tools add-on to a standard package, as the dependency on having the add-on installed (which requires a working network) is rather ugly for a network card driver.

**Comment by vpeter4** [comment]
I don't see vid:pid in 5.15.5.
Regarding usb_modeswitch: There is always an option to do that.

**Comment by chewitt** [comment]
Something is upstream but I can't find vid/pid stuff: https://github.com/torvalds/linux/commits/master?after=2b14864acbaaf03d9c01982e243a84632524c3ac+139&branch=master&path%5B%5D=drivers&path%5B%5D=net&path%5B%5D=wireless&path%5B%5D=realtek&path%5B%5D=rtw88

**Comment by vpeter4** [comment]
@chewitt: I got option to test this devices and seems it is enough to just eject /dev/sr0 device as done in 40-modeswitch.rules - no usb_modeswitch program is needed. That's why I only add rule there. I assume this would be acceptable for LE?

**Comment by chewitt** [comment]
Yeah, not a problem since it's just a couple of lines of text. Hopefully upstream lands support for them at some point.

**Review by chewitt — APPROVED** [review]

**Comment by vpeter4** [comment]
Thank you.

**Comment by Vyacheslav-S** [comment]
This rule does not work.
 I tested this rule on system 11.05, 11.06 and nightly builds 12.
```
journalctl -f
....
Apr 07 20:51:46 LibreELEC kernel: usb 4-1.1: new high-speed USB device number 4 using ehci-platform
Apr 07 20:51:46 LibreELEC kernel: usb-storage 4-1.1:1.0: USB Mass Storage device detected
Apr 07 20:51:46 LibreELEC kernel: scsi host0: usb-storage 4-1.1:1.0
Apr 07 20:51:47 LibreELEC kernel: scsi 0:0:0:0: CD-ROM            Realtek  Driver Storage   1.00 PQ: 0 ANSI: 0 CCS
Apr 07 20:51:47 LibreELEC kernel: sr 0:0:0:0: [sr0] scsi3-mmc drive: 0x/0x caddy
Apr 07 20:51:47 LibreELEC kernel: cdrom: Uniform CD-ROM driver Revision: 3.20
Apr 07 20:51:47 LibreELEC kernel: sr 0:0:0:0: Attached scsi CD-ROM sr0
Apr 07 20:51:47 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:52:18 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:52:48 LibreELEC systemd-udevd[326]: sr0: Worker [1697] processing SEQNUM=2589 is taking a long time
Apr 07 20:52:49 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:53:20 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:53:51 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:54:01 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:54:31 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:54:48 LibreELEC (udev-worker)[1697]: sr0: Spawned process 'cdrom_id --lock-media /dev/sr0' [1725] timed out after 46s, killing
Apr 07 20:54:48 LibreELEC systemd-udevd[326]: sr0: Worker [1697] processing SEQNUM=2589 killed
Apr 07 20:54:48 LibreELEC systemd-udevd[326]: sr0: Worker [1697] terminated by signal 9 (KILL).
Apr 07 20:55:02 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:55:10 LibreELEC nmbd[1012]: [2024/04/07 20:55:10.629396,  0] ../../source3/nmbd/nmbd_namequery.c:109(query_name_response)
Apr 07 20:55:10 LibreELEC nmbd[1012]:   query_name_response: Multiple (2) responses received for a query on subnet 192.168.10.204 for name WORKGROUP<1d>.
Apr 07 20:55:10 LibreELEC nmbd[1012]:   This response was from IP 192.168.10.226, reporting an IP address of 192.168.10.226.
Apr 07 20:55:33 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:55:49 LibreELEC systemd-udevd[326]: sr0: Worker [1734] processing SEQNUM=2593 is taking a long time
Apr 07 20:56:04 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:56:34 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:57:05 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:57:36 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:57:49 LibreELEC systemd-udevd[326]: sr0: Worker [1734] processing SEQNUM=2593 killed
Apr 07 20:58:07 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:58:17 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:58:17 LibreELEC systemd-udevd[326]: sr0: Worker [1734] terminated by signal 9 (KILL).
Apr 07 20:58:48 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:59:18 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:59:28 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 20:59:59 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 21:00:18 LibreELEC nmbd[1012]: [2024/04/07 21:00:18.146471,  0] ../../source3/nmbd/nmbd_namequery.c:109(query_name_response)
Apr 07 21:00:18 LibreELEC nmbd[1012]:   query_name_response: Multiple (2) responses received for a query on subnet 192.168.10.204 for name WORKGROUP<1d>.
Apr 07 21:00:18 LibreELEC nmbd[1012]:   This response was from IP 192.168.10.226, reporting an IP address of 192.168.10.226.
Apr 07 21:00:30 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 21:01:03 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 21:01:35 LibreELEC kernel: usb 4-1.1: reset high-speed USB device number 4 using ehci-platform
Apr 07 21:02:25 LibreELEC kernel: usb 4-1.1: USB disconnect, device number 4
......

```
It only works like this: 
```
usb_modeswitch -K -W -v 0bda -p 1a2b
```
```
# lsusb
...
Bus 004 Device 005: ID 0bda:c820 Realtek Semiconductor Corp. 802.11ac NIC
...
```

**PS:** _tested on OrangePi 3lts._

**Comment by vpeter4** [comment]
You should provide complete dmesg. Maybe with running `usb_modeswitch` at the end after a minute or two to be complete.

**Comment by Vyacheslav-S** [comment]
Ok.
Thanks for the quick response to my message!
dmesg after booting the system:
[https://pastebin.com/1qsuCDnN](https://pastebin.com/1qsuCDnN)
dmesg after `usb_modeswitch -K -W -v 0bda -p 1a2b` :
[https://pastebin.com/L5eYNFvr](https://pastebin.com/L5eYNFvr)
`journalctl -f:`
[https://pastebin.com/j4ZJehnB](https://pastebin.com/j4ZJehnB)

**Comment by vpeter4** [comment]
I don't know why it doesn't work but looks strange to me that CD-ROM appears so late after boot.
```
[   40.728887] usb 4-1.1: new high-speed USB device number 4 using ehci-platform
[   40.839204] usb-storage 4-1.1:1.0: USB Mass Storage device detected
[   40.840631] scsi host0: usb-storage 4-1.1:1.0
[   41.855533] scsi 0:0:0:0: CD-ROM            Realtek  Driver Storage   1.00 PQ: 0 ANSI: 0 CCS
[   41.861873] sr 0:0:0:0: [sr0] scsi3-mmc drive: 0x/0x caddy
[   41.861896] cdrom: Uniform CD-ROM driver Revision: 3.20
[   41.867103] sr 0:0:0:0: Attached scsi CD-ROM sr0
```

What happen if you boot device without a stick and you attach it later: Does it work or also usb_modeswitch is needed?

**Comment by Vyacheslav-S** [comment]
> What happen if you boot device without a stick and you attach it later: Does it work or also usb_modeswitch is needed?

I did that. First, I downloaded the device , and then connected the Wifi.

**Comment by vpeter4** [comment]
And what happens when device is attached on boot?

**Comment by Vyacheslav-S** [comment]
The udev rule worked once. But it doesn't happen every time.

**Pull request merged**
