### PR TITLE
kodi: update to 2022-12-23

### PR DESCRIPTION
**Pull request by CvH**
build and runs for generic

### CODE REVIEW

**Comment by heitbaum** [comment]
```
=== run tested on ===
Generic.x86_64-devel-20211215093434-f2f12e6
Linux nuc11 5.15.8 #1 SMP Wed Dec 15 10:08:31 UTC 2021 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:2fa799fc5d6a89282c9e5a0924465b6f2f7c13ca). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2021-12-15 by GCC 10.3.0 for Linux x86 64-bit version 5.15.8 (331528)
Running on LibreELEC (heitbaum): devel-20211215093434-f2f12e6 11.0, kernel: Linux x86 64-bit version 5.15.8
FFmpeg version/source: 4.4-Kodi
Host CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 8 cores available
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0041.2021.0811.1505 08/11/2021
CApplication::CreateGUI - trying to init gbm windowing system
RetroPlayer[PROCESS]: Registering process control for GBM
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_RENDERER = Mesa Intel(R) Xe Graphics (TGL GT2)
GL_VERSION = OpenGL ES 3.2 Mesa 21.3.1
libva info: VA-API version 1.13.0
vainfo: VA-API version: 1.13 (libva 2.13.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.4.3 (c5a7688bda)
```

**Review by heitbaum — APPROVED** [review]

**Comment by SupervisedThinking** [comment]
this needs some adjustments https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Rockchip/patches/kodi/0002-WIP-DRMPRIME-deinterlace-filter.patch#L470

```
    APPLY PATCH (project)      projects/Rockchip/patches/kodi/0002-WIP-DRMPRIME-deinterlace-filter.patch
patching file xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecDRMPRIME.cpp
Hunk #2 succeeded at 344 (offset 11 lines).
Hunk #3 succeeded at 432 (offset 24 lines).
Hunk #4 succeeded at 481 with fuzz 1 (offset 33 lines).
Hunk #5 succeeded at 575 (offset 45 lines).
Hunk #6 succeeded at 816 (offset 45 lines).
Hunk #7 succeeded at 834 (offset 45 lines).
Hunk #8 succeeded at 866 (offset 45 lines).
patching file xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecDRMPRIME.h
Hunk #1 FAILED at 38.
1 out of 1 hunk FAILED -- saving rejects to file xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecDRMPRIME.h.rej
```

**Comment by jernejsk** [comment]
same fix is needed for AW

**Comment by HiassofT** [comment]
Updated deinterlace patch for RPi is here: https://github.com/HiassofT/LibreELEC.tv/commit/94eae283cdd8c29aec05ac043d437ac56b1805b0

Runtime test on RPi4 looks good so far

**Comment by CvH** [comment]
updated kodi and added the rpi patch (unpack works)
@jernejsk RK and AW DI patch needs a rebase

**Review by HiassofT — APPROVED** [review]
Runtime test on RPi4 looks good so far

**Comment by jernejsk** [comment]
This fixes AW patch: http://ix.io/3JjG I suppose RK fix is the same. Patches just need rebase.

**Comment by CvH** [comment]
@jernejsk added patch + rebased patches ontop current kodi (patch is not from a rebase I guess), unpacks cleanly for AW and RK - not sure this works

rebased cec framework patch too, should apply cleanly now

**Comment by jernejsk** [comment]
It tested AW DI patches, so they work. This type of rebases have very low chance to break something, so I think this is gtg.

**Comment by heitbaum** [comment]
```
=== tested on ===
Generic.x86_64-devel-20211224094451-3689b81
Linux nuc11 5.15.11 #1 SMP Fri Dec 24 09:37:40 UTC 2021 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:5633f5940067d57bff1395aaf2dd3a8536d0e437). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2021-12-24 by GCC 10.3.0 for Linux x86 64-bit version 5.15.11 (331531)
Running on LibreELEC (heitbaum): devel-20211224094451-3689b81 11.0, kernel: Linux x86 64-bit version 5.15.11
FFmpeg version/source: 4.4-Kodi
Host CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 8 cores available
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0041.2021.0811.1505 08/11/2021
CApplication::CreateGUI - trying to init gbm windowing system
RetroPlayer[PROCESS]: Registering process control for GBM
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_RENDERER = Mesa Intel(R) Xe Graphics (TGL GT2)
GL_VERSION = OpenGL ES 3.2 Mesa 21.3.2
libva info: VA-API version 1.13.0
vainfo: VA-API version: 1.13 (libva 2.13.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.4.3 (3689b81222)
```

**Pull request merged**
