### PR TITLE
i.MX6 4.4 kernel: update the patches set to all known in the wild

### PR DESCRIPTION
**Pull request by jerome-benoit**
There's DVB and HID input drivers update, a bug fix to eMMC card booting, etc.

It's a safe patches set used by a lot of projects using kernel 4.4 for i.MX6

Signed-off-by: Jérôme Benoit <jerome.benoit@piment-noir.org>

### CODE REVIEW

**Comment by vpeter4** [comment]
I really doubt that out there are users which are using all those remote controls and dvb devices. But probably can't hurt to include them anyway.

Btw: which projects using kernel 4.4 for i.MX6 (because you wrote a lot)? I don't know many of them.

**Comment by jerome-benoit** [comment]
armbian, xbian, RPI v1 v2 and v3 projects are based on 4.4 often with some of the patches here, all GNU/Linux distributions that ship ARMv7 variant have used 4.4 at some point (Debian, Fedora, Ubuntu, OpenSUSE, Arch Linux ARM, etc.) 

Fedora 24 is based on 4.7.X and lack OpenEGL support on i.MX6 but work with some bugs.

The patches set is tested here since 24 h on playlist that loop without any issues so far. 

Regards.

**Comment by chewitt** [comment]
@jerome-benoit LE has a minimalist approach towards hardware support. We are happy to add support for specific things that _will_ be used (for a new hardware platform or a specific user request) but we do not speculatively add support for things that _might_ be used. This approach helps us avoid "the death of a thousand cuts" and unnecessary bloat in our images. Attempting to support all possible devices is the job of general purpose distro's. 

NB: If we add support we generally try to keep things in-sync across multiple build-system projects. In the case of iMX6 we also need to consider that we are downstream from mk01's Xbian work and some changes may be more appropriate there to reduce our local patch set.

**Comment by jerome-benoit** [comment]
Please read the patches set, it simply cover support for hardware that is commonly used and not might used by other projects. 

New DVB drivers support and bugs fixed in the kernel DVB layer is not optional to a mediacenter distro. 
New joysticks support and bugs fixed on very common one like PS/3 or XBOX is not optional to distribution centered on kodi that have support for games.  

I agree that the handling of kernel patches in LE should be done differently but since LE do not have  
a smart way to share them across projects and same major kernel version, for now I've added them where it's relevant and known to work flawlessly. Make use of them across more projects can be done later when/if LE have the infrastructure to share patches across projects with same major kernel version. And as a bonus the patches set will benefit of some testing by i.MX6 users. 

And pushing them in your i.MX6 upstream is orthogonal to adding them in LE, it's a simple matter of "git rm" when it's merged.

**Comment by vpeter4** [comment]
There are not much imx6 users and I really doubt there will be anyone using any new dvb device or remote. Most only needs working cec.

Maybe @Kivutar can comment if anything is useful for Lakka.

**Comment by Kivutar** [comment]
Yeah OUYA can be useful.

**Comment by jerome-benoit** [comment]
On Wed, 26 Oct 2016 11:06:19 -0700 in
<LibreELEC/LibreELEC.tv/pull/883/c256430303@github.com>, "Peter V."
<notifications@github.com> wrote:

> There are not much imx6 users and I really doubt there will be anyone
> using any new dvb device or remote. Most only needs working cec.

Probably because there's no documentation detailing the
installation and setup of a DVB device on the wiki ;-) 

The joystick support will be more important with the games repo in Kodi.

> 
> Maybe @Kivutar can comment if anything is useful for Lakka.
> 

Lakka already use this patches set with a 3.14.X kernel base. 
They also have added support for the valve hardware. 

Cheers,

-- 
Jérôme Benoit aka fraggle
Piment Noir - http://piment-noir.org
OpenPGP Key ID : 9FE9161D
Key fingerprint : 9CA4 0249 AF57 A35B 34B3 AC15 FAA0 CB50 9FE9 161D

**Comment by jerome-benoit** [comment]
On Wed, 26 Oct 2016 11:06:19 -0700 in
<LibreELEC/LibreELEC.tv/pull/883/c256430303@github.com>, "Peter V."
<notifications@github.com> wrote:

> There are not much imx6 users and I really doubt there will be anyone
> using any new dvb device or remote. Most only needs working cec.

In fact this patches set is not an improvement, it fix a regression
since the switch to linux kernel version 4.4 for i.MX6. 

LE were shipping stable version based on 3.14 with this patches set
and even more. 
LE is now shipping alpha version based on 4.4 without them. 

Regards,  

-- 
Jérôme Benoit aka fraggle
Piment Noir - http://piment-noir.org
OpenPGP Key ID : 9FE9161D
Key fingerprint : 9CA4 0249 AF57 A35B 34B3 AC15 FAA0 CB50 9FE9 161D

**Comment by vpeter4** [comment]
imx6 le project will always be far, far back from other ones. 
And it is not me who decide about including such patches.

**Comment by jerome-benoit** [comment]
On Thu, 27 Oct 2016 08:57:38 -0700 in
<LibreELEC/LibreELEC.tv/pull/883/c256687850@github.com>, "Peter V."
<notifications@github.com> wrote:


> And it is not me who decide about including such patches.

If LE project policy is to ship regression between release, do not
include them :-)

-- 
Jérôme Benoit aka fraggle
Piment Noir - http://piment-noir.org
OpenPGP Key ID : 9FE9161D
Key fingerprint : 9CA4 0249 AF57 A35B 34B3 AC15 FAA0 CB50 9FE9 161D

**Comment by vpeter4** [comment]
Seems you are offering yourself for imx6 project head? Just let us know - but keep CEC working (which is broken atm) and keep my LVDS display working on Udoo dual/quad (which is also broken). And I will finally have much more free time :D

**Comment by Kivutar** [comment]
This PR breaks these two things?

**Comment by vpeter4** [comment]
No, both things are broken without it in master.

**Comment by Kivutar** [comment]
Then if this PR is not breaking things, and fixes a regression on eMMC I think it's worth merging it. @jerome-benoit said they were safe and well tested.
That plus the various joypad support added.

**Comment by jerome-benoit** [comment]
Le 28/10/2016 à 14:54, Peter V. a écrit :
>
> Seems you are offering yourself for imx6 project head?
>

Not at all, just a power user that can't use anymore is AverTV Volar HD
2 key and PS/3 joypad with his cubox-i after switching to LE alpha ;-)
Then finally found the reason and wanted to fix it.

> Just let us know - but keep CEC working (which is broken atm) and keep
> my LVDS display working on Udoo dual/quad (which is also broken). And
> I will finally have much more free time :D
>

Is it broken on other hardware too ?

Regards,

-- 
Jérôme Benoit aka fraggle
Piment Noir - http://piment-noir.org
OpenPGP Key ID : 9FE9161D
Key fingerprint : 9CA4 0249 AF57 A35B 34B3 AC15 FAA0 CB50 9FE9 161D

**Comment by vpeter4** [comment]
Let's merge then.
And move on to new challenges :)

**Comment by gdachs** [comment]
I am not aware of any other LE platform with broken CEC. The only other platform that has CEC is Amlogic.  
The kernel drivers and libcec adapters for Amlogic, have not so much in common with the drivers of the i.MX6.

**Comment by vpeter4** [comment]
Broken cec on imx6 has nothing to do with amlogic.
It happens from v7.90.007 where it is fine and with v7.90.008 doesn't work anymore. Seems kernel bump but didn't have time to check what went wrong (working on LVDS display atm).

**Comment by gdachs** [comment]
@vpeter4: but that is exactly what I told. It was jerome-benoit that was asking for other platforms.

**Comment by sopparus** [comment]
if it means anything this works fine for me (not using any of the extra features)

**Pull request merged**
