### PR TITLE
libX11: remove makekeys dependency on X headers

### PR DESCRIPTION
**Pull request by vpeter4**
Needed for building on arm (and using with jre/bd-j menus).

### CODE REVIEW

**Comment by lrusak** [comment]
There isn't really much context here. Why should we add a patch for something we don't even support? Can you link to the relevant commits that require this change?

**Comment by vpeter4** [comment]
I will soon send PR for addon with JRE to play BD-J menus. And JRE needs some extra X libraries which are not build for arm or they are build statically (and rebuild shared as for chrome browser).

**Comment by vpeter4** [comment]
So is there any interest in addon? If not I will not waste time sending another PR with it.

**Comment by vpeter4** [comment]
Thank you.

**Comment by MilhouseVH** [comment]
x86_64 builds now fail: http://ix.io/1NMu

**Comment by MilhouseVH** [comment]
@vpeter let me know what you plan on doing with this - I feel a quick revert might be best so that you can try again?

**Comment by MilhouseVH** [comment]
Looks like on systems without `/usr/include/X11/X.h` (eg. Ubuntu 16.04) then `libX11` will fail for the reason above - this is almost certainly a dependency issue (missing `xorgproto`) but digging deeper...

**Comment by MilhouseVH** [comment]
Just to say it's not an `xorgproto` dependency issue, as `libX11` pulls in `xorgproto` via `libXau`, so at the moment it's not obvious why this patch causes builds to fail on systems that don't have `/usr/include/X11/X.h` installed.

**Comment by CvH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/pull/3655 should fix it

**Comment by vpeter4** [comment]
The point of mine patch was to remove the X dependency for makekeys. That's why only uses some internal headers which are part of the package. But seems some strange things happen which depends on installed host headers. I can't replicate this failed building.

**Comment by CvH** [comment]
just rename/rm `/usr/include/X11/X.h` at host system :)
the fix above should fix that

**Comment by vpeter4** [comment]
Then xorgproto should be build for host and not only target? This would bring file but there is also missing include. So better to just skip everything if not needed at all.

**Comment by vpeter4** [comment]
Seems there were already discussion about same problem here https://github.com/LibreELEC/LibreELEC.tv/pull/3194 which I forgot.
But because such issues are ignored we come back again on it and waste time even more time :(

**Comment by CvH** [comment]
> Seems there were already discussion about same problem here #3194 which I forgot.

but there was no proper fix available that time, luckily someone fixed libx11 upstream some weeks ago :)

**Comment by vpeter4** [comment]
We could come to it if there would be enough willpower.

**Comment by MilhouseVH** [comment]
>  But because such issues are ignored we come back again on it and waste time even more time :(

Not ignored, just not understood - at the time there wasn't a problem building LE master, which made it far less urgent, and it was a problem with an unknown out of tree package which tends to make it harder to understand the problem in the first place.

As you can see from the discussion - which you were a part of - it wasn't clear why the proposed change was required (which was wrong, or at best a hacky fix which rightly contributed to the non-merge situation), or what the correct fix should be, and it turns out a more comprehensive upstream fix was required (which has now appeared, fortunately).

Breaking master does tend to focus the attention, though - so well done on that, but please don't do it again any time soon. :)

**Comment by vpeter4** [comment]
> at the time there wasn't a problem building LE master

And that's the problem: no problem with le -> no problem for anyone else.

> Breaking master .... don't do it again any time soon

You are kidding right? Master is a playground and such problems can occur. But ok, will try not to send any pr soon.

**Comment by MilhouseVH** [comment]
> And that's the problem: no problem with le -> no problem for anyone else.

I'd have thought my statement was pretty obvious. I really don't see why you think it is a problem. As much as anyone here is willing to help with out of tree problems, the priority and focus of most of us is on the code we have in front of us.

> You are kidding right? Master is a playground and such problems can occur.

Absolutely not kidding. Master is not a playground - that's why we have PRs which we normally test prior to merging but because you started stamping your feet and making threats with this comment:

> So is there any interest in addon? If not I will not waste time sending another PR with it.

you somehow circumvented the normal process and were able to have your 2-3 day old PR merged without even the most basic testing from others.

Of course things break in master, even my own stuff breaks (as we found while testing your JRE PR), but it's pretty rare these days for a PR of mine or anyone else to be merged without actually even building! It's been quite a while actually since master hasn't been able to build because of a faulty PR, and that's generally how we like it. :smile:

Were it not for the fact that you demanded that this PR be merged without adequate testing I think we (certainly I) could have looked more favourably upon this breakage, and that's the real issue here. You weren't prepared to wait a reasonable period of time to allow testing (this all sounds strangely familiar!), broke master as a result, and then someone else had to clear up the mess - fortunately upstream had a fix otherwise this PR would have been reverted. This is not normal for us but if that's how you think it works here (and think master is a playground) then you might want to send your PRs elsewhere.

> But ok, will try not to send any pr soon.

That is entirely your choice, but personally I hope you do continue to send your PRs. All we ask/expect is to be given the time to test the PRs before anyone starts stamping their feet after a couple of days. :smile:

**Comment by vpeter4** [comment]
> you somehow circumvented the normal process and were able to have your 2-3 day old PR merged without even the most basic testing from others.

It was not a request to merge asap but just to get an answer. So to break master it was not my fault.

**Pull request merged**
