### PR TITLE
[LE12] Allwiner: Implement 10-bit decoding & displaying and some fixes

### PR DESCRIPTION
**Pull request by jernejsk**
Mostly H6 related fixes and improvements. This finally brings H6 on par with some RK SoCs and possibly RPi4 too.

Note that HEVC 4k@60 10-bit decoding may not be smooth in all cases. Manual claims Level 5.1 support and some videos with aforementioned properties may be Level 5.2. These can be a bit jerky at times during playback. 30 fps are always smooth, though.

Fixes:
- Add back ATF hack for regulators, since new approach broke ethernet on OrangePi 3 LTS.
- Replace patch for H6 DRAM initialization which supposedly solves all cases
- Fix potential issues with HEVC decoding
- Fix some issues in DRM driver

Improvements:
- Cedrus implements AFBC buffer compression (H6)
- Implement true 10-bit display pipeline in monitor/TV native format (video is shown as-is, without processing) (H6)
- Add GPU OPP table to all H6 boards for frequency scaling
- Increase Cedrus frequency a bit

### CODE REVIEW

**Review by HiassofT — APPROVED** [review]

**Comment by dhewg** [comment]
Thanks, this fixes ethernet upon cold booting my non-LTS opi3!

But something still isn't right (tested with #8205 included too):
Upon suspend, ethernet isn't always properly disabled and/or powered down. The connected router then doesn't get the "interface is down" event (which worked with a build from a few months ago). Only upon **waking up** the device, the router first gets a down followed by an up event, but then ethernet still doesn't work, somewhat as before this PR.

Any idea?

**Comment by jernejsk** [comment]
Probably revert of f8e03eae5f50e48f1d883fe268d2f45f56c74633 will help. New approach, targeted to be mainlined, seems to have some corner cases which are not covered yet. Please report if revert works. While I won't accept it as solution, I'll at least have better understanding.

**Comment by dhewg** [comment]
I can try a build tomorrow, but reverting just that yields patch file 
conflicts, the annoying kind.

Reverting all of
25bd7da4ae3f4c134b520b334783124123437d54
5e27f9b916ca8853b8b66c34d41daa75763566eb
ada80d4d3a45afbe967adbc238dd6ab616c94cb2
e8bf439a445e774471c7048c0fc733b66588ed27
works, but is that what I really want? :D

**Comment by dhewg** [comment]
With this patch, which also describes how I created it, it works again:
[0001-revert-f8e03eae5f50e48f1d883fe268d2f45f56c74633-by-h.patch.txt](https://github.com/LibreELEC/LibreELEC.tv/files/13060692/0001-revert-f8e03eae5f50e48f1d883fe268d2f45f56c74633-by-h.patch.txt)

I could manually suspend and resume 3 times, and kodi is able to idle suspend too, followed by a crust IR wakeup. Each time the router got the proper "link is down" event.

Let me know if I messed something up or if I should add/remove some hunks

**Comment by jernejsk** [comment]
as I said, this restores old state, but idea is to make new approach behave properly, since is the way to go for upstream. If you have some time, please try to fix new patch.

**Comment by dhewg** [comment]
Time is sparse, and I would kinda poke in the dark. So if you have any ideas I'd prefer a patch to test drive.

Maybe it's just a missing delay? 
Is it maybe the order of the two regulators that's wrong?
What about the `rgmii-id`/`rgmii-txid` change, is it worth trying to change that back?

**Comment by jernejsk** [comment]
rgmii change is related to rx/tx delay. If you change one, you should also change other. I took another look at board schematic and bsp based DT file and I would say new settings are correct (rgmii-id, without rx/tx delay). You can determine which settings are better by doing speed test.

I believe your issue comes from new regulator handling code and not timing settings. It seems that code needs some refinements. Going back to old code isn't something that I want. Anyway, please open issue with relevant details discussed here. Nobody tracks discussions in already merged PRs.

**Pull request merged**
