### PR TITLE
add lcms2 support for kodi

### PR DESCRIPTION
**Pull request by lrusak**
Not sure how I ever missed this.

This allows color management profiles in kodi

This adds an upstream patch from https://github.com/xbmc/xbmc/pull/11072

### CODE REVIEW

**Comment by MilhouseVH** [comment]
The package builds, but is unusable in Kodi - selecting the ICC profile will cause Kodi to crash when playing video: http://sprunge.us/GSJf

I've included this PR (with latest https://github.com/xbmc/xbmc/pull/11072 on top of latest Kodi master) in my #1207 test build where you can see how it behaves - not well.

I guess it's technically correct to merge this, but it's broken upstream...

**Comment by lrusak** [comment]
We can just hold off then. It's not pressing as no one has noticed it was missing until now.

**Comment by MilhouseVH** [comment]
I agree. I'll drop this package from test builds, but re-introduce if there's any potential kodi fixes.

Adding some debug-enabled crashlogs:

Steps to reproduce #1:
1. Play a video
2. Open OSD, click on Settings
3. Open `Colour Management`
4. Enable `Colour management`
5. Switch from `3DLUT file` to another mode (presumably `ICC profile`)
6. Instant crash: http://sprunge.us/XXZS

Steps to reproduce #2:
1. Settings > System settings > Display
2. Enable `Colour management`
3. Select `ICC Profile` as `Colour management mode`
4, Play a video
5. Instant crash: http://sprunge.us/HXQF

**Comment by MilhouseVH** [comment]
Crashlog (reproduced with method #1, above) using lcms2-2.7: http://sprunge.us/YHDV

**Comment by arucard21** [comment]
I did some investigation on this which I reported in #11072. I think the problem here is just because the ICC display profile isn't filled in when ICC mode is enabled for Colour Management. When you select a valid ICC display profile file, it should work correctly.

**Comment by MilhouseVH** [comment]
Yes, confirmed - once an ICC Profile file is selected it no longer crashes (tested both lcms2-2.7 and lcms2-2.8). There needs to be a way to prevent ICC from crashing Kodi before a valid profile file is selected, otherwise enabling ICC via the OSD (method #2, above) will be impossible.

**Comment by arucard21** [comment]
If you want to enable ICC via OSD when it hasn't been configured yet, I think the GUI also needs to be changed. It currently doesn't include a way to specify the ICC display profile. So this can only be done in the Settings dialog.

**Comment by chewitt** [comment]
@lrusak the upstream PR was merged aeons ago. Can you revisit/update or close please.

**Comment by lrusak** [comment]
Just leave it open.

The upstream commit is in yes, but it causes crashes as @MilhouseVH found out.

**Comment by MilhouseVH** [comment]
Agreed. Until Kodi sort out the GUI so that it doesn't crash without a profile file selected there is little point enabling this feature (so leave it open) particularly as it will only be used in anger by a small number of users but become a support overhead as inquisitive users try to use it and end up with a crashing system.

**Pull request closed without merging**
