### PR TITLE
pvr.filmon: Change user agent as filmon was blocking old one

### PR DESCRIPTION
**Pull request by mcaptur**

### CODE REVIEW

**Comment by chewitt** [comment]
Thanks, it will be a couple of days before it appears in the add-on repo as we're still working though a wider list of fixes after the recent gcc bump.

**Comment by awiouy** [comment]
Should we not backport this, as LE7 users are also impacted?

**Comment by chewitt** [comment]
Users who need this can update to the current alpha builds. Upstream Jarvis add-ons haven't been updated since June so there's no plan to backport.

**Comment by Mike-KL** [comment]
@chewitt OK if no plan to backport so where are we with providing inputstream.rtmp for Windows, Andriod and macOS in Krypton as everyone very quite in kodi forum?

http://forum.kodi.tv/showthread.php?tid=297360&pid=2459474#pid2459474
http://forum.kodi.tv/showthread.php?tid=282158&pid=2459931#pid2459931

**Comment by chewitt** [comment]
@Mike-KL inputstream.rtmp is a binary add-on that must be compiled. GitHub "release" files are sources (packed in a zip) not something you can just install from zip. I can't speak for Kodi devs on why something isn't available for other platforms ~ we've enough to handle without worrying about other people's repo's!

**Comment by Mike-KL** [comment]
@chewitt apologies my mistake, incorrectly thought was commenting on recent general kodi update to pvr.filmon not LibreELEC builds. (sorry about noise)

**Pull request merged**
