### PR TITLE
buildsystem: fixes as required

### PR DESCRIPTION
**Pull request by MilhouseVH**
Keep this open a few days, if any other fixes are needed they can be added here.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I have `yacc` installed on my two build hosts, grr.

**Comment by MilhouseVH** [comment]
`tools/dashboard` suggestion from @chewitt - show dashboard for latest build if `PROJECT` is not known/specified.

Specify `PROJECT= DEVICE= ARCH=` to only show the dashboard for a specific build directory.

Add `auto` argument to override PROJECT/DEVICE/ARCH behaviour.

**Comment by vpeter4** [comment]
One suggestion: Pressing Ctrl-C in the middle of building should kill all childs currently building. Now the main script ends but childs are still executed till they finish.

**Comment by MilhouseVH** [comment]
@vpeter4 I'm not seeing this behaviour on Ubuntu 16.04/17.10 - for me, all currently executing processes are automatically killed once the main script (and thus the main `parallel` process) is terminated with CTRL-C.

The only way I can trigger a situation that leaves the child processes executing after the main `parallel` process has exited is to `kill -9 <main-parallel-pid>`, and there's not really very much anyone can do about that (the in-flight build processes will eventually finish/die, and no more jobs will be started as there's no longer a `parallel` main process).

**Comment by vpeter4** [comment]
Maybe you don't see it because you probably have very fast build system? :)
Anyway, it is not a big deal. Was more an observation.

**Comment by MilhouseVH** [comment]
Thanks - observation noted, however ctrl-c should signal the main `parallel` process to terminate which should then terminate all currently executing jobs before it exits, so at the moment I'm not sure why that isn't happening for you (fast system or not). If we can identify the cause then sure, will try and implement a fix.

**Comment by chewitt** [comment]
@MilhouseVH Slice changes LGTM - I clean built/tested an image this morning

**Pull request merged**
