### PR TITLE
vdr-addon: REV 116, update vdr (2.4.7) and plugins / fix $PKG_NAME-config scripts

### PR DESCRIPTION
**Pull request by mglae**
vdr-addon REV 116:
- update VDR to 2.4.7
- update eepg to f8698d8
- update epgsearch to cff8dfe
- update iptv to 7369c95
- update live to b2938de
- update robotv to f521e57
- update satip to 0a216f1
- update wirbelscan 2021.03.07

---
While testing this PR for Generic  some VDR plugins were dynamically linked against libraries we do only build statically. This was caused by $PKG_NAME-config scripts executed from $TOOLCHAIN/bin adding `-L$TOOLCHAIN/lib` to the linker. 

*-config scripts must be installed in $TOOLCHAIN/bin to be reachable but point to sysroot. Before the edited scripts have been installed to $SYSROOT_PREFIX/bin but were never executed.

Fixing this allow in addition to remove all the pkgconfig patches from vdr plugins.

Only the packages curl, cxxtools, ncurses, pcre and tntnet needed for this PR are changed. Other $PKG_NAME-config candidates can be changed in a future PR (maybe for LE 11 only)

---
Runtime tested on Generic after clean building the image and  addons vdr, system-tools, multimedia-tools and network-tools.

### CODE REVIEW

**Comment by CvH** [comment]
@mglae Due the fact we are doing a final/rc LE10 very soonish I am not merge this pr for LE10.

Could you push just the VDR bumps and add the other fixes for LE11?

**Comment by mglae** [comment]
As said, several plugins did not link successfully and I'm happy having found the reason for it. It's a waste of time looking for ugly work arounds when a bug fix exist.

Fixing our toolchain should IMO be possible even in RCs. Furthermore it is unlikely this fix will affect other packages because we should have seen similar issues there in the past when using the *-config scripts.

**Comment by CvH** [comment]
anyone an opinion to the ncurses, pcre, curl changes ?

**Comment by mglae** [comment]
> anyone an opinion to the ncurses, pcre, curl changes ?

As a knowledge question: is anyone aware of a package using ncurses-config, pcre-config or curl-config beside the vdr-plugins?

**Comment by heitbaum** [comment]
I like the fix, I had a not dissimilar problem with pkg-config (can’t remember the package - been too many 😀 - may have been mpd)

having a look at the changelog some commits of interest. It has been moved before it seems.
- c2f3fa56a3b2e9efe99f40c1ebe209d19998ddcb
- d90f7fc063a3ef892f2c861f049a31241d23ed88
- 072ab1a6248b33116adfaeb7282f8d1443073d0c
- 4646c8b19ebbb710ec4d092fa9d5ad26f98ecc2b

The -config doesn’t seem to be consistent : http://paste.ubuntu.com/p/gYPF6fwHqs/

on checking my build tree - at least these packages are using the …-config…
```
cmake-3.20.4
htop-3.0.5
libmicrohttpd-0.9.73
mc-4.8.26
mpd-0.22.9
nmap-7.91
swig-4.0.2
util-linux-2.37
zstd-1.5.0
```

**Comment by mglae** [comment]
@heitbaum Thanks.

> I had a not dissimilar problem with pkg-config 

The pkg-config usage is separated into host and target configuration and should be safe to use. E.g. see the pkg-config patches that are removed in this PR after changing the package specific config scripts.

> having a look at the changelog some commits of interest. It has been moved before it seems.

In the current toolchain we have to decide if the package specific config scripts are usable for building target or (exor) host. IMO target is the better use case. If really needed we have to separate this too in the future.

> on checking my build tree - at least these packages are using the …-config…

I'll go through the list but I do expect some pkg-config false positives.

**Comment by mglae** [comment]
```
cmake:  host; curl-config but using own cmcurl lib
ntop:  target; ncurses-config
libmicrohttpd: target; curl-config but build with --disable-curl
mc: target; pcre-config
mpd: target; curl-config
pcre: target; pcre-config
swig: host; pcre-config but build with --without-pcre
util-linux: host+target; ncurses-config mentioned but build with --without-ncurses --without-ncursesw
zstd: host (+target with addon-zstd); curl-config only in "tests", not used

nmap: target; pcre-config but building own static libpcre
qemu: host; optional curl-config but using pkg-config

```

Conclusion: *-config scripts are likely not used for building host packages. Building target packages is improved with this PR.

**Review by CvH — APPROVED** [review]

**Pull request merged**
