### PR TITLE
add new retroplayer emulators

### PR DESCRIPTION
**Pull request by lrusak**
These currently only work for x86

### CODE REVIEW

**Comment by chewitt** [comment]
All but one have PKG_ARCH set to `any` so if they're x86 only it would make sense to change that or set PKG_ADDON_PROJECTS to `Generic` to save makework on the build server.

**Comment by Anuskuss** [comment]
@lrusak Can you please add [GLupeN64](https://github.com/GLupeN64/GLupeN64/)? It is the best N64 emulator on the Raspberry Pi.

**Comment by lrusak** [comment]
@Anuskuss maybe in the future. Retroplayer doesn't support opengl/es right now so there is no point really.

**Comment by lrusak** [comment]
@chewitt The addons have PKG_ARCH set to x86_64 The others are set to any because they can compile for and arch but we on't want the add-ons for x86_64 if that makes sense.

**Pull request merged**
