### PR TITLE
rpi: switch to zstd squashfs images

### PR DESCRIPTION
**Pull request by antonlacon**
For LE10.

Switch generic too? I'm not sure a user will notice but it should save bandwidth/storage on LE's end.

Benchmarks available here: https://github.com/LibreELEC/LibreELEC.tv/pull/3209

### CODE REVIEW

**Comment by MilhouseVH** [comment]
> Switch generic too?

It probably requires a little more analysis to be sure (ie. file size comparisons etc.), but I suspect we could probably switch all systems to `zstd` for LE10, kernel support permitting.

**Comment by CvH** [comment]
>Btw. what about other ARM platforms like S905?

AML S905 is faster then RPi3+ so it should be okay, requires mainline ofc, ancient 3.14 won't do it.

**Comment by antonlacon** [comment]
Time to look at merging with LE9.2 branched?

**Comment by MilhouseVH** [comment]
With my own nightly test builds, the SYSTEM image file with zstd is reduced in size as follows:

| | Before | After | Change |
|----|----|----|----|
| RPi | 140MB | 110MB | -30MB |
| RPi2 | 140MB | 110MB | -30MB |
| Generic | 246MB | 205MB | -41MB |

Handy! :)

**Comment by 5schatten** [comment]
@antonlacon 
I guess you can also add this to Rockchip options. I use it in my community builds and it works fine.

**Comment by antonlacon** [comment]
@Kwiboo fyi on rockchip change. Verified CONFIG_SQUASHFS_ZSTD=y was in configs, but didn't test anything past that.

This also puts all projects on zstd.

**Comment by MilhouseVH** [comment]
Is this good to go - remove block label and merge?

**Comment by antonlacon** [comment]
As far as I know, it's complete. I've used zstd on rpi since at least October, and the 1MB block size since January.

**Comment by MilhouseVH** [comment]
Thanks!

**Pull request merged**
