### PR TITLE
linux: update to linux-4.9.0

### PR DESCRIPTION
**Pull request by MilhouseVH**
Work in progress. 4.9-rc7.

nvidia-legacy requires a new driver as current driver builds but doesn't load ([ref](https://devtalk.nvidia.com/default/topic/973807/linux/nvidia-linux-x86_64-340-98-driver-not-building-with-kernel-4-9-0-rc2-/post/5008447/#5008447))

ddbridge commit dropped. TBS patch and updated firmware added.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Dropped dvb firmwares - they're in https://github.com/LibreELEC/dvb-firmware/pull/5. The kernel support for the new firmware remains in this PR.

**Comment by lrusak** [comment]
@MilhouseVH at some point (before merging) can you reset the commit dates?
```
git rebase --ignore-date upstream/master
```
Other wise the commits will show up in the list back in november

**Comment by MilhouseVH** [comment]
Updated with 4.9-rc8.

**Comment by MilhouseVH** [comment]
Rebased to use `default` patch directory.

**Comment by MilhouseVH** [comment]
Updated to 4.9.0.

Still waiting for compatible nvidia-legacy driver.

**Comment by MilhouseVH** [comment]
Should be safe to merge after #1059.

**Pull request merged**
