### PR TITLE
lcdd: initial addon

### PR DESCRIPTION
**Pull request by awiouy**
LCDproc as an addon.
I am not sure to have included all required drivers

### CODE REVIEW

**Comment by lrusak** [comment]
might as well build all drivers if it is being built as an addon

```
PKG_CONFIGURE_OPTS_TARGET="--with-ft-prefix=$SYSROOT_PREFIX/usr \
                           --enable-libusb \
                           --enable-libftdi \
                           --disable-libX11 \
                           --enable-libhid \
                           --disable-libpng \
                           --enable-drivers=all \
                           --enable-seamless-hbars"
```

also, it would be nice to dynamically list the drivers into the settings.xml
```
cat $ROOT/$PKG_BUILD/.$TARGET_NAME/config.log | sed -n "s|^DRIVERS=' \(.*\)'|\1|p" | sed "s|.so||g"
```

**Comment by awiouy** [comment]
Rebased:
- builds all drivers
- drivers in settings are updated at build time

**Comment by lrusak** [comment]
LGTM

**Comment by awiouy** [comment]
Rebased:
- removed built-in lcdproc
- updated PKG_ARCH="any"
Thank you @lrusak

**Comment by lrusak** [comment]
Perfect! I'm happy with this.

along with https://github.com/LibreELEC/service.libreelec.settings/pull/33 should be everything.

**Comment by MilhouseVH** [comment]
Can I make a suggestion for the LCD driver settings - instead of a spinner, can you make it a list? Kodi are getting rid of spinners where there's a lot of options available.

**Comment by awiouy** [comment]
Rebased:
use select/values instead of labelenum/lvalues

**Comment by lrusak** [comment]
a couple issues,
```
Could not open driver module /storage/.kodi/addons/service.lcdd/lib/l: libserdisp.so.1: cannot open shared object file: No such file or directory
```
and
```
Could not open driver module /storage/.kodi/addons/service.lcdd/lib/l: /storage/.kodi/addons/service.lcdd/lib/lcdproc/curses.so: undefined symbol: cur_term
```
so just disable curses driver

**Comment by awiouy** [comment]
Rebased to add icon, curses and libserdisp
Will request testing on forum

**Comment by lrusak** [comment]
all good? @awiouy please update the commit dates and we can merge

**Comment by MilhouseVH** [comment]
There was a discussion on Slack (or was it the forum?) about the changing location of the lcdproc config (was /storage/.config, now .kodi/userdata/addon_data etc.) which is going to cause problems/confusion for existing users. Does anyone want to address the migration issues?

**Comment by awiouy** [comment]
Posted on the forum: 2 downloads, 0 feedback.
Rebased on master.

**Comment by lrusak** [comment]
@MilhouseVH so basically you want to migrate so that it detects the driver user were using? and copy the relevant LCDd.conf? I'm not sure if this matters because they have to install the add-on anyway, it shouldn't be a big deal to select the driver they want to use.

**Comment by MilhouseVH** [comment]
@lrusak: http://forum.kodi.tv/showthread.php?tid=269814&pid=2437858#pid2437858

Users seem to have to manually edit a config, so migrating the existing config would make the transition easier, alternatively using the existing config instead of changing the location would make migration unnecessary.

Just mentioning it prior to merge, as it will cause noise that could be avoided.

**Comment by awiouy** [comment]
Like this?

**Comment by lrusak** [comment]
looks good to me

**Comment by awiouy** [comment]
Rebased.

**Comment by awiouy** [comment]
6 downloads in the forum, no feedback.
No news, good news?
Ready to merge,

**Comment by camelreef** [comment]
Hello,

I switched from the 8.0 addon zip provided by Milhouse to the 8.0.100 in the repo, and it's running fine.

Thanks!

**Pull request merged**
