### PR TITLE
kodi: update to lastest master version

### PR DESCRIPTION
**Pull request by HiassofT**
build tested for RPi

### CODE REVIEW

**Review by chewitt — APPROVED** [review]

**Comment by heitbaum** [comment]
Couple strange things:

```
$ rm  /var/media/DATA/home-rudi/LibreELEC.tv/sources/libdvdcss/libdvdcss-bc00dd5770eea1b71209c279f7af43a66a5327fd.tar.gz
$ s/get libdvdcss

[2/1588] Performing download step (verify and extract) for 'dvdcss'
FAILED: build/libdvd/src/dvdcss-stamp/dvdcss-download /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/kodi-cdb14802e55d6ad12085059419ce515844364d45/.x86_64-libreelec-linux-gnu/build/libdvd/src/dvdcss-stamp/dvdcss-download
cd /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/kodi-cdb14802e55d6ad12085059419ce515844364d45/.x86_64-libreelec-linux-gnu/build/libdvd/src && /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/cmake -P /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/kodi-cdb14802e55d6ad12085059419ce515844364d45/.x86_64-libreelec-linux-gnu/build/libdvd/src/dvdcss-stamp/verify-dvdcss.cmake && /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/cmake -P /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/kodi-cdb14802e55d6ad12085059419ce515844364d45/.x86_64-libreelec-linux-gnu/build/libdvd/src/dvdcss-stamp/extract-dvdcss.cmake && /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/cmake -E touch /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/kodi-cdb14802e55d6ad12085059419ce515844364d45/.x86_64-libreelec-linux-gnu/build/libdvd/src/dvdcss-stamp/dvdcss-download
-- verifying file...
     file='/var/media/DATA/home-rudi/LibreELEC.tv/sources/libdvdcss/libdvdcss-bc00dd5770eea1b71209c279f7af43a66a5327fd.tar.gz'
CMake Error at dvdcss-stamp/verify-dvdcss.cmake:29 (message):
  error: SHA512 hash of

    /var/media/DATA/home-rudi/LibreELEC.tv/sources/libdvdcss/libdvdcss-bc00dd5770eea1b71209c279f7af43a66a5327fd.tar.gz

  does not match expected value

    expected: '5185dbdbeb1bd13ea9d8723f1f4ab599d6f3102f5ba1096cd085aa1cda252c045f327c719227bba8e1b742352ade5e335106c8d0c1637a5a6b93ce661620dd7e'
      actual: 'a6ac5d60c578ef78a9bda3d905d6761bebc8824dc388b4487d7c34ed9ad9a0ec9786b8fa7e1215dd3f3f2be102b02be7816e05b2bfa50771153e55412d011efd'
```

**Comment by heitbaum** [comment]
tested on both:
- Allwinner H6 (Tanix TX6)
- Generic Generic (Intel TGL - NUC11)

Intel NUC11 i7-1165G7
```
=== tested on ===
Generic.x86_64-devel-20220212032256-7cc27a8
Linux nuc11 5.16.9 #1 SMP Sat Feb 12 01:38:52 UTC 2022 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:cdb14802e55d6ad12085059419ce515844364d45). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2022-02-12 by GCC 10.3.0 for Linux x86 64-bit version 5.16.9 (331785)
Running on LibreELEC (heitbaum): devel-20220212032256-7cc27a8 11.0, kernel: Linux x86 64-bit version 5.16.9
FFmpeg version/source: 4.4-Kodi
Host CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 8 cores available
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0042.2021.1213.1702 12/13/2021
CApplication::CreateGUI - trying to init gbm windowing system
RetroPlayer[PROCESS]: Registering process control for GBM
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_RENDERER = Mesa Intel(R) Xe Graphics (TGL GT2)
GL_VERSION = OpenGL ES 3.2 Mesa 22.0.0-rc2
libva info: VA-API version 1.13.0
vainfo: VA-API version: 1.13 (libva 2.13.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.2.0 (7cc27a84e2)
```
Allwinner Tanix TX6
```
=== tested on ===
H6.aarch64-devel-20220212033315-f494b19
Linux tx6 5.17.0-rc3 #1 SMP PREEMPT Sat Feb 12 03:34:20 UTC 2022 aarch64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:cdb14802e55d6ad12085059419ce515844364d45). Platform: Linux ARM 64-bit
Using Release Kodi x64
Kodi compiled 2022-02-12 by GCC 10.3.0 for Linux ARM 64-bit version 5.17.0 (332032)
Running on LibreELEC (heitbaum): devel-20220212033315-f494b19 11.0, kernel: Linux ARM 64-bit version 5.17.0-rc3
FFmpeg version/source: 4.4-Kodi
4 CPU cores available
ARM Features: Neon enabled
RetroPlayer[PROCESS]: Registering process control for GBM
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_VERSION = OpenGL ES 2.0 Mesa 21.3.6
```

**Review by heitbaum — APPROVED** [review]

**Comment by HiassofT** [comment]
@heitbaum if you replace libdvdcss/nav/read with a different version than the ones specified in kodi target depends you'd also have to patch kodi version files - or better build them separately instead of using kodi's depends mechanism

**Comment by HiassofT** [comment]
runtime test on RPi4 looks fine, removing draft

**Comment by CvH** [comment]
libblueray needs updated too, the dep was finally updated at kodi

**Comment by HiassofT** [comment]
libbluray bump PR is now here https://github.com/LibreELEC/LibreELEC.tv/pull/6226

**Comment by HiassofT** [comment]
@heitbaum could you have a look at bumping Python - kodi now uses 3.9.10 https://github.com/xbmc/xbmc/pull/20853,  we're still at 3.8

**Comment by heitbaum** [comment]
> @heitbaum could you have a look at bumping Python - kodi now uses 3.9.10 [xbmc/xbmc#20853](https://github.com/xbmc/xbmc/pull/20853), we're still at 3.8

Draft done
- #6227

**Review by CvH — APPROVED** [review]

**Pull request merged**
