### PR TITLE
projects/S905: clean unused modules from kernel config

### PR DESCRIPTION
**Pull request by adamg88**

### CODE REVIEW

**Comment by chewitt** [comment]
We should remove items from kernel config by #commenting not deleting lines. The sole exception is when the CONFIG_BLAH item has been superseded and changed.

**Comment by adamg88** [comment]
The lines are removed automatically as a result of certain options being set to N

The original config was from the N kernel where some options also do not exist in the current MM kernel hence their removal

**Comment by MilhouseVH** [comment]
What is the systemd change for, this doesn't affect only S905?

**Comment by adamg88** [comment]
@MilhouseVH it says in the commit description

**Comment by MilhouseVH** [comment]
Ok thanks. Just for future reference if you put all the information in the commits and nothing in the PR it makes the PR harder to review.

**Comment by adamg88** [comment]
If you look in man/systemd-sleep.conf.xml sleep is configured in 1 of 4 places
```    <para><filename>/etc/systemd/sleep.conf</filename></para>
    <para><filename>/etc/systemd/sleep.conf.d/*.conf</filename></para>
    <para><filename>/run/systemd/sleep.conf.d/*.conf</filename></para>
    <para><filename>/usr/lib/systemd/sleep.conf.d/*.conf</filename></para>```

Of these 4 only 1 is removed and symlinked, I have checked all projects before hand to confirm that this would not interfere with any other projects, sleep config is stored in /usr/lib/systemd/sleep.conf.d on the other AML projects, and no other project uses it.

The problem was pointed out to me in community builds [link](https://forum.libreelec.tv/thread/10301-9-0-libreelec-9-x-for-s905-s905x/?postID=73865#post73865)

**Comment by Kwiboo** [comment]
@adamg88 I recently added a `sleep.conf` to rockchip feature branch in https://github.com/LibreELEC/LibreELEC.tv/commit/eec47f5203555741fd522dd65c29edecfca9671b and put it at `/etc/systemd/sleep.conf`, not sure if your change will affect anything on Rockchip or not.

**Comment by adamg88** [comment]
@Kwiboo. unfortunately it would, you need to move the file to projects/XXX/filesystem/usr/lib/systemd/sleep.conf.d then there would be no conflict, this is also where it is stored in other projects

**Pull request closed without merging**
