### PR TITLE
emby: update to 3.2.70.13

### PR DESCRIPTION
**Pull request by RobLoach**
https://github.com/MediaBrowser/Emby/releases/tag/3.2.70.13

### CODE REVIEW

**Comment by CvH** [comment]
I have also an ffmpegx update (+addon) we could push along with that (as emby depends at ffmpegx), I pr that separately soonish.

**Comment by RobLoach** [comment]
Thanks, @CvH. Glad to see these get pushed forwards.

**Comment by CvH** [comment]
@RobLoach I close this PR in favor of https://github.com/LibreELEC/LibreELEC.tv/pull/2510, your commit was merged there. Tx for commit !

**Comment by RobLoach** [comment]
This is great! Thanks so much, @CvH. :+1:

**Pull request closed without merging**
