### PR TITLE
retroplayer addons: update to latest Leia versions

### PR DESCRIPTION
**Pull request by HiassofT**
backported mame2014/2015 changes from master.

excluded mame2014 from auto updates as it's decommissioned now.

updates are completely untested - @5schatten can you have a look please?

### CODE REVIEW

**Comment by 5schatten** [comment]
Please add this to the PR https://github.com/LibreELEC/LibreELEC.tv/pull/3780

**Comment by HiassofT** [comment]
with the nestopia and melonds bumps reverted and fixes for stella and yabause all addons build now for RPi4

**Comment by HiassofT** [comment]
re-synced with kodi-game repo to get a proper nestopia githash and added desmume, melonds and nestopia fixes (mainly ported from @5schatten repo). All game addons are now up to date and build for RPi4

**Comment by HiassofT** [comment]
I've marked game.libretro.melonds as PKG_ARCH="none" as libretro-melonds is built with OpenGL support by default and retroplayer doesn't support that.

I've kept the basic build changes for libretro-desmume though it's not built in LE (because game.libretro.desmume is PKG_ARCH="none" for the same reason - no OpenGL).

All game addons now built fine for RPi4 and Generic

**Pull request merged**
