### PR TITLE
docker: rename docker to moby

### PR DESCRIPTION
**Pull request by InuSasha**

### CODE REVIEW

**Comment by InuSasha** [comment]
added changelog entry and drop ADDON variables from moby package.mk

**Comment by lrusak** [comment]
I'm ok with this as it will continue to be named `service.system.docker`

**Comment by awiouy** [comment]
Why not just change PKG_ADDON_NAME, PKG_LONGDESC and PKG_SHORTDESC, which are purely cosmetic, to Moby? Is there such a thing as a copyrighted/trademarked file/service name?

**Comment by InuSasha** [comment]
When i had correct understand, was docker will divided into several parts/modules.
The bundle will called docker, but the parts will get other names, of cause.
Moby is only one part.
So the addon description should not change, but in moby package i will change it.

**Comment by anoma** [comment]
This absolutely will need to happen but in my opinion this is not the time for us to be trailblazing. Accept and park until the world understands what the Moby distinction is and the dust has settled on the final re-brand (or we run the risk of having to do this more than once).

**Comment by piotrasd** [comment]
for now others didnt make move to change name, here i mean companies like Synology, QNAP, LimeTech (unraid) etc.

**Comment by awiouy** [comment]
Sorry, I might be thick, but I still do not get why the docker package has to be split into a moby and a docker packages, especially since a docker package remains. Why not simply change the name displayed in the Kodi user interface, via PKG_ADDON_NAME, PKG_LONGDESC and PKG_SHORTDESC.

**Comment by lrusak** [comment]
@awiouy we need to separate the packages so we can continue to use the same add-on name which is service.system.docker. If that were to change then people would lose their data. It's how our build system works by taking the PKG_NAME and the PKG_SECTION

**Comment by awiouy** [comment]
@lrusak I am aware of that, adding addons to LibreELEC is my trade. I still do not understand the rationale behind the split/rename. The addon can be renamed in the Kodi user interface without changing PKG_NAME or PKG_SECTION. Additional components can be shipped within the package or added from separate packages. Could anyone here explain the purpose of the moby package, apart from creating a useless matryoshka?

**Comment by InuSasha** [comment]
believe not needed after  #1796

**Comment by lrusak** [comment]
@InuSasha I'd still like to do it this way.

**Comment by chewitt** [comment]
I'd prefer to leave this open so the topic isn't forgotten about, regardless of what form we commit something in at a later stage. @InuSasha we can very slow at this stuff sometimes :)

**Comment by InuSasha** [comment]
rebase to current master, to solve merge conflicts

**Pull request merged**
