### PR TITLE
build: start using .libreelec-unpack

### PR DESCRIPTION
**Pull request by MilhouseVH**
NOTE: This will require a clean build! Best to include next time we bump something which requires a clean build, such as gcc or similar.

### CODE REVIEW

**Comment by escalade** [comment]
Why not simply .unpack? :)

**Comment by MilhouseVH** [comment]
> Why not simply .unpack?

Provided it doesn't conflict with any existing package directory - I feel this is going to be far less likely with a `.libreelec-` prefix (and which is presumably why it currently uses the `.openelec-` prefix)

**Comment by chewitt** [comment]
Just a heads up that I plan to merge this in the next couple of days before clean building v7.90.003

**Comment by MilhouseVH** [comment]
Merging this at the same time as #433 would be a good idea.

**Pull request merged**
