### PR TITLE
lirc: update to 0.9.4

### PR DESCRIPTION
**Pull request by lrusak**
I decided to split this out of #428 as it is a large change.

It builds ok, but needs runtime testing.

### CODE REVIEW

**Comment by lrusak** [comment]
@stefansaraev would you mind having a look at this? specifically the second commit.

the new version of lirc splits out the uinput mode into a sperate binary `lircd-uinput` which has to be run along side `lircd`, this seems to be the best method to control both of them unless you have a better idea.

`systemctl status` shows 
```
             ├─system-lircd.slice
             │ ├─lircd@usb-hiddev0:macmini:lircd.conf.service
             │ │ └─559 /usr/sbin/lircd --uinput --driver=macmini --device=/dev/usb/hiddev0 --output=/run/lirc/lircd-usb-hiddev0 --pidfile=/run/lirc/lircd-usb-hiddev0.pid /etc/lirc/lircd.conf
             │ └─lircd-uinput@usb-hiddev0.service
             │   └─644 /usr/sbin/lircd-uinput /run/lirc/lircd-usb-hiddev0
```

**Comment by stefansaraev** [comment]
I dont use lirc for years now, but your change looks ok to me.

**Comment by lrusak** [comment]
@MilhouseVH would you mind making a test build for this again? seems the issue was that lircd was running on systems where it wasn't supposed to.

**Comment by MilhouseVH** [comment]
Couple of positive reports in the test build #0617x:

http://forum.kodi.tv/showthread.php?tid=269815&pid=2360310#pid2360310
http://forum.kodi.tv/showthread.php?tid=269815&pid=2360516#pid2360516

**Comment by HiassofT** [comment]
Here's the summary of last night's tests (on RPi with GPIO receiver and lirc-rpi kernelmodule) so they don't get lost:
* lircd --uinput (which is now deprecated) seems to be working fine
* lircd-uinput doesn't, keys are missing and it can get stuck - sending out endless keypress input events

Kodi receives both the "lircd --uinput" events, via eventlircd as LIRC input and the "lircd-uinput" events, the latter as linux input events, handled as "Keyboard".

When lircd-uinput manages to translate a key fine we get double keypresses in kodi. But if it gets stuck (sending out repeated events that aren't there) navigation in kodi is impossible.

I think it might be best to revert the lircd bump for now.

Using lircd-uinput together with "lircd" (latter without --uinput) seems to be the recommended way, but something doesn't work there.

Sure, we could use the deprecated "lircd --uinput" and make sure "lircd-uinput" doesn't get started but then IMHO  this somewhat defeats the purpose of the lircd bump.

**Pull request merged**
