### PR TITLE
buildsystem: cleanup password hashing; drop busybox:host

### PR DESCRIPTION
**Pull request by antonlacon**
This PR does three things:

Replace busybox:host's cryptpw password hashing with python's crypt module. Python was chosen as the replacement as it's already required in checkdeps.

Moves password hashing into `config/function`'s `add_user()`. This means supplying `add_user()` with the password, like the comment for the function says, rather than the password hash, like needs to be generated now, and then passed to `add_user()`.

`arch` and `cryptpw` are the only commands built by busybox:host. The need for `cryptpw` is removed, and I found no users for `arch`. `arch` is equivalent to `uname -m`, and was added by accepting busybox's default suggestions in an update PR (#2504). This eliminates the need for busybox:host.

### CODE REVIEW

**Comment by heitbaum** [comment]
Hi @antonlacon (just on the password thing - that mkpasswd is also there under proftpd, something we should include/add an action to use the python crypt for this too?)

```
$ git grep whois
packages/addons/addon-depends/whois/package.mk:PKG_NAME="whois"
packages/addons/addon-depends/whois/package.mk:PKG_URL="https://github.com/rfc1036/whois/archive/v${PKG_VERSION}.tar.gz"
packages/addons/addon-depends/whois/package.mk:PKG_LONGDESC="A tool that queries the whois directory service for information pertaining to a particular domain name."
packages/addons/service/proftpd/package.mk:PKG_DEPENDS_TARGET="toolchain libcap openssl ncurses pcre whois"
packages/addons/service/proftpd/package.mk:    cp $(get_install_dir whois)/usr/bin/mkpasswd ${ADDON_BUILD}/${PKG_ADDON_ID}/bin
```

**Comment by antonlacon** [comment]
Any chance you're using proftpd to test? https://github.com/antonlacon/LibreELEC.tv/commits/proftpd-passwd should have the necessary parts for such a change (though not the changelog bump, whois package dropped, etc). 

Alternatively, `openssl passwd` could be used, but I don't know if it has its own salt generator so it may need some of the prior solution too.

**Comment by CvH** [comment]
gtg ?

**Comment by antonlacon** [comment]
Yes.

**Review by CvH — APPROVED** [review]

**Comment by howie-f** [comment]
apparently this breaks building LE master on Debian 11 Bullseye, but not on Arch/Ubuntu 20.04 (confirmed working by @CvH and @jernejsk)

error message:
```
INSTALL      busybox (target)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fhw/LE/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/lib/python3.8/crypt.py",
     line 6, in <module>
    import _crypt
ImportError: /home/fhw/LE/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/...
        ...toolchain/lib/python3.8/lib-dynload/...
        ..._crypt.cpython-38-x86_64-linux-gnu.so: undefined symbol: crypt_r
FAILURE: scripts/install busybox:target during post_install (package.mk)
*********** FAILED COMMAND ***********
PASSWORD=$(python -c "import crypt; print(crypt.crypt('$PASSWORD', crypt.mksalt(crypt.METHOD_SHA512)))")
**************************************
FAILURE: scripts/install busybox:target has failed!
```

i thought, as Bullseye ships both Python-**2.7.18** and Python-**3.9.2** binaries by default, this could be the potential fix:
```
--- a/config/functions
+++ b/config/functions
@@ -1497,7 +1497,7 @@ add_user() {
   if [ "$PASSWORD" = "x" ]; then
     PASSWORD="*"
   else
-    PASSWORD=$(python -c "import crypt; print(crypt.crypt('$PASSWORD', crypt.mksalt(crypt.METHOD_SHA512)))")
+    PASSWORD=$(python3 -c "import crypt; print(crypt.crypt('$PASSWORD', crypt.mksalt(crypt.METHOD_SHA512)))")
```

however the error is the same, only reverting both commits of this pr fixes it. means reintroducing `busybox:host` and using `${TOOLCHAIN}/bin/cryptpw` for password generation.

@antonlacon any ideas?

**Comment by antonlacon** [comment]
Would you try replacing the call to `python` with `/usr/bin/env python3`? It was my expectation to have it use the host distro's python3 (not python3:host), and this should get back to that.

**Comment by howie-f** [comment]
sorry doesn't change anything 
```
ImportError: /home/fhw/LE/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/lib/python3.8/lib-dynload/_crypt.cpython-38-x86_64-linux-gnu.so: undefined symbol: crypt_r
FAILURE: scripts/install busybox:target during post_install (package.mk)
*********** FAILED COMMAND ***********
PASSWORD=$(/usr/bin/env python3 -c "import crypt; print(crypt.crypt('$PASSWORD', crypt.mksalt(crypt.METHOD_SHA512)))")
**************************************
FAILURE: scripts/install busybox:target has failed!
```

**Pull request merged**
