### PR TITLE
systemd: update to 247.3

### PR DESCRIPTION
**Pull request by heitbaum**
update 247 to 247.3
changelog: https://github.com/systemd/systemd-stable/commits/v247-stable
use systemd-stable source as it includes backports of patches from systemd
git to stable distributions

### CODE REVIEW

**Review by bantilan — APPROVED** [review]
No errors and working on RPI 3 and Tinker board

**Review by lrusak — COMMENTED** [review]
I'm not really sure about the need to change to the `systemd-stable` line. Unless the systemd line is explicitly marked as unstable or for testing then I don't really see the reason to change.

**Comment by CvH** [comment]
there is no 247.2 at the current git (@heitbaum there is now even a 247.3 release), the maintained bugifxes are at `systemd/systemd-stable`, from my understanding we should always use systemd-stable instead of the dev-tree `systemd/systemd`
@HiassofT objections ?

**Comment by heitbaum** [comment]
@CvH - I’m running 247.3 in my dev branch, I can update the PR. From looking Ubuntu, alt, ... all use systemd-stable.

**Comment by HiassofT** [comment]
No objections from my side, I've been testing with this PR the last 10 days or so. There weren't really important fixes in 247.2 but it also wouldn't hurt to include them.

@heitbaum can you update to 247.3?

**Comment by heitbaum** [comment]
> No objections from my side, I've been testing with this PR the last 10 days or so. There weren't really important fixes in 247.2 but it also wouldn't hurt to include them.
> 
> @heitbaum can you update to 247.3?

Done

**Review by HiassofT — APPROVED** [review]

**Pull request merged**
