### PR TITLE
glib: update to 2.81.2

### PR DESCRIPTION
**Pull request by heitbaum**
- glib: update to 2.81.2

### CODE REVIEW

**Comment by vpeter4** [comment]
What is the reason in glib to require those new packages?

**Comment by jernejsk** [comment]
Python world is moving to new build system. With #9218 in, this PR will become just glib update.

**Comment by jernejsk** [comment]
and yeah, glib uses python and python install commands during build process

**Comment by vpeter4** [comment]
Yes, this PR just have too much packages then. And order of applying few PR is then important. Looks messy right now.

**Comment by vpeter4** [comment]
My point is that this PR is named `glib: update to 2.81.2` but PR also includes few new packages which has nothing to with glib bump.

**Comment by jernejsk** [comment]
They do, it's not possible to build new glib without them.

**Comment by vpeter4** [comment]
Ok, let's be more clear because PR itself is not.
Glib 2.81.2 builds on current master without any extra package. But after https://github.com/LibreELEC/LibreELEC.tv/pull/9218 those new packages are needed. Correct?

**Comment by jernejsk** [comment]
Hm, I'm sure I saw packaging as dependency for glib at one point. Maybe older version.

**Comment by heitbaum** [comment]
> What is the reason in glib to require those new packages?

This is very draft and shared whilst moving towards Python 3.12, is not intended to go in as-is. Will be dependent on the Python changes first.

**Comment by vpeter4** [comment]
Then write this info in description.

**Comment by heitbaum** [comment]
@jernejsk tested the build of glib 2.79.0 (which needs the packaging python package) using your 3 packages and using Python 3.11 - all worked as expected on generic,arm,aarch64. So a good test

**Review by jernejsk — APPROVED** [review]

**Comment by vpeter4** [comment]
Now whole useless conversation should be deleted.

**Pull request merged**
