### PR TITLE
busybox: remove cron support

### PR DESCRIPTION
**Pull request by lrusak**
we have systemd so if people need cron-like support they can just use a systemd timer instead.

### CODE REVIEW

**Comment by lrusak** [comment]
systemd timers are much more simple. For example, here is a systemd timer for running fstrim once a week
```
[Unit]
Description=Discard unused blocks once a week

[Timer]
OnCalendar=weekly
AccuracySec=1h
Persistent=true

[Install]
WantedBy=timers.target
```

save that as `/storage/.config/systemd/system/fstrim.timer`
then run `systemd enable fstrim.timer`

then you can check the status of the unit using normal systemd symantics

**Comment by HiassofT** [comment]
Systemd timers are nice if you benefit from the additional features.

But until core cron features like MAILTO are missing (or did hte systemd guys implement that yet?) most people - like me - will stick to cron.

Adding a single line to a crontab and automatically getting an email notification if the script output something to stdout/stderr is a core functionality.

Sure, we don't need/have that in LE, but unless that's implemented I don't see many people wanting to deal with systemd timers (on any platform) if there are working alternatives they are familiar with.

So, until cron is unmaintainable, we should keep it.

**Comment by lrusak** [comment]
> Adding a single line to a crontab and automatically getting an email notification if the script output something to stdout/stderr is a core functionality.

since when did we support MAILTO on LE??

**Comment by InuSasha** [comment]
i found this interesting repo: https://github.com/systemd-cron/systemd-cron-next
It is packaged in arch-linux (https://aur.archlinux.org/packages/systemd-cron-next/)

**Comment by vpeter4** [comment]
Another crazy PR :-)

> adding systemd timer: GOOD
> removing cron: BAD

**Comment by escalade** [comment]
This is just crippling LE for no reason. How is a systemd timer any easier than a cronjob? Most people who use cron remember the syntax, I doubt any of you remember all the keywords and sections needed to make a systemd timer without a google search. How large is the busybox applet, 5 kilobytes?

LE needs more functionality, not less. Just my 2 cents.

**Comment by Raybuntu** [comment]
Last time I/we checked (I think it was with milhouse) was that systemd-timers (it was for fstrim) didn't work for systems without RTC.

**Comment by MilhouseVH** [comment]
@Raybuntu it was #2402, and we haven't fixed the remaining issue which is that systems without a RTC are not able to correctly calculate their post-boot next trigger date/time, although to be honest I've no idea if cron is any better in this regard, but yeah, we do have potential issues with systemd timers. For frequent systemd timers that trigger at regular intervals throughout the day (every hour, every 15 mins etc.) there's unlikely to be a problem, but timers based on intervals greater than a day (ie. every week) are likely to have issues, particularly if the device is rebooted fairly regularly...

Regarding this PR, I think that since cron works (as far as we know) and is low maintenance, I'd vote for keeping it as it offers a simple alternative to systemd. Horses for courses, and all that - choose which method you prefer and/or find the least technically challenging. Perhaps when we stop running everything as root and switch to a user-based implementation we might want to revisit this.

Oh and guys... just a general request - can we tone down the snarky comments when responding to PRs that offend you... we welcome the criticism, so long as it's polite & constructive! Thanks. :)

**Comment by vpeter4** [comment]
I assume last sentence was meant to me: None of PRs offend me. But when I see such crazy things I see dark only :) How can someone even think on removing cron is beyond me. It is such a standard thing. Sure, add systemd timers and prefer it on every answer. But you need to educate users first. Even if you have nice wiki page about functionality there will still be posts "how can I do that".

**Comment by escalade** [comment]
I can understand the desire to clean up the options file / makefile though, cron doesn't seem like a feature that needs to be on/off for certain builds.

**Comment by vpeter4** [comment]
Finally some sense :)

**Pull request closed without merging**
