### PR TITLE
gcc: update to 13.1.0

### PR DESCRIPTION
**Pull request by heitbaum**
Packages that need,to,be updated before this PR can be moved forward
- ~~mariadb - patch to be included in 10.11.3~~
  - ~~https://jira.mariadb.org/browse/MDEV-31057~~
  - ~~https://github.com/MariaDB/server/commit/cf4a16b5557be5fb3568c1de0d6cc0a18291afc9~~
  - These patches are included in the #7826 10.11.3 release
- media-driver - not yet incorporated
  - https://github.com/intel/media-driver/pull/1648
- nss - patch already in nss master

other minors that the plan is to go with the patch:
- https://github.com/warmcat/libwebsockets/pull/2824
- https://github.com/badaix/snapcast/pull/1124 (just waiting on a release)
- Kodi addons (all have been accepted into master)
- https://github.com/NilsBrause/waylandpp/pull/71

All gcc-13 “build error” fixes are upstream patches (or have been submitted to upstream)

Build testing with all target .img (x86_64/arm/aarch64) is working (including Wayland)
All addons build correctly (ARMv7,ARMv8.arm,ARMv8.aarch64,Generic,Generic-legacy)
- No workarounds using -Wno-error have been needed

### Reference
- #7766 includes the fix for inputstream.adaptive

### CODE REVIEW

**Comment by lrusak** [comment]
If it's not possible to use GCC 13 soonish It would be nice if this could be split as the build fixes are needed with a host that uses GCC 13 (ie. Fedora 38)

**Comment by heitbaum** [comment]
I’m out at the moment. I’ll squash the Mariadb one. The media-driver/nss ones seems not to be progressing as fast. With the nss and media-driver releases this week. I’m ok to have this merged and I’ll fix as upstream is released.

**Comment by heitbaum** [comment]
> If it's not possible to use GCC 13 soonish It would be nice if this could be split as the build fixes are needed with a host that uses GCC 13 (ie. Fedora 38)

Done. Cleaned up the commits. Would be good to get an upstream inputstream.adaptive release - that will get every thing building with with gcc-13

**Comment by lrusak** [comment]
> > If it's not possible to use GCC 13 soonish It would be nice if this could be split as the build fixes are needed with a host that uses GCC 13 (ie. Fedora 38)
> 
> Done. Cleaned up the commits. Would be good to get an upstream inputstream.adaptive release - that will get every thing building with with gcc-13

Cheers thanks!

**Comment by lrusak** [comment]
If you want to avoid breaking the bisect you may want to reorder the commits so the gcc-13 bump is the last commit.

**Comment by heitbaum** [comment]
> If you want to avoid breaking the bisect you may want to reorder the commits so the gcc-13 bump is the last commit.

Good call - updated

**Pull request merged**
