### PR TITLE
open-iscsi: fix build with gcc-14

### PR DESCRIPTION
**Pull request by heitbaum**
patches are from upstream

[https://github.com/open-iscsi/open-iscsi 69](https://github.com/open-iscsi/open-iscsi/pull/69)

### CODE REVIEW

**Comment by CvH** [comment]
didn't we want to drop iscsi at LE13 ? (I am not sure tbh)

**Comment by heitbaum** [comment]
> didn't we want to drop iscsi at LE13 ? (I am not sure tbh)

Maybe. I’ll have another look at it now that there is a bunch of other cleanup done, and if I can easily update it. Happy to support the fixes for the moment, I only pulled the bare minimum (2 commits) forward.

**Comment by CvH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/pull/5015#issuecomment-774652765
ups we "planed" to drop it at LE11 and didn't ship it at all since 2 years https://github.com/LibreELEC/LibreELEC.tv/pull/6356

So the amount of complains is around 1 at the forum so i would say keep it at the build system and d not touch it ?

**Review by mglae — APPROVED** [review]

**Comment by mglae** [comment]
Working fine together with #9283

**Pull request merged**
