### PR TITLE
u-boot: Odroid-C2 Adjust dvfs table for high cpu frequency sets

### PR DESCRIPTION
**Pull request by wrxtasy**
https://github.com/hardkernel/u-boot/commit/095fdbe2906dd7d1d208a8e33b70171dc2d8bf16
Allows stable CPU Overclocking up to 1.752GHz

CPU Overclocking is user adjustable via the boot.ini file found on the SD card:
https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Amlogic/devices/Odroid_C2/bootloader/boot.ini#L19

### CODE REVIEW

**Comment by Gizmo-Ger** [comment]
Incorrect checksum calculated on downloaded file: got 25ee7c8208d8a97c831b8dd9222ce8984f4a0b8f95dabf9d513c130d04aa05b5, wanted 0d05829e07e226d1acbc6b23ff038d6c92fa3ed738ddc28703d51987c0fab3bb

**Comment by chewitt** [comment]
@wrxtasy can you check and PR pls

**Comment by CvH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/pull/2641 hash wasn't updated at bump

**Comment by wrxtasy** [comment]
Thx. CvH

**Pull request merged**
