### PR TITLE
[Allwinner,Generic,Rockchip] linux: Update to 5.10.61

### PR DESCRIPTION
**Pull request by heitbaum**
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.48
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.49
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.50
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.51
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.52
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.53
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.54
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.55
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.56
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.57
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.58
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.59
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.60
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.61

5.10.48 - 6 patches
5.10.49 - 6 patches
5.10.50 - 598 patches
5.10.51 - 212 patches
5.10.52 - 243 patches
5.10.53 - 123 patches
5.10.54 - 168 patches
5.10.55 - 24 patches
5.10.56 - 67 patches
5.10.57 - 30 patches 
5.10.58 - 135 patches 
5.10.59 - 19 patches 
5.10.60 - 98 patches 
5.10.61 - 98 patches 

log - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-5.10.y

```
5.10.61 Build tested on all of:
```

```
PROJECT=Allwinner ARCH=arm DEVICE=H6 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H3 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX6 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX8 s/build linux
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
PROJECT=Generic ARCH=x86_64 s/build linux
```

Not run tested yet
- Samsung and Qualcomm options **have been dropped** from 5.10.61 before pulled.

### CODE REVIEW

**Review by heitbaum — COMMENTED** [review]
@knaerzche could you have a look at this a62437e1d98ea720e38387b1cafef7e879032b7e. I have removed all of the usb3 dwc patches - the upstreamed patch does not include all of yours or Peter's patch. But will need to be refactored if we are to pull 5.10.51 into LE1x. Thanks

**Comment by knaerzche** [comment]
@heitbaum 
Yes: upstream decided to not add the (required) phy driver yet for RK3328 (yet) - its a bit tricky to rebase: You'll basically have to add the `usb3phy: usb3-phy@ff470000 ` node and add the `usb-phy = <&usb3phy_utmi>, <&usb3phy_pipe>;` to the (now existiing) `usbdrd3: usb@ff600000` in rk3328.dtsi.
Enablements of usb3 in the board devicetrees have to be checked if they are allready existend  by now (phy enablements are not existend in any)... I can do that end of next week (on vacation now). BTW: I hope we do 5.13 or later in LE 11 :) 

@jernejsk maybe  we should rename `V4L2_HEVC_PPS_FLAG_DEPENDENT_SLICE_SEGMENT` to `V4L2_HEVC_PPS_FLAG_DEPENDENT_SLICE_SEGMENT_ENABLED` in ffmpeg patches too.

**Comment by jernejsk** [comment]
Yes, ffmpeg must follow kernel changes.

**Comment by jernejsk** [comment]
@heitbaum can you please pick this commit? https://github.com/jernejsk/LibreELEC.tv/commit/cb0bdc133931f7a4b2300dbb5a3dca5bb6245e9f
In grand scheme of things, it won't change anything. It will just align HEVC API macro name with mainline.

**Comment by knaerzche** [comment]
@heitbaum  what has been renamed upstream is `V4L2_HEVC_PPS_FLAG_DEPENDENT_SLICE_SEGMENT` to `V4L2_HEVC_PPS_FLAG_DEPENDENT_SLICE_SEGMENT_ENABLED`.
You also removed also the patches which add `V4L2_HEVC_SLICE_PARAMS_FLAG_DEPENDENT_SLICE_SEGMENT` for both RK and AW ;) You should restore the second removed hunk in projects/Rockchip/patches/linux/default/linux-2001-v4l-wip-rkvdec-hevc.patch in https://github.com/LibreELEC/LibreELEC.tv/pull/5499/commits/2fc4e7f8a2124660e7b5a9fdefbccff31ca679d4 and the projects/Allwinner/patches/linux/0058-media-cedrus-wip-hevc-dependent-flag.patch in https://github.com/LibreELEC/LibreELEC.tv/pull/5499/commits/787248188ba29fa8b38cde8235a3405719e36fdc

Will do RK3328 dts changes, when I'm back home.

**Comment by heitbaum** [comment]
> nevermind: This flag has been pushed to stable also - sorry, wasn't aware.

All good. Been pretty careful about just cutting chunks … (sure I’ll miss some) always great to QA 👍. I have a review to do on projects/NXP/devices/iMX8/patches/linux/0001-drm-bridge-mhdp-Add-cdns-mhdp-driver-bridge-driver.patch where I have had to hack out patches, (rock chip drm ones) but I haven’t had the time to go through the one by one :-) 1722 lines … been a bit busy this week, so just been doing the tick along stuff. Will see what the weekend brings. No lockdown this weekend at least.

**Comment by CvH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/pull/5546#issuecomment-896121902

guess we directly bump to 5.13/14 in master and just pull this to LE10 (after we released 10.0)

**Comment by mglae** [comment]
Generic bump to 5.10.58 or https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.10.58&id=11891adab23daa7e08a8e0c25bebfba9c5b5a579 is required to get Gemini Lake working.

**Comment by heitbaum** [comment]
My plan was to update to latest 5.10 as suggested (fLE10) into LE10 branch. I'll add 5.10.59 later today.
Still need to fix https://github.com/LibreELEC/LibreELEC.tv/pull/5499#pullrequestreview-709491715 before this is ready. 

Regarding LE11 - I would like to go straight to 5.14 - I'm running rc6 as daily on TGL and the N2+.

**Comment by jernejsk** [comment]
> Regarding LE11 - I would like to go straight to 5.14 - I'm running rc6 as daily on TGL and the N2+.

Can you make a draft PR? That way I could adapt AW patches and avoid doing double work with common patches. I have a branch in my local repo with 5.13.

**Comment by heitbaum** [comment]
> > Regarding LE11 - I would like to go straight to 5.14 - I'm running rc6 as daily on TGL and the N2+.
> 
> Can you make a draft PR? That way I could adapt AW patches and avoid doing double work with common patches. I have a branch in my local repo with 5.13.

Thought the same as I finished up last night, will do today.

**Comment by heitbaum** [comment]
> Yes: upstream decided to not add the (required) phy driver yet for RK3328 (yet) - its a bit tricky to rebase: You'll basically have to add the `usb3phy: usb3-phy@ff470000 ` node and add the `usb-phy = <&usb3phy_utmi>, <&usb3phy_pipe>;` to the (now existiing) `usbdrd3: usb@ff600000` in rk3328.dtsi.
> Enablements of usb3 in the board devicetrees have to be checked if they are allready existend by now (phy enablements are not existend in any)...

we have agreed to leave this https://github.com/LibreELEC/LibreELEC.tv/commit/a62437e1d98ea720e38387b1cafef7e879032b7e patch out of libreelec:libreelec-10.0 branch. Will be reviewed at a later date.

**Review by CvH — APPROVED** [review]

**Pull request merged**
