### PR TITLE
buildsystem: adjust for python crypt module deprecation

### PR DESCRIPTION
**Pull request by antonlacon**
This is to resolve the issues with python's crypt deprecation shown in #7160. This is a continuation of #5736. I apparently can't reopen it once closed if I force push the branch after. Continuing to use python for hash generation now looks something like:
```
#!/usr/bin/env python

import base64
import hashlib
import os

pw_string = 'libreelec'
# 16 character salt
salt = base64.b64encode(os.urandom(12))
# algo, password, salt, rounds, digest length
password = base64.b64encode(hashlib.pbkdf2_hmac('sha512', bytes(pw_string, 'utf-8'), salt, 200000, 64))
# = is a padding character in base64
print(f'$6${salt.decode("utf-8")}${password.decode("utf-8").rstrip("=")}')
```

I'm not excited about embedding that into a bash script and hashlib.pbkdf2_hmac is itself deprecated and will be unavailable if python is not built with openssl. While we enable openssl in python, I don't know the benefit of using python over openssl directly at this point.

Added openssl:host to toolchain depends as it's a really a depend of config/function's `add_user` so I don't believe it should be added to busybox's deps directly.

Draft as I haven't tested the proftpd changes.

### CODE REVIEW

**Comment by heitbaum** [comment]
Unit test looks right. Random salt 👍.
```
docker@1682a9d2d5f8:/var/media/DATA/home-rudi/LibreELEC.tv$ openssl passwd -6 gh
$6$ltjnTMPr5tVS0kU0$kyGvzYpjl6zPAF.Ux3XX/PlZ8bd2Ftd74ujogqMy0kcGleZoLaekjrlwDZgIoUmBeMsSCEr/1GOo5RJPoNkI81
docker@1682a9d2d5f8:/var/media/DATA/home-rudi/LibreELEC.tv$ openssl passwd -6 gh
$6$aSU1q9Qcqqiey/AE$NyjgSyahs8OD3/NNNpsQHmcI7HJf4KGucyZDp8sVe7RgQ4kwMwYyUts8f/vuYnhUFQGHwGNFWdGzLlbMlvH2J.
docker@1682a9d2d5f8:/var/media/DATA/home-rudi/LibreELEC.tv$ openssl passwd -6 gh
$6$iadPvLzIZiIfP4CB$OFkFD2KOTWUAKS66s.RR1BL2wf58i2X5LobtgPqT3xDlhLTdgqrvsmJLzBgpQMYjRAIhl3USo1C1Obc.zUTGc/
```

**Comment by antonlacon** [comment]
Ok for wider testing.

**Comment by lrusak** [comment]
Just a note that the second commit has a spelling error.

**Comment by heitbaum** [comment]
> Ok for wider testing.

Please change “conver” to “convert” in commit message.

**Review by CvH — APPROVED** [review]

**Pull request merged**
