### PR TITLE
WC:Update bootloader/logo and recovery images from 2017/01/23 OTA

### PR DESCRIPTION
**Pull request by Ntemis**
You can push the update to other branches too

### CODE REVIEW

**Comment by chewitt** [comment]
@Ntemis can you please explain what exactly has been-changed? - the img blobs don't show much detail :)

**Comment by codesnake** [comment]
Don't use bootloader built for Android, LE NAND installs will stop booting.

**Comment by Ntemis** [comment]
oh, didn't know this was a special build for LE
So what happens when Users use **2017/01/23 Android OTA on nand** and dual boot LE from SDcard then decide to **install LE to nand**?

**Comment by codesnake** [comment]
Nothing bad will happen, LE in NAND will work as usual.

**Comment by Ntemis** [comment]
I lost you here, you said LE NAND installs will be unable to boot using this new bootloader yet using this bootloader and installing LE on nand nothing bad will happen.

**Comment by codesnake** [comment]
When you install LE into NAND it overwrites the bootloader.

**Comment by Ntemis** [comment]
Clear

**Pull request closed without merging**
