### PR TITLE
build: Size optimization option

### PR DESCRIPTION
**Pull request by ozolli**
Adds a build size optimization option:
- When set to "yes" (default) compile with -Os/MinSizeRel
- When set to "no" compile with -O2/Release

Tested on Generic and working well on both settings.
Size optimized version is exactly the same size as LE master version.
I may have missed something, made mistakes so am all ears from you!

### CODE REVIEW

**Comment by escalade** [comment]
I think you missed this: 4df4ea789c44137f90c8c804888649cd35ae5e7c and this: 107d60aebc6ae0620fcaabf91a05768ad21f75c4

I've been using -O2 in my builds for a long time and have come across two issues. One is that Kodi will segfault on ARM when compiled with -O2, the other is that the Kodi youtube addon will fail with an urllib2 error. I haven't been able to narrow down the latter to a specific package.

**Comment by ozolli** [comment]
@escalade : Ok so I close it.

**Comment by ozolli** [comment]
FYI @escalade I don't have this urllib2 error on the YT addon with the -O2 optimization. You may try again to see if it has changed?

**Comment by escalade** [comment]
This was quite recently and I follow master closely. Could be due to some of my mods in combination, but point being that -Os is probably the safest choice for a standard build as there may be the odd issue with -O2.

**Pull request closed without merging**
