### PR TITLE
kodi: switch RPi4 to use vendor tree

### PR DESCRIPTION
**Pull request by HiassofT**
Source kodi with RPi4 patches from https://github.com/popcornmix/xbmc/tree/leia_pi4 instead of having local patches in the LE tree.

Dealing with the tree conflicts between LE's kodi and ffmpeg patches and the leia_pi4 tree was a bit tricky.

For kodi's conflicting "use alsa and pulse together" I chose to move it to the kodi vendor patch dir and use a version rebased onto the leia_pi4 branch for RPi4.

For ffmpeg's conflicting "Add-common-V4L2-request-API-code" from LE and the HEVC patch from the leia_pi4 branch I chose a different approach, adding 2 patches to temporarily revert the conflicting ffmpeg changes and adding them back after applying the (device specific) HEVC patch.

We should rethink how we deal with all these ffmpeg downstream patches and eg make v4l2 request api and rkmpp conditional, moved into separate patch dirs and only apply them if they are needed. Doing this in this PR is a bit out of scope and I'm not too familiar which project/device/... actually needs which patches.

### CODE REVIEW

**Comment by Kwiboo** [comment]
`v4l2 request api`-patches is needed for mainline projects, at least on Allwinner, Rockchip and any platform with Hantro decoder (iMX8), I guess the Raspberry Pi 4 HEVC decoder may end up as an stateful decoder.
It is not possible to fully upstream this decoder until kernel v4l2 controls is out of staging.

`rkmppdec`-patches can be removed once `master` have fully transisioned into mainline only for Rockchip.

**Comment by HiassofT** [comment]
@Kwiboo thanks a lot for the feedback!

From a quick glance current situation in master looks identical to the one in LE9.2, only Allwinner makes use of v4l2-request API and only RK uses rkmpp - for all other projects these options are explicitly disabled.

Situation in master might change soon and other projects might use request API as well, and some of those might be backported/added to LE9.x as well, and at some point master will use newer ffmpeg while 9.x will be using 4.something-Leia.

As we probably need to maintain LE9.x with Kodi 18 for a year (or even longer) it makes sense to think about how to keep the patchsets maintainable. And I think separating them into disjoint feature sets makes sense as that will reduce the chance of conflicts and we don't need to explicitly disable the features added by the patchsets if we're not using them.

eg, in case of request patches:
```
if [ "$PROJECT" = "Allwinner" ]; then
  PKG_PATCH_DIRS+=" v4l2-request-api"
  PKG_DEPENDS_TARGET="$PKG_DEPENDS_TARGET libdrm systemd" # systemd is needed for libudev
  PKG_FFMPEG_V4L2_REQUEST="--enable-v4l2-request --enable-libudev --enable-libdrm"
fi
```

I should then probably handle the RPi HEVC patches in a similar way, after thinking about it I'm not convinced using device specific patches (where I needed to duplicate/symlink the patch for RPi,RPi2,Slice,Slice3) was such a good idea - PKG_PATCH_DIRS looks more elegant to me.

If we go that way I'd like to leave the refactoring to the one's who added the patchsets (eg @Kwiboo and @jernejsk) - for me it's not 100% clear which patch belong to which featureset or should be kept global (eg ffmpeg-95.0001-avutil-add-av_buffer_pool_reclaim.patch was added via the request api commit)

**Comment by Kwiboo** [comment]
I agree using different "feature" patch folders could be a way forward. I am planning on finishing the mainline Rockchip pull request this weekend and then the situation will be different in master (both Allwinner and Rockchip will require v4l2 request api).
In the long run (once hwaccel has been merged upstream) the v4l2 request api feature should always be enabled or auto detected.

ffmpeg-95.0001-avutil-add-av_buffer_pool_reclaim.patch adds a function that is used by the v4l2 request api hwaccel and should be seen as part of that patchset.

**Comment by HiassofT** [comment]
thanks for the info! I agree, for master we'll need v4l2 request api patches for (almost?) all projects. Keeping them separate shouldn't do any harm though, when we bump ffmpeg to a version with request api support we could simply drop the whole patch folder.

For LE9.x situation will be different, we quite certainly won't be using v4l2 on RPi/RPi2 (and probably also Generic), we may think about switching RPi4 to it though when we think it's mature enough and wider testing via LE9.x is desired - that's stuff for the future though.

**Comment by HiassofT** [comment]
added WIP tag, currently thinking about and testing other ways to handle the ffmpeg patches. Also we might get some updated kodi versions the next couple of days, better batch them up than merge now.

This PR is still good for testing though :-)

**Comment by HiassofT** [comment]
I've pushed a tree with a second version of this PR, based on the ffmpeg patch restructure PR #3619 : https://github.com/HiassofT/LibreELEC.tv/commits/le92-kodi-vendor-rpi4-ffmpeg-restructure

RPi4 HEVC patch can now be taken as-is from tools/depends/target/ffmpeg/pfcd_hevc_optimisations.patch in kodi tree and no work-around patches are needed.

**Comment by HiassofT** [comment]
I've rebased this now onto the ffmpeg patch restructure PR #3619 

Github webui displays the commits in some funny order and scattered the ffmpeg commits between comments. The commit listing of the branch is easier to read: https://github.com/HiassofT/LibreELEC.tv/commits/le92-kodi-vendor-rpi4

**Comment by lrusak** [comment]
I'm just putting this here as an FYI but I really dislike using the vendor trees rather than patch sets. Sure it makes it more convenient to bump versions but in the long run it's more of a problem in my opinion. If we don't actively see the patches that we are including there is no incentive to get rid of them. IMO it's always better to use the vanilla source and patch on top of it so we know exactly what we are including and so onlookers can see what we are doing. Just my 2c.

**Pull request merged**
