### PR TITLE
linux: update to 6.9

### PR DESCRIPTION
**Pull request by heitbaum**
### packages updated
- linux: update to 6.9.2
- xf86-video-nvidia-legacy: patches for linux-6.8 and gcc-14.1
- strace: update to 6.9
- iwlwifi-firmware: update to githash b334878

# 6.9.x mainline kernel update

- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.9
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.9.1
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.9.2

- 6.9.1 - 5 patches
- 6.9.2 - 25 patches

### errors / fixes / issues / regressions / todo
- fixes
  - na 
- todo
  - 1111eaa7fd425e183c2be54d15a5438c0afa84de
- done 
  - RTL8192DU-b65f87820526cd8835c5cac19fd7e659c84e8215 Does not compile
    - https://github.com/lwfinger/rtl8192du/
    - Fixed with add R8712U for WEXT_PRIV required for RTL8192DU
  - nvidia-legacy
  - strace
  - Iwlwifi

### log 
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.9.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.9.y
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/log/
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.9
- https://linux-regtracking.leemhuis.info/regzbot/mainline/
- https://linux-regtracking.leemhuis.info/regzbot/stable/

### 6.9.x Build tested on all of:

```
PROJECT=Allwinner ARCH=aarch64 DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H3 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 s/build linux
PROJECT=Allwinner ARCH=aarch64 DEVICE=R40 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=aarch64 DEVICE=RK3328 s/build linux
PROJECT=Rockchip ARCH=aarch64 DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX6 s/build linux
PROJECT=NXP ARCH=aarch64 DEVICE=iMX8 s/build linux
PROJECT=Qualcomm ARCH=aarch64 DEVICE=Dragonboard s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
```

### 6.9.y Run tested on all of:
- Allwinner H6 - tested - 6.9 - jernejsk
- Allwinner H6 (Tanix TX6) - 6.6.2-rc1 - heitbaum
- Generic Generic (Intel ADL - NUC12) - 6.9.1 - heitbaum
- NXP iMX6 (Cubox-i4Pro) - TBA - heitbaum
- Rockchip RK3399pro (Rock Pi N10) - TBA - heitbaum
- RK all - tested - TBA - knaerzche
- Samsung Exynos (Hardkernel ODROID XU4) - TBA - heitbaum

### CODE REVIEW

**Comment by heitbaum** [comment]
@jernejsk could you please have a look at 1111eaa7fd425e183c2be54d15a5438c0afa84de - im unsuire what to do with the EDID change in the kernel.

**Comment by heitbaum** [comment]
This is ready to go with the exception of 9d186498bd8559de574076278bbe115e5e7c509a which needs to to fixed for Allwinner EDID

**Comment by eldersixpack13** [comment]
> @jernejsk could you please have a look at [1111eaa](https://github.com/LibreELEC/LibreELEC.tv/commit/1111eaa7fd425e183c2be54d15a5438c0afa84de) - im unsure what to do with the EDID change in the kernel.

I hope cheering helps to get 6.9 into LE13:

@jernejsk 
@jernejsk 
@jernejsk 

:-)

Background:
my P-Cores of my Nuc13 CPU are annoyed because they have to do all the work while the E-Cores “_lie lazy on the beach_”

https://www.phoronix.com/news/Linux-6.9-APIC-x86-CPU-Topology

**Comment by jernejsk** [comment]
on it

**Comment by jernejsk** [comment]
@heitbaum Please incorporate changes from https://github.com/LibreELEC/LibreELEC.tv/commit/1fef6020dc4e363a56a5ed4b2bc3571e7c8691a9 With this, Linux 6.9 works fine on H6.

**Comment by heitbaum** [comment]
> @heitbaum Please incorporate changes from [1fef602](https://github.com/LibreELEC/LibreELEC.tv/commit/1fef6020dc4e363a56a5ed4b2bc3571e7c8691a9) With this, Linux 6.9 works fine on H6.

merged your patch in - and removed the "MERGE BLOCK"

**Review by jernejsk — APPROVED** [review]

**Pull request merged**
