### PR TITLE
added one more ident for ZOTAC IR reciver

### PR DESCRIPTION
**Pull request by piotrasd**
please wait before merge, i will test tomorrow

### CODE REVIEW

**Comment by lrusak** [comment]
I imagine you will have to change the diff numbers aswell.

**Comment by piotrasd** [comment]
yes sorry i will fix that

**Comment by lrusak** [comment]
Please rebase on master or wait until 4.8 kernel is merged

**Comment by lrusak** [comment]
@piotrasd please rebase

**Comment by chewitt** [comment]
@piotrasd can you rebase please, then this can be included in v7.90.008

**Comment by piotrasd** [comment]
Hi sorry for delay, maybe after bump kernel to 4.8.3 ?

**Comment by chewitt** [comment]
replaced by #874

**Pull request closed without merging**
