### PR TITLE
Remove 3rd party repositories

### PR DESCRIPTION
**Pull request by HiassofT**
as discussed on slack, questionable addons were added

### CODE REVIEW

**Comment by CvH** [comment]
`questionable addon` was removed from kodinerds and get likely pred to the kodi addons that support/tolerates this kind of stuff

**Comment by lrusak** [comment]
LGTM :+1:

**Comment by Raybuntu** [comment]
Please don't merge that. The Problem was resolved in the Kodinerds repo. People in charge there have always been responsible and try to resolve those issues ASAP. Let's not burn Bridges with other community projects.

As I mentioned on slack. We have more problematic addons in our repo: Oscam.

So either close this PR or update the PR to remove linuxserver.io repo and oscam as well.

There is no reason for this anymore.

**Comment by HiassofT** [comment]
I agree, LibreELEC should stay neutral and not promote the use of select 3rd party repos.

**Comment by HiassofT** [comment]
I've dropped the oscan removal commit that I had added before. This PR only focuses on 3rd party repos

**Comment by CvH** [comment]
I am against it as it solves no problem and impair the current ootb user experience. 

Alternatives: 
- Nerds addon repoinstaller gets accepted at the official kodi repo (guess this won't happen) - also this wouldn't change anything for us
- ls.io repo could be hosted under our account if there is no trust into @aptalca - also there is no real point in keeping the docker addon if this gets removed for no reason as the addons are tailored for our docker addon

Also I am still unsure what this fixes at all - the initial problem was fixed after 5min and was no real problem at all. This kind of addon would be perfectly fine at the official kodi repo too and I guess we won't remove the official repo if these kind of stuff is added there. 

There was no single problem at the ls.io repo at all, also removing the only repo that make use of the Docker addon sounds strange.

But we should decide the one or the other, currently we ship 3 repos from where 2 are clean and were added as kind of recommendation (ofc not installed by default or enabled).
If this pr is merged we finally ship zero clean repos at all (besides our own). 

Sry can't see the improvement. At the moment its all about burning bridges to the community to fix problems we never had.

**Comment by Raybuntu** [comment]
I can no longer support this change as it is clearly a political change with no real benefit or reason. Therefore I have dismissed my review.

**Comment by adamg88** [comment]
I'm neither for nor against this but I'm curious why Oscam and all the emulators are not being removed instead/as well as we are actually hosting these 'questionable' add-ons as opposed to just a repository?

Just seems like hypocrisy and double standards to me.

**Comment by HiassofT** [comment]
@adamg88 we're trying to focus on one thing at a time - in this PR how to deal with 3rd party repos that are not under our control.

Everything else should be handled separately

**Comment by HiassofT** [comment]
Closing for now until final team decision is found how to deal with 3rd party repos

**Pull request closed without merging**
