### PR TITLE
[LE13] Python: Remove usage of distutilscross

### PR DESCRIPTION
**Pull request by jernejsk**
This is first step towards python 3.12.

distutilscross is a distutils overlay, which helps with cross compiling binary parts of python libraries. However, it's not needed for a long time since invoking python in right way takes care for all settings adjusted with distutilscross and more. More importantly, python 3.12 completely dropped support for distutils and this method doesn't work anymore. As an added bonus, binary libraries have right prefix and likely we'll be able drop python_fix_abi() hack in near future (as usual, testing on various platforms is needed.)

Next step will be switching to python 3.12 and last one switch to new building and installation methods of python packages.

@HiassofT Please check if lg-gpio still works as expected.

Marked as "Merge blocked" until more testing is done.

### CODE REVIEW

**Comment by heitbaum** [comment]
Build and run tested Generic today. 
Will do some more builds tonight on other targets.

**Comment by HiassofT** [comment]
thanks, lg-gpio still seems to work fine (there's an unrelated issue with current kernel in gpiozero though)

**Comment by heitbaum** [comment]
Successful build of `PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 make image`
Failed build of `PROJECT=Allwinner ARCH=arm DEVICE=H3 make image`

```
<<< simplejson:target seq 246 <<<
UNPACK      simplejson
BUILD      simplejson (target)
    TOOLCHAIN      manual
Traceback (most recent call last):
  File "/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/simplejson-3.19.3/setup.py", line 10, in <module>
    from distutils.command.build_ext import build_ext
  File "/usr/lib/python3.11/distutils/command/build_ext.py", line 13, in <module>
  File "/usr/lib/python3.11/distutils/sysconfig.py", line 51, in <module>
    'platstdlib': '{base}/Lib',
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/sysconfig.py", line 677, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.11/sysconfig.py", line 538, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_sysconfigdata__linux_arm-linux-gnu'
FAILURE: scripts/build simplejson:target during make_target (package.mk)
*********** FAILED COMMAND ***********
_PYTHON_HOST_PLATFORM="linux-${TARGET_ARCH}" _PYTHON_PROJECT_BASE="$(get_install_dir Python3)" _PYTHON_SYSCONFIGDATA_NAME="_sysconfigdata__linux_${TARGET_ARCH}-linux-gnu" PYTHONPATH="$(get_install_dir Python3)/usr/lib/${PKG_PYTHON_VERSION}" PYTHONNOUSERSITE=1 $@
**************************************
```

**Review by HiassofT — APPROVED** [review]
Thanks, build test for RPi2 and runtime-test on RPi5 look good now

**Review by heitbaum — APPROVED** [review]
Build of H3,H6,RK3288,RK3328,RK3399,iMX6,iMX8,Exynos,Dragonboard all passed now

**Pull request merged**
