### PR TITLE
libXcursor: move to packages/x11/lib and add to sysroot

### PR DESCRIPTION
**Pull request by heitbaum**
Proposal to move libXcursor to library location same as other http://www.X.org libraries.

- also added new glfw3 package - https://www.glfw.org/ (existing glfw - 2.7.9 remains as used by vsxu)
- glfw3 depends on libXcursor

### CODE REVIEW

**Comment by lrusak** [comment]
Why add glfw3?

**Comment by heitbaum** [comment]
For the latest vsxu (currently working though the last bump issues)

**Comment by heitbaum** [comment]
If you suggest that we just bump glfw from 2 to 3  (I’ll refactor to PR) and we deal with only version 3.

packages/graphics/glfw/package.mk:PKG_NAME="glfw"
packages/graphics/glfw/package.mk:PKG_SITE="http://glfw.org"
packages/graphics/glfw/package.mk:PKG_URL="$SOURCEFORGE_SRC/glfw/$PKG_NAME-$PKG_VERSION.tar.gz"
packages/graphics/glfw3/package.mk:PKG_NAME="glfw3"
packages/graphics/glfw3/package.mk:PKG_SITE="http://glfw.org"
packages/graphics/glfw3/package.mk:PKG_URL="$SOURCEFORGE_SRC/glfw/glfw-$PKG_VERSION.tar.gz"
packages/graphics/vsxu/package.mk:PKG_DEPENDS_TARGET="toolchain $OPENGL libX11 glew glfw zlib libpng libjpeg-turbo freetype pulseaudio alsa-lib SDL2"
packages/graphics/vsxu/package.mk:PKG_DEPENDS_CONFIG="glfw"

**Comment by heitbaum** [comment]
Updated PR, removed glfw3. Will bundle glfw3 in vsxu PR

**Comment by lrusak** [comment]
We don't need vsxu anymore as the add-on was dropped here, https://github.com/LibreELEC/LibreELEC.tv/commit/1687857278eceeac0069bfaa4909961601d4e71a

Thus you don't even need glfw either.

**Pull request closed without merging**
