### PR TITLE
Add support for logging and reporting QA Checks

### PR DESCRIPTION
**Pull request by lrusak**
This adds support for logging QA checks via a new `log_qa_check` function. This function takes a title (of the check) and a message that explains the issues and possibly how to solve it.

This is needed so we can catch some simple problems that seems to keep making their way into master.

This changes `safe_remove` to be a qa check and logs anything that `safe_remove` flags.

The QA checks are logged in `${BUILD}/qa_checks/${PKG_NAME}-${PKG_VERSION}/`

These checks are then printed at the end of a build.

I plan to add more qa checks in the future that are related to kernel configs and rpaths and some other things. This PR just lays the base of this expansion.

I would be in favour of killing the build when encountering a QA issue but it's not possible until all the QA issues are solved.

For example:
```
Successful build, creating image...
Parallel mksquashfs: Using 12 processors
Creating 4.0 filesystem on /home/lukas/git/libreelec/target/LibreELEC-RPi4.arm-11.0-devel-20220701101813-27b48dd.system, block size 1048576.
[=========================================================================================================================================================================================-] 8250/8250 100%

<snip>

[QA CHECK] [general] [qa_issues]:
QA issues present, please fix!
/home/lukas/git/libreelec/build.LibreELEC-RPi4.arm-11.0-devel/qa_checks/glibc-2.35/safe_remove
/home/lukas/git/libreelec/build.LibreELEC-RPi4.arm-11.0-devel/qa_checks/libdrm-2.4.111/safe_remove
```

You can then read the files for the issue
```
$ cat build.LibreELEC-RPi4.arm-11.0-devel/qa_checks/libdrm-2.4.111/safe_remove

path does not exist: /home/lukas/git/libreelec/build.LibreELEC-RPi4.arm-11.0-devel/install_pkg/libdrm-2.4.111/usr/bin/amdgpu_stress
path does not exist: /home/lukas/git/libreelec/build.LibreELEC-RPi4.arm-11.0-devel/install_pkg/libdrm-2.4.111/usr/bin/kms-steal-crtc
path does not exist: /home/lukas/git/libreelec/build.LibreELEC-RPi4.arm-11.0-devel/install_pkg/libdrm-2.4.111/usr/bin/kms-universal-planes
```

### CODE REVIEW

**Comment by lrusak** [comment]
Merge?

**Review by antonlacon — APPROVED** [review]

**Review by CvH — APPROVED** [review]

**Comment by antonlacon** [comment]
`if [ -d "${BUILD}/qa_checks" -a -n "$(ls -1 ${BUILD}/qa_checks/)" ]` is evaluating both conditions instead of failing when there's no directory (no qa issues made). Either sending the `ls -1` output to /dev/null or using `[[` to test should resolve.

**Comment by vpeter4** [comment]
Now that this check is in the found issues could be fixed?

**Comment by Portisch** [comment]
What's this now?

```text
[QA CHECK] [general] [qa_issues]:
QA issues present, please fix!
~/CE/CoreELEC/build.CoreELEC-Amlogic-ne.arm-20/qa_checks/glibc-2.35/safe_remove
~/CE/CoreELEC/build.CoreELEC-Amlogic-ne.arm-20/qa_checks/libdrm-2.4.112/safe_remove

portisch@ubuntu:~/CE/CoreELEC$ cat ~/CE/CoreELEC/build.CoreELEC-Amlogic-ne.arm-20/qa_checks/glibc-2.35/safe_remove
path does not exist: ~/CE/CoreELEC/build.CoreELEC-Amlogic-ne.arm-20/install_pkg/glibc-2.35/usr/lib/libc_pic
path does not exist: ~/CE/CoreELEC/build.CoreELEC-Amlogic-ne.arm-20/install_pkg/glibc-2.35/usr/lib/*.map
portisch@ubuntu:~/CE/CoreELEC$ cat ~/CE/CoreELEC/build.CoreELEC-Amlogic-ne.arm-20/qa_checks/libdrm-2.4.112/safe_remove
path does not exist: ~/CE/CoreELEC/build.CoreELEC-Amlogic-ne.arm-20/install_pkg/libdrm-2.4.112/usr/bin/amdgpu_stress
path does not exist: ~/CE/CoreELEC/build.CoreELEC-Amlogic-ne.arm-20/install_pkg/libdrm-2.4.112/usr/bin/kms-steal-crtc
path does not exist: ~/CE/CoreELEC/build.CoreELEC-Amlogic-ne.arm-20/install_pkg/libdrm-2.4.112/usr/bin/kms-universal-planes
```
Some "improvement"? :disappointed:
Even if this is a "improvement": LE: `please fix!`

**Comment by lrusak** [comment]
@Portisch PR's welcome 😊

**Comment by vpeter4** [comment]
> I plan to add more qa checks in the future

Cool - introduce more new issues without fixing them ...

**Comment by SupervisedThinking** [comment]
> Cool - introduce more new issues without fixing them ...

Could you please outline & elaborate the newly introduced issues?

**Comment by Portisch** [comment]
`QA issues present, please fix!`?

**Comment by vpeter4** [comment]
Look few messages above for one? Why don't you fix the issue your QA check finds?
And if you forgot maybe you should read discussions  of your other PR's too again.

**Comment by SupervisedThinking** [comment]
Well you're aware of the fact that `safe_remove` nags since ages about files which should be removed but don't exist? So it's a friendly reminder to update some packages but it's not really something of importance & if you're worried about: just open a PR to fix it, as you obviously did now.

**Comment by vpeter4** [comment]
> that `safe_remove` nags since ages

But not at the end of every build. It is annoying if nothing else.

**Pull request merged**
