### PR TITLE
u-boot: update to 2024.07

### PR DESCRIPTION
**Pull request by heitbaum**
- u-boot (Rockchip): drop upstreamed patches for 2024.07
- u-boot: update to 2024.07

### wip
- build error with Dragonboard
  - I’m guessing it has something to do with https://github.com/u-boot/u-boot/commit/a149974d3cf81dfc11254e3093f645bec3d5d88e

```
make[1]: Leaving directory '/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-Dragonboard.aarch64-13.0-devel/build/u-boot-2024.07'
No valid dtbs found
FAILURE: scripts/build u-boot during makeinstall_target (package.mk)
```

running test builds:
- PROJECT=Amlogic ARCH=aarch64 DEVICE=AMLGX make image
- PROJECT=Allwinner ARCH=aarch64 DEVICE=A64 make image
- PROJECT=Allwinner ARCH=arm DEVICE=H3 make image
- PROJECT=Allwinner ARCH=aarch64 DEVICE=H5 make image
- PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 make image
- PROJECT=Rockchip ARCH=arm DEVICE=RK3288 make image
- PROJECT=Rockchip ARCH=aarch64 DEVICE=RK3328 make image
- PROJECT=Rockchip ARCH=aarch64 DEVICE=RK3399 make image
- PROJECT=NXP ARCH=arm DEVICE=iMX6 make image
- PROJECT=NXP ARCH=aarch64 DEVICE=iMX8 make image
- PROJECT=Qualcomm ARCH=aarch64 DEVICE=Dragonboard make image
- PROJECT=Samsung ARCH=arm DEVICE=Exynos make image

### CODE REVIEW

**Comment by heitbaum** [comment]
Build of all u-boot targets work (except Dragonboard - any ideas?)

**Comment by jernejsk** [comment]
So https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Qualcomm/devices/Dragonboard/bootloader/install needs update with new U-Boot. So this is best done by someone who actually has the board. I'm not sure if dtbtool step is needed, since official U-Boot documentation don't mentioned it: https://source.denx.de/u-boot/u-boot/-/blob/master/doc/board/qualcomm/board.rst

**Comment by chewitt** [comment]
ping @lrusak

**Comment by lrusak** [comment]
> ping @lrusak 

My dragonboard has been broken for a few years now. If no one else has one then it's probably worth dropping the project as I don't think anyone else actively uses it.

**Comment by heitbaum** [comment]
Unblocking u-boot PR along with deprecating GHA CI builds of Dragonboard. - https://github.com/LibreELEC/actions/pull/85

**Review by CvH — APPROVED** [review]

**Pull request merged**
