### PR TITLE
open-vm-tools: update to open-vm-tools-stable-11.0.0

### PR DESCRIPTION
**Pull request by MilhouseVH**
I did have an unusual failure on Ubuntu 16.04 (https://github.com/vmware/open-vm-tools/issues/370) with this PR, that I haven't been able to reproduce, so beware... If you hit the same issue, please post details to this PR.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Grrr just had this failure on Ubuntu 17.10 as well, when I had previously built `open-vm-tools-11.0.0` successfully, so this failure is random. Will try a `-j1`... nasty.

**Comment by MilhouseVH** [comment]
`-j1` doesn't help, so that's not it...

**Comment by vpeter4** [comment]
I think it is just linking error. vmbackup needs vmtools but path is not specified.
Try with this hack (I'm sure there is better solution):
```
post_configure_target() {
  sed -i "s|libvmbackup_la_LIBADD = \(.*\)|libvmbackup_la_LIBADD = \1 -L$PKG_BUILD/.$TARGET_NAME/libvmtools/.libs|g" $PKG_BUILD/.$TARGET_NAME/services/plugins/vmbackup/Makefile
}
```

**Comment by MilhouseVH** [comment]
@vpeter4 Thanks.

I haven't had any time to look into this today (Sunday) but I did run several more clean builds overnight (Saturday/Sunday, on both Ubuntu 16.04 and 17.10) and they all succeeded, so now I'm starting to question my own memory...

I'm 99% certain the first failure (Friday night) was a clean build on Ubuntu 16.04 with `open-vm-tools-11.0.0`. All subsequent `open-vm-tools-11.0.0` clean builds (Ubuntu 16.04/17.10) have been successful. All "unclean" builds - upgrading `open-vm-tools-10.3.10` to `open-vm-tools-11.0.0` - have been failures (on Ubuntu 17.10 only, so far).

So now I'm starting to wonder if the first failure was really clean, and if this is just an issue with a scrambled sysroot, which is only apparent when upgrading? In which case it may not be necessary for any workaround, as that kind of failure isn't entirely unusual (clean build, move on). Hmmm...

I'll run some more tests on Monday. Hopefully I can get to a point where I have a reproducible failure so that I can test your suggested workarounds - fingers crossed.

Has anyone else seen this failure when building `open-vm-tools-11.0.0` and LibreELEC?

**Comment by MilhouseVH** [comment]
So as expected, upgrading an existing build from `open-vm-tools-10.3.10` to `open-vm-tools-11.0.0` is failing, and adding the `post_upack()` fix allows the build to succeed (it links successfully, I assume it works - no idea...!)

Is this worth running past the open-vm-tools maintainer?

I'll add the fix to this PR as a separate commit - if anyone can think of anything better then it can be updated. Thanks again, @vpeter4.

**Comment by vpeter4** [comment]
I was building on dirty build and just changed package version. And build failed every single time.
Trying clean build now without hack. Didn't even think to do that before :(

**Comment by MilhouseVH** [comment]
Thanks for testing. Hopefully "unclean" builds upgrading to `11.0.0` should now be successful too.

**Comment by vpeter4** [comment]
I think the correct solution to the problem above is to add this to function _post_unpack()_. You can figure out the reason yourself :)
`  rm -f $SYSROOT_PREFIX/usr/lib/libvmtools*`

**Comment by MilhouseVH** [comment]
Yes, clearing out the old installation is likely the solution to most of these types of problem. I'll have a think, it's not very nice... but does avoid modifying the package source code. I did let the `open-vm-tools` maintainer know of the fix on the issue I opened, and they're going to look into it but ultimately it might be a LibreELEC-specific issue. Ideally this issue would be reproducible on a regular distro that has 10.3.10 installed, and which then fails while installing 11.0.0.

**Comment by vpeter4** [comment]
The main problem is that open-vm-tools-11.0.0 is linking with library from open-vm-tools-10.3.0. I assume issue should happen on "normal" distro too when same library libvmtools.so is installed under /usr.

I would say it is not LibreELEC specific issue.

**Comment by MilhouseVH** [comment]
That is my suspicion too - will see what the `open-vm-tools` developers come back with but it might not be any time soon, so in the meantime I'll have a think about your latest proposal. Thanks.

**Comment by vpeter4** [comment]
You should check if some other things are copied to toolchain. At least the libraries and includes are problematic.

But I wouldn't do much. If you know dirty build is bad just use clean one :D

**Comment by MilhouseVH** [comment]
> But I wouldn't do much. If you know dirty build is bad just use clean one :D

Yep, that's always the option of last resort as eventually with some bumps there's just no way (or no point) trying to salvage the toolchain! 

I think what set me off on this course was that I (for a reason I can't remember) thought I had had a clean build failure, but if it was actually an unclean build failure then there really isn't much point trying to fix `open-vm-tools` - just clean build, it's not something we bump often.

**Comment by MilhouseVH** [comment]
I've implemented the `rm -f ${SYSROOT_PREFIX}/usr/lib/libvmtools*` fix (tested, it works). I dunno if it's really necessary/worthwhile but let's see how it goes... I'll notify upstream also.

**Pull request merged**
