### PR TITLE
MiQi: Add linux patch for missing GPU&CPU nodes in dts

### PR DESCRIPTION
**Pull request by Ntemis**

### CODE REVIEW

**Comment by lrusak** [comment]
Is this still needed?

**Comment by Ntemis** [comment]
Yes it does https://github.com/torvalds/linux/blob/master/arch/arm/boot/dts/rk3288-miqi.dts

**Comment by lrusak** [comment]
@Ntemis did you send the patch upstream at all? Or find someone that is willing to send it for you?

**Comment by Ntemis** [comment]
Both answers are no but second cpu opp is not valid and wont be accepted as it is.
Miqi "officially" can only reach 1.7ghz as it seems

**Comment by lrusak** [comment]
Ok well you can reopen this if a proper upstream solution is found.

**Comment by Ntemis** [comment]
With out this merged MiQi doesnt have a gpu to work with. Dont understand why you closed it :D

**Pull request closed without merging**
