### PR TITLE
initramfs: enable gzip and CONFIG_INITRAMFS_COMPRESSION_GZIP=y

### PR DESCRIPTION
**Pull request by lrusak**
This should save a little space. Not sure how detrimental it is to RPi and low powered platforms.

@stefansaraev is `gzip` fine or should we `gzip -9`?

### CODE REVIEW

**Comment by escalade** [comment]
Save space? The initial ramdisk is like 6-7MB, so I can't see that compression will be that useful.

**Comment by stefansaraev** [comment]
@lrusak ok as-is.

**Comment by lrusak** [comment]
anyone interested in testing this?

**Comment by MilhouseVH** [comment]
I'll try a build overnight.

**Comment by MilhouseVH** [comment]
With this PR...

RPi and RPi2 boot to rainbow screen.
NUC hangs on BIOS splash screen.

This wasn't a clean build, but it did rebuild linux and produced `initramfs.cpio` that was 2.6MB smaller than without this PR (on Generic).
```
With PR:    5911630   3032 -rw-rw-r--   1 neil     neil      3102675 Oct  6 02:15 ./image/initramfs.cpio
Without PR: 5911630   5644 -rw-rw-r--   1 neil     neil      5778432 Oct  6 03:00 ./image/initramfs.cpio
```

All systems boot again after building without this PR.

**Comment by lrusak** [comment]
Sorry for the trouble milhouse, I had only tested this on my Wetek devices.

There is a change in kernel 3.15 where the initramfs will be compressed by the kernel makefile. so basically it has been gzipped in the kernel all allong and this PR really only pertains to kernels < 3.15 aka amlogic.

reference:
https://github.com/torvalds/linux/blob/master/usr/Kconfig#L9-L15
http://elinux.org/About_Compression#Initramfs_compression

```
Initramfs in most cases is compressed. If you specify an initramfs file system while building the kernel, the initramfs image will be compressed and embedded into the kernel image. It is not required to compress the image, but there is no CONFIG option to disable this. The build scripts always perform the compression, and only if you tweak the script you can avoid the compression.
```

**Comment by MilhouseVH** [comment]
OK, no problem!

**Comment by stefansaraev** [comment]
> Initramfs in most cases is compressed. If you specify an initramfs file system while building the kernel, the initramfs image will be compressed and embedded into the kernel image. It is not required to compress the image, but there is no CONFIG option to disable this. The build scripts always perform the compression, and only if you tweak the script you can avoid the compression.

only if you specify a directory. not if you specify a ready-to-use cpio file. in this case you care for the compression yourself.

**Comment by lrusak** [comment]
> only if you specify a directory. not if you specify a ready-to-use cpio file. in this case you care for the compression yourself.
Hmm, this doesn't seem to be the case. 

When looking at the code and documentation it seems different to me
see, https://github.com/torvalds/linux/blob/master/usr/Makefile#L72-L74
and, https://github.com/torvalds/linux/blob/master/scripts/gen_initramfs_list.sh#L17-L30

**Comment by stefansaraev** [comment]
as you wish..

**Comment by lrusak** [comment]
ok well maybe it has to be name `*.cpio.gz` ???
https://github.com/torvalds/linux/blob/master/scripts/gen_initramfs_list.sh#L197

**Comment by stefansaraev** [comment]
uh. it seems I misinterpreted what that makefile snipped was doing last time I looked at it. it seems to double-compress your compressed init.cpio into initramfs_data.cpio.gz so yes try with .gz suffix

**Comment by lrusak** [comment]
I'll do a clean build overnight and see if it works.

**Comment by lrusak** [comment]
Works. @MilhouseVH care to give this another go? :D

**Comment by MilhouseVH** [comment]
All RPi/RPi2/Generic systems now boot with the updated PR, but I'm not seeing any size benefit for these systems - is there expected to be any?

```
1006:  Without this PR
1006b: With this PR


RPi:
-rw-r--r-- 1 neil neil 5649988 Oct  6 13:50 LibreELEC-RPi.arm-8.0-devel-20161006115502-#1006-ga946329.kernel
-rw-r--r-- 1 neil neil 5648788 Oct  6 21:12 LibreELEC-RPi.arm-8.0-devel-20161006204705-#1006b-g141d669.kernel

RPi2:
-rw-r--r-- 1 neil neil 5829680 Oct  6 13:51 LibreELEC-RPi2.arm-8.0-devel-20161006115502-#1006-ga946329.kernel
-rw-r--r-- 1 neil neil 5829664 Oct  6 21:12 LibreELEC-RPi2.arm-8.0-devel-20161006204704-#1006b-g141d669.kernel

Generic:
-rw-r--r-- 1 neil neil 11697312 Oct  6 14:52 LibreELEC-Generic.x86_64-8.0-devel-20161006115502-#1006-ga946329.kernel
-rw-r--r-- 1 neil neil 11696672 Oct  6 21:14 LibreELEC-Generic.x86_64-8.0-devel-20161006204705-#1006b-g141d669.kernel
```

From the 1006b build directories for RPi/RPi2/Generic I see the new compressed initramfs, but this doesn't translate into a reduced size for `*.kernel` (see above):

```
RPi:
 20450182   3792 -rw-rw-r--   1 neil     neil      3883008 Oct  6 10:22 ./image/initramfs.cpio
 20452772   2020 -rw-rw-r--   1 neil     neil      2066901 Oct  6 20:54 ./image/initramfs.cpio.gz

RPi2:
 21367852   3772 -rw-rw-r--   1 neil     neil      3860992 Oct  6 10:22 ./image/initramfs.cpio
 21377802   2020 -rw-rw-r--   1 neil     neil      2067521 Oct  6 20:54 ./image/initramfs.cpio.gz

Generic:
 21367929   5644 -rw-rw-r--   1 neil     neil      5778432 Oct  6 10:42 ./image/initramfs.cpio
 21377752   3028 -rw-rw-r--   1 neil     neil      3098354 Oct  6 20:53 ./image/initramfs.cpio.gz
```

**Comment by MilhouseVH** [comment]
As this has no impact on 4.x kernels I guess this needs testing by the 3.x kernel guys.

**Comment by chewitt** [comment]
I'm closing this PR due to lack of activity, and because "if it works, don't fix it" applies to this part of the distro. Thanks.

**Comment by lrusak** [comment]
The only time I really needed this was when working on an android system where the boot partition is so small that when using a debug kernel it was larger than the size of the partition.

It really doesn't hurt to have it in. Though it may not have much of a perceivable effect.

**Pull request closed without merging**
