### PR TITLE
Networking improvements

### PR DESCRIPTION
**Pull request by rvleij**
**Why**
In order to support the Docker Add-On in LE to run in a Docker Swarm setup, overlay networking (VXLAN) support is required, which was not part of the included kernel in 9.2.6. Docker Swarm allows the LE box to run in a cluster, automatically load balancing workloads (containers) over the LE box and (for example) a Pi4.

**How**
With this PR I include the required kernel modules (VXLAN as well as netfilter (iptables) modules and IP_VS modules required for the built-in load balancing in Docker Swarm. I also bump the included version of iptables and it's libraries.

**Testing**
To test I made 10 test builds and installed them on amd64, until I got this running stable (it wasn't unstable the first 9 builds, I just lacked kernel modules which I then added until it worked). Docker now starts without errors and provides the full cluster / overlay networking functionality out of the box. I've picked stable versions of iptables and configured most modules to be compiled as modules (loaded when needed), only a few changes are compiled into kernel. Size increase is limited:

**Size Increase numbers**
New image:
256001312 Jan 26 22:30 LibreELEC-Generic.x86_64-9.2-devel-20210126212510-6bd7e98.img.gz
16655232 Jan 26 22:30 LibreELEC-Generic.x86_64-9.2-devel-20210126212510-6bd7e98.kernel
257443840 Jan 26 22:31 LibreELEC-Generic.x86_64-9.2-devel-20210126212510-6bd7e98.ova
242139136 Jan 26 22:30 LibreELEC-Generic.x86_64-9.2-devel-20210126212510-6bd7e98.system
259123200 Jan 26 22:30 LibreELEC-Generic.x86_64-9.2-devel-20210126212510-6bd7e98.tar

Original 9.2.6 image from website:
16577408 Oct 25 11:03 KERNEL (increase 77824 B)
255879664 Jan 29 21:18 LibreELEC-Generic.x86_64-9.2.6.img.gz (increase 121648 B)

I haven't made changes to the other projects, since I can't test. But my other node is a Pi4 (arm7), and the individual components (iptables, netfilter libs and kernel modules) are running there (just not a LE box).

### CODE REVIEW

**Comment by lrusak** [comment]
I'm not sure if this was a mistake but I'm going to close it 😄

**Comment by rvleij** [comment]
I think I did something wrong with the PR, even though I followed the "Note: All functional changes should be submitted to the master branch first", but I did my changes on 9.2.6. Not sure how to fix that, it's my first PR...

**Comment by lrusak** [comment]
> I think I did something wrong with the PR, even though I followed the "Note: All functional changes should be submitted to the master branch first", but I did my changes on 9.2.6. Not sure how to fix that, it's my first PR...

You need to PR to the branch your local branch is based on. We say all changes should be PR'd to `master` first so your local branch should also be based on the `master` branch

**Comment by rvleij** [comment]
Yeah, it looked fishy. :) I'll try again in a new one, thanks.

**Pull request closed without merging**
