### PR TITLE
Rockchip: RK3399: add support for Orange Pi 4 LTS

### PR DESCRIPTION
**Pull request by danijelt**
This patch adds support for Orange Pi 4 LTS. This device is similar to the already supported Orange Pi 4, but it uses Motorcomm YT8531C ethernet controller and CDW 20U5622-00 Wi-Fi + BT controller. There's no indication of attempts to mainline CDW driver so wireless and BT don't work at the moment.

The patches for Motorcomm driver and device tree are taken from manjaro-arm's linux-opi repository:
https://gitlab.manjaro.org/manjaro-arm/packages/core/linux-opi

Support for YT8531C is mainlined and present in v6.3-rc1 branch, so once LibreELEC switches to Linux v6.3, that patch can be dropped.

Additionally, U-Boot is patched to add OPi 4 LTS support too. This is not strictly required, but as LibreELEC's build system uses U-Boot's configured dtb name for Linux dtb as well, this solution is simpler than overhauling the build scripts.
Since U-Boot doesn't support Motorcomm PHY, the support is added by simply copying existing rk3399-orangepi dts and defconfig as rk3399-orangepi-4-lts. This means that networking won't work on 4 LTS, but there's no big impact because LibreELEC doesn't rely on network functionality in U-Boot.

### CODE REVIEW

**Comment by knaerzche** [comment]
@danijelt How about submitting this DT upstream? I'd like to avoid having (so simple) patches here forever, as they also need to be maintained forever.
If you need help doing it: ping me.

**Comment by knaerzche** [comment]
@danijelt if @spikerguy doesn't have the time to do it, you can do so either and keep the authorship.
This DT is floating around in so many different repos for a long time now: I think it's time to push it upstream :)

**Comment by zhangn1985** [comment]
upstream kernel (6.3.y) already supports YT8531, and Rockchip kernel is 6.3.4, please drop related patch.

**Comment by zhangn1985** [comment]
you can check:
https://github.com/armbian/build/pull/5291

**Comment by JDM170** [comment]
Hi, here I wrote a list of problems I could find without normal OPi4 LTS support:
- Problems with screen resolution (maximum 1024x768 instead of 1920x1080)
- No sound output
- On the last commit of the master branch ethernet gets IP-address 169.254.-.-, and should be 192.168.-.- (in my case), after merging opi4lts and master branch and also a little editing of the patch - ethernet works as it should (patch can be found here - https://gist.github.com/JDM170/a77d0a69bf1d065fc0fb2f6424c3227c).

Also I did some information search and found out that the main Wifi and BT chipset is called UWE5622 (analogs - AW859A, SC2355). I found drivers for it in armbian repository on Github as patches. I tried adding them to LibreELEC, the build completes successfully, but the system does not start with a partition mount error.
I think I need to add some kind of definition to the dts file so that the board knows it has such an adapter (UWE5622). I tried to get the dts file from armbian, I also tried to add only the wifi adapter to the dts file, but unfortunately it didn't work.

**Comment by danijelt** [comment]
I was able to boot from master the other day with DTS from Armbian as suggested by @zhangn1985, but CEC is not working. Other than that, everything else works fine like it does in v11 release. (Still have to test U-Boot, though.)

**Comment by lisander-lopez** [comment]
I would like to echo that I am available as well as any builds become available. For now, I will look at docs on how to build this myself. Using this branch. Currently I tried to use the build "LibreELEC-RK3399.aarch64-11.95.1-orangepi.img.gz" from here https://libreelec.tv/downloads/rockchip/ but it just "boot loops"

**Comment by lisander-lopez** [comment]
I burned `LibreELEC-RK3399.arm-12.0-devel-20240329165856-20d54cf-orangepi.img` and I still get a boot loop

**Comment by chewitt** [comment]
@danijelt I'm going to close the PR down due to lack of progress. LE is happy to backport patches adding new boards that have been merged upstream as we can drop them in a future kernel bump on a predictable timescale. I can't see any kernel patches for this board being sent to the linux-rockchip mailing lists though (checking in patchwork).

**Pull request closed without merging**
