### PR TITLE
RPi: support the OK button on the o2.cz BT remote

### PR DESCRIPTION
**Pull request by chewitt**
This file is present in master branch under `projects\Amlogic` but I'm using the same remote with an RPi4 under LE 9.2. If anyone can point me to the correct upstream location for this change to be sent so we can remove such things in the future - I will happily send a PR.

### CODE REVIEW

**Comment by HiassofT** [comment]
Why not just add a udev rule to route the remote through eventlircd, like we do for several other BT remotes? https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/eventlircd/udev.d/98-eventlircd.rules#L208-L230

I don't know that remote but I'd guess it sends KEY_OK (please confirm with evtest or libinput debug-events) and eventlircd is a simple solution to work around kodi's inability to cope with that keycode.

**Comment by chewitt** [comment]
The remote sends no key-mappable events without this. It was the solution you directed me to (some time ago) when I first tried to fix the problem with an Amlogic board.

**Comment by MilhouseVH** [comment]
Why aren't we pushing this to `master` first?

**Comment by chewitt** [comment]
9.2 branch is closer to a release and I'd like to ensure it gets in, and I'd prefer to fix it upstream for master .. but still seeking where that is. If not I'll send a PR.

**Comment by HiassofT** [comment]
Ah, OK. hwdb.d is managed in systemd git, but if you want to send that upstream you'd need to map the button to KEY_OK (assuming the button is labeled "OK" on the remote).

As this remote doesn't seem specific to RPi it'd be better to add the hwdb entry tree-wide, eg in the systemd package. And I agree with Milhouse, this should go to master first (opening a 9.2 backport in parallel and keeping them in sync is fine).

**Pull request closed without merging**
