### PR TITLE
multimedia-tools: add-on update

### PR DESCRIPTION
**Pull request by CvH**
@MilhouseVH mind a look at the `alsa-utils/lib` and maybe include it at your build as it effects kodi too.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Is there any particular reason why PKG_NAME is being removed from the urls?

**Comment by CvH** [comment]
pushed pulseaudio and soxr changes, builds for me at RPi1/2 and Generic

**Comment by MilhouseVH** [comment]
It might be better to add `-lto` to `soxr` for all projects as building with lto seems to cause more problems than it solves.

**Comment by CvH** [comment]
@MilhouseVH added

**Pull request merged**
