### PR TITLE
Rockchip: update rkmpp and mitigate gcc 9 build issues

### PR DESCRIPTION
**Pull request by Kwiboo**
This PR updates rkmpp to latest, fixes ffmpeg rkmpp patches for gcc 9, disables linux perf for gcc 9 and reverts back to use lzo as squashfs compression as use of zstd cause issues.

This should fix compilation of 4.4 images until PR for move to mainline is ready (after master moves to linux v5.3.x).

### CODE REVIEW

**Comment by MilhouseVH** [comment]
The Rockchip project now builds successfully for all 4 devices (MiQi, RK3328, RK3399 and TinkerBoard) with `ARCH=arm`, many thanks!

**Comment by CvH** [comment]
Using the much much more recent rk kernel is no option?

**Comment by MilhouseVH** [comment]
RK3328 and RK3399 images (including all board variants) built successfully with `ARCH=aarch64`.

**Comment by Kwiboo** [comment]
Runtime tested on TinkerBoard and RK3328.

**Comment by Kwiboo** [comment]
> Using the much much more recent rk kernel is no option?

The LE specific patches is no longer easily rebased on top of latest RK 4.4 kernel, and I would not like to spend more time on 4.4 kernel. Instead i want to focus on moving LE master to only use linux mainline kernel for Rockchip after v5.3.0 has been released next week.

**Pull request merged**
