### PR TITLE
[le11] linux: request to enable SCSI generic devices support

### PR DESCRIPTION
**Pull request by dtechsrv**
This is necessary for proper handling of optical drives (e.g. BD-ROM) under certain conditions.
For example, it is basically required to use MakeMKV.

This is already enabled by default for Generic (x86_64) platform.

_In the first round, I made patches only for the platforms I use (AMLGX and PRi*)._

### CODE REVIEW

**Comment by HiassofT** [comment]
Please PR to master and enable as a module instead of built-in. Other than that I have no objections for enabling it for all projects/devices

**Comment by chewitt** [comment]
If making changes like this please enable for all projects/devices so things are consistent

**Comment by chewitt** [comment]
Also PR to master first, then backport to LE11

**Comment by dtechsrv** [comment]
Ok, I'll make it on the master first for every project, but there's still a risk of inconsistency because it's already included in the config of Generic (x86_64) as built-in:
https://github.com/LibreELEC/LibreELEC.tv/blob/1a5ac4e047b1a172b86af9c64b3ec047f5276f05/projects/Generic/linux/linux.x86_64.conf#L1887
Should I change it back to module here as well, or can I use `=y` for all projects?
In this section (SCSI support type), essentially all configs set to built-in, so I'm not sure this one exception has much merit.

**Comment by HiassofT** [comment]
I'd just change it ot `=m` on Generic as well.

sg usage is very very niche today and lots of software (eg CD rippers) only support it for legacy devices (eg real SCSI which you won't see around much nowadays) and often with very limited support and known issues.

Debian x86 kernel has it enabled as module as well

**Comment by dtechsrv** [comment]
I also sent a PR for master ([#8190](https://github.com/LibreELEC/LibreELEC.tv/pull/8190)) and modified this backport as well.

Finally, `CONFIG_CHR_DEV_SG` was added as a module under all projects, and changed from built-in to module under Generic.

**Review by HiassofT — APPROVED** [review]

**Pull request merged**
