### PR TITLE
linux: update to linux-4.15.0

### PR DESCRIPTION
**Pull request by MilhouseVH**
Patches for nvidia drivers.

Most of the out-of-tree WiFi (Realtek, bcm_sta) drivers are currently unbuildable and will need a non-trivial update after [timer changes](https://github.com/torvalds/linux/commits/844056fd74ebdd826bd23a7d989597e15f478acb/include/linux/timer.h). Example in-tree change: [rtl8723bs](https://github.com/torvalds/linux/commit/e8b1844a7e59fc35c086358021d9d42b4ce3ee22#diff-218d912e45e61e9db2d6c86672d9c9c3).

---
#### Test build posts
| Kernel | RPi/RPi2 | Generic | Build | Announce |
| :--- | :---: | :---: | :----: | :----: |
| 4.15-rc1 | [Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2675778#pid2675778) | [Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2675780#pid2675780) | `#1204x` | [Link](https://lkml.org/lkml/2017/11/26/187) |
| 4.15-rc2 |||| [Link](https://lkml.org/lkml/2017/12/3/87) |
| 4.15-rc3 | [Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2678832#pid2678832) | [Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2678833#pid2678833) | `#1212x` | [Link](https://lkml.org/lkml/2017/12/10/204) |
| 4.15-rc4 | [Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2681065#pid2681065) | [Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2681066#pid2681066) | `#1219x` | [Link](http://lkml.iu.edu/hypermail/linux/kernel/1712.2/00650.html) |
| 4.15-rc5 | [Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2684440#pid2684440) | [Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2684441#pid2684441) | `#1229x` | [Link](https://lkml.org/lkml/2017/12/24/1) |
| 4.15-rc6 | [Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2686304#pid2686304) | [Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2686305#pid2686305) | `#0102x` | [Link](https://lkml.org/lkml/2017/12/31/125) |
| 4.15-rc7 | [Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2689066#pid2689066) | [Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2689067#pid2689067) | `#0108x` | [Link](https://lkml.org/lkml/2018/1/7/255) |
| 4.15-rc8 | [Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2691956#pid2691956) | [Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2691957#pid2691957) | `#0115x` | [Link](https://lkml.org/lkml/2018/1/14/210) |
| 4.15-rc9 | [Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2695780#pid2695780) | [Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2695781#pid2695781) | `#0124x` | [Link](https://lkml.org/lkml/2018/1/21/196) |
| 4.15.0 | [Link](https://forum.kodi.tv/showthread.php?tid=298461&pid=2697861#pid2697861) | [Link](https://forum.kodi.tv/showthread.php?tid=298462&pid=2697863#pid2697863) | `#0129x` | [Link](https://lkml.org/lkml/2018/1/28/173) |

### CODE REVIEW

**Comment by CGarces** [comment]
I have write access to rtl8192eu and the jwrdegoede version of rtl8189fs (will send a PR to use that source).
I'll made the patch on 6 Nov.

**Comment by adamg-xda** [comment]
jwrdegoede rtl8189fs does not work with 3.x

**Comment by CGarces** [comment]
Hi @adamg-xda

The code of jwrdegoede rtl8189fs has been  changed recently, maybe you have tested and old version.
The last code is the same version that you are using (from khadas)+ some changes to build correctly on x86 and newer kernels +  some changes introduced by jwrdegoede like [this one](https://github.com/jwrdegoede/rtl8189ES_linux/commit/bfc9bdbac4e7349210b16ac8bde43c38693fc042)

I have tested with [mainline kernels](https://travis-ci.org/CGarces/rtl8189ES_linux) and AmLogic kernel 3.10, only  AmLogic 3.14 is missing (will do it tonight)

Can you please test again with the last version (from yesterday)?

**Comment by adamg-xda** [comment]
@CGarces the module compiled without issue it just would not load, I cant recall the exact error, I will try it again later today.

**Comment by MilhouseVH** [comment]
> In any case, as I see in the compilation log I need to check this https://patchwork.kernel.org/patch/10059179/

Yes, currently building Generic with this kernel requires additional build host dependencies as per the message below:
```
 Makefile:938: *** "Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel".  Stop.
```

However we already build the [`elfutils` package](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/devel/elfutils/package.mk) so it may just be a case of building `elfutils` for host, and adding it as a host dependency for x86_64 `linux`.

**Comment by MilhouseVH** [comment]
Updated `connman` patch with that proposed by Daniel Wagner: https://lists.01.org/pipermail/connman/2018-January/022411.html - builds fine with 3.14.29, 4.14.14 and 4.15-rc8 kernels.

**Comment by MilhouseVH** [comment]
With 4.15-rc9 the B44 (Broadcom ethernet) and SSB (Sonics Silicon Backplane - [lwn.net](https://lwn.net/Articles/243521/)) options are no longer configured for Generic (see `config: update options for linux-4.15-rc9`).

This change is because of [this commit](https://github.com/torvalds/linux/commit/58eae1416b804d900014d84feadda7195007cc30). At this time I'm not sure if this is going to be a problem, or not.

**Comment by MilhouseVH** [comment]
Restore Intel SST ("Smart Sound Technology") support for Generic.

`SND_SOC_INTEL_SST_TOPLEVEL`  is introduced in rc1 and defaults to not enabled, which is unfortunate as all the Intel ASoC sound drivers are dependent on this option. Consequently all Intel ASoC drivers have not been building between rc1 and rc8.

**Comment by MilhouseVH** [comment]
Closing, as I'm not maintaining two kernel branches indefinitely.

**Pull request closed without merging**
