### PR TITLE
linux: bump Amlogic kernel to 6.0.y

### PR DESCRIPTION
**Pull request by chewitt**
This bumps the Amlogic kernel and patches to Linux 6.0.9

### CODE REVIEW

**Comment by chewitt** [comment]
Blocking merge until we figure out what makes `lima` run at low GPU clock all the time

**Comment by chewitt** [comment]
This is the fix https://patchwork.kernel.org/project/dri-devel/patch/20221027073200.3885839-1-nunes.erico@gmail.com/

**Comment by SupervisedThinking** [comment]
```
=== tested on ===
AMLGX.arm-RR-20221118-a14b1ef
Linux vim1 6.0.9 #1 SMP PREEMPT Fri Nov 18 04:52:26 CET 2022 aarch64 GNU/Linux
Starting Kodi (20.0-BETA1 (19.90.801) Git:20.0b1-Nexus). Platform: Linux ARM 32-bit
Using Release Kodi x32
Kodi compiled 2022-11-17 by GCC 12.2.0 for Linux ARM 32-bit version 6.0.9 (393225)
Running on Amlogic Meson GXL (S905X) Khadas VIM with LibreELEC (ST): RR-20221118-a14b1ef 11.0, kernel: Linux ARM 64-bit version 6.0.9
FFmpeg version/source: dev/4.4/rpi_import_1-f9638b6
Host CPU: ARMv8 Processor rev 4 (v8l), 4 cores available
ARM Features: Neon enabled
RetroPlayer[PROCESS]: Registering process control for GBM
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_VERSION = OpenGL ES 2.0 Mesa 22.3.0-rc3
```

**Review by SupervisedThinking — APPROVED** [review]
lgtm

**Pull request merged**
