### PR TITLE
u-boot: properly handle gcc upgrade now and in the future

### PR DESCRIPTION
**Pull request by jerome-benoit**
Unify compiler-gcc?.h headers into a unique compiler-gcc.h header file.

Signed-off-by: Jérôme Benoit <jerome.benoit@piment-noir.org>

### CODE REVIEW

**Comment by Kwiboo** [comment]
`patches/6e4e886/u-boot-0000-unify-compiler-gcc.h.patch` should probably be dropped from this PR and redirected to hardkernels upstream u-boot repo.

LibreELEC uses gcc-linaro-aarch64-elf and gcc-linaro-arm-eabi 4.9-2016.02 to build u-boot for the C2 since the kernel don't start when u-boot is compiled with gcc5/6.

**Comment by jerome-benoit** [comment]
On Fri, 18 Nov 2016 10:48:02 -0800 in
<LibreELEC/LibreELEC.tv/pull/949/c261609742@github.com>, Jonas Karlman
<notifications@github.com> wrote:

> `patches/6e4e886/u-boot-0000-unify-compiler-gcc.h.patch` should
> probably be dropped from this PR and redirected to hardkernels
> upstream u-boot repo.

It's an harmless patch and easy to drop once merged upstream and the
current package version updated. 

> LibreELEC uses gcc-linaro-aarch64-elf and gcc-linaro-arm-eabi
> 4.9-2016.02 to build u-boot for the C2 since the kernel don't start
> when u-boot is compiled with gcc5/6.

That will probably get updated one day and then the patch will ease
the maintenance burden :)

-- 
Jérôme Benoit aka fraggle
Piment Noir - http://piment-noir.org
OpenPGP Key ID : 9FE9161D
Key fingerprint : 9CA4 0249 AF57 A35B 34B3 AC15 FAA0 CB50 9FE9 161D

**Comment by Kwiboo** [comment]
I would argue that it is more of a maintenance burden to have a unneeded patch downstream for a toolchain that is currently unsupported by amlogic/hardkernel. If there ever come a day when gcc5/6 works it should probably come from upstream.

Please note that my comments are only in regards to the hardkernel 6e4e886 specific patch.

**Comment by jerome-benoit** [comment]
On Fri, 18 Nov 2016 12:26:04 -0800 in
<LibreELEC/LibreELEC.tv/pull/949/c261633266@github.com>, Jonas Karlman
<notifications@github.com> wrote:

> I would argue that it is more of a maintenance burden to have a
> unneeded patch downstream for a toolchain that is currently
> unsupported by amlogic/hardkernel.

It is generally the case but there's always special cases when it's
not. And this patch is in that case: 

* no core code changes so upstream changes have almost zero chance to
  collide;
* simplify all the interactions with the toolchain in the long run
  without needs to make code change. 

If you really do not want a patch that will simplify all
interactions with the toolchain with zero impact, I will drop it but
it's fairly a dumb decision.  

>  If there ever come a day when
> gcc5/6 works it should probably come from upstream.
> 

u-boot upstream is not the hardkernel fork and the real upstream has
already this patch in since almost two years. hardkernel should push
their changes to the real upstream, it will then for sure ease the
maintenance for every projects based on their hardware. It has be done
for the U2/3, the XU so maybe one day. 

-- 
Jérôme Benoit aka fraggle
Piment Noir - http://piment-noir.org
OpenPGP Key ID : 9FE9161D
Key fingerprint : 9CA4 0249 AF57 A35B 34B3 AC15 FAA0 CB50 9FE9 161D

**Comment by Kwiboo** [comment]
I'd say drop it for hardkernel 6e4e886, having a patch that fixes nothing and eventually will be deleted (when upstreamed to hardkernel u-boot or switching to upstream u-boot) makes no sense. LE should have as few patches as possible and only for stuff that cannot be added upstream or are unique for LE.

Hardkernels u-boot is currently needed for booting linux-amlogic 3.14 as upstream u-boot only can boot mainline linux on the C2.
Once there is full support for amlogic S905 in mainline linux/upstream u-boot and LE switches to upstream u-boot as you pointed out this patch will already be included hence there is no real need for this patch for the hardkernel specific u-boot unless it is coming with a version bump of hardkernels u-boot.

**Comment by chewitt** [comment]
I'm closing this PR due to lack of apparent need or activity. Thanks.

**Pull request closed without merging**
