### PR TITLE
crazycat, dvb-latest: copy files before calling make

### PR DESCRIPTION
**Pull request by vpeter4**
This allows to edit files in build folder itself and build package again.

### CODE REVIEW

**Comment by CvH** [comment]
@vpeter4 I guess you need to rebase your git branch, current base is from 1 year ago

**Comment by vpeter4** [comment]
And I though gitbub something messed up - it should be fine now.

**Comment by CvH** [comment]
@vpeter4 this is not forgotten, I test it as soon I fiddle around with dvb stuff

**Comment by vpeter4** [comment]
Sure. Just want to upstream changes found you know where.

**Pull request closed without merging**
