### PR TITLE
rsync: fix missing dependency openssl

### PR DESCRIPTION
**Pull request by Portisch**

### CODE REVIEW

**Comment by antonlacon** [comment]
Thanks. Would you add `--disable-openssl` to PKG_CONFIGURE_OPTS_HOST?

**Comment by Portisch** [comment]
Why disable a option if the needed dependency is available?

**Comment by antonlacon** [comment]
To my knowledge, rsync:host is only built to copy files as part of building the linux kernel. It would be time spent building something that won't be used, and may be inconsistent as to whether it will automatically find support depending on the build plan. I haven't read the logs/plan lately to know if that's true or if it varies by builder.

If you know of another reason for rsync:host to have support for openssl, please let me know and add it to rsync:host's depends too.

**Comment by Portisch** [comment]
We install `rsync` also target because we use it also in some embedded scripts. Your time loss is equal to zero as the dependency `openssl` is built anyway for a lot of other packages:
```
build   openssl:host              (wants: ccache:host)
build   cmake:host                (wants: ccache:host, openssl:host, pkg-config:host)
build   linux:host                (wants: ccache:host, rsync:host, openssl:host, gcc-arm-aarch64-none-linux-gnu:host)
install openssl                   (wants: toolchain)
install diskdev_cmds              (wants: toolchain, openssl)
install wpa_supplicant            (wants: toolchain, dbus, libnl, openssl)
install openssh                   (wants: toolchain, openssl, zlib)
install rsync                     (wants: toolchain, zlib, openssl)
install Python3                   (wants: toolchain, Python3:host, sqlite, expat, zlib, bzip2, xz, openssl, libffi, readline, ncurses, util-linux)
install openvpn                   (wants: toolchain, lzo, openssl)
install rtmpdump                  (wants: toolchain, zlib, openssl)
install curl                      (wants: toolchain, zlib, openssl, rtmpdump, libidn2, nghttp2)
install megatools                 (wants: toolchain, glib, openssl, curl)
install pulseaudio                (wants: toolchain, alsa-lib, dbus, libcap, libsndfile, libtool, openssl, soxr, speexdsp, systemd, glib:host, glib, sbc, avahi)
install mariadb-connector-c       (wants: toolchain, zlib, openssl)
```

**Comment by lrusak** [comment]
as @antonlacon indirectly points out, it's better to be explicit here rather than implicit.

Please add `--disable-openssl` to `PKG_CONFIGURE_OPTS_HOST` and `--enable-openssl` to `PKG_CONFIGURE_OPTS_TARGET`

**Comment by Portisch** [comment]
Thank you, I think I got the idea. I will rebase and force push the commit.

**Review by antonlacon — APPROVED** [review]

**Review by chewitt — APPROVED** [review]

**Pull request merged**
