### PR TITLE
Add nghttp2 for http2 support in curl

### PR DESCRIPTION
**Pull request by islipfd19**

### CODE REVIEW

**Comment by vpeter4** [comment]
Out of curiosity: Which servers supports HTTP2 protocol? I mean media related.

Also: I think you removed script kodi.sh?

**Comment by islipfd19** [comment]
@vpeter this change will support a PR change for kodi's support of http2, if I'm not mistaken.

The removal of kodi.sh was a squash error that included it when updating this PR.

**Comment by vpeter4** [comment]
Understand about http2.
But this PR is still bad regarding kodi.sh removal.

**Comment by islipfd19** [comment]
I'm probably going to cancel it because of that.

**Comment by vpeter4** [comment]
I'm sure some git gurus will help you clean it.

**Pull request closed without merging**
