### PR TITLE
disable connman when using kernel ip config / netboot

### PR DESCRIPTION
**Pull request by HiassofT**
This is a follow-up to the closed PR #3883, addressing the issues that came up during testing.

Connman is pretty useless (at best) when network booting LE so just detect if kernel ip configuration is being used and in that case disable connman, setup resolver and NTP server settings with the values from kernel ip config  and run systemd-timesyncd for NTP sync instead.

To handle corner cases users can provide resolv.conf and timesyncd configuration files via /storage/.config - see the commit messages for details.

RPi4 netboot tests worked fine here, only (mainly cosmetical) issue is we'll sometimes get a "storage unmount failed" message during reboot/shutdown as systemd is trying to unmount /storage too early (due to default dependencies for network mount units). For some very odd reason overriding /storage mount dependencies (via a drop-in, like we do for /flash) doesn't seem to work, systemd also doesn't show the /storage unit as being generated from /proc/self/mountinfo (like it's the case for /flash).

### CODE REVIEW

**Comment by HiassofT** [comment]
LE settings change to hide/disable the network settings sections is here https://github.com/LibreELEC/service.libreelec.settings/pull/140

**Comment by mglae** [comment]
Successful tested on Generic too.

**Comment by HiassofT** [comment]
PR #3984 fixes  the "unmount storage failed" message

**Comment by HiassofT** [comment]
rebased onto current master

**Comment by bestouff** [comment]
This is buggy: https://forum.libreelec.tv/thread/21577-libreelec-9-2-1-no-more-dhcp-after-a-while/#post136352

**Pull request merged**
