### PR TITLE
linux: update to 5.17.y

### PR DESCRIPTION
**Pull request by heitbaum**
### errors / fixes / issues / regressions
- ~HEVC api request patches - jernejsk (WIP)~
  - confirmed as a 5.18 patch - https://git.linuxtv.org/media_tree.git/commit/include/media/hevc-ctrls.h?id=7a3b3dc3bb2eeac4adf8b01b1b6b519bcbc48cfc
- ~already in **master**~
  - ~[Upstream] rtl8192cu: update githash to support 5.17.x~
  - ~[Upstream] RTL8192DU: update githash to support 5.17.x~
  - ~[Upstream] RTL8812AU: update to 2022-03-05~
  - ~[Upstream] rtl8192eu: update to 2022-03-13~
- includes kernel-firmware: update to 20220209
  - have not used 20220310 - due to build error
- Includes iwlwifi-firmware: update to ccf1a23
- Includes bcm_sta: patch to compile with Linux 5.17
- includes xf86-video-nvidia-legacy: allow build with kernel 5.17
- ~iMX8 failed build with rc3 and rc4 - some issue with dependency of `CONFIG_DRM_GEM_CMA_HELPER` in the latest kernel.~
  - ~patch added for the moment~
  - ~99fc9358c656641d5c10350151970006de4b8ea6~
  - ~https://patchwork.kernel.org/project/linux-arm-kernel/patch/20220216212228.1217831-1-rudi@heitbaum.com/~
  - Patch is included in 5.17-rc6
- ~systemd (upstream patch required) - is included in v250.4~
  - ~patch added for the moment~
  - ~https://patch-diff.githubusercontent.com/raw/systemd/systemd/pull/22312.patch~
  - ~https://github.com/systemd/systemd-stable/issues/166~
  - ~amlogic version reverted~
  - Replaced by #6295 
- https://lore.kernel.org/all/164598944963.346832.10219407090470852309@leemhuis.info/
- https://lore.kernel.org/lkml/2ea77295-e8a1-d312-e142-2e238f081993@leemhuis.info/
- https://github.com/torvalds/linux/commits/master

### kernel 5.17 Build tested on all of:

```
PROJECT=Allwinner ARCH=arm DEVICE=A64 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H3 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H5 s/build linux
PROJECT=Allwinner ARCH=arm DEVICE=H6 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX6 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX8 s/build linux
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic s/build linux
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy s/build linux
```

### 5.17.y Run tested on all of:
- Allwinner all - tested - TBA - jernejsk
- Allwinner H6 (Tanix TX6) - 5.17 - heitbaum
- Generic Generic (Intel TGL - NUC11) - 5.17 - heitbaum
- NXP iMX6 (Cubox-i4Pro) - TBA  - heitbaum
- Rockchip RK3399pro (Rock Pi N10) - TBA - heitbaum
- RK all - tested - TBA - knaerzche
- Samsung Exynos (Hardkernel ODROID XU4) - TBA - heitbaum (video issue)

### CODE REVIEW

**Comment by CvH** [comment]
@heitbaum pls rebase

**Comment by heitbaum** [comment]
> @heitbaum pls rebase

Rebase done. Should be ready - once 5.17.0 is available.

**Comment by heitbaum** [comment]
As I suspected, we have an -rc8
- https://lore.kernel.org/lkml/CAHk-=wiHa0vsZseZES=1T0rJ4Z_bC5cwHMUJfqFL9hVpvB283g@mail.gmail.com/

**Comment by heitbaum** [comment]
Build tested on all of released 5.17

**Review by CvH — APPROVED** [review]

**Pull request merged**
