### PR TITLE
kodi: use github url, remove skin patches, package estuary and estouchy.

### PR DESCRIPTION
**Pull request by lrusak**
We have never needed to have more than one skin.

I'm not sure if anyone has any objections here but with this we don't have to carry a couple patches.

This also allows us to use the github url instead of using the mkpkg script.

I still need to runtime test this, I have only build tested it.

### CODE REVIEW

**Comment by vpeter4** [comment]
I assume that both skins will now be included by default? In this case images are around 4MB larger because of including Estouchy skin.

**Comment by lrusak** [comment]
@vpeter4 yes both skins will be installed. It would be nice to ship Estouchy as an add-on but I'm not sure the best way to do this yet.

**Comment by vpeter4** [comment]
Without proper thinking: what about making addon zip file in kodi's post_install(). And then removing folder from image.

**Comment by TheUlpio** [comment]
Well, this is not related to the technical progression of LibreELEC, but after the "new" ugly estuary rework i think that let users to build their own default skins (obviously who has the skill to provide the necessary package.mk) is the right way. Of course, everyone can install their own skin via addon manager, then, why fill /flash with superfluous code and either /storage with other addons? Personally after the "new" estuary skin, where i get 20x15 buttons and the need of continuously scroll either horizontally and vertically, i reverted to confluence (more, more, more usable) as default (and only) skin without waste space in /storage.
Anyway this is only my thought, my two cents. I never seen an enigma based equipment that need continuously scroll to let a (normal) user to comfortably use it. If this is only my need, i can continue to build LibreELEC reverting this commit...

**Comment by vpeter4** [comment]
After kodi is build with cmake there is no option to select different default skin when building image. Meaning this PR only adds Estouchy skin to image and doesn't change anything else. And It should be removed and repacked to addon somehow.

@lrusak: I think [this](https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/functions#L482-L486) should be removed too.

**Comment by lrusak** [comment]
@vpeter4 thanks, updated

**Comment by lrusak** [comment]
I have reworked this and added a commit from @vpeter4 for estouchy.

This way Estuary can still be installed by default, but self builders can still remove it and add other skin options if they want.

@TheUlpio is this more to your liking?

**Comment by TheUlpio** [comment]
@lrusak Very, very thanks for this:) you made me (but i hope i'm not alone) a great Christmas present:)
Now i'm away for Christmas holidays, soon i'll try to build my own confluence and report results (maybe in the forum so it does not spam github).

@vpeter4 You're right, after cmake transition there was no way to build other skins, but reactivate the functionality is very simple, just 4-5 lines in package.mk. When i'll come back to home, i have to test if it still works with this pr, if yes may i propose a patch for a review?

**Comment by vpeter4** [comment]
Just a little tip

**Comment by TheUlpio** [comment]
Ok, i'm back to home:)
@vpeter4 you're right, to allow the adoption of an alternate skin, is necessary to work on addon-manifest.xml. This is the approach that i used to make confluence the default skin after kodi is built with cmake

[package.mk.patch.txt](https://github.com/LibreELEC/LibreELEC.tv/files/673329/package.mk.patch.txt)

This will require a review after this pr will be applied, but for now the concept matters

**Comment by MilhouseVH** [comment]
All seems fine, thanks.

I've built this on top of latest Kodi 18 master and there are no issues.

Comparing pre-PR1080 and post-PR1080 shows no differences in the resulting image -  no extra or missing files, no change in file sizes - so it all looks good. Will include this in test builds.

**Pull request merged**
