### PR TITLE
librespot: update to 0.3.1

### PR DESCRIPTION
**Pull request by simonpils**
This works for me since librespot 0.3.1 was released

### CODE REVIEW

**Comment by vpeter4** [comment]
You missed https://github.com/LibreELEC/LibreELEC.tv/pull/5891 ?

**Comment by heitbaum** [comment]
Hi @simonpils, there was already a `librespot` in the PR queue for both LE10 and LE11. But if you would like to rebase this request for the bump to `rust`. That would be great - could you please check if this workaround https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/addon-depends/librespot-depends/rust/package.mk#L48-L56 is still valid though.

**Comment by heitbaum** [comment]
In reviewing the conflicts https://github.com/LibreELEC/LibreELEC.tv/pull/5900/conflicts I do notice the difference between `` and ``. I’m not a rust programmer, but if your in a better patch - please submit this as an improvement.

**Comment by heitbaum** [comment]
Please reopen if required.

**Pull request closed without merging**
