### PR TITLE
use e2fsprogs/dosfstools from toolchain for image creation

### PR DESCRIPTION
**Pull request by HiassofT**
We already build fsck.fat in dosfstools:host but didn't install it to toolchain. Add that (plus fatlabel which may be helpful, too) and use it in mkimage

Edit: by building e2fsck, mke2fs and tune2fs and installing to toolchain we can drop the dependency on build host tools completely and also remove /sbin from the PATH for mkimage

### CODE REVIEW

**Comment by HiassofT** [comment]
updated scripts/mkimage to explicitly use `${TOOLCHAIN}/sbin/fsck.fat` instead of just fsck.fat

**Comment by vpeter4** [comment]
Isn't `${TOOLCHAIN}/sbin` and `${TOOLCHAIN}/bin` already in PATH?

**Comment by HiassofT** [comment]
Yes, TOOLCHAIN/(s)bin is already on path so it isn't strictly necessary (which is why I had it without it in my first version). But we had a short discussion on Slack and (not only) my preference is to make this explicit so we don't accidentally fall back to /sbin (which is added by scripts/image and is a bit odd - as normally it's not in the path for regular users)

**Comment by vpeter4** [comment]
Excuse my ignorance but why we would fall back to /sbin ?

**Comment by HiassofT** [comment]
All it takes is someone/something messing with PATH or dosfstools package.

scripts/image is more expicit there and calls depmod, fakeroot, mksquashfs all with TOOLCHAIN/bin prefixed.

scripts/mkimage is a bit of a mess and at first I thought mke2fs cane from toolchain as well - it wasn't obvious to me that e2fsprogs binaries are not built and installed to toolchain but the whole thing works only because scripts/image adds /sbin to the PATH (which I didn't expect)

So as it is now I'd prefer to follow scripts/image style and call fsck.fat with explicit TOOLCHAIN prefix.

Ideally we should then clean up image build, build use mke2fs etc from toolchain and drop /sbin from the PATH. I think we should have most of the stuff already there, but this is something for a separate PR.

After that it'd be fine to drop explicit TOOLCHAIN/sbin prefixes

**Comment by vpeter4** [comment]
You lost me with **someone** and **something** :)

**Comment by HiassofT** [comment]
I'm currently testing with e2fsprogs binaries built for host, which will allow us to drop /sbin from the path, so I've added WIP label for now. I'll push an update (with $TOOLCHAIN/sbin dropped from fsck.fat call) when the test build finished successfully.

**Comment by HiassofT** [comment]
RPi4 image build was successful, I've updated the PR (and the description).

Would be nice if someone could do independent build+runtime tests with this PR, so I'll keep it at WIP for now.

**Comment by MilhouseVH** [comment]
I'll run clean builds overnight. I did test the version from last night without issues, but will test again.

**Comment by vpeter4** [comment]
Generic ova build and runs on VMware as before.

**Comment by MilhouseVH** [comment]
Looks good to me (tested RPi/RPi2/Generic).

**Comment by HiassofT** [comment]
Thanks for testing and the feedback!

I've removed WIP, feel free to review / bikeshed now :-)

**Pull request merged**
