### PR TITLE
buildsystem: use no-lto, when lto is disabled

### PR DESCRIPTION
**Pull request by InuSasha**
else gcc/binultis can reenable it, automatically

Build tested with Generic, RPi2 and LePotato

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Ah, meant to try a clean build of this the other day - will kick it off overnight and merge this tomorrow if no issues.

**Comment by MilhouseVH** [comment]
After this PR we will build Kodi without LTO even when we request Kodi to build using the internal LTO options. This patch resolves that issue: http://ix.io/1avA

**Comment by InuSasha** [comment]
@MilhouseVH thanks
i have not seen this special case. 
Your patch looks good. I will add it, after work day. 

Sorry for late reaction, i was ill the last two days.

PS: patch is needed for gcc8 transition.

**Comment by InuSasha** [comment]
@MilhouseVH patch added

**Comment by MilhouseVH** [comment]
Thanks, hope you're feeling better now!

**Pull request merged**
