### PR TITLE
dosfstools/e2fsprogs: update to latest

### PR DESCRIPTION
**Pull request by MilhouseVH**

### CODE REVIEW

**Comment by mglae** [comment]
1) For 'target' both dosfstools and busybox are creating `mkfs.vfat`. Removing it from [busybox config](https://github.com/LibreELEC/LibreELEC.tv/blob/77a21197311a993f197cd82a0e9453557a07c9c0/packages/sysutils/busybox/config/busybox-target.conf#L648) looks preferable but is not tested.

2) A question more for my education: why are `pre_build_host()`and `make_host()` needed (or have been needed) for dosfstools? Replacing them with `PKG_MAKE_OPTS_HOST="PREFIX=/usr"` creates identical binaries.

**Comment by MilhouseVH** [comment]
1. Agreed on dropping the `busybox` version
2. In `dosfstools-4.0`, they [updated their build system](https://github.com/dosfstools/dosfstools/releases) which may have rendered the `pre_build_host()` workaround/hack no longer necessary

Thanks for spotting both issues, I'll look into fixing them on Monday.

**Comment by MilhouseVH** [comment]
`dosfstools-4.0.0` builds fine without `pre_build_host()` and `make_host()`.

These workarounds were required because `dosfstools-3.x` does not include a `configure` script, so we didn't [automatically create](https://github.com/LibreELEC/LibreELEC.tv/blob/master/scripts/build#L222-L233) `${PKG_BUILD}/.${HOST_NAME}` (etc.) and build into it. Without the workarounds, all created host binaries (`mkfs.fat`, `fsck.fat` etc.) would be dropped into the root of `$PKG_BUILD` - this would be confusing as this is also where the `target` binaries are/were dumped (we didn't use the same hack for `target`) so the workarounds are preventing the `host` binaries from overwriting the `target` binaries (and vice versa).

Fortunately, `dosfstools-4.0.0` now includes a `configure` script, so all targets build into their respective host-tuple directory, and problem solved...

Extra commit added.

**Comment by MilhouseVH** [comment]
I've added another commit to disable the `busybox` `mkfs.vfat`. We already build (and install) `mkfs.fat` from `dosfstools`, and `mkfs.vfat` is just a sym-link to `mkfs.fat` so this change won't result in any additional bloat but will ensure that `mkfs.vfat` is now a more capable "full-fat" version.

It's important to eliminate this type of issue as the order in which the `dosfstools`/`busybox` packages are built would have determine whether we installed the full-fat `mkfs.vfat` from `dosfstools`, or the cut-down version from `busybox`.

**Comment by mglae** [comment]
LGTM. Thanks for the detailed explanation.

**Pull request merged**
