### PR TITLE
Tvheadend 4.2 with transcoding

### PR DESCRIPTION
**Pull request by CvH**
Transcoding is only integrated for Generic
- Vorbis, aac, VP8/9 and x264/5

- needs more runtime testing - [test addons for Generic / RPi2-3 / WeTek_Play click here](http://goo.gl/47EtF4)

- reworked the whole default settings to hopefully useful settings and without errors
- renamed that we are able to ship 2 Tvh versions (4.0 and 4.1/2)
- I couldn't test the xmltv and power scripts - **maybe** borked
- splitted in 2 commits that it is easier to see what is needed for transcoding/reverting/porting

- **QSV for Intel gpu acceleration is NOT included because it is not working for unknown reason** (it compiles fine but didn't work)

tx to @vpeter4 and @lrusak

### CODE REVIEW

**Comment by lrusak** [comment]
looks pretty good, my only concern is when/if we move back to one tvheadend that the addon id's will be borked, but nothing we can really do about this.

**Comment by CvH** [comment]
you never know what is happen in the feature :-/

**Comment by stefansaraev** [comment]
addonid should not be changed. and if there is high demand for transcoding. it should be enabled for all platforms.. and you will hit a wall with this. too

**Comment by CvH** [comment]
Addonid isn't nice - we know - but no better idea to allow 2 versions of Tvh (it is prerequisite to support 4.0 - at least at 7.0).

Software transcoding at arm is atm more or less useless - something hw accelerated isn't implemented somewhere.

**Comment by stefansaraev** [comment]
why 2nd? what if there is demand for yet one more tvh feature tomorrow, you will add 3rd addon ?

**Comment by CvH** [comment]
Not supporting 4.0 would result in "failed" upgrading for OE users (if 4.2 would replace it).
Not supporting Tvh 4.2 would be a major mistake - feature and stableness wise.
There is no plan to support 4.0 till forever. The situation isn't ideal - but we won't sacrifice user-friendliness over KISS.

**Comment by stefansaraev** [comment]
sp, same sh** like OE's 3.2 -> 4.0 migration. and even worse, as tvh can't handle it's own (old) config files now. what about 4.4, 4.6 and 4.8 btw ? new addons because upgrade will fail ?

**Comment by stefansaraev** [comment]
I am sure @perexg can help fixing the remaining issues if you run tvheadend under gdb and report to him, adding new addon just because upgrading from old version fails is a no go.

**Comment by CvH** [comment]
The upgrade fails for numerous reasons even at debian as reported by different users. 
We need an 1click solution that actually work. I would also like *just* an update but at the moment this fails. We could provide a clean upgrade path that works through this. At the moment every change is dictated if the upgrade will work (even Kodi fails there). If 4.4 is also not upgrade friendly, I guess, we would add an "new" package again (4.0 is dropped ofc). Nobody likes to setup his Tv at every major upgrade - so we could at least stretch the time till this is necessary.

**Comment by lrusak** [comment]
I think we should just keep it the same for all platforms. No reason to single out the Generic project.

If people want to try and transcode on their RPi1 then that's their choice

**Comment by CvH** [comment]
@lrusak then you have to do the upstream work and implement it in Tvheadend it self, even the normal packages doesn't support it. Even if implemented you have to write an gpu encode integration because the cheap ass ARMs doesn't have enough cpu power to get something done. I don't think that we need to support more as the upstream creators. The benefit (I guess nobody wants to write an gpu integration) is 0 because it is far away from usable.

**Comment by piotrasd** [comment]
@CvH QSV Intel still dont work ? 
https://trac.ffmpeg.org/wiki/HWAccelIntro#IntelQSV

**Comment by CvH** [comment]
@piotrasd
sadly not, also it is deprecated and the vaapi implementation (ffmpeg 3.1) should be used but they is still not completely supported by Tvh

**Comment by piotrasd** [comment]
@CvH this is not becuase 

> Requriments on Linux: you need either to rely on the Intel Media Server Studio for Linux, or use a recent enough supported system, with the libva and libdrm libraries, the libva Intel drivers, and the libmfx library packaged by lu_zero
> 
libmfx library ??

**Comment by CvH** [comment]
@piotrasd the problem is the libmfx lib - they have some problem (forgot why) and sadly there is zero help (from the creators) if you only mention ffmpeg (libav vs ffmpeg situation) :/ 
If someone gets this fixed I`m the last one who is against to include it ;)

**Comment by piotrasd** [comment]
@CvH ok thanks for answer :) i will also look about some news in topic.
 i have please, because i know you tried get working x11grab in ffmpeg
could you look at https://github.com/LibreELEC/LibreELEC.tv/pull/523 after --enable-x11grab im still get Unknown input format: 'x11grab', im suppose that problem libxcb

**Pull request merged**
