### PR TITLE
linux: update to linux-4.12.0

### PR DESCRIPTION
**Pull request by MilhouseVH**
Work in progress....

1) `nvidia-legacy` doesn't currently build
2) ~~`media_build` doesn't currently build~~
3) ~~XBOX remote patch isn't compatible, needs reworking?~~
4) `RTL8723BS` added as module - ping @sorhtyre, #1601 

I've submitted fixes for `RTL8812AU`, `RTL8192CU` and `RTL8192EU` upstream, will bump and remove as those packages are updated.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Updated XBOX remote script - thanks @HiassofT. Added latest RPi support commits.

**Comment by MilhouseVH** [comment]
Added commit to install all firmwares from `linux-firmware/rtlwifi` for all projects - adds extra 924Kb. This will mean the firmwares for rtl8723bs are installed.

**Comment by MilhouseVH** [comment]
On reflection I've reverted the rtlwifi firmware change as we already install rtlwifi from [wlan-firmware](https://github.com/LibreELEC/wlan-firmware). However the wlan-firmware package needs updating, ideally with the removal of files that are (or can be) provided by kernel-firmware. I'll see what I can do over the weekend.

**Comment by MilhouseVH** [comment]
@sorhtyre & @piotrasd: is [this service](https://github.com/LibreELEC/LibreELEC.tv/pull/1601/files#diff-b5e3981b107db6d2f1eeef07a5f29127) still required for RTL8723BS in this PR?

**Comment by HiassofT** [comment]
@MilhouseVH could you please add these 2 options on RPi and RPi2?
```
CONFIG_REGULATOR_ARIZONA_LDO1=m
CONFIG_REGULATOR_ARIZONA_MICSUPP=m
```
The old CONFIG_REGULATOR_ARIZONA was split up into 2 separate options. See also here:
https://github.com/raspberrypi/linux/pull/2101

**Comment by MilhouseVH** [comment]
Thanks @HiassofT - RPi/RPi2 configs updated.

**Comment by MilhouseVH** [comment]
Rebased. Build tested on RPi/RPi2/Generic OK.

@sorhtyre & @piotrasd: if additional work is required for RTL8723BS you'll need to sort it out yourself.

4,12.1 is already available so I'll push a PR for that (merge about 4.12.4, I guess).

**Comment by HiassofT** [comment]
Please add this patch to media_build https://github.com/LibreELEC/LibreELEC.tv/pull/1780/commits/8a24ffd554cedff52c7718c093786d7af65d8de3 - it fixes non-working lircd.

Also since lirc_rpi will be broken by the media_build bump (and probably won't get fixed) it's better to remove it from the kernel configs.

I'm not sure if lirc_xbox still works, but since that would be the only lirc driver remaining I think it's best to remove the downstream patch and disable CONFIG_LIRC_STAGING (which should remove both LIRC_RPI and LIRC_XBOX).

**Comment by MilhouseVH** [comment]
media_build patches updated.

Dropped LIRC_RPI and LIRC_STAGING from RPi/RPi2/Generic due to media_build conflicts. Not sure about other projects - will add if needed.

Looks like LIRC_XBOX is now dead, so perhaps we can drop https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/linux/patches/default/linux-052-XBOX_remote_support.patch ?

**Comment by MilhouseVH** [comment]
Can we merge this, I'm on 4.12.1 already... if we need more changes they can come later.

**Comment by MilhouseVH** [comment]
And 4.12.2 is now available...

**Pull request merged**
