### PR TITLE
[patches] - remove tivo slide pro kernel patches for 3.14 amlogic ker…

### PR DESCRIPTION
**Pull request by Memphiz**
…nels. Patch is carried in the kernel src instead now to affect all platforms.

This has to be merged after 
https://github.com/LibreELEC/linux-amlogic/pull/55
and
https://github.com/LibreELEC/linux-amlogic/pull/56

@codesnake fyi

### CODE REVIEW

**Comment by stefansaraev** [comment]
are you sure you want to remove projects/imx6/patches/linux/3.14-sr/linux-010_tivo_slide_pro.patch ?

**Comment by CvH** [comment]
@stefansaraev you don't miss something ;)
@Memphiz pls drop `projects/imx6/patches/linux/3.14-sr/linux-010_tivo_slide_pro.patch` as imx uses a different kernel source

**Comment by Memphiz** [comment]
yep - my bad - just saw 3.14 and thought "same amlogic like for the others) - totally ignoring that its imx6 ;)

Also PRed the patch to the 3.10 linux-amlogic branch too now here https://github.com/LibreELEC/linux-amlogic/pull/56

@stefansaraev the only obvious thing you miss is that i only have and care about wetek hub atm, i am a newbie when it comes to the whole LibreElec eco system and i just screwed up the PR in the first try. The intention wasn't to remove the feature from the wetek play but adding it to the hub of course ;)

**Comment by chewitt** [comment]
@Memphiz the final piece of jigsaw is bumping githashes in packages/linux/package.mk

**Comment by Memphiz** [comment]
To late already - will do tomorrow ;)

**Comment by Memphiz** [comment]
@chewitt done

**Pull request merged**
