### PR TITLE
autoreconf: support custom PKG_CONFIGURE_SCRIPT

### PR DESCRIPTION
**Pull request by mglae**
PKG_BUILD path was hard coded in autoreconf script. Use path of PKG_CONFIGURE_SCRIPT that is by default set to "${PKG_BUILD}/configure".

See discussion of #4972

### CODE REVIEW

**Comment by mglae** [comment]
Applied PKG_CONFIGURE_SCRIPT  to open_vm_tools and asio packages.

**Comment by CvH** [comment]
anyone ? otherwise lgtm

**Comment by CvH** [comment]
@mglae gtg ?

**Comment by mglae** [comment]
Yes, still building.

**Review by CvH — APPROVED** [review]

**Pull request merged**
