### PR TITLE
kodi: update to githash 68effd5

### PR DESCRIPTION
**Pull request by heitbaum**
- update to latest Kodi with https://github.com/xbmc/xbmc/pull/25867 to support pvr build changes in #9434

### CODE REVIEW

**Comment by HiassofT** [comment]
The fences patches need a rebase as the GBM plane selection changes were reverted https://github.com/xbmc/xbmc/pull/25864

**Comment by HiassofT** [comment]
Instead of rebasing the patches it's easier to also revert the egl async fixes PR, as suggested by popcornmix https://github.com/HiassofT/LibreELEC.tv/commits/le13-kodi-fences

I had a quick go at it and RPi5 build was fine - haven't runtime tested it yet though
https://github.com/HiassofT/LibreELEC.tv/commits/le13-kodi-fences

**Comment by popcornmix** [comment]
I've been running locally with latest kodi tree plus the two elg async PRs reverted, and it's been working fine for last week.

**Comment by HiassofT** [comment]
The RPis look fine with the new revert change (tested on RPi3B+, RPi4 and RPi5)

**Comment by heitbaum** [comment]
@HiassofT i have added your revert

**Review by HiassofT — APPROVED** [review]

**Comment by HiassofT** [comment]
thanks!

@jernejsk @chewitt @knaerzche could you give this a try and check if AW/AML/RK is fine, too?

**Pull request merged**
