### PR TITLE
Cmake ninja

### PR DESCRIPTION
**Pull request by lrusak**
We use both ninja and cmake, so why not use them together!

This isn't a real serious PR, I doubt it will make any difference to build time at all, but I just wanted to PR it in case anyone had interest in using ninja. My only real issue is that this complicates the build system as it adds another level of failure.

I'll kick off a jenkins build and see what happens.

### CODE REVIEW

**Comment by InuSasha** [comment]
should the ninja package moved from addon-depend to devel section, in this case?

**Comment by lrusak** [comment]
Yes, but it's just aesthetics really

**Comment by chewitt** [comment]
@lrusak is this still something desired or interesting?

**Comment by chewitt** [comment]
@lrusak revise and merge or close?

**Comment by lrusak** [comment]
I've updated this. I still need to run through a full build test.

The reason I'd like to do this is that there is a push towards the meson build system in some projects. I have another branch that will integrate meson also. Meson requires building with ninja, so we might as well use ninja for everything.

**Pull request merged**
