### PR TITLE
tinkerboard: disable 5s polling for CEC adapters

### PR DESCRIPTION
**Pull request by viulian**
In an attempt to reduce Kodi load on the Asus Tinkerboard S, I discovered that it was polling for CEC devices every 5 seconds (using CEC library):

`[pid  5019] openat(AT_FDCWD, "/sys/bus/cec/devices/", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = 60'`

Raspberry PI already has a check in place to disable pooling, the reasoning being that the CEC addapter [cannot be removed](https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/peripherals/bus/virtual/PeripheralBusCEC.cpp#L51).

However, I cannot add a similar check for Tinkerboard, as it seems that both vendor ID and adapterType are 0 (UNKNOWN) - no clean way to modify Kodi to add a proper check. The workaround I found was to just set polling to false in Libreelec, in the tree of Tinkerboard. I've hard-coded m_bNeedsPolling to false before the switch, to make it easier to remove and not to interfere with the existing code too much. 

I hope I chose the file name correctly ...

### CODE REVIEW

**Comment by Kwiboo** [comment]
Thanks for your contribution!

The `adapterType` for the cec-framework adapter should be `ADAPTERTYPE_LINUX` (`0x400`), to make this a little bit more generic I would suggest you add a new case in the swtich statement:

```
    case ADAPTERTYPE_LINUX:
      /** the Linux adapter cannot be removed, no need to rescan */
      m_bNeedsPolling = false;
      break;
```

The libcec cec-framework adapter patch only gets applied when `CEC_FRAMEWORK_SUPPORT=yes`. This kodi patch should be handled in a similar way, i.e. add the patch under `packages/mediacenter/kodi/patches/cec-framework` and add the following to kodi `package.mk`.

```
if [ "$CEC_FRAMEWORK_SUPPORT" = "yes" ]; then
  PKG_PATCH_DIRS+=" cec-framework"
fi
```

**Comment by viulian** [comment]
Thank you for the review:

I got confused by the output of cec-client where the vendor id and product id were zero; haven't investigated type Linux as it sounded too generic to do a switch on it and mistakenly catch all other Linuxes.

```
tinker-s-libreelec:~ # cec-client -l
libCEC version: 4.0.4,  compiled on Thu May  9 08:12:34 UTC 2019 by viulian@libreelec-build on Linux 4.4.0-146-generic (x86_64), features: P8_USB, DRM, P8_detect, Linux
Found devices: 1

device:              1
com port:            Linux
vendor id:           0000
product id:          0000
firmware version:    0
type:                Linux
```

I'll fix the code, test, and commit the changes.

**Comment by Kwiboo** [comment]
Thanks, and yeah, the `Linux` name is rather generic, I named it Linux because it is an adapter for the linux cec-framework api :smile:

In LibreELEC the cec-framework adapter is only used for on-board cec usage similar to rpi so I think a patch like this should work great.
I do not expect that it can be sent upstream to Kodi since it may be too generic and the cec-framework adapter is not merged in libcec.

**Comment by viulian** [comment]
Please let me know if the commit is OK.

**Pull request merged**
