### PR TITLE
media_build: build rc modules

### PR DESCRIPTION
**Pull request by CvH**
this fixes the cir/rc/ir problems
cc @kszaq @wrxtasy

### CODE REVIEW

**Comment by HiassofT** [comment]
I'm not feeling comfortable replacing the in-kernel remote drivers with the bleeding-edge mediabuild drivers. Please disable building the RC drivers in the media build.

**Comment by CvH** [comment]
@HiassofT see slack pls

**Comment by lrusak** [comment]
@CvH are you happy with this?

**Comment by CvH** [comment]
@lrusak yes no problems known

**Pull request merged**
