### PR TITLE
media-driver: update and include in build

### PR DESCRIPTION
**Pull request by lrusak**
It's time we include the iHD libva driver in the build. It is very much usable

### CODE REVIEW

**Comment by lrusak** [comment]
@MilhouseVH this is worth including and testing as this will override using the `intel-vaapi-driver`

https://github.com/intel/libva/blob/master/va/drm/va_drm_utils.c#L40-L41

It should be merged quickly though and we can always add an environment override to use intel-vaapi-driver if required by using `LIBVA_DRIVER_NAME=i915`

**Comment by MilhouseVH** [comment]
Will do.

**Comment by MilhouseVH** [comment]
Deltas... `#0127` is last night's text build without this PR, `#0128` includes this PR (and also the `samba` bump PR):
```
NEW FILE       Delta: 15           #0128: 15            #0127: n/a          /usr/lib/libigdgmm.so -> libigdgmm.so.11
NEW FILE       Delta: 19           #0128: 19            #0127: n/a          /usr/lib/libigdgmm.so.11 -> libigdgmm.so.11.1.0
NEW FILE       Delta: 458,272      #0128: 458,272       #0127: n/a          /usr/lib/libigdgmm.so.11.1.0
NEW FILE       Delta: 6,928,120    #0128: 6,928,120     #0127: n/a          /usr/lib/dri/iHD_drv_video.so
SIZE CHANGE    Delta: -4,096       #0128: 34,672        #0127: 38,768       /usr/lib/libcli-cldap-samba4.so
SIZE CHANGE    Delta: -24          #0128: 455,184       #0127: 455,208      /usr/lib/libkrb5-samba4.so
SIZE CHANGE    Delta: -8           #0128: 198,592       #0127: 198,600      /usr/lib/libgensec-samba4.so
SIZE CHANGE    Delta: -8           #0128: 169,952       #0127: 169,960      /usr/lib/libgse-samba4.so
SIZE CHANGE    Delta: 8            #0128: 272           #0127: 264          /etc/issue
SIZE CHANGE    Delta: 24           #0128: 487           #0127: 463          /etc/os-release
SIZE CHANGE    Delta: 4,096        #0128: 15,396,288    #0127: 15,392,192   /usr/lib/kodi/kodi.bin
TOTAL CHANGE   Delta: 7,386,418 (more) in #0128 (kernel 5.4.15) compared with #0127 (kernel 5.4.15) [minimum delta: 0, files below threshhold: 0]

SYSTEM         Delta: 2,056,192    #0128: 221,278,208   #0127: 219,222,016  (more in #0128)
KERNEL         Delta: 0            #0128: 18,686,848    #0127: 18,686,848   (more in #0128)
```

How does one tell which driver they're using? What is the benefit of this PR?

**Comment by lrusak** [comment]
> How does one tell which driver they're using? What is the benefit of this PR?

It will show up in the Kodi log.
```
2020-01-28 11:08:57.507 T:358529   DEBUG: libva info: VA-API version 1.6.0
2020-01-28 11:08:57.507 T:358529   DEBUG: libva info: va_getDriverName() returns 0
2020-01-28 11:08:57.507 T:358529   DEBUG: libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
2020-01-28 11:08:57.507 T:358529   DEBUG: libva info: Found init function __vaDriverInit_1_6
2020-01-28 11:08:57.521 T:358529   DEBUG: libva info: va_openDriver() returns 0
```



You can read about the media-driver here https://github.com/intel/media-driver

**Comment by MilhouseVH** [comment]
Thanks - it's working once I add `LIBVA_DRIVER_NAME=iHD` to `/storage/.config/kodi.conf` - without this override I continue to use the i965 driver by default (Skylake i5 NUC).

Currently my `/storage/.config/kodi.conf` has the following overrides and appears to be working normally:
```
MESA_LOADER_DRIVER_OVERRIDE=iris
LIBVA_DRIVER_NAME=iHD
```
With the above overrides I see `OpenGL vendor: Intel` in System Info > Video (confirming the mesa/iris override) and
```
2020-01-28 19:46:40.036 T:2748   DEBUG: libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
```
confirming the use of this new Intel media driver.

**Comment by lrusak** [comment]
@MilhouseVH rebased

**Pull request merged**
