### PR TITLE
ffmpeg: update to 7.1

### PR DESCRIPTION
**Pull request by HiassofT**
Initial testing on RPi4 and RPi5 looks mostly fine, only HW deinterlace doesn't work yet.

Other platforms are completely untested and need updated patches

Merge this together with #9570

### CODE REVIEW

**Comment by chewitt** [comment]
@HiassofT I've done some smoke testing with Amlogic and that seems to be fine too.

**Comment by chewitt** [comment]
I meant you can use his `test/7.1/main` branch. Sorry..

**Comment by HiassofT** [comment]
Thanks for the hint, I missed that I accidentially switched Aml to plain 7.1 ffmpeg.

I've now switched it to jc's branch and dropped the patches in the Amlogic project dir - hope it's fine now.

**Comment by knaerzche** [comment]
@HiassofT I pushed updates for `v4l2-drmprime`, ` v4l2-request` and ` vf-deinterlace-v4l2m2m`.  `v4l2-drmprime` is a pure rebase w/o testing, as I can't test. 
@jernejsk pls test.

**Comment by heitbaum** [comment]
Build and run tested on Generic

**Comment by knaerzche** [comment]
I've now also added  not-yet-merged https://github.com/xbmc/xbmc/pull/25467 which is required for latest ffmpeg v4l2-request patches. Has been tested on RPi also https://github.com/xbmc/xbmc/pull/25467#issuecomment-2382747518, so it should be safe to add it to common kodi patches.

**Comment by HiassofT** [comment]
@knaerzche thanks a lot, I did a very quick test on RPi5 and HEVC still worked fine with the kodi patch

**Comment by HiassofT** [comment]
I've added a small cleanup and switched the libreelec patch branch to use FFMPEG_VERSION, like used for the v4l2 patches, so we don't have to modify that manually in the future. No functional change, just branch rename.

**Comment by zhangn1985** [comment]
@HiassofT do you have upstream or bug link for RK3288 VPU mmu issue?

**Comment by HiassofT** [comment]
@zhangn1985 sorry, I'm not familiar with RK, but  @knaerzche may be able to provide more information

**Comment by knaerzche** [comment]
> @HiassofT do you have upstream or bug link for RK3288 VPU mmu issue?

You can be sure we really tried very hard to be able to make the new code working on all platforms - however there is a yet to be found, probable subtile, bug in hantro driver which strikes only on 32-bit platforms and we are "behind the scenes" in contact with the maintainers of this driver anyway. However it works fine with iommu disabled and it actually makes no difference from users POV. (All (most) of this information can be found in the commit message where iommu is disabled, btw.)

**Comment by ilmich** [comment]
tested on my rockchip board (rk3328) with h264 and hvec streams and everything seems to work.

**Comment by jernejsk** [comment]
tested on AW H6 and works great

**Comment by HiassofT** [comment]
Feel free to merge if you are happy, we can fix RPi HW deinterlace in a separate PR - no big deal and no reason to delay the ffmpeg bump

**Comment by zhangn1985** [comment]
@jernejsk I tested FFmpeg patches from your [repo](https://github.com/jernejsk/FFmpeg) on AW H3 with Linux 6.6.38, with mpv player.
it fails to open hw codec device.

does it require linux 6.12 and later?

FFMpeg 6.1 patches are also from your repo and works well with linux 6.6.38, thank you.

**Comment by jernejsk** [comment]
I'm not familiar with mpv needs. I only check Kodi compatibility. As far as kernel needs go, I believe 6.6 should suffice, but I forgot which kernel version got latest fixes.

**Comment by HiassofT** [comment]
@knaerzche I've dropped the local PR25467 patch as it's now in kodi (kodi PR is updated to current HEAD)

**Review by knaerzche — APPROVED** [review]

**Pull request merged**
