### PR TITLE
Intel: add patch for kernel 4.7 HDMI sound

### PR DESCRIPTION
**Pull request by CvH**
patch for HDMI audio support for intel BYT/CHT SoC

@piotrasd should be okay ?

### CODE REVIEW

**Comment by piotrasd** [comment]
yes, but before merge give me some time for test and build, i just added this patch yesterday, and i didn't have time to test it

**Comment by chewitt** [comment]
@MilhouseVH please pick this to test in your builds, thanks.

**Comment by piotrasd** [comment]
@CvH @MilhouseVH please dont forget enable HDMI audio in kernel config

**Comment by CvH** [comment]
@piotrasd done

**Comment by piotrasd** [comment]
tested on Milhouse build  - HDMI sound working fine !

**Pull request merged**
