### PR TITLE
add missing libretro addons

### PR DESCRIPTION
**Pull request by CvH**
- this is just buildtested (at generic) because I have nothing to runtime test it
- mame2016 is building, game.libretro.mame2016 fails - ideas welcome how to fix it

```
buildbot:~/LE$ PROJECT=Generic ARCH=x86_64 scripts/create_addon game.libretro.mame2016
CREATE ADDON game.libretro.mame2016 (Generic/x86_64)
     BUILD      game.libretro.mame2016 (target)
         TOOLCHAIN      cmake (auto-detect)
Executing (target): cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=/builddir/toolchain/etc/cmake-x86_64-libreelec-linux-gnu.conf -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=MinSizeRel /builddir/game.libretro.mame2016-2581a76552da518cb82f8940e3dd1c37d07e640d
-- MAME2016_VERSION=0.174.0.1
-- Configuring done
-- Generating done
-- Build files have been written to: /builddir/game.libretro.mame2016-2581a76552da518cb82f8940e3dd1c37d07e640d/.x86_64-libreelec-linux-gnu
Executing (target): ninja 
ninja: no work to do.
[0/1] Install the project...
-- Install configuration: "MinSizeRel"
CMake Error at cmake_install.cmake:49 (file):
  file INSTALL cannot find
  "/builddir/game.libretro.mame2016-2581a76552da518cb82f8940e3dd1c37d07e640d/MAME2016_LIB-NOTFOUND".


FAILED: CMakeFiles/install.util 
cd /builddir/game.libretro.mame2016-2581a76552da518cb82f8940e3dd1c37d07e640d/.x86_64-libreelec-linux-gnu && /builddir/toolchain/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

### CODE REVIEW

**Comment by CvH** [comment]
@garbear , @5schatten pointed out that fbalpha2012 is completely useless - any idea why this was added at game.kodi at all ?

**Comment by garbear** [comment]
why is it useless?

**Comment by CvH** [comment]
@garbear the latest version supports everything even at RPi0 - why ship an 6year old one ?

**Comment by garbear** [comment]
Sometimes older versions can offer improved compatibility and performance on low-end devices. If that's not the case, then FBA2012 can be dropped.

**Comment by CvH** [comment]
@vpeter4 
tx fixed, hmm strange for some reason upstream is not using the real name

**Comment by CvH** [comment]
Removed fbalpha2012 from pr, there is no point in supporting some random old version if everything works at the latest version - same situation for fbalpha2018.

As long nobody has some proper reason to include it (besides that libretro/kodi-game has it) we can easily skip it. Also we don't increase the mess due the huge number of emulator cores with no proper way to distinguish the functions.

**Comment by garbear** [comment]
I support your decision to drop FBA2012. Thanks for keeping libretro add-ons up to date, there's so many of them and I know how much effort it takes to keep everything updated.

**Pull request merged**
