### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by MilhouseVH**
### \*\* CLEAN BUILD ALERT! \*\*

The following have been built for and runtime tested on RPi, RPi2 and Generic.

Note that this PR includes a bump to gcc-6.1.0, as well as several other core packages.

Package | Old | New | Changelog
:----|:----:|:----:|:----
`alsa-lib` | 1.1.1 | 1.1.2 | http://www.alsa-project.org/main/index.php/Changes_v1.1.1_v1.1.2
`alsa-utils` | 1.1.1 | 1.1.2 | http://www.alsa-project.org/main/index.php/Changes_v1.1.1_v1.1.2
`elfutils` | 0.165 | 0.166 | https://git.fedorahosted.org/cgit/elfutils.git/tree/ChangeLog?h=elfutils-0.166
`gcc` | 5.4.0 | 6.1.0 | https://gcc.gnu.org/gcc-6/changes.html
`gdb` | 7.11 | 7.11.1 | https://www.gnu.org/software/gdb/download/ANNOUNCEMENT
`glibc` | 2.23 | 2.24 | https://www.sourceware.org/ml/libc-alpha/2016-08/msg00212.html
`kmod` | 22 | 23 | http://git.kernel.org/cgit/utils/kernel/kmod/kmod.git/tree/NEWS?id=a29268d00e335afb34d93d56898cac531d038867
`libmnl` | 1.0.3 | 1.0.4 | N/A
`libpng` | 1.6.23 | 1.6.24 | https://sourceforge.net/p/libpng/code/ci/libpng16/tree/CHANGES
`libressl` | 2.3.5 | 2.4.2 | https://github.com/libressl-portable/portable/blob/v2.4.2/ChangeLog
`make` | 4.1 | 4.2.1 | http://lists.gnu.org/archive/html/info-gnu/2016-05/msg00013.html, http://lists.gnu.org/archive/html/info-gnu/2016-06/msg00005.html
`mysql` | 5.7.13 | 5.7.14 | https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-14.html
`qemu` | 2.5.1 | 2.6.0 | http://wiki.qemu.org/ChangeLog/2.6
`sqlite` | 3.12.2 | 3.14.1 | https://www.sqlite.org/changes.html
`systemd` | 230 | 231 | https://github.com/systemd/systemd/blob/v231/NEWS

----

I wanted to include the following:

Package | Old | New | Changelog
:----|:----:|:----:|:----
`binutils` | 2.26 | 2.27 | https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=binutils/NEWS;hb=refs/tags/binutils-2_27
`libgcrypt` | 1.6.5 | 1.7.2 | https://lists.gnupg.org/pipermail/gnupg-announce/2016q3/000392.html

However with both `gcc 6.1.0` and `gcc 5.4.0`:

1) `binutils` 2.27 ([commit](https://github.com/MilhouseVH/LibreELEC.tv/commit/804405e8f73da44e8aa10b92055530aec8ba4ab7)) results in the following kernel panic on RPi2 (didn't bother booting Generic):

panic

`binutils` 2.26.1 does boot normally, so it's a problem introduced with 2.27. I saw little point in bumping to 2.26.1. I'm working to bisect the 2.27 commits.

2) `libgcrypt` 1.72 (commits: [1](https://github.com/MilhouseVH/LibreELEC.tv/commit/f335556788f5c9ce5d45cbac737524f2056bbe13), [2](https://github.com/MilhouseVH/LibreELEC.tv/commit/a8fb9000f8a977fb59bfecc06e59bec37ce68062), [3](https://github.com/MilhouseVH/LibreELEC.tv/commit/477e6e3e913a0ba1f7512f9526cda181691b3f14)) fails to build on Generic:

```
libtool: link: /home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc -shared  -fPIC -DPIC  .libs/libgcrypt_la-visibility.o .libs/libgcrypt_la-misc.o .libs/libgcrypt_la-global.o .libs/libgcrypt_la-sexp.o .libs/libgcrypt_la-hwfeatures.o .libs/libgcrypt_la-stdmem.o .libs/libgcrypt_la-secmem.o .libs/libgcrypt_la-missing-string.o .libs/libgcrypt_la-fips.o .libs/libgcrypt_la-hmac256.o .libs/libgcrypt_la-context.o .libs/hwf-x86.o  -Wl,--whole-archive ../cipher/.libs/libcipher.a ../random/.libs/librandom.a ../mpi/.libs/libmpi.a ../compat/.libs/libcompat.a -Wl,--no-whole-archive  -L/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib /home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libgpg-error.a  -march=x86-64 -m64 -Os -flto -mmmx -msse -msse2 -mfpmath=sse -Wl,--version-script=/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/libgcrypt-1.7.2/src/libgcrypt.vers -march=x86-64 -m64 -Wl,--as-needed -fuse-ld=gold -fuse-linker-plugin -flto   -Wl,-soname -Wl,libgcrypt.so.20 -o .libs/libgcrypt.so.20.1.2
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/lib/gcc/x86_64-libreelec-linux-gnu/6.1.0/../../../../x86_64-libreelec-linux-gnu/bin/ld.gold: error: /tmp/ccVygTe1.ltrans16.ltrans.o: requires dynamic R_X86_64_PC32 reloc against '.Laes_consts' which may overflow at runtime; recompile with -fPIC
collect2: error: ld returned 1 exit status
```
The AES-NI SSE3 feature is added in 1.7.0.

So for now I've left out `binutils` and `libgcrypt` - suggestions welcome on how to fix!

### CODE REVIEW

**Comment by MilhouseVH** [comment]
There are gcc kernel project patches for WeTek Play/Core/Hub - I assume these are still needed, this hasn't been tested.

What's the magic word to trigger builds with this PR for all projects?

**Comment by MilhouseVH** [comment]
Not sure if there's going to be any add-on breakage. I've built PVR.* and inputstream.* with this PR, but all others still need to be tested.

**Comment by MilhouseVH** [comment]
Closing until LE9 kicks off.

**Comment by vpeter4** [comment]
For future reference: patch projects/imx6/patches/linux/linux-compiler-gcc.h.patch must be moved to projects/imx6/patches/linux/3.14-mx6-sr/linux-compiler-gcc.h.patch.

**Pull request closed without merging**
