### PR TITLE
add install to eMMC GUI

### PR DESCRIPTION
**Pull request by 150balbes**

### CODE REVIEW

**Comment by 5schatten** [comment]
@150balbes just wondering if you had some time / any progress to add the VIM as a supported device?

**Comment by 150balbes** [comment]
@5schatten 
 I may have misinterpreted your question. Initially, this patch supports all models of s9xxx, including VIM, and does not require revision specifically for VIM.

**Comment by 5schatten** [comment]
I'm pretty sure it failed for VIM but I would give it a try. Can you rebase it?

**Comment by 150balbes** [comment]
Sorry, I didn't get the point. On my VIM, it works without problems.

**Comment by 5schatten** [comment]
I can't even cherry pick this PR on my vanilla LE master branch. So you probably have to update some stuff to match upstream code.

**Comment by 150balbes** [comment]
As I recall, Chewitt uses some of the information from this request. So I can't change anything yet.

**Comment by chewitt** [comment]
I've a copy in a patch file so feel free to rebase and change things.

**Comment by mo123** [comment]
@150balbes Is there a similar patch for Rockchip to add Install to emmc you can share?

**Comment by mo123** [comment]
> @mo123 I can form such a patch for you. Not to wait, you can see all the changes here.
> 
> https://github.com/150balbes/LibreELEC.tv/tree/Amlogic-Leia/projects/Rockchip/devices/RK3328

OK, thanks, now I see the changes.
I want to build on latest LE branch and try the 'Install to EMMC' later, will see if I can get it working.
If you have time later and can make a separate patch, it will save a lot of time, so other changes are excluded and you can just apply the patch to latest LE branch easily.
After doing 'Install to emmc', can you only restore a full Android backup through LE from an sd-card since you are replacing emmc again(and it causes problems if you are already booting from emmc) or can you still flash Android stock firmware again through AndroidTool on a PC for Rockchip devices or won't it detect the device then since LE uses different partitions, bootloader?

Will try to not post more here, so it stays on topic for Amlogic 'Install to EMMC' support.

**Comment by 150balbes** [comment]
> > @mo123 I can form such a patch for you. Not to wait, you can see all the changes here.
> > https://github.com/150balbes/LibreELEC.tv/tree/Amlogic-Leia/projects/Rockchip/devices/RK3328
> 
> OK, thanks, now I see the changes.
> I want to build on latest LE branch and try the 'Install to EMMC' later, will see if I can get it working.
> If you have time later and can make a separate patch, it will save a lot of time, so other changes are excluded and you can just apply the patch to latest LE branch easily.
> After doing 'Install to emmc', can you only restore a full Android backup through LE from an sd-card since you are replacing emmc again(and it causes problems if you are already booting from emmc) or can you still flash Android stock firmware again through AndroidTool on a PC for Rockchip devices or won't it detect the device then since LE uses different partitions, bootloader?
> 
> Will try to not post more here, so it stays on topic for Amlogic 'Install to EMMC' support.

Can you tell me which branch you're using to build LE (so I can build a patch specifically based on its state and recent changes) ?

**Comment by mo123** [comment]
> > > @mo123 I can form such a patch for you. Not to wait, you can see all the changes here.
> > > https://github.com/150balbes/LibreELEC.tv/tree/Amlogic-Leia/projects/Rockchip/devices/RK3328
> > 
> > 
> > OK, thanks, now I see the changes.
> > I want to build on latest LE branch and try the 'Install to EMMC' later, will see if I can get it working.
> > If you have time later and can make a separate patch, it will save a lot of time, so other changes are excluded and you can just apply the patch to latest LE branch easily.
> > After doing 'Install to emmc', can you only restore a full Android backup through LE from an sd-card since you are replacing emmc again(and it causes problems if you are already booting from emmc) or can you still flash Android stock firmware again through AndroidTool on a PC for Rockchip devices or won't it detect the device then since LE uses different partitions, bootloader?
> > Will try to not post more here, so it stays on topic for Amlogic 'Install to EMMC' support.
> 
> Can you tell me which branch you're using to build LE (so I can build a patch specifically based on its state and recent changes) ?

Master branch
https://github.com/LibreELEC/LibreELEC.tv/tree/master

**Comment by 150balbes** [comment]
> Master branch

patch for rk3328
https://yadi.sk/d/FDZv4XzvCveQdA

**Comment by 150balbes** [comment]
@mo123 
The patch hit the old version (with the error). Here is the correct (proven) version.
https://github.com/150balbes/LibreELEC.tv/blob/Amlogic-Leia-4.x/projects/Rockchip/devices/RK3328/packages/rockchip-autoscript/instboot/install2emmc.sh

**Comment by mo123** [comment]
> @mo123
> The patch hit the old version (with the error). Here is the correct (proven) version.
> https://github.com/150balbes/LibreELEC.tv/blob/Amlogic-Leia-4.x/projects/Rockchip/devices/RK3328/packages/rockchip-autoscript/instboot/install2emmc.sh
Hi

I try with your patch and new install2emmc.sh file.

On MVR9 RK3328 LE built from LE master branch,
when I go to LE settings and choose Install to emmc, nothing happens and then I can't leave the settings menu, I waited for 20 minutes. When removing the micro-sd card, it still boots to Android.
When I choose Backup emmc, then it shows a quick message, Backing up that disappears and then after 20 minutes also nothing happens and you are stuck in the LE settings menu and can't go back.
Is there some other bug or do I need to wait longer perhaps?

Thanks

**Comment by 150balbes** [comment]
@mo123 
So as not to disturb others, I suggest to continue discussion in this topic
https://github.com/150balbes/LibreELEC.tv/issues/23

**Comment by polojoe** [comment]
I would appreciate to see install to emmc on my mvr9/trn9 box.

**Comment by mo123** [comment]
> I would appreciate to see install to emmc on my mvr9/trn9 box.

I hope LE team will also merge 'Install to emmc' in future.
I think this issue was for Amlogic to add 'Install to emmc', one wasn't opened for Rockchip devices yet.

Balbes150's images are very close to latest main LE code.
https://yadi.sk/d/oje0RHxPqpEqqQ/20190116

**Comment by lrusak** [comment]
It most likely won't happen till after the transition to the mainline kernel. So give it a year at least.

**Comment by polojoe** [comment]
I hope someone could do pr for rockchip. Update emmc install to official build isn't possible or is it?

**Comment by 150balbes** [comment]
> I hope someone could do pr for rockchip. Update emmc install to official build isn't possible or is it?

What do you expect from the official version ? What's wrong with builds from the developer community ?

**Comment by polojoe** [comment]
I'm not able to update your builds with update share. Le doesn't boot after update. I'm not able to use the same addons like in official builds. Eg tvheadend 4.3 doesn't start in your builds. I would expect the same behavior as on sdcard.

**Pull request closed without merging**
