### PR TITLE
adafruit-libraries: new library addon with python libraries from adafruit

### PR DESCRIPTION
**Pull request by InuSasha**
addon starts with all libraries emanate from  the old Raspberry-Pi-Python-Code.
The three libraries from the rpi-tools was migrated to this packages, too.

### CODE REVIEW

**Comment by chewitt** [comment]
Updated icon: http://chewitt.libreelec.tv/icon/icon_adafruit_libs.png

**Comment by InuSasha** [comment]
@chewitt you want color, you get color :)
icon replaced with your version

**Comment by CvH** [comment]
@InuSasha could you shuffle the lines (and drop some of them) in `addons/libraries/adafruit-libraries/package.mk` shown [here](https://gist.github.com/CvH/6d3911cf8418eb801383b68a65a4ef0b) (to follow the standard package schema which is not yet adopted by all addons - my bad)
also the change in the changelog.txt is missing for rpi-tools (due the rev bump it is "needed")

**Comment by InuSasha** [comment]
@CvH is there a full description of package.mk format, and is it linked in the CONTRIBUTING.md? (I have not seen it)

**Comment by CvH** [comment]
@InuSasha sadly not yet (my bad - I have to do it asap)

**Comment by chewitt** [comment]
I'll "Ask the audience" for input. Should this be "Adafruit Libraries" or "Adafruit Tools" to match other bundles that we called "tools". RSVP :)

**Comment by InuSasha** [comment]
I decided to "libraries", because there is no executable in the package. Only python modules.

**Comment by MilhouseVH** [comment]
I'd keep it as "libraries", since "tools" could imply complete programmes (scripts, executables etc.)

**Comment by chewitt** [comment]
built and published .. thanks @InuSasha

**Pull request merged**
