### PR TITLE
Python2: Bye bye.

### PR DESCRIPTION
**Pull request by MilhouseVH**
#### ~This is very much a WORK IN PROGRESS!~

This is for use on top of #3906 

1. ~Samba is broken (and not included in the build)~
2. The LibreELEC Settings add-on is broken (included, but not compiled)
3. Expect most other add-ons to also be broken
4. `Python3-3.7.5` is as far as we can go at the moment - Python3-3.8 is not an option (see https://github.com/xbmc/xbmc/issues/16560).

---

1. Cross-compiling Samba since 4.10.0 is not working (originally [`heimdal` cross-compile badness](http://ix.io/1YYP) failure, now [ASN1 syntax errors](http://ix.io/1YYW)), and is temporarily disabled.

    Feel free to try and build Samba. There are several open issues ([1](https://bugzilla.samba.org/show_bug.cgi?id=13846), [2](https://bugzilla.samba.org/show_bug.cgi?id=13856), [3](https://bugzilla.samba.org/show_bug.cgi?id=14164), [4](https://bugzilla.samba.org/show_bug.cgi?id=14132)), affecting different versions from 4.10.x onwards. I'll keep looking into this, but would appreciate any help in case I've done something stupid. (edit: apparently I'm not stupid, and they're all genuine upstream Samba bugs).

2. The current Python version (`python3.7`) is now extracted automatically from the Python3 package in `config/options`. This means we only need to maintain `PKG_PYTHON_VERSION` in one file, `Python3/package.mk`.

3. Many addons are (not surprisingly) broken due to Python3 compatibility issues - missing modules ([Netflix](https://github.com/CastagnaIT/plugin.video.netflix/pull/211), ~YouTube~, etc.), old style exceptions (LibreELEC Settings), and other issues. Due to the inability to compile LibreELEC Settings, the source code is installed as-is and all compilation disabled. This might actually make it easier to debug/modify...

4. Python 3.5+ no longer creates [`.pyo`](https://www.python.org/dev/peps/pep-0488/) files - they're now `.pyc` files instead.

5. I did try building `RPi.GPIO` for Python3, which built and installed successfully, but I had difficulty loading the module on the target device - not sure if we will have issues with CPython-based Python add-ons, or maybe I've overlooked something:
```
rpi22:~/.kodi/addons/virtual.rpi-tools/lib # python
Python 3.7.5 (default, Oct 17 2019, 03:26:44)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import RPi.GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/storage/.kodi/addons/virtual.rpi-tools/lib/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
ModuleNotFoundError: No module named 'RPi._GPIO'
>>> quit()
```
6. Most of the Python3 patches are from [buildroot](https://github.com/buildroot/buildroot/tree/master/package/python3). The remaining patches are adaptations of the previous Python2 cross-compile patches we were using, which still seem to be required.

### CODE REVIEW

**Comment by vpeter4** [comment]
For Samba try version 4.11.1 + `export LDFLAGS="$LDFLAGS -lreadline -lncurses"`.

**Comment by MilhouseVH** [comment]
@vpeter4 I would if it compiled to the point where it was obvious they were required. Is `samba-4.11.1` building for you? At the moment the issues with Samba appear to be much more fundamental as the new Samba build system doesn't actually work very well, at all. The current build issue is that Samba (from the latest `v4.11-test` branch) builds using the bundled `asn1_compile` binary even when configured to use the "system" binary from `heimdal` (ie. `toolchain/bin/asn1_compile`), and the bundled version is failing due to `syntax errors` (see: [bug 14164](https://bugzilla.samba.org/show_bug.cgi?id=14164)).

**Comment by MilhouseVH** [comment]
`samba-4.11.1` also fails due to ASN1 syntax errors. Sadly it never gets far enough to actually link anything for the LDFLAGs to be relevant... :(

**Comment by vpeter4** [comment]
LE master 31cb9c012a20c9d76fdee4269e657823f1bd876d + PR3921, Ubuntu 16.04.6 LTS
Generic build fine with `./scripts/build samba`. But RPi2 not (seems it try to run some program build for target). Will look into.

**Comment by MilhouseVH** [comment]
I've just got `samba-4.10.8` to build for RPi2, will update this PR shortly with a new set of patches to fix Samba etc. The ASN1 issue appears to be a 4.11.0 regression.

**Comment by MilhouseVH** [comment]
I've added `samba-4.10.9` which builds, but don't get your hopes up as the installation to custom destination directory is the next thing to be broken (see [bug #14132](https://bugzilla.samba.org/show_bug.cgi?id=14132)).

**Comment by MilhouseVH** [comment]
> LE master 31cb9c0 + PR3921, Ubuntu 16.04.6 LTS
> Generic build fine with ./scripts/build samba. But RPi2 not (seems it try to run some program build for target). Will look into.

Yes, the issue with 4.11.1 is when cross-compiling ([bug 14164](https://bugzilla.samba.org/show_bug.cgi?id=14164)), as it's ignoring the `--bundled-libraries` option, causing it to cross-compile all the binaries (such as `asn_compile`, `compile_et` which are normally supplied by Heimdal) and then tries to use them in the build. This very clearly fails on non-x86_64, and although it may appear to work when "cross-compiling" x86_64 -> x86_64, it really isn't... :)

Maybe 4.11.x has a working installation to custom `--destdir` - let's hope so!

**Comment by MilhouseVH** [comment]
Updated:
1. Stop deleting `.pyc` files from `dbus-python` and `pygobject` from `.install_pkg` (otherwise we have nothing left to install...)
2. Enable `lzma` support in Python3 target
3. Removed the bogus `pgen` workaround from Python3 package.mk - it appears to have no effect with Python3

**Comment by CastagnaIT** [comment]
for netflix addon two fixes are needed in kodi otherwise it does not work properly
patches to get pycriptodome module working, that is also broken on android/windows
and py reuselanguageinvoker which has been reverted

**Comment by MilhouseVH** [comment]
Hopefully we'll get nightly builds based on latest Kodi master and Python3 out soon enough (maybe without Samba, for now) - hopefully that will help with add-on migration testing/development.

Can you provide a link for the required Kodi patches?

**Comment by CastagnaIT** [comment]
I am new to this environment and have little knowledge of C,
i can link the posts with some info:
https://github.com/xbmc/xbmc/pull/16116#issuecomment-542379419
https://forum.kodi.tv/showthread.php?tid=348495

**Comment by MilhouseVH** [comment]
Thanks. Yes, there's a few rough edges still to sort out with Kodi Pythoh3 support. I'm almost at the point where I think I'm done with adding Python3 support to LibreELEC, we'll see what falls out when testing modules in anger - not sure if we'll have issues with `pycryptodome` as whatever add-ons depend on it usually fail longer before trying to import it... :(

If you're in a position to test your Netflix fork, I can upload a test build later - let me know if you need Generic or RPi2...

**Comment by MilhouseVH** [comment]
Updated.

Hopefully the Python3 changes are pretty much done  with everything compiling correctly. Just need to update (and enable) the `LibreELEC-setttings` addon at some point.

Samba is bumped to 4.11.1 but not yet enabled - although it now builds (with minimal patching) it doesn't install anything (and neither does 4.10.9 - bug [#14132](https://bugzilla.samba.org/show_bug.cgi?id=14132)). Fingers crossed there's a solution for that bug sooner than later.

Unfortunately building `samba-4.9.13` is no longer an option as the `waf` build system won't build at all with Python3, and installing Python2 just to build Samba is not easy (`$TOOLCHAIN/bin/python` now sym links to `python3.7`, and Samba `waf` uses `python` everywhere, when it needs to use `python2` instead).

**Comment by CastagnaIT** [comment]
Yes thanks i can test the addon with the generic build

**Comment by MilhouseVH** [comment]
> Yes thanks i can test the addon with the generic build

Great, please give this Generic build a spin [`#1020l`](http://milhouse.libreelec.tv/builds/testing/Generic/LibreELEC-Generic.x86_64-9.80-devel-20191020211608-%231020l-gc9510d4.tar)

It lacks all Samba functionality, and there is no LibreELEC-Settings add-on (make sure you've enabled ssh before applying the update, or add `ssh` to the kernel command line), but should be otherwise feature complete (latest Kodi master, with "Reusepython" https://github.com/xbmc/xbmc/pull/16812).

**Comment by MilhouseVH** [comment]
I've added a temporary manual `samba` installation workaround for [bug #14132](https://bugzilla.samba.org/show_bug.cgi?id=14132).

The Samba Server build config needed a minor tweak for [bug #14166](https://bugzilla.samba.org/show_bug.cgi?id=14166).

Samba client (Kodi) & server 4.11.1 are now both now enabled, and apparently working fine.

**Comment by CastagnaIT** [comment]
I tried your debug test build
the addon now is installed correctly and seem working

unfortunately there are problems to be solved several things apparently compatible for transition do not work.. so you can't go beyond the password screen

but i can not test in this way takes to me too long time use an external machine (also virtual)
i'll wait for the commits to be included into the master kodi windows build

**Comment by MilhouseVH** [comment]
This is now ready for testing, I've no further changes planned (unless bugs are found etc.)

**Comment by CastagnaIT** [comment]
can you give me a link with a latest build generic update?
samba is enabled?
with windows build still have pycryptodome broken..

**Comment by MilhouseVH** [comment]
@CastagnaIT build #1028 here: https://forum.kodi.tv/showthread.php?tid=343069

**Comment by HiassofT** [comment]
forgot to add: Thanks a lot, @MilhouseVH , for caring about this, you did an awesome job!

**Pull request merged**
