### PR TITLE
mesa: update to mesa-18.2.0

### PR DESCRIPTION
**Pull request by MilhouseVH**

### CODE REVIEW

**Comment by 5schatten** [comment]
@MilhouseVH 
You can remove "-Dtexture-float=true \" too

https://github.com/mesa3d/mesa/commit/66673bef941af344314fe9c91cad8cd330b245eb

**Comment by MilhouseVH** [comment]
Thanks, updated.

**Comment by 5schatten** [comment]
np 👍

**Comment by 5schatten** [comment]
Well okay I already added the xrandr package as dependency but good to know the lib is enough to build it.

**Comment by lrusak** [comment]
Can you please move the libXrandr dependency to the x11 only depends?

**Comment by MilhouseVH** [comment]
> Can you please move the libXrandr dependency to the x11 only depends?

Done

**Pull request merged**
