### PR TITLE
bluez: added patches to support bluetooth on some aml s9xx devices

### PR DESCRIPTION
**Pull request by adamg88**
This PR mainly adds support for QCA9377 to bluez and also corrects an issue with some bcm chips.

### CODE REVIEW

**Comment by lrusak** [comment]
I'm sorry but I'm not into adding some 3000 line out of tree patch.

Is that patch going upstream at all?

**Comment by kszaq** [comment]
FYI The source of the patch is https://github.com/boundarydevices/android_external_bluez/commit/ebe15e8f085c80f42951a10bad2f738c123e5493
I don't think it's been submitted upstream.

**Comment by Raybuntu** [comment]
Not sure what the upstream policy is in bluez but it's probably best to upstream. If it's the same hostile bullshit environment as Kodi or even worse death by age LibCEC we should merge it for the time it's not upstream.

**Comment by chewitt** [comment]
If someone can make the effort to reach-out to the original author and enquire/clarify their plans to upstream that would be appreciated. If it's going to be sent, it's not an issue to add the patch while that happens. If there are no plans then we need to consider the long-term technical debt implications and make a decision. Thanks.

**Comment by adamg88** [comment]
This is ridiculous every PR is a fight rather than thank you. These patches are to benefit end users who currently have non functional Bluetooth.

I have no interest in submitting other people's work upstream and taking responsibility for them.

**Pull request closed without merging**
