### PR TITLE
libprojectM: update to 3.1.12

### PR DESCRIPTION
**Pull request by benpicco**
This bumps the version of projectM to the latest version.

This is unfortunately untested as 

    PROJECT=Generic ARCH=x86_64 scripts/create_addon visualization.projectm

just gets me

```
ERROR: no addons matched for filter visualization.projectm
For more information type: ./scripts/create_addon --help
*********** FAILED COMMAND ***********
addons+=" $(get_addons ${1})"
**************************************
```

and `visualization.projectm` is also not included in `visualization.*` - not sure what I'm doing wrong here (this is also on `master`)

### CODE REVIEW

**Comment by heitbaum** [comment]
Try this: 

`PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy scripts/create_addon visualization.projectm`

It is because of this:
```
if [ "${OPENGL}" = "no" ]; then
  exit 0
fi
```

**Comment by lrusak** [comment]
> Try this: 
> 
> 
> 
> `PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy scripts/create_addon visualization.projectm`
> 
> 
> 
> It is because of this:
> 
> ```
> 
> if [ "${OPENGL}" = "no" ]; then
> 
>   exit 0
> 
> fi
> 
> ```

We should probably change `exit 0` (and any others that may be in the code) to use `die "reason for exit"`. That would make it more clear than just stopping with no reason.

**Comment by benpicco** [comment]
Thank you, that works.
Unfortunately it looks like something about the presets folder changed, compared to `master` I now get

```
find "presets" -path "presets/tests" -prune -o -type d -exec /usr/bin/mkdir -p "/home/benpicco/dev/LibreELEC.tv/build.LibreELEC-Generic-legacy.x86_64-11.0-devel/.sysroot/libprojectM.target//usr/share/projectM/{}" \;
find: 'presets': No such file or directory
```

Btw: Is this `Generic-legacy` because of the GLX (X11) dependency? My original intention was to flip the `--enable-gles` switch to get this running on the Raspberry Pi (or maybe the new driver even support full OpenGL?) but that fails with `#include <GLES3/gl3.h>` not being found.

**Comment by SupervisedThinking** [comment]
Well for which RPi device did you try to build an image? The RPi4 should support GLES 3.0 - others don't. Beside that the addon builds fine for X11

**Comment by benpicco** [comment]
I was hoping I could run it on the RPi3 now with the new driver - [it](https://docs.mesa3d.org/drivers/vc4.html) only supports GLES2/OpenGL 2.1 but there have been patches upstream that report success with this: https://github.com/projectM-visualizer/projectm/pull/399

With the old libprojectM I would get `error: vendored libglm not found` and with the current one I'm getting `fatal error: GL/glx.h: No such file or directory` with `PROJECT=RPi ARCH=arm DEVICE=RPi2`.

For `PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy` it compiles but with the new version something about the handling of the `presets` folder has changed that breaks the `install-data-local` target :confused:

**Comment by SupervisedThinking** [comment]
Well according to your link:
[```These changes enable running ProjectM on hardware which supports only older GLSL versions, such as the VideoCore IV GL implementation used by the Raspberry Pi (versions <=3).```](https://github.com/projectM-visualizer/projectm/pull/399#issue-673356078)

So basically they've lowered the GL requirements not the GLES ones. And the GL path obviously depends on X11/GLX. No clue about the `install-data-local` - the addon builds fine on my system. Could you post the complete build output?

**Comment by benpicco** [comment]
Ah OK - I suppose the ARM image does not include X11 then.

The build output I get with the new version is [build.LibreELEC-Generic-legacy.x86_64-11.0-devel/.threads/logs/184.log](https://paste.ubuntu.com/p/KcdX55dbkR/)

**Comment by heitbaum** [comment]
Reference from: https://forum.libreelec.tv/thread/21612-projectm-2-3-5-1-visualization-addon/?postID=164735#post164735

**Comment by benpicco** [comment]
Ah thank you for the heads up!
Since support for this is actively being worked on and the build system is likely going to change yet again, I'll just close this for now, until there is a new version.

**Pull request closed without merging**
