### PR TITLE
kodi: update to latest master

### PR DESCRIPTION
**Pull request by CvH**
update to latest master

- Generic build + addons are fine

kodi patches were rebased with the new tool, so a lot cosmetic changes due that, next time there should be much less

### CODE REVIEW

**Comment by heitbaum** [comment]
```
=== tested on ===
 18:34:41 up 1 min,  load average: 2.47, 1.01, 0.37
Generic.x86_64-devel-20210130065119-0d57c29
Linux LibreELEC 5.10.11 #1 SMP Sat Jan 30 03:09:32 UTC 2021 x86_64 GNU/Linux
Starting Kodi (19.0-RC1 (18.9.910) Git:bb88e5e1db54844bc27befc7014c8118ae5ca275). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2021-01-30 by GCC 10.2.0 for Linux x86 64-bit version 5.10.11 (330251)
Running on LibreELEC (heitbaum): devel-20210130065119-0d57c29 9.80, kernel: Linux x86 64-bit version 5.10.11
FFmpeg version/source: 4.3.1-Kodi
Host CPU: Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz, 4 cores available
[    0.000000] DMI:  /NUC6i5SYB, BIOS SYSKLi35.86A.0073.2020.0909.1625 09/09/2020
CRenderSystemGL::InitRenderSystem - Version: 4.6 (Core Profile) Mesa 21.1.0-devel, Major: 4, Minor: 6
GL_RENDERER = Mesa Intel(R) Iris(R) Graphics 540 (SKL GT3)
GL_VERSION = 4.6 (Core Profile) Mesa 21.1.0-devel
```

**Comment by CvH** [comment]
added updated libretro addons
picodrive requires now a kitchensink of submodules and libretro provides no releases, so drop picodrive or build it with the git handler

all bumped addons are building

**Comment by chewitt** [comment]
I'd rather drop picodrive or mark broken while a packaging conversation is had with upstream. These things are usually about release tooling and ignorance of the downstream problems caused rather than people deliberately trying to be difficult.

**Comment by SupervisedThinking** [comment]
https://docs.libretro.com/library/picodrive/ -> `Designed to run on weak devices.` it's not really necessary anyway

**Comment by CvH** [comment]
pulled the picodrive commit into own pr, instead of a workaround just nuke it
I guess this is the solution for future libretro problems.
https://github.com/LibreELEC/LibreELEC.tv/pull/5075

**Comment by sixpack58** [comment]
one question reading https://github.com/LibreELEC/LibreELEC.tv/pull/5064/files.

please search for "hasne"

@@ -1774,7 +1774,6 @@ const infomap system_labels[] = {{"hasnetwork", SYSTEM_ETHERNET_LINK_ACTIVE},
@@ -1774,7 +1774,6 @@ const infomap system_labels[] = {{"hasne

is in the last line correct or is it just a display error ? 
it apears to be an edit error.

**Comment by CvH** [comment]
@sixpack58 its correct, just the first x-characters are used for line finding

depending what tool you use its complete or not at generating, but both ways applying cleanly

**Comment by sixpack58** [comment]
> @sixpack58 its correct, just the first x-characters are used for line finding
> 
> depending what tool you use its complete or not at generating, but both ways apply cleanly

my "tool" is an webbrowser (firefox) ;-)

**Comment by CvH** [comment]
I used `./tools/refresh-patches kodi` , the script uses quilt that is designed to rebase patches :)

**Comment by sixpack58** [comment]
> I used `./tools/refresh-patches kodi` , the script uses quilt that is designed to rebase patches :)

well, you are an developer.
I'm just a plain'ol dumb user "visual grepping" the source awaiting a fix for my bug (kodi crashes, currently debugging)
happy coding

**Comment by heitbaum** [comment]
Running on ODROID-N2Plus
```
=== tested on ===
Linux odroid 5.11.0-rc5 #1 SMP PREEMPT Sat Jan 30 12:08:17 UTC 2021 aarch64 GNU/Linux
Starting Kodi (19.0-RC1 (18.9.910) Git:bb88e5e1db54844bc27befc7014c8118ae5ca275).
Running on Amlogic Meson G12B (S922X) Hardkernel ODROID-N2Plus
FFmpeg version/source: 4.3.1-Kodi
Host CPU: ARMv8 Processor rev 2 (v8l), 6 cores available
GL_VERSION = OpenGL ES 3.0 Mesa 21.1.0-devel
```

**Review by chewitt — APPROVED** [review]

**Pull request merged**
