### PR TITLE
added lnbp22.c patch for more power

### PR DESCRIPTION
**Pull request by Ognian**
see https://forum.libreelec.tv/thread-3381-post-25787.html#pid25787
for more info

This patch is from the original driver author, I found it in https://www.spinics.net/lists/linux-media/msg38226.html

I have tested it with TT S2-3650CI and a HH90 rotor and it works.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Needs a rebase as we no longer have a `4.8.12` folder - use `default` instead. Has this been tested with the current 4.9.0 kernel?

Also the other dvb-related patches are `linux-2xx` - can you renumber this patch somewhere in the 200 range?

Adding @cvh to review.

**Comment by CvH** [comment]
ping @trsqr 
this should go upstream i guess - looks like an orphaned/forgotten pr at media_tree

this is impossible to test for me, could also affect various other DVB devices, i trsqr can't vote for a clear yes I would move it at least to LE9

**Comment by trsqr** [comment]
Yes, upstreaming it would be good.

This is affecting only pctv452e driver, that's the only one that uses lnbp22. pctv452e supports only three older devices. I've got no possibility to test this either. Looks fine to me. We could push it to some alpha/beta releases and if we get no complaints then push for the final. Low risk patch in my opinion. The 3 devices affected are:

static struct usb_device_id pctv452e_usb_table[] = {
        {USB_DEVICE(USB_VID_PINNACLE, USB_PID_PCTV_452E)},
        {USB_DEVICE(USB_VID_TECHNOTREND, USB_PID_TECHNOTREND_CONNECT_S2_3600)},
        {USB_DEVICE(USB_VID_TECHNOTREND, USB_PID_TECHNOTREND_CONNECT_S2_3650_CI)},

**Comment by CvH** [comment]
@trsqr tx for review
for the record - affected devices
Pinnacle PCTV Sat HDTV Pro USB (452e)
TechnoTrend TT-connect S2-3600
TechnoTrend TT-connect S2-3650 CI

@Ognian pls do the changes according milhouse and this could get merged, tx !

**Comment by Ognian** [comment]
I would like to make the above changes, but at the moment the 4.9 kernel simply doesn't work.
( see  https://forum.libreelec.tv/thread-3381-post-25787.html#pid25787) What I have found out so far is that when power control is turned on for the pctv452e driver (pctv452e.c the  pctv452e_power_ctrl function is called) the call to mutex_lock fails due to a null pointer... This code was added newly to many dvb-usb drivers in the 4.9 branch, not only to the pctv452e driver; I can't belive that it was not tested at least for some of the other drivers, so maybe this is something specific to the rpi...
Please help

**Comment by chewitt** [comment]
@trsqr any suggestions?

**Comment by MilhouseVH** [comment]
Small nit: the first 30 lines of the patch are using spaces when the underlying file is using tabs. The patch should be changed to use tabs consistently.

s1

**Comment by chewitt** [comment]
Use `rebase -i HEAD~3` to squash the 2nd/3rd commits into the 1st, then update the PR by force pushing changes with `push -f origin lnbp22_patch`

**Comment by Ognian** [comment]
Sorry that this has taken so long...
I decided to do the changes now so you can merge it. The problems with the driver still persist, but they have noting to do with this patch.

**Comment by CvH** [comment]
@Ognian could you pls reword the commit messages (google `git amend`) to fit house style + remove the commit messages from the suqashed commits ? `linux: add lnbp22 rotor patch` or similar

And could you do me a favour and add some comments to the patch (at the beginning) what the patch fixes/or adds that we know in 1yr what the patch fixes and for what hardware. tx

**Comment by Ognian** [comment]
I did the changes 7 day ago, is there still a problem to fix?

**Comment by CvH** [comment]
@Ognian sorry the push notification was eaten by spamfilter
as we merged media_build recently the patch needs to be relocated to `packages/linux-drivers/media_build/sources/media_build/backports/`
idk how good your git knowledge is, if you can't figure out how this is working i could do it for you :)

**Comment by Ognian** [comment]
@CvH i hope I did it right now...

**Comment by CvH** [comment]
@Ognian tx for pr ! 
(a additional patch is needed to "activate" it, that is already in preparation including other stuff)

**Pull request merged**
