### PR TITLE
cleanup: avoid using find command to determine package directory

### PR DESCRIPTION
**Pull request by MilhouseVH**

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I've taken the liberty of extending this a little, by adding a generic `get_pkg_variable` helper which will return the value of any variable for the specified package.

This means `get_pkg_version`, `get_pkg_directory` and `get_build_dir` are all simplified.

If I'm not mistaken, `kernel_path` and `kernel_version` could also be updated to use these new functions as follows:
```
kernel_path() {
  get_build_dir linux
}

kernel_version() {
  get_pkg_version linux
}
```
This change (including the kernel changes above) would ensure that `package.mk` processing is more consistent and doesn't duplicate $PROJECT/$PACKAGES searching/selection, and as much as possible uses only `config/options` to access `package.mk`.

The [xorg-server](https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/x11/xserver/xorg-server/package.mk) package is directly sourcing the `package.mk` of various drivers to determine their version, this could/should also be cleaned up to call `get_pkg_version` instead.

**Comment by MilhouseVH** [comment]
Updated xorg-server to use `get_pkg_version` - it was having to reload it's own package.mk!

**Comment by MilhouseVH** [comment]
@lrusak: updated with `kernel_path` and `kernel_version` changes. Seems to build OK...

**Comment by lrusak** [comment]
LGTM

**Pull request merged**
