### PR TITLE
dvb-update

### PR DESCRIPTION
**Pull request by CvH**
- updates everything to latest
cc to 5.6RC1
dvb-latest to 5.6RC1
digital devices is still disabled because the drivers do not even build for 5.4 (premium hardware, premium support ...)

- switched to self hosted media_build versions and dropped all patches
- changed the way we disabling stuff for building (see https://github.com/LibreELEC/media_build/blob/libreelec/v4l/versions.txt) - allows to build for allwinner etc too (V4L2 stuff get messed up due media_build) , I need to check the options (another pr)
- disabled RC completely (@HiassofT) this is a bit hacky but if you use the IR from you DVB device (that are not too much ppl use) it will use the modules from the normal image ~ may work, may not ?

### CODE REVIEW

**Comment by HiassofT** [comment]
Using the kernel rc modules from newer media tree is probably going to fail as the ABI isn't stable (structs and function parameters change) which will probably lead to a crash.

It should be doable though if you replace the rc-core includes (include/media/rc-core.h, include/media/rc-map.h, maybe a couple of others) in the media tree with the ones from the kernel.

Might need a bit of additional patching (eg if a DVB driver references an RC protocol that's not present in the base kernel yet), but I guess that could be doable without too much effort.

**Comment by CvH** [comment]
rebased against master and updated to 5.6 RC1 trees

**Comment by MilhouseVH** [comment]
@cvh Shall we merge this?

The driverselect add-on needs a bump to add `xbmc.python 3.0.0` support, but I can add this in #4203 (which is where it is needed).

**Comment by CvH** [comment]
merge it away 👍

**Pull request merged**
