### PR TITLE
Decommission PKG_PRIORITY

### PR DESCRIPTION
**Pull request by CGarces**

### CODE REVIEW

**Comment by Kwiboo** [comment]
Suggest you also remove PKG_PRIORITY from the following files in this PR
```
config/path:  PKG_PRIORITY="optional"
packages/devel/popt/package.mk:PKG_PRIORITY="optional"
packages/devel/slang/package.mk:PKG_PRIORITY="optional"
packages/tools/newt/package.mk:PKG_PRIORITY="optional"
```

**Comment by CGarces** [comment]
Done

**Comment by chewitt** [comment]
Thanks :)

**Comment by Kwiboo** [comment]
`config/path` still have a `PKG_PRIORITY` ;)

https://github.com/LibreELEC/LibreELEC.tv/search?utf8=%E2%9C%93&q=PKG_PRIORITY

**Pull request merged**
