### PR TITLE
functions: use openssl passwd in add_user

### PR DESCRIPTION
**Pull request by antonlacon**
Workaround a build error on Debian 11:

Undefined symbol: crypt_r

when importing python:host's crypt module.

@howie-f

### CODE REVIEW

**Comment by heitbaum** [comment]
Follow up fix for #5453

**Comment by howie-f** [comment]
this works like a charm on bullseye and hopefully on any other distro. thx. :+1:  approved

**Comment by CvH** [comment]
@antonlacon pls have a look at https://github.com/LibreELEC/LibreELEC.tv/issues/5757

**Comment by antonlacon** [comment]
Should no longer be needed.

**Pull request closed without merging**
