### PR TITLE
OpenGL: do not fake GL libraries when installer is not supported

### PR DESCRIPTION
**Pull request by zhangn1985**

### CODE REVIEW

**Comment by zhangn1985** [comment]
when installer is not supported, xorg-configure@.service is not run, thus not able to fixup the fake GL libraries, and xorg-launch script also can't find the settings file.

test under H3, with X11 enabled, cursor shows successfully.

**Comment by lrusak** [comment]
why do you want to use x11 on an arm device on LibreELEC?

**Comment by zhangn1985** [comment]
because I want to try OpenGL, but it looks like require X11.

Why OpenGL: https://mesamatrix.net/ you will find mesa has better opengl support than gles, on ARM GPUs.

and this project focus on mesa, thus use opengl is more reasonable try.

**Comment by lrusak** [comment]
> because I want to try OpenGL, but it looks like require X11.
> 
> 
> 
> Why OpenGL: https://mesamatrix.net/ you will find mesa has better opengl support than gles, on ARM GPUs.
> 
> 
> 
> and this project focus on mesa, thus use opengl is more reasonable try.

Define "better support". What's does OpenGL offer that you need?

We have optimized Kodi for running on arm platforms using OpenGL ES.

Using the x11 build you won't have any hardware video rendering available.

**Comment by zhangn1985** [comment]
OK, just test it with H3, doesn't mean the patch is useless. if someone don't build X86_64 with installer support, it will not boot to GUI, right?

**Comment by chewitt** [comment]
It's a bit hypothetical because the Generic x86_64 image requires (and has always included) installer support

**Comment by zhangn1985** [comment]
this makes the option possible. :)

**Comment by zhangn1985** [comment]
IMG_20210127_212909
another reason which I try opengl is game.  I know no good chioce to use it for game. but why not. 
H3 is default to use gles, no game can show, while use opengl, 2048 main screen is shown. and pp interrupt is running. it uses lima to render. 

but I don't have a real game controller., thus don't know how to really play it.

**Comment by SupervisedThinking** [comment]
Well what's the general purpose of sacrificing GLES in favor of GL for a mediacenter distribution targeting  Kodi? If you need a desktop environment you could still use wayland which uses GLES too. Beside that if you want to play some games on your SBC you should probably have a look at https://github.com/libretro/Lakka-LibreELEC/

**Comment by zhangn1985** [comment]
I know Lakka, it's for game. but LibreELEC provides game emulation, why not make it work?
and why I want to try GL, because, on H3, Lakka uses GL.

and at same time I also build GLES, thus not break media playback.

does it sound like better?

**Comment by lrusak** [comment]
> I know Lakka, it's for game. but LibreELEC provides game emulation, why not make it work?
> and why I want to try GL, because, on H3, Lakka uses GL.
> 
> and at same time I also build GLES, thus not break media playback.
> 
> does it sound like better?

LibreELEC provides game emulation through kodi. Kodi depends on GLES or GL. We don't support running emulators natively.

**Comment by lrusak** [comment]
I appreciate the effort you put into this, however, this moves LibreELEC in the wrong direction. 

I'm all about adding flexibility but only if it's useful and this is not useful to LibreELEC (in terms of Kodi).

I hope you understand.

**Comment by SupervisedThinking** [comment]
@zhangn1985 could you please guide me to the package where the Allwinner H3 boards use OpenGL? The master & mainline branch use the prop. driver package libmali:

https://github.com/libretro/Lakka-LibreELEC/blob/master/projects/Allwinner/devices/H3/options#L41
https://github.com/libretro/Lakka-LibreELEC/blob/master/projects/Allwinner/options#L44

while the 2.3.2 branch uses allwinner-libmali

https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-2.3.2/projects/Allwinner/options#L103

So personally I don't understand why you would assume they use GL, llvmpipe, swrast, X11 etc. pp?

**Comment by zhangn1985** [comment]
@SupervisedThinking thanks for asking.

**Pull request closed without merging**
