### PR TITLE
snapcast: add streaming from kodi

### PR DESCRIPTION
**Pull request by awiouy**

### CODE REVIEW

**Comment by awiouy** [comment]
To stream from Kodi:
1. In `Add-ons/My addons/Services/Snapserver/Configure` set `Preset` to `Kodi`
2. In `Settings/System/Audio` set `Audio output device` to `PULSE: Default` or `PULSE: Linux FIFO sink /tmp/snapfifo`
3. In `Add-ons/My addons/Services/Snapclient/Configure` increase `Latency` (`600` somehow works here, your mileage may vary) in order to (attempt to) synchronise audio and video; this must be done for all Snapclients

Remarks:
- Sound quality feels inferior
- Boot time feels longer

**Comment by awiouy** [comment]
meh... snapserver should wait for pulse

**Comment by awiouy** [comment]
# Snapcast
Snapcast is a multi-room client-server audio player, where all clients are time synchronized with the server to play perfectly synced audio. On LibreELEC it comes as two addons: Snapserver to stream AirPlay, Kodi or Spotify, and Snapserver to play.

# Installation

## Snapserver
Install Snapserver on one system in your network. Snapserver also exists for systems other than LibreELEC.

## Snapclient
Install Snapclient on every system in your network you want to stream to. Snapcast also exists for systems other than LibreELEC.

# Configuration

## Snapserver for LibreELEC
By default, Snapserver streams AirPlay. You can select a stream in the settings of the addon from Airplay, Kodi or Spotify.

### AirPlay
In the settings of the addon, select AirPlay Then check with a phone or tablet that Snapcast is available.

### Kodi
It works but is still quite capricious. Expect trial and error.

Before streaming Kodi, install Snapserver and reboot LibreELEC. After rebooting you should find PULSE: Snapserver in Settings/System/Audio/Audio output device. Do not select it yet. First select Kodi in the settings of the addon. Then select PULSE: Snapserver in Settings/System/Audio/Audio. After that, you should be able to select any audio output device without rebooting.

Before you switch to another stream in the settings of the addon, make sure you have selected a device other than PULSE:

You will notice that audio and video are not synchronized. This can easily be fixed during video playback by setting Audio offset to Ahead by 1.000s in Settings/Audio settings while playing. You may also wish to disable Play GUI sounds in System/Settings/Audio.

### Spotify
In the settings of the addon, select Spotify. Then check with a Spotity app that Snapcast is available.

## Snapclient for LibreELEC

### Sound Card
First, start streaming from the source you have set in Snapserver. If you are lucky, Snapclient will start playing.

If Snapclient does not play or uses a wrong sound card, go the settings of the addon. There, select "List sound cards" to list available sound cards, note the index of the card you wish Snapclient to use (3 for example), and set it in the "Sound Card" field. Snapclient should play after you change the settings with the "OK" button.

If "List sound cards" lists no card or only the null sound card you will wnat to add a sound card. For a Rasberry Pi, you can do this in the Raspberry Pi tab of the settings by setting "Manage onboard audio", selecting a playback mode and changing the settings with the "OK" button. When you return in the settings of the addon you should be able to list and select a card.

Enjoy!

**Comment by awiouy** [comment]
I am done. Please review and test.

**Comment by CvH** [comment]
lgtm 👍  (no runtime test as no usecase)

**Comment by awiouy** [comment]
This can be merged, no?

**Comment by diabl0w** [comment]
the alsa-plugins are useless, alsa-lib is hardcoded with a plugindir of /usr/lib/alsa and this addon installs alsa-plugins to its own kodi addon directory... setting LD_LIBRARY_PATH does not affect alsa and so it isnt fixing anything

**Pull request merged**
