### PR TITLE
scripts/create_addon: fix typo of official

### PR DESCRIPTION
**Pull request by CvH**
`scripts/create_addon official` was not working

### CODE REVIEW

**Comment by wwark** [comment]
Hi,

This change needs also an update of this wiki: https://libreelec.wiki/compile i think

` Compile every LE add-on

PROJECT=Generic ARCH=x86_64 script/create_addon offical`

Thanks,
Wwark

**Comment by CvH** [comment]
@wwark tx for pointer, fixed

**Comment by wwark** [comment]
Hi,
Another point, there is a missing 's' at the end of script on all commands 'script/create_addon' in the wiki https://libreelec.wiki/compile.

Thanks,
Wwark

**Comment by CvH** [comment]
@wwark tx a lot, fixed

**Pull request merged**
