### PR TITLE
vdr-addon: update plugins

### PR DESCRIPTION
**Pull request by CvH**
- add streamdev HEVC support
- update VNSI to 1b96c6a
- update Sat>IP plugin to db0c18b

### CODE REVIEW

**Comment by chewitt** [comment]
@CvH let me know when properly tested

**Comment by piotrasd** [comment]
please wait with merge i will try update each plugin to support VDR 2.3.1 etc. 
sometimes patches are on forum not in git sources ... so i need litle time to collet them

**Comment by piotrasd** [comment]
update of progress:
- VDR: updated to 2.3.1
- VDR: added 2 patches from patchwork
one reduce CPU usage when bufforing, second fix typo
more here: 
https://patchwork.linuxtv.org/patch/33421/
https://patchwork.linuxtv.org/patch/34432/
also works for VDR 2.2.0

- updated plugins to support VDR v2.3.1:
eepg
epgsearch
iptv
satip
vnsiserver
wirbelscan (this need patch for compiling, author changed makefile so we need adjust to our toolchain, when i made test and compiled from  VDR folder source eveything was fine)

plugins dropped:
epgfixer
live (this we can replace for webapp which work with restfuliapi, more here:
https://github.com/hannemann/vdr-webapp/
http://www.vdr-portal.de/board1-news/board101-news-archiv/p1233743-announce-mobil-browser-gestütztes-frontend-für-vdr-oder-restfulapi-client/


depends:
- libdvbcsa added patch for "NEON support on aarch64"

Possible also add for VDR: Device power saving feature
for VDR 2.2.0 and 2.3.1
https://patchwork.linuxtv.org/patch/36497/

my work (but this is only draft not for PR)
https://github.com/piotrasd/LibreELEC.tv/commits/vdr_4k

**Comment by chewitt** [comment]
@CvH has this been tested yet?

**Comment by CvH** [comment]
@chewitt works for me 👍

**Pull request merged**
