### PR TITLE
docker: updated to 19.03.13

### PR DESCRIPTION
**Pull request by heitbaum**
https://github.com/docker/docker-ce/releases/tag/v19.03.13

I have rebased the proposed https://github.com/LibreELEC/LibreELEC.tv/pull/3889 against Master with the latest 19.03.13 with containerd 1.3.7. I used @5schatten patches as a based line. This Docker has been tested on Generic.

### CODE REVIEW

**Comment by CvH** [comment]
What is `docker-100.03-remove-marshaljson.patch` doing/fixing ?

**Comment by heitbaum** [comment]
> What is `docker-100.03-remove-marshaljson.patch` doing/fixing ?

Hi @CvH - it’s the reversal of the Patch of builder.go from https://github.com/moby/moby/commit/85733620ebea3da75abe7d732043354aa0883f8a#diff-5bd491fa0dcc561cb6d449b64d08a79c851683d0c285589d7b778b47922f45b2
The build fails on f.Keys(), as per the commit notes it is slated for 20.01 and is to futureproof. I would expect that we will be able to remove our patch once updated in docker-ce.

**Comment by CvH** [comment]
pr3246??? https://github.com/LibreELEC/LibreELEC.tv/pull/3246

looks wrong

**Comment by heitbaum** [comment]
> pr3246??? #3246 - looks wrong

That patch file was directly from the @5schatten branch, which is why I missed it in the first pull - https://github.com/LibreELEC/LibreELEC.tv/pull/3889/files#diff-36554b5f90e5a43fb220b2891c7d57cad8574aaf172cee619562bc5f0a2f8add 
Definitely needed to compile docker.

**Comment by CvH** [comment]
https://github.com/containerd/containerd/commit/bf5a4246798a6c1b1b0af4810fbb2d53eac91112 belongs to https://github.com/containerd/containerd/pull/3246

Looks like this was a early version of the final fix, the containered version 1.3.7 has that fix already so it is not needed to include (I guess this won't build/merge at all). So save to drop I think.

**Comment by heitbaum** [comment]
The included containerd within the docker-19.03.13.tar.gz  is bundled with 1.2.0, thus the need for the patch against docker.

rudi@a1f14a68ce8f:~/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/build/docker-19.03.13/.gopath/src/github.com/containerd/containerd/version$ grep "Version =" version.go 
        Version = "1.2.0+unknown"

The patch did successfully merge :
rudi@a1f14a68ce8f:~/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/build/docker-19.03.13/.gopath/src/github.com/containerd/containerd/runtime/v1/shim/client$ ls -l          
total 20
-rw-rw-r-- 1 rudi rudi 8931 Nov  8 12:33 client.go
-rw-rw-r-- 1 rudi rudi 1194 Sep 16 16:52 client_linux.go
-rw-rw-r-- 1 rudi rudi  842 Sep 16 16:52 client_unix.go

**Comment by CvH** [comment]
@heitbaum sorry my bad, forgot about the docker building glory

**Review by CvH — APPROVED** [review]
tx

**Pull request merged**
