### PR TITLE
openssl: update to 1.1.1+

### PR DESCRIPTION
**Pull request by InuSasha**
- Attention: API breakage

### CODE REVIEW

**Comment by InuSasha** [comment]
rebased against master, after porting partials to #2871

**Comment by InuSasha** [comment]
Update to LTS version 1.1.1
There are good chances to get openssl 1.1.1 support in openssh :)

**Comment by InuSasha** [comment]
use openssh devel. it includes the new openssl 1.1.x support.

**Comment by InuSasha** [comment]
* fix oscam
* switch to openssh 7.9
* rebase on master

only rtmpdump is open, but i prefer to drop `rtmps://` support

**Comment by InuSasha** [comment]
* rebased against master
* updated to openssl 1.1.1a
* build test an RPi2 successful, ssh connection test successful

**Comment by antonlacon** [comment]
If this is due to be merged soon, openssl-1.1.1b was released a few days ago.

**Comment by CvH** [comment]
would be nice to merge this with 1.1.1b sooner then later - we kind of "waiting" for the ABI breakage at the addon department

**Comment by InuSasha** [comment]
updated to openssl 1.1.1b
build tested for RPi2 and Generic

**Comment by MilhouseVH** [comment]
Can you check the `oscam` patch, it's not applying:
```
UNPACK      oscam
    APPLY PATCH (common)      packages/addons/service/oscam/patches/oscam-01-revision.patch
patching file config.sh
    APPLY PATCH (common)      packages/addons/service/oscam/patches/oscam-02-link-with-ludev.patch
patching file CMakeLists.txt
patching file utils/CMakeLists.txt
    APPLY PATCH (common)      packages/addons/service/oscam/patches/oscam-03-pcsc-pthread.patch
patching file CMakeLists.txt
    APPLY PATCH (common)      packages/addons/service/oscam/patches/oscam-04-openssl-1.1.1.patch
patching file cscrypt/mdc2.c
Hunk #1 FAILED at 37.
1 out of 1 hunk FAILED -- saving rejects to file cscrypt/mdc2.c.rej
```

**Comment by CvH** [comment]
@MilhouseVH @InuSasha looks like the patch could be dropped, it is already present at the version we are currently using

**Comment by InuSasha** [comment]
yeah patch can dropped. i pushed the drop.
I started a build of all addons, for RPi2 and Generic.

**Comment by MilhouseVH** [comment]
Thanks, oscam builds OK now.

**Comment by MilhouseVH** [comment]
If this can be rebased, I'll merge it.

**Comment by CvH** [comment]
@InuSasha okay that gone wrong ... tried githubs resolve function, doesn't works like I though -.-

**Pull request merged**
