### PR TITLE
virtio-gpu support (qemu/kvm)

### PR DESCRIPTION
**Pull request by lrusak**
This adds support for using the host GPU for HW accell in qemu/kvm without having to passthrough the host GPU.

It's a pretty minimal change so I think it's acceptable

Imgur

I had this running in libvirt and virt-manager
```
[    2.204886] [drm] Initialized
[    2.205561] [drm] pci: virtio-vga detected
[    2.205917] [drm] virgl 3d acceleration enabled
[    2.207563] [drm] virtio vbuffers: 272 bufs, 192B each, 51kB total.
[    2.294786] virtio_gpu virtio0: fb0: virtiodrmfb frame buffer device
[    2.294824] [drm] Initialized virtio_gpu 0.0.1 0 on minor 0
```
```
[384120.593] (II) modeset(0): [DRI2] Setup complete
[384120.593] (II) modeset(0): [DRI2]   DRI driver: virtio_gpu
[384120.603] (II) AIGLX: Loaded and initialized virtio_gpu
[384120.603] (II) GLX: Initialized DRI2 GL provider for screen 0
```

To use this you need the following:

`/etc/libvirt/qemu.conf`
```
cgroup_device_acl = [
    "/dev/null", "/dev/full", "/dev/zero",
    "/dev/random", "/dev/urandom",
    "/dev/ptmx", "/dev/kvm", "/dev/kqemu",
    "/dev/rtc","/dev/hpet", "/dev/vfio/vfio",
    "/dev/dri/renderD128"
]
```
and in the machine xml
```
    <graphics type='spice'>
      <listen type='socket' socket='/tmp/spice.socket'/>
      <gl enable='yes'/>
    </graphics>
    <video>
      <model type='virtio' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
```

ref, https://www.kraxel.org/blog/2016/09/using-virtio-gpu-with-libvirt-and-spice/

### CODE REVIEW

**Comment by lrusak** [comment]
@piotrasd know of anyone else that can test this? any unraid qemu users perhaps?

**Comment by MilhouseVH** [comment]
This is in last night's #0207 test build if anyone needs a download.

**Comment by piotrasd** [comment]
ok i will post on unraid forum ;)

**Comment by lrusak** [comment]
@piotrasd any news?

**Comment by llonca13** [comment]
I was trying to test it on my Unraid server but im not able to install LE on it (any version,official 8.0 etc).I tried multiple guides and all end the same (black screen after installation).If anyone can package it as a bootable img (like the unRaid 7.0.1 version) i will test it ALOT.Thanks

**Comment by lrusak** [comment]
@llonca13 you will only be able to use the Generic build and you have to use GPU passthrough for it to work.

**Comment by llonca13** [comment]
i have gpu passthrough working in windows and osx.but i cant boot LE after install(with gpu,with vnc..).idk why.im doing something wrong.if you can install this build to any hard disk image(img,qcow2,vmdk) i will test it..

**Comment by llonca13** [comment]
i also tried putting tar.gz to LE 7.0.1 (unraid build from templates that is working fine) but it could't update.Some error came up i dont remember

**Comment by MilhouseVH** [comment]
@llonca13 Are you building yourself? If the builds you are testing don't include this PR then they're unlikely to work. As this PR is not merged you won't find it in any official releases.

You will however find it it this LE9/Kodi 18 build: http://milhouse.libreelec.tv/builds/master/Generic/LibreELEC-Generic.x86_64-9.0-Milhouse-20170306061816-%230305-g4ba2169.tar

It's not a bootable image, but you can create this yourself:
1) Create a USB boot stick using the official LibreELEC 8.0 img - write it using the USB SD Creator
2) Using any x86_64 PC, boot from the LE8 USB, booting into the `run` mode (type `run` at the boot prompt)
3) Once LE8 is booted and Kodi 17 is running, copy the above tar file into the Upgrade folder and reboot (each time the system reboots allow it to use the default boot mode, which should now be `run`)
4) Once the system is successfully upgraded to the new LE9 build you can use it to install a clean system on your UnRaid machine using the `installer` mode (type `installer` at the boot prompt)

**Comment by lrusak** [comment]
probably good to go in as @MilhouseVH has had it in his builds for a while

**Comment by llonca13** [comment]
Sorry guys i planned to test it this weekend but didnt have time

**Comment by cmgraz** [comment]
Tested successfully on unRAID using Millhouse directions on how to build with the bootable USB.  It's slow obviously, but it works:





I initially was poking around to find a solution for Krypton.  This however as advertised, installed 9.0 which was Kodi 18.  Is there a Milhouse build that does the same thing as above, allowing a user to run LibreELEC without a GPU, but do so on Kodi 17?

**Comment by lrusak** [comment]
@cmgraz it looks like you are running without hw acceleration. That's probably why it's so slow. You need to enable the virgl 3D acceleration in the qemu xml file. See the sample xml in the original post.

You can check the Xorg.0.log to see if it gets enabled properly.

**Comment by cmgraz** [comment]
I'll check!  To my original question.  I'm running this as the sole purpose of being a library updater running 24/7.  Is there a way to get this same type of functionality, but on Kodi 17?

**Comment by chewitt** [comment]
You can apply the changes in this PR to your own Krypton build. There is nothing official. Further Q's and support via the forums please.

**Pull request merged**
