### PR TITLE
dbus: drop unused package (replaced by dbussy)

### PR DESCRIPTION
**Pull request by heitbaum**
- LibreELEC-settings: remove previous dbus dependancies - pygobject dbus-python
- dbus-glib: drop unused package (replaced by dbussy)
- dbus-python: drop unused package (replaced by dbussy)
- pygobject: drop unused package (replaced by dbussy)

### CODE REVIEW

**Review by bantilan — CHANGES_REQUESTED** [review]
Tested this PR on Asus Tinkerboard, the PR causes a lag (unable to press anything) and the "LibreELEC" introduction box won't show during first time installation.

**Comment by bantilan** [comment]
Sorry, couldn't spot which of these causes the lag, the lag still exist on the following PR:

- #4961 
- #4982 
- #5020 
- #5022 
- #5068 

After reverting those PR, the lag has gone.

Tested on Asus Tinkerboard and RPI R3 b+

**Comment by heitbaum** [comment]
Hmm strange. I believe that gobject is no longer in the LibreELEC settings package. So that shouldn’t be it. I haven’t done a fresh install for a week or so, but last I did so on the Odroid N2. I’ll try and grab a machine tomorrow and do a clean install on a machine.

**Comment by heitbaum** [comment]
Update now that #5194 has been committed.

**Review by chewitt — APPROVED** [review]

**Pull request merged**
