### PR TITLE
alsa-plugins: reintroduce package, only build the pulse plugin

### PR DESCRIPTION
**Pull request by awiouy**
This reintroduces the `pulse` alsa-plugin to the image, for a total of 71 kilobytes for RPi2

### Motivation
This enables snapclient and other programs that output to alsa only to:
- share audio devices used with pulseaudio, eg by Kodi,
- output to Bluetooth through pulseaudio

The above can be achieved by a user or an addon simply by adding the following lines to `/storage/.config/asound.conf` and selecting the corresponding device:
```
pcm.pulse {
    type pulse
    hint {
        show on
        description "PulseAudio Sound Server"
    }
}
ctl.pulse {
    type pulse
}
```

### Alternatives
Alsa is currently built with `--with-plugin-dir=/usr/lib/alsa` and therefore expects plugins to be in `/usr/lib/alsa`. All my attempts to add them elsewhere, ie somewhere in `/storage`, have failed.

Alternatives I could think of are:
1. ~~Build alsa packages with a `--with-plugin-dir` flag pointing somewhere in `/storage`~~
2. Adapt the programs to output to pulseaudio instead of or in addition to alsa

### Status
I discussed this with lrusak, who is of the opinion that alternative 2 is the only option for LibreELEC. I am however neither capable to implement this option, nor willing to implement it, especially since redirecting alsa to pulseaudio is the purpose of the `pulse` alsa-plugin, see [here](https://wiki.archlinux.org/index.php/PulseAudio#ALSA).

I therefore submit this pull request, in the hope that someone will help us to find a compromise.

### CODE REVIEW

**Comment by HiassofT** [comment]
I have no objections to adding the alsa pulse plugin, this seems to be the easiest way.

Moving the plugindir to storage won't work as this would break the alsa-lib plugins - alsa-lib only searches in a single directory for plugins.

**Comment by awiouy** [comment]
Thank you for your feedback @HiassofT

**Comment by vpeter4** [comment]
> Alsa is currently built with --with-plugin-dir=/usr/lib/alsa and therefore expects plugins to be in /usr/lib/alsa. All my attempts to add them elsewhere, ie somewhere in /storage, have failed.

I'm not sure if this is the same problem but I had some similar issue with jackd addon. There i was using this in asound.conf to load some shared library
```
pcm_type.jack {
  lib "/storage/.kodi/addons/service.audio.jack/lib/alsa/libasound_module_pcm_jack.so";
}
```
My complete [asound.conf](https://pastebin.com/3Hyf34Ai).

**Comment by awiouy** [comment]
It works, thanks!

**Comment by awiouy** [comment]
Closed in favor of #2716

**Pull request closed without merging**
