### PR TITLE
decommission PKG_REV for packages

### PR DESCRIPTION
**Pull request by awiouy**
PKG_REV is only used for addons

### CODE REVIEW

**Comment by awiouy** [comment]
I rebased this against current master

**Comment by awiouy** [comment]
Let me know if we want to merge this, and I will rebase again.
Otherwise, close it.

**Comment by vpeter4** [comment]
I think we should remove this variables and clean up the packages because they are not needed anyway.

**Comment by awiouy** [comment]
Ready to merge

**Pull request merged**
