### PR TITLE
gcc: update to 14.1

### PR DESCRIPTION
**Pull request by heitbaum**
Fixes:
- ~~game.libretro.mame2003_plus~~
  - ~~https://github.com/libretro/mame2003-plus-libretro/issues/1721~~
- ~~game.libretro.atari800~~
  - ~~https://github.com/libretro/libretro-atari800/issues/94~~
  - ~~Upstream patch (to be merged) included https://github.com/libretro/libretro-atari800/pull/92~~
- ~~game.libretro.bluemsx~~
  - ~~https://github.com/libretro/blueMSX-libretro/issues/169~~
  - ~~https://github.com/libretro/blueMSX-libretro/pull/170~~
  - ~~https://github.com/libretro/blueMSX-libretro/pull/167~~
- game.libretro.bk
  - https://github.com/xttx/bk-emulator/issues/1
  - https://github.com/libretro/bk-emulator/pull/24
  - Workaround applied
  - #libretro-bk: fix gcc-14 build
- ~~game.libretro.uae~~
  - ~~https://github.com/libretro/libretro-uae/issues/656~~
  - ~~Upstream patch included https://github.com/libretro/libretro-uae/pull/657~~
  - ~~Workaround applied~~
  - ~~`#workaround gcc-14 erroring with incompatible pointer type`~~
  - ~~`TARGET_CFLAGS+=" -Wno-incompatible-pointer-types"`~~
- network-tools
  - ncftp - email sent to ncftp support
  - Fix applied
  - ncftp: define HAVE_STDLIB_H fixes gcc-14 missing header 
  - Workaround applied
  - `#workaround gcc-14 erroring with incompatible pointer type`
  - `CFLAGS+=" -Wno-incompatible-pointer-types"`
- ~~dvb-tools~~
  - ~~t2scan~~
    - ~~https://github.com/mighty-p/t2scan/issues/16~~
    - ~~https://github.com/mighty-p/t2scan/pull/15~~
- ~~mariadb (a single test failure)~~
  - ~~https://jira.mariadb.org/browse/MDEV-34072~~
  - ~~event.h fix added~~
- ~~kodi (for 32 bit targets)~~
  - ~~https://github.com/xbmc/xbmc/issues/25221~~
  - ~~#8899~~
- ~~gcc:host~~
  - ~~libsanitizer doesn’t build~~
  - ~~patch added~~
  - ~~gcc regression https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115153~~

Required patches/changes - all upstreamed:
- hid_mapper: fix gcc-14 build
- argtable2: fix gcc-14 build
- tsdecrypt: fix gcc-14 build
- opencaster: fix gcc-14 build
- audiodecoder.usf: fix gcc-14 build
- pvr.stalker: fix gcc-14 build
- rapidjson: fix gcc-14 build
- screen: fix gcc-14 build
- kodi: fix gcc-14 build
- media-driver: workaround for gcc-14.1 change
  - https://github.com/intel/media-driver/issues/1797
- bluez: fix gcc-14 build
- lirc: fix gcc-14 build
- ~~mariadb-connector-c: Fix GCC 14 -Wcalloc-transposed-args~~
  - ~~Revert "mariadb-connector-c: Fix GCC 14 -Wcalloc-transposed-args"~~
  - ~~Now upstream in 3.3.10~~
- libcdio: workaround gcc-14 error
  - https://savannah.gnu.org/bugs/?65751
- zip: fix gcc-14 build
- ncurses: compile with --enable-sigwinch
- libretro-snes9x: update to githash 3265c0a
- libretro-prboom: update to githash ab05295
- libretro-mame2000: update to githash 905808f
- libretro-mame2003_plus: update to githash ab725a7
- t2scan: fix gcc-14 build
- libretro-bk: fix gcc-14 build
- libcdio: workaround gcc-14 error on 32-bit targets
- ncftp: define HAVE_STDLIB_H fixes gcc-14 missing header
- ncftp: workaround gcc-14 error incompatible-pointer-types
- mariadb: fix gcc-14 build
- libretro-bluemsx: update to githash 0dcb73a
- gcc: 14.1.0: revert Arm: Block predication on atomics [PR111235]
- libretro-atari800: update to githash 8bfa3b8
- libretro-uae: update to githash 3432007

### CODE REVIEW

**Comment by heitbaum** [comment]
@jernejsk - I note you fixed t2scan last time. If you could have a look at the 2 below if you have time.
- https://github.com/mighty-p/t2scan/issues/16
- https://github.com/mighty-p/t2scan/pull/15

**Comment by vpeter4** [comment]
> * libsanitizer doesn’t build

You did notice that this is same error like with kodi?

**Comment by heitbaum** [comment]
> > * libsanitizer doesn’t build
> 
> You did notice that this is same error like with kodi?

I built all arch/device combinations with your patch for kodi:target. I’ll try and relook at libsanitizer now that there is some idea of where / what to look for.

**Comment by heitbaum** [comment]
> > * libsanitizer doesn’t build
> 
> You did notice that this is same error like with kodi?

Looks like you pinpointed the issue:
- 9cfa84fd7236f152ae468431ba08ee02505618cb
All builds are now working.

**Review by CvH — APPROVED** [review]

**Pull request merged**
