### PR TITLE
[le11] nextpvr: update to 6.1.1

### PR DESCRIPTION
**Pull request by emveepee**

### CODE REVIEW

**Comment by emveepee** [comment]
Can you mark as do not release, pending update to 6.1.1 at the source

**Comment by emveepee** [comment]
@heitbaum since PR 7012 was not released, I include this update in it

**Comment by heitbaum** [comment]
> @heitbaum since PR 7012 was not released, I included this update in it

👍 is nextpvr 6.1.1 ready to go now?

**Comment by emveepee** [comment]
> > @heitbaum since PR 7012 was not released, I included this update in it
> 
> 👍 is nextpvr 6.1.1 ready to go now?

It was released yesterday but the special link for LE appears not to be working at the moment.  That should be fixed soon, and I wouldn't block the release since new users can't use PVR in LE11 at the moment because of a backend issue until LE pulls the current Nexus code changes.

**Comment by emveepee** [comment]
@heitbaum it is working now.

**Review by heitbaum — APPROVED** [review]

**Pull request merged**
