### PR TITLE
mesa: make it possible to enable llvmpipe

### PR DESCRIPTION
**Pull request by zhangn1985**

### CODE REVIEW

**Comment by SupervisedThinking** [comment]
Purpose? Running a software rasterizer on a platform which does neither support GL nor GLES?

**Comment by zhangn1985** [comment]
when lima is the only OpenGL provider, kodi will refuse to startup, due to GLX vinfo is NULL.
add swrast to just make kodi start. and finally kodi will use lima.

**Comment by zhangn1985** [comment]
I will push H3 OpenGL patches.

**Comment by SupervisedThinking** [comment]
Well you actually see the aftermath of these changes? Kodi es optimzed for GLES on SBCs so once you switch to X11 & OpenGL you build llvmpipe which is afaik a software(!) rasterrizer used for system where no suitable hardware acceleration is present. Again whats the prupose? Running a single game? LibreELEC is focused on Kodi so mediacenter usecases, lakka is focused on retro gaming.
If you want to mix those usecase then have a look at my stuff https://github.com/SupervisedThinking/LibreELEC-RR/tree/master-rr but for upstream LE these changes are mostly useless.

**Comment by lrusak** [comment]
see my comment here for closing this https://github.com/LibreELEC/LibreELEC.tv/pull/5045#issuecomment-768597406

further, I don't see any point in trying to use a sw renderer (cpu only) for LibreELEC on arm devices.

**Pull request closed without merging**
