### PR TITLE
u-boot: build tools to provide mkimage for host

### PR DESCRIPTION
**Pull request by adamg-xda**
This is required for PR #2261 

@HiassofT @MilhouseVH @kszaq @Raybuntu

### CODE REVIEW

**Comment by adamg-xda** [comment]
@Kwiboo you will have to update rockchip branch as well following merge

**Comment by MilhouseVH** [comment]
The `u-boot:host` dependency in `toolchain` is wrong as you don't need `u-boot` (host) unless you're creating a u-boot image. So in that sense `u-boot` (host) is not a hard `toolchain` dependency.

I would think this is better:
```
diff --git a/scripts/image b/scripts/image
index 6254bc2..c6312b8 100755
--- a/scripts/image
+++ b/scripts/image
@@ -181,6 +181,9 @@ $SCRIPTS/install network
 # Virtual image creation support
 [ "$PROJECT" = "Generic" ] && $SCRIPTS/install virtual

+# u-boot support
+[ -n "$UBOOT_SYSTEM" ] && $SCRIPTS/install u-boot:host
+
 # Installer support
 [ "$INSTALLER_SUPPORT" = "yes" ] && $SCRIPTS/install installer

```
as now you'll only be building `u-boot` (host) when it is needed.

**Comment by adamg-xda** [comment]
@MilhouseVH this commit is in relation to the incoming S905 project which does not use the UBOOT_SYSTEM variable

**Comment by MilhouseVH** [comment]
OK then adapt the logic to suit everyone - what I posted is just an example.

**Comment by adamg-xda** [comment]
I had adapted it previously and my recommendations where rejected, so we are at somewhat of an impasse

**Comment by HiassofT** [comment]
How about an BOOTLOADER="u-boot" check then?

Packages should only be built and installed when they are really needed

**Comment by adamg-xda** [comment]
@HiassofT I totally agree but it was yours and @kszaq suggestion to add it to toolchain so the option would be to add an `if` statement in the toolchain product.mk

**Comment by HiassofT** [comment]
$TOOLCHAIN directory and the toolchain package are 2 different things.

The toolchain packlage really is only the core stuff, like compiler.

The u-boot:host build/install is fine, but it should be invoked conditionally (eg in scripts/image) when it's needed

**Comment by adamg-xda** [comment]
Ok I have rebased it for conditional building now

**Comment by MilhouseVH** [comment]
In your S905 PR you are calling `mkimage` which will (after this PR) come from the `u-boot` (host) package, here: https://github.com/adamg-xda/LibreELEC.tv/blob/1a818170b507cc40c64343e0b33fded0b19e2325/scripts/mkimage#L268

If you want to call `mkimage` then you must have already built `u-boot` (host). In which case the condition that leads you to execute `mkimage` is the same condition that causes you to build `u-boot` (host). Right?

Revising my previous example:
```
diff --git a/scripts/image b/scripts/image
index 6254bc2..11b0271 100755
--- a/scripts/image
+++ b/scripts/image
@@ -181,6 +181,9 @@ $SCRIPTS/install network
 # Virtual image creation support
 [ "$PROJECT" = "Generic" ] && $SCRIPTS/install virtual

+# u-boot image creation support
+[ "$BOOTLOADER" = "u-boot" -a \( -n "$UBOOT_SYSTEM" -o "$UBOOT_VERSION" = "vendor" \) ] && $SCRIPTS/install u-boot:host
+
 # Installer support
 [ "$INSTALLER_SUPPORT" = "yes" ] && $SCRIPTS/install installer

```

I must admit the whole "Am I building with u-boot?" question does seem overly complicated, but maybe that can be left for a separate PR.

**Comment by adamg-xda** [comment]
@MilhouseVH no because the intention was to remove that so builds can be reproduced like-for-like regardless of the OS it is built on

**Comment by Raybuntu** [comment]
I'm fine with $UBOOT_TOOLS variable now. I don't want it to build for C2 cause it has a seperate project specific u-boot package.
+1

**Comment by adamg-xda** [comment]
@MilhouseVH as I had already said in #2261 adding u-boot-tools to EXTRA_DEPS made this PR pointless but neither you nor @HiassofT was happy with that.

 That is where the already built mkimage came from. As I said above the logic behind this PR is so builds can be reproduced like-for-like.

**Comment by MilhouseVH** [comment]
I understand where the already built `mkimage` came from, and I understand why building `u-boot` (host) is a better solution. However what I don't understand is why you can't use the same logic that causes you to call `mkimage`, as the decision to build `u-boot` (hosts).

If you need to call `mkimage`, then you need to build `u-boot` (host).

If you don't need to call `mkimage`, you don't build `u-boot` (host).

I'm fine if you want to add `UBOOT_TOOLS` but it seems redundant.

**Comment by vpeter4** [comment]
I don't follow progress much and maybe I don't understand but why doesn't u-boot build u-boot:host and copy mkimage file? Why there has to be some extra check if build or not?

**Comment by adamg-xda** [comment]
@MilhouseVH your confusing me now, my private fork is for community builds and doesnt live up to the same high standards as the master branch so please dont refer to it here as it has no bearing

mkimage(host) is used for 1 purpose and 1 purpose alone atleast where the S905 is concerned and you can see where it is called in #2261 

You are overcomplicating something rather simple now

**Comment by adamg-xda** [comment]
@vpeter4 the current product.mk has no definition to build mkimage for the host

The check is there as it is unnecessary to build it for all projects because it isn't needed

**Comment by MilhouseVH** [comment]
@adamg-xda I pointed to a line in your PR 2285 which you submitted for merging so if you don't stand by the quality of your code why did you PR it?

If you only want PR 2261 to be considered then look where you are [calling mkimage](
https://github.com/kszaq/LibreELEC.tv/blob/eca03eb6ce4130ab1a92780d0857e732f55c45fb/scripts/mkimage#L265) and see [the condition](https://github.com/kszaq/LibreELEC.tv/blob/eca03eb6ce4130ab1a92780d0857e732f55c45fb/scripts/mkimage#L228) hat causes you to execute it. Why shouldn't the same condition determine whether `u-boot` (host) is built or not?

**Comment by adamg-xda** [comment]
@MilhouseVH Excuse me? Are you always that rude? That PR is a wip and everybody in slack is aware of that.

You suggested having it initiate from a variable and then changed to having it in the condition block so make your mind up where you would like it

**Comment by vpeter4** [comment]
@adamg-xda: so add everything in package.mk. Why adding in toolchain package, scripts/image if not needed.

Seems simple LE build system is becoming more and more complicated ;)

**Comment by vpeter4** [comment]
I just checked nxp branch and there is also boot-2017.09 used. And mkimage is there build by default.
But if not this one liner helps building tools without whole host build of u-boot:
```
diff --git a/packages/tools/u-boot/package.mk b/packages/tools/u-boot/package.mk
index 0bcca04..040d230 100644
--- a/packages/tools/u-boot/package.mk
+++ b/packages/tools/u-boot/package.mk
@@ -39,6 +39,7 @@ make_target() {
     CROSS_COMPILE="$TARGET_PREFIX" LDFLAGS="" ARCH=arm make mrproper
     CROSS_COMPILE="$TARGET_PREFIX" LDFLAGS="" ARCH=arm make $($ROOT/$SCRIPTS/uboot_helper $PROJECT $DEVICE $UBOOT_SYSTEM config)
     CROSS_COMPILE="$TARGET_PREFIX" LDFLAGS="" ARCH=arm make HOSTCC="$HOST_CC" HOSTSTRIP="true"
+    CROSS_COMPILE="$TARGET_PREFIX" LDFLAGS="" ARCH=arm make tools HOSTCC="$HOST_CC" HOSTSTRIP="true"
   fi
 }
```

**Comment by vpeter4** [comment]
I just checked nxp branch and there is also boot-2017.09 used. And mkimage is there build by default.
But if not this one liner helps building tools without whole host build of u-boot:
diff --git a/packages/tools/u-boot/package.mk b/packages/tools/u-boot/package.mk
index 0bcca04..040d230 100644
--- a/packages/tools/u-boot/package.mk
+++ b/packages/tools/u-boot/package.mk
@@ -39,6 +39,7 @@ make_target() {
     CROSS_COMPILE="$TARGET_PREFIX" LDFLAGS="" ARCH=arm make mrproper
     CROSS_COMPILE="$TARGET_PREFIX" LDFLAGS="" ARCH=arm make $($ROOT/$SCRIPTS/uboot_helper $PROJECT $DEVICE $UBOOT_SYSTEM config)
     CROSS_COMPILE="$TARGET_PREFIX" LDFLAGS="" ARCH=arm make HOSTCC="$HOST_CC" HOSTSTRIP="true"
+    CROSS_COMPILE="$TARGET_PREFIX" LDFLAGS="" ARCH=arm make tools HOSTCC="$HOST_CC" HOSTSTRIP="true"
   fi
 }

And we already copied mkimage in the past: https://github.com/vpeter4/LibreELEC.tv/blob/9b819040be92daa4cece95f5e13eec9352144932/packages/tools/u-boot/package.mk#L108

**Comment by adamg-xda** [comment]
That is for make target not make host :)

Thanks anyway vpeter4

**Comment by vpeter4** [comment]
Seems host for me:
```
~/LibreELEC/LibreELEC.tv.nxp$ ./build.LibreELEC-iMX6.arm-9.0-devel/u-boot-2017.09/tools/mkimage   
Error: Missing output filename
Usage: ./build.LibreELEC-iMX6.arm-9.0-devel/u-boot-2017.09/tools/mkimage -l image
          -l ==> list image header information
       ./build.LibreELEC-iMX6.arm-9.0-devel/u-boot-2017.09/tools/mkimage [-x] -A arch -O os -T type -C comp -a addr -e ep -n name -d data_file[:data_file...] image
          -A ==> set architecture to 'arch'
          -O ==> set operating system to 'os'
          -T ==> set image type to 'type'
          -C ==> set compression type 'comp'
          -a ==> set load address to 'addr' (hex)
          -e ==> set entry point to 'ep' (hex)
          -n ==> set image name to 'name'
          -d ==> use image data from 'datafile'
          -x ==> set XIP (execute in place)
       ./build.LibreELEC-iMX6.arm-9.0-devel/u-boot-2017.09/tools/mkimage [-D dtc_options] [-f fit-image.its|-f auto|-F] [-b <dtb> [-b <dtb>]] [-i <ramdisk.cpio.gz>] fit-image
           <dtb> file is used with -f auto, it may occur multiple times.
          -D => set all options for device tree compiler
          -f => input filename for FIT source
          -i => input filename for ramdisk file
Signing / verified boot not supported (CONFIG_FIT_SIGNATURE undefined)
       ./build.LibreELEC-iMX6.arm-9.0-devel/u-boot-2017.09/tools/mkimage -V ==> print version information and exit
Use '-T list' to see a list of available image types
```
Also when building package seems fine:
```
  HOSTCC  tools/mkimage.o
  HOSTLD  tools/mkimage

  MKIMAGE u-boot.img
  MKIMAGE SPL
```

**Comment by adamg-xda** [comment]
Apologies I didn't look at it the patch properly

**Comment by vpeter4** [comment]
But from what I see tools (mkimage) are always build for host. Or am I wrong? So only `cp `is missing just like it was before.

**Pull request closed without merging**
