### PR TITLE
linux: include HBR and ELD fixes for Intel

### PR DESCRIPTION
**Pull request by MilhouseVH**
HBR: https://bugs.freedesktop.org/show_bug.cgi?id=98797#c119
ELD: https://bugs.freedesktop.org/show_bug.cgi?id=101583#c34

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Added WIP until patches confirmed as working.

**Comment by MilhouseVH** [comment]
Updated with v2 patches:

HBR: https://patchwork.kernel.org/patch/9960405/
ELD: https://cgit.freedesktop.org/drm-tip/commit/?id=d81fb7fd9436e81fda67e5bc8ed0713aa28d3db2

**Comment by escalade** [comment]
These are now upstreamed with Linux 4.14-rc4.

**Comment by MilhouseVH** [comment]
Thanks. I'm still including these in my 4.13.y builds but there's probably no point merging this and I'll close it once 4.14.y is released.

**Comment by MilhouseVH** [comment]
ELD is now in 4.13.6

**Comment by MilhouseVH** [comment]
Closing now that 4.14 is here and includes these commits.

**Pull request closed without merging**
