### PR TITLE
gcc: update to 11.2.0 and Arm GNU Toolchain to 11.2-2022.02

### PR DESCRIPTION
**Pull request by heitbaum**
### Arm GNU Toolchain to 11.2-2022.02
GNU Toolchain releases from Arm were published previously as two separate releases - one for A-profile and the other for R & M profiles ([GNU Toolchain for A-profile processors](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a) and  [GNU Arm Embedded Toolchain](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm)). 

Arm GNU Toolchain releases unifies these two into a single release and the previous way of releases therefore have been discontinued.

- https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/downloads
- Download link changed as per `GNU toolchain releases for A-profile processors (discontinued)`

### gcc: update to 11.2.0
Updated to gcc 11.2.0 after fixing build issue with:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100289
  - libgcc/libgcov.h: bootstrap failure due to missing #include <sys/mman.h>. 
- Fix was simply to NOT build gcov during bootstrap.
- Added patches to support build of glibc-2.32 with gcc-11.2
  - https://sourceware.org/bugzilla/show_bug.cgi?id=26647

Took the pointer from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100289#c16 and **_attempted the patch as below_** - before testing and concluding that the issue was isolated to the bootstrap for which gcov was not required.

Additionally this PR:
- reorders the `BOOTSTRAP` OPTS into sort order.
- sets `--disable-libgomp` for `BOOTSTRAP` which would also cause a build failure

### gcc 11.2 run tested with:
- Generic Generic (Intel TGL - NUC11) - 5.16.10 - heitbaum

```
commit e87de21981f7f4c101b2cf34232a715baba4e8d9
Author: Rudi Heitbaum <rudi@heitbaum.com>
Date:   Fri Feb 18 23:27:07 2022 +0000

    WIP: gcc: libgcc/libgcov.h: bootstrap failure due to missing #include <sys/mman.h>

    Workaround with bug:
    - https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100289

    Issue is also present with cross-compiler (11.2) on FreeBSD:

    Can confirm this bug when building an AVR cross-compiler (11.2) on
    FreeBSD. To get it working, I'm now patching it to #undef
    HAVE_SYS_MMAN_H in libgcov.h before starting.

    This is a WIP - if this patch / workaround is to be used - it should
    only be used in the bootstrap stage of the compiler build.

diff --git a/packages/lang/gcc/patches/gcc-100.01-undef-have-sys-mman-h.patch b/packages/lang/gcc/patches/gcc-100.01-undef-have-sys-mman-h.patch
new file mode 100644
index 0000000000..af78d28fd9
--- /dev/null
+++ b/packages/lang/gcc/patches/gcc-100.01-undef-have-sys-mman-h.patch
@@ -0,0 +1,10 @@
+--- a/libgcc/libgcov.h 2022-01-16 22:32:11.000000000 +0000
++++ b/libgcc/libgcov.h 2022-02-18 23:16:59.436212752 +0000
+@@ -45,6 +45,7 @@
+ #include "libgcc_tm.h"
+ #include "gcov.h"
+
++#undef HAVE_SYS_MMAN_H
+ #if HAVE_SYS_MMAN_H
+ #include <sys/mman.h>
+ #endif
```

### CODE REVIEW

**Comment by knaerzche** [comment]
@heitbaum pls also update the prebuild aarch64 toolchains - 11.2-2022.02 was released just a few days ago: https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/downloads

**Comment by heitbaum** [comment]
> @heitbaum pls also update the prebuild aarch64 toolchains - 11.2-2022.02 was released just a few days ago: https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/downloads

👍Can do.

**Comment by knaerzche** [comment]
Note: depends on (at least) the glibc bump in https://github.com/LibreELEC/LibreELEC.tv/pull/5876 (for aarch64 / arm builds)

**Comment by heitbaum** [comment]
### Build tested on all of:
- Build host: tools/docker Ubuntu 20.04
- Tested with #5876 (glibc 2.34 and binutils 2.37) - **without 8c71dd0d93**
- Also tested with 8c71dd0d93 against master (glibc 2.32 and binutils 2.35.1)

```
PROJECT=Allwinner ARCH=arm DEVICE=A64 make image
PROJECT=Allwinner ARCH=arm DEVICE=H3 make image
PROJECT=Allwinner ARCH=arm DEVICE=H5 make image
PROJECT=Allwinner ARCH=arm DEVICE=H6 make image
PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 make image
PROJECT=NXP ARCH=arm DEVICE=iMX6 make image
PROJECT=NXP ARCH=arm DEVICE=iMX8 make image
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard make image
PROJECT=Samsung ARCH=arm DEVICE=Exynos make image
PROJECT=Generic ARCH=x86_64 DEVICE=Generic make image
PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy make image
PROJECT=RPi ARCH=arm DEVICE=RPi2 make image
PROJECT=RPi ARCH=arm DEVICE=RPi4 make image
PROJECT=Amlogic ARCH=arm DEVICE=AMLGX make image
```

**Comment by SupervisedThinking** [comment]
@heitbaum did you run test it? My syslinux was broken / "kernel paniked" after a clean rebuild and I managed to screw up the system afterwards :D

**Comment by heitbaum** [comment]
Think this answers it then. We wait on #5876. Setting mergeblock.

**Comment by SupervisedThinking** [comment]
@heitbaum rebase please & I guess merge then?

**Comment by heitbaum** [comment]
Rebased and glibc 2.32 dropped.

**Review by CvH — APPROVED** [review]

**Pull request merged**
