### PR TITLE
librespot: update python scripts

### PR DESCRIPTION
**Pull request by henri-funck**

### CODE REVIEW

**Comment by chewitt** [comment]
@henri-funck Can you provide some background info on the changes proposed: what do they achieve?, who authored the changes (yourself, or copied from some upstream source?) and how have been tested? - assume the reviewing audience are not experienced Python developers :)

**Comment by henri-funck** [comment]
@chewitt The changes improve the python scripts. playback uses an inputstream, track position and duration can be displayed, pauses are handled better. I authored the changes.

**Comment by chewitt** [comment]
@antonlacon @mglae as we are always stuck for Python capable reviewers, can I ask you to have a look at this PR?

**Comment by mglae** [comment]
Unfortunately I cannot test anything because not using Spotify. Changes LGTM, so merge and see if someone complains (we are on LE13 pre alpha).

**Review by mglae — APPROVED** [review]
As said

**Pull request merged**
