### PR TITLE
[Allwinner,Generic,Rockchip] linux: Update to 5.10.17

### PR DESCRIPTION
**Pull request by heitbaum**
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.12
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.13
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.14
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.15
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.16
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.17

Generic tested - @heitbaum 
RK tested  - @knaerzche 
AW waiting on 5.10.17 - @jernejsk

### CODE REVIEW

**Comment by CvH** [comment]
@jernejsk @knaerzche pls test at AW/RK

**Comment by heitbaum** [comment]
5.10.16
- Linux LibreELEC 5.10.16 #1 SMP Sat Feb 13 22:23:30 UTC 2021 x86_64 GNU/Linux
- https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.16
- No changes to patches required for Allwinner,Generic,Rockchip,NXP
- I’ll add to this PR if you suggest, otherwise - first one for next bump.

**Comment by jernejsk** [comment]
Can we wait until 5.10.17? With it, 5 AW fixes can be removed. Given that I got e-mail notification, it should be released in a day or two.

**Comment by knaerzche** [comment]
All good for RK. @heitbaum - before this gets merged: Would you mind to also update the kernel configs in device folders for RK (even if it is only for the version number), thanks.

**Comment by heitbaum** [comment]
```
=== tested on ===
Generic.x86_64-devel-20210217113557-5aa2ab4
Linux LibreELEC 5.10.17 #1 SMP Wed Feb 17 11:23:19 UTC 2021 x86_64 GNU/Linux
Starting Kodi (19.0-RC1 (18.9.910) Git:04303bf0c08adb47d9519cf7339acdd6edb1ec87). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2021-02-17 by GCC 10.2.0 for Linux x86 64-bit version 5.10.16 (330256)
Running on LibreELEC (heitbaum): devel-20210217113557-5aa2ab4 9.80, kernel: Linux x86 64-bit version 5.10.17
FFmpeg version/source: 4.3.1-Kodi
Host CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 8 cores available
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0037.2021.0106.1527 01/06/2021
CRenderSystemGL::InitRenderSystem - Version: 4.6 (Core Profile) Mesa 21.1.0-devel, Major: 4, Minor: 6
GL_RENDERER = Mesa Intel(R) Xe Graphics (TGL GT2)
GL_VERSION = 4.6 (Core Profile) Mesa 21.1.0-devel
```

**Comment by heitbaum** [comment]
@jernejsk can you please look at which of these patches needs to be updated/deleted for 5.10.17?

projects/Allwinner/patches/linux/0050-clk-sunxi-ng-mp-fix-parent-rate-change-flag-check.patch
projects/Allwinner/patches/linux/0051-drm-sun4i-tcon-set-sync-polarity-for-tcon1-channel.patch
projects/Allwinner/patches/linux/0052-drm-sun4i-dw-hdmi-always-set-clock-rate.patch
projects/Allwinner/patches/linux/0054-drm-sun4i-dw-hdmi-Fix-max.-frequency-for-H6.patch

**Comment by heitbaum** [comment]
@knaerzche 991ef24a3f4ea1ae8abc9b310dd581f799a81019 changed between 5.10.16 and 5.10.17

**Comment by knaerzche** [comment]
all good for RK, thanks @heitbaum

**Comment by CvH** [comment]
@heitbaum pls rebase

**Comment by etrax79** [comment]
For NXP/iMX6 project the last patch (iMX6: add upstream patch to fix cubox ethernet) is also included since kernel 5.10.13 and has to be removed...

**Comment by heitbaum** [comment]
@etrax79 - patch removed
@CvH  rebased

**Review by CvH — APPROVED** [review]

**Comment by antonlacon** [comment]
What testing was done of the Samsung and Qualcomm kernels? Why were the linux versions at the top of their configs changed? To my knowledge, those platforms are unmaintained and those values should reflect what they were last tested / blessed for. If they happen to still work, that's by chance.

**Comment by heitbaum** [comment]
You are right - probably should have left the ##.## as the old ones. I updated/removed the patches on both Samsung and Qualcomm, so that the upstream patches included in the kernel tar have been removed. patches apart, Qualcomm compiles, Samsung additionally needs at least these patches reviewed to have a clean compile.
- samsung-0007-MEMEKA-videobuf2-dc-Support-cacheable-MMAP.patch  
- samsung-0008-MEMEKA-ARM-dma-mapping-add-support-for-non-consisten.patch
- samsung-0009-MEMEKA-media-s5p-mfc-use-cacheable-DMA-buffers-to-im.patch

**Comment by chewitt** [comment]
Samsung is not a release target right now and can be disabled in Jenkins. I'll get around to poking it again .. once I get past a longer list of other undone priorities.

**Pull request merged**
