### PR TITLE
Net-snmp addon

### PR DESCRIPTION
**Pull request by Celedhrim**
Bump version to reflect changelog state

### CODE REVIEW

**Comment by CvH** [comment]
@Celedhrim addon is failing to build at current master
https://pastebin.com/Jh4EPmmW
could you have a look ?

**Comment by Celedhrim** [comment]
Hello,

I have git pull latest master , build wetek play 2 image , and build net-snmp addon.
No error :/
It fail on a particular project / arch ?

**Comment by CvH** [comment]
@Celedhrim it works for Generic for me too, but it still fails at WeTek Core (kernel 3.10)

**Comment by Celedhrim** [comment]
@CvH ,

I have build image then net-snmp for wetek core  (arch arm) without issue !

**Comment by chewitt** [comment]
@Celedhrim If you build the image first there is a risk you mask missing dependencies etc. that cause build or linking failures. All add-ons should be built independently from the distro image.

**Comment by Celedhrim** [comment]
@CvH PR submit to fix that !

https://github.com/LibreELEC/LibreELEC.tv/pull/2271

**Pull request merged**
