### PR TITLE
gcc: update to gcc-9.2.0

### PR DESCRIPTION
**Pull request by MilhouseVH**
Tested building RPi/RPi2/Generic `image` and all add-ons. Images all booted fine on relevant hardware.

### CODE REVIEW

**Comment by 5schatten** [comment]
The Rockchip builds probably need a Kernel bump or at least some patches https://pastebin.com/Ehxv4ytd

**Comment by MilhouseVH** [comment]
Tested all packages for RPi/RPi2/Generic/Allwinner(A64)/NXP(iMX6)/Qualcomm(Dragonboard).

Ready to merge.

**Comment by lorenz** [comment]
This broke Rockchip since GCC 9 has more warnings and something sets -Werror

**Comment by MilhouseVH** [comment]
@lorenz yes, sorry that was unintentional but an updated Rockchip kernel has been promised that should build successfully, which is why this hasn't been reverted (or otherwise fixed) in the meantime. For now, it's best to temporarily disable building `perf` for Rockchip with http://ix.io/1Urw - that _should_ get you past the issue (not tested).

**Comment by lorenz** [comment]
This fix works for the Linux kernel, but u-boot also needs to be fixed (Makefile:363).

**Comment by MilhouseVH** [comment]
@lorenz what is the u-boot failure? Can you post your command line that is failing.

**Comment by lorenz** [comment]
```
lib/uuid.c:239:2: error: converting a packed 'struct uuid' pointer (alignment 1) to a 'unsigned int' pointer (alignment 4) may result in an unaligned pointer value [-Werror=address-of-packed-member]
```

**Comment by MilhouseVH** [comment]
Command line?

**Comment by lorenz** [comment]
`env PROJECT=Rockchip DEVICE=RK3328 ARCH=aarch64 UBOOT_SYSTEM=rock64 make release`

**Comment by MilhouseVH** [comment]
It looks like Rockchip will fail to build `ffmpeg-4.0.4` as the Rockchip ffmpeg patches also need fixing up - best to wait for @kwiboo to update the project and patches.

**Comment by lorenz** [comment]
I'm running custom ffmpeg patches anyways so I've fixed that there.

**Comment by MilhouseVH** [comment]
[This](https://libreelec.wiki/compile#choose_the_project_and_arch_to_compile) is the supported list of project/device/arch triplets, so you're kind of on your own with `ARCH=aarch64` but glad you got it working. We don't currently support 64-bit userland on ARM because there is no Widevine support and therefore no Netflix/Amazon etc.

When building from `master` (and possibly/probably `libreelec-9.2` - I haven't checked) you don't need to specify `UBOOT_SYSTEM` when building only the `tar` file (ie. `make release`) - `UBOOT_SYSTEM` has no effect when building only the `tar` file.

`UBOOT_SYSTEM` is an optional command line property whenever building the `img.gz` (ie. `make image`). If not specified, then after the main image is created the additional per-board images will be automatically created; otherwise only the specified board image will be created.

**Comment by MilhouseVH** [comment]
Turns out `UBOOT_SYSTEM` is also optional for `tar` files - if `UBOOT_SYSTEM` is specified when performing `make release` then the uboot files will be included for the specified board (and updated during upgrade). If not specified, then the u-boot installation won't be updated during the upgrade.

I believe the plan with LibreELEC official releases will be to create multiple u-boot board-specific `img.gz` files for new users, and a single common `tar` file without u-boot (for upgrade users).  Users that are upgrading via tar (ie. automatically) will do so from a single `tar` file while keeping their existing u-boot installation. Anyone wanting to refresh their u-boot installation (perhaps to fix bugs etc.) can re-upgrade using the correct board specific `img.gz` - let's hope u-boot isn't a buggy mess in future...

I guess for development purposes there may be times when a board specific tar file is useful.

**Comment by lorenz** [comment]
I'm aware that UBOOT_SYSTEM is no longer needed for tar builds, it's just a leftover from earlier builds. I also know that aarch64 is technically unsupported, but it's easier when building external stuff (for example Go programs) for it and the Rock64 has it so why not.

**Pull request merged**
