### PR TITLE
linux: update Amlogic to 6.0.y

### PR DESCRIPTION
**Pull request by SupervisedThinking**
- switch to https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git repo which works fine with tags/commits
-  dropped upstreamed patch(es)
- updated kernel conf

### CODE REVIEW

**Comment by SupervisedThinking** [comment]
#### Vim1
```
=== tested on ===
AMLGX.arm-RR-20221201-d513479
Linux vim1 6.0.10 #1 SMP PREEMPT Thu Dec 1 13:04:32 CET 2022 aarch64 GNU/Linux
Starting Kodi (20.0-BETA1 (19.90.801) Git:20.0b1-Nexus). Platform: Linux ARM 32-bit
Using Release Kodi x32
Kodi compiled 2022-12-01 by GCC 12.2.0 for Linux ARM 32-bit version 6.0.9 (393225)
Running on Amlogic Meson GXL (S905X) Khadas VIM with LibreELEC (ST): RR-20221201-d513479 11.0, kernel: Linux ARM 64-bit version 6.0.10
FFmpeg version/source: dev/4.4/rpi_import_1-f9638b6
Host CPU: ARMv8 Processor rev 4 (v8l), 4 cores available
ARM Features: Neon enabled
RetroPlayer[PROCESS]: Registering process control for GBM
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_VERSION = OpenGL ES 2.0 Mesa 22.3.0
```

**Comment by SupervisedThinking** [comment]
```
=== tested on ===
AMLGX.arm-RR-20221203-0ab916a
Linux vim1 6.0.11 #1 SMP PREEMPT Sat Dec 3 11:52:11 CET 2022 aarch64 GNU/Linux
Starting Kodi (20.0-BETA1 (19.90.801) Git:20.0b1-Nexus). Platform: Linux ARM 32-bit
Using Release Kodi x32
Kodi compiled 2022-12-01 by GCC 12.2.0 for Linux ARM 32-bit version 6.0.9 (393225)
Running on Amlogic Meson GXL (S905X) Khadas VIM with LibreELEC (ST): RR-20221203-0ab916a 11.0, kernel: Linux ARM 64-bit version 6.0.11
FFmpeg version/source: dev/4.4/rpi_import_1-f9638b6
Host CPU: ARMv8 Processor rev 4 (v8l), 4 cores available
ARM Features: Neon enabled
RetroPlayer[PROCESS]: Registering process control for GBM
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_VERSION = OpenGL ES 2.0 Mesa 22.3.0
```

**Comment by SupervisedThinking** [comment]
#### Vim3
```
=== tested on ===
AMLG12B.arm-RR-20221203-f7cfad7
Linux vim3 6.0.11 #1 SMP PREEMPT Sat Dec 3 18:59:30 CET 2022 aarch64 GNU/Linux
Starting Kodi (20.0-BETA1 (19.90.801) Git:20.0b1-Nexus). Platform: Linux ARM 32-bit
Using Release Kodi x32
Kodi compiled 2022-12-02 by GCC 12.2.0 for Linux ARM 32-bit version 6.0.10 (393226)
Running on Amlogic Meson G12B (A311D) Khadas VIM3 with LibreELEC (ST): RR-20221203-f7cfad7 11.0, kernel: Linux ARM 64-bit version 6.0.11
FFmpeg version/source: dev/4.4/rpi_import_1-f9638b6
Host CPU: ARMv8 Processor rev 4 (v8l), 6 cores available
ARM Features: Neon enabled
RetroPlayer[PROCESS]: Registering process control for GBM
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_VERSION = OpenGL ES 3.1 Mesa 22.3.0
```

**Comment by SupervisedThinking** [comment]
```
=== tested on ===
AMLGX.arm-RR-20221210-41e0c6e
Linux vim1 6.0.12 #1 SMP PREEMPT Sat Dec 10 15:09:49 CET 2022 aarch64 GNU/Linux
Starting Kodi (20.0-RC1 (19.90.901) Git:20.0rc1-Nexus). Platform: Linux ARM 32-bit
Using Release Kodi x32
Kodi compiled 2022-12-10 by GCC 12.2.0 for Linux ARM 32-bit version 6.0.12 (393228)
Running on Amlogic Meson GXL (S905X) Khadas VIM with LibreELEC (ST): RR-20221210-41e0c6e 11.0, kernel: Linux ARM 64-bit version 6.0.12
FFmpeg version/source: dev/4.4/rpi_import_1-f9638b6
Host CPU: ARMv8 Processor rev 4 (v8l), 4 cores available
ARM Features: Neon enabled
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_VERSION = OpenGL ES 2.0 Mesa 22.3.0
```

**Comment by SupervisedThinking** [comment]
```
=== tested on ===
AMLGX.arm-RR-20221215-d9e97d4
Linux vim1 6.0.13 #1 SMP PREEMPT Thu Dec 15 05:49:18 CET 2022 aarch64 GNU/Linux
Starting Kodi (20.0-RC1 (19.90.901) Git:20.0rc1-Nexus). Platform: Linux ARM 32-bit
Using Release Kodi x32
Kodi compiled 2022-12-15 by GCC 12.2.0 for Linux ARM 32-bit version 6.0.13 (393229)
Running on Amlogic Meson GXL (S905X) Khadas VIM with LibreELEC (ST): RR-20221215-d9e97d4 11.0, kernel: Linux ARM 64-bit version 6.0.13
FFmpeg version/source: dev/4.4/rpi_import_1-f9638b6
Host CPU: ARMv8 Processor rev 4 (v8l), 4 cores available
ARM Features: Neon enabled
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_VERSION = OpenGL ES 2.0 Mesa 22.3.1
```

**Comment by heitbaum** [comment]
- Superseded by #7387

**Pull request closed without merging**
