### PR TITLE
RPi Steamlink support [LE9.2]

### PR DESCRIPTION
**Pull request by antonlacon**
The is the LE9.2 version of #4029  

The xbmcgui lines of the addon are commented out as either python2 or the python lib work differently compared to the LE10 version. It's a cosmetic issue on first run where users don't get confirmation feedback that the addon is doing anything. Further launches, kodi gets shutdown pretty much immediately.

Existing sound cards should not be clobbered by dtparam settings.

addon_post_install() isn't available in LE9.2, so package version and hash is placed in the addon.

Tested on RPi3. My expectation is RPi4 will not work due to missing libs.

### CODE REVIEW

**Comment by antonlacon** [comment]
Re RPi4 support: https://steamcommunity.com/app/353380/discussions/6/2145343313162988731/#c2260186248419735359

**Comment by cwildfoerster** [comment]
Can confirm that the plugin works on my rpi3 as well. Getting the gui messages to work would be nice tho

**Comment by cwildfoerster** [comment]
From the code i can't see how an update of the steamlink could work? The download only happens if prep.ok is not present. Is this file deleted on a kodi addon update? Or should the plugin save the currently installed/downloaded steamlink version and check it against?

**Comment by cwildfoerster** [comment]
hello @antonlacon i updated the python part of the addon a little bit to make it a little bit more userfriendly by adding a progress bar. Today i discovered hat somehow steamlinks screenblank was buggy, because after some time i suddenly lost audio and stopping steam link didn't restart steam link so you could close it to get back to kodi... screen was just black. I suspect the missing xserver to be the problem. The simplest solution i had found was to replace the `screenblank` executable by an empty script, so i updated the addon to patch the file after downloading. Working like a charm so far! Been using the Xbox 360 Wireless Controller (with USB Dongle), the Steam Controller and the Xbox One Bluetooth Controller... but getting that one to work was tricky (Bluetooth Mode, udev rule) and the Bluetooth connection sucked so much (rpi behind TV), so i didn't use it anymore.

This is my first work on a kodi addon, i would like to add a check to against `http://media.steampowered.com/steamlink/rpi/public_build.txt` in the future to enable `auto` updates, but i don't like that the URL doesn't use a valid SSL certificate (akamai cdn).

```python
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2019-present Team LibreELEC (https://libreelec.tv)

import os
import stat
import tarfile
import subprocess
import xbmcaddon
import xbmcgui
from hashlib import sha256
from tempfile import mkdtemp
from shutil import rmtree
from sys import exit
from urllib import urlretrieve

STEAMLINK_NAME = "Steam Link"
STEAMLINK_VERSION = "1.1.62.158"
STEAMLINK_HASH = "6af0b843d909c8c5e24297ba327070bb4ed8ab46a62a1b1283feb81e84d8086e"
STEAMLINK_TARBALL_NAME = "steamlink-rpi3-{}.tar.gz".format(STEAMLINK_VERSION)
STEAMLINK_URL = "http://media.steampowered.com/steamlink/rpi/{}".format(STEAMLINK_TARBALL_NAME)
ADDON_DIR = xbmcaddon.Addon().getAddonInfo("path") + "/"

pDialog = None

def GetSHA256Hash(file_name):
  """ Get sha256sum of file_name in 8kb chunks """
  with open(file_name,"rb") as file:
    SHA256HASH = sha256()
    while True:
      data_block = file.read(8192)
      if not data_block:
        break
      SHA256HASH.update(data_block)
  return SHA256HASH.hexdigest()

def TouchFile(file_name):
  if os.path.exists(file_name):
    os.utime(file_name, None)
  else:
    open(file_name, 'a').close()

def GetRPiProcessor():
  """ Use vcgencmd to obtain cpu identifier as int """
  VC_CMD_OUTPUT=subprocess.check_output(["vcgencmd", "otp_dump"])

  for line in VC_CMD_OUTPUT.splitlines():
    if line[0:3] == "30:":
      PROCESSOR=line.split(":")[1] # entire processor id
      return int(PROCESSOR[4:5])   # only cpu id

  return 0

def ShowDownloadProgress(count, blockSize, totalSize):
  global pDialog
  
  percent = int(count * blockSize * 100 / totalSize)
  pDialog.update(percent)

def DownloadSteamlink(temp_dir):
  """ Download Steam Link for RPi """
  STEAMLINK_TEMP_PATH = os.path.join(temp_dir, STEAMLINK_TARBALL_NAME)

  global pDialog
  pDialog = xbmcgui.DialogProgress()
  pDialog.create(STEAMLINK_NAME, "Downloading {} {}...".format(STEAMLINK_NAME, STEAMLINK_VERSION))
  
  urlretrieve(STEAMLINK_URL, STEAMLINK_TEMP_PATH, ShowDownloadProgress)
  if tarfile.is_tarfile(STEAMLINK_TEMP_PATH):
    DOWNLOAD_HASH = GetSHA256Hash(STEAMLINK_TEMP_PATH)
    if STEAMLINK_HASH == DOWNLOAD_HASH:
      pDialog.update(100, "Download complete, extracting...")
      STEAMLINK_TARBALL = tarfile.open(STEAMLINK_TEMP_PATH)
      STEAMLINK_TARBALL.extractall(path=ADDON_DIR)
      pDialog.update(100, "Patching files...")
      
      # screenblank seems to be buggy without xserver, audio stops working after some time 
      # and after stopping remote play, screen stays black. So we backup the executable and 
      # replace it with an empty script
      pathToScreenblank = os.path.join(ADDON_DIR, "steamlink", "bin", "screenblank")
      os.rename(pathToScreenblank, os.path.join(ADDON_DIR, "steamlink", "bin", "screenblank_orig"))
      fd = os.open(pathToScreenblank, os.O_RDWR|os.O_CREAT)
      os.write(fd, "#!/bin/bash\n\nexit 0\n")
      os.close(fd)
      st = os.stat(pathToScreenblank)
      os.chmod(pathToScreenblank, st.st_mode | stat.S_IEXEC)
      
      pDialog.update(100, "{} {} successfully installed!".format(STEAMLINK_NAME, STEAMLINK_VERSION))
      pDialog.close()
    else:
      pDialog.update(100, "Download error: bad file hash, try again later")
      #pDialog.close()
      exit(1)
  else:
    pDialog.update(100, "Download error: bad download or missing file")
    #pDialog.close()
    exit(1)

def StartSteamlink():
  # Check if running on RPi3 or higher, steamlink/.ignore_cpuinfo will also be checked by steamlink itself
  if not os.path.isfile(ADDON_DIR + "steamlink/.ignore_cpuinfo") and GetRPiProcessor() < 2:
    xbmcgui.Dialog().ok(STEAMLINK_NAME, "{} will not run on this hardware. Aborting...".format(STEAMLINK_NAME))
    exit(1)
  
  # copy steamlink libs
  if not os.path.isfile(ADDON_DIR + 'prep.ok'):
    subprocess.call(ADDON_DIR + "bin/steamlink-prep.sh")

    # Download Steam Link if not present
    Temp_Dir = mkdtemp()
    DownloadSteamlink(Temp_Dir)
    rmtree(Temp_Dir)

  # Disable Steam Link's cpu check
  if not os.path.isfile(ADDON_DIR + "steamlink/.ignore_cpuinfo"):
    TouchFile(ADDON_DIR + "steamlink/.ignore_cpuinfo")

  # Start Steamlink
  xbmcgui.Dialog().notification(STEAMLINK_NAME, "Starting {} {}".format(STEAMLINK_NAME, STEAMLINK_VERSION), xbmcgui.NOTIFICATION_INFO, 3000)
  TouchFile("/tmp/steamlink.watchdog")
  subprocess.call(["systemctl", "start", "steamlink-rpi.watchdog.service"])


StartSteamlink()
```

**Comment by cwildfoerster** [comment]
Updated to auto update from stable channel url. Maybe i will add addon settings in the future to enable/disable auto updates/checks. Works flawlessly on my rpi3. 

```python
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2019-present Team LibreELEC (https://libreelec.tv)

import os
import stat
import tarfile
import subprocess
import re
import xbmc
import xbmcaddon
import xbmcgui
from tempfile import mkdtemp
from shutil import rmtree
from sys import exit
from urllib import urlretrieve

STEAMLINK_NAME = "Steam Link"
STEAMLINK_VERSION_URL = "http://media.steampowered.com/steamlink/rpi/public_build.txt"
ADDON_DIR = xbmcaddon.Addon().getAddonInfo("path") + "/"

pDialog = None

def ReadFileAsString(filename):
  try:
    with open(filename, "r") as file:
      return file.read().strip()
  except:
    return ""

def GetInstalledVersion():
  return ReadFileAsString(ADDON_DIR + "steamlink/version.txt")

def GetLatestVersionUrl():
  urlretrieve(STEAMLINK_VERSION_URL, "/tmp/steamlink-latest.txt")
  return ReadFileAsString("/tmp/steamlink-latest.txt")

def GetVersionFromUrl(url):
  m = re.search('(\d+\.\d+\.\d+\.\d+)', url)
  if m:
    return m.group(1)
  return ""

def TouchFile(file_name):
  if os.path.exists(file_name):
    os.utime(file_name, None)
  else:
    open(file_name, 'a').close()

def GetRPiProcessor():
  """ Use vcgencmd to obtain cpu identifier as int """
  try:
    VC_CMD_OUTPUT=subprocess.check_output(["vcgencmd", "otp_dump"])

    for line in VC_CMD_OUTPUT.splitlines():
      if line[0:3] == "30:":
        PROCESSOR=line.split(":")[1] # entire processor id
        return int(PROCESSOR[4:5])   # only cpu id
  except:
    xbmcgui.Dialog().ok(STEAMLINK_NAME, "Not running on Rasperry Pi. May not work! (dev on vm)")
    return 2

  return 0

def ShowDownloadProgress(count, blockSize, totalSize):
  global pDialog
  
  percent = int(count * blockSize * 100 / totalSize)
  pDialog.update(percent)

def DownloadSteamlink(tmpDir, url, currentVersion):
  """ Download Steam Link for RPi """
  xbmc.log("steamlink-rpi: DownloadSteamlink: {}, {}, {}".format(tmpDir, url, currentVersion));
  
  tmpDownloadPath = os.path.join(tmpDir, "steamlink-rpi3.tar.gz")
  newVersion = GetVersionFromUrl(url)

  global pDialog
  pDialog = xbmcgui.DialogProgress()
  pDialog.create(STEAMLINK_NAME, "Updating {} to version {}...".format(STEAMLINK_NAME, newVersion))
  
  urlretrieve(url, tmpDownloadPath, ShowDownloadProgress)
  if tarfile.is_tarfile(tmpDownloadPath):
    pDialog.update(100, "Download complete, extracting...")
    steamlinkTarfile = tarfile.open(tmpDownloadPath)
    steamlinkTarfile.extractall(path=ADDON_DIR)
    pDialog.update(100, "Patching files...")
      
    # screenblank seems to be buggy without xserver, audio stops working after some time 
    # and after stopping remote play, screen stays black. So we backup the executable and 
    # replace it with an empty script
    pathToScreenblank = os.path.join(ADDON_DIR, "steamlink/bin/screenblank")
    os.rename(pathToScreenblank, os.path.join(ADDON_DIR, "steamlink/bin/screenblank_orig"))
    fd = os.open(pathToScreenblank, os.O_RDWR|os.O_CREAT)
    os.write(fd, "#!/bin/bash\n\nexit 0\n")
    os.close(fd)
    st = os.stat(pathToScreenblank)
    os.chmod(pathToScreenblank, st.st_mode | stat.S_IEXEC)
    
    # Disable Steam Link's cpu check
    TouchFile(ADDON_DIR + "steamlink/.ignore_cpuinfo")
      
    pDialog.update(100, "{} {} successfully installed!".format(STEAMLINK_NAME, newVersion))
    pDialog.close()
  else:
    xbmc.log("steamlink-rpi: DownloadSteamlink: downloaded file is not a tarfile!");
    pDialog.update(100, "Download error: bad download or missing file")
    #pDialog.close()
    exit(1)

def StartSteamlink():
  xbmc.log("steamlink-rpi: StartSteamlink");

  # Check if running on RPi3 or higher, steamlink/.ignore_cpuinfo will also be checked by steamlink itself
  if not os.path.isfile(ADDON_DIR + "steamlink/.ignore_cpuinfo") and GetRPiProcessor() < 2:
    xbmcgui.Dialog().ok(STEAMLINK_NAME, "{} will not run on this hardware.".format(STEAMLINK_NAME))
    exit(1)
  
  currentVersion = GetInstalledVersion()
  latestVersionUrl = GetLatestVersionUrl()
  
  xbmc.log("steamlink-rpi: currentVersion: {}".format(currentVersion));
  xbmc.log("steamlink-rpi: latestVersionUrl: {}".format(latestVersionUrl));
  xbmc.log("steamlink-rpi: GetVersionFromUrl: {}".format(GetVersionFromUrl(latestVersionUrl)));
  
  # check currentVersion is empty which means steamlink hasn't been installed yet 
  # or if a newer steam link version is available
  if len(currentVersion) == 0 or latestVersionUrl.find(currentVersion) == -1:
    # delete old steamlink installation, if steamlink hasn't been installed yet, throws exception
    try:
      rmtree(ADDON_DIR + "steamlink")
    except:
      pass
    
    # download steam link
    tmpDir = mkdtemp()
    DownloadSteamlink(tmpDir, latestVersionUrl, currentVersion)
    rmtree(tmpDir)
    
    # copy steam link libs by calling steamlink-prep.sh, which just copies
    # the bundles libs and enables the steamlink-rpi.watchdog.service (which is okay to happen multiple times)
    xbmc.log("steamlink-rpi: copy steamlink libs, execute bin/steamlink-prep.sh");
    subprocess.call(ADDON_DIR + "bin/steamlink-prep.sh")

  # Start Steam Link
  xbmcgui.Dialog().notification(STEAMLINK_NAME, "Starting {}".format(STEAMLINK_NAME), xbmcgui.NOTIFICATION_INFO, 3000)
  TouchFile("/tmp/steamlink.watchdog")
  subprocess.call(["systemctl", "start", "steamlink-rpi.watchdog.service"])


StartSteamlink()
```

**Comment by antonlacon** [comment]
The intended upgrade path is when the Kodi addon is updated, it will pull down a new version of steamlink. I haven't tested what survives an addon update beyond confirming default.py gets shifted to the new one to look for an updated steamlink tarball (everything is wip and with things not merged I squash new versions into the 'initial' addon).

I avoided the auto-upgrade on purpose. Valve takes the approach that building for Raspberry Pi, means building for Raspbian, which means at any given update something may break for LE. This addon uses bundled libraries and ones built for LE, and I'm sure at one point or another, updating will break (either because we're not Raspbian, or because Valve occasionally releases bad builds). Pinning the version used should keep that from happening unexpectedly as someone sits down to try and use it. An auto-upgrade feature would need to be attached to a configure option, and defaulted to off.

If you wanted the package grabbed by such an auto-ugprade to be 'secure' you can look at the raspbian package's steamlink launcher script. I believe it authenticates the package via a gpg key. Gpg is not in LE, and given the above, I'm not in a rush to look into.

Thank you for testing, and for working on a progress bar. I haven't seen the issue with screenblank, but I'm not opposed to the workaround. Have you tried what happens if you only delete/rename it instead of the stub script?

**Comment by cwildfoerster** [comment]
Thank you for your explanation, makes sense to not rely on everything being the same. I will test the screenblank issue today or tomorrow a little bit more, because i haven't had the issue a couple of weeks ago, maybe it is due to a more recent steamlink version.

**Pull request closed without merging**
