### PR TITLE
media-driver: update to 20.4.3

### PR DESCRIPTION
**Pull request by heitbaum**
For clean build with Mesa 20.3.0 https://github.com/LibreELEC/LibreELEC.tv/pull/4713 - I needed to update to Intel media-driver 20.4.2.

Note: 20.4.3 is not compiling https://github.com/intel/media-driver/issues/1103

```
=== tested on ===
 01:45:24 up 22:58,  load average: 1.17, 1.22, 2.04
Generic.x86_64-devel-20201207142003-b781374
Linux LibreELEC 5.9.12 #1 SMP Mon Dec 7 14:05:54 UTC 2020 x86_64 GNU/Linux
Starting Kodi (19.0-BETA2 (18.9.821) Git:19.0b2-Matrix). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2020-12-07 by GCC 10.2.0 for Linux x86 64-bit version 5.9.12 (329996)
Running on LibreELEC (community): devel-20201207142003-b781374 9.80, kernel: Linux x86 64-bit version 5.9.12
FFmpeg version/source: 4.3.1-Kodi
Host CPU: Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz, 4 cores available
[    0.000000] DMI:  /NUC6i5SYB, BIOS SYSKLi35.86A.0073.2020.0909.1625 09/09/2020
```

### CODE REVIEW

**Comment by mglae** [comment]
Updating media-driver usually requires updating gmmlib and libva.

**Comment by heitbaum** [comment]
My current build tree.

git ls | grep libva | head
caf208b5dc libva: updated to 2.10.0 [heitbaum]
git ls | grep gmm | head
06423d4b05 gmmlib: update to 20.3.2 [mglae]

But you are right media-driver 20.4.3 is dependant on gmmlib 20.3.3.
I have just updated to gmmlib 20.3.3 (and will test along side media-driver 20.4.3) media-driver 
- build was successful
Media-driver 20.4.[23] says its happy with the earlier libva’s
-- Checking for module 'libva>=1.8.0'
--   Found libva, version 1.10.0

I had been waiting for the official libva release notice before raising that PR.
If you suggest - I can rebase this to media-driver 20.4.3,libva,gmmlib (still noting the build error I had with Mesa 20.3.0)

**Comment by mglae** [comment]
If you see no regressions in media-driver 20.4.3 bump it together with gmmlib 20.3.3 and wait with libva 2.10.0 until official release.

**Comment by heitbaum** [comment]
> If you see no regressions in media-driver 20.4.3 bump it together with gmmlib 20.3.3 and wait with libva 2.10.0 until official release.

All looking good - ran 20.4.3, 20.3.3 and 1.10.0 for 4 hours of playback against Mesa 20.3.0  So will push.

**Comment by heitbaum** [comment]
** also did a full clean and full build. All ok.

**Review by CvH — APPROVED** [review]

**Comment by heitbaum** [comment]
Reached out to Carl @ Intel, and 1.10.0 likely to be officially released this/next week - but confirmed tagged 1.10.0 is the one.

**Pull request merged**
