### PR TITLE
Docker update to 17.10

### PR DESCRIPTION
**Pull request by Raybuntu**
Apparently moby is not required after all. Although it's possible to build individual moby and docker-cli packages those upstream git repo's do not correspond with the Actual docker release. There are no tags whatsoever in moby.
Better to use docker-ce repo which bundles moby and docker-cli and follows official Docker release cycle. So for simplicity I'm moving moby related code back to the docker package.
Several package bumps of docker depends.
Also docker requires a more recent GO version. 
I guess only syncthing besides docker + dependencies requires GO so I'll have to test if that's still building before a merge.
I have tested this with linuxserver.io nexcloud addon and it's working so far.

### CODE REVIEW

**Comment by Raybuntu** [comment]
I've tested syncthing and it's building with updated GO.

**Comment by Raybuntu** [comment]
Thanks

**Comment by escalade** [comment]
Needs approval (and backport?).

**Comment by Raybuntu** [comment]
Not sure what you mean by "needs approval"? PR is already approved. The  commits after that approval where just a rebase to fix recent PKG_TOOLCHAIN changes in master.

**Comment by escalade** [comment]
I thought every PR needed approval by two persons. In any case, I just want to see it merged ;)

**Comment by Raybuntu** [comment]
Ahh I didn't know that. Thanks.

**Pull request merged**
