### PR TITLE
Update inputstream.adaptive to version 2.4.4-Leia

### PR DESCRIPTION
**Pull request by JavierNicolas**

### CODE REVIEW

**Comment by alex1616** [comment]
Usefull for Disney+ !

**Comment by MilhouseVH** [comment]
Thanks for this.

**Comment by JavierNicolas** [comment]
> Thanks for this.
No problem. When will be available? Will it come as a LibreElec update or simply as a add-on update?

**Comment by CvH** [comment]
Around today evening as normal addon update

**Pull request merged**
