### PR TITLE
backport of #1321 (linux-amlogic: update to 83803a1)

### PR DESCRIPTION
**Pull request by lrusak**
backport of #1321

### CODE REVIEW

**Comment by Raybuntu** [comment]
Should I close mine https://github.com/LibreELEC/LibreELEC.tv/pull/1319?

**Comment by lrusak** [comment]
I didn't see yours when I made this. We can use either.

You should always PR to master first though, otherwise we get out of sync.

**Comment by Raybuntu** [comment]
OK sorry. I closed mine.

**Comment by lrusak** [comment]
updated.

**Pull request merged**
