### PR TITLE
packages: align source code licence usage with project licence

### PR DESCRIPTION
**Pull request by MilhouseVH**
The [project licence](https://github.com/LibreELEC/LibreELEC.tv/blob/5ccaa745e268b0a1763a4df732bbace45670945b/README.md) currently states:

---
**License**

LibreELEC original code is released under [GPLv2](https://www.gnu.org/licenses/gpl-2.0.html).

and

**Copyright**

... Unless expressly stated otherwise all code submitted to the LibreELEC project (in any form) is licensed under [GPLv2](https://www.gnu.org/licenses/gpl-2.0.html) ...

---

As we appear to have unintentionally diverged at some point by permitting a looser interpretation of the licence, this PR aligns the LibreELEC copyrighted source code with the correct LibreELEC project licencing requirements.

### CODE REVIEW

**Comment by Raybuntu** [comment]
Why do you think you are legally allowed to do such a change?
Before SPDX was introduced almost every file had a header saying GPLv2 or later. This is clearly a license restriction hence you need to ask everyone who made changes to the code of the individual packages if she/he agrees. @sraue is/was the main license holder and I doubt he would agree.

And the main license says it clearly: "Unless expressly stated otherwise.."
So this is not legit.

**Comment by anoma** [comment]
Only code ` # Copyright (C) 2016-present Team LibreELEC (https://libreelec.tv)` is touched in this PR so everything should be fine.

**Comment by Raybuntu** [comment]
@anoma ????
https://github.com/LibreELEC/LibreELEC.tv/pull/3381/files#diff-a30d6dd617d48b03b4d0149656d3868aR1

**Comment by anoma** [comment]
@Raybuntu this is quite a long list so please excuse if I am missing something but as far as I can tell all the content you linked is copyright LibreELEC? Let me know if you spot a change that isn't.

**Comment by Raybuntu** [comment]
@anoma I have not looked through all the file but I just picked a random one:
https://github.com/LibreELEC/LibreELEC.tv/blob/d4f6326142c80203991ee445616812c851d82a2d/packages/addons/service/tvheadend42/source/bin/tv_grab_file

As you can see in Github there are several people who edited this file in git hence they all edited it under GPLv2-or-later. Therefore they are all copyright holders so you need to ask permission from everyone to re license unless you have written consent to forfeit copyright to this (iirc) non-existent legal entity  "Team LibreELEC".

**Comment by Raybuntu** [comment]
Here your are just claiming copyright:
https://github.com/LibreELEC/LibreELEC.tv/pull/3381/files#diff-82f30b0e06a851b7114f17db07d73b1fR2
Where the same file already was in OpenELEC:
https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/devel/configtools/package.mk

**Comment by Raybuntu** [comment]
Anotherone:
https://github.com/LibreELEC/LibreELEC.tv/pull/3381/commits/e691b3b6933f82c1fb2f75c0d9a8d85b533956b7#diff-5943e5276afe0fcf566c8b14d4f84d43R2
https://github.com/LibreELEC/LibreELEC.tv/commit/f51faa070d93ed357a3f035d81b1c0f79339b83b#diff-5943e5276afe0fcf566c8b14d4f84d43

**Comment by Raybuntu** [comment]
Ncurses was orignally from @sraue too:
https://github.com/LibreELEC/LibreELEC.tv/commit/f51faa070d93ed357a3f035d81b1c0f79339b83b#diff-d7b1183588993621193ec37fbe8cc9b8

**Comment by Raybuntu** [comment]
Popt:
https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/devel/popt/package.mk

**Comment by Raybuntu** [comment]
Slang:https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/devel/slang/package.mk

**Comment by Raybuntu** [comment]
Nevermind. I will not spam this PR. Go ahead.

**Comment by vpeter4** [comment]
In packages there were text

> #  LibreELEC is free software: you can redistribute it and/or modify
> #  it under the terms of the GNU General Public License as published by
> #  the Free Software Foundation, either version 2 of the License, or
> #  (at your option) any later version.

But now you are changing to only version 2?

**Comment by MilhouseVH** [comment]
> But now you are changing to only version 2?

Yes, as per the opening comment in this PR, the source code (with sole LibreELEC copyright) now aligns with the project licence which has always been GPLv2 only - no mention of `-or-later`. There is/was a mismatch between the two, now that issue is resolved.

**Comment by vpeter4** [comment]
This means license on top of package file is useless? What is stronger then: main project license or package file license?

**Comment by MilhouseVH** [comment]
> This means license on top of package file is useless?

Not at all, it simply means the top of package licence is now correct and aligns with the overall project licence.

> What is stronger then: main project license or package file license?

It merely corrects a mismatch, we could have changed either. In this case we decided to apply the project licence on packages where there was a difference.

**Comment by gotmi1k** [comment]
This is a very bad change as per https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility you can not legally include any subproject licensed under GPLv3 now, this includes Samba amongst a variety of other packages that LE is using.

**Comment by 5schatten** [comment]
@gotmi1k out of sheer curiosity how did you stumble upon this particular commit? Beside that which part of LibreELECs own code uses code that is or was licensed under GPLv3? Can you point me to some stuff that might violates them?

**Comment by MilhouseVH** [comment]
>This is a very bad change as per https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility you can not legally include any subproject licensed under GPLv3 now, this includes Samba amongst a variety of other packages that LE is using.

@gotmi1k These changes apply to the LibreELEC _build system_ and creating an operating system/distribution with software using a mixture of different licences is not prohibited by the GPL - for instance the Linux kernel is GPLv2, while Samba is GPLv3+, and our ability to build/include/distribute these packages despite their different licensing requirements is not affected by the LibreELEC build system being licensed as GPLv2.

Here's a quote from Stallman[1] on GPLv2/GPLv3 incompatibility when building an operating system:

> Fortunately, license incompatibility only matters when you want to link, merge or combine code from two different programs into a single program. There is no problem in having GPLv3-covered and GPLv2-covered programs side by side in an operating system. For instance, the TeX license and the Apache license are incompatible with GPLv2, but that doesn't stop us from running TeX and Apache in the same system with Linux, Bash and GCC. This is because they are all separate programs. Likewise, if Bash and GCC move to GPLv3, while Linux remains under GPLv2, there is no conflict.

The LibreELEC _build system_ is separate and distinct from Linux, Samba etc., hence there is no licence incompatibility. The sole purpose of this change is simply to eliminate the discrepancy/ambiguity that exists between the stated project licence (GPLv2) and the published build system headers (GPLv2+). This has actually been an ongoing issue for several years ever since the ambiguity first appeared in the previous OpenELEC project, and indeed one of the main agitators for this change within LibreELEC is the person that wrote the original OpenELEC licence.

Eliminating the ambiguity does however mean that any downstream projects taking the OpenELEC/LibreELEC build system source code and proceeding to re-licence this code with an incompatible licence with the sole intention of not allowing changes to be submitted back upstream, and/or using this LibreELEC GPLv2-only build system source code within an incompatible GPLv3 build system will be in violation of the GPLv2 licence under which the LibreELEC source code is now published. Re-licensing source code without the permission of all copyright owners, by the way, is blatantly illegal but that's another issue that will be dealt with separately.

Here's another quote from Stallman[1] on when GPLv2/GPLv3 *is* incompatible:

> When we say that GPLv2 and GPLv3 are incompatible, it means there is no legal way to combine code under GPLv2 with code under GPLv3 in a single program. This is because both GPLv2 and GPLv3 are copyleft licenses: each of them says, “If you include code under this license in a larger program, the larger program must be under this license too.” There is no way to make them compatible.

The LibreELEC build system is "a single program", and the licence of that single program must be respected, which is essentially GPLv2 (with some parts, `GPLv2-or-later` out of respect to existing copyright). For most forks of LibreELEC this change is not going to be an issue, but for those forks that have seen fit to ignore copyright by re-licensing OpenELEC/LibreELEC source code as GPLv3 (illegal) and/or using LibreELEC GPLv2 source code in an incompatible GPLv3 project (also illegal) they should:

a) First and foremost, respect existing copyright which prohibits licence changes without approval
b) Reconsider the incompatible licence they themselves are using - or stop using GPLv2 source code which is no longer compatible.

Hopefully this clears up the situation and allays your concerns.

1. http://gplv3.fsf.org/rms-why.html

**Comment by adamg88** [comment]
> The LibreELEC build system is "a single program", and the licence of that single program must be respected, which is essentially GPLv2 (with some parts, GPLv2-or-later out of respect to existing copyright). For most forks of LibreELEC this change is not going to be an issue, but for those forks that have seen fit to ignore copyright by re-licensing OpenELEC/LibreELEC source code as GPLv3 (illegal) and/or using LibreELEC GPLv2 source code in an incompatible GPLv3 project (also illegal) they should:

I guess this is directed at CE? Firstly LE build system is not "a single program" it is a bunch of scripts, a single program could only apply to the first script called which is scripts/image but everything it does is calling other scripts. So you don't expect when you call other programs or scripts from this script that they have to be compatible with the license. If you do you can't use fakeroot, because this is called too.

CE has not re-licensed to GPLv3 but rather changes that we have made have been licensed as GPLv3 which we are within our rights to do.

The LE license was GPLv2-or-later which you inherited by forking OE, you can not simply state that this was a mistake or an oversight along the way as it has been more than 2 years now of pushing PR's that this has been the case but on the subject of relicensing then I guess what is good for the goose is good for the gander, no?

Nobody has broken any laws either so I fail to see how you can say something is illegal, the GPL is a civil contract.

I should add that nothing has been ignored and CE has respected LE by leaving your by-lines in our fork which is more than can be said on the opposite side of the table.

**Comment by 5schatten** [comment]
@adamg88 
Well both OpenELEC & LibreELEC state that they are released under GPLv2 :thinking: 

> OpenELEC is released under GPLv2. Please refer to the "licenses" folder and source code for clarification on upstream licensing.

https://github.com/OpenELEC/OpenELEC.tv/blob/master/README.md

> LibreELEC is released under GPLv2. Please refer to the "licenses" folder and source code for clarification on upstream licensing.

https://github.com/LibreELEC/LibreELEC.tv/blob/40af3531322b723e9ec76204c6a65c19f01574dc/README.md

So I'm curious how it's possible to change the license to GPLv3 without permission of all contributors?

**Comment by adamg88** [comment]
> Well both OpenELEC & LibreELEC state that they are released under GPLv2 🤔

True but that doesn't say under what provision, however the license headers clearly state GPLv2-or-later and it has been that way for a number of years.

> So I'm curious how it's possible to change the license to GPLv3 without permission of all contributors?

In GPLv2-or-later permission is not required, but even with GPLv2-only where new files are created then the license is not inherited as LE is not a single program.

**Pull request merged**
