### PR TITLE
RPi/RPi2/imx6/Odroid-C2: enable fbtft

### PR DESCRIPTION
**Pull request by vitalogy**
https://forum.libreelec.tv/thread-2487.html

### CODE REVIEW

**Comment by lrusak** [comment]
Thanks but can this add-on run on all hardware? if so you need to adjust the kernel configs of all the projects

**Comment by vitalogy** [comment]
I can enable fbtft for other hardware too, but i think it makes no sense to do so for Generic and Weetek. Both have no GPIO to connect such a device. I suppose it for Weetek devices.
So i can do this for RPi, imx6 (hummingboard) and Odroid-C2.

The addon kodisplay should run on other hardware too, but need probably same work in the package SDL, because i have disabled some stuff.

**Comment by vitalogy** [comment]
RPi - done
imx6 - fbtft was always been enabled in xbian-4.4
Odroid-C2 - not possible, due to old kernel

**Comment by gdachs** [comment]
[here](https://github.com/torvalds/linux/blob/5924bbecd0267d87c24110cbe2041b5075173a25/drivers/staging/fbtft/README#L19) is explained what to do with kernels before 3.15. So it should be possible to use it with Odroid C2.

**Comment by lrusak** [comment]
I ask because we try to keep feature parity the same between projects unless it is completely not possible.

**Comment by vitalogy** [comment]
rebased
I can test imx6 this week.
What is the right naming convention for patches?

**Comment by vpeter4** [comment]
imx6 linux 3.14 builds. But I have no hw to test. Let's assume it works.

**Comment by vitalogy** [comment]
- build imx6 with linux-3.14 and fbtft
- build dependencies for kodisplay (pygame,SDL)
- loaded fbtft with
  `fbtft_device custom name=fb_ili9341 gpios=reset:67,dc:195,led:72 speed=24000000 busnum=1`
- ... and kodisplay works on imx6

**Comment by vpeter4** [comment]
That's nice :)
Are there any cheap USB based displays available like this?

**Comment by vitalogy** [comment]
As far as I know there is no cheap display with USB connection. I'm own only displays with GPIO too.
Btw, the patch for Odroid and imx6 is similar the same, is there a way to make one patch available for both projects?

**Comment by vpeter4** [comment]
Patch can be used for all projects or for only one.

**Comment by vitalogy** [comment]
If someone is interested to test it for RPi2/3:
[RPi2/3 LibreELEC image](http://milaw.biz/files/fbtft_kodisplay/LibreELEC-RPi2.arm-8.0-devel-20161216145314-r24969-g61268ad.img.gz) 128MB
[RPi2/3 LibreELEC tar for update](http://milaw.biz/files/fbtft_kodisplay/LibreELEC-RPi2.arm-8.0-devel-20161216145314-r24969-g61268ad.tar) 141MB
[RPi2/3 Addon KoDisplay](http://milaw.biz//files/fbtft_kodisplay/script.kodisplay-0.1.6.zip) (includes SDL/pygame) 1.5MB

**Comment by vitalogy** [comment]
The fbtft modules were already enabled in imx-4.4 and will be enabled for other projects too.
Can someone take a look at this PR ...

**Comment by wrxtasy** [comment]
fbtft was added to the HardKernel S905 C2 Kernel 6 months ago:
https://github.com/hardkernel/linux/tree/odroidc2-3.14.y/drivers/video/fbtft

Not sure where @vitalogy grabbed his S905 backport sources from but its worth posting here for future reference.

**Comment by chewitt** [comment]
This PR has been gathering dust. If it is still desired/required there needs to be agreement on the changes and it needs rebasing against current kernel sources. If I hear nothing in the next week it will be closed. Thanks.

**Comment by chewitt** [comment]
I'm closing this PR due to lack of follow-up from everyone including the submitter. Thanks.

**Pull request closed without merging**
