### PR TITLE
Python3: update to 3.9.10

### PR DESCRIPTION
**Pull request by heitbaum**
Updated for patches completed:
- Merge changes from buildroot patches
  - https://patchwork.ozlabs.org/project/buildroot/patch/20201014101848.972915-1-james.hilliard1@gmail.com/
  - https://lore.kernel.org/buildroot/20211215141628.15283-1-peter@korsgaard.com/
- Update recent backport patch (in 3.9.10) for:
  - `GCC 8+ returns $arch-linux-{musl,uclibc} for musl/uClibc based toolchains confusing python. Fix that up` 
- Remove upstreamed patch:
  - [packages/lang/Python3/patches/Python3-0500-fix-bpo45262.patch](https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/lang/Python3/patches/Python3-0500-fix-bpo45262.patch)
- Rebased patches

Others:
- update libxml2 to be compatible with Python >= 3.9.0a4

### CODE REVIEW

**Review by HiassofT — APPROVED** [review]
Runtime test on RPi4 looks good, youtube and LE settings addons still work.

Let's get it in and let jenkins find out if some addons may need additional fixing

**Comment by polojoe** [comment]
builds since february 13th are crashing kodi when opening some addons on rpi4 for me. build from february 12th is ok.

**Comment by heitbaum** [comment]
> builds since february 13th are crashing kodi when opening some addons on rpi4 for me. build from february 12th is ok.

Have the addons been recompiled with python 3.9? What are the addons?

**Comment by polojoe** [comment]
eg YouTube addon

**Comment by polojoe** [comment]
crashes are skin related (estuary mod v2), I contacted author.

**Pull request merged**
