### PR TITLE
linux (Allwinner): Bluetooth: btrtl: Add support for RTL8822BS UART

### PR DESCRIPTION
**Pull request by heitbaum**
Found in some variants of Tanix TX6

Before:
[    7.512876] rtw_8822bs mmc2:0001:1: Firmware version 27.2.0, H2C version 13
[    8.219545] Bluetooth: hci0: RTL: examining hci_ver=07 hci_rev=000b lmp_ver=07 lmp_subver=8822
[    8.430833] Bluetooth: hci0: RTL: examining hci_ver=07 hci_rev=000b lmp_ver=07 lmp_subver=8822
[    8.430866] Bluetooth: hci0: RTL: unknown IC info, lmp subver 8822, hci rev 000b, hci ver 0007
After:
[    8.958224] rtw_8822bs mmc2:0001:1: Firmware version 27.2.0, H2C version 13
[    9.017294] Bluetooth: hci0: RTL: examining hci_ver=07 hci_rev=000b lmp_ver=07 lmp_subver=8822
[    9.021399] Bluetooth: hci0: RTL: rom_version status=0 version=2
[    9.021428] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822bs_fw.bin
[    9.024180] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822bs_config.bin
[    9.048050] Bluetooth: hci0: RTL: cfg_sz 75, total sz 24543
[   10.316891] Bluetooth: hci0: RTL: fw version 0xaa89f793

### CODE REVIEW

**Comment by heitbaum** [comment]
```
LibreELEC:~ # bluetoothctl 
Agent registered
[bluetooth]# list
Controller 54:EF:33:E9:0A:B7 LibreELEC [default]
[bluetooth]# scan on
Discovery started
[CHG] Controller 54:EF:33:E9:0A:B7 Discovering: yes
[NEW] Device 05:C9:29:FE:9B:6E 05-C9-29-FE-9B-6E
[NEW] Device D8:E0:E1:90:5F:64 [TV] Samsung 6 Series (43)
[NEW] Device 56:D8:60:DC:6D:9D 56-D8-60-DC-6D-9D
[NEW] Device 67:C4:35:3F:5B:73 67-C4-35-3F-5B-73
[NEW] Device 46:E9:02:C8:0B:C4 46-E9-02-C8-0B-C4
[NEW] Device 34:58:4F:3A:BF:18 34-58-4F-3A-BF-18
[NEW] Device 6D:E8:53:BD:5D:EB 6D-E8-53-BD-5D-EB
[NEW] Device 6F:89:C6:EF:3E:C5 6F-89-C6-EF-3E-C5
[NEW] Device 62:11:09:56:9F:DF 62-11-09-56-9F-DF
[NEW] Device 03:26:94:A2:BC:6D 03-26-94-A2-BC-6D
[NEW] Device 49:C5:E9:4C:A5:AA 49-C5-E9-4C-A5-AA
[NEW] Device 55:4F:1F:91:92:86 55-4F-1F-91-92-86
[NEW] Device 7B:69:AD:6B:3A:6A 7B-69-AD-6B-3A-6A
[NEW] Device 63:EC:ED:61:DD:00 63-EC-ED-61-DD-00
[NEW] Device 4E:0B:C1:01:58:38 4E-0B-C1-01-58-38
[NEW] Device A4:34:F1:DA:C4:9E LUNA MINI3
[CHG] Device D8:E0:E1:90:5F:64 LegacyPairing: yes
[CHG] Device D8:E0:E1:90:5F:64 Class: 0x000c043c
[CHG] Device D8:E0:E1:90:5F:64 Icon: audio-card
[NEW] Device 44:AE:AB:83:C7:00 44-AE-AB-83-C7-00
[NEW] Device 08:DF:1F:E5:CE:E8 LE-Bose QuietComfort 35
```

**Comment by jernejsk** [comment]
Same issue with both FWs?

**Comment by heitbaum** [comment]
> Same issue with both FWs?

Yep. Just reading into what those 2 x HCI are. (Steep reading curve) wondering if it is a BT4.1 versus 4.2 thing. And the feature flags are not set right in btrtl.c

**Comment by heitbaum** [comment]
btmon output while running `modprobe hci_uart`
- generates a soft error and Bluetooth is available
  - `[  111.176802] Bluetooth: hci0: Opcode 0x c7a failed: -56`
  - When performing HCI_OP_WRITE_SC_SUPPORT
```
…
< HCI Command: Write Secure Conne.. (0x03|0x007a) plen 1  #257 [hci0] 13.798533
        Support: Enabled (0x01)                                                
> HCI Event: Command Complete (0x0e) plen 4               #258 [hci0] 13.799136
      Write Secure Connections Host Support (0x03|0x007a) ncmd 2
        Status: Unknown HCI Command (0x01)
  ```      


btmon output while running `modprobe hci_uart`
- generates a hard failure and Bluetooth is not available
  - `[  166.405326] Bluetooth: hci0: Opcode 0x c77 failed: -56`
  - When performing HCI_OP_READ_SYNC_TRAIN_PARAMS
```
…
< HCI Command: Read Local Extended Features (0x04|0x0004) plen 1                                              #243 [hci0] 21.142012
        Page: 2
> HCI Event: Command Complete (0x0e) plen 14                                                                  #244 [hci0] 21.142703
      Read Local Extended Features (0x04|0x0004) ncmd 2
        Status: Success (0x00)
        Page: 2/2
        Features: 0x5f 0x03 0x00 0x00 0x00 0x00 0x00 0x00
          Connectionless Peripheral Broadcast - Central
          Connectionless Peripheral Broadcast - Peripheral
          Synchronization Train
          Synchronization Scan
          Inquiry Response Notification Event
          Coarse Clock Adjustment
          Secure Connections (Controller Support)
          Ping
< HCI Command: LE Set Event Mask (0x08|0x0001) plen 8                                                         #245 [hci0] 21.142795
        Mask: 0x000000000000001f
          LE Connection Complete
          LE Advertising Report
          LE Connection Update Complete
          LE Read Remote Used Features Complete
          LE Long Term Key Request
> HCI Event: Command Complete (0x0e) plen 4                                                                   #246 [hci0] 21.143475
      LE Set Event Mask (0x08|0x0001) ncmd 2
        Status: Success (0x00)
< HCI Command: LE Read Advertising Channel TX Power (0x08|0x0007) plen 0                                      #247 [hci0] 21.143577
> HCI Event: Command Complete (0x0e) plen 5                                                                   #248 [hci0] 21.144161
      LE Read Advertising Channel TX Power (0x08|0x0007) ncmd 2
        Status: Success (0x00)
        TX power: 0 dbm (0x00)
< HCI Command: LE Read Accept List Size (0x08|0x000f) plen 0                                                  #249 [hci0] 21.144261
> HCI Event: Command Complete (0x0e) plen 5                                                                   #250 [hci0] 21.144863
      LE Read Accept List Size (0x08|0x000f) ncmd 2
        Status: Success (0x00)
        Size: 32
< HCI Command: LE Clear Accept List (0x08|0x0010) plen 0                                                      #251 [hci0] 21.144971
> HCI Event: Command Complete (0x0e) plen 4                                                                   #252 [hci0] 21.145573
      LE Clear Accept List (0x08|0x0010) ncmd 2
        Status: Success (0x00)
< HCI Command: Delete Stored Link Key (0x03|0x0012) plen 7                                                    #253 [hci0] 21.145679
        Address: 00:00:00:00:00:00 (OUI 00-00-00)
        Delete all: 0x01
> HCI Event: Command Complete (0x0e) plen 6                                                                   #254 [hci0] 21.146378
      Delete Stored Link Key (0x03|0x0012) ncmd 2
        Status: Success (0x00)
        Num keys: 0
< HCI Command: Read Synchronization Train Parameters (0x03|0x0077) plen 0                                     #255 [hci0] 21.146485
> HCI Event: Command Complete (0x0e) plen 9                                                                   #256 [hci0] 21.147157
      Read Synchronization Train Parameters (0x03|0x0077) ncmd 2
        invalid packet size
        01 ac bd 11 80 01                                ......          
= Close Index: 54:EF:33:E9:0A:B7                                                                                   [hci0] 21.147289
```

**Comment by heitbaum** [comment]
Using Patch 1/3 from “arm64: allwinner: a64: add bluetooth support for Pinebook” (and rebasing it to current kernel), and adding the quirk to the 8822 allows the BT to start without error.
- https://patchwork.kernel.org/project/netdevbpf/patch/20220524212155.16944-2-bage@debian.org/

**Comment by heitbaum** [comment]
Need to merge 
- https://github.com/LibreELEC/misc-firmware/pull/6
First, so that the misc-firmware package can be bumped in the PR.

**Review by chewitt — APPROVED** [review]

**Pull request merged**
