### PR TITLE
initramfs: enable DNS if network is up

### PR DESCRIPTION
**Pull request by chrisnovakovic**
I ran into a problem while trying to network-boot LibreELEC: by specifying a hostname for the NFS server in the `boot` or `disk` kernel parameters, the init script fails with a nondescript error message. This is because, while my DHCP server is pushing a DNS server address (and the kernel is reporting it in `/proc/net/pnp`), the address is not being written to `/etc/resolv.conf` and the copy of glibc in the initramfs has no DNS resolver anyway.

This PR adds just enough of NSS to allow glibc to perform DNS resolutions in the initramfs, and writes any DNS servers known to the kernel to `/etc/resolv.conf` so they can be used by the glibc resolver.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks, what device are you using as I can include this in the next RPi/RPi2/Generic test builds.

**Comment by chrisnovakovic** [comment]
Sorry, I just saw `CONTRIBUTING.md` - do you want me to redo this on a separate branch and create a new PR?

**Comment by MilhouseVH** [comment]
Well, you should have created a topic branch in your repo first, and then pushed from that branch, but that's just to make your life easier really. Now that you've closed this PR you might as well do it again from your topic branch.

**Comment by chrisnovakovic** [comment]
Will do - sorry for the confusion!

**Pull request closed without merging**
