### PR TITLE
RTL8812AU Use mirror repository

### PR DESCRIPTION
**Pull request by CGarces**
Branch 4.3.22_beta has been removed from the [repository](https://github.com/Grawp/rtl8812au_rtl8821au) in the package.

I have changed to a mirror as workaround.

Beta branch is used since #139

### CODE REVIEW

**Comment by lrusak** [comment]
@vpeter what do you think?

**Comment by vpeter4** [comment]
I think we should use 4.3.20 branch (which supports kernel >= 4.8.0) because it is newer than removed 4.3.22_beta.

@sopparus: I think you proposed the same to me few days back? But I didn't check this branch.

**Comment by sopparus** [comment]
My vote goes for https://github.com/diederikdehaas/rtl8812AU/commits/driver-4.3.22-beta
it's based on the same one as the older one but this branch gets updated for newer kernel and other stuff.

@jerome-benoit hade an image for me with this driver and it's tested and works fine.

**Comment by CGarces** [comment]
Ok, I'll made the changes tonight and remove my repo.
Any patch is needed over ./os_dep/linux/usb_intf.c?

**Comment by jerome-benoit** [comment]
Here is the patch that sopparus have tested: https://github.com/PimentNoir/LibreELEC.tv/commit/d49a86ba9f0b6851a49c3b6750c08eea724f9358

**Comment by chewitt** [comment]
I'd prefer if we continued to use the current driver location (but 4.3.20 branch with 4.8 changes) as it's the main one used and maintained by Arch Linux:

https://aur.archlinux.org/packages/rtl8812au_rtl8821au-dkms-git/

**Comment by jerome-benoit** [comment]
Le 03/11/2016 à 17:26, Christian Hewitt a écrit :
>
> I'd prefer if we continued to use the current driver location (but
> 4.3.20 branch with 4.8 changes) as it's the main one used and
> maintained by Arch Linux:
>
> https://aur.archlinux.org/packages/rtl8812au_rtl8821au-dkms-git/
>
>

Here is the build with this driver version for RTL8812AU :
http://people.piment-noir.org/~fraggle/download/libreelec/LibreELEC-imx6.arm-8.0-devel-20161104162251-r24371-g7c8944f.img.gz
against the master branch.

The branch containing the changes made to the RTL8812AU package is here
: https://github.com/PimentNoir/LibreELEC.tv/commits/RTL8812AU-update

If you want me to make the PR, just let me know.

Regards,

-- 
Jérôme Benoit aka fraggle
Piment Noir - http://piment-noir.org
OpenPGP Key ID : 9FE9161D
Key fingerprint : 9CA4 0249 AF57 A35B 34B3 AC15 FAA0 CB50 9FE9 161D

**Comment by sopparus** [comment]
just tried @jerome-benoit  image with the 4.3.20 drivers arch is using and the dns issue I had before isnt there anymore.

**Comment by jerome-benoit** [comment]
On Sun, 06 Nov 2016 08:06:25 -0800 in
<LibreELEC/LibreELEC.tv/pull/901/c258690607@github.com>, sopparus
<notifications@github.com> wrote:

> just tried @jerome-benoit  image with the 4.3.20 drivers arch is
> using and the dns issue I had before isnt there anymore. 

Ok, I make a PR then. 

Regards,

-- 
Jérôme Benoit aka fraggle
Piment Noir - http://piment-noir.org
OpenPGP Key ID : 9FE9161D
Key fingerprint : 9CA4 0249 AF57 A35B 34B3 AC15 FAA0 CB50 9FE9 161D

**Comment by CGarces** [comment]
Superseded by #923

**Pull request closed without merging**
