### PR TITLE
Kodi "Piers"

### PR DESCRIPTION
**Pull request by heitbaum**
- kodi: update to githash d212b0a (July 6 2024)
- kodi: update to githash d7876de (July 9 2024)
- kodi: update to githash 060417c (July 14 2024)
- pcre: drop unused package
  - last part of #6798

needs:
- https://github.com/LibreELEC/service.libreelec.settings/pull/322

~~moved package changes into #9076~~
- ~~exiv2: initial package~~
  - ~~https://github.com/xbmc/xbmc/pull/24109~~
  - ~~Added Kodi dependency~~
  - ~~exiv2: update to 0.28.3~~
  - ~~Needs to changed over to meson~~
- ~~pcre2: build 8BIT target~~

### CODE REVIEW

**Comment by heitbaum** [comment]
> * kodi: update to githash 42120bb
> * libmicrohttpd: swap to shared library

Testing on ADL x86_64

Issues:
- Timezone wrong (known)

**Comment by vpeter4** [comment]
Is it `evix2` or `exiv2` ?

**Comment by enen92** [comment]
exiv2 new version will likely be released tomorrow (https://github.com/Exiv2/exiv2/issues/3008)

**Comment by heitbaum** [comment]
> exiv2 new version will likely be released tomorrow ([Exiv2/exiv2#3008](https://github.com/Exiv2/exiv2/issues/3008)). The version you're bundling is not compatible with some of the cmake options (e.g. disable filesystem) and needs patching. However, the new version will solve this.

Added the 0.28.3 published version

```
UNPACK      exiv2
BUILD      exiv2 (target)
    TOOLCHAIN      cmake
Executing (target): cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/etc/cmake-x86_64-libreelec-linux-gnu.conf -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DEXIV2_ENABLE_WEBREADY=OFF -DEXIV2_ENABLE_XMP=OFF -DEXIV2_ENABLE_CURL=OFF -DEXIV2_ENABLE_NLS=OFF -DEXIV2_BUILD_SAMPLES=OFF -DEXIV2_BUILD_UNIT_TESTS=OFF -DEXIV2_ENABLE_VIDEO=OFF -DEXIV2_ENABLE_BMFF=OFF -DEXIV2_ENABLE_BROTLI=OFF -DEXIV2_ENABLE_INIH=OFF -DEXIV2_ENABLE_FILESYSTEM_ACCESS=OFF -DEXIV2_BUILD_EXIV2_COMMAND=OFF -DBUILD_WITH_CCACHE=ON /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/exiv2-0.28.3
-- The C compiler identification is GNU 14.1.0
-- The CXX compiler identification is GNU 14.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/bin/python3.12 (found version "3.12.3") found components: Interpreter
-- Found ZLIB: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libz.so (found version "1.3.1")
-- Performing Test Iconv_IS_BUILT_IN
-- Performing Test Iconv_IS_BUILT_IN - Success
-- Found Iconv: built in to C library
-- Iconv_INCLUDE_DIRS :
-- Iconv_LIBRARIES :
-- Program ccache found
-- Performing Test HAS_FSTACK_CLASH_PROTECTION
-- Performing Test HAS_FSTACK_CLASH_PROTECTION - Success
-- Performing Test HAS_FCF_PROTECTION
-- Performing Test HAS_FCF_PROTECTION - Success
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG - Success
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Performing Test EXV_STRERROR_R_CHAR_P
-- Performing Test EXV_STRERROR_R_CHAR_P - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Install prefix:    /usr
-- ------------------------------------------------------------------
-- CMake Generator:   Ninja
-- CMAKE_BUILD_TYPE:  Release
-- Compiler info: GNU (/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-g++) ; version: 14.1.0
-- CMAKE_CXX_STANDARD:17
--  --- Compiler flags ---
-- General:           -march=x86-64-v3 -Wall -pipe  -O2 -fomit-frame-pointer -DNDEBUG
         -fstack-clash-protection
         -fcf-protection
         -fstack-protector-strong
         -Wp,-D_GLIBCXX_ASSERTIONS
         -Wp,-D_FORTIFY_SOURCE=2
         -Wall
         -Wcast-align
         -Wpointer-arith
         -Wformat-security
         -Wmissing-format-attribute
         -Woverloaded-virtual
         -W
         -Wno-error=format-nonliteral
-- Extra:
-- Debug:             -g3 -gstrict-dwarf -O0
-- Release:
-- RelWithDebInfo:    -O2 -g -DNDEBUG
-- MinSizeRel:        -Os -DNDEBUG
--  --- Linker flags ---
-- General:           -Wl,--as-needed -fuse-ld=gold
-- Debug:
-- Release:
-- RelWithDebInfo:
-- MinSizeRel:
--
-- Compiler Options
-- Warnings as errors:                 NO
-- Use extra compiler warning flags:   NO
--
-- ------------------------------------------------------------------
-- Building shared library:            NO
-- Building PNG support:               YES
-- XMP metadata support:               NO
-- Building BMFF support:              NO
-- Brotli support for JPEG XL:         NO
-- Native language support:            NO
-- Building video support:             NO
-- Nikon lens database:                YES
-- Building webready support:          NO
-- Building exiv2 command:             NO
-- Building samples:                   NO
-- Building unit tests:                NO
-- Building fuzz tests:                NO
-- Building doc:                       NO
-- Building with coverage flags:       NO
-- Building with filesystem access     NO
-- Using ccache:                       YES
-- Configuring done (0.5s)
-- Generating done (0.0s)
-- Build files have been written to: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/exiv2-0.28.3/.x86_64-libreelec-linux-gnu
Executing (target): ninja
[46/64] Building CXX object src/CMakeFiles/exiv2lib.dir/image.cpp.o
../src/image.cpp: In static member function 'static Exiv2::BasicIo::UniquePtr Exiv2::ImageFactory::createIo(const std::string&, bool)':
../src/image.cpp:780:12: warning: unused variable 'fProt' [-Wunused-variable]
  780 |   Protocol fProt = fileProtocol(path);
      |            ^~~~~
[64/64] Linking CXX static library lib/libexiv2.a
[0/1] Install the project...
-- Install configuration: "Release"
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/lib/pkgconfig/exiv2.pc
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/share/man/man1/exiv2.1
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/lib/libexiv2.a
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/basicio.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/bmffimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/bmpimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/config.h
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/convert.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/cr2image.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/crwimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/datasets.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/easyaccess.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/epsimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/error.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/exif.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/exiv2.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/futils.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/gifimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/image.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/image_types.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/iptc.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/jp2image.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/jpgimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/metadatum.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/mrwimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/orfimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/pgfimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/photoshop.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/preview.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/properties.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/psdimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/rafimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/rw2image.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/slice.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/tags.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/tgaimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/tiffimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/types.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/value.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/version.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/webpimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/xmp_exiv2.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/xmpsidecar.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/pngimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/exv_conf.h
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/include/exiv2/exiv2lib_export.h
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/lib/cmake/exiv2/exiv2Export.cmake
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/lib/cmake/exiv2/exiv2Export-release.cmake
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/lib/cmake/exiv2/exiv2ConfigVersion.cmake
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/.sysroot/exiv2.target/usr/lib/cmake/exiv2/exiv2Config.cmake
[0/1] Install the project...
-- Install configuration: "Release"
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/lib/pkgconfig/exiv2.pc
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/share/man/man1/exiv2.1
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/lib/libexiv2.a
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/basicio.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/bmffimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/bmpimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/config.h
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/convert.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/cr2image.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/crwimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/datasets.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/easyaccess.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/epsimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/error.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/exif.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/exiv2.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/futils.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/gifimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/image.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/image_types.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/iptc.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/jp2image.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/jpgimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/metadatum.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/mrwimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/orfimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/pgfimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/photoshop.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/preview.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/properties.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/psdimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/rafimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/rw2image.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/slice.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/tags.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/tgaimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/tiffimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/types.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/value.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/version.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/webpimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/xmp_exiv2.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/xmpsidecar.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/pngimage.hpp
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/exv_conf.h
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/include/exiv2/exiv2lib_export.h
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/lib/cmake/exiv2/exiv2Export.cmake
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/lib/cmake/exiv2/exiv2Export-release.cmake
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/lib/cmake/exiv2/exiv2ConfigVersion.cmake
-- Installing: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/exiv2-0.28.3/usr/lib/cmake/exiv2/exiv2Config.cmake

Build timing details:
================================
              unpack:      0.582
     pre-build setup:      0.002
           configure:      0.501
                make:     10.379
        make install:      0.024
        copy sysroot:      0.016
     cleanup install:      0.018
--------------------------------
          total time:     11.522
```

**Comment by vpeter4** [comment]
Instead of patching kodi (and maybe some other packages) for `pcre2` I think more appropriate place would be `pcre2` package itself to force using static library by default if only those were build. Why patching 2 or more packages if only one change is actually needed.

```
diff --git a/cmake/pcre2-config.cmake.in b/cmake/pcre2-config.cmake.in
index 84eebad..eb9d2db 100644
--- a/cmake/pcre2-config.cmake.in
+++ b/cmake/pcre2-config.cmake.in
@@ -23,6 +23,9 @@
 #   PCRE2::32BIT - The 32 bit PCRE2 library.
 #   PCRE2::POSIX - The POSIX PCRE2 library.
 
+# only static library was build so use it by default
+set(PCRE2_USE_STATIC_LIBS ON)
+
 set(PCRE2_NON_STANDARD_LIB_PREFIX @NON_STANDARD_LIB_PREFIX@)
 set(PCRE2_NON_STANDARD_LIB_SUFFIX @NON_STANDARD_LIB_SUFFIX@)
 set(PCRE2_8BIT_NAME pcre2-8)

```

**Comment by heitbaum** [comment]
> Instead of patching kodi (and maybe some other packages) for `pcre2` I think more appropriate place would be `pcre2` package itself to force using static library by default if only those were build. Why patching 2 or more packages if only one change is actually needed.
> 
> ```
> diff --git a/cmake/pcre2-config.cmake.in b/cmake/pcre2-config.cmake.in
> index 84eebad..eb9d2db 100644
> --- a/cmake/pcre2-config.cmake.in
> +++ b/cmake/pcre2-config.cmake.in
> @@ -23,6 +23,9 @@
>  #   PCRE2::32BIT - The 32 bit PCRE2 library.
>  #   PCRE2::POSIX - The POSIX PCRE2 library.
>  
> +# only static library was build so use it by default
> +set(PCRE2_USE_STATIC_LIBS ON)
> +
>  set(PCRE2_NON_STANDARD_LIB_PREFIX @NON_STANDARD_LIB_PREFIX@)
>  set(PCRE2_NON_STANDARD_LIB_SUFFIX @NON_STANDARD_LIB_SUFFIX@)
>  set(PCRE2_8BIT_NAME pcre2-8)
> ```

Because of

```
# pcre2-config.cmake
# ----------------
#
# Finds the PCRE2 library, specify the starting search path in PCRE2_ROOT.
#
# Static vs. shared
# -----------------
# To make use of the static library instead of the shared one, one needs
>>>> # to set the variable PCRE2_USE_STATIC_LIBS to ON before calling find_package.
# Example:
#   set(PCRE2_USE_STATIC_LIBS ON)
#   find_package(PCRE2 CONFIG COMPONENTS 8BIT)
```

```
CMake Error at /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find PCRE2: missing: 8BIT (found
  /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/cmake/pcre2-config.cmake
  (found version "10.44.0"))
Call Stack (most recent call first):
  /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:246 (_FPHSA_FAILURE_MESSAGE)
  /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:588 (_FPHSA_HANDLE_FAILURE_CONFIG_MODE)
  /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/cmake/pcre2-config.cmake:112 (find_package_handle_standard_args)
  cmake/modules/FindPCRE2.cmake:57 (find_package)
  cmake/scripts/common/Macros.cmake:378 (find_package)
  cmake/scripts/common/Macros.cmake:390 (find_package_with_ver)
  CMakeLists.txt:279 (core_require_dep)
```

**Comment by vpeter4** [comment]
You didn't look my patch good enough: I set this `set(PCRE2_USE_STATIC_LIBS ON)` at start of `pcre2-config.cmake` which does the same as setting from kodi.
And I test the patch and kodi is build fine.

**Comment by heitbaum** [comment]
> You didn't look my patch good enough: I set this `set(PCRE2_USE_STATIC_LIBS ON)` at start of `pcre2-config.cmake` itself which does the same as setting from kodi. The main difference is that problem is solved at the source. And I test the patch and kodi is build fine.

I didnt read the diff - just the comment, now I see what you’ve got with the detailed explanation. 

I see the patch in this WIP PR as a temporary during this WIP phase. I’d like to see it fixed upstream in Kodi (as it is already “static” in much of https://github.com/xbmc/xbmc/blob/master/cmake/modules/FindPCRE2.cmake) - if needed a variable as input into the Kodi cmake e.g. PCRE2_IS_STATIC

**Review by CvH — APPROVED** [review]

**Pull request merged**
