### PR TITLE
RPi support: drop ksoftirqd commit

### PR DESCRIPTION
**Pull request by MilhouseVH**
See: https://github.com/LibreELEC/LibreELEC.tv/pull/2382#issuecomment-362468188

### CODE REVIEW

**Comment by chrisnovakovic** [comment]
RPi builds still fail because the patch is against Linux 4.14.16 but `package.mk` still tries to compile 4.14.15. Plain sailing after setting `PKG_VERSION="4.14.16"` and `PKG_SHA256="070bdb482245977b1ff7f9008eb6455ec27501fb7438426bb54f3b592513ac24"` in `packages/linux/package.mk` though - thanks!

**Comment by MilhouseVH** [comment]
Yeah... hmm. Working on it.

**Comment by MilhouseVH** [comment]
Updated patch should apply cleanly against 4.14.15.

**Comment by HiassofT** [comment]
clean RPi2 master build succeeded with this, let's get it in

**Pull request merged**
