### PR TITLE
projects/WeTek*: Fix build with Kodi 17

### PR DESCRIPTION
**Pull request by kszaq**
1. dvdplayer changed to VideoPlayer, fix path in "Fix compiler badness" patch.
2. After https://github.com/xbmc/xbmc/pull/9050 it is not needed to modify SetNativeResolution to get 4k.

Tested to build properly but I don't have a Core nor 4k TV to test.

Ping @gdachs and @codesnake

### CODE REVIEW

**Comment by lrusak** [comment]
Please add the changes to the WeTek_Play as well.

**Comment by kszaq** [comment]
Compiler badness patch has already been fixed in https://github.com/LibreELEC/LibreELEC.tv/commit/27e79cd60bebd1744c06d02f0d912af4c40c408b and WP doesn't use 4k patch. I'll have a look if there are any other build issues.

**Comment by lrusak** [comment]
this patch can be dropped
```
projects/WeTek_Play/patches/kodi/0018-aml-Fix-stuttering-during-a-playback-of-a-video-with.patc
```
and this patch needs adjusting
```
projects/WeTek_Play/patches/kodi/0020-aml-Add-support-for-4k-resolutions.patch
```

**Comment by kszaq** [comment]
I see it now. I think both patches can be dropped as WP does not support 4k resolutions.

**Comment by lrusak** [comment]
sounds good to me

**Comment by kszaq** [comment]
I'm running a test build right now and will update the PR soon.

**Comment by kszaq** [comment]
Added WP patch and rebased. Builds OK.

**Comment by codesnake** [comment]
You will not get 4K on Linux without 0020-aml-Add-support-for-4k-resolutions.patch because it will always set 1920x1080 framebuffer, so you'll get a 4K resolution but image in 1920x1080 window. I will adjust the patch shortly and PR it upstream.

**Comment by kszaq** [comment]
@codesnake I deleted the 4k patch only for WeTek Play which doesn't support 4k anyway. For WeTek Core I adjusted the patch. I only deleted `SetNativeResolution` modification as it was simplified by you upstream. Can you please have a look at `0003-aml-Add-support-for-4k-resolutions.patch` change?

**Comment by codesnake** [comment]
@kszaq  Ah sorry, didn't notice that. +1 from me.

**Comment by codesnake** [comment]
@kszaq Your changes to 4K patch look good, but unfortunately I cannot test that too - I don't have a 4K TV. That patch was written blindly and tested by others.

**Comment by codesnake** [comment]
I asked out guys at WeTek to test a build with these changes and it seems 4K resolution work OK in Kodi, just the LE splash screen is top left corner:
le_4k

**Comment by kszaq** [comment]
Thank you. Is `hdmimode` in cmdline set to 4k? This would need modifying platform_init to support 4k resolutions.

**Comment by lrusak** [comment]
I'm happy with this 👍

**Pull request merged**
