### PR TITLE
mesa: update to mesa-19.2.3

### PR DESCRIPTION
**Pull request by MilhouseVH**

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Added blocker lablel.

`mesa`-19.2.2 no longer installs [glvnd headers](https://gitlab.freedesktop.org/mesa/mesa/commit/8355658fa857536d948773b361c5ede770e637a3), so we're missing `sysroot/usr/include/KHR/khrplatform.h`, causing `libepoxy` to fail.

Need to come up with a fix for that before we can proceed... probably something to change in `libglvnd`.

**Comment by MilhouseVH** [comment]
Thanks @5schatten for the extra fixes. Generic now builds successfully. Removing "merge blocked" label, but we probably also need to check RPi4 etc. before merging.

**Comment by HiassofT** [comment]
unclean RPi4 build was fine, runtime test too

**Comment by MilhouseVH** [comment]
Thanks, clean RPi4 build also seems OK (builds + runs).

**Pull request merged**
