### PR TITLE
WeTek_Play_2: set CONFIG_AML_AO_CEC=y

### PR DESCRIPTION
**Pull request by lrusak**
I'm not sure if anything else is needed as I don't have a device to test with.

### CODE REVIEW

**Comment by codesnake** [comment]
It seems CONFIG_AML_AO_CEC=y is not enough to enable CEC support: https://github.com/LibreELEC/LibreELEC.tv/commit/816a3e98d8d78d2c61fcfe03a1460e71c159a96c

With just CONFIG_AML_AO_CEC=y kernel fails to build.

**Comment by lrusak** [comment]
thanks, updated

**Comment by lrusak** [comment]
maybe it should be added to module depends?

**Comment by codesnake** [comment]
Yes, add to depends, or maybe #ifdef TVIN usage in CEC driver.

**Comment by codesnake** [comment]
I have tested this on my WP2, works fine for me. Thanks @lrusak.

**Comment by wrxtasy** [comment]
Yes that's the correct Kernel config.

I'm still having lots of issues getting HDMI CEC and LibCEC working on the Hub tho.
Same Kernel, same config, same set of patches.

**Pull request merged**
