### PR TITLE
kodi update to latest

### PR DESCRIPTION
**Pull request by CvH**
- kodi updated
- addons updated
- inputstream.adaptive had no new release since may and current release fails to build with current master so I bumped it to latest from git
- latest mr.boom didn't build so I didn't updated it

kodi runtime tested, addons buildtested for generic

### CODE REVIEW

**Comment by HiassofT** [comment]
FYI: kodi gbm also needs #4601 - please merge that before or together with this PR

**Comment by CvH** [comment]
updated to latest from today, works for generic

**Comment by jernejsk** [comment]
works for allwinner

**Review by HiassofT — APPROVED** [review]

**Comment by HiassofT** [comment]
RPi4 works fine, too, I'll take care about the game addon tags mess in a follow-up PR

**Pull request merged**
