### PR TITLE
Remove gperftools workaround in favor of TLS alignment patch to solve Widevine 4.10.2252.0 stability issues

### PR DESCRIPTION
**Pull request by wagnerch**
This patch is rolling back gperftools introduced in #5376, which was a workaround for TLS allocation failures from dlopen() calls.  In favor of the correct solution found by the CoreELEC team, which was a TLS alignment issue and requires another patch to glibc.

tcmalloc (gperftools) was found to cause stability issues on some devices that resulted in segmentation faults of the kodi executable.

### CODE REVIEW

**Comment by kszaq** [comment]
+1 for the revert as tcmalloc causes Kodi to crash when browsing content shared over UPnP (probably worth fixing as mentioned in https://github.com/CoreELEC/CoreELEC/pull/287#issuecomment-853786503) and users can preload libwidevine - this works for me but crashes for others...

**Comment by CvH** [comment]
@wagnerch just that we understand it correctly

the preload is not needed anymore
> LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so

due the increasing of the max possible value there should be no side-effects ?

**Comment by wagnerch** [comment]
@CvH correct LD_PRELOAD is no longer required, and neither is tcmalloc.  The reason for tcmalloc was to work around TLS allocation issues while dlopen()ing libwidevinecdm, because I knew that tcmalloc had TLS and was using a initial-exec model which was know to cause TLS allocation failures.  At the time, I didn't understand that this may be related to alignment. 

As for side effects, I personally haven't noticed any, but of course I had no problems with the workaround solution either but others did.   I guess other noteworthy things is x86_64 is already using a 64-byte alignment.  And aarch64 uses an __alignof__(struct pthread) to define this, where as arm uses 16 bytes for this.  Like the previous patch, it's just applied to arm, to help mitigate any issues.

I have been running this patch for about 4 or 5 hours on a RPi4.  I also did some testing of CE 19 with their patch on an Amlogic S905D, but it was some fairly brief testing 10-30 seconds of a Netflix stream, but others that had issues were reporting positive results so far on their forum.  Might be worthwhile to push it in a nightly, put it out there and solicit some feedback.

I also did test briefly the 9.2 branch with this patch, a few minutes of a Netflix stream, no noticeable issues there.  But LE 10 is really my daily driver.

**Review by CvH — APPROVED** [review]
tx, if fubar happens we can still revert

**Comment by vpeter4** [comment]
> And aarch64 uses an **alignof(struct pthread)** to define this, where as arm uses 16 bytes for this.

Fyi, **alignof(struct pthread)** on arm gives 16 bytes (or maybe 32 - don't remember anymore) which doesn't do what we need.

**Comment by knaerzche** [comment]
Do I understand correctly: LD_PRELOAD is no longer required (also not for libwidevinecdm.so)?
Doesn't seem to work:
```
2021-06-11 13:50:22.422 T:1002     INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 2, Type: VOD, Download speed: 0.0000 Bytes/s
2021-06-11 13:50:22.425 T:1002    ERROR <general>: AddOnLog: inputstream.adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)
2021-06-11 13:50:22.425 T:1002    ERROR <general>: AddOnLog: inputstream.adaptive: OpenDRMSystem failed
```
with
```
LibreELEC:~ # cat .kodi/cdm/config.json 
{"channel": "stable-channel", "desc": "", "file": "chromeos_13816.82.0_veyron-tiger_recovery_stable-channel_tiger-mp.bin", "filesize": 2319657472, "hwidmatch": "^TIGER .*", "manufacturer": "AOpen", "md5": "fb067e4cbb01964d9289e40a2b3cfb61", "model": "AOpen Chromebase Mini", "name": "AOpen Chromebase Mini", "photourl": "", "sha1": "2fb86333ded0738d6a185bbcf137e00131e6acf9", "sku": "", "url": "https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_13816.82.0_veyron-tiger_recovery_stable-channel_tiger-mp.bin.zip", "version": "13816.82.0", "zipfilesize": 1032829591, "chrome_version": "90.0.4430.218", "hwids": [], "hwid": "TIGER"}
```
Which should be  libwidevinecdm.so 4.10.2252.0. 

Note: LibreElec builds arm not aarch64 userspace for all arm projects - not sure this makes a difference here.
```
NAME="LibreELEC"
VERSION="nightly-20210611-f547d15"
ID="libreelec"
VERSION_ID="10.0"
PRETTY_NAME="LibreELEC (community): nightly-20210611-f547d15"
HOME_URL="https://libreelec.tv"
BUG_REPORT_URL="https://github.com/LibreELEC/LibreELEC.tv"
BUILD_ID="f547d15d698b61586da2738470114217b6885e26"
LIBREELEC_ARCH="RK3328.arm"
LIBREELEC_BUILD="community"
LIBREELEC_PROJECT="Rockchip"
LIBREELEC_DEVICE="RK3328"
```
where this commit is included.

**Comment by kszaq** [comment]
@knaerzche If you have a compile environment, you can try to bulid a simple app from https://github.com/xbmc/inputstream.adaptive/issues/678#issuecomment-839287040 place it in `/storage/.kodi/cdm` and check if it runs correctly.

Here is the binary prebuilt: 
[loader.zip](https://github.com/LibreELEC/LibreELEC.tv/files/6640337/loader.zip)

**Comment by knaerzche** [comment]
It cannot work because of https://github.com/LibreELEC/LibreELEC.tv/pull/5431. I wonder if it ever was tested for anything beyond RPi, which doesn't use arm64 kernel.
If glibc patches are applied correctly it works.

**Comment by wagnerch** [comment]
@knaerzche From my end I do not have anything other than an RPi4 on LibreELEC, so you are correct in terms of the extent of testing.  I certainly wasn't aware of this gap in how the build system works, but agree with you that the build system should understand userland ARCH vs kernel ARCH.

**Comment by CvH** [comment]
can anyone confirm ?
https://forum.libreelec.tv/thread/24076-le-9-2-and-le10-fix-for-widevine/?postID=157230#post157230

```
ISH checks 2 things to determine if the system is capable of handling Widevine CDM v4.10.2252.0 and after:
* TLS 64 byte alignment: for the detection it needs to add the 'arm64tls' suffix to the version number.
```

so we would need https://github.com/dtechsrv/LibreELEC-AML/commit/ce5d1584d6cdd42e90ab4aa2d5a24d83413ea0f6#diff-246ec78884f9e3f4631cd12faacde7f0bfcbf7c16824b02791f573c3bb095ce6 ??

**Comment by vpeter4** [comment]
https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/450

**Comment by knaerzche** [comment]
Please don't go override/change the glibc version string which might have more implcatations than we are currently aware.
I don't understand why inpustream helper would want to "detect" what an OS supports and expecting the OS to be behave like it wants.
In my opption we off-hacked glibc enough. Users should ignore this dialog and just install the latest libwidevinecdm.

**Comment by vpeter4** [comment]
It is to prevent ISH to download new library which can't be used on non-supported systems.

**Comment by dtechsrv** [comment]
That's all nice, but then what happens next? Will there be another solution, idea or someting???
Because the glibc suffix solution doesn't seem to be officially acceptable, as I see.

What I want to say is that there is a pretty buggy version 9.2.7, and we should do something with it.

**Comment by vpeter4** [comment]
We are waiting for mainline solution which fixes everything.

**Comment by dtechsrv** [comment]
Is this patch already acceptable instead of the glibc version suffix?
[https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/450#issuecomment-870218942](https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/450#issuecomment-870218942)

**Pull request merged**
