### PR TITLE
gcc: update to gcc-8.2.0

### PR DESCRIPTION
**Pull request by MilhouseVH**
Successfully build and run-time tested RPi/RPi2/Generic with 4.14.y/4.17.y and 4.18-rc7 kernels.

### CODE REVIEW

**Comment by 5schatten** [comment]
Does "glfw" build fine for you? I've got some undefined references:
https://pastebin.com/nn5ATpU4

RPi build finished without errors.

So I've updated the glfw package to 3.2.1 and at least it builds fine now.

`# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)

PKG_NAME="glfw"
PKG_VERSION="3.2.1"
PKG_SHA256="e10f0de1384d75e6fc210c53e91843f6110d6c4f3afbfb588130713c2f9d8fe8"
PKG_ARCH="x86_64"
PKG_LICENSE="BSD"
PKG_SITE="http://glfw.org"
PKG_URL="https://github.com/glfw/glfw/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain mesa glu"
PKG_SECTION="graphics"
PKG_SHORTDESC="provides a simple API for creating windows, contexts and surfaces, receiving input and events"
PKG_LONGDESC="provides a simple API for creating windows, contexts and surfaces, receiving input and events"

if [ "$OPENGL" = "no" ] ; then
  exit 0
fi

PKG_CMAKE_OPTS_TARGET="-DGLFW_BUILD_EXAMPLES=off \
                       -DGLFW_BUILD_TESTS=off \
                       -DGLFW_BUILD_DOCS=off"`

**Comment by MilhouseVH** [comment]
I successfully built `chrome` using latest LE master and this PR. Current LE master doesn't build `glfw` (or `gconf`) when building `chrome` - are you sure your tree is up to date, or do you have additional local patches?

`game.libretro.desmume` is the addon which builds `libretro-desmume` and the addon is currently configured in such a way (`PKG_ARCH="none"`) that it won't build for any project. This needs updating and fixing, unless you've already got the fixes?

I successfully built `mpd` which uses `boost` (1_65_1), so no `boost` issue as far as I can see. Can you tell me how you produced the `boost` problem?

**Comment by MilhouseVH** [comment]
Building `boost` 1_65_1 with `PROJECT=Generic ARCH=x86_64 scripts/build boost` is successful with current LE master and this PR (building on Ubuntu 16.04 VM).

**Comment by 5schatten** [comment]
I'm using Linux Mint Mate 19 so basically Ubuntu 18.04.x to build my LE 9.0 fork. Right now I'm rebuilding the whole distro to make sure it's not related to something else but until now everything worked fine with gcc 8.1. 

You're right the chrome addon has no gconf dependency and maybe it's not needed anymore? I've basically forked escalades Remix build and his chrome-stable package needed it.

Maybe it was some odd ccache quirk or something. I see if it builds fine again & apply the commit again and report my results.

**Comment by MilhouseVH** [comment]
For `chrome` it looks like the package needs a bit of a cleanup as some depends have been removed but the packages remain. It's on the list!

Thanks for the commit, it may prove useful for when we update those retroplayer packages.

Submitting PRs is pretty straightforward, but the PRs will need to be based on LE master rather than a fork so maybe that doesn't fit in with your workflow and would mean extra work. However submitting the changes upstream (ie to LE master) is the best way to reduce the number of patches you (and related downstream distributions) will be carrying, so it all depends where you want to put the work in - once for upstream, or repeatedly for downstream.

**Comment by MilhouseVH** [comment]
We don't mind taking a PR that makes the build system work better for you, providing it's configurable (which keeps everyone happy), so that's one possibility if you want to drop some patches in future.

While ideally we'd prefer PRs that can be reviewed and ultimately merged, if that doesn't work for you and you're happy to provide a pointer every now and again then that's better than nothing, but what is implemented in LE master may not be 100% to your needs so you may still need to patch here and there.

**Comment by 5schatten** [comment]
Looks like a second try works fine. The RPi build finished without errors and the generic one is almost complete. I've rebuild the fork with gcc 8.1 to make sure it's not code related, made a distclean and now I'm rebuilding with gcc8.2. I've updated glfw to avoid  "undefined references", boost & libretro-desmume also build fine now.

**Pull request merged**
