### PR TITLE
[Allwinner,Generic,Rockchip] linux: Update to 5.10.21

### PR DESCRIPTION
**Pull request by heitbaum**
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.18
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.19
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.20
- 5.10.20 has quite a large number of patches
- log - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-5.10.y

https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.21

Also included in this PR are:
- Patch: PCI: rockchip: support ep-gpio undefined case (has been included in the upstream kernel)
- 5.10.20 included the i915 patches proposed for #5196 

**Generic - build and run tested - @heitbaum**

build tested for all of:
```
PROJECT=Allwinner ARCH=arm DEVICE=H6 UBOOT_SYSTEM=tanix-tx6 s/build linux
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 s/build linux
PROJECT=NXP ARCH=arm DEVICE=iMX8 s/build linux
PROJECT=Qualcomm ARCH=arm DEVICE=Dragonboard s/build linux
PROJECT=Samsung ARCH=arm DEVICE=Exynos s/build linux
PROJECT=Generic ARCH=x86_64 s/build linux
```

### CODE REVIEW

**Comment by jernejsk** [comment]
I very quickly tested this on Allwinner H6 and everything seems fine. Note that there are some important improvements in 5.10.20 for AW, so I would like this to be merged in LE10.

**Comment by heitbaum** [comment]
> I very quickly tested this on Allwinner H6 and everything seems fine. Note that there are some important improvements in 5.10.20 for AW, so I would like this to be merged in LE10.

Linux 5.10.21-rc1: Doesn’t look like there is anything of priority - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-5.10.y

**Comment by SupervisedThinking** [comment]
LGTM

**Comment by knaerzche** [comment]
Runtime tested for RK as well. I also vote for having 5.10.20 (or later) in LE10.

**Comment by SupervisedThinking** [comment]
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.21

**Comment by jernejsk** [comment]
5.10.21 seems to be important for us. Fixed memory leak in v4l2, plenty of bluetooth fixes and audio fixes.

**Comment by heitbaum** [comment]
Updated and run tested on 
```
=== tested on ===
Generic.x86_64-devel-20210307221849-a76452d
Linux LibreELEC 5.10.21 #1 SMP Sun Mar 7 22:06:50 UTC 2021 x86_64 GNU/Linux
Starting Kodi (19.0 (19.0.0) Git:19.0-Matrix). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2021-03-06 by GCC 10.2.0 for Linux x86 64-bit version 5.10.20 (330260)
Running on LibreELEC (heitbaum): devel-20210307221849-a76452d 10.0, kernel: Linux x86 64-bit version 5.10.21
FFmpeg version/source: 4.3.1-Kodi
Host CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 8 cores available
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0037.2021.0106.1527 01/06/2021
CRenderSystemGL::InitRenderSystem - Version: 4.6 (Core Profile) Mesa 21.1.0-devel, Major: 4, Minor: 6
GL_RENDERER = Mesa Intel(R) Xe Graphics (TGL GT2)
GL_VERSION = 4.6 (Core Profile) Mesa 21.1.0-devel
```

build testing on remaining 5.10 targets now.

**Review by chewitt — APPROVED** [review]

**Pull request merged**
