### PR TITLE
buildsystem: add absolute patch dirs, remove unecessary sub-process, other cleanup

### PR DESCRIPTION
**Pull request by MilhouseVH**
Add support for absolute paths to `PKG_PATCH_DIRS`, simplifying #3635 

Stop using a sub-process around the call to `unpack()` as this creates undesirable non-standard behaviour - any variables modified within the function call are "lost" as a result of being modified in the sub-process.

Fix misconfigured packages, and remove files that no longer serve any purpose since the introduction of `PKG_DEPENDS_UNPACK`.

### CODE REVIEW

**Comment by vpeter4** [comment]
Try to build `chrome-libxcb` after you remove `sources/libxcb`. For me it doesn't work on master + this pr - sources are not downloaded. Or maybe I'm doing something wrong :)

**Comment by vpeter4** [comment]
Run this first (chrome-libxcb is build)
`./scripts/clean libxcb ; ./scripts/clean chrome-libxcb ; rm -fr sources/libxcb ; ./scripts/build chrome-libxcb`
then run this and chrome-libxcb is not build because sources are not downloaded
`./scripts/clean chrome-libxcb ; rm -fr sources/libxcb ; ./scripts/build chrome-libxcb`

**Comment by MilhouseVH** [comment]
Thanks, I'll investigate later this evening and fix.

**Comment by MilhouseVH** [comment]
I think the recursive unpack change I made earlier in the week may be responsible for this - I'm guessing that `chrome-libxcb` fails to unpack because `libxcb` is already unpacked so it (`libxcb`) doesn't download the missing tarball, causing `chrome-libxcb` to fail. Will confirm once I'm at the PC later.

**Comment by MilhouseVH** [comment]
I think if the call to `scripts/get` is restored to its original place in `scripts/unpack` (after the first `pkg_lock()`, before the `PKG_DEPENDS_UNPACK` processing) then it should work OK. Not tested...

**Comment by MilhouseVH** [comment]
@vpeter4 OK it was as I suspected - fix pushed.

**Pull request merged**
