### PR TITLE
image: add libidn2 to system image

### PR DESCRIPTION
**Pull request by antonlacon**
Libidn2 added as a virtual/libc depend, as glibc will use it when it's present in the system. Some addons require it, and it's also being automatically found by yet more addons. In order to have a consistent result form glibc, just have libidn2 installed into the image for everyone.

I don't do anything with internationalized domains, so this isn't checked beyond confirming it builds and the library is in the image.

Libidn2 2.1.1 reverts a soname version bump, so addons may need to be rebuilt to pick up on the change.

Systemd has a reference to libidn2 in the package.mk. This is for adding support to systemd-resolved, which LE doesn't use.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
systemd currently builds with libidn and libidn2 disabled, so in theory this could be enabled for systemd too (although we don't enable networkd so the benefit might be limited).

**Comment by antonlacon** [comment]
Added the dependency for systemd. Compile tested only as I don't think it will do anything without systemd-resolved.

**Comment by MilhouseVH** [comment]
Do we need `/usr/bin/idn2`?

It's not very big, only 80KB (RPi2) and 68KB (Generic) but if we only need the shared library then we should add:
```
post_makeinstall_target() {
  safe_remove ${INSTALL}/usr/bin
}
```

**Comment by antonlacon** [comment]
idn2 shouldn't be necessary. commit updated.

**Comment by MilhouseVH** [comment]
Added to 9.2 backport #3488

**Pull request merged**
