### PR TITLE
ConnMan: use UseGatewaysAsTimeservers option

### PR DESCRIPTION
**Pull request by chrisnovakovic**
I recently implemented runtime-configurable support for ConnMan's "use default gateway as timeserver" feature and had it accepted upstream (the salient commits are [`20f20417`](https://git.kernel.org/pub/scm/network/connman/connman.git/commit/?id=20f2041702f09b75ae96f0cb4853a52cc1ebf48c) and [`3ce40776`](https://git.kernel.org/pub/scm/network/connman/connman.git/patch/?id=3ce40776cf1e9cbb02279117298e2514aba42ffe)). The default is for this behaviour to be disabled, as it's only useful in a tiny number of (broken) network setups and is almost always the wrong thing to do everywhere else. This new feature obsoletes LibreELEC's custom patch `connman-04-do-not-add-default-gw-as-timeserver.patch`, which hard-codes the same behaviour at compile-time.

This PR cherry-picks the upstream commits implementing this feature, disables it by setting `UseGatewaysAsTimeservers=false` in `/etc/connman/main.conf` (not strictly necessary, but useful in case upstream decides to change the default behaviour someday), and drops `connman-04-do-not-add-default-gw-as-timeserver.patch` (as it's no longer necessary). When ConnMan 1.37 is released and we upgrade to it, `connman-00-upstream-main-Add-UseGatewaysAsTimeservers-option.patch` and `connman-00-upstream-timeserver-UseGatewaysAsTimeservers.patch` can also be dropped.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks @chrisnovakovic - I'll include this in test builds for the next few days just to be on the safe side, even though it doesn't look like it's going to cause any problems.

**Comment by MilhouseVH** [comment]
The `connman-00-upstream-main-Add-UseGatewaysAsTimeservers-option.patch` patch doesn't apply on connman-1.36:
```
  INSTALL    network (target)
      UNPACK   connman
          APPLY PATCH (common)   packages/network/connman/patches/connman-00-upstream-main-Add-UseGatewaysAsTimeservers-option.patch
patching file src/main.c
Hunk #1 FAILED at 82.
Hunk #2 FAILED at 102.
Hunk #3 FAILED at 123.
Hunk #4 FAILED at 144.
Hunk #5 succeeded at 431 with fuzz 1 (offset -10 lines).
Hunk #6 succeeded at 651 with fuzz 2 (offset -13 lines).
4 out of 6 hunks FAILED -- saving rejects to file src/main.c.rej
Makefile:9: recipe for target 'release' failed
```

**Comment by chrisnovakovic** [comment]
@MilhouseVH You're quite right, sorry - I didn't think there had been any significant changes to `main.c` between 1.35 and that commit. I'll revise and recommit.

**Comment by chrisnovakovic** [comment]
This one applies cleanly and compiles correctly.

**Comment by MilhouseVH** [comment]
Thanks, looks good now (builds fine on RPi/RPi2/Generic). I'll include for a few days in test builds, and if no problems we should be able to merge middle of next week.

**Comment by stefansaraev** [comment]
*lol*

sorry for the spam, but I could not resist :D

**Comment by chrisnovakovic** [comment]
Mistakes were made, let's leave it at that... 😉

**Comment by MilhouseVH** [comment]
No reported issues so far, I reckon this can go in. Thanks @chrisnovakovic !

**Comment by chewitt** [comment]
@chrisnovakovic I spotted this when working on some connman issues with one of their developers:

https://lists.01.org/pipermail/connman/2019-March/023277.html

**Comment by chrisnovakovic** [comment]
@chewitt Good spot, thanks! No idea how that happened...

**Pull request merged**
