### PR TITLE
Python cross-compile changes and qemu

### PR DESCRIPTION
**Pull request by heitbaum**
Address cross compile and pyvenv requirement of qemu.
Also cleans up some cross compile and setuptools within build system.

Build and Run Testing behaving well through all of qemu RCs cycles.
- build of simplejson .so and Pillow .so build as aarch64

fixes:
- #8009
- #5538

### CODE REVIEW

**Comment by vpeter4** [comment]
Looks like qemu checksum has been changed?

**Comment by vpeter4** [comment]
Please correct qemu PKG_SHA256 for easier testing.

**Comment by heitbaum** [comment]
> Please correct qemu PKG_SHA256 for easier testing.

strange I’m getting the same sha as the .mk file.
```
 s/get qemu
GET      qemu (archive)
--2023-08-01 14:43:44--  https://download.qemu.org/qemu-8.1.0-rc1.tar.xz
Resolving download.qemu.org (download.qemu.org)... 143.244.62.6, 2a02:6ea0:db00::1
Connecting to download.qemu.org (download.qemu.org)|143.244.62.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 123569692 (118M) [application/octet-stream]
Saving to: '/var/media/DATA/home-rudi/LibreELEC.tv/sources/qemu/qemu-8.1.0-rc1.tar.xz'

/var/media/DATA/home-rudi/LibreE 100%[==========================================================>] 117.84M  30.4MB/s    in 3.9s    

2023-08-01 14:43:48 (30.0 MB/s) - '/var/media/DATA/home-rudi/LibreELEC.tv/sources/qemu/qemu-8.1.0-rc1.tar.xz' saved [123569692/123569692]

    INFO      Calculated checksum: 98b032d46d23075a3011222b3642ccb9c327222bd4c67c33945fb9304a1e3f08
    ```

**Comment by vpeter4** [comment]
Strange, I get d2fedcf962eac9b79e0de9e8e01ba7f63095c387c70d9c5364b2cccc93261c2d.
Same with online tool https://www.conversion-tool.com/sha256/

**Comment by heitbaum** [comment]
Hopefully just a glitch with the rc’s

**Comment by vpeter4** [comment]
I think reason is this: https://gitlab.com/qemu-project/qemu/-/issues/1791

**Comment by heitbaum** [comment]
> I think reason is this: https://gitlab.com/qemu-project/qemu/-/issues/1791 File with d2fedcf962eac9b79e0de9e8e01ba7f63095c387c70d9c5364b2cccc93261c2d looks newer at least when compare the content and file timestamps.

Added rc2. Hopefully same sha256 on all cdn

**Comment by heitbaum** [comment]
Updated to now released qemu 8.1.0. I have been building and running with this for the last month. This pr addresses not just qemu, but aligns host build to Python3 pyc approach. And continues to allow for “only pyc” in target,

**Review by CvH — APPROVED** [review]

**Pull request merged**
