### PR TITLE
linux: update to linux-4.10.4

### PR DESCRIPTION
**Pull request by MilhouseVH**
4.10.3 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.10.3
4.10.4 changelog: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.10.4

`linux-063-fix-rc-raw-decoder-loading.patch` is now upstream in 4.10.4.

Cosmetic change to RPi/RPi2 options resulting from `make oldconfig`.

Not yet build/run tested - hold off merging until at least Sunday.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
No complaints so far.

Added "Merge Me". :)

**Comment by polojoe** [comment]
There are still unresolved dvb issues since kernel 4.9
https://forum.libreelec.tv/thread-4235-post-30556.html#pid30556

**Comment by CvH** [comment]
@polojoe
that is partly a problem of the current linux version that breaks random adaptors - that is not much we can do as long there is no fix upstream or a clear bug (commit) that can be reverted, we guess some usb related change that breaks currently some adapters.

**Comment by polojoe** [comment]
Is there already a filed bug upstream where we could help identifiying the issue?

**Comment by CvH** [comment]
@polojoe not yet as far as i know, I also have none of the affected hardware so I can't test it myself.

**Comment by polojoe** [comment]
How could I help?

**Comment by CvH** [comment]
@polojoe bisect the commit that breaks it
afaik the problem is somewhere between https://github.com/torvalds/linux/commit/6b5e09a748ad0a0b198d0e268c7e689044bfe48a and https://github.com/torvalds/linux/commit/2937f375751922ffce9ef1d5fa84491840b0c8e0 - it is extremly time consuming doing a bisect remotly. The problem should exist at ubuntu too, so i makes maybe sense to build the kernel there.

**Comment by polojoe** [comment]
Unfortunately thats over my knowledge. I even don't have build environment.

**Pull request merged**
