### PR TITLE
u-boot: update to 2023.10

### PR DESCRIPTION
**Pull request by heitbaum**
[ANN] U-Boot v2023.01 released
- https://www.mail-archive.com/u-boot@lists.denx.de/msg460294.html

[ANN] U-Boot v2023.04 released
- https://www.mail-archive.com/u-boot@lists.denx.de/msg470414.html

[ANN] U-Boot v2023.07 released
- https://lists.denx.de/pipermail/u-boot/2023-July/522217.html

[ANN] U-Boot v2023.10 released
- https://lists.denx.de/pipermail/u-boot/2023-October/532381.html

Releases
- U-Boot v2023.01 was released on Mon 9 January 2023.
- U-Boot v2023.04 was released on Mon 3 April 2023.
- U-Boot v2023.07 was released on Mon 10 July 2023.
- U-Boot v2023.10 was released on Mon 2 October 2023.

Update u-boot (for all)

- u-boot-tools: use u-boot download and version
- u-boot: update to 2023.01
  - rebase Rockchip patch
  - drop upstreamed amlogic patches
  - Rename CONFIG_SYS_TEXT_BASE to CONFIG_TEXT_BASE
  - Rename CONFIG_DM_VIDEO to CONFIG_VIDEO
- u-boot: update to 2023.04
  - rebase Allwinner patches
  - Add pyelftools
  - Drop upstream rockchip patches
  - Rebase rockchip patches
- u-boot: update to 2023.10
  - rebase Allwinner patches
  - rebase Rockchip patch
  - Drop upstream Allwinner patch
  - Drop upstream Amlogic patches

### Fixed

- Rockchip rock-pi-4 and rock-pi-4-plus both fail with
  - HOSTCC  tools/mkeficapsule
  - tools/mkeficapsule.c:21:10: fatal error: gnutls/gnutls.h: No such file or directory
  - 21 | #include <gnutls/gnutls.h>
  - |          ^~~~~~~~~~~~~~~~~
  - compilation terminated.
- Dragonboard build error with compiler flags
  - since #6871
  - With 2023.10 it is building correctly
- Amlogic ffmpeg build failing
- iMX8 kernel build failing due to hdmi-dp changes
- https://github.com/LibreELEC/LibreELEC.tv/blob/b8279928ad0b9ebea5a7fa7014d1c9c59da6567a/projects/Rockchip/bootloader/install#L24
- Rockchip - Wrote map file './simple-bin.map' to show errors
binman: Node '/binman/simple-bin/fit': subnode 'images/@atf-SEQ': Failed to read ELF file: Python: No module named 'elftools'
- Dragonboard build error occurs between 2022.07 and 2022.10-rc1 - still need to investigate.
- update binman Allwinner patch 

### Issues
-

### Build tested - 6.6-rc6 + u-boot 2023.10
```
PROJECT=Allwinner ARCH=aarch64 DEVICE=A64 make image
PROJECT=Allwinner ARCH=arm DEVICE=H3 make image
PROJECT=Allwinner ARCH=aarch64 DEVICE=H5 make image
PROJECT=Allwinner ARCH=aarch64 DEVICE=H6 make image
PROJECT=Allwinner ARCH=arm DEVICE=R40 make image
PROJECT=Amlogic ARCH=aarch64 DEVICE=AMLGX make image
PROJECT=NXP ARCH=arm DEVICE=iMX6 make image
PROJECT=NXP ARCH=aarch64 DEVICE=iMX8 make image
PROJECT=Qualcomm ARCH=aarch64 DEVICE=Dragonboard make image
PROJECT=Samsung ARCH=arm DEVICE=Exynos make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3288 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3328 make image
PROJECT=Rockchip ARCH=arm DEVICE=RK3399 make image
```

### Run testing - 6.6-rc6 + u-boot 2023.10
- Allwinner all - tested - with H616 - jernejsk
- Allwinner H6 (Tanix TX6) - TBA - heitbaum
- Amlogic all - tested - 2023.10 - chewitt
- NXP iMX6 (Cubox-i4Pro) - TBA  - heitbaum
- Samsung Exynos (Hardkernel ODROID XU4) - TBA - heitbaum

### Images built @ Oct 22 2023
```
$ ls -1 target/*.img.gz

target/LibreELEC-A64.aarch64-12.0-devel-20231021123702-d93b153-orangepi-win.img.gz
target/LibreELEC-A64.aarch64-12.0-devel-20231021123702-d93b153-pine64.img.gz
target/LibreELEC-A64.aarch64-12.0-devel-20231021123702-d93b153-pine64-lts.img.gz
target/LibreELEC-A64.aarch64-12.0-devel-20231021123702-d93b153-pine64-plus.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-bananapi-m2-pro.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-bananapi-m2s.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-bananapi-m5.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-box.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-khadas-vim2.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-khadas-vim3.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-khadas-vim3l.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-khadas-vim.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-lafrite.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-lepotato.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-nanopi-k2.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-odroid-c2.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-odroid-c4.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-odroid-hc4.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-odroid-n2.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-radxa-zero2.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-radxa-zero.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-wetek-core2.img.gz
target/LibreELEC-AMLGX.aarch64-12.0-devel-20231021124641-d93b153-wetek-play2.img.gz
target/LibreELEC-Dragonboard.aarch64-12.0-devel-20231021125922-d93b153-410c.img.gz
target/LibreELEC-Exynos.arm-12.0-devel-20231021130238-d93b153-odroid-xu3.img.gz
target/LibreELEC-Exynos.arm-12.0-devel-20231021130238-d93b153-odroid-xu4.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021113946-d93b153-bananapi-m2p.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021113946-d93b153-beelink-x2.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021113946-d93b153-libretech-h3.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021113946-d93b153-nanopi-m1.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021113946-d93b153-orangepi-2.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021113946-d93b153-orangepi-pc.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021113946-d93b153-orangepi-pc-plus.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021113946-d93b153-orangepi-plus2e.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021113946-d93b153-orangepi-plus.img.gz
target/LibreELEC-H5.aarch64-12.0-devel-20231021123423-d93b153-orangepi-pc2.img.gz
target/LibreELEC-H5.aarch64-12.0-devel-20231021123423-d93b153-tritium-h5.img.gz
target/LibreELEC-H5.aarch64-12.0-devel-20231021123555-d93b153-orangepi-pc2.img.gz
target/LibreELEC-H5.aarch64-12.0-devel-20231021123555-d93b153-tritium-h5.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021124026-d93b153-beelink-gs1.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021124026-d93b153-orangepi-3.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021124026-d93b153-orangepi-3-lts.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021124026-d93b153-orangepi-lite2.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021124026-d93b153-orangepi-one-plus.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021124026-d93b153-pine-h64.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021124026-d93b153-pine-h64-model-b.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021124026-d93b153-tanix-tx6.img.gz
target/LibreELEC-iMX6.arm-12.0-devel-20231021125252-d93b153-cubox.img.gz
target/LibreELEC-iMX6.arm-12.0-devel-20231021125252-d93b153-udoo.img.gz
target/LibreELEC-iMX6.arm-12.0-devel-20231021125252-d93b153-wandboard.img.gz
target/LibreELEC-iMX8.aarch64-12.0-devel-20231021125628-d93b153-mq-evk.img.gz
target/LibreELEC-iMX8.aarch64-12.0-devel-20231021125628-d93b153-pico-mq.img.gz
target/LibreELEC-R40.arm-12.0-devel-20231021124140-d93b153-bananapi-m2u.img.gz
target/LibreELEC-RK3288.arm-12.0-devel-20231021130645-d93b153-miqi.img.gz
target/LibreELEC-RK3288.arm-12.0-devel-20231021130645-d93b153-tinker.img.gz
target/LibreELEC-RK3328.arm-12.0-devel-20231021134957-10121dd-a1.img.gz
target/LibreELEC-RK3328.arm-12.0-devel-20231021134957-10121dd-roc-cc.img.gz
target/LibreELEC-RK3328.arm-12.0-devel-20231021134957-10121dd-rock64.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-hugsun-x99.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-khadas-edge.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-nanopc-t4.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-nanopi-m4.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-orangepi.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-rock960.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-rock-pi-4.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-rock-pi-4-plus.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-rock-pi-n10.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-rockpro64.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-roc-pc.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-roc-pc-plus.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021135000-10121dd-sapphire.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-hugsun-x99.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-khadas-edge.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-nanopc-t4.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-nanopi-m4.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-orangepi.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-rock960.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-rock-pi-4.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-rock-pi-4-plus.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-rock-pi-n10.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-rockpro64.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-roc-pc.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-roc-pc-plus.img.gz
target/LibreELEC-RK3399.arm-12.0-devel-20231021203203-10121dd-sapphire.img.gz
```

```
=== tested on ===

```

### CODE REVIEW

**Comment by knaerzche** [comment]
> Rockchip rock-pi-4 and rock-pi-4-plus both fail with
> HOSTCC tools/mkeficapsule
> tools/mkeficapsule.c:21:10: fatal error: gnutls/gnutls.h: No such file or directory
> 21 | #include <gnutls/gnutls.h>
> | ^~~~~~~~~~~~~~~~~
> compilation terminated.

Since don't use / want uefi support, adding 

`# CONFIG_TOOLS_MKEFICAPSULE is not set`

to `projects/Rockchip/bootloader/config` should fix it.

**Comment by heitbaum** [comment]
> > Rockchip rock-pi-4 and rock-pi-4-plus both fail with
> > HOSTCC tools/mkeficapsule
> > tools/mkeficapsule.c:21:10: fatal error: gnutls/gnutls.h: No such file or directory
> > 21 | #include <gnutls/gnutls.h>
> > | ^~~~~~~~~~~~~~~~~
> > compilation terminated.
> 
> Since don't use / want uefi support, adding
> 
> `# CONFIG_TOOLS_MKEFICAPSULE is not set`
> 
> to `projects/Rockchip/bootloader/config` should fix it.

Thank you. Added the commit.

**Comment by heitbaum** [comment]
@knaerzche - any guidance on what this needs to be updated with:
https://github.com/LibreELEC/LibreELEC.tv/blob/b8279928ad0b9ebea5a7fa7014d1c9c59da6567a/projects/Rockchip/bootloader/install#L24

**Comment by knaerzche** [comment]
> @knaerzche - any guidance on what this needs to be updated with:
> 
> https://github.com/LibreELEC/LibreELEC.tv/blob/b8279928ad0b9ebea5a7fa7014d1c9c59da6567a/projects/Rockchip/bootloader/install#L24

These have been replaced in u-boot-2023-01 - as you wrote, so this should get

`PKG_LOAD_ADDR=$(sed -n "/CONFIG_TEXT_BASE/s/#define CONFIG_TEXT_BASE //p"`

pls remember also https://github.com/LibreELEC/LibreELEC.tv/pull/7365#issuecomment-1397678285

**Comment by antonlacon** [comment]
> Rockchip - Wrote map file './simple-bin.map' to show errors
> binman: Node '/binman/simple-bin/fit': subnode 'images/@atf-SEQ': Failed to read ELF file: Python: No module named 'elftools'

First commit of https://github.com/antonlacon/LibreELEC.tv/commits/pyelftools should add pyelftools resolving that. Last two commits add pyelftools:host to uboot depends, and drops what I believe are upstreamed rockchip patches, respectively.

Built test Rockchip/RK3399/arm make image. No hardware to run test.

**Comment by Kwiboo** [comment]
My PR https://github.com/heitbaum/LibreELEC.tv/pull/26 to this PR should fix Rockchip issues, please pick my or @antonlacon commits

**Comment by CvH** [comment]
@heitbaum pls pick https://github.com/antonlacon/LibreELEC.tv/commit/d9cdf3be2a438dd27699b38b6c0deff774d636b6
that includes the licence stuff and has the LE licence header correct

**Comment by jernejsk** [comment]
Please reinstate patch for AW, this is new version: http://ix.io/4JAV

**Comment by heitbaum** [comment]
> Please reinstate patch for AW, this is new version: http://ix.io/4JAV

Done, and reran the Allwinner build test.

```
$ ls -1 target/*.img.gz
target/LibreELEC-A64.aarch64-12.0-devel-20231021211139-e3f5873-orangepi-win.img.gz
target/LibreELEC-A64.aarch64-12.0-devel-20231021211139-e3f5873-pine64.img.gz
target/LibreELEC-A64.aarch64-12.0-devel-20231021211139-e3f5873-pine64-lts.img.gz
target/LibreELEC-A64.aarch64-12.0-devel-20231021211139-e3f5873-pine64-plus.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021211458-e3f5873-bananapi-m2p.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021211458-e3f5873-beelink-x2.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021211458-e3f5873-libretech-h3.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021211458-e3f5873-nanopi-m1.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021211458-e3f5873-orangepi-2.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021211458-e3f5873-orangepi-pc.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021211458-e3f5873-orangepi-pc-plus.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021211458-e3f5873-orangepi-plus2e.img.gz
target/LibreELEC-H3.arm-12.0-devel-20231021211458-e3f5873-orangepi-plus.img.gz
target/LibreELEC-H5.aarch64-12.0-devel-20231021211405-e3f5873-orangepi-pc2.img.gz
target/LibreELEC-H5.aarch64-12.0-devel-20231021211405-e3f5873-tritium-h5.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021211419-e3f5873-beelink-gs1.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021211419-e3f5873-orangepi-3.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021211419-e3f5873-orangepi-3-lts.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021211419-e3f5873-orangepi-lite2.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021211419-e3f5873-orangepi-one-plus.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021211419-e3f5873-pine-h64.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021211419-e3f5873-pine-h64-model-b.img.gz
target/LibreELEC-H6.aarch64-12.0-devel-20231021211419-e3f5873-tanix-tx6.img.gz
target/LibreELEC-R40.arm-12.0-devel-20231021211517-e3f5873-bananapi-m2u.img.gz
```

I have cleaned up the commit comments and reordered them logically. So setting the PR as ready for review. I’ll leave it Merge Blocked till testing results come in.

**Comment by jernejsk** [comment]
I tested this on H616, when working on new SoC support, and looks good.

**Review by jernejsk — APPROVED** [review]

**Pull request merged**
