### PR TITLE
x11vnc: initial addon

### PR DESCRIPTION
**Pull request by awiouy**
This builds, but I have no system to test it

### CODE REVIEW

**Comment by CvH** [comment]
just for reference, works most likely at Nvidia and AMD - Intel is hitting this bug (driver bug)
https://bugs.freedesktop.org/show_bug.cgi?id=94483

**Comment by awiouy** [comment]
Could anyone please test whether this does not flicker/tear on LE8 with AMD/Nvidia or LE7?

**Comment by chewitt** [comment]
The addon @CvH built/shared via Slack the other day works fine on my main box which has an nvidia GT520 GPU. I can't test AMD/Intel.

**Comment by CvH** [comment]
Same for LE7/8

**Comment by chewitt** [comment]
closing as superseded with TigerVNC #801

**Comment by awiouy** [comment]
Moved here: https://github.com/awiouy/LibreELEC.tv/commit/5db3321d25ce56b14ed99b060a43a248274d59b0

**Pull request closed without merging**
