### PR TITLE
nvidia: update to xf86-video-nvidia 378.13

### PR DESCRIPTION
**Pull request by vitorp07**
http://www.geforce.com/drivers/results/115031
"Fixed a bug that caused system hangs when resuming from suspend with some GPUs"

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Isn't this the same bug fixed in 375.39? I also think we want to continue with the LTS branch.

Also PR title isn't very informative, please use "<package-name>: update to <package-name>-<package-version>"

**Comment by vitorp07** [comment]
Sorry about the title,
Some users are still experiencing this bug after updating to 375.39, not sure if the same fixes were applied to 378.13.

**Comment by chewitt** [comment]
@vitorp07 we need to see positive reports that this resolves the suspend issue before we bump the driver in a release branch. The same change should also be PR'd to master branch.

**Comment by MilhouseVH** [comment]
I'm not really in favour of switching from the long lived branch (375.x) to the short lived branch (currently 378.x).

[NVIDIA Has A New "Long-Lived" Linux Driver](https://www.phoronix.com/scan.php?page=news_item&px=OTkxOA)

>This is a new category of releases, so I think it needs a little explanation. We've started maintaining longer-lived release branches that only take critical or low-risk fixes. These releases are intended for users of non-legacy GPUs who don't necessarily need the latest and greatest features. If you've ever used Ubuntu's LTS releases, these should be a similar idea.

The long lived and short lived branches have both received the same suspend fixes, so there seems little reason to believe switching to the short lived branch will resolve any suspend issues currently seen with the long lived branch. And even if it does, since it's essentially a "beta" branch (for new features) there's an increased likelihood of other problems appearing that may impact an even greater number of users.

Users that continue to experience resume-from-suspend issues with 375.39 should try switching to the legacy driver as detailed [here](http://forum.kodi.tv/showthread.php?tid=269815&pid=2379108#pid2379108), since this seems to resolve most issues reported so far.

Switching Nvidia driver branches is not a decision to be taken lightly (and definitely not in a release branch), but also not something we should really be doing in order to fix a single problem seen by a relatively small number of users (particularly when a potential workaround exists).

@chewitt I'd suggest closing this, at the very least because it's a major bump in a release branch.

@vitorp07 try the legacy driver workaround if you're experiencing resume issues yourself.

**Comment by chewitt** [comment]
If we get positive reports with the short-lived driver I can take up the conversation with nvidia contacts to see when the same fixes will appear in the long-lived driver.

**Comment by MilhouseVH** [comment]
In that case I think we can probably do some internal testing with 378.13 (I believe klojum may have the relevant hardware), but I'd still advise against a major bump in a release branch regardless of the outcome...

I imagine 378.13 probably has a better chance of building against 4.9.x than 4.10.x, ie. a libreelec-8.0 build rather than master (we're still waiting for Nvidia to release 4.10.x compatible drivers). I can look into it creating a build later in the afternoon unless you're able to knock something up before then.

**Comment by vitorp07** [comment]
I never experienced these issues myself, also testing Lubuntu 17,04Beta with Nvidia drivers 378.13 installed, i am not seeing any problem in that regard.

If you do create a build, i can test it with a GTX 1070 also a GTX 750ti and report back.

**Comment by MilhouseVH** [comment]
> If you do create a build, i can test it with a GTX 1070 also a GTX 750ti and report back.

Please test this build of 8.0.1: http://milhouse.libreelec.tv/builds/testing/Generic/LibreELEC-Generic.x86_64-8.0.1-20170305144946.tar - it contains 378.13 instead of 375.39

**Comment by vitorp07** [comment]
@MilhouseVH  Thank you, testing your build right now.

**Comment by vitorp07** [comment]
Installed on a USB drive, the only difference i can see until now is the "gputemp" you mentionned,
everything else is behaving pretty much like drivers v375.39.

Here are the logs right after resuming from suspend;
[log-2017-03-06-22.21.23.zip](https://github.com/LibreELEC/LibreELEC.tv/files/822725/log-2017-03-06-22.21.23.zip)

and more logs after playing video test files(1080p & 2160p @60fps and 2160p @24fps-10Bit);
[log-2017-03-06-22.30.29.zip](https://github.com/LibreELEC/LibreELEC.tv/files/822743/log-2017-03-06-22.30.29.zip)

**Comment by MilhouseVH** [comment]
The thing is, if you didn't have the resume-from-suspend problem with 375.39 (or don't know if you do, because you haven't tested it) then just because you don't have the resume-from-suspend problem with 378.13 doesn't actually mean it's fixed in 378.13 - it just means you don't have this particular issue with your hardware.

Internal testing suggests the resume-from-suspend issue is more likely to affect older cards (eg. GT520) than it will newer cards (such as a GTX 950, or your 1070. Your GTX 750ti is more likely to be borderline and could go either way, so that's worth testing with 375.39 and 378.13.

With 378.13, a GT520 still has the same resume-from-suspend problem as it does with 375.39, in which case that particular bug has not been fixed.

I suspect that Nvidia have addressed other suspend bugs that were present in both drivers, but haven't yet addressed the suspend bug we see with older hardware and the 375.x driver (which is fixed by forcing the legacy driver).

**Comment by vitorp07** [comment]
Got it, will now test 375.39 and 378.13 using the GTX 750ti with an older computer.

**Comment by vitorp07** [comment]
I can confirm what @MilhouseVH said in the post above, here is what i got so far(everything tested using the same USB drive);

-GTX 1070 + i5 4690s + H97N-wifi
LE 8.0 drivers v375.39= no problem resuming from suspend
LE test build drivers v378.13= no problem resuming from suspend

-GTX 750ti + i7 920 + P6TD Deluxe
LE 8.0 drivers v375.39= crashed when trying to enter suspend mode
LE test build drivers v378.13= crashed when trying to enter suspend mode

**Pull request closed without merging**
