### PR TITLE
Generic: switch to GBM and create X11 and Generic device

### PR DESCRIPTION
**Pull request by CvH**
follow up PR of https://github.com/LibreELEC/LibreELEC.tv/pull/5591

- creates a Generic device (that defaults to gbm) and a X11 device (maybe name it legacy instead of X11?)
- added needed changes from pr #5591 
- no HDR patches included
- DRMPRIME (that allows HDR) is still missing basic stuff

I just rushed the PR - this is currently untested (based on a similar pr a year ago that worked well at that time).

### CODE REVIEW

**Comment by heitbaum** [comment]
For commit b444b24f5a3d0c5356c07eaaf0979815084b901f - is "util-macros" required for X11? Or is this just a nice to have in X11? 

I have run 736a03c56621ca6ff44fc406e352040cb5a810e0 and 5b0af763515b45a0699297f7e632ec86638bb99f for the last 2 days on NUC11 TGL 5.14 - all ok so far. 
I have just added a3ea55587acbc4d21db2973e84a590ede93576d1 and 5976012d38c5187ceefcd33d18b2ae0b87ccd4a2 to my dev tree and will do some clean builds and tests

**Comment by smp79** [comment]
I'm not sure https://github.com/LibreELEC/LibreELEC.tv/pull/5601/commits/b444b24f5a3d0c5356c07eaaf0979815084b901f is needed here since we are keeping all the X11 packages.

**Comment by CvH** [comment]
> I'm not sure b444b24 is needed
I think it is needed as soon we drop X11 so I guess better keep it (won't hurt atm)?

Filename of the resulting Files:
X11 : `LibreELEC-X11.x86_64-11.0-devel-20210904200948-2879ba5.tar`
GBM: `LibreELEC-Generic.x86_64-11.0-devel-20210903231904-736a03c`

X11 is really not optimal, so I guess I go with renaming it to Generic-legacy ?

**Comment by smp79** [comment]
> so I guess better keep it (won't hurt atm)?

Sure.

> so I guess I go with renaming it to Generic-legacy ?

No complaints here.

**Comment by CvH** [comment]
renamed X11 to "Generic-legacy"

**Comment by smp79** [comment]
The fix from https://github.com/LibreELEC/LibreELEC.tv/pull/5601/commits/a5c0a1d0875f160de96ac8fa32246909568a7a32 is now merged into [media-driver 21.3.3](https://github.com/intel/media-driver/compare/intel-media-21.3.2...intel-media-21.3.3)

**Comment by CvH** [comment]
removed the media-driver patch

**Comment by CvH** [comment]
while testing I recognized that drmprime is set default, as long it is not basic feature complete we should default to "just" gbm. Anyone and idea how to achieve this without disabling DRMPrime completely !?

**Comment by lrusak** [comment]
> while testing I recognized that DRMPrime is set default, as long it is not basic feature complete we should default to "just" gbm. Anyone and idea how to achieve this without disabling DRMPrime completely !?

Use the appliance.xml

**Comment by SupervisedThinking** [comment]
BTW: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/3197?commit_id=7f3ffce27ed3f83842f08ed5f9d27277ef2462f5#note_1044211

Looks like future versions of Nvidia/Mesa 3D will most likely support GBM too - so LE could just make it's move to Wayland/Sway then and ditch X11

**Comment by zhangn1985** [comment]
need to enable "VIDEO_KMSDRM"  to enable egl/gles2 display for SDL2

**Comment by SupervisedThinking** [comment]
@zhangn1985 this works reliable for my builds (AML, Generic, RK & RPi)
https://github.com/SupervisedThinking/LibreELEC-RR/blob/libreelec-10.0-RR/packages/supervisedthinking/multimedia/SDL/sdl2/package.mk#L122-L129

**Comment by CvH** [comment]
added `kodi: add appliance.xml for gbm at generic`, this defaults to gbm instead to drmprime, crossgrade works and so far no problems
testbuilds https://cvh.libreelec.tv/test/gbm/

@zhangn1985 @SupervisedThinking we can fix SDL in a follow up pr, SDL is not used at LE so I can't test.

**Review by heitbaum — APPROVED** [review]
Confirmed running and tested both Generic and Generic-legacy (and swapping between them.)

**Pull request merged**
