### PR TITLE
glib: bump to 2.67.0

### PR DESCRIPTION
**Pull request by Portisch**

### CODE REVIEW

**Comment by heitbaum** [comment]
Hi @Portisch - was watching to see when 2.67.1 would be announced. It has been tagged for 8 days.
https://github.com/GNOME/glib/commit/55b4a25eaf0069f84219b685a3fc10db922f7414

**Comment by CvH** [comment]
2.67.1 is released https://gitlab.gnome.org/GNOME/glib/-/releases/2.67.1

**Review by heitbaum — CHANGES_REQUESTED** [review]
PKG_VERSION="2.67.1"
PKG_SHA256="3b3409fe3a93f9e9f6f5dc9cd8405edfd7513b289589987e568369e627d3350c"

**Comment by Portisch** [comment]
Feel free to close the PR and bump to the newer version

**Comment by CvH** [comment]
superseded by https://github.com/LibreELEC/LibreELEC.tv/pull/4766

**Pull request closed without merging**
