### PR TITLE
Add media-backports package

### PR DESCRIPTION
**Pull request by kszaq**
This PR adds media-backports package to provide support for DVB tuners and other media devices for older kernels.

For now 2 tuners have been confirmed to work with 3.14 kernel: Geniatech T230 and DVBSky S960.

I think it's better to make the package opt-in (project has to add it in `options`) rather than have a project-specific definition in `package.mk` - but I'm open to suggestions.

Please keep this PR open for now as it needs to be tested with WeTek Play's built-in tuners - I'll be able to test it in a few days.

### CODE REVIEW

**Comment by kszaq** [comment]
Whoops, this needs a fix for WeTek to compile properly. I was compiling with my forked kernel, it does not build with stock. I'll update the PR when I have it ready, please don't merge.

**Comment by kszaq** [comment]
PR update, builds available at: http://kszaq.libreelec.tv/pr539/

I'll test on my WeTek Play soon. 

Ping @codesnake - you may want to have a look.

**Comment by CvH** [comment]
@kszaq did you tried it with Media_build if it's work with that patches?

**Comment by kszaq** [comment]
I'm not sure how to patch media_build with these patches. What is better about media_build?

**Comment by CvH** [comment]
@kszaq if you not tried it I can also try it locally, media_build takes the latest media_tree (only dvb) from the latest kernel

**Comment by lrusak** [comment]
any updates here?

**Comment by drieschel** [comment]
@kszaq started his vacation today, so there will be updates in two weeks earliest.

**Comment by kszaq** [comment]
A small update:
- WeTek Play internal DVB-S tuner works with this PR. I haven't tested DVB-T but it should also work since it's the very same kernel module
- this PR breaks RTL2838U tuner support which is AFAIK a fairly popular one. It errors out with `rtl2832: probe of 0-0010 failed with error -22`. The only similar issue I could find was with RPi kernel in OSMC some time ago but I can't see what the solution was: https://discourse.osmc.tv/t/dvb-t-dongle-not-working-after-2015-08-03-update/6683

It would be great if someone can point me to what fixed the issue on RPi so I can port the fix and get this PR fully working.

**Comment by kszaq** [comment]
It seems like rtl2832 driver needs a kernel-side fix, "something" that was added between 3.18 and 4.1.

OSMC's fix was upgrading kernel to 4.3 and that fix is already included in media-backports.

**Comment by ozkaradag** [comment]
Hello my friend,

I have the TBS 5980 and TBS 5990 USB-TV tuners.
http://www.tbsdtv.com/products/tbs5980-dvb-s2-ci-tv-tuner-usb.html
http://www.tbsdtv.com/products/tbs5990-dvb-s2-ci-tv-tuner-usb.html

I want to use them to connect to the WeTek Play via TVH, what would help if you need to test, etc. etc.

I will appreciate it if you would, too.

Thank you in advance.

Respects...

**Comment by lrusak** [comment]
Any updates here @kszaq ???

**Comment by kszaq** [comment]
Yes, unfortunately tuners using I2C are broken with 3.10 kernel.

**Comment by ozkaradag** [comment]
Ok, i'm sadly.

For Kernel 3.14?

Play 2 uses kernel 3.14.

**Comment by lrusak** [comment]
@kszaq can we just disable this for the wetek play then?

**Comment by kszaq** [comment]
I don't have information on how these work with 3.14 kernel. Other than that, I have adopted media_build from @CvH as it seems to be more up-to-date than media_backports.

**Comment by CvH** [comment]
if media build works you got at least the latest DVB drivers (this alone is a major win), if you wanne have the most possible (driver wise) at the current date you need https://github.com/tbsdtv/linux_media (that builds with media build + other url for download) - I stuck at some random error that I can't fix maybe you got more luck :) [didn't put too much effort into this](https://github.com/CvH/LibreELEC.tv/commit/7edf0c8c535695205bf916a89c329396b7dc50c5)
Btw media_build never works for me for the WC (iirc) - did you patched something that I cant find at your git ?

**Comment by kszaq** [comment]
Media_build patch for Amlogic 3.10: https://github.com/kszaq/LibreELEC.tv/blob/libreelec-7.0/projects/S805/patches/media_build/media_build-fix.patch

**Comment by ozkaradag** [comment]
Any updates here @kszaq and @CvH?

**Comment by kszaq** [comment]
PR is closed, I no longer work on it.

**Pull request closed without merging**
