### PR TITLE
Kodi bump to 20.0 branch

### PR DESCRIPTION
**Pull request by CvH**
builds
- rebased patches
- blindly adjusted the minimize patch (no idea how to test)
- ffmpeg updated

### CODE REVIEW

**Comment by jernejsk** [comment]
I updated request api patches and put them in v4l2-request-hwaccel-4.4 branch. However, there are 2 issues:
1. v4l2 stateful patches don't build (I just disabled them for now)
2. deinterlacing filter doesn't work (completely breaks any kind of video playback).

Point 2 can be connected to point 1, so I'll test again once you update and fix all patches.

**Comment by CvH** [comment]
updated all patches and added AW di patchset

**Comment by jernejsk** [comment]
Please also copy  projects/Allwinner/patches/kodi/0002-WIP-DRMPRIME-deinterlace-filter.patch to projects/Rockchip/patches/kodi

**Comment by CvH** [comment]
@jernejsk done

**Comment by CvH** [comment]
@HiassofT the update bump script is not working (or I am holding it wrong)
```
cvh@ubuntu:~/LE/tools/mkpkg$ ./update_binary-addons master
[mkpkg] Checking out https://github.com/xbmc/xbmc ...
[mkpkg] Checking out https://github.com/xbmc/repo-binary-addons.git ...
[mkpkg] Skipped screensaver.cpblobs
[mkpkg] Skipped screensavers.rsxs

The following addons were skipped, please add packages for these addons:
[ screensaver.cpblobs screensavers.rsxs]

SKIPPING excluded package vfs.sacd
```

**Comment by heitbaum** [comment]
> @HiassofT the add-on update script is not working (or I am holding it wrong)
> 
> ```
> cvh@ubuntu:~/LE/tools/mkpkg$ ./update_binary-addons master
> [mkpkg] Checking out https://github.com/xbmc/xbmc ...
> [mkpkg] Checking out https://github.com/xbmc/repo-binary-addons.git ...
> [mkpkg] Skipped screensaver.cpblobs
> [mkpkg] Skipped screensavers.rsxs
> 
> The following addons were skipped, please add packages for these addons:
> [ screensaver.cpblobs screensavers.rsxs]
> 
> SKIPPING excluded package vfs.sacd
> ```

nexus is the trick…

here is my script that uses the above and then creates the commit.

```
$ more zz-push-binaries 
#ls -1 ../LibreELEC.binaries/ | grep git$ | while read x
#do
#  ln -s ../LibreELEC.binaries/$x .
#done

tools/mkpkg/update_binary-addons Matrix | tee yy-output
echo "kodi-binary-addons: update to latest versions" > yy-output.updated
echo >> yy-output.updated
cat yy-output | grep "^UPDATED " | sed 's/^UPDATED /- /' | sed 's/ from /: update /' >> yy-output.updated
git commit -eF yy-output.updated .
```

**Comment by HiassofT** [comment]
A quick test with this PR plus a local bump to latest rpi ffmpeg patch looks fine here on RPi4

**Comment by heitbaum** [comment]
```
=== tested on ===
Generic.x86_64-devel-20210924181214-e2cef15
Linux nuc11 5.15.0-rc2 #1 SMP Fri Sep 24 18:39:10 AEST 2021 x86_64 GNU/Linux
Starting Kodi (20.0-ALPHA1 (19.90.101) Git:71500af1106bd0561fcdb7c97fe825b3169e4ab7). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2021-09-24 by GCC 10.3.0 for Linux x86 64-bit version 5.15.0 (331520)
Running on LibreELEC (heitbaum): devel-20210924181214-e2cef15 11.0, kernel: Linux x86 64-bit version 5.15.0-rc2
FFmpeg version/source: 4.4-Kodi
Host CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 8 cores available
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0041.2021.0811.1505 08/11/2021
RetroPlayer[PROCESS]: Registering process control for GBM
CApplication::CreateGUI - using the gbm windowing system
EGL_VENDOR = Mesa Project
GL_RENDERER = Mesa Intel(R) Xe Graphics (TGL GT2)
GL_VERSION = OpenGL ES 3.2 Mesa 21.2.2
libva info: VA-API version 1.12.0
vainfo: VA-API version: 1.12 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.3.3 (e2cef15841)
```

**Comment by jernejsk** [comment]
Is it just me or "kodi-remote" stopped working with current master + this PR?

**Comment by jernejsk** [comment]
Commit https://github.com/xbmc/xbmc/commit/a1bae53e6bb284aefeb2ac5af8f10cc97d5903b1 causes that PYTHON_EXECUTABLE doesn't get overriden by -D cmake option in package.mk so distro python is used instead. Can someone look into it?

**Comment by jernejsk** [comment]
@CvH Issue found and fix submitted to Kodi repo. Please include or wait on https://github.com/xbmc/xbmc/pull/20171

**Comment by CvH** [comment]
temporarily added the py fix, waiting for merging (should happen soon)

**Comment by CvH** [comment]
works for me, kodi was bumped to include the python fix from @jernejsk

**Review by jernejsk — APPROVED** [review]

**Pull request merged**
