### PR TITLE
Revert "dash: add package, configure as CONFIG_SHELL"

### PR DESCRIPTION
**Pull request by HiassofT**
This reverts commit 3b5986704e002602cf72c9e34206d2938dcc0a0b.

The config shell is set as an interpreter in libtool scripts
and as Linux has a hard limit of 127 bytes on the first line
in scripts (including the hashbang) this causes the build to
fail with a "bad interpreter" error if the path to the config
shell exceeds this limit.

These errors were first noticed on jenkins builds but can be
easily reproduced by building LibreELEC in a longer build dir.

eg RPi2 clean build failing on libtool invocation in kmod build:

./doltlibtool: /home/hias/rpi/libreelec-testing-with-a-long-directory-path-as-on-jenkins/build.LibreELEC-RPi2.arm-9.0-devel/kmod-24/.x86_64-linux-gnu/libtool: /home/hias/rpi/libreelec-testing-with-a-long-directory-path-as-on-jenkins/build.LibreELEC-RPi2.arm-9.0-devel/toolchain/bin/d: bad interpreter: No such file or directory

### CODE REVIEW

**Comment by vpeter4** [comment]
Building in very long folder doesn't work without dash either. I get
`config/optimize: line 59: /bin/uname: Argument list too long`

**Comment by HiassofT** [comment]
I noticed that as well during testing but this seems to be a different issue. The one we're hitting here is the script interpreter limit

**Comment by HiassofT** [comment]
I had a closer look at the "argument list too long" error from "uname -m" in config/optimize and it's caused by the exported _CACHE_PACKAGE_GLOBAL variable exceeding the 32 page (128k) MAX_ARG_STRLEN limit - see https://github.com/torvalds/linux/blob/master/include/uapi/linux/binfmts.h

In my test, running an RPi2 build in `/home/hias/rpi/libreelec-testing-in-a-very-long-directory-path-to-check-why-we-get-an-argument-list-too-long-error-from-config-optimize` that variable was 151597 bytes long and caused excecve() of uname -m to fail.

@MilhouseVH I think the global cache needs to be reworked, storing it in an exported variable is problematic. Maybe storing it in a temporary file and exporting the path to that fille (and importing it in scripts, when needed) could work.

**Comment by koenkooi** [comment]
This PR fixes the builderror in popt when doing `make PROJECT=Rockchip DEVICE=RK3328 ARCH=aarch64 `

**Pull request merged**
