### PR TITLE
fix auto-sense in lirc_rpi driver

### PR DESCRIPTION
**Pull request by IngoKresse**
HI, I've got a small fix for Raspberry Pi 2 remote controls (a patch for a patch, so to speak).

On a Raspberry Pi 2, the lirc_rpi driver might receive spurious
interrupts and change it's low-active / high-active setting.
When this happens, the IR remote control stops working.

This patch disables this auto-detection if the 'sense' parameter
was set in the device tree, making the driver robust to such
spurious interrupts.

### CODE REVIEW

**Comment by chewitt** [comment]
@popcornmix I think this should go into your repo so we don't patch patches?

@IngoKresse You need to set the git globals for username/email or github does not attribute commits to your github account when you make commits or submit PR's

**Comment by popcornmix** [comment]
Agreed - if the fix is good it be submitted to https://github.com/raspberrypi/linux

**Comment by IngoKresse** [comment]
Cool, thanks. I'll make a pull request there tonight.

**Comment by lrusak** [comment]
Did this get sent upstream?

**Comment by IngoKresse** [comment]
I issued a pull request here: https://github.com/raspberrypi/linux/pull/1581. To my knowledge, this is as far upstream as the lirc_rpi driver got. I am waiting for feedback from popcornmix or any other maintainer there.

**Pull request closed without merging**
