### PR TITLE
inputstream.adaptive: bump package to 20.0.1

### PR DESCRIPTION
**Pull request by Portisch**

### CODE REVIEW

**Comment by heitbaum** [comment]
Can we please change this to Matrix-19.0 release until #5546 is merged? No technical difference between 19.0 and 20.0 or 2.6.23 (apart from some translations from what I can see.)

**Comment by heitbaum** [comment]
Waiting on https://github.com/xbmc/repo-binary-addons/pull/148

**Comment by Portisch** [comment]
Yes, I did found the same reason that there is no update possible right now.

I did temporary override it by apply the downloaded PR as patch:
```bash
diff --git a/tools/mkpkg/update_binary-addons b/tools/mkpkg/update_binary-addons
index 5fd1b67dd4..7fad123462 100755
--- a/tools/mkpkg/update_binary-addons
+++ b/tools/mkpkg/update_binary-addons
@@ -77,6 +77,12 @@ for addontxt in $KODI_DIR/cmake/addons/bootstrap/repositories/*-addons.txt ; do
   ADDONS_GIT_REPO=$(cat $addontxt | awk '{print $2}')
   ADDONS_GIT_BRANCH=$(cat $addontxt | awk '{print $3}')
   git_clone $ADDONS_GIT_REPO $ADDONS_GIT_DIR ${ADDONS_GIT_BRANCH}
+  (
+    cd $ADDONS_GIT_DIR
+    git am -3 < 148.patch
+    # update to Nexus
+    # https://github.com/xbmc/repo-binary-addons/pull/148
+  )
```

**Comment by AlwinEsch** [comment]
The most addons are updated to use for Nexus, now only all vfs addons (4), ~10 audiodecoder addons and 2 PVR addons.
After this are done, becomes the repo-binary-addons his pull request in

**Comment by AlwinEsch** [comment]
All binary addons have now the Nexus branch and changes on https://github.com/xbmc/repo-binary-addons are in.

**Review by CvH — APPROVED** [review]

**Pull request merged**
