### PR TITLE
add xmlstarlet to toolchain depends

### PR DESCRIPTION
**Pull request by CvH**
`PROJECT=abc ARCH=abc scripts/create_addon abc` fails at clean builds due missing `xmlstarlet:host`

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Unfortunately this creates a circular dependency.

`toolchain` will build `xmlstarlet`, which tries to build `toolchain`:

https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/textproc/xmlstarlet/package.mk#L26

Try a clean build, it will fail after forking thousands of `scripts/build xmlstarlet` processes.

So OK, remove `toolchain` from `xmlstarlet` as a PKG_DEPENDS_HOST dependency.

But `xmlstarlet` needs `libxml2:host` (which itself needs `zlib:host`) and `libxslt:host`, which each have a dependency on `toolchain` which they themselves try to build... so again `toolchain` tries to build `xmlstarlet:host`, and so it goes on, forever until the machine runs out of resources.

You need to remove `toolchain` from the PKG_DEPENDS_HOST of `xmlstarlet` and all `xmlstarlet` dependencies (and their dependencies) in order to "break" the circular dependency, otherwise it won't be possible to build `xmlstarlet` as part of `toolchain`.

http://sprunge.us/YUjM

I think the above patch works.

**Comment by CvH** [comment]
@MilhouseVH tx, I forgot about the circular dependency, trying a clean build

**Comment by CvH** [comment]
@MilhouseVH fixed and updated pr

**Comment by MilhouseVH** [comment]
Please rebase #1821

**Comment by LongChair** [comment]
Any chance we could backport that one to 8.2. xmlstarlet wouldn't build and keep stuck on an Ubuntu 17.10 without that patch ...

**Pull request merged**
