### PR TITLE
[le12] linux: update 6.6.39

### PR DESCRIPTION
**Pull request by sky42src**
Build for all official supported platforms and run tested on RPi4, RPi5, Generic with my community release 240712

### CODE REVIEW

**Review by CvH — APPROVED** [review]

**Comment by HiassofT** [comment]
Ahem, why was this merged? 6.6.39 is known to cause a massive regression in the xhci driver which was fixed by reverting the offending commit in 6.6.40.

see https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.40 and eg https://github.com/raspberrypi/linux/issues/6270

BTW: current stable kernel is 6.6.41and it's also not goot that the RPi kernel in LE12 is now ahead of LE13 - I have RPi kernel bumps already in the queue

**Comment by sky42src** [comment]
Sorry. For me it is fine since a week on Generic and RPi4 every day. I know 6.6.41 is the latest, but that would not be tested for a couple days by me.

Should i rollback this PR? If so what is the correct procedure for that. Never done that before. Make a new PR with those 2 commits rolled back i guess.

**Comment by HiassofT** [comment]
Yes, please PR a revert of those 2 commits so nighty builds are fixed soon.

We can then update kernels, I had planned to do that end of this week for RPi (LE13 and LE12)

**Comment by sky42src** [comment]
I hope it is correct like that https://github.com/LibreELEC/LibreELEC.tv/pull/9117

**Comment by HiassofT** [comment]
Thanks! Change looks good

**Pull request merged**
