### PR TITLE
imx6: update kodi, libcec and linux 3.14 patches

### PR DESCRIPTION
**Pull request by vpeter4**
Patches got from usual sources.

### CODE REVIEW

**Comment by vpeter4** [comment]
Jenkins was happy, ready to merge.

**Comment by vitalogy** [comment]
@vpeter4 
getting this by running: `$ PROJECT=imx6 ARCH=arm LINUX_VERSION="sr-3.14" scripts/build linux`

```
...
APPLY PATCH (project - 3.14-mx6-sr)   /home/michael/workspace/LibreELEC.tv/projects/imx6/patches/linux/3.14-mx6-sr/linux-compiler-gcc.h.patch
patching file include/linux/compiler-gcc.h
Hunk #1 FAILED at 122.
1 out of 1 hunk FAILED -- saving rejects to file include/linux/compiler-gcc.h.rej
```
compiler-gcc.h.rej: http://pastebin.com/XgX5UC9W
any idea?

**Comment by vpeter4** [comment]
You still have patch file projects/imx6/patches/linux/3.14-mx6-sr/linux-compiler-gcc.h.patch which was removed. You can see this here: https://github.com/LibreELEC/LibreELEC.tv/pull/1021/commits/27c38bd87c87102dc727935eac71e1bf3f4bebaf#diff-e44f20e50705389689e89f4fda9f3fd5

**Comment by vitalogy** [comment]
uhm ... i should also apply new commits to my branch ... thx

**Pull request merged**
