### PR TITLE
merge Virtual project into Generic

### PR DESCRIPTION
**Pull request by lrusak**
There is no point in maintaining two projects when there is minimal difference.

It is also confusing that using qemu you should use the Generic project and vmware use the Virtual project.

My only reservation here is when xf86-video-vmware breaks because of a kernel bump. This shouldn't be much of an issue though in my opinion.

This will also allow us to add extra support for running LibreELEC in a VM.

I haven't build tested this yet so hopefully I haven't missed anything.

It would be nice to get a size comparison also, as this shouldn't really add much size at all.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I built this (Generic with/without DEBUG) and haven't seen any issue. I'll include this in tonight's test build, if anyone wants to then download and test in a VM.

**Comment by lrusak** [comment]
thanks @MilhouseVH 

FYI, for anyone wanting to test. You will have to do `touch /storage/.update/.nocompat` in order to change projects when updating.

@MilhouseVH weren't we going to implement some way around that?

**Comment by piotrasd** [comment]
could we add QXL drivers ?

**Comment by MilhouseVH** [comment]
> @MilhouseVH weren't we going to implement some way around that?

There is a way around that: https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/busybox/scripts/init#L381-L383

Create the `canupdate.sh` script in `projects/Generic/files/usr/share/bootloader`

It will be passed the old (ie. installed) project/arch (eg. `Virtual.x86_64`) and the new project/arch (ie. `Generic.x86_64`). The following one-liner should allow `Virtual.x86_64` to cross-grade to `Generic.x86_64`:
```
[ "$2" = "Virtual.x86_64" ] && exit 0 || exit 1
```

**Comment by lrusak** [comment]
This is good to go :+1:

**Pull request merged**
