### PR TITLE
libcec: update to libcec-next

### PR DESCRIPTION
**Pull request by MilhouseVH**
Replacement for #4282. Will track the development branch until there is a new release.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
[PR380](https://github.com/Pulse-Eight/libcec/pull/380) has now merged upstream. but presumably we still only want to enable `HAVE_LINUX_API` for Allwinner/Amlogic/Rockchip (at this time)? With #4288 we'll be adding RPi to that list - what's the reason for continuing to disable it on Generic? @Kwiboo @HiassofT

**Comment by lrusak** [comment]
> [PR380](https://github.com/Pulse-Eight/libcec/pull/380) has now merged upstream. but presumably we still only want to enable `HAVE_LINUX_API` for Allwinner/Amlogic/Rockchip (at this time)? With #4288 we'll be adding RPi to that list - what's the reason for continuing to disable it on Generic? @Kwiboo @HiassofT

@MilhouseVH we don't enable the CEC media API on the Generic kernel. If you want to use the HAVE_LINUX_API then you'll need to enable the corresponding kernel config items.

**Comment by MilhouseVH** [comment]
>  If you want to use the HAVE_LINUX_API then you'll need to enable the corresponding kernel config items.

Is that something worth investigating? Any expected benefits (other than consistency)? I don't really have any CEC capable hardware so can't test anything myself. CEC is pretty much voodoo to me...!

**Comment by bdutro** [comment]
FWIW, it seems like CEC support is enabled by default in the Generic kernel. I plugged in a USB-C -> HDMI adapter with CEC passthrough and it creates a /dev/cec0 device. I made a side build of libcec and ran it on my Libreelec box and got this output:

```
libCEC version: 4.0.4,  compiled on 2020-04-17 22:50:35 by root@3711c0b86ecf on Linux 5.6.4-arch1-1 (x86_64), features: P8_USB, DRM, P8_detect, randr, Linux
Found devices: 1

device:              1
com port:            Linux
vendor id:           0000
product id:          0000
firmware version:    0
type:                Linux
```

**Comment by bdutro** [comment]
I did a custom Generic build of LIbreelec with CEC_FRAMEWORK_SUPPORT="yes" and I can confirm that CEC is working well.

**Comment by MilhouseVH** [comment]
No further updates for this PR.

**Pull request merged**
