### PR TITLE
Fix building with Perl 5.26 v2

### PR DESCRIPTION
**Pull request by jernejsk**
This PR makes possible to build LE with Perl 5.26 installed on host. Since that version, perl is more strict about "{" character in regex expressions - it has to be escaped with "\".

This is same as #2088 with @MilhouseVH solution.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
@jernejsk can you rebase please - just some minor changes to packages after #2117

**Comment by MilhouseVH** [comment]
For some reason that merge commit isn't visible when downloading this PR as a patch - there are only 3 commits/patches:

https://github.com/LibreELEC/LibreELEC.tv/pull/2111.patch

**Comment by jernejsk** [comment]
I resolved conflicts using web GUI, so I guess changed are squashed into offending commit.

**Comment by MilhouseVH** [comment]
We really should ban the Github GUI...

**Comment by MilhouseVH** [comment]
@jernejsk I'm afraid the Github GUI has screwed things up again. If you click on your new merge commit, there's a yellow box at the bottom with a link, click the link and it will show that Github thinks the merge commit includes several hundred other changes.

Please drop the merge commit and apply the change as a single extra commit. Ideally use the command line `git`, which is really quite easy once you've mastered the basics. Or close this PR as I don't think it's safe to merge in it's current state with this merge commit.

Using the Github GUI is a really, really bad idea for anything more than a single commit change.

**Comment by CvH** [comment]
I guess i repaired it -.-

**Comment by MilhouseVH** [comment]
Thanks @jernejsk and @CvH.

**Comment by LongChair** [comment]
Can we backport that to 8.2 as well ? I can't build 8.2.0.1 on Ubuntu 17.10 for the same reason :)

**Pull request merged**
