### PR TITLE
linux: update to 5.8.7

### PR DESCRIPTION
**Pull request by jernejsk**
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.1
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.2
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.3
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.4
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.5
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.6
https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.7

### CODE REVIEW

**Review by CvH — COMMENTED** [review]
just as info, Intel Haswell CPUs are going to have a bad time with 5.7.x
https://gitlab.freedesktop.org/drm/intel/-/issues/2024

5.8.7 made it even worse compared to 5.7.0
popular HTPC CPUs Intel G3xxx are affected too, black screen and driver crash at every start of LE :(

**Review by CvH — APPROVED** [review]

**Comment by jernejsk** [comment]
We were already at 5.8.0 before this PR...

**Comment by CvH** [comment]
sorry mixed it up :D
it is already a problem at 5.7.x, it got worse with 5.8.0 and got even more problematic with 5.8.7 :)

**Comment by jernejsk** [comment]
well, 5.8.7 is not at fault, it has no DRM related changes. It must have been some version before that.

**Comment by Freedater** [comment]
This has been a problem for Haswell for a long time now and also extends to Cherry Trail Z8350 SOC's too.

I think that things started to go wrong with things like Libreelec when the kernel went from 3.14 to 5.XX

The very last build of the Millhouse releases that I always used and worked without giving a black screen is LibreELEC-Generic.x86_64-9.1-Milhouse-20190311210303-#0311-g28f2bb3

Every single release since then has the same issue.

**Comment by CvH** [comment]
@Freedater its a problem of the intel driver, not really anything we can do at the moment
https://gitlab.freedesktop.org/drm/intel/-/issues/2024

looks like not even fixed at 5.9
the Bay Trail disaster returns :(

**Comment by Freedater** [comment]
> @Freedater its a problem of the intel driver, not really anything we can do at the moment
> https://gitlab.freedesktop.org/drm/intel/-/issues/2024
> 
> looks like not even fixed at 5.9
> the Bay Trail disaster returns :(

Thanks for the clarification.

At least I know the position and can wait and see.

**Pull request merged**
