### PR TITLE
Add support for OrangePI Lite2 (H6 Based) board

### PR DESCRIPTION
**Pull request by prabuselva**
- Added DTS patches from armbian and megous linux
  - Patches are from https://github.com/armbian/build/commit/634ec8f5dac0f22733dfb781d2e744ee5d89117a
  - Only patch/kernel/sunxi-dev/board-h6-orangepi-lite2-fix-missing-all.patch &  patch/kernel/sunxi-dev/0012-general-h6-new-opp-table.patch files were used to patch LE kernel 
- Device is running at quite stable with major peripherals WIFI and Bluetooth working..
- Fixed H6 CPU freq to max at 1.32Ghz (similar to max freq of H3 devices) as running in at 1.8Ghz causes heat issues.

### CODE REVIEW

**Comment by lrusak** [comment]
@prabuselva thanks for submitting your first PR.

Please can you drop the LibreELEC-settings changes. They are not needed in this PR.

Please can you provide links or commits when adding patches. If we do not know where the patches came from we cannot maintain them.

I would also drop the changes to the linux config file as they aren't relevant to running the orangepi-lite2.

Also try and follow out commit message format of `Topic: brief commit message`

**Comment by prabuselva** [comment]
Thanks for the review.. Sure.. I will make the suggested changes and updated the PR

**Comment by prabuselva** [comment]
@lrusak Please check and let me know if the PR is fine.

**Comment by chewitt** [comment]
@prabuselva please squash the revert commits into the "add initial support" commit, and modify the commit messages to follow house-style where we identify the object being changed so that it's clearer to someone reviewing a large number of commits. Something like `allwinner: add initial support for H6 orangepi-lite2 board` and `allwinner: cpu max-frequency fix for H6 devices` would be fine.

**Comment by prabuselva** [comment]
@chewitt I hope that I did the rebase as per you suggestion..Let me know if something is still missed...

**Comment by jernejsk** [comment]
@prabuselva you didn't properly rebased your commits. You still have "revert" commits and some of them include unneeded files (*.orig).

Additionally, I would drop anything CPU frequency related. This is a bit complicated topic for H6. It may work for you, but there are 3 different speed grades in the wild, so you would have to first find which one is it and then select correct cpu freq table for it. Let upstream sort it out first. As I said before - becauese HW decoding is used, there is no need for higher than default frequencies.

**Comment by jernejsk** [comment]
Oh, one other thing - any custom patches, like your DT patch, should be mainlined. Only this way maintenance burden is manageable. From what I see, you take shortcut in DT by removing one include and instead copied many nodes. This won't fly upstream. Please leave that common include and instead make changes where appropriate.

I can help you with mainlining that DT patch, if you wish.

**Comment by prabuselva** [comment]
@jernejsk 

> @prabuselva you didn't properly rebased your commits. You still have "revert" commits and some of them include unneeded files (*.orig).

The 16-orangepi-lite2.patch file which I committed doesn't include any patch for *.orig files ...I am not for where did *.orig comes..
 If I checkout my fork fresh, I don't see those revert commit but github have those.. I will have to read about how github still has those commits..

> 
> Additionally, I would drop anything CPU frequency related. This is a bit complicated topic for H6. It may work for you, but there are 3 different speed grades in the wild, so you would have to first find which one is it and then select correct cpu freq table for it. Let upstream sort it out first. As I said before - becauese HW decoding is used, there is no need for higher than default frequencies.

I will try to avoid the cpufreq and recheck the stability of the device

> Oh, one other thing - any custom patches, like your DT patch, should be mainlined. Only this way maintenance burden is manageable. From what I see, you take shortcut in DT by removing one include and instead copied many nodes. This won't fly upstream. Please leave that common include and instead make changes where appropriate.
> 
> I can help you with mainlining that DT patch, if you wish.

Yeah...I accept that DT copied many nodes by skipping the include and fully understand mainlining may not be possible. Since I followed armbian patches and also I felt updating the dt within include may affect all other H6 devices too...Thats the reason I removed the include and got the device to quickly up and running for test.. If you can help with DT patch...sure, let me do some proper patching and get back to you for help for upstream work

**Comment by chewitt** [comment]
One mistake is that you're working in your local master branch instead of a topic branch. Things have moved on in the conversation, but assuming your git repo is defined as `origin` and the LE repo is `upstream` something like this would be a way to sort things out:

```
git checkout master
git fetch upstream master
git reset --hard upstream/master
git push -f origin master
git checkout -b orangepi-lite2
git cherry-pick c4f07e3f3c789a953421484770ec200187fa6ad6
git cherry-pick eb9afadd8dbac0b397b94609f7f42c25555fa553
git cherry-pick c9c2640cae1dab38c09ac50de42898105e039350
git cherry-pick b5316b158c91db8f1be3521730e477f8e61ac094
git cherry-pick 0d8ad417207cd11fd0b82611d6d9c7cba8df214b
git cherry-pick f32321d1c542be33ff5e50ffa2b6ca07a82105ae
git rebase -i HEAD~6
<use copy/paste to reorder commits and change 'pick' to 'fixup' to combine reverts into the commit above (the list shows first commit at top, most recent at bottom)>
git push -f origin orangepi-lite2
```
Then edit the PR (top-right on screen) and change it to use the new `orangepi-lite2` branch instead of the master branch. 

As a rule, never work in master. If you work in a topic branch (branched from master) then it becomes simple to update/reset your local master branch to be in-sync with our upstream master branch, and then you can rebase your changes against master - which means you retain the changes, but you avoid merging (which adds merge commits to the branch).

**Comment by prabuselva** [comment]
@chewitt I followed your instructions.. Everything went good... Now I have orangepi-lite2 branch with appropriate commits.. 
But this PR seems to closed automatically and I can't open it as I am unable to change the branch by clicking Edit

Does it mean I have to create new pull request?

**Comment by chewitt** [comment]
I've no idea why this PR cannot be reopened to change the branch - that's normally (historically) possible. From a git perspective the commits in the new branch look good now, so best to send a new PR so @jernejsk can review the content.

**Comment by prabuselva** [comment]
@jernejsk So, I will make more cleaner patch as per your suggestion and test it out with the device and then create a new PR for your review

**Comment by clementperon** [comment]
@prabuselva you're trying to merge your master to the LE master which has no difference.

You should select your orangepi-lite2 branch instead

**Comment by prabuselva** [comment]
@clementperon It looks like.. Based on this, It seems we can only change to base branch and cannot change the "from" branch after 
PR has been created..
https://stackoverflow.com/a/24159161

Anyway I will close the PR and request a new one later..

**Pull request closed without merging**
