### PR TITLE
kodi: bump inputstream.adaptive

### PR DESCRIPTION
**Pull request by chewitt**

### CODE REVIEW

**Comment by stbenz** [comment]
I hope it's ok that I reply here directly. If not please direct me to where I should report this.

This bump to 2.0.15 seems to break loading of decrypter libraries in inputstream.adaptive, as it includes [this commit](https://github.com/peak3d/inputstream.adaptive/commit/3be3da56a092cf21af6046fddf80f4cd334ec2f9), which changed the loading path to "special://xbmcbinaddons/inputstream.adaptive/". This path is translated to something like /usr/lib/kodi/.../inputstream.adaptive (don't have the logfile right now, but can provide it later if neccessary), wich doesn't exist in LibreELEC 8.x as inputstream.adaptive isn't built in. 

Therefore it seems that all addons that require decryption with inputstream.adaptive (e.g. Sky Go, Sky Ticket) no longer work with this version.

**Comment by chewitt** [comment]
we're aware - this is required in the Krypton branch: https://github.com/peak3d/inputstream.adaptive/commit/01e390ddbe4552fd4c5fe22332213bae0a4aab76

**Comment by Linkinsoldier** [comment]
How are we to fix this in the Krypton bases builds? Should be create a symlink?

**Comment by MilhouseVH** [comment]
> May I ask how this can be fixed in the Krypton bases builds? Should we create a symlink?

I don't think you can do anything - the current Krypton addon only checks the path in the r/o file system but - due to the `return` instead of `continue` - doesn't check the /storage/.kodi/addons path. There's not really anything you can do, but wait for an updated addon.

**Comment by Linkinsoldier** [comment]
Thanks for the answer. Updated addon like skygo, Amazon or inputstream.adaptive?

**Comment by MilhouseVH** [comment]
inputstream.adaptive.

**Comment by Linkinsoldier** [comment]
Thanks milhouse! As far as I know @Maven already informed @peak3d, so I am sure he is doing his best! I will wait and offer to test in the meantime!

**Pull request merged**
